### ISSUE TITLE
Issues with blend modes (2.2 Alpha)

### ISSUE THREAD

**Issue by Deanphillips** [soflyy/oxygen-bugs-and-features#10]
Hey guys,

I'm having two issues when it comes to blend modes (under opacity) I'm having 2 issues:

1. It doesn't render an image when a blend mode is applied on mobile (chrome, android - latest version)

https://photos.app.goo.gl/hT3NKYt7r1VuurSx9

2. The blend mode stops when an animation is added:

https://www.useloom.com/share/7c88e052fad24f8eb3ebdbae7ab78010

**Comment by Deanphillips** [comment]
How can I do that? Blend modes + animations are in 2.2 alpha? (not possible
in sandbox)

**Comment by Spellhammer** [comment]
> How can I do that? Blend modes + animations are in 2.2 alpha? (not possible
in sandbox)

You can uninstall the pre-installed version of Oxygen on the Sandbox and install the Alpha instead. Here's one I set up for you: http://spotless-horse.w6.wpsandbox.pro?upass=2abYh0Z7LY1a

**Comment by Deanphillips** [comment]
Phew, managed to recreate both errors straight away :)

http://spotless-horse.w6.wpsandbox.pro/the-tour/

<img width="1435" alt="screenshot 2019-01-15 at 21 54 30" src="https://user-images.githubusercontent.com/21025321/51212336-286e5000-1910-11e9-90a9-b6a5cc891535.png">

![screenshot_20190115-215304](https://user-images.githubusercontent.com/21025321/51212350-358b3f00-1910-11e9-9c0c-7ce162e867ba.png)

**Comment by Deanphillips** [comment]
You're right, that's so strange, on other browsers on my mobile it works
fine and I've asked several people to test it and it works fine too.

Seems to just be an issue on my instance of chrome (android) even in
incognito mode. Which is okay, as long as others can see it :)

As for the animation issue, that's existing for everyone and here's how to
recreate it: https://www.useloom.com/share/a0dd389035f54eeda2772216c0cdf85f

It happens when applying an animation to a column element (and not a single
element)

**Comment by Spellhammer** [comment]
Thanks for the details. I've been able to reproduce the animation / mix-blend-mode issue.

**Comment by Spellhammer** [comment]
@Deanphillips I had to spend some time to verify that this was an Oxygen specific issue first, and I should be able to shed some light on this behavior:

Mix-blend-mode sets how an element's content should blend with the content of the element's parent and the element's background (https://developer.mozilla.org/en-US/docs/Web/CSS/mix-blend-mode). This means that setting the mix-blend-mode on the image should blend the image with the **column div**, but not the great-grand-parent div (with the gradient background). The fact that it is when the column div is not animated is an anomaly and shouldn't work. The behavior you see when an animation is applied reflects the way mix-blend-mode should work, in that it's blending with its direct parent and not grand-parent or more distant elements. We can see that this is the primary issue by adding the gradient to the column div instead, which I've done on the test site at: http://spotless-horse.w6.wpsandbox.pro/the-tour/

So the issue isn't that animations break mix-blend-mode, it's that applying an animation makes mix-blend-mode work like it's supposed to (weird, right?)

That being the case, you can either animate only the image, which retains the mix-blend-mode, or add a background to the column div.
