### ISSUE TITLE
Global Input Checkbox Error (Oxygen WooCommerce Plugin)

### ISSUE THREAD

**Issue by JeremyGruver** [soflyy/oxygen-bugs-and-features#1000]
The plugin adds a checkbox to all radio buttons that use a checkbox setup, site-wide.

**Comment by JeremyGruver** [comment]
![image](https://user-images.githubusercontent.com/6181902/78947129-8eee0980-7a92-11ea-8e1a-216e1d3a490f.png)

In my WP Forms Conversational Forms Plugin, for example, radio button has an SVG that's applied (which shouldn't be there) on top of the Letter that's selected

input[type="checkbox"]:checked ~ span::before {

**Comment by KittenCodes** [comment]
@JeremyGruver Please replicate this on a Sandbox site so that we can take a look. You can create a Sandbox site here: https://oxygenbuilder.com/try/.

**Comment by JeremyGruver** [comment]
> @JeremyGruver Please replicate this on a Sandbox site so that we can take a look. You can create a Sandbox site here: https://oxygenbuilder.com/try/.

![image](https://user-images.githubusercontent.com/6181902/78994212-7ff86d00-7b0d-11ea-8acf-6ec991e6dee4.png)

I started a sandbox, however on my site version it's showing, going to try and replicate what I did on sandbox.

**Comment by KittenCodes** [comment]
@JeremyGruver Please open a support ticket so that we can take a look at your site: https://oxygenbuilder.com/support.
