### ISSUE TITLE
Random Sort Order in Easy Posts and Repeater

### ISSUE THREAD

**Issue by waptug** [soflyy/oxygen-bugs-and-features#1003]
**Describe the feature you'd like to see included in Oxygen.**
*A clear, detailed description of the feature you're requesting.*

I would like to have a sort order option in the Easy Post to randomly sort the posts on each page view. So the ordering was different every time the page was viewed.

**What are the use cases for this feature?**
*e.g. Accessibility, e-commerce store that sells bicycles, etc.*

Use case would be for randomly featuring posts from the archive so order of posts would be randomly ordered. Would be good for surfacing posts from our large business directory of 19,000 locations for instance. 

**Examples of this feature or functionality.**
*If another product has done it well, provide examples here.*

Content Views has a random sort order available but using it is slower then using easy Posts. https://wordpress.org/plugins/content-views-query-and-display-post-page/

**Comment by LuntenLarry** [comment]
That Feature would be really great.

**Comment by Spellhammer** [comment]
You can do this with the Advanced query.

**Comment by netrunner7** [comment]
+1

**Comment by geraldmorales** [comment]
+1
