### ISSUE TITLE
Structure widget is empty

### ISSUE THREAD

**Issue by Adrenalne22** [soflyy/oxygen-bugs-and-features#1013]
No matter what elements I place in the template, the structure widget doesn't show any elements.

Has anyone encountered this problem before?

Fresh install, no plugins (except Woocommerce).

**Comment by Adrenalne22** [comment]
Not only that, even saving doesn't work. PHP Version is 7.3

**Comment by KittenCodes** [comment]
@Adrenalne22 Please open a support ticket so that we can take a look at this for you: https://oxygenbuilder.com/support.
