### ISSUE TITLE
Rest api stops Oxygen's editor (v3.2.1) from loading

### ISSUE THREAD

**Issue by norskalf** [soflyy/oxygen-bugs-and-features#1015]
When I register a rest route Oxygen's Editor will not load.
When I disable this code Oxygen's editor loads again.
Big issue. Because I use rest routes a lot.

**Comment by Spellhammer** [comment]
Please post the code you're using to register the route, and the method you're using to implement the code (e.g. custom plugin, Code Snippets). We need to be able to test this to fix it, and it's very possible that we could register our own REST route and not have the same result.

**Comment by norskalf** [comment]
function artiesten_rest(){

    register_rest_route('kaart/v1', 'voorstellingen', array(
        'methods'   => WP_REST_SERVER::READABLE,
        'callback' => 'resultatenArtiesten',
    ));
}

add_action('rest_api_init', 'artiesten_rest');

function resultatenArtiesten(){
    
    $kaartItems = new WP_Query(array(
        'post_type' => 'voorstelling',
        'posts_per_page' => -1
    ));
    $kaartItemsResultaten = array();

    while($kaartItems->have_posts()){
        $kaartItems->the_post();
        
        array_push($kaartItemsResultaten, array(
            'userId'              => get_the_author_meta( 'ID' ),
            'naam_groep'          => get_field('naam'),
            'naam_voorstelling'   => get_field('naam_voorstelling'),    
            'omschrijving'        => get_field('omschrijving'),
            'prijs'               => get_field('prijs'),
            'website'             => get_field('website'),
            'foto'                => get_field('foto'),
        ));
    }
    return $kaartItemsResultaten;
}

**Comment by norskalf** [comment]
I found out. Where Wordpress is not making a problem of a blank first line. Oxygen does. I overlooked that.
