### ISSUE TITLE
Not Support RTL Language and Translate persian Language

### ISSUE THREAD

**Issue by profetionali20** [soflyy/oxygen-bugs-and-features#1016]
**Describe the bug**
*I want to buy the plugin, but unfortunately it has the following problems!
The plugin does not support Persian for translation!
The plugin does not support right-to-left languages!*

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
*Yes*

**Comment by KittenCodes** [comment]
#30
