### ISSUE TITLE
404 Error On wp-admin/post.php When Updating

### ISSUE THREAD

**Issue by amsgator** [soflyy/oxygen-bugs-and-features#1020]
**Describe the bug**

When I update [one particular page](https://www.triggerpressers.com/training/concealed-carry-class/), not saving within the Oxygen builder, but saving the actual WordPress page, with Oxygen as the only activated plugin I get a 404 error. If I deactivate Oxygen it saves perfectly fine for a little while. It also updates fine if all my plugins _except_ Oxygen are activated.

If I copy and paste the Oxygen shortcodes into a new page it saves fine too. After a while, it starts returning 404 again. So I’m not sure if it’s got to do with the revisions themselves or what. From what I can tell there’s no way to delete the revisions for me to check?

The problem is I cannot keep rebuilding the rest of the fields on the page (i.e. SEO settings, etc) over and over and over again.

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
Yes. Nothing changes and the error log is empty.

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
No, it is confined to one particular page as previously stated.

**Expected behavior**
I expect the page to update...

**What actually happens**
404 error on wp-admin/post.php

**Desktop (please complete the following information):**
- OS: Windows 10 Home
 - Browser: Brave and Chrome
 - Oxygen Version 3.2.1

**Comment by amsgator** [comment]
Prior to the update/save going 404, the last few updates/saves were very very slow. Something on the order of 30-60 seconds. When I copy the Oxygen shortcodes to a new page and move everything over the page updates/saves extremely fast. This is what makes me think it might be the large number of Oxygen revisions that are being saved. There really needs to be a way to delete or limit the number of Oxygen revisions.

**Comment by amsgator** [comment]
Alright, I just confirmed there is a bug. I had 22 post revisions saved for the page in questions and according to the [Revisions Systems](https://oxygenbuilder.com/documentation/other/revisions-system/) page, it should have only saved 20. 

I manually went into the database and deleted the ct_builder_shortcodes_revisions for the page experiencing the problem and upon doing so the page saved/updated without issue.

**Comment by Spellhammer** [comment]
> Alright, I just confirmed there is a bug. I had 22 post revisions saved for the page in questions and according to the Revisions Systems page, it should have only saved 20.

This isn't entirely accurate. It is possible to have more than 20 revisions, just not more than 20 for a single day.

The fact that the revisions are slowing down saving/causing a 404 is very interesting. Would you be willing to share your server specs & the shortcodes from the page?

**Comment by amsgator** [comment]
> The fact that the revisions are slowing down saving/causing a 404 is very interesting. Would you be willing to share your server specs & the shortcodes from the page?

What I noticed is that towards the "end" of successful WP saves (as opposed to Oxygen saves) I occasionally experienced ERR_CONNECTION_REFUSED errors in Brave/Chrome. 

My hosting is shared hosting and not the greatest on specs. I don't have the specifics, but what I was thinking is maybe the WP save process just became so slow with all of the Oxygen revisions that it threw an error? And then maybe eventually the server just returned 404 due to the delay?

I tried increasing max_execution_time and max_input_time but that didn't help either. I was just toying around with troubleshooting, I'm not sure if those would have any effect or not.

But I can confirm with 100% certainty, the minute I manually deleted the ct_builder_shortcodes_revisions the page saved quickly and without issue again.

**Comment by Spellhammer** [comment]
@amsgator Having the page shortcodes could help us troubleshoot, especially if it's a very long & complex page.

**Comment by amsgator** [comment]
> @amsgator Having the page shortcodes could help us troubleshoot, especially if it's a very long & complex page.

@Spellhammer there's definitely nothing complex going on on the page. It's probably one of the most basic Oxygen pages out there right now. 

Here are the shortcodes attached as a text file.

[shortcodes.txt](https://github.com/soflyy/oxygen-bugs-and-features/files/4476308/shortcodes.txt)

**Comment by amsgator** [comment]
@Spellhammer Alright, so I figured out what the problem is but I don't know why.

My firewall (WebARX) was blocking post.php for XSS, CSRF, ID, RFE. What I don't understand is why it was only being blocked when the number of revisions exceeded a certain amount.

**Comment by KittenCodes** [comment]
@amsgator Would your firewall block post.php if the data exceeds a certain size?

**Comment by amsgator** [comment]
> @amsgator Would your firewall block post.php if the data exceeds a certain size?

I have no idea. I tried to whitelist URL:/wp-admin/post.php?post=5876&action=edit

But that didn't do any good either.
