### ISSUE TITLE
DONE: Enable undo for any action

### ISSUE THREAD

**Issue by swinggraphics** [soflyy/oxygen-bugs-and-features#1021]
**Describe the feature you'd like to see included in Oxygen.**
It needs to be possible to undo any action.

**What are the use cases for this feature?**
Everyone, all the time; Oxygen is unusable without it. Just a few examples of the hundreds I run into every day building sites:

- Drag an element to a new place. Don't like it. Undo. Nope, can't. Okay, drag it back. Annoying.

- Change the padding on an element. Don't like it. Want to change it back to what it was. Hmm, I don't know what it was set to. Can't undo, so I guess I'll have to refresh the page. Hope I saved immediately before making that one tiny change, or else everything will be lost!

- Clicked somewhere accidentally. Not sure what changed, but it messed something up. Again,  hope I saved _immediately_ before that mistake!

Need I go on?

**Examples of this feature or functionality.**
Literally every other builder and WP itself has this, and they do it better than what I'm asking for.

Undo simply does not exist in Oxygen. Period. Sure, if you delete an element, it briefly gives you the option to undo it by clicking the little message. But if you click anywhere else, that option goes away. And no other actions are undoable. I am utterly flabbergasted that undo is not present. Multiple level undo is a valid feature request for version 2 of a product (ahem, 3.3 and still no? seriously?), but undoing the very last action is a version 1.0-beta feature that should not need to be requested.

Elementor, Beaver, Gutenberg, TinyMCE, etc, all have undo, all have multiple undo and redo, and all have it accessible via the keyboard.

I'm not asking for multiple undo here; I've already upvoted that request elsewhere. And this is not "Make undo available via the keyboard" because wording it that way suggests that undo is available another way. It isn't. The ability to undo any action does not exist in Oxygen, and it absolutely needs to.

**Comment by amsgator** [comment]
You should go to [this feature request](https://github.com/soflyy/oxygen-bugs-and-features/issues/12) and give it a thumbs up rather than posting a duplicate request.

**Comment by chapolote** [comment]
Just for your interest and if you are able to spend some money for it: search for oxy undo from oxy plugins ;)

But I agree: it would be very nice to have this implemented directly in oxygen builder!!!!

**Comment by Luke-Keil** [comment]
This would be a great feature, just a simple Ctl+z would be great as there have been many times Ive accidentally dragged something out of a column and no matter how hard I try, cannot get it back into a column so end up rebuilding the column.

**Comment by brendanquine** [comment]
Just bumping this to note that it can be marked closed as of Oxygen 3.4
@KittenCodes

**Comment by KittenCodes** [comment]
Implemented in v3.4.
