### ISSUE TITLE
Random Oxygen blocks (Gutenberg) are showing on homepage (3.3 Beta 1 + 1.3 Beta 1)

### ISSUE THREAD

**Issue by Rados51** [soflyy/oxygen-bugs-and-features#1023]
**Describe the bug**
*Random Gutenberg Oxygen blocks are showing on the homepage. Those blocks are not anyhow assigned to homepage or main template*

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
*Yes*

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
*I've recreated it inside Sandbox as well - https://oxygen-qpb9ltp7mb28k.oxygen-demo.qsandbox.me/*

**To Reproduce**
1. Install Oxygen 3.3 Beta 1 and Oxygen Gutenberg 1.3 Beta 1
2. Create the main template with catch-all.
2. Create a random header + inner content.
3. Create a homepage with assigned main as template.
4. Create random Oxgen Gutenberg block template.
5. Create random another page with none assigned template and insert created Oxygen Gutenberg block.
6. Look at the homepage.

**Expected behavior**
*Not showing on Homepage.*

**What actually happens**
*There is a random block from another page*

**Screenshots**
*https://oxygen-qpb9ltp7mb28k.oxygen-demo.qsandbox.me/*

**Desktop (please complete the following information):**
- OS: macOS
 - Browser Chrome
 - Oxygen Version 3.3 Beta 1 

**Additional context**
*I've just tried to reproduce other Gutenberg bug while creating new Oxygen template with Other > Inner Content. After that, the problem is gone and the homepage is back to normal. But again, when you insert the inner content element inside the template that has other > inner content problem is back. I will leave this template in the trash so you can restore it and try it out.*

**Comment by Spellhammer** [comment]
This is most likely because you had a single page set as both the home page and the posts page:

![image](https://user-images.githubusercontent.com/8459002/79232518-9bc58100-7e35-11ea-9141-c11546f5f124.png)

WordPress discourages this as it can result in unexpected behavior. I've changed the posts page to a different page and un-associated Gutenberg blocks (e.g. the other page's content) are no longer showing on the home page.

**Comment by Rados51** [comment]
@Spellhammer Good to know! Thanks :)
