### ISSUE TITLE
DO NOT SAVE PAGE

### ISSUE THREAD

**Issue by nz352** [soflyy/oxygen-bugs-and-features#1026]
**Describe the bug**
when trying to add a footer from "Atomic Design Set" to an existing template (with header and "inner content" elements) I get following red message 

There was an error. DO NOT SAVE THE PAGE. Please copy below error message and send to our support team.

TypeError: l.findComponentItem(...) is undefined

**Comment by KittenCodes** [comment]
@nz352 Please open a support ticket so that we can take a look at this for you: https://oxygenbuilder.com/support.
