### ISSUE TITLE
Ajax issues for reusable parts

### ISSUE THREAD

**Issue by benfavre** [soflyy/oxygen-bugs-and-features#1028]
![image](https://user-images.githubusercontent.com/664679/79490568-595e9880-801d-11ea-8373-b1be7178b3e4.png)

ajax_render_callback method in plugins/oxygen/component-framework/api/oxygen.element.class.php
Undefined variable

**Comment by KittenCodes** [comment]
@benfavre Please open a support ticket so that we can take a look at your site: https://oxygenbuilder.com/support.
