### ISSUE TITLE
DONE: Relative heading and text size

### ISSUE THREAD

**Issue by estraatios** [soflyy/oxygen-bugs-and-features#1029]
Hi.

I would like to have a relative font size. The em is not working for the heading and the text.

Also, a global setting font size for breakpoints would be awesome.

Thank you

**Comment by jamescrabb** [comment]
Thumbs up for the Global Font Size Settings to have Breakpoint options

**Comment by jrdemontfort** [comment]
Would it be possible to add vw, vh, calc etc to Heading tag font sizes?

**Comment by KittenCodes** [comment]
You can now use px, %, em, rem and "none", which allows you to use things like clamp().
