### ISSUE TITLE
Oxygen builder | template error blank screen

### ISSUE THREAD

**Issue by alissonpaganini** [soflyy/oxygen-bugs-and-features#1030]
**To Reproduce**
See this video : https://youtu.be/S1ilTRSKdp0

**Expected behavior**
*What happened was that I was simply building the site and went to edit a tampon and it went blank with this red balloon. I've tried to do several things like: migrate from server update the plugin, disable all plugins. I don't know what's causing this.*

**Comment by KittenCodes** [comment]
@alissonpaganini 

Please open a support ticket so that we can take a look at this for you: https://oxygenbuilder.com/support.

**Comment by TurboMedia** [comment]
@KittenCodes - I really wish you guys would put the solution up here. It's a pain to have to go through support for everything. I have a template that works in-editor but doesn't display on the front-end.

**Comment by TurboMedia** [comment]
I found that if I drag my sections around in the structure pane, it'll repopulate on the page. Weird bug, and it's been happening for a few releases.

**Comment by Josnoddy** [comment]
Been getting this for years. Expired product. Avoid.
