### ISSUE TITLE
Backround attachment fixed (parallax) on phone

### ISSUE THREAD

**Issue by CYBORG974** [soflyy/oxygen-bugs-and-features#1032]
**Describe the bug**
Hello,

When I fixe the background (div, section etc) for the parallax effect, It works great on desktop, but appear oversized (really really big!) and scroll on smartphone (Iphone x).

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
No

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**

Yes:
[https://oxygen-q5np3kzwhs38k.oxygen-demo.qsandbox.me/bug-test/](url)

**To Reproduce**
1. Go to 'background'
2. Click on 'fixed'
3. See error on mobile (for me: iphone x)

**Expected behavior**
A fixed and cover background on mobile for parallax.

**What actually happens**
A scroll and huge background on mobile.

**Desktop (please complete the following information):**
- OS: [windows 10]
 - Browser [firefox]
 - Oxygen Version [3.2]

**Smartphone (please complete the following information):**
- Device: [Iphone x]
 - OS: [iOS 12.1.3]
 - Browser [safari]
 - Oxygen Version [3.2]

**Comment by KittenCodes** [comment]
@CYBORG974 iOS doesn't support the CSS background-attachment: fixed. I would suggest setting it to "scroll" on the 480px break point (I've done this on the Sandbox site).
