### ISSUE TITLE
Error occured while saving

### ISSUE THREAD

**Issue by Marzii** [soflyy/oxygen-bugs-and-features#1039]
**Describe the bug**
Error occured while Saving 
200
Your server returned a 200 error for the request to undefined

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
Yes - I do not have access to the error.log though

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
No. I don't know what happend that the error appeared. 

**To Reproduce**
?

**Expected behavior**
A I expect my site to be saved and published

**What actually happens**
The wheel keeps spinning and in the top left an error messages appears

**Screenshots**
![error](https://user-images.githubusercontent.com/22818735/79642423-a6697880-819d-11ea-9c2a-e2b7cb027c18.PNG)

**Desktop (please complete the following information):**
- OS: Windows 10
 - Browser: Microsoft Edge Version 81.0.416.58
 - Oxygen Version: 3.2.1

**Error from browser consol**
```
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>503 Service Unavailable</title>
</head><body>
<h1>Service Unavailable</h1>
<p>The server is temporarily unable to service your
request due to maintenance downtime or capacity
problems. Please try again later.</p>
</body></html>
```

```
iframe.min.js?ver=3.2.1:6 SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at iframe.min.js?ver=3.2.1:6
    at angular.js?ver=1.4.2:9280
    at processQueue (angular.js?ver=1.4.2:13075)
    at angular.js?ver=1.4.2:13091
    at Scope.$eval (angular.js?ver=1.4.2:14291)
    at Scope.$digest (angular.js?ver=1.4.2:14107)
    at Scope.$apply (angular.js?ver=1.4.2:14395)
    at done (angular.js?ver=1.4.2:9569)
    at completeRequest (angular.js?ver=1.4.2:9756)
```

Both are relating to **http://dev.marmorwerk-horb.de/wp-content/plugins/oxygen/component-framework/angular/controllers/iframe.min.js?ver=3.2.1**

**Comment by Spellhammer** [comment]
Please submit a support request at https://oxygenbuilder.com/support and we will investigate.

**Comment by mupersan** [comment]
I have this same bug. This is driving me crazy

**Comment by MichaelErbe** [comment]
Hey guys, I have the same issue. Could you retrieve the error and have you found a solution? Thanks, Micha

**Comment by swinggraphics** [comment]
I also encountered this after changing a global font size and then the font size of an element on the page.

**Comment by uglyeoin** [comment]
Man I wish you would  post the answers here and not privately.  I've submitted a ticket but if there's a quicker solution which doesn't require me to bother you I would take it.

**Comment by Paciente8159** [comment]
Ok I've ran into to the same problem and dug a bit deeper. This error might be being triggered by some other plugin (due to Oxygen's design). In my case it was plugin I am developing. The problem is that while saving the oxygen screens are not registered as an administrative page. So any operations done by other plugins doing "theire thing" to the frontend most probably be reproduced in Oxygen.
The problem is while saving Oxygen makes some calls to some custom ajax points(other then admin-ajax) and the response that should be a single JSON string may get "contaminated".
I don't know if this is an easy thing to tackle and it might need a deeeeeppp change in Oxygen. Just my 5 cents.

**Comment by mwm-webdesign** [comment]
I had the same issue, it was caused by having an old version of SearchWP installed, after updating it to the latest version the error went away.

**Comment by Deichscheich** [comment]
Same problem, it's driving me nuts.

**Comment by M-Marbouh** [comment]
Same problem here...
Hopefully this will be fixed in V4.
![image](https://user-images.githubusercontent.com/53920207/166638071-a576ec30-6006-4ad0-af8a-9095af7b4eec.png)

**Comment by harryfear** [comment]
Same issue here. Very annoying!

**Comment by jacmcz** [comment]
Something new? Thats make me crazy!

**Comment by smithbenites** [comment]
I still have the same problem with the latest version released today, 4.0.4.

**Comment by ddgoehler** [comment]
We too have this issue. Still on 4.0.4.
Any news?? Or workaround?

**Comment by jojoba007** [comment]
Same issue over here!

**Comment by Spellhammer** [comment]
Anyone who is having this issue, please submit support tickets at support@oxygenbuilder.com so that we can investigate.

This is likely a server-dependent issue, so we have to see this in your specific environments to better understand the circumstances that cause it.

**Comment by mwmdev** [comment]
This issue kept comming up, I narrowed it down to a "template_redirect" action in one of my plugins that was supposed to run only on the front, but was causing trouble in oxygen.

Putting this at the beginning of the function fixed the problem :

```php
if ( $_REQUEST['ct_builder'] || preg_match( '/^ct_/', $_REQUEST['action'] ) ) {
  return;
}
```

**Comment by jojoba007** [comment]
> This issue kept comming up, I narrowed it down to a "template_redirect" action in one of my plugins that was supposed to run only on the front, but was causing trouble in oxygen.
> 
> Putting this at the beginning of the function fixed the problem :
> 
> ```
> if ( $_REQUEST['ct_builder'] || preg_match( '/^ct_/', $_REQUEST['action'] ) ) {
>   return;
> }
> ```

Hi, thanks for your reply. This is of great help. Could you maybe give me some additional info on where to implement this snippet specifically. I do code a little bit, but its not my main focus.

**Comment by mwmdev** [comment]
> Could you maybe give me some additional info on where to implement this snippet specifically. 

It really depends, what I did is deactivate all plugins except Oxygen, and reactivate them one by one, until the error starts to appear in the builder, which was with one of my own plugins. Then I commented out my plugin code and uncommented it block by block to find which part of it was causing the issue. Finally added the snippet at the start of the guilty function.

I suspect that any code that redirects the current page automatically on the frontend will cause issues when loaded in Oxygen.

**Comment by jereloh** [comment]
I have faced a similar issue, and have found that it was caused by a misconfigured nginx file after looking through digital ocean docs

changing the line  try_files $uri $uri/ /index.php; to try_files $uri $uri/ /index.php$is_args$args;

mine was configured to be:
```
server {
    . . .
location / {
    try_files $uri $uri/ /index.php;
  }  
    . . .
}
```


it should be:
e.g. under /etc/nginx/sites-available/wordpress
```
server {
    . . .
    location / {
        try_files $uri $uri/ /index.php$is_args$args;
    }
    . . .
}
```
