### ISSUE TITLE
Mobile navbar design

### ISSUE THREAD

**Issue by Ronblbc** [soflyy/oxygen-bugs-and-features#1044]
**Describe the feature you'd like to see included in Oxygen.**
- I have been researching mobile navigation menu optimization, it seems that there are no options available. For example, https://wpdevdesign.com/oxygen-responsive-menu, explains it well. But I am reluctant to install third-party plugins to customize the responsive menu.

**What are the use cases for this feature?**
https://wpdevdesign.com/oxygen-responsive-menu

**Examples of this feature or functionality.**
Mobile menu of this website shows it https://impactchirolb.com/

**Comment by KittenCodes** [comment]
@Ronblbc Please see Oxygen's Pro Menu element: https://oxygenbuilder.com/documentation/builder-elements/pro-menu/.

**Comment by Ronblbc** [comment]
@KittenCodes - thank you for the information. I was trying to update Oxygen 3.2.1 which is equipped with the functionality, but updates failed.

https://oxygenbuilder.com/2020/03/25/oxygen-3-2-1-now-available/, states "in-place update via the Plugins page in the WordPress admin panel." And that is not available. Wordpress is updated as of now but the feature is not available in plugins admins page on Wordpress.

Any suggestions to correct the issue?

Thanks gain

**Comment by KittenCodes** [comment]
@Ronblbc 

Please re-save your licence key via Oxygen > Settings > Licence, and then try to run the auto-update again. If it still fails, you can update manually by following these steps:

- Take a full backup of your site
- Deactivate and delete Oxygen
- Download the latest version from the customer portal: https://oxygenbuilder.com/portal
- Install it via the Plugins page on your site

**Comment by Ronblbc** [comment]
@KittenCodes - thanks, updating license key worked.

**Comment by Ronblbc** [comment]
@KittenCodes - thank you so much for the help so far. I upgraded to 3.2.1 and explored it. It seems still there is no setting for customizing the mobile menu size; it has either off-canvas menu or full-width menu. I could not find a way to customize to open it within the page as
![mobile menu dropdown_1](https://user-images.githubusercontent.com/63990663/79942489-cdcd7900-841b-11ea-820f-7e909683b02c.PNG)
![mobile menu dropdown](https://user-images.githubusercontent.com/63990663/79942494-d2922d00-841b-11ea-96d6-d0959bc0776e.PNG)

 it shows on the image attached.

**Comment by KittenCodes** [comment]
@Ronblbc 

Unfortunately, there's no built-in way to set the width of the mobile menu. However, you can do something like this with CSS:

```css
#-pro-menu-59-29 .oxy-pro-menu-container.oxy-pro-menu-open-container, #-pro-menu-59-29 .oxy-pro-menu-container.oxy-pro-menu-off-canvas-container {
    margin: auto;
    width: 80%;
    height: 80vh;
}
```
