### ISSUE TITLE
Single Post Template - Seth is blank in visual editor

### ISSUE THREAD

**Issue by sethc333** [soflyy/oxygen-bugs-and-features#1049]
Having mostly completed this template, it shows up when I preview a post that it is applied to. However, when I try to edit the template, the visual editor is blank. 

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
Yes

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
*If yes, provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*

**To Reproduce**
1. Go to Wordpress Home, Oxygen templates, Single Post Template - Seth
2. Click on Edit in Oxygen
3. See that the page is completely devoid of information, including the Main template it should inherit. 

**Expected behavior**
The template should load and be editable, just like the other templates.

**What actually happens**
The visual editor is blank, there are no post previews to apply from the drop down menu, and nothing happens when I click load Frontend. This only happens on this one template. All other templates load in the visual editor. 

**Screenshots**
<img width="1440" alt="Screen Shot 2020-04-20 at 4 28 07 PM" src="https://user-images.githubusercontent.com/64043438/79801606-01c57300-8324-11ea-9f89-dd97d39be5e1.png">

**Desktop (please complete the following information):**
- OS: macOS Mojave
 - Browser Firefox
 - Oxygen Version - newest

**Comment by KittenCodes** [comment]
@sethc333 Please send the site details to us in a support ticket so that we can take a look: https://oxygenbuilder.com/support.
