### ISSUE TITLE
Search box breaks template preview

### ISSUE THREAD

**Issue by dev-null-at** [soflyy/oxygen-bugs-and-features#1050]
Win10 / Firefox

When a template contains a Search Form block than loading the template produces the error:
"Error occured while rendering inner content"

Inner content can be shown with deleting the inner content element and insert it new. Frontend rendering is not effected.

Troubleshooting guide has been followed

The issue could be replicated with Oxygen 3.2.1 with plugings and with blank install. Also Beta 3.3 shows the same issue

1. Create a template for page
2. Insert at least an inner content and a search form element
3. save the template
4. make sure to have some content for preview
5. load the template to edit

- OS: Windows 10
- Browser Firefox
- Oxygen Version 3.2.1, 3.3 Beta 1

The issue does not occure with Google Chrome

![OxyError](https://user-images.githubusercontent.com/64080278/79865673-d30ad380-83db-11ea-8963-de131326de78.PNG)

**Comment by KittenCodes** [comment]
@dev-null-at 

I haven't been able to replicate this on our Sandbox site using Firefox on Windows 10. If you'd like us to take a look at your site, please open a support ticket: https://oxygenbuilder.com/support.
