### ISSUE TITLE
remote management of oxygen sites and key

### ISSUE THREAD

**Issue by misterjak93** [soflyy/oxygen-bugs-and-features#1051]
**Describe the feature you'd like to see included in Oxygen.*
a space where it is possible to remotely manage the various oxygen builder installations remove or generate new keys or, as a borderline case, completely block oxygen builder on a given site

**What are the use cases for this feature?**
not all customers / collaborators are equal, with some it is better to be careful ...

**Examples of this feature or functionality.**
Like in divi builder

**Comment by KittenCodes** [comment]
Duplicate: #123
