### ISSUE TITLE
Oxygen 3.3 Beta breaks the Date phpfunction

### ISSUE THREAD

**Issue by Gibsonion** [soflyy/oxygen-bugs-and-features#1054]
**Describe the bug**
Oxygen 3.3 Beta breaks the Date phpfunction, in previous versions I could use the Oxygen PHP function shortcopde to call just the current year with [oxygen data='phpfunction' function='date' arguments='Y'] in 3.3 this short code now returns a php error date() expects at least one parameter

**Have you tried all the steps at 
Yes

The issue was instantly resolved when switching back to version 3.2

**Comment by KittenCodes** [comment]
@Gibsonion This works correctly in the upcoming release of 3.1 RC 1.

**Comment by Gibsonion** [comment]
> @Gibsonion This works correctly in the upcoming release of 3.1 RC 1.

Do you mean 3.3?

**Comment by wpsumo** [comment]
@KittenCodes Is it going to be released this week?

**Comment by KittenCodes** [comment]
> Do you mean 3.3?

My bad. Yes, I do mean 3.3. I've amended my comment with the correct version..
