### ISSUE TITLE
Template Edit, AJAX Error

### ISSUE THREAD

**Issue by belenblndclr** [soflyy/oxygen-bugs-and-features#1057]
**Describe the bug**
*A clear and concise description of what the bug is.*
When i'm editing a template i'm triggering an error everywhere the template is called (also in child template). It's also trigger an error when Regenerating Cache CSS.
Warning: Invalid argument supplied for foreach() in /home/clients/df3c7391f7bb21a38ffa1ddac3abe500/wordpress/wp-content/plugins/oxygen/component-framework/includes/ajax.php on line 625 
(and an other Warning foreach() which I've haven't backup and I'm not keen on doing again)

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
*Yes/No*
Yes

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
*If yes, provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*

**To Reproduce**

**Expected behavior**
*A clear and concise description of what you expected to happen.*

**What actually happens**
*A clear and concise description of what happens instead of the expected behavior.*

**Screenshots**
*If applicable, add screenshots to help explain your problem.*

**Desktop (please complete the following information):**
- OS: Windows X
 - Browser : Firefox & Opera
 - Oxygen Version :  3.2.1

**Smartphone (please complete the following information):**
 - Oxygen Version : 

**Additional context**
*Add any other context about the problem here.*

**Comment by KittenCodes** [comment]
Fixed in v3.6.
