### ISSUE TITLE
Activating Oxygen on site with MemberPress Plugin breaks MemberPress content protection

### ISSUE THREAD

**Issue by petebytes** [soflyy/oxygen-bugs-and-features#106]
Added zip file containing video of the issue - also created a support incident and provided wpsandbox.

[Oxygen-MemberPress-conflict.mp4.zip](https://github.com/soflyy/oxygen-bugs-and-features/files/2904212/Oxygen-MemberPress-conflict.mp4.zip)

**Comment by wplit** [comment]
Memberpress protects the content inside the_content(). So any content inside the WordPress editor. In your video, the content that appears on the page is content created with Oxygen, which isn't.

You can still use Memberpress to protect Oxygen created content by following [this tutorial](https://wpdevdesign.com/how-to-password-protect-entries-in-oxygen/).

There is also a [video tutorial](https://oxygenbuilder.com/tutorial/membership-website-with-memberpress/) on Oxygen website showing more generally how to use Memberpress with Oxygen.

**Comment by petebytes** [comment]
For my use case, those were not great workarounds.

Here is what I ended up with:

* Write a MemberPress Rule to protect a Partial content
(this gives you shortcodes to hide and show content)

* Then use a Shortcode Wrapper to both, protect the Oxygen content and show the Login if unauthorized.

The trick part is that Oxygen ShortCode wrapper is not working if the shortcode uses a dash such as [mepr-hide and] [mepr-show]
So I had to modify the plugin files and replace the dashes with underscores [mepr-hide] -> [mepr_hide] for each of the shortcodes I am using.

Not a great solution but still a more workable solution for me.

There are two things that would make this a much improved solution.
* One is that the shortcode wrapper support dashes (although I think WP recommends underscores) I have an open issue here https://github.com/soflyy/oxygen-bugs-and-features/issues/86
* Two have a way to override plugins ( I know there are a few workarounds for that as well)

**Comment by petebytes** [comment]
Although the workaround is protecting content, several MemberPress capabilities are impacted.

Custom unauthorized messages/links do not trigger when usin partials.  This is a pretty severe as it possibly impacts sales by not providing a direct link to the product/membership.

Page protection status is not visible (due to using partials).  This is not a huge deal.

**Comment by wplit** [comment]
If you're happy / comfortable changing core plugin files for a quick solution, you could try changing Oxygen rather than Memberpress. This way some of the capabilities of the membership may not be impacted.

Haven't tested this fully with memberpress yet, but works on simple tests using hyphens in shortcode wrappers..

Here is default Oxygen failing the test with shortcode which has the hyphen...

http://fierce-rat.w5.wpsandbox.pro/

Here is Oxygen with one line of code changed to allow hyphen..

http://prickly-platypus.w5.wpsandbox.pro/

Line of code changed is line 58 of nestable-shortcode.class.php, changed to...

`preg_match('/\[(\w{1,}-\w{1,})[^\]]*\]/i', $wrappingShortcode, $matches);`

login links to test sites if you need;

http://fierce-rat.w5.wpsandbox.pro?upass=w0t3Ue3B6IeF
http://prickly-platypus.w5.wpsandbox.pro?upass=H3Ns36E9tgIg

**Comment by petebytes** [comment]
@wplit Cool thanks - I will try it out this weekend.

**Comment by wplit** [comment]
Hold on.. it doesn't work. It breaks the other shortcodes. I'll revise it.

**Comment by petebytes** [comment]
OK :)

**Comment by wplit** [comment]
I don't have time to figure it out today, my regex skills are failing me, and i need to go out, but that's the line of code that is causing the problem. 

(\w{1,}) only allows numbers, letters and underscores, which is usually fine as it's following what WordPress says. Shortcodes shouldn't have dashes. But Memberpress aren't following that. So it just needs to be changed to include words that are hyphenated.

**Comment by wplit** [comment]
think i've got it..

preg_match('/\[([\w-]{1,})[^\]]*\]/i', $wrappingShortcode, $matches);

**Comment by wplit** [comment]
Update: memberpress now supports underscores in their shortcodes 

<img src="https://scontent.fsyd3-1.fna.fbcdn.net/v/t1.0-9/55945100_10157231881550979_8576581156424646656_o.jpg?_nc_cat=111&_nc_ht=scontent.fsyd3-1.fna&oh=c04bb339cb4db2b42da8191ad4463262&oe=5D149209">

**Comment by KittenCodes** [comment]
Oxygen 2.3 now supports shortcode wrappers that contain a hyphen.
