### ISSUE TITLE
Content Encoding Error

### ISSUE THREAD

**Issue by platinumwb** [soflyy/oxygen-bugs-and-features#1060]
**Describe the bug**
I can no longer edit any Oxygen template or go into the Oxygen builder.  I get a page that give an error message "Content Encoding Error"

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
*Yes*

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
*If yes, provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*

I could not replicate this on your Sandbox install.

**To Reproduce**
1. Go to 'Oxygen > Templates'
2. Click on 'Edit then edit with Oxygen'
4. See error "Problem Loading Page" / "Content Encoding Error"

**Expected behavior**
*A clear and concise description of what you expected to happen.*

To have access to Oxygen builder.

**What actually happens**
*A clear and concise description of what happens instead of the expected behavior.*

I get a "Problem Loading Page" / "Content Encoding Error"

**Screenshots**
*If applicable, add screenshots to help explain your problem.*

**Desktop (please complete the following information):**
- OS: [iOS iMAC Catelina]
 - Browser [FireFox]
 - Oxygen Version [e.g. 2.2 Alpha]

**Smartphone (please complete the following information):**
 - Oxygen Version [3.2.1]

**Additional context**
*Add any other context about the problem here.*

Here is a screencast of the error
http://somup.com/cYf0h4iOAP

**Comment by KittenCodes** [comment]
@platinumwb Please reach out to your web host for help with this error.
