### ISSUE TITLE
oxygen builder

### ISSUE THREAD

**Issue by jozefridarcik** [soflyy/oxygen-bugs-and-features#1061]
Sorry for my english - i am from slovakia and little bit old :-D i am looking for website builder - i tryed Nicepage, not bad but... mobirise impossilbe tu put on CMS. I foung an Oxygen - i have a question:
When i build a website on oxygen, its possible to export classic html website with all needs (pictures, js, css..) and use it on other CMS than Wordpress? No joomlu, but some own cms - i need only u pure code with css - it is on oxygen possible? 

Thanks
jr.

**Comment by KittenCodes** [comment]
> When i build a website on oxygen, its possible to export classic html website with all needs (pictures, js, css..) and use it on other CMS than Wordpress? 

No, this isn't possible.
