### ISSUE TITLE
Error trying to update Add to Cart button color

### ISSUE THREAD

**Issue by nicocollu** [soflyy/oxygen-bugs-and-features#1064]
**Describe the bug**
I have an "Add to Cart" button and changed the color but when I apply parameters, it bugs out and ends up saying:
"Uncaught RangeError: Maximum call stack size exceeded on line #2 in https://berserkshoes.com/?ct_template=single-product&ct_builder=true&ct_inner=true&oxygen_iframe=true"
After this it reverts back to looking as it did even though the changes are set in the element settings.

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
No

**Desktop (please complete the following information):**
- OS: iOS
 - Browser: Brave
 - Oxygen Version: 3.2.1 & 1.2

**Comment by KittenCodes** [comment]
@nicocollu Please run a plugin conflict test by disabling all plugins (aside from Oxygen) and see if the RangeError persists.

If it occurs when Oxygen is the only active plugin, please open a support ticket: https://oxygenbuilder.com/support.

**Comment by nicocollu** [comment]
It's still an issue - I will contact support, thank you.
