### ISSUE TITLE
DONE: Client mode editing

### ISSUE THREAD

**Issue by yankiara** [soflyy/oxygen-bugs-and-features#1067]
**Describe the feature you'd like to see included in Oxygen.**
We need a client mode where templates editing is forbidden and where everything but content (text/icons/images) is locked, since fullpage Gutenberg editable mode doesn't work in all circumstances and doesn't sync content with editor.
Option to separately lock text, images, or icons would be a plus.

**What are the use cases for this feature?**
Safe content editing by client.

**Comment by KarzanTT** [comment]
+1

**Comment by alexandrudinu** [comment]
This would be great. At least to allow the customer to hide sections and update text without having to see all of it _(These are some options I think of, but there can be more)._

**Comment by andyduo** [comment]
+1 for this. It would be great if we could set what parts of a page/template are editable based on a user role. So clients could use the oxygen interface to edit or add text and images without access to the actual layout. I feel like this would make wordpress a much more user friendly experience for our clients.

**Comment by arsh999cg** [comment]
+1 for this.

**Comment by Clag75** [comment]
Yes, it would be great to be able to allow clients to only see and edit the parts I select! I would start building all sites in Oxygen if this was available.

**Comment by Martin-1** [comment]
Oh man a + a gazillion for this!!!

**Comment by tmz1970** [comment]
I stopped using Oxygen because clients can't safely edit content I build in Oxygen, and the Gutenberg integration is finicky/weak, and ACF is cumbersome/tedious. This would be an essential feature.

**Comment by alexandrudinu** [comment]
Not anymore, now is here!

**Comment by Spellhammer** [comment]
Implemented in Oxygen 3.6 alpha 1.

**Comment by andyduo** [comment]
Very excited about this one!
