### ISSUE TITLE
We do not see custom SVGs after uploading it from SVG Sets in Settings

### ISSUE THREAD

**Issue by vnshah** [soflyy/oxygen-bugs-and-features#1070]
We are able to successfully upload custom SVG icons but we are not able to see it when we add the icon element on the page/template. We followed the YouTube tutorial that is available on the website. https://oxygenbuilder.com/tutorial/custom-svg-icon-sets/

We also tried clearing the cache but no joy!

Any help much appreciated. 

Thanks

**Comment by Spellhammer** [comment]
IcoMoon changed the way their symbol-defs files are generated and there's an extra step you have to take now, from our documentation:

1. Visit IcoMoon.io and click IcoMoon App at the top right. You are redirected to the web app.
2. Choose the icons to add to your icon set. You can upload your own icons by clicking Import Icons in the top bar.
3. **Once you have finished, click Generate SVG & More, click Preferences at the top and select "Add <title> to symbol-defs.svg". Close the pop-up window and then click Download. The video here shows how to do this.**

Step 3 is now required to ensure the symbol-defs file contains the required title element.

**Comment by Spellhammer** [comment]
If the above doesn't fix the issue please submit a support ticket via https://oxygenbuilder.com/support.

**Comment by GandalfGrey77** [comment]
I have the same issue. Your tutorial is not working in my case. The icon is not working in the oxygen. 
My steps: 
iconmoon > import my own svg > export with title selected > import in oxygen > call the icon  but it appear as blank square (not icon)

**Comment by KittenCodes** [comment]
@GandalfGrey77 Please ensure your icon set contains at least two icons. If that doesn't help, please open a support ticket and send us the symbol-defs.svg file so that we can take a look: https://oxygenbuilder.com/support.

**Comment by GandalfGrey77** [comment]
Even if I use 2 icons more, there is not any of my customs svg icons. Show only the standard liblary icons that I choose, but not my custom icon.

**Comment by KittenCodes** [comment]
@GandalfGrey77 Please submit a support ticket via https://oxygenbuilder.com/support. Please include your symbol-defs.svg file in the ticket.
