### ISSUE TITLE
Error occurred while rendering innercontent

### ISSUE THREAD

**Issue by sarmientocarlos** [soflyy/oxygen-bugs-and-features#1071]
**Describe the bug**
*A clear and concise description of what the bug is. I want edit a template an apperas me an error: Error occurred while rendering innercontent, when save: Error occurred while saving

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?Yes
*Yes/No*

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?NO
*If yes, provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*

**To Reproduce**
1. Go to Oxygen->Templates->Main or another->Edit->go to oxygen editing->appears the error en red box.'

**Expected behavior**
*can´t editing anything on templates but, i can edit a webpage, home, contact, etc*

**What actually happens**
*A clear and concise description of what happens instead of the expected behavior.*

**Screenshots**
*If applicable, add screenshots to help explain your problem.*

**Desktop (please complete the following information):**
- OS: [e.g. iOS]Ubuntu 18.04
 - Browser [e.g. chrome, firefox]
 - Oxygen Version [3.2]

**Smartphone (please complete the following information):**
 - Oxygen Version [e.g. 2.2 Alpha]

**Additional context**
*Add any other context about the problem here.*
this is a test enviroment with Wordpress multisite with woocommerce. is a subdomain site. poleraslartes.tiendasde.cl
server is on Amazon lightSail with Gridpane control

**Comment by sarmientocarlos** [comment]
Error log: Notice: Undefined index: button_priority in /var/www/tiendasde.cl/htdocs/wp-content/plugins/oxygen/component-framework/api/oxygen.element.class.php on line 37

**Comment by KittenCodes** [comment]
@sarmientocarlos 

> Error occurred while saving

This error usually occurs when the address you're using to access the site doesn't match the addresses set via Settings > General in the WordPress admin area. For example, if you're accessing the site via HTTPS then the site addresses must also use HTTPS.

If this doesn't help, please open a support ticket so that we can take a look at your site: https://oxygenbuilder.com/support.

**Comment by smoothwebsites** [comment]
I'm experiencing this issue on a multilingual site which uses Polylang. Each language on the site uses a different domain, templates are not translated.

The primary domain of the WP installation is EN language, but when loading the builder, I can only choose to preview pages in SV language. I see the same error described above and am unable to save changes.

Working around it currently by choosing to preview 'English' in the builder, which I think relates to the language taxonomy that Polylang creates.
