### ISSUE TITLE
Iconset from Iconmoon doesn't show any icons when imported

### ISSUE THREAD

**Issue by smonsebjanic** [soflyy/oxygen-bugs-and-features#1072]
Hi,

When I create my own svg set on iconmoon with my uploaded svg icons the set is empty when I install it on my Oxygen install.

I can replicate the error on a sandbox too. https://oxygen-ql7pdf58q266.oxygen-demo.qsandbox.me/

It doesn't matter where I try to use it (template or post or page).

If I  look at the files downloaded from iconmoon I can see the icons, but they are not shown in Oxygen.

Please help.

All the best, 

Simon

**Comment by KittenCodes** [comment]
@smonsebjanic 

> When I create my own svg set on iconmoon with my uploaded svg icons the set is empty when I install it on my Oxygen install.

Please ensure that you're adding the <title> tag to your svg-defs file: https://www.loom.com/share/ae1c88e4cec34c8fa5cec6a4cc47de06.

Please also ensure that the icon set contains two or more icons.
