### ISSUE TITLE
Oxygen Reveals URL to Admin Login Page

### ISSUE THREAD

**Issue by mezimm** [soflyy/oxygen-bugs-and-features#1073]
Describe the bug**
I usually change the url to my admin login page so www.site.com/wp-login no longer works and it is changed to something like www.site.com/secretlogin 

The problem is oxygen let’s anyone find this url if they add the following to the end of the url:

https://www.site.com/?ct_builder=true

If you use that url, it doesn't matter if you changed your admin login url, anyone can now find it... I have not checked other URLs accessible to oxygen so there may be more URLs that trigger the redirect.

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
Yes

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
No because it requires changing the admin URL

**To Reproduce**
1. Change the admin url
2. Logout
3. Visit https://www.xxxx.com/?ct_builder=true

**Expected behavior**
404

**What actually happens**
It redirects you to the hidden admin url.

**Desktop (please complete the following information):**
- OS: windows 10
 - Browser chrome
 - Oxygen Version latest version

**Comment by louisreingold** [comment]
If you try to access the builder without the proper permissions it redirects you to the login screen. That's correct behavior.

Changing the URL of the login page obviously isn't going to stop the WordPress function that gets the URL of the login page from working.

If we "fixed" this non-bug we'd get other bug reports from people saying "I tried to access the builder URL when I wasn't logged in, but it doesn't redirect me to the login page."

**Comment by louisreingold** [comment]
A word of advice: making your login URL "secret" isn't a real security precaution. You may notice that wordpress.org's WP admin URL is public: wordpress.org/wp-admin. If it was such a problem they wouldn't be doing it.

**Comment by mezimm** [comment]
Well Wordpress the company probably has a bit more sexy precautions in place and custom code on the backend than the average joe? 

Also, why can’t you just have an option in settings to disable this behavior? Just have it 404. Like, what is the purpose of redirecting to the login page because who in the world aside from a potential hacker would be visiting that url anonymously? Makes no sense to me.
