### ISSUE TITLE
Code Block Search not appearing on other pages 

### ISSUE THREAD

**Issue by crezajill** [soflyy/oxygen-bugs-and-features#1074]
**Describe the bug**
*A clear and concise description of what the bug is.*

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
*Yes/No*

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
*If yes, provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*

**To Reproduce**
1. Go to https://suntime.com.my/demo/
2. On home page shows search Icon on top bar but then click on other pages
3. Code block search bar  not showing on other pages

Please advise

**Expected behavior**
 Code Block search bar should show to all pages since they are the same template

**What actually happens**
It's not appearing on other pages except home page

**Screenshots**
http://prntscr.com/s6io38

**Desktop (please complete the following information):**
- OS: Windows
 - Browser Chrome
 - Oxygen Version 3.2

**Comment by KarzanTT** [comment]
+1

**Comment by KittenCodes** [comment]
@crezajill Please open a support ticket so that we can take a look at this: https://oxygenbuilder.com/support.
