### ISSUE TITLE
Responsive control for div width doesn't work on Oxygen beta 3.3 beta 1

### ISSUE THREAD

**Issue by KarzanTT** [soflyy/oxygen-bugs-and-features#1075]
Hi

I have tried to create three horizontal div inside on section, but when I tried to control the div(s) width with less than 992px can't make the div width to %100?

Works fine on Oxygen 3.2.1 

Screen shoots:
https://prnt.sc/s6kqzd

OS: macOS 
Browser: Google Chrome
Oxygen Version: 3.3 beta 1

Thanks

**Comment by KittenCodes** [comment]
@KarzanTT I've not been able to replicate this in 3.3 Beta 1.

Please check if the width is set via the element ID - if it is then the class won't be able to override it.

If that doesn't help, please open a support ticket so that we can take a look at this: https://oxygenbuilder.com/support.
