### ISSUE TITLE
When me and my coworkers work on a project we overwrite each others style

### ISSUE THREAD

**Issue by 234873** [soflyy/oxygen-bugs-and-features#1078]
**Describe the bug**
*A clear and concise description of what the bug is.*
If i am editing a template and create classes for my elements, and another person is working in another template and save after me, all of my classes are not saved.
**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
*Yes/No*
Yes
**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
*If yes, provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*
I am able to replicate this, and it does not matter which template we are editing.
**To Reproduce**
1. Go to edit template on two seperate users on two seperate templates
2. Click on add selector
3. Create styles
4. The one that saves first have their styles erased

**Expected behavior**
*A clear and concise description of what you expected to happen.*
Styles created from both users are saved when working simultaneously
**What actually happens**
*A clear and concise description of what happens instead of the expected behavior.*
Only styles from the last saved template are saved
**Screenshots**
*If applicable, add screenshots to help explain your problem.*

**Desktop (please complete the following information):**
- OS: [e.g. iOS] macOS
 - Browser [e.g. chrome, safari] Chrome
 - Oxygen Version [e.g. 2.2 Alpha] 3.2

**Smartphone (please complete the following information):**
 - Oxygen Version [e.g. 2.2 Alpha]

**Additional context**
*Add any other context about the problem here.*

**Comment by Spellhammer** [comment]
This isn't a bug - editing by multiple concurrent users or in multiple tabs simultaneously just isn't supported. We've introduced edit locking in Oxygen 3.3 (the RC was just released) which should help prevent accidental overwrites. Please add your vote to this feature request if you'd like to see support for multi-user/multi-tab editing: https://github.com/soflyy/oxygen-bugs-and-features/issues/1066.
