### ISSUE TITLE
Class not working in a Modal element

### ISSUE THREAD

**Issue by jlebouch76** [soflyy/oxygen-bugs-and-features#1079]
While designing my footer, i included a modal element opening on clicking on text link, i observed the following problem (either in inline or live-preview (in-editor element):
After i assigned a class for Text or Heading element in a modal, i can't control the font size and weight of those elements. I'm using the same contact block than the one you used in the demo  video [https://www.youtube.com/watch?v=zyoBPUjX-H8](url). The font size is not changing in the backend as well as in the front end. 
When i remove the class on those text and heading and play with the font size and font weight on individual elements, the size and weight of the Heading or Text are properly changing both in backend end and frontend.

I use Oxygen 3.2.1 and gutenberg integration an, brave browser (1.7.98). I didn't resigned all the shortcodes since i only have one template. This is the first site i'm designing with Oxygen and i'm not a pro developer.

Thank you to look into this.

**Comment by KittenCodes** [comment]
@jlebouch76 Please ensure you have removed all styling from the element ID before styling it using a class. Classes can't override styles set via an ID.

If that doesn't help and you continue to have problems, please open a support ticket: https://oxygenbuilder.com/support.
