### ISSUE TITLE
RE: previously reported, "known" bug > possible connection to delay in download of Oxygen CSS file

### ISSUE THREAD

**Issue by DanFeather** [soflyy/oxygen-bugs-and-features#1080]
**Describe the bug**
*A clear and concise description of what the bug is.*
(Ha! If it were clear it wouldn't be a bug! But it is VERY annoying and threatens to be a deal-breaker.)

I reported the continual logging of Oxygen errors into site's "error_log." You replied that this was a  known bug. Hmmm . . . I purchased your software March 8, and my error_logs show that the bug was there at the time. And you've had an update . . .and the bug is still there. So that's 6 weeks. 

I've been very disappointed with the load speed of my site, despite its small size (homepage = 475 kb). I went through Lewis' YouTube tutorial on optimizing (which is VERY good, by the way. Thanks!), and I found that there was always a very long delay in fetching an Oxygen CSS file ("/?xlink=css&ver=5.4"). There is a "waiting" time of 2.58 seconds. That's half the time of the entire page load time. (This according to repeated test with GTMetrix.) [attached screenshot of test today]

Anyway, before I ran the GTMetrix test today, I deleted error_log from my site. Upon running the test, the error_log had been created with the usual errors (attached file).

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
*Yes/No*

These "shooting" steps don't seem relevant now. Tell me if there's something specific we might try.

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
*If yes, provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*

N/A

**Screenshots**
*If applicable, add screenshots to help explain your problem.*

see files

[error_log-from 0 to this after one hit.txt](https://github.com/soflyy/oxygen-bugs-and-features/files/4541444/error_log-from.0.to.this.after.one.hit.txt)
![slow-to-fetch-realted-error_log-maybe-20200427-DFeather](https://user-images.githubusercontent.com/16339251/80407752-1c539b00-8894-11ea-89b0-056e18cac8d3.jpg)

**Comment by louisreingold** [comment]
?xlink=css has nothing to do with errors in your error log. Enable the built-in CSS caching feature of Oxygen (or don't disable it, it's enabled by default). 

If you need assistance doing this, submit a support ticket and the team would be happy to help you.

If you've already reported the errors, there's no need to submit them again. If you have not, open a dedicated bug report with just the error log.

**Comment by DanFeather** [comment]
Hi, Louis. (sorry I misspelled your name in my github post!)

YES! Your suggestion made all the difference! Page load time went from 4.7 to 1.7 seconds. Sweet!

Thanks so much! 

Just so I'll understand a bit better:

* Is there any reason at all to turn off the CSS caching? . . . 

 - Dan

**Comment by louisreingold** [comment]
Our GitHub issue tracker is not the place for technical support / q&a.

Join the Oxygen user community on Facebook (10,000+ members) and ask there, or email our support team.
