### ISSUE TITLE
Color selector button is misaligned in Firefox

### ISSUE THREAD

**Issue by yankiara** [soflyy/oxygen-bugs-and-features#1084]
**Describe the bug**
In color selectors (left or right panels), the color selection button (circle) is not properly aligned.

Quick FIX:
```
.wp-picker-container {
    display: block;
}
```

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
*Yes*

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
*Yes but no need*

**To Reproduce**
*No need*

**Expected behavior**
*Button should be aligned.*

**What actually happens**
*Button is not aligned.*

**Screenshots**
![oxygen color selector](https://user-images.githubusercontent.com/36680757/80574824-d79a4200-8a02-11ea-9d6c-bae25ee29605.png)

**Desktop (please complete the following information):**
- OS: Windows 10
 - Browser: Firefox
 - Oxygen Version: 3.2.1

**Comment by KittenCodes** [comment]
@yankiara I'm not able to replicate this issue on a clean Sandbox site - I suspect another plugin or other CSS on your site is moving the position of the colour selector icon.

Screenshot: https://d.pr/i/5r7If4.

**Comment by yankiara** [comment]
Sandbox blank install, Firefox, please check again:

![color alignement](https://user-images.githubusercontent.com/36680757/81496856-047c0e00-92bb-11ea-9d59-3c637b170a38.png)

**Comment by KittenCodes** [comment]
@yankiara I'm very sorry - I missed that it was a Firefox-specific issue. I've reported this internally.

**Comment by ddon** [comment]
![image](https://user-images.githubusercontent.com/187798/84927648-ceaa2080-b0d5-11ea-849a-cafeb7d2733c.png)

checked in beta 1, still the same problem... single line bug fix, please find time to fix this.

**Comment by KittenCodes** [comment]
Fixed in v3.8 Beta 1.
