### ISSUE TITLE
DONE: Reset Element Styles to Default / Global Styles

### ISSUE THREAD

**Issue by TheStigenator** [soflyy/oxygen-bugs-and-features#1085]
**Describe the feature you'd like to see included in Oxygen.**
I'd like the feature where we can 'reset styles' for individual elements. Sometimes when mucking around, you accidently change something and then you cant find it. Its easier to just 'reset' the style elements to default / global style (if its set already globally). 

For example, you are playing around with say nested DIV's and you change something on one div, and the elements within that div end up getting changed. Now you are trying to track where that change happened. Its easier to reset that master div, or element (maybe a text, or a iconbox or whatever), and restart that styling. This usually happens with size / spacing / layouts / text styling / effects etc. 

I've highlighted 'yellow', the items that got changed within the styles. You cant tell what you changed within it sometimes, and best if we can just reset it back to defaults. 

**What are the use cases for this feature?**
makes development easier, fixing bugs easier. 

**Examples of this feature or functionality.**
Divi, has a local style reset for the elements. 

[image](https://user-images.githubusercontent.com/64546967/80619394-83d72b00-89f9-11ea-9e47-a22a9e758f29.png)

**Comment by KittenCodes** [comment]
You can now click the Delete icon to remove all the styles from an ID or class.

**Comment by wpsumo** [comment]
@KittenCodes are you sure he is not referring to property reset and not the whole element ID/Class styling? Like reset layout property etc.
