### ISSUE TITLE
component.class check if string first (FIX INCLUDED)

### ISSUE THREAD

**Issue by LeonardoCiaccio** [soflyy/oxygen-bugs-and-features#1086]
**Describe the bug**
The function `static function get_width( $width )` return error if **$width** not a string.
Fixed with `if( !is_string($width) || trim($width) == "" )$width = "";` before.

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
Yes

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
Yes but no need

**To Reproduce**
No need

**Expected behavior**
No errors

**What actually happens**
Return errors

**Screenshots**
![Screenshot 2020-04-29 19 09 57](https://user-images.githubusercontent.com/1698144/80625208-2bca1400-8a4d-11ea-8b5b-c7e24bfeed9c.jpg)

**Desktop (please complete the following information):**
- OS: Windows 10
 - Browser: Firefox 75.0 (64bit)
 - Oxygen Version: 3.2.1

I LOVE OXYGEN BUILDER!!!

**Comment by KittenCodes** [comment]
Fixed in 3.6 Beta.
