### ISSUE TITLE
DONE: Develop a fine and thorough permissions management system in Oxygen

### ISSUE THREAD

**Issue by pdubhol75** [soflyy/oxygen-bugs-and-features#109]
It should be possible to give access to Oxygen while hiding all the settings that we want to protect. 

The goal is to allow clients to modify all fixed content (fixed text, pictures, videos ...) without the risk of destroying the design.

Currently the technique to apply is Advanced Custom Fields. But it's not really flexible in Oxygen for that.

Competitors such as Elementor offer fine and thorough authorization management.

**Comment by AmibeWebsites** [comment]
I'd be specifically interested in preventing roles from doing anything that allows anyone to execute PHP code. Perhaps there's a hook that allows this functionality to be turned off or restricted?

**Comment by skrypt-nl** [comment]
Unfortunately this is the only thing I feel like Oxygen is really missing right now. This is a really great feature of Elementor for people who build websites for clients and don't want them to mess up the design, but still want them to be able to change the content of the website.

**Comment by RochallorDigital** [comment]
This is so needed. The only example I know of this is from Themeco' X and Pro themes, and I think it's brilliant.
They even have profiles for changing Text only, Text and Images, just some elements, and so on.
https://theme.co/docs/configure-user-permissions

**Comment by KittenCodes** [comment]
Added in Edit Mode in v3.6.
