### ISSUE TITLE
Client can't change image in Gutenberg...

### ISSUE THREAD

**Issue by cpasq** [soflyy/oxygen-bugs-and-features#1091]
when image is in a column. In that case clicking on the image has no effect whereas on other parts of the same page he can change another standalone image.

**Describe the bug**
*A clear and concise description of what the bug is.*

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
*Yes/No*
no
**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
no, can't edit images at all on sandbox
*If yes, provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*

**To Reproduce**

**Expected behavior**
*A clear and concise description of what you expected to happen.*

**What actually happens**
*A clear and concise description of what happens instead of the expected behavior.*

**Screenshots**
*If applicable, add screenshots to help explain your problem.*

**Desktop (please complete the following information):**
- OS: [e.g. iOS] windows 10
 - Browser [e.g. chrome, safari]edge (chrome)
 - Oxygen Version [e.g. 2.2 Alpha]3.3RC

**Smartphone (please complete the following information):**
 - Oxygen Version [e.g. 2.2 Alpha] 

**Additional context**
*Add any other context about the problem here.*

**Comment by KittenCodes** [comment]
@cpasq We will need to see this happening to be able to help. Please open a support ticket: https://oxygenbuilder.com/support.
