### ISSUE TITLE
24 PHP error from Oyxgen in a fresh installed site, I am not sure is it a problem or a bug

### ISSUE THREAD

**Issue by 1101blueli** [soflyy/oxygen-bugs-and-features#1095]
**Describe the bug**

Undefined index: button_priority 24 +
wp-content/plugins/oxygen/component-framework/api/oxygen.element.class.php:37
![Screenshot 2020-05-01 at 11 54 20 PM](https://user-images.githubusercontent.com/55223003/80824952-01758380-8c12-11ea-9c0c-663af7efaeff.png)

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
No*

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
*If yes, provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*

**To Reproduce**

**Expected behavior**
*A clear and concise description of what you expected to happen.*

**What actually happens**
*A clear and concise description of what happens instead of the expected behavior.*

**Screenshots**
*If applicable, add screenshots to help explain your problem.*

**Desktop (please complete the following information):**
 - Oxygen Version [e.g. 2.2 Alpha]

**Smartphone (please complete the following information):**
 - Oxygen Version [e.g. 2.2 Alpha]

**Additional context**
*Add any other context about the problem here.*

**Comment by KittenCodes** [comment]
#974
