### ISSUE TITLE
Header behavior in builder is not identical to the front end

### ISSUE THREAD

**Issue by ramnathk** [soflyy/oxygen-bugs-and-features#1097]
**Describe the bug**
I create a header with an image on the left and say an icon on the right. The preview at various device resolutions shows the image getting resized heavily, while on the frontend this does not happen

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
Yes

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
*If yes, provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*

https://oxygen-q4gp7qmlm798k.oxygen-demo.qsandbox.me/wp-admin/admin.php?page=oxygen_vsb_settings&tab=cache&start_cache_generation=true

**To Reproduce**
https://www.loom.com/share/6dcfd24bad924005913bf250e48a2fea

**Expected behavior**
*A clear and concise description of what you expected to happen.*
The spacing between the elements in the builder should reflect what happens on the frontend

**What actually happens**
*A clear and concise description of what happens instead of the expected behavior.*

**Screenshots**
*If applicable, add screenshots to help explain your problem.*
https://www.loom.com/share/6dcfd24bad924005913bf250e48a2fea

**Desktop (please complete the following information):**
- OS: MacOS
 - Browser Chrome
 - Oxygen Version 3.2.1 (and 3.3 rc1)

**Smartphone (please complete the following information):**
 - Oxygen Version [e.g. 2.2 Alpha]

**Additional context**
*Add any other context about the problem here.*

**Comment by KittenCodes** [comment]
@ramnathk 

When you're working in the builder, the middle header row (which isn't in use in your demo) has a width of 80px set. This is so that you can easily drag elements into it.

When the site is rendered on the front-end, that width doesn't exist. This allows the image to take up 100% of the available space.
