### ISSUE TITLE
Add "edit with oxygen" link in post/page list

### ISSUE THREAD

**Issue by AThoss** [soflyy/oxygen-bugs-and-features#1098]
Hi, I would like to have an "Edit with Oxygen" link right in the admin page/post list when I hover over a page item. This would make you not to open the page before you can edit it.

**Comment by KittenCodes** [comment]
This has been added in 3.3. Please see the Alpha changelog here: https://oxygenbuilder.com/2020/04/01/oxygen-3-3-alpha-1-now-available/.

**Comment by AThoss** [comment]
Awesome thank you.
