### ISSUE TITLE
Cache left sideabar window position when selecting similar elements  

### ISSUE THREAD

**Issue by AThoss** [soflyy/oxygen-bugs-and-features#1099]
I noticed that a lot of unnecessary clicks are necessary when working in the editor and change some settings from a lot of elements.
When you select a element under "Structure" in the right sidbar in the editor and then in the left sidebar navigate to let's say "advanced" > "Size & Spacing", this position should be saved/cached. 
When you select another similar item in the main window or under "Structure" then on the left there still should be the "Size & Spacing" section opened in the left sidebar. This would make the workflow more efficient.

**Comment by KittenCodes** [comment]
Please see:

#112 

#13
