### ISSUE TITLE
DONE: Edit with oxygen link

### ISSUE THREAD

**Issue by sergiubacioiu** [soflyy/oxygen-bugs-and-features#110]
![annotation 2019-02-28 162952](https://user-images.githubusercontent.com/3979555/53573549-5f25c000-3b76-11e9-82a0-5cd48b84232f.jpg)

I think the image is self-explanatory

Right now I made this function but it needs more improvements. This is enough for me at this moment because I avoid one step when I want to load the builder faster in development.

```
function oxygen_post_row_action_edit( $actions, $post ) {
if ( $post->post_type == 'post' ) {
$actions['oxygen'] = '<a href="'. post_permalink( $post->ID ) .'?ct_builder=true&ct_inner=true">Edit with Oxygen</a>';
}
return $actions;
}
add_filter( 'post_row_actions', 'oxygen_post_row_action_edit', 10, 2 );
```

I think this would be a nice addition to the oxygen core.

**Comment by wplit** [comment]
I agree. Removing the view link to simplify would also be good also as it only takes us to the same place as the edit link. Code i use...

`function remove_row_actions( $actions )
{
    if( get_post_type() === 'ct_template' )
        unset( $actions['view'] );
    return $actions;
}
add_filter( 'post_row_actions', 'remove_row_actions', 10, 1 );`

**Comment by wplit** [comment]
Oops. I was referring to the template screen, not the posts. Either way, a link straight to the builder on both screens would be useful.

**Comment by KittenCodes** [comment]
This has been added.
