### ISSUE TITLE
Custom Font not displaying in the selection option in left menu

### ISSUE THREAD

**Issue by andycaps** [soflyy/oxygen-bugs-and-features#1103]
**Describe the bug**
*A clear and concise description of what the bug is.*

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
*Yes/No* ****YES****

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**

NO

*If yes, provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*

**To Reproduce**

**Expected behavior**
*A clear and concise description of what you expected to happen.*

I FOLLOWED YOUR VIDEO FOR CREATED CUSTOM-ICONS WITH ICOMOON - DOWNlLOADED THE FILES AND INSTALLED IN OXYGEN, IT APPEARS TO SAVE THE FILE AND DISPLAY THE NAME OF THE ICON SET BUT NOTHING IS DISPLAYED FOR USER SELECTION.

**What actually happens**
*A clear and concise description of what happens instead of the expected behavior.*

NOT ABLE TO MAKE AN ICON SELECTION

**Screenshots**
*If applicable, add screenshots to help explain your problem.*

THIS SCREEN SHOT DISPLAYED THE FILE NAME INSTALLED.
![Screenshot 2020-05-02 at 17 55 47](https://user-images.githubusercontent.com/10528963/80870417-33342c00-8c9e-11ea-9240-b36772afe547.png)

THIS SCREEN SHOW SHOWS THE DOWNLOADED FILES FROM ICOMOON - I INSTALLED THE FILE: symbol-defs.svg
<img width="447" alt="Screenshot 2020-05-02 at 17 56 54" src="https://user-images.githubusercontent.com/10528963/80870429-519a2780-8c9e-11ea-81e3-d70e8ccd6362.png">

**Desktop (please complete the following information):**
 - Oxygen Version [e.g. 2.2 Alpha]

<img width="503" alt="Screenshot 2020-05-02 at 17 58 47" src="https://user-images.githubusercontent.com/10528963/80870483-9a51e080-8c9e-11ea-9882-f1831a5fdf15.png">

I AM USING APPLE SAFARI WEB BROWSER

MY VERSION OF OXYGEN IS: 3.2.1

**Smartphone (please complete the following information):**
 - Oxygen Version [e.g. 2.2 Alpha]

**Additional context**
*Add any other context about the problem here.*

THE PREINSTALLED ICONS BY FONT AWESOME AND LINEARICONS WORK AS EXPECTED

**Comment by Spellhammer** [comment]
From our documentation at https://oxygenbuilder.com/documentation/other/custom-svg-icon-sets/:

> Once you have finished, click Generate SVG & More, click Preferences at the top and select "Add <title> to symbol-defs.svg". Close the pop-up window and then click Download. The video here shows how to do this.
