### ISSUE TITLE
A way to set up multiple vendors like https://wedevs.com/dokan

### ISSUE THREAD

**Issue by mugaan** [soflyy/oxygen-bugs-and-features#1106]
**Describe the feature you'd like to see included in Oxygen.**
*A clear, detailed description of the feature you're requesting.*

**What are the use cases for this feature?**
*e.g. Accessibility, e-commerce store that sells bicycles, etc.*

**Examples of this feature or functionality.**
*If another product has done it well, provide examples here.*

**Comment by mugaan** [comment]
The ability to create multi-vendor sites like https://wedevs.com/dokan provides would be a great feature for oxygen builder.

**Comment by louisreingold** [comment]
There's nothing stopping you from using Oxygen on a WordPress site with multiple vendors right now...
