### ISSUE TITLE
Bug Report for Show/Hide feature

### ISSUE THREAD

**Issue by HeadBit** [soflyy/oxygen-bugs-and-features#1108]
**Describe the bug**
The show/hide selector in the property pane just show text that is not active

**Have you tried all the steps at**
 Yes
![Screen Shot 2020-05-03 at 3 00 49 PM](https://user-images.githubusercontent.com/4798586/80927162-a8f8d000-8d50-11ea-8ea2-e8bb1c1d761e.png)

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
Yes. https://oxygen-q5vn9jrx9wa9k.oxygen-demo.qsandbox.me/

**To Reproduce**
Load any page/template in the editor and it show just unlinked text

**Expected behavior**
I expected there to be a button as in the intro video that is clickable to hide/show properties

**What actually happens**
Nothing

**Screenshots**
Yes

**Desktop (please complete the following information):**
- OS: Mac OS
 - Browser: Chrome Firefox Developer
 - Oxygen Version: 3.3 RC1

**Comment by Spellhammer** [comment]
Please hard-refresh your browser (clear the cache) and this issue should be corrected. If it's not, send a ticket via https://oxygenbuilder.com/support.
