### ISSUE TITLE
Selling Oxygen Themes

### ISSUE THREAD

**Issue by gmichel1994** [soflyy/oxygen-bugs-and-features#1109]
Hello dear Oxygen IT Support, 

I have recognized that no one is selling Oxygen Themes on themeforest and other plattforms. 
Is it allowed to build a custom theme Importer for Oxygen and sell the theme including Oxygen Pagebuilder (of cource without the purchased license key)?

I am very convinced of OXYGEN and would like to make it more public.

Kind regards, 
Georgij

**Comment by louisreingold** [comment]
You can already create your own design sets for Oxygen and sell them. Many people are doing so on our Facebook group.

**Comment by gmichel1994** [comment]
Ok thank you for this information. 
Kind regards, 
Georgij Michel
