### ISSUE TITLE
Add WooCommerce Schema Markup

### ISSUE THREAD

**Issue by KittenCodes** [soflyy/oxygen-bugs-and-features#1111]
WooCommerce automatically adds schema to products. However, the schema is only output if the Product template in Oxygen uses an Inner Content element so that the default WooCommerce product layout is used.

If you are using Oxygen's elements to build the layout then no schema data is added.

It would be nice to see the WooCommerce schema being added to products automatically.

**Comment by michacassola** [comment]
Yes! Schema all around please!

**Comment by flo-glass** [comment]
Same here. This is very important for me

**Comment by MPHood** [comment]
gogogo

**Comment by Spellhammer** [comment]
This was added in WooCommerce 2.0, but we never closed the public report. If there are issues with our implementation, please open a new bug report.
