### ISSUE TITLE
Tables in database getting "is marked as crashed and should be repaired"

### ISSUE THREAD

**Issue by runechronos** [soflyy/oxygen-bugs-and-features#1115]
Hy,

I got a major problem overall using Oxygen the 2 last days and I don't know why. 
Just by using Oxygen, building things saving in th visual builder, etc. I end up with my server loading indefinitely not being able to save nor to show the webpages. And I have no choice but to restart my computer.

I'm working on my localhost with **apache 2.4 and mariadb 10.**
I've looked the error logs of maria db and I get many times theses errors : **"my_table" is marked as crashed and should be repaired"**
For tables **wp_options, wp_usermeta, wp_posts, wp_postmeta** 

I repaired thoses tables inside my sql console and afterwards everything was working again but like an hour after, it happened again, and it keeps hapenning. I don't get why, I never had those problems before and I did not do something special. It's preventing me from working, i'm starting to get insane reset the computer and repair the database each time every 10 minutes, I just can't work like this.....

What might be happening ? I think it might be related to memory allocation:
What are the recommande values to use Oxygen 3.3 properly ? I think it should be this because I haven't any problem until my webstite started to get more complex.
Recommanded values for : 

**PHP memory_limit ?**
**InnoDB buffer size ?**
**SQL max allowed packets ??**

Thanks in advance.

Edit: I tried to put high values like PHP memory_limit : 4095mo, InnoDB buffer size 2048Mo, i managed to have no bug for 1hour, and the same error happenned again. I'm really desperate.

**Comment by KittenCodes** [comment]
@runechronos Unfortunately, we can't troubleshoot local environments. However, if you experience the same issue in an accessible environment, please open a support ticket so that we can investigate: https://oxygenbuilder.com/support.

The recommended values will depend on the size of your site.
