### ISSUE TITLE
Adding a div in a new header row breaks the layout and corrupts shortcodes

### ISSUE THREAD

**Issue by yankiara** [soflyy/oxygen-bugs-and-features#1117]
**Describe the bug**
After adding a row to a header element, adding a div break the layout.
Sometimes it's just the frontend that won't show some other elements in the header.
Sometimes it corrupts shortcode and breaks the whole template and it is unrecoverable, except if you go back in revisions.

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
Yes

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
https://oxygen-qk87jkm4s398k.oxygen-demo.qsandbox.me

**To Reproduce**
1. Go to template TEST
2. Open Hello world in frontend

**Expected behavior**
Frontend should show what's defined in backend.

**What actually happens**
Top row is empty
If you delete text element or div, everything is broken (screenshot 3)

**Screenshots**
![02 bug div header 2](https://user-images.githubusercontent.com/36680757/81169476-33337500-8f99-11ea-8783-8dc9f900cae0.png)
![02 bug div header 3](https://user-images.githubusercontent.com/36680757/81169480-3464a200-8f99-11ea-9700-208f8cafe6e0.png)
![02 bug div header](https://user-images.githubusercontent.com/36680757/81169483-34fd3880-8f99-11ea-9642-bc8c8a1d869b.png)

**Desktop (please complete the following information):**
- OS: Windwos
 - Browser Firefox
 - Oxygen Version 3.2.1

**Comment by KittenCodes** [comment]
@yankiara I've taken a look at the Sandbox site, but I'm not able to see a broken layout - the builder layout matches the Structure Panel, and the front-end of the site matches the builder display.

If you're still having problems, please record a quick video showing exactly what you're doing and what is happening: https://www.loom.com/.

**Comment by yankiara** [comment]
Hi!
I'm sooo sorry for my late answer... I'm pretty busy these days, and can't
remember exactly what I had done to provoke this bug because it's been a
long time and it was kind of tricky.
It happened to me again in another circumstance, wrapping an element into a
div in the header. Everything was broken again, including the page
shortcode (some entire row missing) and frontend (header tag missing, and
entire top row div or something like that).

I'll try again soon and let you know if I can reproduce it properly.

Thx for your help,
Yan

Le dim. 10 mai 2020 à 13:05, Soph Simmonds <notifications@github.com> a
écrit :
