### ISSUE TITLE
Slider creates TypeError in the preview

### ISSUE THREAD

**Issue by NetOldie** [soflyy/oxygen-bugs-and-features#1118]
**Describe the bug**
The bug is already present since version 3.2. It is reproducible in FireFox and Opera Browser

Steps to Reproduction:

1. create normal page with a slider
2. open a template (MainTemplate)
3. set the preview of the page with the slider
4. wait three to five seconds or scroll to Slider

Then the error appears:
TypeError: $(...).unslider is not a function on line #1 in https://xxxxx.example.com/wp-includes/js/jquery/jquery.js line 2 > eval

The content of the slider will be displayed below each other.
The slider itself does not work anymore

The error does not occur on the page itself.

**Screenshots**
*If applicable, add screenshots to help explain your problem.*

**Desktop (please complete the following information):**
- Device: Desktop
 - OS: Windows 10 
 - Browser FireFox 75.0 & Opera Version:68.0.3618.63
 - Oxygen Version 3.3 & 3.2.1

![Anmerkung 2020-05-06 155431](https://user-images.githubusercontent.com/64497200/81185583-0dff3080-8fb2-11ea-8245-b6e4022f394a.jpg)
![Anmerkung 2020-05-06 155519](https://user-images.githubusercontent.com/64497200/81185589-0e97c700-8fb2-11ea-87ac-383ecf0e6535.jpg)

**Comment by jasperf** [comment]
Any news on this bug? Seems to cause issues with stylesheet editor as well.

![Screen Shot 2020-06-14 at 11 51 17 AM](https://user-images.githubusercontent.com/344138/84585027-6210f680-ae35-11ea-8e51-65cae4fec9b7.png)

**Comment by KittenCodes** [comment]
@jasperf The CodeMirror issue is separate and occurs when specific widgets are added to the builder. We have an internal bug report open for this.

**Comment by jasperf** [comment]
@KittenCodes does 3.4 fix the CodeMirror issue?

**Comment by gleysen** [comment]
@jasperf I'm currently editing on 3.4 and have this same issue (slider in page that uses main template, and when I edit the main template with that page as preview, it throws this error)

**Comment by didgex** [comment]
I just noticed this bug still shows up in 3.5 (Chrome / FF). 
Fresh and clean WP (5.5.1) install with no other plugins installed. 
In my case the error seems to show up only with a Pro Menu in the header.

**Comment by danpii** [comment]
Same problem here (FF, Chrome)
WP 5.5.1, Oxygen 3.5.
The error also only shows up with the Pro Menu.

**Comment by pixluser** [comment]
Same bug too.

`$(...).unslider is not a function on line #1 in https://xx/?ct_template=head-footer&ct_builder=true&oxygen_iframe=true`

**Comment by nikxexde** [comment]
No solution yet?

**Comment by pixluser** [comment]
me no ...


// Lionel Loeb

**Comment by NetOldie** [comment]
Yesterday, I see the Error again.

**Comment by YammYcoding** [comment]
+1

**Comment by iampinha** [comment]
Any news on this bug?

**Comment by iampinha** [comment]
WordPress 5.7
Oxygen 3.7.1
Pro Menu + Slider Page
Error: TypeError: $(...).unslider is not a function on line #2 ...

**Comment by ElectronEsq** [comment]
Issue exists in 3.8 Alpha 1 (March 19th)
![image](https://user-images.githubusercontent.com/29914179/111948027-38a29b00-8b2a-11eb-9a86-82a2cc12d68a.png)

**Comment by cubicom** [comment]
Hi, WP 5.7.1, Oxy 3.7.1, Pro Menu + Slider and the same error.
This is a year old bug, please fix it! Thanks.

**Comment by KittenCodes** [comment]
Fixed in v3.8 Beta 1.
