### ISSUE TITLE
Hide & Show feature does not work

### ISSUE THREAD

**Issue by NetOldie** [soflyy/oxygen-bugs-and-features#1119]
The new feature hide & show in version 3.3 does not work in the Opera browser. 
It works well in Firefox.

Version:68.0.3618.63
Opera is up to date
Update Stream:Stable
Operating system:Windows 10 64-bit

see screenshot
![Anmerkung 2020-05-06 155834](https://user-images.githubusercontent.com/64497200/81186502-26bc1600-8fb3-11ea-8370-c2803a1c7282.jpg)

**Comment by Spellhammer** [comment]
Clear your browser cache and any caching plugins running on your site.

**Comment by NetOldie** [comment]
Thank you for pointing that out.

Only after another complete clearing of the cache in Opera it will work now.
