### ISSUE TITLE
Ghost "button area" elements appear at the bottom of every inner content page structure !

### ISSUE THREAD

**Issue by huaultpierre** [soflyy/oxygen-bugs-and-features#1122]
Congratulations for this last 3.3 update of Oxygen !
Great enhancements for sure as we use it and are happy to do so day after day.

This said, such strange an effect has appeared I can’t explain.  I noticed this happened at the very moment I've upgraded but it may be a coincidence, who knows ? 
Did I miss something ?

Mainly, I’ve made the find of a new element at the very bottom of each of my inner content structure panel, called « button area », wich I can have absolutely no power over (can’t delete it, nor expand it, while it shows a + icon, and that send me an error message as soon as I try to move it in the structure hierachy !!). (screen 1&2)
This element (that I can’t find any clue in any element panel), is now implemented in each inner content of the whole pages. Due to the fact, I mean auto-implemented !!
This element is also present at the very first stage in the Inner Content structure when creating a new page. (screen 3)
 
How is it that this happened ? How this « ghost element », named as « undefined » can be usefull (if it is) ? How can I manage to delete this element (if it is not) ? 

I just would like to know how to get power over this somehow.

Thank you so much for your feedback on this point. Moreover, thank you for 
the great great job and tool you've built.
Take care.
All the best

PS issue posted on the official Oxygen user group with no back input at the time

<img width="872" alt="Capture d’écran 2020-05-06 à 10 05 12" src="https://user-images.githubusercontent.com/23433787/81235258-c94bb780-8ffa-11ea-98cb-af04b746ced4.png">
<img width="262" alt="Capture d’écran 2020-05-06 à 10 16 15" src="https://user-images.githubusercontent.com/23433787/81235319-e5e7ef80-8ffa-11ea-8e8d-d63d2bda9e8c.png">
<img width="791" alt="Capture d’écran 2020-05-07 à 00 28 10" src="https://user-images.githubusercontent.com/23433787/81235335-eda79400-8ffa-11ea-8eaf-2b2c0f3aca90.png">

**Comment by KittenCodes** [comment]
@huaultpierre This is most likely caused by the Icon Box element. If you would like us to remove the Button Area elements for you, please open a support ticket: https://oxygenbuilder.com/support.

**Comment by KittenCodes** [comment]
#529

**Comment by Lupul** [comment]
I also have this issue, multiple ghost 'button area' elements show up in the structure. Please advise how we can remove them ourselves until this bug gets fixed in Oxygen.

**Comment by Damdo74** [comment]
Hi Oxygen Support,
can you please help me out here as i happen to have the same issue : Ghost Button Area, now show on my templates. No idea where they come from.

![image](https://user-images.githubusercontent.com/68645122/95585381-6d6cdb00-0a3f-11eb-8564-191177724800.png)
![Capture d'écran 2020-10-09 14 54 31](https://user-images.githubusercontent.com/68645122/95585400-78277000-0a3f-11eb-8bb8-1c1733926bc6.jpg)

**Comment by KittenCodes** [comment]
@Damdo74 These are caused by Oxygen's Icon Box element. Unfortunately, the only way to fix it is to remove the Icon Box elements from your site and to build the same layout using Divs.

If you need help doing this, please open a support ticket: https://oxygenbuilder.com/support.

**Comment by KittenCodes** [comment]
Fixed in 3.7 Beta 1: https://oxygenbuilder.com/2021/01/22/oxygen-3-7-beta-1-now-available/.
