### ISSUE TITLE
Missing menu and delete in "Structure" with jQuery 3.5.0 and above

### ISSUE THREAD

**Issue by riDuxd** [soflyy/oxygen-bugs-and-features#1126]
I've been using jQuery Updater for awhile now and I noticed that with the latest update that came with jQuery 3.5.1, the menu and delete button (image below) disappeared.. I tried the plugin in with jQuery 3.4.1 and it works just fine.

![image](https://user-images.githubusercontent.com/32417703/81419012-69d8cf00-9102-11ea-8999-f421946b17f9.png)

**Comment by KittenCodes** [comment]
Oxygen uses the version of jQuery that is within the WordPress core (v1.12.4). I suspect something has changed in jQuery v3.5.1 that breaks Oxygen.

Unfortunately using a different version of jQuery isn't something we can support.
