### ISSUE TITLE
There is an option for input fields? I am creating food app so I need to make a reservation section.

### ISSUE THREAD

**Issue by faranmughal12** [soflyy/oxygen-bugs-and-features#1127]
**Describe the feature you'd like to see included in Oxygen.**
*A clear, detailed description of the feature you're requesting.*

**What are the use cases for this feature?**
*e.g. Accessibility, e-commerce store that sells bicycles, etc.*

**Examples of this feature or functionality.**
*If another product has done it well, provide examples here.*

**Comment by YammYcoding** [comment]
+1
