### ISSUE TITLE
Pro Menu item padding set as 'px' after 3.3 update.

### ISSUE THREAD

**Issue by shoelaced** [soflyy/oxygen-bugs-and-features#1129]
**Describe the bug**
*A clear and concise description of what the bug is.*

After the 3.3 update I've lost all the padding that I had set as `em` on the desktop menu items. After investigation, this appears to be because Oxygen is saving the padding as `px` regardless of the unit selection, so `1em` gets converted to `1px`.

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
*Yes/No*

Yes.

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
*If yes, provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*

No, because the Sandbox has not been updated to the new version. Another user in the Group is experiencing the same issue and it's appearing on all of my sites.

**Comment by shoelaced** [comment]
Update - this is also happening with margin.

![image](https://user-images.githubusercontent.com/8772661/81471614-412c0480-91ea-11ea-9551-5b97d341ea5f.png)
👇
![image](https://user-images.githubusercontent.com/8772661/81471641-6b7dc200-91ea-11ea-82c3-6aa7c245fa09.png)

**Comment by shoelaced** [comment]
I don't have time to go through all of my sites and change the padding to a pixel value, so I'm reverting back to the previous version of Oxygen. I'll optimistically hope that this issue will be fixed soon, and also that future releases will be tested better, since things that break the fontend are high priority issues that I really don't want to have to constantly worry about dealing with on many sites.

**Comment by shoelaced** [comment]
Also just noticed that padding is not working in the Product Tabs block for WooCommerce either.

**Comment by shoelaced** [comment]
Okay so Pro Menu is completely a mess - in the dropdowns I tried resetting all the padding as a pixel value and now only the left padding is still in `em`s.

It also appears that you don't have the previous versions available for download on the website, so.......... this is going to be a long day.

**Comment by KittenCodes** [comment]
@shoelaced You can get v3.2.1 here: https://d.pr/f/yYQS5I.

**Comment by Spellhammer** [comment]
Bug confirmed. You'll need to regenerate your CSS cache under Oxygen > Settings > CSS Cache after reverting to 3.2.1 for the units to be corrected. @shoelaced

**Comment by shoelaced** [comment]
@Spellhammer Thanks, will do.

**Comment by yankiara** [comment]
Same for MOBILE pro menu, links padding, background position, everything is forced to px.
Needs a quick fix, please, menus in production! @Spellhammer

**Comment by shoelaced** [comment]
Also happening in the Product Images block.

**Comment by KittenCodes** [comment]
Fixed in v3.4.
