### ISSUE TITLE
Show the actual px when changing margins via the UI drag

### ISSUE THREAD

**Issue by petebytes** [soflyy/oxygen-bugs-and-features#113]
![image](https://user-images.githubusercontent.com/676739/53618524-eab84480-3ba8-11e9-84f0-7a24c6d7e75c.png)

**Comment by sbwp** [comment]
Check the bottom right on the screen. The value is displayed there!

**Comment by petebytes** [comment]
@sbwp Cool Thanks
Mine is actually covered by cookies warning :)

Still think it's better to place the value near what the user is looking at. But not that I know where to look not a biggie.
