### ISSUE TITLE
Oxygen does not work well with Siteground's SG Optimiser

### ISSUE THREAD

**Issue by OST-dev** [soflyy/oxygen-bugs-and-features#1134]
**Describe the bug**
*A clear and concise description of what the bug is.*

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
*Yes/No*

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
*If yes, provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*

**To Reproduce**

**Expected behavior**
*A clear and concise description of what you expected to happen.*

**What actually happens**
*A clear and concise description of what happens instead of the expected behavior.*

**Screenshots**
*If applicable, add screenshots to help explain your problem.*

**Desktop (please complete the following information):**
 - Oxygen Version [e.g. 2.2 Alpha]

**Smartphone (please complete the following information):**
 - Oxygen Version [e.g. 2.2 Alpha]

**Additional context**
*Add any other context about the problem here.*

**Comment by OST-dev** [comment]
Siteground's SG Optimiser WP plugin (installed automatically with every WP install) does not play well with OXY. - a recent auto-update on two separate sites on different SG accounts broke the visual rendering of sites. see below for SG support feedback relating to a work-around. Is this something OXY and SG can sort out? It would be nice to use all optimisation functionality. 

![oxysg](https://user-images.githubusercontent.com/61204061/81549954-76199200-9377-11ea-9c36-ff5c9ffa9f93.jpg)

**Comment by KittenCodes** [comment]
@OST-dev Minifying and combining files in any caching plugin can break Oxygen (and other WordPress plugins). There's further information here: https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/.
