### ISSUE TITLE
Mixed content - demo data

### ISSUE THREAD

**Issue by ms971** [soflyy/oxygen-bugs-and-features#1138]
**Describe the bug**
*A clear and concise description of what the bug is.*

I was following Louis' video on templating and as soon as I added demo content from Atomic header in Main template, the url changes to unsecure as it loads unsecure demo content. 

<img width="1062" alt="Oxygen Visual Editor - Main - Oxygen Sandbox 2020-05-11 10-05-51" src="https://user-images.githubusercontent.com/65174194/81570962-49617c80-936f-11ea-9880-0c84bfc302cb.png">
 

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
*Yes/No*
Yes
**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
*If yes, provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*
Sure can.
http://oxygen-qkbygrmw99d9k.oxygen-demo.qsandbox.me/?ct_template=main&ct_builder=true
appears as unsecured content.

**To Reproduce**

**Expected behavior**
*A clear and concise description of what you expected to happen.*

**What actually happens**
*A clear and concise description of what happens instead of the expected behavior.*

**Screenshots**
*If applicable, add screenshots to help explain your problem.*

**Desktop (please complete the following information):**
 - Oxygen Version [e.g. 2.2 Alpha]

**Smartphone (please complete the following information):**
 - Oxygen Version [e.g. 2.2 Alpha]

**Additional context**
*Add any other context about the problem here.*

**Comment by ms971** [comment]
Here is screen shot of the log entry
https://prnt.sc/sebedb

**Comment by ms971** [comment]
Added plugin. https://wordpress.org/plugins/ssl-insecure-content-fixer/

**Comment by ms971** [comment]
Enabling as attached still gives mixed content warning. 
Just respond and tell me if this is something I can fix or it's the unsecured source of the assets on your server.
<img width="717" alt="RSSSL settings ‹ oxysm art — WordPress 2020-05-11 20-20-58" src="https://user-images.githubusercontent.com/65174194/81624879-5ad57380-93c5-11ea-98a3-926e6175b49c.png">

**Comment by KittenCodes** [comment]
@ms971 You will need to replace the images from the design set with images loaded from your own server.

**Comment by ms971** [comment]
I did that, but it kind of defeats the utility of having premade pages if you have to replace the content.
