### ISSUE TITLE
Can't use functions from code snippets in the Oxygen Insert Data > PHP Function Return value

### ISSUE THREAD

**Issue by adrien-robert** [soflyy/oxygen-bugs-and-features#114]
**Describe the bug**
I have a code snippet which suppose to return the ACF subfield of an ACF group field
![52949247_10219006587419244_4059273479504003072_n](https://user-images.githubusercontent.com/4320990/53635448-74095e80-3c1d-11e9-8328-6f2c72d145ef.jpg)

But when in one of my reusable template I try to use this function with the name of my group field and the name of my subfield:
![52991289_10219006591459345_1147106617104269312_o](https://user-images.githubusercontent.com/4320990/53635462-81bee400-3c1d-11e9-9919-145415ff9c6d.jpg)

it display nothing:
![52631651_10219006601459595_6039592353189068800_n](https://user-images.githubusercontent.com/4320990/53635476-8daaa600-3c1d-11e9-8053-53971920706a.jpg)

When I put the function in a code block and I display the result of the function:
![52842307_10219006606819729_983307434997055488_n](https://user-images.githubusercontent.com/4320990/53635485-94391d80-3c1d-11e9-8120-58ce058013d7.jpg)

I get the text from the code block:
![53580512_10219006607819754_4416798368383107072_n](https://user-images.githubusercontent.com/4320990/53635490-9b602b80-3c1d-11e9-887d-ae02e6a43606.jpg)

Why? Is this something with Code Snippets or with Oxygen PHP Function Return value?

The thread where this issue was discuss: https://www.facebook.com/groups/1626639680763454/permalink/2121933594567391/

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
Yes

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
*If yes, provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*

Here is a sandbox install to showcase the issue: http://strange-sable.w6.wpsandbox.pro?upass=B1oxaPLV368d

Don't install any template just back to the admin panel if it ask.

You can see the homepage where I have the 2 fields.
The first which is using Oxygen PHP Return function value
And the second is just a code block with the function inside.

**Comment by adrien-robert** [comment]
Here is the all-in-one wp migration file of the sandbox install if needed: https://we.tl/t-mvA2eQyo0n

**Comment by Spellhammer** [comment]
You can use functions from Code Snippets in the PHP Function Return Value dynamic data option, but the function you're trying to use isn't working because if($field) is not evaluating as true when the parameters are passed via the insert data modal. I think it may be due to the name of the field. Please try using a different name with only letters and let me know what the result is.

**Comment by adrien-robert** [comment]
You mean renaming my function inside my code snippets to mydisplayacfsubfield instead of my_display_acf_subfield?

**Comment by adrien-robert** [comment]
I don't understanding, you mean remove the underscore from the field name?

Can you get the sandbox I used in this ticket and show me what you would do to make it work?

Here is the link to download the sandbox again (with All in one wp migration): https://we.tl/t-M8q0TGHHsa

**Comment by Spellhammer** [comment]
> I don't understanding, you mean remove the underscore from the field name?

Yes, please try that and let me know what the result is.
