### ISSUE TITLE
There is no native drop down features in the mobile responsive header builder. My mobile can not provide good UX this way. Please fix.

### ISSUE THREAD

**Issue by mupersan** [soflyy/oxygen-bugs-and-features#1140]
**Describe the feature you'd like to see included in Oxygen.**
*A clear, detailed description of the feature you're requesting.*
The menu feature in the header builder, when configuring the mobile responsive area, there is no feature for a drop down toggle for childed pages. It is either all pages in the menu vertically listed (which looks like crap if you have any sort of built out menu) or just the parent pages.

**What are the use cases for this feature?**
Better UX for your platform. I consider this a missing feature that is a necessity. I don't know how people do mobile responsive menus without this.

**Examples of this feature or functionality.**
Elementor has this, as does divi and beaver builder. You can choose how to design your dropdown toggles.

**Comment by KittenCodes** [comment]
Please use the Pro Menu element instead of the Menu element.
