### ISSUE TITLE
Can't edit text - Selects column over text area where I am clicking and you don't have an option in the left edit bar to edit text from there. 

### ISSUE THREAD

**Issue by mupersan** [soflyy/oxygen-bugs-and-features#1142]
**Describe the bug**
When I click to try and edit text that is in a column, it doesn't let me ever select and edit the text, it just selects the column the text is edited in. I can choose the right element in the sidebar, but I HAVE to click into the text to edit it (which seems like a major shortcoming)

**Have you tried all the steps at 
Yes

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
I don't know and frankly I don't have time to troubleshoot a thousand different steps. Your platform has too many bugs and we are about ready to move away from it and write about our negative experience with it. 

**To Reproduce**
1. Click on any text in any column

**Expected behavior**
Edit text

**What actually happens**
Selects the column

**Screenshots**
*If applicable, add screenshots to help explain your problem.*

**Desktop (please complete the following information):**
- OS: windows 10, latest chrome version

**Smartphone (please complete the following information):**
 - Oxygen Version [e.g. 2.2 Alpha]

**Additional context**
*Add any other context about the problem here.*

**Comment by KittenCodes** [comment]
@mupersan I suspect there is some CSS at play that is preventing you from being able to edit the element. If you'd like us to take a look, please send your site details to us in a support ticket: https://oxygenbuilder.com/support.
