### ISSUE TITLE
error 500 - I can`t edit template main_template, and the other template, I can`t create new template.

### ISSUE THREAD

**Issue by yericho07** [soflyy/oxygen-bugs-and-features#1143]
I have a error 500
I can`t edit template main_template, and the other template, I can`t create new template.
And the front end, the page with main_template don't show good. -> page Dormitorios", so, I use, change, in this page template empty.

The website is https://www.mueblestante.com

In my personal hosting assitant change version php and I can`t acces file error_lop beacuse the hosting is share. So I don't know to do more. 

So, I write in the comunity support oxygen.

I'm waiting answer. 

**Describe the bug**
*A clear and concise description of what the bug is.*

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
*Yes/No*

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
*If yes, provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*

**To Reproduce**

**Expected behavior**
*A clear and concise description of what you expected to happen.*

**What actually happens**
*A clear and concise description of what happens instead of the expected behavior.*

**Screenshots**
*If applicable, add screenshots to help explain your problem.*

**Desktop (please complete the following information):**
 - Oxygen Version [e.g. 2.2 Alpha]

**Smartphone (please complete the following information):**
 - Oxygen Version [e.g. 2.2 Alpha]

**Additional context**
*Add any other context about the problem here.*

**Comment by yericho07** [comment]
delete cache, new read shortcode, and new read css code,.. and read permant link.. and the finish unistall plugin and install plugins.. and nothing solution. version is the last 3.03. I think".  I can't create new template, and I can't edit. It's a problem important. In the hosting today modific a domain, and active, exist problem, cdn www. change. and them,,.. with this problem, change the php version 7.6 or mysql,.. I don't remember. And this problem was the past today. And I desactive all the plugins only active oxygen, and the problem live too. so I don't know more. Please hep me, and the oxygen oxygen to be secure and the more future.

**Comment by KittenCodes** [comment]
@yericho07 Please open a support ticket so that we can take a look at this for you: https://oxygenbuilder.com/support.
