### ISSUE TITLE
Design Set components preview not loading

### ISSUE THREAD

**Issue by gzah3053** [soflyy/oxygen-bugs-and-features#1144]
Some Design Sets are not working in preview. If i go to Design Sets and choose some parts like header it normally shows a preview of each header. But in some Design Sets they are not shown. Instead there is an empty field. If i click on the element it will be inserted. But the preview is in many casas not working. Especially in SAAS 2 the most components are not shown.
![oxygen_design-set-not-showing](https://user-images.githubusercontent.com/65247618/81728268-7a829f80-948a-11ea-9262-98faa9f037cb.png)

**Comment by gzah3053** [comment]
As you can see on the screenshot the last one is loaded. All other headers are witout preview.

**Comment by gzah3053** [comment]
![oxygen-no-screenshots-in-design-library](https://user-images.githubusercontent.com/65247618/81729470-4c9e5a80-948c-11ea-9298-a1fcb02ffbca.png)

**Comment by gzah3053** [comment]
Now i turned off everything (adblocker, pi hole) and as you can see on the second screenshot there is still the same problem. But now it looks a bit different with "no screenshot".

**Comment by KittenCodes** [comment]
@gzah3053 Unfortunately, some of our design set elements don't have screenshots.

**Comment by KittenCodes** [comment]
#45

**Comment by KittenCodes** [comment]
Most library items should now have screenshots.
