### ISSUE TITLE
I like to report this bug, please see my screenshot

### ISSUE THREAD

**Issue by githubtommyhauernl** [soflyy/oxygen-bugs-and-features#1148]
Hi There, 

I just started working with Oxygen, and i found this bug 
https://www.screencast.com/t/NPlfx8H3ys

For some reason this piece of data comes in my screen when i click on just one section inside my website. I tried to remove this section but i can't because its overlaying this the trash bin button.

Hope you can help me out here.

Kind regards, 
Tommy Hauer

**Comment by KittenCodes** [comment]
#1603
