### ISSUE TITLE
Oxygen Loading All Font Weights

### ISSUE THREAD

**Issue by sunnyt7** [soflyy/oxygen-bugs-and-features#115]
I'm not sure exactly what's causing it, but Oxygen 2.2 is loading all font-weights. It looks something like:

<link href="https://fonts.googleapis.com/css?family=Montserrat:700,regular,italic,500italic,|Lato:700,regular,italic,|Open+Sans:600,regular,|Open+Sans:100,200,300,400,500,600,700,800,900|Lato:100,200,300,400,500,600,700,800,900|Montserrat:100,200,300,400,500,600,700,800,900" rel="stylesheet"><title>Test - Sandbox</title>

It properly loads just the font weights I selected, but then loads all of them immediately after.

There is an example of it here:

http://motionless-locust.w5.wpsandbox.pro/
Login: http://motionless-locust.w5.wpsandbox.pro?upass=Cd2580ZLUciv

The weird thing is that it was working properly when I first set the page up, but then had the issue after I copy/pasted the page shortcode from my personal site.

**Comment by Deanphillips** [comment]
Having this problem too

https://www.useloom.com/share/71ef80e7ef604c749c99d05d146ac6d9

**Comment by KittenCodes** [comment]
@sunnyt7 Unfortunately, I haven't been able to replicate this. Please can you let me know if you can still replicate it in the latest version of Oxygen (currently 2.3).
