### ISSUE TITLE
Missing styles after setting display none

### ISSUE THREAD

**Issue by druphero** [soflyy/oxygen-bugs-and-features#1150]
Hello,
I have found that if you set Layout/Display none to some element of the page (section, div or some predesined secton or elements it loses it's styles. Don't need to save, just set display to none and right after that - to block, it loses the styles.

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
*Yes/No*

YES

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
*If yes, provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*

Ies, I am able: https://oxygen-qx4t355w67f9k.oxygen-demo.qsandbox.me/

This is the second block - testimonials one column.

**To Reproduce**

**Desktop (please complete the following information):**
 - Oxygen Version [e.g. 2.2 Alpha]

OS: Windows 8.1
Browser: Firefox
Oxygen version: 3.3 and 3.3.1 RC1

**Comment by Spellhammer** [comment]
Unable to replicate. Please provide steps or a screencast showing how to make this happen and we'll investigate further.

**Comment by druphero** [comment]
![oxy_display_none_bug_1](https://user-images.githubusercontent.com/63197079/81893763-f5e16f80-95b6-11ea-8b13-6e7a610a8baf.jpg)
![oxy_display_none_bug_2](https://user-images.githubusercontent.com/63197079/81893767-f7129c80-95b6-11ea-9860-5d82b0708733.jpg)
![oxy_display_none_bug_3](https://user-images.githubusercontent.com/63197079/81893768-f7ab3300-95b6-11ea-995b-31da004d2f85.jpg)

**Comment by druphero** [comment]
Sorry, now I have seen that flex-direction has changed to default - row. I have changed to column and the block is now correct.
