### ISSUE TITLE
Undo / protocol

### ISSUE THREAD

**Issue by gzah3053** [soflyy/oxygen-bugs-and-features#1152]
a protocol like in Photoshop would be super helpful. Every step, every change is listed and can be undone at any time with one click. I know you have already implemented some kind of versioning. Sometimes it saves a version and sometimes it doesn't. It is also a bit cumbersome if I always have to load the page or preview first to see if I have loaded the right version.
A protocol directly in oxygentab would be great. Currently there is not even a return unless you have deleted an object. At least a back should be available in a first step in all operations.

**Comment by KittenCodes** [comment]
#12

**Comment by Spellhammer** [comment]
Closing as a duplicate. Please add your vote to https://github.com/soflyy/oxygen-bugs-and-features/issues/12
