### ISSUE TITLE
AngularJS: the $injector:modulerr error?

### ISSUE THREAD

**Issue by FrenchDesign** [soflyy/oxygen-bugs-and-features#1153]
This error is very blocking, it prevents other plug-ins from working. 

**Please fix it as soon as possible.**

**Error :**

jquery.min.js:2 Uncaught Error: [$injector:modulerr] Failed to instantiate module CTFrontendBuilderUI due to:
Error: [$injector:nomod] Module 'CTFrontendBuilderUI' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.

https://errors.angularjs.org/1.6.10/$injector/modulerr?p0=CTFrontendBuilderUI&p1=Error%3A%20%5B%24injector%3Anomod%5D%20Module%20'CTFrontendBuilderUI'%20is%20not%20available!%20You%20either%20misspelled%20the%20module%20name%20or%20forgot%20to%20load%20it.%20If%20registering%20a%20module%20ensure%20that%20you%20specify%20the%20dependencies%20as%20the%20second%20argument.%0Ahttps%3A%2F%2Ferrors.angularjs.org%2F1.6.10%2F%24injector%2Fnomod%3Fp0%3DCTFrontendBuilderUI%0A%20%20%20%20at%20chrome-extension%3A%2F%2Fmgacnbmocekcfjbdfpdnbnjfhaomffhk%2Fapp%2Fbower_components%2Fangular%2Fangular.js%3A125%3A12%0A%20%20%20%20at%20chrome-extension%3A%2F%2Fmgacnbmocekcfjbdfpdnbnjfhaomffhk%2Fapp%2Fbower_components%2Fangular%2Fangular.js%3A2313%3A17%0A%20%20%20%20at%20ensure%20(chrome-extension%3A%2F%2Fmgacnbmocekcfjbdfpdnbnjfhaomffhk%2Fapp%2Fbower_components%2Fangular%2Fangular.js%3A2234%3A38)%0A%20%20%20%20at%20module%20(chrome-extension%3A%2F%2Fmgacnbmocekcfjbdfpdnbnjfhaomffhk%2Fapp%2Fbower_components%2Fangular%2Fangular.js%3A2311%3A14)%0A%20%20%20%20at%20chrome-extension%3A%2F%2Fmgacnbmocekcfjbdfpdnbnjfhaomffhk%2Fapp%2Fbower_components%2Fangular%2Fangular.js%3A5010%3A22%0A%20%20%20%20at%20forEach%20(chrome-extension%3A%2F%2Fmgacnbmocekcfjbdfpdnbnjfhaomffhk%2Fapp%2Fbower_components%2Fangular%2Fangular.js%3A418%3A20)%0A%20%20%20%20at%20loadModules%20(chrome-extension%3A%2F%2Fmgacnbmocekcfjbdfpdnbnjfhaomffhk%2Fapp%2Fbower_components%2Fangular%2Fangular.js%3A4994%3A5)%0A%20%20%20%20at%20createInjector%20(chrome-extension%3A%2F%2Fmgacnbmocekcfjbdfpdnbnjfhaomffhk%2Fapp%2Fbower_components%2Fangular%2Fangular.js%3A4911%3A19)%0A%20%20%20%20at%20doBootstrap%20(chrome-extension%3A%2F%2Fmgacnbmocekcfjbdfpdnbnjfhaomffhk%2Fapp%2Fbower_components%2Fangular%2Fangular.js%3A1965%3A20)%0A%20%20%20%20at%20bootstrap%20(chrome-extension%3A%2F%2Fmgacnbmocekcfjbdfpdnbnjfhaomffhk%2Fapp%2Fbower_components%2Fangular%2Fangular.js%3A1986%3A12)
    at angular.js:125
    at angular.js:5034
    at forEach (angular.js:418)
    at loadModules (angular.js:4994)
    at createInjector (angular.js:4911)
    at doBootstrap (angular.js:1965)
    at bootstrap (angular.js:1986)
    at angularInit (angular.js:1871)
    at HTMLDocument.<anonymous> (angular.js:34875)
    at l (jquery.min.js:2)

**Comment by KittenCodes** [comment]
@FrenchDesign I suspect this is caused by conflict with another plugin on your site, most likely a caching plugin. Please try disabling all plugins (aside from Oxygen) and see if the issue persists. If that fixes it, you can re-enable the plugins one-by-one until you find the cause.

If that doesn't help, please open a support ticket so that we can take a look: https://oxygenbuilder.com/support.
