### ISSUE TITLE
Error occurred while rendering the component

### ISSUE THREAD

**Issue by livia-rgstudio** [soflyy/oxygen-bugs-and-features#1154]
**Describe the bug**
*A clear and concise description of what the bug is.*
I have an error message when I try to edit a template: Error occurred while rendering the component.
If I try to save it here is what I get: Error occurred while saving
In the logs I see this error message: PHP Warning:  Invalid argument supplied for foreach() in /web/wp-content/plugins/oxygen/component-framework/components/css-util.class.php on line 100

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
*Yes/No*
Yes

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
*If yes, provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*

**To Reproduce**

**Expected behavior**
*A clear and concise description of what you expected to happen.*

**What actually happens**
*A clear and concise description of what happens instead of the expected behavior.*

**Screenshots**
*If applicable, add screenshots to help explain your problem.*

**Desktop (please complete the following information):**
 - Oxygen Version [e.g. 2.2 Alpha]

**Smartphone (please complete the following information):**
 - Oxygen Version [e.g. 2.2 Alpha]

**Additional context**
*Add any other context about the problem here.*

**Comment by KittenCodes** [comment]
@livia-rgstudio Please open a support ticket so that we can take a look at your site: https://oxygenbuilder.com/support.
