### ISSUE TITLE
Additional body margin-top: 2121px 

### ISSUE THREAD

**Issue by eZweblogic** [soflyy/oxygen-bugs-and-features#1155]
**Describe the bug**
*A style snippet in editor adding exactly 2121px to the top of body element.
here is the HTML `<body class="rtl page-template-default page page-id-52341 page-parent logged-in ct_inner plg-peepso oxygen-builder-body ng-scope wutb_frontend wutb_framed" ng-controller="BuilderController" data-aos-easing="ease" data-aos-duration="400" data-aos-delay="0" style="margin-top: 2121px;">`*

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
*No*

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
*If yes, provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*

**To Reproduce**
1. try to edit any web page with Oxygen

**Expected behavior**
*I expected a header and a footer with inner content block without 2121px top margin
<img width="1992" alt="Screen Shot 2020-05-14 at 4 00 15 PM" src="https://user-images.githubusercontent.com/6707978/81938760-0ff27080-95fe-11ea-84a2-80d0df8e6351.png">
<img width="2559" alt="Screen Shot 2020-05-14 at 4 13 06 PM" src="https://user-images.githubusercontent.com/6707978/81938778-12ed6100-95fe-11ea-97d0-6b67bf503a7c.png">
<img width="2559" alt="Screen Shot 2020-05-14 at 4 14 15 PM" src="https://user-images.githubusercontent.com/6707978/81938781-14b72480-95fe-11ea-960f-e1d598a0c11c.png">

*

**What actually happens**
*A clear and concise description of what happens instead of the expected behavior.*

**Screenshots**
*If applicable, add screenshots to help explain your problem.*

**Desktop (please complete the following information):**
- OS: [Mac OS X Catalina]
 - Browser [safari]
 - Oxygen Version [3.3]

**Smartphone (please complete the following information):**
 - Oxygen Version [e.g. 2.2 Alpha]

**Additional context**
*Add any other context about the problem here.*

**Comment by KittenCodes** [comment]
@eZweblogic Please open a support ticket so that we can find what is causing this: https://oxygenbuilder.com/support.
