### ISSUE TITLE
Single Shop (archive) template invoked for multiple product categories 

### ISSUE THREAD

**Issue by Pantoeflou** [soflyy/oxygen-bugs-and-features#1156]
Hi Guys,

I have been going through your videos, and it would seems that we need to create a template for each product category? Is that right?

I would like to create a single product archive template, and then create multiple pages where each page just shows the products in an a single category while using the same template

Is this already possible, or is this in the making?

**Comment by KittenCodes** [comment]
@Pantoeflou This is already possible. You need to create a template and apply it to Archive > Taxonomies > All Product Categories. If you then add a Products List element to the template and use the Default query, the correct products will be shown when the category is viewed.

You don't need to create pages for the categories - you should be able to use the default category URL.
