### ISSUE TITLE
Compatibility to translate Templates and Re-usable parts with WPML

### ISSUE THREAD

**Issue by knut-studio** [soflyy/oxygen-bugs-and-features#1157]
**Describe the feature you'd like to see included in Oxygen.**
*A clear, detailed description of the feature you're requesting.*

It would be really useful for multilingual sites that WPML and Oxygen were fully compatible. Now it's possible to translate Pages, but there are many problems when translating Templates and Re-usable parts, as well as code blocks and any custom element.

**What are the use cases for this feature?**
*e.g. Accessibility, e-commerce store that sells bicycles, etc.*

Any website that would like to have more than one language.

**Examples of this feature or functionality.**
*If another product has done it well, provide examples here.*

Many Wordpress Builders are compatible with WPML, as well as many templates. Making a multilingual website with Divi, for example, and WMPL is pretty easy.

Thank you!!

**Comment by Netzlichter** [comment]
Is a must have!

**Comment by out-of-order** [comment]
https://github.com/soflyy/oxygen-bugs-and-features/issues/938#issuecomment-719508598
