### ISSUE TITLE
Disable "Edit Locking"

### ISSUE THREAD

**Issue by jammerinbc** [soflyy/oxygen-bugs-and-features#1158]
"Edit Locking" is severely limiting for our team.
I would like to be able to Turn it Off or on completely at will.
We work together in an office on sites together
We need to be able to work on 2 different pages at the same time.

**Comment by Spellhammer** [comment]
You can click the "open anyway" link and still work on two pages at the same time. Be aware that working with Oxygen in this way can and most likely will result in lost global styles, settings, or classes.

**Comment by YammYcoding** [comment]
That's why we ask to not have edit lock anymore, maybe you guys could make a way to sync these styles, settings and classes in a third temporary file, and maybe ask us which one to keep when there is a conflict, and then, the edit lock would not be needed anymore ;)
