### ISSUE TITLE
Cannot edit Oxygen Template - Notice: Undefined index: button_priority */oxygen.element.class.php on line 37

### ISSUE THREAD

**Issue by jshacklette63** [soflyy/oxygen-bugs-and-features#1159]
**Describe the bug**
When trying to edit oxygen templates by clicking "edit" for the template I want to edit, I only get a blank white page.  I checked the network response and it was a 500 http error.  I enabled logging within wordpress and received the below error.

Notice: Undefined index: button_priority in /home/ti2mwr1jxocp/public_html/owp/wp-content/plugins/oxygen/component-framework/api/oxygen.element.class.php on line 37

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
Yes

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
I have tried migrating the site to another fresh install of wordpress and encounter the same issue.  The links are below to both the original and secondary site I setup today to test.  The original site is not showing any issues on the front of the site, only when I try to edit templates or pages with Oxygen Builder.  The secondary site is not showing the header and footer of the site as that is one of the templates that I cannot access.  I seems to not have transitioned well during the migration.

Original - www.droptship.com/owp
Secondary - www.droptship.com/owpmig

**To Reproduce**
1. From the wordpress dashboard, hover over Oxygen in the left nav and select templates.
2. Click the Edit link on any of the templates available in the list
3. Receive blank page and a 500 http error in network tab of the browser debugging tools.

**Expected behavior**
I expect to be directed to the wordpress template page where I can then select to open the Oxygen Editor to modify the templates.

**What actually happens**
I receive a blank white page and 500 http error

**Screenshots**
*If applicable, add screenshots to help explain your problem.*

**Desktop (please complete the following information):**
- OS: Windows 10
 - Mozilla, Chrome, Edge
 - Oxygen Version 3.2 and 3.3 - I upgraded after it happened the first few times to see if that would help but received the same outcome.

**Smartphone (please complete the following information):**
N/A

**Additional context**
This started to happen when nothing appeared to change.  I do not have auto updates on and did not perform any updates prior to this happening.

**Comment by KittenCodes** [comment]
@jshacklette63 I suspect the 500 error is caused by your site running out of memory. Please contact your web host and ask them to check the server error logs.
