### ISSUE TITLE
sizeof typo in ajax.php prevents design library import process from completing (if PHP errors are enabled)

### ISSUE THREAD

**Issue by rscs** [soflyy/oxygen-bugs-and-features#116]
I am seeing a PHP warning when loading a design library, which causes the AJAX request to fail and the design library import process to stop at the "Templates" step.

**Warning:  sizeof(): Parameter must be an array or an object that implements Countable in /var/www/html/XXX/wordpress/wp-content/plugins/oxygen/component-framework/includes/ajax.php on line 2530**

It looks like `sizeof($ct_source_color_map > 0)` should be changed to `sizeof($ct_source_color_map) > 0`.  This fixed it for me.

I am running the public release of v2.2 and PHP v7.2.13.

**Comment by Spellhammer** [comment]
This error is specific to PHP 7.2+. You can roll back to 7.1 for now in order to import the new design sets.

Fixed at soflyy/oxygen#1623 for upcoming release.

**Comment by KittenCodes** [comment]
This is fixed in the latest version of Oxygen.
