### ISSUE TITLE
Gutenberg Styling

### ISSUE THREAD

**Issue by OutOfBreath** [soflyy/oxygen-bugs-and-features#1161]
**Describe the feature you'd like to see included in Oxygen.**
*A clear, detailed description of the feature you're requesting.*

**What are the use cases for this feature?**
*e.g. Accessibility, e-commerce store that sells bicycles, etc.*

**Examples of this feature or functionality.**
*If another product has done it well, provide examples here.*

**Comment by KittenCodes** [comment]
Closing because there is no information.
