### ISSUE TITLE
Google Font - Comfortaa - set in global settings but does not change font.

### ISSUE THREAD

**Issue by andycaps** [soflyy/oxygen-bugs-and-features#1163]
**Describe the bug**
*A clear and concise description of what the bug is.*

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
*Yes/No* Yes

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
*If yes, provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.* NO

**To Reproduce**

**Expected behavior**
*A clear and concise description of what you expected to happen.*
When font is selected to Google Comfortaa I expect my fonts within my page when selected to change to this font.

**What actually happens**
*A clear and concise description of what happens instead of the expected behavior.*
Nothing!!!  it remains the same font as selected, for example - if I have the default setting and I want to change to the Comfortaa, nothing happens when I select it from the left menu

**Screenshots**
*If applicable, add screenshots to help explain your problem.*
**Setting up in the Global Settings:**
<img width="366" alt="Global Set Up" src="https://user-images.githubusercontent.com/10528963/82026215-5beaf700-968a-11ea-85b5-1e9d8d75c1d9.png">

**Selecting the font in the left menu:**
<img width="743" alt="Selecting my font in the left menu" src="https://user-images.githubusercontent.com/10528963/82026359-8e94ef80-968a-11ea-8eec-73d9f71aaf6c.png">

**Font does not change - I am expecting this font:**
<img width="689" alt="Screenshot 2020-05-15 at 09 01 46" src="https://user-images.githubusercontent.com/10528963/82026522-c2701500-968a-11ea-80a9-2794ca52aa49.png">

**Desktop (please complete the following information):**
- OS: [e.g. iOS] **CATALINA - 10.15.4**
 - Browser [e.g. chrome, safari] **SAFARI**
 - Oxygen Version [e.g. 2.2 Alpha] **3.3**

**Smartphone (please complete the following information):**
 - Oxygen Version [e.g. 2.2 Alpha]

**Additional context**
*Add any other context about the problem here.*
I did not notice any issues with fonts prior to 3.3 update - ?

**Comment by KittenCodes** [comment]
@andycaps Please open a support ticket so that we can take a look at your site: https://oxygenbuilder.com/support.
