### ISSUE TITLE
All menus open when editing a page

### ISSUE THREAD

**Issue by alFrame** [soflyy/oxygen-bugs-and-features#1167]
**Describe the bug**
When I edit a page all menus (inclusive drop down) are open distracting the editing area...

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
Yes

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
*If yes, provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*
No I did not take the time yet to recreate the error...

**Expected behavior**
All menus should be closed (rolled up) so the page can be edited.

**What actually happens**
I load the page in the editor and it looks like the following screenshot.

**Screenshots**
*If applicable, add screenshots to help explain your problem.*
![image](https://user-images.githubusercontent.com/27587287/82154366-a082b800-986d-11ea-981e-ec0cb4ff9a8c.png)

**Desktop (please complete the following information):**
- OS: Windows
 - Browser Firefox
 - Oxygen Version 3.3

**Comment by KittenCodes** [comment]
@alFrame I suspect this is caused by a conflict with another plugin on your site. Please run a conflict test: https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/.

If that doesn't help, please open a support ticket so that we can take a look: https://oxygenbuilder.com/support.

**Comment by alFrame** [comment]
@KittenCodes thank you! I did do the "disable plugins, rebuild CSS and resigning sing and dance". Didn't help. I will open a support ticket.
