### ISSUE TITLE
Visual grid builder

### ISSUE THREAD

**Issue by golokios** [soflyy/oxygen-bugs-and-features#1170]
**Describe the feature you'd like to see included in Oxygen.**
*A clear, detailed description of the feature you're requesting.*
I think a visual grid builder for oxygen would be really amazing. Right now WE can only use grid with microthemer or custom CSS. But a nice Integration Like the one webflow ist Using would be amazing and would Bring oxygen to a whole new level of Design posibilitys.

**What are the use cases for this feature?**
*e.g. Accessibility, e-commerce store that sells bicycles, etc.*
Creating amazing or otherwise difficult Designs. CSS grid is the future and if oxygen would be the first Wordpress pagebuilder to use it would be amazing.

**Examples of this feature or functionality.**
*If another product has done it well, provide examples here.*
The best example by far would be webflow.
And i think themecos x-pro theme hast integrated it recently

Sorry for the bad english, i am from Germany and auto correction on my Phone is Killing me😣

**Comment by KittenCodes** [comment]
Duplicate:

#524 
#118
