### ISSUE TITLE
Menu error

### ISSUE THREAD

**Issue by larsjnielsen09** [soflyy/oxygen-bugs-and-features#1171]
Hi, i have the Oxygen v. 3.3 and using Pro menu, and suddenly the menu is behaving badly.
The menu, randomly, dissapears to the left, when clicking on a menu item.
https://denlillekeramikskole.dk
I can force it to happen, by clearing the browsing data.

[menu_error-denlillekeramikskole.dk.zip](https://github.com/soflyy/oxygen-bugs-and-features/files/4649204/menu_error-denlillekeramikskole.dk.zip)

see attached zip/video

Best regards
Lars Nielsen
lars@noernielsen.dk

**Comment by KittenCodes** [comment]
@larsjnielsen09 Please open a support ticket so that we can take a look at this for you: https://oxygenbuilder.com/support.
