### ISSUE TITLE
Oxygen is loading all menu items expanded

### ISSUE THREAD

**Issue by thejoel12** [soflyy/oxygen-bugs-and-features#1172]
**Describe the bug**
Oxygen is loading all menu/submenus expanded

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
n/a

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
*If yes, provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*

**To Reproduce**
1. Go to https://staging.newmouth.com/test-menu/

**Expected behavior**
It shouldn't be showing these menus when started, only on hoverover.

**What actually happens**
*A clear and concise description of what happens instead of the expected behavior.*

**Screenshots**
<img width="753" alt="Screen Shot 2020-05-19 at 3 24 24 PM" src="https://user-images.githubusercontent.com/36237806/82374602-e615c100-99e4-11ea-9b24-bea9fca7a625.png">

**Desktop (please complete the following information):**
All OSes and browsers. 

**Smartphone (please complete the following information):**
 - Oxygen Version [e.g. 2.2 Alpha]

**Additional context**
*Add any other context about the problem here.*

**Comment by KittenCodes** [comment]
@thejoel12 Please open a support ticket so that we can take a look at your site: https://oxygenbuilder.com/support.
