### ISSUE TITLE
Slider Helper : "All slides stretch to same height"  does nothing to the slider

### ISSUE THREAD

**Issue by jamescrabb** [soflyy/oxygen-bugs-and-features#1174]
"All slides stretch to same height"

This feature doesn't take effect on the slider, Have to use a set height for the slides instead atm.

**Comment by jamescrabb** [comment]
<img width="2553" alt="Screenshot 2020-05-20 at 13 31 15" src="https://user-images.githubusercontent.com/53167342/82446259-39981580-9a9e-11ea-9a6e-3df1534ea6c1.png">


Visit https://10.corstotest.co.uk to view slider live and the effect not being applied to the Slides

**Comment by Spellhammer** [comment]
This should be fixed in the forthcoming 4.6 Beta 1.
