### ISSUE TITLE
Too slow with the "Oxygen Elements for WooCommerce" plugin activated

### ISSUE THREAD

**Issue by AlfaDelta** [soflyy/oxygen-bugs-and-features#1175]
Sorry that I do not follow the Bug Report template. No time for that. I hope this is fixed soon ;-)

I have a problem with Oxygen loading times. When I click on [Edit with Oxygen] I usually have to wait 8 seconds (somehow already a long time). This on a subdomain of a reasonably fast hosting. 

But with Oxygen and the "Oxygen Elements for WooCommerce" plugin activated, the time increase from 8 sec to 20 seconds! Even for an almost empty About page with only one textarea, it takes +/- 20 seconds. :-( 

To give an indication of the hosting:

In another subdomain on the same server, I have Divi with up to 7 seconds loading time for pages with even more content. 

With Enfold also in a subdomain my waiting takes no more than 2 seconds.

What can I look at to improve Oxygen + WooCommerce?

I posted this in Official Oxygen User Group where others has the same experience. 
https://www.facebook.com/groups/1626639680763454/

**Comment by louisreingold** [comment]
"Sorry that I do not follow the Bug Report template. No time for that."

lol.
