### ISSUE TITLE
Comment form and comment list aren't working

### ISSUE THREAD

**Issue by Cenay** [soflyy/oxygen-bugs-and-features#1177]
**Describe the bug**
*A clear and concise description of what the bug is.*
Adding a comment list and comment form "works", but nothing is displayed. 

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
*Yes/No*
Yes and a few others. 

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
*If yes, provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*

https://oxygen-qvl9habgntk9k.oxygen-demo.qsandbox.me/wp-admin/

**To Reproduce**
1. Open page with Edit with Oxygen
2. Insert new section, new div inside section
3. Inside new div, add both comment list and comment form
4. Save and view on front end. 

**Expected behavior**
*A clear and concise description of what you expected to happen.*

If no comments present, expect to just see the comment form. If comments are present on the page or post, would expect to see both the list and form. 

**What actually happens**
*A clear and concise description of what happens instead of the expected behavior.*

No comment list or comment form are present on screen. However, this is in the HTML of the page source: 
`<section id="section-80-40" class=" ct-section">
    <div class="ct-section-inner-wrap">
        <div id="div_block-81-40" class="ct-div-block">
            <div id="_comment_form-82-40" class="oxy-comment-form">
            </div>
            <div id="_comments-83-40" class="oxy-comments">
            </div>
        </div>
    </div>
</section>`

**Screenshots**
*If applicable, add screenshots to help explain your problem.*

Screen shot of the new section added showing my text (added after the second video to make it more obvious)
https://www.screencast.com/t/Cj7EGWgNV6

**Desktop (please complete the following information):**
- OS: [e.g. iOS] Windows 10 Pro 64 bit
 - Browser [e.g. chrome, safari] Developers Edition FireFox, Chrome and Normal FireFox.
 - Oxygen Version [e.g. 2.2 Alpha] 

**Smartphone (please complete the following information):**
 - Oxygen Version [e.g. 2.2 Alpha] 3.3

**Additional context**
*Add any other context about the problem here.*

Recorded two small videos of the effort and results. 
https://www.screencast.com/t/CfDWDZozUrS6
https://www.screencast.com/t/FA9Actwa

**Comment by KittenCodes** [comment]
This seems to be a WordPress issue. Comments have been enabled for pages, but WordPress is showing that comments are closed, even when Oxygen is disabled. You can see that here: https://oxygen-qslkmprgrhl9k.oxygen-demo.qsandbox.me/about-me/.
