### ISSUE TITLE
DONE: CSS-grid layout system

### ISSUE THREAD

**Issue by ziogio98** [soflyy/oxygen-bugs-and-features#118]
**Describe the feature you'd like to see included in Oxygen.**
CSS grids will allow oxy-users to have the newest layout engine released directly inside oxygen. It's clearly already possible to use css-grid by coding, but it would be very useful to have an integrated css-grid layout system.

**What are the use cases for this feature?**
CSS grids are useful in a minimalistic world, where shapes are king and queens of designs. Placing shapes with text and creating advanced 2-levels design is pretty annoying with position:absolute, flex, negative margins, ecc. 

This is totally not urgent, but CSS grids would be useful to achieve complex designs in a shorter timeframe.

**Examples of this feature or functionality.**
Webflow implemented CSS grids perfectly. Their CSS-layout system is almost magical to use, because it feels like those shitty drag n drop builders, but it's actually using modern-web standards (not fixed width like those shitty builders).

**Comment by expionage** [comment]
👍

**Comment by CameronGilroy** [comment]
👍🏻

**Comment by Deanphillips** [comment]
https://www.youtube.com/watch?v=ZXr5XR7XOjo&list=PLNHKFtMjaNvHQ55HQE3Am_iIWCc7sSsYt

Pinegrow do this so well. The panel is super handy too (for responsive design)
<img width="575" alt="Screenshot 2019-07-07 at 03 42 56" src="https://user-images.githubusercontent.com/21025321/60763303-5fc0ec80-a069-11e9-8448-f37d718a18a3.png">

**Comment by muzaffarsiddiqui** [comment]
+1

**Comment by alpabuz** [comment]
+1

**Comment by Deanphillips** [comment]
The more I use Webflow's grid, the more I really wish we had it. I know this isn't done because O2 don't want it, from comments I've seen, I don't think it's possible in O2 anytime soon. Counting down the days till it is though.

**Comment by Oxymaniac** [comment]
Really needed!

**Comment by wpdevlab** [comment]
👍 +1

**Comment by etcaetera** [comment]
Please make this happen <3

**Comment by alriksson** [comment]
Theme.co recently added this to their theme and builder: https://theme.co/changelog/ tried it out and works pretty good.

**Comment by alriksson** [comment]
Would be great to have integrated natively in oxygen, +1.

**Comment by Deanphillips** [comment]
Themeco + MT have nailed this. Makes me feel we'll get it one day in O2.

**Comment by willyarisky** [comment]
http://shoelace.io/ UI inspiration for Grid layout

**Comment by etcaetera** [comment]
> https://www.youtube.com/watch?v=ZXr5XR7XOjo&list=PLNHKFtMjaNvHQ55HQE3Am_iIWCc7sSsYt
> 
> Pinegrow do this so well. The panel is super handy too (for responsive design)
> <img alt="Screenshot 2019-07-07 at 03 42 56" width="575" src="https://user-images.githubusercontent.com/21025321/60763303-5fc0ec80-a069-11e9-8448-f37d718a18a3.png">

Love Pinegrow :)

**Comment by Deanphillips** [comment]
> > https://www.youtube.com/watch?v=ZXr5XR7XOjo&list=PLNHKFtMjaNvHQ55HQE3Am_iIWCc7sSsYt
> > Pinegrow do this so well. The panel is super handy too (for responsive design)
> > <img alt="Screenshot 2019-07-07 at 03 42 56" width="575" src="https://user-images.githubusercontent.com/21025321/60763303-5fc0ec80-a069-11e9-8448-f37d718a18a3.png">
> 
> Love Pinegrow :)

Microthemers way is similar to this, but I think MT's is better done. Add Themecos (same webflow's) style of dragging on the canvas too and it'll be a gamechanger imo. I also love how MT includes smart minmax templates.

**Comment by joejoerson** [comment]
+1

**Comment by HeruLutalo** [comment]
+1

**Comment by alanzirpoli** [comment]
+1

**Comment by Jimmyg128** [comment]
+1

**Comment by kokohcokisiregar** [comment]
+1

**Comment by willopez** [comment]
+1

**Comment by UrbanFugitive** [comment]
+1 - would definitely like to see this put in place. I nearly always design first using a grid format. would be great to build in a corresponding way.

**Comment by Netzlichter** [comment]
+1 :).

**Comment by bauhaus-Design** [comment]
That would be super practical. We already use CSS Grid wherever possible. Native support would be great anyway and would save us external tools.

**Comment by Cerulis** [comment]
+1

**Comment by ms971** [comment]
I use Sarah Drasner's [https://cssgrid-generator.netlify.app/](url)
but it would be nice inside Oxygen, but not a priority.

**Comment by numanzahid** [comment]
+1
CSS Grid is demand of time now.

**Comment by Spellhammer** [comment]
CSS grid added in 3.7 alpha 1.
