### ISSUE TITLE
DONE: The possibility of not specifying a unit for a property

### ISSUE THREAD

**Issue by FrenchDesign** [soflyy/oxygen-bugs-and-features#1181]
Hi,

Oxy Agency Tools for Oxygen is a really well thought out tool, unfortunately we can't use it at full power because of Oxygen.

Example 

Some properties like this: length. Requires a unit to be specified. 
Usually the pixel (px) is used by default.

In some cases, we would like to be able to have no unit, which would be really great to put variables in.

Here is an example (oxygen 3.3) :

If I enter the value 10 in the width property of an element, Oxygen generates with the default unit, width: 10px;

If I enter the value var(var(--logo-size)) in the width property of an element, Oxygen generates width: var(--logo-size);px 

This causes an error in the CSS and does not work. It should be possible to insert a value without a unit. That would be really great and would open up a lot of possibilities.

Thank you.

**Comment by wkoehn** [comment]
Thanks for submitting this! I did a little bit of digging around in Oxygen code yesterday and found a function 'measure_type_select() in toolbar.class.php. It's fairly simple to add a new unit for 'var', and it shows up in the editor and is output in the CSS. However, I was unable to find exactly where the CSS is actually generated for this to add a check to enable the 'var' setting to be unitless? If someone has an idea of how to implement this from a 3rd party plugin I'd love to hear more about it.

**Comment by KittenCodes** [comment]
Implemented in v3.6.
