### ISSUE TITLE
Woocommerce description & elements not showing on front end

### ISSUE THREAD

**Issue by mupersan** [soflyy/oxygen-bugs-and-features#1182]
**Describe the bug**
Building out multiple pages. 

**Have you tried all the steps at /
Yes

**Expected behavior**
Woocommerce elements show on the front end when using the product builder. Only the title shows, not the other information.

**What actually happens**
Only the title shows

**Desktop (please complete the following information):**
- Windows & Mac
 - Chrome & Brave
 - Oxygen Version - latest update

**Additional context**
Several other bugs, had to re-sign short codes several time and were getting errors.

**Comment by KittenCodes** [comment]
@mupersan Please open a support ticket so that we can take a look at your site: https://oxygenbuilder.com/support.

**Comment by mupersan** [comment]
<img width="539" alt="Screen Shot 2020-05-22 at 10 54 06 AM" src="https://user-images.githubusercontent.com/49402303/82685907-915b8b80-9c1a-11ea-94ee-d0d929808642.png">

**Comment by mupersan** [comment]
This is the response I get when trying to use your support form on your site.

**Comment by KittenCodes** [comment]
@mupersan 

Please select "Something's broken and I need help".
