### ISSUE TITLE
Update Failed: Download failed. Unauthorized

### ISSUE THREAD

**Issue by sparklefun** [soflyy/oxygen-bugs-and-features#1183]
I have a couple of sites where I have installed Oxygen Builder. When I go to update the plugin, I am routinely getting this error message: 

Update Failed: Download failed. Unauthorized. 

If I deactivate and delete the plugin and manually upload the new one things are working fine. 

In using a service (such as managewp or sync@ ithemes) to process my sites for updates, they all appear to fail with this same error. 

I have confirmed the License entered is correct as it validates with the updated plugin. 

I have used this plugin on 3 different providers (godaddy, flywheel, and siteground). The update appears to work at siteground without issue. 

Flywheel has been helpful in attempting to resolve the issue, by looking through their logs and validating the plugin. But their logs are not reflecting any requests that error for grabbing the update link. They did have one success which was resetting permissions on the server and then reprocessing the update. But doing this doesn't resolve it long term. Manually having to reset permissions on all servers, for all sites doesn't inherently make it efficient. 

Any recommendations (other than moving my sites all to siteground)?

Thank you for any assistance or recommendations you can provide.

**Comment by KittenCodes** [comment]
@sparklefun Please open a support ticket so that we can take a look at this for you: https://oxygenbuilder.com/support.
