### ISSUE TITLE
Unable to search-replace URLs when switching environment

### ISSUE THREAD

**Issue by mickaelperrin** [soflyy/oxygen-bugs-and-features#1184]
**Describe the bug**
WordPress stores absolute URLs in content. When moving from development to production, we used to use `wp search-replace` to change local domains with production ones.

Oxygen stores URL base64 encoded and prevent search-replace from working.

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
*Yes*

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
*Can't do that*

**Expected behavior**
Provide a tool (back-office, wp cli, whatever...) that allows to regenerate URLs or perform search-replace in base64 content.

**What actually happens**
In production, URL are still pointing to development environment when importing database.

**Comment by KittenCodes** [comment]
@mickaelperrin 

Unfortunately, we made a change to how the URLs are encoded and stored in the database in v3.3.

We have released an RC version of v3.3.1, which has a fix for the base_64 encoded URLs. You can download it from the customer portal by clicking Testers: Get Alpha / Beta / RC releases: https://oxygenbuilder.com/portal.

**Comment by mickaelperrin** [comment]
@KittenCodes Thanks for the quick answer. I will have a look.
