### ISSUE TITLE
Insert Data Text Block

### ISSUE THREAD

**Issue by fsekerli** [soflyy/oxygen-bugs-and-features#1186]
I have a template, and I add a text block, and then change the tag to p. Then, I double click to text element and Insert Data and choose content. 

When I inspect on the front end, I see that text block element does not wrap all the p elements. The text block element is above of all the p elements and it creates empty space.

**Comment by KittenCodes** [comment]
@fsekerli Please open a support ticket so that we can take a look at this for you: https://oxygenbuilder.com/support.
