### ISSUE TITLE
DONE: Click ID settings to zero/default

### ISSUE THREAD

**Issue by Deanphillips** [soflyy/oxygen-bugs-and-features#119]
it would be great to have the ability to zero all the setting on an ID (hitting a reset button) this would return everything to 0 so classes can be used.

**Comment by LordWhisper** [comment]
This would be such a time saver. Sometimes you do create some stuff and then learn that it's more practical to go with a class rather than editing each element on its own. Having a "Reset"-Button would be huge for these cases!

**Comment by Gibsonion** [comment]
It would be even better to have a transfer ID css to new class button, saving having to type it out again.

**Comment by maltmann-muc** [comment]
I want to vote for the reset feature.
While creating a site you sometimes fiddle around with settings, just to learn there's a better way, and want to go back.
Furthermore, if some settings have been changed and then changed back, the section is still marked as "modified" even if all settings have been set back to the origin state.

**Comment by adrien-robert** [comment]
+1

**Comment by Noz5** [comment]
+1

**Comment by wpdevlab** [comment]
+1

**Comment by eizil** [comment]
this is sure a great features to have in oxygen, +1

**Comment by KittenCodes** [comment]
This has been added.
