### ISSUE TITLE
Integration with PODS plugin

### ISSUE THREAD

**Issue by chryspear** [soflyy/oxygen-bugs-and-features#1190]
Integration with PODS plugin
PODS is a custom post types and custom fields creator. 

It's an alternative to ACF and Toolset, and it currently have more than 90,000 active installations and well supported by an active community. 

This integration can open oxygen to these users who are constrained to  rely on Oxygen's competitors just because Oxygen does not support this very robust plugin. 

As indicated this [thread link](https://wordpress.org/support/topic/pods-integration-with-oxygen/), the guys at PODS are willing to have Oxygen integrate with them. Kindly make it happen soon.

Thanks

**Comment by KittenCodes** [comment]
Duplicate: https://github.com/soflyy/oxygen-bugs-and-features/issues/478.
