### ISSUE TITLE
Failed to load template data

### ISSUE THREAD

**Issue by ManusMentz** [soflyy/oxygen-bugs-and-features#1192]
**I've just completed a brand new wordpress installation with the latest version of Oxygen (3.3.1). Started editing the Main Template.  After about 30 minutes go the error "Failed to load template data".  Cannot fix, tried to cache, resign shortcodes, etc.  Looked on FB group for help.  No luck.  All templates gives same error now. **
*Error message on editing ANY template: "Failed to load template data"*

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
*Yes*

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?** No, haven't tried this.
*If yes, provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*

**To Reproduce**

**Expected behavior**
*A clear and concise description of what you expected to happen.*

**What actually happens**
*A clear and concise description of what happens instead of the expected behavior.*

**Screenshots**
*If applicable, add screenshots to help explain your problem.*

**Desktop (please complete the following information):**
- OS: Windows 
 - Browser Chrome
 - Oxygen Version [3.3.1]

**Smartphone (please complete the following information):**
 - Oxygen Version [e.g. 2.2 Alpha]

**Additional context**
*Add any other context about the problem here.*

**Comment by KittenCodes** [comment]
@ManusMentz Please open a support ticket so that we can take a look at this for you: https://oxygenbuilder.com/support.
