### ISSUE TITLE
Broken product template editing

### ISSUE THREAD

**Issue by woxer** [soflyy/oxygen-bugs-and-features#1193]
**Describe the bug**
*A clear and concise description of what the bug is.*

I have created a template for a woocommerce product and it cannot be edited. A small red window pops up, but it is too high up and the message cannot be read.

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
*Yes/No*

Yes

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
*If yes, provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*

**To Reproduce**

**Expected behavior**
*A clear and concise description of what you expected to happen.*

Product appearance settings

**What actually happens**
*A clear and concise description of what happens instead of the expected behavior.*

Nothing is displayed for editing

**Screenshots**
*If applicable, add screenshots to help explain your problem.*

**Desktop (please complete the following information):**
 - Oxygen Version [e.g. 2.2 Alpha]

**Smartphone (please complete the following information):**
 - Oxygen Version [e.g. 2.2 Alpha]

**Additional context**
*Add any other context about the problem here.*

**Comment by KittenCodes** [comment]
@woxer Please run a plugin conflict test: https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/.

If that doesn't help, please open a support ticket so that we can take a look: https://oxygenbuilder.com/support.
