### ISSUE TITLE
Hi Just this...!

### ISSUE THREAD

**Issue by jveyes** [soflyy/oxygen-bugs-and-features#1194]
: Maximum execution time of 30 seconds exceeded in on line

Fatal error/home/inframun/public_html/wp-content/plugins/oxygen-gutenberg/oxygen-gutenberg.php388

**Comment by Spellhammer** [comment]
This is not a bug report. Contact us via https://oxygenbuilder.com/support if you want assistance with the error you posted.

**Comment by jveyes** [comment]
its Ok Thanks, solved already
