### ISSUE TITLE
3.3.1 update breaks relative URL links

### ISSUE THREAD

**Issue by alextester1990** [soflyy/oxygen-bugs-and-features#1198]
Upgrading to v3.3.1 seems to break relative URL links.

I have a few sites containing relative URL /blog/ and after update it links to homepage instead. Replicated on multiple sites.

In Oxygen, the link URL has become 'oxy_base64_encoded::L2Jsb2cv'.

**Comment by KittenCodes** [comment]
@alextester1990 Please resign your shortcodes via Oxygen > Settings > Security.

**Comment by alextester1990** [comment]
This didn't fix it when the link was an anchor (i.e. #div_block-32-8)

**Comment by KittenCodes** [comment]
@alextester1990 Please open a support ticket so that we can take a look at this for you: https://oxygenbuilder.com/support.
