### ISSUE TITLE
DONE: Multiple undo option

### ISSUE THREAD

**Issue by marceli78** [soflyy/oxygen-bugs-and-features#12]
One undo option is just not enough for speedy work. If you make mistake twice or more you have to delete and do things again. It really slows down design process.

**Comment by jaswanthch** [comment]
@marceli78 Multiple undo options are added now. 
is there any chance that you are referring to CTRL+Z within the builder itself?

**Comment by zviz** [comment]
undo using ctrl-z from the builder is quite necessary for fluent work.

**Comment by FlexonReclame** [comment]
Maybe the developers could focus first on the simple but necessary improvements

**Comment by divmonkey** [comment]
Now that is a MUST have. And yes, with Ctrl+Z(undo) and Ctrl+Y(redo)

**Comment by rwill007** [comment]
Why isn't the need for this feature taken seriously? It's hard to consider this a WYSIWYG visual builder / editor without the ability to quickly undo simple edits. smh!

**Comment by louisreingold** [comment]
It is taken seriously. But so are all the other requests on this page.

**Comment by zviz** [comment]
the thing is, talking on my behalf only: i've purchased oxygen based on the previous good experience i've had with wp all import, and as show of support to the team behind these products.
but since purchasing i've avoided using it for actually building projects, since the lack of easy undo is a complete must.
the months that have passed since, does not show it is being taken seriously.

**Comment by rwill007** [comment]
I see that I'm not the only one who gets the sense that oxygen is being managed as more of a pet project than a serious business tool.

**Comment by zviz** [comment]
I hope you are wrong.
it can grow into an amazing tool.

**Comment by asbpette** [comment]
+1

**Comment by ddwenterprises** [comment]
Not purchasing for this reason alone.  I am following this issue and will purchase once implemented.  Undo should include moving and edits to elements.

**Comment by danlavie** [comment]
> The thing is, talking on my behalf only: I've purchased Oxygen on a really early stage based on previous good experience i've had with wp all import product. i did so as a show of support to the team behind these products.
> Yet since purchasing i've avoided using it for actually building projects. first beacuse RTL problems and then the lack of easy undos which is a complete must.
> The months that have passed since, does not show it is being taken seriously.

I also wait for RTL support. Would be a shame if not implemented, since there are other options out there, but Oxygen is much superior in many ways.
To loose bigger client base just for RTL is a huge miss! and it's happening right now, since many asked me to move from another page builder to a better and faster one.

**Comment by verioussmith** [comment]
Multiple undo support would be very helpful.  I would go so far as suggesting an actual history pallette. DIVI has something like a history pallette.  This is closer to what photoshop does and makes it very easy for you to navigate back and forth through different historical changes in the life of your document.

This would be a win.

**Comment by bstramsek** [comment]
The undo option doesn't need to be complicated - just saving the state in browser should do the trick. This way undo would go only to the point of last save (what it usually goes to)...
This way there is no need to bloat the db with undo states and if you would want to - a simple refresh would bring you to the last saved state. Undo shortcut would then be able to go back one step.

**Comment by oldrup** [comment]
Coming from other builders, I tend to experiment and accidentally drag and drop elements into wrong places without really knowing what I did. Ctrl-Z to undo is almost muscle memory, and I really miss it in oxygen. So, a +1 to that feature from Denmark.

(Still insanely satisfying to build in oxygen though - so much closer to "the real thing" than other builders)

**Comment by divmonkey** [comment]
I made a **poll** about this in the official Oxygen Pagebuilder group and it reaches a [total vote of 157 in favor of YES](https://www.facebook.com/groups/1626639680763454/permalink/2337607536333328/). I know everyone noticed it, even louis does. Just want to add this here.

**Comment by Willem-Siebe** [comment]
Just bought Oxygen after trying Brizy. First thing I missed was Ctrl-Z when I moved a picture and could not move it back to the place it belonged. Ctrl-Z would have been very helpfull there.

**Comment by sushinger** [comment]
yup, pls add this, thank you 🙏

**Comment by chembim** [comment]
+1

**Comment by HenkDz** [comment]
A must. I am forced to reload the whole page if anything goes wrong.

**Comment by alriksson** [comment]
Undo, redo and reset style per element is a must.

**Comment by alriksson** [comment]
How about a reset button as well? Which would be per element/div etc. So it's possible to easily reset a styling that was made to the ID that was supposed to be assigned to a custom class.

Right now it's a hassle to reset everything. The fastest way is usually to recreate it since all styling to ID is not always cleaned. And I do not want to style 5 identical columns with 5 unique ID's which will have the same style. Most users will use custom classes and it would be good if we could be able to reset styling here.

Alternative also add copy style form ID to class and vise versa.

**Comment by dontforgetmario** [comment]
At the beginning I thought it must be there, all other builders have it, then I looked everywhere, than I thought maybe I have to active that “undo”’feature somewhere, then I asked and then I found out, there is no undo... I seems unreal, I paid $169 for a builder which has no undo button?

**Comment by krstivoja** [comment]
+ Trazilion, so I can work in any other professional tool.

**Comment by Oxymaniac** [comment]
+1

**Comment by wpdoit** [comment]
+1

**Comment by maeonian** [comment]
+1

Being new to Oxygen, I really need an Undo and a Reset for options. I keep finding myself having to delete entire sections and starting it over when I make mistakes.

**Comment by bzle** [comment]
+1

**Comment by robert1112** [comment]
+1 Elementor has this a while. It is very helpful.

**Comment by ActiveVentilationProducts** [comment]
yes yes!

**Comment by jcmatoskx** [comment]
It's been a year and there still isn't a ctrl+Z option? :'(

**Comment by joecodino** [comment]
Moving from Elementor to Oxygen. Unable to work without an Undo feature. Sometimes a bad mouse movement or an accidental click can damage your page.

**Comment by HenkDz** [comment]
> Moving from Elementor to Oxygen. Unable to work without an Undo feature. Sometimes a bad mouse movement or an accidental click can damage your page.

Whenever you are satisfied with your changes just click save. Whenever your mouse move accidentally just refresh the page. I survived years doing this.

**Comment by marou-lia** [comment]
+1 !!!!!!

**Comment by Spritpit** [comment]
Oxygen is committed to the fast workflow and I agree that it is fast, but without an undo function and also going back a few steps, the whole thing lags enormously. Command + Z is important to try things out quickly and to take the steps back one by one. This is a process of development and that includes quickly trying and deleting things. Please implement this !! :-)

**Comment by junaidsmsG** [comment]
+1

**Comment by OST-dev** [comment]
i would enjoy using OXY a lot more if there was a multiple undo/history built-in.

for new users with limited code knowledge it is MISERY when things go wrong. 

i remember Louis slagging off the competition in one of the DIVI / OXY / COMPETITOR youtube vids. I liked his attitude and swung me to try OXY over the comfortable surrounds of DIVI. However, if you want to be the best, then work harder at being the best!!

**Comment by marks1974** [comment]
Just started to use Oxygen so still a newb (thumbs up so far!). Having come from using the free version of Elementor which has it as standard, a real undo and history feature would be a big benefit to the workflow. I can't imagine it would fun to code up the software behind Oxygen in any code editor without having ctrl z so would this not be a big benefit to every user since it is present in most everyday software? It is a bit like not having the Escape key when Apple killed it off on the MBP a few years back. You expect it to be there but it isn't!

**Comment by designbysteph** [comment]
NEED this. Such an excellent and advanced builder without a basic and necessary function!
Just an undo button is too slow, having to move the cursor over. Need shortcut keys for workflow.
Also, need to be able to undo anything you do, not just deleting a section.

**Comment by imanuky** [comment]
essential!!! Please! It is amazing that it does not have this function being a payment plugin...  :(

**Comment by comtekss** [comment]
Would be extremely helpful please

**Comment by bipenett** [comment]
Hey, Oxygen Builder TEAM, when are we going to have the UNDO feature????? This is HIGHLY NEEDED!!!

**Comment by gdnwebmedia** [comment]
+1

**Comment by zunaidk** [comment]
+100

**Comment by krlhngs** [comment]
+1

**Comment by joejoerson** [comment]
Yes, undo please +1

**Comment by justadityaraj** [comment]
+1

**Comment by designbysteph** [comment]
Come on Oxygen! This is a basic necessity. You have the best builder but are going to lose customers/ranking as the best builder if this is not addressed.

**Comment by KarzanTT** [comment]
+1

**Comment by andielliott** [comment]
Coming to Oxygen cold a few months ago I'd say it's the one missing feature that makes Oxygen feel like a less polished product - Elementor/Beaver Builder/Visual Composer have this built in.

**Comment by verioussmith** [comment]
So I recently saw that someone came out with and undo for Oxygen builder but the first thing that came into my mind when I saw that plugin was that "This should be a core feature".  

I am eagerly anticipating this needed feature.

+1000 from me.

**Comment by yasien-s** [comment]
... and it is causing issues in the community, very sad :( 
these guys did it in such a short period of time...

**Comment by ictsource** [comment]
+1  essential to compete with Elementor

**Comment by wpjohnny** [comment]
+1000 from me. most obvious missing feature right off the get-go.

**Comment by lshivamber** [comment]
+1 really need this before I can use it on my important projects

**Comment by cngohar** [comment]
9999++

**Comment by slunkeh** [comment]
+1 from me!

**Comment by alanzirpoli** [comment]
+1

**Comment by Colgen** [comment]
+infinity.  Now there's a plugin available (little expensive compared to Oxygen) - hopefully it will expedite this feature.

**Comment by SEO-Durban** [comment]
+1

**Comment by UrbanFugitive** [comment]
+1 upvoted

**Comment by MiekDesigns** [comment]
+1

**Comment by Spellhammer** [comment]
If you want to upvote a feature request, make sure you're clicking the thumbs up icon as well.
![image](https://user-images.githubusercontent.com/8459002/79157146-0fb64980-7da2-11ea-8fef-d334eee1c487.png)

**Comment by swinggraphics** [comment]
The fact that this hasn't been implemented after SUCH a long time does not bode well for its use as for serious work. I am reluctant to use Oxygen on client projects.

**Comment by swinggraphics** [comment]
[After experimenting with Oxygen a bit…] Forget multiple undo. I'd settle for a single undo! I can't believe nothing is undoable.

**Comment by wordpressguy22** [comment]
+1 from me as well!
Hope it comes soon :)

**Comment by wpsumo** [comment]
+1

**Comment by profiVideos** [comment]
+1

**Comment by dmccan** [comment]
I've accidentally changed something and it is difficult to get it back the way it was.  It would be much easier to have undo rather than needing to delete the element and start over.  Thanks.

**Comment by booyen** [comment]
it is important features for a good/awesome design testing environment. +1

**Comment by vaztimur** [comment]
+1

**Comment by edricho** [comment]
UNDO!!! YES PLEASE! this is really badly needed!

**Comment by edricho** [comment]
> Multiple undo support would be very helpful. I would go so far as suggesting an actual history pallette. DIVI has something like a history pallette. This is closer to what photoshop does and makes it very easy for you to navigate back and forth through different historical changes in the life of your document.
> 
> This would be a win.

Elementor has a history pane as well, can go back to any significant edit, makes it really easy for fast work

**Comment by thinkmediaco** [comment]
+1.  I really love oxygen. But as a new user, it's extremely difficult to reverse anything manually (because I usually have no idea what in the hell I've just done about 10 steps deep...), so I end up having to refresh the page, then losing other edits. With things like columns in particular once I've gone down a bad design rabbit hole there's no reversing it. It's frustrating. I'm getting better about saving and going slowly now when experimenting, but I wish I didn't have to do that.

I don't know how difficult this is to add to the platform. But it would be hugely appreciated if it could be added sometime in the (near?) future. Thx guys.

**Comment by zviz** [comment]
it's been a while since we asked for the UNDO feature, and though it's a bit disapointing not getting the solution built in to Oxygen, i found that the Oxy Toolbox plugin is a good purchase to enhance the builder.

https://oxyplugins.com/downloads/oxy-toolbox/

it contains undo and many great features and i find myself using it on each site i build now.
it's extreml handy and price wize, both of these tools are still way cheaper than other alternatives.

at least for me the UNDO, Class act and Class Cleaner that come in this bundle make it way easier to make Oxygen a working solution and not just a cool toy that would be useful one day.

**Comment by edricho** [comment]
> it's been a while since we asked for the UNDO feature, and though it's a bit disapointing not getting the solution built in to Oxygen, i found that the Oxy Toolbox plugin is a good purchase to enhance the builder.
> 
> https://oxyplugins.com/downloads/oxy-toolbox/
> 
> it contains undo and many great features and i find myself using it on each site i build now.
> it's extreml handy and price wize, both of these tools are still way cheaper than other alternatives.
> 
> at least for me the UNDO, Class act and Class Cleaner that come in this bundle make it way easier to make Oxygen a working solution and not just a cool toy that would be useful one day.

whilst i definitely see how useful this add-on is, i think the Oxygen builder itself, being a tool created for developers, should have the Undo feature baked directly in, we shouldnt need to spend more money to get other tools for this function

**Comment by zviz** [comment]
> > it's been a while since we asked for the UNDO feature, and though it's a bit disapointing not getting the solution built in to Oxygen, i found that the Oxy Toolbox plugin is a good purchase to enhance the builder.
> > https://oxyplugins.com/downloads/oxy-toolbox/
> > it contains undo and many great features and i find myself using it on each site i build now.
> > it's extreml handy and price wize, both of these tools are still way cheaper than other alternatives.
> > at least for me the UNDO, Class act and Class Cleaner that come in this bundle make it way easier to make Oxygen a working solution and not just a cool toy that would be useful one day.
> 
> whilst i definitely see how useful this add-on is, i think the Oxygen builder itself, being a tool created for developers, should have the Undo feature baked directly in, we shouldnt need to spend more money to get other tools for this function

i tottaly agree, yet found it more useful to start using it instead of being bummed of it not working properly.
i've waited too long for them to add this functunality, and saw that the rest of the functions in the oxypack make sense and shave a lot of time off my production time.

**Comment by ms971** [comment]
Please consider building Undo/Redo/Autosave function and integrate into the existing revision history/restore. Presently, it's like walking on eggshells just hoping the latest was valid, knowing of there was a problem with invalid entry of values, you can't go back.

**Comment by Spellhammer** [comment]
Undo/redo implemented in 3.4 Alpha 1.

**Comment by zviz** [comment]
> Undo/redo implemented in 3.4 Alpha 1.
looking great :)
better late than never
i suppose this is the end for this lovely thread :)))

**Comment by HenkDz** [comment]
This thread survived for more than a year. It's time we say goodbye.

**Comment by wpsumo** [comment]
@Spellhammer In the video, the revision history seems to reset once you saved in the editor. Just because you save you may want to revert or see the revision history:
https://youtu.be/cESHnVACHb0?t=147

**Comment by bzle** [comment]
@wpsumo Agreed, I thought the same thing. It would be nice if the revision history didn't change, and there was simply an icon added to the revision list to show the save point.

**Comment by GHNalk2016** [comment]
This is absolute A must.
