### ISSUE TITLE
DONE: Link wrapper add option target="_blank"

### ISSUE THREAD

**Issue by nicholasrdwhite** [soflyy/oxygen-bugs-and-features#120]
**Describe the feature you'd like to see included in Oxygen.**
*A clear, detailed description of the feature you're requesting.*
Add external link options to link wrapper, e.g. target="_blank".

**What are the use cases for this feature?**
*e.g. Accessibility, e-commerce store that sells bicycles, etc.*
It helps avoid having to do external links in a code block.

**Examples of this feature or functionality.**
*If another product has done it well, provide examples here.*
Sorry, I only use Oxygen and I'm trying to forget about all the others.

**Comment by KittenCodes** [comment]
This has been added.
