### ISSUE TITLE
Gutnberg Integration text editing

### ISSUE THREAD

**Issue by RandallHolbrook** [soflyy/oxygen-bugs-and-features#1201]
Oxygen Blocks and pages I have made "editable" in Gutenberg don't have the ability to do basic text editing. The client wants to add to his bio and use Bold and Italicized text, but the functions are not there in the Gutenberg editor for Oxygen blocks. If I cut and paste an existing bold sentence, it is pasted as plain text. Also, text added in the gutenberg editor is not carried over into the Oxygen editor so it can't be edited there either.

**Comment by KittenCodes** [comment]
@RandallHolbrook Please use a Rich Text element in your design and not a Text element. Your client will then have additional formatting options in Gutenberg.

> Also, text added in the gutenberg editor is not carried over into the Oxygen editor so it can't be edited there either

Please add a vote to the feature request here: https://github.com/soflyy/oxygen-bugs-and-features/issues/798.

**Comment by RandallHolbrook** [comment]
It worked, however, when I added a link wrapper around the rich text and then duplicated it a couple of times, the duplicates became editable on the front-end on (not logged in to WP) another browser (MS Edge), and the links did not work.
I went back and did it again, this time it worked as intended. But there may be a glitch in there somewhere.
Thank you

**Comment by RandallHolbrook** [comment]
I know you closed this ticket a few days ago, but I am still having issues. 

Both the client and myself have tried to update using the Gutenberg editor. It accepts the text edit in the editor, but when I hit the update button I am getting this error:

Updating failed. You are probably offline.

 

Thank you,

Randall

949 235-3428

**Comment by RandallHolbrook** [comment]
I know you closed this ticket a few days ago, but I am still having issues. 
Both the client and myself have tried to update using the Gutenberg editor. It accepts the text edit in the editor, but when I hit the update button I am getting this error:
"Updating failed. You are probably offline."
So I had to edit it in Oxygen.
Thank you,
Randall

**Comment by RandallHolbrook** [comment]
Thank you, I will do that.
