### ISSUE TITLE
Oxygen visual editor is broken and can not display template structure

### ISSUE THREAD

**Issue by williammei** [soflyy/oxygen-bugs-and-features#1202]
**Describe the bug**
*A clear and concise description of what the bug is.*
After using drag and drop a group of DIVs to another location in Re-usable Part Template , Oxygen visual editor seem to be broken. It only display only part of Re-usable part template, and the Template Structure display nothing. But the website page can display whole and correct Re-usable Part.

Restore previous versions of template's design is not working. But preview of Previous versions is working and correct, just like what I designed.

How can I repair Oxygen visual editor’s display fault?

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
*Yes*

**Screenshots**
*If applicable, add screenshots to help explain your problem.*

**Desktop (please complete the following information):**
- OS: [win7]
 - Browser [chrome, firefox]
 - Oxygen Version [3.3.1]

![oxygen01](https://user-images.githubusercontent.com/11188730/83214061-48fe1980-a196-11ea-8e21-8a59f2b220ec.jpg)
![oxygen03](https://user-images.githubusercontent.com/11188730/83214079-50bdbe00-a196-11ea-8f55-b60252db11bd.jpg)
![oxgen02](https://user-images.githubusercontent.com/11188730/83214086-53201800-a196-11ea-83d9-d2247703eb12.jpg)

**Comment by KittenCodes** [comment]
@williammei Please open a support ticket so that we can take a look at this for you: https://oxygenbuilder.com/support.
