### ISSUE TITLE
Error in the JS console for the Oxygen Editor

### ISSUE THREAD

**Issue by FrenchDesign** [soflyy/oxygen-bugs-and-features#1203]
Hi,

After a new installation of WordPress without cache and with all other plug-ins disabled. 

I get this error in the JQuery console "Uncaught ReferenceError: jQuery is not defined", since editing a new page in the Oxygen editor.

Note that before installing the Oxygen plug-in, I get no error!

How to solve this problem ? 

Thank you for your support.

**Comment by KittenCodes** [comment]
@FrenchDesign Please open a support ticket so that we can take a look at your site: https://oxygenbuilder.com/support.
