### ISSUE TITLE
Out of builder CSS editor

### ISSUE THREAD

**Issue by hardwareheathens** [soflyy/oxygen-bugs-and-features#1205]
**Describe the feature you'd like to see included in Oxygen.**
*A clear, detailed description of the feature you're requesting.*
An out of builder CSS Editor. It would merely let you choose a custom stylesheet, global or page specific and save, allowing you to refresh the page and see changes.

**What are the use cases for this feature?**
*e.g. Accessibility, e-commerce store that sells bicycles, etc.*
This feature is incredibly useful as a core element.
My websites usually use a ton of my own custom CSS, for woocommerce, forms, and many other things that are used everywhere.  As a result, whenever a change needs to be made during troubleshooting, usually near the end i find that loading up the builder environment is cumbersome and time consuming. A dedicated tab in oxygen, similar to templates, that merely allows editing of global custom stylesheets, and does not take a while to load. 

**Examples of this feature or functionality.**
*If another product has done it well, provide examples here.*
Right now im custom styling a completely finished website which is where this feature would excel. I just have a bunch of small changes in the forms, woo, and some other plugins, and having to load up the builder is time consuming, and could increase workflow, adding more value to the product.

**Comment by KittenCodes** [comment]
Duplicate #221
