### ISSUE TITLE
Failed to load template data

### ISSUE THREAD

**Issue by PV-B** [soflyy/oxygen-bugs-and-features#1209]
This should not have been closed. This is so frustrating. Template elements are not saved appropriately. This is a bug but I have yet to see any responses.

**Comment by KittenCodes** [comment]
@PV-B Please open a support ticket so that we can take a look at this for you: https://oxygenbuilder.com/support. If you haven't already, please run a plugin conflict test: https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/.
