### ISSUE TITLE
Other instance of oxygen.

### ISSUE THREAD

**Issue by PV-B** [soflyy/oxygen-bugs-and-features#1210]
At the same time as getting 1209 issue, I have the other instance open in "". This occurs sometimes when I have "properly saved" the template, returned to the WP dashboard to do other things (eg- check setting, update menu not in template) then going back to editing the template.

I click open anyway (cleared caches, deactivated plugins, the lot) elements go missing. They are not the last element added or changed, so it is not a case of the last changes not saved.

There is no other instance.

![Other Oxygen](https://user-images.githubusercontent.com/30435556/83348951-101b9b80-a374-11ea-919a-2fe14aa2689d.PNG)

https://github.com/soflyy/oxygen-bugs-and-features/issues/1209#issue-627924638

**Comment by KittenCodes** [comment]
@PV-B Please open a support ticket so that we can take a look at this for you: https://oxygenbuilder.com/support. If you haven't already, please run a plugin conflict test: https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/.
