### ISSUE TITLE
Image aspect ratio gets broken on different devices.

### ISSUE THREAD

**Issue by wacaszafar** [soflyy/oxygen-bugs-and-features#1212]
Image aspect ratio gets broken when using in link wrapper as a background. 

I have set a link wrapper in the repeater main div. once I set the background to featured image as cover and set width as 100% there is no way for me to set the height to maintain the aspect ratio. I can only set it in px which works on one screen size but when a different screen size comes the the aspect ratio gets distorted and does not maintain. Please find a solution for this.

**Comment by KittenCodes** [comment]
@wacaszafar Please use the settings shown here for your background image: https://d.pr/i/MWxeQJ. The aspect should then be retained.

If you still have problems, please open a support ticket: https://oxygenbuilder.com/support.
