### ISSUE TITLE
Cant edit a teamplate - Catch All Teamplate - Not editable

### ISSUE THREAD

**Issue by gmichel1994** [soflyy/oxygen-bugs-and-features#1218]
Hello dear support, 
i can not edit the catch all teamplate anymore. 
What could be the reason for an issue like this?
At the beginning i have thought, that the reason was one of my hooks but i have deactivated my plugin and still it is not able to edit it. 

Kind regards, 
Georgij

**Comment by Spellhammer** [comment]
Please submit a support request via https://oxygenbuilder.com/support.
