### ISSUE TITLE
ACF Options

### ISSUE THREAD

**Issue by hocasiones** [soflyy/oxygen-bugs-and-features#1225]
**Describe the bug**
ACF options doesn't seem to work with Oxygen builder but if I disable Oxygen plugin the ACF options page appears.

I would like to control all the header / footer contents that I built as template and that's is the best way I think to do it.

**Comment by KittenCodes** [comment]
@hocasiones Please open a support ticket so that we can take a look at this for you: https://oxygenbuilder.com/support. Please include information on how you enabled the ACF options page.
