### ISSUE TITLE
DONE: undo and global elements = win

### ISSUE THREAD

**Issue by clockwood** [soflyy/oxygen-bugs-and-features#1229]
Undo - I know a million people have asked for undo, and I am adding my voice as well.

Global elements / library - Add the option to have global library elements that can be reused on multiple pages, and when edited, they update everywhere. Divi allows you to make certain parts of a global element not-global, which is helpful.

UI - right click in the builder to access settings in a context menu

**Comment by louisreingold** [comment]
Already done: https://oxygenbuilder.com/documentation/templating/reusable-parts/

**Comment by louisreingold** [comment]
Undo just shipped in 3.4 alpha 1 as well.
