### ISSUE TITLE
DONE: Licence Management

### ISSUE THREAD

**Issue by Jamie-owens** [soflyy/oxygen-bugs-and-features#123]
A system to manage licences for clients. This can allow us to generate and revoke licences per domain/website.

A major concern at the moment is that a client can get access to our personal licence if we include it with their website. I believe this method would make the licence more valuable as it cant be copied or stolen.

**What are the use cases for this feature?**
To manage licences and have more control of how they are used.

**Examples of this feature or functionality.**
Elementor and Brizy are currently doing it.

**Comment by muzaffarsiddiqui** [comment]
+1

**Comment by wordpressrehberi** [comment]
+1

**Comment by wordpressrehberi** [comment]
+1

**Comment by thor-webmaestrodk** [comment]
Correct me if I'm wrong, but would this not make it impossible to work offline, locally, with Oxygen if an API call is required to authenticate?

Also, I remember there being a huge issue with Elementer being DDoS'ed for days, making said API calls and autentifikation impossible and thus disabling development / editing. Not sure about the specifics. I don't use that junk :p

**Comment by Kalakus** [comment]
+1

**Comment by hawkmusician** [comment]
+1

**Comment by rorar** [comment]
Would be nice.
Here are two options related to that - but locally:
1. Have an Option to hide the license code after inserting it. Only a specific user can view it.
2. Have an Master Sword.... ehh password to unlock the license field
(it's dangerous to go alone... take this"

**Comment by wplit** [comment]
> A major concern at the moment is that a client can get access to our personal licence

I don't understand how this is a major concern. it's a lifetime deal we all have for unlimited sites. You build the client's site. You give them the site with Oxygen's licence active, they receive updates going forward.

Is the concern that they may inspect the code to 'steal' the licence and then build another site with it? Even this unlikely event did happen, I don't see how would effects us as the licence holders? If they're stealing from anybody, it's the Oxygen team, as they are using their product without paying - and the Oxygen team said they don't care about this and not to worry about it. Our ability to create infinite websites with our licences is untouched, regardless how many clients sneak a peak at the licence.

**Comment by Kalakus** [comment]
> > A major concern at the moment is that a client can get access to our personal licence
> 
> I don't understand how this is a major concern. it's a lifetime deal we all have for unlimited sites. You build the client's site. You give them the site with Oxygen's licence active, they receive updates going forward. (important as they'll need security updates)
> 
> Is the concern that they may inspect the code to 'steal' the licence and then build another site with it? Even if this unlikely event did happen, I don't see how it would effect us as the licence holders? If they're stealing from anybody, it's the Oxygen team they're stealing from, as they are using their product without paying (and the Oxygen team said they don't care about this and not to worry about it), our ability to create infinite websites with our licences would be untouched, regardless how many clients sneak a peak at the licence. We'd never know about it as it wouldn't effect us at all.
> 
> It's kind of like... if my friend secretly took a photo of my gym membership card so he could take the serial number to gain access himself sometimes. I currently have unlimited access membership, meaning i can walk into any of around 600 gyms anytime just by typing in my number at the door. I would never know if he was using my serial number to access some of these gyms without me knowing. If he was doing this, he'd actually be stealing from the company that owns the gyms, not me. I'd be completely unaffected and therefore, uninterested.

Main concern is the leak of our license code, yes. We paid for it and know that (remotely speaking) our license can be used by people that didn’t pay for the product is a valid concern.

Another concern is the subscription model for updates, for example an year price for the client itself. If the license code can be used by anyone this mean free updates, a domain validation can be really useful to disable updates for example if the client don’t want to pay for support and updates.

With other builders or plugin without a VALID license key assigned to a domain you can’t update the plugin for example (and you can’t also receive support)

This is more an enhancement, they can insert also an option to enable or disable the validation if this cause trouble to you.

**Comment by wordpressrehberi** [comment]
This feature should be 100%. It is also found in page builders like divi and brizy. It is better for each customer to have their own license.

**Comment by davidnavarrodev** [comment]
Yes please, we need something to manage licenses.
I think could be a good idea the possibility to create licenses for clients and limit it by the domain.
Currently anyone can just go to inspector and see my license key wich i don't like because I paid for it not them.

**Comment by Gibsonion** [comment]
While the fact it's visible in the inspector could be an issue in limited circumstances, the question I have is why does your client have access to Oxygen at all? If you're worried about it only give them a limited access account so Oxygen doesn't even show up in the dashboard, if you host the website the client has no access to the database either, If they're tech savvy enough to even know how to do this why would they even be hiring you to build them a site in the first place? If the site is under their hosting, just don't input the license, Oxygen works perfectly well without it. The only benefit it provides is automatic updates

**Comment by davidmarkshaw** [comment]
I would like this as I don't want either clients or third parties using my license key. please mak this happen.

**Comment by misterjak93** [comment]
> > A major concern at the moment is that a client can get access to our personal licence
> 
> I don't understand how this is a major concern. it's a lifetime deal we all have for unlimited sites. You build the client's site. You give them the site with Oxygen's licence active, they receive updates going forward. (important as they'll need security updates)
> 
> Is the concern that they may inspect the code to 'steal' the licence and then build another site with it? Even if this unlikely event did happen, I don't see how it would effect us as the licence holders? If they're stealing from anybody, it's the Oxygen team they're stealing from, as they are using their product without paying (and the Oxygen team said they don't care about this and not to worry about it), our ability to create infinite websites with our licences would be untouched, regardless how many clients sneak a peak at the licence. We'd never know about it as it wouldn't effect us at all.
> 
> It's kind of like... if my friend secretly took a photo of my gym membership card so he could take the serial number to gain access himself sometimes. I currently have unlimited access membership, meaning i can walk into any of around 600 gyms anytime just by typing in my number at the door. I would never know if he was using my serial number to access some of these gyms without me knowing. If he was doing this, he'd actually be stealing from the company that owns the gyms, not me. I'd be completely unaffected and therefore, uninterested.

for example if you work with a collaborator or the customer switches to another service provider ... this other person can use my license on other projects... pay for it

**Comment by ms971** [comment]
I couldn't care less if our customer could get our license key--that would be Soflyy's loss, since we already have an unlimited lifetime license. 

If a client defaults on payments, and they get a hacker to change the admin user rights, they can lock us out of the site, and we would have no redress under your present license system which issues a single code for all installations. If the updates continue, the departing client or his developer has no need to contact Oxygen. 

If we could revoke the active licence associated with the domain, then as soon as their updates fail, assuming they still wanted to use Oxygen, they would be approach you directly, thus giving you the chance at making them into a paying customer, even if they don't want to deal with us. 

This has happened to me years ago before we had all these advanced license registration procedures, so I know it can happen under your present system.

Elegant Themes generates an API key for each installation and gives us the ability to generate and delete API keys from our dashboard. That to me sounds like a better system of control for Agency clients.

**Comment by Spellhammer** [comment]
Implemented license management on https://oxygenbuilder.com/portal/purchase-history.
![image](https://user-images.githubusercontent.com/8459002/85950436-a5399200-b92a-11ea-8f6e-142f0ef1f679.png).

**Comment by wordpressrehberi** [comment]
thanks

Elijah Mills <notifications@github.com>, 28 Haz 2020 Paz, 17:33 tarihinde
şunu yazdı:
