### ISSUE TITLE
Different social network icons on the backend and frontend

### ISSUE THREAD

**Issue by viniciusmartin** [soflyy/oxygen-bugs-and-features#1230]
**Describe the bug**
*A clear and concise description of what the bug is.*

There is a difference in the management of social icons on the panel, and in the frontend view.

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
*Yes/No*

Yes

**Screenshots**
*If applicable, add screenshots to help explain your problem.*

Backend: http://viniciusmartin.com.br/oxygen/backend.PNG

Frontend: http://viniciusmartin.com.br/oxygen/frontend.PNG

**Comment by KittenCodes** [comment]
@viniciusmartin Please open a support ticket so that we can take a look at this for you: https://oxygenbuilder.com/support.
