### ISSUE TITLE
Can not compare two dynamic data fields in conditional display

### ISSUE THREAD

**Issue by etegan** [soflyy/oxygen-bugs-and-features#1232]
**Describe the bug**
I am unable to compare two dynamic values in a condition. The use case is that I want to display my CPT "Event" which has a 'date' field and only display events that are greater or equal to todays date.
 
**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
No

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
Yes: https://oxygen-qd2337nagx86.oxygen-demo.qsandbox.me/wp-admin (admin/admin check the 'test' page)

**To Reproduce**
1. Create new page
2. Add item with condition
3. Set condtion to php return value, function name = date, args=Ymd (for clarity; the final condition should be todays date == todays date).

**Expected behavior**
The item with the condition should show

**What actually happens**
It does not...

**Desktop (please complete the following information):**
- OS: Win10
 - Browser chrome
 - Oxygen Version 3.3.1

**Additional info**
If I switch out the dynamic data field for 20200608 (date when reporting) I get the expected behaviour.

**Comment by greenyboy** [comment]
I can confirm this bug too. Please fix as it is a really useful feature

**Comment by smitherines** [comment]
yes very annoying

**Comment by srikat** [comment]
Fixed in 3.5 Beta 1.
