### ISSUE TITLE
Importing settings causes Templates - Global settings for Text links to not be applied 

### ISSUE THREAD

**Issue by clockwood** [soflyy/oxygen-bugs-and-features#1233]
**Describe the bug**

Importing settings causes Templates - Global settings for Text links to not be applied to page OR saved.  If I change any settings at Manage > Settings > Global Styles > Links, they do not apply to the page. If I save and reload the editor, the settings haven't been saved (they are default/blank)

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
Yes

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
Yes. https://oxygen-qf4xwgyhfpt9k.oxygen-demo.qsandbox.me/

**To Reproduce**
Import Oxygen settings (see attached file).
[oxy-settings.txt](https://github.com/soflyy/oxygen-bugs-and-features/files/4748475/oxy-settings.txt)
Then try to edit/save Manage > Settings> Global Styles > Links >All, etc.

Edit a template. Click Manage > Settings > Global Styles > Links.
Add color or other setting. Save.

**Expected behavior**
Links on template should update to show changes made in settings. Changes should persist.

**What actually happens**
Styles are not applied to template, nor are they saved.

**Screenshots**

**Desktop (please complete the following information):**
Win 10
Firefox, 77.0.1 (64-bit)
Oxygen Version 3.3.1

**Additional context**
The problem occurred on the original site before exporting/importing the settings. However, importing settings from this site, causes the issue on other sites.

**Comment by KittenCodes** [comment]
@clockwood 

The Links section in your Export JSON is malformed, which is why the issue persists when you import it to another site.

I've removed the Links section and verified that I can change link colours when I import it to a Sandbox site. Here's the fixed JSON: 
[exportjson.txt](https://github.com/soflyy/oxygen-bugs-and-features/files/4751834/exportjson.txt)
