### ISSUE TITLE
Fix the Unidentified index Button priority as it is filling up my logs.

### ISSUE THREAD

**Issue by khiser** [soflyy/oxygen-bugs-and-features#1234]
I have multiple sites that all have huge log files due to a never-ending error.  I know it is s simple fix and would appreciate it being taken care of as it makes looking through logs tedious.  (This log is 477 mb of this stuff.  :(

****** sample of log ******
28-May-2020 20:18:57 UTC] PHP Notice:  Undefined index: button_priority in /home/{clientname}/public_html/wp-content/plugins/oxygen/component-framework/api/oxygen.element.class.php on line 37
[28-May-2020 20:18:57 UTC] PHP Notice:  Undefined index: button_priority in /home/{clientname}/public_html/wp-content/plugins/oxygen/component-framework/api/oxygen.element.class.php on line 37
[28-May-2020 20:18:57 UTC] PHP Notice:  Undefined index: button_priority in /home/{clientname}/public_html/wp-content/plugins/oxygen/component-framework/api/oxygen.element.class.php on line 37
****** end of sample ********

Thanks in advance,

**Comment by tuqqo** [comment]
still a problem

**Comment by twistedpixel** [comment]
Still a problem, despite it being reported ~5 months ago.

**Comment by perrelet** [comment]
c'mon!

**Comment by twistedpixel** [comment]
> c'mon!

It looks like they've fixed a lot of these in 4.6 which I imagine will be released soon as it's at RC 2. Hopefully they've caught them all.

**Comment by KittenCodes** [comment]
@twistedpixel You're correct - we have fixed a number of PHP bugs in v3.6, including this button_priority bug. You can find a changelog here: https://oxygenbuilder.com/2020/09/28/oxygen-3-6-beta-1-now-available/.
