### ISSUE TITLE
Deque Styles - does not work with Oxygen

### ISSUE THREAD

**Issue by gmichel1994** [soflyy/oxygen-bugs-and-features#1237]
Hello, dear Oxygen Support, 

i wanted to optimize the page which is created with Oxygen. Wordpress Version 5.4.1
For this i wrote this script to deque specific stylesheets. But it does not work. 
I have tried a lot of variations. All people who wanted to help says that it should have effect. But it does not.

function disable_bloat() {
    //Prevent loading WP-Core CSS outside Admin Area.
	if(!is_admin()){
        //Option One
        wp_dequeue_style('dashicons-css');
        wp_dequeue_style('admin-bar-css');
        wp_dequeue_style('wp-block-library-css');
       //Option Two
        wp_deregister_style('dashicons-css');
        wp_deregister_style('admin-bar-css');
        wp_deregister_style('wp-block-library-css');
    }
    
    if(!is_page('kontakt')){
        wp_dequeue_style('contact-form-7-css');
        wp_deregister_style('contact-form-7-css');
    }
}add_action('wp_enqueue_scripts', 'disable_bloat', PHP_INT_MAX); 

How Oxygen loads the scripts and how to prevent it?

Kind regards, 
Georgij

**Comment by swinggraphics** [comment]
What file did you put this code in? I'm guessing you put it in a theme's functions.php file. If that is the case, please see https://oxygenbuilder.com/documentation/code/alternatives-to-functions-php/
