### ISSUE TITLE
Oxygen template displays "failed to load template data" - no structure panel data is visible

### ISSUE THREAD

**Issue by alexanders-nz** [soflyy/oxygen-bugs-and-features#1238]
**Describe the bug**
On a live site - https://coeliac.org.nz/ which continues to function but the template (and/or copies of it) are not editable in a reliable fashion.

*A clear and concise description of what the bug is.*
the error message "failed to load template data" appears briefly - no structure panel data - sections / divs etc is visible.
It is possible to add, edit and delete the rendered content but attempting to move any div results in an UnCaught Type error .. 'replace' 

see attached 
![oxygen moving div error](https://user-images.githubusercontent.com/39969946/84217018-2c130000-ab1f-11ea-9eb9-13401b17d2ad.png)
![oxygen empty structure panel](https://user-images.githubusercontent.com/39969946/84217026-303f1d80-ab1f-11ea-92f2-08378bfa9a81.png)

I have tried reverting back to Oxygen v3.2.1 no change
This server is running on PHP 7.4.6 other Oxygen sites with 3.3.1 are fine .. the other templates on the site are also fine.

Your help much appreciated .. 
Access available at your request.

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
*Yes/No*
YES

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
*If yes, provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*

**To Reproduce**

**Expected behavior**
*A clear and concise description of what you expected to happen.*

**What actually happens**
*A clear and concise description of what happens instead of the expected behavior.*

**Screenshots**
*If applicable, add screenshots to help explain your problem.*

**Desktop (please complete the following information):**
 - Oxygen Version [e.g. 2.2 Alpha]

**Smartphone (please complete the following information):**
 - Oxygen Version [e.g. 2.2 Alpha]

**Additional context**
*Add any other context about the problem here.*

**Comment by KittenCodes** [comment]
@alexanders-nz Please open a support ticket so that we can take a look at this for you: https://oxygenbuilder.com/support.

**Comment by lazerbeam84** [comment]
After lots and lots of struggling I figured out what causes this. If you are using this as a blog post template and you have any posts that are still drafts it will cause this error. To resolve it just publish your blog posts.
