### ISSUE TITLE
API issue | When nesting divs inside nestable components.

### ISSUE THREAD

**Issue by wplit** [soflyy/oxygen-bugs-and-features#1239]
**Describe the bug**
When elements created with the API (also happens with product builder) are nestable, there is a bug where if the user either wraps elements inside a div, or nests divs inside divs.. the divs (and their contents) will not be output correctly on the front end.

What happens is either they don't appear in the markup at all, or we see a [/ct-div-block] where the div element should be.

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
Yes, https://oxygen-q3a8kvkj9y86.oxygen-demo.qsandbox.me/product/wordpress-pennant/

I added three divs. One div then child div then another child inside that one. On the front there is only one div appearing. Now if you go inside the builder, you'll only see one div, but that div won't be select it inside the structure as something has bugged out. 

**To Reproduce**
1. Go to https://oxygen-q3a8kvkj9y86.oxygen-demo.qsandbox.me/product/wordpress-pennant/
2. Create a div inside the product builder, then add another div inside and again so three levels deep
3. Save
4. View on front and see there is only one div in markup.
5. Go back to builder, the divs will be gone (as well as any content inside), sometimes only one div will remain that is now unselectable. Other times none are there.

**Expected behavior**
All elements should appear on the front as they do inside the builder.

**What actually happens**
They don't appear in the markup at all, or sometimes we see a [/ct-div-block] where the div element should be.

**Note**
We've seen this behaviour before, back when users couldn't nest divs inside the row-left, row-center, row-right divs inside the header builder. https://github.com/soflyy/oxygen-bugs-and-features/issues/585?fbclid=IwAR1-zF86neqN9iLIur4rdd2RlIZKYuiOxDKLzOKdXR-ZggU5sgEMMb2kqrI I couldn't find the original bug report, it may have been before it was all in github.

**Comment by wplit** [comment]
Video of adding nested divs inside product builder in that sandbox site, it doesn't register them on the front (shows the default) back inside the builder the divs are missing https://www.loom.com/share/ef4e5e02d1334df4b840cc3b6b7945a4

**Comment by wplit** [comment]
This bug is still happening with API components, including the product builder. It's only when nesting divs, something about nesting divs inside API components that can cause the shortcodes to break.

**Comment by marc-maurer** [comment]
Still happening with oxygen 3.6.1
In Oxygen everything looks fine but at the frontend everything is broken.

I would really appericiate if this gets fixed sooon as it is prevnting me from getting my sites done.

**Comment by igmarketing** [comment]
I never faced this issue before but I have updated to Oxygen 3.7 and now I am having the same issue. https://i.imgur.com/AEwfi6Z.png

Please fix this guys!
