### ISSUE TITLE
Header Columns should be selected

### ISSUE THREAD

**Issue by flashwebdeveloper** [soflyy/oxygen-bugs-and-features#1240]
I don't know why this feature is missing in oxygen. But, don't you think that it'll be better if we can select Header Columns (Row left, Row center, and Row right) and edit them in the editor (like background, size, etc.). A lot of the time I have to inspect and tweak the element to get the desired effect.

**Comment by swinggraphics** [comment]
This is a MUST. It's very frustrating not being able to target the columns for sizing, visibility, colors, etc, etc… Yes, we can add custom code, but we should not have to.

**Comment by swinggraphics** [comment]
Just discovered that flex child settings aren't available in the Selector editor, so we must actually hand code various aspects of the header. As soon as I start hand coding for basic layout, I question why I'm using a page builder.

**Comment by VinceBalk** [comment]
With one header row it is all ok, but with two or more header rows a selector is not unique enough. we need to be able to style/format one header row separatly. thanks.

**Comment by KittenCodes** [comment]
See: https://github.com/soflyy/oxygen-bugs-and-features/issues/1240
