### ISSUE TITLE
Reusable-Part breaks template css for good

### ISSUE THREAD

**Issue by YammYcoding** [soflyy/oxygen-bugs-and-features#1241]
**Describe the bug**
After making a footer reusable, template css stopped rendering completely ( just displaying plain html text on browser ).
Also randomly display a blank page with a block of odd characters instead of what was in template and content.

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
Yes, tried it, and din't solve anything.

**To Reproduce**
1. Create a header, inner content and footer with stuff inside.
2. Make footer reusable part.
3. Show page in browser.
4. All styles from oxygen stop working OR a block of odd characters on a white page take its place.
5. Tried to fix importing the reusable part as editable and deleting reusable part template, now styles come back to render in part, all styles from footer gets gone.
6. Go to global styles / fonts > all other google fonts gets gone ( now only have the default ones, georgia, times, arial, tahoma, verdana, courier )

Looks like the reusable part action is not carring the entire css to its place correctly and is leaving bad code behind on the original template, breaking it for good. I create another blank template and things still render half assed, so now any template renders badly. Site is gone.

**Screenshots**
- styles gone after reusable part:
![image](https://user-images.githubusercontent.com/1200923/84231202-fbea4380-aac3-11ea-8bbd-79e57553c2eb.png)

- odd chars after a few page reloads ( after chars take place, it never come back to the pure text or the styled page again ):
![image](https://user-images.githubusercontent.com/1200923/84231130-d52c0d00-aac3-11ea-9fbb-73e007dd7620.png)

**Comment by KittenCodes** [comment]
@YammYcoding Please open a support ticket so that we can take a look at this for you.

**Comment by YammYcoding** [comment]
I opened the ticket, nobody came. I deleted everything again.

**Comment by YammYcoding** [comment]
Coming back to tell that this happened again, on a template for an archive I was making here using ACF post. It was all working, I was editing the page, for no reason, the template changed to this WSOD page. Restoring the revisions didn't solve it, I had to delete the template and start all over again.

Some try catch error message would be strongly appreciated.

Versioon was still on 5.4

**Comment by KittenCodes** [comment]
@YammYcoding If this happens again, please open a support ticket so that we can take a look at this for you: https://oxygenbuilder.com/support. You need to select "Something's broken and I need help".
