### ISSUE TITLE
Ultimate Member is no longer able to inject their forms into an Oxygen template

### ISSUE THREAD

**Issue by AlvaroAtl** [soflyy/oxygen-bugs-and-features#1242]
**Describe the bug**
*A clear and concise description of what the bug is.*

Using Oxygen 3.3.1 I've found that the template pages no longer work with the shortcodes given by Ultimate Member, it now shows blank spaces where the forms used to be after updating Oxygen.

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
*Yes/No*

Yes

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
*If yes, provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*

The issue is in my staging server: 
http://recetapp.huakal.com/login/
http://recetapp.huakal.com/register/

**To Reproduce**

As far as I've noticed, install latest Oxygen build and latest UM plugin, try to integrate forms into the default pages > Forms do not appear

**Expected behavior**
*A clear and concise description of what you expected to happen.*

I was expecting the UM forms to appear on front end as they used to before updating Oxygen

**What actually happens**
*A clear and concise description of what happens instead of the expected behavior.*

Forms do not appear on front end regardless of the method used to integrate the UM forms

**Screenshots**
*If applicable, add screenshots to help explain your problem.*

More info can be found using the link added previously to the report

**Desktop (please complete the following information):**
 - Oxygen Version [e.g. 2.2 Alpha]

Firefox (latest version) Chrome (latest version)

**Smartphone (please complete the following information):**
 - Oxygen Version [e.g. 2.2 Alpha]

Same as before

**Additional context**
*Add any other context about the problem here.*

**Comment by KittenCodes** [comment]
@AlvaroAtl Please open a support ticket so that we can take a look at this for you: ohttps://oxygenbuilder.com/support
