### ISSUE TITLE
Template Previewing List limited to 20

### ISSUE THREAD

**Issue by jasperf** [soflyy/oxygen-bugs-and-features#1244]
**Describe the bug**
When i search for a product page I cannot locate it as I have more than 20 search results based on search term. Even when I put in the full title I still see twenty listed and not the product I want to work on in preview

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
*Yes*

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
No.*

**To Reproduce**
1. Go to Oxygen Templates > single product template
2. Previewing
3. Enter term that will get more than 20 hits
4. See that 20 products are listed but not the one you were looking for

**Expected behavior**
I expected the product to show up, but instead I saw 20 other products and not that one. It seems Oxygen limits to 20 search results.

**What actually happens**
Only twenty products showed and not the product I wanted to preview

**Screenshots**
![Screen Shot 2020-06-11 at 10 24 36 AM](https://user-images.githubusercontent.com/344138/84341952-946cea80-abce-11ea-9fae-4da8fda412f0.png)

**Desktop (please complete the following information):**
- OS: macOS Catalina
 - Browser Firefox Developer Edition
 - Oxygen Version 3.3.1

**Smartphone (please complete the following information):**
 - Oxygen Version [e.g. 2.2 Alpha]

**Additional context**
*Add any other context about the problem here.*

**Comment by Spellhammer** [comment]
Please try changing the "Preview Dropdown Limit" under Oxygen > Settings in the WordPress admin panel.
![image](https://user-images.githubusercontent.com/8459002/84653418-609a0980-aedb-11ea-8e61-4e5b14f96c24.png)
