### ISSUE TITLE
Bug in version 3.4

### ISSUE THREAD

**Issue by BrunoPirard** [soflyy/oxygen-bugs-and-features#1245]
I have these errors on the pro menu when installing version 3.4
Warning: strpos () expects parameter 1 to be string, array given in D: \ wamp64 \ www \ bilyanakamenova.xyz \ wp-content \ plugins \ oxygen \ component-framework \ includes \ tree-shortcodes.php on line 951
I have disabled all plugins and I have the same result. Also on several sites (locally - wamp) WP 5.4.2.

**Comment by axelparatre** [comment]
Hi, I just went through this error by adding gradient on shape divider (and the gradient is not working btw) !

**Comment by Spellhammer** [comment]
> Hi, I just went through this error by adding gradient on shape divider (and the gradient is not working btw) !

Can you provide steps to replicate this?

**Comment by axelparatre** [comment]
On a section, "Add shape divider", "Color", select any color. On backoffice everything seems fine but on frontoffice there is this error message appearing : 

<div id="-shape-divider-236-9" class="oxy-shape-divider " style="color: black !important;z-index: 99999;"><br><b>Warning</b>:  strpos() expects parameter 1 to be string, array given in <b>/app/conecs/wp-content/plugins/oxygen/component-framework/includes/tree-shortcodes.php</b><br> on line <b>951</b><div class="oxy_shape_divider">
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1440 320" preserveAspectRatio="none"><path fill="currentColor" fill-opacity="1" d="M0,288L1440,0L1440,320L0,320Z"></path></svg></div>

**Comment by wplit** [comment]
I have similar issue, I'm just about to post a seperate bug report but a similar error occurs when changing the typography settings of an API component (happens with the Pro Menu > Mobile Menu > Typography and select either 'Text' or 'Display' as the font family.

Error on front end - Warning: strpos() expects parameter 1 to be string, array given in /home/dezign/www/new/wp-content/plugins/oxygen/component-framework/includes/tree-shortcodes.php on line 951

**Comment by mikeingz** [comment]
I confirm the font bug with v3.4 RC1. I did some tests and it happens every time on local websites, live websites, new website with only Oxygen and no other plugins. BUT weirdly, I am unable to replicate it in the Oxygen Sandbox.

**Comment by Spellhammer** [comment]
Fixed in 3.4 RC 2.
