### ISSUE TITLE
Warning: Cannot modify header information - headers already sent by (output started at /wp-content/plugins/oxygen/component-framework/api/oxygen.element.class.php:37)

### ISSUE THREAD

**Issue by jasperf** [soflyy/oxygen-bugs-and-features#1251]
**Describe the bug**
Loading WooCommerce Product Add-On ultimate with `define('WP_DEBUG_DISPLAY', true);` causes issues loading the page related to a bug / notice in Oxygen

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
*Yes*

**To Reproduce**
1. Go to `wp-admin/edit.php?post_type=pewc_product_extra&page=global`
2. See page not load until a lot later
3. See errors related to header already sent

**Expected behavior**
*Site to only load with notices displayed*

**What actually happens**

Error caused significant display and warning display

```
Warning: Cannot modify header information - headers already sent by (output started at /wp-content/plugins/oxygen/component-framework/api/oxygen.element.class.php:37) in /home/debxxxxxx/domains/domain.com/public_html/staging/wp-includes/option.php on line 962
```

**Desktop (please complete the following information):**
- OS: macOS Catalina
 - Browser Firefox Developer Edition
 - Oxygen Version 3.3.1

**Comment by KittenCodes** [comment]
@jasperf 

Does this only happen when the WooCommerce Product Add-On plugin is active?

**Comment by Slumb** [comment]
@KittenCodes 
For me, yes it is

**Comment by jasperf** [comment]
@KittenCodes Well, the reason I turned it on is to debug the other issue mentioned here https://github.com/soflyy/oxygen-bugs-and-features/issues/1248 related to a possible add-on Oxygen conflict so that could be the case. I can however not live without Oxygen nor Plugin Republic's [WooCommerce Product Add-ons Ultimate](https://pluginrepublic.com/wordpress-plugins/woocommerce-product-add-ons-ultimate/) . Will test briefly locally with it turned off and see if `WP_DEBUG_DISPLAY true;` runs without issues and get back to you.

**Comment by jasperf** [comment]
Yes, with WooCommerce Product Add-ons Ultimate turned off `WP_DEBUG_DISPLAY true;` does not hit `headers already sent` failure. So I guess I need to solve the conflict to solve this issue as well.
