### ISSUE TITLE
TypeError: jQuery(...).photoSwipe is not a function

### ISSUE THREAD

**Issue by linformatique** [soflyy/oxygen-bugs-and-features#1253]
Describe the bug
Gallery widget cause an error in template editor.

Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?
Yes

Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?
Yes

To Reproduce
Steps to reproduce the behaviour:

    Edit home page in Oxygen (or another page)
    Add gallery widget and save
    Go to Oxygen->Templates
    Click to edit Main template
    Set preview on page with gallery widget
    See error

Expected behaviour
No error

What actually happens
Uncaught TypeError: jQuery(...).photoSwipe is not a function on line #3

Desktop (please complete the following information):

    OS: Windows 10 (current)
    Browser: Firefox
    Oxygen Version 3.3.1

**Comment by KittenCodes** [comment]
Duplicate #888
