### ISSUE TITLE
Add option to set "overflow" status to prevent white space problem.

### ISSUE THREAD

**Issue by pitouking** [soflyy/oxygen-bugs-and-features#1259]
There is a lot of white space problem on mobile when using AOS, especially right/left animation.
That is due to the default overflow status of every new section. It's visible.

Problem with mobile version of site that show a white space when horizontal animations are used.
It's because of the overflow:visible default status of every section.
New users of Oxygen (it took me a month to find out.) do have that problem and are asking in the FB group.

An default overflow:hidden instead of visible for every new section would prevent that.
Better, add that to the global settings along padding options etc...

Thanks !

**Comment by KittenCodes** [comment]
I'd suggest adding the following CSS to a stylesheet via Manage > Stylesheets in the top right of the builder:

```
.ct-section {
    overflow: hidden;
}
```
