### ISSUE TITLE
No option to add oxygen blocks inside gutenberg editor for a second website in a multisite installation 

### ISSUE THREAD

**Issue by artjomzab** [soflyy/oxygen-bugs-and-features#1261]
**Describe the bug**

In a multisite (subdomain) installation only the main site has the "Oxygen Blocks" option in the gutenberg editor.

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**

Yes

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**

No, issue is only present on a multisite installation, which I cannot replicate here.

**To Reproduce**

1. Create a multisite installation (subdomain mapping)
2. Install oxygen + gutenberg extension
3. Create a second website
3. Activate oxygen + gutenberg extension on main and the second website
3. Create a block
4. See that you cannot choose the block on the second website, only on the first

**Expected behavior**

In the gutenberg editor I should be able to select oxygen blocks for the website I am editing in a multisite environment.

**What actually happens**

On the main site of the network I can choose oxygen blocks, however on the second website there is no option to choose oxygen blocks in the gutenberg editor.

**Desktop (please complete the following information):**

- OS: Windows 10
 - Browser Chrome 83.0.4103.106
 - Oxygen Version 3.3.1
 - Oxygen Gutenberg 1.3

**Additional context**

Currently I have activated Oxygen + Gutenberg extension for each indivual website. When I activate it for the entire network, the "Block Library" link under the "Oxygen" menu is not even displayed.

**Comment by KittenCodes** [comment]
@artjomzab Please enable the Block Library on the child site via Oxygen > Settings > Library.

Whilst investigating this, I did find that I was able to add blocks to Gutenberg on child sites. However, the CSS doesn't load correctly in Gutenberg, but it does on the front-end of the site. I will report this internally.
