### ISSUE TITLE
My license - unable to cut and paste.

### ISSUE THREAD

**Issue by manisulur** [soflyy/oxygen-bugs-and-features#1264]
I got the agency program for Oxygen. I am trying to copy and paste the license in the area in WP under settings. For some strange reason, it is responding as invalid. I never had issues with other apps where I could copy and paste. This one is driving me crazy. Also, do you recommend the pro version (recommended) or the pro version blank?

**Comment by KittenCodes** [comment]
@manisulur If you're still having problems, please open a support ticket: https://oxygenbuilder.com/support.
