### ISSUE TITLE
PHP Deprecated error messages

### ISSUE THREAD

**Issue by ddon** [soflyy/oxygen-bugs-and-features#1267]
**Describe the bug**
After activating plugin, error log is now filling up really fast with error messages

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
No

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
Can't see logs there

**To Reproduce**
1. Have PHP 7.4 and activate your plugin

**Expected behavior**
No messages in error log while normal operation

**What actually happens**
error appear in error log

**Screenshots**
![image](https://user-images.githubusercontent.com/187798/84921195-d618fc00-b0cc-11ea-823f-078701bf2c19.png)

**Desktop (please complete the following information):**
- OS: Linux
 - Browser: not related
 - Oxygen Version: most recent, 3.something

**Smartphone (please complete the following information):**
not relevant

**Additional context**
error messages in text:

2020/06/17 15:55:17 [error] 79#79: *5924 FastCGI sent in stderr: "PHP message: PHP Deprecated:  implode(): Passing glue string after array is deprecated. Swap the parameters in /www/wp-content/plugins/oxygen3/component-framework/component-init.php on line 4846PHP message: PHP Deprecated:  implode(): Passing glue string after array is deprecated. Swap the parameters in /www/wp-content/plugins/oxygen3/component-framework/component-init.php on line 4846PHP message: PHP Deprecated:  implode(): Passing glue string after array is deprecated. Swap the parameters in /www/wp-content/plugins/oxygen3/component-framework/component-init.php on line 4846PHP message: PHP Deprecated:  implode(): Passing glue string after array is deprecated. Swap the parameters in /www/wp-content/plugins/oxygen3/component-framework/component-init.php on line 4846PHP message: PHP Deprecated:  implode(): Passing glue string after array is deprecated. Swap the parameters in /www/wp-content/plugins/oxygen3/component-framework/component-init.php on line 4846PHP message: PHP Notice:  Undefined index: icon-background-color in /www/wp-content/plugins/oxygen3/component-framework/components/classes/social-icons.class.php on line 207PHP message: PHP Notice:  Undefined index: icon-background-hover-color in /www/wp-content/plugins/oxygen3/component-framework/components/classes/social-icons.class.php on line 213PHP message: PHP Deprecated:  implode(): Passing glue string after array is deprecated. Swap the parameters in /www/wp-content/plugins/oxygen3/component-framework/component-init.php on line 4846PHP message: PHP Deprecated:  implode(): Passing glue string after array is deprecated. Swap the parameters in /www/wp-content/plugins/oxygen3/component-framework/component-init.php on line 4846PHP message: PHP Deprecated:  implode(): Passing glue string after array is deprecated. Swap the parameters in /www/wp-content/plugins/oxygen3/component-framework/component-init.php on line 4846PHP message: PHP Deprecated:  implode(): Passing glue string after array is d
2020/06/17 15:55:17 [error] 79#79: *5924 FastCGI sent in stderr: "lue string after array is deprecated. Swap the parameters in /www/wp-content/plugins/oxygen3/component-framework/component-init.php on line 4846PHP message: PHP Notice:  Undefined index: icon-background-color in /www/wp-content/plugins/oxygen3/component-framework/components/classes/social-icons.class.php on line 207PHP message: PHP Notice:  Undefined index: icon-background-hover-color in /www/wp-content/plugins/oxygen3/component-framework/components/classes/social-icons.class.php on line 213PHP message: PHP Deprecated:  implode(): Passing glue string after array is deprecated. Swap the parameters in /www/wp-content/plugins/oxygen3/component-framework/component-init.php on line 4846PHP message: PHP Deprecated:  implode(): Passing glue string after array is deprecated. Swap the parameters in /www/wp-content/plugins/oxygen3/component-framework/component-init.php on line 4846PHP message: PHP Notice:  Undefined index: menu_padding-bottom in /www/wp-content/plugins/oxygen3/component-framework/components/component.class.php on line 2580PHP message: PHP Notice:  Undefined index: menu_padding-bottom in /www/wp-content/plugins/oxygen3/component-framework/components/component.class.php on line 2610PHP message: PHP Deprecated:  implode(): Passing glue string after array is deprecated. Swap the parameters in /www/wp-content/plugins/oxygen3/component-framework/component-init.php on line 4846PHP message: PHP Deprecated:  implode(): Passing glue string after array is deprecated. Swap the parameters in /www/wp-content/plugins/oxygen3/component-framework/component-init.php on line 4846PHP message: PHP Deprecated:  implode(): Passing glue string after array is deprecated. Swap the parameters in /www/wp-content/plugins/oxygen3/component-framework/component-init.php on line 4846PHP message: PHP Deprecated:  implode(): Passing glue string after array is deprecated. Swap the parameters in /www/wp-content/plugins/oxygen3/component-framework/component-init.php on line 484

**Comment by ddon** [comment]
tested using 3.4 Beta 1, errors still there...

**Comment by Cenay** [comment]
I would add that it is more than having 7.4 PHP loaded, I am getting it in PHP 7.1.36 as well on one site, and 7.2 on another and they are still getting it.

**Comment by Raravin-Keebs** [comment]
So I understand this is a confirmed bug and I am on 7.2 was this fixed anywhere as I am getting it on our checkout page in big text for clients.

**Comment by wpsumo** [comment]
@KittenCodes Still an issue in 3.6 even if it's confirmed to be fixed in the changelog.

**Comment by KittenCodes** [comment]
@wpsumo Are you able to give me the steps needed to replicate this?

**Comment by wpsumo** [comment]
Not really I just open console on a page and seeing this errors. Using latets oxygen 3.6 and yoast 15.1.2

**Comment by KittenCodes** [comment]
@wpsumo If you'd like us to take a look at your site, please open a support ticket: https://oxygenbuilder.com/support.

**Comment by wpsumo** [comment]
The support ticket system is down. I do not get any confirmation emails. It is very often down, and very annoying as you spent time sending a report/information but never remember to save as you expect it to work.

**Comment by KittenCodes** [comment]
> The support ticket system is down. I do not get any confirmation emails. It is very often down, and very annoying as you spent time sending a report/information but never remember to save as you expect it to work.

Would you mind recording a quick video showing what happens when you try to open a support ticket? Please then send a link to the video to us directly using support@oxygenbuilder.com

**Comment by wpsumo** [comment]
I never receive the confirmation email. You say if this happens your email did not reach you.
