### ISSUE TITLE
Responsive resolution drop down not working correctly

### ISSUE THREAD

**Issue by ddon** [soflyy/oxygen-bugs-and-features#1269]
**Describe the bug**
Selector to select resolution (media query) not working correctly.
![image](https://user-images.githubusercontent.com/187798/84926723-7e7e8e80-b0d4-11ea-9f26-3752d221d2a9.png)

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
Yes

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
yes

https://oxygen-q2blvkpr6a96.oxygen-demo.qsandbox.me/sample-page/

tried even on beta 1 on my server, bug is still there

**To Reproduce**
1. Go to any page, select any component and try to select resolution in that drop down. when you select 992, 768 will be selected. And the same will be happening with every other... 

**Expected behavior**
992 should select 992, not 768

**What actually happens**
768 get selected instead of 992

**Screenshots**
![image](https://user-images.githubusercontent.com/187798/84926607-4ecf8680-b0d4-11ea-955f-dce7415fe9d2.png)

**Desktop (please complete the following information):**
- OS: Windows 10
 - Browser: Firefox
 - Oxygen Version: 3.3.4 and recent beta

**Comment by ddon** [comment]
Tried in Chrome, just in case... and the same problem.

**Comment by KittenCodes** [comment]
This is not a bug. When you select a break point, Oxygen will display the next smallest break point plus 1px so that you can be sure the design you're created will work on all screen sizes that will use that break point.

So, 992px will be shown at 769px so that you can check the design works on the smallest possible screen that will use that break point.

**Comment by ddon** [comment]
This is how it used to work (I am using Oxygen from very beginning):
![image](https://user-images.githubusercontent.com/187798/85053750-adb00100-b1a3-11ea-908c-edb71515af91.png)

So, this got changed now and this is new normal?
