### ISSUE TITLE
Opening Editor generates 503 Error Page after 2.2 update

### ISSUE THREAD

**Issue by Budoman** [soflyy/oxygen-bugs-and-features#127]
**Describe the bug**
*A clear and concise description of what the bug is.*
Unable to open Oxygen Editor after updating from 2.1.2 to 2.2. Running WP 5.0.3.
 
**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
*Yes/No*

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
*If yes, provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*

**To Reproduce**

**Expected behavior**
*A clear and concise description of what you expected to happen.*

**What actually happens**
*A clear and concise description of what happens instead of the expected behavior.*

**Screenshots**
*If applicable, add screenshots to help explain your problem.*

**Desktop (please complete the following information):**
 - Oxygen Version [e.g. 2.2 Alpha]

**Smartphone (please complete the following information):**
 - Oxygen Version [e.g. 2.2 Alpha]

**Additional context**
*Add any other context about the problem here.*

**Comment by Spellhammer** [comment]
If this is still occurring in Oxygen 2.2.1, please submit a support ticket to support@oxygenbuilder.com.
