### ISSUE TITLE
Using effects (animations)

### ISSUE THREAD

**Issue by msnetdesign** [soflyy/oxygen-bugs-and-features#1273]
**Describe the bug**
*A clear and concise description of what the bug is.*
**I've got a WP-installation on my webserver using a subdomain without SSL certificate. I designed the page with Oxygen an on several elements I wanna use effects (animations). I see the effects in the backend, I save everything and proceed to the frontend: I can't see the elements with effects...somehow they are hidden in the frontend?**

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
*Yes/No*
**Yes as far as I'm able to (I'm new to Oxygen)**

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
*If yes, provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*
**No, I haven't tried...**

**To Reproduce**

**Expected behavior**
*A clear and concise description of what you expected to happen.*
**I just want to use effects on some elemnts of the page and these should show up in the frontend**

**What actually happens**
*A clear and concise description of what happens instead of the expected behavior.*
**The elements styled with effects are not showing up!**

**Screenshots**
*If applicable, add screenshots to help explain your problem.*

**Desktop (please complete the following information):**
 - Oxygen Version [e.g. 2.2 Alpha]
**I'm using Oxygen newest release on iMAC OS Catalina
Browsers used: Firfox, Safari, Chrome
Wordpress: newest version available**

**Smartphone (please complete the following information):**
 - Oxygen Version [e.g. 2.2 Alpha]

**Additional context**
*Add any other context about the problem here.*

**Comment by KittenCodes** [comment]
@msnetdesign Please run a plugin conflict test to see if another plugin is preventing the animation from working: https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/. If that doesn't help, please open a support ticket so that we can take a look at this for you: https://oxygenbuilder.com/support.

**Comment by msnetdesign** [comment]
THX, solved...found the buggy plugin...
