### ISSUE TITLE
Oxygen won't display dynamic data shortcode value

### ISSUE THREAD

**Issue by landiadeto** [soflyy/oxygen-bugs-and-features#1281]
**Describe the bug**
_After having updated my install to version 3.2, 3.3 and 3.4 RC1 Oxygen no longer displayed dynamic data in WooCommerce products and on the front-end overall. I have reproduced the bug in a sandbox successfully. I've updated from Oxygen 3.1.2 through WP plugin update._

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
*Yes*

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
*Yes, please read below as sandbox install is not really needed.*

**To Reproduce**
1. Edit any post, product or page
2. Add '[oxygen data='title] shortcode' to the page or any other similar shortcode
3. Save the post/product/page and view on the frontend.

**Expected behavior**
*Oxygen must return shortcode's value*

**What actually happens**
*It returns empty space instead of the shortcode's output.*

**Screenshots**
*N/A*

**Desktop (please complete the following information):**
- OS: [any]
 - Browser [any]
 - Oxygen Version [3.2 and above]

**Smartphone (please complete the following information):**
- Device: [any]
 - OS: [any]
 - Browser [any]
 - Oxygen Version [3.2 and above]

**Comment by KittenCodes** [comment]
@landiadeto I've not been able to replicate this on our Sandbox site. Please open a support ticket so that we can investigate the issue for you: https://oxygenbuilder.com/support.

**Comment by landiadeto** [comment]
I opened the support ticket on Feb 27, 2020, and it was replied by Phe. Sorry for being not clear enough. Please check this post on sandbox install where I have replicated the issue successfully: https://oxygen-q5tz9kztwd49k.oxygen-demo.qsandbox.me/hello-world/

**Comment by KittenCodes** [comment]
@landiadeto I understand, thank you.

It's not possible to use Oxygen's shortcodes in the WordPress content editor. They must be used within Oxygen's elements in the builder.

**Comment by landiadeto** [comment]
@KittenCodes Thanks for clarifying. Although it was working that way before version 3.2. I have checked it within the Oxygen editor and dynamic data is displayed fine there indeed.

**Comment by KittenCodes** [comment]
@landiadeto We prevented this behaviour for security reasons - it shouldn't have been possible to execute Oxygen's shortcodes from the WordPress content area.

**Comment by landiadeto** [comment]
@KittenCodes Thank you for elaborating on that as I must have missed this info from the changelog.
