### ISSUE TITLE
Custom SVG Icon Set not displayed in Oxygen template

### ISSUE THREAD

**Issue by LauraAmato** [soflyy/oxygen-bugs-and-features#1283]
**Issue**
I followed the tutorial on how to add a custom icon set (https://oxygenbuilder.com/documentation/other/custom-svg-icon-sets/). When selecting it in the template, it doesn't show any icons, as if the set was empty:

<img width="291" alt="Screenshot 2020-06-26 at 11 50 07" src="https://user-images.githubusercontent.com/67466456/85854563-e90a8b00-b7b4-11ea-9766-71c6287a94d7.png">

The file that I generated on IcoMoon doesn't seem to be broken, but I generated a new set just to make sure. I downloaded the files, added the new set to Oxygen, but still it doesn't show the icons. 

Info: I imported SVG icons (Font Awesome Light) to generate the custom set.

Any idea what went wrong?

**Comment by jamescrabb** [comment]
Did you make sure the title tag was exported in the svg’s from icomoon?

You need to select the cog and check the box so the file is exported with title tags.

I have also found that the svgs need to be square otherwise they don’t show up either.

**Comment by KittenCodes** [comment]
@LauraAmato Please ensure you've added the SVG titles (see: https://www.loom.com/share/ae1c88e4cec34c8fa5cec6a4cc47de06) and that the icon set contains two or more icons.

If you still have problems, please open a support ticket so that we can take a look: https://oxygenbuilder.com/support.
