### ISSUE TITLE
Easy Posts Feature Image not displayed on second Easy Post element added to a page or template

### ISSUE THREAD

**Issue by Cenay** [soflyy/oxygen-bugs-and-features#1285]
**Describe the bug**
Use case: Archive template for a specific category, and sidebar to displays all posts, all categories in descending date order.
The second Easy Posts element will not render the featured image within the template.

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
Yes

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
https://oxygen-qjjgaznmc649k.oxygen-demo.qsandbox.me/
Recreating this on the sandbox site was revealing. When I accepted the default install (Atomic) and added a second Easy Post the featured image rendered. When I installed the "design library" I installed on customer's site (Winery), I was able to reproduce the issue. You can see that here: https://oxygen-qjjgaznmc649k.oxygen-demo.qsandbox.me/category/work-productivity/

**To Reproduce**
1. Create/Edit template for Archives that includes an Easy Post - set to default on query
2. Add a second Easy Post element and set to custom on query, all "posts", order by date descending
3. Second Easy Post will not display the featured image, tho the rest of the content appears to be correct on a per post basis.
4. (Note, this is also possible in pages and posts, not just archive templates)

**Expected behavior**
I should be able to display the category posts (when user clicks the /category/category-name/ link), but also display "ALL" posts in sidebar, regardless of category.

**What actually happens**
A second or third **Easy Posts** will not display the faetured image, despite that template working when it's the only Easy Posts on the page. Please note I always use different queries when attempting to add a new **Easy Posts**, there are not attemping to display the "SAME" content. 

**Screenshots**
https://www.screencast.com/t/g2ddBq36 (image)
https://www.screencast.com/t/hgXA9nfHgUlT (video explanation)

**Desktop (please complete the following information):**
- OS: Windows 10 Pro
 - Browser: FireFox Developers Edition, Standard FireFox, FireFox Lite, Chrome, and Edge
 - Oxygen Version 3.3.1

**Smartphone (please complete the following information):**
Not applicable to this issue

**Additional context**
Winery Design Library
See the video above that details the issue.

**Comment by Spellhammer** [comment]
Thank you for the very thorough report.

In this case, the image in the second Easy Posts element wasn't showing because it was using a different template with some incorrect CSS:

```
%%EPID%% .oxy-post-image-fixed-ratio {
  padding-bottom: 100%;
  background-size: cover;
  background-position: center center;
}
```

This rule should have a width declaration as well. Adding width: 100% causes the image to start showing in the second Easy Posts element.

I suspect if you use the same exact template for both Easy Posts elements (e.g. duplicate the first one, change the query) it will always render images. If that's not the case, please re-open this with details and we'll investigate further.

**Comment by Cenay** [comment]
Interesting! I would add that the template for Winery was un-changed by me -- I comment the original out rather than delete. Chasing this bug lead me to documenting each template in the Winery theme, that when compared to the default (Atomic) shows some big differences. 

I'll call this one done (as I tried your add and it worked) but I would mention that maybe the template's CSS might need review, this wasn't original code by me, it was from within your template files. 

Thanks again for your help!

**Comment by Cenay** [comment]
**To Future Readers:** 
If you don't "select" a specific template on the main part of the page and just the one added when you insert an Easy Posts, then the CSS for THAT element will be used as the default for everything else (Easy Posts) on the page. The second Easy Posts (with the selected template whether edited by you or not) will be _more_ specific, but if it's missing elements defined in the parent, it won't over ride it. 

So doing as he states above didn't resolve my issue fully. I had to add the missing element to the CSS element with the most specificity, and ALSO update the parent element. 

To help clarify - the default CSS for the first Easy Posts contained: 
.oxy-post-image {
	display: flex;
	align-items: flex-start;
	justify-content: flex-start;
	width: 100%;
	**padding-bottom: 40%;**
	min-height: 120px;
	background-position: center center;
	background-size: cover;
    background: color(18);
}

And this was the specific child rule (more specific), but in my case, I wanted 0px padding on the bottom. So I updated to this. The bolded it was NOT a part of the original template but needed here to halt the behavior of squishing the main "archive" part of the page.

%%EPID%% .oxy-post-image {
  position: relative;  
  background-color: grey;
  background-image: repeating-linear-gradient(
  45deg,
  #eee,
  #eee 10px,
  #ddd 10px,
  #ddd 20px);
  width: 120px;  
  **padding-bottom: 0;**
  flex-shrink: 0;
  flex-grow: 0;
  margin-right: 10px;
  padding-top:0;
  margin-top:0;
}

Hope this saves someone else some time!

**Comment by Spellhammer** [comment]
That's a good point. Easy Posts CSS rules without %%EPID%% will be generic and apply to all Easy Posts. All of our default Easy Posts templates should have %%EPID%% to avoid this issue, but it sounds like Winery's templates specifically have some problems with that.

Thanks for the follow up.
