### ISSUE TITLE
Bug Installation and Responsive

### ISSUE THREAD

**Issue by AdrianVatavu000** [soflyy/oxygen-bugs-and-features#1287]
Hi, I have acquired the oxygen package.
1. With every installation of oxygen on a site I miss something about each one ... I downloaded the zip file several times and I installed oxygen many times and each time a component is missing.
2. I created a site with oxygen 3.3 on Desktop and if I try to make the changes on the Responsive side the changes are also shown on the Desktop side. In addition, on the Oxygen Backend it shows the responsive page in a way while when you open from your mobile phone or inspect it on google the indentation is totally different.
For example "https://hotelbristol.l4fenice.it/" on the Desktop side the site is ready while if you open it on the responsive side it is half the screen.
I hope I was clear.
I look forward to your reply.
Best regards
Web Developer Spuntolab
Vatavu Adrian

**Comment by louisreingold** [comment]
support@oxygenbuilder.com
