### ISSUE TITLE
Litespeed Cache: Page Optimization "HTML minify" isn't working with Oxygen

### ISSUE THREAD

**Issue by Netzlichter** [soflyy/oxygen-bugs-and-features#1289]
**Describe the bug**
Plugins:
Litespeed Cache Version 3.2.3.2
Oxygen Builder Version 3.4 RC 1

When "Page Optimization" - > HTML Minify is ON some Footer and Content Elements are not loading anymore.

**Comment by KittenCodes** [comment]
Not all HTML can be minified without causing problems.

**Comment by SimonErich** [comment]
Solved this issue here:
https://github.com/soflyy/oxygen-bugs-and-features/issues/1077#issuecomment-799178920
