### ISSUE TITLE
DONE: Make media query breakpoints adjustable

### ISSUE THREAD

**Issue by mishterk** [soflyy/oxygen-bugs-and-features#129]
There is one thing I always come up against in Oxygen and that is the slightly confusing language around media queries and their breakpoints in the editor. 

i.e; the editor uses the term 'less than 768px' when in actual fact the CSS media query is less than 
and including that 768th pixel. I know it seems like a bit of a nitpick, but 768px is an iPad in portrait mode which means I can never quite support that device properly as it ends up with the CSS intended for devices smaller than 768px. Here is a screenshot for reference:

![oxygen-breakpoints](https://user-images.githubusercontent.com/2113020/54061667-ed283780-4255-11e9-83ad-7db08049a9a1.jpg)

Understandably, changing this now would affect a lot of sites making that unfeasible. But, if there were some way to modify the media queries, this would be a nice little addition to Oxygen. 

Global settings would be great but even just some filters would be functional.

**Comment by LordWhisper** [comment]
It could keep the ones that are there and just give us the ability to add further ones and delete the ones we have. That way it wouldn't break anything unless you'd delete it yourself.

**Comment by Cenay** [comment]
I would like to add my "Up vote" on this feature request.

**Comment by Caffeinedesign** [comment]
i would think something like @LordWhisper's suggestion, something like a pool of 6 or 8 media queries, all customisable and wich can be activated in global settings (so if you need 3, you have less options around your UI)

**Comment by Budoman** [comment]
Why not just have an expanded list of ranged presets for today's common devices and also have the ability to modify them. Huge big 'ol "hell yeah" from me.

**Comment by JtothaL** [comment]
up voted

**Comment by benddesign** [comment]
Upvoted

**Comment by Martin-1** [comment]
You got my vote and especially including @LordWhisper his suggestion of adding my own and deleting others.

**Comment by fvpDev** [comment]
I am getting so tired of not being able to find a single customizable builder plugin/theme out there that can do this... Guys and gals, please check the following link out and let me know what you think:
https://www.freecodecamp.org/news/the-100-correct-way-to-do-css-breakpoints-88d6a5ba1862/

**Comment by louisreingold** [comment]
References to lizards, gitmo, and no logical argument about why his way is 100% correct - a bad article. He uses a lot of words to conclude you need four arbitrary numbers (why?). Oxygen also has four arbitrary numbers.

**Comment by louisreingold** [comment]
Anyway, I agree with the original suggestion in the OP.

**Comment by nickfmc** [comment]
Really there should just be a way to just add what ever breakpoints you want. Hate when builder designed sites hit a "breakpoint" and everything shifts and is "meh" for about 300px until you hit the sweet spot you designed it for.  I've just been enqueuing my own stylesheet for mobile styles. In this day and age you need to be using breakpoints on the fly when the content requires it.  You really shouldn't care how many pixels a given device has, this is taking things WAY back in time having set mobile breakpoints instead of a fluid design calling media queries when and where you need them.

**Comment by jamescrabb** [comment]
Would really like to see the ability to ADD my own breakpoints, simple solution to a big problem or include the css calc function into the UI somewhere

**Comment by perrelet** [comment]
+1 Bump

**Comment by Spellhammer** [comment]
Breakpoint editing introduced in Oxygen 3.2 Alpha 1.

**Comment by sassythewookie** [comment]
Was the ability to add custom breakpoints added too?

**Comment by jamescrabb** [comment]
> Was the ability to add custom breakpoints added too?

 Not as far as I’m aware, it’s still open here as feature request #700
