### ISSUE TITLE
Coding custom element

### ISSUE THREAD

**Issue by gmichel1994** [soflyy/oxygen-bugs-and-features#1290]
Hello Soflyy, 

i want to build a plugin for oxygen. I was very close to my aim but had some problems. 
My aim is to write a form builder inside oxygen. Now i am going to explain my issues. 

I have followed this [instruction](https://codewriteups.com/build-custom-oxygenbuilder-elements-in-wordpress.html?fbclid=IwAR18y78uzW0EY_HchwBaFJNZEO9Tn0QcC2ftDngNUgLB9R__d3IoAjVLldY).
The Problem with extending OxyEl was, that there will be an additional div surrounding my custom elements. 
So i have used jQuery to unwrap them. 
$=jQuery;
$("null").contents().unwrap(); // Null is my custom divwrapper which is going to be unwrapped

That caused that the the visualisation in the frontend was right, but the selector detector wasnt working fine in the backend. At reloading the visual builder it does not detect the elements. The solution would be to customize the elements that way that there will be no initial div wrapper around my custom elements.

So i have tried the way with extending CT_Components. 
The problem here is that my elements have no preview in the visual builder. 

How to fix this problem?

Is there a bettertutorial how to write extensions for oxygen?

Kind regards, 
Georgij

**Comment by KittenCodes** [comment]
@gmichel1994 Please see the tutorial here: https://codewriteups.com/build-custom-oxygenbuilder-elements-in-wordpress.html.

**Comment by vijaykumarim** [comment]
> @gmichel1994 Please see the tutorial here: https://codewriteups.com/build-custom-oxygenbuilder-elements-in-wordpress.html.

The link is not working Kitten. Can you please share new resource.
Thanks
