### ISSUE TITLE
Altering border width in reusable template element saves invalid CSS

### ISSUE THREAD

**Issue by Cenay** [soflyy/oxygen-bugs-and-features#1294]
**Describe the bug**
Updating and saving the reusable template part in Oxygen Builder saves the CSS with an invalid property (it is missing the "px" in the style rule border-left-width:12;)

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
*Yes/No*
Yes

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
*If yes, provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*
I did not setup Sandbox as I've tested it and reproduced it at will on two sites. I believe the behavior to be a global bug.

**To Reproduce**
1. Create a reusable element that contains columns
2. Add a border width of 12px to all sides around columns.
3. Save the reusable part and add to a page (I actually did this in reverse. I created page, added a new section for the author box and saved it as a reusable part. I later edited the reusable part)
4. Display the page and review the CSS in Developers Tools for the CSS. Invalid property as the "px" is not present.

**Expected behavior**
Saving changes to the border width should render in CSS with the missing px.

**What actually happens**
The CSS is created without the px on border widths. Regenerating the CSS will re-create the problem if you manually edit the oxygen generated CSS (after editing). So this isn't just in the builder, it's in the utility that regenerates the CSS.

**Screenshots**
Video reproducing the issue: https://www.screencast.com/t/c7Enf5OO25A9
Follow up video showing the regenerate issue: https://www.screencast.com/t/sBOzwXlVA2Eb

**Desktop (please complete the following information):**
- OS: [e.g. iOS] Windows 10 Pro
 - Browser FireFox (Dev Edition), Chrome and FireFox (standard)
 - Oxygen Version 3.3.1

**Additional context**
Video reproducing the issue: https://www.screencast.com/t/c7Enf5OO25A9

UPDATED to add follow up notes and video.

**Comment by KittenCodes** [comment]
@Cenay 

I've not been able to replicate this on a clean Sandbox site. If you're able to replicate it on a Sandbox site, please send me a link to the site so that I can take a look. You can create a Sandbox site here: https://oxygenbuilder.com/try/.

**Comment by Cenay** [comment]
For those of us who take the time to document, record and report bugs, **closing** this after a note to spend another hour to setup a sandbox site with all the required pieces and parts in an attempt to replicate the exact steps is a little frustrating. For example, this installation installed Atomic first, then installed (with a delete) the Winery theme. However, the Winery theme on another site is experiencing the same issue and it was the first theme installed. 

I can invite you into the site for exploration if you are interested in resolving this bug.

**Comment by Spellhammer** [comment]
Hey Cenay,

If we closed the issue and requested a sandbox replication, it means we followed your steps and the behavior did not present itself. If you'd like help on a non-sandbox site where this is occurring, we'd be glad to assist, but you'll need to submit a support ticket rather than a bug report: https://oxygenbuilder.com/support.
