### ISSUE TITLE
Container padding of added class not applied if "0"

### ISSUE THREAD

**Issue by Netzlichter** [soflyy/oxygen-bugs-and-features#1296]
**Describe the bug**
Hi there,
I make a section and add a class to that section. After that going to Advanced -> site & spacing -> Container padding -> setting all to 0. In backend the style is applied. But it frontend it isn't. it only happens with value = 0 and add that to a class.

Version 3.4 RC 2

**Comment by KittenCodes** [comment]
Duplicate: https://github.com/soflyy/oxygen-bugs-and-features/issues/720
