### ISSUE TITLE
Shortcode wrapper break dimensions/alignments

### ISSUE THREAD

**Issue by Deanphillips** [soflyy/oxygen-bugs-and-features#130]
Hey guys,

Shortcode wrappers don't seem to be working

https://www.useloom.com/share/6d4714e712a04b018d32508b33e1dfc0

Thanks

**Comment by petebytes** [comment]
@Deanphillips Here are other shortcode wrapper issues that you may want to look at.
https://github.com/soflyy/oxygen-bugs-and-features/issues/131
https://github.com/soflyy/oxygen-bugs-and-features/issues/86

**Comment by KittenCodes** [comment]
Hey @Deanphillips,

Unfortunately, I haven't been able to replicate this in the latest version of Oxygen. Please replicate it at https://oxygenbuilder.com/debug/, and send me a link to the page where the shortcode wrapper isn't working.
