### ISSUE TITLE
New feature add element

### ISSUE THREAD

**Issue by rayhan62** [soflyy/oxygen-bugs-and-features#1302]
**Describe the feature you'd like to see included in Oxygen.**
*A clear, detailed description of the feature you're requesting.*

**What are the use cases for this feature?**
*e.g. Accessibility, an e-commerce store that sells bicycles, etc.*

**Examples of this feature or functionality.**
*If another product has done it well, provide examples here.*

why you didn't add li element If you add li element people can create custom header..?

and why you didn't add a data attribute
All of this Element very helpful

**Comment by rayhan62** [comment]
If you add li element people can create a custom header,
you can see the webflow website they have li element,
please I really recommend for this element and data attribute,
All of this Element very helpful 👏👏👏👏

**Comment by KittenCodes** [comment]
https://github.com/soflyy/oxygen-bugs-and-features/issues/1402
