### ISSUE TITLE
Woo-commerce addon checkout page issue.

### ISSUE THREAD

**Issue by JadeTaylorAu** [soflyy/oxygen-bugs-and-features#1303]
Woo-commerce addon checkout page issue.

When you build a checkout page with the oxygen builder, The checkbox for the email signup (Klaviyo integration) has disappeared and the checkbox for the create account, etc, have stopped working when you click them.

They were working on the default page before I went into the builder and added the checkout page module to properly set up and edit the page.

I then backed up my site and deleted the oxygen builder modules from the page so it went back to the default woo page and it works again but now I can edit or style the page.

I took screenshots but don't know how to send as I've never used Github before.

Looks like it could be css but not a coder so not completely sure.

Not sure if there are issues anywhere else on the site, I just noticed it on the checkout page.

Can't really launch the site without this working.

**Describe the bug** 
*A clear and concise description of what the bug is.* 

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?** 
*Yes/No* 

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?** 
![Screenshot (83)_LI](https://user-images.githubusercontent.com/67833044/86515182-938c4900-be5a-11ea-96b2-07c10ef2ea1c.jpg)
![Screenshot (85)_LI](https://user-images.githubusercontent.com/67833044/86515186-95eea300-be5a-11ea-9110-2cd6fca65e17.jpg)

*If yes, provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*

**To Reproduce**

**Expected behavior**
*A clear and concise description of what you expected to happen.*

**What actually happens**
*A clear and concise description of what happens instead of the expected behavior.*

**Screenshots**
*If applicable, add screenshots to help explain your problem.*

**Desktop (please complete the following information):**
 - Oxygen Version [e.g. 2.2 Alpha]

**Smartphone (please complete the following information):**
 - Oxygen Version [e.g. 2.2 Alpha]

**Additional context**
*Add any other context about the problem here.*

**Comment by KittenCodes** [comment]
@JadeTaylorAu Please open a support ticket - we will need to take a look at your site: https://oxygenbuilder.com/support.
