### ISSUE TITLE
Properties showing in the fields  when working with responsiveness

### ISSUE THREAD

**Issue by ubuntuproductions** [soflyy/oxygen-bugs-and-features#1304]
Hello!! ❤️

In new to Oxygen and I’m loving it. But when I was working to adapt the page in building to mobile devices I realized that it was something that slowed down my workflow. When I was working with the different breakpoints I realized that the field of the properties did not indicate the value that is set in the “all sizes” selector. For example, I needed to adapt the text size and when selecting a smaller screen size or breakpoint, I could not see in the field the size of the text (in the darker grey for example), many times I would have to come back to the “all sizes” tab, check the size of the text again, change the screen size again and type the new text size. 

Working with one property at a time might not be a big deal, but sometimes I would try to change text size, let’s say margin and width and I world have to go back and forward to refresh the values of the diverse field, losing quite a bit of time honestly. 

Hope you can add this functionality. Love.

**Comment by MimiDev** [comment]
Yep, I have to go through this ALLL the time. Would be nice to have any pre-existing values displayed when going down to smaller screen sizes.

**Comment by ubuntuproductions** [comment]
@MimiDev Yes, exactly. 👍

**Comment by githrun** [comment]
Yes please implement this -  my workflow is so slow because of this.  Having to check every device above it, every time I want to update a field.

**Comment by schietegal** [comment]
+1

**Comment by Daniel-Florian** [comment]
+1!!
This would be a huge improvement to my workflow also

**Comment by aureldelic** [comment]
I feel this is a must. Too many times switching around breakpoints to see what changes I made. Make it so they are marked and greyed out so we know easily what we did..

**Comment by ubuntuproductions** [comment]
This will be implemented on Oxygen V4 🎉💚🙏🏽
