### ISSUE TITLE
Errors after update to 3.4

### ISSUE THREAD

**Issue by IADDIC** [soflyy/oxygen-bugs-and-features#1307]
**Describe the bug**
*Wordpress error messages.*

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
*Yes*

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
*No*

**To Reproduce**
1. Turn on WP error display in wp-config
2. // Enable Debug logging to the /wp-content/debug.log file
define( 'WP_DEBUG_LOG', true );

// Disable display of errors and warnings 
define( 'WP_DEBUG_DISPLAY', true ); 
@ini_set( 'display_errors', 0 );

**Screenshots**
![image](https://user-images.githubusercontent.com/4072655/86633606-79578580-bf96-11ea-9301-7fd1ee37f575.png)

**Comment by Hud1ai2** [comment]
I have the same issue. Is it possible, please, to download version 3.3 somewhere? Please could you make this for us to have always newest and older version to download? For these cases. Thanks.

**Comment by KittenCodes** [comment]
@Hud1ai2 Please open a support ticket - we can then send you a copy of v3.3.1: https://oxygenbuilder.com/support.

**Comment by KittenCodes** [comment]
Fixed in v3.6.
