### ISSUE TITLE
Add Rem unit on every element

### ISSUE THREAD

**Issue by saysonjerald** [soflyy/oxygen-bugs-and-features#1309]
**Describe the feature you'd like to see included in Oxygen.**
Rem unit is very useful when it come to scaling the website from large desktop to mobile device view. 
Setting the default font size inside the HTML TAG will affect all the child elements below it with rem units on it. If want to scale my website down all i need to to is to add media query and inside the media query then only change the font size and all the child element will be affected with rem units on it.  Em unit are good but they are not more powerful than Rem unit.

**What are the use cases for this feature?**
Mobile responsiveness,

**Examples of this feature or functionality.**
Scalability, Flexibility, Ease of Use

check out my project where I used rem.
https://www.frontendmentor.io/solutions/responsive-page-using-css3-sass-and-bootstrap-xUwvdH0fO

you can download the my files on github and check on how I use rem unit.

**Comment by KittenCodes** [comment]
Implemented in Oxygen 3.6 alpha 1.

**Comment by saysonjerald** [comment]
Amazing ^_^ love you guys
