### ISSUE TITLE
[2.2] Serious issue with Shortcode Wrappers corrupts page content and breaks Oxygen editor

### ISSUE THREAD

**Issue by petebytes** [soflyy/oxygen-bugs-and-features#131]
*For me this is a CRITICAL issue and is impacting a production digital content site.
For others that may need to use shortcodes I would think they feel the same: 
- Corrupted content structure showing wrong content or missing content.
- Inability to use Oxygen editor to fix the content.
Note: you can fix it by manually modifying the editor shortcodes.  However not knowing how it breaks to begin with is not a very comforting position.

**Describe the bug**
When using Shortcode Wrappers the page can break the content structure of the page (showing incorrect content or missing content) and unable to use Oxygen UI.

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
*Yes

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
*No, I have provided environment where the issue exists, but unable to determine specific steps to reproduce.
However the problem domain is narrowed down to pages using shortcodes. And the specific data corruption has been identified.
It seems to happen after saving the page but it does not happen every time, thus making reproduction very difficult.

**Expected behavior**
The ability to use Oxygen Shortcode wrappers without corrupting the page.

**Screenshots**
**Corrupted Content**
![image](https://user-images.githubusercontent.com/676739/54090142-4368a980-432e-11e9-82eb-f76ce4c592a6.png)

**Unable to use Oxygen editor for fix the issue**
![image](https://user-images.githubusercontent.com/676739/54090184-ab1ef480-432e-11e9-8757-f5959ed428fc.png)

**Corrupted Oxygen structure**
![image](https://user-images.githubusercontent.com/676739/54090424-516bf980-4331-11e9-8cce-b2afb6904773.png)

**What actually happens**
https://courageous-journeys-public.s3.amazonaws.com/ShortCodeWrapper-issue.mp4

**Desktop (please complete the following information):**
- OS: macOS 10.14.3
 - Browser: Firefox 65.0.1
 - Oxygen Version: 2.2

**Comment by petebytes** [comment]
Any updates on this?

**Comment by KittenCodes** [comment]
Hi @petebytes,

Please can you let me know if you're still experiencing this in the latest version of Oxygen (currently 2.3)?
