### ISSUE TITLE
Undefined Index (shape dividers)

### ISSUE THREAD

**Issue by twistedpixel** [soflyy/oxygen-bugs-and-features#1312]
**Describe the bug**
PHP error: "Undefined index: custom_shape in {REDACTED}/wp-content/plugins/oxygen/component-framework/components/classes/shape-divider.class.php on line 240"

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
Yes

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
No because you have not made the latest update of Oxygen available there. 

**To Reproduce**
1: create 4 shape dividers (2 top, 2 bottom)
2: profit

**Expected behavior**
No error

**What actually happens**
All 4 shape dividers appear but also error appears.

**Desktop (please complete the following information):**
Should be irrelevant as PHP error but latest version of macOS Mojave, Safari 13.1.1
latest version of Oxygen (3.4 I believe)

**Comment by KittenCodes** [comment]
Fixed in v3.6.
