### ISSUE TITLE
CSS from code block is added to the bottom of the page. Should load before markup.

### ISSUE THREAD

**Issue by chrishaff** [soflyy/oxygen-bugs-and-features#1313]
**Describe the bug**
When adding CSS using a code block then even if I place the block first the CSS code appears at the bottom of the markup causing an incorrect rendering followed by a redraw. The positioning of the code block should be significant and work as implied in the builder interface. Generally CSS should always come before markup, no?

From the  sandbox: 
Builder - https://i.imgur.com/WyPKDQt.png
Generated code - https://i.imgur.com/XkURUsi.png

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
https://oxygen-qq7y5pdwd796.oxygen-demo.qsandbox.me/sample-page/

**Desktop (please complete the following information):**
 - Oxygen Version 3.3.1

**Comment by KittenCodes** [comment]
@chrishaff Please use a stylesheet via Manage > Stylesheets in the top right of the builder - the CSS will then be loaded in the head.

**Comment by chrishaff** [comment]
So you're not going to fix this?
