### ISSUE TITLE
Not editable and displayed components in the builder - e.g. woocommerce and pro menu 

### ISSUE THREAD

**Issue by suitocortez** [soflyy/oxygen-bugs-and-features#1315]
After patching to 3.4 the woocommerce components can neither be seen nor edited in the builder. 
Also the Pro Menu does not get displayed. I can see it in the right Structure tab but not in the editor.

I have tried the troubleshooting steps. 

Happens on ...
Windows 10 [Chrome, Edge]
Google Pixel 3 [Chrome]

Wordpress up to date
Oxygen Version 3.4

![woo-oxy](https://user-images.githubusercontent.com/67983412/86862392-6396ad00-c0c9-11ea-8c18-f71793155228.jpg)

**Comment by KittenCodes** [comment]
@suitocortez Please open a support ticket so that we can take a look at this for you: https://oxygenbuilder.com/support.
