### ISSUE TITLE
Pro Menu's Sub menu jumping when i try to open

### ISSUE THREAD

**Issue by tech2win** [soflyy/oxygen-bugs-and-features#1317]
**I Develop a website for my client using oxygen every thing is ok except 1 or 2 things so i need your help to solve my problem no 1 which is Related to pro menu i created a menu for website (https://appsquare.com.au/new-as) and when i try to open sub menu in mobile page jump automatically to website's another page... check here https://appsquare.com.au/new-as ** i tried every thing which is mention in fb and here https://github.com/soflyy/oxygen-bugs-and-features/issues/932

Please guide me how to solve this issue its urgent i have a project delivery with in 3 days 

**To Reproduce**
1. Go to 'https://appsquare.com.au/new-as' mobile version (iOS or android )
2. Click on 'Menu and click on We can help with.... '

*

**Desktop (please complete the following information):**
- OS:  iOS
 - Browser chrome, safari
 - Oxygen Version [e.g. 3.4 ]

**Smartphone (please complete the following information):**
- Device: [e.g. iPhone8plus and iPhoneX, Remdi note 7 pro]
 - OS:  iOS 13
 - Browser: chrome
 - Oxygen Version [e.g. 2.2 Alpha]

**Additional context**
*Add any other context about the problem here.*

**Comment by KittenCodes** [comment]
@tech2win Please open a support ticket so that we can take a look at this for you: https://oxygenbuilder.com/support.
