### ISSUE TITLE
Add the ability to save classes and set a default style for elements.

### ISSUE THREAD

**Issue by Flipback8** [soflyy/oxygen-bugs-and-features#1320]
**Describe the feature you'd like to see included in Oxygen.**
It would be great if you can save classes so you don't have to configure elements every single time. 

**What are the use cases for this feature?**
Let's say you have something styled like a button and you have all of its states configured, button rounded, and styled. You don't want to have to restyle everything every single time. 

**Examples of this feature or functionality.**

Drop an element onto a page already styled based on classes you have pre-configured once before.

**Comment by Spellhammer** [comment]
This is how Classes work in Oxygen currently.

Create a .button class, style your button element. Every time you add a new button, just add the .button class to inherit those styles.

Iterate on that class with modifications like .button--large or .button--small or whatever you want to do.

Do you mean the ability to have a class applied to an element automatically when it's added?
