### ISSUE TITLE
[USABILITY REQUEST]  Gradient is missing the blue dash indicator for style applied here

### ISSUE THREAD

**Issue by YammYcoding** [soflyy/oxygen-bugs-and-features#1321]
Know that blue dash to indicate on UI that a style was applied there ?

I just miss this dash over the background > gradient spot.  I have style there, but have no means to know it, only cliking inside to see.

I hope it helps :)

https://prnt.sc/tf4z1k

**Comment by KittenCodes** [comment]
Known issue: #64
