### ISSUE TITLE
[USABILITY REQUEST] give us a Wrap with Link ! 

### ISSUE THREAD

**Issue by YammYcoding** [soflyy/oxygen-bugs-and-features#1322]
Here is the problem:
1. add image
2. forget the link
3. have to add a link wrapper
4. and move image to inside of it ( this process takes too much time )

Solution: Give as a wrapp with Link on the structure element :)

https://prnt.sc/tf5gwt

**Comment by KittenCodes** [comment]
Click the link icon at the top of the properties pane on the left.

**Comment by YammYcoding** [comment]
> 
> 
> Click the link icon at the top of the properties pane on the left.

Rofl, I never noticed that, haha thanks !
