### ISSUE TITLE
[USABILITY REQUEST] This tiny border is very hard to see on a large monitor

### ISSUE THREAD

**Issue by YammYcoding** [soflyy/oxygen-bugs-and-features#1323]
This border is for ants - I have to squish my eyes and come closer to monitor in order to see the tiny dark border on the selected button. Sometimes it shows this grey outline instead of the blue active color. I wonder why they did that..... bug ? intended ? If so, please my eyes are tired, give us a better readability there! :)

https://prnt.sc/tf5vk7

**Comment by louisreingold** [comment]
https://www.eyebuydirect.com/

**Comment by YammYcoding** [comment]
> 
> 
> https://www.eyebuydirect.com/

It's funny but try seeing that on a 28" monitor at 3 am in the dark, with dark mode :D It's hard, man! Seriouslly! 

If you want to make it different than the blue color, maybe do another color, instead of that tiny border, a light green, or something, anything is better, believe me! :)
