### ISSUE TITLE
DONE: Please Add Shortcode Functionality in the Toggle & Tab Components

### ISSUE THREAD

**Issue by mikee77777** [soflyy/oxygen-bugs-and-features#1324]
There are both aesthetic and SEO related reasons to place shortcodes into both toggles, tabs and accordions. Shortcode generated content is not being respected by the toggle.

The Divi theme has done a good job using toggles that have a both a visual and html text editor available that recognizes shortcodes. This is honestly the main reason why I have been using Divi on client projects, but it is so slow!!

https://www.elegantthemes.com/documentation/divi/toggle/

**Comment by mikee77777** [comment]
I had to dig deeper and found it was already a feature.

**Comment by KittenCodes** [comment]
Added in v3.6.
