### ISSUE TITLE
Slider images jump during fade transition

### ISSUE THREAD

**Issue by paulnaude** [soflyy/oxygen-bugs-and-features#1325]
I can illustrate some weird behaviour on this sand box page with the slider element:

The second slider's images jump between 4 and 1 as well as between 2 and 3, but ONLY when set to FADE, not when set to HORIZONTAL.

http://impartial-deer.w6.wpsandbox.pro/slider-page/

It is a problem I have on our company website too, but only when the sliders are stacked (narrow screen) not when next to each other (wide screen): https://simteq.co.za/
![homepage jump](https://user-images.githubusercontent.com/23168020/87163908-5267bf00-c2c8-11ea-948b-08a75dfa7989.jpg)

**Comment by KittenCodes** [comment]
@paulnaude 

You can prevent this behaviour by setting the slide to "Stack child elements horizontally". You then need to set the Horizontal Item Alignment to "Center" and the Vertical Item Alignment to "Middle". Next, add a Div to the slide, set the Horizontal Item Alignment to "Center". Move the image and the text into the Div.

You should now see it working correctly on the front-end of the site. Please note that I was only able to see the jump on the Slide 1 > Slide 2 transition.

**Comment by paulnaude** [comment]
Thanks I will try this.

Regards
Paul Naudé
