### ISSUE TITLE
Borders width separtly dont work

### ISSUE THREAD

**Issue by Rensoconese** [soflyy/oxygen-bugs-and-features#1326]
**Describe the bug**
*A clear and concise description of what the bug is.*

Setting each bordersto a div don't work

I set 24px for top left and right 0 to bottom
the result is 1px because the browerser don't take the PX in the number.

**Comment by KittenCodes** [comment]
@Rensoconese Please open a support ticket so that we can take a look at this: https://oxygenbuilder.com/support.
