### ISSUE TITLE
Codeblock with ACF relationship field give different results in template and frontend

### ISSUE THREAD

**Issue by mzayani** [soflyy/oxygen-bugs-and-features#1328]
**Describe the bug**
A codeblock to show an ACF relationship filed work and results visible in the template, but in the frontend it is not working

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
*Yes*

**To Reproduce**
1. create an ACF relationship filed and link it to a post
2. create Oxy template for the single post with a codeblock to show the relationship content
3. the code block is as per https://www.advancedcustomfields.com/resources/relationship/

**Expected behavior**
See the relationship content in the template and the frontend

**What actually happens**
Output is OK in the template preview, but in the front end result is always refereing to the actual post

**Screenshots**
<img width="717" alt="frontend" src="https://user-images.githubusercontent.com/6707843/87222461-d7b0a980-c384-11ea-815e-775d3cc18023.png">
<img width="1049" alt="in the template" src="https://user-images.githubusercontent.com/6707843/87222470-de3f2100-c384-11ea-808b-cf48b754fc40.png">
<img width="662" alt="codeblock" src="https://user-images.githubusercontent.com/6707843/87222630-53f7bc80-c386-11ea-90d7-4cd0005d2dbc.png">

**Desktop (please complete the following information):**
- OS: MacOS
 - Browser Firefox
 - Oxygen Version 3.4

**Comment by KittenCodes** [comment]
@mzayani I suspect you need to add:

```
$post_id = get_the_ID();
```

To the top of your code and then adjust your code so that get_field uses the current post ID.

You will then need to adjust your code further so that "the_permalink", "the_title" etc use the ID from the $post variable, rather than the current post (which is what will be used automatically).
