### ISSUE TITLE
Add Offset field to built-in smooth scroll option

### ISSUE THREAD

**Issue by Spellhammer** [soflyy/oxygen-bugs-and-features#133]
**Describe the feature you'd like to see included in Oxygen.**
Add the ability to specify Offset in px for built-in smooth scrolling.

**What are the use cases for this feature?**
More control over final position of viewport when smooth scrolling. This would allow us to avoid awkward overlaps of sticky headers, etc.

**Examples of this feature or functionality.**
Self explanatory.

**Comment by alriksson** [comment]
Any workaround until this is implemented?

**Comment by KittenCodes** [comment]
You can use jQuery. Here's an example that offsets the scroll by the height of the header.

```js
var $header = jQuery('#_header-20-15');

jQuery('a[href^="#"]').click(function(e){
	e.preventDefault();
	jQuery('html,body').animate({scrollTop:jQuery(this.hash).offset().top - $header.height()}, 750);
});
```

**Comment by alriksson** [comment]
@KittenCodes Many thanks!

**Comment by KittenCodes** [comment]
> It works but it also seem to remove the #anchor-jump-to-url in the address bar?

Yes, I think it does remove the #link from the address bar.

**Comment by alriksson** [comment]
Yep, I would like to keep that. Do you have a workaround but keeping #anchor-link ?

**Comment by KittenCodes** [comment]
@alriksson I'm sorry, but I don't have a workaround to keep the #link.

**Comment by alriksson** [comment]
Ok, hope to see everything working once this is added natively in oxygen.

**Comment by alriksson** [comment]
@KittenCodes When using a modal and clicking on it I see following error in the console:

```
:formatted:5107 Uncaught TypeError: Cannot read property 'top' of undefined
    at HTMLAnchorElement.<anonymous>
    at HTMLAnchorElement.dispatch 
    at HTMLAnchorElement.v.handle
```

**Comment by vecchionico** [comment]
> @KittenCodes When using a modal and clicking on it I see following error in the console:
>

I stumbled upon the same issue... A quick workaround is to use a more specific selector, e.g.:

```
jQuery('.myclass a[href^="#"]').click(function(e)
```

This way modals are not affected by the code

**Comment by alriksson** [comment]
@vecchionico Thanks do you also get `Uncaught SyntaxError: Unexpected identifier on line #12`

Which in my case is:

```
jQuery('.js-toc-content a[href^="#"]').click(function(e)
	**e.preventDefault();**
	jQuery('html,body').animate({scrollTop:jQuery(this.hash).offset().top - $header.height()}, 750);
});
```

**Comment by vecchionico** [comment]
@alriksson nope, sorry, using the more specific selector I do not get any error

**Comment by alriksson** [comment]
`Uncaught SyntaxError: Unexpected identifier on line #12` is within the code block and the javascript editor in oxygen.

I do unfortunately  also get a console error in the frontend in the console `Uncaught SyntaxError: Unexpected identifier`

**Comment by alriksson** [comment]
@KittenCodes cause issues with tocbot script so can not use it.

Would be nice to see this built into the builder and hopefully a table of content element.

Any other solution to fix the off-set?

**Comment by porg** [comment]
Proposing to close this issue because according to your [3.8 release notes](https://oxygenbuilder.com/2021/06/11/oxygen-3-8-now-available/) this feature is already implemented.

**Comment by porg** [comment]
#2459 would be the improved version of this feature here.
