### ISSUE TITLE
Variation Images Does Not Work When Using the "Product Images" Element for WooCommerce

### ISSUE THREAD

**Issue by touchdowntech** [soflyy/oxygen-bugs-and-features#1330]
The product image does not change for variable products when variation images are used.

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
No but [others on Facebook have expressed the same problem](https://www.facebook.com/groups/1626639680763454/permalink/2911150245645718) with the only solution to use the "Product Builder" element instead. 

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?** The Sandbox does not have WooCommerce installed.

**Expected behavior**
The product image should change with the variation selections.

**What actually happens**
Only the featured image is displayed.

**Desktop (please complete the following information):**
- OS: MacOS
 - Browser Chrome
 - Oxygen Version 3.4

**Comment by KittenCodes** [comment]
@touchdowntech You need to use the Product Builder element - you can move your design inside it which will overwrite the default layout. The Product Builder is required as it adds additional code that is needed for the elements you've added to function correctly.

**Comment by jasperf** [comment]
We are using the product builder. And once builder is added you can add items like cart buttons and images. But now I read somewhere on the Facebook group that I cannot use separate items to display variants? Is that true? That would be really limiting the builder as you can then no longer move these items freely around. Hope to hear back on this soon.

**Comment by jasperf** [comment]
Hmm even when I do a product builder in that location and add product images below it I still do not see image change on choosing color variation. All variations have been added with prices and images so do not think that is the issue here.

**Comment by jasperf** [comment]
I see now. When I do add pricing under same product builder it does switch. But under separate ones or simply separate and not under the same one where the image is does not allow loading new image.

**Comment by touchdowntech** [comment]
> @touchdowntech You need to use the Product Builder element - you can move your design inside it which will overwrite the default layout. The Product Builder is required as it adds additional code that is needed for the elements you've added to function correctly.

Thank you for clarifying. I didn't realize that the Product Builder element is a "container". Works great!
