### ISSUE TITLE
Link with Current Page State

### ISSUE THREAD

**Issue by yepyeh** [soflyy/oxygen-bugs-and-features#1332]
**Describe the feature you'd like to see included in Oxygen.**
*A clear, detailed description of the feature you're requesting.*
Ability to add a Current Page State to a Link or a Button or Link Wrapper.

**What are the use cases for this feature?**
*e.g. Accessibility, e-commerce store that sells bicycles, etc.*
I created a Header Menu, like a custom mega menu, using Link Wrappers. I would like to add a Current Page State. For example if page is About Us, the About Us link will have a border.

**Examples of this feature or functionality.**
*If another product has done it well, provide examples here.*
A link with current page state.

If someone knows a solution, please let me know.

Thanks

**Comment by KittenCodes** [comment]
You can add a class to the current item using jQuery. Here's an example - you would need to modify it based on your requirements:

```
jQuery(function () {
    setNavigation();
});

function setNavigation() {
    var path = window.location.pathname;
    path = path.replace(/\/$/, "");
    path = decodeURIComponent(path);
  
    jQuery(".shop-archive-menu").each(function () {
         
        var href = jQuery(this).attr('href');
      
        if (href.indexOf(path) >= 0) {
            jQuery(this).closest('a').addClass('active');
        }
    });
}
```
