### ISSUE TITLE
3.4 Broke the USER ID Condition

### ISSUE THREAD

**Issue by legalassoc** [soflyy/oxygen-bugs-and-features#1334]
**Describe the bug**
*A clear and concise description of what the bug is.*

The USER ID Condition cannot accept ACF field values, meta values, or even php function return values in 3.4
However, it does work if you manually type in the User ID.

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
Yes

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
Yes
*If yes, provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*
http://super-antelope.w5.wpsandbox.pro/sample-page/

**To Reproduce**
1. Go to this sandbox site http://super-antelope.w5.wpsandbox.pro/sample-page/
2. Go to users and click on login as demo 
3. Go to this page http://super-antelope.w5.wpsandbox.pro/sample-page/

**Expected behavior**
Should show the text "This should only show on the demo user"

**What actually happens**
But instead, it shows "This should only show NOT on the demo user"

**Screenshots**
*If applicable, add screenshots to help explain your problem.*

**Desktop (please complete the following information):**
- OS: Pop-OS
 - Browser Chomre
 - Oxygen Version 3.4

**Smartphone (please complete the following information):**
- Device: Galaxy note 9
 - OS: Android 
 - Browser Chrome
 - Oxygen Version 3.4

**Additional context**
*Add any other context about the problem here.*

**Comment by KittenCodes** [comment]
Fixed in v3.5.
