### ISSUE TITLE
Menu Header 

### ISSUE THREAD

**Issue by Trentburns97** [soflyy/oxygen-bugs-and-features#1336]
There is a problem with the header builder where you cannot make the left or right header row different colors when set to full width and have that color go the entire way to the side of the screen. You can change the header row section background colors but it will not go the entire way to the side of the screen and will leave a gap. I do not know how to fix this.

**Comment by KittenCodes** [comment]
Please set the Header Builder to full-width via Advanced > Size & Spacing. You will see a dropdown - set it to "full-width" instead of "page-width". You may also want to set the padding to 0.
