### ISSUE TITLE
[USABILITY REQUEST]  this select auto hover must go

### ISSUE THREAD

**Issue by YammYcoding** [soflyy/oxygen-bugs-and-features#1338]
![image](https://user-images.githubusercontent.com/1200923/87363419-8270c580-c547-11ea-8dd4-f8ee99a80dcc.png)

The problem: when I go to select a color ( and I do this a lot ), the dam font family select happens to automatically hover on top of the text color.
I have stop what I was doing to look at cursor, slowly move around of it, just to get the cursor onto the text color. This happens everytime. I don't know you guys, but this bugs me a lot.

My request: turn this select hover off, for god sake !  :)

**Comment by KittenCodes** [comment]
@YammYcoding Please can you let me know where you're changing the colour and what element it is? I've never seen this occur.

**Comment by YammYcoding** [comment]
Looks like the problem is gone. Now when I hover the text color balls, the font select no longer appears on top of it. It might have been fixed a couple patches ago....
