### ISSUE TITLE
Wrong CSS value in Flexbox Child Controls

### ISSUE THREAD

**Issue by andreslotta** [soflyy/oxygen-bugs-and-features#1341]
**Describe the bug**
When using the Flexbox Child Controls for a div and setting Align Self to `right` the element gets a css value of `right` instead of `flex-end` for the `align-self` property.

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
Yes.

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
Yes. http://excited-cat.w6.wpsandbox.pro/flexbox-child-controls/.

**To Reproduce**
1. Create a new page.
2. Insert a section.
3. Insert a div into the section.
4. Insert a text element into the div.
5. Select the div, go to "Advanced > Layout >> Flexbox Child Controls >> Align Self" and choose `right`.

**Expected behavior**
The div should be right aligned within the section.

**What actually happens**
The div stays left aligned. In the browser's developer tools you see something like ~~align-self: right;~~.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/12016014/87393808-0316dc80-c5af-11ea-95c8-a15fcb18b1a6.png)

**Desktop (please complete the following information):**
Device and browser independent.
 - Oxygen 3.4

**Smartphone (please complete the following information):**
Device and browser independent.
 - Oxygen 3.4

**Additional context**
I'm sure you can fix that... ;-)

**Comment by KittenCodes** [comment]
#259

**Comment by andreslotta** [comment]
Sorry. Missed that one...
