### ISSUE TITLE
Product Builder breaks when child divs, columns etc are added as child elements.

### ISSUE THREAD

**Issue by damienlee77** [soflyy/oxygen-bugs-and-features#1342]
When the product builder is used and laid out with internal columns etc, all displays correctly on the backend, but on the frontend, the builder element, its parent element and siblings all are missing. Phe was able to replicate this problem on a clean sandbox site so this bug should be confirmed. I thought that he posted this bug here, but couldn't find it. This problem effectively makes Oxygen Builder unusable at present for WooCommerce sites.

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
Yes

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
Yes, consult with Phe as he has recreated the problem in a sandbox.

**To Reproduce**
1. Create a single product template.
2. Add a Product Builder element
3. Include any div or column etc
4. Add product builder child elements including, in particular, the product image.
5. Save and open on front end for the vanishing act!

**Expected behavior**
Any child element should be able to be nested inside of the product builder element.

**What actually happens**
Unknown, but the entire elements of the product builder, as well as its parent, appear to vanish from frontend code.

**Desktop (please complete the following information):**
- OSX Caterlina
 - Chrome
 - Oxygen Version 3.4

**Additional context**
This problem has been discussed with Phe. Given the impact of this problem, I think it should be considered extremely urgent.

**Comment by damienlee77** [comment]
Further work on this by Phe and testing by myself has shown that if the product builder is placed within a section rather than a div, that it appears to resolve the issue. Clearly still a bug, but this may help nail why so thought it worth mentioning in here.

**Comment by damienlee77** [comment]
> Further work on this by Phe and testing by myself has shown that if the product builder is placed within a section rather than a div, that it appears to resolve the issue. Clearly still a bug, but this may help nail why so thought it worth mentioning in here.

Nope, after further testing this comment above is incorrect and a parent section doesn't resolve the issue. This issue is MAJOR and critically can effectively brick someone's WooCommerce site if they edit their single product page while this issue exists. I'm just lucky in that I have not gone live with my oxygen rebuild yet, so am not losing money.

Please address this issue urgently with an update! I am happy to discuss in chat to help resolve this problem ASAP if it helps.

**Comment by KittenCodes** [comment]
Fixed in v3.5.
