### ISSUE TITLE
Copy / Paste styles/effects

### ISSUE THREAD

**Issue by Zyles** [soflyy/oxygen-bugs-and-features#1343]
**Describe the feature you'd like to see included in Oxygen.**

I would like an easy way to copy and paste styles between two elements. For example: I designed a heading with text shadow, uppercase and white.

Then I made a second heading by duplicating the first one.

Now if I wanted to change the style of heading 1 I need to change the style of heading 2 manually instead of changing it once and copying the styles over to the other headings.

**What are the use cases for this feature?**

Save time.

**Examples of this feature or functionality.**

Changing multiple elements faster that need the same style, such as headings and buttons.

**Comment by KittenCodes** [comment]
#36
