### ISSUE TITLE
Functionality to arrange product using price in ascending or descending order on product list

### ISSUE THREAD

**Issue by gagankhatri** [soflyy/oxygen-bugs-and-features#1347]
With oxygen + woocommerce builder, I was able to use product builder and place Product list element on any page, but was not able to sort the products with Price.
Currently there are options for title, date, etc.... but not for Price, which I believe is the must.
Can pricing can be added on the list.

**Comment by KittenCodes** [comment]
You can change this in the WooCommerce settings via Appearance > Customize in the WordPress admin area.
