### ISSUE TITLE
DONE: Have a detailed management of user rights in Oxygen

### ISSUE THREAD

**Issue by pdubhol75** [soflyy/oxygen-bugs-and-features#1348]
Hello,

Oxygen does not currently have a fine user rights management logic. And yet this is very important. This functionality is highly developed in competitors such as Elementor.

Can you tell me if such a development is planned for Oxygen in the coming months ? Because Oxygen really allows you to do everything except manage user rights. 

That's all it lacks and I think that's essential.

Best regards,
Patrick

**Comment by mayankguptadotcom** [comment]
@pdubhol75 - honestly this doesn't help anyone understand the correct requirement. Would you be more specific please? https://oxygenbuilder.com/documentation/other/role-manager/

from what I already know, elementor doesn't offer much different from what Oxygen is already doing in user capability management part.

**Comment by simonclay** [comment]
Elementor allows these rights for Users:
 - No access to Elementor Editor
 - Limited access to Elementor Editor (ability to edit text and images only, not design/layout. Great for allowing clients to edit on-page).
 - Full access to Elementor Editor.

**Comment by Spellhammer** [comment]
Implemented in Oxygen 3.6 alpha 1.
