### ISSUE TITLE
Elegant Custom Fonts bug

### ISSUE THREAD

**Issue by mupersan** [soflyy/oxygen-bugs-and-features#1349]
**Describe the bug**
= Added custom fonts and followed the tutorial here https://wpdevdesign.com/video-how-to-add-custom-fonts-in-oxygen/. After doing so, the fonts are indeed added to the font dropdown. However, upon selecting the font I added to change a content, the text changed into a times new roman type of font. It doesn't show the exact style font I added.

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
*Yes/No* = YES

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?** No.
*If yes, provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*

**To Reproduce**

**Expected behavior**
Based on the tutorial, the fonts should work immediately but in my case it didn't. I still had to add the font codes from the elegant font plugin to the stylesheet for them to work.

**What actually happens**
*A clear and concise description of what happens instead of the expected behavior.*

**Screenshots**
*If applicable, add screenshots to help explain your problem.*

**Desktop (please complete the following information):**
- OS: Windows 10
 - Browser: Brave
 - Oxygen Version: 3.4

**Additional context**
*Add any other context about the problem here.*

**Comment by KittenCodes** [comment]
@mupersan Please open a support ticket so that we can take a look at this for you. I suspect something is either blocking access to the font, or the font URL is incorrect.
