### ISSUE TITLE
jQuery migrate disabled after updating to 2.2

### ISSUE THREAD

**Issue by MCampagnini** [soflyy/oxygen-bugs-and-features#135]
On two of my sites jQuery migrate was not loaded (without the checkbox being checked in Bloat eliminator) after upgrading to 2.2. I managed to fix it by clicking disable jQuery migrate, saving, then unchecking disable jQuery migrate and everything was back to normal.

1. Update to 2.2 (from 2.1).
2. jQuery migrate was not being loaded.

Temp Fix
1. Enable Disable jQuery Migrate in Bloat Eliminator
2. Save
3. Disable Disable jQuery Migrate
4. Save

**Comment by KittenCodes** [comment]
Hi @MCampagnini,

Please check if this is still an issue when updating to the latest version of Oxygen (currently 2.3).
