### ISSUE TITLE
Product image scales larger when viewport is toggle in Firefox

### ISSUE THREAD

**Issue by Gibsonion** [soflyy/oxygen-bugs-and-features#1350]
**The Bug**
In the editor using Firefox when the viewport is toggled, the product image gets bigger and keeps getting larger with each change. Here's a video of it https://1drv.ms/v/s!AowYpWI8R1-Hvo9fEEYM1i_lqb398w?e=SVkeOJ

**Have you tried...**
Yes

**Sandbox version:**
http://sympathetic-teira.w5.wpsandbox.pro?upass=YL4h8Eknq55A

**Test Page:**
http://sympathetic-teira.w5.wpsandbox.pro/?ct_template=15&ct_builder=true

**To Reproduce**
This seems to occur under a very specific set of circumstances

### **(In Firefox only)**
1. Make product single template
2. Add WC Product image 
3. Choose a product with at least one additional gallery image, (single image items are not affected)
4. Set product image - Avd > Layout: Flex
5. Add stylesheet with the following:

```
.woocommerce-product-gallery img {
  width: 100%;
}
```

6. Toggle the viewport size up and down
7. See error

**Screenshots**
See video in link

**Desktop (please complete the following information):**
Win 10 Pro
Firefox (Latest)

**Note:**
_Not a high priority bug as is as it's simply a bit of redundant code I can remove, but it's an odd behaviour which only occurs in Firefox and maybe worth looking into in case this is only a symptom of something more important._

**Comment by KittenCodes** [comment]
@Gibsonion Please put the Product Images element inside the Product Builder element. The Product Builder is required to add additional styling to the WooCommerce elements shown here: https://d.pr/i/I8uo1o.

**Comment by Gibsonion** [comment]
Well I can't do that because the product build is completely broken, I tried to build with it 3 times in a row starting with fresh pages and new templates and every time it was not saving most of the design, and somethings it would save, and then on the next save they'd all disappear

**Comment by KittenCodes** [comment]
@Gibsonion 

> I can't do that because the product builder is completely broken, I tried to build with it 3 times in a row starting with fresh pages and new templates and every time it was not saving most of the design, and somethings it would save, and then on the next save they'd all disappear.

Please open a support ticket so that we can take a look at this for you: https://oxygenbuilder.com/support.

> Not to mention this bug I've been trying to work around all day which is outputting PHP warning in the Oxygen CSS file https://prnt.sc/tjqis4

We have an internal bug report open to make our developers aware of this PHP warning. To my knowledge, it shouldn't prevent anything working on your site.

**Comment by Gibsonion** [comment]
> Please open a support ticket

I'd like to but these bugs have significantly put me behind and I can't spare the time to recreate a sandbox  etc atm

> To my knowledge, it shouldn't prevent anything working on your site.

In my case it is, it's breaking the CSS and preventing various classes and ID's from rendering correctly, they have to be deleted and remade, and the warning is appearing on the front end visible to users, it isn't just admin only PHP warnings that can be hidden, this is appearing as rendered text inside the design
