### ISSUE TITLE
Detect shortcode in post/page

### ISSUE THREAD

**Issue by Zyles** [soflyy/oxygen-bugs-and-features#1351]
**Describe the bug**

I have a plugin with a shortcode and want to conditionally inject CDN JS whenever it is called.

This code does not seem to work with Oxygen:

In my plugins PHP code:
```
function enqueue_scripts() {
   global $post;
   if (has_shortcode($post->post_content, "myWidget")) {
        wp_enqueue_script('vue', 'https://cdn.jsdelivr.net/npm/vue@2.6.11', [], '2.6.11');
   }
}
```

The function has_shortcode never detects the shortcode.

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
Yes

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
No

**To Reproduce**

1. Make custom plugin
2. Try to inject script on page only if the shortcode is being used

**Expected behavior**

Able to inject scripts if shortcode is present.

**What actually happens**

No scripts are injected.

**Desktop (please complete the following information):**

Oxygen 3.4

**Comment by KittenCodes** [comment]
@Zyles Please replicate this on a Sandbox site: https://oxygenbuilder.com/try/.

**Comment by Zyles** [comment]
http://nice-oystercatcher.w5.wpsandbox.pro?upass=98RBIom4bzT4

http://nice-oystercatcher.w5.wpsandbox.pro/about-us/

**Comment by KittenCodes** [comment]
Thanks @Zyles.

Oxygen's content isn't stored in the WordPress content area. It's stored in a field in the postmeta table called "ct_builder_shortcodes". I've updated your plugin code on the Sandbox site to:

```
...
function enqueue_scripts() {
   global $post;
   global $widgetVersion;
   $post_id = get_the_ID();
   $meta = get_post_meta($post_id, "ct_builder_shortcodes", true);
   if (has_shortcode($meta, "testPlugin")) {
        wp_enqueue_script('vue', 'https://cdn.jsdelivr.net/npm/vue@2.6.11', [], '2.6.11');
   }
}
...
```

The file is now loading successfully.

**Comment by Zyles** [comment]
That works thanks. But I have a follow up question with a problem.

I need to use dynamic variables/attributes in my shortcode and that does not seem possible using the GUI.

Because of this I instead tried to use a code block.

With the following code:
```
<?php
  $provider_id = get_field('provider_id');
    echo do_shortcode('[myWidget provider_id="'. $provider_id . '"]');
?>
```
I am using this in a template and custom post fields.

Now the problem is, I can't detect the shortcode on the page because this if statement does not catch it:
`if (has_shortcode($meta, "myWidget") || has_shortcode($post->post_content, "myWidget")) {`

Do you have a solution for this?

Thanks.

**Comment by KittenCodes** [comment]
> Now the problem is, I can't detect the shortcode on the page because this if statement does not catch it:

Code in Oxygen's Code Block elements is encoded with base_64 when it's added to the database. You would need to retrieve the shortcodes from the ct_builder_shortcodes field, search for encoded strings and decode them.
