### ISSUE TITLE
Repeater Produces Container Divs With Redundant Dom ID Matching The First Div's ID

### ISSUE THREAD

**Issue by AdventurouslySocial** [soflyy/oxygen-bugs-and-features#1352]
**Describe the bug**
Repeater element assigns the same DOM ID to every container of repeated content instead of giving each container its own unique ID. (You can probably extrapolate for yourself the problems that could be created from this). I discovered it by way of working with 'Accessibility'.

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
N/A (?)

**To Reproduce**
1. Create Repeater Element.
2. Populate with any content you wish to repeat.
3.) Save & Inspect in Dev Tools

**Expected behavior**
It would seem that each container for repeated content would be assigned a unique DOM ID.

**What actually happens**
Each repeated piece of content is contained in a parent element with a DOM ID that matches the first element. (if you have 19 repeated elements - you'll end up with 19 DIVS all with the same ID.

**Screenshots**
https://imgur.com/a/BWf06nk

**Desktop (please complete the following information):**
- OS: Mac OS
 - Browser CHROME (ALL BROWSERS)
 - Oxygen Version 3.3

**Comment by KittenCodes** [comment]
Duplicate: #432
