### ISSUE TITLE
Saving a slider as a re-usable part returns an error and slider also disapears

### ISSUE THREAD

**Issue by gleysen** [soflyy/oxygen-bugs-and-features#1356]
**Describe the bug**
When you have a slider build in a page, and you want to save that section with a slider as a re-usable part, the editor returns an error "Error occurred while loading post " with the id of the post.
At the same time as the error, the editor window updates and the slider section disappears from the editor. (So you can't save or you would loose the slider completely)
The reusable block does get created in the background, however when using it in a new page, I do get some Javascript errors (see screenshots)
![Screenshot 2020-07-17 at 19 24 10](https://user-images.githubusercontent.com/839660/87813994-4305ea00-c863-11ea-93cd-3383e1ab3ec6.png)

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
No*

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
No, didn't try yet, busy building site for my client.

**To Reproduce**
1. Go to editor and insert a slider with some slides and save your work
2. go back and edit the page, and try to make that section a re-usable block.
3. now you should see the error.

**Expected behavior**
I expect it to save the re-usable part, without the error or the slider disappearing from the editor.

**What actually happens**
Error, and slider vanishes...

**Screenshots**
![Screenshot 2020-07-17 at 18 51 52](https://user-images.githubusercontent.com/839660/87813790-d559be00-c862-11ea-9ca7-741790a27c2b.png)
![Screenshot 2020-07-17 at 18 58 07](https://user-images.githubusercontent.com/839660/87813802-db4f9f00-c862-11ea-9686-abfeaf451601.png)

**Desktop (please complete the following information):**
- OS: Mac
 - Browser Chrome, latest version
 - Oxygen Version 3.4

**Additional context**
I think this is linked to another confirmed bug that I also experienced with my Slider: 
https://github.com/soflyy/oxygen-bugs-and-features/issues/1118

**Comment by KittenCodes** [comment]
@gleysen I've not been able to replicate this on a clean Sandbox site running Oxygen v3.4. Is your slider using dynamic data?

**Comment by gleysen** [comment]
@KittenCodes No I'm not using dynamic data in the slider, just a div with a title, text and a button. I do have it set to full-width (covering the section it's in)... I don't have the time now, but I'll try to create a sandbox version when my project is done.... and I do still think it's linked to bug #1118
