### ISSUE TITLE
Deprecated: implode

### ISSUE THREAD

**Issue by heartfelttech** [soflyy/oxygen-bugs-and-features#1357]
**Describe the bug**

If I turn on debug mode I'm seeing this error a lot. It doesn't seem to impact the site but it's getting in the way of debugging another issue.

Deprecated: implode(): Passing glue string after array is deprecated. Swap the parameters in /var/web/site/public_html/wp-content/plugins/oxygen/component-framework/component-init.php on line 4857 Deprecated: implode(): Passing glue string after array is deprecated. Swap the parameters in /var/web/site/public_html/wp-content/plugins/oxygen/component-framework/component-init.php on line 4857 Deprecated: join(): Passing glue string after array is deprecated. Swap the parameters in /var/web/site/public_html/wp-content/plugins/oxygen/component-framework/components/component.class.php on line 2281

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
*Yes*

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**

http://tame-loris.w6.wpsandbox.pro/wp-admin/index.php
Visible on admin console at top 

**To Reproduce**
With php 7.3,

add to wp-config.php
  define('WP_DEBUG', true);
  define( 'WP_DEBUG_DISPLAY', true );

**Expected behavior**
No error messages

**What actually happens**
In the dashboard (and on pages on my own site but just the dash on the test site) I see error messages:

Notice: Undefined index: button_priority in /var/www/public/tame-loris/wp-content/plugins/oxygen/component-framework/api/oxygen.element.class.php on line 38

On my own site I'm also seeing this error: 
Deprecated: implode(): Passing glue string after array is deprecated. Swap the parameters in /var/web/site/public_html/wp-content/plugins/oxygen/component-framework/component-init.php on line 4857 Deprecated: implode(): Passing glue string after array is deprecated. Swap the parameters in /var/web/site/public_html/wp-content/plugins/oxygen/component-framework/component-init.php on line 4857 Deprecated: join(): Passing glue string after array is deprecated. Swap the parameters in /var/web/site/public_html/wp-content/plugins/oxygen/component-framework/components/component.class.php on line 2281

**Desktop (please complete the following information):**
- OS: MacOS
 - Browser Safari
 - Oxygen Version Version 3.4

**Comment by KittenCodes** [comment]
Fixed in v3.6 Beta.
