### ISSUE TITLE
DONE: Section Shape Dividers

### ISSUE THREAD

**Issue by aboutwd** [soflyy/oxygen-bugs-and-features#136]
I do like Oxygen. Thanks for making it.  
And I know this has been [asked before](https://oxygenbuilder.com/forums/topic/section-shape-dividers/)....  but.... it's actually a pretty big deal for me.

**Section Shape Dividers**

Yes, I've seen the CSS code you can [manually insert](https://oxygenbuilder.com/forums/topic/how-to-easily-add-a-shape-divider-between-2-sections/) to make it happen. But that's just not the same.  A UI for inserting Section Shape Dividers would take this system up a notch, for sure. 

I have clients asking for it specifically, and I have to use other systems for them because of it.

Please consider adding this.
Thanks

**Comment by Deanphillips** [comment]
Thrive has a few but has added loads now. https://thrivethemes.com/new-fancy-dividers/

I really would love these built into the system

**Comment by Deanphillips** [comment]
Been playing around with thrives and they're brilliant. Makes life so much easier.

**Comment by totemdomains** [comment]
may as well add the ability to animate too! ;)

**Comment by bdups** [comment]
This is definetely one feature that puts Oxygen way down below Elementor. Shape Dividers are a MUST. I have quit using all themes and builders that do not work with shape divider because every single client wants it. Nobody wants square sites anymore. This is a huge use case letdown for the developers as this is a key feature in the market right now that the developers simply choose to ignore or rather, have a disbelief in market trends, which is an even bigger issue. Could this be a hint to the future of Oxygen?

**Comment by Deanphillips** [comment]
I'd like to be able to put these on the left/right/top/bottom and be able to do a bottom + top in one section like Thrive Architect allows
<img width="400" alt="Screenshot 2019-07-07 at 03 15 02" src="https://user-images.githubusercontent.com/21025321/60763116-85e48d80-a065-11e9-8de3-e81864ba7472.png">

**Comment by HenkDz** [comment]
> I'd like to be able to put these on the left/right/top/bottom and be able to do a bottom + top in one section like Thrive Architect allows
> <img alt="Screenshot 2019-07-07 at 03 15 02" width="400" src="https://user-images.githubusercontent.com/21025321/60763116-85e48d80-a065-11e9-8de3-e81864ba7472.png">

Fancy Dividers are great in Thrive, and even greater if implemented in Oxygen. I think this will be easy for the Oxygen team just needs some time.

**Comment by muzaffarsiddiqui** [comment]
+1

**Comment by fmommeja** [comment]
+1

**Comment by ciaoweb** [comment]
+1 yes! we definitely need an easy way to insert shape dividers.

**Comment by Colgen** [comment]
HUGE +1!  Would like the side decorations too like Thrive has.

**Comment by marceloaof** [comment]
Elementor already had [Shape Dividers](https://elementor.com/blog/v130-shape-divider/), and now they expanded this feature with [Fancy Dividers](https://elementor.com/blog/introducing-background-slideshow/).
Oxygen, please consider both!
I can only recreate SVG-dividers with images, and for sure this is not the best possibility.

**Comment by marceloaof** [comment]
Elementor already had Shape Dividers, and now they expanded this feature with Fancy Dividers.
Oxygen, please consider both! I can only recreate SVG-dividers with images in Oxygen, and for sure this is not the best possibility.

Maybe this feature can come into reality as an "SVG manager" element, which can be expanded inside "Section and Elements" in each Design Sets of the Library.

**Comment by marceloaof** [comment]
Elementor already had [Shape Dividers](https://docs.elementor.com/article/207-shape-divider), and now they expanded this feature with [Fancy Dividers](https://elementor.com/blog/introducing-background-slideshow/).
Oxygen, please consider both. I can only recreate SVG-dividers with images in Oxygen, and for sure this is not the best possibility.

Maybe this feature can come into reality as an "SVG manager" element, which can be added inside "Section and Elements" to be expanded in each Design Sets of the Library.

**Comment by marcel2008** [comment]
+++++1

**Comment by BrynWithin** [comment]
This feature would be such a godsend. Done exactly like Thrive, and a massive bonus would be subtle animated effects.

**Comment by williammei** [comment]
+1

**Comment by MimiDev** [comment]
+1

**Comment by Spellhammer** [comment]
Shape dividers implemented in 3.4 alpha 1.

**Comment by swinggraphics** [comment]
Why was this only implemented on Sections?

**Comment by BrynWithin** [comment]
> Why was this only implemented on Sections?

Because they're _section_ dividers?

**Comment by swinggraphics** [comment]
> > Why was this only implemented on Sections?
> 
> Because they're _section_ dividers?

Isn't the header of my website a _section_? Can't add a divider to that.

**Comment by BrynWithin** [comment]
> Isn't the header of my website a _section_? Can't add a divider to that.

Just add the divider to the first section of your site beneath the header. You can add a negative top margin to push the section into the space of your header.

**Comment by swinggraphics** [comment]
That is a usable workaround for that case. But why limit us? It's just a div. They could add it to almost anything. It even appears in Structure. It could (should?) just be an element we can add like any other.

**Comment by HenkDz** [comment]
> > Isn't the header of my website a _section_? Can't add a divider to that.
> 
> Just add the divider to the first section of your site beneath the header. You can add a negative top margin to push the section into the space of your header.

Or just put the whole header in a section with a divider.

**Comment by swinggraphics** [comment]
> Or just put the whole header in a section with a divider.

Or they could just give us the option of adding simple elements like this without creating extraneous wrapper elements
