### ISSUE TITLE
{"error":"Forbidden"}

### ISSUE THREAD

**Issue by foreversong2020** [soflyy/oxygen-bugs-and-features#1363]
**Describe the bug**
*A clear and concise description of what the bug is.*

I'm using Centos Web Panel I'm running my own server. I have many of my customers been using WordPress for a while (great product) I have over almost 20 websites using oxygen. but this time i ran into some problem i never seen it before. 
new website hosting. installed WordPress thru 5.4.2 softaculous. after installing the WordPress first thing I installed the oxygen plugin. .3.4 final. I try to new install template. once it clicks install template it has an error  {"error":"Forbidden"}

besides creating a template/theme from an oxygen builder. I try to create an individual page that loads the template. it won't allow me to. 

I tired the re-build a new account // removing the entire account and re-setup for the account in my server. 

Thanks
Andy

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
*Yes

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
*If yes, provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*

**To Reproduce**

**Expected behavior**
*A clear and concise description of what you expected to happen.*
![error1](https://user-images.githubusercontent.com/68581395/88019402-bb84d900-caf7-11ea-98df-7240a76adef7.png)
![error2](https://user-images.githubusercontent.com/68581395/88019405-bc1d6f80-caf7-11ea-9295-3b73335a86c4.PNG)
![error3](https://user-images.githubusercontent.com/68581395/88019406-bc1d6f80-caf7-11ea-9512-a61d6abcfb65.PNG)

**What actually happens**
*A clear and concise description of what happens instead of the expected behavior.*

**Screenshots**
*If applicable, add screenshots to help explain your problem.*

**Desktop (please complete the following information):**
 - Oxygen Version [e.g. 2.2 Alpha]

**Smartphone (please complete the following information):**
 - Oxygen Version [e.g. 2.2 Alpha]

**Additional context**
*Add any other context about the problem here.*

**Comment by KittenCodes** [comment]
@foreversong2020 This can happen if our server blocks access to the design sets for some reason. Please open a support ticket that includes your site details so that we can take a look: https://oxygenbuilder.com/support.
