### ISSUE TITLE
La página de tienda no sé visualiza el diseño

### ISSUE THREAD

**Issue by kataaramburu** [soflyy/oxygen-bugs-and-features#1364]
Bueno estoy haciendo una tienda en oxygen builder, mi URL es productosorganico.com pero en la página tienda que pongo como página tienda a través de woocommerce configuraciones no funciona ya que no me muestra el diseño que hize en oxygen . Pero sin embargo mientras no diga que esa página no es mi tienda , normal el diseño se puede visualizar.

Ayuda por favor. Gracias

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
*Yes/No*

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
*If yes, provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*

**To Reproduce**

**Expected behavior**
*A clear and concise description of what you expected to happen.*

**What actually happens**
*A clear and concise description of what happens instead of the expected behavior.*

**Screenshots**
*If applicable, add screenshots to help explain your problem.*

**Desktop (please complete the following information):**
 - Oxygen Version [e.g. 2.2 Alpha]

**Smartphone (please complete the following information):**
 - Oxygen Version [e.g. 2.2 Alpha]

**Additional context**
*Add any other context about the problem here.*

**Comment by KittenCodes** [comment]
@kataaramburu Please open a support ticket so that we can take a look at this for you: https://oxygenbuilder.com/support. You need to select "Something's broken and I need help".
