### ISSUE TITLE
DONE: Wordpress 5.6 and jQuery 3.0 and 3.5

### ISSUE THREAD

**Issue by wpsumo** [soflyy/oxygen-bugs-and-features#1365]
**Describe the feature you'd like to see included in Oxygen.**
Compatible with upcoming WordPress 5.6 which will be shipped with an updated version o jQuery.
https://make.wordpress.org/core/2020/06/29/updating-jquery-version-shipped-with-wordpress/

Several of users are already updating it with code or other plugins to make use of jQuery 3.5.x.x, This breaks the interface of the builder but frontend works just fine.

Preferably to reduce libs and make use of vanilla JS instead of relying on libs as jQuery.

**What are the use cases for this feature?**
Make compatibility before it's urgent.

**Examples of this feature or functionality.**
https://jquery.com/upgrade-guide/3.0/
https://jquery.com/upgrade-guide/3.5/

**Comment by mikeingz** [comment]
Maybe we can start to report the 'bugs' ? So it will be easier/faster for them to fix them.

With jQuery 3.5.1 , the 2 icons for each element in the structure, have just disappeared : 

![image](https://user-images.githubusercontent.com/2438157/88267509-85b44000-cd03-11ea-8095-8db5cbc6677d.png)

**Comment by wpsumo** [comment]
@mikeingz It is not a bug they are compatible with the native jQuery from WordPress. It's a feature enhancement. Once 5.6 is released and if not fixed it would be considered as a bug.

Icons across the builder interface and third party addons to the builder tend to stop working. Check the console and you will see several of errors :)

**Comment by Spellhammer** [comment]
This is on our radar, but if anyone using the new built-in jQuery encounters specific issues, reporting them here would be helpful.

**Comment by wpsumo** [comment]
@Spellhammer Do you refer to the v1 or the plugin from the core team https://wordpress.org/plugins/wp-jquery-update-test/ suing v3 and report on bugs with v3?

**Comment by Spellhammer** [comment]
> Do you refer to the v1 or the plugin from the core team https://wordpress.org/plugins/wp-jquery-update-test/ suing v3 and report on bugs with v3?

Using the plugin. We'll be doing our own internal testing as well to ensure we're ahead of any issues that will come with WP 5.6 and the jQuery change.

**Comment by wpsumo** [comment]
Sounds good, looking forward to seeing oxygen compatible with jQuery 3.5.1 + as soon as possible 👍

**Comment by sq2** [comment]
WordPress 5.5 is coming soon. You can download 5.5 RC1 right now. Not sure about 5.6 mentioned above. Oxygen 3.5 RC1 works pretty well on WordPress 5.5 RC1. Although, the color picker doesn't work. Not sure if that's a WordPress or Oxygen issue. It's pretty noticeable. Since they are both RC versions, I wonder if it's even worth reporting these issues at this point.

**Comment by wpsumo** [comment]
@Spellhammer  I would at the point of starting to prepare for vanilla js for wordpress 5.6 and jQuery 3.5x.x. We are going that direction anyhow and it's better for the user and you can begin with removing dependencies and move to vanilla js frontend. 

This way we wouldn't be dependent on jQuery and for advanced users who already have plugins which isn't dependent on the jQuery lib can unload it. But right now Oxygen is one of the bottlenecks which loads inline jQuery for several of elements such as tabs, accordion, pro menu etc.

Some things does not even require javascript it can be done with css and make it even more lightweight 👍

**Comment by KittenCodes** [comment]
Added in 3.6.1.
