### ISSUE TITLE
Space between ShapeDivider on section and the element underneeth

### ISSUE THREAD

**Issue by qa-joerg** [soflyy/oxygen-bugs-and-features#1366]
There is small space between the ShapeDivide on a section and the element which follows underneeth the section on the mobile view. The background of the section is shown.

Divider Shape on a section (margin top 50)
Under the section are columns (margin 0, padding 20)
Section container padding 0, hight 100%
Divider Shape: Balance 3
Position: Bottom
The background color of the columns is the same like the divider shape

Hope you can reproduce this anyhow. Please visit https://www.golfheroes.de/die-helden/ using your smartphone. Please scroll down to the middle of the page. I see this issue on a Iphone 11 pro.

![](https://user-images.githubusercontent.com/56035737/88161544-6688b600-cc10-11ea-90b8-91fdbc4ff3a8.jpg)

**Comment by jamescrabb** [comment]
I have seen this also, not used the new shape div element but used to do them manually and to fix it I would offset the bottom or top px to be -1 this would resolve the issue

**Comment by qa-joerg** [comment]
Thank you
