### ISSUE TITLE
500 Error when trying to open or add a new template

### ISSUE THREAD

**Issue by falccon1** [soflyy/oxygen-bugs-and-features#1367]
**Describe the bug**
When I try to edit an old template or create a new one, I get a 500 error in the Oxygen editor

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
Yes, I've tried everything

**To Reproduce**
1. Go to 'Oxygen->Templates'
2. Click on 'Edit with Oxygen'
3. See error: '500'

**Expected behavior**
I can change and add templates normally.

**What actually happens**
I'm recieving a 500 Error - failed to load template data.

Screenshot
![grafik](https://user-images.githubusercontent.com/68655902/88200868-06613680-cc47-11ea-983f-98cc9e825211.png)

**Desktop (please complete the following information):**
- OS: Windows 10
 - Browser: Firefox / Chrome
 - Oxygen Version: 3.4

**Additional context**
Screenshot of debug.log:
![grafik](https://user-images.githubusercontent.com/68655902/88200423-69060280-cc46-11ea-81a8-3374aafd0ac5.png)

Please help me, thanks!

**Comment by Spellhammer** [comment]
Your log indicates you're running out of memory. Try increasing the memory allocated to your install. If you're not sure how to do that, contact your host.

**Comment by falccon1** [comment]
Hi, I've already checked the memory and there is more than enough space. The problem isn't solved yet.

**Comment by KittenCodes** [comment]
@falccon1 Memory and space are different. Please send the error messages to your web host and ask them to increase your PHP memory for you.

**Comment by falccon1** [comment]
Ok so I fixed the problem with increasing the memory_limit to 1024M. But still, why is there this huge amount of data transfered? Is it normal or will I'm running in further problems in the future? Thanks!!

**Comment by jamescrabb** [comment]
> Ok so I fixed the problem with increasing the memory_limit to 1024M. But still, why is there this huge amount of data transfered? Is it normal or will I'm running in further problems in the future? Thanks!!

This is the standard memory limit I set all my Wordpress installs to. It is not excessive at all. 👍
