### ISSUE TITLE
[REQUEST] make a tip for where a condition has been set previously on the element

### ISSUE THREAD

**Issue by YammYcoding** [soflyy/oxygen-bugs-and-features#1368]
I just added a condition to  a section. But now I see no means to remember weather I added it or where, if I come back later to this section. Such thing does not exist ?

If not, please add it some day :)

![image](https://user-images.githubusercontent.com/1200923/88275955-9be6df80-ccb4-11ea-915d-e5c09b617f6e.png)

**Comment by Spellhammer** [comment]
An icon is added to the element in the Structure Pane when it has an active Condition.
