### ISSUE TITLE
changing size of background

### ISSUE THREAD

**Issue by MYIG** [soflyy/oxygen-bugs-and-features#137]
you guys may think 'we already have that feature!', but it is not... I asked support about it many times but they just said false things...

**Comment by wplit** [comment]
This is a feature. 

Source: I've been using it in Oxygen for the past 9 months. Works as expected, the control changes the 'background-size' in the CSS.

<img width=400 src="https://i.ibb.co/6JDHwCv/feature.png">

**Comment by MYIG** [comment]
i already did it... I asked support about it over 1 week..
