### ISSUE TITLE
Recently added Elements (Files, ACF Fields etc.) are shown up and causing errors while selected in Previewing Dropdown

### ISSUE THREAD

**Issue by VF404** [soflyy/oxygen-bugs-and-features#1373]
**Describe the bug**
Every new added Element in Wordpress (eg. a File, ACF Field or even an Oxygen Template or Gutenberg Block etc.) will be automaticly selected in the Previewing Dropdown as the "Previewing Page" in a "catch all" template. Beside its really annoying it causes some 500 / 404 errors with files like recently uploaded zip-file for example or a acf field!

This one says, its actually fixed, but it isn't! #74 

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
Yes

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
Yes, but only with Gutenberg Blocks build within Oxygen

**To Reproduce**
1. create a gutenberg block with oxygen
2. edit a "catch all" template
3. Previewing automaticly selects last created element inside wordpres backend => eg the gutenberg block created with oxygen
4. See 500 Error or wrong preview, because the Oxygen Builder trys to preview the recently created file / acf field etc.

**Expected behavior**
Previewing Selection should only except pages and posts, but not all kind of data

**What actually happens**
recently created files are showing up in the previewing selection field and causing problems

**Screenshots**
N/A

**Desktop (please complete the following information):**
- iOS
 - Firefox
 - Oxygen Version 3.4

**Comment by KittenCodes** [comment]
@VF404 I've not been able to replicate this behaviour on a Sandbox site when previewing an item that contains an ACF field through the Main template. Please replicate this on our Sandbox site and send us the URL: https://oxygenbuilder.com/try/.
