### ISSUE TITLE
Improve layout shift (add width and height to html of images)

### ISSUE THREAD

**Issue by wpsumo** [soflyy/oxygen-bugs-and-features#1374]
**Describe the feature you'd like to see included in Oxygen.**
Oxygen do not insert height and width into the HTML. Use default style (desktop?) for reference value to HTML w and h.

**What are the use cases for this feature?**
Distance fraction 
The other part of the layout shift score equation measures the distance that unstable elements have moved, relative to the viewport. The distance fraction is the greatest distance any unstable element has moved in the frame (either horizontally or vertically) divided by the viewport's largest dimension (width or height, whichever is greater).
https://web.dev/cls/#distance-fraction

**Comment by kancur** [comment]
Yup, this is super important.

WordPress is adding width and height attributes to IMG tags by default now. It works flawlessly with lazy loading. Unfortunately, oxygen page builder doesn't include these attributes automatically which is crucial for getting rid of CLS issues. 

Google plans to start using CLS as a ranking factor in 2021. Please consider adding this feature.

**Comment by KittenCodes** [comment]
Duplicate: https://github.com/soflyy/oxygen-bugs-and-features/issues/1249
