### ISSUE TITLE
Code Component Disabler

### ISSUE THREAD

**Issue by pawelgp** [soflyy/oxygen-bugs-and-features#1376]
In structure panel to add in each element, or at least in section one, a checkbox to exclude generating code in frontend if ticked (disabling a component alike).

Importance of the feature is: 
- building a few versions of a component for a client to have an option quickly choose from, 
- for a dev. no hassle to copying / removing code and making changes for indecisive clients, 
- on click visibility cutting unused components bloating code with for instance visibility: none; 

The meaning:
An examplary online client requested to see three versions of a landing page. She/He can have them all at once on one page, after decide we just click twice and there is one landing page visible. Five minutes after the client changes his mind saying that the other one was better we just click twice and the change is made. Every bodies happy, job done with no time at all.

**Comment by KittenCodes** [comment]
You can do this using Conditions.
