### ISSUE TITLE
Additional Conditional Operators for Dynamic Data

### ISSUE THREAD

**Issue by damienlee77** [soflyy/oxygen-bugs-and-features#1377]
**Describe the feature you'd like to see included in Oxygen.**

Due to the really essential need for this feature, it should really be considered a bug. Conditions for dynamic data already include ==, >= & <= but don't contain other essential operators such as !=, > & <. This really restricts use of conditions with custom fields!

**What are the use cases for this feature?**
Very Broad!

**Examples of this feature or functionality.**
If a numeric value is held in a custom field, a condition cannot be applied to hide an element without using multiple conditions and elements.

**Comment by KittenCodes** [comment]
#763
