### ISSUE TITLE
Section loss if an image has a specific name!

### ISSUE THREAD

**Issue by FrenchDesign** [soflyy/oxygen-bugs-and-features#1379]
A section where you insert an image, whose filename is: assistance-au-referencement.jpg, does not work.

The section disappears during a preview and in Oxygen's editor, after saving and reopening the page.

This problem leads me to ask the following question: 
Are there any reserved words that should not be used with Oxygen Builder?

**Comment by KittenCodes** [comment]
@FrenchDesign Please open a support ticket so that we can take a look at this for you: https://oxygenbuilder.com/support.

**Comment by FrenchDesign** [comment]
> @FrenchDesign Please open a support ticket so that we can take a look at this for you: https://oxygenbuilder.com/support.

Yet I opened a support ticket! I don't understand.
