### ISSUE TITLE
Change the name to be more unique and searchable?

### ISSUE THREAD

**Issue by aaronkorn** [soflyy/oxygen-bugs-and-features#138]
New to Oxygen here and so far I'm very impressed with the UI. 

But I have a hard time finding tutorials on youtube and Google because Oxygen, the name is not unique like Elementor or Divi.

Can you change the name to Oxygentor or Oxygendiv? so i can have a better time finding tutorials and examples.

It's very intuitive and easy to learn. I think you have a winner here.
Elementor just changed to 2.5 and added the grid system -- they basically f-u my pages.
Forget that, I'm making new pages with Oxygen now.

**Describe the feature you'd like to see included in Oxygen.**
*A clear, detailed description of the feature you're requesting.*

**What are the use cases for this feature?**
*e.g. Accessibility, e-commerce store that sells bicycles, etc.*

**Examples of this feature or functionality.**
*If another product has done it well, provide examples here.*

**Comment by Caffeinedesign** [comment]
ok, can be a good idea for SEO in general (i suggest you to add the word wordpress in your searches)... but oxygentor? oxygendiv? really? why not beaver oxygener? you could name something with half of a competitor name? lol

at least something like: 

- Oxygener (oxygen + builder, it's a short hand for complete name, doesn't need more than 2 letters to be added to actual brand design)

- Oxygenpress (oxygen + wordpress wich isn't a competitor but the platform is based on)

- Oxybuilder or Oxybuild

just oxygenpress would need a little brand change, others are jost shorthands and you can do some tricks like

>###  Oxygener
> Oxygen builder

> ### Oxybuilder
> The Oxygen builder


p.s.
a little suggestion for logo would be to move the "molecule" in a different position, there at first sight or  without the complete word Oxygen could seem a Q 

my2c

**Comment by ukuwi** [comment]
Boo...
