### ISSUE TITLE
Notice: Undefined index: button_priority in

### ISSUE THREAD

**Issue by lisandi** [soflyy/oxygen-bugs-and-features#1382]
**Describe the bug**
*A clear and concise description of what the bug is.*
Blocking the display of the site

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
*Yes/No*
Yes

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
*If yes, provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*
No as your system is using different PHP version

**To Reproduce**

Install Oxygen on a Fresh install of Wordpress via Bedrock template
install Oxygen
Error appears

**Expected behavior**
*A clear and concise description of what you expected to happen.*

**What actually happens**
*A clear and concise description of what happens instead of the expected behavior.*

Notice: Undefined index: button_priority in /path/web/app/plugins/oxygen/component-framework/api/oxygen.element.class.php on line 38

Deprecated: implode(): Passing glue string after array is deprecated. Swap the parameters in /path/web/app/plugins/oxygen/component-framework/component-init.php on line 4857

Deprecated
: implode(): Passing glue string after array is deprecated. Swap the parameters in
/path/web/app/plugins/oxygen/component-framework/component-init.php
on line
4857

**Screenshots**
*If applicable, add screenshots to help explain your problem.*

**Desktop (please complete the following information):**
 - Oxygen Version [e.g. 2.2 Alpha]

**Smartphone (please complete the following information):**
 - Oxygen Version [e.g. 2.2 Alpha]
If you can do it with WordPress, you can design it with Oxygen.
Version 3.4 | By Soflyy

Version | 5.4.2
-- | --

Server architecture | Linux 5.4.0-42-generic x86_64
-- | --

Web server | Apache/2.4.41
PHP version | 7.4.8 (Supports 64bit values)
PHP SAPI | cgi-fcgi
PHP max input variables | 1000
PHP time limit | 300
PHP memory limit | 256M
Max input time | 60
Upload max filesize | 60M
PHP post max size | 60M
cURL version | 7.68.0 OpenSSL/1.1.1g

**Additional context**
*Add any other context about the problem here.*

We thought we coud use Oxygen but now need to use DIVI again instead - SAD!

**Comment by KittenCodes** [comment]
@lisandi 

> We thought we coud use Oxygen but now need to use DIVI again instead - SAD!

If the errors are showing on the front-end of your site or in the admin area, please add the following two lines to your wp-config.php file, just below the WP_DEBUG line:

```
define( 'WP_DEBUG_DISPLAY', false );
@ini_set( 'display_errors', 0 );
```

https://github.com/soflyy/oxygen-bugs-and-features/issues/974

**Comment by lisandi** [comment]
Hi Soph

Hiding errors does actually not solve the problem!
will the deprecation problem be solved in the next update?

**Comment by KittenCodes** [comment]
@lisandi 

> will the deprecation problem be solved in the next update?

I can see that our developers have been working on the internal bug report, but I'm not yet sure which release it will be added to.
