### ISSUE TITLE
Block Settings > Advanced > Additional CSS class(es) Aren't Added To Oxygen Gutenberg Blocks

### ISSUE THREAD

**Issue by AdventurouslySocial** [soflyy/oxygen-bugs-and-features#1384]
Block Settings > Advanced > Additional CSS class(es) don't seem to be added to Oxygen created blocks.

**Why this might be important:**
You may want to use caching plugin's built-in lazy load exclusion rules for element class names or parent class names while building pages with Oxygen Blocks.

You don't want to add the lazy load exclusion class every time the block is used. Only when it appears above the fold. This means the lazy load exclusion class shouldn't be added from within Oxygen editor, but at the time of the block's placement on a page.

**NOTE:** I've tried this with various types of Oxygen Blocks (text only, images, headlines, full sections, etc.
Checking source code reveals that Block Settings > Advanced > Additional CSS class(es) are only added to native block elements.

Could this be fixed?

**Comment by chris2604** [comment]
Hello ! Any solution ? Thanks in advance

**Comment by KittenCodes** [comment]
Duplicate: https://github.com/soflyy/oxygen-bugs-and-features/issues/976
