### ISSUE TITLE
Add inner content element available in templets to pages

### ISSUE THREAD

**Issue by MauritzBotma** [soflyy/oxygen-bugs-and-features#1389]
Add the ability to add an inner content to pages not just templates

Often I have inner content on my WP page that I want to make use of but I need the functionalities from oxygen to add additional elements.

Example: I have an events template. Anyone can add the basic detail of the event description in WP editor and the event details using the created custom fields. No for instance I want to add a registration form using a code block. 

I can copy and paste the WP content into something like a rich text element but if someone edits the WP content it will not update in oxygen.

**Comment by Spellhammer** [comment]
You can use Dynamic Data to insert the content from the WordPress editor on pages.

You can find that under +Add > WordPress > Dynamic Data, use the Content element.
