### ISSUE TITLE
advanced custom fields wysiwyg editor not working

### ISSUE THREAD

**Issue by Mikkelka** [soflyy/oxygen-bugs-and-features#139]
Oxygin dont render advanced custom fields with wysiwyg editor, it is just plain text, no img or link, just text.

**Comment by timpixel** [comment]
I don't think this is a bug, more like a missing feature? Many acf field types are not supported by the oxygen editor.

**Comment by KittenCodes** [comment]
Unfortunately, this is a known issue. To insert an ACF WYSIWYG field and retain the proper formatting, please insert a Code Block and use PHP instead:

```php
<?php
    the_field('field_name');
?>
```
