### ISSUE TITLE
Issue with SyntaxHighlighter Evolved Plugin

### ISSUE THREAD

**Issue by thevarunsood** [soflyy/oxygen-bugs-and-features#1390]
Hi,

I am using SyntaxHighlighter Evolved plugin on my website to display code snippets on my website.

I am having issues with displaying left and right angle brackets as part of the code snippets (< and >). Everything looks fine when I am logged into the website and previewing the post while being logged in.

<img width="710" alt="Screenshot at Aug 05 11-58-01" src="https://user-images.githubusercontent.com/46369176/89379819-1c292e00-d714-11ea-908f-b102cccea991.png">

However, when a logged-out user looks at the same post, all brackets look like they have been converted into corresponding HTML entities.

<img width="707" alt="Screenshot at Aug 05 12-07-08" src="https://user-images.githubusercontent.com/46369176/89379874-382ccf80-d714-11ea-91d0-41466686894d.png">

Please suggest what could be going on here.

**Comment by KittenCodes** [comment]
@thevarunsood This may be caused by your database or table encoding. Please check that both are encoded with utf8mb4_general_ci or utf8_general_ci.

Unfortunately, if that doesn't help then it's unlikely that you can use the plugin with Oxygen.

**Comment by thevarunsood** [comment]
Well, the plugin is working fine except this weird issue with angular brackets. Moreover, it works fine when I am logged into the site. Anyway, I'll dig deep.
