### ISSUE TITLE
Failed to load template data

### ISSUE THREAD

**Issue by sudomistress** [soflyy/oxygen-bugs-and-features#1391]
**Describe the bug**
When attempting to edit a template, the error "Failed to load template data" is displayed, no structure is visible. 

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
Yes

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
Sadly, no.

**To Reproduce**

**Expected behavior**
When oxygen builder loads, the structure should load as well.

**What actually happens**
Only the first part of the header row shows (not the third column) or anything else after it. The console displays error: TypeError: parentComponent.hasClass is not a function.

**Screenshots**
N/A

**Desktop (please complete the following information):**
- OS: Windows 10
 - Browser:  Tested in Chrome and Firefox
 - Oxygen Version: 4.0

**Smartphone (please complete the following information):**
 - Oxygen Version [e.g. 2.2 Alpha]

**Additional context**
 Note, I have set the memory limit to 1024MB to see if that fixes it and it does not. The site is in a docker container using local by flywheel. The front end of the site does display the correct content, so it does exist, just the builder does not load for editing. Wordpress version is 5.4.2. Only thing created were blank pages and 3 menus which were being used by the template. Also only template in the instance. neither php nor nginx log showed anything.

**Comment by KittenCodes** [comment]
@sudomistress Please open a support ticket so that we can take a look at this for you: https://oxygenbuilder.com/support.
