### ISSUE TITLE
Custom characters in site name result in Items not found Unauthorized when trying acces the site Design Set

### ISSUE THREAD

**Issue by Deimz** [soflyy/oxygen-bugs-and-features#1394]
The website Design Set Name is based on the  website's named defined in Wordpress settings.

If this name contains special chars like ' ( Example : L'avion ) it will forbid the Design Set to load in the editor. 

To fix it you just need to remove special characters in site name waiting for a patch

Thanks all

**Comment by KittenCodes** [comment]
@Deimz I've not been able to replicate this on a site with the title L'avion - I'm able to use the design set items both on the original site and on the site that is using the design set.

Are you seeing any errors in the logs when you try to access the design set?
