### ISSUE TITLE
Adding images to existing gallery

### ISSUE THREAD

**Issue by simshaun** [soflyy/oxygen-bugs-and-features#1395]
**Describe the bug**
Unable to add images to existing gallery. Using the Add Media tab in the WP file manager. Creating a new gallery works but isn't ideal.

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
Yes

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
http://cheerful-badger.w5.wpsandbox.pro/sample-page/?ct_builder=true&ct_inner=true

**To Reproduce**
1. Add a gallery block.
2. Create a new gallery with a couple images.
3. Click the Browse button the Image IDs field to add more images.
4. Make sure the "Add Media" action is chosen.
5. Select a couple more photos and click "Insert Into Post"

**Expected behavior**
Selected media should be added to existing gallery.

**What actually happens**
Nothing seems to happen at all.

**Desktop (please complete the following information):**
  - OS: Win10
 - Browser: Chromium Edge
 - Oxygen Version 3.4

**Comment by KittenCodes** [comment]
https://github.com/soflyy/oxygen-bugs-and-features/issues/169
