### ISSUE TITLE
"Your shortcodes lack a valid signature" directly after signing

### ISSUE THREAD

**Issue by ascripter** [soflyy/oxygen-bugs-and-features#140]
**Describe the bug**
Oxygen Error: Your shortcodes lack a valid signature - most likely because a migration has taken place. Please re-sign your shortcodes inside the WordPress admin panel, at Oxygen > Settings > Security.

This error appeared out of the blue and still stays even directly after signing the shortcodes (and clearing the browser cache). I use self written shortcodes in my project.

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
Yes

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
*If yes, provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*
No

**Expected behavior**
No error message

**What actually happens**
Error message

**Desktop (please complete the following information):**
- OS: Windows 10
 - Browser Firefox 65.0.2
 - Oxygen Version 2.2

**Comment by ascripter** [comment]
Update: After restarting the browser the error didn't reappear. However before posting my bug report I reloaded the page with Ctrl+F5 as well as disabling HTTP-cache in firebug which didn't solve the problem. So maybe it might be some caching issue with the oxygen-frontend?

**Comment by rrdirnens** [comment]
Hi! 
I am having the same issue: 
![image](https://user-images.githubusercontent.com/42729985/72268210-15c54e80-362a-11ea-8d20-a13ad7ed75c6.png)

**Comment by aQziany** [comment]
Hello, 

I have this problem also.

![Screenshot 2020-11-26 152718](https://user-images.githubusercontent.com/29342405/100421200-94837880-3090-11eb-9dd2-16846da10c4f.png)
![Screenshot 2020-11-26 213357](https://user-images.githubusercontent.com/29342405/100421202-95b4a580-3090-11eb-8e9f-ad7550c88579.png)
![Screenshot 2020-11-26 213425](https://user-images.githubusercontent.com/29342405/100421203-95b4a580-3090-11eb-9bc5-d941e6f5a21e.png)

**Comment by KittenCodes** [comment]
@aQziany Please open a support ticket so that we can take a look at your site: https://oxygenbuilder.com/support.
