### ISSUE TITLE
Oxygen Gutenberg Styles Not Showing On Back End

### ISSUE THREAD

**Issue by mielcafedesign** [soflyy/oxygen-bugs-and-features#1401]
I'm using Oxygen Gutenberg integration and when I check "Make this full page editable in Gutenberg" I get the contents I arranged in the builder, yet not in the same disposition and without the styles applied. It seems like the CSS generated within the builder isn't reported in Gutenberg.
This happens only on certain websites, while on others it works completely fine.
The only difference between a website giving me the issue and one working fine is that I found "Error while traversing the CSS: Error: undefined:754:1: missing '}'" in Console.

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
*Yes*

**Expected behavior**
*A clear and concise description of what you expected to happen.*
The same layout built within Oxygen should be showed in Gutenberg.

**What actually happens**
*A clear and concise description of what happens instead of the expected behavior.*
Oxygen custom styles are not applied to Gutenberg.

**Screenshots**
*If applicable, add screenshots to help explain your problem.*

Layout in Oxygen Builder:
![Oxygen-Builder-Layout](https://user-images.githubusercontent.com/69353426/89650581-f8581a80-d8c2-11ea-97be-4392b4b92822.png)

Layout in Gutenger:
![Gutenberg-Layout](https://user-images.githubusercontent.com/69353426/89650575-f55d2a00-d8c2-11ea-99e0-fc094a830c80.png)

**Desktop (please complete the following information):**
- OS: Mac OSX Catalina 10.15.6
 - Browser: Latest version of Safari, Opera, Firefox, Chrome
 - Oxygen Version: 3.4

**Comment by KittenCodes** [comment]
@mielcafedesign This is usually caused by a syntax error in your stylesheets or selectors. Please open a support ticket so that we can take a look at your site: https://oxygenbuilder.com/support.

**Comment by sergiubacioiu** [comment]
I found out the hard way that if you create a new block and the styling is not available in Gutenberg you have to enable CSS Caching.
The first thing I did when the styles were not available was to Regenerate the CSS Cache but there was no change.
After trying on a clean install and everything worked fine I re-enabled CSS Caching (usually disabled in development).

So my fix is to re-enable CSS Caching and regenerate CSS Cache.
In development I reenabled CSS Caching and enabled "Auto regenerate CSS cache on save" option from the Hydrogen Pack.
