### ISSUE TITLE
Unable to set different color for mobile menu closing icon

### ISSUE THREAD

**Issue by Zyles** [soflyy/oxygen-bugs-and-features#1405]
**Describe the bug**

We use the menu component and have a white hamburger menu for the mobile version. When user clicks the menu the actual menu itself is white with black link text.

This makes the closing icon invisible and there is no way to make a black closing icon, with a white hamburger menu. They can only be set to be the same color.

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
Yes

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
Yes

**To Reproduce**

1. Create new menu
2. Style the mobile menu button to white
3. Style the mobile background menu to white and black links

**Expected behavior**

Able to set a color for the menu closing button specifically.

**What actually happens**

Not able to set color for menu closing button, making it invisible on white background.

**Comment by Spellhammer** [comment]
Please clarify, is this when using the normal Menu element or the Pro Menu element?

**Comment by Zyles** [comment]
Normal menu.

**Comment by KittenCodes** [comment]
@Zyles You can change the closing icon colour using the below CSS in a stylesheet via Manage > Stylesheets in the top right of the builder:

```css
.oxy-nav-menu-open .oxy-nav-menu-hamburger-line {
    background-color: green;
}
```
