### ISSUE TITLE
Unable to create 404 template

### ISSUE THREAD

**Issue by dlovere** [soflyy/oxygen-bugs-and-features#1410]
**Describe the bug**
*A Javascript error prevents display of saved 404 template*

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
*Yes*

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
The 404 template that I created at http://faithful-giraffe.w6.wpsandbox.pro/?ct_template=404&ct_builder=true&ct_inner=true does not affect 404 pages. There is some other template in play that adds the class "customize-support" to the page, and shows "Recent Posts with some dummy text and the hello world post. I didn't see how to change this, however my custom 404 template still does not appear. 

**To Reproduce**
1. Create a 404 template using Oxygen in the usual manner. 
2. Visit any random page name that is not already in use. 

**Expected behavior**
The 404 template that I created should show. 

**What actually happens**
In my instance, I get the following Javascript error in FireFox Developer Edition:

`Uncaught SyntaxError: expected expression, got ','`

Tracing the error leads to the following code:
`jQuery(document).ready(function($){
        jQuery("#wp-admin-bar-edit_post_template > a").click(function(){
            jQuery.post( 'https://housing.orange3.ovcsa.unc.edu/wp-admin/admin-ajax.php', { 
                action: 'set_oxygen_edit_post_lock_transient',
                post_id: ,
                nonce: '28e1737349'
            })
        });
    });`

Server error log reveals the following:
`[Tue Aug 11 13:27:52.135346 2020] [php7:warn] [pid 27402] [client 172.17.29.177:61745] PHP Warning:  file_get_contents([/var/www/dlovere/wp/housing]/wp-content/plugins/oxygen/component-framework/components/classes/search-form/search-form.css): failed to open stream: No such file or directory in /var/www/dlovere/wp/housing/wp-content/plugins/oxygen/component-framework/components/classes/search-form.class.php on line 97, referer: https://housing.orange3.ovcsa.unc.edu/?ct_template=404&ct_builder=true&ct_inner=true&oxygen_iframe=true`

File permissions on my server:
`drwxrwxr-x. 7 apache apache   4096 Jul  9 12:01 classes
-rw-r--r--. 1 apache apache   7348 Jul  9 12:01 search-form.class.php`

**Desktop (please complete the following information):**
- OS: MacOS
 - Browser FireFox Developer Edition, Chrome
 - Oxygen Version 3.4

**Additional context**
Wordpress 5.4.2

*Server*
Server architecture | Linux 3.10.0-1127.18.2.el7.x86_64 x86_64
Web server | Apache/2.4.6 (Red Hat Enterprise Linux) OpenSSL/1.0.2k-fips mod_fcgid/2.3.9 PHP/7.2.31
PHP version | 7.2.31 (Supports 64bit values)
PHP SAPI | apache2handler
PHP max input variables | 1000
PHP time limit | 180
PHP memory limit | 1024M
Max input time | 60
Upload max filesize | 720M
PHP post max size | 64M
cURL version | 7.29.0 NSS/3.44
Is SUHOSIN installed? | No
Is the Imagick library available? | No
.htaccess rules | Custom rules have been added to your .htaccess file.

*Database*
Extension | mysqli
Server version | 5.5.65-MariaDB
Client version | 5.5.65-MariaDB
Database username | wp_housing
Database host | localhost
Database name | wp_housing
Table prefix | wp_
Database charset | utf8mb4
Database collation | utf8mb4_unicode_ci

**Comment by dlovere** [comment]
Sandbox login: http://faithful-giraffe.w6.wpsandbox.pro?upass=XJf7sxA33Aw0

**Comment by KittenCodes** [comment]
@dlovere Please set a higher priority on your 404 template. I've set it to 5 and it's now working correctly on the Sandbox site.

**Comment by dlovere** [comment]
@KittenCodes That is indeed the issue. Thank you for setting me right!

**Comment by twistedpixel** [comment]
I ran into this today. Although @KittenCodes solution works, this should still be considered a bug. Oxygen's JS is tripped up by a blank value followed by a comma because (I presume) the PHP code tries to print the page ID (which doesn't exist, because the page doesn't exist). A simple check of the value's existence would be enough to resolve this.

**Comment by harryfear** [comment]
This is surely a bug still. I'm getting this issue on an WooCommerce Product Archive page. It's also blocking transitions from running too and some other jQuery, so it's a real pain.

**Comment by osmgit** [comment]
I'm seeing this same error on the search page when no results are found. I have a modal that doesn't seem to open because of this. It only happens when I am logged into Wordpress though. If I log out, the modal works just fine.

**Comment by Kpudlo** [comment]
Related to https://github.com/soflyy/oxygen-bugs-and-features/issues/1491 and these issues have been reported internally at https://github.com/soflyy/oxygen/issues/3002
