### ISSUE TITLE
WP2Static issue because of xlink

### ISSUE THREAD

**Issue by Zyles** [soflyy/oxygen-bugs-and-features#1411]
**Describe the bug**

I am trying to statify a Oxygen built site but there is a problem because a stylesheet resides in a "xlink".

The plugin WP2Static is unable to find and save this file.

Why is the CSS stored in this xlink and how can I avoid doing that and store it i a .css file in source code?

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
Yes
**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
Yes

**To Reproduce**

1. Create website with Oxygen
2. Install WP2Static and run export

**Expected behavior**

WP2Static only finds .css files and the xlink does not have a file type.

**What actually happens**

WP2Static unable to find xlink files.

![image](https://user-images.githubusercontent.com/1741593/89965348-e5d83b00-dc4c-11ea-8200-8b3a42713bd2.png)

**Comment by Zyles** [comment]
I concluded the problem is:

1. WP2Static does not follow dynamic CSS links
2. Oxygen uses xlink CSS to have unique CSS on a per page basis

So, a solution to this problem would be an option to convert the xlink CSS into a inline block on a per page basis instead.

Then the CSS would be parsable by caching plugins and not create a unique CSS file per page.

**Comment by wplit** [comment]
Turn on Oxygen CSS cache to create a real CSS file instead of the xlink. That is what that setting does.

**Comment by Zyles** [comment]
Thanks, it works now. I tried it before but for some reason it didn't work and generated more xlinks.
