### ISSUE TITLE
Choose Color problem

### ISSUE THREAD

**Issue by SimplyIztok** [soflyy/oxygen-bugs-and-features#1412]
**Describe the bug**
After WP 5.5 update i cant choose any color in any "color choose" panel. Can be only add or change manualy (#000000), cant open mini menu for chosing color like usualy.

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
*Yes/No*

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
YES, after update WP 5.5.

**To Reproduce**

**Expected behavior**
*Open menu color or any reaction for choose color*

**What actually happens**
*Blank click, when click on color*

**Screenshots**
![Zajeta slika](https://user-images.githubusercontent.com/69559048/89966813-42892500-dc50-11ea-8204-1b6aa255a719.PNG)

**Desktop (please complete the following information):**
- OS: Win10
 - Browser 84.0.4147.125 (Uradna različica) (64-bitno)
 - Oxygen Version 3.4

**Additional context**
*Add any other context about the problem here.*

**Comment by KittenCodes** [comment]
This has been fixed in v3.5. However, v3.5 is currently in Beta and it's not recommended for use on live sites. In the mean time, I would suggest downgrading to WordPress 5.4.

**Comment by cordschneider** [comment]
> This has been fixed in v3.5. However, v3.5 is currently in Beta and it's not recommended for use on live sites. In the mean time, I would suggest downgrading to WordPress 5.4.

How long do you think that v3.5 will be in beta? There are a lot of performance and security improvements in WordPress 5.5 and I would prefer not to have to downgrade my sites to 5.4 if necessary.

**Comment by KittenCodes** [comment]
> How long do you think that v3.5 will be in beta?

v3.5 is now in RC: https://oxygenbuilder.com/portal.

**Comment by KittenCodes** [comment]
Fixed in v3.5.
