### ISSUE TITLE
Oxygen Web Builder Issue with Color Picker on latest Wordpress 5.5 update

### ISSUE THREAD

**Issue by zumpalov** [soflyy/oxygen-bugs-and-features#1415]
**Describe the bug**
*A clear and concise description of what the bug is.*

Upon updating to Wordpress 5.5 from 5.4, I lost the color picker on any menu of the Oxygen Web Builder. 

There is no circle visible but the pointer changes from a type-icon to a mouse pointer.

The field for typing is still working and writing: rgba(0,0,0,0.5) works fine. But the cirlce which was previously the color-picker menu is now a square box in which the user can type.

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
*Yes/No*

Yes, I tried removing cache, regenerating the CSS and I checked for updates from Soflyy.

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
*If yes, provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*

**To Reproduce**

1. Update to Wordpress 5.5
2. Create a new post
3. Choose a background color to any element using the menu color picker if you see one.

**Expected behavior**
*A clear and concise description of what you expected to happen.*

Have the color picker back where it is supposed to be.

**What actually happens**
*A clear and concise description of what happens instead of the expected behavior.*

**Screenshots**
*If applicable, add screenshots to help explain your problem.*

**Desktop (please complete the following information):**
 - Oxygen Version [e.g. 2.2 Alpha]

Safari Browser on a PC. Latest version of Oxygen.

**Smartphone (please complete the following information):**
 - Oxygen Version [e.g. 2.2 Alpha]

**Additional context**
*Add any other context about the problem here.*

**Comment by hrood** [comment]
I am having the exact same issue and downgrading to 5.4.2 appears to fix it for me as well.

**Comment by zumpalov** [comment]
How did you downgrade to 5.4.2? Thanks.

**Comment by maxtaleon** [comment]
I am having the same problem. For Wordpress 5.5
How to fix the problem, please help.

**Comment by reisws** [comment]
I just bought OxygenBuilder and the first thing I noticed was that the color picker was not there as I saw in the tutorials I watched. 
I can see the following errors on the console:
![Screenshot from 2020-08-12 22-09-23](https://user-images.githubusercontent.com/46939761/90086573-baa32980-dce8-11ea-8b29-610509dbcd33.png)

**Comment by reisws** [comment]
I confirm that it works with WordPress version 5.4.2. I downgraded it with the [WP Downgrade](https://wordpress.org/plugins/wp-downgrade/) plugin and the color picker is back.

**Comment by KittenCodes** [comment]
Duplicate: #1416

**Comment by greatscottd** [comment]
Why is this closed?? Didi somebody solve this issue?

If so, please post here.

**Comment by KittenCodes** [comment]
It's closed because it's a duplicate. If you check the linked issue, you will see that the issue is fixed in the latest version of Oxygen (v3.5).

**Comment by greatscottd** [comment]
I have version 3.5 and it's definitly not fixed.

Anyway, I rolled back WP for now and will wait for better days.

Thanks for your help.

**Comment by KittenCodes** [comment]
@greatscottd Please open a support ticket so that we can take a look at this for you: https://oxygenbuilder.com/support.
