### ISSUE TITLE
Colors bug

### ISSUE THREAD

**Issue by Cedrickart** [soflyy/oxygen-bugs-and-features#1416]
**Describe the bug**
*A clear and concise description of what the bug is.*

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
*Yes/No*

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
*If yes, provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*

**To Reproduce**

**Expected behavior**
*A clear and concise description of what you expected to happen.*

**What actually happens**
*A clear and concise description of what happens instead of the expected behavior.*

**Screenshots**
*If applicable, add screenshots to help explain your problem.*

**Desktop (please complete the following information):**
 - Oxygen Version [e.g. 2.2 Alpha]

**Smartphone (please complete the following information):**
 - Oxygen Version [e.g. 2.2 Alpha]

**Additional context**
*Add any other context about the problem here.*

**Comment by Cedrickart** [comment]
OS:macOS Catalina 10.15.6
browser: Google
Oxygen 3.4

I can no longer choose the colors directly from the color chart I must directly enter the color code. basically when i want to change the color the box is empty and i can only enter the color code.

**Comment by VinceBalk** [comment]
I can confirm that. color(ID) works, but color picker is broken. WP 5.5, FF 79.0, OS 10.15.6

**Comment by Spellhammer** [comment]
Known issue, fixed in 3.5 beta 1 which should be in release candidate phase very soon.
