### ISSUE TITLE
No Color Picker Appears

### ISSUE THREAD

**Issue by maxtaleon** [soflyy/oxygen-bugs-and-features#1417]
The problem is explained with the attached Video.
Color Picker is not active when highlighted and does not open when clicked.

[2020-08-13_01-40-09.zip](https://github.com/soflyy/oxygen-bugs-and-features/files/5066295/2020-08-13_01-40-09.zip)

**Comment by visualtribe** [comment]
I have the same problem. I have other sites running the newest Oxygen, but a site I just implemented Oxygen on, the color picker isn't there nor the global colors on all color picker areas. I have turned off all my plugins and still nothing. I have deleted Oxygen and reinstalled, still didn't fix. If I put in the hex and number a color appears, but is square not a circle as normal.

**Comment by reisws** [comment]
This problem started yesterday after updating WordPress to 5.5, if you downgrade to the previous version (5.4.2) the Color Picker will work correctly.

I downgraded using the [WP Downgrade](https://wordpress.org/plugins/wp-downgrade/) plugin and the Color Picker is back.

The Oxygen team will fix this for sure, but until then using the WordPress 5.4.2 will do.

**Comment by KittenCodes** [comment]
Duplicate: #1414
