### ISSUE TITLE
Warning: Invalid argument supplied for foreach() 

### ISSUE THREAD

**Issue by Cedrickart** [soflyy/oxygen-bugs-and-features#1418]
**Describe the bug**
*A clear and concise description of what the bug is.*

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
*Yes/No*

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
*If yes, provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*

**To Reproduce**

**Expected behavior**
*A clear and concise description of what you expected to happen.*

**What actually happens**
*A clear and concise description of what happens instead of the expected behavior.*

**Screenshots**
*If applicable, add screenshots to help explain your problem.*

**Desktop (please complete the following information):**
 - Oxygen Version [e.g. 2.2 Alpha]

**Smartphone (please complete the following information):**
 - Oxygen Version [e.g. 2.2 Alpha]

**Additional context**
*Add any other context about the problem here.*

**Comment by Cedrickart** [comment]
MacOS Catalina 10.15.6 on chrome with Oxygen 3.5I have this messages when i open the builder from the pages section:

Warning: Invalid argument supplied for foreach() in /homepages/25/d836466075/htdocs/clickandbuilds/hoiriedubarbierparis/wp-content/plugins/oxygen/component-framework/includes/ajax.php on line 625

Warning: Invalid argument supplied for foreach() in /homepages/25/d836466075/htdocs/clickandbuilds/hoiriedubarbierparis/wp-content/plugins/oxygen/component-framework/includes/ajax.php on line 600

Everything disappeared !!!

**Comment by Spellhammer** [comment]
@Cedrickart Please send us a ticket at support@oxygenbuilder.com with login details so that we can take a look for you.
