### ISSUE TITLE
Integrate ACF Options pages into Oxygen

### ISSUE THREAD

**Issue by JackGraal** [soflyy/oxygen-bugs-and-features#142]
**Describe the feature you'd like to see included in Oxygen.**
Allowing to insert data from ACF Options Page (like a Theme Settings page that is global for the whole website) the same way that ACF custom fields work right now for data from post types. Right now it's only possible with a custom block and an additional "option" value in the code, like this: `<img  src="<?php the_field('logo','option'); ?>" />` - to show a logo that is set in the Theme Settings page created with ACF Options page.

**What are the use cases for this feature?**
Setting a global logo, footer, gallery and other ACF data that can be used on every page, in header, footer and other repeatable parts. It's also an easier way for a client to edit information.

**Examples of this feature or functionality.**
No need for providing examples.

**Comment by adrien-robert** [comment]
I work a lot if ACF Options pages and I would love to see those implemented in Oxygen as well!

**Comment by adrien-robert** [comment]
Can we have an update on this one please? @Spellhammer

**Comment by alriksson** [comment]
+1 still not implemented or any handy solution to work with. Should be working with the PHP function return value as well. But no success on my end.

**Comment by JackGraal** [comment]
ACF Options page works with Oxygen via the PHP function return value. Just write "get_field" into the first window and "my_acf_field_name,option" into the second. Don't put space between your acf field name and "option" - there has to be just a comma with no spaces!

**Comment by alriksson** [comment]
Not working that way when fetching from an ACF repeater and when it's an image field in ACF to fetch to image block of oxygen.

If you have solutions to both of my challenges above it would be great. tried different fetch values for repeater since has_rows and subfields have to be fetched differently.

But struggle with the ACF repeater into oxygen from the options page or if image field.

Yes agree, should be an easy way for support.

**Comment by the-stew** [comment]
Making ACF options pages easier in Oxygen would be the cherry on top for the 'ultimate client mode' that the Gutenberg feature introduced.

**Comment by Oxymaniac** [comment]
+1

**Comment by alriksson** [comment]
Anyone with a solution on how to fetch images from options page until this is implemented. If static or if wrapped in a repeater? Thanks in advance.

**Comment by martonjuha** [comment]
> Anyone with a solution on how to fetch images from options page until this is implemented. If static or if wrapped in a repeater? Thanks in advance.

Hi! Did you find any solution?
I have the same problem. I want to add dinamic data from options page to a backround image.
Thanks in advance.

**Comment by alriksson** [comment]
@Spellhammer Any tips until you natively support this in oxygen to share?

**Comment by alriksson** [comment]
I only receive notifications but can't see the comments in the thread.

@the-stew I've tried this but it does not fetch images for me. It is either blank or just a broken image. tried various ways to fetch the field without success. A quick recording would be great since I don't see what is wrong as you mention this should work. But for me, it does not, unfortunately.

Preferably I would like to fetch the image and other fields that are within an ACF repeater. Which should be possible with the oxygen repeater and php function return value.

**Comment by alriksson** [comment]
@JackGraal How would you write to fetch data from ACF options if it's in a repeater. oxygen builder find the acf repeater but do not fetch the data.

**Comment by alriksson** [comment]
https://youtu.be/0kMZfjPwtZs?t=555
Even Elementor support it now.

**Comment by alexanderkladov** [comment]
@alriksson Just checked out the Elementor's implementation and it's pretty good! I wish Oxygen had that level of integration too.

**Comment by alriksson** [comment]
Hoped so too, many Oxygen users use ACF so support for options page in all verticals would be useful. Including more field data, such as fetching custom fields from a selected post object etc. Condiition support for options page etc.

**Comment by lonelyviking** [comment]
This is very needed! +1000 from me.

**Comment by pablodesign** [comment]
this is a big plus one from me as well please

**Comment by alexanderkladov** [comment]
Just FYI, until they hopefully implement this properly, you can use Oxygen's [Dynamic Data feature](https://oxygenbuilder.com/documentation/templating/dynamic-data/) with **PHP Function Return Value** as a data source to get your ACF options data. Enter ACF's `get_field` function under **Function Name** and `ACF_FIELD_NAME, options` under **Function Arguments** (replace `ACF_FIELD_NAME` with your unique field name). It's not ideal & ugly, but it works for simple text fields.

**Comment by wpsumo** [comment]
@alexanderkladov Works in all cases except once you want to use value from dynamic data in conditions then you break frontend thats my issue. As for right nwo you have to setup your own conditions for options pages which becomes more raw and a conditon for each field depending on how you want to use them.

As an example fi you want your condition to liten to the value of a options page you have to raw code the condition to a specific options page field. In the long run it's not as smooth but it works. Just a lot of conditions :D

**Comment by gslwebsolutions** [comment]
+1 waiting for this as well

**Comment by thomasjulienalain** [comment]
+1

**Comment by gabrieluntura** [comment]
+1

**Comment by beleancristian** [comment]
+1

**Comment by YammYcoding** [comment]
+1

**Comment by eduardoyi** [comment]
+1

**Comment by musik92** [comment]
The bigger issue is using repeaters with option pages, there is no easy fix I know about other than writing your own repeater code.

**Comment by wpsumo** [comment]
@musik92 Correct, it should be an easy native way.

**Comment by avocadesign** [comment]
This is an issue for us as we've used options fields on every site we've built for years and working with them in Oxygen is a pain at the moment

**Comment by gleysen** [comment]
+1

**Comment by JonathanFortin** [comment]
+1

**Comment by jamescrabb** [comment]
2 years and still no word on this.

I think the ACF integration is great it's just not completely integrated. For example Options page custom fields and also taxonomy custom fields don't work using the UI

**Comment by T-21** [comment]
+1

**Comment by heyfletch** [comment]
Chiming in with an example for @alexanderkladov's workaround above:

`[oxygen data='phpfunction' function='get_field' arguments='email_address, options']`

**Comment by KittenCodes** [comment]
> Chiming in with an example for @alexanderkladov's workaround above:

I think the argument should be 'email_address,option'

**Comment by heyfletch** [comment]
`options` works, `option` does not.

**Comment by alexanderkladov** [comment]
> `options` works, `option` does not.

@heyfletch Both `option` & `options` should work just fine. Check [official ACF  `get_field()` documentation](https://www.advancedcustomfields.com/resources/get_field/).


If anyone is still struggling with the concept, here is site demo I setup with a working example (it will be erased in a few days, so if you can't login, then just watch the video below): [https://oxygen-qcqbtwakyaddl.oxygen-demo.qsandbox.me/wp-admin/?wtlwp_token=e8e0afa236d39594f00f0bf97519e253](https://oxygen-qcqbtwakyaddl.oxygen-demo.qsandbox.me/wp-admin/?wtlwp_token=e8e0afa236d39594f00f0bf97519e253)

And here is a video demo of how to use ACF Options in Oxygen Conditions (I used both both `option` & `options` in the video to demonstrate that they both work):

[![Oxygen Conditions with ACF Options](https://i.imgur.com/He2HYmm.png)](https://drive.google.com/file/d/1ZOwxd1mKWoon2qo0R4TFWXFZSKZR2m3Y/view?usp=sharing "Oxygen Conditions with ACF Options")

**Comment by hieptd** [comment]
+1

**Comment by sercanvirlan** [comment]
+1

**Comment by hayatbiralem** [comment]
+1

**Comment by jdemailas** [comment]
+1 

Not being able to use acf repeaters from options page is a big pain in oxygen

**Comment by Spellhammer** [comment]
ACF options page support added in 3.9.

**Comment by paulusmacaulus** [comment]
> > `options` works, `option` does not.
> 
> @heyfletch Both `option` & `options` should work just fine. Check [official ACF `get_field()` documentation](https://www.advancedcustomfields.com/resources/get_field/).
> 
> If anyone is still struggling with the concept, here is site demo I setup with a working example (it will be erased in a few days, so if you can't login, then just watch the video below): https://oxygen-qcqbtwakyaddl.oxygen-demo.qsandbox.me/wp-admin/?wtlwp_token=e8e0afa236d39594f00f0bf97519e253
> 
> And here is a video demo of how to use ACF Options in Oxygen Conditions (I used both both `option` & `options` in the video to demonstrate that they both work):
> 
> [![Oxygen Conditions with ACF Options](https://camo.githubusercontent.com/89b617330263349f00ae49a66faf07459432a21fc3cf132e653a3a73a535d84b/68747470733a2f2f692e696d6775722e636f6d2f48653248596d6d2e706e67)](https://drive.google.com/file/d/1ZOwxd1mKWoon2qo0R4TFWXFZSKZR2m3Y/view?usp=sharing)
> 
> EDIT:
> 
> > I think the argument should be 'email_address,option'
> 
> @KittenCodes Forgot to add that spaces around **Function Arguments** don't seem to matter, as long as syntax is correct otherwise. After I recorded a video, I added section 4, where I have passed the argument in a butchered way, where I had like 10 spaces after the comma (like `option_4, _10_SPACES_HERE_ option`). Excess spaces got ignored & everything worked as expected.
________
I have just been informed from a client of things missing on their page, when i checked, the spaces before the options apparently 'do' now matter as it wont work when they are there, i havent worried overly because of this post, now it matters, meh. It would be great for Oxygen to allow the spaces again, why it has been changed is beyond me when stated here that it doesn't matter.

**Comment by KittenCodes** [comment]
> It would be great for Oxygen to allow the spaces again, why it has been changed is beyond me when stated here that it doesn't matter.

This was a change made by ACF themselves in a recent update - it's not something that we've changed.

**Comment by OatTeeraphat** [comment]
I need to use  ACF repeater field in from option page :( , pls support this feature

**Comment by wpsumo** [comment]
+1

**Comment by exetico** [comment]
> I need to use repeater field in from option page apply to dynamic slider , pls support this feature

+1 

Do you know any workarounds?

**Comment by alexanderkladov** [comment]
> > I need to use repeater field in from option page apply to dynamic slider , pls support this feature
> 
> +1
> 
> Do you know any workarounds?

Just use a PHP code block at this point. That way you won't have to wait on an official integration & can potentially make your option retrieval more efficient by fetching everything at once via ACF's `get_fields( 'options' )` function (compared to fetching them individually via `get_field( 'field_name', 'options')` for every field, which increases the number of requests from cache, or, worst case scenario, directly from DB).

It's as simple as this:

```php
// Stop, if ACF is not active
if ( ! class_exists( 'ACF' ) ) { return; }

$acf_repeater = get_field( 'acf_options_repeater', 'option' );

// Stop, if repeater doesn't exist or is empty
if ( ! $acf_repeater || ! count( $acf_repeater ) ) { return; }

// Loop through repeater rows
foreach ( $acf_repeater as $acf_repeater_row ) {
  // Do whatever you need to do with each field inside a row.. E.g.:
  $field_1_safe = wp_strip_all_tags( $acf_repeater_row['field_1_name'] );
  echo $field_1_safe;
}
```
