### ISSUE TITLE
Hover effect glitch on Chromium browsers

### ISSUE THREAD

**Issue by veebzid** [soflyy/oxygen-bugs-and-features#1420]
I tried replicating [this effect](https://www.youtube.com/watch?v=QBWmnoXjvqw), but I'm getting extreme perspective glitches. It only happens on Chrome and Edge, seems to be working fine on Firefox.

**Comment by KittenCodes** [comment]
@veebzid Please open a support ticket so that we can take a look at this for you: https://oxygenbuilder.com/support.
