### ISSUE TITLE
Semantic Issues

### ISSUE THREAD

**Issue by ezosher** [soflyy/oxygen-bugs-and-features#1421]
Hey guys thanks for this great Plugin,

I not sure if its a bug its deliberately like so, but I'v noticed a `Semantic` issue that happens when you select the `Text Element` from the Basics panel. the element defaults to a `div` tag instead of a `p` tag or maybe other text related tags. 
I know its not a real issue, but oxygen thrives to be the best and in my opinion it is :). plus its a bit annoying when you using classes.

Thanks in advance to all.

**Comment by KittenCodes** [comment]
@ezosher This is the intended behaviour.
