### ISSUE TITLE
Animations added to classes are not working in the editor.

### ISSUE THREAD

**Issue by Guido81** [soflyy/oxygen-bugs-and-features#1422]
**Describe the bug**
*A clear and concise description of what the bug is.*
Animations added to classes are not working in the editor.

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
*Yes

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
*If yes, provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*
Yes, but in the sandbox the animations doesn't work but you can see the text.
http://light-warbler.w6.wpsandbox.pro/

**To Reproduce**
1. See link: https://www.loom.com/share/2fb2efc23c7a4d1ea7c48f196df0eca8

**Expected behavior**
*A clear and concise description of what you expected to happen.*
To see the animations work in the visual builder. In my case no text is showing up so anoying to edit.

**What actually happens**
*A clear and concise description of what happens instead of the expected behavior.*
Text stays hidden.

**Screenshots**
*If applicable, add screenshots to help explain your problem.*
See video: https://www.loom.com/share/2fb2efc23c7a4d1ea7c48f196df0eca8

**Desktop (please complete the following information):**
- OS: [e.g. iOS] Windows
 - Browser [e.g. chrome, safari] Chrome
 - Oxygen Version [e.g. 2.2 Alpha] Oxygen 3.5 Beta

**Additional context**
*Add any other context about the problem here.*
I also noticed that putting a animation i a class and apply that class to an element in the first section is giving issues on the front-end. Sometime works sometimes not. For elements in the first section i need to add the animation to the ID. It seems the on scroll doesn't really work nicely on the first section of the page.

**Comment by KittenCodes** [comment]
@Guido81 I suspect this is caused by the Shortcode element in your page. Please select the Shortcode element and then select "Don't render in Oxygen" in the Properties pane on the left. Save the design and reload the builder.

Do the animating elements then show correctly for you?

**Comment by Guido81** [comment]
> @Guido81 I suspect this is caused by the Shortcode element in your page. Please select the Shortcode element and then select "Don't render in Oxygen" in the Properties pane on the left. Save the design and reload the builder.
> 
> Do the animating elements then show correctly for you?

@KittenCodes  I changed the shortcode to " Don't render in Oxygen" and now the text is visible. The animation still don't work though in the Visual Builder. But that's not a big issue. At least i see the text now and can edit. 

Thanks!
Guido
