### ISSUE TITLE
ACF image fields don't work in Repeaters

### ISSUE THREAD

**Issue by Scottzonn** [soflyy/oxygen-bugs-and-features#1423]
**Explanation**
I have an ACF repeater with an image field in it. The image return type is array. 

I have an Oxygen repeater field with an image element in it.  The Oxygen repeater dynamic data is set to the ACF repeater. 

I insert dynamic data for my image URL and choose the ACF Repeater Image. I get no options for choosing image size. When I click Insert, nothing is displayed. 

**To Reproduce**
1. Create a repeater in ACF pro with an image field inside it. 
2. Set the ACF image field to return an array.
3. Edit a page with oxygen and add a repeater. Set the repeater dynamic data to the ACF repeater
4. Add an image to the repeater. Try to set the image to the ACF image. 

**Expected behavior**
When the ACF Image Field is set to return an array, Oxygen should show the following fields like in your demo video of acf. The image should work.
![image](https://user-images.githubusercontent.com/8142923/90227785-7c2c7c80-de58-11ea-8c8a-5751e5b3f405.png)

**What actually happens**
No image appears. No size select fields are shown.
![image](https://user-images.githubusercontent.com/8142923/90227639-3ec7ef00-de58-11ea-9a9b-33d79a60c37b.png)
![image](https://user-images.githubusercontent.com/8142923/90227672-4c7d7480-de58-11ea-98e2-0cf4ea44bdf3.png)

A work around is to set the ACF image return type to URL, but this is not ideal.

**Comment by KittenCodes** [comment]
@Scottzonn Please set ACF to return the image URL and not the Array.
