### ISSUE TITLE
Enabling CSS cache breaks the layout

### ISSUE THREAD

**Issue by Zyles** [soflyy/oxygen-bugs-and-features#1426]
**Describe the bug**

I have random bug out of nowhere. When I enable CSS caching and regenerate cache, the frontpage design messes up. The fonts do not render correctly with the Google font used and the margins are all incorrect.

When I disable CSS caching the site will render okay again.

This only happens on the front page.

I did nothing special really, it just started to happen. Now the layout is completely broken.

Even with caching enabled it still creates an xlink stylesheet (which is impossible to cache)

`<link   rel='stylesheet' id='oxygen-styles-238-css'  href='https://example.com/?post_id=238&#038;xlink=css&#038;ver=5.4.2' type='text/css' media='all' />`

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
Yes

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
No

**To Reproduce**

Don't know.

**Expected behavior**

Website should render correctly.

**What actually happens**

CSS breaks on front page for some random reason.

**Comment by Zyles** [comment]
Is this normal?
```
CSS Generation Process Started
**Universal CSS cache not generated.**
...
```

Is it also normal that it only generates CSS for templates, and not actual posts?

**Comment by KittenCodes** [comment]
@Zyles 

> Is this normal?

Please enable Oxygen's CSS caching before regenerating the CSS cache.

If you're still having problems, please open a support ticket so that we can take a look at your site: https://oxygenbuilder.com/support.

**Comment by Zyles** [comment]
I generated it 5 times, how many times do you want me to regenerate?

![image](https://user-images.githubusercontent.com/1741593/90330837-21a63400-dfb0-11ea-8d2c-696e171de6c1.png)

**Comment by KittenCodes** [comment]
@Zyles Please open a support ticket so that we can take a look at your site: https://oxygenbuilder.com/support. You need to click "Something's broken and I need help".
