### ISSUE TITLE
Color Wheel not available

### ISSUE THREAD

**Issue by linformatique** [soflyy/oxygen-bugs-and-features#1433]
**Describe the bug**
Color Wheel not available (for text, background and other)

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
*Yes*

WordPress					---»	Version 5.5 
Oxygen Builder				---»	Version 3.4
Installed Plugin				---»	Classic Editor 1.6
Ensure a Modern PHP			---»	Version 7.4.8
Clear All Caches				---»	Done
Check & Resave Your Permalinks	---»	Done
Re-Sign Oxygen Shortcodes		---»	Done
Regenerate Oxygen's CSS Cache	---»	Done
Database Collation set to :		---»	utf8mb4_general_ci

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
http://perfect-jaguar.w5.wpsandbox.pro/?ct_template=main&ct_builder=true
Applies to pages, post and other but only did MAIN TEMPLATE for demo purpose

**Expected behaviour**
The white color dot should be there and once click the color wheel should appear.

**What actually happens**
No white color dot and cannot click so no color wheel.

**Screenshots**
See attach 2 GIF files
![Color-Wheel-01](https://user-images.githubusercontent.com/6477144/90337516-04259a00-dfb1-11ea-98af-d88f9349ae2d.gif)
![Color-Wheel-02](https://user-images.githubusercontent.com/6477144/90337517-04be3080-dfb1-11ea-8929-c358732cb8e6.gif)

**Impression**
Problem stem from Wordpress 5.5 update

Regards,

Ducktape
PS Please send me notice when fix

**Comment by KittenCodes** [comment]
Duplicate #1412 

Fixed in 3.5 RC 1.
