### ISSUE TITLE
is Oxygen Version 3.4 compitable with wp 5.5? Color menu not showing.....

### ISSUE THREAD

**Issue by yahya-github** [soflyy/oxygen-bugs-and-features#1435]
when I click an element to change its color from the side menu there is no options. I have to enter the color manually! 

Oxygen version 3.4
WP version 5.5

**Comment by kihoshin** [comment]
I have the same problem.

**Comment by KittenCodes** [comment]
Duplicate: https://github.com/soflyy/oxygen-bugs-and-features/issues/1412
