### ISSUE TITLE
Woocommerce Product Builder

### ISSUE THREAD

**Issue by bchangia** [soflyy/oxygen-bugs-and-features#1437]
**Describe the bug**
*A clear and concise description of what the bug is.*
Product Builder view is not same as Product Tab view

https://share.getcloudapp.com/NQurK1OK - Product Builder Tab
https://share.getcloudapp.com/4gu9OJzo - Product Tab View 

We can't customize each element of the Product Builder view hence I was using each element separately but the visiblity is completly different please help.

**Comment by KittenCodes** [comment]
> Product Builder view is not same as Product Tab view

You need to add the Product Builder to your template and then move your design inside it to overwrite the default design in the Product Builder.
