### ISSUE TITLE
2.3 alpha custom design sets not transferring selectors?

### ISSUE THREAD

**Issue by wplit** [soflyy/oxygen-bugs-and-features#144]
**Describe the bug**
Not sure if it's a bug, or by design.
Classes, all the styles from IDs, global colors all transfer over from one site to another. But any custom selectors that have been created, don't.

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
Yes, http://lively-pony.w6.wpsandbox.pro/oxy_user_library/test-header/

You can see the last menu item has different styling. This doesn't get transferred over as custom selectors were needed to target the last menu item.

**To Reproduce**
In the example, I added a custom selector in order to target the menu item. Something like.. 
`#header-menu .menu-item:last-child ` 

**Expected behavior**
After saving the template, screenshoting, I expected it to carry over onto a new site when I next visited the design set and added to the site. Everything looked as it should in the screenshot, of course, but the selectors do not get carried over so what actually appeared on the next site was missing important styles. The last menu item had no extra styles applied.

**Additional context**
As I said before, this maybe by design. If so, i think it limits what we can put in our design sets. I use custom selectors all the time. Otherwise we can't create flexible layouts that adapt depending on how many items are present, by using :nth-child of child elements etc.

**Comment by wplit** [comment]
Found another example use case for the same thing. When building a blog post template for a design set, I wanted to include basic styles for default WordPress blocks to match the style of the template. I don't seem to be able to find a way of including those styles in the template that will transfer to a new site using the template from the set.

**Comment by srikat** [comment]
More on this topic incl. a screencast: https://www.facebook.com/groups/1626639680763454/permalink/2218490508245032/

**Comment by Spellhammer** [comment]
This is working as intended.

Custom selectors are excluded intentionally to avoid confusion for the end user. Additionally, including any custom selector would require us to include all custom selectors, which obviously isn't great.
