### ISSUE TITLE
Color settings

### ISSUE THREAD

**Issue by rixk-source** [soflyy/oxygen-bugs-and-features#1442]
I opened oxygen and noticed my color settings didn't allow me to use the color grid/circle, I have to manually write the color I want and it's limiting my creativity. Anyone knows how to deal with the issue?

**Comment by kihoshin** [comment]
I think this is due to the WordPress 5.5 version.

I have the same issue on the site with WordPress 5.5.

**Comment by KittenCodes** [comment]
Duplicate: https://github.com/soflyy/oxygen-bugs-and-features/issues/1412
