### ISSUE TITLE
Oxygen 3.5_RC1 - Adding custom attributes to repeater div locks us out of repeater

### ISSUE THREAD

**Issue by wplit** [soflyy/oxygen-bugs-and-features#1443]
**Describe the bug**
Not major issue but if we add a custom attribute to the child div of the repeater component, then click 'apply attributes' the attribute is added, but it removes the oxy_repeater_original class from the first repeater div making it uneditable. 

We then have to go back to the query settings to click Apply Query Params in order to rebuild the repeater so it's editable again. It should probably trigger a rebuild so users don't have to go through that process.

**Comment by KittenCodes** [comment]
Fixed in v3.6.
