### ISSUE TITLE
Heading block creates an internal div tag inside

### ISSUE THREAD

**Issue by roireshef** [soflyy/oxygen-bugs-and-features#1445]
**Describe the bug**

* This internal div is useless and creates page overflow issues on some viewport values. Why not just do <h?>content</h?> ? *

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
*Yes*

**Comment by KittenCodes** [comment]
@roireshef This isn't normal behaviour - please see the heading tag at the top of the page here: https://oxygen-qxfx7nza9nval.oxygen-demo.qsandbox.me/.

First off, please try running a plugin conflict test: https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/.

If that doesn't help, please open a support ticket: https://oxygenbuilder.com/support. You need to select "Something's broken and I need help".
