### ISSUE TITLE
Display problem using Safari on a Mac

### ISSUE THREAD

**Issue by greenfrog111** [soflyy/oxygen-bugs-and-features#1447]
I recently completed a site built in Oxygen for a client. It's at https://naturalhealthfocus.com.au/wellbeing/

The site displays as intended in all the browsers I've tested - and in the simulators I've used. But for some reason I cannot fathom, it looks weird on my Mac in Safari.

The first screenshot below is the site in Firefox. The second is when I use Safari. As you can see, Safari doesn't display the header (and footer) or the sidebar.

https://naturalhealthfocus.com.au/wellbeing/display-problems-temp-page/

Has anyone else experienced this problem with Safari? Is there a fix? Does the site display normally for you?

**Comment by twistedpixel** [comment]
Looks normal to me in Safari but you do have a few JS console errors you will want to look at.

**Comment by twistedpixel** [comment]
Try emptying Safari's cache and reloading.

**Comment by greenfrog111** [comment]
Thx twistedpixel. Your post prompted me to check my Prefs in Safari once again, and I noticed that under the 'Reader' rab (Preferences>Website>Reader) I'd somehow selected that particular website as 'On'. Switched it off and problem fixed. Sorry to have wasted ppl's time.

**Comment by twistedpixel** [comment]
No problem - we all have the occasional brain fart!

If you haven’t already you should close this topic to keep things clean.
