### ISSUE TITLE
Warning:  strpos() expects parameter 1 to be string

### ISSUE THREAD

**Issue by irfan-muhammad** [soflyy/oxygen-bugs-and-features#1448]
**Describe the bug**
*A clear and concise description of what the bug is.*

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
*Yes/No*

Yes 
**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
*If yes, provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*

**To Reproduce**

**Expected behavior**
*A clear and concise description of what you expected to happen.*

**What actually happens**
*A clear and concise description of what happens instead of the expected behavior.*

`NOTICE: PHP message: PHP Warning:  strpos() expects parameter 1 to be string, array given in plugins/oxygen/component-framework/components/component.class.php on line 3564`

**Screenshots**
*If applicable, add screenshots to help explain your problem.*

**Desktop (please complete the following information):**
 - Oxygen Version [e.g. 2.2 Alpha]

Version 3.1.1

**Smartphone (please complete the following information):**
 - Oxygen Version [e.g. 2.2 Alpha]

**Additional context**
*Add any other context about the problem here.*

I am using Oxygen Builder Version 3.1.1and getting below warning:

`NOTICE: PHP message: PHP Warning:  strpos() expects parameter 1 to be string, array given in plugins/oxygen/component-framework/components/component.class.php on line 3564`

**Comment by malikshi** [comment]
I got the same problem here with the latest oxygen 3.5, multiple chain error line 3622 till 3642
`Got error 'PHP message: PHP Warning:  strpos() expects parameter 1 to be string, array given in /home/runcloud/webapps/QUANTUM/wp-content/plugins/oxygen/component-framework/components/component.class.php on line 3622 .... referer: https://MYSITES/`

**Comment by rcg4u** [comment]
3.6 beta 1 fixes this error https://oxygenbuilder.com/2020/09/28/oxygen-3-6-beta-1-now-available

**Comment by KittenCodes** [comment]
> PHP Error "strpos() expects parameter 1 to be string, array given in component.class.php."

Fixed in v3.6 Beta.

**Comment by Cenay** [comment]
Please note that in version 3.7.1 this issue continues, tho the line number has changed. Posting the new errors message below: 
[25-Mar-2021 00:10:42 UTC] PHP Warning:  strpos() expects parameter 1 to be string, array given in /home/s104/html/wp-content/plugins/oxygen/component-framework/component-init.php on line 2366

**Comment by KittenCodes** [comment]
> Please note that in version 3.7.1 this issue continues, tho the line number has changed. Posting the new errors message below:
> [25-Mar-2021 00:10:42 UTC] PHP Warning: strpos() expects parameter 1 to be string, array given in /home/s104/html/wp-content/plugins/oxygen/component-framework/component-init.php on line 2366

This is a different file - it's not related to the original issue in this bug report. I've reported this error internally.

**Comment by Josnoddy** [comment]
> Please note that in version 3.7.1 this issue continues, tho the line number has changed. Posting the new errors message below:
> [25-Mar-2021 00:10:42 UTC] PHP Warning: strpos() expects parameter 1 to be string, array given in /home/s104/html/wp-content/plugins/oxygen/component-framework/component-init.php on line 2366

I'm experiencing the same issue.

"[Thu Apr 01 22:34:51.661830 2021] [proxy_fcgi:error] [pid 650:tid 140458431014656] [client 82.152.158.197:51570] AH01071: Got error 'PHP message: PHP Warning: strpos() expects parameter 1 to be string, array given in /home/557544.cloudwaysapps.com/nrghwvueya/public_html/wp-content/plugins/oxygen/component-framework/component-init.php on line 2366PHP message: PHP Warning: strpos() expects parameter 1 to be string, array given in /home/557544.cloudwaysapps.com/nrghwvueya/public_html/wp-content/plugins/oxygen/component-framework/component-init.php on line 2366', referer: https://nextlevelsocial.co.uk/?ct_template=default-page&ct_builder=true&ct_inner=true&oxygen_iframe=true"
