### ISSUE TITLE
Issue when edit the template & select template option 'singular/archive/other'

### ISSUE THREAD

**Issue by manuhal** [soflyy/oxygen-bugs-and-features#1449]
Issue:
After updating to wordpress 5.5, when editing the template, selecting the template type (singular or archive or other) will collapse the whole Oxygen meta-box. It is very annoying. 

Sandbox:
http://healthy-quetzal.w6.wpsandbox.pro/

To Reproduce:
Watch and follow the video here, it will demonstrate the issue before and after WP5.5:
https://www.youtube.com/watch?v=Cx-WkN1bJf0

Desktop:
- OS: IOS
- Browser: firefox, safari, chrome
- Oxygen Version 3.4
- Wordpress Version 5.5

**Comment by Spellhammer** [comment]
Fixed in 3.5.
