### ISSUE TITLE
Malware in video.class.php and progress-bar.class.php

### ISSUE THREAD

**Issue by pzeylstra** [soflyy/oxygen-bugs-and-features#1454]
Got a warning from my provider this morning:

Last night a malware scan detected that the following infected files are present on the server:
{HEX}base64.inject.unclassed.6 : **/wp-content/plugins/oxygen/component-framework/components/classes/video.class.php
{HEX}base64.inject.unclassed.6 : **/wp-content/plugins/oxygen/component-framework/components/classes/progress-bar.class.php

I bought Oxygen yesterday and tried it for the first time in a clean testing environment.

**Comment by KittenCodes** [comment]
@pzeylstra This is a false positive. Some scanners tend to pick up files that are using the PHP base_64 encode function.
