### ISSUE TITLE
[USABILITY REQUEST] Add some of those shape dividers to the core

### ISSUE THREAD

**Issue by YammYcoding** [soflyy/oxygen-bugs-and-features#1456]
1. There is this svg editor online app here: https://www.shapedivider.app/

With some beautiful shape dividers, that oxygen doesn't have. It would be nice to have these one added too. They are all very nice.

**Comment by KittenCodes** [comment]
You can copy the <svg> code from ShapeDivider.app and use it in the Custom Shape box in Oxygen. It would make more sense to copy it from the app so that you can customise it yourself.
