### ISSUE TITLE
[BUG] Cannot do negative margin of a layered div when top section have a shape divider on it

### ISSUE THREAD

**Issue by YammYcoding** [soflyy/oxygen-bugs-and-features#1458]
1. Make two sections with differente bg colors.
2. Add shape divider and section to top section.
3. add some height to bottom section.
4. Define video to z-index: 10

[BUG] video does not bleed to the bottom section, instead, it gets eaten by top section margin, like showed in folowing picture:

![image](https://user-images.githubusercontent.com/1200923/90648470-f0c43a00-e20f-11ea-8ce7-82238177378d.png)

**Comment by Spellhammer** [comment]
Not a bug. Sections with Shape Dividers are intentionally given overflow: hidden.
