### ISSUE TITLE
Icon color missing when using variable css colors

### ISSUE THREAD

**Issue by MIJNDESIGN** [soflyy/oxygen-bugs-and-features#1459]
**Describe the bug**
Icon color missing when using variable css colors

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
Yes

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
Yes

*If yes, provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*

http://excited-gnu.w6.wpsandbox.pro?upass=fB80h06dRpIM

**To Reproduce**
1. Go to
Go to stylesheet and make a variable color example: 
:root {
	--red: #ff0000;
}

2. Click on 
Settings -> Global Styles -> Colors and make a color with var(--red)
3. Click on
Click on a color picker the color is there but the icons are missing

**Screenshots**
*If applicable, add screenshots to help explain your problem.*

https://share.getcloudapp.com/geuzbNLN

**Comment by KittenCodes** [comment]
Duplicate: https://github.com/soflyy/oxygen-bugs-and-features/issues/204
