### ISSUE TITLE
DONE: All sizes for any field wich support sizes

### ISSUE THREAD

**Issue by Caffeinedesign** [soflyy/oxygen-bugs-and-features#146]
**Describe the feature you'd like to see included in Oxygen.**
Simple, we have many kind of sizes, some of us use mostly some of them, other times for a project would be bettere to use a size unit than another etc... 
we can simply have
PX % EM REM VW VH CALC for anything wich has a size in? fonts, borders, padding, anything wich supports them ;)

**What are the use cases for this feature?**
Flexibility, customisation, easy to implement

**Examples of this feature or functionality.**
Beaver builder and divi are doing this (i didn't notice if both do for all sizes, but for example i remember divi have vw on borders)

**Comment by bbdstar** [comment]
Yes, this should be commonplace. Also being able to set the unit of measure by typing would be cool. ie. "100vh" overrides px and sets the unit of measure to "VH".  Webflow handles this really well.

**Comment by Caffeinedesign** [comment]
Yes, probably the override features is still better (and probably easier to develop, you don't have to add anything to interface, just transform it in a text field wich accepts anything lol). 
a field where you can just write anything:
100vh
calc(100% - 2.5em) 
etc etc

**Comment by marou-lia** [comment]
+1 I use rem all the time in my design.

**Comment by KittenCodes** [comment]
Custom units added in v3.6: https://oxygenbuilder.com/2020/11/06/oxygen-3-6-now-available/
