### ISSUE TITLE
[REQUEST] What if we could save the entire page as a reusable part ?

### ISSUE THREAD

**Issue by YammYcoding** [soflyy/oxygen-bugs-and-features#1460]
Today I had this particular need, one page would be reused like 8 or 9 times. While thinking about weather I should duplicate the page 9 times, or save reusable parts for all sections, I had this question in my mind:

What if we could save all page content as a single reusable part ?

Maybe we could call it 'reusable page' :)  Tell me what you guys think, it's an idea...

**Comment by MIJNDESIGN** [comment]
Maybe you can wrap all the section into a div and make that div reusable.
https://share.getcloudapp.com/xQuLb1Ob
