### ISSUE TITLE
template data failed to load

### ISSUE THREAD

**Issue by tomatpercipi** [soflyy/oxygen-bugs-and-features#1461]
**Describe the bug**
*A clear and concise description of what the bug is.*

When I open a template for custom post type (Toolset Type), I have to manually select the first post, often twice, to fetch the data (it finally works so not a big issue, just an annoying UX), otherwise, it displays "data failed to load"
This is happening on WP 5.5 on the current Oxygen version or on the RC1

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
*Yes/No*

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
*If yes, provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*

**To Reproduce**
1. Go to 'open template for single custom post'

**Expected behavior**
*A clear and concise description of what you expected to happen.*
just before, Oxygen was able to fetch relevant data without problems

**What actually happens**
*A clear and concise description of what happens instead of the expected behavior.*
a red message on top left  "template data failed to load"

**Screenshots**
*If applicable, add screenshots to help explain your problem.*

**Desktop (please complete the following information):**
- OS: [e.g. iOS] W10
 - Browser [e.g. chrome, safari] Chrome
 - Oxygen Version [e.g. 2.2 Alpha] current and RC1- two different sites with no other plugins that Oxygen and Toolset

**Smartphone (please complete the following information):**
 - Oxygen Version [e.g. 2.2 Alpha]

**Additional context**
*Add any other context about the problem here.*

**Comment by KittenCodes** [comment]
@tomatpercipi Please open a support ticket so that we can take a look at your site: https://oxygenbuilder.com/support. You need to click "Something's broken and I need help".
