### ISSUE TITLE
No longer able to manage colors

### ISSUE THREAD

**Issue by madebyjong** [soflyy/oxygen-bugs-and-features#1463]
Dear Oxygen,

recently I am unable to make colors more transparent or amend/manipulate them whatsoever. Unlike before, the color dots are now square. I have it on all my installs and re-installing O2 does not fix it. Help!!

Any change fixing this.

**Comment by MIJNDESIGN** [comment]
https://www.facebook.com/groups/1626639680763454/permalink/3189487084478698/

Fixed in oxygen 3.5 RC1
