### ISSUE TITLE
I diden't have color choice and shape don't work on r 3.4

### ISSUE THREAD

**Issue by Justacom** [soflyy/oxygen-bugs-and-features#1464]
Hi OxyTeam,

I today i create my 20th or 30th website with OxygenBuilder. 
And when i wand create a shape divider or select color in shortcut
i can't, i have a error but i can't see the message, cause windows i behind the nav bar. 

![2020-08-20 18_05_04-Oxygen Visual Editor - Secondary - SCC Digital Week et 13 pages de plus - Person](https://user-images.githubusercontent.com/50703096/90796554-c48fe280-e30f-11ea-9237-aa50145dacc1.png)
![2020-08-20 18_05_50-Oxygen Visual Editor - Secondary - SCC Digital Week et 13 pages de plus - Person](https://user-images.githubusercontent.com/50703096/90796596-cf4a7780-e30f-11ea-8837-9ddabff3f2f4.png)

I site is hosting on OVH but I've never had this problem
If i change html code with inspector, the error box is empty Oo
![2020-08-20 18_12_05-Oxygen Visual Editor - Secondary - SCC Digital Week et 6 pages de plus - Personn](https://user-images.githubusercontent.com/50703096/90797381-d7ef7d80-e310-11ea-9936-2202ca8a5444.png)

Maybe Iframe is locked by my serv ?
Could you help me pls ? 

Thanks

**Comment by MIJNDESIGN** [comment]
https://www.facebook.com/groups/1626639680763454/permalink/3189487084478698/

**Comment by Justacom** [comment]
> https://www.facebook.com/groups/1626639680763454/permalink/3189487084478698/

Thanks a lot for your response

**Comment by KittenCodes** [comment]
@Justacom If you're still seeing the empty error message after downgrading to WordPress 5.4 or upgrading to Oxygen 3.5 RC 1 then please open a support ticket so that we can take a look at your site: https://oxygenbuilder.com/support.
