### ISSUE TITLE
After upgrading to wordpress 5.5 Color Picker stops working completely

### ISSUE THREAD

**Issue by adilmush** [soflyy/oxygen-bugs-and-features#1465]
Hello Soflyy Team,
since a couple of days back I'm noticing in all our projects the moment we upgrade the WordPress version to 5.5 the color picker of Oxygen builder stops working, not sure about other things at the moment but I'll keep you guys posted.

Hope to get this solved asap.

__
Best Regards
Webzstore Team

**Comment by MIJNDESIGN** [comment]
Fixed in Oxygen 3.5 RC 1
