### ISSUE TITLE
Color selector grayed out

### ISSUE THREAD

**Issue by jacob4** [soflyy/oxygen-bugs-and-features#1466]
**Color selector gone**
<img width="629" alt="Annotation 2020-08-20 170013" src="https://user-images.githubusercontent.com/10079209/90834084-a7a2e180-e306-11ea-969d-2d702fa37e7a.png">

*Brand new oxygen install on a brand new site. First thing I do is build a header and try to set a background. The selector is missing (see screenshot).*

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
*N/A*

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
*If yes, provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.* No, the selector was there on the sandbox.

**To Reproduce**

**Expected behavior**
*A clear and concise description of what you expected to happen.*

**What actually happens**
*A clear and concise description of what happens instead of the expected behavior.*

**Screenshots**
*If applicable, add screenshots to help explain your problem.*

**Desktop (please complete the following information):**
- OS: Windows
 - Browser Chrome
 - Oxygen Version 3.2, 3.4 (tried on both, same result)

**Smartphone (please complete the following information):**
 - Oxygen Version [e.g. 2.2 Alpha]

**Additional context**
*Add any other context about the problem here.*

**Comment by MIJNDESIGN** [comment]
Fixed in Oxygen 3.5 RC 1 

https://www.facebook.com/groups/1626639680763454/permalink/3189487084478698/
