### ISSUE TITLE
Typekit API not working

### ISSUE THREAD

**Issue by dmv70tres** [soflyy/oxygen-bugs-and-features#1478]
**Describe the bug**
*A clear and concise description of what the bug is.*

My Adobe Typekit key is not working. I have an active Adobe subscription. After clicking submit, I do not get additional options. Thank you. 

My email address is ggiraldez@brainstromvisualmarketing.com

**Comment by KittenCodes** [comment]
@dmv70tres Please open a support ticket so that we can take a look at this for you: https://oxygenbuilder.com/support. You need to click "Something's broken and I need help".

**Comment by dmv70tres** [comment]
It was fixed
