### ISSUE TITLE
Problems editing links inner text when using Hash Links 

### ISSUE THREAD

**Issue by ezosher** [soflyy/oxygen-bugs-and-features#1481]
**Describe the bug**
Hey all, I'm reporting a small bug with a feature enhancement. 
I find myself a lot struggling to double click a link wrapper / text link to edit its inner text 
without making the link submit. usually the problem happens when the `href` is set to a `hash links`.
I found a small workaround using `Ctrl + double clicking` and then highlighting the text with `Ctrl + A`, but its annoying.

**Enhancement**
I think if there will be a button in the primary tab or somewhere else that get you into the text editing
mode and auto focus and highlight the text for you without the need to Double click will reduce a lot of Struggle. 
plus I think that it will be a good idea if there was an option to disable Hash links default behavior inside the builder.
**this feature can be added to all text elements as well**

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
Yes

**To Reproduce**
1. Add a link wrapper or text link
2. Set the link to one of the Sections using Hash links ID
3. Double click to edit the text

**Expected behavior**
Double click to edit instead of submitting the link href

**What actually happens**
The Editor is not letting you edit text probably.

**Comment by KittenCodes** [comment]
@ezosher What browser and which version of Oxygen are you using?

**Comment by ezosher** [comment]
@KittenCodes  Sorry if I was lacking info. 
I'm using Chrome with the latest version of Oxygen

**Comment by KittenCodes** [comment]
Thanks @ezosher 

I've not been able to replicate this on a clean Sandbox site running Oxygen v3.5, using Chrome on Windows 10.

If you'd like us to take a look at your site, please open a support ticket: https://oxygenbuilder.com/support.

**Comment by ezosher** [comment]
@KittenCodes Hey sorry for the late reply.
I just created a sandbox using oxygen you can visit the login area here [URL](http://alive-deer.w5.wpsandbox.pro?upass=LlYyq670WMu1)

username: admin
pass: admin

and the page with the replicated issue is this [Issue page](http://alive-deer.w5.wpsandbox.pro/test/)

now try to edit the button text where it says `CLICK HERE FOR ISSUE` . in my end when the Smooth scroll script is active
you will have a hard time to edit the text because its pointing to the hash link plus the cursor is not always available for edit. hope this is a better explanation.

Cheers

**Comment by KittenCodes** [comment]
Thanks @ezosher. I've found that it's only an issue if "Smooth scroll to hashlinks" is turned on in the Global settings. I will report this internally.

**Comment by KittenCodes** [comment]
Fixed in v3.8 Beta 1.
