### ISSUE TITLE
Gutenberg integration not working

### ISSUE THREAD

**Issue by orbruno** [soflyy/oxygen-bugs-and-features#1483]
**Describe the bug**
*Guttenberg integration not working*

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
*Yes*

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
No

**To Reproduce**
Steps to reproduce the behaviour:
1. Went to block library
2. Created a block
3. Went to create a new post
4. No oxygen block is shown

**Expected behaviour**
I expect to see the blocks I created but when creating a post

**What actually happens**
I am trying to use Gutenberg integration, but I am not getting the blocks in the post page. I purchased the Gutenberg module as well

**Screenshots**
*If applicable, add screenshots to help explain your problem.*
![image](https://user-images.githubusercontent.com/47383585/91316000-a23b1080-e7b8-11ea-8a24-277fc8705e51.png)

![image](https://user-images.githubusercontent.com/47383585/91316106-bf6fdf00-e7b8-11ea-80f1-e7392426ea9c.png)

**Desktop (please complete the following information):**
- OS: iOS
 - Browser: Chrome
 - Oxygen Version 3.5

**Smartphone (please complete the following information):**
 - Oxygen Version [e.g. 2.2 Alpha]

**Additional context**
I am using plugin Asset clean up, I thought that maybe it was not allowing Gutenberg modules to load. I disable the plugin but still get the same behaviour.

**Comment by KittenCodes** [comment]
@orbruno Please open a support ticket so that we can take a look at this for you: https://oxygenbuilder.com/support.
