### ISSUE TITLE
oxygen 3.5

### ISSUE THREAD

**Issue by yoogleuk** [soflyy/oxygen-bugs-and-features#1484]
**Describe the bug**
*A clear and concise description of what the bug is.*

my website 
https://hongtherapycentre.co.uk/?tzzp

has completely disappeared since I upload 3.5 update this morning

no plug in page no media everything goes to posts page

I am in panic mode

Kind regards

David Parker

**Comment by Spellhammer** [comment]
Please submit a support ticket at https://oxygenbuilder.com/support and we'll assist.
