### ISSUE TITLE
site disappeared

### ISSUE THREAD

**Issue by yoogleuk** [soflyy/oxygen-bugs-and-features#1485]
**Describe the bug**
*A clear and concise description of what the bug is.*

after uploading Oxygen 3.5
all site contents incl media vanished

site 
https://hongtherapycentre.co.uk

to stop redirect

SITE HAD COMPLETELY VANISHED JUST GOES TO BLOG PAGE - NO MAGES OR PLUGINS
USED CHROME ON APPLE

Kind regards

David

**Comment by yoogleuk** [comment]
email yoogleuk@gmail.com not yoogleuk2

**Comment by Spellhammer** [comment]
You need to immediately change your login credentials.

**This is not a private support channel. Anyone on GitHub can see your login credentials.**

As I requested elsewhere, submit a ticket to our official support via https://oxygenbuilder.com/support for assistance.
