### ISSUE TITLE
Disable elements from the structure panel

### ISSUE THREAD

**Issue by dogoman78** [soflyy/oxygen-bugs-and-features#1486]
**Describe the feature you'd like to see included in Oxygen.**
*A clear, detailed description of the feature you're requesting.*

Be able to disable elements from the structure panel and leave it them there in case of a later use

**What are the use cases for this feature?**
*e.g. Accessibility, e-commerce store that sells bicycles, etc.*

My site is a ecommerce, and some times sections or elements are for specific time, or some times that be excellent for design testing.

Be able to just disable instead of deleting and have to recreating and reorganizanting in case of a later use or temporaly  change

**Examples of this feature or functionality.**

Design testing, temporaly changes, preproduction changes.

*If another product has done it well, provide examples here.*

N/A

**Comment by Spellhammer** [comment]
This is already possible with Conditions.

Just set the element's Condition to something that never evaluates as true. It will be visible in the builder but will not be output on the front end.
