### ISSUE TITLE
add rand function repeater element

### ISSUE THREAD

**Issue by dogoman78** [soflyy/oxygen-bugs-and-features#1487]
**Describe the feature you'd like to see included in Oxygen.**
for repeater element / Query / order
Add rand function

**What are the use cases for this feature?**
For rand function, several times you just want to display elements in a random way to make your page more dynamic

**Examples of this feature or functionality.**

For displaying several products in a limited space with a random function

*If another product has done it well, provide examples here.*

**Comment by KittenCodes** [comment]
Duplicate of #1003
