### ISSUE TITLE
issue with oxygen builder when editing new pages created with wordpress - error 404 

### ISSUE THREAD

**Issue by pablovvmm** [soflyy/oxygen-bugs-and-features#1488]
**Describe the bug**

I have a 404 error when I'm editing a new page in oxygen builder. I create it inside the pages tab in Wordpress, then I edit with Oxygen Builder. At this moment is when the window itself sugest me to go to Settings > permalinks and re save the permalink structure. I select "Plane" for the permalink structure and save it, but after I do this, it just keeps happening.

*A clear and concise description of what the bug is.*

Error 404 from Oxygen Builder when creating a new page.

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
*Yes/No*

Yes 

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
*If yes, provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*

https://patagonianwoods.cl/?page_id=32&ct_builder=true&ct_inner=true

**To Reproduce**
1. Go to 'Pages'
2. Click on 'Add New'
3. Scroll down to 'Edit with Oxygen'
4. See error 404

**Expected behavior**
*A clear and concise description of what you expected to happen.*

I expected to Wordpress to create a new page and edit it with Oxygen builder

**What actually happens**
*A clear and concise description of what happens instead of the expected behavior.*

The window shows a 404 error and sugests me to go to settings > permalinks and change the permalink structure.

**Screenshots**
*If applicable, add screenshots to help explain your problem.*

![Sin título-1](https://user-images.githubusercontent.com/70291338/91351757-33ad8100-e7bf-11ea-82a5-766d474b585f.png)

**Desktop (please complete the following information):**
- OS: Microsoft Windows 10
 - Browser Google Chrome 
 - Oxygen Version 3.5 with Guttenberg and WooCoomerce integration

**Smartphone (please complete the following information):**
Not using inside smartphone

**Additional context**
no more additional context to add.

**Comment by KittenCodes** [comment]
@pablovvmm Please ensure you have published the page before editing with Oxygen. If you have and you're still getting the 404 error, please open a support ticket so that we can take a look at your site: https://oxygenbuilder.com/support. You need to click "Something's broken and I need help".
