### ISSUE TITLE
Hover styles not applied correctly in Custom CSS with multiple selectors

### ISSUE THREAD

**Issue by dposnanski** [soflyy/oxygen-bugs-and-features#1490]
**Describe the bug**
If I have multiple, comma-separated selectors, the hover styles only apply to the last selector. Use case: I'm using this instead of classes because it's the only way I've found so far to change the styling of specific menu items on desktop as well as on mobile.

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
No

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
Yes, see http://cheerful-gecko.w6.wpsandbox.pro/sample-page

**To Reproduce**
1. Add two divs to a page with some height
2. Go to Manage > Selectors and add the IDs of the selectors (comma-separated)
3. In Custom CSS, add background-color
4. Switch state to hover, add another background-color
5. See error

**Expected behavior**
I expect hover to be appended at the end of each of the selectors

**What actually happens**
Hover is only appended at the end of the last selector

**Screenshots**
*If applicable, add screenshots to help explain your problem.*
![image](https://user-images.githubusercontent.com/22684573/91436145-cf92c780-e867-11ea-91a4-41af33a5d7c2.png)

**Desktop (please complete the following information):**
- OS: Windows 10.0.18363
 - Browser Version 84.0.4147.135
 - Oxygen Version 3.5

**Comment by KittenCodes** [comment]
@dposnanski When setting a hover state for multiple comma separated selectors, you need to do this:

```css
.selector1:hover, .selector2:hover {
    
}
```
