### ISSUE TITLE
Renamig structure elements by double clicking.

### ISSUE THREAD

**Issue by bentalgad** [soflyy/oxygen-bugs-and-features#1492]
Right now you have to click on the burger menu and the click "rename".
![CleanShot 2020-08-28 at 07 47 53](https://user-images.githubusercontent.com/23374215/91522415-d589b680-e902-11ea-8d1c-fd53e0930dec.gif)

It would be much easier and intuitive to just double click the name (just like you do
on most applications) to change it.

**Comment by KittenCodes** [comment]
Closing - duplicate: https://github.com/soflyy/oxygen-bugs-and-features/issues/936.
