### ISSUE TITLE
Pro Menu Mobile

### ISSUE THREAD

**Issue by yepyeh** [soflyy/oxygen-bugs-and-features#1493]
**Describe the bug**
Can't click on top level menu items anymore.
Also the sub items display on the page before the page leaves for the next page.

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
Yes

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
Yes, please see here: http://alive-mongoose.w5.wpsandbox.pro/

**To Reproduce**

**Expected behavior**
Should be able to click on top menu item, but also use dropdown to see sub-items.
Sub items should not still be present after menu has gone.

**What actually happens**
Can't click on top level menu items anymore.
Also the sub items display on the page before the page leaves for the next page.
Please see videos below.

**Screenshots**
Screen recordings here: https://www.dropbox.com/sh/t2w7uh7gskxliwq/AACmmy-PiiG8LTBvBHhl79hwa?dl=0
Clear to see on sandbox, but my site, loads quickly and difficult to see sometimes.

**Desktop (please complete the following information):**
- OS: [e.g. iOS] iOS
 - Browser [e.g. chrome, safari] Safari
 - Oxygen Version [e.g. 2.2 Alpha] Oxygen 3.5

**Smartphone (please complete the following information):**
- Device: [e.g. iPhone6] ipad (chrome emulation), iphone 11.
 - OS: [e.g. iOS8.1] ios 13.6.1
 - Browser [e.g. stock browser, safari] Safari
 - Oxygen Version [e.g. 2.2 Alpha] Oxygen 3.5

**Additional context**
Please help!
My client hates me!

**Comment by yepyeh** [comment]
I need a quick fix if anyone has a suggestion. Thanks

**Comment by Spellhammer** [comment]
Uncheck "Entire Parent Toggles Dropdown" in the Mobile Dropdown settings in the Properties Pane: https://d.pr/i/1FmPAy

This will allow the parent link to be followable. It'll then work like it did previously.

**Comment by yepyeh** [comment]
Thanks Elijah,

That did fix the top menu items being clickable.
However in my issue I was experiencing the menu drop down showing after an item is clicked.
Please see screen videos i recoreded.

Thanks

**Comment by Spellhammer** [comment]
> However in my issue I was experiencing the menu drop down showing after an item is clicked.

Can you elaborate? It's unclear to me what exactly is occurring after reviewing your videos.

The expected behavior is that:

1. If a parent link has a href of # OR the "Entire Parent Toggles Dropdown" checkbox is ticked, clicking anywhere on the parent link will toggle the dropdown menu.
2. If the above is not true, then clicking the dropdown icon to the right of the parent link will toggle the dropdown menu.

How does the behavior you experience differ from the expected behavior?

**Comment by yepyeh** [comment]
So it's not really about the top-menu item link now.
It is regarding the menu items in the drop down, after a link is clicked the menu dissapears but you can still see the sub-menu items.
In the videos it is very quick, but if you look close just after the menu hides you can see the sub menu items just hovering at the top of the page. You can aslo impect the html and it will show you the positions of the sub menu items where they appear momentary.
Please see this video again, using my iphone/safari/oxygen sandbox site: http://alive-mongoose.w5.wpsandbox.pro/
Video: https://www.dropbox.com/s/m7xqcs0tv3nxm8o/RPReplay_Final1598612211.mp4?dl=0

Thanks
Steven

**Comment by Filipsons-K** [comment]
Hello, yes the same problem to me for 5 websites mobile menu. After update.

**Comment by yepyeh** [comment]
Any update on this would be very reassuring! @Spellhammer

**Comment by tommielehmann** [comment]
Just stop using the pro-menu.. apparently nobody cares it doesn't work.. I am making my own menu's for mobile using GSAP
