### ISSUE TITLE
Loss of information after saving certain sections

### ISSUE THREAD

**Issue by ellbe69** [soflyy/oxygen-bugs-and-features#1494]
**Describe the bug**
I have made a page using the Conference Design Set. In the template I have added a the footer with map from Atomic and in the inner section of the page I have added a full schedule section from Conference. I can fill them both out while editing, but once I save the changes, the entire full schedule section is empty and the footer looses the adress, phone and e-mail fields. I have re-entered the sections and the information but it just keeps happening over again every time I save the changes. 

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
No

**Expected behavior**
I expected the content to be visible after saving...

**What actually happens**
the entire full schedule section is empty and the footer looses the adress, phone and e-mail fields

**Screenshots**
![screenshot oxygen](https://user-images.githubusercontent.com/58416443/91558900-65495800-e937-11ea-897d-94bb197619c9.JPG)

What I expected:
![screenshot 2](https://user-images.githubusercontent.com/58416443/91558909-6a0e0c00-e937-11ea-9ddb-bbf78daf31c3.JPG)

**Desktop (please complete the following information):**
- OS:Mac Catalina as well as in Windows10
 - Oxygen Version 3.5

**Smartphone (please complete the following information):**
- Device: Motorola Moto G7 plus
 - OS: android
 - Browser Chrome, Samsung
 - Oxygen Version 3.5

**Comment by KittenCodes** [comment]
@ellbe69 Please open a support ticket so that we can take a look at this for you: https://oxygenbuilder.com/support. You need to click "Something's broken and I need help".
