### ISSUE TITLE
Failed To Load Template Error

### ISSUE THREAD

**Issue by jakemull** [soflyy/oxygen-bugs-and-features#1496]
**Describe the bug**
Red alert saying "Failed to load template data" on template screen

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
Yes

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
No

**To Reproduce**
1. Go to 'Oxygen->Templates'
2. Click on 'Edit in Oxygen Builder' on any template

**Expected behavior**
A full template loads in the builder.

**What actually happens**
A blank page and an error banner appears saying, "Failed to load template."

**Screenshots**
<img width="1410" alt="Screen Shot 2020-08-28 at 8 34 25 PM" src="https://user-images.githubusercontent.com/70417452/91624425-38fcfe00-e96e-11ea-9a63-1209fb14c9d9.png">

**Desktop (please complete the following information):**
- OS: MacOS Mojave
 - Browser: Chrome
 - Oxygen Version: 3.5

**Smartphone (please complete the following information):**
- Device: iPhone SE
 - OS: iOS 13
 - Browser: Chrome
 - Oxygen Version: 3.5

**Additional context**
Site: https://BrewPastors.org

**Comment by KittenCodes** [comment]
@jakemull Please open a support ticket so that we can take a look at your site: https://oxygenbuilder.com/support. You need to click "Something's broken and I need help".

**Comment by wpsumo** [comment]
@KittenCodes Same here no console errors and I can not save or do anything in templates right now.

Regenerated css and shortcodes wihtout success.

**Comment by wpsumo** [comment]
@KittenCodes @jakemull FYI disable oxypowerpack it's the issue at the moment, one of the latest patches caused this issue, I'm reporting the bug.
