### ISSUE TITLE
Gutenberg editor back-end not showing the right way

### ISSUE THREAD

**Issue by gladior-maarten** [soflyy/oxygen-bugs-and-features#1500]
Hello, 

When we use the Gutenberg editor on a page, the page is not showing the right way in de back-end. It looks like the CSS is not right. Can you please take a look? In the past we have a lot of problems when we want to use the Gutenberg editor in combination with WPML. 

We have the newest version of Oxygen, Gutenberg editor and WPML.

Basiclly the problem is on every page when we are activating the Gutenberg editor. We also checked it when deactivate the plugins but the problem didn't disapear.

Example page: https://suurmond.triplehosting.nl/polymer-handling/

![screencapture-suurmond-triplehosting-nl-wp-admin-post-php-2020-08-31-11_30_09](https://user-images.githubusercontent.com/70512653/91705531-61a71280-eb7d-11ea-9c86-27af98ba811e.png)

Can I add the login details also in this post?

Thanks for the help!

**Describe the bug**
*A clear and concise description of what the bug is.*

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
*Yes/No*

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
*If yes, provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*

**To Reproduce**

**Expected behavior**
*A clear and concise description of what you expected to happen.*

**What actually happens**
*A clear and concise description of what happens instead of the expected behavior.*

**Screenshots**
*If applicable, add screenshots to help explain your problem.*

**Desktop (please complete the following information):**
 - Oxygen Version [e.g. 2.2 Alpha]

**Smartphone (please complete the following information):**
 - Oxygen Version [e.g. 2.2 Alpha]

**Additional context**
*Add any other context about the problem here.*

**Comment by KittenCodes** [comment]
@gladior-maarten Please open a support ticket so that we can take a look at your site: https://oxygenbuilder.com/support. You need to click "Something's broken and I need help".
