### ISSUE TITLE
You must add Custom responsive device include 

### ISSUE THREAD

**Issue by rayhan62** [soflyy/oxygen-bugs-and-features#1501]
**Describe the bug**
*A clear and concise description of what the bug is.*

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
*Yes/No*

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
*If yes, provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*

**To Reproduce**

**Expected behavior**
*A clear and concise description of what you expected to happen.*

**What actually happens**
*A clear and concise description of what happens instead of the expected behavior.*

**Screenshots**
*If applicable, add screenshots to help explain your problem.*

**Desktop (please complete the following information):**
 - Oxygen Version [e.g. 2.2 Alpha]

**Smartphone (please complete the following information):**
 - Oxygen Version [e.g. 2.2 Alpha]

**Additional context**
*Add any other context about the problem here.*

**Comment by rayhan62** [comment]
Webflow they have custom responsive devices, please add custom device,and add css grid

**Comment by rayhan62** [comment]
Make woocommerce single Product add, why you know because people can add anywhere single product,when i need to add single product  add to homepage, i can't understant, how can i add

**Comment by Spellhammer** [comment]
1. You didn't follow the template
2. This isn't a bug report
3. This is two feature requests and a support request

>> Make woocommerce single Product add, why you know because people can add anywhere single product,when i need to add single product add to homepage, i can't understant, how can i add

Start here: https://oxygenbuilder.com/documentation/woocommerce-integration/overview/ - watch the videos and progress through the WooCommerce documentation. If you still don't know how to do what you want to do after that, contact us for help via https://oxygenbuilder.com/support.
