### ISSUE TITLE
WordPress 5.5 may have broke Gutenberg integration

### ISSUE THREAD

**Issue by guyinpv** [soflyy/oxygen-bugs-and-features#1504]
**Describe the bug**
After doing all my updates recently, I noticed the Gutenberg plugin doesn't work any more. When I click on any text blocks, TinyMCE opens but has no content in it.

I've checked on two sites so far, and created a new blank page with a single text box and still didn't work.

Have Oxygen and the Oxygen Gutenberg Integration plugins installed and active.
WordPress 5.5 or 5.5.1.
1. Create a new page. Turn on the Gutenberg integration checkbox.
2. Add a section and some text using the Oxygen interface and save it.
3. Go in WordPress backend Gutenberg editor and see if you can edit the text.

**Expected behavior**
TinyMCE would have the content in the the popup box.

**What actually happens**
TinyMCE pops up and has no content in it.

**Desktop (please complete the following information):**
- OS: Windows 10 latest
- Chrome or Firefox
- Oxygen 3.5
- Oxygen Gutenberg Integration 1.2

**Comment by KittenCodes** [comment]
@guyinpv Please update Oxygen's Gutenberg integration to the latest version.
