### ISSUE TITLE
Oxygen Builder / Yoast / WooCommerce issue

### ISSUE THREAD

**Issue by TheWebSmiths** [soflyy/oxygen-bugs-and-features#1506]
**Describe the bug**
*A clear and concise description of what the bug is.*

I have a problem with the Yoast 14.9 update when editing products in WooCommerce with Oxygen Builder.

Clicking the 'text' tab in the description or short description editor does nothing as does clicking the 'link options' cog in the add link popup to set to new tab, etc.

If I disable Yoast this functionality comes back.

My console shows the following error:
yoast-seo-compatibility.js?ver=f599d686067a9bb97202e0b58d8978c7:4 Uncaught TypeError: Cannot read property 'registerPlugin' of undefined
    at new YoastOxygen (yoast-seo-compatibility.js?ver=f599d686067a9bb97202e0b58d8978c7:4)
    at HTMLDocument.<anonymous> (yoast-seo-compatibility.js?ver=f599d686067a9bb97202e0b58d8978c7:20)
    at i (jquery.js?ver=1.12.4-wp:2)
    at Object.fireWith [as resolveWith] (jquery.js?ver=1.12.4-wp:2)
    at Function.ready (jquery.js?ver=1.12.4-wp:2)
    at HTMLDocument.J (jquery.js?ver=1.12.4-wp:2)

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
*Yes*

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
*Yes*
*If yes, provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*

**To Reproduce**
1. Go to 'edit product'
2. Click on 'Text tab for description or short description / Highlight some tect to make a link then click the 'link options' cog to create/amend link'
4. See error 'Nothing happens'

**Expected behavior**
*A clear and concise description of what you expected to happen.*
The relevant code/html should be in view / the link options box should open
**What actually happens**
*A clear and concise description of what happens instead of the expected behavior.*
Nothing / nothing
**Screenshots**
*If applicable, add screenshots to help explain your problem.*

**Desktop (please complete the following information):**
- OS: [e.g. iOS] WINDOWS
 - Browser [e.g. chrome, safari] CHROME & FIREFOX
 - Oxygen Version [e.g. 2.2 Alpha] 3.5

**Smartphone (please complete the following information):**
 - Oxygen Version [e.g. 2.2 Alpha]

**Additional context**
*Add any other context about the problem here.*

**Comment by TheWebSmiths** [comment]
I am able to reproduce both issues in the Oxygen Sandbox by installing Yoast & WooCommerce then creating, saving and editing a product.

**Comment by KittenCodes** [comment]
Replicated and reported internally.

**Comment by sebastianstolarski93** [comment]
Good morning, 
Do you have any progress with this bug? I have the same bug but without woocommerce. Normal wordpress editor - tinyMCE (not Guttenberg) - not working because in /wp-content/plugins/oxygen/component-framework/admin/js/yoast-seo-compatibility.js file your scripts can't register a plugin for YoastSEO.

**Comment by aaronriedle** [comment]
I have the Same Problem with Oxygen 3.5 and WooCommerce 4.5.2 and Yoast 14.9. 
Cant add or Edit Add-Ons Products.

**Comment by KittenCodes** [comment]
@aaronriedle Please downgrade Yoast to 14.8.

**Comment by robbygnwn** [comment]
Hello,

I have a similar issue with Oxygen 3.5 and Yoast (14.9 onward). I can't switch between Visual and Text tab on the Classic Editor. Also, the toolbar is blank (the buttons -bold, italic, etc- are not showing up).

**Comment by KittenCodes** [comment]
@robbygnwn This is fixed in Oxygen 3.6, which is currently in RC: https://oxygenbuilder.com/2020/10/14/oxygen-3-6-release-candidate-1-now-available/.

If you don't want to run an RC version on your site, you can downgrade Yoast to v14.8.

**Comment by robbygnwn** [comment]
@KittenCodes Thanks for the update. I downgraded Yoast right after I noticed the issue. I think I'll just wait until Oxygen 3.6 is officially released.

**Comment by SubstringTV** [comment]
We hit this issue with some sites recently and managed to implement a temporary fix should people want to keep the latest version of Yoast and be comfortable with editing the Oxygen plugin.

Note that this change would be only to fix this issue until Oxygen 3.6 is released and would be overwritten when updating to Oxygen 3.6.

If you edit the file found at `/wp-content/plugins/oxygen/component-framework/admin/js/yoast-seo-compatibility.js` and change the line 21 from `$(document).ready(function(){` to `$(window).load(function() {` it should resolve the issue while you wait for Oxygen 3.6.

I hope that helps.

**Comment by robbygnwn** [comment]
@SubstringTV Thanks for the information. Unfortunately it's not working on my end. I'm using Yoast 15.2.

**Comment by dhakshinait** [comment]
@robbygnwn , I had the same issue but oxygen 3.6 version update solved the issue.

**Comment by TheWebSmiths** [comment]
3.6 has sorted this issue 👍
