### ISSUE TITLE
Accessibility: modal window doesn't take the focus

### ISSUE THREAD

**Issue by Shemzone** [soflyy/oxygen-bugs-and-features#151]
Oxygen 2.3.a1 - Modal window focusable elements don't take the focus
You are still able to navigate underneath the modal window which you should not until the modal window is closed.

**Have you tried all the steps at 
*No*

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
No, 2.3.a1 is not installed on the sandbox

**To Reproduce**
1. Create a modal window over a section containing elements able to take the focus (button, link).
2. In this modal window, create elements able to receive focus as well (link, close button, etc.)
3. Run a trigger to open the modal window and try to navigate with the keyboard (tab key) in the focusable elements of the modal window. You can't access them until you reach the end of the focusable elements of the modal window's parent.

**Expected behavior**
As soon as the modal window is open, its focusable elements must be reachable immediately. The focusable elements of the parent are deactivated until the modal window is closed

**What actually happens**
Results is that you are still able to navigate underneath the modal window which you should not until the modal window is closed.

**Screenshots**
![parent-element-still-focused](https://user-images.githubusercontent.com/11276853/54495590-3ecf6280-48e5-11e9-8209-aceb6a82170d.JPG)
![reached-element](https://user-images.githubusercontent.com/11276853/54495604-50186f00-48e5-11e9-9e49-aa1ccd8e7025.JPG)

**Desktop (please complete the following information):**
- OS: Windows 10 64bits
 - Browser : Brave (Chromium based)
 - Oxygen Version : 2.3 Alpha 1

**Smartphone (please complete the following information):**
NA

**Additional context**
Resources:
https://www.youtube.com/watch?v=JS68faEUduk
https://www.w3.org/TR/wai-aria-practices-1.1/#dialog_modal

**Comment by wplit** [comment]
100%!

A common need for this when we add a search form in a modal. When the user clicks, say, a search icon and the full screen modal appears with a search form. The user expects to be able to just start typing, not have to actually click in the input field to focus it.

**Comment by KittenCodes** [comment]
Fixed in v3.8 Beta 1.
