### ISSUE TITLE
Oxygen 3.5 Pro menu on mobile show dropdown desktop menu in backgraund. 

### ISSUE THREAD

**Issue by Filipsons-K** [soflyy/oxygen-bugs-and-features#1511]
**Describe the bug**
*A clear and concise description of what the bug is.*
Oxygen update 3.5 on pro menu, when used on mobile desktop menu dropdown, show up in the background when load pages like products, or other pages in the dropdown menu. 
On Oxygen 3.4 works all fine. 

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
*Yes/No*
Yes

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
*If yes, provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*

[https://oilproject.lv/](https://oilproject.lv/)
[https://oilproject.lv/products/](https://oilproject.lv/products/)
[https://oilproject.lv/product-category/cars_motor_oil/](https://oilproject.lv/product-category/cars_motor_oil/)
[https://oilproject.lv/product-category/motorcycle_oil/](https://oilproject.lv/product-category/motorcycle_oil/)
[https://oilproject.lv/product-category/gear-lube/](https://oilproject.lv/product-category/gear-lube/)
[https://oilproject.lv/product-category/lubricants/](https://oilproject.lv/product-category/lubricants/)

**To Reproduce**

**Expected behavior**
*A clear and concise description of what you expected to happen.*
The desktop menu needs to be hidden on mobile. 

**What actually happens**
*A clear and concise description of what happens instead of the expected behavior.*
The desktop dropdown menu showing up when it's loads the next chosen page. 

**Screenshots**
*If applicable, add screenshots to help explain your problem.*
![AMSOIL ONLINE STORE in RIGA, LATVIA order online 001](https://user-images.githubusercontent.com/66617494/92333378-ae16b480-f08d-11ea-8ef1-526397018772.png)
![Amsoil Break In Oil, The First in Synthetics - Oilproject lv 1594](https://user-images.githubusercontent.com/66617494/92333290-faadc000-f08c-11ea-821b-7e7ee4a1f4fd.png)
![AMSOIL ONLINE STORE in RIGA, LATVIA order online](https://user-images.githubusercontent.com/66617494/92333295-fe414700-f08c-11ea-9cbb-a0ebb6be6223.png)

**Desktop (please complete the following information):**
 - Oxygen Version [e.g. 2.2 Alpha] 3.5

**Smartphone (please complete the following information):**
- Device: [e.g. iPhone6]Yes
 - OS: [e.g. iOS8.1]Yes
 - Browser [e.g. stock browser, safari]Yes
 - Oxygen Version [e.g. 2.2 Alpha] 3.5

**Additional context**
*Add any other context about the problem here.*

**Comment by csaib** [comment]
To Oxy team - when you plan to solve this issue?

**Comment by Filipsons-K** [comment]
Yes, the same question.

**Comment by KittenCodes** [comment]
This is fixed in v3.6 Beta: https://oxygenbuilder.com/2020/09/28/oxygen-3-6-beta-1-now-available/.
