### ISSUE TITLE
After upgrading to V3.5, I cannot edit any of my pages anymore        

### ISSUE THREAD

**Issue by azrinsani** [soflyy/oxygen-bugs-and-features#1512]
**Describe the bug**
After upgrading to V3.5, I cannot edit any of my pages anymore. I can open them on my website
The website is https://vlix.webredirect.org. It opens up fine. However, the oxygen editor cannot edit the page

In Chrome console, a bunch of javascript error comes out. I have attached the log:
[Chrome Console Log vlix.webredirect.org-1599434905543.log](https://github.com/soflyy/oxygen-bugs-and-features/files/5180454/Chrome.Console.Log.vlix.webredirect.org-1599434905543.log)

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
Yes, i have followed the guide

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
You can access my website, I can give you temporary access,

**To Reproduce**
1. I upgraded the oxygen version
2 I was able to open a page first time
3 I save the page
4 I refresh the page
5 All these errors come out.

**Screenshots**
<img width="1920" alt="chrome_Q6XEF8WpRw" src="https://user-images.githubusercontent.com/23360540/92337424-32902400-f0dc-11ea-9d68-415a607803d4.png">
<img width="1920" alt="chrome_Zgv91NPp4I" src="https://user-images.githubusercontent.com/23360540/92337437-4dfb2f00-f0dc-11ea-9783-2099305bc789.png">

**Desktop (please complete the following information):**
- OS: Windows 10
 - Browser: Chrome
 - Oxygen Version: 3.5

**Comment by Spellhammer** [comment]
Please submit a ticket to support@oxygenbuilder.com with admin login credentials so that we can investigate.

**Comment by azrinsani** [comment]
> Please submit a ticket to [support@oxygenbuilder.com](mailto:support@oxygenbuilder.com) with admin login credentials so that we can investigate.

I've just submitted a ticket, have given WPAdmin and MySql Database Access
