### ISSUE TITLE
Custom Font Support For Oxygen Builder

### ISSUE THREAD

**Issue by adilmush** [soflyy/oxygen-bugs-and-features#1513]
Hello Elija,
I would like to request this feature and I know it is recommended to use Elegant Custom Fonts plugin by your team if we want to use any local fonts and I'm already using this plugin in all of my projects so far, but this plugin has not been updated for the last 3 years and as you know with the recent hack on most of the WordPress website because of WP File manager plugin me being a victim of this I'm feeling very nervous in using this plugin for the custom font.

So it's a request please do something about this matter, either launch a plugin or provide a system on the Oxygen settings itself which would be the best option I believe.

__
Thanks & Regards
Adil

**Comment by acicovic** [comment]
Related: https://github.com/soflyy/oxygen-bugs-and-features/issues/519

**Comment by mbs1337** [comment]
+1

There is a "good" way for doing this here: https://www.altmann.de/en/blog-en/code-snippet-integrate-custom-fonts-into-oxygen-en/

But a feature in Oxygen would be preferred.

**Comment by Kpudlo** [comment]
Closed as a duplicate in favor of https://github.com/soflyy/oxygen-bugs-and-features/issues/2637 as that has more upvotes/comments.
