### ISSUE TITLE
Responsive menu does not scroll

### ISSUE THREAD

**Issue by dkwoodhouse** [soflyy/oxygen-bugs-and-features#1514]
**Description
View the responsive menu on my site at https://woodhousemasks.com to see that the modal menu does not scroll.  

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
Yes

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
No

*If yes, provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*

**To Reproduce**
1. Go to https://woodhousemasks.com
2. Resize window small to get the hamburger menu
3. Select the hamburger menu and resize the window shorter than the menu height
4. Try to scroll to the bottom of the menu. The page does not scroll.

**Expected behavior**
Need to be able to scroll through the responsive menu on phone. Currently, on my Pixel 3XL, the Cart is not available.

**What actually happens**
Scrolling is disabled for the responsive / modal menu

**Screenshots**
*If applicable, add screenshots to help explain your problem.*

**Desktop (please complete the following information):**
- OS: any
 - Browser - any
 - Oxygen Version 3.5

**Smartphone (please complete the following information):**
- Device: Pixel 3XL, any
 - OS: any
 - Browser: any
 - Oxygen Version 3.5

**Comment by KittenCodes** [comment]
@dkwoodhouse Please open a support ticket so that we can take a look at your site: https://oxygenbuilder.com/support. You need to click "Something's broken and I need help".
