### ISSUE TITLE
Heights not Constrained - Menu and Headings

### ISSUE THREAD

**Issue by dahnitru1** [soflyy/oxygen-bugs-and-features#1521]
**Describe the bug**
Element heights escaping their divs.

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
Yes

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
No. Here is a video where I replicate the issue:
https://www.awesomescreenshot.com/video/900223?key=0590632ffa0ed3268bcd15059ed53944&fbclid=IwAR0H0x81rPXAVTNYJFHfc2Qg_bV6TZIn8lVeDOA-b6dpStXQ6x9p4JWzQ-4

**To Reproduce**

**Expected behavior**
I've built lots of sites with oxygen but not the newest versions of oxygen and wordpress together. When I add a menu to the header builder, the height is constrained to the header row. When I add a heading, that heading's height is constrained to its line-height.

**What actually happens**
So far my menu and heading heights are not contained within their respective divs. They seem to be very tall and when I try to change the heights manually they are still straying outside of their parent divs.

**Screenshots**
menu: http://zsadvantage.com/wp-content/uploads/2020/09/Screen-Shot-2020-09-08-at-10.22.03-PM.png

h3 (not supposed to have all this white space around but they're tall, and see how the menu from the sticky header is down at the bottom of the page because it's so tall): http://zsadvantage.com/wp-content/uploads/2020/09/Screen-Shot-2020-09-08-at-10.22.19-PM.png

**Desktop (please complete the following information):**
- OS: mohave
 - Browser: chrome
 - Oxygen Version - 3.5

**Additional context**
Here is a video where I replicate the issue: 
https://www.awesomescreenshot.com/video/900223?key=0590632ffa0ed3268bcd15059ed53944&fbclid=IwAR0H0x81rPXAVTNYJFHfc2Qg_bV6TZIn8lVeDOA-b6dpStXQ6x9p4JWzQ-4

*Add any other context about the problem here.*

**Comment by KittenCodes** [comment]
@dahnitru1 I suspect there is some CSS on your site that is causing this. Please open a support ticket so that we can take a look at your site: https://oxygenbuilder.com/support.
