### ISSUE TITLE
Custom image background bug

### ISSUE THREAD

**Issue by alexgr1985** [soflyy/oxygen-bugs-and-features#1522]
hello, I'have create a woocommerce products list template for categories. 
With ACF I have add a custom image field. When I create my template, I choose this custom image to be display as a banner in the top of the page. But nothing is display, It doesn't work.
Do you have any idea why?

**Comment by KittenCodes** [comment]
@alexgr1985 Please ensure your ACF image field is set to return the image URL and not the array. If that doesn't help, please open a support ticket so that we can take a look at your site: https://oxygenbuilder.com/support. You need to click "Something's broken and I need help".
