### ISSUE TITLE
Giant Error Logs with strpos warning

### ISSUE THREAD

**Issue by overyde** [soflyy/oxygen-bugs-and-features#1525]
**Describe the bug**
I'm getting HUGE error logs with this single line of code: strpos() expects parameter 1 to be string, array given in /home/"mysitename"/public_html/wp-content/plugins/oxygen/component-framework/components/component.class.php

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
I couldn't find this issue

**Expected behavior**
No errors on the log file

**What actually happens**
ended up with a 5gb error.log file on myserver over a few months

 - Oxygen Version [e.g. 3.2 and now 3.5]

**Comment by andergmartins** [comment]
Same as #1448.

**Comment by KittenCodes** [comment]
Fixed in v3.6 Beta.
