### ISSUE TITLE
hackers infiltrated site. Concern it was through Oxygen

### ISSUE THREAD

**Issue by visualtribe** [soflyy/oxygen-bugs-and-features#1528]
**Describe the bug**
*A clear and concise description of what the bug is.*
Oxygen sites are being hacked. Initially, hackers put malware on index.php page, but their latest infiltration was on a wp_post page and wp_options through the database. 

I am posting this here to see if you guys have a hole in your code. They are walking through Wordfence to get there.

**Comment by jasperf** [comment]
@visualtribe Did these hacks happen on separate servers and hosters or just one server? How did the logs show Oxygen was used as entry point? Did Wordfence mention anything or nothing on this? What about access logs at the time of the hack?

**Comment by Spellhammer** [comment]
This isn't a bug report.

If you have a security concern, please contact us via support@oxygenbuilder.com with all pertinent details and we'll advise.
