### ISSUE TITLE
Inserting a Gallery Video Playlist displays empty element, renders as invalid html

### ISSUE THREAD

**Issue by JayFett** [soflyy/oxygen-bugs-and-features#1529]
This issue can be replicated in the Oxygen sandbox by inserting a Gallery video playlist from the media library.

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
Yes

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
https://oxygen-q69kcvlk2b8al.oxygen-demo.qsandbox.me/?page_id=7

**To Reproduce**
Upload a media file to the Wordpress media library.  Insert an Oxygen 'Gallery', select video playlist, select the video, insert the playlist.  Save page, view on front-end.  Should show as empty (but clicking it plays the video).  The image src is incorrect, see the following output from Devtools:

[
![front-end inspect](https://user-images.githubusercontent.com/4452883/92956620-cccdd000-f42c-11ea-982a-18d624faff25.png)
](url)

**Expected behavior**
Videos should show a preview / other controls

**What actually happens**
A corrupt element is created

**Screenshots**
Screenshot shows the html from Devtools inspection of front-end preview

**Desktop (please complete the following information):**
Windows 10, Chrome browser, Oxygen v3.5

**Comment by KittenCodes** [comment]
@JayFett Oxygen's Gallery element doesn't work with video. If you would like to see this option in a future release of Oxygen, please open a feature request: https://github.com/soflyy/oxygen-bugs-and-features/issues/new/choose.

**Comment by JayFett** [comment]
> @JayFett Oxygen's Gallery element doesn't work with video. If you would like to see this option in a future release of Oxygen, please open a feature request: https://github.com/soflyy/oxygen-bugs-and-features/issues/new/choose.

But the component in question is called 'Video Gallery", I don't understand how it doesn't work with video.  This isn't a request for a new feature but either a bug report or request for clarification.

**Comment by JayFett** [comment]
> @JayFett Oxygen's Gallery element doesn't work with video. If you would like to see this option in a future release of Oxygen, please open a feature request: https://github.com/soflyy/oxygen-bugs-and-features/issues/new/choose.

But the component in question is called 'Video Gallery", I don't understand how it doesn't work with video. This isn't a request for a new feature but either a bug report or request for clarification.
