### ISSUE TITLE
Bug on repeater and space-between

### ISSUE THREAD

**Issue by erikworkshop** [soflyy/oxygen-bugs-and-features#1531]
Hi,
When you make a repeater and choose a space between horizontal alignment, there is a gap at the end and the repeater don't use the 100% of the length of the repeater.
For the moment a display:none on the last div made by oxygen, resolve the problem
I made an example here
https://oxygen-qkyfpnc8f5c7.oxygen-demo.qsandbox.me/bug-on-repeater/

**Comment by KittenCodes** [comment]
@erikworkshop Please select "Allow Multiline" on the layout tab of the Repeater and then add the following CSS to a Code Block or stylesheet:

```css
.oxy-repeater-pages-wrap {
  width: 100%;
}
```

I've done this on the Sandbox site.
