### ISSUE TITLE
Modal size does not scale and modal content does not scroll with large amounts of data

### ISSUE THREAD

**Issue by cordschneider** [soflyy/oxygen-bugs-and-features#1532]
**Describe the bug**
As of Oxygen 2.3 and to the present version, when a large amount of content is placed in a modal that does not fit the vertical space of the viewport, it will be cut off at top and bottom with no way to scroll down especially on mobile devices. When attempting to scroll, the underlying web page scrolls rather than the modal content.

This issue is described here:
https://wpdevdesign.com/fixing-the-modal-issue-in-oxygen-2-3/

And an improved workaround is described here:
https://oxywp.com/en/disabling-page-scrolling-when-opening-the-modal-in-oxygen/

This fix should be incorporated into future releases of Oxygen's modal element and users should not have to rely on implementing a workaround with every modal used.

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
Yes

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
This issue is easily replicable in any Oxygen deployment. Create a modal and place a large amount of content in the modal. If the content overflows the viewport, the top and bottom of the modal are cut off and there is no way to scroll the content.

**To Reproduce**
See above.

**Expected behavior**
There are two sets of expected behaviour that need to be addressed:
1. When a modal is active, scrolling should not scroll the underlying web page.
2. When a modal is active and the modal content is larger than the viewport, the contents of the modal should be scrollable.

**What actually happens**
See above.

**Screenshots**
N/A

**Desktop (please complete the following information):**
- OS: macOS Catalina (10.15.6)
 - Browser: Firefox Developer Edition 81.0b9 (64-bit), Brave 1.13.82 Chromium: 85.0.4183.83 (Official Build) (64-bit), Google Chrome 85.0.4183.102 (Official Build) (64-bit), Safari 13.1.2
 - Oxygen Version: 3.5

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by KittenCodes** [comment]
Duplicate https://github.com/soflyy/oxygen-bugs-and-features/issues/279

**Comment by cordschneider** [comment]
Thanks for the update @KittenCodes - I thought that there might be a reported bug but my limited search didn't find anything.

Bearing in mind that [#279](https://github.com/soflyy/oxygen-bugs-and-features/issues/279) has been open for more than 16 months and has several potential fixes - including a very comprehensive fix supplied on this ticket that works well on mobiles too - when are we looking at getting this issue fixed?

**Comment by jamescrabb** [comment]
> Thanks for the update @KittenCodes - I thought that there might be a reported bug but my limited search didn't find anything.
> 
> Bearing in mind that [#279](https://github.com/soflyy/oxygen-bugs-and-features/issues/279) has been open for more than 16 months and has several potential fixes - including a very comprehensive fix supplied on this ticket that works well on mobiles too - when are we looking at getting this issue fixed?

**Agree Needs fixing or some transparency at least in what they aim to do about all the confirmed bugs**
