### ISSUE TITLE
Oxygen template don't render the same throughout the website

### ISSUE THREAD

**Issue by etiennemansard** [soflyy/oxygen-bugs-and-features#1533]
**Describe the bug**
I have created a template with the header and footer that is applied throughout the website. The font weight don't render the same as it does in the Oxygen builder. Only one page (Contact us) render correctly but all the other page don't. 

*A clear and concise description of what the bug is.*
I have created a template with the header and footer that is applied throughout the website. The font weight don't render the same as it does in the Oxygen builder. Only one page (Contact us) render correctly but all the other page don't. 

In Oxygen builder, in the "Main header and footer" template, I have created a header and footer. I have changed the weight of the menu and the the text link in the footer (so it appears bold). When I view my website in the browser, only the "Contact us" page render the header and footer font weight the way I created it in Oxygen. The rest of the website don't appears correctly.

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
Yes

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
No

**To Reproduce**
1. Go to 'https://www.clearlightclinic.co.uk/'
2. Click on 'Contact us' in the header menu
3. See the font-weight looks different in the header menu and the footer

**Expected behaviour**
Font weight should look like the same throughout the website as it is in 'https://www.clearlightclinic.co.uk/contact-us/'

**What actually happens**
The header and footer template renders properly in "Contact us" page but not in the rest of the website.

**Screenshots**
https://www.dropbox.com/sh/b7tp4zap2taoash/AAAY8HoLeVqQrbPeHV45ikfsa?dl=0

**Desktop (please complete the following information):**
- OS: iOS 13.7 and Mac OS Catalina 10.15.6
 - Browser Safari and Chrome
 - Oxygen Version 3.5

**Smartphone (please complete the following information):**
- Device: iPhone X
 - OS: Mac Book Pro
 - Browser Chrome and Safari
 - Oxygen Version 3.5

**Additional context**
*Add any other context about the problem here.*

**Comment by KittenCodes** [comment]
@etiennemansard Please open a support ticket so that we can take a look at this for you: https://oxygenbuilder.com/support.

**Comment by etiennemansard** [comment]
Hello,

But I did open a ticket already, no?

Etienne
