### ISSUE TITLE
Responsive CSS doesn't work / angular.js error

### ISSUE THREAD

**Issue by stitchinger** [soflyy/oxygen-bugs-and-features#154]
**Describe the bug**
There seem to be some issues, if you edit a class by selecting it in selector-panel.

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
**Yes**. http://persistent-finch.w6.wpsandbox.pro?upass=hQVN944Bn8pf

**To Reproduce**
1. Create new Sandbox Atom.
2. Edit "Home"-page with oxygen builder.
3. Click on any button.
4. Add a class to button
5. Go to selector-panel and select created class.
6. Change font-size for desktop-view
7. Change font-size for mobile-view
8. Font-size field is greyed out now and some error pops up in console. 

**Expected behavior**
I should be able to edit classes and there responsive queries where ever I want. 

**What actually happens**
Oxygenbuilder doesn't create multiple queries for selectors.

**Desktop (please complete the following information):**
- OS: OSX 10.14
 - Chrome
 - Oxygen Version [2.2 and 2.21]

**Comment by KittenCodes** [comment]
Fixed in v3.5.
