### ISSUE TITLE
Category Blog Roll Templating

### ISSUE THREAD

**Issue by BPCreative** [soflyy/oxygen-bugs-and-features#1544]
**Describe the feature you'd like to see included in Oxygen.**
When I go the the sitemap (https://www.yankeesupply.com/sitemap_index.xml) and click the category sitemap (https://www.yankeesupply.com/category-sitemap.xml), then click on a category, I get a 404.  

I realize I can setup a page for each category, but that is a lot of pages.  I would like to see an option to set a template and have it get the posts permalink (so, in this case not blog, but /articles/) and then the have it apply like "/articles/category/*" so it catches all blog categories.

**What are the use cases for this feature?**
SEO & Fixing Google Console Errors

**Examples of this feature or functionality.**
No examples for this.

**Comment by KittenCodes** [comment]
@BPCreative Please open a support ticket so that we can take a look at this for you. It seems that your category archives aren't working correctly for some reason.

You can open a ticket here: https://oxygenbuilder.com/support.
