### ISSUE TITLE
Slider breaking when multiple divs placed within a slide

### ISSUE THREAD

**Issue by webprogrammingsolutions** [soflyy/oxygen-bugs-and-features#1547]
**Describe the bug**
When adding multiple div layers in a slider, the functionality breaks on the front end of the website.

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
Yes

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
Yes, here, on the sample page: https://oxygen-qsg2nasrskabl.oxygen-demo.qsandbox.me/sample-page/

**To Reproduce**
1. Add a new slide.
2. Add multiple divs and text elements/imaged to slide
3. Save

**Screenshots**
https://imgur.com/a/P72X5gi

**Expected behavior**
A beautiful slide becomes visible on the front end

**What actually happens**
The slider shortcode breaks and visually breaks the slider

**Desktop (please complete the following information):**
macOS, Chrome latest version, Oxygen sandbox

**Additional context**
It seems possible to fix this by re-loading the Oxygen editor, and re-saving the page. The shortcode is no longer broken on the front end. But if you add a new (complex) slide, and save all in one page editing session, the shortcode will be broken.

For example, if you duplicate a slide and save - broken on front end.

If you duplicate a slide and save, reload editor, save - not broken on front end.

https://imgur.com/a/P72X5gi

**Comment by KittenCodes** [comment]
@webprogrammingsolutions Do you happen to have a screenshot showing element layout in the structure panel that caused the behaviour?

**Comment by webprogrammingsolutions** [comment]
> @webprogrammingsolutions Do you happen to have a screenshot showing element layout in the structure panel that caused the behaviour?

yes, it was included in my initial report:
https://imgur.com/a/P72X5gi

**Comment by KittenCodes** [comment]
@webprogrammingsolutions I've replicated that structure on a Sandbox site, but I'm not able to cause the behaviour you're seeing. You can find the Sandbox site here: https://oxygen-qrdzamfq8hdbl.oxygen-demo.qsandbox.me/?qcmd=auto_login&user=demo&pass=demo&next=admin

Page: https://oxygen-qrdzamfq8hdbl.oxygen-demo.qsandbox.me/wp-admin/post.php?post=7&action=edit

Please can you let me know if it's working as expected for you?
