### ISSUE TITLE
Product Template No items to preview

### ISSUE THREAD

**Issue by jasperf** [soflyy/oxygen-bugs-and-features#1549]
**Describe the bug**
We set up a product template for specific categories and sub categories. So we selected single products and only have it apply to taxonomies: Gr8 parts, Fr8 parts, secret service parts and so on. These are all parts and accessories category products. On the frontend the products do load but only with image, title and description though we added more product builder items. On the backend we are told no items are there to preview so we cannot even choose a product to look at.

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
*Yes/No*

We Do use a PHP version 7.x and we do have debug running though we turned off notices as Oxygen Builder has some notices that pollute our logs and make them grow to tens of MBs in no time.

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
*If yes, provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*

**Expected behavior**
*A clear and concise description of what you expected to happen.*

We expect to be able to choose a product to preview. There are none to choose from now. And so there is no preview to work with.

**What actually happens**
*A clear and concise description of what happens instead of the expected behavior.*

Preview dropdown is empty and nothing is loaded. We can only work with the structure pane.
**Screenshots**
*If applicable, add screenshots to help explain your problem.*
<img width="1432" alt="chosen post type and applied to" src="https://user-images.githubusercontent.com/344138/93406948-2fa2e980-f8bb-11ea-9137-32fa6a7ddfb3.png">
<img width="1640" alt="frontend look with things like tabs missing" src="https://user-images.githubusercontent.com/344138/93406957-3893bb00-f8bb-11ea-933c-158025c8b95f.png">
<img width="1477" alt="nothing to preview" src="https://user-images.githubusercontent.com/344138/93406968-3b8eab80-f8bb-11ea-9ddc-ddbf07363c80.png">

**Desktop (please complete the following information):**
- OS: macOS Catalina 10.15.5
 - Browser Firefox Developer 79.0b6 (64-bit)
 - Oxygen Version 3.5

**Comment by jasperf** [comment]
It seems to be that when you select multiple taxonomies to apply the product too conflicts occur. And that is why the template did not allow the loading of previews. The frontend however still loaded products with this layout for all the categories and sub categories it was applied too. Why the products tab did not load items I am not sure of yet. Perhaps because there was no data for it. It was in the same section as the product builder after all. 

Annoying part is not that we probably need to added another category for the accessories as I can probably not apply this template to it to as that would cause conflicts as well. Now just applying it to parent category parts loads all products under it but not accessories. Surely there must be a better way for this?

**Comment by KittenCodes** [comment]
@jasperf If you'd like us to take a look at this for you, please open a support ticket: https://oxygenbuilder.com/support.

**Comment by jasperf** [comment]
Support ticket just created
