### ISSUE TITLE
options (auto, cover, contain, manual) in Video Background

### ISSUE THREAD

**Issue by zimmiel** [soflyy/oxygen-bugs-and-features#1552]
Hello
In section for Video Background create the same options Background Size as for Background Image (auto, cover, contain, manual)
-
So that you can control small pieces of sections with video background
For example: 
In section I add another section (because options video background exists only in section) 250px width and I want the whole video to fit in the given width.
![oxy-videobg](https://user-images.githubusercontent.com/42843497/93472720-bbd60080-f8fd-11ea-8b3a-b69fb83c7720.png)

**Comment by KittenCodes** [comment]
I would suggest using a Div and Oxygen's Video element, or a Code Block if you want a self-hosted video.
