### ISSUE TITLE
Show / Hide Oxygen Metabox in 3.6 Alpha 1

### ISSUE THREAD

**Issue by jmcbade** [soflyy/oxygen-bugs-and-features#1558]
**Describe the bug**
Show/Hide tc boxes do not work?
I have tested with both Classic and Gutenberg editors.

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
Yes

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
http://carefree-rabbit.w6.wpsandbox.pro?upass=P7Tk53vBuQi1

**To Reproduce**
Edit role for Editor and do not tic the hide box for Page or Post
Try to edit /Add a post or Page. 

**Expected behavior**
Expect to see the Oxygen Metabox.  If Metabox is displayed, expect to see Template pick list.

**What actually happens**
No Oxygen Metabox is displayed

**Screenshots**
*If applicable, add screenshots to help explain your problem.*

**Desktop (please complete the following information):**
- OS: MAC OS 10.15.6
 - Browser Tested Chrome and Safari
 - Oxygen Version 3.6 Alpha 1

**Smartphone (please complete the following information):**
 - Oxygen Version [e.g. 2.2 Alpha]

**Additional context**
*Add any other context about the problem here.*

**Comment by KittenCodes** [comment]
@jmcbade The meta box is always hidden for users with edit only access.

**Comment by jmcbade** [comment]
Which is my point.  With the metabox exposed we could allow our clients to access from a list of predefined templates.  This makes sense if we don't want to have to have the client use some level Oxygen Layout expertise.

If it worked at the level of "native" WP, they would have a list of pre-defined templates to choose from in Classic and Gutenberg editors.

The Page Attributes drop downs appear but don't do anything.  I put in a request to at least hide these and it was turned into a "feature request".  *meh*

So as it works now, unless we give the client some level of access to Oxygen Builder, they have a system that hides any ability to manage layouts other than what is possible inside the content area.  If they are to use Oxygen Builder (even in some limited level), they have to learn and understand it.  If we don't expose Oxygen, then they have a WP system with as far as the client is concerned, has a broken Template list.

Oxygen Builder could make things REALLY simple for the novice client if we could pre-define more than on Template for Posts or pages (aside from CPTs) and have a valid working list to pick from.

**Comment by Spellhammer** [comment]
> The Page Attributes drop downs appear but don't do anything. I put in a request to at least hide these and it was turned into a "feature request". meh

That's because it's a feature request.

> So as it works now, unless we give the client some level of access to Oxygen Builder, they have a system that hides any ability to manage layouts other than what is possible inside the content area.

Edit Mode is literally a way to give the client some level of access to Oxygen Builder.

> If they are to use Oxygen Builder (even in some limited level), they have to learn and understand it.

50% of your clients will probably have to learn and understand WordPress, too. You should teach them what they need to know to use the tools you're handing them.

Thanks for making a feature request at #1555. That's the appropriate way to provide this feedback and request the changes you're advocating for. I'm closing this because showing/hiding Oxygen's metaboxes isn't supposed to work in Edit Mode, since Edit Mode hides the metaboxes.

**Comment by jmcbade** [comment]
"_50% of your clients will probably have to learn and understand WordPress, too. You should teach them what they need to know to use the tools you're handing them._"

I am not trying to be adversarial here, but there really is another side to how to look at this.

"_You should teach them what they need to know to use the tools you're handing them._"  Sure if that is what the client was asking for and wanted.

**_Ok, I see your goal here is to give the client we build a site using Oxygen Builder with more granular ways and access to make changes.  Great I get that and if that is the goal, 3.6 seems a great start at that goal._**  

I don't understand in that effort why hiding template selection and assignment might not be an edit mode option that fits in that scope.  Maybe you could help me understand that design decision?  I'm not trying to be in any way snarky, it's an honest question.

The "Other 50%" of my clients do not want to learn more Wordpress and more tools, but have more simplified options that they have me design and pay me to make them.  What they do mostly care about is that by my using Oxygen to build their product is how performant it is.  The rest of web design and operations is in their minds "smoke and mirrors" to them.  

What seems very simple and straight forward to us as far as WP and O2 go is something they barely grasp.  My job most of the time is to make the website as easy and simple for them as possible. Being able to select a more then pre-defined template and then use some custom blocks really hits a "sweet spot" fo a big portion of skill levels and abilities. 

They aren't corporate clients, they are very small companies and organizations that are good at what they do but websites are way out of scope for them. They just want to run their business and let other do most of or as much of the website with some predefined options they pay me to create.  If they want more options, they pay me to create them.   I have amended my feature request to make that definition more clear.

My intension is not to make you wrong, but to offer a different perspective.

Thank you for your time to review my input and suggestions.

Kind regards,

-John
