### ISSUE TITLE
Off-by-one error on columns responsive breakpoints

### ISSUE THREAD

**Issue by benhohner** [soflyy/oxygen-bugs-and-features#156]
**Describe the bug**
The oxygen mobile breakpoints, specify less than 480px, less than 768px, or less than 996px, but they actually break at less than 481px, less than 769px, and less than 997px, respectively. This is particularly important because iPads are 768px wide, meaning styles that are meant for mobile phones will also target iPads.

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
Yes

**To Reproduce**
1. Create a columns element with multiple columns
2. set the "Stack columns vertically" breakpoint to one of the mobile breakpoints (992px, 768px, 480px)
3. Save the page and view on the front-end with browser inspector in mobile testing mode.
4. Set mobile testing mode to responsive.
5. set the screen width to any of the designated breakpoint widths.
6. The page should break 1 pixel wider than it's supposed to.

**Expected behavior**
breakpoints should break at:
max-width: 991px
max-width: 767px
max-width: 479px

**What actually happens**
breakpoints break at one pixel too large:
max-width: 992px
max-width: 768px
max-width: 480px

**Screenshots**
![2019-03-18 18_30_51-Oxygen Visual Editor - 2H Media - Agile Digital Marketing Strategy](https://user-images.githubusercontent.com/1463217/54568605-3d1da180-49ae-11e9-88ef-db4ec9d6bcc3.png)
![2019-03-18 18_31_02-Oxygen Visual Editor - 2H Media - Agile Digital Marketing Strategy](https://user-images.githubusercontent.com/1463217/54568608-4149bf00-49ae-11e9-904f-e984496f92f2.png)

![2019-03-18 18_33_12-2H Media - Agile Digital Marketing Strategy](https://user-images.githubusercontent.com/1463217/54568612-43138280-49ae-11e9-986c-fb986ae307fb.png)
These columns should collapse into single columns below 768px, not at 768px.

**Desktop (please complete the following information):**
- OS: Windows 10 latest
 - Browser: Chrome latest
 - Oxygen Version: 2.2

**Additional context**
Note: A simple rename of the fields in the builders doesn't fix this issue as these breakpoints are troublesome when styling websites for actual devices.

**Comment by KittenCodes** [comment]
@benhohner,

There's a feature request here to add custom break points. Please add a vote to it: https://github.com/soflyy/oxygen-bugs-and-features/issues/129.

**Comment by louisreingold** [comment]
Would we really break anything by just fixing this and changing 992 to 991, 768 to 767, etc?

**Comment by KittenCodes** [comment]
> Would we really break anything by just fixing this and changing 992 to 991, 768 to 767, etc?

I can't see anything being broken by it, and changing them by 1px would seem to make sense.

**Comment by Spellhammer** [comment]
Breakpoints corrected to behave as their labels indicate in 3.1 alpha 1.
