### ISSUE TITLE
Choose width of the structure panel

### ISSUE THREAD

**Issue by mbs1337** [soflyy/oxygen-bugs-and-features#1565]
**Describe the feature you'd like to see included in Oxygen.**
It would be great if it was possible to change and control the width of the Structure Panel

**What are the use cases for this feature?**
so it's possible to delete something, without having to use the scroll bar below.

**Examples of this feature or functionality.**
It's a paid feature from Hydrogen, but my thought is that it could benefit the Oxygen UI by standard. Without having to pay for third part plugins.

Se also this GIF [https://i.imgur.com/PB7k1k2.gif](https://i.imgur.com/PB7k1k2.gif)

**Comment by mbs1337** [comment]
Might be a duplicate of: [#289](https://github.com/soflyy/oxygen-bugs-and-features/issues/289)

**Comment by KittenCodes** [comment]
> Might be a duplicate of: [#289](https://github.com/soflyy/oxygen-bugs-and-features/issues/289)

Yes, you're correct. Closing.
