### ISSUE TITLE
Errors caused by depreciated use of implode() and join() 

### ISSUE THREAD

**Issue by jheslop25** [soflyy/oxygen-bugs-and-features#1567]
The files affected are

oxygen/component-framework/components/component.class.php (join()) line 2212
oxygen/component-framework/component-init.php (implode()) lines 4724, 4728, and 4740.

The error is caused by improper order of arguments to the functions and can be solved by reversing the order.

see screen shots for SOLVED version. 

This error basically breaks the entire framework and causes the editor to fail with a 503 status code as well as completely blowing up the front end.

<img width="1259" alt="Screen Shot 2020-09-22 at 11 38 33 AM" src="https://user-images.githubusercontent.com/36897536/93919582-1d65e880-fccb-11ea-9f29-d7c599a2538e.png">
<img width="1259" alt="Screen Shot 2020-09-22 at 11 42 37 AM" src="https://user-images.githubusercontent.com/36897536/93919589-2060d900-fccb-11ea-9397-619ffbbd3a3d.png">

**Comment by KittenCodes** [comment]
Fixed in v3.6.
