### ISSUE TITLE
[2.2] The Add Reusable Parts menu is hidden unless you rapidly resize the bottom of the window (Chrome W10)

### ISSUE THREAD

**Issue by benhohner** [soflyy/oxygen-bugs-and-features#157]
**Describe the bug**
In Chrome on Windows 10, when you load the editor if you have created a Reusable Part, the Add Reusable Part menu is not visible. The only way to make it visible is to resize the bottom of the window up and down quickly until it becomes visible. (not even joking.)

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
Yes

**To Reproduce**
1. Create a Reusable Part
2. Refresh the builder
3.  Click Add +
4. The Reusable Part Accordion Tab is missing

To fix:
5. Using the mouse, grab the bottom of the window and resize it up and down rapidly (multiple times a second)
6. After maybe 5 seconds, the menu will appear.

**Expected behavior**
The add reusable parts accordion menu should be visible if there is a reusable part existing on the site.

**What actually happens**
The add reusable parts accordion menu is not visible until you rapidly resize the browser window or resize the window to make it very tall in proportion to its width.

**Screenshots**
![2019-03-18 20_13_08-](https://user-images.githubusercontent.com/1463217/54571716-4ca2e780-49ba-11e9-9d95-7acd3dd2f57d.png)
Reusable Part created, but menu not visible without rapidly resizing bottom of browser window.

**Desktop (please complete the following information):**
- OS: Windows 10 latest
 - Browser: Chrome latest
 - Oxygen Version: 2.2

**Additional context**
**Tested in FF latest on Windows 10, and this bug is not present.**

**Comment by KittenCodes** [comment]
This is fixed in the latest version of Oxygen.
