### ISSUE TITLE
Problem to show specified template on specified page by ID

### ISSUE THREAD

**Issue by MerkurNord** [soflyy/oxygen-bugs-and-features#1570]
Hi :)

We have buy Oxygen and we develop our first website with it. We have problem, and we do not understand why this not work for us.

**The issue is:**
We have create a template we want to show on a page with specific ID number. 

**We have do this:**

- Created a template
- Under singular have we choose "Page" and under "Only apply if parent ID is one of the following" set the ID to the page ID.

Then I think I have do the right, and check page. But when I check the page, that only show me my header and footer, but not the template. Why?

Best regards Mads

**Comment by KittenCodes** [comment]
@MerkurNord This won't work as you're applying the template to pages where the parent is the ID. It won't apply it to the parent page.

Please open the page in the WordPress admin area and manually select the template from the dropdown box below the "Edit with Oxygen" button.
