### ISSUE TITLE
Universal.css return to original value and can't be change

### ISSUE THREAD

**Issue by inovaweb33** [soflyy/oxygen-bugs-and-features#1573]
Hello,

There is a lot of SelectorsCSS i would like to change directly in universal.css to make my code proper, but i can't because when i update the file , he seems to be automaticaly updated with the original version.

Do you know what file i need to change to avoid this ? 

I want to change the /* Product Categories Widget */

Because i dont want to override, its not very proper.

Thanks a lot

**Comment by KittenCodes** [comment]
You need to use a stylesheet via Manage > Stylesheets in the top right of the builder. It's not possible to modify universal.css directly.

If you have created the Selectors, you can modify them via Manage > Selectors.

**Comment by wpsumo** [comment]
@KittenCodes I think it's also about to not override css with more css. Rather see that we could edit the default values instead of overriding over and over again.
