### ISSUE TITLE
Implement a mobile first approach

### ISSUE THREAD

**Issue by derSebastian** [soflyy/oxygen-bugs-and-features#1574]
Implement a mobile-first approach in Oxygen by using the min-width instead of max-width for breakpoints. 

As mobile traffic is continually rising and depending on region or industry may already be the main device used to browse a site. Implementing min-width (mobile-first approach) would allow for both mobile-first and desktop-approach which would change how designers think about design and it is generally easier to move and element around when you have more space then when you have to scram or hide content as you move to a smaller display size.

Oxygen could potentially implement this via a settings toggle so that users could choose their preferred method. You already have custom stylesheet options so maybe combining that in the Oxygen builder would enable min-width and set the default editor preview to the smallest device.

I won't compare it to other software as I believe Oxygen stands out over others and has an already more 'code or developer-friendly' approach as compared to other page builders.

Ref:
https://zellwk.com/blog/how-to-write-mobile-first-css/
https://www.smashingmagazine.com/2018/12/generic-css-mobile-first/
https://www.mightyminnow.com/2013/11/what-is-mobile-first-css-and-why-does-it-rock/

**Comment by michacassola** [comment]
Very cool idea! Please @derSebastian mention this idea over in the Facebook group so people vote for this.

**Comment by scmrecordings** [comment]
+1

**Comment by wplit** [comment]
Already requested - https://github.com/soflyy/oxygen-bugs-and-features/issues/126

**Comment by F1yingBears** [comment]
+1
