### ISSUE TITLE
Code Block Lost Functionality

### ISSUE THREAD

**Issue by scmrecordings** [soflyy/oxygen-bugs-and-features#1575]
All of my code blocks no longer have php, css or javascript editors accessible. It's hard for me to pinpoint when this happened but I believe I installed 3.6 alpha 1 and used it for a few days without issues. I then purchased and installed the Oxy Tools and Hydrogen Pack plugins and things seemed fine as well but at some point the code block started only having the "tag" and "style output" options in the primary tab and then every option except for the php, css and javascript editor in the advanced tab. That being said all existing code blocks still have their old code functionality but I just can't access it. I completely deactivated all plugins and only activated Oxygen and the problem persists. I even rolled back to Oxygen 3.5 and code blocks are still broken.

I really wish I could pinpoint when it happened or how it happened but because I didn't realize the problem existed until after whatever caused it happened, I really don't know what steps can be taken to reproduce it.

I feel like it possibly has to do with the new client control options in that my administrator role somehow lost access to code blocks but I really am not sure. I do have the complete error log from the time everything happened (early this morning) until now which I can send if that's helpful.

Anything I can do to help figure it out, I am happy to do!

**Comment by scmrecordings** [comment]
Update:
I installed a backup from the day before and reinstalled 3.6 Alpha 1, Oxy Tools and Hydrogen Pack and everything is working fine. I saved a backup with WP AIO Migrate before restoring in case the team wanted to take a look at it and see what might have gone wrong. Additionally I saved the php error log in case that's useful.

**Comment by Lupul** [comment]
I have the same problem on clean install of Oxygen 3.6 alpha.1 with wp 5.5.1

**Comment by KittenCodes** [comment]
@Lupul Please open a support ticket so that we can take a look at this for you: https://oxygenbuilder.com/support.

@scmrecordings If you would like us to take a look at your backup file, please send us the required information in a support ticket: https://oxygenbuilder.com/support.

**Comment by Lupul** [comment]
@KittenCodes Haven't opened a support request yet as it looks to be already confirmed by the devs: https://www.facebook.com/groups/1626639680763454/permalink/3306026029491469
