### ISSUE TITLE
How to create related post in Single post type ?

### ISSUE THREAD

**Issue by bdloner** [soflyy/oxygen-bugs-and-features#1577]
When I use Easy Post element and choose manual WP Query

I can't use * 'post__not_in' => array (get_the_ID()) * for Detect current post

What should I do?

**Comment by KittenCodes** [comment]
It's not possible to use variables in Oxygen's manual query. Please use the workaround here: https://gist.github.com/yankiara/c43da83662a14e7609b4e23f6d82717a (you will need to modify it to work on your site).
