### ISSUE TITLE
Header builder background color not respected when set to overlay

### ISSUE THREAD

**Issue by Deralict** [soflyy/oxygen-bugs-and-features#1578]
**Describe the bug**
The background color set for the header is ignored when the header is set to overlay. This makes it impossible to make the header semi-transparent or opaque when it's set to overlay content below.

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
*Yes*

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
Yes: https://oxygen-q6ssrh5crsd7.oxygen-demo.qsandbox.me/wp-admin/index.php

**To Reproduce**
1. Edit template "Main"
2. Select Header Builder object 
3. Set background colour to red
4. Set "Overlay header" to ALWAYS

**Expected behavior**
Background of header should be red.

**What actually happens**
It's transparent (no background) 

**Screenshots**
https://www.dropbox.com/s/pxfox7ypf5totvn/Screen%20Shot%202020-09-27%20at%202.49.29%20PM.png?dl=0

**Desktop (please complete the following information):**
- OS: [Mac OSX]
 - Browser Chrome
 - Oxygen Version 3.5

**Comment by shoelaced** [comment]
I just built a site where this is actually the behavior I wanted - a background color when not overlaid and no background when overlaid, so it worked great for me, but I did originally want a translucent background when overlaid and simply gave up eventually. I know it's possible by duplicating the header but it seems like being able to set the background color for overlay and non-overlay separately would be helpful and allow those of us who do want a transparent background on overlay to achieve the same effect by just reducing the color opacity to zero.

**Comment by KittenCodes** [comment]
@Deralict You can set the background of an overlay header using CSS in a stylesheet via Manage > Stylesheets in the top right of the builder. Here's some example CSS - you would need to update it to use the ID of your header:

```css
body #_header-2-225.oxy-header.oxy-overlay-header:not(.oxy-sticky-header-active) {
    background-color: rgba(255,0,0,0.27) !important;
}
```

**Comment by thorsolutions** [comment]
Not sure why this is closed, by default the background should not be ignored and the need for custom css could have been avoided. Is the assumption that on using a header row as overlay, everyone uses a complete transparent background?

**Comment by Spellhammer** [comment]
> Is the assumption that on using a header row as overlay, everyone uses a complete transparent background?

Yes. That's the purpose of the overlay option, is to achieve a transparent header overlaid on top of whatever content is below it in the DOM, e.g. a hero section.

**Comment by shoelaced** [comment]
> > Is the assumption that on using a header row as overlay, everyone uses a complete transparent background?
> 
> Yes. That's the purpose of the overlay option, is to achieve a transparent header overlaid on top of whatever content is below it in the DOM, e.g. a hero section.

I think the issue is when people want to have a translucent background for the overlay rather than a completely transparent one. The CSS that @KittenCodes offered helps but it's cumbersome.

**Comment by ribenawrath** [comment]
> > Is the assumption that on using a header row as overlay, everyone uses a complete transparent background?
> 
> Yes. That's the purpose of the overlay option, is to achieve a transparent header overlaid on top of whatever content is below it in the DOM, e.g. a hero section.

I need  to create a pill nav, where the background images go around the nav section. The only way to make this work in oxygen is having an overlay that respects my background colour. Seems like a really weird limitation you're implemented

**Comment by shIxx01** [comment]
It works as desired, but the setting is somewhat hidden.

1. Create a header using the header builder (with logo, menu, etc.).

2. Set the overlay to "always." The background color will no longer have any effect!

3. Go to Advanced/Background/Image Overlay Color and adjust the transparency and color there.
