### ISSUE TITLE
Oxygen plus Yoast 14.9  plus Classic Editor plus WP 5.5.1

### ISSUE THREAD

**Issue by SaraMackers** [soflyy/oxygen-bugs-and-features#1579]
On WP v 5.5.1 and Oxygen, Yoast14.9 and Classic Editor installed, on the page editor / post editor pages of Wordpress, you cannot toggle from the 'Text' to 'Visual' in the editor.

It causes this error in the console;
Uncaught TypeError: Cannot read property 'registerPlugin' of undefined
    at new YoastOxygen (yoast-seo-compatibility.js?ver=5.5.1:4)
    at HTMLDocument.<anonymous> (yoast-seo-compatibility.js?ver=5.5.1:20)
    at i (jquery.js?ver=1.12.4-wp:2)
    at Object.fireWith [as resolveWith] (jquery.js?ver=1.12.4-wp:2)
    at Function.ready (jquery.js?ver=1.12.4-wp:2)
    at HTMLDocument.J (jquery.js?ver=1.12.4-wp:2)

If Oxygen is deactivated - this error goes away.

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
Yes

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
Yes - http://defiant-salamander.w5.wpsandbox.pro/wp-admin/post.php?post=2&action=edit

**To Reproduce**
1. Go to 'Sample Page'
2. Click on 'Visual' or 'Text' (whichever is not selected)
3. You'll notice nothing happens
4. If you check the console - you'll see the error as per above

**Expected behavior**
Being able to toggle from one view to another

**What actually happens**
As per above

**Screenshots**
*If applicable, add screenshots to help explain your problem.*

**Desktop (please complete the following information):**
- OS: [Mac OS Catalina]
 - Browser [Chrome 85.0.4183.121]
 - Oxygen Version [3.5]

*Add any other context about the problem here.*
This issue is not present with Yoast V14.8

**Comment by KittenCodes** [comment]
Fixed in 3.6 Beta: https://oxygenbuilder.com/2020/09/28/oxygen-3-6-beta-1-now-available/

**Comment by SaraMackers** [comment]
Thanks! Is the Beta version OK to use in live sites?

**Comment by KittenCodes** [comment]
> Thanks! Is the Beta version OK to use in live sites?

No, Alpha and Beta releases aren't recommended for use on live sites. In the mean-time, I would suggest downgrading to Yoast 14.8.

**Comment by wpsumo** [comment]
@KittenCodes Neither this one is fixed for me:
```
Uncaught TypeError: Cannot read property 'registerPlugin' of undefined
    at new YoastOxygen (yoast-seo-compatibility.js?ver=5.5.3:4)
    at HTMLDocument.<anonymous> (yoast-seo-compatibility.js?ver=5.5.3:20)
    at i (jquery.js?ver=1.12.4-wp:2)
    at Object.fireWith [as resolveWith] (jquery.js?ver=1.12.4-wp:2)
    at Function.ready (jquery.js?ver=1.12.4-wp:2)
    at HTMLDocument.J (jquery.js?ver=1.12.4-wp:2)
```

**Comment by KittenCodes** [comment]
@wpsumo It sounds as though there's some caching on your site that is preventing you from seeing the fixes added to v3.6.

**Comment by wpsumo** [comment]
Cleared all cache again without success.

```
(function($){
	YoastOxygen = function() {
		if(typeof(YoastSEO) !== 'undefined') {
			YoastSEO.app.registerPlugin( 'YoastOxygen', {status: 'ready'} );
			YoastSEO.app.registerModification( 'content', this.replaceDataWithOxygenMarkup, 'YoastOxygen', 5 );
		}
	}

	/**
	 * Replaces the full content with Oxygen generated markup, as it is supposed to contain the_content too
	 *
	 * @param data The data to modify
	 */
	YoastOxygen.prototype.replaceDataWithOxygenMarkup = function(data) {
		// The full Oxygen generated markup is already enqueued
		return ysco_data.oxygen_markup;
	};

	$(document).ready(function(){
		new YoastOxygen();
	});
})(jQuery);
```

**Comment by wpsumo** [comment]
Did a hard reload now and it seems like that solved the problem.

**Comment by KittenCodes** [comment]
@wpsumo Please open a support ticket so that we can take a look at this for you: https://oxygenbuilder.com/support.

**Comment by wpsumo** [comment]
It is down. Can not do that.
