### ISSUE TITLE
more customize option in Easy Post

### ISSUE THREAD

**Issue by MYIG** [soflyy/oxygen-bugs-and-features#158]
I am using 'easy post' and its template is 'grid-image-standard'. I tried to change the template to 'grid-image w/ animated dark gradient overlay'. but its arrangement is just like 2 X 3 (total 6) or 2 X 5(total 9). I want more option like 3 X 2 or 4 X 1 and so on...

there is an option only about font. there is no option about the size of the image. I already said about it #137 ... I really talked about it for over 1 week with staff...

**Comment by KittenCodes** [comment]
You can modify the Easy Posts templates to change the number of items per row. Do do that, you need to go to Templates > Template CSS.

Alternatively, you can also use Oxygen's Repeater element.
