### ISSUE TITLE
SuperBox Box Shadow Vertical Offset Bug.

### ISSUE THREAD

**Issue by batmullow** [soflyy/oxygen-bugs-and-features#1580]
**Describe the bug**
The vertical offset of box shadow of superbox is also adjusting the horizontal offset of box shadow.

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
Yes

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
*If yes, provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*

**To Reproduce**

**Expected behavior**
Vertical offset to actually offset the vertical axis of box shadow of  the superbox.

**What actually happens**
Slider or keying in values of superbox vertical offset still affects only the horizontal axis.

**Screenshots**
*If applicable, add screenshots to help explain your problem.*

**Desktop (please complete the following information):**
- OS: Windows 10
 - Browser Google Chrome
 - Oxygen Version 5.4

**Smartphone (please complete the following information):**

**Additional context**

**Comment by KittenCodes** [comment]
@batmullow I've not been able to replicate this on a clean Sandbox site running Oxygen 3.5: https://oxygen-qcj4z4ypy7gbl.oxygen-demo.qsandbox.me/superbox/.

If you're able to replicate it, please send me a link to the Sandbox site: https://oxygenbuilder.com/try/.
