### ISSUE TITLE
Design Set Generated Image Fails

### ISSUE THREAD

**Issue by jmcbade** [soflyy/oxygen-bugs-and-features#1584]
**Describe the bug**
After generating design set images, the images associated with elements have the shape but no image.

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
Yes

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
http://cheerful-termite.w5.wpsandbox.pro?upass=eIT3x4T3eAu5 

**To Reproduce**
Make the site a Design set in the Oxygen settings under library
Create a template
Assign some sections to categories
Tick the box to make sections elements
Click the box to generate the screen shots
Go back into the Oxygen editor and look at the user design set elements
Items have the shape but no image, or, they are not even representative of the section at all, but are random content area images.

**Expected behavior**
Generate images for user design set images.  Design set images generator is currently unusable in this version and the Oxygen 3.6 Beta 1 as tested.

**What actually happens**
*A clear and concise description of what happens instead of the expected behavior.*

**Screenshots**

![image](https://user-images.githubusercontent.com/1731707/94628435-f4f97200-02fa-11eb-84d5-3e6df412e986.png)

![image](https://user-images.githubusercontent.com/1731707/94628489-178b8b00-02fb-11eb-88d9-3aea8b755bd7.png)

**Desktop (please complete the following information):**
- OS: MAC OS 10.15.7
 - I use Chrome mostly but browser agnostic
 - Oxygen Version 3.5, 3.6 Beta 1

**Smartphone (please complete the following information):**
 - Oxygen Version [e.g. 2.2 Alpha]

**Additional context**
Needs resolution soon!

**Comment by KittenCodes** [comment]
@jmcbade 

> After generating design set images, the images associated with elements have the shape but no image.

This is happening because none of the templates on the Sandbox site are assigned to anything. When this is the case, Oxygen can't take a screenshot using the template because when it views something on the "virtual" front-end of the site, it can't see the template in use.

I've assigned the template here as the catch-all: http://cheerful-termite.w5.wpsandbox.pro/wp-admin/post.php?post=12&action=edit. I then regenerated the screenshots for that template and all are working correctly.

**Comment by jmcbade** [comment]
Soph,

I see you closed this before I could even reply.

Ok, but I have templates here locally on my server that are assigned and don't create any images:

Here is a screenshot:



I can't get any images to generate and again, these are assigned to pages.

This is the home page.

What's do you think is the reason?

Thanks,

-John

**Comment by KittenCodes** [comment]
@jmcbade

Unfortunately, your screenshot doesn't show in your comment. Are you able to upload it?

> Ok, but I have templates here locally on my server that are assigned and don't create any images:

Is your server HTTP accessible? The reason for asking is that it would need to contact our servers to be able to use the screenshot API.

**Comment by jmcbade** [comment]
Soph,


Yes, it has http access as confirmed by updating plugins etc. :)

This should be the screen shot.  Can you see it?  I converted it to a png this time.



Thanks,


-John

**Comment by KittenCodes** [comment]
@jmcbade 
> This should be the screen shot.  Can you see it?  I converted it to a png this time.

Sorry, I still can't see it. Are you able to manually add it to the thread instead of replying by email please?

**Comment by jmcbade** [comment]
![No Element Screenshot Images-2](https://user-images.githubusercontent.com/1731707/94874648-708b2880-048d-11eb-92f2-dc839e4b0448.png)

**Comment by KittenCodes** [comment]
Thanks @jmcbade 

I've not seen Oxygen produce blank white screenshots previously. Is it possible for you to send me login details for the site and a link to the item that has the white screenshot so that I can take a look? You can open a ticket here: https://oxygenbuilder.com/support.

**Comment by electricarts** [comment]
Hey, 

same Problem here. Is this already under investigation? Should i open a ticket too?

**Comment by KittenCodes** [comment]
> Hey,
> 
> same Problem here. Is this already under investigation? Should i open a ticket too?

Yes, please open a support ticket: https://oxygenbuilder.com/support.
