### ISSUE TITLE
"Featured products" in Woocommerce

### ISSUE THREAD

**Issue by mbs1337** [soflyy/oxygen-bugs-and-features#1587]
**Describe the feature you'd like to see included in Oxygen.**
How can I make a block to show "Featured products" in Woocommerce? There is this standard feature from Woocommerce, where you can click "Featured product" on each product and then it's possible to show these on the frontpage as an example. I can't see any thing about this in Oxygen, and this might not be a function yet. I have manage to get trough this, by making a category named "Featured" and then use the "Product list" block, to only show products in this particular category. 

**What are the use cases for this feature?**
To show featured products on the frontpage (as an example)

**Examples of this feature or functionality.**
See this video of what I mean with Featured Products: https://www.youtube.com/watch?v=IzNG4DBhteY

**Comment by KittenCodes** [comment]
@mbs1337 You can show featured products using the Products List element. You need to set the query to custom, and then right at the bottom of the Products Query tab, you need to select "featured" from the Visibility dropdown box.
