### ISSUE TITLE
Resizing the Structure Panel Column

### ISSUE THREAD

**Issue by j-ki** [soflyy/oxygen-bugs-and-features#1589]
**Describe the feature you'd like to see included in Oxygen.**
I'd like to be able to widen the structure column.

**What are the use cases for this feature?**
As the webpage gets more nested divs, columns, images, text, etc., I have to scroll right to access the hamburger menu that allows me to rename, duplicate, or delete a part.

By widening the structure column, I can save myself a few clicks by not scrolling to the right, accessing the hamburger menu, then scrolling back to the left.

**Examples of this feature or functionality.**
*If another product has done it well, provide examples here.*

**Comment by KittenCodes** [comment]
Duplicate: https://github.com/soflyy/oxygen-bugs-and-features/issues/289
