### ISSUE TITLE
Div with background image in field is empty when class added to div

### ISSUE THREAD

**Issue by visualtribe** [soflyy/oxygen-bugs-and-features#1593]
**Describe the bug**
When I add a background image to a div and or background overlay then I add a class to that div, the field with the background image is now blank. If I remove class, field once again shows background image.

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
No, this is a Oxygen bug

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
*If yes, provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*
Yes, same thing happens

**To Reproduce**
1. place a div on page
2. Go to background and add a background image
3. Add a colour overlay although it happens without the overlay as well
4. Add a class to the div
5. Background image and overlay fields are now blank.
6. If you try to change the image even if blank, field still blank and nothing is changed. As well as overlay colour. 
7. If class is removed fields are populated again. 

**Expected behavior**
*A clear and concise description of what you expected to happen.*
Even if class is on div, you should still see and change overlay colour as well as see background image link.

**What actually happens**
*A clear and concise description of what happens instead of the expected behavior.*
Background and overlay image fields blank. 

**Screenshots**
*If applicable, add screenshots to help explain your problem.*

**Desktop (please complete the following information):**
- OS: Mac
 - Browser Firefox 81.0.1
 - Oxygen Version 3.5

**Comment by KittenCodes** [comment]
@visualtribe This isn't a bug, You have added the background image to the element ID. This won't show when the class is added because the CSS doesn't belong to the class.

You can copy the styles from the ID to the class - please see: https://oxygenbuilder.com/2020/08/25/oxygen-3-5-now-available/.
