### ISSUE TITLE
Easy Posts element doesn't display correctly in category pages

### ISSUE THREAD

**Issue by carmescl** [soflyy/oxygen-bugs-and-features#1594]
**Describe the bug**
In the footer, I used Easy Posts. It displays correctly in pages and posts but in archive pages it's missing the image and the styling is ruined.

*A clear and concise description of what the bug is.*

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
*Yes/No*

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
*If yes, provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*
YES. https://oxygen-qkmjdxrh9gjbl.oxygen-demo.qsandbox.me/
Please compare footer between a page and an archive page, i.e. https://oxygen-qkmjdxrh9gjbl.oxygen-demo.qsandbox.me/ VS https://oxygen-qkmjdxrh9gjbl.oxygen-demo.qsandbox.me/blog/

![image](https://user-images.githubusercontent.com/72305751/94992721-7d5b6980-05be-11eb-8669-38918f5d39e0.png)

**To Reproduce**

**Expected behavior**
*A clear and concise description of what you expected to happen.*

**What actually happens**
*A clear and concise description of what happens instead of the expected behavior.*

**Screenshots**
*If applicable, add screenshots to help explain your problem.*
![image](https://user-images.githubusercontent.com/72305751/94992729-85b3a480-05be-11eb-97c3-5dc59e319044.png)

**Desktop (please complete the following information):**
- OS: Windows 10
 - Browser: Firefox, Chrome, Edge
 - Oxygen Version [e.g. 2.2 Alpha] - latest version

**Smartphone (please complete the following information):**
 - Oxygen Version [e.g. 2.2 Alpha]

**Additional context**
*Add any other context about the problem here.*

**Comment by KittenCodes** [comment]
@carmescl Thank you for bringing this to our attention. For some reason, the Easy Posts element in the Financial design set wasn't using %%EPID%% in the Template CSS to ensure that the CSS is only applied to that specific Easy Posts element.

I've updated it for you on the Sandbox site and the footer Easy Posts element is now loading correctly on the Blog page.

**Comment by carmescl** [comment]
Hi KittenCodes,

Thanks for responding. I can see that it loads correctly in the sandbox site. Can you please tell me how to replicate the fix?
Is this where you added %%EPID%% (see image below) ? That code has always been there.

![image](https://user-images.githubusercontent.com/72305751/95041787-4b571e00-070a-11eb-8d60-c8d7839daa0f.png)

**Comment by carmescl** [comment]
Ah, I have figured it out. This is the template for the Posts Page.
