### ISSUE TITLE
PHP WARNING from oxygen component is bloating error_log

### ISSUE THREAD

**Issue by YammYcoding** [soflyy/oxygen-bugs-and-features#1595]
`PHP Warning:  strpos() expects parameter 1 to be string, array given in /public_html/www/wp-content/plugins/oxygen/component-framework/components/component.class.php on line 3638`

happened on two installs. might be happening to everyone else...

fix? :)

**Comment by KittenCodes** [comment]
Fixed in 3.6 Beta: https://oxygenbuilder.com/2020/09/28/oxygen-3-6-beta-1-now-available/
