### ISSUE TITLE
"Slider" shows the Dots and Arrows above the mobile menu - "Update" Problem in PC and mobile

### ISSUE THREAD

**Issue by Bebuk85** [soflyy/oxygen-bugs-and-features#1596]
**Describe the bug**
The dots and arrows of the slider are showing up when you click in the mobile menu and in PC

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
*Yes*

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
Yes.
http://stormy-ape.w6.wpsandbox.pro/
User: demo
Password: 41ebhJ6OLRx2

**To Reproduce**
1.Create a template with header builder and edit it
2.Create a Menu
3. Create a page and put a section>Div>Slider>Slide>Image and edit it

**Expected behavior**
The mobile menu (and PC )will show normal without the dots and arrows of the slider

**What actually happens**
The dots and arrows of the slider are showing up in the mobile (menu and PC)

**Screenshots**
![slider](https://user-images.githubusercontent.com/72046610/95001551-410d1680-0588-11eb-9a55-5999fc305c18.PNG)
![Slider1](https://user-images.githubusercontent.com/72046610/95001656-343cf280-0589-11eb-8ea1-b696f3389ff0.jpeg)

**Desktop (please complete the following information):**
- OS: Windows 10
 - Browser Chrome
 - Oxygen Version 3.5

**Smartphone (please complete the following information):**
- Device: Huawei P10 Pro
 - OS: Android 9
 - Browser Chrome
 - Oxygen Version 3.5

**Additional context**
I was testing the site with the Inspector in Chrome and puting each phone as Iphone X, 6,7,8, etc and each one has the same problem

**Comment by KittenCodes** [comment]
@Bebuk85 This happens when the header is set to "overlay". To fix it, please add the following CSS to a stylesheet via Manage > Stylesheets in the top right of the builder. You will need to update the CSS to use the ID of your slider:

```css
#slider-3-62 .unslider-arrow.prev, #slider-3-62 .unslider-arrow.next, #slider-3-62 .unslider .unslider-nav {
  z-index: 10;
}
```

**Comment by MonolithAdmin** [comment]
Very simple way you can just adjust z-index of the three elements to 1 and this will take effect on ALL sliders across your entire site. Add the CSS to a code block in your template that covers each page or inject with code snippets or add to additional CSS in the appearance>edit>custom css section.

```
.unslider-arrow.prev, .unslider-arrow.next, .unslider-nav {
  z-index: 1 !important;
}
```
