### ISSUE TITLE
CSS Clamp() Function Feature

### ISSUE THREAD

**Issue by saysonjerald** [soflyy/oxygen-bugs-and-features#1597]
The clamp() CSS function clamps a value between an upper and lower bound. clamp() enables selecting a middle value within a range of values between a defined minimum and maximum. It takes three parameters: a minimum value, a preferred value, and a maximum allowed value.

see this video demo here by Gary Simon using the clamp(): [YT link](https://www.youtube.com/watch?v=dg488RrpNTc)
see for more details: [click here](https://developer.mozilla.org/en-US/docs/Web/CSS/clamp)

Yo! This is the CSS trend right now.

**Comment by KittenCodes** [comment]
@saysonjerald This is available in 3.6 (which is currently in Beta). There's more information here: https://oxygenbuilder.com/2020/09/15/oxygen-3-6-alpha-1-now-available/.
