### ISSUE TITLE
responsive breakpoint for new feature 

### ISSUE THREAD

**Issue by rayhan62** [soflyy/oxygen-bugs-and-features#1599]
**Describe the feature you'd like to see included in Oxygen.**
*A clear, detailed description of the feature you're requesting.*

**What are the use cases for this feature?**
*e.g. Accessibility, e-commerce store that sells bicycles, etc.*

**Examples of this feature or functionality.**
*If another product has done it well, provide examples here.*

**Comment by rayhan62** [comment]
bro i need to add custom device breakpoint please make it new feature , because editor x and webflow they have custom device  breakpoint it's very helpful bro please this include in a new feature,,,,

**Comment by rayhan62** [comment]
bro i need to add custom device breakpoint please make its new feature, because editor x and webflow they have custom device  breakpoint it's very helpful bro please this include in a new feature,

**Comment by arsh999cg** [comment]
+1

**Comment by KittenCodes** [comment]
#1700
