### ISSUE TITLE
2.3 Alpha 1 - Styles showing in editor, missing in front-end

### ISSUE THREAD

**Issue by bconnell** [soflyy/oxygen-bugs-and-features#160]
**Describe the bug**
*A clear and concise description of what the bug is.*

When you design in the editor, it does not show in the front-end. Example, a menu I designed in a reusable header template contained inside of a page template has a nice red background with white text, and hover/dropdown. In the front end, it shows with zero styling whatsoever.

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
*Yes/No*

Yes

**Screenshots**
*If applicable, add screenshots to help explain your problem.*

https://i.imgur.com/N8Mf5sF.jpg
https://i.imgur.com/c71ogbh.jpg

**Desktop (please complete the following information):**
 - Oxygen Version [e.g. 2.2 Alpha]

Windows 10
Chrome - latest
Oxygen 2.3 Alpha 1

**Additional context**
*Add any other context about the problem here.*

See the issue at http://howtowholesalerealestate.pcriot.com/

NOT a caching issue.

**Comment by bconnell** [comment]
Fixed it by making global colors and assigning them to the menu items. Bug is that the style is ignoring non global styles it seems.

**Comment by KittenCodes** [comment]
@bconnell, If you're still having this issue in Oxygen 2.4.1, please recreate the issue on a Sandbox site at https://oxygenbuilder.com/try/ and send the Sandbox login to support@oxygenbuilder.com.
