### ISSUE TITLE
Errors cames up from the oxygen plugin after debugging mode on

### ISSUE THREAD

**Issue by naiemofficial** [soflyy/oxygen-bugs-and-features#1600]
I'm getting the following errors after turned on debugging mode

1. Deprecated : join(): Passing glue string after array is deprecated. Swap the parameters in /home/public_html/wp-content/plugins/oxygen/component-framework/components/component.class.php on line 2301
2. Deprecated : implode(): Passing glue string after array is deprecated. Swap the parameters in /home/public_html/wp-content/plugins/oxygen/component-framework/component-init.php on line 4953, 4965, 3055, 3056
3. This is a bit different, it looks oxygen plugin code exist in jetpack plugin >>Notice: Undefined index: oxygen-styles in /home//public_html/wp-content/plugins/jetpack/class.jetpack.php on line 6371

**Comment by naiemofficial** [comment]
After installing beta version below errors cames up
![2020-10-06_____21-59-48](https://user-images.githubusercontent.com/34242279/95226989-61a2ce00-081f-11eb-902b-0abe2e52b75f.png)

**Comment by naiemofficial** [comment]
@KittenCodes 
After installing beta below errors cames up

![2020-10-06_____21-59-48](https://user-images.githubusercontent.com/34242279/95227591-1b01a380-0820-11eb-87cb-eca539fbca87.png)

**Comment by naiemofficial** [comment]
> @naiemofficial
> 
> The deprecated messages have been addressed in 3.6 Beta: https://oxygenbuilder.com/2020/09/28/oxygen-3-6-beta-1-now-available/.
> 
> I've not seen the JetPack error previously. If you're able to replicate it on a Sandbox site, please send me a login for the site so that I can take a look: https://oxygenbuilder.com/try/.

I'm not getting reply yet

**Comment by KittenCodes** [comment]
@naiemofficial Did you open a support ticket? If you did, please can you let me know which email address your message came from?
