### ISSUE TITLE
Bug in Price Box module when adding symbols

### ISSUE THREAD

**Issue by mediatopper** [soflyy/oxygen-bugs-and-features#1602]
**Describe the bug**

In a price box when adding symbols like " ' or ( the module lose all styling

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**

Yes

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
 
No, you have to do it live to see it

**To Reproduce**
1. Go to the buider
2. Add a section 
3. Add a column (3 col)
4. Add a price box module into a column
5. Go to the features tekst and ad the word: Pagina's
 -> with the ' or " or ( in the tekst, all styling is lost instantly

**Expected behavior**
No loss of styling with use of ' " or ( ) 

**What actually happens**
All styling is lost

**Screenshots**
no

**Desktop (please complete the following information):**
windows 10
every browser (chrome, firefox, edge)

**Smartphone (please complete the following information):**
also the case

**Additional context**
Aksed on the oxygen builder forum and they confirmed it

**Comment by KittenCodes** [comment]
@mediatopper I've not been able to replicate this. Please can you record a quick video showing the issue: https://www.loom.com/ and send me the URL of the video?

Which version of Oxygen are you using?

**Comment by mediatopper** [comment]
Hi, I use the latest version of Oxygen. On the Facebook support page they could replicate this.

Here is the loom video: https://www.loom.com/share/536c3c7a90b04b3f9483bb1a65677f38

Thanks

**Comment by KittenCodes** [comment]
@mediatopper Thank you for the video. I've been able to replicate the issue and find another bug report for this: https://github.com/soflyy/oxygen-bugs-and-features/issues/850.
