### ISSUE TITLE
License key clear in inspector... 

### ISSUE THREAD

**Issue by Caffeinedesign** [soflyy/oxygen-bugs-and-features#161]
**Describe the bug**
simple: if you inspect license field you can see license number... so if i buy oxygen, any customer can have my license key, or i would have to remove it making it not updatable

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
there's no troubleshooting for this ;) 

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
you can replicate on any oxygen install ;)

**To Reproduce**
1. go to settings
2. go to license
3. insert key
4. validate key
5. inspect password field ;)

**Expected behavior**
that license would be hidden or "rehashed" or something

**What actually happens**
you can just see license number ;) 

**Screenshots**
![oxygenlic](https://user-images.githubusercontent.com/48643750/54632556-ac62c680-4a7e-11e9-862a-03eed56c716a.JPG)

**Desktop (please complete the following information):**
device agnostic

**Smartphone (please complete the following information):**
device agnostic

**Additional context**
*Add any other context about the problem here.*

**Comment by Caffeinedesign** [comment]
beaver builder for example does it this way:

![oxygenlicbeaver](https://user-images.githubusercontent.com/48643750/54633083-b9cc8080-4a7f-11e9-8f20-734d709394bd.JPG)

**Comment by louisreingold** [comment]
If your customer has access to the Oxygen > License screen then don't they have access to the entire WP database, which means they could read the license key anyway?

> so if i buy oxygen, any customer can have my license key

Who cares? Not us. And it doesn't affect you. So just don't worry about it.
