### ISSUE TITLE
remove pre-title inserts

### ISSUE THREAD

**Issue by forreggbor** [soflyy/oxygen-bugs-and-features#1610]
**Describe the feature you'd like to see included in Oxygen.**
remove “Archive:”, “Category:” etc. pre-title inserts in Archive Titles

**What are the use cases for this feature?**
Category archive page would be more clear. Displaying "Category:" before the category title is not necessary in most cases.

**Examples of this feature or functionality.**
https://wpdevdesign.com/how-to-remove-archive-category-etc-pre-title-inserts-in-archive-titles/

**Comment by KittenCodes** [comment]
You can do this using the Code Snippets plugin: https://wordpress.org/plugins/code-snippets/. Here's the code:

```
add_filter( 'get_the_archive_title', function ($title) {    
	if ( is_category() ) {    
		$title = single_cat_title( '', false );    
	} elseif ( is_tag() ) {    
		$title = single_tag_title( '', false );    
	} elseif ( is_author() ) {    
		$title = '<span class="vcard">' . get_the_author() . '</span>' ;    
	} elseif ( is_tax() ) { //for custom post types
		$title = sprintf( __( '%1$s' ), single_term_title( '', false ) );
	} elseif (is_post_type_archive()) {
		$title = post_type_archive_title( '', false );
	}
	return $title;    
});
```
