### ISSUE TITLE
Template inheritance

### ISSUE THREAD

**Issue by oy1958** [soflyy/oxygen-bugs-and-features#1612]
I have two templates , one catches all the other for posts.
Want to inherit the main template but it won't show up.

**Comment by KittenCodes** [comment]
@oy1958 Please ensure that the template you want to inherit contains an Inner Content element.

**Comment by oy1958** [comment]
Thank you for your reply

Le ven. 9 oct. 2020 à 13:48, Soph Simmonds <notifications@github.com> a
écrit :

**Comment by ifranl** [comment]
Thanks @KittenCodes!
