### ISSUE TITLE
bug in nav menu pro Oxygen

### ISSUE THREAD

**Issue by diegobril** [soflyy/oxygen-bugs-and-features#1616]
**Describe the bug**
*A clear and concise description of what the bug is.*

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
*Yes/No*
yes 
**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
*If yes, provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*
this is the link to the sandbox: https://oxygen-q369ly6ccknbl.oxygen-demo.qsandbox.me/?ct_builder=true
**To Reproduce**
1. open the page on a desktop computer'
2. narrow the browser window to below 768px width, so that the nav menu changes to the burger menu of mobile version
2. Click on the burguer menu to open the modal that contains the mobile nav menu, then close the modal
3. without refreshing the page, widen the browser window to above 768 px width.
4. See error: the nav menu of the desktop version is broken

**Expected behavior**
*A clear and concise description of what you expected to happen.*
the nav menu of desktop version should appear inside the browser window, but instead, it goes far beyond the end of the browser window
**What actually happens**
*A clear and concise description of what happens instead of the expected behavior.*

**Screenshots**
*If applicable, add screenshots to help explain your problem.*

**Desktop (please complete the following information):**
 - Oxygen Version [e.g. 2.2 Alpha]

**Smartphone (please complete the following information):**
 - Oxygen Version [e.g. 2.2 Alpha]

**Additional context**
*Add any other context about the problem here.*
<img width="1198" alt="Screen Shot 2020-10-11 at 5 39 18 PM" src="https://user-images.githubusercontent.com/72710067/95689664-ba3fe580-0be8-11eb-9563-01c744de4c65.png">

**Comment by KittenCodes** [comment]
Duplicate: https://github.com/soflyy/oxygen-bugs-and-features/issues/873
