### ISSUE TITLE
Changing Font Family to Default causes incorrect rendering in editor

### ISSUE THREAD

**Issue by swinggraphics** [soflyy/oxygen-bugs-and-features#1632]
**To Reproduce**
1. Change the Font Family setting on (probably any) element to Default. (You can even go from "inherit" to "default" and this will happen.)
2. See the typeface revert to the browser default (which is not the same as "inherit" or "unset").

**Expected behavior**
It should clear the `font-family` style rule in the editor.

**What actually happens**
It causes the CSS in the editor to render `font-family: ''`, which actives the browser's default font-family (usually "serif").

**Comment by Martin-1** [comment]
+1

**Comment by KittenCodes** [comment]
@swinggraphics If Oxygen is set to use the Default font, it will use the browser font, so this is working as intended.

**Comment by swinggraphics** [comment]
Nope. "default" is not a valid `font-family` value, so "Default" in the menu implies "Don't specify a separate value for this element", and it outputs an empty `''` value, which is also invalid.

**Comment by swinggraphics** [comment]
@KittenCodes  Please reopen the issue. This is a straight up bug.

**Comment by swinggraphics** [comment]
Contacted support through the website, and evidently outputting invalid CSS is, in fact, the intended behavior. Unbelieveable.
