### ISSUE TITLE
No way to turn AOS off.

### ISSUE THREAD

**Issue by wplit** [soflyy/oxygen-bugs-and-features#164]
**Describe the bug**
I've realised that once it has been set globally, even if all the options are unset to try and remove, the AOS script still runs on all pages.

I think it's because you cannot unselect the 'disable on'. Once you have chosen an option, there's no way to go back to no selection.

**Comment by benfavre** [comment]
For an editor marketed for performance, not being able to disable a useless script is quite a major issue.

**Comment by KittenCodes** [comment]
Fixed in v3.3.
