### ISSUE TITLE
PHP function condition does not work with 0 or false

### ISSUE THREAD

**Issue by swinggraphics** [soflyy/oxygen-bugs-and-features#1647]
**Describe the bug**
Setting a PHP Function Return Value to `== 0` or `== false` does not work. The element will never be displayed.

In my case, I am using `is_front_page`. When set to 1, the element is correctly displayed on the front page and not other pages. When set to 0, it is not displayed on any page.

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
*Yes*

**Comment by swinggraphics** [comment]
I discovered setting it to `<=0` does what's desired. That is a good workaround, but it is unintuitive. `== 0` should also work.

**Comment by KittenCodes** [comment]
@swinggraphics 

The WordPress is_front_page() function returns 1 for the front page and nothing if it's not the front page. You can test that by using the function in a Code Block.

You could use is_blank or is_not_blank, depending on the desired outcome.

**Comment by swinggraphics** [comment]
No, it returns a boolean value. Read the docs
https://developer.wordpress.org/reference/functions/is_front_page/

**Comment by KittenCodes** [comment]
> No, it returns a boolean value. Read the docs

I did read the docs. I then tested the function in a Code Block element to check what was being retuned and I found that the value was blank if it was run on any page that wasn't the front page.

**Comment by swinggraphics** [comment]
If you're echoing something, false converts it to an empty string. 

> A boolean TRUE value is converted to the string "1". Boolean FALSE is converted to "" (the empty string). This allows conversion back and forth between boolean and string values.
https://www.php.net/manual/en/language.types.string.php

But anything with `return false`, like `is_front_page()`, `__return_false`, etc, is actually returning false.

`if ( __return_false() == false ) echo 'Is false';` The `==` works as expected in PHP, and should work the same way in your display conditional. If you're display conditional can't properly evaluate `return false` as `== false`, it is doing something wrong.
