### ISSUE TITLE
Non-Supported Error (Lottie Player)

### ISSUE THREAD

**Issue by Ranz79** [soflyy/oxygen-bugs-and-features#1649]
Hi... I got a Non-Supported Error referring to some lottie player. Not sure if it's serious, how it affects my site or how to fix it. Attached is a screenshot of the error.

Unsure if this an issue related to me alone or a bug so I posted it here.

Kind thanks.

![Screen Shot 2020-10-17 at 3 19 15 PM](https://user-images.githubusercontent.com/70836871/96474157-82e0c280-1200-11eb-8a15-533966084ad8.png)

**Comment by KittenCodes** [comment]
@Ranz79 

I suspect you are seeing this error because you've added Lottie files to your site and the builder doesn't know to load the required files. As long as the front-end of your site is working correctly, you should be able to ignore the error.
