### ISSUE TITLE
Editor is pulling wrong post

### ISSUE THREAD

**Issue by nugroho-mr** [soflyy/oxygen-bugs-and-features#1653]
Hi there,

I have an issue that suddenly appear. Everytime I open Oxygen editor in any place (including template & gutenberg block), it will show the content of one particular page, lets call it 'page X'. So I can basically only able to edit 1 page (page X).

**Comment by KittenCodes** [comment]
@nugroho-mr Please open a support ticket so that we can take a look at this for you: https://oxygenbuilder.com/support.
