### ISSUE TITLE
Section Container Padding 0 is ignored

### ISSUE THREAD

**Issue by swinggraphics** [soflyy/oxygen-bugs-and-features#1658]
If you set any Container Padding value of a Section to 0, it is treated as a blank value by Oxygen. It should output `padding-left: 0` etc. It looks correct on the backend, but the frontend code is not generated.

**Comment by swinggraphics** [comment]
I'm going to close, because although I was able to reproduce it reliably, I found I could change it to something else first, then set it to 0 for it to work as expected.

**Comment by swinggraphics** [comment]
Then again… If you apply 0 padding to a section with a __class name as the selector__, that value is not output on the front end, no matter what.

**Comment by KittenCodes** [comment]
Duplicate: https://github.com/soflyy/oxygen-bugs-and-features/issues/720
