### ISSUE TITLE
Manual ID selection not working in repeater, easy posts

### ISSUE THREAD

**Issue by AlkoKod** [soflyy/oxygen-bugs-and-features#1661]
**Describe the bug**
The manually select ID´s in repeater and easy posts element does nothing. Was discovered by other users in facebook group too. It is 100% bug,

**Comment by KittenCodes** [comment]
@AlkoKod The ID selection works correctly in both the Repeater and Easy Posts elements. Please ensure you are entering a comma separated list of IDs without spaces.

You can see this working correctly on the page here: https://oxygen-qhqazcbhlxf7.oxygen-demo.qsandbox.me/id-test/. If you want to log into the Sandbox site to see how it has been set up, the username and password are both demo.

**Comment by AlkoKod** [comment]
@KittenCodes you are right, it works on your sandbox. But it does not at my sites. So there is something happening stil..

**Comment by KittenCodes** [comment]
@AlkoKod If you would like us to take a look at your site, please open a support ticket: https://oxygenbuilder.com/support.
