### ISSUE TITLE
Problem with custom icon sets disappearing from live website

### ISSUE THREAD

**Issue by runechronos** [soflyy/oxygen-bugs-and-features#1667]
Hy, I've got a question about Oxygenx, maybe you can help me: I have imported fontawesome 5.15 icon set in my oxygen website, inside the "svg sets", then I used some icons in the builder. Cleared all cache, etc.

It works for some days, then by magic, the custom svg sets disappears and the icons are of course not visible anymore on the website. Only the basic "Fontawesome" and "Linearicons" sets are still present.

I don't get why it's doing this, It did this 2 times already (the website is still running on Oxygen 3.3, I'm also using W3 Total cache )
Thanks in advance if someone has any idea on what is causing that thing ?

It is not browser dependant, it's an oxygen bug. Does it have to do something with my older Oxygen version ?

**Comment by KittenCodes** [comment]
@runechronos Does it work correctly if you disable all other plugins on your site? If you'd like us to take a look at your site, please open a support ticket: https://oxygenbuilder.com/support.
