### ISSUE TITLE
Undefined index

### ISSUE THREAD

**Issue by lucadima15** [soflyy/oxygen-bugs-and-features#167]
Getting two "undefined index" in 'oxygen/component-framework/components/component.class.php':

Notice : Undefined index: button-text-color in
[...]/plugins/oxygen/component-framework/components/component.class.php
on line 2763

Notice : Undefined index: button-size in
[...]/plugins/oxygen/component-framework/components/component.class.php
on line 2764

SOLVED changing lines 2762, 2763 and 2764:

$buttonColor 		= oxygen_vsb_get_global_color_value($this->states[$key]['button-color']);
$buttonTextColor 	= oxygen_vsb_get_global_color_value($this->states[$key]['button-text-color']);
$buttonSize 		= $this->states[$key]['button-size'];

WITH:

if(isset($this->states[$key]['button-color']))
                    $buttonColor 		= oxygen_vsb_get_global_color_value($this->states[$key]['button-color']);
if(isset($this->states[$key]['button-text-color']))
                    $buttonTextColor 	= oxygen_vsb_get_global_color_value($this->states[$key]['button-text-color']);
if(isset($this->states[$key]['button-size']))
                    $buttonSize 		= $this->states[$key]['button-size'];

**Comment by KittenCodes** [comment]
@lucadima15,

If you're still seeing these notices in your logs using Oxygen 2.4.1, please send a copy of your debug.log file to support@oxygenbuilder.com.
