### ISSUE TITLE
How to Add meta tag before body tag

### ISSUE THREAD

**Issue by rayhan62** [soflyy/oxygen-bugs-and-features#1670]
**Describe the feature you'd like to see included in Oxygen.**
*A clear, detailed description of the feature you're requesting.*

**What are the use cases for this feature?**
*e.g. Accessibility, e-commerce store that sells bicycles, etc.*

**Examples of this feature or functionality.**
*If another product has done it well, provide examples here.*

**Comment by rayhan62** [comment]
How to Add meta tag before body tag
Please make it new feature how to add meta tag before body tag..?
and include add new media query add custom breakpoint device..?

**Comment by KittenCodes** [comment]
> How to Add meta tag before body tag

Depending on what you're wanting to add, you can probably use the Insert Headers and Footers plugin: https://wordpress.org/plugins/insert-headers-and-footers/.
