### ISSUE TITLE
CSS font-display property not present on the HTML <link href> tag generated by Oxygen -> How to configure it ?

### ISSUE THREAD

**Issue by runechronos** [soflyy/oxygen-bugs-and-features#1676]
Hy,

I don't find any way to configure the default font-display CSS property for fonts coming from google like "Open Sans" for example. I have to set a "font-display" which has to be present in the url 

Actually this is the tag generated by oxygen:

`<link href="https://fonts.googleapis.com/css?family=Open+Sans:100,200,300,400,500,600,700,800,900|Open+Sans:100,200,300,400,500,600,700,800,900|Open+Sans:100,200,300,400,500,600,700,800,900" rel="stylesheet">`

But I need it to be for example like this one, with the **display=auto**, to control how text will be rendered in case of fallback -> it is affecting my Page ranking by not beeing there.

`<link href="https://fonts.googleapis.com/css?family=Open+Sans:100,200,300,400,500,600,700,800,900|Open+Sans:100,200,300,400,500,600,700,800,900|Open+Sans:100,200,300,400,500,600,700,800,900&display=auto" rel="stylesheet">`

Is it a bug or can I configure it somewhere ?

Thanks in advance.

**Comment by KittenCodes** [comment]
@runechronos 

> But I need it to be for example like this one, with the display=auto, to control how text will be rendered in case of fallback -> it is affecting my Page ranking by not beeing there.

Unfortunately, there's not currently a way to add fallback fonts. If you'd like to see the option in a future release of Oxygen, please add a vote to the feature request here: https://github.com/soflyy/oxygen-bugs-and-features/issues/990.
