### ISSUE TITLE
Another undefined index

### ISSUE THREAD

**Issue by lucadima15** [soflyy/oxygen-bugs-and-features#168]
Getting two "undefined index" in 'oxygen/component-framework/components/component.class.php':

Notice : Undefined index: icon-color in
[...]/plugins/oxygen/component-framework/components/component.class.php
on line 2819

Notice : Undefined index: icon-background-color in
[...]/plugins/oxygen/component-framework/components/component.class.php
on line 2820

SOLVED changing lines 2819 and 2820:

$iconColor = oxygen_vsb_get_global_color_value($this->states['media'][$is_media][$key]['icon-color']);
$iconBackgroundColor= oxygen_vsb_get_global_color_value($this->states['media'][$is_media][$key]['icon-background-color']);

WITH:

$iconColor = (isset($this->states['media'][$is_media][$key]['icon-color']) && $this->states['media'][$is_media][$key]['icon-color']) ? oxygen_vsb_get_global_color_value($this->states['media'][$is_media][$key]['icon-color']) : '';
$iconBackgroundColor= (isset($this->states['media'][$is_media][$key]['icon-background-color']) && $this->states['media'][$is_media][$key]['icon-background-color']) ? oxygen_vsb_get_global_color_value($this->states['media'][$is_media][$key]['icon-background-color']) : '';

**Comment by KittenCodes** [comment]
@lucadima15,

If you're still seeing these notices in your logs using Oxygen 2.4.1, please send a copy of your debug.log file to support@oxygenbuilder.com.
