### ISSUE TITLE
Client mode: 'Save before edit with Oxygen' dont work

### ISSUE THREAD

**Issue by Webdegelijk** [soflyy/oxygen-bugs-and-features#1680]
In client mode its not possible to go directly to Oxygen after saving. One has to move out and then re-open the page in order to be able to open Oxygen. 
3.6 rc2

**Comment by Spellhammer** [comment]
@Webdegelijk Did you resolve this yourself? What did you find?

**Comment by Webdegelijk** [comment]
Thanks for your comment Elijah! My client complained about it and sent me a video, and the mistake I made was to add the issue directly to github. 

After I added the issue I verfied the complaint, in my test the blue square Oxygen button showed directly, so I decided to close the issue.

I think it had something to do that I have seen many times before myself, as a adminstrator login I’ve seen this many times: “Oxygen is open in another tab or by another user. Please close the other instance of the builder and refresh this page to edit.” This might have been the problem for the editor too? 

Regards,
Paul

**Comment by Spellhammer** [comment]
If Oxygen was edit-locked, the Oxygen edit button should show up but be disabled (greyed out.)

If this comes up again, feel free to contact us via https://oxygenbuilder.com/support and we can investigate.

**Comment by Webdegelijk** [comment]
Ok I will contact support cos the button doesn't show up at all in my install. 
Thanks again Elijah, keep up the great work. 
Regards, 
Paul
