### ISSUE TITLE
Custom SVG icon sets not loading icons.

### ISSUE THREAD

**Issue by Sicutunum** [soflyy/oxygen-bugs-and-features#1683]
**Describe the bug**
*A clear and concise description of what the bug is.*
Hi. I recently purchased Oxygen (using the latest version 3.5 love it). I was watching this tutorial on your Youtube channel "Rebuilt: Making Elementor's Landing Page in Oxygen". I went to icomoon.io and generated an icon set as explained in the video. I'm on Windows, so after downloading, I unzipped the package. The symbol-defs.svg file was there. I uploaded it to my site via the menu located at Oxygen settings > SVG Sets. The file appeared to load fine, the name was accepted (just named it Test Set). However, none of the icons from the set appear in the dropdown box after selecting the set I uploaded when editing a page with Oxygen. "Test Set" appears as an option along with Fontawesome and Linearicons, but none of the icons I created the file with appear in the dropdown box. At first I thought this might be an issue with the search box, so I deleted the initial "thumbs-up" text but still nothing showed up. One of the icons I added was pacman (titled icon-pacman in the symbol-defs.svg file) typing full or partial entries into the icon search box after selecting "Text Set" produced no results. I disabled all plugins, tried again and it did not work. I also tried with a blank install of Oxygen via your site's sandbox and got the same results. I tried saving the file after selecting "Test Set" to see if that would refresh the box. It did not work. I tried creating and uploading multiple SVG sets and got the same results every time. I tried disabling Oxygen's cache via settings, did not work. No errors were produced in my site's log. I'm wondering if something in the output of the symbol-defs.svg file from icomoon.io has changed?

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
*Yes/No*
YES

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
*If yes, provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*

https://oxygen-qq29xmwj9qxbl.oxygen-demo.qsandbox.me/sample-page/?ct_builder=true

**To Reproduce**
1. Go to https://oxygen-qq29xmwj9qxbl.oxygen-demo.qsandbox.me/sample-page/?ct_builder=true
2. Click on the only oxygen icon element on the screen, select "Test Set" as the icon set.
3. Scroll down to: NA
4. See error: NA

**Expected behavior**
*A clear and concise description of what you expected to happen.*
I expected to see the icons that were present in the symbol-defs.svg file.

**What actually happens**
*A clear and concise description of what happens instead of the expected behavior.*
The icon selection box remains empty regardless of what is or isn't typed into the icon search box.

**Screenshots**
*If applicable, add screenshots to help explain your problem.*

**Desktop (please complete the following information):**
- OS: [e.g. iOS] Windows 7
 - Browser [e.g. chrome, safari] Chrome
 - Oxygen Version [e.g. 2.2 Alpha] 3.5 (official release)

**Additional context**
*Add any other context about the problem here.*
I've included the symbol-defs.svg file I was using (had to zip it to upload here).

[symbol-defs.zip](https://github.com/soflyy/oxygen-bugs-and-features/files/5465023/symbol-defs.zip)

**Comment by Sicutunum** [comment]
Apologies. Just now seeing the updated video where it says you have to check the option to add <title> before exporting the icons from Icomoon. I've added a comment to that video but I would recommend also removing that original video from your "Oxygen Complete Video Reference" playlist, adding a card, or a note within the visible lines of the video description.

**Comment by Spellhammer** [comment]
> I've added a comment to that video but I would recommend also removing that original video from your "Oxygen Complete Video Reference" playlist, adding a card, or a note within the visible lines of the video description.

That's our mistake, sorry for the confusion.

**Comment by dmorawetz** [comment]
I had the exact same problem, but it was due to `fill` and `style` attributes on my paths in the SVG. Maybe you can add a notice, that those should be removed from custom SVGs, too.

**Comment by Vasilis-Vr** [comment]
I have exactly the same problem - I have set the <title> to be added in Preferences. I run Oxygen Classic 4.9.1 in WordPress 6.7.2, in Safari, under Windows 10. The Icon Set dropdown shows the imported icon set (consisting of one svg icon), I delete whatever is in the search box and no icon is displayed in the Icon gallery.
Is this a bug?

**Comment by Vasilis-Vr** [comment]
Eventually, I re-created a set with more icons (not only one) and it worked ok.
