### ISSUE TITLE
Wrong Fonts Displayed

### ISSUE THREAD

**Issue by bob2007** [soflyy/oxygen-bugs-and-features#1688]
On a header template, I am using some Google fonts that are in the font list. While I am in the edit mode the fonts show just fine. When the page is being viewed in any of my browsers, it just shows plain text, not the Google font I have selected. 
https://busyladybug.com/wow-gifts/  In the Header (Wow Gifts and the Busy Lady Bug text)
![Wow Gifts Header Correct](https://user-images.githubusercontent.com/13498259/97805081-e1a33480-1c21-11eb-8847-3aeec63656bb.png) 
![Wow Gifts Header Wrong Text](https://user-images.githubusercontent.com/13498259/97805086-e7991580-1c21-11eb-89a1-b0b3568184b6.png)

Was using Version 3.4 of Oxygen Builder, updated to 3.5 then to 3.6.2 RC. Nothing changed. 

This is a Reuseable section that when I bring it into the page, I select Single so I have to modify the template to make changes.

**Comment by KittenCodes** [comment]
@bob2007 Please open a support ticket so that we can take a look at this for you: https://oxygenbuilder.com/support.

**Comment by bob2007** [comment]
Thanks for the response
Now
How do I do a pull request

Link would be great

Thanks
