### ISSUE TITLE
element with brand new class gets some sort of cache

### ISSUE THREAD

**Issue by gdewey** [soflyy/oxygen-bugs-and-features#1689]
have tried this with 2 different browsers.

created 1 div and create a new class name.. make changes (styles)..

then create other div and add the same class name

create a third div.. only 2 and 3 will take the sytle. but first will act as if it was independent.   I have to mannually delete syle and re. asign class name to all so they can all take the changes.. 

its a real pain as sometimes old values gets cache and dont know why something is wrong

class management really needs a check.. its not reliable.

**Comment by gdewey** [comment]
there seems to be a problem with Spinup https://spinupwp.com/ cache. Thats what we normally use for wp. We never had an issue with elementor, divi or BB. The whole class system gets crazy using spinup.. so this is not really a bug but an issue using o this..  what is the url path that your plugin uses to whitelist the cache? tks

**Comment by gdewey** [comment]
also another mistake was that id will overwrite class properties. so as I created changes on first element and then created a class.. all new properties where done on the id not the class. this is kind of confusing but make sense as it is.. its just that there is no clarification anywhere about this.

**Comment by KittenCodes** [comment]
> what is the url path that your plugin uses to whitelist the cache?

If you're using Oxygen's CSS cache then the files will be in /wp-content/uploads/oxygen/css/.

> also another mistake was that id will overwrite class properties

This is how CSS works. It's not an oddity in Oxygen.
