### ISSUE TITLE
Guttenberg Oxygen and Builder Discrepency

### ISSUE THREAD

**Issue by SuperSonicSites** [soflyy/oxygen-bugs-and-features#1690]
**Describe the bug**
When a change is made to the Guttenberg version of the page, it doesn't appear in the builder.

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
Yes

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
https://oxygen-qaf68xmgckzbl.oxygen-demo.qsandbox.me/

**To Reproduce**
1. Go to the homepage
2. Click on Oxygen builder
3. Scroll down to the beer section
4. See how each slider is exactly the same...not as what it shows in the Guttenberg editor

**Expected behavior**
I expect to have the Oxygen builder to show the same content as the Guttenberg editor

**What actually happens**
The oxygen builder shows how we duplicated the old sliders but not the updates done via Guttenberg

**Comment by KittenCodes** [comment]
@SuperSonicSites This isn't a bug.

If you would like to see changes from Gutenberg reflected in Oxygen, please add a vote to the feature request here: https://github.com/soflyy/oxygen-bugs-and-features/issues/798
