### ISSUE TITLE
Visual Builder

### ISSUE THREAD

**Issue by qdxm** [soflyy/oxygen-bugs-and-features#1693]
It's difficult to describe what happened. However, I'll give it a try.

I spent a while creating a "Posts" template. I do not believe I did anything incorrectly but I noticed one of the elements changed position. I tried to move of back to where it was supposed to be but I could not. I immediately closed the page.

After reopening the template with Oxygen  Builder I noticed that even though I did not save the template, the template continued to have the element in the incorrect place. 

Also, the template structure was missing. Completely blank. I could not get it back. 

I received the following message immediately after opening the template:

**There was an error. DO NOT SAVE THE PAGE. Please copy below error message and send to our support team.
TypeError: Cannot read property 'model' of undefined**

Sorry for my ramblings, however, if I had to guess what could have happened. I'd say that the history for the template reached its max and failed.

Thank
Daniel

**Comment by KittenCodes** [comment]
@qdxm We would need to take a look at your site to be able to help with this. Please open a support ticket: https://oxygenbuilder.com/support.
