### ISSUE TITLE
DONE: Woocommerce

### ISSUE THREAD

**Issue by Phukit** [soflyy/oxygen-bugs-and-features#17]
I would like to see woocommerce integration in the new version of oxygen.

Thanks.

**Comment by nshkrsh** [comment]
ability to create custom product pages (like we can design custom single blog post page) would be awesome.

**Comment by Spellhammer** [comment]
Implemented in Oxygen 3.0.

**Comment by michacassola** [comment]
> Implemented in Oxygen 3.0.

Close this?

**Comment by nshkrsh** [comment]
yes sure. thank you.

Regards,
NSK
