### ISSUE TITLE
Ability to create more "Width & breakpoints"

### ISSUE THREAD

**Issue by kalaio** [soflyy/oxygen-bugs-and-features#1700]
It would be very useful if the user could create additional breakpoints. Sometimes there is the need to create specific adjustments to the layouts at breakpoints that doesn't exist.

**Comment by ProdigyMaster** [comment]
Hey, I also have clients that want to have a "bigger website". Webflow got it right: the main breakpoint is 960px but you can add additional higher resolutions: 1280px, 1440px, 1920px. (https://university.webflow.com/lesson/intro-to-breakpoints)

It would be wonderful if you can add these additional bigger resolutions ❤

**Comment by KittenCodes** [comment]
https://github.com/soflyy/oxygen-bugs-and-features/issues/700
