### ISSUE TITLE
Unable to select measurement units for Column Element divs in 3.6

### ISSUE THREAD

**Issue by Hypersight** [soflyy/oxygen-bugs-and-features#1701]
**Describe the bug**
After upgrade to 3.6, unable to select width units for column divs within the column element from the Primary panel on elements that were existing prior to upgrade. Adding a new column element post upgrade works fine.

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
Yes

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
Yes. https://oxygen-q5rpmm28rg3bl.oxygen-demo.qsandbox.me/sample-page/?ct_builder=true

**To Reproduce**
1. Edit any page with Oxygen
2. Place a column element
3. From the Primary panel, try and select the unit for width and you are not given a choice

**Expected behavior**
You should be given a list of measurement units, similar to if to when you go to Advanced > Size & Spacing and attempted to change the measurement unit for any attribute in this panel. You'll notice the width attribute works fine here.

**What actually happens**
No width units are suggested upon click

**Screenshots**
N/A

**Desktop (please complete the following information):**
OS: macOS Catalina 10.5.7
Browsers: Chrome 86.0.4240.183, Firefox Developer Edition 83.0b9, Brave 1.15.72 

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by KittenCodes** [comment]
@Hypersight I have updated the Sandbox site to Oxygen v3.6 and the new units are showing on the Columns element on the sample page you set up.

If you're still having problems on your site, please open a support ticket so that we can take a look: https://oxygenbuilder.com/support.

**Comment by Hypersight** [comment]
Apologies @KittenCodes, I made the assumption that Sandbox was 3.6. Thanks for looking at it, I'll raise a ticket. Thanks.

**Comment by KittenCodes** [comment]
> Apologies, I made the assumption that Sandbox was 3.6. Thanks for looking at it, I'll raise a ticket. Thanks.

No problem! I've updated our Sandbox sites to v3.6 this morning. I apologise the the delay there.
