### ISSUE TITLE
Dynamic data "Author Pic" don't adapt to selected size

### ISSUE THREAD

**Issue by Titou74** [soflyy/oxygen-bugs-and-features#1708]
**Describe the bug**
Author pic size not working.

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
No

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
Yes
https://oxygen-qg7fnnqsr44bl.oxygen-demo.qsandbox.me/test-author-image/

**To Reproduce**
1. Install a plugin to save avatar localy
2. On a repeater, add an image and set image URL to dynamic data "Author Pic"
3. Select an image width (200 or 400)

**Expected behavior**
Image should have the selected size (200px or 400px)

**What actually happens**
The image have default size (96px)

**Potential solution**
Error of "get_avatar_url()" function call on:
Oxygen_VSB_Dynamic_Shortcodes\oxygen_author_pic (line 297)
```php
function oxygen_author_pic($atts) {
	return get_avatar_url(get_the_author_meta('email'), $atts['size']);
}
```

According to WP documentation (https://developer.wordpress.org/reference/functions/get_avatar_url/), second parameter should be an array, but the call pass a string.

Solution is to replace "$atts['size']" by "$atts". Work on my installation.

**Comment by KittenCodes** [comment]
Fixed in v3.8 Beta 1.
