### ISSUE TITLE
Error when selecting Selector Detector first time

### ISSUE THREAD

**Issue by jmcbade** [soflyy/oxygen-bugs-and-features#1710]
I get this error when selecting the Selector Detector in settings for Oxygen the first time on my iMac Pro and my MacBook Pro and  Running Catalina 10.15.7.   Using LocalWP for a server.  Oxygen 3.6 release.

![When-selecting-Selector-detctor-first time-in-settings-1](https://user-images.githubusercontent.com/1731707/99051343-b9311800-25db-11eb-89fb-afc0b22b8bfd.png)

**Comment by KittenCodes** [comment]
Duplicate: https://github.com/soflyy/oxygen-bugs-and-features/issues/1621
