### ISSUE TITLE
flex-wrap button doesn't work for menu

### ISSUE THREAD

**Issue by out-of-order** [soflyy/oxygen-bugs-and-features#1711]
**Describe the bug**
The flex -> flex-wrap_wrap button doesn't work.

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
*Yes/No*
Yes

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
*If yes, provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*

Yes, I have reproduced it in the sandbox, too.

**To Reproduce**
1. Enhance the menu entries
2. Click layouts->flex->flex-warp->wrap
4. See that nothing is being applied

**Expected behavior**
*A clear and concise description of what you expected to happen.*

line-break

**What actually happens**
*A clear and concise description of what happens instead of the expected behavior.*

nothing

**Screenshots**
*If applicable, add screenshots to help explain your problem.*

use your imagination

**Desktop (please complete the following information):**
 - Oxygen Version [e.g. 2.2 Alpha]

**Smartphone (please complete the following information):**
 - Oxygen Version [e.g. 2.2 Alpha]

**Additional context**
*Add any other context about the problem here.*

**Comment by KittenCodes** [comment]
@out-of-order 

Please can you explain what you mean by "Enhance the menu entries"?

**Comment by out-of-order** [comment]
@KittenCodes 
I meant that I had enlarged the amount of menu entries.
I added all existing pages available in the sandbox.

**Comment by KittenCodes** [comment]
@out-of-order 

Flex wrap is correctly added to the Menu element. However, it needs to be added to the child menu items, which can only be done using CSS. Please add the following CSS to a stylesheet via Manage > Stylesheets.

```
.oxy-nav-menu-list {
    flex-wrap: wrap;
}
```
