### ISSUE TITLE
ACF Repeater

### ISSUE THREAD

**Issue by fenwikk** [soflyy/oxygen-bugs-and-features#1712]
**Describe the feature you'd like to see included in Oxygen.**
*A clear, detailed description of the feature you're requesting.*

A feature that has the same functionality as [*Advanced Custom Fields PRO*s Repeater Field](https://www.advancedcustomfields.com/resources/repeater/). 

**What are the use cases for this feature?**
*e.g. Accessibility, e-commerce store that sells bicycles, etc.*

It makes it much easier to make data tables and restaurant menus since you dont need to buy a new plugin with a lot of other features we dont need since we are using Oxygen.

**Examples of this feature or functionality.**
*If another product has done it well, provide examples here.*

[*Advanced Custom Fields PRO*s Repeater Field](https://www.advancedcustomfields.com/resources/repeater/).

Couldnt seem to find this feature anywhere the only thing i found was your video on how to use data tables with ACF PRO

**Comment by perrelet** [comment]
They are in different scopes.
Oxygen's purposed is to provide rapid templating (frontend).
ACFs purpose is to provide rapid data-structures (backend).
ACF and Oxy work seamlessly together...

**Comment by weismannweb** [comment]
Yes a ui for repeaters would be nice but i guess for now you can use a php block right?
