### ISSUE TITLE
oxygen with LearnDash - focus mode

### ISSUE THREAD

**Issue by christian0903** [soflyy/oxygen-bugs-and-features#1714]
**making it possible to use LearnDash 3.. - focus mode with Oxygen **
*For the moment LEarnDash is not functionning with Learndash 3.0 and more less with its focus mode*

I bought oxygen to make an online course academy and I see it is not compatible
and nowhere info about this
Learndash is a leader in its field, so you cannot implement a solution

I'm obliged to disactivate oxygen to activate learndash

**Comment by KittenCodes** [comment]
Oxygen does work with Focus Mode: https://oxygenbuilder.com/tutorial/how-to-use-learndash-focus-mode-with-oxygen/

**Comment by christian0903** [comment]
> **making it possible to use LearnDash 3.. - focus mode with Oxygen **
> _For the moment LEarnDash is not functionning with Learndash 3.0 and more less with its focus mode_
> 
> I bought oxygen to make an online course academy and I see it is not compatible
> and nowhere info about this
> Learndash is a leader in its field, so you cannot implement a solution
> 
> I'm obliged to disactivate oxygen to activate learndash

So I see it is possible, so disregard !!!

**Comment by christian0903** [comment]
So it is possible (see above)
Just a regret: impossible to find in the documentation !!!
