### ISSUE TITLE
Shortcode umlauts get replaced

### ISSUE THREAD

**Issue by devNN1994** [soflyy/oxygen-bugs-and-features#1715]
**Describe the bug**

MySQL Version 5.6, PHP Version 7.4
Using a clean install of oxygen (and being the only plugin used). 

Scenario

I create a new page, edit it with Oxygen and write some text wich has umlauts or special characters in it (ä,ö, ß, €, ...). Then I click on "Save it" (in the Oxygen Builder). The page will be saved and it's content is written in the "wp_postmeta" table in "ct_builder_shortcodes". Note that at this point, the umlauts and special characters are written correctly into the database. 

Now, if I open the page in Wordpress under Pages->Edit (not Edit with Oxygen), simply clicking on "Update" in the top right corner will overwrite the shortcode in the database, replacing the umlauts and special characters with some strange letters. 
For example: Hellö there will be changed into HellÃ¶ there. See the text from the database below from before and after.

`[ct_div_block ct_sign_sha256='8439893fc1e22954f8a6e7a95737ff6b1f24b92e599d81a45b25d079d9a0d3da' ct_options='{"ct_id":1,"ct_parent":0,"selector":"div_block-1-15"}'][ct_headline ct_sign_sha256='35f40262aaf84edf8d33df3542d601dbf977be23678485dbe18bedbe1042b283' ct_options='{"ct_id":2,"ct_parent":1,"selector":"headline-2-15"}']Hellö there[/ct_headline][/ct_div_block]`

will be overwritten with

`[ct_div_block ct_sign_sha256='8439893fc1e22954f8a6e7a95737ff6b1f24b92e599d81a45b25d079d9a0d3da' ct_options='{"ct_id":1,"ct_parent":0,"selector":"div_block-1-15"}'][ct_headline ct_sign_sha256='35f40262aaf84edf8d33df3542d601dbf977be23678485dbe18bedbe1042b283' ct_options='{"ct_id":2,"ct_parent":1,"selector":"headline-2-15"}']HellÃ¶ there[/ct_headline][/ct_div_block]`

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
Yes

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**

The Sandbox Version works as intended. The issue is not reproducable there.

**To Reproduce**
1. Go to 'Pages'
2. Click on 'Create new page'
3. Scroll down to 'Edit with Oxygen', write some text with umlauts, then save it. (Shortcode has umlauts in it, wich is right)
5. Go back to wordpress edit page, click on 'Update'. 
4. See error. (Now the umlauts in the shortcode get replaced by strange characters)

**Expected behavior**

Umlauts and special characters in the shortcode should be shown correctly.

**What actually happens**

Umlauts and special characters are replaced by strange characters.

**Screenshots**

![1](https://user-images.githubusercontent.com/69054572/99187966-ec99b100-2759-11eb-8e17-c7d4e633c629.JPG)

I created a new page, edited it with Oxygen and saved it.

![2](https://user-images.githubusercontent.com/69054572/99187992-09ce7f80-275a-11eb-8487-acb617fa38e6.JPG)

As you can see, the shortcode already has changed the umlauts. Now let's take a look at the database.

![3](https://user-images.githubusercontent.com/69054572/99188018-27034e00-275a-11eb-858b-1933e2130c30.JPG)

Here we see that the shortcode is written correctly with all umlauts into the table.

![4](https://user-images.githubusercontent.com/69054572/99188043-40a49580-275a-11eb-8416-b03c5825770f.JPG)

Now we open the page with wordpress and click on "Update".

![5](https://user-images.githubusercontent.com/69054572/99188062-59ad4680-275a-11eb-8f4b-bee6eebcff81.JPG)

The shortcode is now written incorrectly into the database.

**Desktop (please complete the following information):**
- OS: [e.g. iOS] Tested on iOS and Windows 10
 - Browser [e.g. chrome, safari] Edge and Firefox
 - Oxygen Version [e.g. 2.2 Alpha] 3.6 (latest)

**Smartphone (please complete the following information):**
 - Oxygen Version [e.g. 2.2 Alpha]

**Additional context**

The wordpress install worked correctly. The charset in wp-config is set to utf8 (default), but we also tested utf8mb4.
The database collation is set to '**utf8mb4_unicode_520_ci**'

**Comment by KittenCodes** [comment]
@devNN1994 Please can you let me know what your database and tables are encoded with?

**Comment by KittenCodes** [comment]
> The database collation is set to 'utf8mb4_unicode_520_ci'

Please try setting the database collation and table encoding to utf8mb4_general_ci.

**Comment by devNN1994** [comment]
Hello Soph,

sadly the problem is still present. See the screenshot for our current database collation.

Regards
Nils

________________________________
Von: Soph Simmonds <notifications@github.com>
Gesendet: Dienstag, 17. November 2020 18:32
An: soflyy/oxygen-bugs-and-features <oxygen-bugs-and-features@noreply.github.com>
Cc: devNN1994 <nils_nitsch@hotmail.com>; Mention <mention@noreply.github.com>
Betreff: Re: [soflyy/oxygen-bugs-and-features] Shortcode umlauts get replaced (#1715)


The database collation is set to 'utf8mb4_unicode_520_ci'

Please try setting the database collation and table encoding to utf8mb4_general_ci.

**Comment by KittenCodes** [comment]
@devNN1994 Unfortunately, the screenshot didn't get added to your reply.

As you're still having problems, please open a support ticket so that we can take a look at this for you: https://oxygenbuilder.com/support.
