### ISSUE TITLE
JQUERY 3.5.1 BREAKS STRUCTURE OPTIONS IN EDITOR

### ISSUE THREAD

**Issue by Bebuk85** [soflyy/oxygen-bugs-and-features#1722]
Jquery 3.5.1 breaks the structure>selectors like remove elements and the other (i do not the name but the hamburger icon).

Install jQuery Manager for WordPress and activate Jquery 3.5.1 and see the problems.

3.5.1 ![3 5 1](https://user-images.githubusercontent.com/72046610/99611254-91252880-29d0-11eb-832e-661e2bc68683.PNG)
1.12.4 ![1 12 4](https://user-images.githubusercontent.com/72046610/99611477-faa53700-29d0-11eb-87f7-bcb376b8c3cf.PNG)

**Comment by Spellhammer** [comment]
Fixed in 3.6.1, which is currently available as a release candidate.
