### ISSUE TITLE
Error while saving.

### ISSUE THREAD

**Issue by treksn** [soflyy/oxygen-bugs-and-features#1724]
Hi. I make it short. Wordpress / Oxygen uptodate.

"Error occurs while saving.
200
Your server returned a 200 error to the request to undefined."

Console:
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>503 Service Unavailable</title>
</head><body>
<h*1>Service Unavailable</h*1>
<p>The server is temporarily unable to service your
request due to maintenance downtime or capacity
problems. Please try again later.</p>
</body></html>

iframe.min.js?ver=3.6:6 SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at iframe.min.js?ver=3.6:6
    at angular.js?ver=1.4.2:9280
    at processQueue (angular.js?ver=1.4.2:13075)
    at angular.js?ver=1.4.2:13091
    at Scope.$eval (angular.js?ver=1.4.2:14291)
    at Scope.$digest (angular.js?ver=1.4.2:14107)
    at Scope.$apply (angular.js?ver=1.4.2:14395)
    at done (angular.js?ver=1.4.2:9569)
    at completeRequest (angular.js?ver=1.4.2:9756)

Some older pages are working/able to save and are not affected.
Thank you!

**Comment by KittenCodes** [comment]
@treksn Please open a support ticket so that we can take a look at your site: https://oxygenbuilder.com/support.
