### ISSUE TITLE
Gutenberg: Image with link wrapper can't be edited

### ISSUE THREAD

**Issue by UserPro2021** [soflyy/oxygen-bugs-and-features#1727]
When I create a gutenberg block in Oxygen builder with inside it:
- Link wrapper
   - Image
   - Text 
Then place it on a page in gutenberg. I am able to edit the link, but when I click to change the image it doesn't work.

**Comment by KittenCodes** [comment]
Duplicate: https://github.com/soflyy/oxygen-bugs-and-features/issues/725
