### ISSUE TITLE
Image with Link wrapper cant be changed in Gutenberg

### ISSUE THREAD

**Issue by uixandy** [soflyy/oxygen-bugs-and-features#1728]
**Describe the bug**
When adding an image in a Div and adding a link wrapper to and enabling the whole page to be editable with Gutenberg or creating just a Gutenberg block of it, it is not possible to change the image with gutenberg. When hovering the image you see the notice, that you have to click to change the image, but the library/upload is not appearing.

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
Yes

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
yes -> https://oxygen-qbtjh5w4528bl.oxygen-demo.qsandbox.me/wp-admin/post.php?post=2&action=edit

**To Reproduce**
1. Go to pages, open Sample page
2. Set the check for "make this full page editable in gutenberg"
3. open oxygen editor
4. Add div
5. Add image
6. Add link with wrapper
7. Save and go back to admin
8. Try to change image by clicking on it

**Expected behavior**
I expected the media library and upload possibilty to popup and let me change the image

**What actually happens**
Nothing happens

**Screenshots**
![image](https://user-images.githubusercontent.com/74785449/99824006-63b5b780-2b55-11eb-9f4f-f955edd0e9a1.png)

**Desktop (please complete the following information):**
- OS: iOS
 - Browser Chrome
 - Oxygen Version 3.6

**Comment by KittenCodes** [comment]
Duplicate: #725
