### ISSUE TITLE
Rich Text - Editing window is not full height

### ISSUE THREAD

**Issue by doefler** [soflyy/oxygen-bugs-and-features#173]
**Describe the bug**
*A clear and concise description of what the bug is.*

The editing area of Rich Text field doesn't expand to the full height of the editing modal.
Please see attached image.

This has happened with all websites I have made with Oxygen.

**Screenshots**
<img width="882" alt="Image 2019-03-19 at 1 56 17 PM" src="https://user-images.githubusercontent.com/7951337/54750662-bc8eb900-4bd8-11e9-9120-9799c9545159.png">

**Expected behavior**
*A clear and concise description of what you expected to happen.*

I would expect the Save and Close to be pushed to the bottom of the modal by expanding the actual text editing area.

**Desktop (please complete the following information):**
- OS: Mac OS
 - Browser: Chrome
 - Oxygen Version: All versions I have tried >2

**Comment by doefler** [comment]
Now I found another variation where it is heigher than the window:

<img width="880" alt="Screenshot 2019-03-21 at 18 36 26" src="https://user-images.githubusercontent.com/7951337/54772750-5a4dac80-4c08-11e9-9c2e-81bf120bfbe3.png">

**Comment by shock2d** [comment]
Have the same collapsed window as on 1st screenshot with 2.2.1, win, chrome

**Comment by Spellhammer** [comment]
I've witnessed this as well. You can click and drag the bottom right corner of the text area to resize it.

**Comment by KittenCodes** [comment]
@doefler, this should be fixed in the latest release of Oxygen. If you still have problems, please let me know.
