### ISSUE TITLE
Change CSS ID issue?

### ISSUE THREAD

**Issue by lemon6809** [soflyy/oxygen-bugs-and-features#1730]
Why can’t I edit the CSS style after changing the ID name, and the previous CSS styles are also gone?

**Comment by KittenCodes** [comment]
@lemon6809 I can't replicate this in v3.6. If the issue is still occurring on your site, please open a support ticket: https://oxygenbuilder.com/support.

**Comment by lemon6809** [comment]
@KittenCodes I can reproduce this problem using the environment you provided
<img width="722" alt="截圖 2020-11-22 下午8 04 00" src="https://user-images.githubusercontent.com/43395483/99903240-250f3100-2cfe-11eb-800f-fe4acee6def8.png">

**Comment by KittenCodes** [comment]
@lemon6809 Please record a video showing the steps you're taking.

Here's a video showing what I'm doing: https://www.loom.com/share/5f82ee27731e4244858513f1be608e7a.

**Comment by lemon6809** [comment]
I know why, the CSS ID cannot be named after a number.
