### ISSUE TITLE
I found 2 bugs...

### ISSUE THREAD

**Issue by MYIG** [soflyy/oxygen-bugs-and-features#1733]
My english is bad...

![script error in oxygen by ajax search pro](https://user-images.githubusercontent.com/44285360/99906472-b42a4200-2d1a-11eb-90b7-a1d2f87a5034.jpg)

When I use 'ajax search pro' plugin, it has 'script error'...

![Lightspeed cache error in Oxygen](https://user-images.githubusercontent.com/44285360/99906466-ac6a9d80-2d1a-11eb-887b-2a545e306705.jpg)

![Lightspeed error 2](https://user-images.githubusercontent.com/44285360/99906753-264f5680-2d1c-11eb-8172-0aef3fb47e36.jpg)

And 'LiteSpeed cache' makes it...

I test it in troubleshoot mode by 'health check' plugin. and I don't think litespeed cache is bad plugin... but I don't know why;;

**Comment by KittenCodes** [comment]
@MYIG Please run a plugin conflict test: https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/.

If the issue occurs when Oxygen is the only active plugin on the site, please open a support ticket: https://oxygenbuilder.com/support.

**Comment by SimonErich** [comment]
https://github.com/soflyy/oxygen-bugs-and-features/issues/1077#issuecomment-799178920
