### ISSUE TITLE
Blank Woocommerce Single Product Page 

### ISSUE THREAD

**Issue by hallo7am** [soflyy/oxygen-bugs-and-features#1735]
**Describe the bug**

- Multisite Network Setup
- A main Site + A subsite 
- Cannot load the Woocommerce single product page for the Subsite, the page is blank (No problem to show the Woocommerce single product page for the main site)

*A clear and concise description of what the bug is.*

- Blank Woocommerce Single Product Page for the subsite under multisite network setup.

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
*Yes/No*

- Yes

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**

- Yes

*If yes, provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*

https://oxygen-q7vqhca4q9g7.oxygen-demo.qsandbox.me/en/product/testing-product/

account name: demo
password: 123456

**To Reproduce**

1. Go to Sandbox and create mulsite network (download the file manager plugin and WP Htaccess Editor plugin to create the multisite network)

2. Create a subsite called 'mydomain.com/en'

3. Download Woocmmerce plugin and create a simple product in the subsite

4. View the product and you will see error. The page is blank.

**Expected behavior**

*A clear and concise description of what you expected to happen.*

- Display the product page properly

**What actually happens**
*A clear and concise description of what happens instead of the expected behavior.*

**Screenshots**
*If applicable, add screenshots to help explain your problem.*

- Screenshots explaining the problem

[https://e.pcloud.link/publink/show?code=kZReL7ZD7sVpNgLSiJArVot8vOouRILibNV](url)

**Desktop (please complete the following information):**
 - Browser [e.g. chrome, safari] : Chrome
 - Oxygen Version [e.g. 2.2 Alpha] : 3.61

**Smartphone (please complete the following information):**
 - Oxygen Version [e.g. 2.2 Alpha]

**Additional context**
*Add any other context about the problem here.*

**Comment by KittenCodes** [comment]
@hallo7am 

The sub-site didn't contain any templates - the templates need to be created on the sub-site to be able to display any content. I've created a Product template for you and the product data is now showing.

**Comment by hallo7am** [comment]
@KittenCodes  Thank you! It works!
