### ISSUE TITLE
Add tips where users can share solutions 

### ISSUE THREAD

**Issue by eric7186** [soflyy/oxygen-bugs-and-features#1737]
**When I finally resolve some issue, I want to share the solution with others.**
*A FAQ page with Search that allows registered users to quickly document a solution*

**When a user gets an error but the Trouble Shooting message is not helpful**
*Would like to add the solution to that Trouble Shooting web page*

**After my hosting added a Web Application Firewall, I couldn't save anything edited with Oxygen.**
*The error 403 message brought up a Trouble Shooting page but did not have any helpful information*
*The solution was to just add my computer IP address to the host's WAF settings*
*This info could save someone days of hair pulling frustration*

**Comment by KittenCodes** [comment]
You can do this in the Oxygen Community: https://github.com/soflyy/oxygen-community/discussions.
