### ISSUE TITLE
When activating Oxygen, Error 500

### ISSUE THREAD

**Issue by cavesa10** [soflyy/oxygen-bugs-and-features#174]
Install a Windows subsystem (Ubuntu), I followed this installation guide:
[https://hellojason.net/blog/how-to-setup-wordpress-locally-on-windows-subsystem-for-linux/](url)

I have installed the Oxygen plugin but when I activate it, it launches this error

(WP_Debug_Log)
`Fatal error: Uncaught Error: Call to undefined function simplexml_load_string() in /mnt/c/Sites/wordpress/wp-content/plugins/oxygen/component-framework/component-init.php:375 Stack trace: #0 /mnt/c/Sites/wordpress/wp-includes/class-wp-hook.php(286): ct_plugin_setup('') #1 /mnt/c/Sites/wordpress/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array) #2 /mnt/c/Sites/wordpress/wp-includes/plugin.php(465): WP_Hook->do_action(Array) #3 /mnt/c/Sites/wordpress/wp-admin/admin.php(169): do_action('admin_init') #4 /mnt/c/Sites/wordpress/wp-admin/plugins.php(10): require_once('/mnt/c/Sites/wo...') #5 {main} thrown in /mnt/c/Sites/wordpress/wp-content/plugins/oxygen/component-framework/component-init.php on line 375`

**Desktop (please complete the following information):**
- OS: Windows 10 Pro 64 bits WSL (ubuntu), 
 - Browser Chrome
 - Oxygen Version: 2.2.1

**Comment by Spellhammer** [comment]
You have to install the XML module: https://stackoverflow.com/questions/31206186/call-to-undefined-function-simplexml-load-string.
