### ISSUE TITLE
After changing the ID name, the previous CSS styles are gone?

### ISSUE THREAD

**Issue by lemon6809** [soflyy/oxygen-bugs-and-features#1740]
Why can’t I edit the CSS style after changing the ID name, and the previous CSS styles are also gone?
I reproduce this problem using the environment you provided.
<img width="722" alt="99903240-250f3100-2cfe-11eb-800f-fe4acee6def8" src="https://user-images.githubusercontent.com/43395483/100096584-2e7fd100-2e97-11eb-9359-87d24c9d9016.png">

**Comment by KittenCodes** [comment]
Duplicate: https://github.com/soflyy/oxygen-bugs-and-features/issues/1730#issuecomment-731737650 - please wait for us to reply to the original bug report.
