### ISSUE TITLE
Podcast- Mp3-

### ISSUE THREAD

**Issue by pezjr** [soflyy/oxygen-bugs-and-features#1745]
I would like to see Oxygen builder have a feature for podcast-audio-mp3.
all they have is sound cloud not every body use sound cloud.
When I first bought Oxygen builder it add a audio modal . Then they took it out.
I have ask several times to nothing.
Not very one uses website for sales.

**Comment by KittenCodes** [comment]
Duplicate: https://github.com/soflyy/oxygen-bugs-and-features/issues/836
