### ISSUE TITLE
Enable srcset attribute for images with data

### ISSUE THREAD

**Issue by katsar0v** [soflyy/oxygen-bugs-and-features#1746]
**Describe the feature you'd like to see included in Oxygen.**
On this page: https://oxygenbuilder.com/documentation/other/performance-optimization-options/ you demonstrate the srcset optimization which works pretty good, but it does **not** work on images with data:

![image](https://user-images.githubusercontent.com/7236157/100482528-faefb180-30f7-11eb-9195-8f8c22502838.png) 

**What are the use cases for this feature?**
Well the use cases are a lot, actually more than the use cases this feature was first made for - static image insert. I believe dynamic image insertion with srcset would be awesome

**Examples of this feature or functionality.**
There is no need I guess

**Comment by KittenCodes** [comment]
Duplicate: https://github.com/soflyy/oxygen-bugs-and-features/issues/107

**Comment by katsar0v** [comment]
@KittenCodes it is good that this is a duplicate, what is not good is that Oxygen **do not** react...
