### ISSUE TITLE
CSS !important-attribute causes trouble in header

### ISSUE THREAD

**Issue by jason-schell** [soflyy/oxygen-bugs-and-features#1748]
**Describe the bug**
Using the Header Builder with Sticky and Overlay-attributes "always", causes the css background-color property to be set to "initial !important". Therefore it is not possible to set another background color in the settings pane, nor with custom css.

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
Yes

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
https://oxygen-qmvvcxfn79ccl.oxygen-demo.qsandbox.me/
My webpage is https://webdesign-schell.de/

**To Reproduce**
1. Add Header Builder
2. Activate Sticky and Overlay
3. Change background-color

**Expected behavior**
No !important attribute on the css property "background-color" by Oxygen.

**What actually happens**
Oxygen adds !important to "background-color: initial" when sticky and overlay is activated.

**Screenshots**
![image](https://user-images.githubusercontent.com/44125163/100586409-664fa400-32ef-11eb-9e75-7c505fa2482b.png)

**Desktop and Smartphone:**
- OS: Windows 10 & iOS 14.2
 - Chrome, Safari (both desktop and mobile)
 - Oxygen Version [the latest]

**Comment by KittenCodes** [comment]
https://github.com/soflyy/oxygen-bugs-and-features/issues/479

**Comment by Cedric-M** [comment]
We are in 2024 and issue still hasn't been resolved, I am facing this exact same problem with the exact same `background-color: initial !important;` code
