### ISSUE TITLE
(2.3 Alpha) Modal keeps disappearing in builder.

### ISSUE THREAD

**Issue by wplit** [soflyy/oxygen-bugs-and-features#175]
**Describe the bug**
Modal being very unpredictable. Sometimes doesn't appear in builder even though it appears on front end and also can see it inside the structure panel.

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
Yes, it happened exactly the same as soon as I tried it - 

[sandbox demo](http://expensive-falcon.w5.wpsandbox.pro/)

The text is the trigger for the modal. It works find on the front. The modal is not visible in the builder, so cannot style it.

**Expected behavior**
Should see modal as long as 'Hidden' isn't selected.

**What actually happens**
Is hidden anyway.

**Screenshots**
Go into the sandbox demo

**Desktop (please complete the following information):**
- MacOS: 10.14.3
 - Browser [Chrome 72.0.3626.121]
 - Oxygen Version [2.3 Alpha]

**Additional context**
Sometimes the opposite happens. The modal is always in inline mode when I try to save. I press hidden and it goes away, then I save everything and it immediately returns to inline. Couldn't reproduce this though, could be another cause.

**Comment by KittenCodes** [comment]
@wplit Are you still having this issue in the latest version of Oxygen?
