### ISSUE TITLE
Lazy load images and video

### ISSUE THREAD

**Issue by marcchehab** [soflyy/oxygen-bugs-and-features#1755]
Many users like myself switch to Oxygen because of the page speed. You could improve that loads by having a lazy load functionality for images and videos. That is: Images and videos load dynamically once they're displayed or about to be displayed. Or videos (e.g. Youtube embeds) are only loaded when users click on them. That way a video is just a thumbnail and a play button.

There are existing plugins, but many don't seem to work with Oxygen Builder.

**Comment by joelnewcomer** [comment]
+1

**Comment by YammYcoding** [comment]
+1

**Comment by KittenCodes** [comment]
Duplicate: https://github.com/soflyy/oxygen-bugs-and-features/issues/163
