### ISSUE TITLE
Slow to load" issue 

### ISSUE THREAD

**Issue by Damdo74** [soflyy/oxygen-bugs-and-features#1758]
**Describe the bug**
I'm a pretty new user of Oxygen & i've been only using it on one website so far BUT I find it very slow to load when clicking on EDIT WITH OXYGEN.
It takes more than 30 sec sometimes to open the edit window.

I was wonderint is other users encounter that "slow to load" issue & if you could provide me with hints on how to solve it.

I'm willing to grant you access to my website so that you can better see what i'm taking about.

I'm using OVH hosting 

Finallyn here is an example of how long it takes to open edit mode
**Screenshots**
https://drive.google.com/file/d/12KlkA19PRrbdAbLBSFvhQ_3Y_yIFBLpT/view

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
*Yes*

![Capture d’écran 2020-12-04 à 13 21 35](https://user-images.githubusercontent.com/68645122/101163229-a7b7ba80-3633-11eb-9580-b839c10302ff.png)

**Comment by inferno-adam** [comment]
I'm guessing you're using Google Chrome because this has been an issue with Oxygen Builder + Google Chrome for ages and has yet to be addressed that I could find. Firefox loads it much faster, but that is just a workaround and not a solution.

**Comment by KittenCodes** [comment]
@Damdo74 Please open a support ticket so that we can take a look at your site: https://oxygenbuilder.com/support.
