### ISSUE TITLE
Woocommerce thumbnails display vertically 

### ISSUE THREAD

**Issue by mack32uk** [soflyy/oxygen-bugs-and-features#1763]
Hi

When you add images/thumbnails to the product image they display vertically not horizontally despite changing settings to horizontally on the woocommerce 'product images' option. The default product builder display fine however?

Reproduced also on the sandbox:

ttps://oxygen-qn96yv97twh7.oxygen-demo.qsandbox.me/product/test2/

Using latest version of WordPress & Oxygen and all apps tried with Php 7.3 and 7.4

Thanks

Kirk
![Capture2](https://user-images.githubusercontent.com/18194437/101363556-73ddce80-3899-11eb-9712-3b78fa887e9b.JPG)

**Comment by KittenCodes** [comment]
@mack32uk You need to add the Product Builder to your design - please see the structure on the Sandbox site to see how it needs to be done.

Screenshot: https://d.pr/i/rILcNZ.
