### ISSUE TITLE
Dynamic Color binding

### ISSUE THREAD

**Issue by siniradam** [soflyy/oxygen-bugs-and-features#1767]
I'm using Custom Post Type UI 1.8.1, and I added a color variable for my custom post type.
I want to change the header/section background color based on this variable. Fetching variables for colors would be useful in my case. As far as I can see, this option works with background images, but does not work with colors.

**Comment by YammYcoding** [comment]
+1

**Comment by siniradam** [comment]
Workaround is adding this codeblock;
<?php
	$customFields = get_post_custom();
echo "<style>.pHeader{color:".$customFields['producer_text_color'][0].";background-color:".$customFields['producer_color'][0]."}</style>";
?>

**Comment by YammYcoding** [comment]
i hope it gets added natively

**Comment by KittenCodes** [comment]
#1534

**Comment by silvenna** [comment]
+1
