### ISSUE TITLE
Elements options disappear Wordpress 5.6

### ISSUE THREAD

**Issue by SekSion** [soflyy/oxygen-bugs-and-features#1769]
**Describe the bug**
*A clear and concise description of what the bug is.*
On Oxygen builder the options for elements for example to duplicate or render a block have disappeared with wordpress newest update to 5.6 of wordpress

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
*Yes/No*

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
*If yes, provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*
http://proud-shark.w5.wpsandbox.pro/sample-page/?ct_builder=true

**To Reproduce**

**Expected behavior**
*A clear and concise description of what you expected to happen.*

**What actually happens**
*A clear and concise description of what happens instead of the expected behavior.*
![image](https://user-images.githubusercontent.com/46030872/101647536-be458380-3a30-11eb-8372-69979b38c441.png)

**Desktop (please complete the following information):**
 - Oxygen Version [e.g. 2.2 Alpha]

**Smartphone (please complete the following information):**
 - Oxygen Version [e.g. 2.2 Alpha]

**Additional context**
*Add any other context about the problem here.*
updateed to 5.6 wordpress and tried the JQuery migrate enabled and disabled.

**Comment by SekSion** [comment]
temporary solution downgrade to 5.5.3 version

**Comment by peterquentin** [comment]
@SekSion I have installed WP 5.6 and use oxygen builder 3.6.1
When I hover an element in the structure pane I do get the options menu and delete option:

![image](https://user-images.githubusercontent.com/1672096/101698240-772fb080-3a79-11eb-982e-c75778a2d4cd.png)

What version of oxygen are you using?

**Comment by SekSion** [comment]
uff, its 3.5, i need to try with 3.6, is the blank install on oxygen/try also 3.5 ?

**Comment by SekSion** [comment]
just noticed i didint post correct link
http://proud-shark.w5.wpsandbox.pro?upass=Xrs69A0AvhH7

**Comment by SekSion** [comment]
on the try with oxygen 3.6 also doenst show the options maybe 3.6.1 is fixing that but its not official yet :/

**Comment by SekSion** [comment]
omg im so dumb, just noticed 3.7.1 is the one not available, i didint had 3.6.1installed, my bad let me retry with that

**Comment by peterquentin** [comment]
@SekSion I tried your version and it does not work indeed.
But the good news is, it works on 3.6.1 which means when it is official it's fixed.

PS: I haven't run into any issues using 3.6.1, so you might want to give that one a spin.

**Comment by peterquentin** [comment]
@SekSion Ah I was in the middle of replying, alright come back to me when you've tried it out!

**Comment by SekSion** [comment]
@peterquentin it does work my bad close
