### ISSUE TITLE
Pro-menu dropdowns don't hide on Safari

### ISSUE THREAD

**Issue by hamish-strachan** [soflyy/oxygen-bugs-and-features#1771]
**Describe the bug**
When viewing my site with Safari (Version 13.0.4 on Mac OS 10.14.6) the dropdowns on a pro-menu are visible before mouse-over.

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
*Yes*

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**

YES: https://oxygen-qk7yd6t5npjcl.oxygen-demo.qsandbox.me/hello-world/

**To Reproduce**
Steps to reproduce the behavior: Just view the above link in Safari

**Expected behavior**

Dropdowns hidden before mouse-over.

**What actually happens**
dropdowns on a pro-menu are visible before mouse-over.

**Screenshots**

[https://www.dropbox.com/s/cv27luq70nh3wp4/Screenshot%202020-12-10%20at%2009.17.55.png?dl=0](url)

[https://www.dropbox.com/s/h0wkq2hgyhfy5h2/Screenshot%202020-12-10%20at%2009.23.15.png?dl=0](url)

**Desktop (please complete the following information):**
- OS: Mac OS 10.14.6
 - Browser  Safari Version 13.0.4 
 - Oxygen Version 3.6.1

**Comment by KittenCodes** [comment]
@hamish-strachan 

Please add the following CSS to a stylesheet via Manage > Stylesheets in the top right of the builder to prevent the menus from showing before they animate:

```css
.menu-item-has-children .sub-menu:not(.aos-animate) {
opacity: 0;
}
```

**Comment by KittenCodes** [comment]
Duplicate: https://github.com/soflyy/oxygen-bugs-and-features/issues/1298
