### ISSUE TITLE
Edit Only access not available even after removing & adding Oxygen License

### ISSUE THREAD

**Issue by dubpir8** [soflyy/oxygen-bugs-and-features#1778]
Cannot provide users Edit Only access to Oxygen

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
Yes

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
No

**To Reproduce**
1. Go to 'Oxygen Settings'
2. Click on 'Client Control'
3. Click on Access drop-down for any role
Only No Access and Full Access are available

**Expected behavior**
Edit Only option should be available

**What actually happens**
Only No Access and Full Access are available

**Desktop (please complete the following information):**
- OS: Windows 10
 - Browser FireFox
 - Oxygen Version 3.6.1 

We had the same issue on another site, but managed to fix it by removing our Oxygen License key and adding it again. We have tried the same thing for the website we are currently working on to no avail and need to release it to the client with Edit Only access, but cannot at this time due to this issue.

Thank you

**Comment by KittenCodes** [comment]
@dubpir8 Please open a support ticket so that we can take a look at your site: https://oxygenbuilder.com/support.

**Comment by dubpir8** [comment]
Thanks. Have submitted a support ticket
