### ISSUE TITLE
One Category or Tag Template

### ISSUE THREAD

**Issue by carmescl** [soflyy/oxygen-bugs-and-features#1779]
**Describe the feature you'd like to see included in Oxygen.**

Wordpress already has a default category template which automatically displays the posts per category in each category page.

In Oxygen, currently, we have to manually create each category template by querying the posts per category using the Easy Posts element, which will then display the posts in the category page. Please correct me if I'm wrong.
Now this is not ideal if we have a lot of categories.
Is there any way in Oxygen that we can create only ONE category template that will be used for ALL category pages? 

Thanks

**Comment by KittenCodes** [comment]
> Is there any way in Oxygen that we can create only ONE category template that will be used for ALL category pages?

Yes, create a template and assign it to Archive > Taxonomies > All Categories. Add an Easy Posts element to the template and leave the query set to Default. WordPress will then be able to retrieve the correct posts based on the URL in the browser.

**Comment by carmescl** [comment]
Hi, thanks. I had tried that before and it displays the default blog entries for all category pages, even after assigning a template priority of 1.
Please see category pages below. (I could not find any option to set this comment/reply as private)
https://moneylendingexpert.com/site/category/advice/
https://moneylendingexpert.com/site/category/credit-cards/
https://moneylendingexpert.com/site/category/equity-release/

**Comment by KittenCodes** [comment]
@carmescl 

> I had tried that before and it displays the default blog entries for all category pages, even after assigning a template priority of 1

Please ensure you are using the Default query in your Easy Posts element. If that doesn't work for you, please open a support ticket so that we can take a look at your site: https://oxygenbuilder.com/support.

**Comment by Chosebow** [comment]
Hello! In my case everything works properly, but a little detail. In the template page-title, I put a text that announce that you are in an "X" category page archive. I put a standard text "Category [dinamic data] posts" (by clicking in some category widget item, in the blog sidebar, for example). Every thing work fine, but I cant print only the cagory I've asking for. the dinamic data flield shows another categorys beside. Do you know how can I print only the the category that appears in the permalink, that is the category I've asking for? Thnks!
https://www.inkfusion.es/desarrollo/europalegal/category/intercambio-en-espana/
