### ISSUE TITLE
wrap with div & element unexpectedly moves to previous position in structure

### ISSUE THREAD

**Issue by shock2d** [soflyy/oxygen-bugs-and-features#178]
**Describe the bug**
If I'm trying to wrap element that being moved before wrapping it's being moved to previous positions along being wrapped.

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
*Yes/No*

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
http://intuitive-mamba.w6.wpsandbox.pro/ct_template/main/?ct_builder=true

**To Reproduce**
1. Go to templates, create a new empty one
2. Add a column element with 2 columns
3. Add one div inside the first column + add text line inside that div.
4. move text line outside column element
5. wrap that line with a div

**Expected behavior**
Text line staying outside the column element and being wrapped

**What actually happens**
The text line is being moved to her previous position.

**Screenshots**
https://i.imgur.com/jQLvzay.png

**Desktop (please complete the following information):**
win, chrome, 2.2.1

**Comment by KittenCodes** [comment]
@shock2d I'm not able to replicate this in the latest version of Oxygen. If you're still having problems, please open a support ticket by emailing support@oxygenbuilder.com.
