### ISSUE TITLE
Repeater with Grid Pagination it's own child element

### ISSUE THREAD

**Issue by pascalinger** [soflyy/oxygen-bugs-and-features#1780]
**Describe the bug**
When using the "grid layout" option with a repeater, the pagination becomes its own child, which then results in some issues. For example, when using a three-column layout with 6 items, the pagination is the 7th element which results in a new (empty) row.

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
Yup.

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
Nope

**Screenshots**
*If applicable, add screenshots to help explain your problem.*
![image](https://user-images.githubusercontent.com/19683229/102207909-00f2da00-3ecf-11eb-86ef-0515562c791d.png)

**Desktop (please complete the following information):**
- OS: MacOS
 - Browser: Edge Chromium
 - Oxygen Version: 3.7 Alpha

**Comment by YammYcoding** [comment]
+1

**Comment by Stannistor** [comment]
+1

**Comment by Spellhammer** [comment]
You can fix this by ensuring the last child of the Grid (the pagination) is on its own row with a column span matching the number of columns in the Grid layout, then unchecking this box: https://d.pr/i/E6FAmH.
