### ISSUE TITLE
Disable and Enable My Plugin and my Code

### ISSUE THREAD

**Issue by manish202532** [soflyy/oxygen-bugs-and-features#1783]
I am used Oxygen plugin for my wordpress site.

i have a question that if i will disable my plugin for some time like 10 to 15 mins and enabled my plugin after that. will it affect on my data store. means my data will remains as it is or will be vanished ?

Thank You

**Comment by KittenCodes** [comment]
@manish202532 Oxygen's data is stored in the database. You can disable or delete Oxygen without data loss. However, I would recommend taking a full backup of your site first so that you can roll it back if necessary.
