### ISSUE TITLE
Woocommerce category list does not filter parent=0

### ISSUE THREAD

**Issue by Lupul** [soflyy/oxygen-bugs-and-features#1788]
**Describe the bug**
Oxygen woocommerce category list component does not return first level of  wc categories when using `0` as parent value, sub categ are also shown.

Native shortcode is return proper results
`[product_categories parent="0" hide_empty="true" ]`

(The visual editor is showing correct results)

**Sandbox:** 
I could reproduce the issue on sandbox, Woocommerce was the only plugin installed
http://charming-mantis.w5.wpsandbox.pro/bugreport/

Woo Component settings:
![image](https://user-images.githubusercontent.com/3596864/102775097-e28c5300-4394-11eb-987a-064e2019a6f8.png)

**Comment by KittenCodes** [comment]
Duplicate: https://github.com/soflyy/oxygen-bugs-and-features/issues/1227

**Comment by Lupul** [comment]
Found the problem in `... /plugins/oxygen-woocommerce/elements/archive-categories.php`

This fixed the issue for me:
```diff
--- a/oxygen-woocommerce/elements/archive-categories.php
+++ b/oxygen-woocommerce/elements/archive-categories.php
@@ -46,7 +46,7 @@ class ArchiveCategories extends \OxyWooEl {
                $atts_string = '';
 
                foreach ($shortcode_props as $name => $value) {
-                       if ($value) {
+                       if ($value || is_numeric($value)) {
                                $atts_string .= ' '.$name.'='.$value;
                        }
                }
```
