### ISSUE TITLE
Woocommerce issue with Oxygen for woocommerce

### ISSUE THREAD

**Issue by smonsebjanic** [soflyy/oxygen-bugs-and-features#1789]
Hi, 

As of woocommerce 4.0 there seems to be something missing from the Oxygen for woocommerce plugin.

It seems to be a little thing as most things work but, like the default, WC product slider on a single product template is broken: 

- It lists slides as 1. 2. 3. and a are all in the column (except for the one that is currently in view)
- If you configure a variable product the change in which version of the product you are trying to look at doesn't change the image in the slider (the slider doesn't work for a variable, but it does if you slide to the next image manually ).  
- color integrations with swatches don't fix the issue for variable products.
- If you try to integrate a different slider for your woocommerce products that slider won't work. It appears as working but the slides won't slide. And of course, the variables still don't work.

I tried all of the above on a different theme and all of the above work with no problem. Meaning the swatches can be implemented and they will show the image of the variable product that you are trying to view.

It seems something changed in the new WC single product template in the code for slider and it doesn't integrate with the Oxygen for woocommerce.

This has forced me to change the theme for one of my projects.

Would it be possible to look into it and update the Oxygen for Woocommerce plugin?

Swatches plugin: Variation Swatches for WooCommerce

I can't show images as I had to delete the installation as the project's deadline is near.

**Comment by KittenCodes** [comment]
@smonsebjanic Had you included the Product Builder in your design? That is required for the Product Images to work correctly. The correct structure would look something like this:

```
Section
- Product Builder
- - Columns
- - - Div
- - - - Product Images
- - - Div
- - - - Product Title
- - - - Product Cart Button
- - Related Products
```

**Comment by smonsebjanic** [comment]
Thank you for your help. 

I messed up how I used the single product template.

It works now. I thought that I can just build with elements, without the product builder. I get it now how to do it.

Thank you so much, you just saved me a big headeache.
