### ISSUE TITLE
Library functionality is disabled if Selector Detector is enabled.

### ISSUE THREAD

**Issue by ivanjuras** [soflyy/oxygen-bugs-and-features#179]
**Describe the bug**

All checkboxes in the "Library" tab are disabled if Selector Detector is enabled.

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
Yes

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**

I've tried this on multiple installs, and it's the same thing.

**Expected behavior**

All checkboxes in the Library tab should stay intact.

**What actually happens**

If I enable selector detector, the Library functionality is turned off.

**Comment by ivanjuras** [comment]
I just checked, if anything is checked in the general tab, it will cancel out everything checked in the Library tab, and vice-versa.

**Comment by KittenCodes** [comment]
This is working correctly in the latest version of Oxygen.
