### ISSUE TITLE
Rewrite the slow back-end builder in Vue

### ISSUE THREAD

**Issue by Miguelklappes** [soflyy/oxygen-bugs-and-features#1791]
**Describe the feature you'd like to see included in Oxygen.**
I had a lot of time testing the builder and it works relatively well, but it is too slow as soon as you add custom fields or use WooCommerce. It's a real shame, because the beauty of Oxygen is found in beautiful sites such as Real Estate or e-commerce type.

**What are the use cases for this feature?**
Develop websites faster, reduce frustration due to "lags" inside the builder, get rid of the old Angular and start with a real framework

**Examples of this feature or functionality.**
Zion Builder PRO (or free) is a perfect example. The speed with which they implemented a lot of functions that Oxygen took years, in addition to being written in Vue, is unparalleled. Except the fact that I will always use Oxygen, since I am totally used to it and I really hope you can realize this fact, it is time for a rewrite in Vue.js.

**Comment by Markus992** [comment]
+1 PLEASE

**Comment by estraatios** [comment]
I was going to add the same issue. I am happy that there are other people that want that also.

**Comment by AlbertMarashi** [comment]
Svelte is pretty nice too

**Comment by Spellhammer** [comment]
I'm going to close this because I don't think any software company would consider "rewrite your entire software from the ground up using a different stack" as a feature request. Sorry everyone!
