### ISSUE TITLE
Lack of basic meta tag for mobile devices

### ISSUE THREAD

**Issue by janknop** [soflyy/oxygen-bugs-and-features#1792]
**Describe the bug**
Oxygen generated viewport tag is incorrect
meta name="viewport" content="width=device-width"

Correct meta tag should be:
meta name="viewport" content="width=device-width initial-scale=1.0"

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
*Yes*

You can see the bug here:https://www.77webz.com/CLIENTS/AT/
Display page on iPod and try changing orientation of the device. Unexpected margin appears on the right.

**Expected behavior**
On changing device orientation responsive design for iPod shoud reposition the elements.

**What actually happens**
On changing device orientation a weird margin on the right appears on right-hand side. Seems like reflow feature doesn't kick in. I believe it could be avoided if view port tag was correctly implemented.

**Screenshots**
![IMG_40E95A91B2CB-1](https://user-images.githubusercontent.com/76464361/102850603-d8477480-43e7-11eb-81b1-3fb9c3284fe7.jpeg)

Issue is clearly visible on iPods. Just try to change the orientation.

**Additional context**
This right margin is also a problem if a menu item with a drop down is to close to the right side. The menu even though hidden also creates overflow problem. 

The fix is to make submenu change to right:0; a bit faster when going into less than 1200px breakpoint.

**Comment by AlkoKod** [comment]
Please @louisreingold fix this, it is only this much of code to add: `initial-scale=1.0` ... Very annoying for iOS users to see that white gaps on oxygen sites everyday...

**Comment by d-packs** [comment]
I would add to this that because it is not possible to change the viewport metatag without changing oxygen code or filtering the whole output (which is extremely heavy), **the viewport meta tag should be editable via a filter**.

Yes it is possible to add additional viewport tags, but it is up to the browser to decide which tag to prioritise when finding duplicates, so this is not a solution.

**Comment by gslwebsolutions** [comment]
hope this gets fixed soon

**Comment by adrien-robert** [comment]
+1

**Comment by annettePixie** [comment]
+1

**Comment by netdoctor** [comment]
+1

**Comment by wpsumo** [comment]
Anyone found a solution to alter and inject `initial-scale=1.0` to the viewport tag?
`<meta name="viewport" content="width=device-width, initial-scale=1">`

**Comment by Spellhammer** [comment]
This has been added in Oxygen 4.0.
