### ISSUE TITLE
Border Data Not Shown Once Leaving The Element

### ISSUE THREAD

**Issue by j-ki** [soflyy/oxygen-bugs-and-features#1794]
**Describe the bug**
When I set a border for all sides, leave the block, and go back to the border, the border data isn't shown.

If I select one of the border sides (e.g. top, right, bottom, left), I see the border information.

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
*Yes*

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
*If yes, provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*

http://pleasant-newt.w6.wpsandbox.pro/2017/03/09/hello-world/?ct_builder=true

http://pleasant-newt.w6.wpsandbox.pro?upass=1fc36G4sLgYT

**To Reproduce**
1. Create a border around all sides of a block.
2. Leave the block
3. Go back to the same block and select border attribute

**Expected behavior**
*A clear and concise description of what you expected to happen.*
If I create a border around all sides, when I go back to the block, I expect the information (e.g. color, width, style) to be displayed under all sides.

**What actually happens**
When I go back to the block, the color and width of the border is not displayed. I have to select each of the sides to see the color and width.

**Screenshots**
N/A

**Desktop (please complete the following information):**
- OS: Windows
 - Browser: Firefox
 - Oxygen Version: 3.6.1

**Smartphone (please complete the following information):**
N/A

**Additional context**
I suspect this is happening because users may select custom borders for each side. Perhaps a good compromise would be to display the border information, if the user configured the same border for all sides.

However, if the user selected custom borders, the border section could be expanded to list the borders by sides:

top-border    #dddddd    2px
right-border    #e8e8e8    4px
bottom-border    #000    6px
left-border    #fff    8px

**Comment by KittenCodes** [comment]
> When I set a border for all sides, leave the block, and go back to the border, the border data isn't shown.
> If I select one of the border sides (e.g. top, right, bottom, left), I see the border information.

This isn't a bug. Please add a vote to the feature request here if you would like to see the border controls working differently: https://github.com/soflyy/oxygen-bugs-and-features/issues/1629.
