### ISSUE TITLE
Editor crashes server with &ct_inner=true

### ISSUE THREAD

**Issue by robellinternational** [soflyy/oxygen-bugs-and-features#1795]
**Since the latest updates we experience server crashes (503)** 

Setup:
Wordpress 5.6
WooCommerce 4.8.0
Oxygen 3.6.1
Oxygen Elements for WooCommerce 1.4

We have found this to be the problem:

When selecting 'Edit Template' from the Page or Product listing, this is the URL to edit templates:
https://website.name/?ct_template=book&ct_builder=true

The above works fine, no errors. Editing causes no problem.

But when opening a (product) page first and then clicking the large Oxygen "edit Template" button, this is passed:
https://website.name/?ct_template=book&ct_builder=true **&ct_inner=true**

It appears that **&ct_inner=true** is causing errors and a crashed server. The only difference is the last parameter.

As an example, the below errors are produced, but this varies. They are all caused by a non responsive server. These errors do not appear when editing without **&ct_inner=true** and therefore do not point to actual issues outside Oxygen.

<img width="248" alt="Screenshot 2020-12-22 at 18 23 44" src="https://user-images.githubusercontent.com/76540574/103045566-52f9c680-4585-11eb-9f02-60062b43f3d7.png">
<img width="251" alt="Screenshot 2020-12-13 at 02 40 42" src="https://user-images.githubusercontent.com/76540574/103045570-5725e400-4585-11eb-8467-fc2ae0c4461f.png">
<img width="249" alt="Screenshot 2020-12-22 at 18 23 36" src="https://user-images.githubusercontent.com/76540574/103045562-4d03e580-4585-11eb-82dc-a18623a6e534.png">

**Comment by KittenCodes** [comment]
@robellinternational We would need to take a look at your site to be able to help with this. Please open a support ticket: https://oxygenbuilder.com/support.
