### ISSUE TITLE
Oxygen after WP 5.6 update issues due to jQuery 3.5 update

### ISSUE THREAD

**Issue by tilen-seliskar** [soflyy/oxygen-bugs-and-features#1799]
**Editor issues when updating to WP 5.6**
*When opening editor in WP 5.6, multiple issues occur.*

At first glance, issues are:
- unexpected overlay of WP input fields (see attachment)
- unable to set colors
- Console errors logged

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
*Unable to reproduce as WP version in Sandbox is 5.5.3*

**To Reproduce**
1. Go to 'Edit with oxygen' (Any template)
2. Overlay of WP element is observed at load
3. Click on 'Color select'
4. Nothing happens

**Expected behavior**
*Expectation is that normal operation of Oxygen is supported when using jQuery 3.5*

**What actually happens**
*Well... editing with oxygen is very limited and even not possible for specific parts.*

**Screenshots**
https://mega.nz/folder/D5wBVYKK#GBsPs6lLXwYuoo-OOwkhyA

**Desktop (please complete the following information):**
- OS: Win10
 - Browser: Chrome Version 87.0.4280.88 (Official Build) (64-bit)
 - Oxygen Version 3.6.1

**Additional context**
*Currently a quick workaround is adding "Enable jQuery Migrate Helper" plugin and setting jQuery legacy version 1.12.4.*

**Comment by KittenCodes** [comment]
@tilen-seliskar Please open a support ticket so that we can take a look at your site: https://oxygenbuilder.com/support. You need to click "Something's broken and I need help".

**Comment by tilen-seliskar** [comment]
@KittenCodes , after additional investigation, I have discovered that this is in fact not an Oxygen issue. Errors were caused due to conflict with unrelated plugin - HappyFiles.

Apologize for any inconvenience.
