### ISSUE TITLE
3.7 bug: Dynamic Slider "fade" transition displays overlapping text

### ISSUE THREAD

**Issue by MayaNikolova** [soflyy/oxygen-bugs-and-features#1801]
**Describe the bug**
*Dynamic Slider is used and JS var transition = 'fade'; applied.  displays overlapping text*

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
*No*

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
*No as this is version 3.7*

**To Reproduce**
Insert the Dynamic slide widget, make sure that there is a text field with dynamic data pulled form the posts
1. Go to 'Dynamic Slider Code>JavaScript>'
2. Change JS var transition = 'fade'
3. Apply code and save
4. Open page in front end and see the overlapping text - text from sequential posts is visible albeit faded somewhat.

**Expected behavior**
Text from posts that are not displayed should not be visible

**What actually happens**
*When the post text is displayed on a slide you can see the overlapping text from sequential posts is visible albeit faded somewhat.

**Screenshots**
https://www.dropbox.com/s/nn1ib00zq89ymsc/overlapping%20text%203.7.JPG?dl=0 

**Desktop (please complete the following information):**
- OS: [Windows 10 Pro]
 - Browser Chrome
 - Oxygen Version [e.g. 3.7.1 Alpha 1]

**Comment by KittenCodes** [comment]
@MayaNikolova I've not been able to replicate this when using a dynamic post title.

I've installed v3.7 Alpha on the Sandbox site here: http://helpful-stork.w6.wpsandbox.pro?upass=xr4X8rV1mVN5. If you're able to replicate the issue, please send me a link to the page so that I can take a look.

**Comment by MayaNikolova** [comment]
Hi Soph,

 

Apologies for the late reply, this had gone int my Spam folder.

 

I see that in your installation it is showing correctly…on my page I still have the issue however. Anyway, possibly some sort of plugin conflict. 

This is what I see – the image is OK, however the writing is overlapping:

https://oxy1.naturevolution.net/sample-page/

 



I have the following structure in the repeater (all fields dynamically picked up from the posts):



 

And these plugins active:



 

I will investigate and let you know what I find.

 

Thanks

Maya

**Comment by MayaNikolova** [comment]
Actually Soph – I have replicated it on your sample page, so have a look at this and you can see the overlapping text:

 

http://helpful-stork.w6.wpsandbox.pro/sample-page/

 



 

Hope this helps and ignore my page example below. I will in fact delete this from my installation.

 

Cheers

Maya

 

From: maya.nikolov1966@gmail.com <maya.nikolov1966@gmail.com> 
Sent: Friday, 15 January 2021 10:40 AM
To: 'soflyy/oxygen-bugs-and-features' <reply@reply.github.com>
Subject: RE: [soflyy/oxygen-bugs-and-features] 3.7 bug: Dynamic Slider "fade" transition displays overlapping text (#1801)

 

Hi Soph,

 

Apologies for the late reply, this had gone int my Spam folder.

 

I see that in your installation it is showing correctly…on my page I still have the issue however. Anyway, possibly some sort of plugin conflict. 

This is what I see – the image is OK, however the writing is overlapping:

https://oxy1.naturevolution.net/sample-page/

 



I have the following structure in the repeater (all fields dynamically picked up from the posts):



 

And these plugins active:



 

I will investigate and let you know what I find.

 

Thanks

Maya

**Comment by KittenCodes** [comment]
Hi Maya,

Thank you for the link to the Sandbox site.

The reason this is happening is that you've set a semi-transparent colour as the Side background colour. If it's semi-transparent, you can see the content from the other slides that are behind it, which is why the overlapping effect shows.

I've set the slide background colour to the equivalent solid colour and the overlap no longer occurs.
