### ISSUE TITLE
Upgrade to normalize.css 8.0

### ISSUE THREAD

**Issue by davidmles** [soflyy/oxygen-bugs-and-features#1806]
The final CSS generated by Oxygen includes normalize.css 7.0

Would it be possible to upgrade to the latest 8.0.1 version? It's 2 years old, it should be safe.

https://github.com/necolas/normalize.css/blob/master/CHANGELOG.md

Thanks.

**Comment by Spellhammer** [comment]
@davidmles Which changes in 8.0/8.0.1 do you find yourself missing?

**Comment by davidmles** [comment]
Nothing that I especially need. But it looks like a cleaning up upgrade, since it removes support for very old browsers.

It has an interesting new feature though, that look like a little fix: font family inheriting for forms.

**Comment by Spellhammer** [comment]
> It has an interesting new feature though, that look like a little fix: font family inheriting for forms.

Yes, that would definitely be handy.
