### ISSUE TITLE
valid  JS var = QuerySelector returns null 

### ISSUE THREAD

**Issue by thekerbey** [soflyy/oxygen-bugs-and-features#1807]
**Describe the bug**
*A clear and concise description of what the bug is.*

I am trying to create a variable of the ordered list element within the woocommerce product builder image block.

For simplicity 

`var container = document.querySelector("#product-22 > div.woocommerce-product-gallery.woocommerce-product-gallery--with-images.woocommerce-product-gallery--columns-4.images > ol")`

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
*Yes/No*

Yes

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
*If yes, provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*

https://oxygen-qjlhfbqp4ptcl.oxygen-demo.qsandbox.me/?ct_template=1&ct_builder=true
https://oxygen-qjlhfbqp4ptcl.oxygen-demo.qsandbox.me/product/1/

**To Reproduce**
1. install woocommerce
2. create woocommerce product
3. add product images and featured image
4. name product
5. publish product
4. create an oxygen template
5. select 'products' in 'where does this template apply'  
6. name the template
7. add the 'woocommerce product builder' to the template.
8. save the template
8. open the product page
9. inspect the product page
10. find the ol.flex-control.flex-control-thumbs element that contains the product image thumbnails
11. hover over and right click the element from step 10.
12. click: copy ->  copy JS path 
12. go back to the aforementioned oxygen template 
13. click add code block
14. select javascript
15. within the text box that appears, type 'var container = (paste the JS path from step 10)'
16. click apply code
16. save the template
18. reload the product page on the front end
19. inspect the page
20. open the console
21. type 'container' in the console
22. console returns null

**Expected behavior**
entering 'container' in the console should return:
`<ol class="flex-control-nav flex-control-thumbs">` 

*A clear and concise description of what you expected to happen.*

**What actually happens**
*A clear and concise description of what happens instead of the expected behavior.*

entering 'container' in the console returns:
`null`

**Screenshots**
*If applicable, add screenshots to help explain your problem.*

Oxygen code block input - step 15:

![494abf31a087f93f96ad952ef2c303e0 1](https://user-images.githubusercontent.com/7947153/103389163-30aefe00-4adb-11eb-85fa-a66b1a1207e6.png)

Final steps, container returns null:

![fd5447647cca2c878f0389b776af6f1f 1](https://user-images.githubusercontent.com/7947153/103389176-46242800-4adb-11eb-8a3d-38416fb228f5.png)

After inputting the same variable from the code block in step 15, container returns the 'ol' element as desired, therefore I presume there is nothing wrong with the JS or the variable. 

![07711d35d6e7c90781aca13340893f4e 1](https://user-images.githubusercontent.com/7947153/103389213-8be0f080-4adb-11eb-95f8-ad7f9e929c55.png)

Copying JS path from the aforementioned 'ol' element - step 12:

![66f36d722c977252896b140a0f9e1c98 1](https://user-images.githubusercontent.com/7947153/103389258-c21e7000-4adb-11eb-9fbf-93d4de824704.gif)

**Desktop (please complete the following information):**

Windows 10
Yandex Browser (chrome) - 12/30/2020
Oxygen 3.6.1

**Smartphone (please complete the following information):**
N/A

**Additional context**
*Add any other context about the problem here.*

I would like to customize the thumbnails to function more like an infinite slide, I am not content with the current styling of oxygens defaults. I dont like the numbers appearing next to the woocommerce thumbnail. I would like it to scroll cleanly - not like a separate collage of images with numbers. I plan to remove the overflow, add arrows, infinite scrolling...etc.  more clean. i was hoping i could do this with js in oxygen, but oxygen seems to be giving me problems... I thought about the time of the JS, maybe the code is running before he element exists, maybe I could select the OL by using the oxygen %%this element%% ol, but im not sure if i can select the ol like this.

**Comment by KittenCodes** [comment]
@thekerbey If you add the following to the Code Block element then the correct element is returned:

```
console.log(container);
```

Do you need to be able to access the variable from the console on the front-end of the site, or do you just need to access it from a Code Block?

**Comment by thekerbey** [comment]
Im not seeing that, console.log still returns null for me.

Anyways, I am not sure if the flexslider is broken, or it is meant to have numbers in the thumbnails, it doesnt look right to me.
Consequently, I thought of experimenting with making my own slider of the thumbnails with left and right arrows.
I wanted to do this with something like this:


```
var ol = "#product-22 > div.woocommerce-product-gallery.woocommerce-product-gallery--with-images.woocommerce-product-gallery--columns-4.images > ol"

var container = document.querySelector(ol)

var thumbnails = Array.from(document.querySelectorAll(ol+"> li"))


function thumbnailSlide(ol, li) {
    ol.scrollLeft = li.offsetLeft}

for (i = 0; i < thumbnails.length; i++) { 
thumbnails[i].setAttribute('onclick','thumbnailSlide(container,thumbnails['+i+'])')}
```
My goal is to get a slider that is comparable to this slider here for the image thumbnails.

https://ktcollection.com/product/seven-way-large-necklace/

**Comment by thekerbey** [comment]
This works:

`window.addEventListener('load', (event) => {
  var container = document.querySelector("#-product-images-7-70 > div > ol")
  console.log(container)

});`

**Comment by KittenCodes** [comment]
> This works

Excellent, thank you for letting me know!
