### ISSUE TITLE
Flexbox Gap

### ISSUE THREAD

**Issue by KittenCodes** [soflyy/oxygen-bugs-and-features#1811]
Posted by @cmbibby

Would be great to have support for the Flexbox Gap property.

**Comment by guyinpv** [comment]
Crazy that this issue is only 11 hours old. I just needed this right now and didn't see any option for the gap!

Of course it's easy to add it under Advanced->Custom CSS, but still, it's a kind of an important option for flex box items!

**Comment by andreslotta** [comment]
Would be great to see this in Oxygen now that it finally made its way into Safari and thus is supported by all major browsers. See https://caniuse.com/?search=flexbox%20gap.

**Comment by bohdanps** [comment]
Now in 2021 flexbox gap property is supported by all major browsers so it would be a great feature to add :)

**Comment by AztecInternet** [comment]
+1 

I'd love to see this added to 4.0 too 👍

**Comment by royby** [comment]
+1

**Comment by 1nf0t3ch** [comment]
+1

**Comment by adrien-robert** [comment]
+1

**Comment by renpub** [comment]
+1

**Comment by perrelet** [comment]
+1

**Comment by Flipback8** [comment]
+1

**Comment by tmz1970** [comment]
+1

**Comment by uhlhosting** [comment]
+1

**Comment by d19dotca** [comment]
Looks like this was added as part of 4.0: https://oxygenbuilder.com/2022/04/01/oxygen-4-0-beta-2-now-available/

**Comment by Flipback8** [comment]
Yes, this topic may no be closed.
