### ISSUE TITLE
Header overlaps inner section

### ISSUE THREAD

**Issue by repulesc** [soflyy/oxygen-bugs-and-features#1813]
Header section overlaps inner section despite the Z-index settings on header:1 inner section: 10. It works fine in the oxygen editor window but doesn't work on my live demo website: http://obedient-walrus.w6.wpsandbox.pro/

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
No

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
*If yes, provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*

**To Reproduce**

**Expected behavior**
I expect the gallery work above the header section.

**What actually happens**
The invisible header section overlaps the gallery images on the live site.

**Screenshots**
You can inspect it here: http://obedient-walrus.w6.wpsandbox.pro

**Desktop (please complete the following information):**
- OS: Mac OS Bug Fur
 - Browser Safari
 - Oxygen Version: demo version

**Additional context**
Thanks for your support.

**Comment by KittenCodes** [comment]
@repulesc Please can you add a screenshot showing what the problem is? I've taken a look at the site, but the issue isn't clear to me.

**Comment by repulesc** [comment]
Yes,

https://imgur.com/1sKEdET

I've taken a screenshot of the editor where one of the invisible header row is. I'm not sure if "inner section" can be adjusted to overlap "header builder" as I've tried by setting z-index numbers. The problem is, i suppose the invisible header row covers the inner section and gallery as the images won't respond to click and mouse hover. Cheers!

**Comment by KittenCodes** [comment]
Thank you.

It's not advisable to use the Header Builder in the layout you're trying to design - the Header Builder is intended for use at the top of the page only.

I've adjusted your Main template to use a Columns element instead of the Header Builder and all of the Gallery items can now be clicked correctly.

Please take a look and let me know if anything isn't clear.

**Comment by repulesc** [comment]
Thank you, it works perfect this way. Problem is solved.
The vertical header function is rather neglected, although there is a demand for it. I am in one person. : D
Thanks for your support again and have a nice day!
