### ISSUE TITLE
Oxygen is incompatible with PHP 8

### ISSUE THREAD

**Issue by alex02** [soflyy/oxygen-bugs-and-features#1817]
**Describe the bug**
I'm using Oxygen 3.6.1 on localhost with PHP 8 and no other plugins installed.

After installing the plugin and trying to make a template, the following error is displayed on Oxygen's admin:

> Warning:  Only the first byte will be assigned to the string offset in C:\xampp\htdocs\wp\wp-includes\class.wp-scripts.php on line 492

When I open the page builder, it doesn't load. Attached console.log:
[console log.log](https://github.com/soflyy/oxygen-bugs-and-features/files/5761481/console.log.log)

Things go even worse when I turn WP_DEBUG on, I get the following on the front-end and the admin panel:

> Deprecated: Required parameter $callback follows optional parameter $values in C:\xampp\htdocs\wp\wp-content\plugins\oxygen\component-framework\includes\conditions.php on line 182
> 
> Deprecated: Required parameter $callback follows optional parameter $values in C:\xampp\htdocs\wp\wp-content\plugins\oxygen\component-framework\includes\conditions.php on line 1148
> 
> Deprecated: Required parameter $defaults follows optional parameter $is_media in C:\xampp\htdocs\wp\wp-content\plugins\oxygen\component-framework\components\classes\testimonial.class.php on line 136
> 
> Deprecated: Required parameter $defaults follows optional parameter $is_media in C:\xampp\htdocs\wp\wp-content\plugins\oxygen\component-framework\components\classes\icon-box.class.php on line 122
> 
> Deprecated: Required parameter $defaults follows optional parameter $is_media in C:\xampp\htdocs\wp\wp-content\plugins\oxygen\component-framework\components\classes\pricing-box.class.php on line 428
> 
> Deprecated: Required parameter $defaults follows optional parameter $is_media in C:\xampp\htdocs\wp\wp-content\plugins\oxygen\component-framework\components\classes\progress-bar.class.php on line 124
> 
> Deprecated: Required parameter $defaults follows optional parameter $is_media in C:\xampp\htdocs\wp\wp-content\plugins\oxygen\component-framework\components\classes\slider.class.php on line 398
> 
> Deprecated: Required parameter $defaults follows optional parameter $is_media in C:\xampp\htdocs\wp\wp-content\plugins\oxygen\component-framework\components\classes\superbox.class.php on line 115
> 
> Deprecated: Required parameter $defaults follows optional parameter $is_media in C:\xampp\htdocs\wp\wp-content\plugins\oxygen\component-framework\components\classes\toggle.class.php on line 98
> 
> Deprecated: Required parameter $defaults follows optional parameter $is_media in C:\xampp\htdocs\wp\wp-content\plugins\oxygen\component-framework\api\oxygen.element.class.php on line 723
> 
> Deprecated: Required parameter $selector follows optional parameter $css in C:\xampp\htdocs\wp\wp-content\plugins\oxygen\component-framework\api\oxygen.element.class.php on line 996
> 
> Warning: Attempt to read property "ID" on null in C:\xampp\htdocs\wp\wp-content\plugins\oxygen\component-framework\component-init.php on line 565

When I open the page builder with debug on, the page breaks because of broken content type. I get the following:

> Content Encoding Error
> 
> The page you are trying to view cannot be shown because it uses an invalid or unsupported form of compression.

I haven't enabled any compression.

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
Yes

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
Doesn't support PHP 8.

**To Reproduce**
1. Install Oxygen 3.6.1 on server with PHP 8.
2. Try to use it.

**Screenshots**
![admin panel](https://user-images.githubusercontent.com/361918/103476964-be803700-4dc2-11eb-9c32-c9151ff395bf.png)

**Desktop (please complete the following information):**
- OS: Windows 10
 - Browser Firefox latest
 - Oxygen Version 3.6.1

**Comment by profitlad** [comment]
Hi Alex02,

Did you solve the problem? I have the same exact problem.

**Comment by bcnno** [comment]
Got the same problem. Also when testing with the 3.7 alpha. Hopefully the PHP8 support comes with the next stable release.

**Comment by bendepeng** [comment]
Ran into the same problem, having Oxygen installed on XAMPP.

**Comment by WilliamVercken** [comment]
Same bug here.

- Wampserver 3.2.4
- Php 8.0.2
- MySQL 8.0.23
- Wordpress 5.6.2
- Oxygen 3.6.1

A brand new Wordpress, no plugins other than Oxygen 3.6.1
I create a new Template and I get these errors: 

> `Warning: Undefined array key "oxygen_lock_post_edit_mode" in C:\wamp64\www\ariakan.local.net\htdocs\wp-content\plugins\oxygen\component-framework\admin\admin.php on line 107`
> 
> `Warning: Cannot modify header information - headers already sent by (output started at C:\wamp64\www\ariakan.local.net\htdocs\wp-content\plugins\oxygen\component-framework\admin\admin.php:107) in C:\wamp64\www\ariakan.local.net\htdocs\wp-includes\pluggable.php on line 1296`
> 
> `Warning: Cannot modify header information - headers already sent by (output started at C:\wamp64\www\ariakan.local.net\htdocs\wp-content\plugins\oxygen\component-framework\admin\admin.php:107) in C:\wamp64\www\ariakan.local.net\htdocs\wp-includes\pluggable.php on line 1299`

Then when I'm going to the templates list I have this one:

> `Warning: Only the first byte will be assigned to the string offset in C:\wamp64\www\ariakan.local.net\htdocs\wp-includes\class.wp-scripts.php on line 492`

**Comment by KittenCodes** [comment]
Oxygen isn't compatible with PHP v8. Please use PHP v7.

**Comment by bengosselinca** [comment]
@KittenCodes  I understand it takes some time to ajust and code. Do the oxygen team have an approx timestamp for the integration of php 8?

. It will be awesome.  It is already is with composite elements and all new features !! Continue the good work !

**Comment by greggdev** [comment]
Any time frame on true Php 8 support with Oxygen?

**Comment by Firsh** [comment]
I ran into this too. With a builder aimed at developers, this is not very good.

**Comment by martinskou** [comment]
Would be nice with an estimated date to expect PHP 8 compatibility.

**Comment by katsar0v** [comment]
> Unfortunately, Oxygen is not compatible with PHP v8.x at this time. Our development team is aware of the issue and actively investigating it. However, I'm unable to provide any further details at this time. Please keep using PHP version 7.4 at this time. 

Not gonna be any time soon

**Comment by d-packs** [comment]
PHP 7.4 is nearing end of active support in just a few months. Oxygen php8 compatibility is critical.

**Comment by katsar0v** [comment]
Oxygen is not even wordpress 5.8 compatible though the beta was released long time ago... this plugin has terrible maintenance

**Comment by Spellhammer** [comment]
> Oxygen is not even wordpress 5.8 compatible though the beta was released long time ago... this plugin has terrible maintenance

This is not true. We verified Oxygen had no major issues with WordPress 5.8 before it was released. If you have experienced bugs with WP 5.8 please report them.

**Comment by katsar0v** [comment]
One of the bugs I found is that WordPress 5.8 changes locate_block_template() and this changes how templates are loaded. Therefore `wp_head` sometimes causes double titles and viewport tags in combination with other seo plugins like yoast or rankmath. I think you haven't verified enough. If Oxygen was open source and free to contribute from one, I would kindly do so, but until then - please fix the bugs as a lot of users have paid for this.

**Comment by jamescrabb** [comment]
> One of the bugs I found is that WordPress 5.8 changes locate_block_template() and this changes how templates are loaded. Therefore `wp_head` sometimes causes double titles and viewport tags in combination with other seo plugins like yoast or rankmath. I think you haven't verified enough. If Oxygen was open source and free to contribute from one, I would kindly do so, but until then - please fix the bugs as a lot of users have paid for this.

I also have a site that has duplicate <title> tags in the head using rankmath

**Comment by Spellhammer** [comment]
@katsar0v @jamescrabb If these issues occur only when Oxygen is active, please post a bug report with reproduction steps so that we can fix it.

The way it's worded here makes it sound like the SEO plugins you're using aren't compatible with WP 5.8. That's not something we can fix.

**Comment by katsar0v** [comment]
@Spellhammer already did - https://github.com/soflyy/oxygen-bugs-and-features/issues/2315

Am not sure if the SEO Plugins cause this - when using a normal WP template, it works as usual

**Comment by robd003** [comment]
@KittenCodes Can you guys work on PHP8 compatibility in the next release?

**Comment by katsar0v** [comment]
We will have to wait for Oxygen v10 probably... @robd003

**Comment by LauGau** [comment]
Maybe for Christmas? 😁🎁

**Comment by katsar0v** [comment]
Or after corona goes away...

**Comment by maxiorel** [comment]
And one year after... PHP 7.4 has now Security fixes only and Oxygen Builder is still not compatible with PHP 8. How sad :(

**Comment by KittenCodes** [comment]
PHP compatibility added in v8 Alpha 1: https://oxygenbuilder.com/2021/12/27/oxygen-4-0-alpha-1-now-available/.

**Comment by maxiorel** [comment]
Thanks. But "...alpha and beta releases of Oxygen or Oxygen add-ons should not be used in production environments". So the question is: when will be Oxygen usable again, please? As the current PHP is the 8. Is there any roadmap or timeline?

**Comment by KittenCodes** [comment]
@maxiorel I'm sorry, but we don't have a public road map, and I'm not able to give an ETA on when the stable release of v4 will be available.

**Comment by maxiorel** [comment]
OK, thanks for the answer @KittenCodes. That means we should stop buying/using Oxygen Builder for now because it is not usable with current PHP version. Luckily (honestly not the right word) I have the Ultimate licence, so I can wait another year and use another builders in the meantime.

**Comment by dtaleddesigns** [comment]
Any news on this at all? I've been singing Oxygen's praises for use instead of other builders like Elementor, especially for performance. But looking like I'll have to go with another builder after all.

**Comment by d-packs** [comment]
Yes. Oxygen 4.0 will be PHP 8 compatible. 4.0 alpha is PHP8 compatible. https://www.youtube.com/watch?v=N7jYmrc6FvA

**Comment by robd003** [comment]
Good news! Oxygen 4.0 is PHP 8 compatible. I tested the alpha release and it doesn't crash.

**Comment by colinmcdermott** [comment]
> well apparently beta is out. so surely the final release is not far now.

True! https://oxygenbuilder.com/2022/02/11/oxygen-4-0-beta-1-now-available/

**Comment by fily1212** [comment]
Beta 2 https://oxygenbuilder.com/2022/04/01/oxygen-4-0-beta-2-now-available/

**Comment by aboutwd** [comment]
My host pushed me to PHP-8 (No choice, No warning, shared hosting). 

It's a public elementary school's site, so because of budget and red-tape, we are unable to switch hosts quickly.  We need Oxygen's PHP-8 support ASAP.  Our site is still technically LIVE to the public, but we can't make any content changes to it whatsoever.  Super frustrating.

Please give some indication as to when V4 will be released. Any guess would be helpful.

**Comment by MarcBollmann** [comment]
still no php 8 support?

**Comment by robd003** [comment]
PHP support was added in 4.0 and works perfectly

**Comment by colinmcdermott** [comment]
Can confirm the above, PHP8 support is good with Oxygen since the beta a few months ago, and no problems with current version.

**Comment by robertdiawara** [comment]
Hmm. Oxygen Builder is not crashing, but template editing still only works with PHP7 (Error Masseage: Unable to load Template data). I this persists, I'll try to get rid of it and switch to DIVI builder or completely back to OpenCms. I have practice with OpenCms and Java web development for about 20 Years now. But I was open and tried out the combination Wordpress / Oxygen Builder, but up to now this was nothing but a nightmare :-(.
