### ISSUE TITLE
array offset on value of type bool in oxygen-acf-integration.php

### ISSUE THREAD

**Issue by wpsumo** [soflyy/oxygen-bugs-and-features#1818]
**Describe the bug**

`Notice | Trying to access array offset on value of type bool on line 830 in file /public_html/wp-content/plugins/oxygen/component-framework/includes/acf/oxygen-acf-integration.php`

**Additional context**
Seems to be an issue with the acf integration for images? None of the images fetched with oxygen is using return format array. They are using URL as oxygen doesn't support array. We use array for other images but those are fetched with manual php code.

**Comment by KittenCodes** [comment]
@wpsumo Please can you let me know what I need to do to cause the above error? It's not one I've seen previously.

**Comment by wpsumo** [comment]
@KittenCodes why was it closed?

Fetch a background image from a section via dynamic data and use an ACF image field.

**Comment by KittenCodes** [comment]
@wpsumo 

I close issues where I don't have enough information to replicate the issue. If the original poster replies (like you have done) then I will re-open them.

I've tried to replicate this on a Sandbox site running PHP 7.3, WordPress 5.6 and the free version of ACF, but I can't seem to cause the error. I've also got an advanced error logging script running, which should grab all errors.

Please can you let me know which version of PHP, WordPress and ACF you are using? Is there anything else you can give me that will help me to replicate this? Unfortunately, I can't log it internally if I can't see the issue occurring.

**Comment by wpsumo** [comment]
Please share the sandbox and I will replicate it on the sandbox for you. But give me a few days.

Latest ACF PRO 5.9.2
WordPress 5.5
PHP: 7.4.2 (You have to use later version of php on your sandbox otherwise you miss a lot. You can't force people to downgrade to 7.3. It's old and 7.4.2 is what most use and 8.0 is released which nobody use or should yet but staying on 7.3 of force users to use 7.3 is not ideal)

**Comment by KittenCodes** [comment]
@wpsumo Thank you. Here's a Sandbox site running PHP 7.4: http://precious-bee.w6.wpsandbox.pro?upass=K5z5JweX0Sm3.

**Comment by wpsumo** [comment]
The issue is oxygens acf integration have not built in a `if empty`. This is causing the 
`Trying to access array offset on value of type bool | 1 | +wp-content/plugins/oxygen/component-framework/includes/acf/oxygen-acf-integration.php:830`

We can setup conditions for this sure but if conditions is pretty standard once using ACF I expected it to be built in. So if empty the field is not displayed and cause issues as above. Please consider build this into the oxygen-acf-integration.php

Replicated issue on sandbox:
http://precious-bee.w6.wpsandbox.pro/acf/

Leaning more and more using code blocks for everything due to missing functions or limiations in the dynamic builds. But it's annoying code block have to be a outer div and can't be raw and just start with what we have inside reference https://github.com/soflyy/oxygen-bugs-and-features/issues/320

**Comment by KittenCodes** [comment]
@wpsumo Awesome, thank you.

**Comment by wpsumo** [comment]
@KittenCodes Welcome! The issue is that it's a hassle of maintaining once you have to create a duplicated section as hero block without the background image and set to display each other depending on if acf field is true or false.

**Comment by KittenCodes** [comment]
I've reported this internally.

**Comment by wpsumo** [comment]
@KittenCodes Thanks just edited my comments if you didn't see.

**Comment by wpsumo** [comment]
@KittenCodes any update on this one?

**Comment by EmSixTeen** [comment]
Just another prod, has there been any work done on this?

**Comment by wpsumo** [comment]
No response from oxygen so not sure.

**Comment by KittenCodes** [comment]
> No response from oxygen so not sure.

This has been reported internally. We will update here or close the issue once it has been fixed.

**Comment by karmaral** [comment]
It's was happening to me also but on line 927. 
Apparently adding... 
`function is_settings_page_feild( $group_id ) {

        $is_settings_page = false;

        $field_group = acf_get_field_group( $group_id );

		// ...this guard clause made my error go away
		if ($field_group == false)
			return $is_settings_page;
		
		if (is_array($field_group['location'])) {
            foreach ($field_group['location'] as $location_type) {
                foreach ($location_type as $location) {
                    if ($location['param'] == "options_page") {
                        $is_settings_page = true;
                        break;
                    }
                }
            }
        }

        return $is_settings_page;

    }`

**Comment by wdeer** [comment]
Bump. 
Experiencing same issue:
`Notice: Trying to access array offset on value of type bool in oxygen/component-framework/includes/acf/oxygen-acf-integration.php on line 927`

WP: 5.8.3
Oxygen: 3.9
ACF: 5.11.1

**Comment by wpsumo** [comment]
Upvote the issue guys.

@KittenCodes Any progress here, last interaction on this issue was 3 months ago.

**Comment by bwp-codes** [comment]
Hello everyone,

Today I also stumbled across this issue in `oxygen/component-framework/includes/acf/oxygen-acf-integration.php:927` and found a possible solution.

**Reason for the error**:
When creating fields of type `group`, the array `$field_group['location']` is `NULL` - this field only exists within the "Field Group" and not the "Group" field.

**Solution**:
We can avoid the notice by including a check for the existence of the `$field_group['location']` array, so the function only runs for "Field Groups".

**Code:**

```php
function is_settings_page_feild( $group_id ) {

    $is_settings_page = false;

    $field_group = acf_get_field_group( $group_id );

    if (isset( $field_group['location'] ) && is_array($field_group['location'])) {
        foreach ($field_group['location'] as $location_type) {
            foreach ($location_type as $location) {
                if ($location['param'] == "options_page") {
                    $is_settings_page = true;
                    break;
                }
            }
        }
    }

    return $is_settings_page;

}
```

**Comment by WhereverPanda** [comment]
Hi guys,

I'm testing Oxygen 4.0 Beta 2 on Wordpress 5.9.3 on PHP 8

I'm also getting this error on line 927 and the code above fixes it.

I'm getting more errors though:

When switching from PHP 7.4 to PHP 8, I'm getting the following: …

Warning: Undefined array key "settings_page" in zzz/wp-content/plugins/oxygen/component-framework/includes/acf/oxygen-acf-integration.php on line 811

Warning: Trying to access array offset on value of type bool in zzz/wp-content/plugins/oxygen/component-framework/includes/acf/oxygen-acf-integration.php
on line 706

Warning: Trying to access array offset on value of type bool in zzz/wp-content/plugins/oxygen/component-framework/includes/acf/oxygen-acf-integration.php on line 707

These PHP errors occur in areas where I am showing ACF fields conditionally. For instance if a News article's 'Read more URL' field has a value, one of these errors shows in the region where the read more button should be. 

This works fine on PHP 7.4, but the error show when switching to PHP 8

Can anyone help?

**Comment by jvorld** [comment]
@WhereverPanda Hi, did you find any solution to your problem? I am now encountering the exact same errors. Thanks

**Comment by Tajmi** [comment]
Hi any news on that isue? :/

**Comment by leolll** [comment]
If you're using an error tracker, these warnings chew through your error tracking quota.  Would be great to resolve these.

**Comment by AlkoKod** [comment]
I am experiencing a though times when updating to PHP8. This is a huge problem. How to solve this in general? With some kind of snippet or something?

**Comment by leolll** [comment]
> How to solve this in general?

The only workaround that I know is to disable logging of PHP warnings.  A member of the Facebook group had a code snippet that would suppress all warnings related to Oxygen but unless you're experienced with PHP configuration I wouldn't try that.

**Comment by AlkoKod** [comment]
@leolll I am experienced. However I was kicked out from the group because of comment about Breakdance and Bricks builder. I write a blog about Oxygen (great-tit.com) and I would be happy to post a solution. For me now this is a solution:

1) Open ACF fields
2) find All Image fields and set their output to URL instead of Array
3) Open Oxygen templates which uses these fields
4) Add the dynamic data images again and reload

But this takes a lot of time especially with bigger websites..

**Comment by leolll** [comment]
@AlkoKod That's a nice solution.  I agree it would make life a lot easier if those warnings & notices were addressed in the core Oxygen code.

I'm pasting the comment Matt Hias posted on the Oxygen FB group in case you're curious.  I haven't tried it myself, but Matt seems like a very competent dev:

> Oxygen produces tons of notices and warnings. In every version since I own 2.2.1. And it's not only with PHP 8. It has occurred in PHP 7 as well.
It has been reported countless times. They fix two and add three new. 🙁
It's so annoying. It makes it so hard to debug your own development because you need to scroll through hundreds of messages from Oxygen.
So I wrote a little plugin (only a few lines of code) for my development setups to suppress all notices and warnings from Oxygen.

```
set_error_handler(function ($errno, $errstr, $errfile) {
$ignore = false;
if (strpos($errfile, 'plugins/oxygen') !== false) {$ignore = true;}
if (strpos($errfile, 'plugins/oxy-toolbox') !== false) {$ignore = true;}
if (strpos($errstr, 'send buffer of zlib') !== false) {$ignore = true;}
return $ignore;
}, E_NOTICE | E_DEPRECATED | E_WARNING);

```

> (I added zlib and oxy-toolbox since PHP 8 )

**Comment by gerogr** [comment]
+1

**Comment by leolll** [comment]
This bug still exists in 2023.

**Comment by OneDayCommunication** [comment]
Hi to all
Went this Bug to me on switch from php 8.0 to 8.1

I have changed for now the line 905 from :
 $output = $field['value']['url'];
to
$output = isset($field['value']['url']) ? $field['value']['url'] : '';

no error are returned yet, but is this correct in the way of fixing, I don,t know...

**Comment by OneDayCommunication** [comment]
> This bug still exists in 2023.

I have changed for now the line 905 from :
$output = $field['value']['url'];
to
$output = isset($field['value']['url']) ? $field['value']['url'] : '';

You can try but this is not Update friendly for now

**Comment by Spellhammer** [comment]
This was fixed in 4.0.

**Comment by leolll** [comment]
Line `850` of `oxygen/component-framework/includes/acf/oxygen-acf-integration.php` still causes PHP Warnings on Oxygen 4.8.3:

`Warning: Undefined array key "settings_page"`

`$field = $this->get_field_by_path( $atts['settings_path'], $atts['settings_page'] );`

**Comment by pixluser** [comment]
Go this problem too again.Same error as leolll. error line 850.

**Comment by Hootlord** [comment]
> Go this problem too again.Same error as leolll. error line 850. It' also happen when I'm doing a condition of a dynamic data - ACF field != empty by example.

@pixluser did you find a way to solve this? I have the same problem

**Comment by Hootlord** [comment]
@Spellhammer is there a hotfix for this issue on line 850?

**Comment by pixluser** [comment]
For making a condition of a dynamic data - ACF field != empty by example.  >> no the bug is still there, I finally removed my conditions.
