### ISSUE TITLE
Remove Oxygen's Classes and CSS

### ISSUE THREAD

**Issue by TnowL** [soflyy/oxygen-bugs-and-features#182]
**Describe the feature you'd like to see included in Oxygen.**
Ability to remove Oxygen's classes like ct-div-block, ct-link-button, ct-link-text, etc.

**What are the use cases for this feature?**
Having a cleaner CSS and HTML code website. This will help eliminate unwanted or not need CSS.

**Examples of this feature or functionality.**
A good example is if it works the same was ID where we can rename it to something else. But hoping for a feature to disable ID too if ID not needed.

**Comment by samjco** [comment]
Yes +1
But for now......
```js
   <script>
    jQuery(document).ready(function($) {
        $('div').removeClass("ct-div-block");
        $('div').removeClass("ct-link-button");
        $('div').removeClass("ct-link-text");
    });
    </script>
```

**Comment by yepyeh** [comment]
+1

**Comment by hssktm** [comment]
+1000

**Comment by sergiubacioiu** [comment]
+9999

**Comment by gviger** [comment]
+1000

**Comment by andreasputlitz** [comment]
+1

**Comment by andreasputlitz** [comment]
#2330

**Comment by adrien-robert** [comment]
+1

**Comment by CedricJA** [comment]
Any news on this? 
I just started converting a page to Oxygen and it's quite a pain with all these added styles from Oxygen ...

**Comment by KeviinCosmos** [comment]
To use jQuery for removing a class, looking through many elements, is not very good for performance. 
And place it in footer will just cause in not great look before everything is loaded.

I'm using the "unset" css value
Do this to all you classes you want to inset.
Yes you'l still overwride the css, but the performance is still great.

```
/* to unset one or more */
.some-block-name {
   display: unset;
   flex-direction: unset;
   ... and so on.
}
```

```
/* to unset everything */
   .some-block-name {
   all: unset;
}
```
No let your styling begin.

**Comment by madjedo** [comment]
I'd like to see this for the Woo integration only.

**Comment by farhanmunim** [comment]
+9999999

Any updates on this???

**Comment by gerogr** [comment]
+1

**Comment by Mar1AK** [comment]
This is much needed. It is messing up with my custom utility classes and wherever I don't want to use Flexbox. Please consider, thanks.

**Comment by Ikpixel** [comment]
Can’t wait.

**Comment by beckbeck-se** [comment]
+1

**Comment by samjco** [comment]
Yeah @KeviinCosmos...
But, here's the issue: https://github.com/soflyy/oxygen-bugs-and-features/issues/2330#issuecomment-892484087

**Comment by beckbeck-se** [comment]
Has anybody tried to "Dequeue Oxygen CSS" ?  Found this article.
https://code.dplugins.com/dequeue-oxygen-css/

**Comment by reilix** [comment]
For me additional CSS like this worked:

`
.ct-link-button.btn2, .ct-link-button.btn1 {
	background-color:#926aa6 !important
}

.ct-link-button.btn2:hover {
	background-color:rgba(143,104,163,0.24) !important;
	color: white;
}

.ct-link-button.btn1:hover {
	background-color:rgba(143,104,163,0.24) !important;
}
`

**Comment by reilix** [comment]
For me additional CSS like this worked:

```
.ct-link-button.btn2, .ct-link-button.btn1 {
	background-color:#926aa6 !important
}

.ct-link-button.btn2:hover {
	background-color:rgba(143,104,163,0.24) !important;
	color: white;
}

.ct-link-button.btn1:hover {
	background-color:rgba(143,104,163,0.24) !important;
}
```

**Comment by Spellhammer** [comment]
This is very unlikely to be viable. If that changes, I'll reopen it this.
