### ISSUE TITLE
Protection for function return values

### ISSUE THREAD

**Issue by squarewave17** [soflyy/oxygen-bugs-and-features#1821]
**Describe the bug**
When using a php function return value for dynamic data, the site will break if that function isn't there

**To Reproduce**
1. Create a snippet with a function that returns some data
2. call this function using the php function return into a dynamic data element in oxygen
3. delete the snippet that contains the function
4. The site will now break, as the install now calls a non-existent function

**Expected behavior**
Ideally, the function return should be called with a statement to check that it first exists

**What actually happens**
No conditional is in place, so the site breaks

**Additional context**
Obviously this issue wouldn't come up too much but when it does, it's potentially devastating. Suppose the user has some function in a snippets plugin and for whatever reason, that plugin is deactivated

**Comment by KittenCodes** [comment]
@squarewave17 What issue are you seeing when the function doesn't exist? In my testing, I'm just seeing the text "function does not exist", but the site (both builder and front-end) are still working as expected.
