### ISSUE TITLE
"Items Not Loaded" on 3.7 alpha 1

### ISSUE THREAD

**Issue by shoelaced** [soflyy/oxygen-bugs-and-features#1828]
**Describe the bug**
*A clear and concise description of what the bug is.*

Tried installing 3.7 alpha 1 on a site that I'm only just starting, currently only has a header builder block. After installing I opened up the template and it says "Items not loaded. Try again."

![Screenshot 2021-01-08 154816](https://user-images.githubusercontent.com/8772661/104034571-f6271e80-51c8-11eb-9774-28295bc41450.jpg)

If I close the error, everything seems to work except the new Composite Elements. They are visible in the element browser but clicking on them has no effect, and in the devtools this error appears:

![image](https://user-images.githubusercontent.com/8772661/104035583-34710d80-51ca-11eb-954c-883d3c966e78.png)

I tried refreshing and it happens on every load.

The only thing in the template is a header builder block with a pro menu inserted. This is a brand new site and so far O2 and ACF Pro are the only plugins installed.

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
*If yes, provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*

No, is it possible to install the alpha there?

**Desktop (please complete the following information):**
 - Oxygen Version [e.g. 2.2 Alpha]

Windows 10, Chrome (latest), PHP 7.4, WP 5.6, Nginx.

**Comment by KittenCodes** [comment]
@shoelaced

This is a known issue with 3.7 Alpha. To get around it, you need to enable the default design sets via Oxygen > Settings > Library.

Please let me know if you already had the default design sets enabled.
