### ISSUE TITLE
Fix your responsive setting

### ISSUE THREAD

**Issue by promocot** [soflyy/oxygen-bugs-and-features#1836]
I use a column width of 1280 px, I set the font size to 77 px, when I decide to look at the layout in the width of the columns, I see that this size does not fit and I need to make it smaller (I set it to 61 px), I do, finish the setting and want to check How does responsive work in the browser and what do I see? That in 1280 nx it was necessary to leave 77px, since the text if in 77 nx was in 3 rows, then at 61 nx it stood in 2 rows, and if I go 1130 nx wide, then I see how the solution to put 61 nx is ideal, then I I set the columns to go vertically from 768 px but the columns all go exactly from 998 px, correct the display in the editor, otherwise it's not clear how everything will look like in the end ... your solution is better optimized, but it is still raw and unfinished and cannot compete with The Elementor, since the Elementor customization possibilities are better tuned ... while I can't say that you are ideal, there is something else to work on while the Element, if the code optimizes, you will lose because there are more solutions for them than you and ease of use. Of course, what you don't have is Elementor, but it's not as critical as what they have and what you don't have

**Comment by KittenCodes** [comment]
If you've encountered an actual bug, please replicate the issue on our Sandbox site and send us the URL so that we can take a look: https://oxygenbuilder.com/try/.

**Comment by promocot** [comment]
http://smiling-cockroach.w5.wpsandbox.pro/sample-page/

**Comment by promocot** [comment]
http://smiling-cockroach.w5.wpsandbox.pro/wp-admin/edit.php?post_type=page

**Comment by promocot** [comment]
look in settings and how this look in browser

**Comment by KittenCodes** [comment]
Thank you for the link to the Sandbox site.

Is the problem that the columns are stacking at 992px and not 768px? If that's not the problem, please can you clearly explain what the issue is?
