### ISSUE TITLE
Columns - width calculation broken at Page container sizes (columns collapse)

### ISSUE THREAD

**Issue by johncrumpton** [soflyy/oxygen-bugs-and-features#1837]
**Describe the bug**
I have a 50% 50% column at all devices breakpoint. If I change to Page container and adjust one of the child divs to say 60%, both divs become centered and tiny (collapse).

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
Yes

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
http://homely-ox.w6.wpsandbox.pro/sample-page/?ct_builder=true
75.00

**To Reproduce**
1. Add section.
2. Add columns 50 50 
3. Add text to each column
4. Change size to page container
5. Change width of a column child div to 60 and it breaks

**Expected behavior**
The column should keep the size and adjust the other column(s)

**What actually happens**
Both columns center themselves and shrink to 25px each

**Screenshots**
<img width="515" alt="Screenshot 2021-01-11 042300" src="https://user-images.githubusercontent.com/272776/104147170-2e934c00-53c5-11eb-951d-af9c2029564d.png">

**Video**
https://user-images.githubusercontent.com/272776/104147183-37841d80-53c5-11eb-922a-0e4985ba4e00.mp4

**Desktop (please complete the following information):**
Chrome
 - Oxygen Version [e.g. 2.2 Alpha]

**Comment by johncrumpton** [comment]
Here's the video if you don't want to download it:
https://www.berrycast.com/conversations/2dc6316f-40ff-51de-932e-99542080f49d

**Comment by KittenCodes** [comment]
@johncrumpton This is a known issue. Please go to Advanced > Size & Spacing, and change the column width to your desired percentage there after switching to a smaller breakpoint.

**Comment by KittenCodes** [comment]
Duplicate: https://github.com/soflyy/oxygen-bugs-and-features/issues/895
