### ISSUE TITLE
Add VW for fonts (for what read in description)

### ISSUE THREAD

**Issue by promocot** [soflyy/oxygen-bugs-and-features#1838]
VW is ideal for responsive devices, i use this and % for column padding and margin and have universal responsive website. I show my website in Elementor.

![image](https://user-images.githubusercontent.com/66754335/104185590-d9375900-541d-11eb-958d-2808e2d82bed.png)
![image](https://user-images.githubusercontent.com/66754335/104185631-e48a8480-541d-11eb-9722-b66a75c7767a.png)
![image](https://user-images.githubusercontent.com/66754335/104185658-eb18fc00-541d-11eb-80a0-3490ba14aa85.png)

You can see, different resolution and my typography look same. Same history for tablet.

**Comment by KittenCodes** [comment]
You can use VW for fonts: https://d.pr/i/anFhPJ
