### ISSUE TITLE
Bug with responsive in editor

### ISSUE THREAD

**Issue by promocot** [soflyy/oxygen-bugs-and-features#1839]
1) If i select vertical alignment from 768 px, but after i select 998 px, after i can't select 768 again.
2) if i set breakpoint for tablet 1040, width is 768 px (make possibility to choose portrait or landscape view, for better analyze)

**Comment by KittenCodes** [comment]
@promocot Please open a support ticket so that we can take a look at this for you: https://oxygenbuilder.com/support.
