### ISSUE TITLE
Add "width" and "height" image dimension attributes to <img> tag

### ISSUE THREAD

**Issue by SvenWoltmann** [soflyy/oxygen-bugs-and-features#1840]
**Describe the feature you'd like to see included in Oxygen.**

I would like to have the possibility to add `width` and `height` attributes to the `<img>` tag, so that the following HTML code is created for the image:
```
<img src="..." width="..." height="...">
```

**What are the use cases for this feature?**

I'm aware that the width and height can be defined via CSS, however there's one use case in which this is not enough.

If you want the image's width to be defined as a percentage of it's container's width, while keeping its original aspect ratio, you define it as follows (the style can, of course, also be assigned via a class, too):
``` 
<img src="..." style="width:100%;height:auto">
```

*However*: while loading the image, it's quadratic, because its aspect ratio is unknown. This causes a layout shift once the image is loaded. Such layout shifts are rated as very poor "Core Web Vitals" by search engines.

By adding the `width` and `height` attributes, the browser knows the image's aspect ratio before it is loaded and can correctly render the page from the beginning.

**Examples of this feature or functionality.**

The WordPress core itself does this well.

**Comment by KittenCodes** [comment]
Duplicate: https://github.com/soflyy/oxygen-bugs-and-features/issues/1752

**Comment by SvenWoltmann** [comment]
@KittenCodes The issue you've linked too is neither assigned to the bug reports project nor to the feature requests project. That's why I didn't find it before creating a new ticket.

**Comment by KittenCodes** [comment]
@SvenWoltmann It's not a bug, it's a feature request (labelled enhancement) which is why it's not assigned to bugs.

**Comment by SvenWoltmann** [comment]
@KittenCodes I know, but it's also not assigned to the "feature requests" project (https://github.com/soflyy/oxygen-bugs-and-features/projects/2).

That's where your documentation asks to search for existing feature requests.

**Comment by SvenWoltmann** [comment]
@KittenCodes I just posted another feature request (#1842) - that also didn't get assigned to the "feature requests" project and can also not be found in https://github.com/soflyy/oxygen-bugs-and-features/projects/2.

**Comment by KittenCodes** [comment]
@SvenWoltmann It is assigned to feature requests - the tag is "enhancement".

**Comment by SvenWoltmann** [comment]
@KittenCodes It's still not listed on https://github.com/soflyy/oxygen-bugs-and-features/projects/2 ... which is where your documentation asks to look for existing feature requests.

Just try to filter by ticket IDs...
https://github.com/soflyy/oxygen-bugs-and-features/projects/2?card_filter_query=1752
https://github.com/soflyy/oxygen-bugs-and-features/projects/2?card_filter_query=1842

They can't be found there, because they are not assigned to project 2.

Looks like you changed the way you organize feature requests from assigning them to project 2 to assigning the "enhancement" tag. But you didn't change the documentation on how to search for existing feature requests (at https://github.com/soflyy/oxygen-bugs-and-features). Your documentation says to look in https://github.com/soflyy/oxygen-bugs-and-features/projects/2. You should change it to https://github.com/soflyy/oxygen-bugs-and-features/issues?q=is%3Aissue+is%3Aopen+label%3Aenhancement then.

**Comment by KittenCodes** [comment]
@SvenWoltmann I apologise - you're correct, we have changed the way we manage bugs and features. I've updated the documentation to link to the right places.

**Comment by katsar0v** [comment]
Is there an update on this matter?
