### ISSUE TITLE
WooVariationSwatches is not a function

### ISSUE THREAD

**Issue by jasperf** [soflyy/oxygen-bugs-and-features#1841]
We are no longer see [product add-ons](https://pluginrepublic.com/wordpress-plugins/woocommerce-product-add-ons-ultimate/) loaded on WooCommerce product pages and we are getting this error

```
Uncaught TypeError: $(...).WooVariationSwatches is not a function on line #86 in https://staging.site.com/?ct_template=10168&ct_builder=true&ct_inner=true&oxygen_iframe=true
```

in red in the Oxygen Builder editor on loading a new product by choosing it from the dropdown menu.

**Comment by jasperf** [comment]
May be similar to closed issue https://github.com/soflyy/oxygen-bugs-and-features/issues/1123 where an update in WooCommerce Variation Swatches fixed things.

**Comment by KittenCodes** [comment]
@jasperf It may be that they need to update their plugin to work with the latest version of WordPress. I would suggest asking their developers to take a look at your site as they'll likely be the best team to find why their plugin is throwing an error.

I'll close this for now, but please let me know if you need anything from the Oxygen team.

**Comment by Lupul** [comment]
I have the same problem when editing a Product details template (Singular with [Products+Variations] checked)
but not on other templates like:
- Normal pages: Singular with "Pages" checked
- Product Lists: Archive with PostType:Product+Product_variation, Taxonomies: AllTags+AllProdTags+AllProdType+AllProdCateg

![image](https://user-images.githubusercontent.com/3596864/107114551-5617f000-686f-11eb-9897-00f1359459bf.png)
