### ISSUE TITLE
Gutenberg image gallery shows bullet points in front of every image

### ISSUE THREAD

**Issue by alexhedstrom** [soflyy/oxygen-bugs-and-features#1844]
**Describe the bug**
When using the image gallery in Gutenberg there is a bullet point in front of every image in that gallery. I'm using the Blog Simple Article Template to display the content edited in Gutenberg.

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
No

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
*If yes, provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*
Yes
https://oxygen-qf2zhnp5cn2cl.oxygen-demo.qsandbox.me/test/?preview=true

**To Reproduce**
1. Go to posts
2. Click on new post
3. Add headline
4. Add an images gallery and upload some images
5. Edit in Oxygen and add "Post Hero Blank" and "Simple Article" templates
6. Save
7. Preview

**Expected behavior**
*A clear and concise description of what you expected to happen.*
An image gallery without bullet points

**What actually happens**
*A clear and concise description of what happens instead of the expected behavior.*
An image gallery with bullet points

**Screenshots**
*If applicable, add screenshots to help explain your problem.*

**Desktop (please complete the following information):**
- Windows 10
- Anny browser
- Oxygen Version 3.6.1

**Smartphone (please complete the following information):**
- iPhone 12
- iOS
- Anny browser
- Oxygen Version 3.6.1

**Additional context**
*Add any other context about the problem here.*
<img width="897" alt="Capture" src="https://user-images.githubusercontent.com/2130358/104447165-b7fc7700-559b-11eb-8409-a62389c1f47f.PNG">

**Comment by KittenCodes** [comment]
@alexhedstrom Please try adding this CSS to a stylesheet via Manage > Stylesheets in the top right of the builder:

```css
.wp-block-gallery .blocks-gallery-item {
    list-style-position: outside;
    overflow: hidden;
}
```

The list-style CSS has been set correctly, but for some reason, the additional CSS above is needed to remove the bullets.
