### ISSUE TITLE
Oxygen Loads TypeKit after its Removal

### ISSUE THREAD

**Issue by bretcarmichael** [soflyy/oxygen-bugs-and-features#1846]
**Describe the bug**
After entering an Adobe Fonts API key, TypeKit. However, after removing the API key, TypeKit and the fonts tied to the project continue to be loaded by Oxygen.

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
*Yes.*

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
*Yes.*
Example: http://sympathetic-snail.w5.wpsandbox.pro/

**To Reproduce**
1. Go to 'Oxygen Settinsgs \ TypeKit'
2. Add TypeKit API key.
3. Save.
4. Wait (for Adobe TypeKit as instructed).
4. Remove TypeKit API key.
5. Save.
6. Rebuild Oxygen CSS cache.
7. Wait (Just to be sure. Same after waiting days though).
8. Dump brower cache.
9. Open new window.
10. Visit site.
11. Open Dev Inspector.
12. See TypeKit loaded in sources and head.

**Expected behavior**
After removing the TypeKit API key and saving, TypeKit is no longer loaded by Oxygen.

**What actually happens**
After removing the TypeKit API key and saving, TypeKit continues to be loaded by Oxygen.

**Screenshots**
*If applicable, add screenshots to help explain your problem.*

**Desktop (please complete the following information):**
- OS: macOS 11.1
 - Browser Safari, Chrome, Firefox
 - Oxygen Version 3.6.1
  
**Smartphone (please complete the following information):**
None.

**Additional context**
None.

**Comment by braeu71** [comment]
> **Describe the bug**
> After entering an Adobe Fonts API key, TypeKit. However, after removing the API key, TypeKit and the fonts tied to the project continue to be loaded by Oxygen.
> 
> **Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
> _Yes._
> 
> **Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
> _Yes._
> Example: http://sympathetic-snail.w5.wpsandbox.pro/
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. Go to 'Oxygen Settinsgs \ TypeKit'
> 2. Add TypeKit API key.
> 3. Save.
> 4. Wait (for Adobe TypeKit as instructed).
> 5. Remove TypeKit API key.
> 6. Save.
> 7. Rebuild Oxygen CSS cache.
> 8. Wait (Just to be sure. Same after waiting days though).
> 9. Dump brower cache.
> 10. Open new window.
> 11. Visit site.
> 12. Open Dev Inspector.
> 13. See TypeKit loaded in sources and head.
> 
> **Expected behavior**
> After removing the TypeKit API key and saving, TypeKit is no longer loaded by Oxygen.
> 
> **What actually happens**
> After removing the TypeKit API key and saving, TypeKit continues to be loaded by Oxygen.
> 
> **Screenshots**
> _If applicable, add screenshots to help explain your problem._
> 
> **Desktop (please complete the following information):**
> 
> * OS: macOS 11.1
> * Browser Safari, Chrome, Firefox
> * Oxygen Version 3.6.1
> 
> **Smartphone (please complete the following information):**
> None.
> 
> **Additional context**
> None.

**Comment by KittenCodes** [comment]
Fixed in v3.9 Beta 1.
