### ISSUE TITLE
Oxygen 3.7 no flexbox child controls

### ISSUE THREAD

**Issue by Trentburns97** [soflyy/oxygen-bugs-and-features#1851]
**Describe the bug**
There are no flexbox child controls in this beta version. I just wanted you guys to be aware. 

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
*Yes/No*

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
*If yes, provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*

**To Reproduce**

**Expected behavior**
*A clear and concise description of what you expected to happen.*

**What actually happens**
*A clear and concise description of what happens instead of the expected behavior.*

**Screenshots**
*If applicable, add screenshots to help explain your problem.*

**Desktop (please complete the following information):**
 - Oxygen Version [e.g. 2.2 Alpha]

**Smartphone (please complete the following information):**
 - Oxygen Version [e.g. 2.2 Alpha]

**Additional context**
*Add any other context about the problem here.*

**Comment by KittenCodes** [comment]
@Trentburns97 I've not been able to replicate this on a flex child element. If you're still encountering the issue, please open a support ticket: https://oxygenbuilder.com/support.
