### ISSUE TITLE
O v3.7 Alpha - Background overlay color w/offset bug

### ISSUE THREAD

**Issue by ocbroadband** [soflyy/oxygen-bugs-and-features#1852]
**Describe the bug**
Section/div/etc. with a background image configured.  I've given a Y offset to center the portion of the image to the middle of the section, but with the background overlay(Or gradient) color applied, it appears to 'shift' with the offset.

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
Yes

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
*If yes, provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*
http://light-manatee.w5.wpsandbox.pro/2017/03/09/hello-world/

**To Reproduce**
1. Add Section to page,
2. Go to Advanced -> Background and add background image.
3.  Add Image Overlay Color, and adjust transparency to less than 50% to see image through overlay color.
4. Background Size -> Cover / Background Repeat -> No-Repeat
5. Adjust 'Top' to negative value to bring image to center of Section for focus.  IE, -300
6. Overlay color is now shifted vertically up and does not cover the image completely within the section boundaries.  It appears the overlay color is adjusting with the offset instead of remaining static within the section while the image is offset underneath.

**Expected behavior**
*A clear and concise description of what you expected to happen.*
Overlay color/gradient should remain covering entire section while image is offset only within the section/div/etc..

**What actually happens**
*A clear and concise description of what happens instead of the expected behavior.*
Overlay color/gradient moves with image offset showing a non-covered part of the image within the section/div/etc.

**Screenshots**
*If applicable, add screenshots to help explain your problem.*
![image](https://user-images.githubusercontent.com/13633011/104773906-9e3d6a00-572a-11eb-9882-ab2714e2bc72.png)

**Desktop (please complete the following information):**
- OS: Win10Pro
 - Browser : Chrome
 - Oxygen Version: 3.6 / 3.7 Alpha

**Smartphone (please complete the following information):**
- Device: N/A

**Additional context**
*Add any other context about the problem here.*

**Comment by KittenCodes** [comment]
@ocbroadband To position the image in the center of the Section, please set the Top and Left positions to 50%. When you use a negative margin, the overlay colour still fills the full background space on the Section, but the image does not which is why you're seeing this result. This is how the background-position property works - it's not a bug in Oxygen.
