### ISSUE TITLE
Getting the issue after copying shortcode from one domain to another domain.

### ISSUE THREAD

**Issue by jatindv** [soflyy/oxygen-bugs-and-features#1854]
Getting the issue in easy post after copying short code from one domain to another domain.

I have tried with Sign All Short codes but still getting the same issue.

I have also tried https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/

![138045810_3784676401591899_445142399099292022_o](https://user-images.githubusercontent.com/42375000/104911943-a4914780-59b1-11eb-8a1f-566af3d5d6d2.jpg)

Oxygen: version: 3.6.1,
WordPress version: 5.6

**Comment by Spellhammer** [comment]
Please submit a ticket at https://oxygenbuilder.com/support and we will investigate.
