### ISSUE TITLE
"make the full page editable in gutenberg" not working

### ISSUE THREAD

**Issue by krapock** [soflyy/oxygen-bugs-and-features#1856]
**the bug**
MAKE THIS FULL PAGE EDITABLE IN GUTENBERG
just does not seem to work

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
Yes

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
Yes
 https://oxygen-qkbwv4k6p94cl.oxygen-demo.qsandbox.me/wp-admin/post.php?post=2&action=edit

**To Reproduce**
1. create a sandbox
2. go to oxygen > templates
3. create a new template and edit it
4. add some text component
5. save the template and publish it
6. create a page
7. assign the oxygen template to the page
8. check "MAKE THIS FULL PAGE EDITABLE IN GUTENBERG" loud checkbox
9. save and publish
10. check that you can see the template text in the published page
11. go back to the editor
12. refresh your page (and it's browser cache)

**Expected behavior**
I expect to see the template text block in gutenberg editor

**What actually happens**
gutenberg editor is blank, although you can see in the code view this code :
   `<!-- wp:oxygen-vsb/ovsb-sample-page /-->`

**Screenshots**
*If applicable, add screenshots to help explain your problem.*

**Desktop (please complete the following information):**
- OS: ubuntu 20.10
 - Browser: chrome
 - Oxygen Version 3.6.1 + gutenberg integration 1.4

**Additional context**
this is step-by-step what is shown in the video description of the gutenberg integration : https://oxygenbuilder.com/documentation/gutenberg-client-mode/

**Comment by KittenCodes** [comment]
@krapock This isn't how "Make this full page editable in Gutenberg" works. The page itself needs to have content created within Oxygen. Once the page has content, you can check "Make this full page editable in Gutenberg".

**Comment by khan7swati** [comment]
I can't see the checkbox "Make the full page editable in Gutenberg". I have content on the page added from the library.

**Comment by lucilecollignon** [comment]
@KittenCodes Same problem, I had a template applied to a page which have content created in the inner content block of my template. The website is live and working well. When I click "Make this full page editable in Gutenberg", the content disappears.

**Comment by KittenCodes** [comment]
@lucilecollignon 

Please open a support ticket so that we can take a look at this for you: https://oxygenbuilder.com/support/.
