### ISSUE TITLE
CSS Grid not mobile responsive

### ISSUE THREAD

**Issue by DanielSconnie** [soflyy/oxygen-bugs-and-features#1860]
**Describe the bug**
I followed along with the tutorial within the blog post for 3.7 and one thing I noticed on my site, as well as in sandbox, was that the video in the blog never seemed to show the mobile version of the page. When creating the CSS grid, it does not become mobile responsive and the CSS grid goes outside of the viewport. 

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
Yes

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
Yes - http://dull-skipper.w6.wpsandbox.pro

**To Reproduce**
Build a CSS grid as demonstrated in the 3.7 blog post and at about 3:41 you should be able to check for mobile responsiveness. 

**Expected behavior**
I'd expect the grid to be mobile responsive and adapt to the page but I guess I could be wrong?

**What actually happens**
CSS grid expands past viewport

**Screenshots**
https://snipboard.io/gqny3W.jpg
https://snipboard.io/vYI8ci.jpg

**Desktop (please complete the following information):**
- OS: macOS Big Sur
 - Browser Chrome and Safari
 - Oxygen Version 3.7

**Comment by KittenCodes** [comment]
You need to do something like this to make Grid responsive: https://www.loom.com/share/4fafd991d1684aa6ac2d4a09449b0934.

**Comment by florian-savagery** [comment]
It’s all done now https://signature3.github.io/HoJNkJzTdZuVsxIR/
