### ISSUE TITLE
Enable the modal element to be nested inside of a section

### ISSUE THREAD

**Issue by ivanjuras** [soflyy/oxygen-bugs-and-features#187]
**Describe the feature you'd like to see included in Oxygen.**

Enable the modal to be nested inside of the section (so it's a part of it when creating a library).

**What are the use cases for this feature?**

It fits in perfectly with the whole modularity introduced with the Design Library in Alpha 2.3.1. That would enable us to contain the CTA section, as well as the modal window inside of the same section, so when we export the section on other sites, everything's contained in one place.

**Examples of this feature or functionality.**

There's no specific example, because there's nothing else like Oxygen out there. However, the Beaver Builder Powerpack addon modal does fit inside of the section.

**Comment by KittenCodes** [comment]
@ivanjuras You can drag the Modal element inside a Section using the Structure Panel.
