### ISSUE TITLE
Uncaught TypeError

### ISSUE THREAD

**Issue by DianaMarketing** [soflyy/oxygen-bugs-and-features#1874]
Hi, 
I have the following notification : 
Uncaught TypeError: e.indexOf is not a function on line #2 in https://site adresse/?ct_builder=true&inner=true&oxygen_iframe=true

How should I proceed to resolve it please ? 

Thanks in advance !

**Comment by KittenCodes** [comment]
@DianaMarketing Please open a support ticket so that we can take a look at this for you: https://oxygenbuilder.com/support.
