### ISSUE TITLE
Has anyone had this error? What does it mean? "Identifier 'mouseoverTimer'"

### ISSUE THREAD

**Issue by CriandoSites** [soflyy/oxygen-bugs-and-features#1876]
" Uncaught SyntaxError: Identifier 'mouseoverTimer' has already been declared on line #1 in https://meusistemax.com/home/?ct_builder=true&amp;ct_inner=true&amp;oxygen_iframe=true "

When I open the editor, it shows up

Yes I had tried all the steps

The screenshot: https://scontent.fpoa7-1.fna.fbcdn.net/v/t1.0-9/143100378_2811610192385464_5415574235273890210_n.jpg?_nc_cat=105&ccb=2&_nc_sid=825194&_nc_eui2=AeG2ndbeBsHf5aMqKPWrTFrE80WbFYzDyVLzRZsVjMPJUoCkE3HYlgFFDe7KBiEUAPuMvC23-w6fpP8-6u3gxrsB&_nc_ohc=BW0enCSZC5EAX_l9Vpx&_nc_ht=scontent.fpoa7-1.fna&oh=fb21a87aa2efd5ca23eb30fa02940f43&oe=6035538B

- OS: Windows
- Browser: Brave
- Oxygen Version:  3.6.1

**Comment by CriandoSites** [comment]
> " Uncaught SyntaxError: Identifier 'mouseoverTimer' has already been declared on line #1 in https://meusistemax.com/home/?ct_builder=true&amp;ct_inner=true&amp;oxygen_iframe=true "
> 
> When I open the editor, it shows up
> 
> Yes I had tried all the steps
> 
> The screenshot: https://scontent.fpoa7-1.fna.fbcdn.net/v/t1.0-9/143100378_2811610192385464_5415574235273890210_n.jpg?_nc_cat=105&ccb=2&_nc_sid=825194&_nc_eui2=AeG2ndbeBsHf5aMqKPWrTFrE80WbFYzDyVLzRZsVjMPJUoCkE3HYlgFFDe7KBiEUAPuMvC23-w6fpP8-6u3gxrsB&_nc_ohc=BW0enCSZC5EAX_l9Vpx&_nc_ht=scontent.fpoa7-1.fna&oh=fb21a87aa2efd5ca23eb30fa02940f43&oe=6035538B
> 
> * OS: Windows
> * Browser: Brave
> * Oxygen Version:  3.6.1

**Comment by rodpascoe** [comment]
Why has this issue been closed?  It's never gone away and regularly gets posted as a question in the Facebook group.

**Comment by Spellhammer** [comment]
> Why has this issue been closed? It's never gone away and regularly gets posted as a question in the Facebook group.

@CriandoSites may be able to tell you why they closed it.

This error is probably a conflict with some other JavaScript coming from another plugin, a code block, or a browser extension, as 'mouseoverTimer' isn't actually in Oxygen's code anywhere that I can find.

**Comment by CriandoSites** [comment]
@Spellhammer @rodpascoe 

Oxygen Team about the "mouseoverTimer" and "loadScriptsTimer": 

Both of these errors aren't likely to prevent anything in the builder from loading correctly and can likely be ignored. I suspect the problem is that the code appears to run twice in the builder (once in the builder itself and once in the iframe that loads the design), which then causes the error saying that something has already been declared. If the builder is working as expected, please ignore the errors.

**Comment by dcolumbus** [comment]
> @Spellhammer @rodpascoe
> 
> Oxygen Team about the "mouseoverTimer" and "loadScriptsTimer":
> 
> Both of these errors aren't likely to prevent anything in the builder from loading correctly and can likely be ignored. I suspect the problem is that the code appears to run twice in the builder (once in the builder itself and once in the iframe that loads the design), which then causes the error saying that something has already been declared. If the builder is working as expected, please ignore the errors.

Yeah, it doesn't seem to have any impact ... but the error is still false and should be rectified.
