### ISSUE TITLE
Resetting IDs when copying/duplicating

### ISSUE THREAD

**Issue by dwork** [soflyy/oxygen-bugs-and-features#1880]
**Describe the feature you'd like to see included in Oxygen.**
When Oxygen resets IDs during copy (Hydrogen) or duplicate, it should also rename references to the old ID, or perhaps ask if the ID should be changed, or perhaps an option to say "don't change this ID when copying/duplicating"

**What are the use cases for this feature?**
Anytime someone wants to duplicate or copy an entire template or parts of a template. Otherwise, links are broken

**Examples of this feature or functionality.**
1) I have several IDs in a template -- a button with a #contact-form link that refers to a section with "contact-form" ID. If I copy/duplicate the template, and ID "contact-form" is change to "abcdef",  the button link should be changed to #abcdef. 
2) I have a modal with a button trigger. When the template is copied/duplicated, the button ID is renamed but the modal trigger isn't. Again, if the button ID is changed from "read-more" to "efghij", the modal trigger should also be changed from "read-more" to "efghij". Otherwise, the modal won't open.

**Comment by KittenCodes** [comment]
If this is only occurring when you use the Copy option in Hydrogen, please reach out to their support team.
