### ISSUE TITLE
Condition not working for Shortcode

### ISSUE THREAD

**Issue by mpacatang** [soflyy/oxygen-bugs-and-features#1884]
Conditions not working on Shortcode Component. 
_note: not the shortcode wrapper._

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
Yes

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
Yes...

**To Reproduce**
1. Create a shortcode component.
2. Set a condition. ei: User Logged In?

**behavior**
Not affected by any conditions.
note: only the shortcode.. not the wrapper version of it.

**Comment by KittenCodes** [comment]
@mpacatang Please wrap the Shortcode element in a Div and add the condition to the Div.

**Comment by katsar0v** [comment]
@KittenCodes Please add this somewhere in the documentation on the website.

**Comment by KittenCodes** [comment]
> @katsar0v Please add this somewhere in the documentation on the website.

Done.

**Comment by katsar0v** [comment]
@KittenCodes can you provide a link? These two links have almost no documentation
- https://oxygenbuilder.com/documentation/builder-elements/shortcode-wrapper/
- https://oxygenbuilder.com/documentation/builder-elements/shortcode/

**Comment by KittenCodes** [comment]
@katsar0v I added it to the Conditions documentation: https://oxygenbuilder.com/documentation/other/conditions/.
