### ISSUE TITLE
EXTRA Content imopossible to delete

### ISSUE THREAD

**Issue by jojojojojoj5564656465465** [soflyy/oxygen-bugs-and-features#1893]
**Describe the bug**
*A clear and concise descriptio
![Screenshot_20210206_151014](https://user-images.githubusercontent.com/45184918/107121180-54f7ba80-6891-11eb-9bde-9bafadde819a.png)
![Screenshot_20210206_151014](https://user-images.githubusercontent.com/45184918/107121190-64770380-6891-11eb-8908-61118df19a78.png)

n of what the bug is.*

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
***Yes**

**What actually happens**
**i duplicate a card 2 times it made 5 on the actual website and 3 on wordpress
IMPOSSIBLE to delete those 2 cards (from structure)**

**Screenshots**
![Screenshot_20210206_151014](https://user-images.githubusercontent.com/45184918/107121190-64770380-6891-11eb-8908-61118df19a78.png)

**Desktop (please complete the following information):**
 - Oxygen Version [3.6.1]

**Smartphone (please complete the following information):**
 - Oxygen Version [e.g. 2.2 Alpha]

**Additional context**
*Add any other context about the problem here.*

**Comment by KittenCodes** [comment]
@jojojojojoj5564656465465 Please open a support ticket so that we can take a look at this: https://oxygenbuilder.com/support.
