### ISSUE TITLE
Text Edit a text area to view/edit text of Heading and Text components.

### ISSUE THREAD

**Issue by Filipsons-K** [soflyy/oxygen-bugs-and-features#1895]
Hello, we need this 100% (Text Edit a text area to view/edit text of Heading and Text components.) in oxygen builder. 
![oxy](https://user-images.githubusercontent.com/66617494/107218203-fb6dc800-6a17-11eb-840a-40a26be9db65.jpg)

**Comment by Filipsons-K** [comment]
Thank you Oxygen Team to add this in the new update. I'm happy that you listen to what people wants.

**Comment by KittenCodes** [comment]
Added in v3.8 Beta.
