### ISSUE TITLE
backup not working

### ISSUE THREAD

**Issue by jojojojojoj5564656465465** [soflyy/oxygen-bugs-and-features#1899]
Hello,

I tried every plugins to make a backup of my site but no one works i always get this kind of error 

Warning: unlink(): open_basedir restriction in effect. File(/home/ybrv7474/nouveau-site/wordpress/wp-content/uploads/oxygen/css/blog-post-205.css) is not within the allowed path(s): (/var/www/vhosts/wp5.qsandbox.com_sites/6/4/3/qs3_1612918624_0643/site/s-qa66dlfakrfdl.eu1.wpsandbox.org:/tmp:/zzz_qs) in /var/www/vhosts/wp5.qsandbox.com_sites/6/4/3/qs3_1612918624_0643/site/s-qa66dlfakrfdl.eu1.wpsandbox.org/htdocs/wp-content/plugins/oxygen/component-framework/includes/cache.php on line 190

**Comment by KittenCodes** [comment]
@jojojojojoj5564656465465 Please open a support ticket so that we can take a look at your site: https://oxygenbuilder.com/support.

Bug reports are intended for issues that can be replicated on a clean Sandbox site.
