### ISSUE TITLE
DONE: Slider-carousel with data 

### ISSUE THREAD

**Issue by ThePopularizer** [soflyy/oxygen-bugs-and-features#19]
The current "slider" helper cannot populate slides with data, which limits its uses. As well as this, we do not currently have a carousel helper. 

So, here's a feature request for a slider-carousel, where you can configure not only the number of slides displayed per set (2 or more would be a carousel), but also take data (like ACF) using customisable templates in a similar way to the Easy Posts helper. 

Some good carousel options would be:
* To advance by a whole set, or just by one.
* Auto- or manual advance the slide.
* Responsive slide number options (e.g. 3 slides at 1000px, 2 at 750px, 1 at 500px).

In terms of uses, it would be very versatile (like other helpers). Example uses may include: 
* Featured gallery for page/post
* Featured posts on homepage 
* Featured WooCommerce product 
* Rotating testimonials
* Rotating logos in footer

I'm not sure that I've come across anything as versatile as this. Others may be able to provide similar examples in the market, or it may be something unique to Oxygen.

**Comment by Famarast** [comment]
It would be great to have a carousel in Oxygen!

**Comment by tobytraylor** [comment]
A generic widget that can take a template and a data query and then display the data as a grid, slider, carousel, posts loop, masonry, etc would be very helpful.  I have all my Client and Testimonial information in PODS.  If i could insert the client logo list carousel from the landing, the client logos as a grid with a different template as a grid, then the client testimonials with logos from the Clients list and text and other fields from the Testimonals list as a template loop that could be configured in flexible ways (num rows, num columns) then i would be happy.

**Comment by albertso** [comment]
+1

**Comment by AmibeWebsites** [comment]
A way to use the slider in combination with the 3.0 Repeater component?

**Comment by muzaffarsiddiqui** [comment]
+1

**Comment by adrien-robert** [comment]
+1

**Comment by wpdevlab** [comment]
+1

**Comment by ckevinroque** [comment]
This is one of the feature I was looking for. It is good as well if they include carousel for On-Sale, Latest, Best Seller, and Featured WooCommerce products.

**Comment by nicholasmscott** [comment]
Just wanted to add a +1 here, it is a shame that the repeater has been created but can't apply to Sliders!

**Comment by alriksson** [comment]
Preferably a Swiper.js built natively into oxygen with responsive and ACF galleries and dynamic data support. It would extend the possibilities to build fun things with native functions.

**Comment by tiptronic** [comment]
Jep - Swiper.js with dynamic data. Swiper is lean, fast, supports dynamic handling of slides and is even easy to extend beyond all that!

**Comment by noder5** [comment]
+1

**Comment by alanzirpoli** [comment]
+1

**Comment by masymulh** [comment]
+1

**Comment by georgehedley** [comment]
+1 this is available in elementor with a bunch of plugins and is very useful for displaying unique or dynamic content

**Comment by gagankhatri** [comment]
+1

**Comment by shmaltz** [comment]
This is a must have feature!

**Comment by joejoerson** [comment]
+1 Yes

**Comment by yepyeh** [comment]
I recently purchased and really enjoying Oxygen Builder.
But allowing the slider to take images from Custom Fields Galleries or Repeaters would be HUGELY helpful!!
Take slides from dynamic data: Posts (featured image), Images within a Post/CPT (Gallery or Repeater).
Thank you.

**Comment by shoelaced** [comment]
This is definitely a needed feature - the Slider looks quite nice but I've never been able to use it because the only times I ever use sliders are for dynamic things like posts or ACF repeaters.

**Comment by M-Marbouh** [comment]
+1... Definitely!

**Comment by thomasjulienalain** [comment]
+1

**Comment by swinggraphics** [comment]
A post slider is a basic page-builder feature conspicuously missing.

**Comment by agnosticaf** [comment]
+1

**Comment by Spellhammer** [comment]
Added in Composite Elements.
