### ISSUE TITLE
Vertical box shadow offset only working properly if the horizontal is not empty

### ISSUE THREAD

**Issue by bohdanps** [soflyy/oxygen-bugs-and-features#1905]
**Describe the bug**
Vertical box shadow offset only working properly if the horizontal is not empty

**Screenshots**
Not working
![image](https://user-images.githubusercontent.com/29403400/107659759-c9629d00-6c87-11eb-989d-e35f87d7453c.png)

Working
![image](https://user-images.githubusercontent.com/29403400/107659815-ded7c700-6c87-11eb-90e6-253f3b029203.png)

**Comment by KittenCodes** [comment]
@bohdanps Please set a value in the Horizontal Offset box.
