### ISSUE TITLE
Accordion - 3.7 Beta 1

### ISSUE THREAD

**Issue by stupidcatdesign** [soflyy/oxygen-bugs-and-features#1906]
**Describe the bug**
The Accordion Content area appears to have some limitation as to the length of content you can place in it - yet there is no clear way to adjust this. In addition, the closeOtherToggles = True does not appear to be constraining the ability to open multiple content areas in the accordion.

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
YES

I have not tried this on the sandbox.

**To Reproduce**
Add a div under the Accordion Content
Place several (12) 2-column Columns controls under it with content - most are around 250px tall, each
Final Column control is buried under the next Accordion row

**Expected behavior**
The length of the Accordion content should be easy to configure or unlimited

**Desktop (please complete the following information):**
- OS: ChromeOS
 - Browser Chrome
 - Oxygen Version 3.7 Beta 1

**Comment by Spellhammer** [comment]
You can change the maximum height of the Accordion content area by selecting an Accordion Content element in the Structure Pane, ensuring you have the .oxel_accordion__content selector selected at the top of the Properties Pane, then going to Advanced > Size & Spacing and changing its max-height to your desired maximum. Higher values may result in the opening/closing animation not behaving as expected.

I've adjusted the default to 3000px.
