### ISSUE TITLE
50:50 Columns do not change

### ISSUE THREAD

**Issue by mousebat** [soflyy/oxygen-bugs-and-features#1907]
• Add a Section
• Add a 50:50 Column and change "Stack Columns Vertically" to "Less than 768px"
• Add any content to the Column's child divs
• In the Column's "Size & Spacing", set the top margin to any number
• Change to the "Page container (1120px) and below" view
• In the Column's "Size and Spacing", set the top margin to any number
• Change to the "Less than 992px" view
 
The Column's child divs stack vertically despite being told to stack under 768px.

https://oxygen-qgnfkw2brwgdl.oxygen-demo.qsandbox.me/wp-admin/

**Comment by estraatios** [comment]
I tried the steps and it worked with no problem for me.

**Comment by mousebat** [comment]
Try setting a negative margin top. According to support it's a known bug, they said just use div's instead.
