### ISSUE TITLE
Accordion Composite Element - Oxygen 3.7 RC1

### ISSUE THREAD

**Issue by JJITPro** [soflyy/oxygen-bugs-and-features#1911]
**Describe the bug**
When adding the accordion to a backend page, it populates 3 rows/contents.  When duplicating those to add additional rows/contents, they do not allow you to click (expand) so that you can update the content text.  The 3 built in rows/contents do allow you to click (expand) and update the content text.  I was able to Save, return to Admin, then go back into the page that the accordion exists and all accordion rows/contents expanded as expected.  
Now, however, I have added a second accordion to the same Page and now neither accordion will expand as expected to modify the content text.

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
Yes

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
http://relatable-gharial.w5.wpsandbox.pro/terms-faqs/ - You must login to the backend Oxygen Builder for this page to see the issue.

**To Reproduce**
1. Go to a Page
2. Click on Add, choose the Accordion Composite Element
3. Duplicate the Accordion Row and the Accordion Content a couple of times
4. Click on the first row, it should expand to reveal the Accordion Content
5. Now click on the fourth row, it does not expand to reveal the Accordion Content, which prevents you from changing the Content text

**Expected behavior**
I expect every Accordion row/content, whether added by the Accordion Composite Element or duplicated by me, to expand when clicked on so that the Accordion Content text may be changed to reflect what I want a visitor to my website to see.

**Desktop (please complete the following information):**
- OS: macOS BigSur
 - Browser Chrome
 - Oxygen Version 3.7 RC1

**Comment by Spellhammer** [comment]
Thanks for the report, the issue has been fixed by adding proper event delegation.
