### ISSUE TITLE
New Issues - Accordion Composite Element Backend/Frontend - Oxygen 3.7 RC1

### ISSUE THREAD

**Issue by JJITPro** [soflyy/oxygen-bugs-and-features#1913]
**Describe the bug**
When adding the accordion to a backend page, it populates 3 rows/contents. When duplicating those to add additional rows/contents, they do not allow you to click (expand) so that you can update the content text. The 3 built in rows/contents do allow you to click (expand) and update the content text. I was able to Save, return to Admin, then go back into the page that the accordion exists and all accordion rows/contents expanded as expected.
Now, however, I have added a second accordion to the same Page and now neither accordion will expand as expected to modify the content text.

The first bug report was closed, noting the addition of proper event delegation.  That resolved my issue initially, adding an additional accordion element allowed my 2 existing accordion elements to function so that I could expend them and add my text in the content text field.  Now that I've added everything, saved, went back to WP Admin and then back into the Oxygen page editor, the accordion element will not expand again so that changes can be made, when necessary, to the content text.  Also, the frontend no longer expands to read the associated accordion content.

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
Yes

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
http://relatable-gharial.w5.wpsandbox.pro/terms-faqs/ - You must login to the backend Oxygen Builder for this page to see the issue.

**To Reproduce**

Go to a Page
Click on Add, choose the Accordion Composite Element
Duplicate the Accordion Row and the Accordion Content a couple of times
Click on the first row, it should expand to reveal the Accordion Content
Now click on the fourth row, it does not expand to reveal the Accordion Content, which prevents you from changing the Content text
Expected behavior
I expect every Accordion row/content, whether added by the Accordion Composite Element or duplicated by me, to expand when clicked on so that the Accordion Content text may be changed to reflect what I want a visitor to my website to see.

**Desktop (please complete the following information):**

OS: macOS BigSur
Browser Chrome
Oxygen Version 3.7 RC1

**Comment by Spellhammer** [comment]
The sandbox you listed is still using the old version of the Accordion code. Can you provide an updated sandbox link?

**Comment by JJITPro** [comment]
Elijah,

Sorry for the delay, I have reproduced my issue in the sandbox.  See links below.  The backend is also still hit or miss as to whether or not the accordion will expand to show and allow the accordion content to be displayed and modified.  The only way I have been able to get the backend to work has been to add accordions, sometimes multiple times just to get my existing accordions to work properly on the backend for editing.

Frontend (Accordion not expanding when clicked):
                http://relatable-gharial.w5.wpsandbox.pro/terms-faqs/

Backend:
                http://relatable-gharial.w5.wpsandbox.pro?upass=6m2GwDy6THn6


[Justin Hoffman]
Justin Hoffman
Managing Member
Hoffman Technologies Plus LLC
[cell]
334 245 8668<tel:+13342458668>
mobile

[work]
justin@hoffmantechnologiesplus.com<mailto:justin@hoffmantechnologiesplus.com>
work

[website]
hoffmantechnologiesplus.com<https://hoffmantechnologiesplus.com>
website
[QR Code]
[HoffmanTechPlus]<https://twitter.com/HoffmanTechPlus>[HoffmanTechnologiesPlus]<https://facebook.com/hoffmantechnologiesplus>[HoffmanTechnologiesPlus]<https://www.youtube.com/hoffmantechnologiesplus>
VIEW CARD<https://hihello.me/p/5d401853-8f4d-420b-bbde-798ea6864ed2>
Created with hihello.me<https://www.hihello.me>

**Comment by andreslotta** [comment]
Hey @JJITPro, I just stumbled upon your issue and took a look in the backend. Since you added the accordion element multiple times the composite element's code block also existed multiple times. After removing the duplicated code blocks everything works as expected.

**Comment by Spellhammer** [comment]
> @Spellhammer: I remember having read that those composite elements' duplicated code blocks automatically get removed when "building the site" – as long as they are completely identical. Am I wrong here or should this still be the case?

That's correct, but they have to be literally identical. If you had placed an accordion on the page, then I changed the code, then you placed a new accordion on the page, you'd have two accordion code blocks that are not literally identical and would likely have conflicting code.

@JJITPro Since you posted the login link publicly and @andreslotta appears to have fixed the issue by deleting duplicate code blocks, I can no longer investigate. Note that the latest sandbox you provided is still using the old accordion code. You need to completely delete all accordion elements and then re-add it from the +Add pane to get the updated code.

If, after re-adding the accordion from the +Add pane, the issue still persists, please send the login details to us via https://oxygenbuilder.com/support and we will investigate.

**Comment by andreslotta** [comment]
@JJITPro: Created a new test page with duplicated accordions. Works as expected (even without manually removing the duplicated code blocks): http://brave-tarantula.w5.wpsandbox.pro/accordions/
