### ISSUE TITLE
Hey guys, I think I found a bug/security breach at 'oxygenbuilder.com'

### ISSUE THREAD

**Issue by Eduardinholoko** [soflyy/oxygen-bugs-and-features#1914]
Redacted.

**Comment by Spellhammer** [comment]
@Eduardinholoko Thanks for the report, we'll look into it.

I've removed the instructions included in the post.

A note for anyone reading this:

The issue allows users to register on oxygenbuilder.com without purchasing Oxygen, which means they can access alpha/beta/RC downloads that are intended for customers only.

The issue in no way presents any sort of security risk for customer data or anything important.
