### ISSUE TITLE
Typo in docs

### ISSUE THREAD

**Issue by JakobJR** [soflyy/oxygen-bugs-and-features#1917]
**Describe the bug**
Wrong description on the Oxygen documentation.

Under the **Product Cart Button** element there's information about the **Product Images** element.

**Screenshots**

![image](https://user-images.githubusercontent.com/12740333/108219076-a592d180-7135-11eb-9345-3ce9d93dcdd3.png)

URL: https://oxygenbuilder.com/documentation/woocommerce-integration/product-cart-button/

**Comment by KittenCodes** [comment]
Fixed - thank you for letting us know.
