### ISSUE TITLE
Make code block not create HTML tags.

### ISSUE THREAD

**Issue by ivanjuras** [soflyy/oxygen-bugs-and-features#192]
**Describe the feature you'd like to see included in Oxygen.**

When creating a code block, right now you have to create a wrapping element. But sometimes, I just want to create a simple JS or CSS snippet for that section, and I don't want to have a wrapping element around the code, because that element won't have anything inside.

Could you create an option not to wrap the code inside of the element? Some kind of a "shadow" wrapper option.

**Comment by KittenCodes** [comment]
See #320
