### ISSUE TITLE
Some box appears at the Oxygen Builder admin view

### ISSUE THREAD

**Issue by ukunurk** [soflyy/oxygen-bugs-and-features#1923]
**Describe the bug**
*A clear and concise description of what the bug is.*
Installed Lifter LMS and after few updates of Lifter LMS there is a random box at the top of the window

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
*Yes/No*
NO

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
Yes! I replicated this problem 2 times in Sandbox and it is successifully replicable: just install Lifter LMS
*If yes, provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*
https://oxygen-qk54pffn3ykdl.oxygen-demo.qsandbox.me/

**To Reproduce**
1. Go to plugins and install Lifter LMS
2. Click on Oxygen, create new Template, save and edit with Oxygen
3. Upper left corner there is a random box

**Expected behavior**
*A clear and concise description of what you expected to happen.*
1. clicking delete putton upper left corner deletes items
2. clicking color picker allows to choose colors
3. activate section, click advanced > background > choose background from Media Library

**What actually happens**
*A clear and concise description of what happens instead of the expected behavior.*
1. box covers all the buttons upper left corner
2. color picker does not work
3. Media library does not open

**Screenshots**
*If applicable, add screenshots to help explain your problem.*
![oxygen-builder-lifter-lms-problem](https://user-images.githubusercontent.com/51176993/108527199-add84180-72da-11eb-92f1-34f971a41b76.jpg)

**Desktop (please complete the following information):**
- OS: [e.g. iOS] Mac osx Big Sur
 - Browser [e.g. chrome, safari] Safari
 - Oxygen Version [e.g. 2.2 Alpha] Sandbox does have 3.6.1

**Smartphone (please complete the following information):**
 - Oxygen Version [e.g. 2.2 Alpha]

**Additional context**
*Add any other context about the problem here.*

**Comment by KittenCodes** [comment]
@ukunurk Please import this file to the Code Snippets plugin ( https://wordpress.org/plugins/code-snippets/ ) to resolve the issue: https://www.dropbox.com/s/shlopkm6s9jt3iz/oxygen-compat-jquery-ui-fix.json?dl=1

**Comment by avocadesign** [comment]
Just to report them - we've also seen this issue with Easy Property Listings and Project Huddle plugins enabled :)
