### ISSUE TITLE
Bug in CUSTOM HOVER STATE when using Transform > Translate settings to set values

### ISSUE THREAD

**Issue by udoro** [soflyy/oxygen-bugs-and-features#1928]
**Describe the bug**
Bug exists in CUSTOM HOVER STATE when using Transform > Translate settings to set values. 
But works when using Advanced > CSS to set transform: translate values
Other Transform properties seem to be working fine.

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
Yes

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
Yes, LINK TO SANDBOX -  https://oxygen-qsfqzklf4hldl.oxygen-demo.qsandbox.me/hover-effect/

**To Reproduce**
1. Create a parent div, create a child div inside the parent div, set the child div Advanced > effects > transform > translateX =100%
2. Add custom state to parent div -  hover.parent-div .child-div
3. with the custom state selected, set Advanced > effects > transform > translateX =0%

**Expected behavior**
On hover on the parent div, the child div should revert to translateX=0%

**What actually happens**
But it remains stuck at translateX=100%, on inspecting the hover state of the parent div, and selecting the child div show an empty tranform value in the css.

**Screenshots**
![image](https://user-images.githubusercontent.com/22454125/108609376-c07f7300-73cd-11eb-8180-1c84e1218d5f.png)

**Desktop (please complete the following information):**
- OS: Windows 10
 - Browser: chrome 
 - Oxygen Version 3.6.1

I knew about the issue while watching this oxygen tutorial video:
https://www.youtube.com/watch?v=bZ3_yPxodzo

**Comment by mikeingz** [comment]
Super old bug, you have to put a double zero to make it work : 

![image](https://user-images.githubusercontent.com/2438157/110196729-6e385a80-7e81-11eb-9474-a6f86a98e101.png)

**Comment by KittenCodes** [comment]
Duplicate: https://github.com/soflyy/oxygen-bugs-and-features/issues/794
