### ISSUE TITLE
'Smooth Scroll to Hash links' causes Woo Tabs to scroll to top

### ISSUE THREAD

**Issue by madjedo** [soflyy/oxygen-bugs-and-features#1932]
**Describe the bug**
When enabling Oxygen setting for "Smooth Scroll to Hash links", the Woocommerce product tabs, scrolls the user to the top of page when clicked instead of only switching to correct tab.

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
Yes

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
Yes: https://oxygen-qzpk3tgfjbmdl.oxygen-demo.qsandbox.me/product/test-product/

**To Reproduce**
1. Enable "Smooth Scroll to Hash links" in Manage / Settings / Global Styles / Scripts
2. Click on a Woocommerce product tabs
3. Scrolls to top

**Expected behavior**
To switch to correct Woo tab without scrolling to top.

**What actually happens**
Switches to tab, but scrolls to top.

**Screenshots**

**Desktop (please complete the following information):**
- OS: Android
 - Browser Chrome
 - Oxygen 3.6

**Smartphone (please complete the following information):**
- Device: Huawei

**Additional context**

**Comment by KittenCodes** [comment]
@madjedo Please disable smooth scroll in Oxygen. Next, add a Code Block element to the top of your Main template and add the following code to the JavaScript tab. The code should allow smooth scroll to work, but exclude the Product Tabs:

```
// Select all links with hashes
jQuery('a[href*="#"]')
  // Remove specific links
  .not('[href="#tab-description"]')
  .not('[href="#tab-additional_information"]')
  .not('[href="#"]')
  .not('[href="#0"]')
  .click(function(event) {
    // On-page links
    if (
      location.pathname.replace(/^\//, '') == this.pathname.replace(/^\//, '') 
      && 
      location.hostname == this.hostname
    ) {
      // Figure out element to scroll to
      var target = jQuery(this.hash);
      target = target.length ? target : jQuery('[name=' + this.hash.slice(1) + ']');
      // Does a scroll target exist?
      if (target.length) {
        // Only prevent default if animation is actually gonna happen
        event.preventDefault();
        jQuery('html, body').animate({
          scrollTop: target.offset().top
        }, 1000, function() {
          // Callback after animation
          // Must change focus!
          var $target = jQuery(target);
          target.focus();
          if ($target.is(":focus")) { // Checking if the target was focused
            return false;
          } else {
            $target.attr('tabindex','-1'); // Adding tabindex for elements not focusable
            $target.focus(); // Set focus again
          };
        });
      }
    }
  });
```

**Comment by madjedo** [comment]
Who knows where else your smooth scroll will cause bugs. I am not using your code.
