### ISSUE TITLE
the_excerpt() is not working for posts built with oxygen builder NOTE: BREAKS SEO PLUGSINs AS WELL

### ISSUE THREAD

**Issue by gvanbrunt** [soflyy/oxygen-bugs-and-features#1933]
**Describe the bug**
I used Easy Post to create a post page. Gutenburg posts show excerpts automatically. Oxygen posts are blank. They work if you manually enter text in the excerpt box.

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
Yes

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
Yes

http://outstanding-salamander.w6.wpsandbox.pro/

**To Reproduce**
1. Create a post using gutenburg with some text.
2. Create a post using Oxygen builder.
3. Create a "post page" using Easy Post.
4. Only the Gutenburg post has any text from the excerpt.

**Expected behavior**
Excerpt text should be generated automatically if manul text has not been set.

**What actually happens**
no text is generated. Even if you change to the_content() in the PHP template it still outputs nothing.

**Screenshots**
![2021-02-22_16-38-26](https://user-images.githubusercontent.com/1278955/108773798-e1aaa580-752c-11eb-95c3-92a6a05603b5.jpg)

**Desktop (please complete the following information):**
- OS: Windows
 - Browser Chrome
 - Oxygen Version 3.6

**Smartphone (please complete the following information):**
N/A

**Additional context**
None

**Comment by gvanbrunt** [comment]
Also breaking SEO plugins as they don't seem to be reading the text correctly. Both Rank Math and Yoast are giving incorrect advice. For example, only claiming keywords appear once when there are many times more appearances than that. The one it does see is from the page title which appears in Gutenburg...

**Comment by KittenCodes** [comment]
> Only the Gutenburg post has any text from the excerpt.

This is because Oxygen-designed posts don't have any content in the Content area, or in the Excerpt box. You would need to add some text to one of those boxes for the snippet to appear when using the Easy Posts element.
