### ISSUE TITLE
How to limit posts (pages) displayed by the repeater? 

### ISSUE THREAD

**Issue by andmcspadden** [soflyy/oxygen-bugs-and-features#1934]
**Describe the bug**
*A clear and concise description of what the bug is.*
I tried to follow this video, but my site is not showing the same options.. (3m08s) IN the video it shows - "how many posts?" I don't have that.. 
my setting is "posts per page" - am I doing something wrong?
 https://oxygenbuilder.com/docu.../builder-elements/repeater/

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
***Yes**

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
*If yes, provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*

https://oxygen-q28tvpcw7gmdl.oxygen-demo.qsandbox.me/?post_type=ct_template&p=9&ct_builder=true

**To Reproduce**
1. Go to 'builder'
2. Click on 'repeater' > "query" > "count"
3. See error

**Expected behavior**
*A clear and concise description of what you expected to happen.*
in video it show "how many posts?" // specify number
**What actually happens**
*A clear and concise description of what happens instead of the expected behavior.*
I only get "posts per page" I only want 5 posts in my entire query- not 5 posts per page..

**Screenshots**
*If applicable, add screenshots to help explain your problem.*

**Desktop (please complete the following information):**
 - Oxygen Version [e.g. 2.2 Alpha]

**Smartphone (please complete the following information):**
 - Oxygen Version [e.g. 2.2 Alpha]

**Additional context**
*Add any other context about the problem here.*
How do I limit pages on my repeater?

**Comment by jasonwilliamsau** [comment]
WordPress pulls all posts in a query so it can handle pagination.  The `count` field maps agains `posts_per_page` to return the desired number of posts. 

An option to hide the pagination would be nice. An there's some other issues such as:
duplicate IDs https://github.com/soflyy/oxygen-bugs-and-features/issues/432
and placement of the pagination in the container 
https://github.com/soflyy/oxygen-bugs-and-features/issues/959

**Comment by andmcspadden** [comment]
It seems like a bug because I'm the how to video on the oxygen website it
shows more settings for count parameter... You can limit the number of
posts based on the demo on website.

**Comment by KittenCodes** [comment]
> IN the video it shows - "how many posts?"

The "Count" tab still works in the same way - however, the "How many posts?" text has been removed.

If you want to show 5 posts without pagination, you would need to use a manual query. Here's an example:

post_type=post&posts_per_page=5&no_found_rows=true
