### ISSUE TITLE
Full-with bug in version 3.7

### ISSUE THREAD

**Issue by Desatado85** [soflyy/oxygen-bugs-and-features#1937]
There is a bug showing in front and backend. I can't reproduce on your sandbox, because there is still running version 3.6.1. On this older version all is working fine. On version 3.7 when I make a section full-width it destroys the layout completly. I just installed the 3 oxygen plugins. The Bug was when I chose flexbox - horizontal with 2 divs. 

I found out now, the problem is when I make the 2 divs inside the section both 50% = 100% version 3.7 makes shows only 25%. If I choose 100% for both (200%) it shows the divs width correctly. 

 Bug in version 3.7:
![20210223_185257](https://user-images.githubusercontent.com/79537108/108889237-70daba80-760c-11eb-9ac6-da0e6f8e348a.jpg)

Correct with version 3.6.1:
![20210223_185323](https://user-images.githubusercontent.com/79537108/108890026-55bc7a80-760d-11eb-969c-0cce56b8f26b.jpg)

**Comment by Desatado85** [comment]
Same problem with grid layout

**Comment by Desatado85** [comment]
I think that you have in version 3.7 a pre-definition of width for flexbox and grid. So when I choose a width inside the editor, it calculates to your pre-definition.

Version 3.6.1 works great. Choose 50% and it is 50% and not 25%.

**Comment by Spellhammer** [comment]
Can't replicate. Please send us details for an environment where we can see the issue occurring: https://oxygenbuilder.com/support.
