### ISSUE TITLE
I don't see any of the new Composite Elements

### ISSUE THREAD

**Issue by tuqqo** [soflyy/oxygen-bugs-and-features#1939]
**Describe the bug**
See the topic title. Yes, i have an Agency License.

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
Yes

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
No

**To Reproduce**
Its happening on all of my sites.

**Expected behavior**
The new Elements should be shown in the "ADD" Menu

**What actually happens**
The new Elements are not shown.

**Comment by tuqqo** [comment]
someone on facebook wrote me this:

Note: If you owned an Oxygen Agency license prior to February 12th, 2021 and don't see Composite Elements (denoted by small Oxygen icon in top left corner) in the +Add Pane after updating, please go to Oxygen > Settings > License in the WordPress admin panel, remove your Oxygen license, submit the empty field, then re-enter and re-submit your Oxygen license. If that procedure doesn't work, contact us via https://oxygenbuilder.com/support and we will assist.

This worked, but i don't see the blue icons, which indicates those new composite elements.

**Comment by tuqqo** [comment]
als this seems not to be a permanent solution as the leements gets randomly lost again on various sites....

**Comment by KittenCodes** [comment]
> This worked, but i don't see the purple icons, which indicates those new composite elements.

Please clear your server, site and browser cache.

If you continue to have problems, please open a support ticket: https://oxygenbuilder.com/support.
