### ISSUE TITLE
Pro Menu does not close on anchor link click (within same page)

### ISSUE THREAD

**Issue by leem2209** [soflyy/oxygen-bugs-and-features#1945]
**Describe the bug**
I have a menu with "about" (page link), "services" (anchor link to hompage/#services" and "contact" (anchor link to homepage/#contact)

In the off-canvas menu (mobile view), if I'm on the home page and I click an anchor menu link, the off-canvas menu doesn't close so it looks like it doesn't work. Behind the menu it is scrolling to the relevant section but the user doesn't realise this.

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
*Yes*

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
Yes, happens on sandbox too: http://comfortable-quoll.w6.wpsandbox.pro/

**To Reproduce**
1. Go to 'https://theartybuddha.com/' (on mobile view)
2. Click on 'menu'
3. Click on 'Services or Contact'
4. Off canvas menu does not go away

**Expected behavior**
The page scrolls to the anchor section (Services or Contact) and the off-canvas menu closes

**What actually happens**
The page scrolls to the anchor section but the off-canvas menu still shows and doesn't close (when navigating to the same page)

**Smartphone (please complete the following information):**
All mobile device views (iphone, android, replicated phone in chrome tools & firefox)

**Comment by KittenCodes** [comment]
@leem2209 

Please add the following code to the JavaScript tab of a Code Block to close the Pro Menu off-canvas menu when a hash link is clicked:

```js
jQuery(document).ready(function() { 
  jQuery('a[href^="#"]').click(function() { 
    jQuery('.oxy-pro-menu-mobile-close-icon').trigger('click');
  }); 
}); 
```

**Comment by leem2209** [comment]
Hi, that’s not working.

I’ve added a code block to the header/footer template beneath the footer (last item on the template)

I also deleted the “hello world” from the PHP tab as it was showing “Hello world” beneath the footer.

Should I add the code block somewhere specific?

**Comment by leem2209** [comment]
@KittenCodes - any further update on this?

**Comment by leem2209** [comment]
@KittenCodes - chasing this up again as no response from last reply...

why isn’t your solution working?

**Comment by creativenomads** [comment]
I'm a current user using the most up to date version of Oxygen and this is still an issue. Please advise for the proper fix for this.

**Comment by gdnwebmedia** [comment]
> @leem2209
> 
> Please add the following code to the JavaScript tab of a Code Block to close the Pro Menu off-canvas menu when a hash link is clicked:
> 
> ```js
> jQuery(document).ready(function() { 
>   jQuery('a[href^="#"]').click(function() { 
>     jQuery('.oxy-pro-menu-mobile-close-icon').trigger('click');
>   }); 
> }); 
> ```

This code is not working

**Comment by jschuh23** [comment]
I am having this same issue. I've noticed many other code options to use, but am wondering what is the preferred method considering all of the comments about this bug are from 2021 or later. Thanks!!

**Comment by joeknouse** [comment]
Still an issue.

**Comment by scottconvertlion** [comment]
I was struggling with this also. Here is the correct code to fix it. Just a minor change to the jQuery Selector.

`jQuery(document).ready(function() { 
  jQuery('a[href^="#"]').click(function() { 
    jQuery('.oxy-pro-menu-mobile-close-icon').trigger('click');
  }); 
}); `

**Comment by SummisDesign** [comment]
Thank you @scottconvertlion .

This worked just fine for me !
