### ISSUE TITLE
[DONE in 4.8 beta 1] Template Switcher

### ISSUE THREAD

**Issue by flabernardez** [soflyy/oxygen-bugs-and-features#1946]
In template edition view, a switcher button (or dropdown) witch permits change tamplate in the same view, without go to WordPress Dashboard or Frontend.

While editing, you could quickly switch between templates and change that style option you have just changed in that view, for example.

Figma for example includes a quick pages switcher in its sidebar, above layer display. I miss this feature to be near of Save button, back to WP, Manage or into Estructure. It could be also placing near "Previewing" dropdown, with a text that inform you which template are you now editing. That information I miss it too...

Thanksss

**Comment by srikat** [comment]
Until these are added natively,

https://wordpress.org/plugins/wpdevdesign-oxygen-navigator/

https://wordpress.org/plugins/wpdevdesign-oxygen-currently-editing/

https://oxyplugins.com/doc/navigator/

**Comment by Spellhammer** [comment]
We're looking into this. Ideally this will be a bit more robust than in the original request, and allow quick switching between posts, pages, templates, etc... from directly within Oxygen.

**Comment by flabernardez** [comment]
Amaaaaazingggg!

*Thanks so much!*

**Comment by musik92** [comment]
@Spellhammer you might want to check out Editor Enhancer's implementation: https://editorenhancer.com/docs/context-switching/

**Comment by enterprising-martin** [comment]
Ooh, a big yes please for this!

**Comment by Spellhammer** [comment]
This has been implemented in 4.8, which is currently available as a beta.
