### ISSUE TITLE
[2.2.1] Toggle doesn't toggle (javascript error)

### ISSUE THREAD

**Issue by ascripter** [soflyy/oxygen-bugs-and-features#195]
**Describe the bug**
Toggle element on a plain page doesn't work. There is a javascript error
> `TypeError: Argument 1 of Window.getComputedStyle does not implement interface Element.[Weitere Informationen]`

in this code part in the last line `jQuery(toggle_target).toggle();` 

    <script type="text/javascript">

      jQuery(document).ready(function() {
        oxygenVSBInitToggleState();
        oxygenVSBInitToggleClick();
      });

      oxygenVSBInitToggleState = function() {

        jQuery('.oxy-toggle').each(function() {
        
          var initial_state = jQuery(this).attr('data-oxy-toggle-initial-state'),
             toggle_target = jQuery(this).attr('data-oxy-toggle-target'),
                     active_class = jQuery(this).attr('data-oxy-toggle-active-class');
        
          if (initial_state == 'closed') {
            if (!toggle_target) {
              jQuery(this).next().hide();
            } else {
              jQuery(toggle_target).hide();
            }
            jQuery(this).children('.oxy-expand-collapse-icon').addClass('oxy-eci-collapsed');
                      jQuery(this).removeClass(active_class)
          }
                  else {
                      jQuery(this).addClass(active_class)
                  }
        });
      }

      oxygenVSBInitToggleClick = function() {

        jQuery("body").on('click', '.oxy-toggle', function() {
          
          var toggle_target  = jQuery(this).attr('data-oxy-toggle-target'),
                      active_class   = jQuery(this).attr('data-oxy-toggle-active-class');

                  jQuery(this).toggleClass(active_class)
                  jQuery(this).children('.oxy-expand-collapse-icon').toggleClass('oxy-eci-collapsed');

          if (!toggle_target) {
            jQuery(this).next().toggle(); 
          } else {
            jQuery(toggle_target).toggle();   
          }
        });
      }
    </script>

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
Yes

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
No, it works in the sandbox as expected

**To Reproduce**
No idea. The weird thing: it used to work around two weeks ago (not sure if this was before installing Oxygen 2.2.1)

**Expected behavior**
The toggle should toggle

**What actually happens**
The toggle doesn't toggle. However the classes `toggle-xxxx-expanded` and `oxy-eci-collapsed` *are* toggled on their respective elements.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/8597615/55228585-bcb33800-521a-11e9-828c-6dac0388f717.png)

**Desktop (please complete the following information):**
- Win 10
- Firefox 66.0.2
- Oxygen 2.2.1

**Smartphone (please complete the following information):**
- Device: Sony Xperia
- OS: Android 6
- Chrome

**Additional context**
Behavior observable on both devices, PC and smartphone.

**Comment by KittenCodes** [comment]
Hi @ascripter, If you're still having problems with this in Oxygen 2.4.1+, please email support@oxygenbuilder.com.
