### ISSUE TITLE
Custom CSS breaks on copy-paste from external source

### ISSUE THREAD

**Issue by devisuelekant** [soflyy/oxygen-bugs-and-features#1951]
**Describe the bug**
*Pasting CSS code from an external source into the oxygen css editor sometimes cause the subsequent CSS to break on frontend.*

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
*Yes*

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
http://wicked-monkey.w6.wpsandbox.pro/

**To Reproduce**
*All I did on the sandbox install was adding two stylesheets. In the first one I pasted the code that was causing the problem on my own site. On the second stylesheet, I added code to turn the body background red.*

1. Go to my sandbox install
2. Enter the Oxygen editor through any template
3. copy the css from stylesheet 'cause-css-to-break' and paste it to any oxygen site stylesheet with subsequent stylesheets
4. notice how the subsequent stylesheets still do their thing within the editor, bot not on the frontend

I suspect it happens when copying from the Chrome inspector, but I couldn't reproduce it with just any random copy-paste from there.

**Expected behavior**
*Working CSS*

**What actually happens**
*Broken CSS*

**Desktop (please complete the following information):**
- Windows 10
 - Chrome

**Additional context**
*Please note that in this case, it's a piece of svg code that causes the issue, but I encountered it before with shorter, more straight forward code. Up until now i just removed the faulty cause and typed it myself to solve the issue, but since the SVG code it too long for that I realized I should report this.*

**Comment by devisuelekant** [comment]
After some more testing I'm no longer sure if it's a oxygen issue. When copying a ::after element from the Chrome Inspector containing content: url('...'), it seems to neglect the ''. As a result, the } sign in the svg code seems to close the CSS therefor causing any follwoing CSS to be ignored. I still don't understand why this doesnt affect the CSS inside the Oxygen editor though. I'm not enough o a coder to really see through the surface and understand what's going on.

**Comment by KittenCodes** [comment]
@devisuelekant 

If CSS is breaking Oxygen's stylesheets, it means that there's a syntax error somewhere within the CSS.

When copy/pasting from the inspector, you're best to open the stylesheet directly and copy the code.
