### ISSUE TITLE
3rd Sticky Row does not center align

### ISSUE THREAD

**Issue by ducktape4004** [soflyy/oxygen-bugs-and-features#1952]
**Describe the bug**
*A clear and concise description of what the bug is.*

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
*If yes, provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*

**MAIN** : https://oxygen-q8zv9q5h5qqdl.oxygen-demo.qsandbox.me/?ct_template=main&ct_builder=true

**SINGULAR** : https://oxygen-q8zv9q5h5qqdl.oxygen-demo.qsandbox.me/sample-page/

**To Reproduce**

1.  Create DIV & Center Align
2.  Install Header in DIV
3.  Create Sticky

**Expected behavior**
3rd Sticky Row should center align

**What actually happens**
3rd Sticky Row does not center align

**Screenshots**
See Sandbox

**Desktop (please complete the following information):**
- OS: Windows 10 updated
- Browser : Firefox and Chrome
- Oxygen Version : 3.7 production

**Smartphone (please complete the following information):**
Sticky does not work in smaller size screen

**Additional context**
*Add any other context about the problem here.*

**Comment by KittenCodes** [comment]
@ducktape4004 Please set the left and right margin of the Header Builder element to "auto" via Advanced > Size & Spacing. I've done this for you on the Sandbox site so that you can see it working.

**Comment by ducktape4004** [comment]
Thank you KittenCodes,

Appreciate the help.

Regards,

ducktape
