### ISSUE TITLE
Accessibility

### ISSUE THREAD

**Issue by larsburkhardt** [soflyy/oxygen-bugs-and-features#1953]
I'm very interested in the Oxygen Builder, but a necessary feature for me (and many others) is acccessibility. That's totally missing in Oxygen, for example the navigation is not accessible for keyboards (cannot enter the submenus). ARIA attributes are missing, too.
Do you plan to improve Oxygen regarding a11y?
Thanks!

**Comment by KittenCodes** [comment]
@larsburkhardt 

If you would like to see increased accessibility in a future release of Oxygen, please add a vote to the relevant feature request(s) here: https://github.com/soflyy/oxygen-bugs-and-features/labels/General%20-%20Accessibility%2FStandards%2FSEO
