### ISSUE TITLE
When out of full screen mode the oxygen block in gutenberg breaks the page

### ISSUE THREAD

**Issue by JKdreaming** [soflyy/oxygen-bugs-and-features#1954]
**Describe the bug**
*A clear and concise description of what the bug is.*

When out of fullscreen mode the block stretches over the bounds of the viewable window and you can't scroll past the edge horizontally in the gutengerg editor. 

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
*Yes/No*

yes

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
*If yes, provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*

https://oxygen-qmpk5fg9twqdl.oxygen-demo.qsandbox.me/wp-admin/post.php?post=10&action=edit

**To Reproduce**
1. Create a full Height/Width section
2. Go back to the admin editor
3. Turn off full screen view
4. Breaks the viewable space

**Expected behavior**
*A clear and concise description of what you expected to happen.*
Not to break the editor viewport
**What actually happens**
*A clear and concise description of what happens instead of the expected behavior.*

Here's a video: https://www.loom.com/share/3037a003ea894110a0eb6e174d2c26d9

**Screenshots**
*If applicable, add screenshots to help explain your problem.*

**Desktop (please complete the following information):**
- OS: [e.g. Mac OS]
 - Browser [chrome]
 - Oxygen Version [3.7]

**Smartphone (please complete the following information):**
 - Oxygen Version [e.g. 2.2 Alpha]

**Additional context**
*Add any other context about the problem here.*

**Comment by Shemzone** [comment]
I didn't see it mentionned here but this occurs only with Oxygen Gutenberg Integration (1.4) and Oxygen (3.7).
With Oxygen Gutenberg Integration activated, the sidebar is thrown somewhere outhere. If Oxygen Gutenberg Integration is deactivated, the sidebar is back to its place.
![with-Oxy-gutenberg-integration-activated](https://user-images.githubusercontent.com/11276853/109996382-753f5b80-7d0f-11eb-905f-c67a89aa26dd.jpg)
![without-Oxy-gutenberg-integration](https://user-images.githubusercontent.com/11276853/109996474-8ee0a300-7d0f-11eb-8cfb-d9940e055876.jpg)

**Comment by KittenCodes** [comment]
@JKdreaming @Shemzone Please set the block width to 100% and not 100vw. You will still get a full-width block, but it won't over-run in Gutenberg.
