### ISSUE TITLE
Dynamic Callback in Static Method

### ISSUE THREAD

**Issue by maltmann-muc** [soflyy/oxygen-bugs-and-features#1955]
**Describe the bug**
Oxygen 3.7
component-framework/includes/conditions.php, line 1037
In static method eval_condition(), a dynamic callback is called

**Screenshots**
<img width="1130" alt="Bildschirmfoto 2021-03-03 um 10 30 25" src="https://user-images.githubusercontent.com/51136650/109785621-979c8080-7c0c-11eb-8dd3-000a8216de73.png">

**Comment by maltmann-muc** [comment]
Issue still exists in 3.8 RC 2

**Comment by maltmann-muc** [comment]
Issue still exists in 3.8 final.

**Comment by maltmann-muc** [comment]
Issue still exists in 4.0 beta 1

**Comment by Spellhammer** [comment]
Fixed in Oxygen 4.1 beta 1.
