### ISSUE TITLE
oxygen_lock_post_edit_mode error when saving Custom Fields Group

### ISSUE THREAD

**Issue by raphaelparent** [soflyy/oxygen-bugs-and-features#1956]
**Describe the bug**
When I save a custom field group I get this error.

```
Notice: Undefined index: oxygen_lock_post_edit_mode in /Users/raphael/Documents/hamak/elexpertise/app/bedrock/web/app/plugins/oxygen/component-framework/admin/admin.php on line 107
```

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**

The only relevant one is the log file and I haven't found anything interesting in them.

**To Reproduce**
1. Install Oxygen
2. Install ACF (I have the pro version)
3. Create a new field group and save.

**Expected behavior**
Reload the page saying it saved.

**What actually happens**
Shows an error page even though it actually saved

**Versions**
 - Oxygen Version 3.7
 - ACF Pro Version 5.9.5
 - PHP Version 7.4.1
 
 I also see the "Edit with Oxygen" section on my custom field group, which doesn't make sense at all.

**Comment by raphaelparent** [comment]
Disabling the oxygen editor on acf custom fields solves the problem.

**Comment by prionkor** [comment]
still all index should be checked before accessing.
