### ISSUE TITLE
Flex-wrap for Menu are not working well

### ISSUE THREAD

**Issue by WilliamVercken** [soflyy/oxygen-bugs-and-features#1957]
The bug :

![image](https://user-images.githubusercontent.com/1272792/109891860-200d3680-7c8a-11eb-83e0-bd523287f384.png)

I want the mobile menu to show only under 480px. So I need my menu to be visible.

You can see the bug here : http://wicked-pollan.w6.wpsandbox.pro/ (I don't know if I have to give the link with the login pass)

Or you can copy/paste this shortcode to generate a template : 
`[ct_section ct_sign_sha256='16929fab3be388fb1c60b5f83549f76eb5011280b255485c126775ac3d85406b' ct_options='{"ct_id":1,"ct_parent":0,"selector":"section-1-8"}'][oxy-pro-menu ct_sign_sha256='c1b785914801e24fd7e76cf529273bbac2489824113e7e973c636f962b588091' ct_options='{"ct_id":2,"ct_parent":1,"selector":"-pro-menu-2-8","original":{"menu_id":"2","oxy-pro-menu_show_mobile_menu_below":"phone-portrait","oxy-pro-menu_menu_item_padding_padding-top":"20","oxy-pro-menu_menu_item_padding_padding-left":"20","oxy-pro-menu_menu_item_padding_padding-right":"20","oxy-pro-menu_menu_item_padding_padding-bottom":"20","border-top-color":"#000000","border-right-color":"#000000","border-bottom-color":"#000000","border-left-color":"#000000","border-top-width":"3","border-right-width":"3","border-bottom-width":"3","border-left-width":"3","border-top-style":"solid","border-right-style":"solid","border-bottom-style":"solid","border-left-style":"solid","margin-left-unit":"auto","margin-right-unit":"auto","margin-right":"0","display":"flex","align-items":"center","justify-content":"center","flex-wrap":"wrap","align-content":"center","width":"100","width-unit":"%"}}'][/oxy-pro-menu][/ct_section]`

1. Create a template.
2. Add a section.
3. Add a menu pro (you must have a long menu).
4. Put the mobile menu at 480px only. 
5. Put a width 100% and a border to see the limit of your menu. And some spacing between elements.
6. Change the layout parameters, put "display: flex" and "flex-wrap:wrap".
7. Change the size of your browser to see the problem.

- OS: Windows
 - Browser: Chrome
 - Oxygen Version 3.7

**Comment by srikat** [comment]
I wouldn't call this a bug. This is more the case of software not meeting user's expectations.

Setting flex-wrap to wrap for the Pro Menu component isn't going to help because it should be set to the `ul` that is nested deep inside the Pro Menu. At the moment, there is no built-in control for this. So I guess it is a feature request.

The fix is to simply add this custom CSS at Manage > Stylesheets:

```
.oxy-pro-menu-list {
  flex-wrap: wrap;
}
```

or create a Selector for `.oxy-pro-menu-list` at Manage > Selectors and visually set flex-wrap to wrap.

**Comment by WilliamVercken** [comment]
Hi @srikat ,
I used a custom css to solve the problem yes. 
But the question is : what's the point of having a layout option in the Menu if this not working at all ? I call this a bug... 

Is there a way to solve my problem (the screenshot) without using custom CSS (with of without flexbox, nevermind) because I didn't figure it out and I don't think this is a normal behavier.

**Comment by KittenCodes** [comment]
@WilliamVercken 

It's not possible to do this using the controls in the builder. You would need to use the CSS suggested by @srikat .

**Comment by srikat** [comment]
> But the question is : what's the point of having a layout option in the Menu if this not working at all ? I call this a bug...

Generally speaking, the CSS that we ask Oxygen to generate for a component applies directly to that component only, not to its child elements.
