### ISSUE TITLE
DONE: To be able to disable a Section or a Div in the back-end

### ISSUE THREAD

**Issue by mikeingz** [soflyy/oxygen-bugs-and-features#196]
**Describe the feature you'd like to see included in Oxygen.**
To be able to disable a Section or a Div in the back-end.
So it won't appear in the front-end but will still be available in the back-end.
(and I don't talk about adding a 'display:none' to that section).

![image](https://user-images.githubusercontent.com/2438157/55235251-12fa9800-5268-11e9-81af-728a6975a9ee.png)

**What are the use cases for this feature?**
When you are designing a page, sometimes you try different versions of the same section and you (or your client) are not sure which one you prefer. So it's a good way to still keep a copy of that section in your back-end. Without duplicating the full page or creating a Reusable part.

**Examples of this feature or functionality.**
even Visual Composer has this feature for his Row element :)

**Comment by BruceTunkel** [comment]
great idea

**Comment by busystreet** [comment]
This is a great idea.

**Comment by greenyboy** [comment]
Great Idea

**Comment by blakecogs** [comment]
Excellent idea.

**Comment by Noz5** [comment]
+1

**Comment by magiaslab** [comment]
+1

**Comment by ciaoweb** [comment]
Fantastic idea!

**Comment by wplit** [comment]
Definitely useful if this would cause these specific sections not to be output on the front at all (not just hiding it).

**Comment by RoscoeB** [comment]
The idea in the FB group to be able to disable according to mobile, tablet or desktop would make it more useful.

**Comment by WrongGuy** [comment]
Perfect Idea. 
I was also thinking of double click and change the name of section, instead of clicking burger icon and select rename.

**Comment by totemdomains** [comment]
would like to second @RoscoeB :
(in Divi) the ability to turn off per device type (mobile, tablet, desktop) is _**incredibly**_ handy for solving tricky client design requests in a relatively quick way. ;)

**Comment by Anticosti** [comment]
A great idea. Would also need an "Eye" icon to quickly monitor which section(s) is/are hidden.

**Comment by srikat** [comment]
Workaround: https://wpdevdesign.com/how-to-disable-sections-in-oxygen/

**Comment by creativonline** [comment]
Also add disable section with a date and time picker - to disable automatically for easter/christmas/new year sections if this feature will be implemented

**Comment by Spellhammer** [comment]
This is now possible with the Conditions feature: just set a condition that always evaluates to false, but make sure the in-editor behavior is "always show." This will prevent any of the element's markup from being output, so a much better solution than display:none.

>> Also add disable section with a date and time picker - to disable automatically for easter/christmas/new year sections if this feature will be implemented

Also possible with Conditions.

**Comment by Deanphillips** [comment]
> This is now possible with the Conditions feature: just set a condition that always evaluates to false, but make sure the in-editor behavior is "always show." This will prevent any of the element's markup from being output, so a much better solution than display:none.
> 
> > > Also add disable section with a date and time picker - to disable automatically for easter/christmas/new year sections if this feature will be implemented
> 
> Also possible with Conditions.

That's great! Would be great to still have it the way Mike suggested though (in the tree)

**Comment by demetre19** [comment]
+1
