### ISSUE TITLE
DONE: Make Oxygen load faster please

### ISSUE THREAD

**Issue by michacassola** [soflyy/oxygen-bugs-and-features#1960]
**Describe the feature you'd like to see included in Oxygen.**
I would like Oxygen to load within 5 seconds or less. If not otherwise possible you could make a Chrome extension that holds all kinds of assets already.

**What are the use cases for this feature?**
Slow building is really annoying. Making small changes on a lot of pages becomes a nightmare and you can't even split up the work.

**Examples of this feature or functionality.**
NA

**Comment by greggdev** [comment]
+1

**Comment by Edzerd** [comment]
This is my main problem with Oxygen Builder: loads far to slow:
With my new laptop (Ryzen 5 4500u) a simple page takes 13 seconds!

**Comment by wpsumo** [comment]
In my case it is crashing the server (AWS EC2 with several CPU and enough memory to just load oxygen) since I have too many dynamic data fields. Replicated on local as well with a powerful enough Macbook pro with allocated full memory and cpu from the computer to local. Still crash the local server once loading oxygen template which include acf dynamic data.

I think this isn't fixed since the issue is dep in the core while saving and fetching shortcodes from the database.

**Comment by Spellhammer** [comment]
@wpsumo How many dynamic data fields do you have on the post or template that's crashing?

**Comment by greggdev** [comment]
This was supposed to be about Oxygen builder loading times. For me Oxygen loads the same no matter if I use a low end machine or a 24 core machine, it loads some assets remotely and then loads up the memory in browser.  I get crashes in loading too much Tailwind css in Google Chrome, and we find that loading is fastest in Edge Chrome.  

But as far as dynamic data have several sites with 20 to 50 dynamic data fields, and a few as high as 80 ddf..  Never have a problem.. The confirmed bugs that hurt our development team are not fixed and we have stopped production for some clients

Dynamic data not showing in a 3rd level of template (template Z inherited from template Y inherited from template X) #1881
Inner Content Div doesn't apply to Inner Content Templates #1930

**Comment by greggdev** [comment]
> In my case it is crashing the server (AWS EC2 with several CPU and enough memory to just load oxygen) since I have too many dynamic data fields. Replicated on local as well with a powerful enough Macbook pro with allocated full memory and cpu from the computer to local. Still crash the local server once loading oxygen template which include acf dynamic data.
> 
> I think this isn't fixed since the issue is dep in the core while saving and fetching shortcodes from the database.

This was supposed to be about Oxygen builder loading times. For me Oxygen loads the same no matter if I use a low end machine or a 24 core machine, it loads some assets remotely and then loads up the memory in browser. I get crashes in loading too much Tailwind css in Google Chrome, and we find that loading is fastest in Edge Chrome.

But as far as dynamic data we have several sites with 20 to 50 dynamic data fields, and a few as high as 80 dynamic fields . We use both ACF, Toolset and MetaBox and never have a problem with workstation dev or on our servers.
The confirmed bugs that hurt our development team are not fixed and we have stopped production for some clients

Dynamic data not showing in a 3rd level of template (template Z inherited from template Y inherited from template X) #1881
Inner Content Div doesn't apply to Inner Content Templates #1930

**Comment by Edzerd** [comment]
>quote from greggdev: 'This was supposed to be about Oxygen builder loading times.': Exactly.

**Comment by wpsumo** [comment]
> How many dynamic data fields do you have on the post or template that's crashing?

@Spellhammer Around 150-170 `field_`  Some repeaters and different types of ACF fields. I use code block more often than the intigrated as it's often reduce Div's and extra spans and reduce limitations. Just thought it's worth to mentioned. Also fetching the_content() dynamically. 

Not sure if using more code blocks per fetch of dynamic data to use the div and UI to style each div or using less code blocks and echo divs around the fields cause less stress on the server and oxygen?

The template also have 2 reusable blocks.

**Comment by Spellhammer** [comment]
Since this request was made, we've made multiple big improvements to back-end loading times. Please open a new issue if you still experience slowness.
