### ISSUE TITLE
border does not set px unit by default

### ISSUE THREAD

**Issue by ramnathk** [soflyy/oxygen-bugs-and-features#1966]
**Describe the bug**
If I add a 1 px solid border, oxygen does not add 'px' unit to it by default. I need to switch units and come back to px for it to be applied.

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
yes

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
http://happy-vendace.w5.wpsandbox.pro?upass=7A7RHs48bvLl
The page called 'border bug' with a 1px border which is not set correctly on the front end

**To Reproduce**
https://vimeo.com/520028635/51a3f19355

**Expected behavior**
border width unit should be set by default
border-top-width: 1px;

**What actually happens**
the border width property is set as 
border-top-width: 1;

**Screenshots**
https://vimeo.com/520028635/51a3f19355

**Desktop (please complete the following information):**
- mac os
 - Chrome
 - Oxygen 3.7

**Comment by KittenCodes** [comment]
@ramnathk This happens usually when the "unset borders" button has been used. To resolve it, you should be able to change the unit to something else, save and then change it back to px.
