### ISSUE TITLE
DONE: Adding Custom Tags

### ISSUE THREAD

**Issue by mikeingz** [soflyy/oxygen-bugs-and-features#1968]
At first I was thinking about adding a UL and LI tags to the **DIV** & **Code Block** elements, so we could build proper List : 

![image](https://user-images.githubusercontent.com/2438157/110228526-c2544500-7f3c-11eb-9cc2-197f5e2ee52f.png)

In order to have something like this:
![image](https://user-images.githubusercontent.com/2438157/110228551-f7609780-7f3c-11eb-93ba-910f0ac6c750.png)

But how about adding a custom tag, just like for the size unit, where we can enter anything : 
![image](https://user-images.githubusercontent.com/2438157/110228598-5b835b80-7f3d-11eb-92bc-f72e1e9e7a6e.png)

Then we could enter any tags we want.

Less Limitation = More Power ;)

**Comment by LauGau** [comment]
I can just agree with Mike ;
There is some usefull tags but not used that often (ex: <figcaption>), it will be nice to be able to create our own.
Also <blockquote> is missing.

More generally about tags I would love to be able to switch some Text module to Heading module... (To be able to switch between a <p> and a <h3> or <div> if I want without having to create a new module and copy/paste the text just to change the tag...)

**Comment by alpabuz** [comment]
+1

**Comment by maltmann-muc** [comment]
+1

**Comment by AjmDigitalServices** [comment]
+1

**Comment by Eminencedigital** [comment]
+1

**Comment by DevCarlosGuerrero** [comment]
+1

**Comment by LordWhisper** [comment]
+1

**Comment by wpsumo** [comment]
+1 and allow none so codeblock can be clean and only output what's within the code block without a wrapper.

+1 for some more predefined such as <table> tags.

**Comment by chris-castillo-dev** [comment]
+10 to this. This is essential core functionality that's missing.

**Comment by ewokee** [comment]
+1

**Comment by Rados51** [comment]
+1

**Comment by adrien-robert** [comment]
+1

**Comment by ERROPiX** [comment]
For these who need this, I created a small code snippet for the div element https://www.facebook.com/groups/cleanplugins/permalink/495101971649590/

**Comment by khairulfaizi** [comment]
+1

**Comment by AlkoKod** [comment]
It will be nice to change the code block to be something else then DIV. I am building AJAX tabs and I need code block to be a UL and inside is query which generates <li>. Its the structure of AJAX tabs for jquery.

**Comment by MATTiVOLTARii** [comment]
+1
