### ISSUE TITLE
Font Rendering/Smoothing not the same as Google Fonts

### ISSUE THREAD

**Issue by kalaio** [soflyy/oxygen-bugs-and-features#1975]
**Describe the bug**
I'm not sure if this is a bug or the result of different margin/padding between elements making the font rendering a bit different

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
I didn't find anything related

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
http://prickly-ant.w6.wpsandbox.pro/2017/03/09/hello-world/

**Expected behavior**
The font rendering equal on evey website

**What actually happens**
I need a little help figuring out what am I doing wrong with the way I'm building my website with Oxygen.
The font rendering/smoothing seems a bit off/blurred every time I compare my website with Google Fonts and Oxygen Sandbox (case study attached).

I'm using for this example the Google Font Overpass, 15px and color #202124.

Maybe I'm being a little picky but the text rendered on my website doesn't look the same as google Fonts and Oxygen sandbox. When I analyse big chunk of text like blog posts it is more evident.

I noticed the font smoothing: antialiased have had effect on text smoothing but it doesn't seem to effect anymore (by the way I don't have this option selected).

**Screenshots**
https://imgur.com/a/d4c1XdE

Can you please help? I might be doing something wrong.

**Comment by KittenCodes** [comment]
@kalaio I'm sorry, but I'm not sure that I understand what the problem is. Please can you explain what I need to do on the Sandbox site to see the issue?

**Comment by kalaio** [comment]
Hello KittenCodes, if you open the screenshot url you'll see on the zoom in image the letters are not displayed the same on my site comparing to sandbox and google fonts.

**Comment by KittenCodes** [comment]
@kalaio I have opened the screenshot. However, if the issue is only occurring when zooming in, then there's likely nothing we can do as zoom will distort things.

Is the issue occurring on Sandbox or only on your site? If it's only on your site, please open a support ticket so that we can take a look: https://oxygenbuilder.com/support.

If it's occurring on Sandbox, please let me know exactly what I need to do to see the problem.
