### ISSUE TITLE
Warning : strpos() expects parameter 1 to be string

### ISSUE THREAD

**Issue by FeliceLeo** [soflyy/oxygen-bugs-and-features#1978]
**Describe the bug**
*A clear and concise description of what the bug is.*

I am using Oxygen Builder Version 3.7.1  and get the following error on all product pages:
**Warning
: strpos() expects parameter 1 to be string, array given in
/home/customer/www/URL.com/public_html/wp-content/plugins/oxygen/component-framework/api/oxygen.element-selector.class.php
on line
197**

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
*Yes/No*

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
*If yes, provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*

**To Reproduce**

**Expected behavior**
*A clear and concise description of what you expected to happen.*

**What actually happens**
*A clear and concise description of what happens instead of the expected behavior.*

**Screenshots**
*If applicable, add screenshots to help explain your problem.*

**Desktop (please complete the following information):**
 - Oxygen Version [e.g. 2.2 Alpha]

**Smartphone (please complete the following information):**
 - Oxygen Version [e.g. 2.2 Alpha]

**Additional context**
*Add any other context about the problem here.*

**Comment by Journeytojah** [comment]
Any update on this issue? We are migrating a client's website and encountered the same error on product pages after moving it to a local environment.

**Comment by Spellhammer** [comment]
Fixed in Oxygen 4.1 beta 1.
