### ISSUE TITLE
Section Indictor

### ISSUE THREAD

**Issue by stefan1959** [soflyy/oxygen-bugs-and-features#1979]
If you use a menu as well to link to the section anchors ie #section-25-175 in the sandbox the styling of the menu gets changed.
I'm not sure if this is a bug or we can't use menus as well to link to the section.

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
*Yes

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
yes I use http://misty-wolf.w6.wpsandbox.pro

*If yes, provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*
one click login is 
http://misty-wolf.w6.wpsandbox.pro?upass=RXm7Nf0vTe0

**To Reproduce**
Just check home page, top menu get overwritten with blue of the section dot color.
Menu should not get effected. Its should have it own styling.

Code in the Section Indicator is doing this, I think these lines, and the last line changes the menu background color.

   jQuery("[href='#" + entry.target.id + "'] .oxel_section_indicator__label").removeClass('oxel_section_indicator__label--hidden');
		jQuery("[href='#" + entry.target.id + "']").css({
          'opacity': '1',
          'background-color': jQuery("[href='#" + entry.target.id + "']").css('color') });

Steve

**Comment by KittenCodes** [comment]
@stefan1959 Unfortunately, the Sandbox login doesn't work. Do you happen to have the username and password?

**Comment by Spellhammer** [comment]
Reported internally, fix pending.

**Comment by Spellhammer** [comment]
Fixed. Re-import the Section Indicator and you should see that it now works as expected.
