### ISSUE TITLE
PHP Notice: Undefined offset, index, and variables

### ISSUE THREAD

**Issue by Daniel-Richard** [soflyy/oxygen-bugs-and-features#198]
PHP Notice:  Undefined offset: 21 in /home/public_html/wp-content/plugins/oxygen/component-framework/includes/revisions.php on line 44

PHP Notice:  Trying to get property 'meta_value' of non-object in /home/public_html/wp-content/plugins/oxygen/component-framework/includes/revisions.php on line 44

PHP Notice:  Undefined index: pricing_box_graphic_background in /home/public_html/wp-content/plugins/oxygen/component-framework/components/classes/pricing-box.class.php on line 572

PHP Notice:  Undefined index: pricing_box_title_background in /home/public_html/wp-content/plugins/oxygen/component-framework/components/classes/pricing-box.class.php on line 585

PHP Notice:  Undefined index: pricing_box_price_background in /home/public_html/wp-content/plugins/oxygen/component-framework/components/classes/pricing-box.class.php on line 609

PHP Notice:  Undefined index: pricing_box_content_background in /home/public_html/wp-content/plugins/oxygen/component-framework/components/classes/pricing-box.class.php on line 660

PHP Notice:  Undefined index: pricing_box_cta_background in /home/public_html/wp-content/plugins/oxygen/component-framework/components/classes/pricing-box.class.php on line 672

PHP Notice:  Undefined index: progress_bar_background_color in /home/public_html/wp-content/plugins/oxygen/component-framework/components/classes/progress-bar.class.php on line 219

PHP Notice:  Undefined index: progress_bar_bar_color in /home/public_html/wp-content/plugins/oxygen/component-framework/components/classes/progress-bar.class.php on line 235

PHP Notice:  Undefined variable: google_fonts_cache in /home/public_html/wp-content/plugins/oxygen/component-framework/includes/ajax.php on line 271

--

** To replicate **

Fresh install on Cloudways application (with WooCommerce)

Plugins
Oxygen 2.2.1
Query Monitor

Server
PHP 7.2
MySQL 5.7

--

Note that I can still use Oxygen by turning off the plugin Query Monitor.

**Comment by KittenCodes** [comment]
@Daniel-Richard,

Is this still an issue in Oxygen 2.4.1? If it is, please send a copy of your debug.log file to support@oxygenbuilder.com.
