### ISSUE TITLE
Off canvas menu does not close when using anchor links. 

### ISSUE THREAD

**Issue by leem2209** [soflyy/oxygen-bugs-and-features#1986]
Re-raising this issue as the response to my previous case isn’t working and the case has been closed. 

The response from @KittenCodes was:

“Please add the following code to the JavaScript tab of a Code Block to close the Pro Menu off-canvas menu when a hash link is clicked:”

jQuery(document).ready(function() { 
  jQuery('a[href^="#"]').click(function() { 
    jQuery('.oxy-pro-menu-mobile-close-icon').trigger('click');
  }); 
}); 

however, it’s not working. Maybe I’ve not added a code block to the right place? I added it to the header/footer template, tried it as the first and last element. I also had to delete the standard php “hello world” code as I didn’t want that displayed in my header. 

Am I putting the code block in the right place? 

Here’s a video screen recording of code not working here: https://1drv.ms/u/s!ArE_lwR1Cy5rh_4C6gVFEdRoE5ol_g?e=1f6wsV

**Comment by leem2209** [comment]
Any support on this @KittenCodes ??

**Comment by KittenCodes** [comment]
@leem2209 Please open a support ticket if you'd like us to take a look at your site: https://oxygenbuilder.com/support.
