### ISSUE TITLE
DONE: LINE-BREAK for the Oxygen-Code-Block + other improvements

### ISSUE THREAD

**Issue by HeyHeyDaniel** [soflyy/oxygen-bugs-and-features#1991]
Currently it's really a pain working with the Oxygen- Code-Element (CodeMirror) 😕

The Code-Block in Oxygen should have:

1. Line-break
2. Auto-completion of HTML-tags
3. A light color scheme. In summer or when there's much light in the room you can barely see what's on the display with the current dark color-scheme in Oxygen.

Elementor for example solved all three things very well!

Thanks!

**Comment by HeyHeyDaniel** [comment]
Upvote THIS comment to let Oxygen know you want it too, please!

**Comment by HeyHeyDaniel** [comment]
Hi @KittenCodes: Do you know why some requests can be upvoted (thumbs up) and others (like this one) not? Is there a setting for it? Thanks!

**Comment by sk209** [comment]
> Hi @KittenCodes: Do you know why some requests can be upvoted (thumbs up) and others (like this one) not? Is there a setting for it? Thanks!

You have to click the emoji icon on the top right to add the thumbs up. Once someone has done that, then it's visible in the bottom bar

**Comment by HeyHeyDaniel** [comment]
> > Hi @KittenCodes: Do you know why some requests can be upvoted (thumbs up) and others (like this one) not? Is there a setting for it? Thanks!
> 
> You have to click the emoji icon on the top right to add the thumbs up. Once someone has done that, then it's visible in the bottom bar

Thank you! :)

**Comment by Spellhammer** [comment]
Added in 3.8 alpha 1.
