### ISSUE TITLE
Pro-Menu Not Loading Properly on iPad

### ISSUE THREAD

**Issue by ddavisj** [soflyy/oxygen-bugs-and-features#1996]
**Describe the bug**
Pro-Menu doesn't load properly on my iPad. I've used the Pro Menu on a couple of sites and when viewed in landscape mode on my iPad, the menu partially opens the drop-downs automatically. Looks very broken!

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
*No*

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
No.

**To Reproduce**
Load Pro-Menu on iPad.
It seems that others also face this issue - see https://www.facebook.com/photo/?fbid=3506087419518710
I tried the fix suggested by Matt (ie. added the suggested css) but this did not resolve the issue.

**Expected behavior**
Drop-downs should only drop down when clicked!

**What actually happens**
As described above.

**Screenshots**
See attached

**Desktop (please complete the following information):**
**Smartphone (please complete the following information):**
Only occurs on iPad - mine is an iPad Air 1 (old but works fine on other sites)

**Additional context**
See site listed in the photo below (and the site in the footer) to reproduce this issue.

![160479304_3506087422852043_8116375544704878911_o](https://user-images.githubusercontent.com/65543945/111103888-8a37ac80-85a3-11eb-93f7-33677b79691f.jpg)

**Comment by KittenCodes** [comment]
@ddavisj Please try adding the following code to a stylesheet via Manage > Stylesheets in the top right of the builder:

```css
.menu-item-has-children .sub-menu:not(.aos-animate) {
opacity: 0;
}
```

**Comment by ddavisj** [comment]
Thanks for trying, this didn't fix the issue: it no longer loaded automatically but after dropping down, it no longer flipped back up.. Too buggy! Switched to the normal menu
