### ISSUE TITLE
functions.php on line 5313

### ISSUE THREAD

**Issue by jojojojojoj5564656465465** [soflyy/oxygen-bugs-and-features#1998]
**Describe the bug**
*A clear and concise description of what the bug is.*

I have this message on my site

**Notice: WP_Scripts::localize was called incorrectly. The $l10n parameter must be an array. To pass arbitrary data to scripts, use the wp_add_inline_script() function instead. Please see Debugging in WordPress for more information. (This message was added in version 5.7.0.) in /home/ybrv7474/nouveau-site/wordpress/wp-includes/functions.php on line 5313**

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
No

http://nouveau-site14102020.ybrv7474.odns.fr/?ct_builder=true&ct_inner=true

**Comment by KittenCodes** [comment]
Duplicate: https://github.com/soflyy/oxygen-bugs-and-features/issues/1990
