### ISSUE TITLE
CSS hardcoded image "Hero@2x.png" on design set Dentist Hero Section

### ISSUE THREAD

**Issue by xenio** [soflyy/oxygen-bugs-and-features#1999]
When you add from Design Set -> Dentist -> Section & Elements -> Hero & Titles -> Hero Section
even if you change the background hero image there still is a 404 for this image with path:

**/wp-content/uploads/sites/30/2018/01/Hero@2x.png**

![Screen Shot 2021-03-16 at 18 03 05](https://user-images.githubusercontent.com/153355/111350077-06082680-8682-11eb-8bfc-80edee2a43f2.png)

There is also a typo in the thumb Section Element "Hero Se**cit**on"

Oxygen Builder Version 3.7.1

**Comment by KittenCodes** [comment]
@xenio 

> When you add from Design Set -> Dentist -> Section & Elements -> Hero & Titles -> Hero Section even if you change the background hero image there still is a 404 for this image with path

Thank you for letting us know. I've fixed that issue on the Dentist design set.

> There is also a typo in the thumb Section Element "Hero Seciton"

This has also been fixed.
