### ISSUE TITLE
Notice: WP_Scripts::localize was called incorrectly. The $l10n parameter must be an array.

### ISSUE THREAD

**Issue by jojojojojoj5564656465465** [soflyy/oxygen-bugs-and-features#2002]
**Describe the bug**
*A clear and concise description of what the bug is.*

Notice: WP_Scripts::localize was called incorrectly. The $l10n parameter must be an array. To pass arbitrary data to scripts, use the wp_add_inline_script() function instead. Please see Debugging in WordPress for more information. (This message was added in version 5.7.0.) in /home/ybrv7474/nouveau-site/wordpress/wp-includes/functions.php on line 5313

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
*Yes*

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
*If yes, provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*

no

**To Reproduce**

**Expected behavior**
*A clear and concise description of what you expected to happen.*

**What actually happens**
*A clear and concise description of what happens instead of the expected behavior.*

**Screenshots**
*If applicable, add screenshots to help explain your problem.*

**Desktop (please complete the following information):**
- OS: [linux
 - Browser [chrome
 - Oxygen Version [3.7.1]

**Smartphone (please complete the following information):**
 - Oxygen Version [e.g. 2.2 Alpha]
![image](https://user-images.githubusercontent.com/45184918/111500905-c6eed980-8744-11eb-914e-cf3071bbb613.png)

**Additional context**
*Add any other context about the problem here.*

**Comment by KittenCodes** [comment]
Duplicate: https://github.com/soflyy/oxygen-bugs-and-features/issues/1990
