### ISSUE TITLE
Stylesheets with non-latin characters are not encoded properly

### ISSUE THREAD

**Issue by alex02** [soflyy/oxygen-bugs-and-features#2004]
**Describe the bug**
Whenever a post or page is created with non-latin characters, Oxygen creates a stylesheet file in /wp-content/uploads/oxygen/css/, but the file is not encoded properly and the stylesheet is not found.

This means that any styling on pages or posts with non-latin characters is not working at all.

<img width="413" alt="404" src="https://user-images.githubusercontent.com/361918/111605054-a4a99a00-87de-11eb-8a1c-39ff4c76c827.png">

I also noticed Oxygen still generates invalid css properties. See issue #1623
Example:
#link_text-9-34{url-encoded:true}#link_text-10-34{url-encoded:true}

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
Yes

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
http://fair-grouse.w5.wpsandbox.pro/%d1%82%d0%b5%d1%81%d1%82/
http://fair-grouse.w5.wpsandbox.pro/%d8%a7%d9%84%d9%92%d8%a3%d9%8e%d8%a8%d9%92%d8%ac%d9%8e%d8%af%d9%90%d9%8a%d9%8e%d9%91%d8%a9/

**To Reproduce**
1. Create a page or post with Cyrillic or any non-latin name.
2. Style the page.
3. The styling is not working, because the stylesheet file is not found.

**Expected behavior**
The output stylesheet file should be encoded properly, so it doesn't result in 404.

**Screenshots**
<img width="413" alt="404" src="https://user-images.githubusercontent.com/361918/111605054-a4a99a00-87de-11eb-8a1c-39ff4c76c827.png">

**Desktop (please complete the following information):**
- OS: Any
 - Browser: Any
 - Oxygen Version: 3.7

**Smartphone (please complete the following information):**
- Device: Any
 - OS: Any
 - Browser: Any
 - Oxygen Version: 3.7

**Comment by KittenCodes** [comment]
Duplicate: https://github.com/soflyy/oxygen-bugs-and-features/issues/1871
