### ISSUE TITLE
Give a .class for whole body

### ISSUE THREAD

**Issue by zimmiel** [soflyy/oxygen-bugs-and-features#2025]
Hi
It would be nice if there was an opportunity give a class for whole body
![body](https://user-images.githubusercontent.com/42843497/112278125-2ee47900-8c8b-11eb-9c2d-929e49acc24f.png)

**Comment by pascalinger** [comment]
In most cases, if you want to target a specific page, the automatically generated page-id-xx class will help. Also, there is a selector for post types and the sorts.

Not necessary imo, unless you have a specific use case.

**Comment by zimmiel** [comment]
Ok, thank you. Thank you, I doing this lesson from GreenSoc https://www.snorkl.tv/scrolltrigger-smooth-scroll/
could not figure out how to add class for whole body
