### ISSUE TITLE
Structure dissapear when Google fonts and webfont.js are not deactivated

### ISSUE THREAD

**Issue by bohdanps** [soflyy/oxygen-bugs-and-features#2026]
**Describe the bug**
All info in structure panel dissapears when Google fonts and webfont.js are not deactivated. Also if they're not deactivated there're some webfont.js errors in the console that might be related to this bug.

But when I disable Google Fonts and webfont.js in bloat options, it all works good.

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
Yes

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
No

**Screenshots**

Bloat configuration
![image](https://user-images.githubusercontent.com/29403400/112296196-f77aca00-8c94-11eb-8e4d-7f243f59b411.png)

Structure is empty
![image](https://user-images.githubusercontent.com/29403400/112296362-2133f100-8c95-11eb-99a2-c66ff5cf9f35.png)

Console errors
![image](https://user-images.githubusercontent.com/29403400/112296527-4f193580-8c95-11eb-800c-2964beb84b01.png)

**Desktop (please complete the following information):**
- OS: Windows 10
 - Browser Chrome
 - Oxygen Version 3.7.1

**Additional context**
Oxygen configs and content has been migrated from another web recently. Typekit connection is activated too.

**Comment by KittenCodes** [comment]
@bohdanps Please open a support ticket so that we can take a look at this for you: https://oxygenbuilder.com/support.

If you haven't already, please also run a plugin conflict test: https://pluginconflict.com/?plugin=Oxygen.
