### ISSUE TITLE
DONE: Add a simple text editor for the Heading and Text elements.

### ISSUE THREAD

**Issue by mikeingz** [soflyy/oxygen-bugs-and-features#203]
**Describe the feature you'd like to see included in Oxygen.**
It would be awesome if we could also edit the text from the settings, something like that:

![image](https://user-images.githubusercontent.com/2438157/55455112-e56d7000-5614-11e9-8ac2-55642eb2ba95.png)

**What are the use cases for this feature?**
Sometimes it's impossible to edit a text, especially when the element is hidden, or have an opacity:0, or is covered by other elements.
We have to move it or add a z-index just to be able to edit the text. These extra steps are very annoying and could easily be avoided.

Check this video to see the problem: https://www.facebook.com/groups/1626639680763454/permalink/2172313879529362/?comment_id=2172390356188381&reply_comment_id=2172418806185536

**Examples of this feature or functionality.**
Example with Elementor:

![image](https://user-images.githubusercontent.com/2438157/55455215-67f62f80-5615-11e9-8462-2365007d9a47.png)

**Comment by sunnyt7** [comment]
I've had this issue also!

**Comment by dollhauss** [comment]
This is also a huge issue if you delete all content from a text element. You can't get back in to type again as the container width is zero and has disappeared. If there was a way to edit text in the left hand panel as well there would be no problem.

**Comment by Barinburo** [comment]
+1

**Comment by CASWEBDESIGN** [comment]
Please add this feature, i consider it essential especially in 2.3 when building design sets!

**Comment by demetre19** [comment]
Yes yes yes. Also this woukd make it possible to edit text on mobile. 

Right now. There is no way to do that. Nothing works.

**Comment by MaximPro** [comment]
I was just about to write about this!
**MUST HAVE!** in 2.4

**Comment by adrien-robert** [comment]
Please consider adding this please...
It's really painful that we need to tweak min-height and min-width to enter text again in a text element where is no text anymore. OR delete and create another text element...

**Comment by esaygo** [comment]
+1

**Comment by alpabuz** [comment]
+1

**Comment by demetre19** [comment]
+1

**Comment by muzaffarsiddiqui** [comment]
+1

**Comment by Oxymaniac** [comment]
+1

**Comment by wpdevlab** [comment]
👍

**Comment by Cenay** [comment]
Yes please and thank you!

**Comment by Janik-Dev** [comment]
Don't forget to add an option to add dynamic data directly to the text editor

**Comment by robert1112** [comment]
+1

**Comment by alanzirpoli** [comment]
+1

**Comment by swinggraphics** [comment]
Another couple of months, a major release, and another +1 for this request. This is *badly* needed to make bold, italic, spans, etc. easier.

**Comment by Spellhammer** [comment]
Implemented in 3.8.
