### ISSUE TITLE
change small color preview when color var(--color) as value

### ISSUE THREAD

**Issue by peterpinkster** [soflyy/oxygen-bugs-and-features#204]
**Describe the bug**
I don't know exactly if it's a bug but when I use css variable  "var(colour)" as colour value the small circle doesn't change.   Anyway I am glad I can use it anyway in Oxygen!

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
*Yes/No*  --YES

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
*If yes, provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*

http://magnificent-impala.w6.wpsandbox.pro?upass=U8fUVK8a8b4w
http://magnificent-impala.w6.wpsandbox.pro/css-variable-demo-bug/

**To Reproduce**
Steps to reproduce the behaviour:
1. The address I mentioned above
2. The page css-variable-demo-bug
3. Select the blue section and look at the background colour
4. You'll see background colour with variable   var(--mainColor)
5. But the Circle, colour indicator is white,

_**Expected behaviour**
*A clear and concise description of what you expected to happen.*_
I would like to see it turning to blue. I understand that variables aren't only about colours.

_**What actually happens**
*A clear and concise description of what happens instead of the expected behaviour.*_
It doesn't understand the HEX colour of my variable. I guess

_**Screenshots**
*If applicable, add screenshots to help explain your problem.*_
Stolen from Facebook 
https://scontent-dfw5-1.xx.fbcdn.net/v/t1.0-9/56711128_2407839922582420_6585314874958544896_n.jpg?_nc_cat=101&_nc_ht=scontent-dfw5-1.xx&oh=f4deea9cb9fc4661da760a08a8079c3a&oe=5D3FEFCD

_**Desktop (please complete the following information):**
 - Oxygen Version [e.g. 2.2 Alpha]_
Chrome, the latest update, Windows 10, the Latest Oxygen

_**Smartphone (please complete the following information):**
 - Oxygen Version [e.g. 2.2 Alpha]_
Don't use one now.

_**Additional context**
*Add any other context about the problem here.*_
Its just a small thing.  It would be great when css vars are supportable. I use them to change the colours on the front end. I tried with global colours but I saw that Oxygen doesn't use CSS vars and for that I need to change every single thing if I want to change colour on front side.

Thank you.

**Comment by KittenCodes** [comment]
@peterpinkster, I apologise for the delay here. Unfortunately, the Sandbox install has expired. Would you mind recreating this on a new install and sending me the one click login please?

**Comment by Spellhammer** [comment]
Not a bug. Oxygen's color picker doesn't support CSS variables, though they work fine in the color input itself.
