### ISSUE TITLE
 Migrate website to oxygen builder

### ISSUE THREAD

**Issue by jandresb12** [soflyy/oxygen-bugs-and-features#2040]
Hello everyone, 
I have recently bought Oxygen builder, my question is how do I migrate all my pages, blogs, products, etc. to be able to use Oxygen builder.
This is my website www.air4seniors.com
Thanks for your comments and help.

**Comment by KittenCodes** [comment]
Closing - this isn't a feature request.

If you need help and advice on using Oxygen, please reach out in our Facebook group: https://www.facebook.com/groups/1626639680763454/, or in the Community: https://github.com/soflyy/oxygen-community/discussions. Alternatively, you can open a support ticket: https://oxygenbuilder.com/support.

> I have recently bought Oxygen builder, my question is how do I migrate all my pages, blogs, products, etc. to be able to use Oxygen builder.

Unfortunately, it's not possible to import existing sites into Oxygen. Instead, you would need to rebuild your site using Oxygen.
