### ISSUE TITLE
Animate on scroll elements are not visibile in the back end

### ISSUE THREAD

**Issue by Monimal** [soflyy/oxygen-bugs-and-features#2041]
**Describe the bug**
An element with effect "animate on scroll -> fade" disappears on the back-end on the following changes. It makes changes on animated text hard to quickly elaborate.

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
Yes

**To Reproduce**
1. Add effect "animate on scroll -> fade(any)" to text element or any other element
2. Save changes
3. Refresh back-end page
4. The element is not visibile nor easily editable.

**Expected behavior**
I'd like to see the element on the backend for easy edit.

**Comment by KittenCodes** [comment]
@Monimal I've not been able to replicate this. If you're still having problems, please open a support ticket so that we can take a look for you: https://oxygenbuilder.com/support/.
