### ISSUE TITLE
Reusable content on specific pages

### ISSUE THREAD

**Issue by markp131** [soflyy/oxygen-bugs-and-features#2043]
At the moment (and I hope I am not just being stupid here) it seems impossible to specify what page a re-usable component can be used on. For example: I create a re-usable component to display the top 3 posts in a specific category. And on on lets say the "about page" (using the default page template) I have to add the re-usable component on that template. However, that means that every page using that template will display the component. 

It would be great, if in the oxygen builder sidebar I could click a component or in fact any element and add a page id (or multiple) to a selection on which to display the specific element. 

At the moment I am having to add a code block and use `if (is_page(#))`

**Comment by KittenCodes** [comment]
@markp131 Is there a reason you wouldn't add it to the page itself?

**Comment by markp131** [comment]
I'm confused as to what you mean? 

Do you mean, why do I not add it to the page as in add it in the page editor? 

The reason is: my page content is placed into a column. Then I have a sidebar. 

The  reusable component I want to add is a full width hero banner - call to action or image. 

I can't add a full width component into the page as the content is output to the left column. 

Does that make sense?

**Comment by KittenCodes** [comment]
@markp131 Thank you for explaining. It sounds as though you need to use Oxygen's Conditions feature in your templates: https://oxygenbuilder.com/documentation/other/conditions/.
