### ISSUE TITLE
Selector Detector

### ISSUE THREAD

**Issue by yukimichi215** [soflyy/oxygen-bugs-and-features#2046]
**Describe the bug**
*A clear and concise description of what the bug is.*

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
*Yes*

**To Reproduce**
1. write for `<a class='oxy-post-url' href='<?php the_permalink(); ?>'></a>` to easy posts php
2.  write for  %%EPID%% .oxy-post-url{
position:absolute;
  width:100%;
  height:100%;
  z-index:2;
  left: 0;
    top: 0;
}  to easy posts css
3. The selector is only detecting up to `<a>` tag.

**What actually happens**
I want to select elements below the `<a>` tag.

**Screenshots**
*If applicable, add screenshots to help explain your problem.*

**Desktop (please complete the following information):**
- OS: win10
 - Browser chrome
 - Oxygen Version 3.7

I am Japanese, so I use a translation tool.

Therefore, I apologize if there is any strange grammar.

**Comment by yukimichi215** [comment]
1,write for <a class='oxy-post-url' href='<?php the_permalink(); ?>'></a> to easy posts php
2,write for 
%%EPID%% .oxy-post-url{
position:absolute;
width:100%;
height:100%;
z-index:2;
left: 0;
top: 0;
} to easy posts css
The selector is only detecting up to <a> tag.

**Comment by yukimichi215** [comment]
Sorry, there was an omission, so I supplemented it in the comment above.

**Comment by yukimichi215** [comment]
write to easy posts php　` <a class='oxy-post-url' href='<?php the_permalink(); ?>'></a>`

**Comment by yukimichi215** [comment]
The selector is only detecting up to `<a>` tag.

I'm not familiar with git hub, so I haven't been able to write any code. Sorry about that.

**Comment by KittenCodes** [comment]
@yukimichi215 The Selector detector is intended to create styles for plugin output like contact forms inside of Oxygen - it's not intended to style the Easy Posts element.

**Comment by yukimichi215** [comment]
The problem is not that it happened with Easy Posts, but that if you set the a tag to absolute, width 100%, height 100%, and zindex above other elements, you cannot get elements below that.
