### ISSUE TITLE
Cant find blocks

### ISSUE THREAD

**Issue by markp131** [soflyy/oxygen-bugs-and-features#2047]
In many videos, there is an option to save as block which I don't have when I click the little hamburger icon over the element in the right "structure" menu. 

Also, in many videos, from the admin dashboard there is an option to see the blocks under the oxygen title but I do not see that either. 

I read a few posts that mentioned perhaps there was a plugin but I can not see this. 

What is wrong with my installation?

**Comment by jamescrabb** [comment]
You need the Gutenberg extension to use blocks 👍

**Comment by KittenCodes** [comment]
> You need the Gutenberg extension to use blocks 👍

That's incorrect. You need the Gutenberg extension to make Oxygen-designed content editable in Gutenberg.

> In many videos, there is an option to save as block which I don't have when I click the little hamburger icon over the element in the right "structure" menu.

Please select "Make this WordPress Install a Design Set" via Oxygen > Settings > Library. You should then see the Block Library Option under Oxygen in the WordPress admin menu.
