### ISSUE TITLE
No blocks found in your library.

### ISSUE THREAD

**Issue by markp131** [soflyy/oxygen-bugs-and-features#2050]
Newly created blocks are not showing up in the page (+) element picker. 

I went to the component I wanted to convert to a block and did that. I got the confirm message which told me the block was created and that I can manage the block by going to `oxygen > block library`.

I went there to verify the block was created. It was. 

I then went to the page I wanted to add the block. Clicked the (+) icon in the editor and searched for the block. I got the message: 

> No blocks found in your library.

Wordpress Version 5.7

**Comment by KittenCodes** [comment]
@markp131 Please open a support ticket so that we can take a look at this for you: https://oxygenbuilder.com/support.
