### ISSUE TITLE
Bug in Section Indicator module on iPhone Safari / Chrome and OnePlus Android 11 Chrome

### ISSUE THREAD

**Issue by jojoba007** [soflyy/oxygen-bugs-and-features#2051]
Hi all, I've been looking for a solution to the following issue: When I open the website from a link on my iPhone (for example from WhatsApp) and it opens in Safari, the section indicator pushes the content a bit to the left of the screen, so a margin is visible. See screenshot: https://prnt.sc/10xy6em .
Once I reload the screen in Safari, the website turns back to normal again. It also happens on Chrome mobile. I'm not sure how to solve the issue. The problem is gone once I remove the Section Indicator module. Is this a bug? Because I haven't changed anything on the official settings for the Section Indicator module. I already checked if it could have anything to do with the z-index, or maybe even the max width of sections, but they are all set to max 100% for all devices.
The website where the issue is present is bosb-logistics.nl

**Comment by KittenCodes** [comment]
@jojoba007 Please open a support ticket so that we can take a look at this for you: https://oxygenbuilder.com/support/.
