### ISSUE TITLE
Page loading issue 

### ISSUE THREAD

**Issue by 0jamescampbell0** [soflyy/oxygen-bugs-and-features#2052]
The page loading without CSS when I open on a new tab. 

Hi, new to oxygen so I'm guessing this is going to be obvious... All of a sudden the page isn't loading correctly. I've attached 3 screenshots. One of how the preview looks, one how it looks on a new tab, and one is the report from google page insights... Any help would be much appreciated. 

<img width="1522" alt="Screenshot 2021-03-28 at 14 06 14" src="https://user-images.githubusercontent.com/81517754/112753569-df29e880-8fcf-11eb-9e66-b8a5568995b3.png">
<img width="1522" alt="Screenshot 2021-03-28 at 14 05 56" src="https://user-images.githubusercontent.com/81517754/112753570-dfc27f00-8fcf-11eb-9762-1b3a213bf51a.png">

<img width="1522" alt="Screenshot 2021-03-28 at 14 06 43" src="https://user-images.githubusercontent.com/81517754/112753565-d89b7100-8fcf-11eb-8f70-6b0dd216cfcd.png">

**Comment by KittenCodes** [comment]
@0jamescampbell0 

I suspect this is caused by a caching plugin. If you have any caching plugins installed, please disable them.

If that doesn't help, please open a support ticket so that we can take a look: https://oxygenbuilder.com/support/
