### ISSUE TITLE
License not valid message/Library Items not loading

### ISSUE THREAD

**Issue by carolynne-equiluxe** [soflyy/oxygen-bugs-and-features#2053]
**Describe the bug**
Library items are not loading and I am getting a message that my license is not valid when trying to save screenshots.

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
Yes

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
No. I couldn't figure out how to create a Sandbox install.

**To Reproduce**
1. Go to Library
2. Message says "Items not loaded. Forbidden."
3. Click on "Generate Screenshots"
4. Message says license not valid.

I twice copy/pasted the license information into the settings.

**Desktop (please complete the following information):**
- OS: Windows 10
 - Browser Firefox
 - Oxygen Version 3.7.1

**Comment by KittenCodes** [comment]
@carolynne-equiluxe Please open a support ticket so that we can take a look at your site: https://oxygenbuilder.com/support.
