### ISSUE TITLE
elements with link, text color override  issue

### ISSUE THREAD

**Issue by rony747** [soflyy/oxygen-bugs-and-features#2055]
If we use any elements that have a link. for e.g. if we add a post title with a link the only way to change the text color is via the global link settings. If I choose any color in the editor it does not work. But it should override the other settings.

**Comment by KittenCodes** [comment]
@rony747 You can use CSS to change the colours of links within text and heading elements. The following CSS can be added to a stylesheet via Manage > Stylesheets in the top right of the builder to change them Globally:

```css
.ct-text-block a, .ct-headline a {
    color: red;
}
```
