### ISSUE TITLE
Image comparison - slider control goes outside of container

### ISSUE THREAD

**Issue by azoswald** [soflyy/oxygen-bugs-and-features#2056]
**Describe the bug**
When clicking and dragging the image comparison slider control, it goes outside of the container.
Then it cannot be recovered from outside of the container. The user must reload the page to access the slide controller.

*A clear and concise description of what the bug is.*

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
Yes

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**

https://legacy.maadsites.com/

**To Reproduce**
Open chrome browser.
Go to this page: https://legacy.maadsites.com/
Click and drag the slider control outside the container.

**Expected behavior**
Slider control will disappear.

**What actually happens**
*A clear and concise description of what happens instead of the expected behavior.*

**Screenshots**
*If applicable, add screenshots to help explain your problem.*

https://prnt.sc/10zjrur
https://prnt.sc/10zjs50

**Desktop (please complete the following information):**
- Windows
 - Browser Chrome
 - Oxygen Version current

**Comment by azoswald** [comment]
I have since replaced the Oxygen Components image comparison with the OxyNinja module provided in their Core.

**Comment by Spellhammer** [comment]
Fixed. Re-add the Image Comparison element to see the changed behavior.
