### ISSUE TITLE
ABOUT ?xlink=css&ver=5.7 TIMELINE SLOW

### ISSUE THREAD

**Issue by dls06783** [soflyy/oxygen-bugs-and-features#2059]
Hello, I just bought oxygen in March 12, gtmetrix test report is very fast

But recently, when I tested again, I found that there is an extra file with ： ?xlink=css&ver=5.7 ,  makes the page access very slow.

I don't know how to fix it

thanks

Test on 30／3 （slow）
[https://gtmetrix.com/reports/goldpigtech.com/zAMcuHj3/](url)

Test on 12／3  （fast）
[https://gtmetrix.com/reports/goldpigtech.com/caAkFkI9/](url)

**Comment by KittenCodes** [comment]
@dls06783 Please ensure you have Oxygen's CSS cache enabled via Oxygen > Settings > CSS Cache. If the cache is enabled and the xlink file is still showing, please open a support ticket so that we can take a look at your site: https://oxygenbuilder.com/support/.
