### ISSUE TITLE
Please set min-height on divs less then 80px.

### ISSUE THREAD

**Issue by peterpinkster** [soflyy/oxygen-bugs-and-features#206]
**Describe the feature you'd like to see included in Oxygen.**
Hi, I am designing Applications with Oxygen... and on my phone I want to set a header toolbar of 60px;  In the CSS of Oxygen there is a line that div have a min-height of 80px; ??? That's too big for my application.   Can you set it to a min-height of 40px ???

https://pasteboard.co/I8sNGDu.jpg

and 

https://pasteboard.co/I8sRBiZ.jpg

**What are the use cases for this feature?**
UI on apps is very limited,  I design refering to other apps like facebook etc. A big toolbar will make the user feel that its set for people with bad sight 😂 🤣

I've build a website with another builder... I want to rebuild it now in oxygen but when I started with the header I had directly my first problem when I set my header to 60px

**Examples of this feature or functionality.**
https://ptrweb.nl is my website with a header of 60px;

To make it work I need to put on every used div a 0px padding because oxygen CSS have default 20px;

And I need to remove the min-height 80px;

```
.ct-columns-empty, .oxy-header-row-empty > div, .ct-div-block:empty, .ct-nestable-shortcode:empty, .ct-ul:empty, .ct-link:empty, .ct-new-columns:empty, .ct-widget:empty, .ct-shortcode:empty, .ct-section:empty, .ct-section-inner-wrap:empty, .ct-looper:empty, .ct-separator:empty, .ct-slide:empty, .ct-code-block > span.ng-scope:empty, .oxygen-empty-comments-list, .oxygen-empty-gallery {
        min-height: 80px; 
        display: block;
```

Im not so happy to change the Oxygen CSS to rebuid my website in Oxygen.

**Comment by Gibsonion** [comment]
There is no such issue, you can make a div any height, but Oxygen creates empty divs with a min height so you can see/click them, and this only appears in the editor, on the front end an empty div appears with 0 height.

**Comment by peterpinkster** [comment]
Hi,
Thank you for your anwser.


I had some problems with this..  Inside a div with 50px height the SVG logo
i putt as embed code was bigger then my div.
I wrote a CSS. for me its much beter to work with this way.

.ct-columns-empty,
.oxy-header-row-empty > div,
.ct-div-block:empty,
.ct-nestable-shortcode:empty,
.ct-ul:empty,
.ct-link:empty,
.ct-new-columns:empty,
.ct-widget:empty,
.ct-shortcode:empty,
.ct-section:empty,
.ct-section-inner-wrap:empty,
.ct-looper:empty,
.ct-separator:empty,
.ct-slide:empty,
.ct-code-block > span.ng-scope:empty,
.oxygen-empty-comments-list,
.oxygen-empty-gallery {
        min-height: 20px!important;
}

I really like Oxygen. You guys did a good job.
Thank you very much.

Sincerly,
Peter

>

**Comment by Gibsonion** [comment]
No problem if you do need to collapse a div inside the editor simply place a text element inside it and delete all the text.
