### ISSUE TITLE
Uploaded SVG icons don't show if they're not native Icomoon icons

### ISSUE THREAD

**Issue by aconcheng** [soflyy/oxygen-bugs-and-features#2064]
**Describe the bug**
Hi I was trying to follow this video https://youtu.be/uBJJYaS3S0g to upload some SVG icons to Icomoon and then download the icon set for importing into Oxygen Builder (since these icons can not be found on Icomoon). Of course I ticked the <title>and checked everything but after importing them into Oxygen, all the icons showed only their names and empty boxes in Oxygen. There's no icon inside.

I'm pretty sure I followed the right procedure because the native Icomoon SVG icons downloaded work with no problem in Oxygen. I also tried to create icons in Adobe Illustrator and then saved them in new SVG files before uploading to Icomoon and running through the downloading procedure. Didn't work either.

All the SVG files in the downloaded SVG folder from Icomoon look normal. 

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
Yes

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
Yes.
https://oxygen-q9k6atqltq6dl.oxygen-demo.qsandbox.me/wp-admin/admin.php?page=oxygen_vsb_settings&tab=svg_manager

**To Reproduce**
1. Create a page, template or post and edit with Oxygen.
2. Add a section and then add an icon.
3. Choose "bilibili" as the icon set.
4. See what happens.

**Expected behavior**
Icons names and boxes should be shown and icons should be visible.

**What actually happens**
Icons names and boxes show but there's nothing inside.

**Screenshots**
https://i.imgur.com/OdTqCAi.png

**Desktop (please complete the following information):**
- OS: Win 10 64bit
 - Browser: Edge, Vivaldi
 - Oxygen Version: 3.7.1

**Comment by aconcheng** [comment]
> @aconcheng Please open a support ticket and send us your symbol-defs.svg file so that we can take a look: https://oxygenbuilder.com/support.

Hi KittenCode, can you please tell me how to open a support ticket? The link you provided is what led me here...it basically told me to submit a thread in GitHub, and now here in GitHub you told me to go back to that page. What's happening here?

**Comment by KittenCodes** [comment]
@aconcheng You need to select "Something's broken and I need help" from the dropdown box on the left hand side of the Support page. You will then see a support form that you can fill in.
