### ISSUE TITLE
Unable to edit a Text Block (TypeError: Cannot read property 'model' of undefined....)

### ISSUE THREAD

**Issue by knut-studio** [soflyy/oxygen-bugs-and-features#2065]
**Describe the bug**
We are unable to edit a Text Block on a page that was build months ago. When trying to edit the content in the Text Block this message appears: **_"TypeError: Cannot read property 'model' of undefined on line #1 in [website URL]/plugins/oxygen/component-framework/angular/common.directives.min.js?ver=3.7.1"_**

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
Yes

**Expected behavior**
When double-clicking on the Text Block we always are able to make any change on the text.

**What actually happens**
Instead of being able to modify the text content, a red popup appears with the error and it is not possible to make any changes to the Text Block content.

**Screenshots**
<img width="460" alt="Captura de Pantalla 2021-04-01 a les 10 56 04" src="https://user-images.githubusercontent.com/30494856/113269587-e5260f00-92d8-11eb-8fdf-a3beacedfc46.png">

**Desktop (please complete the following information):**
- OS: iOS
 - Browser: Chrome
 - Oxygen Version: 3.7.1

**Comment by KittenCodes** [comment]
@knut-studio Please open a support ticket so that we can take a look at this for you.
