### ISSUE TITLE
Broken Focus Section fullscreen

### ISSUE THREAD

**Issue by esa-codes** [soflyy/oxygen-bugs-and-features#2066]
Hi, recently i added a Focus Section to a page of my dev website, I customized it but now the "fullscreen" function is totally broken, even if I add a new focus section, in all focus sections I add.

**Comment by KittenCodes** [comment]
@esa-codes Please open a support ticket so that we can take a look at your site: https://oxygenbuilder.com/support. You need to select "Something's broken and I need help".
