### ISSUE TITLE
Number Counter widget 

### ISSUE THREAD

**Issue by save930** [soflyy/oxygen-bugs-and-features#2068]
Hi Support,

I happened Number Counter seem had a bug, this is a Font size can't to change, see this video:

https://drive.google.com/file/d/1wxORqRKdORIXWjxIRy3cu94m3RQPjo2B/view?usp=sharing

Thanks

**Comment by save930** [comment]
This Video use Oxygen version is 3.7.1 .

**Comment by KittenCodes** [comment]
@save930 If you're still having problems with this, please open a support ticket so that we can take a look: https://oxygenbuilder.com/support.
