### ISSUE TITLE
Oxygen + Woocommerce addon: undesired auto scroll to product tabs

### ISSUE THREAD

**Issue by geraldmorales** [soflyy/oxygen-bugs-and-features#2070]
## Please only open a bug report if the issue can be reproduced on a clean site. If it can't be reproduced, please open a support ticket so that we can take a look at your site.

**Describe the bug**
*A clear and concise description of what the bug is.*

With Woocommerce Addon, I get undesired auto scroll to product tabs.
I found a similar ticket here by someone else: https://wordpress.org/support/topic/auto-scroll-to-product-tabs/
An answer from Woocommerce support is interesting. 

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
*Yes/No*
Yes

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
No - not having Woocommerce in Sandbox.

*If yes, provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*

**To Reproduce**

**Expected behavior**
*A clear and concise description of what you expected to happen.*
Shouldn't autoscroll…

**What actually happens**
*A clear and concise description of what happens instead of the expected behavior.*
undesired auto scroll to product tabs

**Screenshots**
*If applicable, add screenshots to help explain your problem.*

**Desktop (please complete the following information):**
- OS: Mac OSX Mojave
 - Browser safari, FF, Chrome
 - Oxygen Version [e.g. 2.2 Alpha]
 

**Smartphone (please complete the following information):**
 - Oxygen Version 3.7.1

**Additional context**
*Add any other context about the problem here.*

**Comment by KittenCodes** [comment]
@geraldmorales This is a known issue that occurs when Smooth Scroll to Hash Links is enabled in Oxygen's General or Page settings.

To prevent it from occurring, please disable Smooth Scroll in the settings. You can then add a Code Block to your catch-all template and add the following code to the JavaScript tab to enable smooth scroll and exclude the product tabs element:

```
// Select all links with hashes
jQuery('a[href*="#"]')
  // Remove specific links
  .not('[href="#tab-description"]')
  .not('[href="#tab-additional_information"]')
  .not('[href="#"]')
  .not('[href="#0"]')
  .click(function(event) {
    // On-page links
    if (
      location.pathname.replace(/^\//, '') == this.pathname.replace(/^\//, '') 
      && 
      location.hostname == this.hostname
    ) {
      // Figure out element to scroll to
      var target = jQuery(this.hash);
      target = target.length ? target : jQuery('[name=' + this.hash.slice(1) + ']');
      // Does a scroll target exist?
      if (target.length) {
        // Only prevent default if animation is actually gonna happen
        event.preventDefault();
        jQuery('html, body').animate({
          scrollTop: target.offset().top
        }, 1000, function() {
          // Callback after animation
          // Must change focus!
          var $target = jQuery(target);
          target.focus();
          if ($target.is(":focus")) { // Checking if the target was focused
            return false;
          } else {
            $target.attr('tabindex','-1'); // Adding tabindex for elements not focusable
            $target.focus(); // Set focus again
          };
        });
      }
    }
  });
```
