### ISSUE TITLE
Bug Edit width Oxygen

### ISSUE THREAD

**Issue by slugaboga** [soflyy/oxygen-bugs-and-features#2072]
Wordpress 5.7
Oxygen 3.7.1

![image](https://user-images.githubusercontent.com/8350522/113553421-6bf02a00-9600-11eb-94f7-f3764389a8d6.png)
![image](https://user-images.githubusercontent.com/8350522/113553510-904c0680-9600-11eb-9ef4-0ec41c0845a6.png)
![image](https://user-images.githubusercontent.com/8350522/113553555-a0fc7c80-9600-11eb-81bb-eaa64574f389.png)
![image](https://user-images.githubusercontent.com/8350522/113553592-b1145c00-9600-11eb-931a-3de244d82df3.png)

**Comment by KittenCodes** [comment]
@slugaboga Please open a support ticket so that we can take a look at your site: https://oxygenbuilder.com/support. You need to select "Something's broken and I need help".
