### ISSUE TITLE
Menu CSS can't be changed at different breakpoints

### ISSUE THREAD

**Issue by Shamusr1** [soflyy/oxygen-bugs-and-features#2076]
## Please only open a bug report if the issue can be reproduced on a clean site. If it can't be reproduced, please open a support ticket so that we can take a look at your site.

**Describe the bug**
*Cannot change CSS of menu in different breakpoints - eg. text padding is set once at default page size then cannot be changed at smaller page sizes*

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
*Yes*

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
*http://cloudy-cow.w6.wpsandbox.pro/?ct_template=test&ct_builder=true*

**To Reproduce**
1. Create menu
2. Set font size
3. Change page size
4. Cannot change font size

**Expected behavior**
Should be able to change settings at different breakpoints

**What actually happens**
Doesn't work

**Screenshots**
*If applicable, add screenshots to help explain your problem.*

**Desktop (please complete the following information):**
- OS: Windows
 - Browser Chrome
 - Oxygen Version [e.g. 2.2 Alpha]

**Smartphone (please complete the following information):**
 - Oxygen Version 3.7.1

**Additional context**
*Add any other context about the problem here.*

**Comment by KittenCodes** [comment]
https://github.com/soflyy/oxygen-bugs-and-features/issues/434
