### ISSUE TITLE
Woocommerce Custom attributes do not appear in the designer

### ISSUE THREAD

**Issue by exonianp** [soflyy/oxygen-bugs-and-features#2078]
## Please only open a bug report if the issue can be reproduced on a clean site. If it can't be reproduced, please open a support ticket so that we can take a look at your site.

**Describe the bug**
When trying to add a custom product attribute in the page (e.g. the country of a product) you see the error as attached here.

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
Yes

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
I havent tried the sandbox

**To Reproduce**
1. Go to designer
2. Select Woocommerce
3. Select Product Meta
4. Select Advanced > Attributes
5. In the list select Custom Categories, Taxonomies 
6. Select Add Attibutes
7. Select the custom attribute that start with pa_

**Expected behavior**
See my custom attribute displayed on the  screen.

**What actually happens**
Error as shown in the attached picture
**Screenshots**
*If applicable, add screenshots to help explain your problem.*

**Desktop (please complete the following information):**
- Windows 10 
 - Chrome
 - Oxygen Version 3.7.1

**Smartphone (please complete the following information):**
 - Oxygen Version [e.g. 2.2 Alpha]

**Additional context**
*Add any other context about the problem here.*
![image](https://user-images.githubusercontent.com/6937118/113947701-e80e8b80-9813-11eb-95f1-fd9d0285465c.png)

**Comment by exonianp** [comment]
https://1drv.ms/v/s!Akul2ygARwfdh5QeQznXJ_UHkrCsfA?e=gTmrup

Here is a video of the issue as well.

**Comment by exonianp** [comment]
Fyi. If for example one likes to display the custom attributes pa_fruitiness, pa_country, pa_sensory-notes  under the "more info" button will use this type of code:

add_action('woocommerce_after_shop_loop_item','display_loop_product_attribute' );
function display_loop_product_attribute() {
    global $product;

    $product_attributes = array('pa_fruitiness', 'pa_country', 'pa_sensory-notes'); // Defined product attribute taxonomies.
    $attr_output = array(); // Initializing

    // Loop through the array of product attributes
    foreach( $product_attributes as $taxonomy ){
        if( taxonomy_exists($taxonomy) ){
            if( $value = $product->get_attribute($taxonomy) ){
            // The product attribute label name
            $label_name = wc_attribute_label($taxonomy);
                // Storing attributes for output
                $attr_output[] = '<span class="'.$taxonomy.'">'.$label_name.': '.$value.'</span>';
            }
        }
    }
    // Output attribute name / value pairs separate by a "<br>"
    echo '<div class="product-attributes">'.implode('<br>', $attr_output).'</div>';
} 


It will be great if Oxygen can work in identifying the custom attributes as well as giving to the end use the ability to customise the output e.g. so that lists of values are not displayed as comma delimited in different lines etc.

**Comment by exonianp** [comment]
Here is custom code solution to the problem:

Lets assume the the sensory-notes custom attribute can have many values than we would like to display like this:

![image](https://user-images.githubusercontent.com/6937118/114148062-1084ab80-9922-11eb-9a89-61f2fa0a2e17.png)


Here is the code I just wrote to do it is:

function display_sensorynotes() {
    global $product;

    $product_attributes = array('pa_sensory-notes'); // Defined product attribute taxonomies.
    $attr_output = array(); // Initializing

    // Loop through the array of product attributes
    foreach( $product_attributes as $taxonomy ){
        if( taxonomy_exists($taxonomy) ){
            if( $value = $product->get_attribute($taxonomy) ){

if( !empty($value) ){
    
    $label_name = wc_attribute_label($taxonomy);
    // Storing attributes for output

    $attr_output[] = '<span class="'.$taxonomy.'"><h1>'.$label_name.'</h1></span>';
  
    echo '<div class="product-attributes">'.implode('<li>', $attr_output).'</div>';
    
                $postIdUn = array();
					$array =  explode(',', $value);
					foreach ($array as $mem_id) {
						$postIdUn[] = $mem_id;
					}
				
			
			$postIdUn = array_values(array_unique($postIdUn));
			$count_id = count($postIdUn);
			echo '<hr><div><ul>';
			for ($i = 0; $i < $count_id; $i++) {
				echo '<li>' . $postIdUn[$i] . '' . get_the_title($postIdUn[$i]) . '</li><hr>';
					}
			echo '</div>';
        }
            
            }
        }
    }
    
   
}

It will be great if Oxygen can provide a form of this code so that the users can pick up how they would like to display the name of the custom attribute as well as the display of the items (e.g. bulleted list, not just comma delimited pragma). 

I hope this helps

**Comment by KittenCodes** [comment]
@exonianp This is not how The Attributes tab works on elements. Please see here for how it should be used: https://oxygenbuilder.com/documentation/code/custom-attributes/.
