### ISSUE TITLE
Progress Bar - % doesn't change

### ISSUE THREAD

**Issue by krissborowy** [soflyy/oxygen-bugs-and-features#2079]
**Describe the bug**
When changing the percentage in the progress bar. Its value generated on the website does not change. Whichever value we set, the default is 85%.

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
*Yes

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
*Yes

https://oxygen-qr6tmmm2jt9dl.oxygen-demo.qsandbox.me/progress-bar/?ct_builder=true

**To Reproduce**
1. Go to 'Page' and Add new Page 
2. Click on 'Save and Edit with Oxygen'
3. Add new components 'Progress Bar'
4. By changing the value of the "Primary" panel, we do not see the change on the page.

**Expected behavior**
The percentage value will be appropriate to the value set in the "Primary" panel

**What actually happens**
The percentage value does not change on the generated page.

**Screenshots**
Screen of the problem added below
<img width="2081" alt="Zrzut ekranu 2021-04-8 o 05 42 02" src="https://user-images.githubusercontent.com/81860559/113965248-4f850500-982d-11eb-9203-cea18784ce23.png">

**Desktop (please complete the following information):**
- OS: macOS Big Sure 11.2.3
 - Browser: Chrome
 - Oxygen Version: 3.7.1

**Comment by KittenCodes** [comment]
@krissborowy You need to double click on the element that shows the percentage and change it. The percentage in the Properties Pane sets how far you want the progress bar to fill up.

I've done this for you on the Sandbox site.

**Comment by krissborowy** [comment]
@KittenCodes Thank you for your answer.

I expected it to be automatically changed by a certain percentage in the 'Primary' panel.

Maybe it's worth adding a fix that will automatically change the value.

Thank You
