### ISSUE TITLE
DONE: Easy Posts Visual Designer

### ISSUE THREAD

**Issue by Gibsonion** [soflyy/oxygen-bugs-and-features#208]
Idea:
Easy Posts is an amazingly powerful tool, but needing to hand code it is time consuming and limits much of its potential to only advanced users. 

The option to hand code would still be needed, but the ability to also design Easy Posts in the same visual way as the rest of Oxygen would be game changer.

Use cases:
Creating advanced custom designs for dynamic content in minutes. Allowing less advanced users access one of Oxygen's most powerful features.

**Comment by albertso** [comment]
There may be a hacky way to use reusable templates for easy post content, doing something like:

`do_shortcode( get_post_meta( $template_id, 'ct_builder_shortcodes', true ) );`

I haven't tried it, but could be a starting point:

https://wpdevdesign.com/shortcode-for-displaying-oxygen-templates-and-reusable-parts/

**Comment by alanzirpoli** [comment]
+1

**Comment by jcmatoskx** [comment]
I think it should be the other way around, I think that Oxygen should show us the generated code/templates for all that is created using the builder. 
So you could use for example the repeater to build visually, and then be able to view and manually import the generated code into an easy posts if you wish to, 
In fact I think ideally every single oxygen element should show the code template that it is generating and allow us to directly edit it, learn from it and use it

**Comment by KittenCodes** [comment]
@Gibsonion Oxygen's Repeater can be used for this - does that cover what you wanted to be able to do?

**Comment by Spellhammer** [comment]
This request is satisfied by the Repeater element.
