### ISSUE TITLE
Icon list background color

### ISSUE THREAD

**Issue by Cr3epy** [soflyy/oxygen-bugs-and-features#2081]
hey,

when I try to add individual colors for each row in an icon list it does not apply it. Usually, the rows below take the same color and you cant change it individual. Screenshot attached. 

Sample: if you change the color from row 2 it applies to row 3. When you change row 3 it applies to row 2.
<img width="1440" alt="Bildschirmfoto 2021-04-08 um 14 37 04" src="https://user-images.githubusercontent.com/77240038/114027728-fabaac00-9877-11eb-975e-58bc9a2281da.png">

**Comment by KittenCodes** [comment]
@Cr3epy If you want different background colours for each row, please ensure you're setting the colour on the ID and not the class.

If you are still having problems, please open a support ticket so that we can take a look at this for you: https://oxygenbuilder.com/support.
