### ISSUE TITLE
Udate Not Working

### ISSUE THREAD

**Issue by ericksonbethann** [soflyy/oxygen-bugs-and-features#2082]
When I update this site to the current oxygen, it does not update. It does not look like other updated versions.

The main difference is in the "mobile" settings. They don't appear across the top of the left hand section.....
what am I doing wrong?
![Screen Shot 2021-04-08 at 8 46 45 AM](https://user-images.githubusercontent.com/82169150/114057888-d646db80-9847-11eb-931f-288bdb8cb93c.png)

Screenshot attached.

**Comment by Spellhammer** [comment]
Which version are you updating from?

**Comment by ericksonbethann** [comment]
I was updating from 3.3 and it says it installed the new version but nothing changes. 

Beth Erickson
www.bethericksondesigns.com
www.bethannerickson.etsy.com

**Comment by Spellhammer** [comment]
@ericksonbethann Please send us login credentials and a link to your site via https://oxygenbuilder.com/support. We'll need to take a closer look to diagnose the problem.
