### ISSUE TITLE
Dynamic slider "fade" transition

### ISSUE THREAD

**Issue by dwork** [soflyy/oxygen-bugs-and-features#2083]
## Please only open a bug report if the issue can be reproduced on a clean site. If it can't be reproduced, please open a support ticket so that we can take a look at your site.

**Describe the bug**
Your documentation at https://oxygenbuilder.com/documentation/builder-elements/composite-elements/#dynamicslider states the available transitions for dynamic slider (composite element) are: **_The available transitions are "slide", "flip", "cube", and "coverflow"._**

The internal documentation includes "fade": var transition = 'fade'; **_// Tranisition effect. Could be "slide", "fade", "cube", "coverflow" or "flip"_**

In chrome and safari, "fade" doesn't work -- it overlays each slide over the previous slide.(see screenshot)

**Expected behavior**
Fade should either work of be removed from the internal js documentation

**Screenshots**
*If applicable, add screenshots to help explain your problem.*![image](https://user-images.githubusercontent.com/251156/114203485-12903f80-990d-11eb-9f38-6b1cdf8fa4d1.png)

**Comment by Spellhammer** [comment]
Removed "fade" from comment in JS.
