### ISSUE TITLE
oxygen not compatible with "nex forms"

### ISSUE THREAD

**Issue by pattotherick2801** [soflyy/oxygen-bugs-and-features#2084]
Once I have installed Nex Form, I can no longer use the builder because then a window appears. Thank you in advance .
[nex-forms.zip](https://github.com/soflyy/oxygen-bugs-and-features/files/6286794/nex-forms.zip)

![image](https://user-images.githubusercontent.com/82226522/114203802-c834b000-9958-11eb-9837-707c819eb275.png)

Steps to reproduce:
1 . install the attached plugin
2. open the builder on any site

**Comment by KittenCodes** [comment]
@pattotherick2801 

Please install the Code Snippets plugin (https://en-gb.wordpress.org/plugins/code-snippets/) and then create a snippet with the following code to see if that resolves the conflict:

```php
add_action( 'wp_enqueue_scripts', function () {

if (! strpos( $_SERVER['REQUEST_URI'], 'ct_builder=true' ) !== false ) return;

foreach ( wp_scripts()->queue as $wp_script ) {
	
	switch( $wp_script ) {
			
		case 'jquery-ui':
			wp_deregister_script( $wp_script );
		break;
			
			
	}
	
}

});
```

**Comment by pattotherick2801** [comment]
@KittenCodes It works. Thanks a lot
