### ISSUE TITLE
Main Template Not showing! Category Pages showing old edited template !

### ISSUE THREAD

**Issue by amukul** [soflyy/oxygen-bugs-and-features#2086]
Main header and footer template not showing every page. I wanted to show the main template of the entire site but the woocommerce category and single products page showing the old template which I wad created but now no presence of the template on my oxygen template. 
-------------------------------------
This is my root domain template which is I wanted to keep my entire website: 

- [https://comfy.com.bd](https://comfy.com.bd/)

Here is my category pages showing the header menu and footer menu differently which I'm not interested. [women shoes 

- category](https://comfy.com.bd/women/)

**But everything showing fine from my logging browser.**  

https://www.loom.com/share/ba612419fb2d4148bf1f25f375f325db
![comfy](https://user-images.githubusercontent.com/37269657/114282652-fb656500-9a66-11eb-9fdb-5651b7da02db.png)
![Screenshot(1)](https://user-images.githubusercontent.com/37269657/114282708-467f7800-9a67-11eb-9c26-c8cc964f6789.png)
![Screenshot](https://user-images.githubusercontent.com/37269657/114282709-47180e80-9a67-11eb-8661-d8c3ff267e71.png)

**Comment by KittenCodes** [comment]
@amukul Please open a support ticket so that we can take a look at your site: https://oxygenbuilder.com/support.
