### ISSUE TITLE
After installing plugin I get error <<Sorry, you are not allowed to access this page.>>

### ISSUE THREAD

**Issue by seang1968** [soflyy/oxygen-bugs-and-features#2087]
## Please only open a bug report if the issue can be reproduced on a clean site. If it can't be reproduced, please open a support ticket so that we can take a look at your site.

**Describe the bug**
*A clear and concise description of what the bug is.*

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
*Yes/No*

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
*If yes, provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*

**To Reproduce**

**Expected behavior**
*A clear and concise description of what you expected to happen.*

**What actually happens**
*A clear and concise description of what happens instead of the expected behavior.*

**Screenshots**
*If applicable, add screenshots to help explain your problem.*

**Desktop (please complete the following information):**
 - Oxygen Version [e.g. 2.2 Alpha]

**Smartphone (please complete the following information):**
 - Oxygen Version [e.g. 2.2 Alpha]

**Additional context**
*Add any other context about the problem here.*

**Comment by seang1968** [comment]
After installing the plugin, activating it, Trying to follow the tutorial and installing a new blank site I get the message <<Sorry, you are not allowed to access this page.>>

Can you help.
I am on siteground and It is not allowing me to start a new blank site or installing an example site

**Comment by Spellhammer** [comment]
This error is usually caused by the SG Starter or WordPress Starter plugin from SiteGround. If you are using that plugin, please disable it.
