### ISSUE TITLE
Add flex and grid layouts to header builder

### ISSUE THREAD

**Issue by binaryfire** [soflyy/oxygen-bugs-and-features#2088]
It would be great if we could use flex and grid in the header builder to create custom/complex layouts. The current fixed 3-column layout can be limiting.

**Comment by jamescrabb** [comment]
Agree but I think this is a duplicate somewhere in the GitHub list

**Comment by jamescrabb** [comment]
Here [https://github.com/soflyy/oxygen-bugs-and-features/issues/1136](https://github.com/soflyy/oxygen-bugs-and-features/issues/1136)

**Comment by binaryfire** [comment]
@jamescrabb Thanks. I searched but must have missed it. Closing this in favour of the other issue. Will update my Facebook post too.
