### ISSUE TITLE
Advanced custom fields and dynamic data integration (specifically date)

### ISSUE THREAD

**Issue by Jean-Like-Denim** [soflyy/oxygen-bugs-and-features#2092]
## Please only open a bug report if the issue can be reproduced on a clean site. If it can't be reproduced, please open a support ticket so that we can take a look at your site.

**Describe the bug**
*A clear and concise description of what the bug is.*

Hi, I tested on the clean install and was able to reproduce. There seems to be an integration issue with Advanced Custom fields when using the dynamic data and the post repeater field. Specifically with the date selector field. "After saving I got white screen of death." 
I was trying to set up a post archive and I want to display a specific date, not the date of the post.

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
*Yes/No*
Yes, I was able to get my site back up myself, but it's a workaround. I would prefer to be able to use the custom fields and the 'date selector' option. I've just changed the field for now. Also probably a goods heads up.

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
*If yes, provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*

https://oxygen-q6rtbnbag3bfl.oxygen-demo.qsandbox.me/test-post/

**To Reproduce**
1. I uploaded the ACF plugin which I use for almost everything I build Oxygen on. 
2. I created two fields for the demo one being date.
3. I created a template to populate the fields dynamically.
4. Then I created a test post so I could add data to the fields.
5. I added a text field to add dynamic data, selected the date and gave format 'd m Y'
6. Reads the date in the editor so I save and exit to admin.
7. II see white screen with plain text looking menu.

**Expected behavior**
*A clear and concise description of what you expected to happen.*
I expected to save and view the normal wordpress admin section.

**What actually happens**
*A clear and concise description of what happens instead of the expected behavior.*
screenshots below.
**Screenshots**
*If applicable, add screenshots to help explain your problem.*

Added screenshots below, also added the debug screen from my own install.
**Desktop (
<img width="1929" alt="Screen Shot 2021-04-13 at 1 36 42 pm" src="https://user-images.githubusercontent.com/62295974/114502789-e6ebbd00-9c5e-11eb-9b92-d33b5668b89c.png">
<img width="709" alt="Screen Shot 2021-04-13 at 10 02 34 am" src="https://user-images.githubusercontent.com/62295974/114502820-f23ee880-9c5e-11eb-9ad8-077ca287f675.png">

please complete the following information):**
 Chrome
 - Oxygen Version [e.g. 2.2 Alpha]
 
3.7.1 and I tried with 3.8 Alpha

**Smartphone (please complete the following information):**
 - Oxygen Version [e.g. 2.2 Alpha]
Nope.
**Additional context**
*Add any other context about the problem here.*

**Comment by KittenCodes** [comment]
Related: https://github.com/soflyy/oxygen-bugs-and-features/issues/559
