### ISSUE TITLE
Colour Selector doesn't work anymore in Oxygen 3.7.1

### ISSUE THREAD

**Issue by Wolfam999** [soflyy/oxygen-bugs-and-features#2095]
## https://www.wptestdw.de/farbe-test/

**Hello the Colour Selector doesn't work anymore (Oxygen 3.7.1)
Also is it not possible to browse an image from the media library. There will appear
an white empty site*

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
*Yes

issue 1. Steps to reproduce the behavior:
1. Go to 'https://oxygenbuilder.com/try?'
2. Click on 'Section', than on Background Colour
3. See error

**Expected behavior**
*The window with the color picker should open.*

**What actually happens**
*Nothing*

issue 2. Steps to reproduce the behavior:
1. Go to 'https://oxygenbuilder.com/try?'
2. Click on 'Section', Advanced,  Background, than on Background Image, browse image
3. See error

**Expected behavior**
*The media library should open.*

**What actually happens**
*there appears only a white black site*

**Screenshots**
*If applicable, add screenshots to help explain your problem.*

**Desktop (please complete the following information):**
- OS: Big Sur 11.2.2
 - Browser [both: Chrome, safari]
 - Oxygen Version [3.7.1

**Smartphone (please complete the following information):**
 - Oxygen Version [e.g. 2.2 Alpha]

**Additional context**
*Add any other context about the problem here.*

**Comment by KittenCodes** [comment]
@Wolfam999 This is most likely caused by a conflict with another plugin on your site. Please run a plugin conflict test: https://pluginconflict.com/?plugin=Oxygen.

If the issue persists when Oxygen is the only active plugin on the site, please open a support ticket so that we can take a look: https://oxygenbuilder.com/support.

**Comment by Wolfam999** [comment]
that is correct. Thanks!
