### ISSUE TITLE
Oxygen blocks layout is lost in Gutenberg

### ISSUE THREAD

**Issue by KonradDeskiewicz** [soflyy/oxygen-bugs-and-features#2099]
**Describe the bug**
Section designed in Oxygen Builder and saved as a block. When inserted into Gutenberg its all layout is lost. Like some of the styles are missing.
I've tried it many times including fresh WP installation. Same effect every time

**To Reproduce**
1. Create a section with a layout based on a grid
2. save it as a block
3. insert block in Gutenberg
4. See an error

**Expected behavior**
As per your video on YT layout should be there. 

**Screenshots**
In Oxygen:
![image](https://user-images.githubusercontent.com/17060750/114828854-af9a1f00-9dca-11eb-9c46-f179c810942a.png)

In Gutenberg:
![image](https://user-images.githubusercontent.com/17060750/114829006-d9ebdc80-9dca-11eb-9090-e2e6bc1638ee.png)

**Desktop (please complete the following information):**
- OS: Windows
- Browser: Chrome / Brave / Firefox
- Oxygen Version: 3.7.1 + Oxygen Gutenberg 1.4

**Comment by KittenCodes** [comment]
@KonradDeskiewicz Please open a support ticket so that we can take a look at your site: https://oxygenbuilder.com/support.

**Comment by KonradDeskiewicz** [comment]
What do you mean by ticket - this is a bug forum yes or no?

**Comment by KittenCodes** [comment]
@KonradDeskiewicz 

> What do you mean by ticket - this is a bug forum yes or no?

This is for reporting bugs that can be reproduced. The issue you are experiencing isn't a bug - you have something on your site that is breaking the CSS in Gutenberg. As such, we need to take a look at your site.

Please open a support ticket: https://oxygenbuilder.com/support. You need to select "Something's broken and I need help" from the dropdown box on the left.
