### ISSUE TITLE
Plugin Conflict with Oxygen

### ISSUE THREAD

**Issue by webstergroup** [soflyy/oxygen-bugs-and-features#2100]
## Please only open a bug report if the issue can be reproduced on a clean site. If it can't be reproduced, please open a support ticket so that we can take a look at your site.

**Describe the bug**
When A website has the plugin https://wordpress.org/plugins/events-manager/ installed Oxygen color pickers no longer function. Also, if the item used a standard color it is listed as "Color (12)" instead of "Really Bright Red"

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
*Yes*

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
Yes
http://spotless-cheetah.w5.wpsandbox.pro/

**To Reproduce**
The sandbox is already set up
Create an item on an Oxygen page and try to use the color picker

**Expected behavior**
Click the color picker and select the color

**What actually happens**
This was described above

**Screenshots**
*If applicable, add screenshots to help explain your problem.*

**Desktop (please complete the following information):**
- OS: OSX
 - Browser Chrome
 - Oxygen Version 3.7

**Smartphone (please complete the following information):**
 - Oxygen Version [e.g. 2.2 Alpha]

**Additional context**

When the conflicting plugin is active

Uncaught TypeError: this._addClass is not a function
    at $.<computed>.<computed>._create (slider.min.js?ver=1.12.1:9)
    at $.<computed>.<computed>._create (jquery-ui.js?ver=1.11.3:415)
    at $.<computed>.<computed>._createWidget (jquery-ui.js?ver=1.11.3:585)
    at new $.<computed>.<computed> (jquery-ui.js?ver=1.11.3:376)
    at HTMLDivElement.<anonymous> (jquery-ui.js?ver=1.11.3:531)
    at Function.each (jquery.min.js?ver=3.5.1:2)
    at s.fn.init.each (jquery.min.js?ver=3.5.1:2)
    at s.fn.init.$.fn.<computed> [as slider] (jquery-ui.js?ver=1.11.3:523)
    at $.<computed>.<computed>._initControls (iris.min.js?ver=5.6.3:5)
    at $.<computed>.<computed>._initControls (jquery-ui.js?ver=1.11.3:415)

**Comment by KittenCodes** [comment]
@webstergroup 

Please install the Code Snippets plugin (https://en-gb.wordpress.org/plugins/code-snippets/) and then create a snippet with the following code to see if that resolves the conflict:

```php
add_action( 'wp_enqueue_scripts', function () {

if (! strpos( $_SERVER['REQUEST_URI'], 'ct_builder=true' ) !== false ) return;

foreach ( wp_scripts()->queue as $wp_script ) {
	
	switch( $wp_script ) {
			
		case 'jquery-ui':
			wp_deregister_script( $wp_script );
		break;
			
			
	}
	
}

});
```
