### ISSUE TITLE
In Editor Elements with Effect start with opacity 0

### ISSUE THREAD

**Issue by zerrodigital** [soflyy/oxygen-bugs-and-features#2105]
HI,

Please check the issue based on the screenshot below:
- In Editor behavior
- Probably because of update to Oxygen 3.7.1
- Same issue happened on certain elements on frontend, see http://zerrodigital.com/oxy/ on bottom of the page

![4t3t434t](https://user-images.githubusercontent.com/82749071/115140570-7c75bb00-a06a-11eb-93cd-7884c904ce2e.JPG)
![FS2555 - http___zerrodigital com_oxy_contact__ct_builder=true ct_inner=true](https://user-images.githubusercontent.com/82749071/115140572-7ed81500-a06a-11eb-9826-8cdccc887a56.png)

**Comment by KittenCodes** [comment]
@zerrodigital Please open a support ticket so that we can take a look at your site: https://oxygenbuilder.com/support/. You need to select "Something's broken and I need help" from the dropdown box on the left.
