### ISSUE TITLE
WooCommerce Product Images Component’s Border Radius shows the bottom of the main image is cutoff

### ISSUE THREAD

**Issue by philippedcote** [soflyy/oxygen-bugs-and-features#2112]
## Please only open a bug report if the issue can be reproduced on a clean site. If it can't be reproduced, please open a support ticket so that we can take a look at your site.

**Describe the bug**
When using Border Radius with the Product Images Component (WooCommerce), we can clearly see the bottom of the main image is cutoff.

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
Unrelated.

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
No because WooCommerce isn’t installed.

**To Reproduce**
0. (Install the One Page theme)
1. Go to 'Add'
2. Click on 'Product Images Component'
3. Select a product to show
4. Use the Border Radius slider and look at the bottom of the main product image

**Expected behavior**
The bottom of the image is cut off.

**What actually happens**
The bottom of the image shouldn’t be cut off.

**Desktop (please complete the following information):**
- OS: macOS
 - Browser Chrome, Safari
 - Oxygen Version 3.7

**Comment by KittenCodes** [comment]
@philippedcote I've not been able to replicate this: https://oxygen-qmqgjj63cyp7.oxygen-demo.qsandbox.me/product/patient-ninja/.

If you're still experiencing this, please recreate the issue on our Sandbox site. You can install WooCommerce on there to reproduce the behaviour.
