### ISSUE TITLE
Oxygen Builder Composite Element Licence Code dosen't works

### ISSUE THREAD

**Issue by Justacom** [soflyy/oxygen-bugs-and-features#2113]
## Please only open a bug report if the issue can be reproduced on a clean site. If it can't be reproduced, please open a support ticket so that we can take a look at your site.

**Describe the bug**
Hi, 

I have Oxygen Builder in Agency Licence since 2019 and today i would like to use Composite Element but when i active i haven't new element in my builder panel.

Could you help me please ? 

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
*Yes*

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
*If yes, provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*

**To Reproduce**

**Expected behavior**
*A clear and concise description of what you expected to happen.*

**What actually happens**
*A clear and concise description of what happens instead of the expected behavior.*

**Screenshots**
*If applicable, add screenshots to help explain your problem.*

**Desktop (please complete the following information):**
 - Oxygen Version [e.g. 2.2 Alpha]

**Smartphone (please complete the following information):**
 - Oxygen Version [e.g. 2.2 Alpha]

**Additional context**
*Add any other context about the problem here.*

**Comment by KittenCodes** [comment]
> I have Oxygen Builder in Agency Licence since 2019 and today i would like to use Composite Element but when i active i haven't new element in my builder panel.

​To use Composite Elements, please update to Oxygen v3.7 (if it's not already installed), then add your Oxygen licence key to the Oxygen box (not the Composite Elements box) via Oxygen > Settings > License and submit it twice. You should then see the new elements available via the +Add menu in the builder.
