### ISSUE TITLE
Problem with modal menu

### ISSUE THREAD

**Issue by iwaniakmateusz** [soflyy/oxygen-bugs-and-features#2114]
Hey Oxygens! I have a problem, I created a menu with a modal box sliding out from the right side. On the homepage, the menu works properly, however, after going to any other subpage of the website and clicking on the Menu to expand the modal box - the browser displays an empty page with the address: **about:blank#blocked**
I've tried various ways to fix it - I don't know if the problem is that I saved the item as re-usable.
Does anyone have an idea how to fix this?
Thank you in advance for your help!

https://user-images.githubusercontent.com/64742086/115474297-8a1a7480-a213-11eb-8001-05eed6c06f34.mov

https://user-images.githubusercontent.com/64742086/115474309-8d156500-a213-11eb-99c9-9822111a9729.mov

**Comment by KittenCodes** [comment]
@iwaniakmateusz Please open a support ticket so that we can take a look at your site: https://oxygenbuilder.com/support/. You need to select "Something's broken and I need help" from the dropdown box on the left.
