### ISSUE TITLE
Slider with gallery

### ISSUE THREAD

**Issue by crezajill** [soflyy/oxygen-bugs-and-features#2118]
**Any bug report that doesn't include a Sandbox link or replication steps will be closed. If you can't provide these pieces of information, we're happy to help you via our official support channel instead: https://oxygenbuilder.com/support**

**Describe the bug**
Slider and Gallery Issue

**A link to a demo site where the bug has been reproduced https://oxygenbuilder.com/try? (REQUIRED)**
https://clients.upstore.com.my/abi/

**IF YOU CAN'T PROVIDE A SANDBOX REPRODUCTION: Steps required to reproduce the bug:**
1. Go to '...' https://clients.upstore.com.my/abi/
2. Scroll down to '....'http://prntscr.com/11u1hlc
3. See error
4.  Also on the backend side I can't click those elements to delete.

**If you can't fill out the above information, you should not be filing a bug report. Instead, contact us via https://oxygenbuilder.com/support with the details you have and we'll investigate your issue further.**

**Comment by KittenCodes** [comment]
@crezajill 

Any bug report that doesn't include a Sandbox link or replication steps will be closed. If you can't provide these pieces of information, we're happy to help you via our official support channel instead: https://oxygenbuilder.com/support. You need to click "Something's broken and I need help".
