### ISSUE TITLE
Ability to set default units other than PX

### ISSUE THREAD

**Issue by pangaeawebservices** [soflyy/oxygen-bugs-and-features#2121]
It is super annoying to have to choose REM instead of PX since I use it far more often. It would be nice to be able to set the default units for the editor.

**Comment by sadrian80** [comment]
Very convenient would be, if we can either set a default including "none" or even better, recognize and adopt a unit typed into the field. So when default is set to PX and I give 2.5rem, the unit sets to rem.

**Comment by minthaik** [comment]
Yes, please

**Comment by cdbakewell** [comment]
yes - woul dbe really useful

**Comment by bbr13** [comment]
Why not define a unit in the main setting of Oxygen ?

**Comment by sadrian80** [comment]
I really think that setting ONE default unit for everything doesn't make that much sense. We all use different units in relation to the property. I also often set a value of 0, auto, unset, initial or none or calculate values via calc, min-max, etc.. So having the units default to em rather than px would make no difference for many users IMO.

The best solution overall would be an option to have **no unit set for all values**, so we can just type away.

**Comment by bbr13** [comment]
ok
This choose could be one of the possible value to set : no unit for all values

**Comment by wdeer** [comment]
Upvote Upvote Upvote!!!
Having the ability to set a default would be a huge timesaver.. but i'd actually take it a step further and allow the ability to simply type the unit versus having to select it at all. How long does it take to type 'rem' 'em' 'px' especially when you've been doing it for YEARS!?

**Comment by DotComCoach** [comment]
> Upvote Upvote Upvote!!! Having the ability to set a default would be a huge timesaver.. but i'd actually take it a step further and allow the ability to simply type the unit versus having to select it at all. How long does it take to type 'rem' 'em' 'px' especially when you've been doing it for YEARS!?

You can use Recoda Workspace until they do implement that; it already allows for this.

**Comment by Spellhammer** [comment]
We looked into doing default units, but it's not super viable with the way units work in Oxygen. Instead, in 4.2, we introduced auto-units like what @wdeer requested above.

I'm going to mark this as closed since this is probably the closest we'll get to implementing the original request for now.
