### ISSUE TITLE
No custom native WordPress CSS update when a Template is edited

### ISSUE THREAD

**Issue by Janvier7** [soflyy/oxygen-bugs-and-features#2126]
Hello:

The bug occur when I'm  editing a template, like here:
[https://oxygen-qkztxgqnfwhfl.oxygen-demo.qsandbox.me/?ct_template=main&ct_builder=true](https://oxygen-qkztxgqnfwhfl.oxygen-demo.qsandbox.me/?ct_template=main&ct_builder=true)

Then, in a different page (frontend not opened from Oxygen), I add some css code in the native WordPress customizer field and save the changes.
[https://oxygen-qkztxgqnfwhfl.oxygen-demo.qsandbox.me/wp-admin/customize.php?url=https%3A%2F%2Foxygen-qkztxgqnfwhfl.oxygen-demo.qsandbox.me%2Fhome%2F](https://oxygen-qkztxgqnfwhfl.oxygen-demo.qsandbox.me/wp-admin/customize.php?url=https%3A%2F%2Foxygen-qkztxgqnfwhfl.oxygen-demo.qsandbox.me%2Fhome%2F)

Finally, I open a new page (frontend) but not from Oxygen editor, and the changes will not appear until I reurn to edited Template, save the changes in Oxygen and open a new frontend page from Oxygen. 
[https://oxygen-qkztxgqnfwhfl.oxygen-demo.qsandbox.me/home/](https://oxygen-qkztxgqnfwhfl.oxygen-demo.qsandbox.me/home/)

**Comment by KittenCodes** [comment]
@Janvier7 I can't replicate this on the Sandbox site you've set up. Changes in the WordPress Customizer are shown instantly without me needing to go into Oxygen.

**Comment by Janvier7** [comment]
Thanks for the answer @KittenCodes Maybe you can try following my steps but opening your own Sandbox session. Is important open an new tab every time and not from Oxygen.

**Comment by KittenCodes** [comment]
@Janvier7 I just refreshed the front-end of the site and could see my changes instantly.

Please note that Oxygen doesn't have any control over CSS added to the WordPress customizer. If the CSS changes aren't showing for you, it's likely caused by browser caching.

**Comment by Janvier7** [comment]
@KittenCodes I understand. I will investigate deeply and if I find a new way to reproduce the (supossed) bug, I will be back again.
Thanks and  have a good weekend.
