### ISSUE TITLE
Editors can change template

### ISSUE THREAD

**Issue by dualwerk** [soflyy/oxygen-bugs-and-features#2128]
This is a big issue for us: editors and other user roles can edit the main and other templates.

1. Go to any post or page in backend (Edit)
2. Click on 'Edit in Oxygen'
3. Click in the header or footer area of your main template
4. Click on Open & Edit Template
5. Click on Edit with Oxygen beside "Edit Template"
6. Now the template is editable

**Comment by Spellhammer** [comment]
You can prevent access to Oxygen templates using Client Control settings: https://oxygenbuilder.com/documentation/other/client-control/

Set the user or role to "Edit Only" access, then go to each Template in the WordPress editor and check "Lock post in edit mode." We may streamline this in the future to make it easier to lock all templates.
