### ISSUE TITLE
Remove default size restriction of a 'div' element inside Oxygen's visual Builder

### ISSUE THREAD

**Issue by Infusednl** [soflyy/oxygen-bugs-and-features#213]
**Describe the bug**
When creating a mobile menu toggles for my website with Oxygen I have a wrapper div called something like '#mobile-menu-toggle' that contains four 'div' elements with a width of 40px and a height of 2px. You can only see three as they animate when being clicked on. The first and fourth icon bar in the toggle will dissappear and the second and third one are placed on top of eachother.
These two will then rotate forming a cross icon where users can click on to hide the menu.

On the frontend it looks fine as you can see here:

<img width="400" alt="1-mobile-menu-toggle-default-frontend" src="https://user-images.githubusercontent.com/6600256/55567253-8f282c00-56fd-11e9-9eb3-11ab611b75ac.png">

But in the Oxygen Builder each of those div's always have a minimum size of 80px width and 80px height regardless of the smaller size that I enter in.

This makes visual editing it inside Oxygen quite hard. It it possible to remove this 80 by 80px size constraint for displaying div's? You can see it here:

<img width="720" alt="3-menu-toggle-inside-oxygen-builder" src="https://user-images.githubusercontent.com/6600256/55567280-9e0ede80-56fd-11e9-8eb1-8364f09beef0.png">

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
No use, as it looks like this is a built in restriction inside Oxygen.

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
No, I tried but the sandbox keeps crashing as it gives an error when I try to save my page.
It contains clean code that works perfect on two websites I am building with Oxygen.

Both websites show the restriction for a 'div' that are smaller than 80 by 80px.

**To Reproduce**
Try to add a 'div' element and give it a size smaller than 80 by 80px.

**Expected behavior**
I want my div's to show the exact dimensions that I give them.
I understand that small div's are harder to select by clicking on them but in this case I can easily acces them through the 'Structure' window.

Plus this code is cleaner then when I have to add a code block that contains these few simple div's.

**What actually happens**
The three menu toggles with a size of 40px width and 2px height show up as 3 enormeous blocks of 80 by 80px.

**Screenshots**
I posted my screenshots above here.

**Desktop (please complete the following information):**
- OS: Mac OS Mojavé 10.13.4
 - Browser: Issue happens in Chrome, Safari, Opera, Firefox and Firefox Developer Edition on Mac.
 - Oxygen Version: Latest public release at time of writing:  Version 2.2.1

**Smartphone (please complete the following information):**
Doesn't apply to smartphone as editing is done on desktop.
Also the menu toggle shows up correct when viewing my websites on the frontend on an iPhone XR running the latest iOS version.

I also contacted support about this issue but wanted other people to see this too in case they run into the same issue as I have so they can reply too.

Thanks in advance,

Christiaan

**Comment by Gibsonion** [comment]
It's not a bug, if the div height collapses completely you can no longer click on it, if you really have to collapse it in the editor for some reason, simply put a text element inside it and delete all the text.

**Comment by KittenCodes** [comment]
This is by design so that you can select the div element and drag content into it. However, you can override this behaviour by adding the CSS in a stylesheet via _Manage > Stylesheets_:

```css
.ct-div-block:empty {
    min-width: 0px !important;
    min-height: 0px !important;
}
```

**Comment by krstivoja** [comment]
If you set div height or width smaller then default it should be smaller...
