### ISSUE TITLE
Code block - Edit only

### ISSUE THREAD

**Issue by flore89** [soflyy/oxygen-bugs-and-features#2131]
I gave the userrole "admin" the edit only status but added via "enable elements" the **code block** element. As you can see here: Client control settings -> [Screenshot](https://i.ibb.co/PxGy5L6/clientcontrol.png)

Now inside the builder I can delete and add codeblocks, but the controll panel to add PHP, CSS and JS is missing. As you can see here: Oxygen Builder view: [Screenshot](https://i.ibb.co/mJWkwqx/oxygen-builder-view.png)

Is this intended? 

**Versions:**
all browser, any OS
Oxygen Version [Version 3.7.1]

**Comment by Spellhammer** [comment]
It's intended that an Edit Only user can never access the Code Block code editors in the builder. This is for security reasons.

Enabling the Code Block in the Client Control settings for Edit Only user should probably not be possible, as it can cause some confusion and there's no reason a "client" should ever be inserting or deleting a Code Block themselves.
