### ISSUE TITLE
Custom CSS fonts not displayed in backend

### ISSUE THREAD

**Issue by 2zero6** [soflyy/oxygen-bugs-and-features#2134]
**Describe the bug**
Hello from Germany,

I have a small bug. I have disabled the Google Fonts in Oxygen and entered them manually in a stylesheet. In the frontend the fonts are also loaded and displayed properly. In the backend (builder) this is not the case. There I only see the fallback font.

Is this known? 

Greetings Jan

http://attractive-mallard.w5.wpsandbox.pro

1. Go to Frontend, you will see another font an Headlines
2. Go to Backend and Edit Page / Template and you do not see the Font

Loom:
https://www.loom.com/share/77fedea17b39472dbbb730172e928c29

**Comment by KittenCodes** [comment]
@2zero6 Please use a supported method to add a custom font to Oxygen: https://oxygenbuilder.com/documentation/other/using-custom-fonts/.
