### ISSUE TITLE
Issue with Animate On Scroll on class and different devices resolution

### ISSUE THREAD

**Issue by laurentches** [soflyy/oxygen-bugs-and-features#2138]
Hi,

I have two issues with Animate On Scroll. The test website is here : https://travail.top/

First issue: in the first big section on the big title "Hello! Je suis directeur artistique, spécialisé dans le digital. "
I have activated an AOS on the element on a class .anim_header_title. My problem it's that this animation doesn't want to be played on page load. I have to refresh several times the page to see (sometimes) the animation played. If I put the AOS on the ID of the title, it works fine, very anoying because I would like to create different class to animate all elements in my topbar (icon, logo) and title. At the moment it works because I have put AOS on IDs, not on class. I leave the AOS on class juste on the big title for the exemple.

Second issues with AOS is on the section with the title "J'ai réalisé des clips de musique." on the element with the image and the text (slideshow).
I have add an AOS on itn, a slide right effet. I want to change the AOS on the resolution less than 992px by a FadeOut animation. Very strange because i can see this change on the back office but in front office it doesn't works... It's not a cache issue because if i put the text (slideshow) in red, I can see it.

here is an other exemple did on the test website for Oxygen : http://shy-hamerkop.w5.wpsandbox.pro/sample-page/

Do you have any ideas ? :/

Best regards,
Laurent.

(sorry for my bad english)

**Comment by laurentches** [comment]
Is there any support on oxygen or not? 🤔

**Comment by Spellhammer** [comment]
> Is there any support on oxygen or not? 🤔

We don't provide official support here. This GItHub is for bug reports and feature requests.

If you'd like help from our support team, please submit a ticket via https://oxygenbuilder.com/support.

> I have activated an AOS on the element on a class .anim_header_title. My problem it's that this animation doesn't want to be played on page load.

Try setting the animation settings on the element's ID instead of a class.

> I want to change the AOS on the resolution less than 992px by a FadeOut animation. Very strange because i can see this change on the back office but in front office it doesn't works... It's not a cache issue because if i put the text (slideshow) in red, I can see it.

This probably isn't possible because AOS works with data attributes which can't be set via media queries.
