### ISSUE TITLE
Add more breakpoints for responsive design. 

### ISSUE THREAD

**Issue by Filipsons-K** [soflyy/oxygen-bugs-and-features#2140]
Hello, I would like to get more breakpoints selection in the builder.

**Comment by jamescrabb** [comment]
Think this is a duplicate

**Comment by KittenCodes** [comment]
Duplicate: https://github.com/soflyy/oxygen-bugs-and-features/issues/700

**Comment by albertvisuals** [comment]
Yes duplicate, but still not solved....
