### ISSUE TITLE
It's possible to see the License Key used 

### ISSUE THREAD

**Issue by kennylajara** [soflyy/oxygen-bugs-and-features#2141]
**Describe the bug**
*If you go to **settings** > **License** and right click on the input field of the license and select inspect element, you can see the license key. This is specially dangerous for multisite installations where the admins of a site will be able to see the keys used by the super admin.*

**A link to a Sandbox site where the bug has been reproduced**
https://oxygen-qvrsh24avlmfl.oxygen-demo.qsandbox.me/

**Steps required to reproduce the bug:**
1. Go to **settings** > **License**
2. Right click on the input field of the license
3. Select inspect element
4. See the used key in the value attribute of the HTML input.

**Comment by KittenCodes** [comment]
Duplicate: https://github.com/soflyy/oxygen-bugs-and-features/issues/1768
