### ISSUE TITLE
What is the action to get the output?

### ISSUE THREAD

**Issue by kennylajara** [soflyy/oxygen-bugs-and-features#2143]
I am trying to create a plugin like [Real time find a replace](https://es.wordpress.org/plugins/real-time-find-and-replace/) and I found that no HTML replace plugin works with oxygen. Most of those plugins use `add_action('shutdown', 'whatever');` but this seams not to be compatible with Oxygen.

What event do you have so I can replace things in the final output?

**Comment by Spellhammer** [comment]
This isn't a feature request. Please submit a ticket via https://oxygenbuilder.com/support and we can help answer questions like this.
