### ISSUE TITLE
Incompatibility with HTML replacement plugins

### ISSUE THREAD

**Issue by kennylajara** [soflyy/oxygen-bugs-and-features#2144]
**Describe the bug**
When you install any plugin to replace HTML (like this, or this) the site gets broken.

**A link to a Sandbox site where the bug has been reproduced https://oxygenbuilder.com/try? (REQUIRED)**
http://happy-polecat.w5.wpsandbox.pro/

**IF YOU CAN'T PROVIDE A SANDBOX REPRODUCTION: Steps required to reproduce the bug:**
1. Install the plugin
2. Watch the site

**Comment by Spellhammer** [comment]
> Install the plugin

Which plugin?

**Comment by kennylajara** [comment]
> Which plugin?

In the link http://happy-polecat.w5.wpsandbox.pro/ I tried with [Real-Time Find and Replace](https://wordpress.org/plugins/real-time-find-and-replace/) but it I also have tried with [Better Find and Replace](https://wordpress.org/plugins/real-time-auto-find-and-replace/). Both of them works well with other themes but breaks the page with Oxygen.

**Comment by Spellhammer** [comment]
What are you replacing?

**Comment by kennylajara** [comment]
It doesn't matter what you try to replace. I even tried to replace just the word `welcome`.

**Comment by kennylajara** [comment]
Addintional Info: It seems not to be working with any plugin touchin the DOM. Other plugins that breaks the site (but works just fine if I deactivate Oxygen) are **WP Hide & Security Enhancer** and **Hide My WP Ghost Lite**.

**Comment by Spellhammer** [comment]
In what way does the site get broken?

**Comment by kennylajara** [comment]
The initial part of the HTML disappears. Everything from the `<!DOCTYPE html>` to 2 lines before `<!-- END OF WP_HEAD() --> </head>` is gone. The html tag, the head tag, me tags, links, script, style tags... Everything is gone.

**Comment by Spellhammer** [comment]
Cannot reproduce on the provided Sandbox with the Real-Time Find and Replace plugin.

Please submit a support ticket at https://oxygenbuilder.com/support with more details and we can investigate further.

**Comment by KittenCodes** [comment]
After running a search and replace on an Oxygen site, you must resign the shortcodes via Oxygen > Settings > Security.
