### ISSUE TITLE
Modification marker not displayed for Layout > Flexbox Child Controls > "Flex Grow" and "Flex Shrink"

### ISSUE THREAD

**Issue by maltmann-muc** [soflyy/oxygen-bugs-and-features#2145]
WordPress 5.7.1
Oxygen 3.7

**Describe the bug**
In Oxygen editor, left sidebar, advanced sections containing modified setting are marked with a blue dot. For example, if you change the Background Color, the Section "Background" is marked as modified.
When changing Advanced > Layout > Flexbox Child Controls > "Flex Grow" or "Flex Shrink", no marker is displayed.
(It works for Flexbox Child Control "Order")

<img width="305" alt="Bildschirmfoto 2021-05-03 um 10 12 42" src="https://user-images.githubusercontent.com/51136650/116854651-50287580-abf8-11eb-85f4-0112f21571a4.png">

**A link to a Sandbox site where the bug has been reproduced https://oxygenbuilder.com/try? (REQUIRED)**
http://rational-wryneck.w5.wpsandbox.pro/?ct_template=demo&ct_builder=true 

**IF YOU CAN'T PROVIDE A SANDBOX REPRODUCTION: Steps required to reproduce the bug:**
1. Edit a template
2. Add a Section and a Div
3. Change the Background of the Div. Section Advanced > Background is marked as modified
4. Change the Layout Flexbox Child Controls "Flex Grow" or "Flex Shrink". Section Advanced > Layout is **NOT** marked as modified.
5. Change the Layout Flexbox Child Control "order" property. Section Advanced > Layout is marked as modified.

**Comment by KittenCodes** [comment]
Duplicate: https://github.com/soflyy/oxygen-bugs-and-features/issues/64
