### ISSUE TITLE
Oxygen 3.8 Beta 1 Error 500 Reusable Part with conditions

### ISSUE THREAD

**Issue by viabit-dev** [soflyy/oxygen-bugs-and-features#2149]
1. Create a Reusable Part with 3 sections. On each section, set a display condition. For example: Day of Month 
2. Insert Reusable Part with 'Single' option in a page.
3. Save page and exit from editor.
4. If you view the page on the frontend, everything is ok.
5. Go to edit page where Reusable part is inserted and go to edit with Oxygen.
6. Error 500 appears:
![Captura](https://user-images.githubusercontent.com/57798462/116987062-dfa05800-acce-11eb-8014-e3d13b2c4282.JPG)

**Comment by Spellhammer** [comment]
Confirmed behavior and reported internally.

**Comment by flyingwebie** [comment]
This is the bug after the error 500

`PHP Fatal error:  Uncaught Error: Call to a member function global_conditions_result() on null in /var/www/clients/client3/web22/web/wp-content/plugins/oxygen/component-framework/components/component.class.php:3841
Stack trace:
#0 /var/www/clients/client3/web22/web/wp-content/plugins/oxygen/component-framework/components/classes/div-block.class.php(39): CT_Component->validate_shortcode()
#1 /var/www/clients/client3/web22/web/wp-includes/shortcodes.php(343): CT_DIV_Block->add_shortcode()
#2 [internal function]: do_shortcode_tag()
#3 /var/www/clients/client3/web22/web/wp-includes/shortcodes.php(218): preg_replace_callback()
#4 /var/www/clients/client3/web22/web/wp-content/plugins/oxygen/component-framework/components/classes/div-block.class.php(47): do_shortcode()
#5 /var/www/clients/client3/web22/web/wp-includes/shortcodes.php(343): CT_DIV_Block->add_shortcode()
#6 [internal function]: do_shortcode_tag()
#7 /var/www/clients/client3/web22/web/wp-includes/shortcodes.php(218): preg_replace_callback()
#8 /var/www/clients/client3/we in /var/www/clients/client3/web22/web/wp-content/plugins/oxygen/component-framework/components/component.class.php on line 3841`

**Comment by Spellhammer** [comment]
This should be fixed in the RC.
