### ISSUE TITLE
localize was called incorrectly

### ISSUE THREAD

**Issue by samste** [soflyy/oxygen-bugs-and-features#2150]
Fresh install with debug mode activated

Oxygen V. 3.7.1
PHP 7.4

when creating a 1st template I get this message from debug:
**Notice**: WP_Scripts::localize was called incorrectly. The $l10n parameter must be an array. To pass arbitrary data to scripts, use the wp_add_inline_script() function instead. 
Please see Debugging in WordPress for more information. (This message was added in version 5.7.0.) in **/var/www/domain.it/htdocs/wp-includes/functions.php on line 5313**

![Immagine 2021-05-04 160901](https://user-images.githubusercontent.com/10726563/117019968-3cfbcf80-acf6-11eb-8ab5-4c7ebae7d743.png)

**Comment by Spellhammer** [comment]
Fixed in 3.8 beta 1.
