### ISSUE TITLE
Mobile phone image response problem

### ISSUE THREAD

**Issue by Rami-MH** [soflyy/oxygen-bugs-and-features#2151]
Hello
first of all i really want to thank u for ur great service u provide really great service 
 thank u

I have a problem with adding responsive images for some types of phones in my website because the image does not respond to smaller phone screens.

Can you help me with this?

Thank you

page link : [nur4tech.com](url) 

![oxy](https://user-images.githubusercontent.com/83662100/117037674-6c6b0600-ad0f-11eb-8472-d7acc56c3c20.jpg)

**Comment by Spellhammer** [comment]
We'd be glad to help you. Please submit a support ticket via https://oxygenbuilder.com/support and we'll advise.
