### ISSUE TITLE
Bug: backend view of Woo Checkout page render goes wrong

### ISSUE THREAD

**Issue by pgwthf** [soflyy/oxygen-bugs-and-features#2156]
See: http://disturbed-gaur.w6.wpsandbox.pro?upass=Nh3lMyEOc461

On my site the general page template with 4 different menus and a content section looks unrecognisable (one big mess - see screenshots) when I edit the Woo Checkout page. Any other page works fine. The frontend of the Checkout page is also fine.

I reproduced it in the sandbox by inserting menus in the a template and selecting the checkout page for view. Alternatively editing the Checkout page gives the same result. In the sandbox the menus are duplicated only once, on my site many more times, see attached screen shots of front end and back end.

Front end renders fine:
<img width="400" alt="frontend" src="https://user-images.githubusercontent.com/1865028/117292423-78baa480-ae70-11eb-8d9c-be464ae56080.png">

Back end horrible mess:
![backend](https://user-images.githubusercontent.com/1865028/117292393-70fb0000-ae70-11eb-8605-2bc3cc469082.png)

Note: I am not sure it has anything to do with the menus, but that is how it appears, because where the menus should be, the page/template show multiple times - in the sandbox it is less messy, but probably only because the template is much simpler.

(This appears to be a more general Oxygen-Woocommerce related issue, because something similar happens when using a Woocommerce  product images widget, it also shows multiple times in the backend - see my wysiwyg comment in separate bug report https://github.com/soflyy/oxygen-bugs-and-features/issues/2123 )

**Comment by KittenCodes** [comment]
@pgwthf Please add an item to the cart. The template will then display correctly in Oxygen.

**Comment by pgwthf** [comment]
Thanks for your help.
That was one of the things I tried before submitting and it didn't work. Now I tried it again and it does - I must have done something wrong.

Anyway, you may not consider this a bug, but I do think it is not very robust that the viewer completely chokes over something like this, while the frontend behaves properly...
(An error message would have been nice)
