### ISSUE TITLE
border doens't  keep values in UI

### ISSUE THREAD

**Issue by peterpinkster** [soflyy/oxygen-bugs-and-features#216]
**Describe the bug**
I tried to put a border of .3px  or 0.5px  etc.  It doens't accept it. the values Width (and colours are set to blank. The style is still in my design..

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
YES

I think its clear enough what I'm trying to say... Isn't it.

**Expected behavior**
I expect that the interface too keep displaying the values width and color.

**What actually happens**
The softwere doenst let me show the values. It should keep them.

Thank you

**Comment by Barinburo** [comment]
I have the same ussue

**Comment by KittenCodes** [comment]
Duplicate: #95

**Comment by adrien-robert** [comment]
+1

**Comment by Martin-1** [comment]
+1 as well

**Comment by fmommeja** [comment]
+1

**Comment by shamshahar** [comment]
+1
