### ISSUE TITLE
Attributes are not added

### ISSUE THREAD

**Issue by hssktm** [soflyy/oxygen-bugs-and-features#2163]
The attributes to the inner-content are not added.
Example I add an inner-content attribute when pub
lishing the site it was not added.

![Screenshot_01](https://user-images.githubusercontent.com/68758341/117549403-de896680-afff-11eb-8a4f-a339044315c0.png)
![Screenshot_02](https://user-images.githubusercontent.com/68758341/117549404-de896680-afff-11eb-9f1d-9a727d5e6c0c.png)

**Comment by murko-sk** [comment]
Hi, I want to add, that INNER CONTENT is probably bugged at whole, or simply it is intended as a simple placeholder - absolutely nothing you set for it in the properties panel works.

**Comment by hssktm** [comment]
The internal content is definitely buggy. Temporary solution. Wrap inner-content with a "di"

**Comment by murko-sk** [comment]
> The internal content is definitely buggy. Temporary solution. Wrap inner-content with a "div"

Yes, thats the only way around atm.

**Comment by Spellhammer** [comment]
Duplicate of #1642
