### ISSUE TITLE
Inner Content - Wont reflect any style/property settings in frontend.

### ISSUE THREAD

**Issue by murko-sk** [soflyy/oxygen-bugs-and-features#2164]
Hi,
steps to reproduce the bug:

- Oxygen v3.7.1
- create any "Inner content" element, add any style/property from the properties sidebar you want (for example background color)
- those settins are visible and correctly shown in editor only
- save the template and open in it frontend
- you will see that "Inner content" element wont have any of your styles/properties

EDIT: Link for sandbox test setup. Inner content should have 5px black border. 

http://selfish-lizard.w6.wpsandbox.pro/

**Comment by KittenCodes** [comment]
This is happening because the Inner Content Div isn't always output on the front-end of the site. A workaround is to wrap it in a Div and style the Div.

Duplicate: https://github.com/soflyy/oxygen-bugs-and-features/issues/1930.
