### ISSUE TITLE
Div widths set as pixels instead of percentage inside column break point

### ISSUE THREAD

**Issue by andyduo** [soflyy/oxygen-bugs-and-features#2172]
**Any bug report that doesn't include a Sandbox link or replication steps will be closed. If you can't provide these pieces of information, we're happy to help you via our official support channel instead: https://oxygenbuilder.com/support. You need to select "Something's broken and I need help" from the dropdown box on the left.**

**Describe the bug**
*A clear and concise description of what the bug is.*
Setting % width on divs inside a column in a device break point sets the width as px instead of %

**A link to a Sandbox site where the bug has been reproduced https://oxygenbuilder.com/try? (REQUIRED)**
*Provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*
http://sincere-finch.w6.wpsandbox.pro/2017/03/09/hello-world/

**IF YOU CAN'T PROVIDE A SANDBOX REPRODUCTION: Steps required to reproduce the bug:**
1, Open template in Oxygen editor
2, Add a section to the page
3, Add a column to the section
4, Add two divs inside the column e.g 50/50 % widths
5, Select a device break point e.g 992px
6, Select one of the divs
7, change a div width to another value like 30% in the Primary panel
8, note width of div should be set as a percentage in the Primary panel but div width appears in px
9, check Advanced panel > Size & Spacing > Width will be set as 30px
10, Correct behavior should set the div width in % value as per the setting on the Primary panel width setting

**If you can't fill out the above information, you should not be filing a bug report. Instead, contact us via https://oxygenbuilder.com/support with the details you have and we'll investigate your issue further.**

**Comment by KittenCodes** [comment]
Duplicate: https://github.com/soflyy/oxygen-bugs-and-features/issues/895
