### ISSUE TITLE
Shortcode not working

### ISSUE THREAD

**Issue by chajadesign** [soflyy/oxygen-bugs-and-features#2173]
Hello support,

There is an issue with a plugin called Modal Survey which generates surveys. The survey must be embedded with a shortcode.
When using the shortcode inside the shortcode module, the survey is not displayed. I also tested it in the Sandbox see link below.
Only when I deactivate oxygen builder and use the Gutenberg editor the survey will be generated on the page.
The developer of the plugin has also tested it on my site and advices to contact Oxygen Builder.
Maybe it needs to be embedded in a different way, but I also have tried the rich text module without success.

https://oxygen-qlwhkg9n5qsfl.oxygen-demo.qsandbox.me/test/

I am looking forward to your reply.

**Comment by Spellhammer** [comment]
We don't provide official support here. This repository is only for bug reports and feature requests.

Please send us a ticket via https://oxygenbuilder.com/support and we'll be glad to assist.

**Comment by chajadesign** [comment]
Okay, I will send a ticket.
