### ISSUE TITLE
Galley Images DISAPPEAR in all devices views, EXCEPT ALL DEVICES

### ISSUE THREAD

**Issue by edcarreiro** [soflyy/oxygen-bugs-and-features#2174]
**Any bug report that doesn't include a Sandbox link or replication steps will be closed. If you can't provide these pieces of information, we're happy to help you via our official support channel instead: https://oxygenbuilder.com/support. You need to select "Something's broken and I need help" from the dropdown box on the left.**

**Describe the bug** 
I put 4 images in a row using Gallery module inside a section. When I change the view to any device (less ALL DEVICES VIEW) the images disapear and the GALLERY section become of the size of a line.

https://oxygen-q3g65bwjavq7.oxygen-demo.qsandbox.me/test/?ct_builder=true

**IF YOU CAN'T PROVIDE A SANDBOX REPRODUCTION: Steps required to reproduce the bug:**

Create a Section, add a Gallery (grid style) and change the view to anything different of ALL DEVICES.
<img width="1920" alt="Shot2021-05-14_18 15 40@2x" src="https://user-images.githubusercontent.com/53188149/118332940-3e40af80-b4e1-11eb-96b8-f22dccaa54d8.png">

**If you can't fill out the above information, you should not be filing a bug report. Instead, contact us via https://oxygenbuilder.com/support with the details you have and we'll investigate your issue further.**

**Comment by KittenCodes** [comment]
@edcarreiro Please click on the Gallery element, then go to Primary > Layout and select "grid". You should then see the Gallery on the selected breakpoint.
