### ISSUE TITLE
Feature Request: Add Admin Toggle for Plain Text Box added in 3.8 Beta

### ISSUE THREAD

**Issue by jdavidkennedy** [soflyy/oxygen-bugs-and-features#2175]
I have been running 3.8 Beta 1 on a dev site and noticed there is no admin toggle for the new plain text box in the properties pane. I prefer an implementation offered through a third-party plug-in. The duplicate box adds visual clutter to the interface.

Would it be possible to add a toggle in the admin settings for this?

**Comment by Spellhammer** [comment]
What makes you prefer the third-party text box?

Also, we're unlikely to alter Oxygen's core to make room for similar features added through third-party plugins.

**Comment by jdavidkennedy** [comment]
@Spellhammer The third-party text box allows for basic html. I mainly use it to wrap my text in a span for styling. This has been helpful as my experience with nested spans in the builder has not been stable.
