### ISSUE TITLE
I have a problem with oxygen function repeater layout.

### ISSUE THREAD

**Issue by Pin1069** [soflyy/oxygen-bugs-and-features#2178]
Hey guys

I need you to tell solution to fix this problem 
look at the fisrt pictiure that I use repeater funciton to place some img. In oxygen editor it show like that and I want to use it.
![1](https://user-images.githubusercontent.com/81943876/118598275-033bc600-b7d8-11eb-979f-f39c66f07971.JPG)
but! At second picture that show on web localhost. It different from I design on oxygen editor. What I have to do?
![2](https://user-images.githubusercontent.com/81943876/118598759-cc19e480-b7d8-11eb-9d07-bf968b121d00.JPG)

Thank you 

ps sorry for my english and some thai in picture

**Comment by KittenCodes** [comment]
This isn't a bug.

@Pin1069 Please open a support ticket: https://oxygenbuilder.com/support - you need to select "Something's broken and I need help".
