### ISSUE TITLE
Hover Issues on Pictures/Icons

### ISSUE THREAD

**Issue by arbabahmad97** [soflyy/oxygen-bugs-and-features#2182]
Hello there:)

I want to hover picture and symbols/Icons, but it doesn't work. It only works on Text Modules. I compared it and you see it on the video below:

I made a short Video, so you can have a look and check:
[https://www.loom.com/share/3db2d269bfb34c9ca32d3e0ea1064455](url)

Sandbox link
[http://relatable-capuchin.w5.wpsandbox.pro?upass=kCb294CS7xgF](url)

It would be great if you can solve it in the update. Thank you :)

**Comment by KittenCodes** [comment]
This isn't a bug.

If you need help, please open a support ticket: https://oxygenbuilder.com/support. You need to select "General Query".
