### ISSUE TITLE
Google fonts calling Typekit fonts via link tag

### ISSUE THREAD

**Issue by meo8** [soflyy/oxygen-bugs-and-features#2183]
Fonts were connected using Typekit API Token. It's connected properly and works. 
Those fonts are set within the Global Styles / Fonts for **Display Fonts** and **Text Fonts**. 
Looks like fonts set in Global Styles / Fonts settings are calling to Google Fonts even though the selected fonts are Typekit.

Getting an error within the console showing the Typekit fonts being requested as Google Fonts and showing 404 errors. 
When the Typekit is replaced with Google Fonts, the request goes through properly and the console error disappears.

`The resource from “https://fonts.googleapis.com/css?family=museo-sans:100,200,300,400,500,600,700,800,900|alternate-gothic-extra-cond:100,200,300,400,500,600,700,800,900|Array:100,200,300,400,500,600,700,800,900” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).`

Page source shows a link tag with the following:

`<link href="https://fonts.googleapis.com/css?family=museo-sans:100,200,300,400,500,600,700,800,900|alternate-gothic-extra-cond:100,200,300,400,500,600,700,800,900|Array:100,200,300,400,500,600,700,800,900" rel="stylesheet">`

**Comment by KittenCodes** [comment]
Fixed in v3.9 Beta 1.
