### ISSUE TITLE
Signing Shortcodes

### ISSUE THREAD

**Issue by jmcbade** [soflyy/oxygen-bugs-and-features#2187]
**Describe the feature you'd like to see included in Oxygen.**
I would like to see a tic box added to select ALL the items at once for short code signing.

**What are the use cases for this feature?**
Make it quicker to select them all if we want to sign everything.
Right now only a Oxygen selected set are ticked by default to save time but sometimes some are not ticked that would solve an issue if that item was re-signed.  This feature would just make signing everything quicker.
Should be simple to implement.

**Examples of this feature or functionality.**
Many apps have this kind of option for situations like this.

**Comment by KittenCodes** [comment]
Duplicate: https://github.com/soflyy/oxygen-bugs-and-features/issues/2103
