### ISSUE TITLE
website has incorrect information (min php version is incorrect)

### ISSUE THREAD

**Issue by csloz** [soflyy/oxygen-bugs-and-features#2189]
**Any bug report that doesn't include a Sandbox link or replication steps will be closed. If you can't provide these pieces of information, we're happy to help you via our official support channel instead: https://oxygenbuilder.com/support. You need to select "Something's broken and I need help" from the dropdown box on the left.**

**Describe the bug**
*A clear and concise description of what the bug is.*

https://oxygenbuilder.com/documentation/getting-started/install/

Your website says min php version is 5.6

This is incorrect, as you use php7 or above functions.
Please amend appropriately., and ensure any other pages that talk about minimum requirements are amended also.

I would suggest adding a question to the FAQ questions - What are the minimum requirements for Oxygen
PHP7 or above is required for Oxygen.

**A link to a Sandbox site where the bug has been reproduced https://oxygenbuilder.com/try? (REQUIRED)**
*Provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*

**IF YOU CAN'T PROVIDE A SANDBOX REPRODUCTION: Steps required to reproduce the bug:**

Go to https://oxygenbuilder.com/documentation/getting-started/install/
Look for troubleshooting.

Read the text 

Make sure you are using PHP version 5.6 or later.

Install oxygen.
Open Oxygen.
Note that php will give a fatal error in the oxygen/component-framework/components/classes/menu-pro.class.php on line 114 framework, with a call to intdiv()

Look at the php page for https://www.php.net/manual/en/function.intdiv.php
Note it says php7, 8 or above.

I have also ticketed it here - https://github.com/soflyy/oxygen-community/discussions/104
 as I'm unsure if this is community driven or by your company.  Anyway, fix it :)

**If you can't fill out the above information, you should not be filing a bug report. Instead, contact us via https://oxygenbuilder.com/support with the details you have and we'll investigate your issue further.**

**Comment by Spellhammer** [comment]
Fixed.

**Comment by csloz** [comment]
While I see that page has been edited now (a search in google for site:oxygenbuilder.com php shows other potential edits btw)

I would suggest adding a question to the FAQ questions ( https://oxygenbuilder.com/frequently-asked-questions/ ) 
i.e.

**What are the minimum requirements for Oxygen**
PHP7.x is required for Oxygen.
