### ISSUE TITLE
DONE: Add attributes to link / linkwrapper

### ISSUE THREAD

**Issue by ascripter** [soflyy/oxygen-bugs-and-features#219]
**Describe the feature you'd like to see included in Oxygen.**
I'd like to generalize the feature request given here: https://github.com/soflyy/oxygen-bugs-and-features/issues/120

I'd like not only to set target="_blank" to a linkwrapper. I'd also like to set other attributes (i.e. rel="nofollow") on a linkwrapper OR a text link.

**What are the use cases for this feature?**
External links that you don't want to give link juice

**Examples of this feature or functionality.**
Currently only with Code Block

**Comment by doefler** [comment]
I would really appreciate this feature.
Being able to add `target="blank"` is essential to me.

**Comment by AleFerrariP** [comment]
This is totally needed. Is something basic and essential the be able to add "nofollow" and "_blank" attributes. Please give to it some priority because all the competition builders already have it implemented.

**Comment by ivanjuras** [comment]
Yes, this is really necessary. I'd like to be able to add "nofollow" and target="_blank", but I'm not able to.

**Comment by KittenCodes** [comment]
@ascripter @doefler @AleFerrariP @ivanjuras 

> target="blank"

If you click "Set" next to the URL then a window will open that allows you to select "Open link in a new tab". Screenshots: https://d.pr/i/dWvlmc and https://d.pr/i/lxF8PE.

> nofollow

Currently you can do this by adding class, like .nofollow, to the link elements that need to have the rel="nofollow" attribute, then drop this JavaScript into the JavaScript editor of a Code Block on the page (or in your main template):

```js
jQuery('a').attr('rel', '');
jQuery('.nofollow').each( function() {
jQuery(this).attr('rel', jQuery(this).attr('rel') + ' nofollow');
});
```

**Comment by Cenay** [comment]
I would like to add that being able to add a **class** to a link being added to text (where not ALL the text is the link) should _also_ be possible and a part of pretty much all your competitor's builders. 
![Snag_20fce6f5](https://user-images.githubusercontent.com/7416703/67256254-e643e300-f43a-11e9-94fb-8e53ee5a6916.png)

Short of using code blocks or the javascript hack shown above, there isn't a way to accomplish this. And again, I am talking about text that _contains_ a link. Ideally, we should be able to highlight the text that is the link, insert the href and class, title and any other needed attributes.

**Comment by bernardoklock** [comment]
> I would really appreciate this feature.
> Being able to add `target="blank"` is essential to me.

> Yes, this is really necessary. I'd like to be able to add "nofollow" and target="_blank", but I'm not able to.

The same here. The only way to put nofollow or sponsored today is by json code. It's not practical.

**Comment by bernardoklock** [comment]
Link attributes individually for each link.

**Comment by Mario43** [comment]
yes, when will it be?

**Comment by Zyles** [comment]
A part of me died when I found out I was not able to add `target="_blank"` and `rel="nofollow noopener"` to my link wrappers.

**Comment by KittenCodes** [comment]
You can now add attributes to links.
