### ISSUE TITLE
Woocommerce 5.3 leads to blank template and error message. 

### ISSUE THREAD

**Issue by Webdegelijk** [soflyy/oxygen-bugs-and-features#2192]
Template is blank and displays this error message: _Internal Server Error 500. Your server returned a 500 error for the request to //xx/wp-admin/admin-ajax.php._
Disabling woo brings back the template.
Tested at two websites. 

Step to replicate: Update Woocommerce to 5.3.0 (I updated from 5.2.2).

I use Oxygen 3.7.1. 

Regards, 
Paul

**Any bug report that doesn't include a Sandbox link or replication steps will be closed. If you can't provide these pieces of information, we're happy to help you via our official support channel instead: https://oxygenbuilder.com/support. You need to select "Something's broken and I need help" from the dropdown box on the left.**

**Describe the bug**
*A clear and concise description of what the bug is.*

**A link to a Sandbox site where the bug has been reproduced https://oxygenbuilder.com/try? (REQUIRED)**
*Provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*

**IF YOU CAN'T PROVIDE A SANDBOX REPRODUCTION: Steps required to reproduce the bug:**

**If you can't fill out the above information, you should not be filing a bug report. Instead, contact us via https://oxygenbuilder.com/support with the details you have and we'll investigate your issue further.**

**Comment by Spellhammer** [comment]
Unable to replicate based on the provided information. Please contact us via support at https://oxygenbuilder.com/support and we'll be glad to troubleshoot.

**Comment by Webdegelijk** [comment]
Ok I will, thanks so far Elijah. I will let support know the 500 error was in fact in a Oxygen popup (this one https://share.getcloudapp.com/jkuPgOPY, maybe that was unclear).

**Comment by Webdegelijk** [comment]
As soon as I heard back from support I'll share the solution but for now I fixed it by by doing this: _You can reduce the number of items in the preview dropdown box by setting the Preview Dropdown Limit to something like 10 via Oxygen > Settings > General._ I chose 100 by the way. I found this at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/. For some reason this in needed, at least in my install, to be able to use woocommerce 5.3 in combination with Oxygen.
