### ISSUE TITLE
Blocks created by Oxygen do not save CSS classes 

### ISSUE THREAD

**Issue by Jehu** [soflyy/oxygen-bugs-and-features#2200]
CSS Classes added to the Oxygen Gutenberg Block are not saved and not added to the frontend Code. This is a problem because so it is not possible making small styling changes without creating a whole new Block Template (for example for changing background color) or wrapping the Oxygen-Block in a WP Group Block.

Sandbox: https://oxygen-qb7mgr3jcg2fl.oxygen-demo.qsandbox.me/sample-page/

1. Go to https://oxygen-qb7mgr3jcg2fl.oxygen-demo.qsandbox.me/wp-admin/post.php?post=2&action=edit
2. Select one of the Gutenberg Blocks
3. Under 'Advanced' add a CSS Class
4. Save the Page, reload the page
5. The CSS Class is empty again

**Comment by KittenCodes** [comment]
This isn't a bug. Oxygen cannot use classes added to elements in Gutenberg. If you wish to add a class, you need to add it using Oxygen.

If you would like to see this functionality in a future release of Oxygen, please add a vote to the feature request here: https://github.com/soflyy/oxygen-bugs-and-features/issues/976.

**Comment by Jehu** [comment]
I do not agree with this. If there is a Block with an CSS Class field it must work. Or you have to hide/remove the CSS Class field from the UI.
