### ISSUE TITLE
HTTP API Requests redirecting and slow

### ISSUE THREAD

**Issue by shmaltz** [soflyy/oxygen-bugs-and-features#2202]
According to Query Monitor, Oxygen Builder is slowing down the admin pages, particularly the plugin update page, with it's API requests. Perhaps it's because of the redirect from http to https?

Would it be possible for you to fix this?

![oxy](https://user-images.githubusercontent.com/26052646/120212994-b822a980-c200-11eb-816c-8c88eec680a1.png)

**Comment by Spellhammer** [comment]
Fixed in Oxygen 4.1 beta 1.
