### ISSUE TITLE
DONE: Quick Access, Full-screen CSS Standalone CSS Editor

### ISSUE THREAD

**Issue by wapiti-digital** [soflyy/oxygen-bugs-and-features#221]
Feature request here (hopefully I'm doing this correctly). Forgive me if this isn't in the correct place. I'm a Github newbie.

I'd love to have a single page editor that is full screen and accesses the site CSS. I have to open a page and then edit in oxygen and then open the CSS in order to make quick tweaks. I feel this would be useful for most people especially on established sites that need a tweak here and there.

I would recommend just adding a link below "Templates" in the Oxygen admin sub-nav.

**Comment by Phukit** [comment]
This would be very helpful!  I continually have to go in just to tweak css.

**Comment by guyinpv** [comment]
I have to agree with this one. 

And this would apply to all the CSS. There is global CSS (could be many categories and stylesheets), as well as the custom selectors, selector detector, etc.

What I envision is CSS becoming more of a 1st class citizen. It would have its own top-level entry point similar to how you get into Structure now. Then it could open up via a slider or modal popup or something, and be contextually aware of whatever element is selected, to make it as fast as possible to see custom selectors, custom CSS, or just global styles (whatever was opened last perhaps).

A custom design is going to end up with a lot of CSS, it just will. So making the editing process much easier, top level, fewer clicks, and not having to completely change the interface from what was already there, would be very nice!

If I don't have to open the Oxygen editor first to get to CSS, that would be ideal. If I just want to edit some global stuff or custom selectors, that should have its own admin screen, it would make sense.

**Comment by lucas-pelton** [comment]
+1
It would also be awesome to be able to write SCSS in the panel and have it processed and output as proper CSS in the cache.

Even if SCSS could be implemented in the current Custom CSS panel for each element, it would go a LONG way to being able to style children of the element (I'm thinking Code Blocks, Shortcodes, things that generate additional markup) instead of using the "Style Element" button to manually select child elements.

**Comment by aleklisefski** [comment]
+10000000

**Comment by adrien-robert** [comment]
+1

**Comment by Spellhammer** [comment]
Implemented in 4.4 beta 1.

**Comment by wpsumo** [comment]
@Spellhammer Would have been nice to have options to css selectors as well.

And build it out more and have more control like https://oxyframe.com/plugins/style-manager/

**Comment by Spellhammer** [comment]
@wpsumo That's out of scope for this feature request, but it sounds like a good idea. Please post it as a new request.
