### ISSUE TITLE
Moving the site breaks everything 

### ISSUE THREAD

**Issue by thenetireland** [soflyy/oxygen-bugs-and-features#2213]
I wanted to write a big long review but that can go somewhere else! 

Problem: Migrating/Publishing the site to a new server breaks the templates. 

Process:
I exported the site from a staging server using All-in-One WP Migration 
Export to file and import on top of a vanilla wordpress install on the FQDN 

Everything was broken. 
Home Page content was destroyed, Templates were broken and all sorts not behaving. 

I re imported it and did a find and replace in SQL but that broke the whole show again. 

I actually ended up copying the SHORTCODE data from the template on the staging server, 
Find and replace in Sublime and pasting it into the broken template on the live site. 

Repeated for the other oxygen pages like about and contact. 
Thankfully the other pages like Woo Archive and products were intact. 

So this does not play well with migration tools. 
Anyone else having this problem. 

Not very impressed with this tool at all.
But the plugins (import export) are unbelievable.

**Comment by Spellhammer** [comment]
Follow the instructions at https://oxygenbuilder.com/documentation/other/importing-exporting/ to avoid the problems you encountered.
