### ISSUE TITLE
Link Wrapper in Repeater Element for Custom Post Type Breaks Layout

### ISSUE THREAD

**Issue by vallabnayak** [soflyy/oxygen-bugs-and-features#2215]
1. Install CPT UI.
2. Create a custom post type and custom taxonomy for that post type.
2. Create an Oxygen Index template for that post type archive.
3. Add a repeater element with a 5-column grid enabled and add the title, publish date, background image, and author tag. Adjust the repeater div to be an appropriate size with a vertical layout. Publish. Everything should look right.
3. Add a link wrapper within the repeater div but around the content. Set the dimensions of the wrapper to 100%.
4. Once published, the layout will be broken with the elements inside the link wrapper in the wrong locations.

Layout in Oxygen Editor (no margins, no padding on text elements)
![image](https://user-images.githubusercontent.com/11186811/120653549-c6fe9b80-c44e-11eb-9f94-920e6d9b44ce.png)

Structure of Elements
![image](https://user-images.githubusercontent.com/11186811/120653633-e1d11000-c44e-11eb-89a8-111f8e81e370.png)

Layout on FrontEnd
![image](https://user-images.githubusercontent.com/11186811/120653800-0b8a3700-c44f-11eb-9d15-8c42811d2b4d.png)

**Comment by Spellhammer** [comment]
No sandbox link. Please contact us via support at https://oxygenbuilder.com/support with a link to where we can see the issue and we'll investigate.
