### ISSUE TITLE
404 Page Template vs. Archive Template

### ISSUE THREAD

**Issue by yoshi-12321** [soflyy/oxygen-bugs-and-features#2218]
I created a 404 Page Template and checked "Where does this template apply?" --> "Other" --> "404". Also installed is an Archive-Template: "Where does this template apply?" --> "Archive" --> "All Archives".
If I now try to reach a non existing page (e.g. mydomain.com/nonexsistingpage) the Archive Template kicks in and I don´t get the 404 page but instead I see the recent posts.

This can be resolved if I rank the 404-Template higher under the "Template-Priority" nevertheless I´d like to report this. To me this is unsuspected behavior.

Link to Sandbox
https://oxygen-qzlgx3madr4fl.oxygen-demo.qsandbox.me/

|tried in version 3.7 and 3.8]

EDIT: 
I ran into the same Problem with a Search-Result Template. Elijah mentions this behavior in the YouTube tutorial on Search Results Template (https://www.youtube.com/watch?v=BOQ1wFbFIng). The solutions seems to be to edit the priority as mentioned above.

**Comment by KittenCodes** [comment]
> This can be resolved if I rank the 404-Template higher under the "Template-Priority" 

This isn't a bug - you need to use template priority.
