### ISSUE TITLE
Builder erroring when adding two new custom data fields. See Video https://www.loom.com/share/5cbfd2672caf4c6985ceafc5d6d23053

### ISSUE THREAD

**Issue by zeenahz** [soflyy/oxygen-bugs-and-features#2221]
**Any bug report that doesn't include a Sandbox link or replication steps will be closed. If you can't provide these pieces of information, we're happy to help you via our official support channel instead: https://oxygenbuilder.com/support. You need to select "Something's broken and I need help" from the dropdown box on the left.**

**Describe the bug**
*A clear and concise description of what the bug is.*

**A link to a Sandbox site where the bug has been reproduced https://oxygenbuilder.com/try? (REQUIRED)**
*Provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*

**IF YOU CAN'T PROVIDE A SANDBOX REPRODUCTION: Steps required to reproduce the bug:**

**If you can't fill out the above information, you should not be filing a bug report. Instead, contact us via https://oxygenbuilder.com/support with the details you have and we'll investigate your issue further.**

**Comment by KittenCodes** [comment]
@zeenahz 

Please open a support ticket so that we can take a look at your site: https://oxygenbuilder.com/support

You need to select "Something's broken and I need help" from the dropdown box.
