### ISSUE TITLE
Bug with ACF Field DATE

### ISSUE THREAD

**Issue by willybonneau** [soflyy/oxygen-bugs-and-features#2228]
Hello,

It's been 2 times that when I use the DATE custom field of ACF Pro in an Oxygen template, I get an error message on the administration side: 
Error occurred while saving
500
Your server returned a 500 error for the request to //mondns.fr/agenda/.

And on the front end I have the following message:
There was a critical error on this site.

I have tried different date formats but I still get this error.

So I have to use the custom field TEXT instead of the DATE field.

Could you fix this bug?

Thanks

Translated with www.DeepL.com/Translator (free version)

**Comment by KittenCodes** [comment]
Duplicate: https://github.com/soflyy/oxygen-bugs-and-features/issues/559
