### ISSUE TITLE
Problem with slider + testimonial

### ISSUE THREAD

**Issue by peterpinkster** [soflyy/oxygen-bugs-and-features#223]
**Describe the bug**
In my slider I put testimonials.  One of the names I used  the charachter '
all sliders after it have problems with style.  When I removed the '  every slider after it was okay.
I've rebuilid it 3 times! 

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
no

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
Yes if you like

**Expected behavior**
I Expected to be able to write all characters. "  or ' etc.

**What actually happens**
All sliders after lost font color etc.

It acutally fucked up my website.  completly.

**Comment by peterpinkster** [comment]
im glad I made 4 exports to my computer and it saved my site! Wow.. the export function works good.

**Comment by KittenCodes** [comment]
@peterpinkster 

This should be fixed in Oxygen 2.4.1 - please can you confirm?
