### ISSUE TITLE
< in Header element doesn't get HTML encoded and shows header shortcodes in frontend

### ISSUE THREAD

**Issue by gleysen** [soflyy/oxygen-bugs-and-features#2230]
When you add a < sign into the text of a header element, it trows the frontend generation off balance and causes the underlying header shortcode to show inside the entered text on the frontend.

1. Go to editor
2. Add a header element
3. type in some text and add "<24" inside the text somewhere
4. save and look at the frontend

![Screenshot 2021-06-08 at 08 30 24](https://user-images.githubusercontent.com/839660/121134586-dbb6a700-c833-11eb-824c-063fd94e0aaa.png)
![WhatsApp Image 2021-06-08 at 08 01 05](https://user-images.githubusercontent.com/839660/121134592-de190100-c833-11eb-96a4-907a6755c702.jpeg)

**Comment by Spellhammer** [comment]
Unable to reproduce. Please submit a ticket at https://oxygenbuilder.com/support and we'll investigate further.
