### ISSUE TITLE
Cmd + S to quickly save in the editor

### ISSUE THREAD

**Issue by joao-vasconcelos** [soflyy/oxygen-bugs-and-features#2233]
**Describe the feature you'd like to see included in Oxygen.**
Having a simple keyboard shortcut to save the edits like Cmd + S or Ctrl + S would be a significant quality of life improvement.

**What are the use cases for this feature?**
While building a website, one must switch between many apps that all have the shortcut to save the edits. I end up doing Cmd + S constantly while in the Oxygen editor only to be shown the browser's default save dialog. Implementing this shortcut would significantly speed up development and avoid frustration when showing the browser's dialog. This simple change would be a long way to make Oxygen feel like a truly 'native' app.

**Examples of this feature or functionality.**
I believe other visual editors like Divi and Elementor already have implemented this functionality, although none saves as quickly as Oxygen 😉

**Comment by devils-inkpot** [comment]
I guess CMD + S is system default on macOS. But CTRL + S should work.
