### ISSUE TITLE
The stylesheet generated for the page is missing if the slug is in Chinese

### ISSUE THREAD

**Issue by thepadding** [soflyy/oxygen-bugs-and-features#2234]
The Bug: Changes on the builder not reflecting in the actual page when the slug is in Chinese. Later found out that the stylesheet for the page is missing.

The Page: https://oxygen-qy87wxq2b2r7.oxygen-demo.qsandbox.me/%e4%bd%a0%e5%a5%bd/?ct_builder=true

Oxygen Builder: https://oxygen-qy87wxq2b2r7.oxygen-demo.qsandbox.me/%e4%bd%a0%e5%a5%bd/ 

The Missing Stylesheet: https://oxygen-qy87wxq2b2r7.oxygen-demo.qsandbox.me/wp-content/uploads/oxygen/css/%e4%bd%a0%e5%a5%bd-11.css?cache=1623326811&amp;ver=5.7

**Comment by KittenCodes** [comment]
Duplicate: https://github.com/soflyy/oxygen-bugs-and-features/issues/1871
