### ISSUE TITLE
Skip to Content issue

### ISSUE THREAD

**Issue by JTabdesign** [soflyy/oxygen-bugs-and-features#2246]
**Any bug report that doesn't include a Sandbox link or replication steps will be closed. If you can't provide these pieces of information, we're happy to help you via our official support channel instead: https://oxygenbuilder.com/support. You need to select "Something's broken and I need help" from the dropdown box on the left.**

**Describe the bug**
Oxygen causes issues with skip to content plugins. The way the content is set up doesn't allow for the content to be highlighted on posts. This is more of an inner content issue.

**A link to a Sandbox site where the bug has been reproduced menkeshkeshcoffeeroasters.com (REQUIRED)**
*Provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*

**IF YOU CAN'T PROVIDE A SANDBOX REPRODUCTION: Steps required to reproduce the bug:**
1. Go to mythical origins blog
2. Tab and select skip to content
4. You will see it doesn't work. See error the skip to content only works on pages. This is a big accessibility issue.

**If you can't fill out the above information, you should not be filing a bug report. Instead, contact us via https://oxygenbuilder.com/support with the details you have and we'll investigate your issue further.**

**Comment by KittenCodes** [comment]
This isn't a bug report. If you need help, please open a support ticket. I've not been able to see the problem from the steps you've listed.
