### ISSUE TITLE
Oxygen Gutenberg Integration 1.4 + Oxygen Builder 3.8 + user account with manager capabilities  = post editor window broken

### ISSUE THREAD

**Issue by Shemzone** [soflyy/oxygen-bugs-and-features#2249]
**Describe the bug**
*A clear and concise description of what the bug is.*
Oxygen Gutenberg Integration 1.4 + Oxygen Builder 3.8 + user account with manager capabilities  = post editor window broken
With Gutenberg Integration activated, my post edition window is a mess and I have to scroll on the right to access the [+] button to add a Gutenberg block).
Once If Oxygen Gutenberg Integration is deactivated, all is fine but as my customer needs to add Oxy blocks in her posts, I need Oxygen Gutenberg Integration is activated.

**IF YOU CAN'T PROVIDE A SANDBOX REPRODUCTION: Steps required to reproduce the bug:**
1. Install Oxygen Gutenberg Integration (current one is 1.4)
2. Create a user with Manager capabilities
2. Create a post or edit an existing one and edit it with this user
3. See the mess

**Proof with Loom video***
https://www.loom.com/share/db89f735f7ce4af9a85f769c59808dc9

**Comment by Spellhammer** [comment]
Not enough details provided.

Send a support request via https://oxygenbuilder.com/support so that we can investigate in your environment and we'll be glad to assist.
