### ISSUE TITLE
Undefined index: oxygen_lock_post_edit_mode on a fresh install

### ISSUE THREAD

**Issue by fabiomigliaccio** [soflyy/oxygen-bugs-and-features#2250]
On a fresh new WP installation, with the Oxygen Builder 3.8 plugin just installed, we got this error in debug.log:

Undefined index: oxygen_lock_post_edit_mode in /wp-content/plugins/oxygen/component-framework/admin/admin.php on line 117

We did nothing with Oxygen, we've just created some categories for posts and created a single post (not edited with Oxygen)

**Comment by plittlefield** [comment]
Confirmed on existing site WP 3.8 in Docker with Oxygen 3.8.1 and OxyNinja 3.4.1 and all other plugins deactivated.

![2021-07-26_14-30](https://user-images.githubusercontent.com/8265704/126997581-f58b5774-6136-4949-bd73-19bf2c09aba9.png)

**Comment by Spellhammer** [comment]
Fixed in Oxygen 4.1 beta 1.
