### ISSUE TITLE
Unable to translate easy post's Read More

### ISSUE THREAD

**Issue by kunzi** [soflyy/oxygen-bugs-and-features#2252]
I'm unable to translate the easy posts component's Read More text with Loco Translate. It seems that the component has this code in it:

`<a href='<?php the_permalink(); ?>' class='oxy-read-more'>Read More</a>`

Is it missing something?

**Comment by KittenCodes** [comment]
You need to click on the Easy Posts element, go to Templates > Template PHP. You will then see that the text "Read More" is within the HTML.

**Comment by kunzi** [comment]
Ok. Thanks for the tip. How does this work with multilingual sites that use for example WPML?
