### ISSUE TITLE
Error code when adding a video

### ISSUE THREAD

**Issue by Quin452** [soflyy/oxygen-bugs-and-features#2254]
I add a video, and the default video that is loaded works fine.  However, when I add my own non-YouTube, it returns with this error:

https://prnt.sc/15t19fd

Steps to reproduce:

1. Go to Builder
2. Add -> Video
3. Paste in URL
4. View on frontend
5. Video loads, but has screenshotted error

On a side note, the video preview remains as the default (and not a preview of my own).
The video is hosted on a WordPress site.

**Comment by KittenCodes** [comment]
@Quin452 The Video element is intended for Vimeo and YouTube videos only. If you want to add a self-hosted video, you need to use the HTML Video tag in a Code Block.
