### ISSUE TITLE
Slider shows images below each other and throw a console error

### ISSUE THREAD

**Issue by Tobias-Conrad** [soflyy/oxygen-bugs-and-features#2276]
Screencast Oxy: slider issue
http://somup.com/criV1BYcn6
`jquery.min.js?ver=3.5.1:2 Uncaught TypeError: $(...).unslider is not a function
    at HTMLDocument.<anonymous> ((index):301)
    at e (jquery.min.js?ver=3.5.1:2)
    at t (jquery.min.js?ver=3.5.1:2)
...`

maybe related to https://github.com/soflyy/oxygen-bugs-and-features/issues/1118

**Comment by KittenCodes** [comment]
@Tobias-Conrad If you would like us to take a look at this for you, please open a support ticket: https://oxygenbuilder.com/support.

It's not something I can replicate on a clean Sandbox site.
