### ISSUE TITLE
Edit "Gallery" photos in Gutenberg

### ISSUE THREAD

**Issue by vitorrloureiro** [soflyy/oxygen-bugs-and-features#2280]
**Describe the feature you'd like to see included in Oxygen.**
The ability to edit Gallery photos when "Make this page editable in Gutenberg" is selected.
It would be super useful and would simplify workflow a lot.

**What are the use cases for this feature?**
Website content management by the client.

**Comment by KittenCodes** [comment]
Duplicate: https://github.com/soflyy/oxygen-bugs-and-features/issues/752
