### ISSUE TITLE
Oxygen Builder Saving troubles with WAF (web application firewall)

### ISSUE THREAD

**Issue by runechronos** [soflyy/oxygen-bugs-and-features#2281]
Hy,

I'm posting this problem here as it is not possible to solve it with my hosting provider.

It seems Oxygen is using some dangerous "code" at multiples spots.

Those Rules ID's are related to some potential security hacks:

**212340**: Cross-site Scripting (XSS) Attack
**212800**: 212800 XSS Attack Detected
**211540** : Blind SQL Injection Attack
**211220**

When the WAF is enabled, even when all rules related to the "Saving" action inside the Oxygen Builder are disabled, saving a page take 2-3 minutes. It's impossible to use oxygen in those conditions. It is working normally if I deactivate the WAF. I don't get why, no errors are logged by the WAF when the rules related to saving are disabled.

You really have to fix this as soon as possible, it is there since the release of Oxygen Builder and yet not taken care of !

Thanks for your suggestion and help.

**Comment by Spellhammer** [comment]
Please submit a support ticket for issues like this: https://oxygenbuilder.com/support.
