### ISSUE TITLE
dynamic data and srcset images not compatible using the Oxygen UI

### ISSUE THREAD

**Issue by jamescrabb** [soflyy/oxygen-bugs-and-features#2283]
Whilst adding dynamic data it is currently not possible to use srcset images using the oxygen UI as you can't use the media library option for images which allows for srcset images and dynamic data is only an option on URL images which don't support srcset.

Would be nice not to have to use  a code block to dynamically display images.....

**Comment by KittenCodes** [comment]
https://github.com/soflyy/oxygen-bugs-and-features/issues/107
