### ISSUE TITLE
Flex reverse

### ISSUE THREAD

**Issue by guillaumelorain** [soflyy/oxygen-bugs-and-features#2284]
Hello,

I noticed that the reverse check option for flex css is not working on live website. 
In the oxygen builder it's working, but then on front office there are not css class added when I check the button.

The problem happens when you create a class from the selector.

In the sandbox I used the .test class

The order of the text should be 1 2 3.

http://fair-capybara.w6.wpsandbox.pro/

Thanks

**Comment by KittenCodes** [comment]
@guillaumelorain I took a look at the Sandbox site, but there weren't any layout options set for the "tests" class.

If you are still having problems, please include a screenshot showing the settings that aren't working.
