### ISSUE TITLE
CPT Archive Template Not Loading

### ISSUE THREAD

**Issue by shmaltz** [soflyy/oxygen-bugs-and-features#2285]
### Setup
We have an archive template (product archive) set to "All Archives" with a priority of "10".

We have a CPT archive set to "{CPT-name} archive" with a priority of "100".

Oxygen v3.8

### Issue

While this setup used to load the CPT archive template properly, it recently started loading the product archive template instead of the correct CPT template.

I am not sure when this started, but I presume it started since we updated to _v3.8_.

Additionally, on that specific archive page I get this notice in the logs:
`NOTICE: wp-content/plugins/oxygen/component-framework/component-init.php:610 - Undefined property: WP_Post_Type::$ID`
`NOTICE: wp-content/plugins/oxygen/component-framework/component-init.php:688 - Undefined property: WP_Post_Type::$ID`

This notice only appears on this CPT archive, and not on the CPT single pages.

**Comment by KittenCodes** [comment]
@shmaltz Please open a support ticket so that we can take a look at this for you: https://oxygenbuilder.com/support.
