### ISSUE TITLE
WPML Template compatibility

### ISSUE THREAD

**Issue by marcorubiol** [soflyy/oxygen-bugs-and-features#2289]
**Describe the feature you'd like to see included in Oxygen.**
I would like to have a full compatibility with WPML. That means to can translate templates like WPML uses to do it in the other parts (pages, posts, CPT...)

**What are the use cases for this feature?**
All multilingual sdites

**Examples of this feature or functionality.**

**Comment by KittenCodes** [comment]
Duplicate: https://github.com/soflyy/oxygen-bugs-and-features/issues/938
