### ISSUE TITLE
Shortcode signature bug with some plugins

### ISSUE THREAD

**Issue by johnchatel** [soflyy/oxygen-bugs-and-features#229]
**Describe the bug**
*A clear and concise description of what the bug is.*
I have two kinds of bugs (2 differents websites) concerning shortcode signature:
- Error message in the oxygen builder when Popup maker plugin is active
- Error message in the WP post editor when YOAST SEO plugin is active

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
Yes I regenarated the shortcode signatures in Oxygen settings but the bugs were not fixed.

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
*If yes, provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*
I tried to replicated the configuration but it was ok on sandbox.

**What actually happens**
*A clear and concise description of what happens instead of the expected behavior.*
Error message display...

**Screenshots**
*If applicable, add screenshots to help explain your problem.*
With Yoast SEO
<img width="793" alt="image" src="https://user-images.githubusercontent.com/6806329/55894175-ede81c80-5bb9-11e9-93ec-ba40bafb14cc.png">
With Popup Maker
<img width="1024" alt="image" src="https://user-images.githubusercontent.com/6806329/55894285-24259c00-5bba-11e9-997b-eebb50b1de70.png">

**Desktop (please complete the following information):**
- OS: OSX Mojave 10.14.3
 - Browser Firefox and Chrome
 - Oxygen Version  2.2.1

**Comment by KittenCodes** [comment]
Hey @johnchatel, if you're still having problems with this on your site, please send an email to support@oxygenbuilder.com.

**Comment by vlloyd6684** [comment]
Is there a fix for this? I'm having the same issue. Yoast causes the shortcode error to appear on a couple of pages. When I disable Yoast, the error goes away. I tried regenerating the shortcodes in Oxygen> Settings>Security, but it didn't fix the problem.
