### ISSUE TITLE
Freelance: white strip in responsive

### ISSUE THREAD

**Issue by Bertille22** [soflyy/oxygen-bugs-and-features#2292]
Hello,

**Describe the bug**
There is a bug with the Freelance theme which creates a white stripe in smartphone format :
<img width="393" alt="Capture d’écran 2021-07-07 à 17 51 54" src="https://user-images.githubusercontent.com/85237314/124791369-4864b480-df4c-11eb-810d-7d6caaf1d123.png">
This display problem is accentuated when adding additional sections and divs.

Ex : https://seriousgroup.fr/
Perform a screen inspection, then switch to smartphone format, starting at 340x328.

**A link to a Sandbox site : https://oxygen-qwcdwg7x47s7.oxygen-demo.qsandbox.me/home-page

We are using version 3.8 of Oxygen.
Waiting for your answer,
Bertille

**Comment by KittenCodes** [comment]
@Bertille22 If you'd like help to get your site to be fully responsive, please open a support ticket: https://oxygenbuilder.com/support.

> There is a bug with the Freelance theme which creates a white stripe in smartphone format

I've not been able to replicate this behaviour on a physical mobile device.
