### ISSUE TITLE
Repeater not working with attachment post types

### ISSUE THREAD

**Issue by zuroma999** [soflyy/oxygen-bugs-and-features#2293]
**Describe the bug**
The repeater element, when used with attachment post types, will break.

1. On the sandbox site, I added some sample posts and then added a repeater containing a text element to display the post title. The repeater properly works when the post type is 'posts'.
2. I then uploaded some random images to the media library and changed the repeater to use post type 'attachment' and reloaded the sample page and nothing is displayed.

Please fix this, as this is the only way we will be able to display Toolset image fields attached to a post (we already have a custom function converting the image field URLs to a list of attachment post IDs, but were surprised when the repeater we used the function with broke). If you have a temporary fix, please let us know. 

**A link to a Sandbox site where the bug has been reproduced https://oxygenbuilder.com/try? (REQUIRED)**
http://beautiful-vulture.w5.wpsandbox.pro/

**Comment by KittenCodes** [comment]
@zuroma999 You need to use an Advanced Query with the following two parameters:

post_type > attachment
post_status > inherit

Screenshot: https://d.pr/i/w1LrRn.

You can then get the image to show by adding an image, selecting "data" > PHP Function Return Value. Enter the function name wp_get_attachment_url.

I've set this up for you on the Sandbox site: http://beautiful-vulture.w5.wpsandbox.pro/sample-page/.

**Comment by zuroma999** [comment]
Thanks so much! We had it all, except the post_status argument, which fixed it.
