### ISSUE TITLE
SVG iconsets not working (v3.8)

### ISSUE THREAD

**Issue by astacreative** [soflyy/oxygen-bugs-and-features#2294]
This is the error showing on every page on the front end and also on the SVG settings page in Oxygen:

**Warning: Invalid argument supplied for foreach() in /home/u55337p52591/domains/xxx/public_html/wp-content/plugins/oxygen/component-framework/component-init.php on line 461**

The SVG iconsets are not showing in the backend and in the builder the dropdown box for SVG icons is not working.

The installation is currently running in PHP v7.4 (tried v7.3 too). With only Oxygen plugin activated (all other plugins are deactivated) the error still shows and SVG icons not working. Caching is off.

Downgrading to v3.71: error is gone and SVG sets are working.

**Comment by Spellhammer** [comment]
Do you have the OxyNinja plugin/icon set installed?

**Comment by astacreative** [comment]
> Do you have the OxyNinja plugin/icon set installed?

Yes

**Comment by astacreative** [comment]
I see that v3.8.1 has just been released: 
Tweak: Changed ct_svg_sets_names default option value to avoid issues with missing icon sets in some rare cases (#3640)

I'm still seeing the same error.

**Comment by Spellhammer** [comment]
Please contact our support team: https://oxygenbuilder.com/support. We believe this to be caused by something in the OxyNinja plugin, and have contacted them, but we can make a modification to your database to fix the issue in most cases.
