### ISSUE TITLE
"Uncaught SyntaxError: Invalid or unexpected token" in Oxygen Pro Menu

### ISSUE THREAD

**Issue by Nathaniel-Fernandes** [soflyy/oxygen-bugs-and-features#2295]
If you [go to my website](chessintellect.com) and open up the Dev Tools, you should see the error "Uncaught SyntaxError: Invalid or unexpected token" on the Oxygen Pro Menu. 

Chrome finds issue with this line, but I don't see what's wrong with it:
`jQuery('#-pro-menu-82-4317 .oxy-pro-menu-show-dropdown .menu-item-has-children > a', 'body').each(function(){
                jQuery(this).append('<div class="oxy-pro-menu-dropdown-icon-click-area"><svg class="oxy-pro-menu-dropdown-icon"><use xlink:href="#FontAwesomeicon-caret-down"></script></div>');  });`

Because of this bug, the jQuery code isn't executed and is instead just shown as plain html text. Please fix!

**Comment by KittenCodes** [comment]
@Nathaniel-Fernandes Please run a plugin conflict test to see if the issue is caused by another plugin on your site: https://pluginconflict.com/?plugin=Oxygen.

If that doesn't help, please open a support ticket: https://oxygenbuilder.com/support
