### ISSUE TITLE
How I can hide the numbers in related products for One Page 2 Template?

### ISSUE THREAD

**Issue by titorusperu** [soflyy/oxygen-bugs-and-features#2296]
Hi, How I can hide the numbers in the related products  and magnifying glass Icon too? Also how can Align product section to principal menu?

I´m using  One Page 2 template for this store, I don´t like how appears numbers in prducts section, I want Hide them.

Thanks a lot.

![pregunta git hub](https://user-images.githubusercontent.com/38791267/125085687-7a7f2f00-e090-11eb-9c03-c1aab65b5b76.jpg)

**Comment by KittenCodes** [comment]
@titorusperu You need to include the Product Builder in your template and then drag your design inside it to overwrite the default layout. Once that's done, the Product Images should display correctly.
