### ISSUE TITLE
Multiple tax_query or meta_query arrays in the Advanced Builder are not working 

### ISSUE THREAD

**Issue by adamslowe** [soflyy/oxygen-bugs-and-features#2297]
I’m having trouble getting the Repeater’s Advanced Query feature to recognize multiple arrays for tax_query or meta_query using AND or OR relations. This issue has been happening since the beta versions of 3.8. 

URL: https://oxygen-qzfxy647dfmgl.oxygen-demo.qsandbox.me/wp-admin/

When I create the query using wp_query in a code block everything works as it should.
![image](https://notes.peakperformancedigital.com/box/attachment/5781310/utqsmduhx8r761mfomm6/49eOPsFLxhxmZvCW/image.png)
This returns the cities Boston & Charleston, as it should, ignoring other pages within the city-cpt custom post type that aren’t 1. classified with city-home, and 2. aren’t in north-america.

**Working WP_Query results:**
Boston
Charleston

When I try to create the same query using the Advanced Queries tool
![](https://notes.peakperformancedigital.com/box/attachment/5781310/utqsmduhx8r761mfomm6/QrmDSuvUFTcww8bR/image.png)
You’ll see that it pulls all pages with the page-type city-home, but ignores the “AND” Relationship specifying that it should also be in north-america. 

**Non-Working Advanced Query**
Amsterdam
London
Boston
Charleston

**See a screenshot of the direct output below:**
 ![](https://notes.peakperformancedigital.com/box/attachment/5781310/utqsmduhx8r761mfomm6/lOoo86y7mSLy02xC/image.png)

If I then change the order of the tax_query inside Advanced Query, the results now return all pages with the north-america category, ignoring that it should only return pages that are also categorized as city-home. 
![](https://notes.peakperformancedigital.com/box/attachment/5781310/utqsmduhx8r761mfomm6/nRQOEPUxgsfO5il5/image.png)
 
**Non-Working Advanced Query (Reversed)**
Charleston – About (this is a sub-page of Charleston which is not categorized with city-home)
Boston
Charleston

I also see the same behavior when working with meta_query parameters.

Secondarily, it doesn’t look like Advanced Query is built to handle nested queries. Is that something on the horizon or should I find a workaround for that?

Any help is appreciated.

**Comment by KittenCodes** [comment]
Reported internally.

> Secondarily, it doesn’t look like Advanced Query is built to handle nested queries. Is that something on the horizon or should I find a workaround for that?

Please could you explain how you're nesting your queries?

**Comment by adamslowe** [comment]
@KittenCodes I'm not nesting them in any of the above examples, but I did notice that the wp_query builder doesn't let you create a nested structure while I was testing. For example:

Return all results that satisfy: 
"quotes" OR ("post-format-quote" AND "wisdom")

***code sample from https://developer.wordpress.org/reference/classes/wp_query/***

$args = array(
    'post_type' => 'post',
    'tax_query' => array(
        'relation' => 'OR',
        array(
            'taxonomy' => 'category',
            'field'    => 'slug',
            'terms'    => array( 'quotes' ),
        ),
        array(
                        'relation' => 'AND',
                        array(
                    'taxonomy' => 'post_format',
                    'field'    => 'slug',
                    'terms'    => array( 'post-format-quote' ),
                        ),
                        array(
                                'taxonomy' => 'category',
                                'field'    => 'slug',
                                'terms'    => array( 'wisdom' ),
                        ),
        ),
    ),
);
$query = new WP_Query( $args );

**Comment by PetterAD** [comment]
Have you found a solution or gotten any help on this issue @adamslowe? I'm having trouble with the same thing, regarding multiple arrays for meta_query.

**Comment by KittenCodes** [comment]
Fixed in v3.9 Beta 1.
