### ISSUE TITLE
Page width ruler for device declaration is set to wrong width

### ISSUE THREAD

**Issue by quadcom** [soflyy/oxygen-bugs-and-features#230]
### Describe the bug
Choosing a device declaration in the drop down resizes the workspace UI but the resized window is not the size as listed. eg; Page Container 1440px resizes the workspace window to just about 1000px

### Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?
**Yes**

### Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?
*If yes, provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*

**Yes, all the device declarations resize the workspace to a width smaller than that defined.**

### To Reproduce
**Steps to reproduce the behaviour:**
**1. Go to any page**
**2. Click on device declaration button and choose a different page width rule**
**3. Check the ruler at the bottom of the workspace and the width will be smaller than that defined in the device declaration**

### Expected behaviour
**Choosing a device width of 1440px should resize the workspace UI to 1440px. Same goes for the other device declaration page widths**

### What actually happens
**The width of the workspace will be smaller than that defined in the device declaration**

### Screenshots
*If applicable, add screenshots to help explain your problem.*
![image](https://user-images.githubusercontent.com/7085931/55983478-3dd1ec80-5c69-11e9-978f-d16778f31e2e.png)

### Desktop (please complete the following information):
 **- OS: Windows10**
 **- Browser Chrome 73.0.3683.86** 
 **- Oxygen Version 2.2.1**

**Comment by KittenCodes** [comment]
@quadcom,

This isn't a bug. Oxygen will automatically show the smallest size the selected viewpoint could apply to when selecting the break point. Otherwise, you may make a design that looks perfect on 1440px, but doesn't work on 993px.
