### ISSUE TITLE
Code block issue in Oxygen 3.8 and 3.8.1

### ISSUE THREAD

**Issue by ahforayeji** [soflyy/oxygen-bugs-and-features#2300]
Hello Oxygen Experts
I found a problem with Code Block
I have designed a custom mega menu and used some of my CSS on code block which I cannot trigger by the selector or I do not know how to trigger them on selector like something (.mega-menu:hover .mega-menu-item). As it is a header, I used a code block on the top of the template and it was loading everywhere. Just not loading on a specific page. First of first I thought it may be a cache problem by hosting because I am not using any cache plugin that is why I called the hosting company and they said that they are not using any cache system on their hosting. Then I start investigation and found that these CSS which is on the code block it is not loading on the page. Instantly I moved then from the code block to a stylesheet and now it is fine.
Note: Now I am using Oxygen version 3.8.1
Same thing I found with 3.8 too. Some days before I posted that my footer is commented and not loading. At the end of the day, I found that there was an empty code block on my reusable template which was doing this. There was some CSS on the code block, but no php or no JavaScript. First, I thought it is a problem of reusable part but after some days I found that actually it was the code block which was making this problem. Moved the CSS to stylesheet then still same. When deleted the code block then it is ok.
So, I hope other people if you are facing this type of same problem then you can understand it. Or if just I am facing this problem, then what to do?
Thank you very much

**Comment by KittenCodes** [comment]
@ahforayeji Please either open a support ticket so that we can take a look at your site ( https://oxygenbuilder.com/support ) or replicate this issue on our Sandbox site ( https://oxygenbuilder.com/try ) and add the Sandbox details to this issue.
