### ISSUE TITLE
Option to Disable Pagination in Repeater Element

### ISSUE THREAD

**Issue by vijaykumarim** [soflyy/oxygen-bugs-and-features#2305]
I recently started using the repeater element a lot in my projects. I found that a option to disable the pagination in the repeater element is great.

Use cases: We don not always want to show all the posts/custom fields in the repeater element. For example I want to add recent posts in the footer section of my website and footer section should not have pagination for those recent posts list. 
This is how we want to show: https://prnt.sc/1bt5wuz
but now only showing like this: https://prnt.sc/1bt6cgx

There is no way I can use the element to show my recent posts without pagination. This is not only applicable in this scenario but also in lot of cases. 

Yes we can hide with CSS by adding display:none but in the HTML it is still present and it won't do any good in terms of SEO and website crawling. 

So request to add this feature to disable pagination in repeater element in Oxygen Builder in coming update. 

Thank you

**Comment by KittenCodes** [comment]
You need to add no_found_rows = true to the query to prevent pagination from showing. That can be done using an Advanced or a Manual query.

**Comment by MattHag** [comment]
Yes, no_found_rows works. However, it's very convenient to use the custom query UI, where just this one button to disable pagination is missing.

**Comment by pixluser** [comment]
That should be integrated into oxygen…

**Comment by shoelaced** [comment]
Can this be reopened and considered? It would be much easier to simply offer a "disable pagination" checkbox or something.

**Comment by teknology** [comment]
+1 I just experienced this.

**Comment by vijaykumarim** [comment]
> Can this be reopened and considered? It would be much easier to simply offer a "disable pagination" checkbox or something.

True, @KittenCodes can you please add small check box or someother way to disable pagination?

Thank you

**Comment by sirhenryhu** [comment]
Ditto. Especially while using the manual method can be such a time killer to non-techie ones like me.

**Comment by DanDawson** [comment]
I am using a Custom query type (not Manual) and need to disable pagination. 

Please add a checkbox to make this super easy. Or what is the method to take all of the details of my custom query and convert it to a manual query? Is there Query export method?

@KittenCodes: How do we go about seeking this issue to be re-opened, or shall I just submit a new issue?

**Comment by jay0110** [comment]
Is this now closed? Is there a new fix or feature to this issue?
