### ISSUE TITLE
"Hello World" BUG on Home Page & Edit Template Page

### ISSUE THREAD

**Issue by menjilx** [soflyy/oxygen-bugs-and-features#2310]
Did anyone encounter this issue? Only "hello world" is shown on the "home page" all other subpages are working fine. This site is hosted in Namecheap.

Home: http://demo.braintreeinteractivemedia.us/
Subpage: http://demo.braintreeinteractivemedia.us/about-us
![image](https://user-images.githubusercontent.com/14908836/126529218-b305fe93-3b32-4094-a707-404c3e0366da.png)

Edit Template Page
![image](https://user-images.githubusercontent.com/14908836/126529459-0c1311e0-7546-48f2-b658-270dcc2b10e8.png)

All templates are signed already, CSS cached generated already, static page set to "home page" as well. And lastly "Home page" template is set to "front page" also.

**Comment by jamescrabb** [comment]
How is the "homepage template" assigned to the homepage? 

Have you not just edited the homepage page? It sounds like you have made a template for the homepage which is unnecessary

**Comment by KittenCodes** [comment]
@menjilx If you're still having problems, please open a support ticket so that we can take a look at your site: https://oxygenbuilder.com/support.
