### ISSUE TITLE
Add width and height attributte in images

### ISSUE THREAD

**Issue by flabernardez** [soflyy/oxygen-bugs-and-features#2317]
Add width and height attributte in images automatically when the sizes are filled in Primary tab.

Now I have to do that twice: one on Primary Tab and another when in the Advanced tab when I attach atributtes in that element.

That will be awesome to performance issues.

Thanks!

**Comment by jornessim** [comment]
+1

**Comment by MattHag** [comment]
That's a great suggestion, that I miss badly in my fight to minimize CLS.

I expect something as basic as this to be handled by Oxygen.

**Comment by MattHag** [comment]
This issue is also a duplicate of the often requested
https://github.com/soflyy/oxygen-bugs-and-features/issues/1752

There are 4 issues requests for that, that need to be combined to calculate the urgency/like score for that.

**Comment by Kpudlo** [comment]
duplicate of #1752
