### ISSUE TITLE
My site broke

### ISSUE THREAD

**Issue by viniciusmartin** [soflyy/oxygen-bugs-and-features#2318]
**Describe the bug**

My website crashed after I installed Yoast SEO.

I noticed that the footer (as well as the enqueues) do not appear at the end of the page (the </body> and </html> tags are missing).

I reinstalled Oxygen Builder (even for previous versions), updated WordPress to 5.8, disabled all plugins and even then it didn't work.

At this time only Oxygen Builder is active on the site.

**Link**

https://franquia.aprovacredito.com.br/

**Server**

Server architecture:  Linux 3.10.0-962.3.2.lve1.5.28.el7.x86_64 x86_64
PHP:  7.4.21
PHP time limit:  300
PHP memory limit:  256M
Upload and Post max size:  32M
Database:  10.3.30-MariaDB-cll-lve  /  Charset:  utf8mb4

**Comment by KittenCodes** [comment]
@viniciusmartin Please open a support ticket so that we can take a look at your site: https://oxygenbuilder.com/support.
