### ISSUE TITLE
FEATURE: Live view link in the dev UI

### ISSUE THREAD

**Issue by quadcom** [soflyy/oxygen-bugs-and-features#232]
**Describe the feature you'd like to see included in Oxygen.**
Simple button/link at the top of the page to open a new window with the live page loaded. Currently, the only way is to either flip out of dev to the live page or manually open a tab/window and nav to the page.

**What are the use cases for this feature?**
ease of use, workflow speed enhancement (would be great if it was incognito to bypass cached pages)

**Examples of this feature or functionality.**
*If another product has done it well, provide examples here.*
Wordpress itself has a live page link at the top when building a page.

**Comment by Spellhammer** [comment]
I'm not sure I understand.

My normal process is to click Back To WP at the top right of the builder, then right click > open in new tab on the Frontend option. Is this not what you're after?

**Comment by quadcom** [comment]
Clicking back to WP backs you out of the builder UI. I'd like to just pop open a live window and be able to refresh as I build.

**Comment by wplit** [comment]
If you're on mac, Cmd ⌘ Shift ⇧ Click when you click on one of the Back to WP options will do what you want. If you're on Windows.. i don't know, but there is likely an equivalent.

**Comment by wplit** [comment]
assuming you're building in chrome that is.

**Comment by quadcom** [comment]
> If you're on mac, Cmd ⌘ Shift ⇧ Click when you click on one of the Back to WP options will do what you want. If you're on Windows.. i don't know, but there is likely an equivalent.

That did it.

Thx

**Comment by peterpinkster** [comment]
Realtime preview.  
For a second monitor? 😁

**Comment by ukuwi** [comment]
This exists with Editor Enhancer for Oxygen, which is a free plugin. Check it out: https://wordpress.org/plugins/editor-enhancer-for-oxygen/
