### ISSUE TITLE
PLUGIN OXYNINJA NOT WORKING PROPERLY

### ISSUE THREAD

**Issue by inesdev** [soflyy/oxygen-bugs-and-features#2323]
Hi,

We had a few issues regarding updating OxyNinja plugin the other day. 
What actually happened while updating, our website administration stopped working, while front end worked just fine. We solved a problem by changing the name of OxyNinja plugin folder in CPanel. If we try to rename as it was, the error occurs again. I also tried to test if there are any conflicts between plugins, by activating one by one and haven't found any problems. There is also a DEMO website on which we also updated OxyNinja and it workd fine.

What are your thoughts? Could you please help?

PHP: version 7.4
WP: version 5.7.2
OXYGEN: version  3.8.1

Kind regards,

**Comment by KittenCodes** [comment]
@inesdev Please reach out to the OxyNinja team if you are having problems with their plugin.
