### ISSUE TITLE
Gutenberg Integration is buggy (WSOD)

### ISSUE THREAD

**Issue by dplgngr** [soflyy/oxygen-bugs-and-features#2325]
**Any bug report that doesn't include a Sandbox link or replication steps will be closed. If you can't provide these pieces of information, we're happy to help you via our official support channel instead: https://oxygenbuilder.com/support. You need to select "Something's broken and I need help" from the dropdown box on the left.**

**Describe the bug**
*A clear and concise description of what the bug is.*

**A link to a Sandbox site where the bug has been reproduced https://oxygenbuilder.com/try? (REQUIRED)**
*Provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*
**Sandbox link:** https://oxygen-qmdjrbaspwwgl.oxygen-demo.qsandbox.me/
**WSOD when editing the frontpage:** https://oxygen-qmdjrbaspwwgl.oxygen-demo.qsandbox.me/wp-admin/post.php?post=20&action=edit&refreshed=1
**Errors on the edit page:** https://i.imgur.com/46QKCdX.png

Steps to reproduce:
1. Install fresh oxygen site
2. Choose "Conference" as the design set.
3. Set **Frontpage** as the homepage.
4. Edit the Frontpage and check "Make this full page editable in Gutenberg".
5. Click Update button and voila, WSOD.

**IF YOU CAN'T PROVIDE A SANDBOX REPRODUCTION: Steps required to reproduce the bug:**

**If you can't fill out the above information, you should not be filing a bug report. Instead, contact us via https://oxygenbuilder.com/support with the details you have and we'll investigate your issue further.**

**Comment by srikat** [comment]
Tested and can confirm.

**Comment by KittenCodes** [comment]
@dplgngr @srikat It's caused by the Code Block element in the Hero Section on the Front Page. You can either move the smooth scrolling code to a Code Block in the Main template, or use Oxygen's smooth scrolling and add the scroll offset in the Global settings.
