### ISSUE TITLE
Conditions in WordPress 5.8

### ISSUE THREAD

**Issue by VinceBalk** [soflyy/oxygen-bugs-and-features#2329]
**Any bug report that doesn't include a Sandbox link or replication steps will be closed. If you can't provide these pieces of information, we're happy to help you via our official support channel instead: https://oxygenbuilder.com/support. You need to select "Something's broken and I need help" from the dropdown box on the left.**

**Describe the bug**

Conditions not ok on WP 5.8 - missing clear button and the settings are not working/different then using WP 5.7.2

Since Sandbox is on WP 5.7.2, I can not reproduce my issue... sorry for that

![set conditions](https://user-images.githubusercontent.com/4202059/128060927-3df2d290-4213-471e-8ce9-4fe553f535e9.png)
Since I updated some sites to 5.8, there is something wrong with the conditions modal and its settings. On one site running 5.7.2 all is ok, on multiple sites testing with 5.8 for new installs and exsisting sites, (local, cloudways, A2 hosting) I miss the clear button and the settings are not like it used to be.

**IF YOU CAN'T PROVIDE A SANDBOX REPRODUCTION: Steps required to reproduce the bug:**
1. Go to any template
2. Click on a section, div or header builder
3. Click on the set conditions icon
3a. Missing the clear button
3b. Next screen to set conditions is missing text (only shows Conditions, used to be Show element if ALL ...
3c. Condition with dynamic data is wrong, not working

![wp572-wp58](https://user-images.githubusercontent.com/4202059/128051667-e98669f7-0eaf-4ddd-b3c1-7c23ed02d83d.png)

**Comment by KittenCodes** [comment]
@VinceBalk 

"e've never had a "Clear" button and the Conditions have not been full width either. You can see this in our Conditions tutorial video here: https://www.youtube.com/watch?v=VYnu4dfkyhw.
​
​I would guess that you've had an Oxygen add-on that added these features for you, and maybe that add-on doesn't work in the latest version of WordPress.
