### ISSUE TITLE
on a Template add  +Shortcodes does not work

### ISSUE THREAD

**Issue by chrizoo** [soflyy/oxygen-bugs-and-features#2335]
I wanted to copy a shortcode Template to another site - the field is always empty.

Tested in a Sandbox environment with latest Safari and Chrome browser too.

**IF YOU CAN'T PROVIDE A SANDBOX REPRODUCTION: Steps required to reproduce the bug:**
1) Add New Template
2) Name it and copy the shortcode in the shortcode window
3) Save

But the shortcode Field is empty ...

**Comment by KittenCodes** [comment]
@chrizoo Please open a support ticket if you need our help: https://oxygenbuilder.com/support.

Bug reports are for reproducible bugs only.

**Comment by chrizoo** [comment]
Okay I open a Ticket - but like I said I have the same issue in sandbox too so I thought it is reproducible ...
