### ISSUE TITLE
Fatal error oxygen/component-framework/components/component.class.php on line 3843

### ISSUE THREAD

**Issue by payche011** [soflyy/oxygen-bugs-and-features#2336]
***
- The website works normally, however when I want to add a new page or post I get a fatal error. Some solution was temporary by making a duplicate page and making a new page or making a change. But it’s not a solution for posts, since I don’t have any posts on the page I want to add a new one but I can’t.
- With wp debug, I don't get any error on the page, except this one

`Fatal error: Uncaught Error: Call to a member function global_conditions_result() on null in /home/brain/webapps/brain/wp-content/plugins/oxygen/component-framework/components/component.class.php:3843 Stack trace: #0 /home/brain/webapps/brain/wp-content/plugins/oxygen/component-framework/components/classes/image.class.php(31): CT_Component->validate_shortcode() #1 /home/brain/webapps/brain/wp-includes/shortcodes.php(356): CT_Image->add_shortcode() #2 [internal function]: do_shortcode_tag() #3 /home/brain/webapps/brain/wp-includes/shortcodes.php(228): preg_replace_callback() #4 /home/brain/webapps/brain/wp-content/plugins/oxygen/component-framework/components/classes/slide.class.php(61): do_shortcode() #5 /home/brain/webapps/brain/wp-includes/shortcodes.php(356): CT_Slide->add_shortcode() #6 [internal function]: do_shortcode_tag() #7 /home/brain/webapps/brain/wp-includes/shortcodes.php(228): preg_replace_callback() #8 /home/brain/webapps/brain/wp-content/plugins/oxygen/component-framework/components/classes/slider.class.ph in /home/brain/webapps/brain/wp-content/plugins/oxygen/component-framework/components/component.class.php on line 3843`

- The site was recently migrated, all procedures were done as on your site. Several sites have already been migrated in the same way, but this is the first so far to rule out this bug

1.Add new page or new post
2.When I try to add a new page or post I get a fatal error pointing to this line of code
3. https://ibb.co/sj0RB1g ( link of img )

**Comment by KittenCodes** [comment]
@payche011 Please update to the latest version of Oxygen (v3.8.1) where this issue is fixed.

If you continue to have problems, please open a support ticket so that we can take a look at your site: https://oxygenbuilder.com/support.
