### ISSUE TITLE
Allow to change images on gallery gutenberg block

### ISSUE THREAD

**Issue by jantivola** [soflyy/oxygen-bugs-and-features#2338]
**Describe the feature you'd like to see included in Oxygen.**
*A clear, detailed description of the feature you're requesting.*

The current gutenberg integration is awesome! I tried creating a gutenberg block that uses the Gallery feature of Oxygen. However, I tried replacing the images on the page that has the block. Sadly, the only option is to edit the block on Oxygen. Which would be quite confusing for non-techy people (i.e. Client)

If you could add an option to replace the images on the Gallery when made into a Gutenberg block, that would be really great! :)

**What are the use cases for this feature?**
*e.g. Accessibility, e-commerce store that sells bicycles, etc.*
Accessibility

**Comment by KittenCodes** [comment]
Duplicate: https://github.com/soflyy/oxygen-bugs-and-features/issues/2280
