### ISSUE TITLE
LATIN EXTENDED Google font issue

### ISSUE THREAD

**Issue by Stefan933** [soflyy/oxygen-bugs-and-features#2340]
**Any bug report that doesn't include a Sandbox link or replication steps will be closed. If you can't provide these pieces of information, we're happy to help you via our official support channel instead: https://oxygenbuilder.com/support. You need to select "Something's broken and I need help" from the dropdown box on the left.**

-I edited the Main template and i have added some text(Test Stefan Živković) in header. I choosed Comic Nue for font family 
-Latin extended font don't show as expected, it should look like this https://fonts.google.com/specimen/Comic+Neue?query=comic&preview.text=Stefan%20%C5%BDivkovi%C4%87&preview.text_type=custom

A link to a Sandbox site where the bug has been reproduced https://oxygen-qzcn7t3ghb5gl.oxygen-demo.qsandbox.me/ 

Steps required to reproduce the bug:
1. Go to 'template,post,page'
2. Enter some text '....'
3. Choose Comic Nue(or some other font with latin extended)
4. latin characters don't show as expected 
![oxy font](https://user-images.githubusercontent.com/48459610/129210015-fc5497d2-b5e5-427e-a96c-fbef99ef92c9.png)

**Comment by KittenCodes** [comment]
@Stefan933 This doesn't seem to be an Oxygen-specific issue - I was able to replicate it on a clean Sandbox site using a WordPress theme: http://agreeable-lion.w5.wpsandbox.pro/.

It may be worth reaching out to the Google Fonts team to let them know this is occurring.
