### ISSUE TITLE
Nested template not executing PHP/Dynamic Data from Main template

### ISSUE THREAD

**Issue by janisii** [soflyy/oxygen-bugs-and-features#2341]
Hi,

I have issues with nested templates and PHP not executed.  Any PHP code added to main template with Dynamic Data to text element is not executed when nested templates used (2nd level deep). Is there any work-around for this, because I use nested templates for a complex website?

PHP code not executed only in frontend, no issues in OXY builder (backend).

Screencast:
[https://youtu.be/SdDmsSF0bEE](https://youtu.be/SdDmsSF0bEE)

Sandbox link:
[http://amused-flatworm.w6.wpsandbox.pro?upass=D82me11YJRvs](http://amused-flatworm.w6.wpsandbox.pro?upass=D82me11YJRvs)

Thanks.

**Comment by bohdanps** [comment]
Hey! It's already beed reported a while ago: https://github.com/soflyy/oxygen-bugs-and-features/issues/1881#issue-797399947

Waiting for some solutions :)

**Comment by KittenCodes** [comment]
Duplicate. Closing.
