### ISSUE TITLE
Enter the license key. After activating the plug-in, you can view the license key with the developer tool of the browser

### ISSUE THREAD

**Issue by sunnyliumr** [soflyy/oxygen-bugs-and-features#2344]
After entering the license key and activating the plug-in, you can view the license key with the developer tool of the browser, which is an obvious vulnerability, which is easy to disclose the license key.

Divi and Astra Pro are hidden. Can you provide corresponding solutions to this problem?

**Comment by KittenCodes** [comment]
Duplicate: https://github.com/soflyy/oxygen-bugs-and-features/issues/1768
