### ISSUE TITLE
Background-color from Main template isn't used in archive template

### ISSUE THREAD

**Issue by gernotron** [soflyy/oxygen-bugs-and-features#2349]
**Describe the bug**
The background-color from the Main (catch-all) template isn't used in the Front-Page or archive templates.
In the given sandbox example, the background-color of the inner content in the Main template is set to red. It is visible when editing the Front-Page/archive templates, but it is not actually displayed on the front-end (when visiting the site).

**A link to a Sandbox site where the bug has been reproduced https://oxygenbuilder.com/try? (REQUIRED)**
https://oxygen-q32pzmz2a32c.oxygen-demo.qsandbox.me/
https://oxygen-q32pzmz2a32c.oxygen-demo.qsandbox.me/category/uncategorized/

Template editor, where inherited background-color is visible:
https://oxygen-q32pzmz2a32c.oxygen-demo.qsandbox.me/?ct_template=archive&ct_builder=true&ct_inner=true

**Comment by KittenCodes** [comment]
@gernotron The Inner Content element isn't always output on the front-end of the site. The best workaround for this is to wrap the Inner Content element in a Div and then set the background colour on the Div instead.

**Comment by KittenCodes** [comment]
Duplicate: https://github.com/soflyy/oxygen-bugs-and-features/issues/1930
