### ISSUE TITLE
ACF URL Issue

### ISSUE THREAD

**Issue by barleedar** [soflyy/oxygen-bugs-and-features#2357]
Let me explain, I have created a Custom Post type, it will have a title and a web URL field (THis field was tested as TEXT and URL just for your info)

When I add the link to text in Repeater it does not work on the front end if the URL does not contain a www. I had added almost 300 URL's that did not have the www and the front end only showed a blank URK, but as soon as I updated one to have the www (http://www.pathwaysbc.ca/ci/2854) it then worked, I can update all via ALl Import, so no time wasted, juts thought you need to know.
![235639609_10226680387498963_294058250568708262_n](https://user-images.githubusercontent.com/47887720/130196761-2b84f55d-67e5-47e7-8c54-45c77c2f041f.jpg)
![239345799_10226680434860147_673450514735230431_n](https://user-images.githubusercontent.com/47887720/130196772-b9ca6816-b732-40e6-bdbd-1eff495a0704.jpg)

**Comment by KittenCodes** [comment]
@barleedar If the URL isn't working without www, then that's not likely an Oxygen issue.
