### ISSUE TITLE
Bug when trying to Edit with Oxygen {{iframeScope.getGlobalColorSet(colorSetIDToAdd).name}}

### ISSUE THREAD

**Issue by Crixus92** [soflyy/oxygen-bugs-and-features#2359]
I was going to change something with my page today and clicked on "Edit with Oxygen". Instead, it displayed a box with the option to enter "New Color". Under it, it says "{{iframeScope.getGlobalColorSet(colorSetIDToAdd).name}}". No matter what I write in the "New Color" field, I cant click past the box. 

1. Go to any page or post on WordPress
2. Click on Edit with Oxygen
3. See the error as I described above. 

![Bug](https://user-images.githubusercontent.com/60885607/130350665-df399f36-9eb5-46c3-aab7-0c00b1906c02.JPG)

**Comment by KittenCodes** [comment]
@Crixus92 This is most likely caused by the SiteGround Optimizer plugin. Please try disabling it.

**Comment by Crixus92** [comment]
@KittenCodes Thank you so much, it worked.

**Comment by Kavouras** [comment]
same here
