### ISSUE TITLE
Unicode names not supported in Structure titles of blocks

### ISSUE THREAD

**Issue by jevgen** [soflyy/oxygen-bugs-and-features#2363]
**Describe the bug**
When entered in non-English language, names of Blocks in Structure pane disappear after saving. Double click for rename returns empty name. 

**Steps required to reproduce the bug:**
1. Go to Struciture Pane.
2. Create Section
3. Rename section in Russian, e.g. Секция, or in Hindi, e.g. का इस्तेमाल
4. Press "Enter"
5. See what you just entered to disappear.

**Comment by KittenCodes** [comment]
Fixed in v3.9 Beta 1.
