### ISSUE TITLE
Woocommerce and Book Previewer for Woocommerce

### ISSUE THREAD

**Issue by foaad1961** [soflyy/oxygen-bugs-and-features#2364]
I have installed the latest Oxygen builder as well as Woocommerce plugins. I have added the plugin "Book Previewer for Woocommerce" as well. The product page stopped showing the images of the book (front and Back). I have created a gallery to have extra images shown, and when I click on the "look inside" button, it opens up a lightbox that displays only the images I have added to the gallery and still not the front or the back images.
Due to the nature of being a publisher plus many services offerings on my site, there are many plugins I have used. However, I decided to create the bug in the sandbox: 
http://smoggy-ratel.w5.wpsandbox.pro/product/hoodie-with-logo-2/
I assume it is a Jave script error that can be resolved with the addition of one or two lines or updating the Jquery. However, it might be deeper than I think, which you should be able to determine.
Regards,
Foaad

**Comment by KittenCodes** [comment]
@foaad1961 I disabled Oxygen on the Sandbox site and the behaviour was the same so this doesn't seem to be caused by Oxygen. I'd suggest reaching out to the plugin developer for advice.
