### ISSUE TITLE
Product Cart button not working

### ISSUE THREAD

**Issue by jianryu** [soflyy/oxygen-bugs-and-features#2367]
**Any bug report that doesn't include a Sandbox link or replication steps will be closed. If you can't provide these pieces of information, we're happy to help you via our official support channel instead: https://oxygenbuilder.com/support. You need to select "Something's broken and I need help" from the dropdown box on the left.**

**Describe the bug**

Product builder works fine while each of the element (e.g. Product Cart Button, Checkout) doesn't work properly. 

**A link to a Sandbox site where the bug has been reproduced https://oxygenbuilder.com/try? (REQUIRED)**
*Provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*

https://oxygen-q686npsjk3ahl.oxygen-demo.qsandbox.me/product/product/

**IF YOU CAN'T PROVIDE A SANDBOX REPRODUCTION: Steps required to reproduce the bug:**
1. Go to https://oxygen-q686npsjk3ahl.oxygen-demo.qsandbox.me/product/product/

2. Click on 'Add to cart' button

3. See error: It doesn't redirect to the checkout page.

**If you can't fill out the above information, you should not be filing a bug report. Instead, contact us via https://oxygenbuilder.com/support with the details you have and we'll investigate your issue further.**

**Comment by KittenCodes** [comment]
@jianryu 

You must place your design inside the Product Builder. I've done this for you on the Sandbox site. If you click "Add to Cart" then the product is added to the cart.

You're not automatically redirected to the checkout page as that's not how Oxygen's Add to Cart button works.
