### ISSUE TITLE
DONE: add in code editor support autocomplete (attach screen record) 

### ISSUE THREAD

**Issue by promocot** [soflyy/oxygen-bugs-and-features#2370]
Hello please add autocomplete code in the editor, sometimes I need to write a big part of code and if will exist autocomplete, this ability make my work faster and exclude mistake in code

![CodeHit](https://user-images.githubusercontent.com/66754335/131115673-9870d6ee-ec20-4eef-8acd-c3e5a1f9294d.gif)

**Comment by Spellhammer** [comment]
Implemented in 4.7.
