### ISSUE TITLE
Smooth Scrolling Back To Top

### ISSUE THREAD

**Issue by Mike-71** [soflyy/oxygen-bugs-and-features#2373]
Smooth scrolling does not work with the "Back To Top" button. "Smooth Scrolling Hash to Links" is activated in the Page Settings> Scripts.

THX Mike

**Comment by vrMarc** [comment]
Hi @Mike-71 did you add the id Top to an element on the page?

**Comment by Mike-71** [comment]
After I assigned the ID #header to the header and the link, it works now. I haven't tested either of these with #top.

**Comment by vrMarc** [comment]
As long as the ID referenced in the link matches the ID assigned to an existing element it will work. Glad you got it to work!

**Comment by Mike-71** [comment]
Unfortunately, the back to top button doesn't work again.  The link points to #header and the ID of the header is header.

**Comment by vrMarc** [comment]
Can you share a link to the page?

**Comment by Mike-71** [comment]
Sure,  https://koerperheilpraxis.de/Freundliche Grüße Michael Amend Hauptstr. 2935435 Wettenberg Fon: 0 641 - 984 579 7Fax: 0 641 - 984 579 8Mail: ***@***.***: https://mediensachen.de
-------- Ursprüngliche Nachricht --------Von: Marc Robinson ***@***.***> Datum: 16.09.21  17:21  (GMT+01:00) An: soflyy/oxygen-bugs-and-features ***@***.***> Cc: Mike-71 ***@***.***>, Mention ***@***.***> Betreff: Re: [soflyy/oxygen-bugs-and-features] Smooth Scrolling Back To Top (#2373) 
Can you share a link to the page?

**Comment by vrMarc** [comment]
That link didn't work for me so I looked at  https://koerperheilpraxis.de. Since your header is given a fixed position once a visitor scrolls down the page, it's no longer positioned before your inner content. The page doesn't scroll when you click the button because the scroll-to-target is already in the viewport. Try using a different element besides the <header> as the target.

**Comment by Mike-71** [comment]
Logical, I overlooked that.  Thank you very much!Freundliche Grüße Michael Amend Hauptstr. 2935435 Wettenberg Fon: 0 641 - 984 579 7Fax: 0 641 - 984 579 8Mail: ***@***.***: https://mediensachen.de
-------- Ursprüngliche Nachricht --------Von: Marc Robinson ***@***.***> Datum: 16.09.21  18:03  (GMT+01:00) An: soflyy/oxygen-bugs-and-features ***@***.***> Cc: Mike-71 ***@***.***>, Mention ***@***.***> Betreff: Re: [soflyy/oxygen-bugs-and-features] Smooth Scrolling Back To Top (#2373) 
That link didn't work for me so I looked at  https://koerperheilpraxis.de. Since your header is given a fixed position once a visitor scrolls down the page, it's no longer positioned before your inner content. The page doesn't scroll when you click the button because the scroll-to-target is already in the viewport. Try using a different element besides the  as the target.

**Comment by Mike-71** [comment]
In fact, inserting the back top button is difficult and it did not work on the onepage page. Now I use the Back to Top Button from OxyExtras and it works perfectly without any programming adjustments. Just for information.

Greetings Mike
Am 16. Sept. 2021, 19:24 +0200 schrieb Michael Amend | mediensachen ***@***.***>:
