### ISSUE TITLE
universall.css for Ben'N'Breakfast constains errors in the BODY selector

### ISSUE THREAD

**Issue by dariobros** [soflyy/oxygen-bugs-and-features#2374]
**Describe the bug**
*A clear and concise description of what the bug is.*

https://pasteboard.co/KizJX2Z.png
lacking values for the following:

body {
    line-height: ;
    font-size: px;
    font-weight: ;
    color: ;

**A link to a Sandbox site where the bug has been reproduced https://oxygenbuilder.com/try? (REQUIRED)**

https://oxygen-qvdzgxhpb3dhl.oxygen-demo.qsandbox.me/home/

**Comment by KittenCodes** [comment]
Thank you. This has been resolved.
