### ISSUE TITLE
All website content lost after pushing website to production

### ISSUE THREAD

**Issue by myelyu2** [soflyy/oxygen-bugs-and-features#2376]
Hello,

I when I pushed my website to production the content on the pages was lost. There is no menu and a lot of other things were lost. All I did was 
1. DNS configurations
2. Copied environment and pushed it to the new domain
Support from GoDaddy and WRengine said that the website should be working fine, so I guess the problem might be in Oxygen.
Here are the screenshots of how the website should look and how it actually looks after pushing
<img width="1374" alt="Screen Shot 2021-09-01 at 09 48 45" src="https://user-images.githubusercontent.com/89800281/131694042-b2c9de7d-de59-46d2-bc1a-af9f8d37747e.png">
<img width="1380" alt="Screen Shot 2021-09-01 at 09 48 52" src="https://user-images.githubusercontent.com/89800281/131694051-de705bf0-e21a-4d0a-9b22-8dff9e2a518c.png">

**Comment by Spellhammer** [comment]
You should follow the instructions at https://oxygenbuilder.com/documentation/other/importing-exporting/.

If following those instructions doesn't resolve the problem, please submit a support ticket at https://oxygenbuilder.com/support.
