### ISSUE TITLE
Modal hide options

### ISSUE THREAD

**Issue by estraatios** [soflyy/oxygen-bugs-and-features#238]
**Describe the feature you'd like to see included in Oxygen.**
*A clear, detailed description of the feature you're requesting.*

**What are the use cases for this feature?**
*e.g. Accessibility, e-commerce store that sells bicycles, etc.*

**Examples of this feature or functionality.**
*If another product has done it well, provide examples here.*

**Comment by estraatios** [comment]
Hi 

Can you add in the modal a hide option? If I create a modal for mail opt-in form, which is displayed automatically and the visitor closes it I would not like it to display the modal if he revisits the page. So I could hide it for some days. 

Also, Could a modal be displayed on the entire website and not only a page?

**Comment by KittenCodes** [comment]
> I would not like it to display the modal if he revisits the page. So I could hide it for some days.

This is possible in the Trigger tab of the Modal. You need to select something in the dropdown for "After Modal Is Shown".

> Also, Could a modal be displayed on the entire website and not only a page?

Please add the Modal to your Main template.

**Comment by estraatios** [comment]
Hide after it is shown is not what I want.

I want to select the days it will be hidden until it reappears again. 

This is common when creating a subscribe and want to hide it for a week so it will no bother all the time the visitor

**Comment by KittenCodes** [comment]
@estraatios You need to select "Show again after" from the dropdown box under "After Modal Is Shown" and then set the number of days.
