### ISSUE TITLE
Color the text in the 'text' pane of the Rich Text element to be seen

### ISSUE THREAD

**Issue by zuroma999** [soflyy/oxygen-bugs-and-features#2380]
When editing the text of a rich text element, and switching to the "text" pane, the text is displayed as light-grey on a white background, which is impossible to see (see image). Displaying the text with a darker color would help.

<img width="451" alt="Screen Shot 2021-09-02 at 10 12 57 AM" src="https://user-images.githubusercontent.com/49953523/131888406-c75f42f0-3b71-469a-96ec-7e9028e8ad1d.png">

**Comment by KittenCodes** [comment]
@zuroma999 This is caused by something on your site. If you'd like help determining exactly what is doing it, please open a support ticket: https://oxygenbuilder.com/support.

**Comment by zuroma999** [comment]
Thanks. Looking at the computed classes for the element, it's coming from bootstrap.css which is coming from the Toolset series of plugins. I'm surprised Oxygen doesn't account for it. In any case, we added css to target .wp-editor-area and it's ok now.
