### ISSUE TITLE
Oxygen 3.9 Alpha 1 – Wrap with <div> completely removes element

### ISSUE THREAD

**Issue by andreslotta** [soflyy/oxygen-bugs-and-features#2384]
**Describe the bug**
When I try to wrap an element (e.g. a heading or a text element) in a div the element gets removed completely (from the canvas as well as the structure pane).

**A link to a Sandbox site where the bug has been reproduced https://oxygenbuilder.com/try? (REQUIRED)**
See "Steps required to reproduce the bug"

**Steps required to reproduce the bug:**
1. Create a new page
2. Add a text (or other) element
3. In the structure pane click on the new element's pencil icon and choose `Wrap with <div>`

**Expected behaviour:**
The element gets wrapped in a new div block.

**Actual behaviour:**
The element gets removed / disappears.

**Screencast showing the issue:**
https://www.loom.com/share/5226c53cc19d47e7b30292315ab7fba7

**Comment by avocadesign** [comment]
I can confirm this behaviour too in a test install

**Comment by andreslotta** [comment]
**Update:**
The same goes for converting an element to / wrapping an element in a link.

**Steps required to reproduce the bug:**
1. Add an icon element
2. Select the icon element and click on the `Link Settings` icon in the top left to wrap the icon in a link wrapper
3. See error

**Expected behaviour:**
The icon gets wrapped in a new link wrapper element.

**Actual behaviour:**
The icon gets removed / disappears.

**Comment by localsbm** [comment]
I confirm that I am also experiencing this issue with 3.9.1

**Comment by bretcarmichael** [comment]
Same. Confirmed. This issue also happens when you add a <div> to a page and drag anything inside that <div>.
