### ISSUE TITLE
Oxygen 3.9.1 Alpha - Meta Box Integration - Phone Number Field Missing From URL data

### ISSUE THREAD

**Issue by localsbm** [soflyy/oxygen-bugs-and-features#2386]
**Describe the bug**
The Meta Box Phone Number field is not selectable in a URL data field. It shows properly when selecting via "insert data" in a text field.

**Steps required to reproduce the bug:**
1. Add custom field type "Phone number" to a post
2. On post add a phone number to the field
3. In the builder, add a text link to the page. Double click, click insert data, then click Meta Box, then click the phone number. 
4. Still within the builder, navigate to add the URL, click "data", then click Meta Box, the phone number field is not shown.

I have used the Meta Box Email field and everything works properly, I was expecting the phone number field to work the same.

**Loom Recording Link:**
https://www.loom.com/share/357ad3e3a8bc45c3bbf38f09caafa044

**Workaround**
My initial workaround is double-clicking the text field, copying the dynamic data shortcode, then pasting it into the URL field. Because it is a phone number I did pre-pend with tel:

**Comment by KittenCodes** [comment]
Fixed in v3.9 Beta 1.
