### ISSUE TITLE
Oxygen 3.9 alpha - movement of the structure window after clicking on the element

### ISSUE THREAD

**Issue by zbyneksmetana** [soflyy/oxygen-bugs-and-features#2389]
1. Expand in the structure panel all elements (click Expand All) (there must be a very large number of elements to occupy a larger area than the browser window)
2. Click on an element in the structure panel 
3. Elements moving up to the top of the page after clicking  (i say about structure window not about movement of the main window with page)
**Look at the movie** [https://youtu.be/LlSakxMkiFk?t=30](https://youtu.be/LlSakxMkiFk?t=30)
**This behaviour dont exist in 3.8 version. Its annoying.** (In short: You click something and suddenly something escapes from your mouse)
I have not seen this behavior in any of the other builders  so I'm guessing it's a bug

**Comment by KittenCodes** [comment]
Fixed in v3.9 Beta 1.
