### ISSUE TITLE
Backround Images with paralax efect on SAFARI browsers

### ISSUE THREAD

**Issue by xxpeggy** [soflyy/oxygen-bugs-and-features#2390]
Hi there,
There is one bug on my Oxygen website, which I cant fix.
My web:
https://matejhorak.cz/

In 3-rd section (with icons) and 5-th section (Dotaznik....) - there are some images on background with the paralax efect.

On Windows and Android it shows perfect. But, on Safari browsers are images "broken" - very badly showed.

I have tried to find some solution on forums, but without success. All people says, that is an bug on the property background-image on Safari browsers.

Please, can you advice me how to fix these bug?

Thanks a lot
Michal

**Comment by KittenCodes** [comment]
@xxpeggy 

Unfortunately, iOS devices don't support "background-attachment: fixed". You would need to set it to scroll on whatever breakpoint is used by those devices.
