### ISSUE TITLE
Oxygen 3.9 Alpha. Reusable error

### ISSUE THREAD

**Issue by Brandinwebdesign** [soflyy/oxygen-bugs-and-features#2395]
In Oxygen 3.9 Alpha i will use a Reusable item. 
But if i want to use him single or editable i get this error:

Error occurred while loading post: 28808

**Comment by KittenCodes** [comment]
@Brandinwebdesign Are you able to replicate this on our Sandbox site? I've tried, but I can't cause the error.

You can create a Sandbox site here: https://oxygenbuilder.com/try.

**Comment by Brandinwebdesign** [comment]
@KittenCodes  Mabey im to fast. i try it again and works know.. i'm sorry
