### ISSUE TITLE
Switcher is broken - won't switch

### ISSUE THREAD

**Issue by scottocs11** [soflyy/oxygen-bugs-and-features#2397]
The switcher is not available in the sandbox site, and the only steps to reproduce the issue are to add a switcher to a blank or per-built site. The switcher doesn't switch. Tried on 3.8 and 3.9a1.

**Comment by Spellhammer** [comment]
I've verified that it's working as expected on a fresh Sandbox install.

Please send us a support ticket with more details: https://oxygenbuilder.com/support.
