### ISSUE TITLE
Oxygen 3.9 Alpa. Link to image broken

### ISSUE THREAD

**Issue by Brandinwebdesign** [soflyy/oxygen-bugs-and-features#2403]
If you add an image first and then add a link wrapper, the image disappears.
The image also disappears from the structure panel

If you add a link wrapper first and then the image it will work.

**Comment by KittenCodes** [comment]
@Brandinwebdesign Would you mind recording a quick video showing what you're doing please as I've not been able to replicate this.

Thanks!

**Comment by Brandinwebdesign** [comment]
@KittenCodes  [https://files.fm/f/kp4yctt9s](url) here the video. Clean install on the sandbox

**Comment by KittenCodes** [comment]
@Brandinwebdesign Thanks!

**Comment by KittenCodes** [comment]
This has been fixed in 3.9 Beta.
