### ISSUE TITLE
Error messages showing: 'Undefined variable show_gradient'

### ISSUE THREAD

**Issue by FaridLouali** [soflyy/oxygen-bugs-and-features#2406]
Hi,
I set 'define( 'WP_DEBUG', true );' for this project.
When working with Oxygen:
1- An error shows in the left panel (error_sidebar.jpg)
![error_sidebar](https://user-images.githubusercontent.com/81163407/132949010-ab13524c-f588-445b-816c-afae9de84ab5.jpg)

2- After saving > Back to WP >Admin, an error page shows for few seconds.
![error_After_Back-to-wp_Admin](https://user-images.githubusercontent.com/81163407/132948928-e3c657d1-386b-4ec3-9d4a-66e229539201.jpg)

Hope this will help. Have a good day.

Farid Louali

**Comment by Spellhammer** [comment]
Are you using PHP 8.x?

**Comment by wpsumo** [comment]
@Spellhammer No this issue "'Undefined variable show_gradient'" was reported months ago, issue shows with php 7.4.2
https://github.com/soflyy/oxygen-bugs-and-features/issues/1719

**Comment by FaridLouali** [comment]
PHP 7.3.21

**Comment by adrien-robert** [comment]
> show_gradient

Did you found a solution for the "Undefined variable show_gradient"?

**Comment by wpsumo** [comment]
I think its sorted in 4.0 if I'm correct @KittenCodes

**Comment by KittenCodes** [comment]
Correct, yes. This is fixed in v4.
