### ISSUE TITLE
3.9 Alpha 1 - Meta Box Setting Page - Image fields are not usable

### ISSUE THREAD

**Issue by localsbm** [soflyy/oxygen-bugs-and-features#2409]
**Describe the bug**
When an image field (any image field type) is set inside a Meta Box settings page it does now show when pulled into the builder. The option to use it is shown in the builder, but it pulls in as blank.

**IF YOU CAN'T PROVIDE A SANDBOX REPRODUCTION: Steps required to reproduce the bug:**
1. Create a Meta Box settings page
2. Create an image field (any image field, preferable are single image and image advanced) and add it to the settings page.
3. In the setting page, add an image, then save.
4. In the builder, add an image component.
5. Select data, then Meta Box, then image field, then select a size.
6. Builder and front end both show the field as blank.

**Comment by KittenCodes** [comment]
Fixed in v3.9 Beta 1.
