### ISSUE TITLE
Attributes added to the "inner content" block don't appear on the front end of the website.

### ISSUE THREAD

**Issue by ChayKelly** [soflyy/oxygen-bugs-and-features#2410]
**Any bug report that doesn't include a Sandbox link or replication steps will be closed. If you can't provide these pieces of information, we're happy to help you via our official support channel instead: https://oxygenbuilder.com/support. You need to select "Something's broken and I need help" from the dropdown box on the left.**

**Describe the bug**
Attributes added to the "inner content" block don't appear on the front end of the website.

**A link to a Sandbox site where the bug has been reproduced https://oxygenbuilder.com/try? (REQUIRED)**
https://oxygen-qwstb9ccvblhl.oxygen-demo.qsandbox.me/ - I've created a single template and added the attributes to the inner content block.

**Comment by KittenCodes** [comment]
@ChayKelly Please wrap the Inner Content element in a Div and apply the Attributes to the Div.
