### ISSUE TITLE
Oxygen Builder not allowing to load any custom template with custom post.

### ISSUE THREAD

**Issue by shamimcse05** [soflyy/oxygen-bugs-and-features#2412]
Hello Team,
Thank you for making awesome builder. but we noticed a serious bug, by default oxygen builder not allowing to load any custom template. we are using this plugin: https://wordpress.org/plugins/mage-eventpress/
this is based on custom post type and they have own template for custom post. but unfortunately we could not keep off oxygen builder with this custom post and oxygen builder forcely loading. we tried to find solution but still no luck. 
Is there any way to keep oxygen builder template loading off for certain post type.

thanks

**Comment by KittenCodes** [comment]
@shamimcse05 You can disable Oxygen selectively using the Deactivate Plugins plugin: https://wordpress.org/plugins/freesoul-deactivate-plugins/.
