### ISSUE TITLE
ACF group subfield insert-data causes Issues

### ISSUE THREAD

**Issue by stitchinger** [soflyy/oxygen-bugs-and-features#2417]
**Describe the bug**
Using insert-data to retrieve data from a ACF group subfield breaks data-retrieval code which comes after it. (Frontend only. Data shows up in oxygen-editor)

**A link to a Sandbox site where the bug has been reproduced https://oxygenbuilder.com/try? (REQUIRED)**
Because there is no ACF installed on your sandboxes, I replicated the issue on my playground site.
https://playground.georgeous.io/model/gina/ (insert-data before code-block)
https://playground.georgeous.io/model/lisa/ (insert-data after code-block)

This is the code I'm using:
```
<?php

$all = [];

// Load default fields
if (have_rows('gruppe')) {
    while (have_rows('gruppe')){
		the_row();
		array_push($all, get_sub_field('city'));
	}
}

// Output fields
foreach ($all as $field) {
	echo $field;
}
?>
```

**Steps to reproduce the behavior:**
1. Create text-module and insert-data from an ACF group sub-field.
2. Create code-module and use the code provided by ACF docs to output some data from the same group.
3. Save and go to frontend.
4. See error (Second output will be empty)
5. Now reverse the order of code and text.
6. Both outputs will show up in the frontend now.

**Comment by KittenCodes** [comment]
@stitchinger 

Unfortunately, Oxygen doesn't yet have support for ACF Group fields - one of the issues being the behaviour you are experiencing. However, I will log this internally so that we have a note of it.
