### ISSUE TITLE
Component search should work if we enter the component name in any sequence

### ISSUE THREAD

**Issue by faizzsheikh** [soflyy/oxygen-bugs-and-features#2421]
**The Component search only finds the component if I enter search in the exact sequence of the Component name. 
For example if I have to search for "Header Builder" I have to start by typing "Header" first, if I search for just "Builder" it won't show.

This is causing annoyance because I have multiple/many reusable parts and I have named them with minimum 3-4 words but it won't show up until I type exactly in the sequence I had named them.

See below screenshots.

![oxygen-1](https://user-images.githubusercontent.com/5747159/134312757-ff0d0de8-2615-414a-89e2-03ef5d72ed9f.jpg)
![oxygen-2](https://user-images.githubusercontent.com/5747159/134312763-ad59bbbf-fda4-4378-9934-f88eb353404c.jpg)
**

**Comment by KittenCodes** [comment]
Duplicate: https://github.com/soflyy/oxygen-bugs-and-features/issues/2307
