### ISSUE TITLE
Code block containing <a> tag breaks parent link wrapper

### ISSUE THREAD

**Issue by dubfonik** [soflyy/oxygen-bugs-and-features#2422]
**Any bug report that doesn't include a Sandbox link or replication steps will be closed. If you can't provide these pieces of information, we're happy to help you via our official support channel instead: https://oxygenbuilder.com/support. You need to select "Something's broken and I need help" from the dropdown box on the left.**

**Describe the bug**
If you put a code block containing an `<a>` tag inside a link wrapper element, it will break the link wrapper. All elements after the code block will not work as a hyperlink.

**A link to a Sandbox site where the bug has been reproduced https://oxygenbuilder.com/try? (REQUIRED)**
http://defeated-chicken.w5.wpsandbox.pro/test/

**IF YOU CAN'T PROVIDE A SANDBOX REPRODUCTION: Steps required to reproduce the bug:**
NA - Sandbox provided

**If you can't fill out the above information, you should not be filing a bug report. Instead, contact us via https://oxygenbuilder.com/support with the details you have and we'll investigate your issue further.**

**Comment by dubfonik** [comment]
In the meantime, a workaround is to not have the link wrapper on the parent, but instead add a link wrapper element as a child with the following CSS:
`position: absolute;
top: 0;
left: 0;
width: 100%;
height: 100%;`

Then, set the parent div to `position: relative;`. This will bring the link wrapper over  the whole element.

You can then use the code block to have your link, however you'll need to increase the z-index on those links so that it's above the link wrapper. 

This is just a workaround, and may not work for all cases.

**Comment by KittenCodes** [comment]
This isn't a bug. Nested links are invalid HTML.
