### ISSUE TITLE
3.9 Alpha Wrap in div

### ISSUE THREAD

**Issue by wojtekpiskorz** [soflyy/oxygen-bugs-and-features#2423]
**Any bug report that doesn't include a Sandbox link or replication steps will be closed. If you can't provide these pieces of information, we're happy to help you via our official support channel instead: https://oxygenbuilder.com/support. You need to select "Something's broken and I need help" from the dropdown box on the left.**

**Describe the bug**

Wrap with DIV on element makes the element erase itself

**A link to a Sandbox site where the bug has been reproduced https://oxygenbuilder.com/try? (REQUIRED)**
*Provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*

**IF YOU CAN'T PROVIDE A SANDBOX REPRODUCTION: Steps required to reproduce the bug:**
1. Go to '...' any page and open oxygen builder
2. Click on '....' any element inside any section, press Wrap with <div>, and it's gone

**If you can't fill out the above information, you should not be filing a bug report. Instead, contact us via https://oxygenbuilder.com/support with the details you have and we'll investigate your issue further.**

**Comment by KittenCodes** [comment]
@wojtekpiskorz This will be fixed in the Beta.
