### ISSUE TITLE
Admin Bar - gets damaged after installation

### ISSUE THREAD

**Issue by krissborowy** [soflyy/oxygen-bugs-and-features#2428]
After installing wordpress and activating the Oxygen Builder plugin, the "Adminbar" on the home page loses CSS styling.

https://oxygen-qk3mck5abbshl.oxygen-demo.qsandbox.me/

**Comment by Spellhammer** [comment]
That happens because there's no Oxygen design on your site. You'll need to add some Oxygen content directly to a post or via a template.
