### ISSUE TITLE
Pro Menu is broken, and there's a syntax error (missing semicolon)

### ISSUE THREAD

**Issue by greatgraphicdesign** [soflyy/oxygen-bugs-and-features#2429]
Last week I started a new site using Oxygen v3.8.1. It's been over 18 months since I built my last Oxygen site. I had problems with Pro Menu back then so I abandoned it. Today, I'm disappointed to learn that Pro Menu is still not working, and it's actually worse than before. 

Currently, dropdown menus do not appear at all when nav items are hovered or clicked. Also, the mobile menu does not open when the open icon is clicked. Chrome Dev Tools tells me there's a syntax error. Looks like a missing semicolon. It's hard to believe that this code has been broken since it was released in June 29 and nobody has submitted a report yet.
 
<img width="515" alt="Screen Shot 2021-09-26 at 9 40 57 PM" src="https://user-images.githubusercontent.com/39844914/134851878-a59dde6c-4071-4e35-a959-3838b19d7e75.png">

**Comment by Spellhammer** [comment]
Please reproduce on a Sandbox at https://oxygenbuilder.com/try and send us the info & link via https://oxygenbuilder.com/support.
