### ISSUE TITLE
Mega menu builder

### ISSUE THREAD

**Issue by estraatios** [soflyy/oxygen-bugs-and-features#243]
Please add a mega menu builder.

It would be awesome to be able to design our own mega menu.

Thanks

**Comment by alexandrudinu** [comment]
I would love to have this in the Oxygen Builder.

**Comment by muzaffarsiddiqui** [comment]
+1

**Comment by dnawebstudio** [comment]
Definitely a must-have.

**Comment by alriksson** [comment]
+1

**Comment by thesounak** [comment]
I would definitely want to see a full-on menu/header builder including the capability to built different types of mega menu, navigation slider from all sides, hamburger menu animation, etc.

**Comment by KarzanTT** [comment]
Please Add Mega Menu/ header builder to OXYGEN

**Comment by thakurtech** [comment]
Since oxygen team is working on MENU enhancement as per 3.2 alpha release. I wish they could add mega menu feature.

**Comment by Tahor** [comment]
Please add ASAP it's 2020!!!

**Comment by alexandrudinu** [comment]
Looking forward to see this soon 👀

**Comment by Tahor** [comment]
Can anyone export a template and link us to it? Thx!

**Comment by estraatios** [comment]
Check jet menu form crocoblocks

https://crocoblock.com/plugins/jetmenu/?gclid=CjwKCAjwqJ_1BRBZEiwAv73uwHcyPRq___dpqswY0uDdshya4U0fTBtGzh36dqLbxv8715ELNOxnmRoCfO4QAvD_BwE

**Comment by Tahor** [comment]
> Check jet menu form crocoblocks https://crocoblock.com/plugins/jetmenu/?gclid=CjwKCAjwqJ_1BRBZEiwAv73uwHcyPRq___dpqswY0uDdshya4U0fTBtGzh36dqLbxv8715ELNOxnmRoCfO4QAvD_BwE

The whole point is to avoid elementor ;P. Too much bloat with it. I want a native oxygen website :)

**Comment by estraatios** [comment]
This is just for a template. Not use this

Στάλθηκε από το Ταχυδρομείο Yahoo σε Android 
 
  Στις Τρί, 28 Απρ, 2020 στις 9:55 μ.μ., ο χρήστηςTahor<notifications@github.com> έγραψε:   



Check jet menu form crocoblocks https://crocoblock.com/plugins/jetmenu/?gclid=CjwKCAjwqJ_1BRBZEiwAv73uwHcyPRq___dpqswY0uDdshya4U0fTBtGzh36dqLbxv8715ELNOxnmRoCfO4QAvD_BwE


The whole point is to avoid elementor ;P. Too much bloat with it. I want a native oxygen website :)

**Comment by webenadam** [comment]
+1

**Comment by Spellhammer** [comment]
Implemented in Composite Elements.
