### ISSUE TITLE
Safari 15.0 on macOS Catalina experiencing significant slowdowns/freezing/errors

### ISSUE THREAD

**Issue by uncouthmike** [soflyy/oxygen-bugs-and-features#2435]
**Describe the bug**
A conflict between Safari 15.0 on macOS Catalina 10.15.7 seems to be triggering strange behaviour with Oxygen. It doesn't occur when using the Firefox browser. I haven't been able to test on Big Sur.
When loading the Oxygen editor, sometimes immediately, sometimes after a minute or two, the screenshotted error will appear: "Script error. on line #0 in." Sometimes (not always) the editor will then become very unresponsive, clicks will take seconds to be responded to. Sometimes the editor will continue to function apparently normally.

https://www.dropbox.com/s/2khfwvklb1rj4ek/Screen%20Shot%202021-09-29%20at%202.05.01%20pm.png?dl=0

The difficulty is that the bug doesn't not reliably appear. When it does, it generates an error in the console in:

angular.js:8479
Error: [$rootScope:infdig] 10 $digest() iterations reached. Aborting!
Watchers fired in the last 5 iterations: [[{"msg":"globalSettings.scripts","newVal":{"scroll_to_hash":"true","scroll_to_hash_time":"200","scroll_to_hash_offset":"-40"},"oldVal":{"scroll_to_hash":"true","scroll_to_hash_time":"200","scroll_to_hash_offset":"-40"}},{"msg":"pageSettingsMeta.scripts","newVal":{"scroll_to_hash":"","scroll_to_hash_time":"","scroll_to_hash_offset":""},"oldVal":{"scroll_to_hash":"","scroll_to_hash_time":"","scroll_to_hash_offset":""}},{"msg":"globalSettings","newVal":{"fonts":{"Text":"Cambay","Display":"Titillium Web"},"indicateParents":"true","classSuggestionsLimit":"5","headings":{"H1":{"font-size-unit":"px","font-size":"36","font-weight":"600","color":"","line-height":"1.4"},"H2":{"font-size-unit":"px","font-size":"30","font-weight":"","color":""},"H3":{"font-size-unit":"px","font-size":"24","font-weight":"","color":""},"H4":{"font-size-unit":"px","font-size":"20","font-weight":"","color":""},"H5":{"font-size-unit":"px","font-size":"18","font-weight":"","color":""},"H6":{"font-size-unit":"px","font-size":"16","font-weight":"","color":""}},"body_text":{"font-size-unit":"px","font-size":"20","font-weight":"400","line-height":"1.6","color":"color(18)"},"links":{"all":{"color":"#b08a35","font-weight":"","text-decoration":"none","hover_color":"","hover_text-decoration":"none"},"text_link":{"color":"","font-weight":"","text-decoration":"","hover_color":"#ac8c60","hover_text-decoration":"underline"},"link_wrapper":{"color":"","font-weight":"","text-decoration":"","hover_color":"","hover_text-decoration":""},"button":{"border-radius-unit":"px","font-weight":"","border-radius":"3"}},"sections":{"container-padding-top-unit":"px","container-padding-bottom-unit":"px","container-padding-left-unit":"px","container-padding-right-unit":"px","container-padding-top":"75","container-padding-bottom":"75","container-padding-left":"20","container-padding-right":"20"},"columns":{"padding-top":"0","padding-top-unit":"px","padding-bottom":"0","padding-bottom-unit":"px","padding-left":"0","padding-left-unit":"px","padding-right":"0","padding-right-unit":"px"},"max-width":"1120","breakpoints":{"tablet":"992","phone-landscape":"768","phone-portrait":"480"},"aos":{"type":"","duration":"","easing":"","offset":"","delay":"","anchor-placement":"","once":"","mirror":"","disable":""},"scripts":"<<already seen>>"},"oldVal":{"fonts":{"Text":"Cambay","Display":"Titillium Web"},"indicateParents":"true","classSuggestionsLimit":"5","headings":{"H1":{"font-size-unit":"px","font-size":"36","font-weight":"600","color":"","line-height":"1.4"},"H2":{"font-size-unit":"px","font-size":"30","font-weight":"","color":""},"H3":{"font-size-unit":"px","font-size":"24","font-weight":"","color":""},"H4":{"font-size-unit":"px","font-size":"20","font-weight":"","color":""},"H5":{"font-size-unit":"px","font-size":"18","font-weight":"","color":""},"H6":{"font-size-unit":"px","font-size":"16","font-weight":"","color":""}},"body_text":{"font-size-unit":"px","font-size":"20","font-weight":"400","line-height":"1.6","color":"color(18)"},"links":{"all":{"color":"#b08a35","font-weight":"","text-decoration":"none","hover_color":"","hover_text-decoration":"none"},"text_link":{"color":"","font-weight":"","text-decoration":"","hover_color":"#ac8c60","hover_text-decoration":"underline"},"link_wrapper":{"color":"","font-weight":"","text-decoration":"","hover_color":"","hover_text-decoration":""},"button":{"border-radius-unit":"px","font-weight":"","border-radius":"3"}},"sections":{"container-padding-top-unit":"px","container-padding-bottom-unit":"px","container-padding-left-unit":"px","container-padding-right-unit":"px","container-padding-top":"75","container-padding-bottom":"75","container-padding-left":"20","container-padding-right":"20"},"columns":{"padding-top":"0","padding-top-unit":"px","padding-bottom":"0","padding-bottom-unit":"px","padding-left":"0","padding-left-unit":"px","padding-right":"0","padding-right-unit":"px"},"max-width":"1120","breakpoints":{"tablet":"992","phone-landscape":"768","phone-portrait":"480"},"aos":{"type":"","duration":"","easing":"","offset":"","delay":"","anchor-placement":"","once":"","mirror":"","disable":""},"scripts":{"scroll_to_hash":"true","scroll_to_hash_time":"200","scroll_to_hash_offset":"-40"}}},{"msg":"globalSettings.sections","newVal":"<<already seen>>","oldVal":{"container-padding-top-unit":"px","container-padding-bottom-unit":"px","container-padding-left-unit":"px","container-padding-right-unit":"px","container-padding-top":"75","container-padding-bottom":"75","container-padding-left":"20","container-padding-right":"20"}},{"msg":"pageSettingsMeta","newVal":{"max-width":"","overlay-header-above":"","aos":{"type":"","duration":"","easing":"","offset":"","delay":"","anchor-placement":"","once":"","mirror":"","disable":""},"scripts":"<<already seen>>"},"oldVal":{"max-width":"","overlay-header-above":"","aos":{"type":"","duration":"","easing":"","offset":"","delay":"","anchor-placement":"","once":"","mirror":"","disable":""},"scripts":{"scroll_to_hash":"","scroll_to_hash_time":"","scroll_to_hash_offset":""}}},{"msg":"pageSettingsMeta.aos","newVal":"<<already seen>>","oldVal":{"type":"","duration":"","easing":"","offset":"","delay":"","anchor-placement":"","once":"","mirror":"","disable":""}}],[{"msg":"globalSettings.scripts","newVal":"<<already seen>>","oldVal":{"scroll_to_hash":"true","scroll_to_hash_time":"200","scroll_to_hash_offset":"-40"}},{"msg":"pageSettingsMeta.scripts","newVal":"<<already seen>>","oldVal":{"scroll_to_hash":"","scroll_to_hash_time":"","scroll_to_hash_offset":""}},{"msg":"globalSettings","newVal":"<<already seen>>","oldVal":{"fonts":{"Text":"Cambay","Display":"Titillium Web"},"indicateParents":"true","classSuggestionsLimit":"5","headings":{"H1":{"font-size-unit":"px","font-size":"36","font-weight":"600","color":"","line-height":"1.4"},"H2":{"font-size-unit":"px","font-size":"30","font-weight":"","color":""},"H3":{"font-size-unit":"px","font-size":"24","font-weight":"","color":""},"H4":{"font-size-unit":"px","font-size":"20","font-weight":"","color":""},"H5":{"font-size-unit":"px","font-size":"18","font-weight":"","color":""},"H6":{"font-size-unit":"px","font-size":"16","font-weight":"","color":""}},"body_text":{"font-size-unit":"px","font-size":"20","font-weight":"400","line-height":"1.6","color":"color(18)"},"links":{"all":{"color":"#b08a35","font-weight":"","text-decoration":"none","hover_color":"","hover_text-decoration":"none"},"text_link":{"color":"","font-weight":"","text-decoration":"","hover_color":"#ac8c60","hover_text-decoration":"underline"},"link_wrapper":{"color":"","font-weight":"","text-decoration":"","hover_color":"","hover_text-decoration":""},"button":{"border-radius-unit":"px","font-weight":"","border-radius":"3"}},"sections":{"container-padding-top-unit":"px","container-padding-bottom-unit":"px","container-padding-left-unit":"px","container-padding-right-unit":"px","container-padding-top":"75","container-padding-bottom":"75","container-padding-left":"20","container-padding-right":"20"},"columns":{"padding-top":"0","padding-top-unit":"px","padding-bottom":"0","padding-bottom-unit":"px","padding-left":"0","padding-left-unit":"px","padding-right":"0","padding-right-unit":"px"},"max-width":"1120","breakpoints":{"tablet":"992","phone-landscape":"768","phone-portrait":"480"},"aos":{"type":"","duration":"","easing":"","offset":"","delay":"","anchor-placement":"","once":"","mirror":"","disable":""},"scripts":{"scroll_to_hash":"true","scroll_to_hash_time":"200","scroll_to_hash_offset":"-40"}}},{"msg":"globalSettings.sections","newVal":"<<already seen>>","oldVal":{"container-padding-top-unit":"px","container-padding-bottom-unit":"px","container-padding-left-unit":"px","container-padding-right-unit":"px","container-padding-top":"75","container-padding-bottom":"75","container-padding-left":"20","container-padding-right":"20"}},{"msg":"pageSettingsMeta","newVal":"<<already seen>>","oldVal":{"max-width":"","overlay-header-above":"","aos":{"type":"","duration":"","easing":"","offset":"","delay":"","anchor-placement":"","once":"","mirror":"","disable":""},"scripts":{"scroll_to_hash":"","scroll_to_hash_time":"","scroll_to_hash_offset":""}}},{"msg":"pageSettingsMeta.aos","newVal":"<<already seen>>","oldVal":{"type":"","duration":"","easing":"","offset":"","delay":"","anchor-placement":"","once":"","mirror":"","disable":""}}],[{"msg":"globalSettings.scripts","newVal":"<<already seen>>","oldVal":{"scroll_to_hash":"true","scroll_to_hash_time":"200","scroll_to_hash_offset":"-40"}},{"msg":"pageSettingsMeta.scripts","newVal":"<<already seen>>","oldVal":{"scroll_to_hash":"","scroll_to_hash_time":"","scroll_to_hash_offset":""}},{"msg":"globalSettings","newVal":"<<already seen>>","oldVal":{"fonts":{"Text":"Cambay","Display":"Titillium Web"},"indicateParents":"true","classSuggestionsLimit":"5","headings":{"H1":{"font-size-unit":"px","font-size":"36","font-weight":"600","color":"","line-height":"1.4"},"H2":{"font-size-unit":"px","font-size":"30","font-weight":"","color":""},"H3":{"font-size-unit":"px","font-size":"24","font-weight":"","color":""},"H4":{"font-size-unit":"px","font-size":"20","font-weight":"","color":""},"H5":{"font-size-unit":"px","font-size":"18","font-weight":"","color":""},"H6":{"font-size-unit":"px","font-size":"16","font-weight":"","color":""}},"body_text":{"font-size-unit":"px","font-size":"20","font-weight":"400","line-height":"1.6","color":"color(18)"},"links":{"all":{"color":"#b08a35","font-weight":"","text-decoration":"none","hover_color":"","hover_text-decoration":"none"},"text_link":{"color":"","font-weight":"","text-decoration":"","hover_color":"#ac8c60","hover_text-decoration":"underline"},"link_wrapper":{"color":"","font-weight":"","text-decoration":"","hover_color":"","hover_text-decoration":""},"button":{"border-radius-unit":"px","font-weight":"","border-radius":"3"}},"sections":{"container-padding-top-unit":"px","container-padding-bottom-unit":"px","container-padding-left-unit":"px","container-padding-right-unit":"px","container-padding-top":"75","container-padding-bottom":"75","container-padding-left":"20","container-padding-right":"20"},"columns":{"padding-top":"0","padding-top-unit":"px","padding-bottom":"0","padding-bottom-unit":"px","padding-left":"0","padding-left-unit":"px","padding-right":"0","padding-right-unit":"px"},"max-width":"1120","breakpoints":{"tablet":"992","phone-landscape":"768","phone-portrait":"480"},"aos":{"type":"","duration":"","easing":"","offset":"","delay":"","anchor-placement":"","once":"","mirror":"","disable":""},"scripts":{"scroll_to_hash":"true","scroll_to_hash_time":"200","scroll_to_hash_offset":"-40"}}},{"msg":"globalSettings.sections","newVal":"<<already seen>>","oldVal":{"container-padding-top-unit":"px","container-padding-bottom-unit":"px","container-padding-left-unit":"px","container-padding-right-unit":"px","container-padding-top":"75","container-padding-bottom":"75","container-padding-left":"20","container-padding-right":"20"}},{"msg":"pageSettingsMeta","newVal":"<<already seen>>","oldVal":{"max-width":"","overlay-header-above":"","aos":{"type":"","duration":"","easing":"","offset":"","delay":"","anchor-placement":"","once":"","mirror":"","disable":""},"scripts":{"scroll_to_hash":"","scroll_to_hash_time":"","scroll_to_hash_offset":""}}},{"msg":"pageSettingsMeta.aos","newVal":"<<already seen>>","oldVal":{"type":"","duration":"","easing":"","offset":"","delay":"","anchor-placement":"","once":"","mirror":"","disable":""}}],[{"msg":"globalSettings.scripts","newVal":"<<already seen>>","oldVal":{"scroll_to_hash":"true","scroll_to_hash_time":"200","scroll_to_hash_offset":"-40"}},{"msg":"pageSettingsMeta.scripts","newVal":"<<already seen>>","oldVal":{"scroll_to_hash":"","scroll_to_hash_time":"","scroll_to_hash_offset":""}},{"msg":"globalSettings","newVal":"<<already seen>>","oldVal":{"fonts":{"Text":"Cambay","Display":"Titillium Web"},"indicateParents":"true","classSuggestionsLimit":"5","headings":{"H1":{"font-size-unit":"px","font-size":"36","font-weight":"600","color":"","line-height":"1.4"},"H2":{"font-size-unit":"px","font-size":"30","font-weight":"","color":""},"H3":{"font-size-unit":"px","font-size":"24","font-weight":"","color":""},"H4":{"font-size-unit":"px","font-size":"20","font-weight":"","color":""},"H5":{"font-size-unit":"px","font-size":"18","font-weight":"","color":""},"H6":{"font-size-unit":"px","font-size":"16","font-weight":"","color":""}},"body_text":{"font-size-unit":"px","font-size":"20","font-weight":"400","line-height":"1.6","color":"color(18)"},"links":{"all":{"color":"#b08a35","font-weight":"","text-decoration":"none","hover_color":"","hover_text-decoration":"none"},"text_link":{"color":"","font-weight":"","text-decoration":"","hover_color":"#ac8c60","hover_text-decoration":"underline"},"link_wrapper":{"color":"","font-weight":"","text-decoration":"","hover_color":"","hover_text-decoration":""},"button":{"border-radius-unit":"px","font-weight":"","border-radius":"3"}},"sections":{"container-padding-top-unit":"px","container-padding-bottom-unit":"px","container-padding-left-unit":"px","container-padding-right-unit":"px","container-padding-top":"75","container-padding-bottom":"75","container-padding-left":"20","container-padding-right":"20"},"columns":{"padding-top":"0","padding-top-unit":"px","padding-bottom":"0","padding-bottom-unit":"px","padding-left":"0","padding-left-unit":"px","padding-right":"0","padding-right-unit":"px"},"max-width":"1120","breakpoints":{"tablet":"992","phone-landscape":"768","phone-portrait":"480"},"aos":{"type":"","duration":"","easing":"","offset":"","delay":"","anchor-placement":"","once":"","mirror":"","disable":""},"scripts":{"scroll_to_hash":"true","scroll_to_hash_time":"200","scroll_to_hash_offset":"-40"}}},{"msg":"globalSettings.sections","newVal":"<<already seen>>","oldVal":{"container-padding-top-unit":"px","container-padding-bottom-unit":"px","container-padding-left-unit":"px","container-padding-right-unit":"px","container-padding-top":"75","container-padding-bottom":"75","container-padding-left":"20","container-padding-right":"20"}},{"msg":"pageSettingsMeta","newVal":"<<already seen>>","oldVal":{"max-width":"","overlay-header-above":"","aos":{"type":"","duration":"","easing":"","offset":"","delay":"","anchor-placement":"","once":"","mirror":"","disable":""},"scripts":{"scroll_to_hash":"","scroll_to_hash_time":"","scroll_to_hash_offset":""}}},{"msg":"pageSettingsMeta.aos","newVal":"<<already seen>>","oldVal":{"type":"","duration":"","easing":"","offset":"","delay":"","anchor-placement":"","once":"","mirror":"","disable":""}}],[{"msg":"globalSettings.scripts","newVal":"<<already seen>>","oldVal":{"scroll_to_hash":"true","scroll_to_hash_time":"200","scroll_to_hash_offset":"-40"}},{"msg":"pageSettingsMeta.scripts","newVal":"<<already seen>>","oldVal":{"scroll_to_hash":"","scroll_to_hash_time":"","scroll_to_hash_offset":""}},{"msg":"globalSettings","newVal":"<<already seen>>","oldVal":{"fonts":{"Text":"Cambay","Display":"Titillium Web"},"indicateParents":"true","classSuggestionsLimit":"5","headings":{"H1":{"font-size-unit":"px","font-size":"36","font-weight":"600","color":"","line-height":"1.4"},"H2":{"font-size-unit":"px","font-size":"30","font-weight":"","color":""},"H3":{"font-size-unit":"px","font-size":"24","font-weight":"","color":""},"H4":{"font-size-unit":"px","font-size":"20","font-weight":"","color":""},"H5":{"font-size-unit":"px","font-size":"18","font-weight":"","color":""},"H6":{"font-size-unit":"px","font-size":"16","font-weight":"","color":""}},"body_text":{"font-size-unit":"px","font-size":"20","font-weight":"400","line-height":"1.6","color":"color(18)"},"links":{"all":{"color":"#b08a35","font-weight":"","text-decoration":"none","hover_color":"","hover_text-decoration":"none"},"text_link":{"color":"","font-weight":"","text-decoration":"","hover_color":"#ac8c60","hover_text-decoration":"underline"},"link_wrapper":{"color":"","font-weight":"","text-decoration":"","hover_color":"","hover_text-decoration":""},"button":{"border-radius-unit":"px","font-weight":"","border-radius":"3"}},"sections":{"container-padding-top-unit":"px","container-padding-bottom-unit":"px","container-padding-left-unit":"px","container-padding-right-unit":"px","container-padding-top":"75","container-padding-bottom":"75","container-padding-left":"20","container-padding-right":"20"},"columns":{"padding-top":"0","padding-top-unit":"px","padding-bottom":"0","padding-bottom-unit":"px","padding-left":"0","padding-left-unit":"px","padding-right":"0","padding-right-unit":"px"},"max-width":"1120","breakpoints":{"tablet":"992","phone-landscape":"768","phone-portrait":"480"},"aos":{"type":"","duration":"","easing":"","offset":"","delay":"","anchor-placement":"","once":"","mirror":"","disable":""},"scripts":{"scroll_to_hash":"true","scroll_to_hash_time":"200","scroll_to_hash_offset":"-40"}}},{"msg":"globalSettings.sections","newVal":"<<already seen>>","oldVal":{"container-padding-top-unit":"px","container-padding-bottom-unit":"px","container-padding-left-unit":"px","container-padding-right-unit":"px","container-padding-top":"75","container-padding-bottom":"75","container-padding-left":"20","container-padding-right":"20"}},{"msg":"pageSettingsMeta","newVal":"<<already seen>>","oldVal":{"max-width":"","overlay-header-above":"","aos":{"type":"","duration":"","easing":"","offset":"","delay":"","anchor-placement":"","once":"","mirror":"","disable":""},"scripts":{"scroll_to_hash":"","scroll_to_hash_time":"","scroll_to_hash_offset":""}}},{"msg":"pageSettingsMeta.aos","newVal":"<<already seen>>","oldVal":{"type":"","duration":"","easing":"","offset":"","delay":"","anchor-placement":"","once":"","mirror":"","disable":""}}]]

**A link to a Sandbox site where the bug has been reproduced https://oxygenbuilder.com/try? (REQUIRED)**
https://oxygen-qyrt5wdt37shl.oxygen-demo.qsandbox.me/safari-test-page/?ct_builder=true&ct_inner=true

**IF YOU CAN'T PROVIDE A SANDBOX REPRODUCTION: Steps required to reproduce the bug:**
1. Open an Oxygen page in Editor using Safari 15.0 (on macOS Catalina 10.15.7)
2. Sometimes the error will appear immediately, sometimes it will appear after a couple of minutes. I have yet to be able to identify a trigger action. Sometimes it won't show up for ages.

**If you can't fill out the above information, you should not be filing a bug report. Instead, contact us via https://oxygenbuilder.com/support with the details you have and we'll investigate your issue further.**

**Comment by rudi-ob** [comment]
Same here :(

**Comment by KittenCodes** [comment]
This is fixed in Oxygen v3.9.
