### ISSUE TITLE
Script error. on line #0 in

### ISSUE THREAD

**Issue by kappesante** [soflyy/oxygen-bugs-and-features#2439]
in only one website i'm working on, no other plugins installed, i got this error as soon as i open oxygen:

**Script error. on line #0 in**

then everything become extremely laggy, can't do anything. i have to wait minutes before a simple click is registered. the tab is very unresponsive.

**Comment by KittenCodes** [comment]
@kappesante Please open a support ticket so that we can take a look at this for you: https://oxygenbuilder.com/support.
