### ISSUE TITLE
HowTo: Add class to <html> like "no-js"

### ISSUE THREAD

**Issue by MLzen** [soflyy/oxygen-bugs-and-features#2440]
Hello guys,

I could not find a solution for adding a class to the <html> tag (<body> tag is not a solution in this case). The solution should not need to filter the output completely for this ;-(
Is there a way to do this?

Best regards
ML

**Comment by KittenCodes** [comment]
You may be able to inject the class using jQuery or JavaScript in a Code Block - https://stackoverflow.com/a/13981006

**Comment by MLzen** [comment]
My fault because I did not tell exactly: it must work without javascript. There is no point in adding "no-js" via javascript, it should be deleted on load if javascript is up.

**Comment by wpsumo** [comment]
Just revert the logic? Add class to body tag with JavaScript and if `class="js-enabled"` tag is there = JavaScript is running, if no tag is there = no JavaScript.

**Comment by MLzen** [comment]
There are cases where you want to have control over <html> before Javascript is up and in normal Wordpress theming you have this control by default. The question is still: how can this be done on the output before Javascript sets something up?
