### ISSUE TITLE
state does not possible delete

### ISSUE THREAD

**Issue by trudoom** [soflyy/oxygen-bugs-and-features#2449]
Pseudo-class name is not posssible delete.

1. click on some element
2. go to left panel and click on "state" button, 
3. than click "add state" and add new pseudo-class name
3. state is correct inserted
4. now is not possible delete this new state

**Comment by KittenCodes** [comment]
@trudoom

I've not been able to replicate this. Are you using the Alpha of v3.9 or the current release v3.8.1?

**Comment by trudoom** [comment]
@KittenCodes I have 3.8.1 version. Here is process with screens:
 
1.  click on some element
2. go to left panel and click on "state" button
![obrazek](https://user-images.githubusercontent.com/66619037/136256454-bb1f1306-5af7-404d-bb8b-94e169517003.png)

3. click "add state" and add new pseudo-class name
![obrazek](https://user-images.githubusercontent.com/66619037/136256556-66a396de-78c3-44a6-afef-3a580529e9f3.png)

![obrazek](https://user-images.githubusercontent.com/66619037/136256763-cfed57a1-53b2-4f2a-a795-eaf788e88d5b.png)

4. state is correct inserted
![obrazek](https://user-images.githubusercontent.com/66619037/136256894-87914305-e56b-4aae-b910-a38ab40405d0.png)

5. now is not possible delete this new state
