### ISSUE TITLE
Gallery (src?): ?width=300 (or any number depends device)

### ISSUE THREAD

**Issue by Bebuk85** [soflyy/oxygen-bugs-and-features#2450]
Hi the gallery of default by oxygen it's creating a new load of the same image adding "?width=300" at the end of the url.

![image](https://user-images.githubusercontent.com/72046610/136132321-f06d703f-28c7-4a08-b34b-8757f7d6fc85.png)
 as you can see in the image the DJI pictures, also if i tried in incognito mode with inspector>network and disable cache on mobile even on pc the lightbox got broken and only redirect to url of the image instead of show the lightbox.

i think the problem is because it's not using "src".

https://loscaboscharters.com/31ftt-ya-sabras/

**Comment by KittenCodes** [comment]
Thanks @Bebuk85.

I still don't seem to be able to replicate this on a clean Sandbox site. Please could you open a support ticket so that we can take a look at your site? You can open one here: https://oxygenbuilder.com/support.
