### ISSUE TITLE
ACF Bug

### ISSUE THREAD

**Issue by katsar0v** [soflyy/oxygen-bugs-and-features#2454]
Just for your info, when an ACF field is created for a page, editor opened and acf field deleted, the following error appears:

```
ui.min.js?ver=3.8.1:formatted?ver=3.8.1:formatted:1223 Uncaught TypeError: Cannot read properties of undefined (reading 'fields')
    at Scope.s.acfRepeaterDynamicDialogProcess (ui.min.js?ver=3.8.1:formatted:1223)
    at HTMLDivElement.<anonymous> (common.directives.min.js?ver=3.8.1:1)
    at HTMLDivElement.dispatch (jquery.min.js?ver=3.6.0:2)
    at HTMLDivElement.v.handle (jquery.min.js?ver=3.6.0:2)
```

**Comment by KittenCodes** [comment]
@katsar0v I've not been able to replicate this. Where does the ACF field need to be deleted from?

**Comment by KittenCodes** [comment]
@katsar0v Are you deleting the field from ACF whilst the builder is open, or before you open the builder?

**Comment by katsar0v** [comment]
> @katsar0v Are you deleting the field from ACF whilst the builder is open, or before you open the builder?

Does not matter, as the issue can be reproduced after refreshing the page. Fix: delete the repeater (as element on the page) and create new. This is what works for me.

**Comment by katsar0v** [comment]
Sorry for the late reply. Both acf repeater and oxygen repeater were involved. The bug seems to be fixed now and I cannot reproduce it.

**Comment by Spellhammer** [comment]
@katsar0v Thanks for the update!
