### ISSUE TITLE
Allow styling of non-oxygen elements

### ISSUE THREAD

**Issue by Helmi** [soflyy/oxygen-bugs-and-features#246]
Oxygen already brings a lot of the features of well known CSS helper plugins (CSS Hero, Microthemer) but as a downside it doesn't allow the styling of "foreign" elements apart from adding selectors manually.

It would be very helpful to be able to easily pick and select elements from the editor and style them with what Oxygen already offers.

This needs a powerful selector picker - Microthemer could be a good tool to look at. I think they're doing it very good already - others not so much.

**Comment by quadcom** [comment]
I do believe that is what the Selector Detector (in settings) allows for.

**Comment by wplit** [comment]
Yes, this already exists in Oxygen. You just need to turn it on (and watch the instruction video)

**Comment by ukuwi** [comment]
It already exists. Enable Selector Detector in settings.
