### ISSUE TITLE
Section Hiding

### ISSUE THREAD

**Issue by andreslotta** [soflyy/oxygen-bugs-and-features#2462]
**Describe the bug**
When I want to hide a section by setting its `display` value to `none` with the native Oxygen controls the setting applies to the inner section container (`.ct-section-inner-wrap`) which is semantically wrong and might lead to unwanted behaviour.

Example for unwanted behaviour:
When that section has an explicit height (e.g. a hero section with a height of `100vh`) set and I want to hide that section in the frontend (e.g. only show it on desktop devices) there is a large whitespace (of `100vh`) because the height is applied to the section and it's just the inner section container that is hidden.

I understand that this happens because other values (like `flex` or `grid`) **have to** apply to the inner container to make the layout work. So I think there has to be some logic to have an exception for the `none` case.

**A link to a Sandbox site where the bug has been reproduced:**
http://bright-quagga.w6.wpsandbox.pro/section-hiding/

**Steps to reproduce the behavior:**
1. Create a page
2. Add two sections
3. Set a height of `100vh` for the first section
4. Set the first section's `display` value to `none` with the native Oxygen controls
5. Add a headline to the second section (for testing purposes)
6. Save the page
7. Check the frontend and see that there is a large whitespace before the second section and its headline appears although the first section should be hidden. Check the page's source code and see that it's not the section that is hidden but its inner container

**Expected behaviour:**
The section (`.ct-section`) is hidden.

**Actual behaviour:**
The inner section container (`.ct-section-inner-wrap`) is hidden.

**Comment by KittenCodes** [comment]
Reported internally.
