### ISSUE TITLE
Overlay covers admin bar

### ISSUE THREAD

**Issue by tannerchung** [soflyy/oxygen-bugs-and-features#247]
**Describe the bug**
*A clear and concise description of what the bug is.*

The overlay menu bar covers the wordpress admin toolbar

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
*Yes/No*

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
*If yes, provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*

**To Reproduce**
Log into the wordpress instance
Create a menu as an overlay

**Expected behavior**
*A clear and concise description of what you expected to happen.*
Zindex of overlay menu bar should always be below the admin toolbar

**What actually happens**
*A clear and concise description of what happens instead of the expected behavior.*
When on the front end logged, the admin toolbar is covered by the overlayed menu

**Screenshots**
*If applicable, add screenshots to help explain your problem.*

![Screenshot_042019_030429_PM](https://user-images.githubusercontent.com/3707037/56461264-98f89300-637d-11e9-8736-2c55d19a0f6d.jpg)

**Comment by KittenCodes** [comment]
@tannerchung, I'm not able to replicate this in the latest version of Oxygen (currently 2.4.1). If you're still having problems, please email support@oxygenbuilder.com.
