### ISSUE TITLE
Responsiveness of sticky header not in sync with menu

### ISSUE THREAD

**Issue by santo74** [soflyy/oxygen-bugs-and-features#2472]
**Describe the bug**
When a header is set to be sticky at a given breakpoint, e.g. "above page container" (1120px), and the mobile menu toggle for the menu contained in that header is set to the same breakpoint ("page container (1120px) and below" in this example) then the stickiness of the header is disabled before the mobile menu is activated.
The reason seems to be that the header stickiness doesn't include the scrollbar width in its calculation while the mobile menu toggle calculation does include the scrollbar width. As a result the former ends before the latter starts.

**A link to a Sandbox site where the bug has been reproduced https://oxygenbuilder.com/try? (REQUIRED)**
I tried to create a reproducer in a sandbox but for some reason the menu doesn't render correctly in the sandbox (frontend) as soon as I edit it. I tried both with a blank install and a prepopulated sample site, but in both cases the menu layout is messed up in the frontend.
In addition, the sandbox doesn't contain the pro menu component, while that is the one where I detected the issue.

**IF YOU CAN'T PROVIDE A SANDBOX REPRODUCTION: Steps required to reproduce the bug:**
1. Create a header with the header builder
2. Add a pro menu to the right part of the header
3. Check "enable sticky header" for the header builder
4. Set "Sticky above" to "At or above 992px"
5. Go to the Pro Menu and set "Mobile Menu / Toggle Below" to "Less than 992px"
6. Go to the frontend and check that the header is sticky.
7. Now resize the browser to around 995px (incl the scrollbar width) so that the menu is still the regular, non-mobile menu.
8. While the menu is still the non-mobile menu the header won't be sticky anymore while it's set to "at or above 992px"

**Comment by KittenCodes** [comment]
@santo74 I've not been able to replicate this on a Sandbox site. Here's a link so that you can check it out - the username and password are both demo: https://oxygen-qdyx2rj73q3hl.oxygen-demo.qsandbox.me/.

If I try it at 995px (using responsive mode in my browser tools, not by resizing the browser), then I see a sticky header and the full menu. This continues down to 992px and works as expected.

If I reduce the width to 991px then the header isn't sticky any longer and the mobile menu is used.

Video: https://www.loom.com/share/1868291dc46d47debf01db6b498e1fb5.

**Comment by santo74** [comment]
Hi @KittenCodes I went to the url you provided and did exactly the same test with the responsive mode in Firefox on Windows and made some screenshots of the results.
The first screenshot is always the initial state at the specified width while the second screenshot is the same width but scrolled down to the testimonials section.

Here are the results:

At 995px I see a sticky header and full menu.
(Please see screenshots 01 and 02 below)

![image](https://user-images.githubusercontent.com/7080464/137640457-e2838715-c79b-41ba-b759-56e819503cda.png)
![image](https://user-images.githubusercontent.com/7080464/137640473-9bda8e70-5135-4939-95b1-67eabe3e2cd6.png)

However, when I reduce the width to 992px the menu is still the full menu but the header isn't sticky anymore (no header when scrolled down, in this example scrolled to the testimonials section).
(Please see screenshots 03 and 04 below.)

![image](https://user-images.githubusercontent.com/7080464/137640492-337d3dee-fb3f-4347-9a56-da02cff0394b.png)
![image](https://user-images.githubusercontent.com/7080464/137640498-481950ab-d6f5-45dd-bc1d-8b2e5c115c3d.png)

I also tested with chrome and Edge and in those browsers the behaviour is similar, but at 991px instead of 992px.

To be honest, it only seems to happen at that specific width. If I reduce the width 1px more then the mobile menu kicks in.
This is in contrast to the behaviour I noticed last week where it seemed to happen over several pixels, appr the number of pixels corresponding to the width of the scrollbar. This was on another system, more specifically a Mac with a Retina display.

**Comment by KittenCodes** [comment]
@santo74 What version of Firefox are you using?

On my computer (Windows 10) using Firefox Developer Edition, v94.0b8 (64-bit), I see the full menu and the sticky header at 992px. If I drop to 991px, then I see the mobile menu and no sticky header.

Video: https://www.loom.com/share/819a095bb5f74dfc8ad3de82e3e28fcf.
