### ISSUE TITLE
Adding of more social networks to social icons element

### ISSUE THREAD

**Issue by edmundyeo** [soflyy/oxygen-bugs-and-features#2476]
Hi there,

May I request for pinterest and tiktok to be added as part of the social icons element in oxygen as these are 2 very popular social networks?

Thank you,
Edmund

**Comment by Cr3epy** [comment]
Same here, an option to upload custom points would be nice if you can update it regulary

**Comment by KittenCodes** [comment]
Duplicate: https://github.com/soflyy/oxygen-bugs-and-features/issues/234
