### ISSUE TITLE
Navigation Items with no link do not appear on mobile

### ISSUE THREAD

**Issue by Hornet25** [soflyy/oxygen-bugs-and-features#248]
If you create a navigation item that has no link but sub-menu items that do have a link, when viewed on mobile, the navigation items do not appear.

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
Yes

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
Yes I can
http://amber-wryneck.w6.wpsandbox.pro/
*If yes, provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*

**To Reproduce**
Create a new menu
Add a Custom Link with a link "##" to get it to appear on the navigation
Delete the URL once in the main menu
Add menu item to real pages in the website as sub menu items to this custom link
Save the menu
Add the menu to the Oxygen Template
View the site on a desktop and the custom link and sub menu items appear as a dropdown
View as a hamburger and the Custom Link does not appear and neither do the sub menu items.

**Expected behavior**
On the assumption that I have created the main menu item that has no link correctly, I would expect the custom link and the sub menu items to appear in the mobile menu.

**What actually happens**
The Custom Link and Sub Menu Items do not appear in the mobile menu

**Screenshots**
*If applicable, add screenshots to help explain your problem.*

**Desktop (please complete the following information):**
 - Oxygen Version [e.g. 2.2 Alpha]

**Smartphone (please complete the following information):**
 - Oxygen Version [e.g. 2.2 Alpha]

**Additional context**
*Add any other context about the problem here.*

**Comment by KittenCodes** [comment]
@Hornet25, Please check if this is still an issue in Oxygen 2.4.1. If it is, please send me a link to a [Sandbox site](https://oxygenbuilder.com/try/) showing the issue.

**Comment by Hornet25** [comment]
Soph,

 

The problem still seems to exist but it isn’t quite as I explained it. The link to the sandbox is below:

 

http://dilligent-gorilla.w5.wpsandbox.pro/home/

 

I have two custom links in my menu.

 

*	Custom Link 1 has no sub menu and links to google.com. This works on big screens and in responsive mode
*	Custom Link 2 has sub menus and I do not want the Custom Link 2 to link to anything and only the sub menus to link to relevant pages. 

*	If I make the link http://## the Custom Link 2 and sub menus are displayed in both big screen and responsive modes. However, Custom Link 2 is clickable and takes me to a blank page. 
*	If I make the link just ‘#’ as suggested in some forums, the sub menus do not display in responsive mode. 
*	If I remove the link entirely from the URL box in the appearance --> menu settings, the link is no longer clickable when it appears on the big screen which is good, but it disappears (as does the two sub menus) when in responsive mode. 
*	If I make the link javascript:void(0) as suggested in other forums, the link isn’t displayed in responsive mode.

 

I hope this is clear

 

Kind regards,

 

Ian Randell 

ian@radiantweb.co.uk <mailto:ian@radiantweb.co.uk> 

 



 

Radiant Web

Office 7, Eclipse House

20 Sandown Road

Watford,

Herts.

WD24 7AE

 

t    0203 362 4121

f    01923 803904

e   sales@radiantweb.co.uk <mailto:sales@radiantweb.co.uk>   

w  radiantweb.co.uk <http://radiantweb.co.uk/> 

 

Please consider your impact on the environment before printing this e-mail.

 

This e-mail message is confidential and for use by the addressee only. If the message is received by anyone other than the addressee, please return the message to the sender by replying to it and then delete the message from your computer. Internet e-mails are not necessarily secure. Radiant Web does not accept responsibility for changes made to this message after it was sent.

 

Whilst all reasonable care has been taken to avoid the transmission of viruses, it is the responsibility of the recipient to ensure that the onward transmission, opening or use of this message and any attachments will not adversely affect its systems or data. No responsibility is accepted by Radiant Web in this regard and the recipient should carry out such virus and other checks as it considers appropriate.

**Comment by KittenCodes** [comment]
@Hornet25,

> If I make the link http://## the Custom Link 2 and sub menus are displayed in both big screen and responsive modes. However, Custom Link 2 is clickable and takes me to a blank page.

I found that the sub items weren't displayed when using this method.

> If I remove the link entirely from the URL box in the appearance --> menu settings, the link is no longer clickable when it appears on the big screen which is good, but it disappears (as does the two sub menus) when in responsive mode.

You're right - "Custom link 2" and the sub items aren't visible when using this method. However, you can select the menu in the builder and go to Mobile Responsive > Dropdowns  and select "Include dropdowns links in the responsive menu", which will show "Custom link 2", "Test 2" and "Test 3" in the mobile menu.

**Comment by Hornet25** [comment]
Soph,

 

The best solution to display a Custom Link that does not have a link but is just used to facilitate a sub menu is definitely the javascript:void(0); option in the URL for the custom link. When you hover over this item on the big screen version, there is no arrow cursor and the sub menu just appears and each sub menu is clickable.

 

In responsive mode, this option doesn’t display and if you click on the ‘Include Dropdown Links’ in the mobile / responsive option, the sub menu items become main menu items. This doesn’t look right to me.

 

If it was possible, I would ideally like the following:

 

The Custom Link has no page linked to it, but a sub menu.

On a big screen, hovering over the Custom Link displays the sub menu and the cursor does not change until it finds a link in the sub menu.

In responsive mode, the Custom Link is displayed and when clicked the sub menus are displayed.

 

I have also just realized that sub menus on normal links are not displayed in responsive mode. I have put Test Page 4 as a sub menu of Test Page 1 and it works fine on a big screen, but goes wrong in responsive mode.

 

To get around it, I have used a new plugin that Sridhar has recently created. I have it opening in a modal and it functions as I want it to, but I would prefer it to all work within Oxygen.

 

I hope this makes sense.

 

Kind regards,

 

Ian Randell 

ian@radiantweb.co.uk <mailto:ian@radiantweb.co.uk> 

 



 

Radiant Web

Office 7, Eclipse House

20 Sandown Road

Watford,

Herts.

WD24 7AE

 

t    0203 362 4121

f    01923 803904

e   sales@radiantweb.co.uk <mailto:sales@radiantweb.co.uk>   

w  radiantweb.co.uk <http://radiantweb.co.uk/> 

 

Please consider your impact on the environment before printing this e-mail.

 

This e-mail message is confidential and for use by the addressee only. If the message is received by anyone other than the addressee, please return the message to the sender by replying to it and then delete the message from your computer. Internet e-mails are not necessarily secure. Radiant Web does not accept responsibility for changes made to this message after it was sent.

 

Whilst all reasonable care has been taken to avoid the transmission of viruses, it is the responsibility of the recipient to ensure that the onward transmission, opening or use of this message and any attachments will not adversely affect its systems or data. No responsibility is accepted by Radiant Web in this regard and the recipient should carry out such virus and other checks as it considers appropriate.

**Comment by KittenCodes** [comment]
> In responsive mode, this option doesn’t display and if you click on the ‘Include Dropdown Links’ in the mobile / responsive option, the sub menu items become main menu items. This doesn’t look right to me.

This is how the Oxygen mobile menu works - sub items are shown as main items. If you'd like to see this work differently, then you can add a vote to the feature request here: https://github.com/soflyy/oxygen-bugs-and-features/issues/80.

> I have also just realized that sub menus on normal links are not displayed in responsive mode. I have put Test Page 4 as a sub menu of Test Page 1 and it works fine on a big screen, but goes wrong in responsive mode.

You need to select Include dropdowns links in the responsive menu via Mobile Responsive > Dropdowns for the sub items to show in the mobile menu.

> To get around it, I have used a new plugin that Sridhar has recently created. I have it opening in a modal and it functions as I want it to, but I would prefer it to all work within Oxygen.

It sounds like the plugin from Sridhar will be the best option currently.
