### ISSUE TITLE
Broken structure pane

### ISSUE THREAD

**Issue by ameneses67** [soflyy/oxygen-bugs-and-features#2496]
3.9 alpha 1 was ok. When upgraded to beta 1 the structure pane doesn't show as it should. Waited until next release but beta 2 keeps the issue. I disabled all plugins to see if it was a plugin conflict, but being Oxygen the only active plugin, the issue remains. On attached images you can see all plugins I'm working with and how the structure pane looks like (can't click any element).

![Snag_47d1671](https://user-images.githubusercontent.com/92225212/139598252-21a21a47-9432-405c-9169-90dad46f3d4b.png)

![Snag_47d33dc](https://user-images.githubusercontent.com/92225212/139598255-3f60c394-1054-4ae1-a0b4-22c369b60b8c.png)

**Comment by KittenCodes** [comment]
@ameneses67 Please open a support ticket so that we can take a look at this for you: https://oxygenbuilder.com/support.

**Comment by Spellhammer** [comment]
This is due to CSS caching and is resolved by hard refreshing your browser to clear the browser cache.

**Comment by ameneses67** [comment]
Hard refreshing fixed the problem.

Thank you,

Alfonso
