### ISSUE TITLE
Duplicate title tag when installing Yoast

### ISSUE THREAD

**Issue by junraemon** [soflyy/oxygen-bugs-and-features#2497]
When installing a Yoast plugin, it'll shows two title(<title>) tags when viewing the source code.

Link to Sandbox:
http://hungry-dormouse.w6.wpsandbox.pro/

**Comment by KittenCodes** [comment]
@junraemon This is fixed in 3.9 Beta.

**Comment by junraemon** [comment]
Thank you @KittenCodes 👍
