### ISSUE TITLE
Negative margins on Columns breaks layout when adjusted in responsive screen size

### ISSUE THREAD

**Issue by mgpub** [soflyy/oxygen-bugs-and-features#250]
**Describe the bug**
Video link to bug description: https://www.youtube.com/watch?v=GEYT3MTzKic
Please NOTE: in the video, my wife incorrectly says she wants the layout to be "vertical" - she meant to say "horizontal".

Server Error Log reports this:
Backend log: PHP Warning:  Invalid argument supplied for foreach() in /home/account_ path/public_html/wp-content/plugins/oxygen/component-framework/toolbar/toolbar.class.php on line 2075

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
*Yes*

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
*If yes, provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*
YES - see: http://selfish-cottonmouth.w6.wpsandbox.pro/test/

**To Reproduce**
1. Go to "Test" page and edit in O2
2. Click on the Columns container in the "Lower Section" - see Structure to navigate
3. Select Responsive Screen size of "Less than 992px"
4. While still on the "Columns" container, Select Advanced properties tab, then Size & Spacing
5. Type anything at all in the Top Margin box

**Expected behavior**
Expected to see the Top margin being adjusted while keeping the 2 column horizontal layout

**What actually happens**
Layout changes to vertically stacked columns and nothing will undo this. Also, PHP error log now has the error listed above.

**Screenshots**
*If applicable, add screenshots to help explain your problem.*
Unlisted YouTube video: https://www.youtube.com/watch?v=GEYT3MTzKic

**Desktop (please complete the following information):**
- OS: [e.g. iOS] Win 7
 - Browser [e.g. chrome, safari] Chrome
 - Oxygen Version [e.g. 2.2 Alpha] = 2.2.1

**Comment by quadcom** [comment]
So it displays wrong in the UI but how does that render if you save the page? I've seen this behaviour before. The UI is messed up but the page renders as intended.

**Comment by mgpub** [comment]
@quadcom I just checked this and it actually does break the design on the frontend too.

**Comment by KittenCodes** [comment]
@mgpub, I'm not able to replicate this in the latest version of Oxygen (2.4.1). If you're still having problems, please email support@oxygenbuilder.com.
