### ISSUE TITLE
DONE: Search box in code editor

### ISSUE THREAD

**Issue by fscriven** [soflyy/oxygen-bugs-and-features#2504]
**Describe the feature you'd like to see included in Oxygen.**
When editing code there should be the ability to search inside the code

**What are the use cases for this feature?**
Makes life much easier. Search is fundamental to editing code. 

**Examples of this feature or functionality.**
Ace editor does this very well. https://ace.c9.io/

**Comment by fscriven** [comment]
Possibly this could be combined with #2503 - but that relates to the CSS editor only. Not sure if they

**Comment by Spellhammer** [comment]
Full search/replace added in 4.7 beta 1.
