### ISSUE TITLE
3.9 RC Can't bring up elements after editing them

### ISSUE THREAD

**Issue by JTabdesign** [soflyy/oxygen-bugs-and-features#2506]
**Any bug report that doesn't include a Sandbox link or replication steps will be closed. If you can't provide these pieces of information, we're happy to help you via our official support channel instead: https://oxygenbuilder.com/support. You need to select "Something's broken and I need help" from the dropdown box on the left.**

**Describe the bug**
When I make changes to any element and click away from them to work on another element, when I go back to the element, the changes aren't available for edit. You see them on the front end, but I can no longer see the actual element changes in the element panel itself.

**A link to a Sandbox site where the bug has been reproduced https://oxygenbuilder.com/try? (REQUIRED)**
*Provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*

**IF YOU CAN'T PROVIDE A SANDBOX REPRODUCTION: Steps required to reproduce the bug:**
1. Go to section
2. add a custom shape divider
3. change the color by adding it to the shape divider
4. add a div to that section
5. Make it white
6. Go back to that section
7. Click on the add a custom shape divider
8. You will not see the shape divider you added in the backend, but it will show on the section in the front end.

1. Add a section
2. add a div
3. add a border to that div
4. add some elements to that div (text, heading, etc)
5. Go back to the div
6. Click on the border part of the div
7. You will not see the edits you made in the back end, just on the front end.

To be clear, in the part where you go to make the changes is where the element disappears, but in the visual side, you can see the changes.

The problem this causes is that any changes you make can not be edited.

**If you can't fill out the above information, you should not be filing a bug report. Instead, contact us via https://oxygenbuilder.com/support with the details you have and we'll investigate your issue further.**

**Comment by Spellhammer** [comment]
Thanks for the report.

I wasn't able to see any issues or disparities between the back-end/front-end on Shape Dividers while following your instructions.

I also believe the issue you're having with the border is the fact that the border settings aren't shown unless you pick a specific border side (top, right, bottom, left) after the border is initially set. This is a very old UI problem and isn't related to 3.9 RC 1.

Please send us a support ticket with a screen recording or access to an environment where the Shape Divider issue is occurring so we can follow the steps there: https://oxygenbuilder.com/support.
