### ISSUE TITLE
No Comments in Blo

### ISSUE THREAD

**Issue by CB16ECA** [soflyy/oxygen-bugs-and-features#2511]
https://optimistic-banzai.51-77-106-5.plesk.page/blog/

Trying to turn off "No Comments" on blog page. Turned off comments in Discussion and on the individual post, but cannot remove it. Please can you advise?

Thanks,

C

**Comment by KittenCodes** [comment]
@CB16ECA If you are still having problems, please open a support ticket: https://oxygenbuilder.com/support.
