### ISSUE TITLE
 The edit link disappeared

### ISSUE THREAD

**Issue by josuecjr** [soflyy/oxygen-bugs-and-features#2513]
Hello Are you okay?

I'm having a problem with the oxygenbuilder

I can't access the link that enables the oxygen editor on the pages.

"Edit with oxygen" disappeared

how can i reset?

**Any bug report that doesn't include a Sandbox link or replication steps will be closed. If you can't provide these pieces of information, we're happy to help you via our official support channel instead: https://oxygenbuilder.com/support. You need to select "Something's broken and I need help" from the dropdown box on the left.**

**Describe the bug**
*A clear and concise description of what the bug is.*

**A link to a Sandbox site where the bug has been reproduced https://oxygenbuilder.com/try? (REQUIRED)**
*Provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*

**IF YOU CAN'T PROVIDE A SANDBOX REPRODUCTION: Steps required to reproduce the bug:**

**If you can't fill out the above information, you should not be filing a bug report. Instead, contact us via https://oxygenbuilder.com/support with the details you have and we'll investigate your issue further.**

**Comment by KittenCodes** [comment]
@josuecjr

> "Edit with oxygen" disappeared

Please check if you disabled Oxygen on any post types via Oxygen > Settings > Client Control > Post Type Manager.

If that doesn't help, please open a support ticket so that we can take a look at your site: https://oxygenbuilder.com/support
