### ISSUE TITLE
wrong hight in Repeater type Grid Layout in 3.9 RC1

### ISSUE THREAD

**Issue by trudoom** [soflyy/oxygen-bugs-and-features#2515]
If you build Repeater for Post where post have feature image, so Grid have height 100% and is not possible change it.

Process:
1. create repeater for post (post must have feature images)
2. in the repeater settings change Grid Layout to check Enable grid
3. set to 3 Columns for example.
4. go to Structure panel and click to first DIV maked by Repeater.
5. go to Advanced Tab and set feature image as Background
6. now go to Size & Spacing and set Width = 300 px and Hight = 300px for this selected DIV. I wanted the square.
Save and see front end - front end has Hight set to 100%. More smaller than a square.
Any change for hight to other number in px don´t work.

**Comment by KittenCodes** [comment]
@trudoom I can't seem to reproduce this. Here's my test page: http://poor-goldfinch.w5.wpsandbox.pro/posties/.

Are you able to reproduce the issue on our Sandbox site? You can log in here: http://poor-goldfinch.w5.wpsandbox.pro?upass=sJ6S9p8lr5EH.
