### ISSUE TITLE
Backend isn't showing correct - Frontend yes

### ISSUE THREAD

**Issue by edcarreiro** [soflyy/oxygen-bugs-and-features#2519]
**Describe the bug**
I create a div inside a section - choose css width 300px and height 2px. The height in backend didn't show the correct size, but in frontend did.

**A link to a Sandbox site where the bug has been reproduced https://oxygenbuilder.com/try? (REQUIRED)**
http://attractive-crocodile.w5.wpsandbox.pro?upass=L4cTf226hMBf

**IF YOU CAN'T PROVIDE A SANDBOX REPRODUCTION: Steps required to reproduce the bug:**
1. Add a Section
2. Add a DIV inside section
3. chenge the div to width 300px and height 2px
4. See that the height don't change in backend but it is correct in frontend
![Screenshot 2021-11-17 --- 16 22 16@2x](https://user-images.githubusercontent.com/53188149/142268437-6585d46d-c1fc-4f24-9ce3-d0d494082e66.png)

![Screenshot 2021-11-17 --- 16 22 41@2x](https://user-images.githubusercontent.com/53188149/142268503-e1729bff-44fe-454f-8d75-02def9b0ab05.png)

**Comment by wplit** [comment]
This is on purpose, empty divs always have a min-height of 80px inside the builder so there's enough room to drag other elements inside them.

**Comment by KittenCodes** [comment]
@edcarreiro The answer from @wplit is correct. This isn't a bug, it's deliberate.

You can set the min-height to 2px, which will reduce the element height in the builder as well.
