### ISSUE TITLE
Global header color styles don't get applied to headers added through WordPress editor

### ISSUE THREAD

**Issue by bperniciaro** [soflyy/oxygen-bugs-and-features#2525]
Global header color styles configured in Oxygen are only being applied to headers added via the Oxygen builder.  Headers added through the standard WordPress editor ignore header color styles.  

I notice this behavior when I start with one of the pre-made site templates, but not when I create my own templates from scratch.  I'm not sure if this is a bug or just me misunderstanding how this works.

http://amiable-thrush.w5.wpsandbox.pro/2017/03/09/hello-world/

**Comment by bperniciaro** [comment]
Upon closer examination, it looks as though the styles overriding the global css settings are specific to the pre-made Oxygen site "Bed and Breakfast".  The pre-made styles are being applied inline, and as such are overriding some of the global CSS settings.

Is this how it is supposed to work?  That seems odd.

**Comment by KittenCodes** [comment]
@bperniciaro Global Styles are the "base" styles. Anything added via classes, stylesheets or by styling the individual elements will override those styles.
