### ISSUE TITLE
Easy Posts archive template pagination fails when permalink category base is set to "." (nothing)

### ISSUE THREAD

**Issue by karmaral** [soflyy/oxygen-bugs-and-features#2528]
**Describe the bug**
When using a category base of  ` . `, this disables the prefix, and the permalinks become:
`%site_url%/%cat_name%/%post_name%`
In doing so, the pagination in the template for the archives breaks.
With no 404 template, nothing happens, it just goes back to the 1st page. On another site in which I do have a 404 template, it just goes there.

[http://troubled-gorilla.w5.wpsandbox.pro/categ1/](http://troubled-gorilla.w5.wpsandbox.pro/categ1/)

**Steps required to reproduce the bug:**
1. Go to link and scroll to the bottom
2. Click on any pagination button
3. See error

This works again if I switch back to having a prefix.

**Comment by KittenCodes** [comment]
@karmaral This isn't caused by Oxygen. If you disable Oxygen, you will see there's still a 404 error for page 2 of the archive.
