### ISSUE TITLE
Issue with animation when scrolling

### ISSUE THREAD

**Issue by celalmentes** [soflyy/oxygen-bugs-and-features#2529]
Describe the bug. A clear and concise description of what the bug is:

When I add an animation to an element eg. Photo or Text, the element will disapear/ is not shown when you open the page on a computer or mac in a fullscreen = normal screen resolution. But is you adjust the window, so the design switches to ipad or smartphone resolution, the element will show up and the animation will start. If you then resize the window to fullscreen everything works again, until you refresh the page. 

On mobile devices everything works out of the box. 

To view the issue with correct styling:

Just check https://qelity.de/
In the section "Ihre Vorteile" I have added an animation to the first element (photo) 

To Reproduce
Add animate on scroll (without global settings) on one or multiple elements .

Expected behavior
When page is loaded, the element should be shown and the animation should start.

What actually happens
A clear and concise description of what happens instead of the expected behavior.
On Desktop Resolution: Element and not shown
On Mobile Resoltion: everything works as expected

Screenshots
Just visit: https://qelity.de/

Desktop (please complete the following information):

OS: MacOS / Windows 10 & 11
Browser Safari, Chrome, Firefox
Oxygen Version "latest official"
Smartphone (please complete the following information):
Huawei P30 Pro & Ipfone 13 Pro

**Comment by KittenCodes** [comment]
@celalmentes Please try selecting "Refresh AOS on page load" via Manage (in the top right of the builder) > Settings > Global Styles > Animate on Scroll.

If that doesn't help, please open a support ticket so that we can take a look at your site: https://oxygenbuilder.com/support.

**Comment by celalmentes** [comment]
@KittenCodes Thanks!!! :)
