### ISSUE TITLE
Error loading menu

### ISSUE THREAD

**Issue by gasserol** [soflyy/oxygen-bugs-and-features#253]
Hello, Using WP 5.1.1 and Oxygen 2.3.beta generates an error while loading menu. We serve the site over https. See error in attached file. If we serve site over http, error does not occur.
![oxygenbuilder-23beta_error](https://user-images.githubusercontent.com/4066878/56572956-583c8c00-65c0-11e9-9281-9601106d16e1.png)

**Comment by Spellhammer** [comment]
Make sure your Site and WordPress addresses under Settings > General in the WP Admin match the URL via which you're accessing the site (including protocol). If that doesn't fix the problem, send a ticket to support@oxygenbuilder.com with details and we'll investigate.
