### ISSUE TITLE
Element structure not visible and page not fully loaded in editor

### ISSUE THREAD

**Issue by RANSIDRAT** [soflyy/oxygen-bugs-and-features#2532]
LINK TO SANDBOX SITE
https://oxygen-qtlch24vhlnjl.oxygen-demo.qsandbox.me/
The page in question loads (ZIPFIXX) correctly on the front end. There is only one page on the website.
The page only partially loads inside the editor the first 50% of the page is visible the remaining 50% is not visible.
The structure panel is not visible to enable editing of the elements. 

1. click link https://oxygen-qtlch24vhlnjl.oxygen-demo.qsandbox.me/ and notice full page appears in browser
2. log in
3. edit page in oxygen 
4. view page in editor and notice the structure panel is not loading and and the last 50% of page is not visible in editor.
username: admin
password: itisahugebug

**Any bug report that doesn't include a Sandbox link or replication steps will be closed. If you can't provide these pieces of information, we're happy to help you via our official support channel instead: https://oxygenbuilder.com/support. You need to select "Something's broken and I need help" from the dropdown box on the left.**

**Describe the bug**
*A clear and concise description of what the bug is.*

**A link to a Sandbox site where the bug has been reproduced https://oxygenbuilder.com/try? (REQUIRED)**
*Provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*

**IF YOU CAN'T PROVIDE A SANDBOX REPRODUCTION: Steps required to reproduce the bug:**

**If you can't fill out the above information, you should not be filing a bug report. Instead, contact us via https://oxygenbuilder.com/support with the details you have and we'll investigate your issue further.**

**Comment by RANSIDRAT** [comment]
When I create another blank page and copy the shortcodes over - it also creates the same issue

**Comment by KittenCodes** [comment]
@RANSIDRAT I've not been able to replicate this behaviour. The builder and the Structure panel are both loading correctly for me on the Sandbox site.

![2021-11-26 11_41_38-NVIDIA GeForce Overlay](https://user-images.githubusercontent.com/18448481/143575750-d1b36456-a564-4823-a221-219cc2710a73.jpg)

Which browser are you using, and do you have any antivirus software installed?

**Comment by RANSIDRAT** [comment]
I have BITDEFENDER installed using chrome.exe, funnily though after your comment, I opened the website in FIREFOX and proceeded to the oxygen editor and there were no issues at all ?????????
So it appears to be an issue with chrome ?

**Comment by KittenCodes** [comment]
It's Bitdefender. Please try disabling their anti tracker feature :)
