### ISSUE TITLE
Getting current category name

### ISSUE THREAD

**Issue by Zyles** [soflyy/oxygen-bugs-and-features#2534]
**Describe the bug**

Before upgrade to Oxygen 3.8.1 I had a category template with a heading and the following:

`[oxygen data='terms' taxonomy='category']`

Which displayed the category title on that specific archive page.

Now the same code will display a list of linked categories.

What is the new command to display the current category title only with dynamic data for the heading?

1. Create a category archive template
2. Add a heading with dynamic content `[oxygen data='terms' taxonomy='category']`
3. Preview in frontend and it shows a list of category titles instead of just the viewed category title

**Comment by KittenCodes** [comment]
You need to use Insert Data > Archive Title.

**Comment by Zyles** [comment]
There is no such option.

![image](https://user-images.githubusercontent.com/1741593/143610294-b9888c68-8e36-4a95-a6f9-c1ac20e1133f.png)

**Comment by Zyles** [comment]
Ah I found the "Insert Data" in the top bar now. Maybe that was moved recently.

Another problem arises where it says "Category: Category name". I don't want this "Category:" part. Is this added by WP or Oxygen?

**Comment by Zyles** [comment]
Figured out you can use `single_term_title` function in `PHP function return value` instead.

**Comment by KittenCodes** [comment]
> Another problem arises where it says "Category: Category name". I don't want this "Category:" part. Is this added by WP or Oxygen?

This is added by WordPress. You can remove it using the following snippet in the Code Snippets plugin:

```php
add_filter( 'get_the_archive_title', function ($title) {    
	if ( is_category() ) {    
		$title = single_cat_title( '', false );    
	} elseif ( is_tag() ) {    
		$title = single_tag_title( '', false );    
	} elseif ( is_author() ) {    
		$title = '<span class="vcard">' . get_the_author() . '</span>' ;    
	} elseif ( is_tax() ) { //for custom post types
		$title = sprintf( __( '%1$s' ), single_term_title( '', false ) );
	} elseif (is_post_type_archive()) {
		$title = post_type_archive_title( '', false );
	}
	return $title;    
});
```
