### ISSUE TITLE
Structure panel doesn't allow element cascading via drag and drop (3.9, Safari)

### ISSUE THREAD

**Issue by sadrian80** [soflyy/oxygen-bugs-and-features#2538]
**Describe the bug**
Cascading of elements in the structure panel doesn't work, ie. moving H1 inside a DIV.
When a cascaded set exists in the panel, drag and drop works for that particular set.

**Video**
https://capture.dropbox.com/u3e05pezoUB6yQRN

**A link to a Sandbox site where the bug has been reproduced https://oxygenbuilder.com/try? (REQUIRED)**
http://gifted-frog.w6.wpsandbox.pro?upass=o5hI3yC4cEY7

**Comment by KittenCodes** [comment]
@sadrian80 

I've not been able to replicate this on the Sandbox site you've linked to.

Please could you let me know which operating system and browser you're using?

**Comment by sadrian80** [comment]
@KittenCodes 

Just tested, the issue persists. I'm using macOS 12.0.1, Safari 15.1.
I can also replicate it with browser stack.com, Safari 15 + 14 as well.

https://capture.dropbox.com/VEyCM8kgSsVRtkDx

Also notice, that when I grab an element at the front, I drag the SVG and not the element container.

**Comment by KittenCodes** [comment]
@sadrian80 Thank you for the video.

Unfortunately, I still can't replicate the issue - I see the SVG icon, but the element drags into place correctly.

https://www.loom.com/share/f99bc8f3b2c24d9aa4a3cd82a06376fa
