### ISSUE TITLE
Header Builder Display Issue

### ISSUE THREAD

**Issue by slewis-royal** [soflyy/oxygen-bugs-and-features#2544]
**Any bug report that doesn't include a Sandbox link or replication steps will be closed. If you can't provide these pieces of information, we're happy to help you via our official support channel instead: https://oxygenbuilder.com/support. You need to select "Something's broken and I need help" from the dropdown box on the left.**

**Describe the bug**
*When a header-builder element is set to ``display: none;`` on a larger screen size but showing on smaller sizes, the header does not render on the front end although it is visible using inspector tools.*

**A link to a Sandbox site where the bug has been reproduced https://oxygenbuilder.com/try? (REQUIRED)**

*Link: https://oxygen-q78tn4d8zmqjl.oxygen-demo.qsandbox.me/product-tour/*

*Resize the screen from larger to small and back. You will see that the original header is visible until 992px whereupon the secondary header should display on the front end but does not.*

*Also see this screenshare video https://www.loom.com/share/fa155749c3ec4ce4bbd4dfaa8db08da9 for my specific use case.*

**Comment by KittenCodes** [comment]
Hey @slewis-royal 

This is working correctly on the Sandbox site. I added a heading to the second header (that shows at 992px) so that you can see it working.

Is it doing what you want it to do, or is there something wrong with it still?

**Comment by slewis-royal** [comment]
Hi @KittenCodes , 

Yes, that is the behavior I desired. The secondary header doesn't display if there is no text ensconced in the div. I'm not quite sure why that is but that is what I have found.

Thank you for your assistance.

**Comment by KittenCodes** [comment]
@slewis-royal 

> Yes, that is the behavior I desired. The secondary header doesn't display if there is no text ensconced in the div. I'm not quite sure why that is but that is what I have found.

This is the cause for all containers (other than Sections) in Oxygen. They don't take up any space on the front-end of the site unless they have any child content, a fixed width & height set, or some padding set.
