### ISSUE TITLE
Form Builder Request

### ISSUE THREAD

**Issue by farhanmunim** [soflyy/oxygen-bugs-and-features#2549]
Ability to create and style forms, like in Webflow, with various input types and logic and with 100% control as Divs currently are. With the ability to both send forms to specified email addresses and save as a submission in the admin panel (with the ability to export form data).

**What are the use cases for this feature?**
Contact form, blog subscription form, pricing/quote form, support form etc. 

**Examples of this feature or functionality.**
Contact Form 7 and Flamingo, Fluent Forms

**Comment by elmichalos** [comment]
+1

**Comment by jontejo** [comment]
+1

I'd like to add: Integrations with all huge email marketing platforms too, multi-step forms, quizzes, etc.

**Comment by Kpudlo** [comment]
Duplicate of #477
