### ISSUE TITLE
Use HTTPS placehold.it images

### ISSUE THREAD

**Issue by rscs** [soflyy/oxygen-bugs-and-features#255]
The placehold.it images in the editor currently load over http, which breaks and/or causes warnings on sites using https.  I see that placehold.it already supports https, so this seems like a no brainer!

**Comment by rscs** [comment]
@quadcom : Yes, I never understood why images are not added with relative paths. It's so much cleaner and easier that way.  But, when moving a site, I find that I have to do a search and replace regardless to get all the guids and other things that have changed in addition to the image paths.

You bring up a completely different topic unrelated to the placehold.it topic though. You might want to create a separate feature request for the relative image paths.

**Comment by KittenCodes** [comment]
This is a feature request and not a bug. Please add a vote to the feature request here: https://github.com/soflyy/oxygen-bugs-and-features/issues/181.

**Comment by rscs** [comment]
@KittenCodes This issue got convoluted because @quadcom referenced a different topic than my original report referenced. My issue is completely **unrelated** to #181.

I am referring to the fact that the Oxygen builder internally uses placeholder images from the placehold.it site and loads them has http:// instead of https://.

**Comment by KittenCodes** [comment]
@rscs I apologise. I've opened a feature request here: https://github.com/soflyy/oxygen-bugs-and-features/issues/483
