### ISSUE TITLE
Device Selector: Selecting breakpoint shows content at just 1px more than next lower breakpoint

### ISSUE THREAD

**Issue by porg** [soflyy/oxygen-bugs-and-features#2551]
## Reproduction
- Open https://oxygen-qydwynf9ahrjl.oxygen-demo.qsandbox.me/our-customers/
- Edit in Oxygen Builder
- Select any element so that the inspector opens
- In the Device Selector select a breakpoint, i.e. "Less than 992px"

## Actual
- It shows the page at 768px, which is its minimum possible size then, just 1px above the next lower breakpoint

## Question
- Is this by design?

## Expectation
- My first gut feeling expectation was that it should show as closely as possible to the maximum of the breakpoint, so just 1px below the breakpoint, so i.e. 991px
- But I did not think deeper about it.
- I'd just like to know the reasons for this, getting an explanation, thanks.

https://user-images.githubusercontent.com/737143/144437534-6091580a-b525-41c4-95bf-37d63f8c08e9.mp4

**Comment by Spellhammer** [comment]
This is by design.

It allows you to design your layout based on the narrowest viewport width the breakpoint applies to. If you designed with 991px viewport width, it might look bad by the time it's down to 770px and before the next breakpoint kicks in.

**Comment by porg** [comment]
Makes sense. Thanks for the explanation.
