### ISSUE TITLE
Issue with Custom Script blocks into Edit mode

### ISSUE THREAD

**Issue by truptesh96** [soflyy/oxygen-bugs-and-features#2554]
* Description of the Issue *

We are using "Simple Custom CSS and JS" plugin for adding custom scripts and style snippets.

We have setup the issue on below sandbox.
https://oxygen-q8arakv8zq27.oxygen-demo.qsandbox.me/wp-admin/index.php

We have created a script block for that and include it into footer. 

https://oxygen-q8arakv8zq27.oxygen-demo.qsandbox.me/wp-admin/edit.php?post_type=custom-css-js

Script Path :
Please, refer - https://oxygen-q8arakv8zq27.oxygen-demo.qsandbox.me/wp-admin/post.php?post=45&action=edit
https://share.getcloudapp.com/5zu9Eww8

Above code working fine into front side as aspected.
https://oxygen-q8arakv8zq27.oxygen-demo.qsandbox.me/meet-the-team/
https://share.getcloudapp.com/8Lu9ArbA

But, the we are not able to get same script working on the edit mode.
Please, refer - https://oxygen-q8arakv8zq27.oxygen-demo.qsandbox.me/meet-the-team/?ct_builder=true&ct_inner=true
https://share.getcloudapp.com/JrunRgxW

Can you please let us know how can we resolve this kind of issues with custom code.

**Comment by KittenCodes** [comment]
> But, the we are not able to get same script working on the edit mode.

The code in the Simple CSS & JS plugin is set to run on the front-end of the site only. I don't see how you can run it both in the admin area and on the front-end, so I'd suggest reaching out to their support team.
