### ISSUE TITLE
Maybe Design set problem with Oxygen 2.3 RC1

### ISSUE THREAD

**Issue by wplit** [soflyy/oxygen-bugs-and-features#256]
This may not be a problem, but i'm flagging it just incase.

I noticed that once I updated the install that was acting as the source site for a design kit from beta to 2.3 RC1. All other sites were unable to access that design kit, even after regenerating the access keys. It wasn't until I updated them all to RC1 that I was able to again use the design kits.

It's probably because you changed something with how the design kits work. But I thought i'd flag it incase it's something else. Ideally we don't want it to be that you must be on the same version of Oxygen as the source site to be able to access a kit.

**Comment by Spellhammer** [comment]
We did make some security changes to the User Design Library between Beta and RC, I suspect that's what caused the reported problem.
