### ISSUE TITLE
oxygen edit error

### ISSUE THREAD

**Issue by neverbackdown0306** [soflyy/oxygen-bugs-and-features#2561]
**Any bug report that doesn't include a Sandbox link or replication steps will be closed. If you can't provide these pieces of information, we're happy to help you via our official support channel instead: https://oxygenbuilder.com/support. You need to select "Something's broken and I need help" from the dropdown box on the left.**

**Describe the bug**
*A clear and concise description of what the bug is.*

**A link to a Sandbox site where the bug has been reproduced https://oxygenbuilder.com/try? (REQUIRED)**
*Provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*

**IF YOU CAN'T PROVIDE A SANDBOX REPRODUCTION: Steps required to reproduce the bug:**
1. just upload the [new_short.zip](https://github.com/soflyy/oxygen-bugs-and-features/files/7673872/new_short.zip)
2. and try to open edit page in oxygen 

**If you can't fill out the above information, you should not be filing a bug report. Instead, contact us via https://oxygenbuilder.com/support with the details you have and we'll investigate your issue further.**

**Comment by KittenCodes** [comment]
@neverbackdown0306 

Your plugin is missing the closing PHP tag. Please add it.

**Comment by neverbackdown0306** [comment]
<img width="933" alt="image" src="https://user-images.githubusercontent.com/95738203/145334566-487b7ca2-4034-4e8e-ad3e-b5583d6d0b47.png">
i have added PHP closing Oxygen edit in not openings.

**Comment by neverbackdown0306** [comment]
<img width="950" alt="image" src="https://user-images.githubusercontent.com/95738203/145334694-5060b0e2-09a3-4a95-b127-c9baea076e25.png">
this is my staging site this occurs on oxygen edit when i use shortcode in my plugin

**Comment by neverbackdown0306** [comment]
@KittenCodes i have resolve it by my self . basically i have found  a bug in oxygen.  oxygen builder  can't render its edit page if  their are White Spaces in our plugin code. so this is the one thing that oxygen should work on in the future
Thank you
