### ISSUE TITLE
Feature for sort out unused selectors

### ISSUE THREAD

**Issue by fredlim** [soflyy/oxygen-bugs-and-features#2570]
**Describe the feature you'd like to see included in Oxygen.**
It is very convenient to add class in elements, but delete selector, I must switch to the Manage panel. not convenient and could leave unused selectors as time move on.
I think it is better to add an "Unused" section in the Selectors panel inside Oxygen editor to list all unused selectors.
Or add an Unused Selectors panel separately.

**Comment by Kpudlo** [comment]
Closing as duplicate of https://github.com/soflyy/oxygen-bugs-and-features/issues/2648
