### ISSUE TITLE
Enhancement Roadmap

### ISSUE THREAD

**Issue by switchupcb** [soflyy/oxygen-bugs-and-features#2572]
**Describe the feature you'd like to see included in Oxygen.**
A roadmap for enhancements would be beneficial for users to understand the status of certain issues. This would prevent duplicate issues and assurance to potential customers that new features are being added/issues dealt with.

**What are the use cases for this feature?**
Here were a list of issues I encountered while using Oxygen to update a website.
| Issue | Reason |
|--|--|
| https://github.com/soflyy/oxygen-bugs-and-features/issues/485 | Mobile Menus require close animation rather than fade **(from 2019; 52 likes)**. |
| https://github.com/soflyy/oxygen-bugs-and-features/issues/1833 | Dropdown Menus ('sub-menu') lack customization options (i.e borders, hover states) and requiring CSS stylesheet code.
| https://github.com/soflyy/oxygen-bugs-and-features/issues/2219 | Read time (as dynamic data or field) is important to blogs for retention. An example of a read-time implementation in Oxygen is shown here: https://github.com/Widdin/wp_oxygen
| https://github.com/soflyy/oxygen-bugs-and-features/issues/2492, https://github.com/soflyy/oxygen-bugs-and-features/issues/315 | When an element is wrapped it messes with inheritance properties which can cause weird activity. There is no way to unwrap a code block and dynamic data is wrapped automatically. One solution is to give elements such as code blocks a **wrap** option.
| https://github.com/soflyy/oxygen-bugs-and-features/issues/537 | Cart Counters and Mini Carts assist with UX on eCommerce stores. Multiple examples can be found such as [Bruce Young](https://youtu.be/9eSTOilqWb4), [Widdin WooCommerce Mini-Cart Sidebar](https://gist.github.com/Widdin/99d9064e812fe596d9a6fe5edc9a8431), [Widdin WooCommerce Cart Counter AJAX](https://gist.github.com/Widdin/978f290f3ba93c499aad0d2a1aeb0e48)
| https://github.com/soflyy/oxygen-bugs-and-features/issues?q=is%3Aissue+is%3Aopen+accessibility | Accessibility is important and you may be limiting the amount of money you will make by not fixing it.

I made this issue because there is no guarantee (or proof) that a reaction will give them more priority.

**Examples of this feature or functionality.**
It can be as simple as another text file: Implement a **Queue** and **NOT ESTIMATED DATES**.

**Comment by madjedo** [comment]
+1 A roadmap is very much needed. At least some sort of short-term roadmap, where they announce plans for next update. I think this would be beneficial to Oxygen team aswell as users could be submitting requests and improvement features much earlier in the dev. cycle for the particular planned enhancements.
