### ISSUE TITLE
Duplication results in Duplicate Child Element IDs

### ISSUE THREAD

**Issue by switchupcb** [soflyy/oxygen-bugs-and-features#2574]
**Describe the bug**
Whenever you copy an element with child elements (i.e Repeater, Page Builder, Divs), it seems that its child elements are also the same. I've only experienced this on 3.9.

1. Go to an existing template and duplicate a repeater/div/etc.

This may be an issue with the way Oxygen interacts with external caches.

**Comment by KittenCodes** [comment]
@switchupcb Are you saying that the actual ID is duplicated when you check the markup on the front-end of the site, or the name in the Structure panel is duplicated?

**Comment by switchupcb** [comment]
@KittenCodes Both.

**Comment by KittenCodes** [comment]
@switchupcb Thanks for confirming.

The nicename in the Structure panel will be duplicated when an element is duplicated, but it should have a unique ID in the markup.

I've not been able to replicate a duplicate ID - are you able to replicate this on our Sandbox site? You can create one here: https://oxygenbuilder.com/try.

**Comment by switchupcb** [comment]
It was simply a rather obscure cache issue. The duplicate works as intended (as you stated). Thanks!
