### ISSUE TITLE
Renaming an element in the structure panel with a name containing an apostrophe makes this element disapear from the front end

### ISSUE THREAD

**Issue by cbontems** [soflyy/oxygen-bugs-and-features#2583]
**Any bug report that doesn't include a Sandbox link or replication steps will be closed. If you can't provide these pieces of information, we're happy to help you via our official support channel instead: https://oxygenbuilder.com/support. You need to select "Something's broken and I need help" from the dropdown box on the left.**

**Describe the bug**
Renaming an element in the structure panel with a name containing an apostrophe makes this element disapear from the front end

**A link to a Sandbox site where the bug has been reproduced https://oxygenbuilder.com/try? (REQUIRED)**
http://stormy-toucan.w6.wpsandbox.pro?upass=2RPzNv64t9yG

**IF YOU CAN'T PROVIDE A SANDBOX REPRODUCTION: Steps required to reproduce the bug:**
1. Go to the structure panel
2. Click on the pencil icon to rename an element
3. input a name containing an apostrophe
4. Save
5. Check front-end. The renamed element has disapeared

**Comment by KittenCodes** [comment]
Duplicate: https://github.com/soflyy/oxygen-bugs-and-features/issues/2550
