### ISSUE TITLE
TikTok Social icon?

### ISSUE THREAD

**Issue by ecology-rocks** [soflyy/oxygen-bugs-and-features#2584]
**Describe the feature you'd like to see included in Oxygen.**
*A clear, detailed description of the feature you're requesting.*
The social icons are a bit too general. I'd love to either be able to customize them easily, or if y'all would add TikTok and Pinterest to the list. Or share how to do it myself.

**What are the use cases for this feature?**
*e.g. Accessibility, e-commerce store that sells bicycles, etc.*
More social sharing!

**Examples of this feature or functionality.**
*If another product has done it well, provide examples here.*

**Comment by KittenCodes** [comment]
Duplicate: https://github.com/soflyy/oxygen-bugs-and-features/issues/234
