### ISSUE TITLE
H1 backgrounds shows inverted 

### ISSUE THREAD

**Issue by Janvier7** [soflyy/oxygen-bugs-and-features#2585]
Hi:

I'm using a dynamic  h1 text with a gradient linear background inside of a repeater.
The gradient shows inverted in the page of oxygen editor, but good in the frontend.

User:
admin

Password:
adminiStrong0

Frontpage:
https://oxygen-q8nmw838mj2jl.oxygen-demo.qsandbox.me/

Edit template page:
https://oxygen-q8nmw838mj2jl.oxygen-demo.qsandbox.me/ui-kit/?ct_builder=true&ct_inner=true

**Comment by sk209** [comment]
You can set it to 180 degrees to fix this
<img width="225" alt="image" src="https://user-images.githubusercontent.com/54979934/146991991-6c5928b8-48e8-48b3-87f7-10857793bc8d.png">

The gradient is set by default to 0 degrees in the editor, which seems to be outputting two different CSS styles

In Editor:
background-image: linear-gradient(0deg, rgba(0,0,0,0) 6%, #000000 92%);

In front-end (it seems to ignore the 0 set in the editor):
background-image: linear-gradient(rgba(0,0,0,0) 6%,#000000 92%);

**Comment by Janvier7** [comment]
Thank you, I will do that.
    That was a bug?
    
      
      body p {color:#3a3a3a; font-family: Arial, Helvetica, sans-serif; font-size:15px; line-height:18px; margin:6px 0 20px 8px;}

      Greetings,
      Javier
          
        
      
    
    
      
      El 21-12-2021 a las 17:16, sk209 escribió:
    
    
      
      You can set it to 180 degrees to fix this
        
      The gradient is set by default to 0 degrees in the
        editor, which seems to be outputting two different CSS styles
      In Editor:
        background-image: linear-gradient(0deg, rgba(0,0,0,0) 6%, #0
        92%);
      In front-end (it seems to ignore the 0 set in the
        editor):
        background-image: linear-gradient(rgba(0,0,0,0) 6%,#0 92%);
      —
        Reply to this email directly, view it on GitHub, or unsubscribe.
        Triage notifications on the go with GitHub Mobile for iOS or Android.
        
        You are receiving this because you authored the thread.Message
          ID: ***@***.***>
      [
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/soflyy/oxygen-bugs-and-features/issues/2585#issuecomment-999066324",
"url": "https://github.com/soflyy/oxygen-bugs-and-features/issues/2585#issuecomment-999066324",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by sk209** [comment]
Yes, it is a bug, because if you input 0 degrees in the Oxygen editor, it doesn't reflect in the CSS on the front-end. We have to enter it as '00' degrees for it to work.

CSS output in frontend when setting 0 degrees in editor:
`background-image: linear-gradient(rgba(0,0,0,0) 6%,#0 92%); 
`//No degree value output, so it will be rendered as 180 degree even though its set as 0 degree in the backend

CSS output in frontend when setting 00 degrees in editor:
`background-image: linear-gradient(00deg, rgba(0,0,0,0) 6%, #0 92%);
`

Similar to [#881](https://github.com/soflyy/oxygen-bugs-and-features/issues/881)

**Comment by Janvier7** [comment]
Thank you!
