### ISSUE TITLE
Repeater pagination not work

### ISSUE THREAD

**Issue by Janvier7** [soflyy/oxygen-bugs-and-features#2586]
Hi again:

- The repeater pagination is not working. The second page link shows the same results of the main page.

- When the repeater query option is setting to 4 post per page, the div class .oxy-repeater-pages-wrap disappears so there is not pagination on frontpage.

Frontpage:
https://oxygen-q8nmw838mj2jl.oxygen-demo.qsandbox.me/

Edit frontpage:
https://oxygen-q8nmw838mj2jl.oxygen-demo.qsandbox.me/?ct_builder=true

admin
adminiStrong0

Thanks.

**Comment by KittenCodes** [comment]
@Janvier7 This is a known issue with pagination on static home pages. To resolve it, please add a Code Block element just above the Repeater and add the following code to the PHP & HTML tab:

```php
<?php

	if ( get_query_var('paged') ) { 
		$paged = get_query_var('paged'); 
	} elseif ( get_query_var('page') ) { 
		$paged = get_query_var('page'); 
	} else { 
		$paged = 1; 
	}

	query_posts('posts_per_page=2&paged=' . $paged); 

?>
```

You will need to replace the "2" with the number of posts what you're showing on each page.

**Comment by Janvier7** [comment]
Thanks!
