### ISSUE TITLE
Flexbox Child Controls: invalid options (left/right) for Align Self - there is no "left/right" in flexbox

### ISSUE THREAD

**Issue by ddenev** [soflyy/oxygen-bugs-and-features#259]
**Describe the bug**
In the "Align Self" option group for Flexbox Child Controls there are two options that do not exist in CSS - Left and Right.
![image](https://user-images.githubusercontent.com/1393766/56831076-df179000-6870-11e9-93cf-2d463add8125.png)

When used these generate the following invalid CSS:
`align-self: left` and `aligh-self: right`
![image](https://user-images.githubusercontent.com/1393766/56831148-0e2e0180-6871-11e9-899e-84e302717ba8.png)

**Expected behavior**
"left" should most probably be renamed to "flex-start" and "right" - to "flex-end"

For reference: https://developer.mozilla.org/en-US/docs/Web/CSS/align-self

Why is this important:
When there is a flex section (with `flex-direction: column` and `align-items: center`) and there are some items in the section that need to be horizontally aligned differently than the default (e.g. to the left or to the right).

**Comment by guyinpv** [comment]
This is not low priority! lol Using align-self is quite common and the tool is outputting invalid CSS. I just wasted about an hour figuring out why this wasn't working!

**Comment by drank** [comment]
This bug is still not resolved in the 3.1 beta 1 bugfix release.

**Comment by yankiara** [comment]
Low priority, really??? For me this is a serious and ridiculous issue.

Well, I know there's custom CSS to get around this, but what the hell, it sould take 30s to fix this and a few minutes to test in different configurations, which must have never happened before, obviously.

**Comment by sunnyt7** [comment]
+ for getting this resolved. It's still a bug.

**Comment by Takkster** [comment]
Seems I don't need to make a bug report, please fix this ASAP, it is a common option and should simply work!

**Comment by Takkster** [comment]
Made a small demo in the sandbox:
https://oxygen-q5npmwps9y57k.oxygen-demo.qsandbox.me/flex-child-controls

**Comment by ruyfialho** [comment]
Common guys. This one is so simple to fix. Please replace the two wrong values (left and right)   for flex-start and flex-end respectively in Align Self.
Then change that in the tutorial:
https://oxygenbuilder.com/documentation/styling-options/layout/

**Comment by yankiara** [comment]
Am I dreaming or this stupid bug is almost one year old???

**Comment by ruyfialho** [comment]
It is unbelievably true. I guess It will be better if we send to him (Louis Reingold) a simple email, by the way I just did it using the support page https://oxygenbuilder.com/support/ or support@oxygenbuilder.com

**Comment by alriksson** [comment]
You also have the issue or an improvement to add. You have to set a new position or display value for each viewport, even if you just want to change `flex-direction: column;` on smaller devices.
While it this does inherit from the main viewport. Just extra code which isn't needed.

**Comment by jmcbade** [comment]
+1 for getting this one resolved

**Comment by alexanderkladov** [comment]
This bug is still alive & kicking, after a whole year. This is crazy. And all it takes to fix this is literally 2 lines of code.

Just change lines 249 & 251 in `/oxygen/component-framework/toolbar/views/layout.view.php` from `left` to `flex-start` & from `right` to `flex-end`.

Not sure why this is taking a year to fix. Makes me worried that Oxygen is slowly dying.. We seem to be waiting longer and longer for new releases.

**Comment by clockwood** [comment]
Please fix this!

**Comment by guyinpv** [comment]
Are they accepting pull requests? Can someone just submit the PR and hopefully get this done?

**Comment by Astwert** [comment]
With version 3.5 the bug is still there. What the problem guys?

**Comment by andreslotta** [comment]
Okay guys. I really love Oxygen and you are making a fabulous job regarding regular updates, new features and a recent release fixing many annoying bugs. But... What can we do to push bugs like this one to the top of the "to be fixed"-list? It might not be the most serious bug and of course there are workarounds. But on the other hand – as @alexanderkladov already mentioned – it's a two liner with no real testing needed. I really hope to see it fixed soon...

Thanks for your great product and effort!

**Comment by petermakeswebsites** [comment]
Please fix this ...

**Comment by devisuelekant** [comment]
What's going on with this one?

To be honest, my general feeling with oxygen is that they constantly prioritize introducing new features over fixes or much needed improvements of the most basic functionality. Maybe they should make someone explicitly responsible for less eye catching updates and fixes..

**Comment by clockwood** [comment]
> To be honest, my general feeling with oxygen is that they constantly prioritize introducing new features over fixes or much needed improvements of the most basic functionality. Maybe they should make someone explicitly responsible for less eye catching updates and fixes..

This is exactly what happened with Divi and is what drove me to give Oxygen a try.

**Comment by luisceladita** [comment]
2 years old and still the problem persists, come on!

**Comment by KittenCodes** [comment]
Fixed in v3.8 Beta 1.
