### ISSUE TITLE
Exit intent popup not working on mobile and ipad

### ISSUE THREAD

**Issue by rab008** [soflyy/oxygen-bugs-and-features#2590]
I have exit intent popup working great on desktop, the issue is that the popup not working on ipad and mobile devices.

**Comment by KittenCodes** [comment]
@rab008 This isn't a bug. If you would like Oxygen's Modal to support exit intent on mobile devices, please add a vote to the feature request here: https://github.com/soflyy/oxygen-bugs-and-features/issues/1977.
