### ISSUE TITLE
Content of SPAN disappear when converted to link

### ISSUE THREAD

**Issue by KonradDeskiewicz** [soflyy/oxygen-bugs-and-features#2591]
**Describe the bug**
Creating SPAN inside text element and then converting it to link cause SPAN content to disappear. You need to save and reload the editor for this element to become visible.

**IF YOU CAN'T PROVIDE A SANDBOX REPRODUCTION: Steps required to reproduce the bug:**
1. Create a text element with some text in it.
2. Mark some text and click the `<SPAN>` button.
3. Once the text is in a separate span click the `link` button to convert it to a link.
4. All link configuration is available but the text itself disappear.
5. Save your work.
6. Reload Editor (`F5`). Text in span is visible again 

Before creating a link:
![image](https://user-images.githubusercontent.com/17060750/147230753-47e3af47-e668-4d3b-8667-b145c37e8aff.png)

After creating a link:
![image](https://user-images.githubusercontent.com/17060750/147230816-34db08b2-3913-4969-ac30-b1ae8101c60a.png)

After editor reload:
![image](https://user-images.githubusercontent.com/17060750/147230932-5b53e7dc-f4af-4a38-a169-c5d221ae325d.png)

**Comment by KittenCodes** [comment]
@KonradDeskiewicz I've not been able to replicate this. Please could you let me know which browser and operating system you're using?

**Comment by KonradDeskiewicz** [comment]
@KittenCodes I've tested it on Chrome and Brave, Win 10. Both have the issue. Tested on Firefox - No issue. It looks that it's chromium engine related issue.

**Comment by KonradDeskiewicz** [comment]
Hi,

Please find a screen grab of an issue:
https://www.loom.com/share/d784d58b29b84c8891dc5fd4fd3da5f1

**Comment by KonradDeskiewicz** [comment]
@KittenCodes any update on this one?

**Comment by KittenCodes** [comment]
@KonradDeskiewicz I apologise for the delay in replying to you.

Here's what I see when I follow the same steps: https://www.loom.com/share/836b48baf2be4d499002831d8a77b033.

Just checking, which version of Oxygen are you using? I was using v3.9.

**Comment by KonradDeskiewicz** [comment]
yes. That was 3.9 on your `/try` env. Strange :) Anyway. Maybe one day I could find a real source of this behavior :)

**Comment by KittenCodes** [comment]
Interesting! Do you have add-ons in your Chromium browsers? If you do, could you try an incognito window please?
