### ISSUE TITLE
Error 4.0 Alpha (shortcodes)

### ISSUE THREAD

**Issue by astacreative** [soflyy/oxygen-bugs-and-features#2596]
Shortcodes not working in frontend:

Warning: strpos() expects parameter 1 to be string, array given in on line 209
/home/u39485p34917/domains/xxx.dev/public_html/xxx/wp-includes/shortcodes.php

Warning: : preg_match_all() expects parameter 2 to be string, array given in on line 218

Warning: array_intersect(): Expected parameter 2 to be an array, null given in on line 219

**Comment by Bebuk85** [comment]
Same situation here, shortcodes not working in the front end

**Comment by KittenCodes** [comment]
Thank you for letting us know. This will be fixed in v4 Alpha 2.

**Comment by steveninety** [comment]
Got the same 3 warnings in Beta 2. Shortcodes (oxyextras carousel) not working.
