### ISSUE TITLE
Dissapearing values in border

### ISSUE THREAD

**Issue by GeneralUniverse** [soflyy/oxygen-bugs-and-features#2597]
If you add values to the border property and change to the different viewport, the values doesn't show there and also it doesn't show when you get back to the original viewport. The styling is applied but I can't see it in the Oxygen sidebar so I have no idea how is the styling set.

**Comment by adrien-robert** [comment]
+1

**Comment by jmcbade** [comment]
I concur - I am seeing this also.  I also set a border in the editor and can see it, but when the template is rendered, not border on an element.

**Comment by KittenCodes** [comment]
This is fixed in v4 Beta 1.
