### ISSUE TITLE
Horizontal Scroll Bar Problem in Builder

### ISSUE THREAD

**Issue by wplit** [soflyy/oxygen-bugs-and-features#26]
**Describe the bug**
When in the builder, working in any device width that makes the rules appear at the bottom of page. When I try to use the ruler to view the site at different widths, a horizontal scroll bar appears over the top of the ruler, making it very difficult to use.

**To Reproduce**
It does the same on the sandbox Oxygen. It's due to the ruler's width being calculated wrong by 6px (not taking into account the 6px margin on the iframe) so we get a horizontal scroll bar that pops up just as we're trying to use the ruler.

**Screenshots**
Screen recording - https://www.useloom.com/share/b821373287524b7182e041083a9289d1

**Desktop (please complete the following information):**
- Mac OS: [e.g. iOS]
 - Chrome
 - Oxygen Version 2.1.2 & 2.2 alpha

**Comment by Spellhammer** [comment]
Can no longer replicate in Oxygen 3.6. Please reply if you're still encountering this in Oxygen 3.6 or later.
