### ISSUE TITLE
Oxygen WooCommerce 2.0 Alpha 1 - missing mini-cart.svg

### ISSUE THREAD

**Issue by dev-null-at** [soflyy/oxygen-bugs-and-features#2605]
Download package for Oxygen WooCommerce 2.0 Alpha 1 does not contain mini-cart.svg for the toolbar.

![image](https://user-images.githubusercontent.com/64080278/147514179-c1b1a31a-f07d-4314-9a89-4ca62127a79f.png)

**Comment by Spellhammer** [comment]
The icon will be added in the beta. Thanks for the report.
