### ISSUE TITLE
DONE: Link Target or lack of link target......and a rant.

### ISSUE THREAD

**Issue by quadcom** [soflyy/oxygen-bugs-and-features#261]
I can't believe that I have to bring this up, again.

Specifying the target a link has was requested September 24, 2018. This is basic functionality. That it hasn't been added in yet is really starting to make me question the validity of Oxygen Builder. Yes, I did see a post on how to add attributes to elements. But come on! Adding a Jscipt to the site and assigning custom classes all to provide functionality that should have been there in the conception stage is not a solution.

I like the road you guys are on with keeping things light and fast but the amount of stupid bugs in the system and the lack of basic functionality is really unbecoming and evidence that this is not ready for prime time yet. Keep in mind, your paying customers are using this builder to create LIVE sites. Not development test sites. The kind and amount of bugs in the system currently are NOT acceptable and I don't think I am alone in my view here. In my view, stop charging people for this, pull back to a beta stage and find external funding to continue development.

Within 1 day of using the builder, I've filed 4 bugs just myself but the amount of time it takes to gather the required examples is taking time out of building client projects. 

As I said, you guys are on the right track but the execution needs to step up.

**Comment by KittenCodes** [comment]
This has been added.

**Comment by quadcom** [comment]
Thanks very much
