### ISSUE TITLE
DONE: Option to change CSS defaults in global settings

### ISSUE THREAD

**Issue by wplit** [soflyy/oxygen-bugs-and-features#262]
**Describe the feature you'd like to see included in Oxygen.**
To be able to change some CSS defaults that already exist in oxygen.css. Notably the padding that is given to all the column divs.

**What are the use cases for this feature?**
The main example is the padding automatically given to all columns of 20px. This makes the sites that use columns (or anybody using elements from the current design sets) auto conform to a grid that has gaps of 40px, (whether they're aware of it or not)

See part of the Atomic demo for eg..

<img width=600 src="https://i.ibb.co/FDYNfSZ/grid.png">

Here you can see the 40px 'grid gap' shown above, the problem is that for sites that only have a page width of say 1140px, which actually the Oxygen demo's do by default, then 40px is too much gap and is nearly matching the width of the columns themselves.. (shown below)

<img width=600 src="https://i.ibb.co/BG4V4Tz/gridsmall.png">

for eg; 30px is much more common from designers. Webflow uses 30px in their guidelines, bootstrap has a grid gap set to 30px. I haven't checked what elementor has. Being able to change this (by adjusting the column padding globally), along side being able to change the page width will allow us to follow any grid we like. Much more flexible.

For those of us who need to build out an existing design that needs to be px perfect and already follows a different grid structure, having these options built in would be ideal.

My suggestion is that you add an option next to where we set global page width etc, to change the default.

Note; obviously we can just add custom CSS to override. My main use case is when distributing design sets, if we want to follow a more traditional grid layout, where 30px makes more sense and looks neater. We can also obv just avoid using columns and add our own flex layout that gives us what we want, but columns give users have a more intuitive way of customising the design, without having to dive into all the flex settings on every layout.

**Comment by jamescrabb** [comment]
I think this needs to be addressed.

If i need to assign a class to the divs inside columns to control the padding I can't i have to use the ids and do it on each div individually

Great pain in the arse

**Comment by SlmnAntnll** [comment]
Any ideas to when we'll be able to set these types of global defaults?

Thanks.

**Comment by anartfulscience** [comment]
I was just researching this whilst thinking of buying. Most web designers (inc myself) work tightly to a grid structure and being able to set these defaults, including an overlay to ensure the layout is 100% would sell it for me!

**Comment by artjomzab** [comment]
Especially on mobile 40px padding is a lot.

**Comment by pascalinger** [comment]
I would totally support this! I would love some more global styling love. In this case for column paddings. Because the padding of 20px is actually added to all columns automatically, and the only way to override this is with either using !important in a class or changing it for every goddamn column.

**Comment by swinggraphics** [comment]
> To be able to change some CSS defaults that already exist in oxygen.css.

It should be easier to edit ALL the defaults for inbuilt elements. This saves us having to duplicate rules in order to override them, or having to change the styles of _every_single_element_ as we add them. (e.g., Superbox, Testimonial, Modal, Toggle………)

**Comment by Spellhammer** [comment]
We've implemented the ability to set the default padding for column divs.
