### ISSUE TITLE
4.0 Alpha 1 - Shortcode wrapper breaks front-end.

### ISSUE THREAD

**Issue by madjedo** [soflyy/oxygen-bugs-and-features#2624]
Example:

Using the shortcode to hide email address from spambots:

[oxygen ct_sign_sha256='6ea823579b02f9d573b655af9b9b98f32f7a8261b578c36f2ecab3c279e8fb8d' data='phpfunction' function='antispambot' arguments='youremail@host.com' ]

Breaks the div with lots and lots of fun php errors and warnings.

**Comment by KittenCodes** [comment]
@madjedo Would you mind sending me the PHP function code that you're using with this please?

**Comment by madjedo** [comment]
@KittenCodes Hi, the function "antispambot" is standard included with WordPress.

Documentation:

https://developer.wordpress.org/reference/functions/antispambot/

**Comment by KittenCodes** [comment]
@madjedo 

> the function "antispambot" is standard included with WordPress

Perfect, thanks! I hadn't realised it was a WP function.

What do you have inside the Shortcode wrapper?

**Comment by madjedo** [comment]
Sorry, I had a troublesome setup with a Link wrapper wrapping a shortcode wrapper wrapping a shortcode haha.

But still, if I set it up correctly following documentation here:

https://oxywp.com/how-to-hide-email-address-from-spam-bots-in-oxygen/

It still won't work. But no more errors atleast. Just not displaying on front-end.

So it is Link wrapper > Shortcode.

**Comment by KittenCodes** [comment]
@madjedo 

Please try using a Text Link or Button element (no Link Wrapper or Shortcode element).

I've done this here in v4 Alpha 1 and it's working as expected: https://oxygen-qr4ml7wvs9akl.oxygen-demo.qsandbox.me/about-me/.

You're welcome to log in and take a look, the username and password are both demo.

As an aside, there are some Shortcode and Shortcode Wrapper issues in v4 Alpha 1 that we are addressing.
