### ISSUE TITLE
Copy-Paste support cross-site

### ISSUE THREAD

**Issue by karchung0930** [soflyy/oxygen-bugs-and-features#2627]
So far the copy-paste features of 4.0 only work within the same website, can you please make it to support cross-site where we can do it from one to another website.

**Comment by shibupandit** [comment]
Yes I agree

**Comment by jornessim** [comment]
Agree.

**Comment by itcomindo** [comment]
up up up

**Comment by jdemailas** [comment]
Yes please

**Comment by drewcifer7840** [comment]
It would probably hurt some 3rd party devs like Hydrogen, etc. I now have that feature with the great Swiss Knife plugin, I think it only makes sense to include it but for the "turf battle politics" of which I know nothing of, LOL. Heck, even Gutenberg has cross-site copy/paste figured out.

**Comment by karchung0930** [comment]
> It would probably hurt some 3rd party devs like Hydrogen, etc. I now have that feature with the great Swiss Knife plugin, I think it only makes sense to include it but for the "turf battle politics" of which I know nothing of, LOL. Heck, even Gutenberg has cross-site copy/paste figured out.

Hydrogen Pack is a great plugin but it actually increase the cost of us /user who are new and just join Oxygen Builder.

We should consider the benefits of the whole community in long term, this is requested a long time ago like about years and it should be a native feature.

**Comment by jornessim** [comment]
> > It would probably hurt some 3rd party devs like Hydrogen, etc. I now have that feature with the great Swiss Knife plugin, I think it only makes sense to include it but for the "turf battle politics" of which I know nothing of, LOL. Heck, even Gutenberg has cross-site copy/paste figured out.
> 
> Hydrogen Pack is a great plugin but it actually increase the cost of us /users who are new and just joined Oxygen Builder.
> 
> We should consider the benefits of the whole community in long term, this is requested a long time ago like about years and it should be a native feature.

I totally agree with you. 
This feature shouldn't be provided by 3rd party but is available natively.
No point in spending money on a basic feature that should be provided by its core.

**Comment by naydenoff** [comment]
Up

**Comment by deftcreative** [comment]
Up up up. My workflow relies on pasting text dumps of pre-made sections from a base library of elements.

Failing cross-site pasting, maybe the ability to switch off Oxygen native shortcuts and continue using Hydrogen or others for this (which does allow cross site pasting)

**Comment by HesterSchoeman** [comment]
+1

**Comment by samste** [comment]
+1

**Comment by loupaok** [comment]
+1

**Comment by brucdesign** [comment]
That would speed up my workflow. I would even pay extra for this. I rather get it from Soulfly than buy another addon.

**Comment by Crey100** [comment]
I don't use the Oxy add-ons so I would really like this.

**Comment by ELEPIX** [comment]
This would be incredibly helpful. Especially when working from staging sites that you want to push to different live sites.

**Comment by sw7589** [comment]
> It would probably hurt some 3rd party devs like Hydrogen, etc. I now have that feature with the great Swiss Knife plugin, I think it only makes sense to include it but for the "turf battle politics" of which I know nothing of, LOL. Heck, even Gutenberg has cross-site copy/paste figured out.

f em

**Comment by Spellhammer** [comment]
Added in 4.1 alpha 1.
