### ISSUE TITLE
Issue with Search&Filter Plugin

### ISSUE THREAD

**Issue by albertso** [soflyy/oxygen-bugs-and-features#263]
I'm trying to implement a similar feature to what is demonstrated on this Oxygen tutorial
["Building a Car Dealership Website with FacetWP"](https://www.youtube.com/watch?v=WEpSwRehdWQ)

I'm using [Search and Filter](https://es.wordpress.org/plugins/search-filter/) plugin, an alternative to FacetWP.

The searchandfilter shortcode displays the form correctly in Oxygen, but when clicking on submit it reloads the same page instead of using the search parameters sent by POST method.

This works fine when deactivating Oxygen.

¿How can we make them work together?

**Comment by KittenCodes** [comment]
@albertso, Please contact Search & Filter support to see if they can identify what's going wrong when using the search on an Oxygen page. If the problem is with Oxygen, they should be able to provide some guidance based on how their plugin works as to what Oxygen's doing to break it.

**Comment by adrien-robert** [comment]
@albertso Did you found a solution?
