### ISSUE TITLE
Arabic chars

### ISSUE THREAD

**Issue by mohammadsobhy** [soflyy/oxygen-bugs-and-features#2632]
Hello when i am using oxygen ver 4 alpha inside the builder the chars of arabic showing right but in the front end special chars .. please support rtl langs in this version i wish

**Comment by habj89** [comment]
Same problem for nordic/scandinavian chars. Æ, ø and å is showing normal in the builder, but not when loading up the page in a browser. Tested with edge, brave and firefox.

This is only happening with chars from repeater elements for me. Normal heading and text is normal.

**Comment by Spellhammer** [comment]
Reproduced and fixed internally for the next release in the 4.0 cycle. Thanks for the report.
