### ISSUE TITLE
Inbuild simple features or elements needs to b added like tootip, popup, lightbox, carousel, form, animation rendering

### ISSUE THREAD

**Issue by shibupandit** [soflyy/oxygen-bugs-and-features#2633]
**Describe the feature you'd like to see included in Oxygen.**
*A clear, detailed description of the feature you're requesting.*

**What are the use cases for this feature?**
*e.g. Accessibility, e-commerce store that sells bicycles, etc.*

**Examples of this feature or functionality.**
*If another product has done it well, provide examples here.*

**Comment by Spellhammer** [comment]
Closing. No details provided. Please re-open a new feature request with some use cases, examples, or details.
