### ISSUE TITLE
Critical error Tanslatepress and Oxygen 4.0 Alpha 1

### ISSUE THREAD

**Issue by Karyo97** [soflyy/oxygen-bugs-and-features#2640]
Hello there,

I've installed Oxygen 4.0 alpha 1  and had a critical error message with a white screen activating Translatepress plugin Version 2.1.8 . 
Another try with Oxygen 3.9 was fine. 

Here is the sandbox site : https://oxygen-q3hdw3zadx6jl.oxygen-demo.qsandbox.me/sample-page/
and the website of the mentionned plugin : https://translatepress.com/

Regards

**Comment by KittenCodes** [comment]
@Karyo97 This is something that TranslatePress will need to address as the error comes from their plugin. Here's the errors:

Fatal error: Uncaught ArgumentCountError: Too few arguments to function tp_oxygen_search_compatibility(), 2 passed in \wp-includes\class-wp-hook.php on line 303 and exactly 4 expected in \wp-content\plugins\translatepress-multilingual\includes\compatibility-functions.php on line 792.

ArgumentCountError: Too few arguments to function tp_oxygen_search_compatibility(), 2 passed in \wp-includes\class-wp-hook.php on line 303 and exactly 4 expected in \wp-content\plugins\translatepress-multilingual\includes\compatibility-functions.php on line 792.

I hope this helps!
