### ISSUE TITLE
When deleting columns, they stay and break.

### ISSUE THREAD

**Issue by QuirkyRobots** [soflyy/oxygen-bugs-and-features#2643]
When I delete columns, they stay, but break the layout. If I undo, it can sometimes self correct.
The arrows point to each column (Status Box) that has been deleted, but remained in a broken position.

![image](https://user-images.githubusercontent.com/29914179/147819582-ab9332e2-2b35-433c-94e8-81f0e2de7067.png)

**Comment by KittenCodes** [comment]
Thanks for reporting this. Issue replicated and logged internally.

**Comment by Kpudlo** [comment]
This was fixed in Oxygen 4.0 Beta 1 but never closed.
