### ISSUE TITLE
Oxygen builder does not load on subpages

### ISSUE THREAD

**Issue by Mike-71** [soflyy/oxygen-bugs-and-features#2644]
Unfortunately, the builder does not load on sub-pages (level 2) but issues the following error message:

**Oxygen encountered a 404 error while loading the builder.
Please re-save your permalinks under Settings> Permalinks in the WordPress admin panel.
Go to Settings> Permalinks**

The permalinks were saved several times in the settings.
If I move the subpage so that it no longer has a main page, i.e. level 1, then the builder works or loads.

**Comment by Spellhammer** [comment]
Can you please elaborate on what you mean by sub-pages? Are these pages that have been set as the child of another page?

**Comment by Mike-71** [comment]
Exakt!

**Comment by Mike-71** [comment]
To rule out that it is a Wordpress problem, I deactivated the plugins and tested an identical installation with the Elementor and the Avada Builder. The error only occurs with the Oxygen Builder. There are no problems with the Gutenberg Editor either.
