### ISSUE TITLE
Use the Repeater for Taxonomies e.g. Categories

### ISSUE THREAD

**Issue by jmoont** [soflyy/oxygen-bugs-and-features#2647]
**Describe the feature you'd like to see included in Oxygen.**
You should be able to choose a Taxonomy as the query for a Repeater loop - e.g. Categories. You should be able to choose the parent (but the depth would be limited to 1). If you want another level you should be able to add another Repeater below.
Within the Repeater, you should be able to use the current Taxonomy e.g. Category to add other elements - e.g. the Title of the Category, the Category image, an Easy Post element filtered to that Category. 
There should be an option to exclude certain IDs and/or Taxonomies without any related Posts.

**What are the use cases for this feature?**
- Listing Categories with their latest Posts as a home page for the Blog. 
- Listing Categories for navigation with their names, descriptions and images.
- Listing Sub-Categories on Archive pages.

**Comment by songsta** [comment]
This is definitely a feature that I would like to see. +1 from me.

**Comment by Spellhammer** [comment]
This would be satisfied by #2257 so closing as duplicate.
