### ISSUE TITLE
Padding and Margins not work in section mobile mode

### ISSUE THREAD

**Issue by Janvier7** [soflyy/oxygen-bugs-and-features#2651]
Hi:

Padding not work in section mobile mode.
Padding and margins not work when a WordPress sidebar is in mobile mode.

Check "1er Sidebar" section here:
https://oxygen-q8nmw838mj2jl.oxygen-demo.qsandbox.me/

User: 
admin

Pass: 
adminiStrong0

![padds-margins](https://user-images.githubusercontent.com/83109262/148172959-eae25a94-8355-4da9-a4a4-3e43f4de81c9.jpg)

**Comment by KittenCodes** [comment]
@Janvier7 The Sidebar element itself isn't actually output on the front-end of the site. Please wrap it in a Div - you should then be able to add classes and padding etc to the Div.

**Comment by Janvier7** [comment]
Thank you. I found out a conflict with a code written in a custom stylesheet that not able Oxygen to implement the padding and margin. Now works fine, thanks and I'm sorry if I made waste your time.
