### ISSUE TITLE
Duplicate Shortcode Execution / Curl Requests

### ISSUE THREAD

**Issue by MilesS** [soflyy/oxygen-bugs-and-features#2664]
### Description 
We have a custom plugin that makes multiple API call via curl to Salesforce. Without Oxygen Builder everything works fine. 

With Oxygen Builder all API requests are doubled; the system calls Salesforce twice with the same request milliseconds after each other.

We have tested on multiple themes, and it looks like Oxygen Builder is causing the conflict.

### Question
When debugging, we can only find the one call; we don't code being executed twice when using Query Monitor. It is as though Oxygen Builder is  running everything twice. Once before we can catch it in a debug, a second time after.

Does Oxygen Builder load WordPress twice?

### Without Oxygen Builder 
Salesforce reports one API call; which is wanted.

### With Oxygen Builder 
Salesforce reports **two** simultaneous API calls, sending the same request.

**Comment by KittenCodes** [comment]
@MilesS Does this happen in the builder or on the front-end of the site (or both)?

**Comment by KittenCodes** [comment]
@MilesS Thanks for the update.

Is the shortcode within Oxygen and within the WordPress editor, or just in Oxygen?

**Comment by MilesS** [comment]
@KittenCodes within just Oxygen

**Comment by KittenCodes** [comment]
Thanks @MilesS.

Please could you open a support ticket so that we can take a look at this for you? You can open a ticket here: https://oxygenbuilder.com/support.
