### ISSUE TITLE
Partial search in custom CSS stylesheet

### ISSUE THREAD

**Issue by Janvier7** [soflyy/oxygen-bugs-and-features#2681]
When I do a word search (Ctrl + f) using Firefox or Chrome in the left bar >> custom stylesheet, the search only find the code shown **on screen**, ignoring the code below the scroll.

Please try to find the 2 codes .j{} in (head-footer stylesheet) on this page. The search only find one, and the same code below scroll will be ignored.

User: admin
Pass: adminiStrong0
https://oxygen-qafajblyxzckl.oxygen-demo.qsandbox.me/?ct_builder=true&ct_inner=true

**Comment by KittenCodes** [comment]
Thank you for reporting this to us. Replicated and reported internally.
