### ISSUE TITLE
Repeater pagination fail

### ISSUE THREAD

**Issue by Janvier7** [soflyy/oxygen-bugs-and-features#2682]
I have a repeater that shows a list of custom posts types called Descargas. The pagination not work.
I have tried using Easy Posts but the pagination fails too.

User: 
admin

Password:
adminiStrong0

https://oxygen-qafajblyxzckl.oxygen-demo.qsandbox.me/descargas/

**Comment by KittenCodes** [comment]
​The problem is that your page and your post type are using the same slug (/descargas), which is causing a URL conflict. I renamed the page permalink to /descargas_page and the pagination is now working correctly.
