### ISSUE TITLE
Oxygen 4 Alpha 1 - CSS editing and some edit boxes - disabled browser copy and paste shortcuts

### ISSUE THREAD

**Issue by whitespacerob** [soflyy/oxygen-bugs-and-features#2685]
With this new copy and paste feature (which is fairly good, not as good as Hydrogen as the right click and ability to choose on the right menu where you want to paste, and right click paste is super helpful) - it becomes a huge pain when editing CSS or trying to copy or paste text in edit or text boxes within the editor.

When pasting anything, in any edit boxes, I am finding it always just pastes the copy Oxygen section feature rather than and text or copied content when you are editing. This is a small thing, but when you are used to keyboard shortcuts for text content, or are a client editing the page, it becomes a huge and confusing pain. 

You also don't realise all the things you've pasted by accident from trying to paste text.

**Comment by KittenCodes** [comment]
@whitespacerob This will be fixed in v4 Alpha 2.
