### ISSUE TITLE
Big problem: The device width previews are wrong (still wrong in 2.3 RC1)

### ISSUE THREAD

**Issue by wplit** [soflyy/oxygen-bugs-and-features#269]
**Describe the bug**
When you select a width to preview the site, say 992px. The preview isn't actually showing us how it will look at 992px, it's showing the next smaller width.

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
Yes, and is the same in 2.3RC1. i think I remember somebody flagging it a while back, I hadn't checked on it until now, but it's still happening.

If you set the device width to be page container width, it instead shows at 992px
If you set it to be 992px, it instead shows us 768px, 768px shows 480px... etc

You can see it visually by looking at the ruler at the bottom. Using google chrome inspector also shows that it is wrong. 

This will be causing lots of people to not be able to properly add responsive styling as they will be expecting the builder to accurately be showing them their site at the selected width, meaning what they see on the front end won't match what they have been seeing in the builder. 

**To Reproduce**
1. Go to Oxygen builder and click any of the devices to change the preview width.
2. Look at the rules at the bottom or check chrome inspector to see it's not showing the site at the correct width.

**Expected behavior**
It should show us the exact width so the styles added at that preview are actually what is added to the page.

**Screenshots**
<img src="https://i.ibb.co/Hq9kNJJ/widths.jpg" width=600>

**Comment by louisreingold** [comment]
This is deliberate.

Choosing a media query resizes the preview to 1px wider than the next media query.

Imagine a 3 column layout that looks fine at 992px wide, but is obviously far too cramped at 769px. 

If we showed the preview at 992px, the user would think it's fine.

Then they'd go down to the 768px media query, see that it's cramped, and stack the columns vertically.

They'd never know the layout looked horrible at 769px and wider (until it got close to 992px).

**Comment by louisreingold** [comment]
Think of 992px as really meaning the styles which apply from 992px to 769px, and only below 768px if they are not overridden. So whatever styles you set in that query absolutely have to make the design look good between 769px to 992px. We could show the preview at any width in that range - but the width that's most likely to show the problem with the design would be 1px above the next media query.

**Comment by wplit** [comment]
Makes sense. I hadn't thought about it enough. I had been thinking that because the styes change at 992px, then that's the point at which you'd want to see the preview, like when you resize the browser width manually. But you're right, this way probably helps people make less mistakes, which is more important. I'll just delete this non-bug report.
