### ISSUE TITLE
Heading Tag won't change

### ISSUE THREAD

**Issue by jornessim** [soflyy/oxygen-bugs-and-features#2690]
I noticed that the heading tag won't change no matter what heading I choose.

Please refer to the screencast:
https://sc.jornes.com/conversations/7329dd47-61f4-596a-b6ec-6ce26efb2e3e

**If you can't fill out the above information, you should not be filing a bug report. Instead, contact us via https://oxygenbuilder.com/support with the details you have and we'll investigate your issue further.**

**Comment by KittenCodes** [comment]
@jornessim I've not been able to replicate this using Oxygen v4 Alpha 2.

If you're still experiencing the issue, please recreate it on a Sandbox site so that we can take a look.

**Comment by jornessim** [comment]
> @jornessim I've not been able to replicate this using Oxygen v4 Alpha 2.
> 
> If you're still experiencing the issue, please recreate it on a Sandbox site so that we can take a look.

I will try using a different browser. Btw, I am using Google Chrome.

**Comment by jornessim** [comment]
hi! I've sent you an email with a temp login link. Please check it out. Thank you!
