### ISSUE TITLE
Oxygen 4 A1&A2 - Fonts issue with Firefox DE

### ISSUE THREAD

**Issue by antic1pate** [soflyy/oxygen-bugs-and-features#2694]
Geomanist font not loading in Firefox Developer Edition.

Everything looks normal when using Safari.

Catalina 10.15.7

![Screenshot 2022-01-18 at 2 46 38](https://user-images.githubusercontent.com/81658414/149853827-b697cdf4-90bf-4c77-b978-5b2ec45fede9.png)
![Screenshot 2022-01-18 at 2 46 57](https://user-images.githubusercontent.com/81658414/149853829-6581e5cd-f596-4319-8a8e-248ff5fbb3d3.png)
![Screenshot 2022-01-18 at 2 53 43](https://user-images.githubusercontent.com/81658414/149853831-a120be95-5482-4c24-b036-bf8af4f188d4.png)
![Screenshot 2022-01-18 at 2 45 52](https://user-images.githubusercontent.com/81658414/149853832-c3260159-5de4-41fa-9117-f3440df4798c.png)

**Comment by antic1pate** [comment]
I found a solution for this. I had to deactivate geomanist webfont from my fonts library and activate the regular version.  I'm not sure if this is Oxygen related issue or not.

**Comment by KittenCodes** [comment]
@antic1pate Are you able to reproduce this behaviour on a [Sandbox site](https://oxygenbuilder.com/support)?
