### ISSUE TITLE
DONE: Replace 'View' on template screen with 'Edit with Oxygen'

### ISSUE THREAD

**Issue by wplit** [soflyy/oxygen-bugs-and-features#27]
By being able to load up the builder straight from the templates screen, it would speed up workflow. Most of the time, when we're in the template screen, it's much more common that we're just trying to load up the builder, not edit where the template is active. That happens much less often. So being able to skip that next edit screen and go straight to the builder would be a smoother workflow.

Currently, the 'view' link that is there is useless as it takes us to the same place as the 'edit' link. So this can just be removed (and replaced with new link)

<img width=600 src="https://i.ibb.co/7XnfT0j/template-view.png">

**Comment by goshenweb** [comment]
+1

**Comment by CameronGilroy** [comment]
+1

**Comment by timpixel** [comment]
This would save most users a ton of clicks. Easily one of the most obvious improvements. I'm guessing it's somehow tricky to build this, otherwise it would have been implemented already?

**Comment by KittenCodes** [comment]
This has been added.
