### ISSUE TITLE
Improve UI for variables

### ISSUE THREAD

**Issue by avviodigital** [soflyy/oxygen-bugs-and-features#2706]
Please take variables into consideration when making UI improvements.

- Increase width of margin/padding and font-size fields
- Place padding/margin on separate rows

![image](https://user-images.githubusercontent.com/96754716/167048231-7fd1891a-aab3-4f87-bf5a-38b2ef7d076c.png)

![image](https://user-images.githubusercontent.com/96754716/167048543-d3aeec64-2133-4dc7-92b8-dbabb6adf08a.png)

**Comment by maltmann-muc** [comment]
+1

**Comment by RaulGandia** [comment]
+1

**Comment by Yosi11** [comment]
+1

**Comment by smithbenites** [comment]
+1

**Comment by beewine** [comment]
+1

**Comment by Vyyt02** [comment]
Oh yes, pleeeease! 👍

**Comment by SiteDesignWeb** [comment]
+1

**Comment by royby** [comment]
+1

**Comment by web2pc** [comment]
+1

**Comment by goshenweb** [comment]
Or they can approach it similar to what Webflow and Zion implemented theirs…
![7B7CF0A5-2916-43CB-B400-C8B7A203A6ED](https://user-images.githubusercontent.com/25493643/150535777-49bb9066-fffe-4fdc-aee1-ce085cdee780.jpeg)

**Comment by jornessim** [comment]
+1

**Comment by yankiara** [comment]
+1000, thanks for opening this :-)

**Comment by avocadesign** [comment]
Agreed +1000 
we use variables everywhere - some are short e.g. "var(--size1)" and some are necessarily quite long "var(--primary-light-alt)". Even the short size variables are always too wide to be seen in full in the editor. Usually all we see is "var(--" that's all there is room for. 

Another way to help would be to include a "var" unit option alongside the other px,em, rem etc that meant that you didn't have to type the "var(" at the start or the ")" at the end - See the image. That way at least you can see the start of the variable. You could even go as far as not needing the "--" either so you just type the variable text

E.g. 
value: "size1"
prepend with: "var(--"
append with: ")"
output: "var(--size1)"

![Screen Shot 2022-03-11 at 10 04 05 AM](https://user-images.githubusercontent.com/782819/157754855-020be16e-fdd5-41b5-9bea-52d7209b6da0.jpg)
