### ISSUE TITLE
Oxygen 4.0 Alpha 2 not working with Pods (PHP Error in FrontEnd)

### ISSUE THREAD

**Issue by vitorrloureiro** [soflyy/oxygen-bugs-and-features#2719]
**Describe the bug**
Oxygen Builder 4.0-alpha2 installed together with Pods will break the frontend and display the following php error:

`QSandbox Fatal error/exception: 
File: /wp-content/plugins/pods/tribe-common/src/Tribe/Service_Providers/Shortcodes.php
Line: 118
Request Id: b66d02a91b4b025f4d764cd99042a7deccb63dfc
Plugin: pods`

Don't happen in version 3.9, so this is why I'm posting it here as a bug that may be related to Oxygen Builder.

*Provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*
[Sandbox Frontend](https://oxygen-q78rmfcv32lkl.oxygen-demo.qsandbox.me)

1. In a clean WordPress environment, install Oxygen Builder v4.0-alpha2
2. Install Pods.
3. Go to the frontend

**Comment by KittenCodes** [comment]
Thanks for the report. This should be resolved in v4 Beta.
