### ISSUE TITLE
4.0 Alpha 2, incompatibility Perfmatters

### ISSUE THREAD

**Issue by madjedo** [soflyy/oxygen-bugs-and-features#2720]
** Describe the bug **

Perfmatters allows you to defer javascripts. Enabling this option breaks front-end styling, scripts doesn't load at all.

Perfmatters works fine with Oxygen 3.9.

** A link to a Sandbox site where the bug has been reproduced **
https://oxygen-qz8j495nbs3c.oxygen-demo.qsandbox.me/test/

Notice that font is not styled with Source Sans Pro for headers or Open Sans for body text.

** Steps to reproduce the behavior: **

1. Install Oxygen builder 4.0 Alpha 2
2. Install perfmatters
3. Activate defer javascript at backend.
4. Visit front-end. Results may vary depending on scripts or fonts loaded.

**Comment by KittenCodes** [comment]
@madjedo This also happens in the current version of Oxygen. You need to exclude webfont.js from deferral.

**Comment by madjedo** [comment]
@KittenCodes hi, am i allowed/able to upload JavaScripts and enque them with code snippets on your sandbox site?

**Comment by KittenCodes** [comment]
@madjedo Yes, you can install / enqueue anything you like on our Sandbox site.
