### ISSUE TITLE
Oxygen Template Editor not Rendering Previously Created Template

### ISSUE THREAD

**Issue by theKaiLamberson** [soflyy/oxygen-bugs-and-features#2721]
After creating a homepage template which includes a Header Builder, Inner Content and Copyright Section, upon re-entering the template following save, the Copyright Section does not render in the editor despite showing correctly on the front-end.  In a local and production environment, I extended this by creating a re-usable part for the footer, and this resulted in the same issue.  Loading the template to then edit does not display what had been previously built correctly.

This issue has been tested and replicated on a local instance, a production instance as well as Oxygen Builder's own sandbox environment.

Oxygen Sandbox:  https://oxygen-qkv53wnv3xmkl.oxygen-demo.qsandbox.me/
Oxygen Editor:  https://oxygen-qkv53wnv3xmkl.oxygen-demo.qsandbox.me/?ct_builder=true&ct_inner=true

**Comment by theKaiLamberson** [comment]
I've been able to progressively narrow down the issue to when I specifically set the font family on the Copyright text.

**Comment by KittenCodes** [comment]
@theKaiLamberson I've not been able to experience this on the Sandbox site - I can see the footer both in the template and when editing the home page in Oxygen.

Please could you let me know which operating system and browser you're using, and also if you have any anti-virus software installed?

![2022-02-01 08_09_39-](https://user-images.githubusercontent.com/18448481/151933174-bc24ffd9-7e53-4e90-84a4-5e2e800b060a.jpg)

**Comment by theKaiLamberson** [comment]
I'm currently running MacOS Monterey with BitDefender Total Security.  It doesn't appear either are responsible for the issue.  What I have been able to determine is the problem occurs when I try to apply styling to a text element, primarily around setting a specific font to that element.  I've gotten around it by applying the styling via the typography section of the parent div.

**Comment by KittenCodes** [comment]
@theKaiLamberson 

The issue is most likely BitDefender. Please can you disable the Anti Tracker as that should resolve the issue you're experiencing.

If that doesn't help, please open a support ticket: https://oxygenbuilder.com/support.

**Comment by theKaiLamberson** [comment]
I believe you are correct.  Just tested and all looks fine.  Honestly didn't think about the anti-tracker being an issue.  Thanks for the resolution :).
