### ISSUE TITLE
4.0 a2 : Promenu mobile not showing

### ISSUE THREAD

**Issue by zebrahosting** [soflyy/oxygen-bugs-and-features#2722]
test site: https://montarnthong.com
Setup with alpha 2, PHP 8 (and tested 7.4)

Upgraded from latest v3.x

Promenu was set as the menu with the setting "Always show" for mobile.
After upgrade the menu only shows the desktop version.

Tested with a fresh menu setup and added the first preset (slide tot the right) but it remains desktop only on the front end for all breakpoints, backend shows mobile menu in the builders as expected.

**Comment by KittenCodes** [comment]
@zebrahosting This will be resolved in the Beta.

**Comment by KittenCodes** [comment]
Duplicate: https://github.com/soflyy/oxygen-bugs-and-features/issues/2697
