### ISSUE TITLE
4.0 Alpha 2, defer javascript (perfmatters), international characters (ÅÄÖ)

### ISSUE THREAD

**Issue by madjedo** [soflyy/oxygen-bugs-and-features#2725]
**Describe the bug**

On Oxygen Builder 4.0 Alpha 2: Using a plugin like perfmatters to defer javascripts causes weird issue with international characters such as ÅÄÖ. See screenshot for end-result of bug:

![international_characters_4 0Alpha2](https://user-images.githubusercontent.com/25926337/151975647-6cdc3cac-4ca1-4c23-a7a5-b7e732e3b82a.jpg)

**A link to a Sandbox site where the bug has been reproduced https://oxygenbuilder.com/try? (REQUIRED)**

https://oxygen-qa2gdxqf5c57.oxygen-demo.qsandbox.me/about-me/

https://oxygen-qa2gdxqf5c57.oxygen-demo.qsandbox.me/about-us/

**Steps required to reproduce the bug:**

1. Install Oxygen 4.0 Alpha 2 with a premade template.
2. Edit a page in Oxygen builder and write some content using international characters such as Å Ä Ö.
3. Save page.
4. Install perfmatters. Activate plugin. Activate feature to defer javascript.
5. Go to WordPress edit page, untick checkbox to defer (see screenshot below). Save page.
6. Visit front-end. Refresh without cache.
7. Back to wordpress edit page, mark checkbox to defer. Save page.
8. Visit front-end.

![defer_javascript_checkbox](https://user-images.githubusercontent.com/25926337/151976925-210cefd9-dd97-44d1-80fb-2e49610518a6.jpg)

Tested previously on Oxygen builder 3.9 with same Perfmatters plugin without any issues.

Of course this can be a "Perfmatters thing". But it works fine on v3.9, leading me to believe this is a "Oxygen thing" related to new JSON format. Requires more investigation.

Tested using both google fonts and a system font stack:

font-family:-apple-system, system-ui, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol";

**Comment by KittenCodes** [comment]
@madjedo Thanks for the report. This has been resolved in the upcoming v4 Beta.
