### ISSUE TITLE
Code Blocks are empty

### ISSUE THREAD

**Issue by jessebrightman** [soflyy/oxygen-bugs-and-features#2727]
Hello, 

I am experiencing a weird bug where the Code Blocks that I have previously entered custom PHP, CSS, and JS are now empty.  Everything still works and the code is being saved somewhere, it's just I cannot make any new edits.   It is a large site with a large number of elements which may have an impact on the performance here.  I will begin the next bug reporting steps when I am able to find some non-client time to investigate further.  Thanks for the great builder, other than these weird quirks, it is still the best tool I have ever used for wordpress.

**Comment by Spellhammer** [comment]
This sounds like something we'll probably want to take a look at directly. If you're able to give us access to the site where it's occurring, please submit a support ticket via https://oxygenbuilder.com/support with login credentials and instructions on what we need to do to see the issue. We can check if the code is still present in your shortcodes (it should be) and try to identify why it's not loading in the code editor for you.

**Comment by jessebrightman** [comment]
Absolutely, Thanks and I appreciate your time on this.  Honestly, it's the best builder I've ever used (and I've used them all).
