### ISSUE TITLE
Modal Always Starts Open

### ISSUE THREAD

**Issue by ivanjuras** [soflyy/oxygen-bugs-and-features#273]
**Describe the bug**
*A clear and concise description of what the bug is.*

Whenever I reload the page that I'm working on, the modal starts as a live preview, or inline. That's really irritating, because I'd like Oxygen to save my settings. Most of the time, I set it to "hidden".

Can you guys fix that?

**Comment by KittenCodes** [comment]
Replicated in 2.4.1.

**Comment by barleedar** [comment]
I would also like to have this hidden option save, since I have the Modal in the header, I cannot hide it when editing pages.

**Comment by yankiara** [comment]
Hi all,
Same problem here, with modal in header (login form), and my clients don't understand why they always have this open when editing any page.
Thus, it is unusable in production, please fix this.
Thx

**Comment by barleedar** [comment]
Until they get it fixed, I dragged the Modal to below the footer to get it out the way

**Comment by KittenCodes** [comment]
This is fixed in the latest version of Oxygen.
