### ISSUE TITLE
Enhanced support of signs and numbers in custom attributes (patch)

### ISSUE THREAD

**Issue by skogowskinetfactory** [soflyy/oxygen-bugs-and-features#2731]
Description:
This feature is a continuation of [patch for issue number 2726](https://github.com/soflyy/oxygen-bugs-and-features/issues/2726)
It would be nice for oxygen custom attributes to support for signs and number in attribute names, that are typically used by javascript frameworks like Vue (colon,dot), Angular (brackets,asterisk). Also it would be nice to remove automatic replacement of characters like '<' in attribute values, as this was never needed because it was automatically done already by oxygen backend.

Here are the fixes that I found to make that possible (after patch from issue  2726 will be applied, it is necessary for the things below to work properly):
`public_html/wp-content/plugins/oxygen/component-framework/component-init.php`
Line 5908 - change the pattern to: 
```
    if ( preg_match("/[^a-z0-9-_:@#\.\*\$\(\)\\[\\]]+/i", $name) ) {
```
`public_html/wp-content/plugins/oxygen/component-framework/angular/controllers/controller.options.js`
Line 4203 - change the pattern as well:
```
        var regex = RegExp('[^a-z0-9-_:@#\.\*\$\(\)\\[\\]]+', 'gi')
```
Line 4273 - function $scope.validateCustomAttributeValue is no longer needed, you may empty it or remove it:
```
    $scope.validateCustomAttributeValue = function(index) {
    }
```

After the above patch is applied, support for vue and angular characters in attributes will be done, also the signs like '<' will not be replaced automatically in the oxygen builder during writing, as it was never actually needed because the same thing was already done on backend (line 5911 in `component-init.php`)

**Comment by Kpudlo** [comment]
Closing in favor of https://github.com/soflyy/oxygen-bugs-and-features/issues/1535 as that issue has an internal report for it.
