### ISSUE TITLE
Gutenberg oxygen block edits not showing frontend on Page

### ISSUE THREAD

**Issue by annettePixie** [soflyy/oxygen-bugs-and-features#2733]
Changes made in Gutenberg to text in an oxygen block do not show on the front end when the page was initially created in Oxygen before the Oxygen blocks plugin was installed. I have flushed cache on my host several times, disabled cache in my browser. 

1. Create a page and edit with Oxygen
2. Create a section with editable text
2. Install Oxygen blocks plugin
3. Convert the section you prevously created into an oxygen block
4. Add the block to the page in Gutenberg and edit text.
5. Save and view - none of the text changes show.
6. Create a brand new page
7. Add the block in Gutenberg and edit
8. Save and view - all text changes are shown.

EDIT***********
Not sure if this is a bug or what it is. Its not about the fact that the page was created before the block plugin. Its the fact that an oxygen template exists for the page. I want a page which is partially editable by the client in gutenberg. I thought oxygen blocks was the way to go. If I create an oxygen template and turn some of the sections into blocks, none of the blocks show up in Gutenberg until I manually add them in - is this the correct behaviour? I don't want to make the full page editable.

ANOTHER EDIT ************
It works if I make the full page editable ie changes made in gutenberg are reflected on the front end. However, dynamic elements in code blocks are not replaced by a placeholder so a client would have no visual clues indicating that they couldn't edit those elements.

**Comment by KittenCodes** [comment]
@annettePixie 

If a page is designed in Oxygen, that design will be used on the front-end of the site and not whatever design has been added via Gutenberg. The only time this isn't the case is if the page has "Make this full page editable in Gutenberg" selected.

> If I create an oxygen template and turn some of the sections into blocks, none of the blocks show up in Gutenberg until I manually add them in - is this the correct behaviour?

Yes, that's correct. Making a Section a block copies it to the Block Library. It doesn't force it to be displayed anywhere.

It sounds as though you'd be best to create your blocks via Oxygen > Block Library, and then build the page using the blocks.

**Comment by annettePixie** [comment]
I'm confused here - One of your videos - **How To Build A Client Friendly WordPress Site With Oxygen + Gutenberg** states that you can make page sections editable in Gutenberg and not just the whole page. It goes on to show exactly how to do it, except it doesnt work. If this is no longer something you can do with oxygen, you really should update the information you have on youtube [https://www.youtube.com/watch?v=vYlwyG-IyW8&t=21s]

>@annettePixie

If a page is designed in Oxygen, that design will be used on the front-end of the site and not whatever design has been added via Gutenberg. The only time this isn't the case is if the page has "Make this full page editable in Gutenberg" selected.
