### ISSUE TITLE
4.0 beta 1: Advanced Query Builder meta_query, compare is stuck as "="

### ISSUE THREAD

**Issue by albertvisuals** [soflyy/oxygen-bugs-and-features#2747]
**Any bug report that doesn't include a Sandbox link or replication steps will be closed. If you can't provide these pieces of information, we're happy to help you via our official support channel instead: https://oxygenbuilder.com/support. You need to select "Something's broken and I need help" from the dropdown box on the left.**

**Describe the bug**
*A clear and concise description of what the bug is.*

It seems that the advanced query builder does not use the compare field value. It is stuck on the default "=". Any different value like "<" ">" "!=" is getting ignored on the front end. It keeps the compare field as "=" and filters the post like that, although a different compare token is inserted in the field. 

**Steps required to reproduce the bug:**

1. Create custom post type with an ACF field (storing a date Ymd return value)
2. Create a page with an repeater element and create an advanced query
3. meta_query field => key: custom_field / compare: any value permitted // value: [oxygen data='phpfunction' function='date' arguments='Ymd']

**Comment by KittenCodes** [comment]
Thanks for the report. Replicated and reported internally.

**Comment by Spellhammer** [comment]
Fixed in 4.0.
