### ISSUE TITLE
Navigation Element Layout Doesn't Work On Smaller Screens

### ISSUE THREAD

**Issue by ivanjuras** [soflyy/oxygen-bugs-and-features#275]
**Describe the bug**

When I change the layout (from horizontal to vertical) on smaller screens, it doesn't work. Even worse, the surrounding elements' layout totally breaks.

Here's the video: https://youtu.be/alBQV0yvMD0

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**

Yes

**Expected behavior**

I expect the custom layout to work on every screen

**What actually happens**

The layout change only works on the default screen size.

**Comment by Spellhammer** [comment]
The Pro Menu element should address this use case.
