### ISSUE TITLE
4.0 beta 1, Animate on Scroll & Element Transition

### ISSUE THREAD

**Issue by WebsiteService360** [soflyy/oxygen-bugs-and-features#2750]
I tried creating a new button, a fairly basic one with just a change of the background color on hover, and have a transition to ease the color change.

And that part works fine. However, if I add Animate on Scroll to the button, then the transition goes away. It is still set on the button, it just simply does not work. On my own site, I also added a transform on hover to slightly enlarge the button, which too also ceased to work if the Animate on Scroll has a value set in the Animation Type. 

https://oxygen-q23jha8dkgvkl.oxygen-demo.qsandbox.me/button/

**Comment by KittenCodes** [comment]
> However, if I add Animate on Scroll to the button, then the transition goes away. It is still set on the button, it just simply does not work

Unfortunately, this is to do with the CSS that's used by the Animate on Scroll library when an element has animation settings set.

If you're wishing to animate an element and also add a transition on hover, I'd suggest looking at the Animate.CSS library: https://oxygenbuilder.com/tutorial/using-animate-css-and-waypoints-to-animate-elements-on-your-oxygen-site/.
