### ISSUE TITLE
Nested Repeater Reset Post Data Not Working

### ISSUE THREAD

**Issue by Simbaclaws** [soflyy/oxygen-bugs-and-features#2753]
Hi there,

I'm trying to use a custom post type with a relational (ACF Pro) field that is set to another custom post type.

Now I have a repeater field in oxygen for post type A.
Inside that repeater is a repeater for post type B.

Underneath the second repeater (not inside) is a custom field from post type A.
This field does not display.

There is a custom field within the repeater for post type B.
This field does display.

I am guessing that because repeater with post type B is added, anything after that will simply use the WP_Query from post type B. Losing reference to all the custom fields of post type A.

I also found out not all ACF fields for post type B seem to come up for some reason.

When I put a custom field from post type A ABOVE the repeater from post type B. The data does get displayed.
This means I can not put anything underneath information from post type B. Unless I can somehow reset the post data to that of post type A.

I've already tried doing:
```wp_reset_postdata();```
in a custom codeblock.
To no avail...

Can anyone help me reset the WP_Query to repeater A after repeater B?

**Comment by Kpudlo** [comment]
Recreated and reported internally with #2261
