### ISSUE TITLE
Mailto: not working at all 

### ISSUE THREAD

**Issue by djlloyd406** [soflyy/oxygen-bugs-and-features#2757]
I cannot set an email link in Oxygen. This is happening across all my sites. I use a Link Wrapper with mailto: and all it does is open a blank page. I recreated this bug in your Sandbox. See the link below. 

https://oxygen-q5fwhnw3bwwkl.oxygen-demo.qsandbox.me/sample-page/?preview_id=2&preview_nonce=a74bd20aeb&preview=true

**Any bug report that doesn't include a Sandbox link or replication steps will be closed. If you can't provide these pieces of information, we're happy to help you via our official support channel instead: https://oxygenbuilder.com/support. You need to select "Something's broken and I need help" from the dropdown box on the left.**

**Describe the bug**
*A clear and concise description of what the bug is.*

**A link to a Sandbox site where the bug has been reproduced https://oxygenbuilder.com/try? (REQUIRED)**
*Provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*

**IF YOU CAN'T PROVIDE A SANDBOX REPRODUCTION: Steps required to reproduce the bug:**

**If you can't fill out the above information, you should not be filing a bug report. Instead, contact us via https://oxygenbuilder.com/support with the details you have and we'll investigate your issue further.**

**Comment by sk209** [comment]
The mailto link in your sandbox is opening my email client. Tested on Windows 11 - Chrome and Firefox

**Comment by KittenCodes** [comment]
@djlloyd406 This is working correctly for me too - tested via Chrome on Android.

Which browser, operating system and mail client are you using?
