### ISSUE TITLE
Oxygen-WooCommerce Product Description Broken

### ISSUE THREAD

**Issue by slewis-royal** [soflyy/oxygen-bugs-and-features#2758]
**Any bug report that doesn't include a Sandbox link or replication steps will be closed. If you can't provide these pieces of information, we're happy to help you via our official support channel instead: https://oxygenbuilder.com/support. You need to select "Something's broken and I need help" from the dropdown box on the left.**

**Describe the bug**
*A clear and concise description of what the bug is.*

>"Product Description" data unavailable in editor or on front end of site. When "Product Builder" Woo element used **alone**, the description shows up. However, if Product Description used singularly or in conjunction with any other OxyWoo elements, the descriptions are not appearing in the editor or on the front end. 

**A link to a Sandbox site where the bug has been reproduced https://oxygenbuilder.com/try? (REQUIRED)**
*Provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*
>https://oxygen-qn3pzkvqa657.oxygen-demo.qsandbox.me/wp-admin/post.php?post=194&action=edit
>The issue occurs inside the Singe Product template.

**IF YOU CAN'T PROVIDE A SANDBOX REPRODUCTION: Steps required to reproduce the bug:**

**If you can't fill out the above information, you should not be filing a bug report. Instead, contact us via https://oxygenbuilder.com/support with the details you have and we'll investigate your issue further.**

**Comment by KittenCodes** [comment]
> "Product Description" data unavailable in editor or on front end of site. When "Product Builder" Woo element used alone, the description shows up. However, if Product Description used singularly or in conjunction with any other OxyWoo elements, the descriptions are not appearing in the editor or on the front end.

Please add a Product Builder element and then create your design inside of it (you can treat it as a container and create your full design). That will overwrite the default layout and allow Oxygen's individual WooCommerce elements to show data.

**Comment by slewis-royal** [comment]
@KittenCodes , 

That is indeed the method I have followed. All Oxyg's individual Woo elements are nested inside the Product Builder container. Please see attached. Perhaps there is something I'm not understanding about the overwrite? 

![image](https://user-images.githubusercontent.com/86374611/155168572-daecd0c0-cb0f-47ac-b07f-ec9a0b7c8a20.png)

**Comment by KittenCodes** [comment]
Hey @slewis-royal

I checked out some of the products on the Sandbox site and there's no description present. Please try using the Product Excerpt element, as I can see that there's a short description for the ones I checked.

I added a description to the product here (https://oxygen-qn3pzkvqa657.oxygen-demo.qsandbox.me/product/right-side-guard-type-a/) and it's visible on the front-end.

I hope this helps!

**Comment by slewis-royal** [comment]
@KittenCodes , 

I'm sorry, there's been a misunderstanding. That screenshot is from the website I'm working on. 

Using Product Excerpt does indeed do the trick. However, I was under the impression that this is what Product Description was supposed to be for. Was I wrong to expect that? Is there somewhere you can point me to so that I may see the functions that the Product Builder elements call? I just wasn't expecting this to be the solution and I'd like to understand better for next time. 

Thank you!

**Comment by KittenCodes** [comment]
Hey @slewis-royal

The Product Description is the text in the content area at the very top of the product page. The Excerpt is the text entered in the "Product short description" box.

Screenshot: https://d.pr/i/ycsOER.

I hope this helps!
