### ISSUE TITLE
Oxygen Template Inner-content element is missing HTML Semantic tag: <main>

### ISSUE THREAD

**Issue by Flipback8** [soflyy/oxygen-bugs-and-features#2761]
Oxygen Template Inner-content element is missing HTML Semantic tag <main>
![inner-content](https://user-images.githubusercontent.com/12590359/155041668-b5579645-9e75-4f53-aa54-0d930b526d82.png)

![semantic-elements](https://user-images.githubusercontent.com/12590359/155041736-5e035c89-c019-4e3d-aac6-ac4d25abadd8.JPG)

https://www.w3schools.com/html/html5_semantic_elements.asp

**Comment by wplit** [comment]
Main would be incorrect, as users may need to other tags such as aside within that area that may not be part of the main content. Better to just have a div, then users decide what tags go inside including using main where needed.

**Comment by KittenCodes** [comment]
Closing as this isn't a bug.
