### ISSUE TITLE
Gallery (Lightbox) doesn't work with cdn images

### ISSUE THREAD

**Issue by Bebuk85** [soflyy/oxygen-bugs-and-features#2767]
Hi the gallery doesn't work with cdn on, it makes that the lightbox got broken, instead of show the lightbox it redirects to url of the CDN

[Here is a video of the problem](https://drive.google.com/file/d/1ojb4tx2gg1_HWP8ccw2OUhk2eXIdTsO9/view)

If i use the images loaded from the domain everything works great.

Gijo from FlyingPress told me this: "It seems to be an issue with Oxy Gallery. They're adding an image URL as a link. So if it's an external domain, it's opening as another page."

**Comment by KittenCodes** [comment]
@Bebuk85 I've not been able to replicate this behaviour - you can see the site here where the FlyingPress CDN is in use and the Gallery images are opening in a Lightbox: http://misty-seal.w6.wpsandbox.pro/about-me/.

If you'd like us to take a look at your site, please open a support ticket: [Support Ticket](https://oxygenbuilder.com/support).
