### ISSUE TITLE
Audio embed using ACF oembed shows the audio shortcode, not the audio player 

### ISSUE THREAD

**Issue by songsta** [soflyy/oxygen-bugs-and-features#2780]
**Describe the bug**
The output of an ACF oembed field that is an audio file does not show the default Wordpress audio control, but instead shows the audio shortcode. It works correctly for a youtube file, but not audio.

**A link to a Sandbox site where the bug has been reproduced https://oxygenbuilder.com/try? (REQUIRED)**

https://oxygen-q7wssh7hy25kl.oxygen-demo.qsandbox.me/?ct_template=blog-post&ct_builder=true&ct_inner=true

**Comment by songsta** [comment]
You will see in the sandbox that when the output of the ACF field is pasted into a shortcode field, it correctly shows the media control.

**Comment by KittenCodes** [comment]
@songsta Oxygen can only render shortcodes that are added to a Shortcode element. If you wanted to add it dynamically, you'd need to do something like this in a Code Block:

```php
<?php
	$acf_field = get_field('audio_file');
	echo do_shortcode($acf_field);
?>
```

I've set up an example on the Sandbox site so that you can see it working.

I hope this helps!
