### ISSUE TITLE
Blur with pro menu element

### ISSUE THREAD

**Issue by AlkoKod** [soflyy/oxygen-bugs-and-features#2785]
**Describe the bug**

When you set blur to pro menu, it is unusable on mobile phones:

.pro-menu-class {
     background: rgba(255, 255, 255, 0.08); 
     backdrop-filter: blur(7.5px); 
     -webkit-backdrop-filter: blur(7.5px);
}

Then pro menu create huge gap on mobile device and when you click icon to open the menu, icon dissapear and you cannot scroll the website anymore.

**Comment by KittenCodes** [comment]
@AlkoKod This isn't a bug in Oxygen. If you use your browser tools, you can see how the CSS is having an effect on the element it's applied to. If that behaviour isn't what is desired, you will need to adjust your CSS.

**Comment by AlkoKod** [comment]
So you are telling me, that if I set a blur to component, it is normal that it does create huge overflow on the right side? Nope. When I do this with normal theme, works fine.

**Comment by KittenCodes** [comment]
@AlkoKod Please submit a [Support Ticket](https://oxygenbuilder.com/support) ticket so that we can take a look at this.
