### ISSUE TITLE
Variations above 30+ cause out of stock to show (when woo is set to hide)

### ISSUE THREAD

**Issue by Alan-Gunning** [soflyy/oxygen-bugs-and-features#2789]
Sandbox link...
https://oxygen-qwyxqxw2axall.oxygen-demo.qsandbox.me/product/test/
Real world link...
https://www.wagyu.co.uk/product/sirloin-gf/

**Describe the bug**
When a product has more than 30 variations, the out of stock items are showing at the same time as in stock (when the woo setting is set to hide).  It looks like the Ajax variation threshold is the issue.  It fixes when variations are below 30.

I've tried upping the priority

function iconic_wc_ajax_variation_threshold( $qty, $product ) {
    return 500;
}
 
add_filter( 'woocommerce_ajax_variation_threshold', 'iconic_wc_ajax_variation_threshold', 200, 2 );

any ideas?

**Comment by KittenCodes** [comment]
Hey Alan,

You need to install [Code Snippets](https://wordpress.org/plugins/code-snippets/) (or some equivalent) and add the following code to it:

```php
function iconic_wc_ajax_variation_threshold( $qty, $product ) {
    return 100;
}

add_filter( 'woocommerce_ajax_variation_threshold', 'iconic_wc_ajax_variation_threshold', 10, 2 );
```

I've done this on the Sandbox site and it's working correctly.

I hope this helps!
