### ISSUE TITLE
Footer Broken by 3rd slide on Slider

### ISSUE THREAD

**Issue by profuzion** [soflyy/oxygen-bugs-and-features#2798]
**Any bug report that doesn't include a Sandbox link or replication steps will be closed. If you can't provide these pieces of information, we're happy to help you via our official support channel instead: https://oxygenbuilder.com/support. You need to select "Something's broken and I need help" from the dropdown box on the left.**

**Describe the bug**
*When I use the Oxygen element Slider, and inside that 1st Slide I add a Review element.
If I replicate this same slide out 2, and then 3 times. The 3rd slide will break my fade up animated elements in my 4 column footer. 
This is actually breaking with only 2 slides now.*

**A link to a Sandbox site where the bug has been reproduced https://oxygenbuilder.com/try? (REQUIRED)**
*Provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*

**IF YOU CAN'T PROVIDE A SANDBOX REPRODUCTION: Steps required to reproduce the bug:**

**If you can't fill out the above information, you should not be filing a bug report. Instead, contact us via https://oxygenbuilder.com/support with the details you have and we'll investigate your issue further.**

![image](https://user-images.githubusercontent.com/35752407/160264521-36044e0e-597f-463a-8328-83a380e37d57.png)

**Comment by KittenCodes** [comment]
@profuzion If you would like us to take a look at this for you, please open a [Support Ticket](https://oxygenbuilder.com/support).
