### ISSUE TITLE
Rename block by clicking it's name on a left pane

### ISSUE THREAD

**Issue by shock2d** [soflyy/oxygen-bugs-and-features#28]
**Describe the feature you'd like to see included in Oxygen.**
To make everything well-organized inside templates we always need to rename objects not leaving them with default names like section, div etc. Today to rename a block you need to open a structure, push the option button, locate rename button.

*It's rather better to make renaming available by:*
1. clicking block title on a left pane (there is not binding to any click event's now)
https://i.imgur.com/Wg9qy4L.png
2. By double-clicking block name in a structure.
3. And maybe one click id renaming somewhere not far from title would be great too because there is also several additional clicks to do that and it's no so clear for new users.

**What are the use cases for this feature?**
Accessibility.

**Examples of this feature or functionality.**
No need to provide an example, a lot of apps using this way of renaming.

**Comment by Core-UX** [comment]
This is a usability issue.

**Comment by Gibsonion** [comment]
I've asked for a related improvement that I think would help keep code more semantic at the same time, that renaming blocks could be linked with a blocks ID, so when the block is renamed if not already customised manually, the element ID would be renamed at the same time, if an ID name already exists it would add a numerical suffix, preferably this feature could be enabled/disabled ass needed on the fly, depending on user preference.

**Comment by Deanphillips** [comment]
Been thinking that myself @gibsonian

**Comment by WrongGuy** [comment]
Instead of clicking Burger icon, double clicking the name should rename using Ajax. It would be much better.

**Comment by dubfonik** [comment]
I came here to write this. I find it a bit of a workflow issue doing it the convoluted way it is currently implemented.

**Comment by robert1112** [comment]
> I came here to write this. I find it a bit of a workflow issue doing it the convoluted way it is currently implemented.

Me too. I click intuitively on it to rename it. This is a basic basic. I cannot believe it is not possible now for a long time app. :(

**Comment by searchandgrow** [comment]
+1 for this please!!

**Comment by marou-lia** [comment]
+1 !!!! In the right column, structure, I always double-click to rename. And it's not working. So boring !

But to be coherent I would say double click to rename block title on a left panel (instead of one click)

**Comment by alanzirpoli** [comment]
+1

**Comment by UrbanFugitive** [comment]
+1

**Comment by wordpressguy22** [comment]
+1

**Comment by Spellhammer** [comment]
Added in 4.0 Alpha 1.
