### ISSUE TITLE
Image bug oxygen 4 beta 2

### ISSUE THREAD

**Issue by Brandinwebdesign** [soflyy/oxygen-bugs-and-features#2803]
Hey,

I'm happy with the new beta 2 update!
Especially the extra options with image!

However, I want to test it right away.
I have now opened the template and want to change the logo.
However, when I click on my logo it continues to load and I get the error message Error occurrend while loading attachment sizes.

I also have the loading icon and I can't click anything on it.

Use php 8.0
WordPress 5.9.2
Cache cleared after update from beta 1 to beta 2

**Comment by KittenCodes** [comment]
@Brandinwebdesign Please open a [Support Ticket](https://oxygenbuilder.com/support) so that we can take a look at this.

**Comment by KittenCodes** [comment]
Related: https://github.com/soflyy/oxygen-bugs-and-features/issues/2804
