### ISSUE TITLE
AFC field on sub-template using Main are empty

### ISSUE THREAD

**Issue by loiceoka** [soflyy/oxygen-bugs-and-features#2812]
**Describe the bug**

I'm using subtemplate based on the MAIN template ( header - footer  + some fields) for my single pages for CPT.
All the custom fields are empty in frontend, even the title. Backend is totally OK, loading the fields, but nothing in frontend.

I have no sandbox and working on a local test site. 

To duplicate the bug :

1. I create a CPT with CPTUI ( whatever name )
2. I create a main template with only title and inner content
3. I create a post for my CPT
4. I create a template for my archive CPT using the main template. No title are shown.
5. Adding any Acf custom fields on the main template won't show them on cpt single archive page 
6. Repeat for any CPT   

Using Beta1, was fine, using Beta2, i lost it.

php 7.4.1
nginx
WP 5.9.3

**If you can't fill out the above information, you should not be filing a bug report. Instead, contact us via https://oxygenbuilder.com/support with the details you have and we'll investigate your issue further.**

**Comment by loiceoka** [comment]
This page has the main template : https://lezarts.louisphilippeday.me
With subpage template and Title as field BUG is reproduce it here : https://lezarts.louisphilippeday.me/test/

No title available, O2 beta1.

**Comment by KittenCodes** [comment]
This will be fixed in v4 RC1.
