### ISSUE TITLE
Slow loading page

### ISSUE THREAD

**Issue by FlexonReclame** [soflyy/oxygen-bugs-and-features#282]
**Describe the bug**
My webpage is loading slow.
After 5 to 6 seconds seeing nothing at all, the page loads
It looks like some "program"/"virusscanner"/"firewall" is starting up or just something else that keeps it from loading 

**Have you tried all the steps**
I have reduced the image size with Image Optimizer WD
And I use WP Super Cache for a faster loading
Other plugins i'ff installed are: 
FileBird Lite
UpdraftPlus - Backup/Restore
Yoast SEO

Its about this site www.flexonsigns.nl

**Comment by quadcom** [comment]
Loads fast for me in Canada.

Try in an incognito window in Chrome and on another computer.

Also, when you see slow loading sites, try it on your phone. It's a totally different network and device.

**Comment by louisreingold** [comment]
This is a place to report bugs or request features in Oxygen specifically, not get general advice on WordPress performance.
