### ISSUE TITLE
Group Field inside Group Field Not Working (Meta Box)

### ISSUE THREAD

**Issue by OJGaming** [soflyy/oxygen-bugs-and-features#2825]
This bug is prevalent with Meta Box. Using groups is very buggy with Oxygen at the moment, BUT using group fields inside another group field really messes it up. This is for 4.0 Beta 2

Steps to replicate:

1) Create a settings page or post page with group field inside another group field.
2) Put more fields inside nested group field
3) Use dynamic data in Oxygen builder
4) The group will fail to output data.

**Comment by KittenCodes** [comment]
@OJGaming Nested groups aren't yet supported. If that's something you'd like to see in a future release, please add a vote to the feature request here: https://github.com/soflyy/oxygen-bugs-and-features/issues/2521.

Thanks!
