### ISSUE TITLE
autoptomize confilct

### ISSUE THREAD

**Issue by Phukit** [soflyy/oxygen-bugs-and-features#283]
oxygen 2.3 and autoptomize have a conflict.

oxygen 2.2.1 and autoptomize worked just fine when I upgraded to 2.3 I now have to disable autoptomize for oxygen to work.

**Comment by mikeingz** [comment]
Can you explain more because it works totally fine for me (Oxygen 2.3)

**Comment by Phukit** [comment]
I cannot edit any pages/templates.  

The wheel only spins

**Comment by mikeingz** [comment]
Did you disable the option "Also optimize for logged in users" in the Autoptimize settings?

**Comment by Phukit** [comment]
What are you new, of course its disabled.  I said it worked fine before the upgrade!

**Comment by Phukit** [comment]
I found the problem with autoptomize and oxygen for the makers of Oxygen.

When the option 'Remove query strings from static resources' under Extra tab it will break the oxygen builder editor.

Thanks.
