### ISSUE TITLE
PRODUCT CARD BUTTON redirect to the PRODUCT PAGE

### ISSUE THREAD

**Issue by waldek44** [soflyy/oxygen-bugs-and-features#2832]
PRODUCT CARD BUTTON redirect to the PRODUCT PAGE.

Why? It's should just add product to cart and note some alert (something like: "you add 5 products to your cart"). But why leaving the shop page? Can you change this behavior?  Please!

**Comment by KittenCodes** [comment]
@waldek44 Please open a [Support Ticket](https://oxygenbuilder.com/support) so that we can take a look at this for you. The cart button shouldn't redirect to the product page.

**Comment by waldek44** [comment]
done!
https://oxygen-q49a2s7xfr87.oxygen-demo.qsandbox.me/

Let me know if you find solution for this.
Thank You!


wt., 19 kwi 2022 o 12:19 Phe Simmonds ***@***.***> napisał(a):

**Comment by KittenCodes** [comment]
@waldek44 Please could I have the login details for the Sandbox site?

**Comment by waldek44** [comment]
oh, yes.......

https://oxygen-q49a2s7xfr87.oxygen-demo.qsandbox.me/
login: soflyy-master
pass: !!!soflyy-master!!!

wt., 19 kwi 2022 o 14:32 Phe Simmonds ***@***.***> napisał(a):

**Comment by KittenCodes** [comment]
Thanks @waldek44.

I found I was able to prevent the redirect from occurring using the WPC Ajax Add to Cart for WooCommerce plugin. Is that a viable workaround for you?

**Comment by waldek44** [comment]
it's ok. I will try this! Thank You.
I will try WPFunnels as well for that :)
I hope that is a chance to avoid this in next versions of Oxygen Elements
for WooCommerce.
All the best for all team!



wt., 19 kwi 2022 o 20:28 Phe Simmonds ***@***.***> napisał(a):
