### ISSUE TITLE
Template was deleted and replaced with another 4.0 beta 2

### ISSUE THREAD

**Issue by peteroe75** [soflyy/oxygen-bugs-and-features#2833]
I have never had this happen with oxygen.

I was just creating away, when I refreshed the page the template, I was working on was gone (woo commerce product archive template) It was replaced with another template, the original template is just gone. Not in the templates list. 

The catalog template was replaced with the single product template. 

The single product template was also acting very strange while building it. The product images block was printing like 8 times on top of itself.

**Comment by KittenCodes** [comment]
Hi @peteroe75

Thanks for the report. Do you know of a way to replicate this behaviour?

**Comment by peteroe75** [comment]
It just happened. I may have hit save on something related to the template at the same time. 

It is a very basic environment. Bitnami current version wordpress VM with php 8. Like 8 plugins that are all very basic/ well known. 

I would try to replicate it but it would take a lot of time as it was very random.

**Comment by KittenCodes** [comment]
@peteroe75 If you happen to replicate the issue, please post the steps here and we'll re-open the issue.
