### ISSUE TITLE
Plugin Conflict: Qubely Pro Image Carousel Block images spill out when Oxygen is activated. 

### ISSUE THREAD

**Issue by steverevere** [soflyy/oxygen-bugs-and-features#2835]
Sandbox link: 
https://oxygen-q6yzaap9xpsll.oxygen-demo.qsandbox.me/44-2/

Deactivate Oxygen and you will see how the block should display. 

I am experiencing this same issue here: 
https://dev.intcultcom.com/how-to-turn-off-notifications-on-android-12/

I can provide backend access to my site if you would like. 

I also have a ticket regarding this up with the Themeum team, the makers of Qubely. Let me know if you'd like me to loop in support@oxygenbuilder.com. 

Thanks Oxygen Team!

**Comment by steverevere** [comment]
I tried this out with another plugin - Kadence Blocks. Thought maybe it was a Qubely thing. Similar issue with their Carousel builder. 

Please tell me, am I nuts? Should I expect the Gutenberg blocks to all display properly in the middle of an Oxygen template I created for Posts, or am I doing it wrong? Is this an issue that may someday be fixed, or should I figure out some other way to get this done. 

I'd love to know. Thanks!

**Comment by KittenCodes** [comment]
@steverevere 

I added an Inner Content element to the template instead of retrieving the content dynamically using a Text element and the slider is now displaying correctly for me. Does it work for you?

**Comment by steverevere** [comment]
Hi Phe,

Thanks for taking a look at this!

Bringing in the content dynamically to an Inner Content element rather than a text element has resolved my problem. Thanks for showing me the error of my ways ~

Best,
Steve
