### ISSUE TITLE
Undefined array key "data" in oxygen-dynamic-shortcodes.php

### ISSUE THREAD

**Issue by TygrScott** [soflyy/oxygen-bugs-and-features#2837]
After migrating my site from localhost to my server, I am seeing a PHP error:
[22-Apr-2022 02:22:10 UTC] PHP Warning:  Undefined array key "data" in /home/scottb/compliance.scottbuehler.com/wp-content/plugins/oxygen/component-framework/includes/oxygen-dynamic-shortcodes.php on line 62

**Describe the bug**
The error_log appears to generate an entry every time a repeater element is loaded on a page. I have a reviews page with 20+ reviews and loading the page generates 20+ of these errors on a page refresh.

**A link to a Sandbox site where the bug has been reproduced https://oxygenbuilder.com/try? (REQUIRED)**
[removed]

I am willing to provide my admin credentials privately as it is a test site.
Oxygen 4.0 Beta 2
PHP 8.0 and PHP 8.1 tested, both produce errors.
Regenerated shortcodes.
Regenerated CSS cache.
Saved permalinks twice.

**Comment by KittenCodes** [comment]
@TygrScott Would you mind opening a [Support Ticket](https://oxygenbuilder.com/support) so that we can take a look at this please? It's not an error I've been able to reproduce using v4 Beta 1/2 and PHP v8.
