### ISSUE TITLE
Global Color issue in 4.0 beta 2 where var(--tag) not referencing color

### ISSUE THREAD

**Issue by samjco** [soflyy/oxygen-bugs-and-features#2838]
**Describe the bug**
When you define color as var(--primary), etc. the selected color doesn't show. even though it works, the color selection show as blanks when choosing. See screenshots.

![image](https://user-images.githubusercontent.com/3359062/164771826-c55d5508-a24f-403d-bece-ad6b1002f9b5.png)
![image](https://user-images.githubusercontent.com/3359062/164771947-09cc1152-a3a7-4c38-88de-9c00c6190b5c.png)

**A link to a Sandbox site where the bug has been reproduced https://oxygenbuilder.com/try? (REQUIRED)**
*Provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*

https://oxygen-qgjwhk9t553c.oxygen-demo.qsandbox.me/

**IF YOU CAN'T PROVIDE A SANDBOX REPRODUCTION: Steps required to reproduce the bug:**
1. Add your global styles as vars
2. Add you global color in the settings
3. Add a button to test
4. Choose global saved colors

**Comment by KittenCodes** [comment]
Duplicate: https://github.com/soflyy/oxygen-bugs-and-features/issues/2839
