### ISSUE TITLE
Highlighting text in a text block

### ISSUE THREAD

**Issue by PatMinich** [soflyy/oxygen-bugs-and-features#2840]
Morning I'm probably using the wrong string in search but I would like to highlight text using a different color or bold etc...
I am unable to find a tutorial for this and if it isn't a feature I would like to request it.  It would certainly help when building a funnel
If there is a tutorial on this please forward me the link

Thank you 
Patrick Minich
pat50n@aol.com

**Comment by KittenCodes** [comment]
@PatMinich You can highlight the text that you want to style differently and then click the "Span" button on the top toolbar. It will then become a separate element and you can style it differently.
