### ISSUE TITLE
PHP Fatal error on svg-icon class

### ISSUE THREAD

**Issue by obiPlabon** [soflyy/oxygen-bugs-and-features#2841]
On a fresh installation, I'm getting this error when trying to load in edit mode. 

PHP Fatal error:  Uncaught Exception: String could not be parsed as XML in `.../oxygen/component-framework/components/classes/svg-icon.class.php`

**Stack trace:**
```
#0 /Users/obiplabon/Sites/oxygen/wp-content/plugins/oxygen/component-framework/components/classes/svg-icon.class.php(197): SimpleXMLElement->__construct('')
#1 /Users/obiplabon/Sites/oxygen/wp-includes/class-wp-hook.php(307): CT_SVG_Icon->output_all_svg_sets('')
#2 /Users/obiplabon/Sites/oxygen/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters(NULL, Array)
#3 /Users/obiplabon/Sites/oxygen/wp-includes/plugin.php(474): WP_Hook->do_action(Array)
#4 /Users/obiplabon/Sites/oxygen/wp-includes/general-template.php(3058): do_action('wp_footer')
#5 /Users/obiplabon/Sites/oxygen/wp-content/plugins/oxygen/component-framework/oxygen-main-template.php(268): wp_footer()
#6 /Users/obiplabon/Sites/oxygen/wp-includes/template-loader.php(106): include('/Users/obiplabo...')
#7 /Users/obiplabon/Sites/oxygen/wp-blog-header.php(19): requ in /Users/obiplabon/Sites/oxygen/wp-content/plugins/oxygen/component-framework/components/classes/svg-icon.class.php on line 197
[24-Apr-2022 19:58:17 UTC] PHP Fatal error:  Uncaught Exception: String could not be parsed as XML in /Users/obiplabon/Sites/oxygen/wp-content/plugins/oxygen/component-framework/components/classes/svg-icon.class.php:197
```

**Possible Solution:**
```php
foreach ( $svg_sets as $set ) {

	if ( empty( $set ) ) {
		continue;
	}
	
	$svg = new SimpleXMLElement( $set );
```

**Comment by KittenCodes** [comment]
@obiPlabon

Please could you open a [Support Ticket](https://oxygenbuilder.com/support) so that we can take a look at your site?

**Comment by obiPlabon** [comment]
@KittenCodes you guys don't need to look at my site as I've given you both problem and solution. Besides, it's in my local development machine (so your team won't be able to access it) where I'm developing extensions for my client.

Thank you

**Comment by KittenCodes** [comment]
@obiPlabon

I need to be able to reproduce the issue for our development team. I am guessing that for some reason, the SVG icons are missing from your install, but I don't know if that's the case from reading the bug report.

**Comment by zartgesotten** [comment]
Having the same Error. Opening support ticket now!
