### ISSUE TITLE
Add Basic Elements or Remove Template Tags around Elements

### ISSUE THREAD

**Issue by Simbaclaws** [soflyy/oxygen-bugs-and-features#2847]
**Describe the feature you'd like to see included in Oxygen.**
*I want to be able to use for example* ```<input>``` *tags or other html tags that I can create, like for example:* ```<textarea>``` *within oxygen builder. Just more basic html tags that we can use as basic oxygen elements in general...*

*If this isn't possible, then maybe add the option to remove the template tag around an oxygen element? 
(The surrounding div tag?). So that I can use my own code block if need be for example.
Maybe having a "none" option inside the tag dropdown... 
Right now I see no way of creating an input html element within the oxygen UI that should be inside of it's parent container.... 
I need this to create a javascriptless (css only) mega menu with custom code.
The :checked  css psuedo and ~ selector can be extremely useful IMO...*

**What are the use cases for this feature?**
*More flexibility in oxygen builder to create custom html elements*

**Examples of this feature or functionality.**
*For example you'd be able to make something like this in pure css: https://codepen.io/jakka/pen/NNQpoj without the need for javascript.*

**Comment by Simbaclaws** [comment]
If there is a way of creating a ```<input>``` tag within the oxygen builder UI. Please let me know any workarounds you know of. I need this for a client site.

**Comment by wplit** [comment]
> If there is a way of creating a `<input>` tag within the oxygen builder UI. Please let me know any workarounds you know of. I need this for a client site.

Yes, use the div element, you can change the tag to any custom tag, also you can add attributes etc so it's essentially a blank HTML element that you can use for anything.

**Comment by Simbaclaws** [comment]
Ah thank you I didn't realize the div tag could do this. I was using the code block and couldn't seem to remove the parent tag. Thank you this solves my issue.
