### ISSUE TITLE
Oxygen V4.0 Beta 2 : Oxygen Block With Code Block Does Not Render

### ISSUE THREAD

**Issue by jam1970** [soflyy/oxygen-bugs-and-features#2850]
Here is a **sandbox link** : https://oxygen-qrdylbaj8jwll.oxygen-demo.qsandbox.me/

When using Oxygen 4.0 Beta 2 and Oxygen Gutenberg Integration V1.4, Oxygen blocks do not render properly if they contain code blocks. I have created two blog posts, one called **Hello World** and the other called **Hello Universe**.

Inside **Hello Universe** there is an Oxygen block called **Block Test 1**
Inside **Hello World** there is an Oxygen block called **Block Test 2**

You can see that the Oxygen block **Block Test 1** does not work - it includes a code block. The output is a long string of characters.  It does however render properly in the editor.
Link to post : https://oxygen-qrdylbaj8jwll.oxygen-demo.qsandbox.me/hello-universe/

Oxygen block Block Test 2 works fine. It includes a heading, text and an icon.
Link to post : https://oxygen-qrdylbaj8jwll.oxygen-demo.qsandbox.me/hello-world/

**Comment by KittenCodes** [comment]
@jam1970 Thanks for the report! This has been fixed in the upcoming v4 RC1 release.
