### ISSUE TITLE
4.0 RC 1 - UX issue - DIV - Size & Spacing

### ISSUE THREAD

**Issue by Schokolader** [soflyy/oxygen-bugs-and-features#2856]
**Any bug report that doesn't include a Sandbox link or replication steps will be closed. If you can't provide these pieces of information, we're happy to help you via our official support channel instead: https://oxygenbuilder.com/support. You need to select "Something's broken and I need help" from the dropdown box on the left.**

**Describe the bug**
You can't see the values in the Size & Spacing of a div. And the UX looks broken. https://share.getcloudapp.com/wbuzlAqj

**A link to a Sandbox site where the bug has been reproduced https://oxygenbuilder.com/try? (REQUIRED)**
*Provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*

**IF YOU CAN'T PROVIDE A SANDBOX REPRODUCTION: Steps required to reproduce the bug:**
1. Add Section
2. Add DIV 
3. Go to Size & Spacing 
4. See the UX issues in Padding / Margin 
5. +You can't see the values

**Comment by Schokolader** [comment]
This does exist on Firefox Dev. On Chrome it seems ok.

**Comment by KittenCodes** [comment]
@Schokolader I've not been able to reproduce this on Windows via Firefox Developer edition. Are you using Windows or Mac?

**Comment by Schokolader** [comment]
I cleared the cache and it seems it was only a cache issue.
