### ISSUE TITLE
PHP notices (although no concrete problem)

### ISSUE THREAD

**Issue by its-thomas** [soflyy/oxygen-bugs-and-features#286]
We have installed the latest Oxygen on a brand new WP installation as the only plugin besides an unobtrusive PHP error log monitor and played around with Oxygen as described in the official "Getting Started Tutorial" video. While playing around, said PHP log has registered over 300 PHP notices related to Oxygen (no errors, mind you!), although no "real" problems were encountered.

- WordPress Version 5.1.1
- Oxygen Version 2.3
- Error Log Monitor Version 1.6.5
- PHP Version 5.6.38 (added this piece of information after @davidfavor's remark)

Link: [PHP log](https://pastebin.com/U9txH20j)

**Comment by davidfavor** [comment]
Actually this is a problem.

Simple notice can be prompted to Fatals with any new release of PHP.

Best to always run with WP_DEBUG enabled + ensure 100% quiet logs.

This way when a real problem does occur, the problem stands out + is very easy to see.

**Comment by its-thomas** [comment]
Update: After having played around with the Oxygen 2.4 Release Candidate 1 like described in the first post, there are still some PHP notices displayed (although this time on a different PHP version). See this new [PHP log](https://pastebin.com/2pW1X8eq) for details.

- WordPress Version 5.2.1
- Oxygen 2.4 Release Candidate 1
- Error Log Monitor Version 1.6.6
- PHP Version 7.2.16

Keep up the great work on an excellent product! :+1:

**Comment by KittenCodes** [comment]
Fixed in v3.6.
