### ISSUE TITLE
Query Users

### ISSUE THREAD

**Issue by OJGaming** [soflyy/oxygen-bugs-and-features#2860]
I'd like to see the ability to query users in repeaters instead of just posts. Elementor can do this, but I can't figure out how to do it in Oxygen.

You could show a list of users based on role, status, etc.

**Comment by portseif** [comment]
+1

**Comment by Kpudlo** [comment]
Closing as duplicate of https://github.com/soflyy/oxygen-bugs-and-features/issues/2257
