### ISSUE TITLE
Oxygen 4 RC1 - Loading="Eager" attribute added by default to images

### ISSUE THREAD

**Issue by Jamie-owens** [soflyy/oxygen-bugs-and-features#2868]
**Describe the bug**
When adding an image in 4.0 RC1, by default, I see loading="eager". This changes to lazy upon ticking the lazy load option in the image settings.

This is a problem as my hosts optimisation software can't seem to override this and it stays as loading="eager". This is not an issue on 3.9.

**Steps to reproduce the behavior**
1. Add image to a page/template.
2. Select image from media library or image url.
3. View image on front end and inspect the image.
4. You will see loading="eager".

**Comment by KittenCodes** [comment]
@Jamie-owens 

Would you mind letting me know what type of loading you see on the image of the person on the page here: https://jubilantaddax.build067.wpsandbox.app/index.php/about-me/.

I see Lazy when viewing the site in Chrome on Windows 11.

Did you upgrade from v3.9 to the RC, or are you using a clean install?

**Comment by Jamie-owens** [comment]
@KittenCodes

Hi,

I found out that my host uses javascript to lazy load images and not the attribute method so there is no conflication as I previously thought.

Yes I can see lazy as the attribute for the image. The attribute of loading eager is added to images for both upgrades from 3.9 and fresh installs.

I no longer believe I have any issues as when I change loading to lazy, it does state loading lazy on front end. I would just like to mention again that on version 4rc1, the default loading of eager is added to images which was not there in 3.9. I am not sure if this is an issue but wondered why it was present in version 4rc1.

**Comment by KittenCodes** [comment]
@Jamie-owens,

"eager" has been added as the default in v4 - we added it when we added the lazy loading option. It's not a bug.
