### ISSUE TITLE
OXYGEN 4.0 RC1:  FILTER WITH WPGRIDBUILDER WITH A CODEBLOCK INSIDE A REPEATER GIVES A MEANINGLESS TEXT

### ISSUE THREAD

**Issue by RaulGandia** [soflyy/oxygen-bugs-and-features#2869]
I **Describe the bug**
Hello, I have a repeater, filtered by WP GRIDBUILDER. Inside the repeater I have several codeblocks to format fields. When I load the page for the first time, or do a hard refresh, everything is displayed fine, but when I filter through WP GRIDBUILDER, all the fields that are inside a codeblocks are displayed as a long meaningless string of text. The problem comes with version 4 RC1, since with 4 Beta 2 it works perfectly.

You can test in a sandbox..
i put one codeblock with a simple "hello world" text. 

If you re-intall Oxygen 4 Beta 2, works fine, with RC1 works bad..

https://oxygen-qv9wqlcsdh3ll.oxygen-demo.qsandbox.me/home/

**Comment by KittenCodes** [comment]
Thanks for the report! Reported internally.

**Comment by Spellhammer** [comment]
@RaulGandia We're working with the developer of WP Gridbuilder to figure out exactly what's happening here. It's likely we'll do a small release following 4.0 to address this and any other issues that may crop up.

**Comment by RaulGandia** [comment]
Thanks so much for your fast response

**Comment by Spellhammer** [comment]
@artur-burkalo Please contact us via https://oxygenbuilder.com/support with full details and login credentials and we will investigate.

Aside from the report above, this issue has been resolved in 4.0.1 RC 1 which is now available via the customer portal.
