### ISSUE TITLE
Frontend shortcut in Oxygen editor on multisite setting

### ISSUE THREAD

**Issue by pogeunpark** [soflyy/oxygen-bugs-and-features#287]
**Describe the bug**
*A clear and concise description of what the bug is.*

The frontend shortcut in Oxygen editor on multisite setting does not work.
It does not give an error or something. It is just not responding to a click.

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
*Yes/No*

There was no multisite setting to test it on.

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
*If yes, provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*

**To Reproduce**

**Expected behavior**
*A clear and concise description of what you expected to happen.*

**What actually happens**
*A clear and concise description of what happens instead of the expected behavior.*

**Screenshots**
*If applicable, add screenshots to help explain your problem.*

**Desktop (please complete the following information):**
- OS: [e.g. iOS] - macOS
 - Browser [e.g. chrome, safari] - Chrome latest.
 - Oxygen Version [e.g. 2.2 Alpha] - latest

**Smartphone (please complete the following information):**
 - Oxygen Version [e.g. 2.2 Alpha]

**Additional context**
*Add any other context about the problem here.*

**Comment by KittenCodes** [comment]
@pogeunpark, Please can you let me know the exact steps I need to follow to be able to reproduce this issue? What kind of post were you trying to edit? If you disable all plugins (aside from Oxygen), do you still have the issue?
