### ISSUE TITLE
Tranform not saving media queries v4.0 RC1 and 3.9

### ISSUE THREAD

**Issue by Gibsonion** [soflyy/oxygen-bugs-and-features#2872]
**The bug:**
When adding a media query to a transform such as translate, I've found multiple times, the media query version overwrites the previous input and when trying to save values of 0 while it's saved in the editor, the CSS file output renders as blank.

i.e. If I set my Translate to 25% in desktop, then try to save 0 in a media query the output simply reads:

`transform: ;`

screenshot: https://prnt.sc/nPCXJ63vqy12

**Sandbox:** https://oxygen-qjy36gkzsy4ll.oxygen-demo.qsandbox.me/sample-page/

1. make an element with a transform for desktop
2. set a media query level and then try to set a new transform to override the first with a value of 0
3. Check result on the front end and view the broswers inspect.

**Comment by KittenCodes** [comment]
@Gibsonion 

It's not caused by the media query as such. There's an issue where setting the value to 0 doesn't work: https://github.com/soflyy/oxygen-bugs-and-features/issues/794#issuecomment-573636364.

Please try the custom CSS workaround in that comment.
