### ISSUE TITLE
All page and template shortcodes have been overwritten by half of the main template shortcode

### ISSUE THREAD

**Issue by jessebrightman** [soflyy/oxygen-bugs-and-features#2875]
We changed the domain on our WP install and was updating the database for additional domain instances (Better Search Replace) when all the Oxygen shortcodes became corrupted and were replaced by half of the Main template shortcode.  In this way, we could not even open the edit post page to check the actual shortcodes themselves but a quick query to the ct_builder_shortcodes showed that all 200+ shortcodes are now identical and 99% of the site page content is gone.  I had hoped to extract the shortcodes from the db to a fresh install but that is not possible as of now.  All of the ct_builder_shortcodes_revisions are also identical.  I have no idea how this could happen and any steps to reproduce it or anything that could relate to this situation or solving it.  Just don't want anyone else have to go through this mess.

**Any bug report that doesn't include a Sandbox link or replication steps will be closed. If you can't provide these pieces of information, we're happy to help you via our official support channel instead: https://oxygenbuilder.com/support. You need to select "Something's broken and I need help" from the dropdown box on the left.**

**Describe the bug**
*A clear and concise description of what the bug is.*

**A link to a Sandbox site where the bug has been reproduced https://oxygenbuilder.com/try? (REQUIRED)**
*Provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*

**IF YOU CAN'T PROVIDE A SANDBOX REPRODUCTION: Steps required to reproduce the bug:**

**If you can't fill out the above information, you should not be filing a bug report. Instead, contact us via https://oxygenbuilder.com/support with the details you have and we'll investigate your issue further.**

**Comment by jessebrightman** [comment]
Global settings are also corrupted.  Basically, the whole thing is gone.  6 month project ruined. Backup pulled from corrupted db so it's toast too.

**Comment by jessebrightman** [comment]
It's funny too that the shortcode that overwrote everything is from months ago.  Trying to find some silver lining here.

**Comment by KittenCodes** [comment]
I've replied to your support ticket this morning.

One thing I didn't ask is if you have a full server backup from before you changed the domain? If you do, I'd appreciate it if you could restore that onto a new server and include the details in a reply via the ticket.
