### ISSUE TITLE
Ability to Disable Links/Link Wrappers in Editing Mode

### ISSUE THREAD

**Issue by Colgen** [soflyy/oxygen-bugs-and-features#288]
I would love the ability to disable the links/link wrappers in editing mode so we could edit the content (for example: changing texts in buttons, changing texts in text links, etc.) rather than going to the actual link every time we try to edit the text/content itself.

Hope that makes sense.  Thank you!

**Comment by alpabuz** [comment]
Yes, it's really inconvenient. Especially when customers try to use the Oxygen editor themselves

**Comment by pdipatrizio** [comment]
Please do something to fix this. The issue makes link wrappers nearly impossible to work with. This suggestion is more of a necessity than an enhancement.

**Comment by Colgen** [comment]
> Please do something to fix this. The issue makes link wrappers nearly impossible to work with. This suggestion is more of a necessity than an enhancement.

Agreed.  It is more of a necessity than an enhancement.    Just needs "Active" or "Live" & "Not Active" or "Not Live" buttons at the top or underneath the URL.  It'll make it a whole lot easier when dealing with links of any sort.

**Comment by wpdevlab** [comment]
👍

**Comment by KittenCodes** [comment]
The latest version of Oxygen no longer follows links as you're editing the URLs in the builder.

**Comment by gkarmas** [comment]
This is still an issue on custom buttons. For example <button onclick="location.href='https://site/sub/'" type="button" > takes me to the page link on the editor

**Comment by TheCartographerDev** [comment]
In Editor just select the element which is linked to something, go to the custom css tab in the editor bar and enter

`pointer-events: none;`
