### ISSUE TITLE
Oxygen 4.0 RC 1: Code Block in page/post doesn't render when viewed in Template Preview

### ISSUE THREAD

**Issue by maltmann-muc** [soflyy/oxygen-bugs-and-features#2886]
Oxygen 4.0 RC 1

**Describe the bug**
A Code Block contained in a page/post created with Oxygen does not render correctly when this page/post is previewed in Oxygen Builder template. 
Displays as binary data. Seems to be improperly or double encoded/decoded.

**Link to Sandbox**
https://oxygen-qp6c9jm9q297.oxygen-demo.qsandbox.me/

**Steps required to reproduce the bug:**
1. Create a Template with Inner Content element, Catch All. Save.
2. Create a page or post and edit with Oxygen. Add a Code Block. Save.
3. Open the Template again in Builder and select this page or post for preview.

**Screenshots**
Post with Code Block in Oxygen Builder: 
<img width="1742" alt="Bildschirmfoto 2022-05-18 um 14 52 02" src="https://user-images.githubusercontent.com/51136650/169044154-8243db28-0f51-4fb5-93ee-1ec8a4c4871d.png">

Post with Code Block when previewed in Template:
<img width="1745" alt="Bildschirmfoto 2022-05-18 um 14 52 51" src="https://user-images.githubusercontent.com/51136650/169044267-e7bda2f1-1d07-47be-85e7-c16e0bce7f59.png">

**Comment by KittenCodes** [comment]
Thanks for the report! This has been fixed internally, and the fix will be available in the next RC release of v4.
