### ISSUE TITLE
Oxygen 4 RC1 - Attributes are not saved in classes

### ISSUE THREAD

**Issue by Schokolader** [soflyy/oxygen-bugs-and-features#2890]
**Describe the bug**

If you add a custom class and add something into attributes it is not saved in the class. If you use this class again on another element the custom attributes are gone.  

**IF YOU CAN'T PROVIDE A SANDBOX REPRODUCTION: Steps required to reproduce the bug:**
1. Add a blog template and create a table of contents with the composite elements 
2. This toc uses all headings of the page into the table. You can now exclude headings via a custom class toc-skip 
3. Into this custom class toc-skip you have to add an attribute of toc-skip with the value 1 
4. Now you can add this class to every heading or parent div and it excludes all headings from the table of contents
5. Problem is that the attributes are not saved in the class. Therefore you have to add the attribute with the value 1 again and again for every heading or parent div you want to exclude. I would expected that the attribute is saved in the custom class and that you can use the custom class of toc-skip everytime you want to exclude a heading from a toc. 

**If you can't fill out the above information, you should not be filing a bug report. Instead, contact us via https://oxygenbuilder.com/support with the details you have and we'll investigate your issue further.**

**Comment by Spellhammer** [comment]
HTML attributes can't be saved to classes, that's just not how CSS classes work unfortunately.
