### ISSUE TITLE
20px padding on Header Builder element

### ISSUE THREAD

**Issue by shIxx01** [soflyy/oxygen-bugs-and-features#2891]
**Describe the bug**
There is a 20px padding left and right when using the Header Builder element.

**A link to a Sandbox site where the bug has been reproduced https://oxygenbuilder.com/try? (REQUIRED)**
https://oxygen-qt6qy8k8qdaml.oxygen-demo.qsandbox.me/sample-page/

1. Make a new Template
2. Click "add" and add the Header Builder
3. Set every width to "full width"
4. Set the background color to see the padding and margin 
5. Add some Text to make the div's visible in the frontend
6. When you inspect in Chrome you will see a class called "oxy-header-container" and here is the 20px padding left and right. but this class is not visible on the Header Builder element in the editor. 
7. Same in Oxygen 3.9 as well as in RC 4.0

How to fix:
Add a class called "oxy-header-container" on the Header Builder element and set the padding to 0

**Comment by KittenCodes** [comment]
@shIxx01 This isn't a bug. It takes the left and right padding values from Oxygen's Global Styles > Sections & Columns > Section Container Padding.
