### ISSUE TITLE
Saving does not save, builder window showing different than live page

### ISSUE THREAD

**Issue by jessebrightman** [soflyy/oxygen-bugs-and-features#2896]
Saving does not save, builder window showing different than live page.  CSS for one block is showing on another block.  divs and elements are all randomly placed

**Any bug report that doesn't include a Sandbox link or replication steps will be closed. If you can't provide these pieces of information, we're happy to help you via our official support channel instead: https://oxygenbuilder.com/support. You need to select "Something's broken and I need help" from the dropdown box on the left.**

**Describe the bug**
*A clear and concise description of what the bug is.*

**A link to a Sandbox site where the bug has been reproduced https://oxygenbuilder.com/try? (REQUIRED)**
*Provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*

**IF YOU CAN'T PROVIDE A SANDBOX REPRODUCTION: Steps required to reproduce the bug:**

**If you can't fill out the above information, you should not be filing a bug report. Instead, contact us via https://oxygenbuilder.com/support with the details you have and we'll investigate your issue further.**

**Comment by jessebrightman** [comment]
Now the builder will not load and results in a hung broswer.  All plugins deactivated to debug with same result.  Restoring earlier known working versions also had same result.  No access to anything on this page at all.  Only solution is to start a new page from scratch (yet again).

**Comment by jessebrightman** [comment]
It was the repeater module causing memory leakage.  I removed the repeater in the shortcodes and the page loaded once again.

**Comment by KittenCodes** [comment]
> It was the repeater module causing memory leakage. I removed the repeater in the shortcodes and the page loaded once again.

Thanks for letting us know. Are you able to reproduce this on our [Sandbox site](https://oxygenbuilder.com/try/) so that we can take a look, or do you no longer need help?
