### ISSUE TITLE
Lazy load enabled by default even it's not marked in the editor

### ISSUE THREAD

**Issue by Bebuk85** [soflyy/oxygen-bugs-and-features#2897]
Hi, all of my images of my staging site are having the lazy load attribute getting conflicts with the preload function of FlyingPress, of no detecting the images above the fold.

WP 6.0 - Oxygen 4.0

**Comment by KittenCodes** [comment]
@Bebuk85 Are you able to reproduce this on a clean [Sandbox site](https://oxygenbuilder.com/try/) so that we can take a look please?
