### ISSUE TITLE
DONE: allow Repeater to set a Tag e.g. <ul> to create a list

### ISSUE THREAD

**Issue by tobiashaas** [soflyy/oxygen-bugs-and-features#2899]
**Describe the feature you'd like to see included in Oxygen.**
If you could Tag the repeater as < ul > and the div inside as < li >, then you could easily create compliant lists using Dynamic Data

**What are the use cases for this feature?**
Create comliant Lists inside a Repeater

**Comment by Schokolader** [comment]
Does it not work when the repeater is wrapped with a div? And there the custom tag <ul> is added.

**Comment by Vyyt02** [comment]
Please add this. It is important for accessibility.

**Comment by gslwebsolutions** [comment]
With Oxygen's increasing number of updates centered on accessibility, I hope this gets pushed soon.

**Comment by Kpudlo** [comment]
Similar to https://github.com/soflyy/oxygen-bugs-and-features/issues/2353

**Comment by Spellhammer** [comment]
Implemented in 4.6 Beta 1
