### ISSUE TITLE
Oxy 4.0 breaks Conditional Logic in Oxy Gutenberg Blocks on Frontend

### ISSUE THREAD

**Issue by ReMeWebsolutely** [soflyy/oxygen-bugs-and-features#2900]
**Any bug report that doesn't include a Sandbox link or replication steps will be closed. If you can't provide these pieces of information, we're happy to help you via our official support channel instead: https://oxygenbuilder.com/support. You need to select "Something's broken and I need help" from the dropdown box on the left.**

**Describe the bug**
*A clear and concise description of what the bug is.*

When using GB Integration 1.4 or 1.4.1 with Oxy 3.9 Conditional Logic works in Blocks as expected (Tested with User Role and Logged In Status). After upgrading to Oxy 4.0 Conditional Logic is at least broken on the frontend but seems to work in the backend still.

This is true for WP 5.9.2 and 6.0

**A link to a Sandbox site where the bug has been reproduced https://oxygenbuilder.com/try? (REQUIRED)**
*Provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*

The Post I used the Block in:
https://oxygen-q68kjhr9yxcml.oxygen-demo.qsandbox.me/gb-test-block-1-post/

I made 4 backups for your convenience (only restore Plugins and Database). All ot them with WP 5.9.2 as I could not update the sandbox to 6.0, but tested it with WP 6.0 on one of my servers.

1. Oxy 3.9 with GBI 1.4
2. Oxy 3.9 with GBI 1.4.1
3. Oxy 4.0 with GBI 1.4.1
4. Oxy 4.0 with GBI 1.4

You can find them right here:
https://oxygen-q68kjhr9yxcml.oxygen-demo.qsandbox.me/wp-admin/options-general.php?page=updraftplus&tab=backups

**IF YOU CAN'T PROVIDE A SANDBOX REPRODUCTION: Steps required to reproduce the bug:**
6. Click on '....'
7. Scroll down to '....'
8. See error

**If you can't fill out the above information, you should not be filing a bug report. Instead, contact us via https://oxygenbuilder.com/support with the details you have and we'll investigate your issue further.**

**Comment by KittenCodes** [comment]
@ReMeWebsolutely Please try the new RC releases of Oxygen and Oxygen's Gutenberg add-on from the [Customer Portal](https://oxygenbuilder.com/portal/). The issues you're seeing should be resolved.

**Comment by ReMeWebsolutely** [comment]
Worked for me. Thank You.
