### ISSUE TITLE
Updated to 4.0 - can not edit templates, repeaters show "Array" in place of products, product pages broken

### ISSUE THREAD

**Issue by Journeytojah** [soflyy/oxygen-bugs-and-features#2906]
**Describe the bug**
*A clear and concise description of what the bug is.*

Upgraded to the latest version of Oxygen and Woocommerce elements. I can not edit any page that is a template, products in repeaters show "Array" and all product pages are completely broken.

**IF YOU CAN'T PROVIDE A SANDBOX REPRODUCTION: Steps required to reproduce the bug:**
Not a sandbox, but can be seen [here](https://staging2.thaishades.com/)

**If you can't fill out the above information, you should not be filing a bug report. Instead, contact us via https://oxygenbuilder.com/support with the details you have and we'll investigate your issue further.**

I have cleared the cache, re-signed all shortcodes, but still no change.

**Comment by Journeytojah** [comment]
I have managed to get into editing templates and saving them fixed the broken product pages.

The site uses Translatepress and it looks like the "Edit Template" button no longer takes the language into the URL.

Repeaters still shows "Array" instead of products.

**Comment by Spellhammer** [comment]
Please send details and login credentials for the effected site to us at support@oxygenbuilder.com so we can do a thorough investigation.
