### ISSUE TITLE
not rendering php code-blocks when called via ajax

### ISSUE THREAD

**Issue by barrychapman** [soflyy/oxygen-bugs-and-features#2911]
**Describe the bug**
When rendering facets (ajax requests to the content) it is not rendering or parsing the encrypted PHP code block

**A link to a Sandbox site where the bug has been reproduced https://oxygenbuilder.com/try? (REQUIRED)**
www.weedys.com/products

https://user-images.githubusercontent.com/152958/171557471-e42d46a2-1f74-45e7-97de-163706fee695.mp4

**Comment by tkwebreform** [comment]
same here. confirmed from wp grid builder support as a problem with double base64 encoded code blocks

**Comment by albertvisuals** [comment]
+1 Same issue encountered with WP GridBuilder

**Comment by yannicklmb** [comment]
Same issue here. Also with WP GridBuilder.
![bugcodeblock](https://user-images.githubusercontent.com/106824519/171877079-f5f704b0-3745-469f-938c-34d686ceb5b8.PNG)

**Comment by shmaltz** [comment]
I had a similar issue after updating to 4.0. I fixed it by simply opening the template and clicking save, without making any changes. Somehow that fixed it for me.

**Comment by albertvisuals** [comment]
Have just tried to re-save the template, sadly it does not work. Seems there is a bug in 4.0 as WP-builder support mentioned, double base64 encoded code blocks

**Comment by perrelet** [comment]
+1

**Comment by Spellhammer** [comment]
We have a fix for this. We're doing some final testing. We should have a 4.0.1 RC 1 out soon which will resolve this and some other 4.0 bugs.

**Comment by albertvisuals** [comment]
Great! Thanks a lot

**Comment by Spellhammer** [comment]
Fixed in 4.0.1 RC 1, which is now available in the customer portal.
