### ISSUE TITLE
I can not access JSON data editing a page

### ISSUE THREAD

**Issue by jgbbob8** [soflyy/oxygen-bugs-and-features#2912]
After updating to 4.0 one of my istallations can not access JSON data.
I only can access Shortcodes (read only) information, but clciking into JSON label nothing happens.
I have made all regeneations stpes, but nothing.

Any idea?

**Comment by maltmann-muc** [comment]
Hard-refresh this page in browser: Ctrl-F5 (Win) or Shift-Cmd-R (Mac). 
That brings up the Plus sign (+) in front of the JSON label and lets you open the JSON box.
