### ISSUE TITLE
Oxigen Builder 4 - Superbox inside a repeater

### ISSUE THREAD

**Issue by movipixel** [soflyy/oxygen-bugs-and-features#2913]
Please check this link to see the problem. The SuperBox only shows state 2 not state 1

https://oxygen-qyy63q8tppa8.oxygen-demo.qsandbox.me/sample-page/

**Comment by EDGFX** [comment]
Also having issues with Superbox within a Repeater:

How State 1 looks in the builder: 
![image](https://user-images.githubusercontent.com/86821237/171682362-17d99f48-f556-4bd1-8c14-46e87a2a0c75.png)

How State 2 looks in the builder: 
![image](https://user-images.githubusercontent.com/86821237/171682702-fe722016-2cd1-4475-bded-a048a9e01d3b.png)

What I see on front-end with no interaction:
![image](https://user-images.githubusercontent.com/86821237/171682774-25d5ef0e-8a37-4318-adf3-d19af611dfc2.png)

**Comment by EDGFX** [comment]
Any updates on this issue? This is resulting in a delay of a website deployment for me.

**Comment by Benoit-TUFFERY** [comment]
Bonjour, 

(Français)
Je voudrait savoir ou en est le bug avec SUPERBOX + REPEATER ?

Je fais remonter le soucis qui pénalise mon site également, SuperBox ne fonctionne pas dans repeater même constat seulement l'état 2 sur front seulement !, même en régénérant le cache CSS rien.

J'ai refais de zero avec nouvelle version et idem même problème !

Help la Team Soflyy.

**Comment by KittenCodes** [comment]
This will be fixed in v4.0.1.
