### ISSUE TITLE
When placing a link wrapper inside repeater div, and dynamic taxonomy inside link wrapper, the layout breaks.

### ISSUE THREAD

**Issue by the-stew** [soflyy/oxygen-bugs-and-features#2916]
**Describe the bug**
When adding a link wrapper inside the main div of a repeater, if you then place a text element and then dynamically pull in taxonomy data, it breaks the layout of the repeater div, pushing the taxonomy outside of the element. I have also tried using a code block to pull in the taxonomy data and the same thing happens.

The issue only presents itself when viewing on the frontend. It looks as expect when inside the builder.

**A link to a Sandbox site where the bug has been reproduced**
https://oxygen-qf4cv7kfaygml.oxygen-demo.qsandbox.me/test/

**Also, here is a video of me recreating it on that demo site:** https://www.screencast.com/t/yLpxfrbgl

**Steps to reproduce the behavior:**
1. Place a repeater
2. Query posts or any other post type
3. Place a link wrapper inside the main repeater div, give width and height 100%
4. Add a background colour/image, some padding, and min-height to link wrapper (to make issue more noticeable)
5. Place a heading inside link wrapper, dynamically pull post title (to see how other elements react).
6. Place a text element inside link wrapper, dynamically pull taxonomy (category or tags)
7. Save and view on frontend (issue does not present inside builder)

**Comment by KittenCodes** [comment]
@the-stew This is expected as you're essentially creating a nested link, which is invalid HTML. You would need to set the parent Div of the Link Wrapper position to Relative, then add the dynamic data to that Div, set its position to Absolute and then position it using the top, left, bottom and right positions.
