### ISSUE TITLE
Inner Content element set to the <main> tag doesn't add the <main></main> on archives (Oxygen 4.0)

### ISSUE THREAD

**Issue by AlkoKod** [soflyy/oxygen-bugs-and-features#2923]
Hey all, when I use the inner content in my main template with header and footer and I set the inner content tag to be a <main> it works when I edit page directly, but it doesn't add the main element on archive templates.

1. Create main template with header, inner content, footer, set it to catch all
2. Set inner content to custom tag <main>
3. Create template for blog post index or taxonomy archive, or other template (for pages, posts)...
4. Open blog post index, check the code and <main></main> is missing.

When I go to pages>select page and edit it directly with Oxygen:

![obrazek](https://user-images.githubusercontent.com/52713604/172584685-47c5aaf6-316b-4168-8ef5-1613a97ddc59.png)

When I create a template for blog posts index or category archive which inherits the main template:

![obrazek](https://user-images.githubusercontent.com/52713604/172584830-10841163-0a15-46d5-9b76-733433145c38.png)

**Comment by Spellhammer** [comment]
This appears to be because the Inner Content element is actually replaced by the content within it on templates inheriting the template containing the Inner Content element.

Assuming you're adding a Section to contain your Easy Posts/Repeater on your sub-templates, you can just set the Section tag to ```main```.

**Comment by AlkoKod** [comment]
@Spellhammer aha! Good to know but not expected behavior from my side.
