### ISSUE TITLE
Javascript from codeblock gets replaced by strange alphanumeric string when "edit with gutenberg" is active

### ISSUE THREAD

**Issue by DrZivil** [soflyy/oxygen-bugs-and-features#2925]
**Javascript from codeblock does not work when "edit with Gutenberg" is active**

**A link to a Sandbox site where the bug has been reproduced **
https://oxygen-q2bggc3pakjml.oxygen-demo.qsandbox.me/sample-page/
-> js console and html

**Steps required to reproduce the bug:**
1. Add Code Block
2. add some js (in my case `console.log('hello world');`
3. check "edit with gutenberg"
4. watch error in frontend

![without-gutenberg-editing](https://user-images.githubusercontent.com/5269825/172929846-2ec956a8-44bd-4daa-b00b-bd5bf3803c5f.PNG)
![with-gutenberg-editing](https://user-images.githubusercontent.com/5269825/172929850-e4d276c8-3bea-44f8-9969-d57c114e5f81.PNG)

**Comment by KittenCodes** [comment]
@DrZivil Thanks for the report. This will be fixed in the next release.
