### ISSUE TITLE
Custom SVG Icon set doesn't show up in the Builder at all

### ISSUE THREAD

**Issue by afroniquely** [soflyy/oxygen-bugs-and-features#2926]
I have followed the steps of making the icomoon svg file (the symbols-def.svg) that included the <title> in the download. I am able to upload the symbols-def file to the site. However once in Oxygen builder, if I add an icon element and then switch to the custom icon pack, nothing shows up at all, I get blank squares.

Sandbox site where the bug has been reproduced: [Sandbox Link](https://oxygen-qwttt9mywvjml.oxygen-demo.qsandbox.me/?ct_template=main&ct_builder=true)

(In the top area under the oxy logo, there is an added icon element, but nothing shows up there, nor in the editor).

I can also provide the original symbols-def file if needed.

**Comment by schietegal** [comment]
Have you already counter-tested the behavior with a guaranteed working icon set?
e.g. this: https://wpdevdesign.com/google-fonts-material-icons-svg-icon-set-for-oxygen/

**Comment by afroniquely** [comment]
Just did the counter test.. Seems that one is working, however no indications as to why the original wouldn't be working? Inspected both codes and they appear the same format, no weird extras etc. So not sure what's triggering this strange issue.

**Comment by schietegal** [comment]
In your Icon set are [more than 2 icons](https://oxygenbuilder.com/documentation/other/custom-svg-icon-sets/)?

**Comment by afroniquely** [comment]
It did, but I just remade the file and added more, now it shows up! whew. Thank you.
