### ISSUE TITLE
Easy post issue with Oxygen Gutenberg editor

### ISSUE THREAD

**Issue by mpiguet** [soflyy/oxygen-bugs-and-features#2929]
When you check "Make this entire page editable in GUTENBERG" on a page that contains an Easy Post, the content of the Easy Post is replaced by a code.

https://oxygen-qntksary93kml.oxygen-demo.qsandbox.me/test/

**Comment by KittenCodes** [comment]
@mpiguet This should be fixed in the RC releases of Oxygen v4.0.2 and v1.4.3 of Oxygen's Gutenberg add-on. You can get both from the [Customer Portal](https://oxygenbuilder.com/portal/).
