### ISSUE TITLE
404 error when trying to edit new page.

### ISSUE THREAD

**Issue by Jironasaurus** [soflyy/oxygen-bugs-and-features#293]
So I recently logged into Wordpress -- after having not touched it for the last month or so -- and something broke with Oxygen.  I got this message:

"Oxygen encountered a 404 error while loading the builder.

Please re-save your permalinks under Settings > Permalinks in the Wordpress admin panel.

I tried that, and it didn't work.  I also deactivated all plugins, but the issue was still there.

So I upgraded Oxygen from v2.2 to v2.3.  And the issue is still there.

I checked the FB group, and apparently other people are having the same problem, but it seems that no one has a solution.  Am kinda hoping someone here has answers for me...

(PS:  I know Oxygen has issues with caching, so I have to disable my Siteground cache plugin each time I wanna edit a page that's already published.  But this issue only comes up when I try to edit a new page [not saved].  Disabled the cache and it still doesn't work.)

**Comment by Jironasaurus** [comment]
Just to add... this issue occurs only when I click on "Add New" for pages without entering a page title or any content, and immediately trying to edit the page with Oxygen.

If I were to enter a title and save the draft, I'm able to go into the Oxygen builder.

**Comment by quadcom** [comment]
That is how the editor has worked from the beginning.

New page > add title > save draft > open Oxy

**Comment by Jironasaurus** [comment]
My bad then.  I always assumed you could just add in the title later.
