### ISSUE TITLE
Menu Not Responsive

### ISSUE THREAD

**Issue by richardjalba** [soflyy/oxygen-bugs-and-features#2934]
There is an issue with the menu. On multiple websites I've been working on, I can't get the menu to be responsive. I've used Oxygen many times before without any issues.

When you view the websites on mobile, the menu will change to the hamburger menu. But when you click the hamburger menu, the color may change (if the CSS for active/hover is enabled) but the actual menu will not appear.

By default, the entire screen is supposed to be taken over by the menu. But due to the bug, the menu screen doesn't appear at all.

The following links are my own test website, followed by the Oxygen sandbox.

http://richarda104.sg-host.com/home/blog/

https://oxygen-qh7s4wrgramml.oxygen-demo.qsandbox.me/bug/

Note: Both websites used the same default Header provided by Oxygen. The only difference is the logo images and font weight + letter spacing. There's no reason why the Header Menu shouldn't be working on my own test site, or the other sites I've been building lately. I keep my Headers as close to what Oxygen provides as possible.

Please notify me what the possible issues and solutions could be. I have clients that want this issue addressed, so I'd really appreciate it. Thank you.

**Comment by richardjalba** [comment]
I've updated the following:

http://richarda104.sg-host.com/home/blog/

The Header is the exact same as the one in the Oxygen sandbox link, but the one on my own test website does not work.

**Comment by KittenCodes** [comment]
@richardjalba I'm sorry for the delay here. If you're still having problems, please open a [Support Ticket](https://oxygenbuilder.com/support) so that we can take a look at your site.
