### ISSUE TITLE
Accordion javascript doesn't close other active (open) accordions once another unopened is clicked

### ISSUE THREAD

**Issue by janknop** [soflyy/oxygen-bugs-and-features#2940]
This code doesn't remove active class and doesn't add hidden class to active accordion content. 

Not working code is located between " >>>>> Doesn't work <<<<<< " markers below:

//** Oxygen Composite Elements Settings Section **//
//** Edit the variables below to change the behavior of the element. **//

var closeOtherToggles = true; // Set this to true to close all other accordions when an accordion is expanded.

//** That's it, stop editing! **/
var ready = (callback) => {
  if (document.readyState != "loading") callback();
  else document.addEventListener("DOMContentLoaded", callback);
}

ready(() => { 
	// Expand the content when row is clicked.
	document.querySelectorAll('.oxel_accordion__row').forEach( accordion => {
		accordion.addEventListener('click', function(e) {
			accordion.classList.toggle('oxel_accordion__row--active');
			accordion.nextElementSibling.classList.toggle('oxel_accordion__content__hidden');
			
			if( closeOtherToggles == true ) {
				accordion.parentElement.querySelectorAll('.oxel_accordion__row--active').forEach( row => {

                                       >>>>> Doesn't work <<<<<<

					if( row != accordion ) { 
						row.classList.remove('oxel_accordion__row--active');
						row.nextElementSibling.classList.add('oxel_accordion__content__hidden');
					}

                                       >>>>> Doesn't work <<<<<<
				});
			}
		})
	})

});

**Comment by KittenCodes** [comment]
@janknop Please reproduce this on our [Sandbox site](https://oxygenbuilder.com/try/) and post a link to it so that we can take a look. If you can't reproduce this, please open a [Support Ticket](https://oxygenbuilder.com/support) so that we can take a look at your site.
