### ISSUE TITLE
Alt Text cryptic for pictures in reusable part

### ISSUE THREAD

**Issue by ectu** [soflyy/oxygen-bugs-and-features#2944]
<img width="1405" alt="Bildschirmfoto 2022-06-17 um 08 56 38" src="https://user-images.githubusercontent.com/78073705/174243155-89d07b78-b918-4418-bab6-4bce71ba674e.png">

**Comment by KittenCodes** [comment]
@ectu Are you able to reproduce this on our [Sandbox site](https://oxygenbuilder.com/try/)? If so, please post a link to the Sandbox site and I can re-open the issue.
