### ISSUE TITLE
DONE: WooCommerce Integration/Support built into Oxygen (please)

### ISSUE THREAD

**Issue by peterode** [soflyy/oxygen-bugs-and-features#295]
All other major themes, designers and page builders have deep integration and support for WooCommerce.  OxygenBuilder should have a proper, world-class WooCommerce integration.

Use cases include high performance display of ecommerce pages. WooCommerce typically slows a WordPress site but Oxygen can help to offset that.

Oxygen should have pre-built templates for: WooCommerce Home pages (several styles); Product category page, Single product per page (several templates), Search by several filters...

The business case for OxygenBuilder: 41% of all eCommerce sites use WooCommerce. These are site owners that don't mind spending money on building a proper money-making web site.  By having the best performing & best looking WooCommerce templates can differentiate OxygenBuilder. See: https://hollerwp.com/woocommerce-statistics/

**Comment by peterode** [comment]
Here's a great add-on for WooCommerce for those using the Divi Theme: https://diviengine.com/product/divi-bodycommerce/  It has some great features, that are most commonly requested for Woo sites.  Hopefully the Divi-BodyCommerce plugin can provide some useful ideas for OxygenBuilder to implement as part of its Woo integration/support. Thanks.

**Comment by KittenCodes** [comment]
WooCommerce integration added in Oxygen v3.
