### ISSUE TITLE
The elements in oxygen builder is not displayed properly

### ISSUE THREAD

**Issue by banashreejt** [soflyy/oxygen-bugs-and-features#2950]
1. Go to 'edit oxygen'
2. Elements are not displayed properly

<img width="954" alt="oxygen error" src="https://user-images.githubusercontent.com/107867688/174622165-f41314a2-b647-4647-8ae6-7fb6a6322f22.PNG">

**Comment by arsh999cg** [comment]
Just hard refresh the browser.

**Comment by KittenCodes** [comment]
Please either reproduce the issue on our [Sandbox site](https://oxygenbuilder.com/try/), or open a [Support Ticket](https://oxygenbuilder.com/support) so that we can take a look at your site.
