### ISSUE TITLE
Responsive image size srcset not working in 4.0

### ISSUE THREAD

**Issue by Knoclar** [soflyy/oxygen-bugs-and-features#2954]
**Describe the bug**
When adding image element, you can't set different image size for different screen size like before
If you set the image size on large screen to "full" and "medium" for small screen, when you came back to large screen, It not "full" anymore but "medium"
In short you can set ONE image size for all you screen size

**Sandbox link**
https://xanthousplover.build067.wpsandbox.app/

**Screenshot link**
https://i.imgur.com/Hbtu2Fw.gif
![firefox_HhFORfewki](https://user-images.githubusercontent.com/48055858/174738118-19af3e7b-432d-4259-83da-3ef0352a6e08.gif)

1. Go to Oxygen , add template and edit it with oxygen | or edit a page with oxygen
2. Click on "add element" and add a section
3. Click on "add element" and add an image element
4. Under "media library", browse the media library and use any image you have
5. On large screen view, set size to "full"
6. Switch to small screen view, and set size to "medium"
7. Go back to large screen view and see that the size value became the same as the small screen size => medium

**Environnement**
WordPress Version 6.0
Oxygen version 4.0
not other plugin enabled

**Comment by Spellhammer** [comment]
Media library images use srcset, which means the most appropriate size of image is loading automatically, so you don't need to specify sizes on breakpoints.
