### ISSUE TITLE
Heading Text Overlap in Install a Website

### ISSUE THREAD

**Issue by osmgit** [soflyy/oxygen-bugs-and-features#2955]
Just a really small bug I noticed on a fresh install when installing a design set. The heading text overlaps if it goes on the next line. Only happens for "Marketing Agency B"

Oxygen > Home > Install a Website > Marketing Agency B > Install

The heading text will be overlapped when it drops down onto the next line since there is no line height specified.

**Comment by KittenCodes** [comment]
@osmgit Would you mind adding a screenshot please as I don't seem to have been able to find the issue.

Thanks!
