### ISSUE TITLE
impossible remove <u> tag from span in text widget

### ISSUE THREAD

**Issue by mredodos** [soflyy/oxygen-bugs-and-features#2960]
is impossible remove <u> from span in text decoration and if you  apply text decoration none on the span not work because is on parent but remove style not remove the <u> tag

![image](https://user-images.githubusercontent.com/42175654/175177778-fd5a7a6b-e059-426e-98a6-cef6bca39a58.png)

**Comment by KittenCodes** [comment]
Please either reproduce the issue on our [Sandbox site](https://oxygenbuilder.com/try/), or open a [Support Ticket](https://oxygenbuilder.com/support) so that we can take a look at your site.
