### ISSUE TITLE
Parse error: syntax error

### ISSUE THREAD

**Issue by picarda** [soflyy/oxygen-bugs-and-features#2966]
Hello, I got this when I activate Oxygen.

Parse error: syntax error, unexpected 'if' (T_IF), expecting function (T_FUNCTION) or const (T_CONST) in /var/www/html/mywebsite.com/wp-content/plugins/oxygen/component-framework/includes/oxygen-connection.php on line 2489

WordPress 5.9.3 running.
Debian 10
Php 7.4
* All other plugin are deactivate. I try with just Oxygen and I got this error.

Thank you.

**Comment by KittenCodes** [comment]
Please either reproduce the issue on our [Sandbox site](https://oxygenbuilder.com/try/), or open a [Support Ticket](https://oxygenbuilder.com/support) so that we can take a look at your site.
