### ISSUE TITLE
Reusable Parts added as Single inside Repeater Items are not repeated in 4.0.1

### ISSUE THREAD

**Issue by pkboy** [soflyy/oxygen-bugs-and-features#2970]
**Describe the bug**

As title says, if you have a repeater and add a reusable part inside of the repeated div, it only shows up in the first spot and not the other items

Sandbox link:
https://oxygen-q2lqrgwgssrml.oxygen-demo.qsandbox.me/test/

**IF YOU CAN'T PROVIDE A SANDBOX REPRODUCTION: Steps required to reproduce the bug:**
1. Create a reusable part, add some text in it and save
2. Go to a page / template, add a repeater and set query for some posts
3. Add the reusable part as a single inside the repeated div
4. Save and view page. Only first item has the text from the reusable part.

**If you can't fill out the above information, you should not be filing a bug report. Instead, contact us via https://oxygenbuilder.com/support with the details you have and we'll investigate your issue further.**

**Comment by pkboy** [comment]
Also a temporary way around this:

add a code block where the reusable part should go then inside the code block add the following php
<?php
echo do_oxygen_elements( json_decode( get_post_meta( 56, 'ct_builder_json', true ), true ) );
?>

where 56 is the ID of the reusable part

working example:
https://oxygen-q2lqrgwgssrml.oxygen-demo.qsandbox.me/test-2/

**Comment by niko-1** [comment]
> add a code block where the reusable part should go then inside the code block add the following php

@pkboy  What's the code?

**Comment by pkboy** [comment]
> > add a code block where the reusable part should go then inside the code block add the following php
> 
> @pkboy What's the code?

@niko-1  Oops forgot to surround w/ code markdown

**Comment by addoklopman** [comment]
Same issue broke a few of my sites

**Comment by Spellhammer** [comment]
Fix committed internally, slated for 4.0.2.

**Comment by adrien-robert** [comment]
> Fix committed internally, slated for 4.0.2.

Can you mark this as completed if that's the case please?

**Comment by Spellhammer** [comment]
@adrien-robert Thanks for the reminder. Closing this as fixed in 4.0.2.
