### ISSUE TITLE
Publishing failed. The response is not a valid JSON response.

### ISSUE THREAD

**Issue by mikeadkins52** [soflyy/oxygen-bugs-and-features#2971]
This started occurring since going to version 4.  I just updated to Version 4.0.1 and it is still occurring.  Every time I go to create a new page, then enter the page Title, then Publish, then confirm by clicking Publish again, I get the message "Publishing failed. The response is not a valid JSON response."  

I reset the permalinks, and then regenerate the CSS.  I even open an Incognito Window to assure this is not coming from cookies or cache.  I have logged out of the site and back in and it still occurs.

Why is this happening?  Google Search is not helping me resolve this issue.  I have also turned off all the plugins.  On this site I only have one and that is Ninja forms and I have it turned off.  I am out of options.  HELP!!!

**Comment by mikeadkins52** [comment]
Doing further research, the REST API error is displayed but could be a result of bad Java code being sent to the server.  How do I check this?

**Comment by mikeadkins52** [comment]
Final Update - I disabled Oxygen and tried to create a page and got the same error.

**Comment by KittenCodes** [comment]
> Final Update - I disabled Oxygen and tried to create a page and got the same error.

Thanks for letting us know. Closing.
