### ISSUE TITLE
Metabox Taxonomy Fields Not Showing Up

### ISSUE THREAD

**Issue by shmaltz** [soflyy/oxygen-bugs-and-features#2974]
I added an image custom field to a custom taxonomy using Metabox, and I want to use that image as a hero section background on the taxonomy archive.

When clicking the data button next to the background image field in the section settings, and then clicking Metabox, the custom field doesn't show up. (In fact, none of my custom fields added to the taxonomy show up - only the regular post custom fields show up).

Is this because the integration doesn't work with term meta fields? Or is this a bug?

**Comment by KittenCodes** [comment]
@shmaltz Unfortunately, Oxygen's dynamic data doesn't yet support retrieving fields from taxonomies.

That said, if you're using a Single Image field, then you can try adding the following code to the [Code Snippets](https://wordpress.org/plugins/code-snippets/) plugin:

```php
function my_get_mb_single_image($field) {
	
        $term_id = get_queried_object_id();
	$image = rwmb_meta($field,['object_type'=> 'term','size'=>'thumbnail'],$term_id);

	return $image['url'];
}
```

To use it in Oxygen, you need to click Data > PHP Function Return Value. Enter the function name my_get_mb_single_image and in the arguments box, enter the slug of your Meta Box field.

**Comment by shmaltz** [comment]
Thank you!
