### ISSUE TITLE
Rename element

### ISSUE THREAD

**Issue by Brandinwebdesign** [soflyy/oxygen-bugs-and-features#2975]
i Dont know if it is a bug or a feauture request. So correct my if i'm wrong

When renaming an element and you use enter then it gives after the name <br> is it also possible to use enter so that it just changes the name? This would work a lot easier and improve the workflow.

**Comment by KittenCodes** [comment]
@Brandinwebdesign I'm sorry, I'm not sure what you mean by "it gives after the name". Please could you explain further?

**Comment by Brandinwebdesign** [comment]
I see you fixed it in 4.0.2 RC!

**Comment by Brandinwebdesign** [comment]
@KittenCodes  I see its not 100% fixed. Only in the strucure panel. If i want to change the name of a ellement en press enter on my keyboard h wel gives a br after the name. See 2 printscreens

Using enter on keyboard:

<img width="291" alt="Schermafbeelding 2022-07-26 om 11 51 37" src="https://user-images.githubusercontent.com/71370585/180978271-d166a2b6-7bc4-4fb5-a98f-6d7ee34c0b23.png">
without using enter on keyboard:

<img width="294" alt="Schermafbeelding 2022-07-26 om 11 51 13" src="https://user-images.githubusercontent.com/71370585/180978275-0cfdc3df-5950-48e5-8c93-fc3f05c62b63.png">
