### ISSUE TITLE
Oxygen Promenu Issue

### ISSUE THREAD

**Issue by dineshvlr** [soflyy/oxygen-bugs-and-features#2977]
After update Lastest Version of oxygen 4.01

* After updated Edited Header Footer Template, update any one element saved the template, then pro menu affected in our web page

attached screenshot for your reference @Spellhammer

![Untitled](https://user-images.githubusercontent.com/108391167/176374364-4f0557cf-5148-4fb5-bb3a-440b493721e8.png)

**Comment by KittenCodes** [comment]
@dineshvlr Please either reproduce the issue on our [Sandbox site](https://oxygenbuilder.com/try/), or open a [Support Ticket](https://oxygenbuilder.com/support) so that we can take a look at your site.
