### ISSUE TITLE
Inner Content tag (and wrapper) disappears after design being inherited from another template

### ISSUE THREAD

**Issue by wittywolk** [soflyy/oxygen-bugs-and-features#2979]
**Any bug report that doesn't include a Sandbox link or replication steps will be closed. If you can't provide these pieces of information, we're happy to help you via our official support channel instead: https://oxygenbuilder.com/support. You need to select "Something's broken and I need help" from the dropdown box on the left.**

**Describe the bug**
*A clear and concise description of what the bug is.*
If you inherit the design from another template the tag which was set for the 'Inner Content' disappears, and the wrapper also.
![image](https://user-images.githubusercontent.com/100383145/176464249-3a7187a7-a44b-472d-b742-3cba48a15508.png)

**A link to a Sandbox site where the bug has been reproduced https://oxygenbuilder.com/try? (REQUIRED)**
*Provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*
https://oxygen-qzf692qvx8sml.oxygen-demo.qsandbox.me/wp-admin/post.php?post=66&action=edit

**IF YOU CAN'T PROVIDE A SANDBOX REPRODUCTION: Steps required to reproduce the bug:**
1. Make template main - header (tag header), inner content (tag main), footer (tag footer).
2. See frontend for page - everything is fine - header, main with content, footer.
3. Make template for posts; inherit design from main (because why make header/footer again) - put dynamic content.
4. See frontend for post - header, content (not being wrapped with main, although editor suggest it'll be because it is inside 'Inner content'), footer.

I fix it myself with wrapping everything in templates different to main with div and set the tag to main; if this is expected behaviour then in my opinion it is misleading because of how the builder show us everything when editing template.

**If you can't fill out the above information, you should not be filing a bug report. Instead, contact us via https://oxygenbuilder.com/support with the details you have and we'll investigate your issue further.**

**Comment by yawBrooks** [comment]
I'm also facing similar issues with a lot of sites i built with oxygen builder. The solution was to regenerate css cache and sign all shortcodes. After, went to the base theme(theme with inner content) to update and went to the other themes that was inheriting this base theme. 

This is a long way around it. Oxygen builder devs should find a way of resolving this

**Comment by wittywolk** [comment]
> I'm also facing similar issues with a lot of sites i built with oxygen builder. The solution was to regenerate css cache and sign all shortcodes. After, went to the base theme(theme with inner content) to update and went to the other themes that was inheriting this base theme.
> 
> This is a long way around it. Oxygen builder devs should find a way of resolving this

This is a fresh demo install, same happened on my fresh built websites. Your solution doesn't work for me, sorry.

**Comment by KittenCodes** [comment]
Thanks for the report!

Duplicate: https://github.com/soflyy/oxygen-bugs-and-features/issues/1930.
