### ISSUE TITLE
Why did you kick me out of the Oxygen facebook group?

### ISSUE THREAD

**Issue by zbyneksmetana** [soflyy/oxygen-bugs-and-features#2983]
Why did you kick me out of the Oxygen facebook group? Two days in a row, I was first fired from the Bricks group (I even received a personal letter from the Bricks creator saying "I don't have to love Bricks") then a fired from the Oxygen group?

**Comment by Kpudlo** [comment]
Hello @zbyneksmetana, 

Please open a ticket via our support form where we'll be able to provide further insight regarding this issue: https://oxygenbuilder.com/support
