### ISSUE TITLE
Dynamic Section Background Image Not Working

### ISSUE THREAD

**Issue by shmaltz** [soflyy/oxygen-bugs-and-features#2990]
Dynamic Section Background Image Not Working

As the title says.

I have a function that outputs an image url, and I want to use that as the section background, however when I set up the image background to use a dynamic function, the whole section disappears from the frontend (It shows the image correctly in the backend).

If I echo my function, it does output the correct full url to the image.

The section shows up in the DOM like this:
```
[hidden], template {
  display: none;
}
```

**TEST FUNCTION**
Add this function to a plugin to test:
```
function testimage() {
    $image = 'https://images.pexels.com/photos/8289302/pexels-photo-8289302.jpeg';
    return $image;
}
```

**Comment by KittenCodes** [comment]
@shmaltz I've not been able to reproduce this on a Sandbox site.

If you're still having problems, please open a [Support Ticket](https://oxygenbuilder.com/support) so that we can take a look at your site.

**Comment by shmaltz** [comment]
Thanks for having a look @KittenCodes .

This issue seems to have been caused by WP GridBuilder's "Filter Custom Content" setting which injects html onto the page.
I disabled that setting and all is good.
