### ISSUE TITLE
Convert Oxygen site to static HTML site

### ISSUE THREAD

**Issue by Crey100** [soflyy/oxygen-bugs-and-features#2994]
Request:
I would like to have the option to easily convert the Oxygen site to a static non-WordPress site. I have done this by hand (it really takes a lot of time tediously picking through the files and code) but am thinking it would be so much nicer to be more automatic.

This would be useful when:
When a client does not need to do edits themselves. For sites that don't have posts. For cutting down on hosting disc space. For security, when a site is getting a lot of WordPress hack attempts.

Another Product that does this (but not for Oxygen):
The WordPress plugin "Simply Static" works for WordPress sites but does not convert the Oxygen files needed for the site.

**Comment by jessebrightman** [comment]
Definitely a nice to have feature that I would endorse.  Sometime ago, I built a plugin that turns WP into static files but one would need a second server to send the static files to.

**Comment by Kpudlo** [comment]
Duplicate of https://github.com/soflyy/oxygen-bugs-and-features/issues/2994
