### ISSUE TITLE
Repeater not displaying an element in a resuable

### ISSUE THREAD

**Issue by devs-wm4d** [soflyy/oxygen-bugs-and-features#2996]
**Any bug report that doesn't include a Sandbox link or replication steps will be closed. If you can't provide these pieces of information, we're happy to help you via our official support channel instead: https://oxygenbuilder.com/support. You need to select "Something's broken and I need help" from the dropdown box on the left.**

**Describe the bug**
*A clear and concise description of what the bug is.*

**A link to a Sandbox site where the bug has been reproduced https://oxygenbuilder.com/try? (REQUIRED)**
*Provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*

**IF YOU CAN'T PROVIDE A SANDBOX REPRODUCTION: Steps required to reproduce the bug:**
1. Go to ['...'](https://oxygen-qby3gxkxrjzml.oxygen-demo.qsandbox.me/)
- No Icons or element / reusable shown on "inspect" after first data...
- I added a codeblock for one edit update.. but i also added the Image element with conditions with the same purpose as the codeblock.. but both image element and codeblock are not showing on the remaining data... pls check link and screenshots..
- we use the reusable because the data needs to be pulled to a page and to a popup... so we need it as we keep updating and adding more sources..

**If you can't fill out the above information, you should not be filing a bug report. Instead, contact us via https://oxygenbuilder.com/support with the details you have and we'll investigate your issue further.**

https://oxygen-qby3gxkxrjzml.oxygen-demo.qsandbox.me/

![Screenshot_3](https://user-images.githubusercontent.com/75340108/178316342-94220484-00a6-4fb1-9616-6043e075dbf7.png)
![Screenshot_4](https://user-images.githubusercontent.com/75340108/178316347-7ee92f17-0ef4-478f-87d9-f3aec500741d.png)
![Screenshot_5](https://user-images.githubusercontent.com/75340108/178316350-a13227fa-b4ad-4e7d-a914-bf8dee0d1850.png)
![Screenshot_6](https://user-images.githubusercontent.com/75340108/178316354-fd98f1e1-2865-46ae-be09-3c877caae20a.png)
![Screenshot_7](https://user-images.githubusercontent.com/75340108/178316358-c4311d97-4035-4b24-92d9-1ec3c5e17753.png)
![Screenshot_8](https://user-images.githubusercontent.com/75340108/178316365-a6afaf47-33c7-45c3-99c0-ca445065bf6d.png)
![Screenshot_10](https://user-images.githubusercontent.com/75340108/178318453-7c3f3baf-fda8-43e8-98e7-9c2e7d0e1268.png)

**Comment by devs-wm4d** [comment]
i must add.. this one was working before updating to 4.0.. we had no issues with it on version 3.8

**Comment by KittenCodes** [comment]
@devs-wm4d This has been fixed in v4.0.2, which is currently available as an RC release from the [Customer Portal](https://oxygenbuilder.com/portal/).
