### ISSUE TITLE
Full page Gutenberg blocks are not editable by users without Oxygen access

### ISSUE THREAD

**Issue by sdafrontdev** [soflyy/oxygen-bugs-and-features#2997]
Please see sandbox site at https://oxygen-qrh7x299fgc8.oxygen-demo.qsandbox.me/

After clicking the checkbox for "Make this full page editable in Gutenberg", users with permission to edit pages should be able to see the page content and make edits within Gutenberg. However, with the current default settings, users who are not Admins see a message like [Your site doesn’t include support for the "oxygen-vsb/ovsb-home" block. You can leave this block intact or remove it entirely.]

A possible workaround is to go to Oxygen settings > Client Control and give at least Edit Only access to the user role in question. I tested with the Editor Role as well as a custom role. After doing that, the Oxygen-generated Gutenberg block shows up as expected when editing a page as a user with the Editor role.

This workaround is not ideal because my clients are not used to seeing anything about Oxygen when editing pages. It used to be that they could edit the content of pages via Gutenberg without needing access to Oxygen, and I would like for that to still be an option if at all possible. It is just simpler that way without having to give users access to Oxygen.

I have taken the steps below to reproduce this issue on the sandbox site home page at https://oxygen-qrh7x299fgc8.oxygen-demo.qsandbox.me/home/ with the following user account set to the Editor role:
username: tester
passsword: ofmnB4o7dYw37d7T)pNuSjuZ

1. Go to a page created with Oxygen and check the box for "Make this full page editable in Gutenberg"
2. Click on update to save the changes
3. Create a new user account with the Editor role
4. log out as an admin and then log in as the new Editor account
5. Navigate to edit the page that should be editable in Gutenberg
6. Find the error message [Your site doesn’t include support for the "oxygen-vsb/ovsb-home" block. You can leave this block intact or remove it entirely.]

Thank you for creating Oxygen and thank you in advance for your support with this issue!
![msedge_lp5DqSLNqH](https://user-images.githubusercontent.com/80837754/178561247-2731af66-45a8-46da-87aa-8a9f44db5047.png)

**Comment by Spellhammer** [comment]
This is fixed in Oxygen 4.0.2 RC 1 which was just released.

**Comment by sdafrontdev** [comment]
Thank you @Spellhammer - I'm not seeing the updates available yet but will keep an eye out.
