### ISSUE TITLE
universal.css file not updated on save (OXY4.0.x - PHP8)

### ISSUE THREAD

**Issue by mikeingz** [soflyy/oxygen-bugs-and-features#2998]
Each time I try to modify the style of an element, via one of his class, it's not updated in the frontend.
Here is what I found out : 

- The file universal.css is NOT updated (that's why the modifications are not visible in the frontend)
- Here is the PHP Fatal error I got after saving a page : 

![image](https://user-images.githubusercontent.com/2438157/178920675-244b9570-474d-47f3-84d6-f294207debca.png)

Note : it's a website, created with Oxy 2 and updated...20 times ?! This issue doesn't seem to happen on a brand new WP installation.
No issue either with PHP 7.4

**Comment by KittenCodes** [comment]
@mikeingz Please could you open a support ticket so that we can take a look at your site?
