### ISSUE TITLE
Display ACF Fields backend vs frontend

### ISSUE THREAD

**Issue by LordWhisper** [soflyy/oxygen-bugs-and-features#300]
**Describe the bug**
Advanced Custom Fields

While the code works fine in the backend, it's not pulling data from get_field(); in the frontend.

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
YES

**Expected behavior**
Display data in frontend the same way it does in the backend. 

**What actually happens**
the_field() and get_field() is empty in frontend while it pulls the data in backend. 

**Screenshots**
![image](https://user-images.githubusercontent.com/4968737/57582833-eaea8f80-74c9-11e9-9880-a5ff77f9e6a8.png)

![image](https://user-images.githubusercontent.com/4968737/57582837-f938ab80-74c9-11e9-9376-100cb677fed5.png)

**Desktop (please complete the following information):**
All kind of browsers.
Oxygen 2.3 (latest) 

**Additional context**
Data is created using ACF Advanced Forms. This creates a CPT af_entries which is supposed to be pulled. Data should be displayed in a page via Code Block.

**Comment by LordWhisper** [comment]
Awesome - when sending my issue it deleted all content and replaced it with the template. :(

**Comment by LordWhisper** [comment]
Edited the issue now and reopened it.

**Comment by KittenCodes** [comment]
@LordWhisper 

I suspect this is caused by a conflict with another plugin on your site. If you disable all plugins (aside from ACF and Oxygen), does the data display?

If that doesn't help, please email site credentials to support@oxygenbuilder.com.
