### ISSUE TITLE
ACF image field not appear in Oxy Repeater Dynamic Data Panel Oxy 4.0

### ISSUE THREAD

**Issue by 1101blueli** [soflyy/oxygen-bugs-and-features#3000]
Hello. 

Actually, it does. But it appears on the panel from the image URL tab's dynamic data button.
By default, the Media Library Tab is selected. However, the dynamic data button does not work when pulling the ACF repeater image. It is confusing to the user. It took me a while to figure out we need to pull that from Image URL one. 

Thanks

**Comment by Tobbehj** [comment]
It's the same for Toolset

**Comment by Spellhammer** [comment]
This should be fixed in Oxygen 4.1 beta 1.
