### ISSUE TITLE
Warning : strpos() expects parameter 1 to be string, array given in

### ISSUE THREAD

**Issue by mentalpiggie1** [soflyy/oxygen-bugs-and-features#3008]
Describe the bug
I get a php error on single product page front end.

Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?
Yes/No

Yes
Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?
No, Sandbox doesn't have access to any product elements.

To Reproduce
    Go to '[this single product](https://y2streetwear.com/winkel/t-shirts/the-devil-faced/)'
    No further action needed to see the error.
    See error

Expected behavior
Visit a single product page and get the proper single product template.

What actually happens
A clear and concise description of what happens instead of the expected behavior.
Visit a single product page and get greeted with the message
Warning
: strpos() expects parameter 1 to be string, array given in
/home/customer/www/y2streetwear.com/public_html/wp-content/plugins/oxygen/component-framework/api/oxygen.element-selector.class.php
on line
197

Notice
: Array to string conversion in
/home/customer/www/y2streetwear.com/public_html/wp-content/plugins/oxygen/component-framework/api/oxygen.element-selector.class.php
on line
207

before anything else on the page.

Screenshots

Desktop (please complete the following information):

    OS: Win 10
    Browser: Firefox & Chrome
    Oxygen Version: Version 4.0.1

Additional context
In oxygen 4.0.1 I'm getting the following error on my single product page;

Warning
: strpos() expects parameter 1 to be string, array given in
/home/customer/www/y2streetwear.com/public_html/wp-content/plugins/oxygen/component-framework/api/oxygen.element-selector.class.php
on line
197

Notice
: Array to string conversion in
/home/customer/www/y2streetwear.com/public_html/wp-content/plugins/oxygen/component-framework/api/oxygen.element-selector.class.php
on line
207

**Comment by KittenCodes** [comment]
@mentalpiggie1 Would you mind opening a [Support Ticket](https://oxygenbuilder.com/support) so that we can take a look at this for you please?

**Comment by mentalpiggie1** [comment]
> @mentalpiggie1 Would you mind opening a [Support Ticket](https://oxygenbuilder.com/support) so that we can take a look at this for you please?

Will do.
