### ISSUE TITLE
Section background image will not update once a class is applied.

### ISSUE THREAD

**Issue by JohnPaulDesign** [soflyy/oxygen-bugs-and-features#3025]
How to reproduce:

1. Open block library and add a new block
3. Using the editor, add a Section
4. Assign a background image to the Section using the media library. I set it to cover and 50% 50% position
5. The background image is applied
6. Add a class to the section. It does not make a difference if the class has any styles applied or not.
7. Update the background image using the media library. Either choose a new image or upload. Apply the new image
8. The background image does not change in the editor. There are no errors in the console or the UI
9. Remove the class from the Section
10. Attempt step 7 again - the background image will now update.

**Comment by Spellhammer** [comment]
Thanks for the report.

You can't override ID styles with class styles. This is how Oxygen & CSS work intentionally.

If I've misunderstood the issue, please clarify and I can reopen.

**Comment by JohnPaulDesign** [comment]
There are no styles applied to the class. Just assigning a class prevents the background being updated from the editor.

**Comment by Spellhammer** [comment]
According to your steps, you're trying to override an ID assigned background image with a background image assigned via a class:

> 1.  Open block library and add a new block
> 2. Using the editor, add a Section
> 3. **Assign a background image to the Section using the media library. I set it to cover and 50% 50% position**
> 4. The background image is applied
> 5. **Add a class to the section. It does not make a difference if the class has any styles applied or not.**
> 6. **Update the background image using the media library. Either choose a new image or upload. Apply the new image**
> 7. The background image does not change in the editor. There are no errors in the console or the UI
> 8. Remove the class from the Section
> 9. Attempt step 7 again - the background image will now update.

Since you didn't specify switching between ID and class, I'm assuming that's what's happening. If I'm wrong, please provide clearer steps or a video so I can see what's happening and better understand the problem.

**Comment by JohnPaulDesign** [comment]
Ah, I see what is happening now. Thanks for your help! :)
