### ISSUE TITLE
Problem with CPT UI & ACF Relationship type field since 4.0.2 update

### ISSUE THREAD

**Issue by pcgreen-john** [soflyy/oxygen-bugs-and-features#3028]
I have created two CPTs, Services and Projects. There is an ACF group in CPT "Services" and one of the fields is "relationship" which is used for selecting multiple featured projects which draw from the CPT "Projects" and display on an advanced code slider. Repeater is a typical post__in with data from the relationship field.
Everything was working fine up to 4.0.1, after the update 4.0.2 it only gets the first element.
I tried a simple repeater without the fancy slider / swiper.js code but it still won't "repeat", just the first element.
I setup a sandbox as suggested by Oxygen support, with a simplified version of my structure, and the problem showed up as well.
I uploaded three projects and the repeater only gets the first one in the field.

Just click on "My amazing service" which takes you to an entry in CPT "Services". It uses the "Single Service" template (which has "Default" as a parent). In that template is the repeater which only gets the first Project.

https://oxygen-q2hgpm6wqcd8.oxygen-demo.qsandbox.me/

**Comment by andreslotta** [comment]
It works if you use the following settings when inserting the dynamic relationship field (I updated the demo accordingly – sorry for that 😄).

![CleanShot 2022-08-02 at 18 50 19](https://user-images.githubusercontent.com/12016014/182430619-2f19a531-5fc9-4d89-8991-faf3c6c2b482.png)

**Comment by pcgreen-john** [comment]
I'm dumbfounded right now, I could swear it worked perfectly before 4.0.2 just leaving it empty. Maybe it was taking these values as default but not since 4.0.2? I just added "," and "post_id" and it works perfectly! Thank you!
