### ISSUE TITLE
Pro menu horizontal/vertical problem on oxygen 4.0.2

### ISSUE THREAD

**Issue by aureldelic** [soflyy/oxygen-bugs-and-features#3030]
After upgrade to 4.0.2 I noticed my footer ProMenu became vertically stacked on desktop instead horizontally. I cleared all caches, server side too, resigned, checked code and menu settings, did some tests and saw that it works for a while on a NEW created menu if css cache is DISABLED, and while comparing both pages (one new where I tested and one existing) saw that on the problematic one it didn't load necessary css files for oxy-pro-menu-list class. After enabling css cache both pages showed erroneus menu.
After DOWNGRADE to 4.0.1rc1 everything works

Upgrade to Oxygen 4.0.2.
New page, add pro menu with couple of items
set menu to horizontal
Enable css cache
Refresh and see error

**Comment by Spellhammer** [comment]
Please submit a support ticket to support@oxygenbuilder.com with links to where we can see the problem and we'll investigate.
