### ISSUE TITLE
Changing Width on any Element resets measurement type (4.0.1)

### ISSUE THREAD

**Issue by theant06** [soflyy/oxygen-bugs-and-features#3031]
When changing any element's width / font size with a set measurement type (em, rem, vw, vh, etc), the editor will default back to px. 

As I cannot provide a sandbox reproduction, because it happens in editor, the steps I tend to do are:

1. Build Template
2. Need to change sizing on an element
3. Type new number into width setting (etc)
4. Measurement type will change to px
5. Change measurement type back.

**Comment by Spellhammer** [comment]
Thanks for posting this here.

> Need to change sizing on an element

Can you clarify what this means?

@theant06

**Comment by theant06** [comment]
For clarification, I have built out a template and realize as I'm designing that I need to adjust the size of an element. When I go to change the element size, say changing 50% to 30%, it'll change from 50% to 30px.

**Comment by Spellhammer** [comment]
> For clarification, I have built out a template and realize as I'm designing that I need to adjust the size of an element. When I go to change the element size, say changing 50% to 30%, it'll change from 50% to 30px.

Which size? Width? Are you changing the value on a breakpoint or for all devices?

**Comment by theant06** [comment]
Width, yes, on an individual element, for all devices. And it'll also happen at individual breakpoints.

**Comment by Spellhammer** [comment]
This behavior is expected & known when manipulating field values with units on breakpoints, where there's another unit besides px used on a larger breakpoint.

I'm unable to reproduce the unit switching after changing the field value in any other case, though. Can you do a quick screen recording so I can make sure I'm not missing any steps?

**Comment by Bebuk85** [comment]
https://user-images.githubusercontent.com/72046610/183219420-551047a2-17f9-4d37-9002-248a4070ef04.mp4

**Comment by Spellhammer** [comment]
Thanks for the screen recording. The issue you're showing is a known limitation of how we inherit units to smaller breakpoints. You have to redefine the unit on each breakpoint if you're not using PX.
