### ISSUE TITLE
Oxygen's "link button" doesn't handle links on headings properly.

### ISSUE THREAD

**Issue by kevingeary** [soflyy/oxygen-bugs-and-features#3034]
The proper HTML structure for a heading link is (linked text nested within heading tag):

<img width="488" alt="Screen Shot 2022-08-05 at 11 19 20 AM" src="https://user-images.githubusercontent.com/4367498/183113905-14ce59d9-7074-4712-8def-99ea4876e213.png">

When you add a heading in Oxygen and use the link button, the output you get is (link wrapping heading tag):

<img width="846" alt="Screen Shot 2022-08-05 at 11 18 58 AM" src="https://user-images.githubusercontent.com/4367498/183113951-0b0a18b5-6480-43af-89b5-01c7ae781b57.png">

If you select the text inside your heading and use the format bar link icon, you get the correct output. However, you then can't style your heading link with the builder because the builder fails to target the nested link (it only styles the heading tag).

Also, when using the correct linking method, you can no longer read your heading text in the builder:

<img width="841" alt="Screen Shot 2022-08-05 at 11 32 52 AM" src="https://user-images.githubusercontent.com/4367498/183114338-31f366ee-7027-487d-8a07-e4c4e29b2137.png">

This issue impacts the behavior of custom CSS as well as CSS frameworks like Automatic.css. We have to tailor the framework to work with the incorrect link structure. If someone uses the correct link structure method, certain custom CSS, ACSS, and Oxygen will all fail to target the link properly.

**Comment by Spellhammer** [comment]
> The proper HTML structure for a heading link is (linked text nested within heading tag)

Can you link to an MDN or other authoritative article indicating this is the definitively correct way to do it? I understand the argument based on nesting rules for block & inline elements, but it seems like that doesn't actually matter in this case as of HTML5.

> This issue impacts the behavior of custom CSS as well as CSS 

Can you please elaborate?
