### ISSUE TITLE
z-index Bug Related to Video Playlist Element

### ISSUE THREAD

**Issue by switchupcb** [soflyy/oxygen-bugs-and-features#3039]
**Describe the bug**
The `iframe` of a YouTube Embed in the Video Playlist takes priority over every other element regardless of the z-index.

**Steps required to reproduce the bug:**
1. Create a video playlist (as outlined in https://youtu.be/7lBjJBd5kv8?t=180)
2. Add an element that overlaps the title (or subscribe button, or controls, etc) and set it's z-index super high.
3. Go to frontend and click the element (which incorrectly causes the YouTube Iframe to do stuff).

# Solution
A solution is described in https://stackoverflow.com/questions/9074365/youtube-video-embedded-via-iframe-ignoring-z-index and https://stackoverflow.com/questions/50877667/youtube-video-and-z-index. Unfortunately, doing this is tedious with the Video Playlist.

## Embed
A video element can have it's code overridden to use manual `iframe` embed code. However, within the Video Playlist, other videos will continue to require the `&wmode=transparent` parameter. To be specific, the video playlist only allows the first video to have it's embed code manually specified. Subsequent videos would _theoretically_ require the user to input the URL with said parameters. This isn't necessarily an issue but can contribute to technical debt if the main URL/ID is what's expected later.

## Documentation
One "solution" is simply the documentation of how to solve this issue using the current feature, once it has been tested.

## Enhancement
Another solution is to build upon the current video and video playlist (entries) elements. Those elements specifically ask for a YouTube or Vimeo URL, so a useful feature may be to add an `advanced` setting where embed parameters _(or specifically the one that solves this issue)_ can be specified.

**Comment by Spellhammer** [comment]
Unable to reproduce. I'd recommend not overlaying other interactive elements on top of the iframe.

**Comment by switchupcb** [comment]
Sticky header
