### ISSUE TITLE
Error opening pages in Oxygen editor

### ISSUE THREAD

**Issue by zebrahosting** [soflyy/oxygen-bugs-and-features#304]
Currently moving an Elementor site to Oxygen with hundreds of pages in Learndash.
This went wel but more often I am now getting issues of not being able to open the page in Oxygen top edit. After clicking the wheel keeps spinning.
Re-assigned shortcuts and sometimes it works when I recreate the page. Some I never get back working.
See attachment for error in console.
Oxygen V2.3 and WP 5.5 PHP 7.3
<img width="473" alt="Screenshot 2019-05-14 at 15 48 57" src="https://user-images.githubusercontent.com/10379403/57707975-d395d880-7668-11e9-8d69-1c6fe596ace7.png">

**Comment by louisreingold** [comment]
The JS error looks to be related to another plugin based on the filename.

Disable all other active plugins and try again - then re-enable one by one to find the one causing the problem. Or email support@oxygenbuilder.com further assistance.
