### ISSUE TITLE
Conflict with Oxygen Builder and WP Indeed membership pro

### ISSUE THREAD

**Issue by igvsupport** [soflyy/oxygen-bugs-and-features#3042]
I am having a conflict issue with Oxygen and an image uploader on a membership plugin. See here: https://wwc2.igvdev.net/register/?lid=17

We are using a plugin called "Wp Indeed Ultimate membership pro" and it has an image uploader that is supposed to let you crop and save a photo upload. This feature works properly on all fronts UNLESS I turn on the Oxygen Builder with it. It even breaks with ONLY Oxygen and this membership plugin active. So it is a conflict between the two.
![oxy-upload-2](https://user-images.githubusercontent.com/110840843/183461901-425ab06a-27c6-44fc-aaca-8dae38a4bb1d.png)
![oxy-upload-error](https://user-images.githubusercontent.com/110840843/183461903-1d457e48-65ef-471c-bc17-b4451fa62ccc.png)
![without-oxygen-upload](https://user-images.githubusercontent.com/110840843/183461904-cbdfc0ed-86bc-40b7-b8a5-f072821b1d94.png)
![wwc2-4](https://user-images.githubusercontent.com/110840843/183461908-10f2e044-dc4e-401b-b26b-bfa3eb5d4358.png)
 See images.

The Membership plugin authors told me that it is an Oxygen issue and I should reach out to you guys.

1.) Go to: https://wwc2.igvdev.net/register/?lid=17
2.) Scroll down to the Avatar field with the upload button.
3.) Attempt the upload an image and see the results. The photo upload just places an image on screen and it just sits there does nothing until I refresh. 
4.) See the Wilma Flintstone image attached to see how this is supposed to work.

Any guidance would be helpful, thanks!

**Comment by Spellhammer** [comment]
> The Membership plugin authors told me that it is an Oxygen issue and I should reach out to you guys.

We'll need more details than that to take a look at this.

**Comment by Spellhammer** [comment]
@igvsupport Thanks for supplying additional details.

Please check to make sure the "Disable jQuery Migrate" option isn't checked under Oxygen > Settings > Bloat Eliminator: https://d.pr/i/jGAEhg. I expect that unticking this box will resolve the issue without any snippets needed.
