### ISSUE TITLE
Unwanted buttons and Oxygen builder not working on shop page

### ISSUE THREAD

**Issue by Nihtram** [soflyy/oxygen-bugs-and-features#3045]
Hi,

When I'm on a blank install and I add the WooCommerce plugin 2 things happen.

First, 6 buttons make their appearance at the bottom of any page of wordpress:
See home page: https://oxygen-qs87d2rh68dnl.oxygen-demo.qsandbox.me
They'r bearing the class "pswp" and i don't know if there is a simple solution for disabling them.

Second, The Oxygen builder doesn't work on the shop page. The shop page is determined in the Woocommerce's plugin settings:
See the shop page: https://oxygen-qs87d2rh68dnl.oxygen-demo.qsandbox.me/shop/?ct_builder=true

I'll attach images of the home page and the oxygen builder of the shop page if the sandbox link is down

![image](https://user-images.githubusercontent.com/72215369/183687073-ec8028b8-edc2-48f8-8dde-58d83b8acff8.png)

![image](https://user-images.githubusercontent.com/72215369/183687417-519ed9d8-8fb1-413e-8883-d10b606cf13e.png)

Sorry for my English, and I hope you'll understand my problems.

Regards

**Comment by Kpudlo** [comment]
Hi Nihtram, 

The issue is that the Sandbox doesn't have any products active on the installation. I've added some sample WooCommerce products to the Sandbox, and the Shop page now loads correctly.
