### ISSUE TITLE
oxygenbuilder template not translated on frontend by wpml if not logged in

### ISSUE THREAD

**Issue by davidperroud** [soflyy/oxygen-bugs-and-features#3048]
When user is not logged in, webiste with oxygen and wpml show the original template and not the correct translation. But, if user is logged in, the website shows the correct page and translation. 

the only way i found to avoid this is by comment 3 lines in /component-framework/admin/cpt-template.php
if(!oxygen_vsb_current_user_can_access()) {
return;
}

But i don't think it's a good idea, so i would be happy to have an official solution 
and official support between WPML and OXYGEN would be very very good !

**Comment by Kpudlo** [comment]
Related to WPML Integration Request #938.

**Comment by Spellhammer** [comment]
We don't offer any official support for WPML yet, unfortunately.
