### ISSUE TITLE
Repeater, Easy Post, Background Image from Featured Image make post page being counted twice by page view counter

### ISSUE THREAD

**Issue by readonecc** [soflyy/oxygen-bugs-and-features#3050]
Description:
I created a single post template using columns:
The first column contains post content such as: Post Title, Post Content, Post Meta, Taxonomy, Adjacent, and Comments
The second column contains widgets, the widget contains the latest posts from various post types.

The problem is:
I'm using page view counter, however every time the page is loaded the page counter will count it twice, this happens when:
1. I added a repeater or easy post element in the widget column.
2. I use a div element with a featured image background

The code I am now using for page view counter:
function getIzdanPostViews($postID){
    $count_key = 'post_views_count';
    $count = get_post_meta($postID, $count_key, true);
    if($count==''){
        delete_post_meta($postID, $count_key);
        add_post_meta($postID, $count_key, '0');
        return "0 View";
    }
 return $count.' Views';
}
 
function setIzdanPostViews($postID) {
    $count_key = 'post_views_count';
    $count = get_post_meta($postID, $count_key, true);
    if($count==''){
        $count = 0;
        delete_post_meta($postID, $count_key);
        add_post_meta($postID, $count_key, '0');
    }else{
        $count++;
        update_post_meta($postID, $count_key, $count);
    }
}
 
remove_action( 'wp_head', 'adjacent_posts_rel_link_wp_head', 10, 0);

Thank you.

**Comment by readonecc** [comment]
The problem is background image from featured image.

**Comment by Spellhammer** [comment]
We can't offer support/bug fixes for custom code like this.
