### ISSUE TITLE
Text section automatically added tag <b> to html content and making bold font on frontend

### ISSUE THREAD

**Issue by neografik** [soflyy/oxygen-bugs-and-features#3056]
When added Text from left menu, Oxygen 4.0.2 to frontend added <b> <b> tag to html element. Sorry but I can't reproduce this bug in sandbox :( 

![obraz](https://user-images.githubusercontent.com/28351686/184532469-fea29308-4680-48c3-b946-23d35c4f9e30.png)

**Comment by neografik** [comment]
<b> tag added when I added <bt> tag to Text Content box from left bar. Then automatically tags added to other elements below.

**Comment by Spellhammer** [comment]
Please contact us at support@oxygenbuilder.com so we can take a look at this on your site.
