### ISSUE TITLE
Oxygen conditions registered via conditions api are not being evaluated

### ISSUE THREAD

**Issue by FallenKN** [soflyy/oxygen-bugs-and-features#3058]
**Describe the bug**
Condition operators are being completly ignored and hence the condtions won't be evaluated.
I have followed the instructions on the [condition api](https://oxygenbuilder.com/documentation/other/conditions/) and created a code snippet plugin which registers a custom condtion.
In this example I have made the callback function just return the value true and created a page called test where I even created two sections and two divs wrapping around a textbox in the first section and a google maps snippet in the second one.
The condition of the first section is set to == true and the second one is set to == false.
This seems to get completly ignored as both sections are still displayed aslong as the function returns true. When the I set the function to return false both sections will be hidden.
This means the condition within the oxygenbuilder is not being evaluated and simply ignored.

**Code being used to register a condition via condition API**
```
if (function_exists( 'oxygen_vsb_register_condition')) {		
	oxygen_vsb_register_condition(
		'Google-Maps-Cookie',
		array('options'=>array('true', 'false'), 'custom'=>false),
		array('=='),
		'gmc_callback',
		'Other'
	);
}

function gmc_callback($value, $operator) {
	return true;
}
```

**Link to the sandbox**
https://oxygen-q8f7mr3ar5jnl.oxygen-demo.qsandbox.me/test/

**Comment by Spellhammer** [comment]
@FallenKN

It looks like your gmc_callback function isn't actually evaluating anything, it's just returning true all the time. This will result in all elements with this Condition applied being visible on the front-end.

You have to use the $value and $operator arguments to decide whether to return true or false. Returning false is what causes the element to be hidden.
