### ISSUE TITLE
Repeater data based on category cannot be styled correctly

### ISSUE THREAD

**Issue by ttump** [soflyy/oxygen-bugs-and-features#3059]
https://oxygen-qcvlxlv8a5d8.oxygen-demo.qsandbox.me/wp-admin/edit.php

A repeater field based on categories cannot have the color of the text set.

3 fields are used in the sandbox example - title, date and category. The Title and date work as expected. The category field displays in a default blue color. The size and font can be changed OK and any static label will change in color but the category name does not change in color

**Comment by ttump** [comment]
[https://oxygen-qcvlxlv8a5d8.oxygen-demo.qsandbox.me/wp-admin/edit.php](url)

A repeater field based on categories cannot have the color of the text set.

3 fields are used in the sandbox example - title, date and category. The Title and date work as expected. The category field displays in a default blue color. The size and font can be changed OK and any static label will change in color but the category name does not change in color

**Comment by ttump** [comment]
found duplicate of this - so closing

**Comment by ttump** [comment]
duplicate

**Comment by ttump** [comment]
Found duplicate

**Comment by Kpudlo** [comment]
Duplicate of #1539
