### ISSUE TITLE
DONE: Add rel="noopener" to links created with Oxygen

### ISSUE THREAD

**Issue by KittenCodes** [soflyy/oxygen-bugs-and-features#306]
Without the rel="noopener", site audits through chrome developer tools it always pulls up errors for all the social media icons and any external links, saying it's a security threat. And currently it's not something that we can edit easily in Oxygen.

Open the site in chrome, go to dev tools, then click on audit and then 'run audit'. You'll see the error: "Links to cross-origin destinations are unsafe".

To fix, please just add rel="noopener" to the html when also applying target="_blank", like in the case of the social icons where users can choose to link 'in a new tab'.

Requested by @wplit

**Comment by adrien-robert** [comment]
Any update on this?

**Comment by KittenCodes** [comment]
This is now possible.

**Comment by moserb12** [comment]
I can see that we can add attributes to links in most cases. However, I am unable to find this functionality in the social icons element found under the helpers section of the add element menu.

**Comment by silvenna** [comment]
Yes, please fix this for the social icons elements too! So annoying having to redo the social icons after discovering this.
