### ISSUE TITLE
Dynamic Data as a link in a text element breaks the builder

### ISSUE THREAD

**Issue by kylebarfuss** [soflyy/oxygen-bugs-and-features#3060]
When I create a text block, convert some of the text in the block to a span, then convert the span to a link and insert dynamic data, it basically breaks the builder. Causes weird stuff to happen when you add elements to the canvas afterward.

Video: https://www.loom.com/share/3379f2fdd80849f392df8d1bcac2f33e

Sandbox: https://oxygen-qwstx9p33pknl.oxygen-demo.qsandbox.me/sample-page/

**Comment by Spellhammer** [comment]
Thanks for the report! I've reproduced this and will report it internally for investigation.

**Comment by kylebarfuss** [comment]
Any update on this? This issue is actually extremely problematic and arises when using any dynamic data inside of reusable blocks. It makes it so any time you add a new element it is linked to a previous one. My error log is filled with these errors, and the builder is saying "AJAX Timeout Error. Please contact support". A rather large website we have been building on Oxygen that is set to go live next week has been completely halted because of this issue and the performance of the site and builder is getting increasingly worse.

2022/09/29 08:51:08 [error] 17736#17736: *116845 FastCGI sent in stderr: "PHP message: PHP Warning:  Invalid argument supplied for foreach() in /htdocs/wp-content/plugins/oxygen/component-framework/includes/oxygen-dynamic-shortcodes.php on line 430PHP message: PHP Warning:  Invalid argument supplied for foreach() in /htdocs/wp-content/plugins/oxygen/component-framework/includes/oxygen-dynamic-shortcodes.php on line 430" while reading response header from upstream, client: 72.183.134.118, server: , request: "POST /wp-admin/admin-ajax.php?action=ct_get_post_data&id=583&nonce=aa821a85e9&post_id=177&preview_post_id=413 HTTP/2.0", upstream: "fastcgi://unix:/var/run/php/php74-fpm.sock:", host: ".com", referrer: "https://.com/?ct_template=template-location&ct_builder=true&ct_inner=true&oxygen_iframe=true"

**Comment by Spellhammer** [comment]
This is fixed internally and the fix will be included in the forthcoming 4.1 beta 1.

**Comment by Spellhammer** [comment]
Oxygen 4.1 beta 1 has been released, which includes a fix for this issue.
