### ISSUE TITLE
Variable already declared

### ISSUE THREAD

**Issue by petteremil** [soflyy/oxygen-bugs-and-features#3061]
**Any bug report that doesn't include a Sandbox link or replication steps will be closed. If you can't provide these pieces of information, we're happy to help you via our official support channel instead: https://oxygenbuilder.com/support. You need to select "Something's broken and I need help" from the dropdown box on the left.**

**Describe the bug**
*A clear and concise description of what the bug is.*
When getting and declaring a list of html Elements and then looping over them in a for of loop the editor complains about the element already being declared earlier.

**A link to a Sandbox site where the bug has been reproduced https://oxygenbuilder.com/try? (REQUIRED)**
*Provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*

**IF YOU CAN'T PROVIDE A SANDBOX REPRODUCTION: Steps required to reproduce the bug:**

Paste this script into a javascript code-section:
"
let inputs = document.getElementsByClassName("order-input");

for (let e of inputs) {
    e.addEventHandler("change",function(){
		if(e.tagName === "INPUT"){
			if(e.value || e.value === ""){
				alert("jeg er tom!");
			}
		}else if(e.tagName === "SELECT"){
			if(e.value || e.value === ""){
				alert("jeg er tom!");
			}
		}
	});
}
"

You will then get the error: "Uncaught SyntaxError: Identifier 'inputs' has already been declared on line #1"

I assume it's got something to do with the parsing of "for (let e of inputs) {"

**If you can't fill out the above information, you should not be filing a bug report. Instead, contact us via https://oxygenbuilder.com/support with the details you have and we'll investigate your issue further.**

![image](https://user-images.githubusercontent.com/59834762/186159295-de4f30d2-dd00-4640-957f-fa107bbc859d.png)

**Comment by Kpudlo** [comment]
Hi @petteremil, 

This is due to the way JavaScript is handled when editing in Oxygen. I'd recommend wrapping the function in a statement that waits for the page to load before firing: 

```js
window.addEventListener('load',function() {
	let simputs = document.getElementsByClassName("order-input");

	for (let e of simputs) {
		e.addEventHandler("change",function(){
			if(e.tagName === "INPUT"){
				if(e.value || e.value === ""){
					alert("jeg er tom!");
				}
			}else if(e.tagName === "SELECT"){
				if(e.value || e.value === ""){
					alert("jeg er tom!");
				}
			}
		});
	}
})
```
