### ISSUE TITLE
Stylesheet Loading Conditions

### ISSUE THREAD

**Issue by shmaltz** [soflyy/oxygen-bugs-and-features#3063]
It would be awesome to be able to have a conditions panel for custom stylesheets, similar to the element conditions panel in oxygen, so we can select on which page/post/taxonomy/CPT to load that custom stylesheet.

Currently the custom Stylesheets load on every page, and that's bad for performance.

**Comment by wpsumo** [comment]
Duplicate, vote here instead https://github.com/soflyy/oxygen-bugs-and-features/issues/18
