### ISSUE TITLE
Repeater bug - if duplicate repeater with Advanced Query

### ISSUE THREAD

**Issue by trudoom** [soflyy/oxygen-bugs-and-features#3064]
If dupliace repeater with Advanced Query and move under other repeater, so all repeaters have same setting.
Make it on Oxygen builder 4.0.3. only.

**IF YOU CAN'T PROVIDE A SANDBOX REPRODUCTION: Steps required to reproduce the bug:**
1. add Section 1
2. add repeater 1 and set Advanced Query 1
3. add Facet WP Grid builder above repeater 1 and choose facets and grid Repeater 1
4. add Section 2
5. add repeater 2 and set different Advanced Query 2
6. duplicate Repeater 1 (make Repeater3 by duplicate ) and move he under Repeater 2.
7. Now try edit Advanced Query in Repeater 3 - he has same satting as Repeater 2.
8. And now all Repeaters has the same setting for editing, but display different things. Now Is not possible edit 

Wordpress 6.0.1
Oxygenbuilder 4.0.3
WP Grid builder 1.68
php 7.4.30

**Comment by Spellhammer** [comment]
Unable to reproduce. Please submit a ticket with login credentials for an environment where we can see this error: https://oxygenbuilder.com/support.
