### ISSUE TITLE
Breakpoint is not reseting after updating

### ISSUE THREAD

**Issue by forayejicreativeagency** [soflyy/oxygen-bugs-and-features#3068]
We have container width in page width setting inside Oxygen and breakpoint setting inside global settings

I am using 1440px page width and for pagewidth part on breakpoint using 1220px (Example). But on the responsive icons I am not getting the 1220px. I am getting full width, 1440px, Less then 992 and others. 

Quite similer is also happeining on Oxygen Server itself where I am getting the default 1120px width for that part.

Here is the link of oxygen hosting where I tested the issue
https://oxygen-qk2gv7npz4pnl.oxygen-demo.qsandbox.me/?ct_builder=true&ct_inner=true

**Comment by Spellhammer** [comment]
Did you regenerate the CSS cache after changing the breakpoints?

**Comment by forayejicreativeagency** [comment]
Yes tried on own server

**Comment by forayejicreativeagency** [comment]
So,
Here I have made a video to describe the problem.


https://www.loom.com/share/9ca0f41c67b7461e9634b25d8c30f777

**Comment by Kpudlo** [comment]
Hello @forayejicreativeagency, 

The video provided shows that is no longer valid. When testing this on a fresh Sandbox site, we're not encountering an issue where the breakpoint in Oxygen's responsive controls doesn't match the breakpoint in Setting > Global Styles > Width & Breakpoints and Oxygen's CSS has been regenerated via Oxygen > Settings > CSS Cache in /wp-admin.

If you are still having an issue with this, please provide an updated video and open a support ticket by emailing support@oxygenbuilder.com. We'll be glad to investigate further.
