### ISSUE TITLE
Multiple Repeaters on page, only the first one shows correct fields

### ISSUE THREAD

**Issue by jessebrightman** [soflyy/oxygen-bugs-and-features#3075]
**Any bug report that doesn't include a Sandbox link or replication steps will be closed. If you can't provide these pieces of information, we're happy to help you via our official support channel instead: https://oxygenbuilder.com/support. You need to select "Something's broken and I need help" from the dropdown box on the left.**

**Describe the bug**
*A clear and concise description of what the bug is.*

**A link to a Sandbox site where the bug has been reproduced https://oxygenbuilder.com/try? (REQUIRED)**
*Provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*

**IF YOU CAN'T PROVIDE A SANDBOX REPRODUCTION: Steps required to reproduce the bug:**

**If you can't fill out the above information, you should not be filing a bug report. Instead, contact us via https://oxygenbuilder.com/support with the details you have and we'll investigate your issue further.**

**Comment by Kpudlo** [comment]
Hi @jessebrightman, 

Please submit a ticket via https://oxygenbuilder.com/support with admin login credentials for where we can see the issue so we can investigate further.

**Comment by jessebrightman** [comment]
Somehow the global post object is not being updated to retrieve the correct acf custom fields in a repeater.  Instead it defaults to the default $post object which is the single CPT of the page.

**Comment by jessebrightman** [comment]
Two years on and this bug still persists.
