### ISSUE TITLE
Copying styles using the copy & paste styles feature causes 502 page error.

### ISSUE THREAD

**Issue by creative-prowess** [soflyy/oxygen-bugs-and-features#3077]
When we use the copy and paste from one style to another the site breaks and causes a 502 page error.

**Comment by Kpudlo** [comment]
Hello @creative-prowess, 

At this time, it is not possible to copy and paste styles from one site to another, only to pages or templates on the same site. Instead, you can [Import & Export](https://oxygenbuilder.com/documentation/other/importing-exporting/) content between sites, or use the [User Design Library](https://oxygenbuilder.com/documentation/design-library/user-design-library/).

**Comment by Kpudlo** [comment]
Hi @creative-prowess, 

Would you be able to provide some additional details on what you were doing when you received this error? For example, were you using a third-party addon when this error occurred? Or, were you copying and pasting styles between selectors? Any additional information you can provide would be appreciated. Thank you!
