### ISSUE TITLE
Headings adds a <br>.

### ISSUE THREAD

**Issue by alexdfy** [soflyy/oxygen-bugs-and-features#3082]
**Describe the bug**

The heading module adds a `<br>` at the end of the title.

**Demonstration**
>> Creating a sandbox
>> Section creation
>> Creating a title: "CECI EST UN H1"
>> Front inspection : 
`<h1 id="headline-3-2" class="ct-headline">CECI EST UN H1<br></h1>`

**SANDBOX LINK ** :
https://oxygen-qb5v66m7h9f8.oxygen-demo.qsandbox.me/sample-page/

**Comment by Kpudlo** [comment]
Hello @alexdfy, 

The issue was with the text in the Heading element. If I copy the text and paste it into the Header element as plain text, the `<br>` tag goes away. You may see this on the linked Sandbox site.
