### ISSUE TITLE
Add css list-style-type : disc

### ISSUE THREAD

**Issue by benlep** [soflyy/oxygen-bugs-and-features#3085]
Hello, 
sorry for this question, 
how add a css list-style-type : disc
![puce](https://user-images.githubusercontent.com/22316691/191896170-1fabef47-6c40-4903-8b5b-f9662f591b3e.png)
I found this in another part of my website but I don't know how my dev did that.
Someone can help me please ?
thanks 
Ben

**Comment by Spellhammer** [comment]
For support from other users, please post this type of question at https://oxygenbuilder.com/facebook.

For official support, please send questions like this to support@oxygenbuilder.com.
