### ISSUE TITLE
ACCORDION (alongside) with TOGGLE

### ISSUE THREAD

**Issue by InternetSemplice** [soflyy/oxygen-bugs-and-features#309]
**Describe the feature you'd like to see included in Oxygen.**
Alongside with the toggle, the accordion will make a much complete and functional feature for showing complex information in a short space on a page.

Definitely it can be a simple variation of the toggle.

I don't think there is any need to explain more about accordions. ;-)

Andy

**Comment by Spritpit** [comment]
Hi everybody,

it would be great to have an accordion, its a perfect tool for userability, thanks!

regards
Spritpit

**Comment by KittenCodes** [comment]
Added in Composite Elements.
