### ISSUE TITLE
ACF Repeaters no longer calling sub fields. 

### ISSUE THREAD

**Issue by JonathanKlein-Brado** [soflyy/oxygen-bugs-and-features#3090]
https://oxygen-q6hrxa48ar5nl.oxygen-demo.qsandbox.me/test-page/

When using the Repeater component to target an ACF Repeater on the page the "insert data" button no longer appears when adding a text or header component and when inserting dynamic data > custom field and targeting the sub field within the repeater it states "no data for field". The only way it works is if you target individual rows, which defeats the whole purpose of the repeater. 
![targeting subfield for text](https://user-images.githubusercontent.com/111536751/192818409-b3d50377-b054-4111-b0c2-a2caa6f6b606.png)
![showing that only individual fields are wanting to display](https://user-images.githubusercontent.com/111536751/192818619-7617d19d-ea11-416e-b0e5-aefb5d4966e1.png)

**Comment by Kpudlo** [comment]
Hello @JonathanKlein-Brado, 

I've not been able to replicate this issue. If you're able to replicate this problem on a sandbox site, please provide a link to the sandbox so we may investigate further: https://oxygenbuilder.com/try

If it is only happening on your site, please send credentials to support@oxygenbuilder.com so we may investigate further.
