### ISSUE TITLE
oxygen not save data with PHP 8

### ISSUE THREAD

**Issue by mredodos** [soflyy/oxygen-bugs-and-features#3094]
Hi on WPMUDEV hosting in multisite network with php 8, on a subsite oxygen not save data when you click on save.

**Comment by Spellhammer** [comment]
Please submit a support ticket at support@oxygenbuilder.com.

**Comment by mredodos** [comment]
on support site say put here the bug...what the hell should I do?

**Comment by Kpudlo** [comment]
Hello @mredodos, 

As this issue may not be more complex beyond a bug report, please submit a support ticket at [support@oxygenbuilder.com](mailto:support@oxygenbuilder.com) so we may be able to assist further.
