### ISSUE TITLE
Regenerate CSS Cache broken when WordPress is installed in a subdirectory

### ISSUE THREAD

**Issue by andreslotta** [soflyy/oxygen-bugs-and-features#3096]
**Describe the bug**
When WordPress is installed in a subdirectory (e.g. somedomain.com/subdirectory/) Oxygen's cache regeneration process seems to be broken. When I start the process (Oxygen > Settings > CSS Cache > Go to Regeneration Page > Start regeneration)  a frontend page is loaded within the admin window. On larger sites with some pages the whole regeneration process does not seem to finish correctly.

Screencast showing the issue: [Issue](https://cln.sh/PPAooL)

**IF YOU CAN'T PROVIDE A SANDBOX REPRODUCTION: Steps required to reproduce the bug:**
1. Create a WordPress installation in a subdirectory
2. Install Oxygen
3. Create a page or two
4. Start the CSS regeneration process as described above and see the issue

**Comment by lowcut** [comment]
+1

**Comment by Kpudlo** [comment]
Replicated and reported internally.

**Comment by thechiefalone** [comment]
I have the same issue, and with OxyExtras Accordion it is more headache. I can not regenerate css cache and I need to open all pages which has Oxyextras Accordion, one by one and save them again inside builder to regenerate these pages css. 

Oxygen Team should implement the solution asap.

**Comment by forayejicreativeagency** [comment]
I still have the issue with Oxygen 4.3

**Comment by Kpudlo** [comment]
> I still have the issue with Oxygen 4.3

Hello @forayejicreativeagency, 

Please open a Support Ticket (https://oxygenbuilder.com/support) so we may investigate further.
