### ISSUE TITLE
White labelled HTML/CSS

### ISSUE THREAD

**Issue by snippety** [soflyy/oxygen-bugs-and-features#31]
**Ability to completely white-label the HTML/CSS output**
*Oxygen automatically creates some CSS IDs/classes that can't be modified or renamed. The idea is to have a list of CSS IDs/classes that Oxygen normally creates dynamically next to input fields so they can be renamed to something else*

**Better product delivery for agencies and clients**
*White-labelling as much of the HTML/CSS output gives a better impression for agencies and clients in that something is highly customised*

**Comment by Spellhammer** [comment]
Closing as it's very unlikely that this will be a viable feature.
