### ISSUE TITLE
Error: This design contains elements registered by another plugin that is no longer active.

### ISSUE THREAD

**Issue by jessebrightman** [soflyy/oxygen-bugs-and-features#3108]
This design contains elements registered by another plugin that is no longer active. Please re-activate the appropriate plugins or remove the missing elements before saving.

We have made no changes to plugins while working on a template, but this error just came up and now we cannot save it.  Saving worked without the error 2 minutes previous. 

**Any bug report that doesn't include a Sandbox link or replication steps will be closed. If you can't provide these pieces of information, we're happy to help you via our official support channel instead: https://oxygenbuilder.com/support. You need to select "Something's broken and I need help" from the dropdown box on the left.**

**Describe the bug**
*A clear and concise description of what the bug is.*

**A link to a Sandbox site where the bug has been reproduced https://oxygenbuilder.com/try? (REQUIRED)**
*Provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*

**IF YOU CAN'T PROVIDE A SANDBOX REPRODUCTION: Steps required to reproduce the bug:**

**If you can't fill out the above information, you should not be filing a bug report. Instead, contact us via https://oxygenbuilder.com/support with the details you have and we'll investigate your issue further.**

**Comment by thelamedia** [comment]
I also have this problem.  No changes to the site whatsoever, but now the heading and richtext boxes are only taking up 33% width instead of 100%.  Not sure what is throwing this error as we have no disabled plugins.

**Comment by jvdreamworker** [comment]
I too just got this error while making a simple change to the header of a site. Header is not using any plugins that I know of and all plugins are active.

**Comment by Spellhammer** [comment]
@jessebrightman @thelamedia @jvdreamworker 

Please submit a ticket at support@oxygenbuilder.com so that we can investigate.

**Comment by reconrad48** [comment]
Okay, was it investigated? I just made 10 minutes of changes to the main template and now I can't save it because of this error. There aren't ANY elements used that aren't part of Oxygen core.

**Comment by Kpudlo** [comment]
Hi @reconrad48, 

Please submit a ticket at support@oxygenbuilder.com so that we can investigate the issue on your site.

**Comment by BluByte** [comment]
Had the same issue after a minor oxygen update. Solved following these steps:
1) exit from the builder
2) go to oxygen -> settings -> security
3) sign all shortocodes (sign everything you need)
4) enter in the builder and try to save again

This procedure worked for me

**Comment by EdCorner1** [comment]
Hey @BluByte was this a 100% fix for you? 

I've tried this and while initially positive, I have to do this every hour or so to prevent the shortcodes from having problems. 

Do you have any other wisdom on this? 

Currently I'm just waiting for a response from the Oxygen team.

**Comment by hasnattanvir** [comment]
This design contains elements registered by another plugin that is no longer active. Please re-activate the appropriate plugins or remove the missing elements before saving.

can't save page

**Comment by BaerHub** [comment]
how is this issue still there?!
i regret wasting the money on this product, it does seem to have multiple issues, for example the oxygen builder site looks different than on the real frontend (icon size, colors, etc.)

**Comment by Hawberry** [comment]
Happens to me, too, when using wp-typography, which I need, since Oxygen breaks smart quotes for me.

**Comment by AW85** [comment]
I too, am still having problems. Can anyone please get to the bottom of this? Markng this as "closed" is not very helpful.

**Comment by mikes-bowden** [comment]
This is not closed. Moving divs out of a column container triggers this for me. We only have a very small handful of required plugins installed for development. How is this still an issue and marked as closed?

**Comment by Kpudlo** [comment]
This is fixed in Oxygen 4.9 Beta 2. This is available for testing through the Customer Portal (https://oxygenbuilder.com/portal/).

If you still encounter this error after installing Oxygen 4.9 Beta 2, please create a new ticket with the steps necessary to see the issue.

**Comment by ZanKilian** [comment]
Try making your main elements reusable and removing them 1 by 1 then saving, After saving, re-add them each one by one and saving, Worked for me, happens sometimes when I duplicate elements

**Comment by mikes-bowden** [comment]
This is not fixed.

Ten minutes ago, I saved no issues; now, I get the error. Zero plugins have been disabled. This only occurs while making edits to different screen sizes; it never does it on the full size.

**Comment by mikes-bowden** [comment]
I was re-applying the edits, and I may have stumbled upon what caused it. This error will be triggered if you add a column element, move the divs out of it, and try to save. Hopefully that helps.

**Comment by monhelle** [comment]
This design contains elements registered by another plugin that is no longer active. Please re-activate the appropriate plugins or remove the missing elements before saving. Find the non-registered elements highlighted in the Structure Pane.


There is no non-registered elements highlighted in the Structure Pane....

**Comment by Psymbionic** [comment]
Having the exact same issue. @mikes-bowden called it correctly - when removing divs from a column element, it causes this error and prevents saving from happening. Version 4.9.6

This issue should be reopened.
