### ISSUE TITLE
DONE: Add microdata to html tags - SEO

### ISSUE THREAD

**Issue by mypcparts18** [soflyy/oxygen-bugs-and-features#311]
**Describe the feature you'd like to see included in Oxygen.**
An option to add microdata tags inside of html tags. 

**What are the use cases for this feature?**
Microdata or a lack thereof can significantly impact Local SEO.

**Examples of this feature or functionality.**
A similar interface to how we can add :states to css classes. 

`(i.e. <div itemscope="name">, <h1 itemprop="name">)`

**Comment by KeywordStuffer** [comment]
Considering the importance of Microdata not only for Local SEO but also for improving the CTR of search results in general, this should have very high priority!

**Comment by alriksson** [comment]
Better to add JSON-LD but other plugins can do this not sure if it should be on oxygen at all to sort.

Most users use Yoast or other tools which include these features.

**Comment by bitingedgemick** [comment]
> Better to add JSON-LD but other plugins can do this not sure if it should be on oxygen at all to sort.
> 
> Most users use Yoast or other tools which include these features.

Wholeheartedly agree with this. Spent quite a bit of time in the last couple of years removing all microdata attributes from my custom themes and switching in JSON-LD only where appropriate. With Oxygen much simpler to add JSON-LD through Code Block or one the many plugins.

**Comment by Spellhammer** [comment]
Custom attributes introduced in 3.5 alpha 1.
