### ISSUE TITLE
WPML support urgently !

### ISSUE THREAD

**Issue by numayos** [soflyy/oxygen-bugs-and-features#3110]
There are a lot of people waiting for compatibility with wpml.
please update this urgently.
There's a whole group asking here: https://github.com/soflyy/oxygen-bugs-and-features/issues/938

Announce at least one ETA

Thanks in advance

**Comment by Kpudlo** [comment]
Duplicate of #938

**Comment by kademario** [comment]
For anyone still looking for an Oxygen + WPML workflow, we have developed an independent third-party connector:

**WPML Oxygen Connector**

It supports Oxygen Builder 6 and Oxygen 4 Classic, and helps translate Oxygen websites with WPML without manually rebuilding layouts for each language.

It is not an official Oxygen or WPML integration, but it may be useful for agencies and developers still maintaining multilingual Oxygen websites.
