### ISSUE TITLE
Nested repeater in oxygen 4.1 RC 1 don't work like expected

### ISSUE THREAD

**Issue by ThomasCayrol** [soflyy/oxygen-bugs-and-features#3122]
Updated oxygen from 4.0.4 RC 1 to 4.1 RC 1, and all my nested repeaters no longer work. 
I checked by rolling back to 4.0.4 RC 1 and then nested repeaters work normally again.

Since new 4.1 RC 1 version nested repeater don't act like before. 2nd level of repeater shows data only for first item.
All following items are empty.

https://ccrlcm.staging.rangoon.fr/test-nested-repeater

1. Add a repeater to the page or template (custom query to load pages with post_parent = "xx")
2. Add a H1 field and insert dynamic data "page title"
3. Add an inner repeater (custom query with post_parent = "post_id")
4. Add a H2 field and insert dynamic data "page title" for 2nd repeater
5. below a screen capture with the 2 results I have between v4.1 et v4.0.1

![bugoxyv41rc1](https://user-images.githubusercontent.com/47623041/200149329-7b1a2aaf-07c4-4ebd-8a0c-ef8e16225ee6.jpg)

**Comment by Spellhammer** [comment]
Thanks for the report. I was able to reproduce this and will prioritize this for our dev team.

**Comment by Spellhammer** [comment]
Fixed in 4.1.1.
