### ISSUE TITLE
ID settings not clearing if you are trying to use a class.

### ISSUE THREAD

**Issue by cfawebdesigns** [soflyy/oxygen-bugs-and-features#3124]
Since version 4.1, if you create a class and then try to delete the original ID settings it does not work. The new class settings will not take effect. My workaround is to do everything with the original ID, then create the class copy all the settings to that class, then delete the class, go back to the original ID and reset all the settings that I want the class to control and then apply the new class. 

Seems to be a little bit more work than it used to be.

**Comment by andreslotta** [comment]
@cfawebdesigns Can you share a screencast or some more details of how to reproduce? If I understood your problem correctly I can't reproduce it. See https://cln.sh/pgCQwf.

**Comment by cfawebdesigns** [comment]
I can't, already done with the site.  On the next project, and it's live.
I will check for the problem and see if it repeats itself on the next
project. Although that was a brand new setup with WordPress, and new MY
SQL, everything from scratch The only plug-ins I've been using is automatic
CSS, slim SEO, WP all-in-one security, and very other basics I use in every
other website like code snippet, advanced database cleaner, all-in-one WP
migration, duplicate page, catch enabler by CDN,.


CFA Web Designs & SEO Optimization
352-340-3559
***@***.***
https://fullcircleadvertizing.com/website-designs/
https://www.linkedin.com/in/cfawebdesigns/
https://cfawebdesigns.com/
Hernando Chamber Board Member
Ambassador Chair

**Comment by cfawebdesigns** [comment]
I have tried it on a fresh setup and its working there. However, on my sites that did the updates, it does not. Most all my sites use the same plugins, and all those sites updated from wp 5.xx to 6.1 now. Before updating to WordPress 6.1 I did apply the patch that they wanted us to do before the upgrade. I did not see that until after the upgrades are already done.

**Comment by Kpudlo** [comment]
@cfawebdesigns, 

If you're unable to recreate this on a fresh sandbox (https://oxygenbuilder.com/try), and this issue still occurs with all other plugins except for Oxygen deactivated, please email support@oxygenbuilder.com with the necessary information to see this issue so we may investigate further.
