### ISSUE TITLE
Some kind of props/arguments in Reusable Parts

### ISSUE THREAD

**Issue by viabit-dev** [soflyy/oxygen-bugs-and-features#3129]
**Describe the feature you'd like to see included in Oxygen.**
At some point I had to duplicate a reusable part to make a minimal change (in a query in a repeater for example)

**What are the use cases for this feature?**
I think if there was a possibility to pass some kind of argument to the reusable part, I could have avoided duplicating it.

**Examples of this feature or functionality.**
In queries contained in components inside the reusable part, to hide or make visible some component, or for any minimal modification.
Anything that helps us avoid having to duplicate the reusable part.

**Comment by raroDev** [comment]
@Spellhammer please consider this feature. That would be huge! It is unique feature for wp page builder but so important one. Now only Themeco implemented this.

**Comment by pkboy** [comment]
in lieu of the feature being added, you can make use of WP functions and hooks to do what you need.

say if you want to modify the query you can use ```pre_get_posts``` hook to modify it before it is ran within the reusable

If you wish to pass something to your part in some instances you can use ```set_query_var``` and ```get_query_var```, so use a code block to set your value before the reusable then inside the reusable you output the value.

**Comment by Spellhammer** [comment]
I think this is a very cool idea, but there is an existing request for this here: https://github.com/soflyy/oxygen-bugs-and-features/issues/1517. Please go vote on the original. Closing this as a duplicate.
