### ISSUE TITLE
Data Attributes with numbers are stripped off numbers

### ISSUE THREAD

**Issue by jevgen** [soflyy/oxygen-bugs-and-features#3134]
Data Attributes with numbers are stripped off numbers

**Describe the bug**
If you add data attrubute with numbers, and number IS NOT initial, like data-b24-form (required for Bitrix24 integration for example), Oxy stips our all numbers from data attribute.

In fact its a mistake in evaluation in regular expression. Only data attributes that START from a number has to be stripped off with some warning. Attributes that CONTAIN numbers and start with a letter are perfectly valid and has not to be stripped out.

**Comment by Kpudlo** [comment]
Duplicate of https://github.com/soflyy/oxygen-bugs-and-features/issues/1535

**Comment by jevgen** [comment]
How it is closed if it is not fixed in v4.2?

**Comment by Kpudlo** [comment]
This specific issue is closed as it is a duplicate of #1535, and that one is still open and active.
