### ISSUE TITLE
Elegant Custom Fonts Integration & Font Suggestions

### ISSUE THREAD

**Issue by AdilPerformAds** [soflyy/oxygen-bugs-and-features#3135]
Sandbox Link: https://oxygen-qln9z4v7rc3pl.oxygen-demo.qsandbox.org/

**Describe the bug**
1. After installing ECF to import a custom font I was greeted with following error message.
The same line (and file) was mentioned on my website, but the error message was slightly different.
![Bildschirm­foto 2022-11-29 um 13 35 43](https://user-images.githubusercontent.com/116073531/204532167-6a51fa21-3575-49b7-b563-cc83019164d9.png)
2. After disabling Google Fonts in ( Oxygen > Settings > Bloat Eliminator ) Oxygen Pagebuilder keeps on suggest Google Fonts inside the editor.
( The source of the frontend shows no google fonts integration - which is correct )
3. I uploaded a file to '/wp-content/fonts/' and added this @font-face to my fresh font-family 'NunitoSansLocal'  using the ECF-Plugin.
But the font-family isn't appearing inside the page editor.

1. Go to 'Oxygen' > 'Templates'
2. Click on 'edit with Oxygen' ( There is only one template.)
4. Click on 'Settings'
5. Click on 'Global Styles'
6. Click on 'Fonts' 
7. See Google Font Suggestions
8. See no 'NunitoSansLocal'

Edit: On my page I added the font-family 'NunitoSansLocal' using 'custom css' and it worked perfectly fine... but...

**Comment by Kpudlo** [comment]
Hello @AdilPerformAds, 

Thank you very much for the feedback. 

> 1 After installing ECF to import a custom font I was greeted with following error message.
> 3 I uploaded a file to '/wp-content/fonts/' and added this https://github.com/font-face to my fresh font-family 'NunitoSansLocal' using the ECF-Plugin.

The ECF plugin is no longer actively maintained, and as such, we've removed it from our list of suggested font plugins. 

Please see our updated documentation 


> 2 After disabling Google Fonts in ( Oxygen > Settings > Bloat Eliminator ) Oxygen Pagebuilder keeps on suggest Google Fonts inside the editor.

Related ticket: https://github.com/soflyy/oxygen-bugs-and-features/issues/236.
