### ISSUE TITLE
Order in Folder for re-usable Parts 

### ISSUE THREAD

**Issue by Digitalarbeit** [soflyy/oxygen-bugs-and-features#3136]
I would be nice to create folders for re-usable parts. Like if you have a lot of re-usable parts, this can be placed more ordered. Also in future advance maybe create different folders for different users, if for example there is a whole Team create a website.

It helps to keep things more clear and ordered. If you have for example 30 re-usable parts, with this feature you can create for example 3 folders for different "parts" of the reusable parts. For example folder "Author" for all reusable parts of all authors, and so one.

**Comment by Kpudlo** [comment]
Similar enough to https://github.com/soflyy/oxygen-bugs-and-features/issues/3111.
