### ISSUE TITLE
Font Smoothing CSS Is Incorrect

### ISSUE THREAD

**Issue by Deanphillips** [soflyy/oxygen-bugs-and-features#314]
Hey guys,

I told the team this a while back but during 2.3 it never got fixed - I've noticed that no ones mentioned it here.

When using font smoothing Oxygen puts -moz-osx-font-smoothing: greyscale; for Firefox but it should be -moz-osx-font-smoothing: grayscale; (gray NOT grey) 

Hope that helps :)

**Comment by Deanphillips** [comment]
Any update on this @Spellhammer? Seems to be confirmed on all my installs but wanted to see if it was on your end too

**Comment by KittenCodes** [comment]
Replicated in 2.4.1.

**Comment by Deanphillips** [comment]
Really hope this is fixed soon. It's a letter change in the output that's required. Surprised it wasn't done a while ago :)

**Comment by KittenCodes** [comment]
This is fixed in the latest version of Oxygen.
