### ISSUE TITLE
Same position of open / close icon in mobile menu

### ISSUE THREAD

**Issue by Hud1ai2** [soflyy/oxygen-bugs-and-features#3143]
From the UX point of view I think that open / close icons in mobile menu should be in same place because user expects it there. Because of this, I need to make by menus by myown (only if there is no submenu in my menu - then I'm not able to do that because of functionality of mobile version of menu element). So please, add more possibilities, modern looking update of menu element - close / open icons position, accordion submenu on menu element etc.

Because now I'm able to do modern and fresh looking websites with oxygen, but the menu / pro menu element can ruin that feeling. Thanks.

Here is the example of menu element (I needed to put there something more, what I'm not able to do with menu / pro menu element also)
[servpro.cz/](https://servpro.cz/)

**Comment by Hud1ai2** [comment]
@Spellhammer Here is another example what I've done - but there is lots of custom code there especialy for the opening the submenu (mobile view)

[bazenybilek.cz/](https://bazenybilek.cz/)

**Comment by Spellhammer** [comment]
I think this is resolved in 4.3 beta 2. If not, please open a new issue with more details.
