### ISSUE TITLE
Site Navigaition element - typography colors dp

### ISSUE THREAD

**Issue by udoro** [soflyy/oxygen-bugs-and-features#3144]
**Any bug report that doesn't include a Sandbox link or replication steps will be closed. If you can't provide these pieces of information, we're happy to help you via our official support channel instead: https://oxygenbuilder.com/support. You need to select "Something's broken and I need help" from the dropdown box on the left.**

**Describe the bug**
*A clear and concise description of what the bug is.*

**A link to a Sandbox site where the bug has been reproduced https://oxygenbuilder.com/try? (REQUIRED)**
*Provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*

**IF YOU CAN'T PROVIDE A SANDBOX REPRODUCTION: Steps required to reproduce the bug:**

**If you can't fill out the above information, you should not be filing a bug report. Instead, contact us via https://oxygenbuilder.com/support with the details you have and we'll investigate your issue further.**

**Comment by Spellhammer** [comment]
Are you able to repro in a different environment where I can take a look?

It's working as expected in my sandbox and local environments.

**Comment by udoro** [comment]
Hi, sorry for the late reply, I didn't get the email you sent 4 days ago.
I'll do that and send you a link by tomorrow.


*Udoro Essien*

*+234 (0) 806 7081 800*

**Comment by udoro** [comment]
> @udoro Just touching base again as we'll be releasing beta 2 soon - are you able to repro this on an environment where I can take a look?

@Spellhammer I couldn't replicate the issue in another environment. It would appear the issue is isolated to my local install. I couldn't figure out the reason. I'll update you once I get more information.

**Comment by Spellhammer** [comment]
@udoro Thank you for the update. I'm going to close this. If you're able to reproduce or provide more information, I'll re-open at that time.
