### ISSUE TITLE
DONE: Ability to add multiple calls to action buttons for the new site navigation element

### ISSUE THREAD

**Issue by paradeshi** [soflyy/oxygen-bugs-and-features#3147]
The new site navigation element is power packed with features and it can be better. I'm suggesting an option to be able to add more than one call to action. Every single website that we build has two calls to action buttons. Donate and buy, for example. Or Give and Volunteer etc.

**Comment by cornish-td** [comment]
We would also like to see this feature. The new site navigation has a lot of potential to become a very good, accessible menu builder! 😊

**Comment by Spellhammer** [comment]
Done in 4.3 RC 1.
