### ISSUE TITLE
Condition error - wrong parameters

### ISSUE THREAD

**Issue by Schokolader** [soflyy/oxygen-bugs-and-features#3151]
**Describe the bug**

If you use condition on a metabox group field, the conditions are the opposite. 
For example: 

If you only want to show a textfield from a metabox group if the content is not empty 
you would use the condition "is not blanc". 
But this does not work. It only works if you use the condition "is blanc". That is wrong. There is an error. 

**Reproduction Steps:** 
- Add metabox group fields to attach to posts
- create a template for blog posts
- add the metabox group fields
- add condition on the metabox group fields
- you will get an array error or the conditions won't work like they should. Is blanc is actually is not blanc etc.

**Comment by Schokolader** [comment]
If you use conditions on the metabox group field, there is a array to string error.

**Comment by Kpudlo** [comment]
Hello @Schokolader, 

I've been unable to recreate this on a staging environment. If you can, please recreate the issue on a Sandbox site (https://oxygenbuilder.com/try/) and then provide the link for the Sandbox site.
