### ISSUE TITLE
Conditions don't work on metabox groud fields 

### ISSUE THREAD

**Issue by Schokolader** [soflyy/oxygen-bugs-and-features#3152]
**Describe the bug**

There is an error with conditions on metabox group fields. The conditions won't work properly. 
- Add metabox group fields to attach to posts 
- create a template for blog posts 
- add the metabox group fields 
- add condition on the metabox group fields 
- you will get an array error or the conditions won't work like they should. Is blanc is actually is not blanc etc.

**Comment by Kpudlo** [comment]
Duplicate of https://github.com/soflyy/oxygen-bugs-and-features/issues/3151
