### ISSUE TITLE
Not all google fonts are available when searching in the dropdown

### ISSUE THREAD

**Issue by stevenrabulan** [soflyy/oxygen-bugs-and-features#3153]
For example, typing "Fig" or "Figtree" doesn't allow me to select this font which is available on google fonts: https://fonts.google.com/specimen/Figtree

**Comment by Kpudlo** [comment]
Hello @stevenrabulan, 

I've not been able to see this issue on a Sandbox site (https://d.pr/i/c956jm). If you're still encountering issues with this, please open a ticket with our Support team so we may access the site you're having a problem on and investigate further: https://oxygenbuilder.com/support

**Comment by mzvdesign** [comment]
Ive found you have to uncheck Cache list of Google Fonts in General settings in Oxygen and then you will have Figtree ;)

**Comment by stevenrabulan** [comment]
Good find, I believe this would have fixed it for me earlier!
