### ISSUE TITLE
[Site Navigation] Add a way to alter or disable "active item" styles

### ISSUE THREAD

**Issue by jkarelbroer** [soflyy/oxygen-bugs-and-features#3158]
Oxygen 4.3 beta 2 shows an unwanted line below the menu items.

See here: https://sandbox.brovisuals.dev
Password: BroSand-22!

![Site navigation menu lines](https://user-images.githubusercontent.com/12644053/207683152-15aeed50-1079-4afa-8aa8-6dd1ac9686bf.png)

**Comment by Spellhammer** [comment]
@jkarelbroer This is because the link items all point to the site root, so they're all the "current page", which gives them an underline treatment. If you add real URLs to the link items it will work as expected.

**Comment by jkarelbroer** [comment]
Tested it with a real How we work page in the menu, but the line is still visible...

![Unwanted line v2](https://user-images.githubusercontent.com/12644053/207689124-0a3f18fd-374a-4d35-a940-0d9faa3e7049.png)

**Comment by Spellhammer** [comment]
@jkarelbroer The line is intentional. Do you want the option to alter or disable it for the current menu item?

**Comment by jkarelbroer** [comment]
@Spellhammer I see… in that case, please provide a way to alter or disable the line.

**Comment by Spellhammer** [comment]
Done in 4.3 RC 1.
