### ISSUE TITLE
[Site Navigation] How to show the CTA button as outline?

### ISSUE THREAD

**Issue by jkarelbroer** [soflyy/oxygen-bugs-and-features#3159]
I think this is a feature request, because I could not find the possibility to set a border around the CTA button.
Hope this option can be added? 😊

![Site Navigation CTA](https://user-images.githubusercontent.com/12644053/207685232-08d1bb75-0345-490f-942b-2aaf2104a9f0.png)

**Comment by Spellhammer** [comment]
Added outline option in 4.3 RC 1.
