### ISSUE TITLE
2.4 alpha, 'always hide in builder' bug

### ISSUE THREAD

**Issue by wplit** [soflyy/oxygen-bugs-and-features#316]
**Describe the bug**
I wrapped all contents of the page inside a div, then set conditions on the div, then I set to hide it in the builder. It didn't hide it, when I inspected the page, the CSS is being applied but is being overridden.

To fix, the CSS needs to be more specific or come later to always override in the builder.

**Screenshots**
You can see the display: none being applied but being overridden by the default div component CSS

<img src="https://i.ibb.co/Yp6V1Rx/Screen-Shot-2019-05-22-at-8-47-27-am.png" width=700>

**Comment by wplit** [comment]
eg something like..

` .oxygen-builder-body .ct_hidden_by_conditional_logic {
     display: none;
}`

**Comment by Spellhammer** [comment]
Reported internally at soflyy/oxygen#1773 - Always hide and show/hide based on condition not working for div and several other elements.

**Comment by KittenCodes** [comment]
This is fixed in the latest version of Oxygen.
