### ISSUE TITLE
[Site Navigation] Add white space and/or divider between submenu items

### ISSUE THREAD

**Issue by jkarelbroer** [soflyy/oxygen-bugs-and-features#3160]
I would like to be able to add white space (which will show the background) between submenu items. Also the possibility to add a divider line (including selecting the line color) between the submenu items would be awesome.

![White space or divider beweeen items](https://user-images.githubusercontent.com/12644053/207687773-3e586987-bd15-4371-97e6-a8acae5e16c1.png)

**Comment by Kpudlo** [comment]
Hi @jkarelbroer 

As of the 4.3 official release, this can be done in the Site Nav element via General Styles > Radius & Border > Spacing.
![image](https://user-images.githubusercontent.com/4432822/211106909-aef89417-0232-48d7-8515-51a94a631ff5.png)

**Comment by jkarelbroer** [comment]
Looks like the spacing does not apply to subitems, but only to main items:

![Item spacing](https://user-images.githubusercontent.com/12644053/211156547-15b96040-c186-4ed8-844f-c424cabcb08c.png)

**Comment by Kpudlo** [comment]
Hey @jkarelbroer, 

I'm showing the spacing works on the menu and submenu items (https://www.loom.com/share/fe8682326b194583918a0ed3a1c431a6).

 Could you see if you can recreate this on a Sandbox site? If so, please send a link to the Sandbox site so we may investigate further.
