### ISSUE TITLE
Shopify

### ISSUE THREAD

**Issue by JakobTomasBolta** [soflyy/oxygen-bugs-and-features#3168]
**Describe the feature you'd like to see included in Oxygen.**

Shopify integration as with WooCommerce.

*A clear, detailed description of the feature you're requesting.*

Shopify integration as with WooCommerce.

**What are the use cases for this feature?**
*e.g. Accessibility, e-commerce store that sells bicycles, etc.*

Many customers find themselves more familiar with Shopify.

**Examples of this feature or functionality.**

Running more webstores with Oxygen.

*If another product has done it well, provide examples here.*

**Comment by banjoBONGO** [comment]
Isn't Shopify it's own platform? I don't understand how that would be possible. Wouldn't that mean your client would need to pay a monthly fee to Shopify and to host the WordPress site? If I'm missing something please let me know...

**Comment by briandash2** [comment]
This doesn't make  sense, they are two completely different platforms. Shopify is it's own company, if you want to use Shopify you have to use their builder tools.
