### ISSUE TITLE
Site Navigation mobile menu links not clickable on ios devices

### ISSUE THREAD

**Issue by bsstiles** [soflyy/oxygen-bugs-and-features#3169]
Mobile menu links are not clickable on ios devices in the new Site Navigation component.

1. Add a site navigation component to your site.
2. Link the component to a WP menu.
3. Publish the site
4. Open the site on an iPhone
5. Try to navigate to another page on your site using the mobile menu.
6. You will notice that while the link is there (long hold, open link in new window), it cannot be selected normally.

**Comment by Spellhammer** [comment]
Which browser and iOS version are you seeing this on @bsstiles ?

**Comment by bsstiles** [comment]
@Spellhammer Thanks for the quick reply. I have tried it on both safari and chrome on ios 16.1.1.

**Comment by bsstiles** [comment]
@Spellhammer Sure, [here is the link](http://website-kit.mysites.io/) to the site I'm testing the beta on.

**Comment by Spellhammer** [comment]
Thank you. I was able to reproduce this. It'll be fixed in the next release.

**Comment by bsstiles** [comment]
@Spellhammer You da man! Thanks.

**Comment by Spellhammer** [comment]
Just committed a fix for 4.3 RC 1. Thanks a bunch for the report, and nice catch!
