### ISSUE TITLE
Repeater not working

### ISSUE THREAD

**Issue by alinbuda** [soflyy/oxygen-bugs-and-features#3170]
https://oxygen-qnhdbmx3zhl8.oxygen-demo.qsandbox.org/sample-page/

Hello there, the repeater is not working anymore.
If I add a text in a repeater and try to insert data fromthe top menu... is not doing anything. 
It stopped working 4 days ago.
1. I was unable to edit an existing repeater (Safari, Orion, Chrome)
2. I am unable to create a section to load the dynamic content from a page. Not working on Safari and Orion, but it works on Chrome. 

Cleared the cache, restart, CSS cache regeneration etc.

Here are the details of the software and computer config:

Orion Browser - Version 0.99.122-beta (WebKit 615.1.11.7)
Safari Browsers - Version 16.2 (18614.3.7.1.5)

MacBook Pro 15" 2017 - 2.8 GHz Quad-Core Intel Core i7
(macOS Ventura 13.1 build 22C65)

**Any bug report that doesn't include a Sandbox link or replication steps will be closed. If you can't provide these pieces of information, we're happy to help you via our official support channel instead: https://oxygenbuilder.com/support. You need to select "Something's broken and I need help" from the dropdown box on the left.**

**Describe the bug**
*A clear and concise description of what the bug is.*

**A link to a Sandbox site where the bug has been reproduced https://oxygenbuilder.com/try? (REQUIRED)**
*Provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*

**IF YOU CAN'T PROVIDE A SANDBOX REPRODUCTION: Steps required to reproduce the bug:**
4. Scroll down to '....'
5. See error

**If you can't fill out the above information, you should not be filing a bug report. Instead, contact us via https://oxygenbuilder.com/support with the details you have and we'll investigate your issue further.**

**Comment by Kpudlo** [comment]
Hello @alinbuda, 

Please open a support ticket so we may investigate further: https://oxygenbuilder.com/support.
