### ISSUE TITLE
Maintenance Mode feature

### ISSUE THREAD

**Issue by jkarelbroer** [soflyy/oxygen-bugs-and-features#3175]
I really would like to see Oxygen shipped with a Maintenance Mode feature.
The site should show a (to defined) page when in maintenance mode. 
Also a secret access key link for users who like to checkout the site while in maintenance mode, would be great.

**Comment by Kpudlo** [comment]
Duplicate of https://github.com/soflyy/oxygen-bugs-and-features/issues/2298
