### ISSUE TITLE
A Whole New Spin on Oxygen Builder (No More WordPress)

### ISSUE THREAD

**Issue by mfentonreb** [soflyy/oxygen-bugs-and-features#3177]
I am fed up with WordPress.  It has more holes than Swiss cheese and we keep getting our WordPress sites hacked.  20 years ago I taught myself to hand-code websites.  A lot has changed since then and websites are far more complex, including mobile optimization.  Back then I hand-coded from within Adobe Dreamweaver so I could use some of its built-in resources.  I recently noticed that Dreamweaver is still around so I downloaded a demo as I was considering using it to build a website, instead of using Oxygen, as we were trying to avoid having another WordPress site.  One day after I put up the new site, we got hacked and our SAAS site, on a subdomain of the same domain, got compromised.  Our developer was able to fix it by re-uploading his backup code, but we have now been working on mitigating the far reaching issues of the hack for a week.

My proposal is to make Oxygen Builder a stand along product that does not rely on WordPress, and make it similar to Adobe Dreamweaver, without changing the way Oxygen currently works to design websites.  It would have to allow for page handling, image handling, and SFTP or some other method of posting the site.  This is how Dreamweaver used to work.  You simply used local folders to store everything.  Then, you could use SFTP to mirror the local folders to the public_html folder on the server.  Since there won't be any plugins available, you could build in additional functionalities, such as a forms tool.  WordPress is terrible and needs to be eradicated from this planet like the server cancer that it is.  Oxygen Builder is a great piece of software and is incredibly easy to use yet still extremely powerful.  It just needs to ditch WordPress.  And the best part is, you can keep the WordPress version of Oxygen and have a non-WordPress version for higher level developers that want to get rid of WordPress.

I will probably be working on learning to use Dreamweaver again and if it's practical, we may end up moving away from Oxygen Builder in order to get rid of WordPress.

**Comment by Torwald45** [comment]
It's a good idea. There should be such possibilities: 

1. use with WP, 
2. export of a static version without a CMS (preferably with forms); something like that: https://wordpress.org/plugins/export-wp-page-to-static-html/ 
3. a new proprietary efficient CMS.

**Comment by Spellhammer** [comment]
This is not really a feature request, but more a request for a completely new piece of software.
