### ISSUE TITLE
Enhance the editor icons for a better UX - make them bigger

### ISSUE THREAD

**Issue by lucianahanan** [soflyy/oxygen-bugs-and-features#3181]
These editor icons are incredibly small, I always have difficulty telling them apart, plus they don't have the same height.

Feature Request: Make the icons bigger, the same size, and as a plus, make them blue instead of the top 'dot' from above.

I made an image for before x after comparison.  I hope you like it :)

![image](https://user-images.githubusercontent.com/1200923/210455408-951d7215-f088-4eaa-8324-201c0e8b38ce.png)

**Comment by maltmann-muc** [comment]
Those icon buttons are from Oxy Toolbox, not Oxygen.
