### ISSUE TITLE
OXYGEN i purchased full package but i dont get cpmposit elemets

### ISSUE THREAD

**Issue by hiran121** [soflyy/oxygen-bugs-and-features#3184]
i purchased full package but i dont get cpmposit elemets

**Comment by Kpudlo** [comment]
Hello @hiran121, 

To access Composite Library elements on your sites, you may need to refresh our system's license check by following these steps: https://oxygenbuilder.com/documentation/composite-elements-licensing/#licenseinstructions.

If you still have issues afterward, please get in touch with our support team via https://oxygenbuilder.com/support.
