### ISSUE TITLE
WooCommerce support request

### ISSUE THREAD

**Issue by ThoxX513** [soflyy/oxygen-bugs-and-features#3197]
I'm having trouble with the selections while establishing a Woocommerce store. My website contains button classes, and I want to maintain that appearance when using woocommerce buttons. With ten different button designs, it would look ridiculous. However, it is not feasible to overwrite the CSS class for Woocommerce Buy buttons. The old woocommerce design is still contained within that class button because something keeps overwriting it, resulting in the final result of 2 buttons. I encounter some problems while attempting to duplicate the class design using the woocommerce integration plugin product builder. I can alter the button's hover background color, but not the hover color of the text. You already have this feature in the product-tabs, there I can change the active tab text color and the hover text color separately from the background

**Describe the feature you'd like to see included in Oxygen.**
*A clear, detailed description of the feature you're requesting.*

**What are the use cases for this feature?**
*e.g. Accessibility, e-commerce store that sells bicycles, etc.*

**Examples of this feature or functionality.**
*If another product has done it well, provide examples here.*

**Comment by Kpudlo** [comment]
Hello @ThoxX513, 

Please open a Support Ticket (https://oxygenbuilder.com/support) regarding this issue. We'll be glad to help you further there.
