### ISSUE TITLE
display flex styles not applying in stylesheet - only in Oxygen dashboard

### ISSUE THREAD

**Issue by andrewschaeffer** [soflyy/oxygen-bugs-and-features#3205]
Problem: When I enter this code in a stylesheet it doesn't take effect for the first flex item in the flex container - only the other children:

display:flex;
flex-direction:column;
align-items:center;

But, If I enter the above information in the Oxygen dashboard, everything works.

First element missing styling (and sticking to the left): 
![Screen Shot 2023-01-24 at 6 47 34 AM](https://user-images.githubusercontent.com/66330360/214325909-4220d3c2-87eb-439a-918f-fea5f7f7908a.png)

Thanks for taking a look!

**Comment by Spellhammer** [comment]
Thanks for the report, but we need some more details.

1. What is the entirety of the CSS you're using? What you provided isn't valid CSS. It's missing a selector.
2. What do you mean by "enter the above information in the Oxygen dashboard"? 
3. How is the way you're adding the CSS different than "entering the above information in the Oxygen dashboard"?
