### ISSUE TITLE
Emmet CLI for adding Oxygen elements

### ISSUE THREAD

**Issue by Spellhammer** [soflyy/oxygen-bugs-and-features#3214]
https://github.com/soflyy/oxygen/issues/4722

This feature would allow the use of Emmet abbreviations to add Oxygen elements inside of the builder. Example:
```
section.grid-class>(div>heading{Grid column}+text)*2
```

Executing this would add an Oxygen Section with the class "grid-class", with two Divs as children, each containing a Heading with the text "Grid column" and a text element.

**Comment by Spellhammer** [comment]
Just released in 4.5 beta 1: https://oxygenbuilder.com/2023/02/03/oxygen-4-5-beta-1-now-available/

**Comment by DeivisPau** [comment]
Would be awesome to get this integrated with WP-CLI or to have API for this outside of Oxy builder.
