### ISSUE TITLE
Better code editor.

### ISSUE THREAD

**Issue by Spellhammer** [soflyy/oxygen-bugs-and-features#3215]
This would involve updating CodeMirror and implementing some of its newer features, including a better search, linting, etc...

https://github.com/soflyy/oxygen/issues/4830

**Comment by karmaral** [comment]
Please consider adding vim keymap support! It's only a CodeMirror plugin away and it would add up a ton <3

**Comment by Spellhammer** [comment]
Code editor improvements added in 4.7, now available as a beta.

**Comment by Spellhammer** [comment]
This also closes:

https://github.com/soflyy/oxygen-bugs-and-features/issues/2504
https://github.com/soflyy/oxygen-bugs-and-features/issues/2681
