### ISSUE TITLE
Compatibility issue with plugin LearnPress

### ISSUE THREAD

**Issue by rich88812** [soflyy/oxygen-bugs-and-features#322]
**Describe the bug**
Installing the wordpress plugin LearnPress when Oxygen is installed (https://en-gb.wordpress.org/plugins/learnpress/) causes Wordpress to crash.

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
Yes

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
*If yes, provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*
Yes - although having installed the plugin, the site is no longer accessible: http://energetic-hippopotamus.w5.wpsandbox.pro

**To Reproduce**
1. Have oxygen installed
2. Goto Add new plugins page
3. Install LearnPress & Activate
4. Wordpress crashes

**Expected behavior**
*A clear and concise description of what you expected to happen.*
LearnPress should be installed without any issues.

**What actually happens**
*A clear and concise description of what happens instead of the expected behavior.*
Wordpress crashes and is no longer available

**Screenshots**
*If applicable, add screenshots to help explain your problem.*

**Desktop (please complete the following information):**
- OS: macOS 10.14.5
 - Browser Chrome Version 74.0.3729.169
 - Oxygen Version 2.3

**Smartphone (please complete the following information):**
 - Oxygen Version [e.g. 2.2 Alpha]

**Additional context**
*Add any other context about the problem here.*

**Comment by Spellhammer** [comment]
@rich88812 We've looked into this previously, and the LearnPress team provided the following code fix. You'll have to implement it in a LearnPress plugin file, so **make sure to perform a backup before making these changes, and note you'll have to re-implement this any time you update the LearnPress plugin.**

In the /learnpress/inc/admin/lp-admin-actions.php there is a function called _learn_press_set_user_items. Replace this entire function with this code:
```PHP
function _learn_press_set_user_items( $query ) {
global $post_type, $pagenow, $wpdb;
if ( !did_action('plugins_loaded') || current_user_can( 'manage_options' ) || ! current_user_can( LP_TEACHER_ROLE ) || ! is_admin() || ( $pagenow != 'edit.php' ) ) {
return $query;
}
if ( ! in_array( $post_type, apply_filters( 'learn-press/filter-user-access-types', array(
LP_COURSE_CPT,
LP_LESSON_CPT,
LP_QUIZ_CPT,
LP_QUESTION_CPT
) ) )
) {
return;
}
$items = $wpdb->get_col(
$wpdb->prepare(
"SELECT ID FROM
$wpdb->posts
WHERE post_type = %s
AND post_author = %d",
$post_type,
get_current_user_id()
)
);

if ( count( $items ) == 0 ) {
$query->set( 'post_type', 'no-item-access' );
} else {
$query->set( 'post__in', $items );
}
add_filter( 'views_edit-' . $post_type . '', '_learn_press_restrict_view_items', 10 );
}
```
