### ISSUE TITLE
Oxygen rendering ACF date field set to September as October

### ISSUE THREAD

**Issue by tituss** [soflyy/oxygen-bugs-and-features#3222]
I've setup an ACF date field. In the Sample page, I have set the date to Sepember 2023. 
In Oxygen, I have called the acf field into a text field. The date is incorrectly displaying as September. 

Rendering the ACF field using php in a code block works correctly.

https://oxygen-q7qpn9scy3yql.oxygen-demo.qsandbox.org/
Access Code: 5123

Not a huge bug, but a tad confusing...

**Comment by Kpudlo** [comment]
Hi @tituss, 

When I view the sandbox site, it shows September 2023 for both the Text field and Code Block methods: 
![image](https://user-images.githubusercontent.com/4432822/217821475-8af00986-a4c6-4c54-aa55-a48a40097e1b.png).

If you still see issues with this, please provide any additional steps to see the problem so we may investigate further.

**Comment by tituss** [comment]
HI Kpudio
Well that's very odd.  It was defenitely an issue when I added the initial comment, but it seems fine now.  I tested this in mulitple browsers before I replicated the issue in the sandbox, so not quite sure how/why it's remedied itself. Anyway - thanks for looking at this - sorry if it was a waste of your time - it defeinetly wasn't working before though.
