### ISSUE TITLE
[2.4 Alpha] Can't select ACF in condition for reusable template

### ISSUE THREAD

**Issue by sunnyt7** [soflyy/oxygen-bugs-and-features#323]
When setting a condition for any element, you have the option to select an Advanced Custom Field:

![image](https://user-images.githubusercontent.com/5510344/58275404-ee500780-7d62-11e9-9d32-8f386513effb.png)

However, when setting the condition for a reusable template, the ACF option doesn't show up:

![image](https://user-images.githubusercontent.com/5510344/58275434-045dc800-7d63-11e9-94d8-5464df0f28f5.png)

**Comment by Spellhammer** [comment]
I think this may be related to the way Oxygen identifies ACF fields for the dynamic data modal. Can you apply some field group to that re-usable template by its ID and see if they show up?

**Comment by sunnyt7** [comment]
> 
> 
> I think this may be related to the way Oxygen identifies ACF fields for the dynamic data modal. Can you apply some field group to that re-usable template by its ID and see if they show up?

Ah, you got it. In the field group, you just need to assign Post Type > Template (ct_template). Shows up now.
