### ISSUE TITLE
Uncaught TypeError: Cannot read properties of null (reading 'scrollHeight')

### ISSUE THREAD

**Issue by switchupcb** [soflyy/oxygen-bugs-and-features#3234]
**Describe the bug**
An uncaught type error occurs while scrolling (with the use of a back-to-top element.

The line of code containing the error can be found in `function oxyScrollFunc()`.
```js
const height = document.getElementById("content").scrollHeight - document.documentElement.clientHeight;
```

**Reproduction**
View the console while scrolling at https://switchupcb.com/blog/series/the-basics-of-software-development/.

**Comment by Kpudlo** [comment]
I'm unable to recreate this issue on a fresh sandbox. If possible, please recreate this issue on a sandbox site or open a Support Ticket (https://oxygenbuilder.com/support) with credentials to the site in question, and we'll be glad to investigate further.

**Comment by switchupcb** [comment]
@Kpudlo I fixed the issue. This technically isn't an issue with Oxygen, thanks.
