### ISSUE TITLE
DONE: Support for Line wrapping and more in Code editor

### ISSUE THREAD

**Issue by srikat** [soflyy/oxygen-bugs-and-features#324]
Note: Also see [this](https://github.com/soflyy/oxygen-bugs-and-features/issues/20) request.

If it is decided to stick with the current library for the code editor [CodeMirror](https://codemirror.net/), please consider adding options for enabling these in Oxygen's settings:

1. Font size change
2. Line wrapping
3. Code folding
4. Search and replace
5. Bracket and tag matching

Thanks in advance.

**Comment by wpdevlab** [comment]
+1

**Comment by perrelet** [comment]
Bump Bump!

Or even **better** yet (and much simpler):

Have an option to just turn CodeMirror off (thus leaving the code window as a standard <textarea> element). We could then use something like:

https://chrome.google.com/webstore/detail/edit-with-sublime-text/eiejadjdcchfommckmikpcdnihljbpai?hl=en

And have all the power of sublime without trying to recreate these functionalities in the browser...

**Comment by srikat** [comment]
@perrelet

Just tested that extension and it is working  Oxygen editor's Code Blocks.

1. Select all the text in the Code Block. If we do not select the existing code, text/code from Sublime Text will get appended at the cursor location.

2. Right click and choose Edit with Sublime Text.

3. Make changes. You may want to turn on the appropriate syntax highlighting (PHP or CSS etc).

4. Press Ctrl/Cmd + S.

5. Code in the Code Block gets replaced.

You can always of course instead, simply copy from Oxygen, paste in Sublime Text or other editor, make changes and repeat copy + paste.

Warning: This plugin requires downloading additional software from outside Chrome extensions site and running a shell command (at least on Mac and Linux) which may be a security concern. So proceed at your own risk.

**Comment by perrelet** [comment]
Hi @srikat

I'm unable to replicate the level of stability you describe.

Whilst I can successfully send between sublime and CodeMirror once or twice, things get real jancky thereafter. When it does work, its slow - when it doesn't it's useless. This behavior is something we should perhaps expect since CodeMirror populates the dom with a whole family of elements to render each line of code.

Controversy, When using the sublime extension to edit a standard <textarea> element (like the one I'm editing right now in Sublime), the behavior is stable and saves are pretty much instant.

### Therefore: we really do need an option to switch CodeMirror off in oxygen.

**Comment by studioavanti** [comment]
Agreed, CodeMirror in Oxygen lacks of options: 
- Wrap lines
- Keyboard shortcut to comment
- Find/Replace
- …

I found a solution to wrap lines in the code editor by editing Oxygen core files that initialize CodeMirror. 
For example this file for editing Oxygen stylesheets: 
`plugins/oxygen/component-framework/toolbar/⁨views⁩/style-sheet.view.php`

…and add this option to the <textarea> part: 
`lineWrapping: true`

It's a poor solution, should be done from outside the plugin's folder obviously.

**Comment by iamrufus** [comment]
+1 the ability to be able to write custom html and css with auto completion for html tags and css properties would speed up workflows.

**Comment by Spellhammer** [comment]
Implemented CodeMirror improvements in 3.8 alpha 1, including:

1. line wrapping
2. tag & bracket matching

Font size option, code folding, and search & replace were not implemented.

**Comment by perrelet** [comment]
That's awesome @Spellhammer!

Any chance we can have an option to turn off CodeMirror **altogether**?

With a plain textarea, we'd be able to use an actual editor instead of the browser window...

Ta!

**Comment by wpsumo** [comment]
@Spellhammer awesome, could we add search foncution in code blocks and stylesheet tabs? Even cmd/ctrl + f never work to search within the editor. Not in chrome with firefox. But would ne nice with it build in. Most code editors have a search function.

**Comment by Spellhammer** [comment]
Marking as done/closed. Further enhancements to our CodeMirror implementation should be posted as separate feature requests.
