### ISSUE TITLE
Code blocks are being arbitrarily overwritten

### ISSUE THREAD

**Issue by jessebrightman** [soflyy/oxygen-bugs-and-features#3245]
Code blocks are being arbitrarily overwritten with other code blocks.

**Comment by Kpudlo** [comment]
Hi @jessebrightman, 

Could you please provide some examples of how this is happening? If you can recreate this issue on a Sandbox site (https://oxygenbuilder.com/try/), please send us a link to the site, and we'll be glad to investigate further.

**Comment by Spellhammer** [comment]
No repro steps or information given. Please submit a support ticket instead: support@oxygenbuilder.com
