### ISSUE TITLE
Events category does not display correctly in Oxygen 4.4

### ISSUE THREAD

**Issue by nd-ops** [soflyy/oxygen-bugs-and-features#3250]
Between Oxygen 4.0 and 4.4, the events associated with a selected category does not display correctly. I don't have versions 4.1, 4.2 or 4.3 to be able to say exactly where the issue was introduced.

Below is the expected view displayed using Oxygen 4.0:

![event-category-page-EXPECTED](https://user-images.githubusercontent.com/126437515/221470148-b37ccda5-4e9d-4809-9b19-c140f115cab9.png)

After updating to Oxygen 4.4: 

![event-category-page-CURRENT](https://user-images.githubusercontent.com/126437515/221471033-30dd85e6-73de-42eb-9619-ec343077e0e5.png)

**Link to Sandbox site where the bug has been reproduced**
https://oxygen-q2jczldvspcrl.oxygen-demo.qsandbox.org/events/category/st-patricks-day/

**Steps to reproduce the behavior:**
1. Go to https://oxygen-q2jczldvspcrl.oxygen-demo.qsandbox.org/event/st-paddys-day-stroll
2. Under Event Category, click on St. Patrick's Day
3. See incorrect display of event category.

**Comment by Kpudlo** [comment]
Hi @nd-ops, 

I believe if you set the Event Archive template to apply to Taxonomies > All Event Categories (https://d.pr/i/RlhJnX), everything will work as expected. 

Please let us know if that fixes the issue you see.

**Comment by nd-ops** [comment]
That worked! Thanks so much for the solution!
