### ISSUE TITLE
Pseudo Elements are not working on the transparent image (png)

### ISSUE THREAD

**Issue by mzosama** [soflyy/oxygen-bugs-and-features#3255]
Hi Oxygen,

The Pseudo Elements are not working on the transparent image (png). 

1. I used code block to add the css code (before/after).
2. .blur class is used
3. Applied the blur class to the transparent image (png). Blur effect not working
4. Applied the same blur class on text and it is working.
5. I also tried the same effect using the oxygen built-in css state and fetched same results as mentioned above.

The reason, i am not using the oxygen default css state feature is to control the pseudo elements in one place and quickly make changes without clicking the menus several times.

Refer to the sandbox site.
https://oxygen-qt6z6flm5yfrl.oxygen-demo.qsandbox.org/home/

Kindly advise suitable workaround.

Regards

Usama Zulfiqar

**Comment by Kpudlo** [comment]
Hello @mzosama, 

I'm very sorry, but the sandbox site had expired before we had a chance to look into this. I've tried to replicate this on a Sandbox site, but haven't been able to. If you could recreate another sandbox so we can investigate further, that would be appreciated. 

Does this effect work for a PNG with standard HTML?

**Comment by mzosama** [comment]
Hi Oxygen

I have created the sandbox, kindly refer to the new sandbox

https://oxygen-q4dz6q358gtrl.oxygen-demo.qsandbox.org/home/

The "myblur" CSS class is applied to transparent img and text

1. On text, "myblur" class with Pseudo Elements is working
2. On transparent img, "myblur" class with Pseudo Elements is not working

Kindly see the website structure on the right side of the oxygen builder.

Please guide.
