### ISSUE TITLE
DONE: Add line-height as a global setting for all the headings

### ISSUE THREAD

**Issue by guyinpv** [soflyy/oxygen-bugs-and-features#326]
In Global Styles for Heading settings, you have the font size, weight, and color. 
It would be nice to see line-height in here, as this has a pretty big effect on the look of headings when they wrap. I'd like to be able to set them in this global section, rather than always have to create custom CSS for that later.

For that matter, letter spacing could also be a common one to add.

Thanks

**Comment by KittenCodes** [comment]
Line height can now be set on all the different heading sizes via Manage > Settings > Global Settings > Headings.
