### ISSUE TITLE
Proteus Theme does not load properly on New Install from theme library

### ISSUE THREAD

**Issue by orbeavers14** [soflyy/oxygen-bugs-and-features#3266]
Sandbox Link: https://oxygen-qfj5hyl3jyjrl.oxygen-demo.qsandbox.org/

When attempting to load the Proteus theme via the GUI's theme library, it shows it was successful, but when going to view the website afterwards, a blank page is all that is presented. No filler content, headers, body, etc.

**A link to a Sandbox site where the bug has been reproduced ---  https://oxygen-qfj5hyl3jyjrl.oxygen-demo.qsandbox.org/

**Comment by Kpudlo** [comment]
After installing a Design Set, please go to Settings > Reading in the WordPress Admin (/wp-admin) area and set the Home page to the installed home page. It should then display as expected on the front end.
