### ISSUE TITLE
Text span disappears when changing heading tag

### ISSUE THREAD

**Issue by guyinpv** [soflyy/oxygen-bugs-and-features#327]
**Describe the bug**
If I change the heading tag on a heading which has span parts, the span parts disappear in the visual editor, though the text still exists.

**To Reproduce**
1. Add a heading of an h2 anywhere.
2. Put a span around some of the text, perhaps change the color.
3. Now select the heading and change it to h3 or other.
4. The span part of the text will disappear.

**Desktop (please complete the following information):**
- OS: Win 10 Pro
 - Browser: tested in Chrome and Firefox
 - Oxygen Version: 2.3

**Additional context**
If it matters, the heading is placed inside a normal section that itself has a background color.

**Comment by KittenCodes** [comment]
This works correctly in the latest version of Oxygen.
