### ISSUE TITLE
Hover state of icon doesn't work  / has corrupted CSS

### ISSUE THREAD

**Issue by m-schmale** [soflyy/oxygen-bugs-and-features#3275]
**Bug description**
When I hover over an icon the background color doesn't change.

This is the CSS generated by Oxygen:
```
#fancy_icon-2-11:hover {
    padding:
}
```

**Link to a Sandbox site where the bug has been reproduced**
[https://oxygen-qs753zpa83trl.oxygen-demo.qsandbox.org/](https://oxygen-qs753zpa83trl.oxygen-demo.qsandbox.org/)

**Steps required to reproduce the bug**
1. Insert an icon
2. Change icon style to solid
3. Change background color of the hover state
4. Hover over the icon
5. See the error 😉

**Comment by Spellhammer** [comment]
Thanks for the report! This should be fixed in Oxygen 4.6. You can download & test with the current beta of Oxygen 4.6 at https://oxygenbuilder.com/portal.
