### ISSUE TITLE
DONE: Visual Loop Builder

### ISSUE THREAD

**Issue by wplit** [soflyy/oxygen-bugs-and-features#328]
_added here as it's a feature that has been mentioned across different channels in different ways, but i couldn't find an official feature request to be able to discuss and vote_

**Describe the feature you'd like to see included in Oxygen.**
To be able to visually build elements that would be part of a loop.

**What are the use cases for this feature?**
- Featured Pages & Post types built visually
- Product listings
- Helper components such as testimonials could be pulling dynamic data from CPT
- Building FAQ accordians.
- Possible integration with ACF repeater field.

..basically any loop, but instead of using Easy Posts and writing the php template, we'd be using the builder to be visually building one instance of the post, adding in the dynamic data fields then using query controls to control the loop.

**Discussion**

As we don't know if you guys/gals are working on it yet, or if you are, how far along, I thought I'd open up a single point of discussion where people could share their use cases and needs. There have been conversations in the FB group and feature requests that were describing a similar problem needing solving.

[FB discussion](https://www.facebook.com/groups/1626639680763454/permalink/1905071412920278/)
[2nd FB discussion](https://www.facebook.com/groups/1626639680763454/permalink/2170671939693556/?comment_id=2172100672884016&comment_tracking=%7B%22tn%22%3A%22R%22%7D)
[3rd FB discussion](https://www.facebook.com/groups/1626639680763454/permalink/1906156239478462/)
[4th](https://www.facebook.com/groups/1626639680763454/permalink/1893774307383322/)

Similar Github request - [Easy Post Visual Designer](https://github.com/soflyy/oxygen-bugs-and-features/issues/208)
Similar Github request - [Splitting Code Block](https://github.com/soflyy/oxygen-bugs-and-features/issues/211)
Similar Github Request - [Add Query Argument Options To Templates](https://github.com/soflyy/oxygen-bugs-and-features/issues/303)
Old Forum Post - [Visual Builder for Post Loop Output](https://oxygenbuilder.com/forums/topic/visual-builder-for-post-loop-output/)

**My thoughts:** 

I think this would be best as a new, more generic 'loop builder' or wrapper component, as opposed to being Easy Posts with a few extra features. The reason is that i think a good direction for Easy Posts to go would be to better help users achieve more magazine type layouts easily. Think [Elementor's posts widget](https://docs.elementor.com/article/101-posts) (full disclosure - haven't used it, just watched the video) where it focuses on helping users create & customise lists/grids of post for their archive pages. Basically what the default Easy Posts templates already do, but with more options and less needing to edit the templates. (control number of items per row for eg, which currently we need to edit the template CSS).

A loop builder however, could have a different objective and have a more flexible way of going about loops. It could act as a sort of wrapper that we could place around a group of elements with Query parameter controls. We could then make anything part of a loop and then use the dynamic data to pull in the content when needed, we'd be using the same UI controls as always to build elements using helpers etc.

**Comment by albertso** [comment]
We also need a way to make a slider with dynamic content:
https://github.com/soflyy/oxygen-bugs-and-features/issues/19

**Comment by reders2** [comment]
Loopbuddy by iThemes was a favourite plugin of mine as someone not overly comfortable with php, it was an easy way to organise and customise any type of post. Being able to do it visually in oxygen want take it to another level.

**Comment by AmibeWebsites** [comment]
First hour using Oxygen and the design calls for a slider on the home page of the three latest news articles. What I would imagine being able to do (based on something similar I built for Elementor) is to design and layout a slide template using Oxygen and dynamic fields, select that template in Easy Posts as an alternative to writing out a php template (I never want to do that again... it's like stepping backwards), and then selecting 'Slider' as one of the post layout options.

An alternative would be to use the Slider component but instead of specifying different slider there would be a dynamic option that allow for a custom query and template selection (as with Easy Posts).

If I was to build this like what I did for Elementor I'd need to know how to hook into and extend Oxygen - is it even possible?

**Comment by AmibeWebsites** [comment]
Found a little workaround using code from the Reusable component that seems to work... create a reusable template and layout everything required for a single post, then insert the following code into the PHP template part of Easy Posts replacing {{ id }} with the reusable template's ID:
```
<?php
$shortcodes = get_post_meta( {{ id }}, "ct_builder_shortcodes", true );

$count = 0; // safety switch
while(strpos($shortcodes, '[oxygen ') !== false && $count < 9) {
	$count++;
	$shortcodes = preg_replace_callback('/(\")(url|src|map_address|alt|background-image|oxycode|value)(\":\"[^\"]*)\[oxygen ([^\]]*)\]([^\"\[\s]*)/i', 'ct_obfuscate_oxy_url', $shortcodes);
}
		
echo do_shortcode( $shortcodes );
?>
```

**Comment by AmibeWebsites** [comment]
Apologies, in my ignorance I had not realised this functionality has been added to Oxygen 3.0. The component that does this is the Repeater. Hopefully this will help all those looking for this functionality.

**Comment by alanzirpoli** [comment]
+1
