### ISSUE TITLE
HTML Header Truncated

### ISSUE THREAD

**Issue by KeanuTang** [soflyy/oxygen-bugs-and-features#3288]
https://oxygen-qgsxp2vj2f8rl.oxygen-demo.qsandbox.org/

This is pretty simple to reproduce. All I did was create a new site through the sandbox. When you view source, the HTML header is cut off. Is this by design? We're missing plugin CSS/JS that is necessary, as well as other tags like TITLE.

I included an image of the source. You can see the HTML starts near the end of the HEAD tag.

![image](https://user-images.githubusercontent.com/121991155/234671299-88d22e9f-7ac8-45fd-bdb0-0b60d00e0a6a.png)

**Comment by maltmann-muc** [comment]
Did you try to click "Line wrap" in the source code view or just scroll to the right?
It's likely that all the head information is emitted in one line and you just don't see it.
You better check with the browser's element inspector instead of the source code view.
I never had an issue with the head / meta information.

**Comment by KeanuTang** [comment]
It's a functional problem. Not a visual artifact. I'm happy to reproduce it any time. I know for a fact it's a functional problem because the missing CSS/JS causes functional problems with the page.

I just recreated the issue. It's super simple, so I suggest you try it first. Just create a blank website with the sandbox tool. View the source of the page. You'll see the issue.
https://oxygen-qypftzta2qbsl.oxygen-demo.qsandbox.org/

I see the same issue in this person's bug report/sandbox as well: https://github.com/soflyy/oxygen-bugs-and-features/issues/3290

**Comment by KeanuTang** [comment]
@Spellhammer my group has run in to this problem twice. I'm not 100% sure, but I think it happened when we after we had pages created and then installed Oxygen. Each time, we weren't sure what to do because the main content of the page is driven by a shortcode. So there is no layout or editing that we expected to do in Oxygen. 

I still think this is a legitimate bug. If your response is "we just aren't going to fix this," it is what it is. At least give some kind of warning when turning on Oxygen if we have existing pages. We wasted days figuring this out for our shortcode pages.

**Comment by KeanuTang** [comment]
@Spellhammer In addition, the person who posted issue https://github.com/soflyy/oxygen-bugs-and-features/issues/3290 has the same issue on her sandbox. So this is probably more common than you think.

**Comment by juditth** [comment]
@KeanuTang Yes - it's happening on any Oxygen site I was able to find, even in Sandbox. 
I found out the embed version of pages is formatted wrong. 
E.g. This is normal post: https://www.great-tit.com/custom-excerpt-lenght-in-oxygen-and-wordpress/
And this should create the embed post (with the nice "Wordpress style" format prepared for embedding) - and it's not happening. There is complete site, not the frame, title... etc. 
https://www.great-tit.com/custom-excerpt-lenght-in-oxygen-and-wordpress/embed/ - with the /embed at the end.

**Comment by KeanuTang** [comment]
Not sure why this was marked at closed. This is a bug. And it's particularly bad when trying to use the Oxygen + Gutenberg integration feature that allows you to create blocks from Oxygen elements. 

For example, from Oxygen, I convert an Oxygen element to be a Gutenberg block. I then create a blank Gutenberg page and use that block. The page itself renders in a broken state because the header is truncated and missing much of the required styles/javascript. This is a bug.

**Comment by maltmann-muc** [comment]
@KeanuTang 
Oxygen is a plugin to replace your theme. Oxygen is meant to "build your own theme".
Having no Oxygen template at all is like having no theme at all.

This is exactly the situation, @Spellhammer was describing for the sandbox mentioned above: There isn't a single template, so basically no "theme". 

It would be the same as installing WordPress and then deleting all themes. You won't get any usable output.

If you want to use Oxygen just for creating Gutenberg blocks and nothing else, you still have to create at least one Main template containing at least an Inner Content element.

**Comment by KeanuTang** [comment]
I have an example here where I have created a simple template and page. The header is still getting truncated even through I have a template for the page.

https://dev.c3engine.com/

![oxygen bug 5](https://github.com/soflyy/oxygen-bugs-and-features/assets/121991155/dd1bfc62-bf4a-4b8b-be3c-87d2354b9173)
![oxygen bug 3](https://github.com/soflyy/oxygen-bugs-and-features/assets/121991155/47eec8c8-3c2d-4e27-8214-e75e88f63868)
![oxygen bug 4](https://github.com/soflyy/oxygen-bugs-and-features/assets/121991155/723012bd-77c0-4797-82cc-746a51e907a6)
![oxygen bug 6](https://github.com/soflyy/oxygen-bugs-and-features/assets/121991155/0427e728-107d-44ba-b3ff-3660bf113588)

**Comment by Kpudlo** [comment]
Hello @KeanuTang, 

Please open a Support Ticket (https://oxygenbuilder.com/support) so we can investigate your issue further.

**Comment by KeanuTang** [comment]
Ok I think I figured it out. I need to have an **Oxygen template**, not a **Gutenberg template**. That seems to have fixed the truncation. It feels like a little odd because my goal is to build a Gutenberg page using the Oxygen elements. But creating the Oxygen template did address the truncation.

**Comment by AlkoKod** [comment]
Hello, I just found that /embed/ is not working on my website great-tit.com which is mean here. What should I do to fix it?

**Comment by KeanuTang** [comment]
@AlkoKod I don't understand how that relates to the problem in this thread. Can you explain more?

**Comment by juditth** [comment]
@AlkoKod That's different issue: https://github.com/soflyy/oxygen-bugs-and-features/issues/3290
