### ISSUE TITLE
[Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event

### ISSUE THREAD

**Issue by inferno-adam** [soflyy/oxygen-bugs-and-features#329]
**Describe the bug**
*JavaScript violation errors are present in Google Chrome on MacOS. Full log of the errors is attached. I see the errors on your sandbox and my local dev instance. I do not see these errors in Safari.*

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
*Yes*

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
*Yes - http://magnificent-pigeon.w5.wpsandbox.pro/?ct_builder=true&ct_inner=true*

**To Reproduce**
1. Go to 'Oxygen Visual Builder' in MacOS Google Chrome version 74.0.3729.169 (Official Build) (64-bit).
2. Go to 'View -> Developer -> JavaScript Console'.
3. See error

**Expected behavior**
*No console errors should be shown.*

**What actually happens**
*Oxygen Visual Builder is eventually loaded but takes longer than usual. Pages/templates seem to save just fine.*

**Screenshots**
*See attached console log.*

**Desktop (please complete the following information):**
- OS: MacOS Mojave
 - Browser: Google Chrome Version 74.0.3729.169 (Official Build) (64-bit)
 - Oxygen Version: 2.3

[magnificent-pigeon.w5.wpsandbox.pro-1559046269768.log](https://github.com/soflyy/oxygen-bugs-and-features/files/3227610/magnificent-pigeon.w5.wpsandbox.pro-1559046269768.log)

**Comment by KittenCodes** [comment]
@inferno-adam I can't replicate this in the latest version of Oxygen. If you're still having problems, please check for a plugin conflict. If that doesn't help, please email login credentials for your site and a link to where we can see the errors to support@oxygenbuilder.com.

**Comment by inferno-adam** [comment]
@KittenCodes The problem has been resolved in the latest version. Thank you for checking into it.

**Comment by KittenCodes** [comment]
Thanks @inferno-adam
