### ISSUE TITLE
DONE: Find and find-and-replace in Oxygen Stylesheet Editor

### ISSUE THREAD

**Issue by spinoWeb2** [soflyy/oxygen-bugs-and-features#3298]
Often there are several style sheets or fairly large style sheets.

It would be useful if there was the possibility of find and find-and-replace. 
These features are typical of any editor and there is no need to add more about their usefulness!

**Comment by Kpudlo** [comment]
Hello @spinoWeb2, 

This was introduced in Oxygen 4.7 Beta 1 due to a similar request from https://github.com/soflyy/oxygen-bugs-and-features/issues/2504. You can download and test the beta version via the Oxygen Customer Portal (https://oxygenbuilder.com/portal/).
