### ISSUE TITLE
Metabox 5.7.1 and Images

### ISSUE THREAD

**Issue by flowww-dev** [soflyy/oxygen-bugs-and-features#3312]
There is a error with Metabox 5.7.1 and Breakdance (all Versions - I know). 

If you choose a Image in Breakdance (Image Element, Background Image and so on) there is a error:

Internal Server Error
Attempt to read property "id" on null.

**Comment by Kpudlo** [comment]
Hello @flowww-dev, 

This repository is for Oxygen-related issues only. If you're having a problem with Breakdance, you would want to report a bug at https://github.com/soflyy/breakdance-bugs/issues/new/choose. 

That being said, this issue has been reported already: https://github.com/soflyy/breakdance-bugs/issues/813.
