### ISSUE TITLE
Upgrading Oxygen affects Full Width sections by reducing their inner container width to less than 100 percent.

### ISSUE THREAD

**Issue by Flipback8** [soflyy/oxygen-bugs-and-features#3313]
Oxygen Sandbox: https://oxygen-qblgq6km2lt8.oxygen-demo.qsandbox.org/
Access Code: 5676

Video illustrating issue: https://vimeo.com/831743465/eedefeff1f

Issue: Upgrading Oxygen affects Full Width sections by reducing their inner container width to less than 100 percent.

I set a background color to the inner section so you can see the issue.

.ct-section-inner-wrap {
	background-color:gray;
}

Reproduce by setting a section to full width. set a background color on the inner section  so you can see the change. 
Then, update Oxygen.

You can see the process in the video provided.

<img width="746" alt="Screenshot 2023-05-30 at 11 50 43 PM" src="https://github.com/soflyy/oxygen-bugs-and-features/assets/12590359/bd6332ac-8a8c-46ee-9837-54672b6513c1">

<img width="303" alt="Screenshot 2023-05-31 at 12 11 15 AM" src="https://github.com/soflyy/oxygen-bugs-and-features/assets/12590359/d6f0b042-946c-4698-a907-e72bbcee32d7">

![c64be61b-fb58-4327-900e-9e5dc3a647b4](https://github.com/soflyy/oxygen-bugs-and-features/assets/12590359/6c508050-91f5-4b26-b0b7-7a5f632c276f)

<img width="866" alt="Screenshot 2023-05-30 at 11 38 51 PM" src="https://github.com/soflyy/oxygen-bugs-and-features/assets/12590359/04d6dd1b-657f-49ef-8dc1-0409eb9e6729">

<img width="1777" alt="Screenshot 2023-05-30 at 11 48 58 PM" src="https://github.com/soflyy/oxygen-bugs-and-features/assets/12590359/cb76b798-ab3c-414b-8fb8-1a4488385f28">

Also note that resigning Shortcodes and Regenerating CSS does not resolve the issue.

**Comment by Kpudlo** [comment]
Replicated and reported internally via https://github.com/soflyy/oxygen/issues/5080

**Comment by Spellhammer** [comment]
If you're having this issue, please download & test 4.6.2 RC 1 from https://oxygenbuilder.com/beta-access/ and let us know if it resolves the problem for you.

**Comment by Spellhammer** [comment]
Fixed in Oxygen 4.6.2.

**Comment by Flipback8** [comment]
> 

Updated to 4.6.2 but the damage has already been done. The only thing that keeps the section full width is my CSS to correct the issue: 

/* Make inner Section wrapper 100% Width */
.ct-section-inner-wrap {
	width: 100%;
}

**Comment by Spellhammer** [comment]
> > 
> 
> 
> 
> Updated to 4.6.2 but the damage has already been done. The only thing that keeps the inner section wrapper full width is my CSS to correct the issue: 
> 
> 
> 
> /* Make inner Section wrapper 100% Width */
> 
> .ct-section-inner-wrap {
> 
> 	width: 100%;
> 
> }

You can fix it by regenerating the CSS cache.

**Comment by Flipback8** [comment]
> > > 
> > 
> > 
> > Updated to 4.6.2 but the damage has already been done. The only thing that keeps the inner section wrapper full width is my CSS to correct the issue:
> > /* Make inner Section wrapper 100% Width */
> > .ct-section-inner-wrap {
> > width: 100%;
> > }
> 
> You can fix it by regenerating the CSS cache.

Okay regenerating CSS cache fixed the issue. Thanks for the quick reply.
