### ISSUE TITLE
add to cart issue

### ISSUE THREAD

**Issue by ValeriaCom** [soflyy/oxygen-bugs-and-features#3315]
Hi, I need support because I notice a malfunction of the plugin on this e-commerce [https://www.evospace.it/shop/] and especially on the ‘add to cart’ event which always tracks the wrong product. Can I get support to solve this problem? Thanks in advance.

**Comment by Spellhammer** [comment]
Hey @ValeriaCom, this repo is for posting bug reports. If you need support, please email support@oxygenbuilder.com and we'll be happy to help.
