### ISSUE TITLE
Buttons are forced to add a black border

### ISSUE THREAD

**Issue by ouengai** [soflyy/oxygen-bugs-and-features#3321]
The first Button in Modal would be forced to add a black border when the Modal's Trigger chooses "On exit intent".

Sandbox: https://oxygen-q7lfl8nv5hrsl.oxygen-demo.qsandbox.org/sample-page/

PS: This is my first time submitting bugs via sandbox. If the sandbox's link is wrong, please reply me.

**Comment by Kpudlo** [comment]
Hello @ouengai, 

The link you sent was perfect, thank you! 

**> The first Button in Modal would be forced to add a black border when the Modal's Trigger chooses "On exit intent".**

In Oxygen, the first focusable element in the Modal automatically has focus when the Modal is opened, and the default browser CSS applies an outline to this element to indicate to users that it has focus. This is an accessibility feature and not something we have any workarounds for on our end.

If you wish to alter it, you could see if using any of the following suggestions would work for your needs: https://www.a11yproject.com/posts/never-remove-css-outlines/. However, this is not something we can provide support for.
