### ISSUE TITLE
Dynamic data background-image does not appear to work for pseudo elements

### ISSUE THREAD

**Issue by perrelet** [soflyy/oxygen-bugs-and-features#3324]
**Describe the bug**

Dynamic data background-image does not appear to work for pseudo elements.

**A link to a Sandbox site where the bug has been reproduced https://oxygenbuilder.com/try? (REQUIRED)**

https://oxygen-qgqk5s39dqrsl.oxygen-demo.qsandbox.org/hello-world/

**Comment by Kpudlo** [comment]
Duplicate of https://github.com/soflyy/oxygen-bugs-and-features/issues/2171
