### ISSUE TITLE
Modal issue when in design set

### ISSUE THREAD

**Issue by wplit** [soflyy/oxygen-bugs-and-features#333]
**Describe the bug**
If animation is applied to a modal from the AOS library, say a fade effect, when the modal is imported onto a new site the contents of the modal are invisible in the builder. 

This is caused by the fact that the modal is visible by default when it's imported via design set, but the trigger hasn't yet been pressed, so nothing has triggered the modal. So this CSS is still being applied.. causing it to all be blank.

```
[data-aos^=fade][data-aos^=fade] {
    opacity: 0;
    transition-property: opacity,transform;
}
```

**Comment by KittenCodes** [comment]
@wplit I haven't been able to replicate this in Oxygen v3.1. If you're still having problems, please can you import the design set to a Sandbox site and send me the login? You can create a Sandbox site here: https://oxygenbuilder.com/try/.
