### ISSUE TITLE
DONE: Oxygen CodeMirror enhancement

### ISSUE THREAD

**Issue by re-co** [soflyy/oxygen-bugs-and-features#3331]
This issue will contain full feedback on Oxygen Builder v4.7 Beta 1 with noticed bug, some fixes and enhancements.

Bugs:
0) I have following error on load: $scope is not defined 
and call is from: _window.currentCMTheme.of(OxyCM.modules[$scope.iframeScope.globalCodeMirrorTheme]),_

**Enhancements:**
1) Autocomplete for custom CSS does not work as expected because CodeMirror tokens expect .selector{ display: flex } syntax, and Oxygen uses shorter version without selectors which confuses default CodeMirror suggestions and instead of suggestion CSS props it will hint right now HTML tags.

2) Suggest Oxygen classes

3) Suggest CSS Variables 

**Solution:**
For that (1, 2, 3) you should replace const cssCompletionSource,
with this file which contains helper function for CSS variables and modified cssCompletionSource that could be found here: https://gist.github.com/re-co/acf90caf7a2ac437bc4311c9672781eb

**Comment by jorodr** [comment]
I hope will do it!

**Comment by demetre19** [comment]
+1

**Comment by davormlinaric** [comment]
+1

**Comment by mannyrak** [comment]
+1

**Comment by mark88008** [comment]
+1

**Comment by Esnola** [comment]
+1

**Comment by itcomindo** [comment]
+1

**Comment by robert1112** [comment]
Yes +1

**Comment by Esnola** [comment]
+1

**Comment by rubengarciajr** [comment]
+1 !!!

**Comment by Spellhammer** [comment]
Noted & logged, thanks!

**Comment by Spellhammer** [comment]
These suggested changes have been implemented in 4.7, currently available as an RC.
