### ISSUE TITLE
DONE: Add ALT tag to images if added to Media Library

### ISSUE THREAD

**Issue by sunnyt7** [soflyy/oxygen-bugs-and-features#334]
If you add an image in Oxygen without an ALT tag, and later add the tag in the Media Library, Oxygen does not currently adopt the tag. 

This means that if you don't add the ALT tag at the time of upload, you need to go through each page and add the tag to each image individually, and it cannot be done in bulk through the Media Library.

Surprisingly, the default WordPress Twenty Nineteen theme does not seem to add the ALT tags either. 

However, Elementor definitely does.

This is something I'd strongly like to see in Oxygen, as it would save hours for anyone who has already published sites, and didn't add ALT tags at the time of upload.

**Comment by ivanjuras** [comment]
This is really big. Please, fix it.

**Comment by louisreingold** [comment]
Obviously this makes no sense if the image is referenced by URL.

To clarify, what you're saying is that when using the Image element, when the Media Library option is chosen instead of the Image URL option, there should be no option to set the Alt text in Oxygen, and instead, whatever is set in the Media Library for that image should be used?

**Comment by sunnyt7** [comment]
> 
> 
> Obviously this makes no sense if the image is referenced by URL.
> 
> To clarify, what you're saying is that when using the Image element, when the Media Library option is chosen instead of the Image URL option, there should be no option to set the Alt text in Oxygen, and instead, whatever is set in the Media Library for that image should be used?

Correct. That's exactly how Elementor handles it.

**Comment by jeffmitchel** [comment]
Is it possible to make a Media Library section in the image's Alt Text > Insert Dynamic Data area?

**Comment by sunnyt7** [comment]
This is still an issue in 3.0 Alpha btw. No alt tags are being added when adding images from the Gutenberg editor.

**Comment by Cenay** [comment]
> To clarify, what you're saying is that when using the Image element, when the Media Library option is chosen instead of the Image URL option, there should be no option to set the Alt text in Oxygen, and instead, whatever is set in the Media Library for that image should be used?

I would think setting it in Oxygen **should also be allowed**, but _default_ the value (if one is present in the Media Library) with the value in the Media Library. That makes more sense to me. 

I am often called in to work on sites already created which contain a lot of images. I use VA's to go back and do things like add Alt Text, update recipes, organize reviews... and these tasks aren't often done at the same time as the development.

**Comment by adrien-robert** [comment]
+1

**Comment by websmx** [comment]
I also agree... automatically adding Alt and title attributes to placed images should be implemented.

**Comment by Spellhammer** [comment]
Implemented automatic pull of alt text from Media Library in 3.3 (image must be added using Media Library option in Oxygen for this to work.)

**Comment by schietegal** [comment]
> Implemented automatic pull of alt text from Media Library in 3.3 (image must be added using Media Library option in Oxygen for this to work.)

Will there be a way or a tutorial to how tu pull alt tags from image that is input dynamically. If we input a image via acf we don't get the option to set the image alt
