### ISSUE TITLE
Mailpoet shortcode not working on published site

### ISSUE THREAD

**Issue by oskarsh** [soflyy/oxygen-bugs-and-features#3344]
**Describe the bug**
The mailpoet shortcode works in the oxygen editor but not on the published site

**IF YOU CAN'T PROVIDE A SANDBOX REPRODUCTION: Steps required to reproduce the bug:**
1. Download Mailpoet plugin
2. create a new form
3. embeed form using shortcode

I read that we can use the shortcode with dynamic data, does someone know step by step on how to use mailpoet with oxygen builder?

**Comment by Kpudlo** [comment]
Hello @oskarsh, 

Please try adding the MailPoet shortcode to the WordPress editor and then using a Text element that is set to display Dynamic Data > Post Content in Oxygen. (see #1785). 

If you'd like to see a better MailPoet integration, please upvote and/or comment on issue #1819
