### ISSUE TITLE
Animation on Scroll not working in conjunction with Slider Module

### ISSUE THREAD

**Issue by adamtownend** [soflyy/oxygen-bugs-and-features#3346]
**Describe the bug**
When using Animate on scroll, the animation does not trigger when the page also has a slider module on it. Resizing the browser window seems to correct it momentarily, but on refresh the issue returns.

**A link to a Sandbox site where the bug has been reproduced https://oxygenbuilder.com/try? (REQUIRED)**
https://oxygen-qky957g4vl8sl.oxygen-demo.qsandbox.org/sample-page/

**Comment by Kpudlo** [comment]
This issue can be resolved by enabling the "Refresh AOS On Page Load" setting in Oxygen's settings. In general, if you are having issues with animations, the following options may resolve the problem:

1. Go to Settings > Global Styles > Animate on Scroll in Oxygen and enable "Refresh AOS On Page Load".
2. Go to Oxygen > Settings > General in the WordPress admin area and enable "Load AOS styles in the head of page".
