### ISSUE TITLE
Init slick slider in editor from external js file

### ISSUE THREAD

**Issue by mapwork** [soflyy/oxygen-bugs-and-features#335]
I inserted the jQuery "slick" plugin using the enqueue method. I inserted the init function in an external js file. the slider works correctly in frontend but not inside the oxygen editor

**Comment by KittenCodes** [comment]
@mapwork Unfortunately, some plugins/shortcodes can't be rendered by the Oxygen builder. If you'd like us to take a look at this specific case, please open a support ticket by emailing support@oxygenbuilder.com.
