### ISSUE TITLE
Insert Data HTML Code Block

### ISSUE THREAD

**Issue by jessehodl** [soflyy/oxygen-bugs-and-features#3352]
Hello,

I have setup a repeater for my post archive. I am listing Podcast Episodes with all the necessary information in the repeater. Additionally, I'd like to embed a podcast player on the site. I have HTML Code I could embed. 

I would love to be able to insert the HTML Code in my Post with ACF. In Oxygen I want to "insert data" into a Code Block Element to execute the different HTML Codes automatically to display Audio players for every episode directly on the Archive Page and for the Blog Post page as well.

Does that make sense?

**Comment by Kpudlo** [comment]
Hi @jessehodl, 

When using a Code Block element and ACF fields, you can use ACF's [get_field](https://www.advancedcustomfields.com/resources/get_field/) hook in PHP.

I hope this helps!
