### ISSUE TITLE
Request Mega Menu Feature

### ISSUE THREAD

**Issue by aluhizmiakanza** [soflyy/oxygen-bugs-and-features#3353]
Hi, Can I request a Mega Menu Feature on my oxygen? I had basic purchase (pic below), It doesn't have Mega Menu Feature, FYI, I already install the new updates (version 4.6.2), which the minimum req for Mega Menu Feature is 3.7 version. 
Thank you!

![image](https://github.com/soflyy/oxygen-bugs-and-features/assets/109655118/9d54c25f-111a-4483-8ac6-e56fb53daf85)

**Comment by Kpudlo** [comment]
Hello @aluhizmiakanza, 

Please open a support ticket at Support Ticket (https://oxygenbuilder.com/support), we'll be glad to assist you further.
