### ISSUE TITLE
Can't see the checkbox "Make the page full editable in Gutenberg".

### ISSUE THREAD

**Issue by khan7swati** [soflyy/oxygen-bugs-and-features#3358]
![Edit-Page-“Home”-‹-Hvac-clone-—-WordPress](https://github.com/soflyy/oxygen-bugs-and-features/assets/57087990/fd97eb96-ac17-4971-8966-73b90ff1374d)

**Comment by Kpudlo** [comment]
Hello @khan7swati, 

Please open a Support Ticket (https://oxygenbuilder.com/support), and provide a staging environment where we can see the problem. We'll be glad to assist further. If you can also include a link to this discussion in that ticket, that would be appreciated.
