### ISSUE TITLE
Header is broken on safari

### ISSUE THREAD

**Issue by QuentinBar** [soflyy/oxygen-bugs-and-features#3359]
**Any bug report that doesn't include a Sandbox link or replication steps will be closed. If you can't provide these pieces of information, we're happy to help you via our official support channel instead: https://oxygenbuilder.com/support. You need to select "Something's broken and I need help" from the dropdown box on the left.**

**Describe the bug**
*A clear and concise description of what the bug is.*

My website header doesn't display correctly in Safari.

**A link to a Sandbox site where the bug has been reproduced https://oxygenbuilder.com/try? (REQUIRED)** 
*Provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*

To see the bug, the link below needs to be open in Safari.
https://oxygen-q2arq33654ftl.oxygen-demo.qsandbox.org/accueil/

**IF YOU CAN'T PROVIDE A SANDBOX REPRODUCTION: Steps required to reproduce the bug:**
1. Create a template "Main" with div and add the "header" Tag.
2. Open the web site with Safari browser.

**If you can't fill out the above information, you should not be filing a bug report. Instead, contact us via https://oxygenbuilder.com/support with the details you have and we'll investigate your issue further.**

**Comment by Kpudlo** [comment]
This issue was addressed in Oxygen Support and no bug was found.
