### ISSUE TITLE
White screen of death all of a sudden

### ISSUE THREAD

**Issue by jessebrightman** [soflyy/oxygen-bugs-and-features#3366]
Out of nowhere out entire store is a white screen of death.  I tried to sign the shortcodes but it will not work any longer either because of error: 

Activate Add-Ons Before Re-Signing

All plugins are the exact same as before, no updates, no nothing.  One moment we had a working system then the next the entire site and store is down.  Regular themes work but Oxygen is causing the issue with no remedy available.  All Oxygen plugins are paid for with valid licenses, and whitelisted urls.  We are losing a ton of money here, what is the solution?  Thanks.

**Any bug report that doesn't include a Sandbox link or replication steps will be closed. If you can't provide these pieces of information, we're happy to help you via our official support channel instead: https://oxygenbuilder.com/support. You need to select "Something's broken and I need help" from the dropdown box on the left.**

**Describe the bug**
*A clear and concise description of what the bug is.*

**A link to a Sandbox site where the bug has been reproduced https://oxygenbuilder.com/try? (REQUIRED)**
*Provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*

**IF YOU CAN'T PROVIDE A SANDBOX REPRODUCTION: Steps required to reproduce the bug:**

**If you can't fill out the above information, you should not be filing a bug report. Instead, contact us via https://oxygenbuilder.com/support with the details you have and we'll investigate your issue further.**

**Comment by Spellhammer** [comment]
Sounds like a 500 error. Check your server error logs then submit a ticket with the information you find: support@oxygenbuilder.com
