### ISSUE TITLE
Uncaught TypeError: s(...).filter(...).selectWoo is not a function

### ISSUE THREAD

**Issue by jessebrightman** [soflyy/oxygen-bugs-and-features#3368]
Cannot edit any pages in the builder as all clicks on any module result in a Uncaught TypeError: s(...).filter(...).selectWoo is not a function error no doubt from woocommerce.  Don't know why it just started happening, worked fine yesterday and no updates since.  

**Any bug report that doesn't include a Sandbox link or replication steps will be closed. If you can't provide these pieces of information, we're happy to help you via our official support channel instead: https://oxygenbuilder.com/support. You need to select "Something's broken and I need help" from the dropdown box on the left.**

**Describe the bug**
*A clear and concise description of what the bug is.*

**A link to a Sandbox site where the bug has been reproduced https://oxygenbuilder.com/try? (REQUIRED)**
*Provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*

**IF YOU CAN'T PROVIDE A SANDBOX REPRODUCTION: Steps required to reproduce the bug:**

**If you can't fill out the above information, you should not be filing a bug report. Instead, contact us via https://oxygenbuilder.com/support with the details you have and we'll investigate your issue further.**

**Comment by jessebrightman** [comment]
the error in jquery seems to be related to 

waitComponentsTemplates timeout in file: controller.main.min.js:1

**Comment by Spellhammer** [comment]
Please submit a ticket: support@oxygenbuilder.com.
