### ISSUE TITLE
Easy post module

### ISSUE THREAD

**Issue by DGibson0217** [soflyy/oxygen-bugs-and-features#3374]
**Describe the bug**
When using the Easy Post module on my site I can choose between default and custom. When I choose default the ability to filter using the categories widget works properly but I can't change post order to descending. If I use custom and change post order to descending then that works but the category widget doesn't filter the posts anymore. https://nrsinjurylaw.com/blog/

**Comment by Spellhammer** [comment]
Unfortunately this is a limitation of the Easy Posts/Repeater query functionality. There's no way to modify the default query.

This kind of functionality is under investigation and you can follow the feature request here: https://github.com/soflyy/oxygen-bugs-and-features/issues/3138.

**Comment by DGibson0217** [comment]
Hi Elijah,

Thank you for the reply but why don't the filters work when I switch to
custom instead of default? When I'm on default the filters I use to the
left work but when I switch to custom to change the order then the filters
stop working.

https://nrsinjurylaw.com/blog/

If you need any more info please let me know.

**Comment by DGibson0217** [comment]
Hi Elijah,

Thank you for the reply but why don't the filters work when I switch to custom instead of default? When I'm on default the filters I use to the left work but when I switch to custom to change the order then the filters stop working.

https://nrsinjurylaw.com/blog/

If you need any more info please let me know.
