### ISSUE TITLE
Preview Images for reusable elements 

### ISSUE THREAD

**Issue by organicallydigital** [soflyy/oxygen-bugs-and-features#3379]
Ability to either add or generate a preview of reusable elements and templates to make it easier to visually identify elements.  

**What are the use cases for this feature?**
It would allow developers and clients alike to have a more visual experience as opposed to being overwhelmed with repeated blank elements with only text to identify them.

**Examples of this feature or functionality.**
Bricks Builder does this really well.

**Comment by Kpudlo** [comment]
Duplicate of https://github.com/soflyy/oxygen-bugs-and-features/issues/2795
