### ISSUE TITLE
Profile Builder shortcode not working

### ISSUE THREAD

**Issue by wildlane** [soflyy/oxygen-bugs-and-features#338]
Unable to display Profile Builder's registration form shortcode. It shows in Oxygen's editor, but not on the live site. However, it works if we disable Oxygen (so it is an issue with Oxygen).

The shortcode in question is:
[wppb-register]

Here's the page with all the shortcodes:
https://www.cozmoslabs.com/docs/profile-builder-2/shortcodes/

**Comment by wildlane** [comment]
Ok, so I've now tried this on 3 different sites, all running different versions of Oxygen and WordPress, and still the [wppb-register] shortcode does not work unless we disable Oxygen. Oxygen and Profile Builder do not work together.

**Comment by KittenCodes** [comment]
@wildlane 

Unfortunately, we don't have a copy of Profile Builder to be able to see this behaviour. Please install it on one of our [Sandbox sites](https://oxygenbuilder.com/try/) and add the one click login to this issue.
