### ISSUE TITLE
Get rid of invisible sub-menu under Dashboard

### ISSUE THREAD

**Issue by wildlane** [soflyy/oxygen-bugs-and-features#339]
Please get rid of the invisible sub-menu under the Dashboard item on the admin panel. It's been there for as long as I can remember.

When you click on it, it takes you to this page:
/wp-admin/index.php?page=oxygen-vsb-setup

**Comment by wildlane** [comment]
![not-cool](https://user-images.githubusercontent.com/51244460/58739458-1ec91e80-83bf-11e9-8aad-408c997937fe.jpg)
![Screen Shot 2019-05-31 at 4 14 02 PM](https://user-images.githubusercontent.com/51244460/58739461-2092e200-83bf-11e9-80c2-0502dc2396a2.png)

**Comment by KittenCodes** [comment]
Fixed in 3.6 Beta.
