### ISSUE TITLE
4.8 Beta 1 - Conditional Logic Bug

### ISSUE THREAD

**Issue by sccbdf** [soflyy/oxygen-bugs-and-features#3390]
**Describe the bug**

Conditional Logic isn't observed under certain conditions in 4.8 Beta 1. If you open the main template, I have conditional logic set for some home page masthead sections. If Editing is set to "Main" and Preview is set to "Home" when switching to another page in Editing, for Example, "About Us" the masthead sections that are set to only display on the home page also show on the "About Us" page.

If switching to "About Us" for preview first, then the conditional logic is observed when changing from editing "Main" to editing "About Us"

When changing to the editing of the page it appears like the preview selection should also be switched to that page automatically (even though it's not visible) so the conditional logic is implemented for the page that is being edited.

**A link to a Sandbox site where the bug has been reproduced https://oxygenbuilder.com/try? (REQUIRED)**
https://oxygen-qj89tkalkq3tl.oxygen-demo.qsandbox.org/

This is the most exciting update for Oxygen since we have started using Oxygen! Thanks!

**Comment by Spellhammer** [comment]
Thanks for the report! We'll be looking into this.

**Comment by Spellhammer** [comment]
Fixed in Oxygen 4.8.
