### ISSUE TITLE
Wordpress is sending me emails saying there is a critical error with OXYGEN

### ISSUE THREAD

**Issue by timjossund** [soflyy/oxygen-bugs-and-features#3391]
**Any bug report that doesn't include a Sandbox link or replication steps will be closed. If you can't provide these pieces of information, we're happy to help you via our official support channel instead: https://oxygenbuilder.com/support. You need to select "Something's broken and I need help" from the dropdown box on the left.**

**Describe the bug**
*A clear and concise description of what the bug is.*

**A link to a Sandbox site where the bug has been reproduced https://oxygenbuilder.com/try? (REQUIRED)**
*Provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*

**IF YOU CAN'T PROVIDE A SANDBOX REPRODUCTION: Steps required to reproduce the bug:**

**If you can't fill out the above information, you should not be filing a bug report. Instead, contact us via https://oxygenbuilder.com/support with the details you have and we'll investigate your issue further.**

Got to bbcconway.com... it is down and Wordpress says it is oxygen. When I disable the plugin the site works but my Oxygen work obviously isn't there

**Comment by timjossund** [comment]
here is the email from Wordpress. 

Howdy!

WordPress has a built-in feature that detects when a plugin or theme causes a fatal error on your site, and notifies you with this automated email.

In this case, WordPress caught an error with one of your plugins, Oxygen.

Another site https://clarksvillebaptistchurch.org is down

**Comment by Kpudlo** [comment]
Hello @timjossund, 

Please open a Support Ticket (https://oxygenbuilder.com/support) regarding this issue and we'll be glad to investigate further. If you can also include a link to this discussion in that ticket, that would be appreciated.
