### ISSUE TITLE
 cURL error 60: SSL: no alternative certificate subject name matches target host name 'elements.oxy.host'

### ISSUE THREAD

**Issue by ronregeer** [soflyy/oxygen-bugs-and-features#3400]
**Any bug report that doesn't include a Sandbox link or replication steps will be closed. If you can't provide these pieces of information, we're happy to help you via our official support channel instead: https://oxygenbuilder.com/support. You need to select "Something's broken and I need help" from the dropdown box on the left.**

**Describe the bug**
I get the error when opening any page:  (see screenshot 1)
 Items not loaded. cURL error 60: SSL: no alternative certificate subject name matches target host name 'elements.oxy.host'
*A clear and concise description of what the bug is.*
I never had this before, but it's on all my sites i have made..
On your site i try to open a sandbox and i get the same.. (see screenshot 2)

**A link to a Sandbox site where the bug has been reproduced https://oxygenbuilder.com/try? (REQUIRED)**
*Provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*

**IF YOU CAN'T PROVIDE A SANDBOX REPRODUCTION: Steps required to reproduce the bug:**

**If you can't fill out the above information, you should not be filing a bug report. Instead, contact us via https://oxygenbuilder.com/support with the details you have and we'll investigate your issue further.**
screenshot 1
![Screenshot from 2023-09-17 15-18-14](https://github.com/soflyy/oxygen-bugs-and-features/assets/2129110/88a8ee06-9097-42dd-a6eb-df93ecd5fead)
screenshot 2
![Screenshot from 2023-09-17 15-23-47](https://github.com/soflyy/oxygen-bugs-and-features/assets/2129110/e95d0b0e-6611-4f4d-8045-a93d8d9add97)

**Comment by Spellhammer** [comment]
This is related to a WP Engine outage that they're currently working on: https://wpenginestatus.com/incidents/524219.

**Comment by Kpudlo** [comment]
This has been resolved by WP Engine, and everything should be working as expected.

**Comment by ronregeer** [comment]
Kevin thx!
I have steen it. It works fine now.
Greetings Ron.

19 sep. 2023 12:29:03 Kevin Pudlo ***@***.***>:
