### ISSUE TITLE
[2.4 Alpha Bug] Headings don't change in builder

### ISSUE THREAD

**Issue by sunnyt7** [soflyy/oxygen-bugs-and-features#341]
It looks like if you insert a Heading element, changing the tag between h1, h2, h3 etc doesn't have any effect in the builder. Here's a video Dean made showing this (which I can confirm):

https://www.loom.com/share/b196a678139e45419d940c869788d38e?fbclid=IwAR1uJ9i1ZTr3kxFdZGlOsQp94w2UUKyciTAPKdxWu5aYlSv2fCUAkv3izGg

It looks like the heading tags are being changed appropriately on the front end though. Hitting Save + refresh also make it reflect properly in the builder.

**Comment by sunnyt7** [comment]
This still exists in the beta btw.

**Comment by Spellhammer** [comment]
Fixed in 2.4
