### ISSUE TITLE
Function in a code block inside a repeater breaks page on frontend

### ISSUE THREAD

**Issue by git-temak** [soflyy/oxygen-bugs-and-features#3413]
**Describe the bug**
I just discovered that when you place a code block in a repeater and write a custom function in the code block, wp crashes on the frontend. Once the function is removed, it works fine. If the code block is placed outside of the repeater (with the function still there), the page works fine

![image](https://github.com/soflyy/oxygen-bugs-and-features/assets/66384168/863d82a6-3328-41b4-8e11-bd2f06e101ef)

**A link to a Sandbox site where the bug has been reproduced https://oxygenbuilder.com/try? (REQUIRED)**
https://oxygen-qpykqpr58nlvl.oxygen-demo.qsandbox.org/
Access Code: 5729

*Provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*
https://oxygen-qpykqpr58nlvl.oxygen-demo.qsandbox.org/wp-admin/post.php?post=36&action=edit

1. Go to Pages
2. Select the 'edit with oxygen' for the Home page
3. There's a repeater in the page with a code block inside of it
4. The function in the code block causes the error. Removing the function fixes the issue.

![image](https://github.com/soflyy/oxygen-bugs-and-features/assets/66384168/1b242293-51a9-4110-b8d1-4c43f9474e28)

How can I make use of a custom function in a code block inside a repeater? I need this to dynamically retrieve info from each post in the repeater and do something with the info.

**Comment by arsh999cg** [comment]
Wrap it with condition if(!function_exists('this_is_test') { // your function },

BWT what is the use case of putting a code-block inside a repeater ?

**Comment by git-temak** [comment]
@arsh999cg thank you, that works fine! I have a set of items that are specific to the posts in the repeater. I need the function to get the id of the current post and use that to handle what I need with the set of items. Appreciate your help with this.
