### ISSUE TITLE
Custom CSS is showing CSS of other selectors.

### ISSUE THREAD

**Issue by mark88008** [soflyy/oxygen-bugs-and-features#3415]
I have made video about it, to understand the issue.

https://youtu.be/3aqE8_Y6BNs

Kind Regards, Michael

**Comment by arsh999cg** [comment]
Did you checked it with RECODA plugin disabled ?

**Comment by mark88008** [comment]
Yes, I disabled it here. I have an other video where I have the issue without Recoda.
https://youtu.be/bZKcxFNiXt0

**Comment by Spellhammer** [comment]
@mark88008 You have some active modification to Oxygen's UI causing the Custom CSS view to stay open when switching between elements. This isn't default behavior. Whatever is implementing this will likely need to be updated to accommodate the new CSS editor changes in 4.8.

If you are able to reproduce without any other plugins/add-ons/scripts besides Oxygen active, please let us know.

**Comment by mark88008** [comment]
Hello Elijah, I found out that the Hydrogen Pack caused this issue. Thanks. Michael

**Comment by Spellhammer** [comment]
@mark88008 Thanks for confirming!
