### ISSUE TITLE
Oxygen Builder won't load templates

### ISSUE THREAD

**Issue by jessebrightman** [soflyy/oxygen-bugs-and-features#3418]
Added some code in a code block and saved then suddenly the builder will not load.  It shows an error "Cannot load template" and half loads a section.  Looks like the json is corrupted again.  This happens WAY TOO OFTEN for production software, it's laughable.

**Any bug report that doesn't include a Sandbox link or replication steps will be closed. If you can't provide these pieces of information, we're happy to help you via our official support channel instead: https://oxygenbuilder.com/support. You need to select "Something's broken and I need help" from the dropdown box on the left.**

**Describe the bug**
*A clear and concise description of what the bug is.*

**A link to a Sandbox site where the bug has been reproduced https://oxygenbuilder.com/try? (REQUIRED)**
*Provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*

**IF YOU CAN'T PROVIDE A SANDBOX REPRODUCTION: Steps required to reproduce the bug:**

**If you can't fill out the above information, you should not be filing a bug report. Instead, contact us via https://oxygenbuilder.com/support with the details you have and we'll investigate your issue further.**

**Comment by jessebrightman** [comment]
Now it's saying there is a problem with the Inner Content.  What a joke.

**Comment by Kpudlo** [comment]
Hi @jessebrightman, 

If you still need help with this, please open a Support Ticket (https://oxygenbuilder.com/support), and provide a staging environment where we can see the problem. We'll be glad to assist further. If you can also include a link to this discussion in that ticket, that would be appreciated.

**Comment by jessebrightman** [comment]
Ha, now it just says '
