### ISSUE TITLE
Don't open links from within the builder

### ISSUE THREAD

**Issue by sunnyt7** [soflyy/oxygen-bugs-and-features#342]
It's currently rather annoying to edit any text or images that are placed within a link wrapper. Whenever I click on the element in the Oxygen builder, it tries to take me to the URL. 

I get the browser prompt "This page is asking you to confirm that you want to leave - data you have entered may not be saved." and I need to hit "Stay on page" each time.

There have also been a couple times where I accidentally hit enter, which chooses the default "Leave This Page", which caused me to lose a bunch of work.

I would like to see links not open from within the builder.

I'm using 2.4 alpha on Firefox.

**Comment by alpabuz** [comment]
I agree. But we need to combine efforts: https://github.com/soflyy/oxygen-bugs-and-features/issues/288

**Comment by sunnyt7** [comment]
> 
> 
> I agree. But we need to combine efforts: #288

Ah! These should be merged.

**Comment by wpdevlab** [comment]
👍

**Comment by KittenCodes** [comment]
This is fixed in the latest version of Oxygen.
