### ISSUE TITLE
Save multiple sections as ´Single reusable template´

### ISSUE THREAD

**Issue by alexandrudinu** [soflyy/oxygen-bugs-and-features#343]
### Hello!

I suggest to have the possibility to save multiple sections from the **_Structure_** as **_Reusable parts_**.

### I think is is useful for:
1) Saving multiple sections that are related in one single reusable part
2) Saving multiple sections that are used to obtain the same design in one single reusable part

For example in the screenshots attached you can see that to obtain that design I used 3 sections. The layout was obtained by playing with different size columns within 3 different sections, alignment and margins:
1) The main section in the middle _(which was used to add the background image)_
2) **_Before section_** & **_After section_** used to add the texts.

In this case would be very useful to have the ability to save all this sections in one single reusable part.

Hope this is a good idea that many of us can find useful.

![Feature screenshot (Oxygen Builder)](https://user-images.githubusercontent.com/28765264/58872953-77e9c880-86c5-11e9-809a-61396adf81c0.png)
![Feature screenshot (Front end)](https://user-images.githubusercontent.com/28765264/58872954-77e9c880-86c5-11e9-9c8f-3ac98a1f63b5.png)

**Comment by albertso** [comment]
Have you tried wrapping the sections in a div and save that as reusable?

**Comment by alexandrudinu** [comment]
I am trying to do so, but all the sections from structure dispensary when I do that.

**Comment by Gibsonion** [comment]
The way to do this while not as streamlined is to save all the parts as reusable and then edit one reusable part and add the extra content.

**Comment by Gibsonion** [comment]
> Essentially what we need is the option to "**group**" items, similar to how we can group items in Illustrator or PS. In Illustrator, once we group items together, then we can move them around together or duplicate the group as well.

This is already possible

**Comment by Hanleymade** [comment]
> > Essentially what we need is the option to "**group**" items, similar to how we can group items in Illustrator or PS. In Illustrator, once we group items together, then we can move them around together or duplicate the group as well.
> 
> This is already possible, I'd recommend watching the tutorials

Specifically what tutorial as I have already watching many of them. Are you talking about the 'reusable parts' video? https://www.youtube.com/watch?v=Emmeaixv5YA

If that's what you're talking about then there's a big limitation to this approach. What if I want to make two + sections into one reusable part? In Oxygen I can't select more than one section at a time, so what do I do? I wasn't able to drag a section into another section, so then what?

**Comment by Gibsonion** [comment]
No, go look yourself I'm not searching for you coz you are too lazy to do it yourself.

**Comment by Hanleymade** [comment]
> No, go look yourself I'm not searching for you coz you are too lazy to do it yourself.

Someone piss in your cornflakes? Seriously I just shared a video that I looked at and asked if that's what you meant. A simple no that's not the one but this is the one would have taken the same time it took you to be an asshole.

**Comment by Hanleymade** [comment]
> No, go look yourself I'm not searching for you coz you are too lazy to do it yourself.

And what you did was the exact opposite of the purpose of being helpful. First you said it could be done without any explanation, then you personally insulted asking the question after they looked for more info. Maybe step away from 'helping' people until you can do so in a positive way again.

**Comment by Gibsonion** [comment]
I just don't see why I should have to look for you, I told you the feature is already available it is not my responsibility to have to teach or show you where it is or how it works. It's not my fault you haven't bothered reading the instructions before asking for features that already exist.

**Comment by Hanleymade** [comment]
> I just don't see why I should have to look for you, I told you the feature is already available it is not my responsibility to have to teach or show you where it is or how it works. It's not my fault you haven't bothered reading the instructions before asking for features that already exist.

Clearly you haven't learned how to listen to feedback. Next time, don't bother responding to my question if you're only options are no helpful information or insulting me.

**Comment by Gibsonion** [comment]
What are you talking about? I am just a user, I do not work for Oxygen

**Comment by Hanleymade** [comment]
I asked a question. I provided a video as reference - thus I did research already. I was asking for confirmation, not insults.

Next time don't assume because someone doesn't know the answer means A ) they are lazing or stupid, B ) that they haven't done research already.

No you've wasted MY time with this side argument. Let's move on.

**Comment by Gibsonion** [comment]
So you expect me to give you my time freely, because yours is so damn important you can't be bothered to do the work yourself? And I'm the one wasting YOUR time? BYE!

**Comment by KittenCodes** [comment]
The correct way to do this is to move all of the Sections into a Div and make the Div reusable. If that's not working for you for some reason, please open a support ticket so that we can take a look: https://oxygenbuilder.com/support.
