### ISSUE TITLE
Repeater element with link wrapper breaks layout while having dynamic content with a link inside

### ISSUE THREAD

**Issue by supaaboy** [soflyy/oxygen-bugs-and-features#3433]
Hey guys,
Today I pick up a topic that has already been mentioned. Namely, I have the following problem that when I use the repeater element, after the div set a link wrapper and then in the link wrapper somewhere insert a Dynamic Content element of WordPress, which contains a link in the content, the layout of the repeater element breaks and suddenly multiple links are created. See screenshots. Access code for the sandbox page is 6360. Please take the issue again and check it very gladly.

<img width="808" alt="Bildschirmfoto 2023-11-02 um 02 20 05" src="https://github.com/soflyy/oxygen-bugs-and-features/assets/63873901/9f947cb1-d94a-4deb-abf6-292525ff5e83">

<img width="1146" alt="Bildschirmfoto 2023-11-02 um 02 22 29" src="https://github.com/soflyy/oxygen-bugs-and-features/assets/63873901/3f7ae0f5-6c7a-43b1-bf1d-35eaa965f4e5">

https://oxygen-qks27w4hjjzvl.oxygen-demo.qsandbox.org/

**Comment by Spellhammer** [comment]
HTML doesn't allow nested anchors, which is why this breaks. You'll have to ensure you're not creating a structure where an ```<a>``` is inside another ```<a>```.
