### ISSUE TITLE
What's the deal with all the opinionated styles in `woo-global-styler.css`?

### ISSUE THREAD

**Issue by perrelet** [soflyy/oxygen-bugs-and-features#3437]
Forcing a `letter-spacing` on buttons and other odd / opinionated woo styles is a pain.

It would handy if oxygen provided a way to prevent these styles from being added to `universal.css` so we don't need to override this css pollution. 

🚀

**Comment by Kpudlo** [comment]
Marking as a duplicate of https://github.com/soflyy/oxygen-bugs-and-features/issues/3221 since adding a filter would resolve this.

**Comment by perrelet** [comment]
https://github.com/soflyy/oxygen-bugs-and-features/issues/3221#issuecomment-2024110807
