### ISSUE TITLE
Oxygen themed sites are facing the css issue.

### ISSUE THREAD

**Issue by SathishArumuga** [soflyy/oxygen-bugs-and-features#3439]
**Any bug report that doesn't include a Sandbox link or replication steps will be closed. If you can't provide these pieces of information, we're happy to help you via our official support channel instead: https://oxygenbuilder.com/support. You need to select "Something's broken and I need help" from the dropdown box on the left.**

**Describe the bug**
### **ISSUE:** I am trying to edit a website in wordpress i am facing some css issue.
**Explanation: ** Actually I have two environments with same wordpress site with same files on two environments separately with separate databases. when ever I do some UI changes on my Env1 the css of the ENV2 gets affected and site is broken with css.
- **ENV1: staging
- ENV2: Live**

**A link to a Sandbox site where the bug has been reproduced https://oxygenbuilder.com/try? (REQUIRED)**
*Provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*
This issue is for complete site.

**Steps required to reproduce the bug:**
Step1: When you do some UI changes on the staging environment you can see the live site css will be broken.
Step2: If you go to live site's oxygen->settings->cacheCSS and click go to Regeneration Page the live site will be back to good.

**I just need to know though I have separate filestore, separate database how do, it is affecting the live site if i do changes on the staging site?**

**If you can't fill out the above information, you should not be filing a bug report. Instead, contact us via https://oxygenbuilder.com/support with the details you have and we'll investigate your issue further.**

**Comment by Kpudlo** [comment]
Hello @SathishArumuga, 

Please create a new Support Ticket (https://oxygenbuilder.com/support) with your login credentials. Please also change your credentials before sending this as this repository is not private.

**Comment by seun6** [comment]
It sounds like you have a similar issue.
1. I cloned the site and changed all the URLs in the DB.
2. both main site and subsite have separate DB and WordPress.
3. at some point (not sure when) you realize that the layout of the main site is broken.
4. you find that files inside wp-content/uploads/oxygen/css have been deleted.
5. you open the main site's oxygen template in the editor and press the 'save' button without doing anything.
6. the CSS file is generated and the layout is recovered.
7. or press the Regenerate CSS button to restore it.

Why do my CSS files suddenly disappear or get deleted?
