### ISSUE TITLE
Fatal erreur php since update Wordpress 6.4 when using Oxygen 4.7 & Advanced Custom Fields for WordPress

### ISSUE THREAD

**Issue by numayos** [soflyy/oxygen-bugs-and-features#3442]
I encounter a Fatal Error since updating WordPress to version 6.4 when I activate the Advanced Custom Fields for WordPress plugin at the same time as Oxygen.

To recreate the problem, simply activate oxygen builder 4.7 and Advanced Custom Fields (ACF latest version 6.2.2) at the same time on WordPress 6.4

Here is the error message :

Warning: require(fake/inc/block-patterns.php): failed to open stream: No such file or directory in /home/xxxxx/xxxx.fr/wp-content/themes/twentytwentytwo/functions.php on line 67

**Fatal error: require(): Failed opening required 'fake/inc/block-patterns.php' (include_path='.:/opt/alt/php74/usr/share/pear') in /home/xxxxxx/xxxxx.fr/wp-content/themes/twentytwentytwo/functions.php on line 67**

**Comment by Kpudlo** [comment]
Same issue as https://github.com/soflyy/oxygen-bugs-and-features/issues/3440
