### ISSUE TITLE
Add new condition type "SHOW/HIDE"

### ISSUE THREAD

**Issue by miraiserver** [soflyy/oxygen-bugs-and-features#3460]
From what I've observed, the current conditions are specifically designed to display information based on the conditions that have been set. The only types of conditions that are currently available are "AND" or "OR".
It would be very useful to be able to set conditions in order to HIDE something. That is to say, add "SHOW/HIDE" condition types.

For example, I have a membership site with 4 levels of paid users and 1 level for free users. I set a specific user type for each membership.
My problem arises because there are users which did not select any membership type. In this particular scenario, the "!=" condition does not function properly with the existing "user roles" even when an "OR" condition type is used. It did not work when I tested...

**Comment by Kpudlo** [comment]
Hello, 

Creating custom Conditions, including your desired operators, should be possible using [Oxygen's Conditions API](https://oxygenbuilder.com/documentation/other/conditions/).
