### ISSUE TITLE
Navigator Issue in 4.8

### ISSUE THREAD

**Issue by mark88008** [soflyy/oxygen-bugs-and-features#3465]
**I have the issue, that I cant see any changes when I try to edit my Main Template.**
 It just happens, if I start to edit some random page and then use the NAVIGATOR to switch to the main template. there I wanted to change for instance the border-radius, and it didnt show in the UI any change. but when I want to preview the changes, I can see the implemented change.

When I directly open the main Theme without using the NAVIGATOR it works, as intended.
Then if I use the NAVIGATOR again and want to edit some pages, it works. Just the theme doesnt work.

I have updated Wordpress to most recent one (4.6.2) and I have deactivated recoda-workspace and hydrogen pack and still the same issue is present.

So I can't really use now 4.8 for any production website. I hope you can replicate this issue and get it fixed :-)

**Comment by Spellhammer** [comment]
@mark88008 Have you done a plugin conflict test yet?

Can you share a screen recording of the issue?

**Comment by mark88008** [comment]
Hello Elijah! I have done a plugin conflict test and I have deactivated everything, and I have still the same issue. I made a video for you
[https://youtu.be/V0pva-71Ir4](url)

Best wishes, Michael

**Comment by Spellhammer** [comment]
@mark88008 Thanks for the details! I have been able to reproduce and reported it internally (https://github.com/soflyy/oxygen/issues/5253).

**Comment by mark88008** [comment]
Thank you Elijah! You know why this bug is happening?

**Comment by Spellhammer** [comment]
This was fixed in 4.8.1.
