### ISSUE TITLE
Other meta boxes order changes after activating Oxygen Builder

### ISSUE THREAD

**Issue by jevgen** [soflyy/oxygen-bugs-and-features#347]
**Describe the bug**
After activating Oxygen the saved order of metaboxes for admin edit screen changes. It also breaks WP behaviour of saved order, i.e. if you try to change metabox order using drag and drop, new positions does not save. This will not make many customers happy. 

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
Yes

**Expected behavior**
After installation and activation of Oxygen builder, metaboxes order does not change, Oxygen metabox adds to bottom and can be moved to the order of user choice, correctly saving order after repositioning. 

**What actually happens**
After installation and activation of Oxygen builder, metaboxes order change. Reordering does not save. 

**Screenshots**
Before Oxy activation:
<img width="1019" alt="before oxy activation" src="https://user-images.githubusercontent.com/255431/59090051-56325080-8914-11e9-8d68-93a7f4db91ca.png">
After Oxy activation:
<img width="1036" alt="after oxy activation" src="https://user-images.githubusercontent.com/255431/59090066-5cc0c800-8914-11e9-9892-a8e982785670.png">

**Desktop (please complete the following information):**
- OS: MacOS 10.14.5
 - Browser Chrome
 - Oxygen Version 2.3

**Additional context**
Used with Toolset with many custom field groups, so this bug was a disaster for content managers.

**Comment by KittenCodes** [comment]
@jevgen 

Please replicate this behaviour on our [Sandbox site](https://oxygenbuilder.com/try/) and add the one click login to this issue.
