### ISSUE TITLE
Browse media button no longer clickable after deletion of already used images.

### ISSUE THREAD

**Issue by realmalikov** [soflyy/oxygen-bugs-and-features#3471]
After deleting some pictures, I am no longer able to upload media via the "Browse" button on the page where the deleted pictures were located. This also applies to templates if the preview page is the page with the deleted images.
However, dynamic data and inserting via an image URL work as usual. Unfortunately, I had no success with deleting the ID styles either.

1. Add images to a page
2. Go to your uploads folder and delete the images
3. Open Oxygen Builder and click on an image element

Screen capture:
https://streamable.com/qng1ty

**Comment by Kpudlo** [comment]
Hello @realmalikov,

Please run a [Plugin Conflict Test](https://pluginconflict.com/?plugin=Oxygen) by disabling all other plugins except Oxygen and see if the issue resolves. 

If the issue still occurs with only Oxygen active, please open a Support Ticket (https://oxygenbuilder.com/support), and provide a staging environment where we can see the problem. We'll be glad to assist further. If you can also include a link to this discussion in that ticket, that would be appreciated.

**Comment by realmalikov** [comment]
I was able to fix the issue. Thank you for your answer.
