### ISSUE TITLE
Purchased Ultimate Package but Composite Elements Features is Missing

### ISSUE THREAD

**Issue by aluhizmiakanza** [soflyy/oxygen-bugs-and-features#3472]
Hi, I purchased the Ultimate Package, but Composite Elements Feature is missing, can you please fix this? 
my email: aluh.hizmiakanza@gmail.com

Thank you a lot

Here I attached the pics
![Issue-2](https://github.com/soflyy/oxygen-bugs-and-features/assets/109655118/b3e78207-1476-4e6a-9894-bfa441632acb)
![Issue-1](https://github.com/soflyy/oxygen-bugs-and-features/assets/109655118/cc74bce5-4364-474d-a8dc-093030d0f0ef)

**Comment by Kpudlo** [comment]
Hello, 

Please refresh your Oxygen license key via the following steps: https://oxygenbuilder.com/documentation/troubleshooting/installation-activation-license-issues/#refresh-license.

If you still have issues afterward, please open a Support Ticket (https://oxygenbuilder.com/support), and provide a staging environment where we can see the problem. We'll be glad to assist further.
