### ISSUE TITLE
Can't load conditions and breaks

### ISSUE THREAD

**Issue by Deanphillips** [soflyy/oxygen-bugs-and-features#348]
Hey guys,

I'm using the 2.4 Beta and only have O2 and 1 other plugin installed.

I'm getting these showing (and they don't go away, even when clicking on different elements, that don't have conditions)

<img width="318" alt="Screenshot 2019-06-08 at 00 08 34" src="https://user-images.githubusercontent.com/21025321/59137884-d347df00-8981-11e9-801f-ef88bbc828da.png">
<img width="323" alt="Screenshot 2019-06-08 at 00 08 31" src="https://user-images.githubusercontent.com/21025321/59137886-d347df00-8981-11e9-83ce-e4f7474feedd.png">
<img width="335" alt="Screenshot 2019-06-08 at 00 08 27" src="https://user-images.githubusercontent.com/21025321/59137887-d347df00-8981-11e9-8620-661b7fe0cd38.png">

**Comment by Deanphillips** [comment]
I've done all I can think of (shortcodes, caching, deactivated other plugins)

**Comment by Deanphillips** [comment]
This seems to be broken on old pages, but not new ones. It's very hit or miss - if I copy the shortcodes and paste them on a new page, this all works well

**Comment by Spellhammer** [comment]
Hey Dean,

Is this a fresh WordPress install or is it an existing install that had a previous version of Oxygen? It kind of looks similar to the issue folks have seen with icons being too large when the Search feature was implemented, and that was normally fixed by a few hard browser refreshes.

Also, what's the 1 other plugin active and did you try disabling it?

**Comment by Spellhammer** [comment]
@Deanphillips Any update since my last message?

**Comment by Deanphillips** [comment]
It was the same with all plugins disabled, however, it's not replicable on
a page to page basis. It seems to just be random (even copying the
shortcodes and making a new page fixes it) - and it's not a problem on my
sites with way more plugins/older sites too, so I'm thinking it's just
random

**Comment by Spellhammer** [comment]
@Deanphillips Have you tried hard-clearing your browser cache? This still looks a lot like a cache issue, since the elements you're seeing should be hidden/styled by new CSS  - it's almost like the CSS isn't there (old CSS is cached).

**Comment by Deanphillips** [comment]
You're right. Works in Firefox. I do get this in Firefox, but that's
unrelated and I'm assuming just the way Firefox is with sliders/dropdowns

**Comment by Deanphillips** [comment]
This can be marked as closed @Spellhammer
