### ISSUE TITLE
Active theme still affects the Wordpress installation when Oxygen is loaded

### ISSUE THREAD

**Issue by Phaen** [soflyy/oxygen-bugs-and-features#3483]
**Describe the bug**
Even though Oxygen should fully disable the active theme from having any effect on the site, the theme can still cause fatal errors and other malfunctions. I have recently come across this stack trace on a Website with Oxygen loaded:

An error of type E_ERROR was caused in line 58 of the file /[REDACTED]/wp-content/themes/vantage/functions.php. Error message: Uncaught Error: Call to undefined function siteorigin_setting() in /[REDACTED]/wp-content/themes/vantage/functions.php:58

```
Stack trace:
#0 /[REDACTED]/wp-includes/class-wp-hook.php(324): vantage_setup()
#1 /[REDACTED]/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()
#2 /[REDACTED]/wp-includes/plugin.php(517): WP_Hook->do_action()
#3 /[REDACTED]/wp-settings.php(621): do_action()
#4 /[REDACTED]/wp-config.php(131): require_once('/[REDACTED]/...')
#5 /[REDACTED]/wp-load.php(50): require_once('/[REDACTED]/...')
#6 /[REDACTED]/wp-login.php(12): require('/[REDACTED]/...')
#7 {main}
```

After deleting the files of this theme, functionality like the featured image option appeared to suddenly be missing on the site. Only after switching the active theme to something else was this fixed.

The active theme should NEVER have any effect on the website when Oxygen is active and this caused the website for my client to suddenly break for no reason, after one of his themes updated.
If this is expected, Oxygen should recommend the active theme to be switched to one of the WP default ones, instead of pretending that the active theme has no effect.

**IF YOU CAN'T PROVIDE A SANDBOX REPRODUCTION: Steps required to reproduce the bug:**
1. Make sure Oxygen is active and go into the active theme's function.php
2. Cause a fatal error. In this case, it was in a function added to the after_setup_theme hook. But I'm sure anything else works.
3. Watch the site crumble for no reason.

Alternative:
1. Make sure Oxygen is active and delete the active theme's files.
2. Watch functionality suddenly disappear, like the featured image option when creating a post.

**Comment by Kpudlo** [comment]
Hello @Phaen, 

I've attempted to recreate this behavior on a sandbox site, but have been unable to. If you can recreate this bug, please create it on a Sandbox site (https://oxygenbuilder.com/try/). Then, please open a Support Ticket (https://oxygenbuilder.com/support), and provide a link to the sandbox site. We'll be glad to assist further. If you can also include a link to this discussion in that ticket, that would be appreciated.

**Comment by Phaen** [comment]
It's been a while, and I don't seem able to replicate the first issue as well. The alternative is still easy to replicate though.

Here's my sandbox example showing the 'featured image' option missing: https://oxygen-qtqk4znhclwzl.oxygen-demo.qsandbox.org/wp-admin/post.php?post=2&action=edit

**Comment by Kpudlo** [comment]
Hi Phaen, 

Thank you for the update. As for the deleting of theme files, the problem with the featured image not showing still occurs even with Oxygen deactivated. While Oxygen does disable the theme system, a valid theme is still recommended.
