### ISSUE TITLE
The `Edit with Oxygen` meta box shouldn't appear for internal post types.

### ISSUE THREAD

**Issue by perrelet** [soflyy/oxygen-bugs-and-features#3485]
The `Edit with Oxygen` meta box shouldn't appear for internal post types.

ACF being a classic example of this:

![image](https://github.com/soflyy/oxygen-bugs-and-features/assets/7825147/f2231638-35e9-4bf1-b62c-127cdc029615)

**Comment by Kpudlo** [comment]
Oxygen can be disabled on post types via Settings > Client Control in WP Admin.

**Comment by perrelet** [comment]
@Kpudlo

You must agree it's pretty bizarre workflow to require your users to manually weed out every private post types for every install of oxygen though?

Wouldn't it make more sense to simply implement the fact that any post type that's registered with `public => false` can't be editted by oxygen anyway?

**Comment by perrelet** [comment]
@Kpudlo 

![image](https://github.com/soflyy/oxygen-bugs-and-features/assets/7825147/f977a57b-db00-428e-ad78-b194dccf2b5a)

**Comment by Kpudlo** [comment]
Hello @perrelet, 

> Wouldn't it make more sense to simply implement the fact that any post type that's registered with public => false can't be editted by oxygen anyway?

It could. I'll reopen this as a feature request. 


> 404 Error

If you're encountering an issue with Oxygen, please open a Support Ticket (https://oxygenbuilder.com/support) with the requested information and our support team will be glad to assist.

**Comment by perrelet** [comment]
@Kpudlo 

> 404 Error

Simply pointing out that this is a `bug` not a `feature request`.

👉 Selecting `Edit with Oxygen` for post types with `public => false` will always return a 404 because these post types don't have public permalinks. Such an error implies a bug, not a feature.

**Comment by perrelet** [comment]
Further, the instructions on the 404 page (see screenshot) do not reflect the issue.

**Comment by Kpudlo** [comment]
Thank you for the details. I've created a new bug report for the 404 issue via #3494.
