### ISSUE TITLE
[2.4 Beta 1] Can´t edit content in multisite subsites

### ISSUE THREAD

**Issue by widevisions** [soflyy/oxygen-bugs-and-features#349]
**Describe the bug**
After the upgrade to 2.4 Beta, I am unable to edit content in subsites of my multisite install.
Also, creating new test pages, I noticed I can´t edit headers to modify the text.

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
Yes

**Expected behavior**
Being able to edit the content

**What actually happens**
Previously created contents are loaded in the frontend, but in the backend, the builder loads but it doesn´t load any type of content with error "unable to load content" or even without any error.

**Desktop (please complete the following information):**
- OS: Windows 10
- Browser Chrome and Firefox
- Oxygen Version 2.4 Beta

**Additional context**
WP 5.2.1 multisite
PHP 7.3

**Comment by widevisions** [comment]
I forgot to add that my multisite installation is directories based.

**Comment by Spellhammer** [comment]
I'm unable to replicate this issue on a multi-site install. Can you please try a plugin conflict test to see if there's another plugin that could be causing this problem?

**Comment by widevisions** [comment]
Hi, I already did the whole debug process. There is nothing enabled on the
subsite, just UpdraftPlus that is network enabled. Do I have to disable
plugins also on the main site?
Thank you for your answer.

Il Lun 10 Giu 2019, 23:20 Elijah Mills <notifications@github.com> ha
scritto:

**Comment by widevisions** [comment]
I checked again and I disabled everything, no success. I upgraded from 2.4 Alpha
If you need to login to my VPS, no problem, it is a development platform so you can do whatever you want.
Let me know
Kindest regards

**Comment by Spellhammer** [comment]
@widevisions Please e-mail support@oxygenbuilder.com with login credentials, a link to the site, and directions on how to see the broken content and we'll take a look.

**Comment by widevisions** [comment]
Hi sorry for the late answer, but I figured it out. For some reason my main
content template got corrupted, I was able to restore a previous version
and now everything works again. Thank you very much and I aopologize but
this never happened before. Kindest regards.

Il giorno lun 10 giu 2019 alle ore 22:20 Elijah Mills <
notifications@github.com> ha scritto:
