### ISSUE TITLE
Error on frontend with changing units of measurement on adapters

### ISSUE THREAD

**Issue by KirillStanislavovich** [soflyy/oxygen-bugs-and-features#3490]
**Any bug report that doesn't include a Sandbox link or replication steps will be closed. If you can't provide these pieces of information, we're happy to help you via our official support channel instead: https://oxygenbuilder.com/support. You need to select "Something's broken and I need help" from the dropdown box on the left.**

**Describe the bug**
*A clear and concise description of what the bug is.*

**A link to a Sandbox site where the bug has been reproduced https://oxygenbuilder.com/try? (REQUIRED)**
*Provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*

**IF YOU CAN'T PROVIDE A SANDBOX REPRODUCTION: Steps required to reproduce the bug:**

u can't fill out the above information, you should not be filing a bug report. Instead, contact us via https://oxygenbuilder.com/support with the details you have and we'll investigate your issue further.**

https://oxygen-qll6vq2mtd3wl.oxygen-demo.qsandbox.org/sample-page/

<img width="1358" alt="Снимок экрана 2024-01-13 в 21 04 44" src="https://github.com/soflyy/oxygen-bugs-and-features/assets/58665744/c1c18315-97a6-4631-8121-0d69730bc702">
<img width="1364" alt="Снимок экрана 2024-01-13 в 21 06 09" src="https://github.com/soflyy/oxygen-bugs-and-features/assets/58665744/0b84f430-226f-4f09-b58a-53db328f8058">
<img width="1363" alt="Снимок экрана 2024-01-13 в 21 06 44" src="https://github.com/soflyy/oxygen-bugs-and-features/assets/58665744/3bad4091-6b57-4051-890c-85ce25bff37f">

**Comment by Kpudlo** [comment]
This is an issue related to some changes for unit inheritance in Oxygen 4.8 - our development team is reviewing potential solutions internally via https://github.com/soflyy/oxygen/issues/5257.

This issue impacts existing elements that haven't had their unit defined on your site and will not impact new sites, new pages, new templates, or new elements added after Oxygen 4.8. 

This can be fixed manually by setting your elements to use PX units for the impacted breakpoints.

**Comment by Marcin-Mazur** [comment]
Is there any schedule to fix the issue? We need this urgently. Thanks!

**Comment by maxmeelay** [comment]
Is this issue still open or maybe wantfix? Updated on our sites are frozen since this update...

**Comment by moloko100plus** [comment]
It got fixed with Oxygen 4.9.:
From the Changelog: For sites where unit sizes are incorrect on the front-end after updating to 4.8+, added a &fix_units=true URL parameter to run a script and fix incorrect units.
