### ISSUE TITLE
2.2 Beta 1 - Settings - Cache List of Google Fonts breaks template load

### ISSUE THREAD

**Issue by cmobrieno2** [soflyy/oxygen-bugs-and-features#35]
**Describe the bug**
*Checking the box for "Cache List of Google Fonts" causes the Builder to not fully load any templates (current or previous builds)*

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
*Yes*

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
*No need, see below.*

**To Reproduce**
1. Go to 'Oxygen -> Settings --> General'
2. Click on 'Cache List of Google Fonts'
3. Create new template or open an existing.

**Expected behavior**
*Builder should load template.*

**What actually happens**
*Template loading fails partially through load*

**Screenshots**
*Screens here: https://www.facebook.com/groups/1626639680763454/2081755118585239/?comment_id=2083767365050681&notif_id=1548861311882732&notif_t=group_comment_reply*

**Desktop (please complete the following information):**
- OS: Win 10
 - Chrome, latest
 - Oxygen 2.2 Beta 1

**Smartphone (please complete the following information):**
- Didnt check

**Additional context**
*Nope.*

![1 google fonts checked](https://user-images.githubusercontent.com/47185055/51993751-73927200-247d-11e9-9cee-7ea9ab930f06.png)
![2 builder loads but no template](https://user-images.githubusercontent.com/47185055/51993748-72f9db80-247d-11e9-855a-07ef98488e90.png)
![3 console message](https://user-images.githubusercontent.com/47185055/51993749-72f9db80-247d-11e9-92e3-05ac65f96e92.png)
![4 edit page](https://user-images.githubusercontent.com/47185055/51993750-73927200-247d-11e9-836d-c874f508a236.png)
![5 google fonts unchecked](https://user-images.githubusercontent.com/47185055/51993752-73927200-247d-11e9-95e7-f981741e7915.png)
![6 google fonts unchecked_template loads](https://user-images.githubusercontent.com/47185055/51993753-73927200-247d-11e9-99a3-49e442a6d31f.png)

**Comment by Spellhammer** [comment]
Unable to replicate this on a Sandbox install. Can you send admin login credentials to support@oxygenbuilder.com so that I can take a look at this on your site?

**Comment by Spellhammer** [comment]
@cmobrieno2 I don't believe we have received a ticket from you on this issue, but I'd really like to take a look at it. Is it still present on your site?

**Comment by Spellhammer** [comment]
Unable to replicate.
