### ISSUE TITLE
Latest Chrome Update Messed up Images

### ISSUE THREAD

**Issue by fsekerli** [soflyy/oxygen-bugs-and-features#350]
After the latest Chrome update, the images added via Media Library are not responsive. This issue happens on version of Chrome which is Version 75.0.3770.80 (Official Build) (64-bit). I tested this on different tablets and mobile phones. The version 75 creates the problem. The version 74 is fine. I see the same behavior for all the websites that I have built with Oxygen. The issue is not seen on other WordPress websites that I have built. I also noticed that if I add images on blog post via Gutenberg, they look fine. So, there must be something with the Oxygen and Chrome conflict.  

I tried all the steps at the troubleshooting guide.

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
Yes, I am able to replicate the issue on a Sandbox install. 
http://relieved-quail.w6.wpsandbox.pro
I added three columns with images through Media Library and they are not responsive. You can see it in the sample page.
http://relieved-quail.w6.wpsandbox.pro/sample-page/

**To Reproduce**
1. Go to any page you create.
2. Click on Add and add a section with three columns. Add image to each column and add the images via Media Library and choose full size. 
3. Save and see the page.

**Expected behavior**
I expected the images to be responsive.

**What actually happens**
The images seem to be not responsive. The width is okay, but the height is not responding to the code I guess.

**Screenshots**

**Desktop (please complete the following information):**
- OS: Linux Mint
 - Browser: Chrome Version 75.0.3770.80 (Official Build) (64-bit)
 - Oxygen Version: 2.3

**Additional context**
I have only two plugins active. One is Code Snippets and the other one is Oxygen. There is only one snippet for changing the length of the excerpt for blog posts.

**Comment by wplit** [comment]
Supa Mike posted the solution, just add this to stylesheet

` img { width: 100%; }`

**Comment by Spellhammer** [comment]
Reported internally at https://github.com/soflyy/oxygen/issues/1804

**Comment by KittenCodes** [comment]
This is fixed in the latest release of Oxygen.
