### ISSUE TITLE
Upgrade broke website and Oxygen builder

### ISSUE THREAD

**Issue by Zyles** [soflyy/oxygen-bugs-and-features#3503]
After upgrading to latest Oxygen everything is broken.

Links in the frontend redirect to the editor. Pages get 404 as links are now broken.

This error pops up in the editor:
![image](https://github.com/soflyy/oxygen-bugs-and-features/assets/1741593/51f4af32-f788-46b4-895f-d49a9cbb72b1)

Creating an archive page for a post type does not work anymore. It goes to 404 and can't find the template when you navigate to the URL.

Oxygen 4.8.1
Wordpress 6.4.3

**Comment by Spellhammer** [comment]
Please contact support: support@oxygenbuilder.com.
