### ISSUE TITLE
ACF fields return blank

### ISSUE THREAD

**Issue by jessebrightman** [soflyy/oxygen-bugs-and-features#3517]
Select a heading and open up insert data.  Select Advanced Custom Field then select the field.  Nothing happens.  Junk software mixed with other junk software creates bloated junk software.

**Any bug report that doesn't include a Sandbox link or replication steps will be closed. If you can't provide these pieces of information, we're happy to help you via our official support channel instead: https://oxygenbuilder.com/support. You need to select "Something's broken and I need help" from the dropdown box on the left.**

**Describe the bug**
*A clear and concise description of what the bug is.*

**A link to a Sandbox site where the bug has been reproduced https://oxygenbuilder.com/try? (REQUIRED)**
*Provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*

**IF YOU CAN'T PROVIDE A SANDBOX REPRODUCTION: Steps required to reproduce the bug:**

**If you can't fill out the above information, you should not be filing a bug report. Instead, contact us via https://oxygenbuilder.com/support with the details you have and we'll investigate your issue further.**

**Comment by Spellhammer** [comment]
We can help you at support@oxygenbuilder.com, but this isn't a bug report.

If you can reproduce this on one of our /try sites, comment here and I'll re-open the issue.
