### ISSUE TITLE
How to limit paging number oxygen builder?

### ISSUE THREAD

**Issue by dotrock** [soflyy/oxygen-bugs-and-features#3518]
Hi Soflyy,

I'm still confused with a limited paging number on the repeater, 
how to limit this number to 5-10 only? Please see the attached image. 
https://prnt.sc/Cbv58K6r4ZUw

Thanks

**Comment by Kpudlo** [comment]
This can be managed with the Gap and Range settings for the Repeater https://oxygenbuilder.com/documentation/builder-elements/repeater/#pagination.
