### ISSUE TITLE
2.4 Alpha to 2.4 Beta Content Missing

### ISSUE THREAD

**Issue by mgpub** [soflyy/oxygen-bugs-and-features#352]
**Describe the bug**
Upgrading from 2.4 Alpha to 2.4 Beta causes all pages built under Alpha to be completely blank after upgrading to Beta.

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
*Yes*

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
No, it is an upgrade issue...

**To Reproduce**
1. Create a page under 2.4 Alpha
2. Upgrade to 2.4 Beta
3. Try to edit the page
4. No content is shown

**Expected behavior**
Was hoping content would still be there.

**What actually happens**
Completely blank builder canvas.

**Screenshots**
*If applicable, add screenshots to help explain your problem.*

**Desktop (please complete the following information):**
- OS: [e.g. iOS] Windows 7 - 64 bit
 - Browser = Chrome
 - Oxygen Version = 2.4 Alpha to 2.4 Beta

**Smartphone (please complete the following information):**
 - Oxygen Version [e.g. 2.2 Alpha]

**Additional context**
*Add any other context about the problem here.*

**Comment by Spellhammer** [comment]
Unable to replicate this when upgrading from 2.3 or 2.4 Alpha 1 to 2.4 Beta 1.

Is the site you experienced this on a WordPress Multisite installation?

**Comment by mgpub** [comment]
It is running on WP 5.2.1 single instance.

**Comment by mgpub** [comment]
reinstalling 2.4 alpha on top of 2.4 Beta gets the page content back again

**Comment by Spellhammer** [comment]
Is the site you experienced this on a WordPress Multisite installation?

**Comment by Spellhammer** [comment]
Please perform a backup of your site using All In One WP Migration, preferably in the post-upgrade broken state, and send the wpress file to support@oxygenbuilder.com along with login credentials and we'll take a look.

**Comment by louisreingold** [comment]
Closing as this is unreproducible and only relates to upgrading from 2.4 alpha to 2.4 beta, but 2.4 final has already shipped.
