### ISSUE TITLE
 metaboxes are black in hover when I install Oxygen

### ISSUE THREAD

**Issue by tengocode** [soflyy/oxygen-bugs-and-features#3520]
Hi, when I install Oxygen, all metabox of WordPress are black in hover. Black with fonts grays, is hard to read.

![image](https://github.com/soflyy/oxygen-bugs-and-features/assets/101949760/d16a8822-8e70-4eb7-800e-5095ee2911f1)

**Comment by Kpudlo** [comment]
Replicated and reported internally via https://github.com/soflyy/oxygen/issues/4989

**Comment by Kpudlo** [comment]
This is fixed in Oxygen 4.9.1, which is available for beta testing. You may download the beta by logging into the [Customer Portal ](https://oxygenbuilder.com/)and then accessing the [Beta page](https://oxygenbuilder.com/beta-access/).
