### ISSUE TITLE
DONE: More API's please :) (adding components)

### ISSUE THREAD

**Issue by wplit** [soflyy/oxygen-bugs-and-features#353]
### **Describe the feature you'd like to see included in Oxygen.**
Loving the extendability of the conditionals feature. I would love to see an official API for creating new components... 

### **What are the use cases for this feature?**
Building more dynamic elements that can be used across sites (in a future proof way). eg a related posts slider using swiper.js, a new type of responsive menu element.. more niche focused components that wouldn't make sense to build in Oxygen. 

Design sets aren't good for these types of things because there isn't a sensible way of including the swiper.js into the set for eg, and even if we did squeeze the JS in somewhere, there's no way to push updates to the code if there is a conflict in the future.

Also, if we make a plugin to manually enqueue the assets, then we need to know which pages to enqueue in advance or we have no choice other than to load on every page. Good for one-off client sites, where we know where we are using the elements (and can manually add our own conditionals for enqueuing), but not good for having elements intended to be used across sites/shared.

The best way i can see going forward, is to be able to add new components ourselves (via plugin), and use design sets for styling those components in different ways. This way the logic/functionality stays inside a plugin (and we can use the component logic to ensure assets are only loaded where they are used like with the current AOS, and Modal features.) Design sets can just be for styles only.

Much more future proof as we can push updates to the core functionality of the component if needed. Also much easier for users to get access to building more complex things without worrying about learning the JS behind it. 

As we don't know what you guys & gals are updating Oxygen in the future, I'm reluctant to dive into that part of the code to start creating my own components without an official API. I'm sure others are the same.

### **Examples of this feature**
The obvious one is Elementor where they have their [developer documentation](https://developers.elementor.com) on building new widgets. The other one is Gutenberg where devs can build custom blocks.

**Comment by mgpub** [comment]
I concur with the comments from WPlit - I too would like the ability to start developing add-on functionality that is natively integrated with Oxygen.
Documentation would be nice, however, my biggest concern is functional continuity going forward. I am definitely one developer who wants to develop to add to the Oxygen ecosphere, but if I code to specific functions (and specific call parameters) and specific class names, I really want the assurance that these won't be suddenly changed or removed from one version to the next.

**Comment by Deanphillips** [comment]
This would be huge. Would also lighten the load from the O2 team too as they wouldn't have to create everything themselves anymore

**Comment by alpabuz** [comment]
We can't breathe without it.

**Comment by ivanjuras** [comment]
Yes, we need the API. That would launch Oxygen into stratosphere.

**Comment by greenyboy** [comment]
+1. This feature would be awesome

**Comment by Hanleymade** [comment]
Elementor is as big as it is because of 3rd party plugins. I'd like to see Oxygen continue building core features but allow other Developers to be Oxygen compatible so it speeds up development and site features.

**Comment by verioussmith** [comment]
Yes this would definitely push Oxygen into the runnings of the big dogs.

**Comment by Thotti79** [comment]
Yes, we need this feature in Oxygen to have a great variety of additional widgets like in Elementor but with the lightweightness of the Oxygen environment.

**Comment by deckerweb** [comment]
This is needed to strengthen the Oxygen ecosystem (and to make it one actually), very important for organic future growth.

Additionally, strong API's help also for special use cases. So it will be a win-win situation for all involved.

**Comment by BaronVonPerko** [comment]
Definitely +1 this. Would be cool if we could write php to create a custom query (more flexible than the query string we have now) and pass it into the easy posts. Power of custom php with the ease of designing with easy posts!

**Comment by steve-goldberg** [comment]
+1 for this. It's unrealistic to assume the Oxygen team, as great as they are, are going to create every addon/extension it's customers want, hence the need for third party addons like Elementor Addons for example. Oxygen is a powerful platform and being able to build on top of it would make it even more powerful.

**Comment by Oxymaniac** [comment]
+1
Hoping for it.

**Comment by wpdoit** [comment]
+1

**Comment by ivanjuras** [comment]
Definitely need this one. It would also take the burden off of Oxy developers. The whole community and ecosystem around Oxygen would flourish, especially if the API is good :)

**Comment by wpdevlab** [comment]
👍 It's time to move this thread to popular requests!

**Comment by laboiteare** [comment]
+1
It seems essential !

**Comment by alriksson** [comment]
+1
Totally agree users would be able to see more features and be able to create more feature-rich applications. Oxygen core would benefit and offload features.

I hope we can control it, so oxygen with addons doesn't become another Elementor. Meaning oxygen somehow control and force performance and no bloat. Meaning the API should be built so if an element is not in a catch all template it should not load globally.

**Comment by perrelet** [comment]
+1
Boom boom - We **really** need this.
You can only do so much with a shortcode wrapper lol...
Saying this, I totally agree with @mgpub - the devs among us would much prefer a solid API that'll last than something that's quick, dirty and will likely undergo continuous development and refactoring.

**Comment by Spellhammer** [comment]
Just updating this to say that there is an elements API, but I'm leaving this issue as a pending feature request until we're able to fully document the API for public usage.

**Comment by mrkenng** [comment]
Can't wait!

**Comment by perrelet** [comment]
@Spellhammer 

Unfortunately extending the component framework only appears to work on front end (not CT Builder)

Example:

`add_action('oxygen_after_add_components', function () {
	include_once("components/classes/test.class.php");
});`

test.class.php:
(which is a duplicate of ct_headline with only class name and options (tag and name) changed):

`Class CT_Test extends CT_Component {

	function __construct( $options ) {

		// run initialization
		$this->init( $options );
		
		// Add shortcodes
		add_shortcode( $this->options['tag'], array( $this, 'add_shortcode' ) );

		// change component button place
		remove_action("ct_toolbar_fundamentals_list", array( $this, "component_button" ) );
		add_action("oxygen_basics_components_text", array( $this, "component_button" ) );
	}


	/**
	 * Add a [ct_headline] shortcode to WordPress
	 *
	 * @since 0.1
	 */

	function add_shortcode( $atts, $content, $name ) {
		if ( ! $this->validate_shortcode( $atts, $content, $name ) ) {
			return '';
		}

		$options = $this->set_options( $atts );

		$content = do_shortcode( $content );
		$content = oxygen_vsb_filter_shortcode_content_decode($content);

		ob_start();

		$editable_attribute = $content;
		if( class_exists( 'Oxygen_Gutenberg' ) ) $editable_attribute = Oxygen_Gutenberg::decorate_attribute( $options, $editable_attribute, 'string' );

		echo "<".esc_attr($options['tag'])." id=\"".esc_attr($options['selector'])."\" class=\"".esc_attr($options['classes'])."\"";do_action("oxygen_vsb_component_attr", $options, $this->options['tag']); echo ">" . $editable_attribute . "</".esc_attr($options['tag']).">";

		return ob_get_clean();
	}
}

global $oxygen_vsb_components;
$oxygen_vsb_components['test'] = new CT_Test ( 

		array( 
			'name' 		=> 'Test',
			'tag' 		=> 'ct_test',
			'params' 	=> array(
					array(
						"type" 			=> "content",
						"param_name" 	=> "ct_content",
						"value" 		=> "Double-click this headline to edit the text.",
						"css" 			=> false,
					),
					array(
						"type" 			=> "font-family",
						"heading" 		=> __("Font Family", "oxygen"),
						"css" 			=> false,
					),
					array(
						"type" 			=> "colorpicker",
						"heading" 		=> __("Text Color", "oxygen"),
						"param_name" 	=> "color",
						"value" 		=> "",
					),
					array(
						"type" 			=> "slider-measurebox",
						"heading" 		=> __("Font Size", "oxygen"),
						"param_name" 	=> "font-size",
					),
					array(
						"type" 			=> "dropdown",
						"heading" 		=> __("Font Weight", "oxygen"),
						"param_name" 	=> "font-weight",
						"value" 		=> array (
											"" 	  => "&nbsp;",
											"100" => "100",
											"200" => "200",
											"300" => "300",
											"400" => "400",
											"500" => "500",
											"600" => "600",
											"700" => "700",
											"800" => "800",
											"900" => "900",
										),
					),
					array(
						"type" 			=> "tag",
						"heading" 		=> __("Tag", "oxygen"),
						"param_name" 	=> "tag",
						"value" 		=> array (
											"h1" => "H1",
											"h2" => "H2",
											"h3" => "H3",
											"h4" => "H4",
											"h5" => "H5",
											"h6" => "H6",
										),
						"css" 			=> false,
					),
				),
			'advanced' 	=> array(
					'typography' => array(
						'values' 	=> array (
								'font-family' 	=> array ( 'global', 'Display' ),
								'font-size' 	=> "",
								'font-weight' 	=> "",
								'text-align' 	=> ""
							)
					),
					'allowed_html'      => 'post',
					'allow_shortcodes'  => false,
			),
			'content_editable' => true,
		)
);`

Shows up as an element in the builder with tag name = 'undefined'

First guess here is that this is caused by limitation within controller.min.js given the js suggestive value of "**undefined**"... No real idea however...

Front end seems ok, but the elements API is seamingly **not** extendable at this time.

**Comment by KittenCodes** [comment]
> Can't wait! I've seen somepeople are able to create custom element. Is there a guide for it already?

There's a third-party guide here: https://codewriteups.com/build-custom-oxygenbuilder-elements-in-wordpress.html.

**Comment by ezosher** [comment]
Hey all, 

Any idea if this was really implemented? it says it does, but couldn't find any resource anywhere.
