### ISSUE TITLE
Nested link wrapper / button in Repeater breaks layout in front-end.

### ISSUE THREAD

**Issue by Anibaaal** [soflyy/oxygen-bugs-and-features#3540]
**Any bug report that doesn't include a Sandbox link or replication steps will be closed. If you can't provide these pieces of information, we're happy to help you via our official support channel instead: https://oxygenbuilder.com/support. You need to select "Something's broken and I need help" from the dropdown box on the left.**

**Describe the bug**
When adding a Link Wrapper inside of the Repeater's default div, and then adding a Button (both pointing to post permalink), the layout in the front end is completely broken or the link is missing. Moving the child button around or wrapping it in another div seems to break the repeater in different ways.

**A link to a Sandbox site where the bug has been reproduced https://oxygenbuilder.com/try? (REQUIRED)**
Link to sandbox: https://oxygen-qd68cbxj7c6yl.oxygen-demo.qsandbox.org/sample-page/

The repeater is in the Sample Page.

Screenshots to demonstrate:
![chrome_an5TJxYAtP](https://github.com/soflyy/oxygen-bugs-and-features/assets/11686035/78202f3c-8fb5-40cb-b5e9-2491800fdcc8)
![chrome_e1CcfaHkWH](https://github.com/soflyy/oxygen-bugs-and-features/assets/11686035/c560e477-1110-41d1-9b17-39278d60e586)

**Comment by KittenCodes** [comment]
@Anibaaal 

> When adding a Link Wrapper inside of the Repeater's default div, and then adding a Button (both pointing to post permalink), the layout in the front end is completely broken or the link is missing. Moving the child button around or wrapping it in another div seems to break the repeater in different ways.

Yes, that would be expected as you are creating invalid HTML by nesting links. The browser then attempts to de-nest these on the front-end of the site, which results in the broken layout.

If you want to create something that looks like a button inside a Link Wrapper, you would need to use a Text element and style it appropriately.
