### ISSUE TITLE
Animate on scroll not working properly after a Toggle element

### ISSUE THREAD

**Issue by roninhaf** [soflyy/oxygen-bugs-and-features#3543]
**Any bug report that doesn't include a Sandbox link or replication steps will be closed. If you can't provide these pieces of information, we're happy to help you via our official support channel instead: https://oxygenbuilder.com/support. You need to select "Something's broken and I need help" from the dropdown box on the left.**

Link: https://oxygen-qwkzcczaybhzl.oxygen-demo.qsandbox.org/home/

**Describe the bug**
*A clear and concise description of what the bug is.*

I've put an Animate on Scroll effect on all the headers of the home page.
I've put a Toggle element at the end of the first section.
After putting the Toggle element, all the headers that have the effect that come after it will not get triggered by scrolling.

**A link to a Sandbox site where the bug has been reproduced https://oxygenbuilder.com/try? (REQUIRED)**
*Provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*

**IF YOU CAN'T PROVIDE A SANDBOX REPRODUCTION: Steps required to reproduce the bug:**

**If you can't fill out the above information, you should not be filing a bug report. Instead, contact us via https://oxygenbuilder.com/support with the details you have and we'll investigate your issue further.**

**Comment by Kpudlo** [comment]
Hi @roninhaf, 

Sometimes, AOS needs to be refreshed when the page loads. This can be enabled by going to Settings > Global Styles > Animate on Scroll within Oxygen and enabling "Refresh AOS On Page Load."

**Comment by roninhaf** [comment]
> Hi @roninhaf,
> 
> Sometimes, AOS needs to be refreshed when the page loads. This can be enabled by going to Settings > Global Styles > Animate on Scroll within Oxygen and enabling "Refresh AOS On Page Load."

Thank you Kpudlo :)

I can confirm that this setting fixes the issue for me. I was not familiar with it. I'm not sure if this is normal behavior or not though.
