### ISSUE TITLE
"Error occurred while loading SVG icons"

### ISSUE THREAD

**Issue by pwil30** [soflyy/oxygen-bugs-and-features#355]
**Describe the bug**
When loading the Oxy template editor, get an error: "Error occurred while loading SVG icons". There are no icon sets present, the list is empty and the icon selector list is empty.

I tried uploading a custom icon set, and it worked and shows in the list in Oxygen settings, but it does not show up in the template editor either.

Error shows in the console (see attached screenshot):
 
/wp-admin/admin-ajax.php?action=ct_get_svg_icon_sets&nonce=1d59017d76&post_id=1201 net::ERR_CONTENT_DECODING_FAILED 200 (OK)

I believe this happened upon upgrading from 2.1 to 2.3.

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
Yes.

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
Yes, but the issue is only present on template pages in the admin, so there is no public facing URL to give.

**Expected behavior**
- icon sets should be shown in the list in the Icon component of the Oxygen editor.
-icons should show in the template.

**What actually happens**
- no icon sets are listed. Dropdown is blank.
- no svgs to select from.
- all SVGs present in the template are converted to a thumbs up icon (perhaps a standard fallback?)
- issue occurred on both our dev install, and production install, hosted on separate servers.

**Screenshots**
Attached

**Desktop (please complete the following information):**
Mac OS Mojave
Chrome 75
Oxygen 2.3

**Smartphone (please complete the following information):**
 - Oxygen Version [e.g. 2.2 Alpha]

![Screen Shot 2019-06-10 at 2 09 02 PM](https://user-images.githubusercontent.com/17596588/59216626-fb099380-8b89-11e9-898e-909cf0b667e4.png)
![Screen Shot 2019-06-10 at 2 05 57 PM](https://user-images.githubusercontent.com/17596588/59216627-fb099380-8b89-11e9-86f4-02959a449ad6.png)
![Screen Shot 2019-06-10 at 1 58 12 PM](https://user-images.githubusercontent.com/17596588/59216628-fb099380-8b89-11e9-8daa-9799e687042e.png)

**Comment by KittenCodes** [comment]
@pwil30 If this is still happening in the latest release of Oxygen, send credentials for your site and a link to where we can see the error to support@oxygenbuilder.com.

**Comment by octapress** [comment]
I am having the exact same issue on a staging site (not https), behind a password.

**Comment by subsevenx** [comment]
Can report this is still happening. I am not sure if it's a conflict with any of the extensions for Oxygen I have installed. 
![image](https://user-images.githubusercontent.com/5679100/132909090-8ac81e18-0feb-42e6-98e0-75f3c121da0b.png)

**Comment by avocadesign** [comment]
We're also seeing this on a number of sites

**Comment by vaztimur** [comment]
Error occurres while loading svg icons in Oxygen 4.3!!!
