### ISSUE TITLE
The function "function oxygen_meta_migration_notice" creates false positives.

### ISSUE THREAD

**Issue by berntjs** [soflyy/oxygen-bugs-and-features#3553]
**Any bug report that doesn't include a Sandbox link or replication steps will be closed. If you can't provide these pieces of information, we're happy to help you via our official support channel instead: https://oxygenbuilder.com/support. You need to select "Something's broken and I need help" from the dropdown box on the left.**

**Describe the bug**
*A clear and concise description of what the bug is.*

I've installed ACF and created a Field Group where "Name" is "cta_test". After creating a new page where this field has a value, the popup for Oxygen meta keys upgrade for 4.8.3 has showed up. This is due to the function oxygen_meta_migration_notice in updates.php, more specific line 89 (bolded below):

// Query to find meta keys starting with 'ct_' but not '_ct_'
    $query = "
        SELECT meta_key
        FROM $wpdb->postmeta
        **WHERE meta_key LIKE 'ct_%'**
        AND meta_key NOT LIKE '\\__ct_%'
        LIMIT 1
    ";

"WHERE meta_key LIKE 'ct_%'" creates false positives since it doesn't just match any values starting with ct_ but also different values, such as cta_test in my example.

**A link to a Sandbox site where the bug has been reproduced https://oxygenbuilder.com/try? (REQUIRED)**
*Provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*

Sandbox: https://oxygen-qbgg4w3d2j4zl.oxygen-demo.qsandbox.org/wp-admin/index.php (Access code 7474)

Link to ACF field group: https://oxygen-qbgg4w3d2j4zl.oxygen-demo.qsandbox.org/wp-admin/post.php?post=20&action=edit

Popup message: _Oxygen 4.8.3+ requires a migration of your Oxygen meta keys, and some keys have not yet migrated automatically. If this notice remains after 5 to 10 minutes and your site is experiencing issues, please click here to re-run the migration manually._

**Comment by KittenCodes** [comment]
@berntjs 

This will be fixed in the upcoming release of v4.9.
