### ISSUE TITLE
ACF Fields do not work in content

### ISSUE THREAD

**Issue by jessebrightman** [soflyy/oxygen-bugs-and-features#3557]
I am trying to add an ACF Field to a template and when clicking on the field name, it doesn't do anything and does not load the field into the page.  When using the field in a code block it works fine.  Sort of defeats the whole purpose though.

**Any bug report that doesn't include a Sandbox link or replication steps will be closed. If you can't provide these pieces of information, we're happy to help you via our official support channel instead: https://oxygenbuilder.com/support. You need to select "Something's broken and I need help" from the dropdown box on the left.**

**Describe the bug**
*A clear and concise description of what the bug is.*

**A link to a Sandbox site where the bug has been reproduced https://oxygenbuilder.com/try? (REQUIRED)**
*Provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*

**IF YOU CAN'T PROVIDE A SANDBOX REPRODUCTION: Steps required to reproduce the bug:**

**If you can't fill out the above information, you should not be filing a bug report. Instead, contact us via https://oxygenbuilder.com/support with the details you have and we'll investigate your issue further.**

**Comment by Kpudlo** [comment]
@jessebrightman, pease open a Support Ticket (https://oxygenbuilder.com/support), and provide a staging environment where we can see the problem. We'll be glad to assist further. If you can also include a link to this discussion in that ticket, that would be appreciated.

**Comment by jessebrightman** [comment]
There are far too many bugs on this platform to have to open a support ticket for each one.  It's already wasted so much of my time that I have long 10s of thousands of dollars on. How I long to go back to .NET or Node.
