### ISSUE TITLE
Parse error: syntax error, unexpected identifier "version"

### ISSUE THREAD

**Issue by picarda** [soflyy/oxygen-bugs-and-features#3560]
Hello,
I'm currently having this message on my home page:

_Parse error: syntax error, unexpected identifier "version" in /home/alainpic/seosolutionsmontreal.com/wp-content/plugins/oxygen/component-framework/components/classes/code-block.class.php(133) : eval()'d code on line 1_

-WordPress 6.5.5 running
- Oxygen Version 4.9

* Same issue with all the other pluging disable.
** No cache

**Comment by Kpudlo** [comment]
Hello @picarda, 

This error indicates there is a problem with `version` in one of the Code Blocks in Oxygen. You'll want to check line 1 in the Code Block on the page/template that triggers the error, look for `version`, and see if modifying the code fixes the issue. 

If you still need help after performing those steps, please open a Support Ticket (https://oxygenbuilder.com/support), and provide a staging environment where we can see the problem. We'll be glad to assist further. If you can also include a link to this discussion in that ticket, that would be appreciated.

**Comment by picarda** [comment]
Hello Kpudlo,
Found the cause... in the Code Block I put a .svg. and the .svg had this on the line 1.
`<?xml version="1.0" encoding="UTF-8" standalone="no"?>`

Thank you!
