### ISSUE TITLE
Hide/Unhide option in the Structure panel is not working

### ISSUE THREAD

**Issue by hashimea** [soflyy/oxygen-bugs-and-features#3562]
**Describe the bug**

The Hide/Unhide option in the Structure panel and the new dropdown is not functioning as expected. It was working fine in previous versions.

1. Open Oxygen Builder and load your existing design or create a new one.
2. Navigate to the Structure panel on the right-hand side.
3. Attempt to use the Hide/Unhide option on any element within the Structure panel.
4. Observe that the Hide/Unhide functionality is not working as intended.
   Additionally, try to use the new dropdown menu for the same purpose and note if the issue persists.

**Comment by neografik** [comment]
Any fix this bug??

**Comment by Kpudlo** [comment]
This has been reported internally via https://github.com/soflyy/oxygen/issues/5436 and will be addressed in the next Oxygen update.

**Comment by neografik** [comment]
https://github.com/soflyy/oxygen/issues/5436 page not found...
When be ready next apdate with this fix?

**Comment by fernandogobah** [comment]
+1

**Comment by QuentinBar** [comment]
+1

**Comment by Kpudlo** [comment]
Hello, 

This is fixed in Oxygen 4.9.1, which is available for beta testing. You may download the beta by logging into the [Customer Portal ](https://oxygenbuilder.com/) and then accessing the [Beta page](https://oxygenbuilder.com/beta-access/).

**Comment by voed** [comment]
@Kpudlo Hi, maybe i am not understanding the purpose of this feature, but the element hides only in the Oxygen Editor and not the actual frontend page.

**Comment by Kpudlo** [comment]
Hi @voed, that is what the feature is for. It is for hiding elements in the builder only, not the front end. 

Setting display to none, or using a condition, will hide it on the front end

**Comment by voed** [comment]
Oh, okay. That's actually what i did. Thanks.
