### ISSUE TITLE
Newest version 4.9 - broken real time preview of the background and shadow properties of an element

### ISSUE THREAD

**Issue by janknop** [soflyy/oxygen-bugs-and-features#3566]
Newest version broke real time preview of updated background position and shadow properties when in the builder. All shows up properly on the front end. 

To replicate the issue:
1. Apply background image or a shadow to an element
2. Try adjusting settings for the above.
3.  Observe that background doesn't change position / shadow real-time preview doesn't work.

After investigating the background position issue I discovered that in the builder CSS code that takes care of real time background positioning is missing units like pixels or percentages.

**Comment by Spellhammer** [comment]
This has been reported, reproduced, and will be fixed in an upcoming release.
