### ISSUE TITLE
Icon Box Text Won't Delete and Stay Deleted

### ISSUE THREAD

**Issue by IncreaseWebDev** [soflyy/oxygen-bugs-and-features#3568]
I'm new to oxygen. I cannot for the life of me get the icon box text to stop loading after I deleted it. 

I delete it, and the default text in the icon blurb keeps coming back after I save it. 

I also tried targetting the CSS to it through stylesheets... and well that's just not working at all.

**Comment by Kpudlo** [comment]
Hello @IncreaseWebDev, 

If you still need help with this, please open a Support Ticket (https://oxygenbuilder.com/support), and provide a staging environment where we can see the problem. We'll be glad to assist further. If you can also include a link to this discussion in that ticket, that would be appreciated.
