### ISSUE TITLE
I want to use Oxygen to edit the theme .  

### ISSUE THREAD

**Issue by Can-sang** [soflyy/oxygen-bugs-and-features#3583]
I want to use Oxygen to edit the theme .  How can I?

**Comment by KittenCodes** [comment]
@Can-sang 

Oxygen disables the WordPress theme on the site. It's not possible to use Oxygen to edit the theme.

**Comment by Can-sang** [comment]
this plugin 'role? This plugin can't make it?

**Comment by Can-sang** [comment]
> @Can-sang
> 
> Oxygen disables the WordPress theme on the site. It's not possible to use Oxygen to edit the theme.
this plugin 'role? This plugin can't make it?   Thank you very much!
