### ISSUE TITLE
Error 200: Can't save page;PHP Warning:  Undefined array key "toggle_active_class"

### ISSUE THREAD

**Issue by TheCartographerDev** [soflyy/oxygen-bugs-and-features#3590]
Big problems the last couple of weeks with my oxygen page. This is the major one so far. I can't save changes to my page inside oxygen editor.

my server shows this error log:

12.11.2024 14:20:23 basemap.de [client XXX.XXX.XXX] PHP Warning:  Undefined array key "toggle_active_class" in /mnt/web121/a2/52/511808952/htdocs/wordpress/wp-content/plugins/oxygen/component-framework/components/classes/toggle.class.php on line 199
12.11.2024 14:20:55 basemap.de [client XXX.XXX.XXX] PHP Warning:  Undefined array key "toggle_active_class" in /mnt/web121/a2/52/511808952/htdocs/wordpress/wp-content/plugins/oxygen/component-framework/components/classes/toggle.class.php on line 199
12.11.2024 14:23:53 basemap.de [client XXX.XXX.XXX] PHP Warning:  Undefined array key "toggle_active_class" in /mnt/web121/a2/52/511808952/htdocs/wordpress/wp-content/plugins/oxygen/component-framework/components/classes/toggle.class.php on line 199
12.11.2024 14:24:23 basemap.de [client XXX.XXX.XXX] PHP Warning:  Undefined array key "toggle_active_class" in /mnt/web121/a2/52/511808952/htdocs/wordpress/wp-content/plugins/oxygen/component-framework/components/classes/toggle.class.php on line 199
12.11.2024 14:26:31 basemap.de [client XXX.XXX.XXX] AH01225: Error reading request entity data
12.11.2024 14:32:01 basemap.de [client XXX.XXX.XXX] PHP Warning:  Undefined array key "toggle_active_class" in /mnt/web121/a2/52/511808952/htdocs/wordpress/wp-content/plugins/oxygen/component-framework/components/classes/toggle.class.php on line 199
12.11.2024 14:37:11 basemap.de [client XXX.XXX.XXX] AH01215: stderr from /home/strato/http/premium/rid/89/52/511808952/htdocs/wordpress/index.php: PHP Warning:  Undefined array key "toggle_active_class" in /mnt/web121/a2/52/511808952/htdocs/wordpress/wp-content/plugins/oxygen/component-framework/components/classes/toggle.class.php on line 199
12.11.2024 14:39:27 basemap.de [client XXX.XXX.XXX] AH01215: stderr from /home/strato/http/premium/rid/89/52/511808952/htdocs/wordpress/index.php: PHP Warning:  Undefined array key "toggle_active_class" in /mnt/web121/a2/52/511808952/htdocs/wordpress/wp-content/plugins/oxygen/component-framework/components/classes/toggle.class.php on line 199
12.11.2024 14:43:22 basemap.de [client XXX.XXX.XXX] AH01215: stderr from /home/strato/http/premium/rid/89/52/511808952/htdocs/wordpress/index.php: PHP Warning:  Undefined array key "toggle_active_class" in /mnt/web121/a2/52/511808952/htdocs/wordpress/wp-content/plugins/oxygen/component-framework/components/classes/toggle.class.php on line 199
12.11.2024 14:54:33 basemap.de [client XXX.XXX.XXX] PHP Warning:  Undefined array key "toggle_active_class" in /mnt/web121/a2/52/511808952/htdocs/wordpress/wp-content/plugins/oxygen/component-framework/components/classes/toggle.class.php on line 199
12.11.2024 14:55:49 basemap.de [client XXX.XXX.XXX] PHP Warning:  Undefined array key "toggle_active_class" in /mnt/web121/a2/52/511808952/htdocs/wordpress/wp-content/plugins/oxygen/component-framework/components/classes/toggle.class.php on line 199
12.11.2024 15:10:21 basemap.de [client XXX.XXX.XXX] PHP Warning:  Undefined array key "toggle_active_class" in /mnt/web121/a2/52/511808952/htdocs/wordpress/wp-content/plugins/oxygen/component-framework/components/classes/toggle.class.php on line 199

This is a major issue right now. Is this on my end?

**Comment by Kpudlo** [comment]
Hi @TheCartographerDev, please open a Support Ticket (https://oxygenbuilder.com/support), and provide a staging environment where we can see the problem. We'll be glad to assist further. If you can also include a link to this discussion in that ticket, that would be appreciated.
