### ISSUE TITLE
Cannot select template type since update to WordPress 6.7

### ISSUE THREAD

**Issue by TechBright-Media** [soflyy/oxygen-bugs-and-features#3592]
Since updating to WordPress 6.7 I cannot set a template type on new or existing templates. The accordion sections titled "Singular", "Archive" and "Other" do not reveal the options below when clicking their respective titles. Your sandbox cannot test version 6.7, this also happens on a fresh install with no additional plugins.

**Comment by TechBright-Media** [comment]
Does anyone know of a temporary work around?

**Comment by laynmin** [comment]
> Does anyone know of a temporary work around?

If you use the browsers Inspect tool to inspect the page, find the element for one of the three tabs: Singular, Archive, or Other. It is an li tagged element with class “control-section”. Find the div element within that with class “accordion-section-content” and uncheck the ‘display: none’ property. You can then use the accordion menus within the template and update as usual.

**Comment by TechBright-Media** [comment]
Nice to know this seems to just be the accordion function, thanks for reply I kinda should of seen that that tbf

**Comment by l00f00** [comment]
> Does anyone know of a temporary work around?

I rolled core back to 6.6.2 and the accordion started working again.

**Comment by Kpudlo** [comment]
We've just released Oxygen 4.9.1. RC 1, which has the fix to address this issue. You can download this version of Oxygen by logging into the [Oxygen Customer Portal](https://oxygenbuilder.com/portal/) and navigating to the [Beta Access](https://oxygenbuilder.com/beta-access/) page.

**Comment by thaers3d** [comment]
> We've just released Oxygen 4.9.1. RC 1, which has the fix to address this issue. You can download this version of Oxygen by logging into the [Oxygen Customer Portal](https://oxygenbuilder.com/portal/) and navigating to the [Beta Access](https://oxygenbuilder.com/beta-access/) page.

I attempted it, but the issue persists.

**Comment by hellomzvdesign** [comment]
You have to press button "Singular" or "Archive" or "Other".

**Comment by laithsinawi** [comment]
> Does anyone know of a temporary work around?

My workaround is simply rollback WP to an earlier version until a fix is released
