### ISSUE TITLE
Applying templates to Archives/Singular/Other broken with WordPress 6.7

### ISSUE THREAD

**Issue by 4tcmedia** [soflyy/oxygen-bugs-and-features#3597]
Since the upgrade to WordPress 6.7, the Oxygen template settings where you can choose to "inherit design from other template", "Where does this template Apply" settings by dropping down the options, does not work. Clicking the headings "Singular, Archives, Other", does not drop down the options to apply the template to. 

Reproduce. 
1. Upgrade to Wordpress 6.7
2. Create an oxygen template or edit an existing template
3. Before clicking the "edit with oxygen" button, attempt to apply the template to a particular taxonomy or post type and you will notice the dropdown does not present any options.

Solution: Rolling back to Wordpress 6.6.2 has rectified the issue. 

Thanks guys.
![bug](https://github.com/user-attachments/assets/011824ca-9ca7-409a-bf54-877e83ef6dab)

**Comment by KittenCodes** [comment]
This issue occurs from changes in WordPress 6.7. Our development team has identified a fix, which is now available in Oxygen 4.9.1 RC 1. You can download this version of Oxygen by logging into the [Oxygen Customer Portal](https://oxygenbuilder.com/portal/) and navigating to the [Beta Access](https://oxygenbuilder.com/beta-access/) page.
