### ISSUE TITLE
DONE: Copy ID to class + Auto Create Class

### ISSUE THREAD

**Issue by Deanphillips** [soflyy/oxygen-bugs-and-features#36]
From the forum:

It would be super nice to be able to use right-click functionality to copy, paste, and reset styles.

Example Use Cases:

1) Copy Styles from ID to Class
- Right click on an ID's Advanced tab > Copy All Styles, switch to the class, right click on Advanced tab > Paste All Styles

2) Copy Certain Advanced Styling from One Element or Class to Another
- Right click on Effects > Copy Effects, switch to different element or class, right click on Effects > Paste Effects

3) Reset Advanced Styles
- In Advanced tab, right click on Typography > Reset Typography

**Comment by sunnyt7** [comment]
This would save soo much time.

**Comment by fscriven** [comment]
Not 100% sure if included above but ability to delete all css in the id (when transferring or even without transferring to class) would be very useful.

This for me is one of the most important feature requests

**Comment by timpixel** [comment]
I'm a bit shocked that this does not have much more votes/likes! Also there are several requests in the github list that are related to this one. Perhaps those posts can be merged into one post that summarizes all the css class features?

**Comment by adrien-robert** [comment]
I agree with the time saved that this feature can bring to every Oxygen users...

**Comment by gitsimhub** [comment]
that would be great!

**Comment by alriksson** [comment]
+1 Would be great with undo and reset functionality together with copy style. All those features with multi-select to paste or reset or undo.

**Comment by 5pointDigital** [comment]
This is quality of life stuff, combined with some odd UI choices, significantly impacts workflow.

**Comment by wordpressguy22** [comment]
+1

**Comment by Spellhammer** [comment]
Copy to/clear styles for selectors implemented in 3.5 alpha 1.

The feature is slightly different, but accomplishes the essential goal of the feature request, so I'm marking this as implemented.

Right click/contextual controls would be part of a much larger overhaul to the way users interact with Oxygen.
