### ISSUE TITLE
Bug when using images with accent in the filename

### ISSUE THREAD

**Issue by johnchatel** [soflyy/oxygen-bugs-and-features#365]
**Describe the bug**
*A clear and concise description of what the bug is.*
I just find that when you are using an image with an accent in the filename, there is a bug and the message about shortcode signature is displayed.

**To Reproduce**
1. Add an image in your template
2. Add a source with accent in the filename (for my example la_télé.jpg)
3. Save
4. Check the front end

**Screenshots**
*If applicable, add screenshots to help explain your problem.*
<img width="301" alt="image" src="https://user-images.githubusercontent.com/6806329/59855760-db3a5280-9375-11e9-8494-d177cc1bc64e.png">

<img width="943" alt="image" src="https://user-images.githubusercontent.com/6806329/59855722-c8c01900-9375-11e9-8364-25632d2ebd46.png">

**Desktop (please complete the following information):**
- OS: Macos Mojave
 - Browser Firefox
 - Oxygen Version 2.4 RC1

**Comment by KittenCodes** [comment]
This is fixed in the latest version of Oxygen.
