### ISSUE TITLE
Text Link open in new tab

### ISSUE THREAD

**Issue by mattsterp** [soflyy/oxygen-bugs-and-features#368]
**Describe the feature you'd like to see included in Oxygen.**
I would like to see a checkbox added to the Text Link object which allows you to open the linked page in a new tab.   This should be available everywhere there is the option to add a link in my opinion.

**What are the use cases for this feature?**
Better user experience to keep the main website open and launch any secondary links in a new tab.

**Examples of this feature or functionality.**
The same feature is available in the WordPress Admin > Menus > Screen Options > Link Target.  
<img width="433" alt="link target" src="https://user-images.githubusercontent.com/6463435/60023299-8cd1d000-9663-11e9-96ca-c8e516247e3e.png">

**Comment by KittenCodes** [comment]
Hey @mattsterp,

If you click "Set" next to the URL then a window will open that allows you to select "Open link in a new tab".

Screenshots: https://d.pr/i/dWvlmc and https://d.pr/i/lxF8PE.

**Comment by mattsterp** [comment]
Thank you for pointing this out to me.

**Comment by zohaib-am** [comment]
@KittenCodes I can confirm that this "Set" button does not work at least in Safari and Firefox.

**Comment by zohaib-am** [comment]
@KittenCodes and negative on Chrome either

**Comment by KittenCodes** [comment]
@zohaib-am I'm not able to replicate this in Firefox or Chrome - the links are opening in a new tab after using the "Set" button and selecting "Open link in a new tab".

I'd like to see why this isn't working for you. Please can you open a ticket at https://oxygenbuilder.com/support/ so that I can take a look?
