### ISSUE TITLE
Cannot style class after style id

### ISSUE THREAD

**Issue by estraatios** [soflyy/oxygen-bugs-and-features#377]
Hi.

If I start styling an element and then create a class for that element, all the stylings in the class are empty and no matter what I change the style is not updating. I have to go to the id, remove everything and then start again at the class. 

It would be nice to have an option to capture all the styling from id to class.

**Comment by wplit** [comment]
I agree, it was also mentioned here - https://github.com/soflyy/oxygen-bugs-and-features/issues/36

**Comment by yankiara** [comment]
This happens all the time, please fix this next release.
So many lost time because of this :-(

**Comment by KittenCodes** [comment]
This isn't a bug - it's the way CSS works. Styles applied to an ID will always take precedence over styles applied to a class.

If you would like to see the ability to copy styles from an ID to a class, please add a vote to the feature request here: #36
