### ISSUE TITLE
Data Field / ACF loses formatting

### ISSUE THREAD

**Issue by nurick** [soflyy/oxygen-bugs-and-features#381]
When I use Oxygen's excellent data facilities to insert text into an Oxygen Text Box from an ACF WYSIWYG field, formatting (HTML tags) is lost. When I insert the same text from the page's Content field, formatting is preserved.

**Comment by KittenCodes** [comment]
Unfortunately, this is a known issue. To insert an ACF WYSIWYG field and retain the proper formatting, you can insert a Code Block and use PHP instead:

```php
<?php
    the_field('field_name');
?>
```

**Comment by Spellhammer** [comment]
Fixed in 2.4.
