### ISSUE TITLE
More role's in the role manager

### ISSUE THREAD

**Issue by ActiveByte** [soflyy/oxygen-bugs-and-features#382]
**Describe the feature you'd like to see included in Oxygen.**
*I want a better role manager with a role to give to customers that are only allowed to edit text on your website so that they can not mess with your design.*

**What are the use cases for this feature?**
*So the designer does not need to edit text on the site for the client, the client can do it*

**Examples of this feature or functionality.**
*Remove elements from the editor etc
https://www.youtube.com/watch?v=aoB8nuq7NZA*

This is the only thing that holds me back from switching to Oxygen. I'm using elementor now

**Comment by Shirkit** [comment]
You should prolly take a look at 3.0 with the Gutenberg integration. May not be 100% but maybe it's good enough.

**Comment by louisreingold** [comment]
Wait for the Gutenberg integration in 3.0, which allows exactly this, with the added benefit that it happens right in Gutenberg as opposed to the customer having to open the builder.

**Comment by ActiveByte** [comment]
Can i have a alpha of beta? If i buy 2.0 will i get the 3.0 upgrade free? If so ill buy it

**Comment by KittenCodes** [comment]
@ActiveByte 

> Can i have a alpha of beta? If i buy 2.0 will i get the 3.0 upgrade free? If so ill buy it

If you buy the current version of Oxygen then you'll have access to the Alpha version of 3.0. When the Beta/RC and full release are available, you'll also have access to those.

**Comment by ActiveByte** [comment]
Hey, i got oxygen and installed Gutenberg. it kinda works but its sadly not like elementor, its not like you can give permission for content only and the user can edit the nav image or some other custom designs made in oxygen. will there be a feature like this
