### ISSUE TITLE
Full sized srcset images inserted from Media getting stretched to 100%

### ISSUE THREAD

**Issue by srikat** [soflyy/oxygen-bugs-and-features#383]
Images inserted from the Media Library with size set to `full` are appearing fine in the Oxygen editor but getting blown up / stretched on the front end.

The issue can be seen here: http://wide-eyed-butterfly.w5.wpsandbox.pro/sample-page/

Screenshot in the editor:

![screenshot](https://d.pr/i/ms5zn4+)

Oxygen Version: 2.4

This problem is not present in v2.3.

This is apparently due to `width` not being present in the value of `srcset` attribute in the generated HTML.

Facebook discussion: https://www.facebook.com/groups/1626639680763454/permalink/2328481307245951/

**Comment by KittenCodes** [comment]
This should be fixed in the latest version of Oxygen.
