### ISSUE TITLE
(3.0 Alpha 1) Oxygen.css messing up Gutenberg UI

### ISSUE THREAD

**Issue by wplit** [soflyy/oxygen-bugs-and-features#385]
**Describe the bug**
Oxygen.css contains very general CSS, so is causing styling problems when being loaded into Gutenberg editor. eg where there is `<button>`

**Screenshots**
<img width="1920" alt="Screen Shot 2019-07-10 at 5 09 09 pm" src="https://user-images.githubusercontent.com/43051571/60948210-c417d080-a335-11e9-9d82-fecd0e455402.png">

**Comment by Deanphillips** [comment]
Yep having this issue too. It's also trying to grab my front end font (which has also had issues since upgrading too)

**Comment by louisreingold** [comment]
@Deanphillips @wplit what should we do about this?

If we want styles (like global styles, normalize.css type styles, Oxygen's default styles, etc.) to apply to Gutenberg, we need to load them in the WP admin. But if we load them in the WP admin... they affect the WP admin.

I feel like we should just break the WP admin styles slightly and hope people (from many projects, not just Oxygen) will encourage the Gutenberg team to use an iframe. Otherwise Gutenberg is headed down a very bad path (millions of silly hoops devs have to jump through) if it ever wants to provide an accurate visual representation of the frontend.

**Comment by Deanphillips** [comment]
Tbh I'm not too bothered about the backend matching the front too much, as this feels more problematic (text tiny + difficult to add elements as it's so to the side)
<img width="1066" alt="Screenshot 2019-07-22 at 00 16 27" src="https://user-images.githubusercontent.com/21025321/61598455-2c0fc600-ac16-11e9-8cb9-dee876e7118c.png">

I think @wplit will have much more input on this than me though (he's a smarter guy in that realm)

**Comment by wplit** [comment]
For this individual problem I flagged, I had it slightly wrong. It would be a quick fix. The only elements that were looking odd in the WP UI weren't being affected by Oxygen.css (even though some styles were being applied there) but the actual thing making it obviously wrong and changing the fonts sizes was just coming from the styles applied by 'global settings > body text' inside Oxygen. The few buttons that were being affected didn't have their own font sizes like the rest do, so were inheriting from body.

So the fix would be replace body {} with .editor-styles-wrapper {} for those global body styles, like you have already done with the global heading styles.

As I mentioned in the other post, this is the way WordPress is recommending & handling it for theme developers. They do it automatically though for themes that are adding support for it, by changing all instances of body to .editor-styles-wrapper for this reason.

From Gutenberg handbook..

<img width="742" alt="Screen Shot 2019-07-22 at 9 50 14 am" src="https://user-images.githubusercontent.com/43051571/61599008-ee3b8d80-ac67-11e9-8e92-688693399fd8.png">

So as hacky as it feels, at least you'd be following suit with many others so there's less likely going to be issues with this method in the future. in terms of any more of the UI breaking that is. I don't think you'd need to touch Oxygen.css though.

**Comment by louisreingold** [comment]
Awesome, thank you.

**Comment by louisreingold** [comment]
Dear Lord... is this really not going to create any CSS specificity problems? 

What about all of our CSS in normalize.css (look in Oxygen.css to see the selectors taken from a typical normalize.css) that isn't prefixed with .editor-styles-wrapper?

**Comment by louisreingold** [comment]
I think we will try this in alpha 3 / beta 1 and see what happens.

**Comment by louisreingold** [comment]
What about the related issue of global heading styles overriding class styles? Any ideas?

**Comment by wplit** [comment]
Apart from prefixing .editor-styles-wrapper to every single rule, I don't know. There's also the problem of some default Gutenberg styling overriding some Oxygen stuff, again due to the CSS specificity.

<img width="1000" alt="Screen Shot 2019-07-22 at 10 47 33 am" src="https://user-images.githubusercontent.com/43051571/61599637-3b226280-ac6e-11e9-889b-28b462c26fd3.png">

Here you can see example of applying a max-width to an image via a single class, but Gutenberg has some default styles that overrides it as a single class isn't specific enough inside the editor.

**Comment by KittenCodes** [comment]
@wplit The CSS issues highlighted in your screenshot are fixed in 3.0 Beta 1.
