### ISSUE TITLE
(3.0 ALPHA 1)

### ISSUE THREAD

**Issue by BrunoPirard** [soflyy/oxygen-bugs-and-features#386]
Clean install WP5.2.2, Oxygen 3 (1st release), Oxygen WooCommerce and WooCommerce 3.6.5.
BUG
I can't add a normal new WP page or edit another (shop page, politic of confidentiality)

another site (test in local with a Woo site made with Oxygen 2.4)
I see a lot of error with SVG with 3.0 
I can make a shop layout but impossible to edit it later

Thank you for all the efforts

**Comment by Deanphillips** [comment]
Did you try cleared the cache?

**Comment by KittenCodes** [comment]
Hey @BrunoPirard,

> I can't add a normal new WP page or edit another (shop page, politic of confidentiality)

Please can you let me know what happens when you try to add or edit a page? Can you replicate the issues on the [Sandbox site here](http://successful-butterfly.w6.wpsandbox.pro?upass=Ok9Y1G3ww4qL)?

**Comment by louisreingold** [comment]
Just submit a support ticket - there are zero steps here that anyone could follow to reproduce any issues and zero indication that they will ever be provided.
