### ISSUE TITLE
Header and Footer Are Inverted 

### ISSUE THREAD

**Issue by ziogio98** [soflyy/oxygen-bugs-and-features#387]
**Describe the bug**
*A clear and concise description of what the bug is.*

When i insert Header and Footer in a template (from the library), they appear inverted. 

Let's say the structure displays:

+ Header
+ Footer

The preview will display

+Footer
+Header

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
*Yes/No*

Yes

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
*If yes, provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*

No, it gave me an error when I tried to install oxy 3.0

I made a video, though: https://www.loom.com/share/57996d8264dd479cbf46c973c38878e3

**Expected behavior**
*A clear and concise description of what you expected to happen.*

The Header + Footer should display as by the structure order.

**Desktop (please complete the following information):**
- OS: Windows
 - Browser chrome 
 - Oxygen Version 3.0 ALPHA + Woocommerce ALPHA

**Comment by Deanphillips** [comment]
With the sandbox did you delete 2.4 first before uploading 3.0?

**Comment by ziogio98** [comment]
Yes :)

Il gio 11 lug 2019, 02:53 Deanphillips <notifications@github.com> ha
scritto:

**Comment by KittenCodes** [comment]
@ziogio98 Are you able to replicate this on our Sandbox site at: https://oxygenbuilder.com/try/? If you can, please send me the URL of the Sandbox so that I can take a look.
