### ISSUE TITLE
(3.0 Alpha) - Gutenburg Block Builder - Can't edit content easily

### ISSUE THREAD

**Issue by Deanphillips** [soflyy/oxygen-bugs-and-features#388]
I know Louis said you can't make the back end fully match the front, which is totally cool (I'm used to Block Lab not matching at all) but I can't seem to change my text as it's black on the black background:

https://www.loom.com/share/4ba15b23c5dd419fa39136ee3c310c08

**Comment by Deanphillips** [comment]
Turns out this exists on blocks that don't have a black background too 
<img width="1029" alt="Screenshot 2019-07-11 at 00 41 58" src="https://user-images.githubusercontent.com/21025321/61012118-0dd3db80-a375-11e9-8833-e7ef03500376.png">
![Uploading Screenshot 2019-07-11 at 00.42.15.png…]()

**Comment by Deanphillips** [comment]
<img width="933" alt="Screenshot 2019-07-11 at 00 42 15" src="https://user-images.githubusercontent.com/21025321/61013543-f697ec80-a37a-11e9-9ba5-11e1321070bc.png">

**Comment by KittenCodes** [comment]
Hey @Deanphillips,

I haven't been able to replicate this issue. Please can you replicate it on the [Sandbox site here](http://average-elephant.w6.wpsandbox.pro?upass=2VOr06peq6ME) and send me a link to the page?

**Comment by Deanphillips** [comment]
> Hey @Deanphillips,
> 
> I haven't been able to replicate this issue. Please can you replicate it on the [Sandbox site here](http://average-elephant.w6.wpsandbox.pro?upass=2VOr06peq6ME) and send me a link to the page?

I can't it says this every time:

 Parse error: syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) in /var/www/public/sore-yak/wp-content/plugins/oxygen/component-framework/api/wrapper/OxyEl.php on line 38

**Comment by Deanphillips** [comment]
@KittenCodes Replicated http://average-elephant.w6.wpsandbox.pro/wp-admin/post.php?post=21&action=edit

<img width="1440" alt="Screenshot 2019-07-14 at 02 14 20" src="https://user-images.githubusercontent.com/21025321/61178075-2cd4a680-a5dd-11e9-9c9e-45eac098ee2e.png">

**Comment by KittenCodes** [comment]
That's great, thanks @Deanphillips. The issue only seems present if the block contains an element with Animate on Scroll enabled. I'll open a bug report for this.

**Comment by KittenCodes** [comment]
This is fixed in the latest version of Oxygen and our WooCommerce add-on.
