### ISSUE TITLE
(3.0 Alpha 1) - Body text changed

### ISSUE THREAD

**Issue by Deanphillips** [soflyy/oxygen-bugs-and-features#389]
It seems that the body text is being changed

https://www.loom.com/share/8e997746a358481985056f933d3686ca

This is affecting all sizing site wide for me because this has been applied:

body:not(.wp-admin) {
  font-size: 16px;
    color: rgba(64, 64, 64, 1);
}

**Comment by KittenCodes** [comment]
Hey @Deanphillips, this is fixed in 3.0 Beta 1.
