### ISSUE TITLE
CAPTION

### ISSUE THREAD

**Issue by linformatique** [soflyy/oxygen-bugs-and-features#39]
Add «Title, Description and Alt Text» option to the gallery Caption with user choice of line 1, line 2 or line 3

Example ;
                         Upper line = Title                 OR   Caption
                         Middle line = Caption          OR   Description
                         Lower line = Description      OR   Title

And please make it possible to edit the Typography of the text on the gallery as well as individual image.

**Comment by KittenCodes** [comment]
See https://github.com/soflyy/oxygen-bugs-and-features/issues/90
