### ISSUE TITLE
Woocommerce - Setting price font and size style only increase the price container size

### ISSUE THREAD

**Issue by greenyboy** [soflyy/oxygen-bugs-and-features#390]
**Describe the bug**
Added a woocommerce Price element to a column. Setting the font style, colour or size only changes the height of the price container and not the text size. The style and colour values have no effect at all

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
Yes

This was done in Chrome using the Oxygen 3 Alpha 1, Woocommerce extension and Wordpress 5.2.2

**Comment by KittenCodes** [comment]
This is fixed in the latest version of Oxygen and our WooCommerce add-on.
