### ISSUE TITLE
(3.0 Alpha) - Product Images Repeated

### ISSUE THREAD

**Issue by greenyboy** [soflyy/oxygen-bugs-and-features#391]
**Describe the bug**
Create a columns element (2 columns) in a section and in the left column added a woocommerce product image. Looks OK. If the product image has several images associated with it, the thumbnail row of these images start to be replicated in the builder (when viewing outside the builder, they look OK)

Using Chrome, Wordpress 5.2.2, Oxygen 3.0 alpha and woocommerce extension 1 alpha

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
*If yes, provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*
No a can't install 3.0 alpha 1

**Screenshots**
![image](https://user-images.githubusercontent.com/4695866/60992795-1f9d8a80-a345-11e9-9c75-e767c6704edc.png)

**Comment by KittenCodes** [comment]
This is fixed in the latest version of Oxygen and our WooCommerce add-on.
