### ISSUE TITLE
Rename 'Oxygen Blocks' in Gutenberg

### ISSUE THREAD

**Issue by wplit** [soflyy/oxygen-bugs-and-features#392]
**Describe the feature you'd like to see included in Oxygen.**
To be able to rename the Oxygen part to a custom name.

**What are the use cases for this feature?**
If the purpose is to hide Oxygen from clients and give them default WP, then the name 'Oxygen blocks' isn't meaningful. Instead being able to rename, or even seperate into categories would be more useful.

**Comment by Deanphillips** [comment]
Categories would be great. Designing blocks for certain things for clients would be great. Personally, I'll mainly be using this to build blocks for my block posts and this would still be handy for that too

**Comment by gitsimhub** [comment]
absolutely right. renaming it is a must.

**Comment by adrien-robert** [comment]
+1

**Comment by adrien-robert** [comment]
We have this feature in Oxygen 3.0

![image](https://user-images.githubusercontent.com/4320990/64220262-050d0b00-cec9-11e9-922a-ae408fa949bd.png)
