### ISSUE TITLE
Pages template (from tutorial Templating>Overview 5:17) not inheriting  content from the Main template

### ISSUE THREAD

**Issue by thebioguy** [soflyy/oxygen-bugs-and-features#395]
**Describe the bug**
*While following the tutorial Templating>Overview, the Pages template is not inheriting the Main template content in 2.4. Roll back to 2.3 fixes the problem.*

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
*Yes*

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
*No. It works in sandbox.  http://jittery-bee.w5.wpsandbox.pro/?ct_template=pages&ct_builder=true&ct_inner=true

**To Reproduce**
1. Install Oxygen 2.4, blank install
2. Follow tutorial Templating>Overview as described
3. Main template is not inherited to Pages template (section starts at 5:17)

**Expected behavior**
*The Pages template should inherit the Header, Inner Content, Footer from the Main template*

**What actually happens**
*Only the Inner Content is inherited, but nothing is actually visible except in the Structure tree*

**Screenshots**
*
![Screen Shot 2019-07-11 at 09 16 25 AM](https://user-images.githubusercontent.com/19596016/61059531-22d95a80-a3c7-11e9-857c-950886132c81.png)
*

**Desktop (please complete the following information):**
- OS: Mac 10.14.5
 - Browser Firefox
 - Oxygen Version 2.4 RC1, 2.4 RC2 and 2.4 final

**Smartphone (please complete the following information):**
 - Oxygen Version [e.g. 2.2 Alpha]

**Additional context**
*Add any other context about the problem here.*

**Comment by Spellhammer** [comment]
I'm unable to replicate this. Please send admin login credentials for a site that we can see the issue on to support@oxygenbuilder.com and we'll investigate.

**Comment by thebioguy** [comment]
It's on a local development server.
I will have to create a temp url for you to get access.

**Comment by thebioguy** [comment]
I sent the login and pw through email.

**Comment by thebioguy** [comment]
I noticed that Louis closed this, but another user on FB reported the same
issue.

**Comment by louisreingold** [comment]
The steps you provided did not reproduce the bug. If you want to provide steps to reproduce the issue, the issue will be re-opened and investigated.

**Comment by louisreingold** [comment]
If you have an open support ticket, we always investigate that - regardless of whether it's actually a bug or not.

**Comment by thebioguy** [comment]
Hi,

I provided a test site with login and password. The bug is sitting right
there.

The steps are as described in the video. Exactly. The issue is reproducible
on 2 browsers, across 2 computers (PC and Mac), on both a local build and
my Digital Ocean server.

The only difference between my setup and the video is, I am NOT using
sandbox. On sandbox, I can not reproduce the bug.

Paul


Web design, development and SEO for individuals and businesses.
Visit www.SpinIdeas.com for more info.

**Comment by thebioguy** [comment]
> If you have an open support ticket, we always investigate that - regardless of whether it's actually a bug or not.

Is this still an open ticket? I saw in a message above that it was closed.

**Comment by louisreingold** [comment]
This is a bug tracking system. For support, email support@oxygenbuilder.com.

**All further comments on this issue will be ignored.**

**Comment by thebioguy** [comment]
Hi Louis,

Here's a video showing the bug.
I follow the Templating/Overview video step by step up to the 5:17 mark
when the bug appears.
Easily reproducible.
https://drive.google.com/file/d/15xhBANptm6Gk3botfqJu5w13As8EtBbV/view?usp=sharing

Regards,
Paul
Web design, development and SEO for individuals and businesses.
Visit www.SpinIdeas.com for more info.

**Comment by thebioguy** [comment]
Hi Elijah,

Here's how you replicate this.
https://drive.google.com/file/d/15xhBANptm6Gk3botfqJu5w13As8EtBbV/view?usp=sharing

Exactly like I described.

Paul

Web design, development and SEO for individuals and businesses.
Visit www.SpinIdeas.com for more info.
