### ISSUE TITLE
Add a Colour Picker.

### ISSUE THREAD

**Issue by HenkDz** [soflyy/oxygen-bugs-and-features#399]
When designing and matching colours you might want to pick a colour from an image. A colour picker would make a great addition for the colour choices in Oxygen.

**Comment by wplit** [comment]
There are browser extensions such as Color Pick Eyedropper that allow you to do this while working in Oxygen. You can copy and paste into Oxygen pretty easily all within the same window.

**Comment by louisreingold** [comment]
This is the job of a browser extension, not Oxygen. I highly doubt it is even possible to write a JavaScript color eyedropper that can run in a browser but also read pixel color values from other web pages or applications. Browser security would never permit it.
