### ISSUE TITLE
3.0 Alpha 1 - When using 'Product Images' the main product image and its thumbnails is not displayed properly.

### ISSUE THREAD

**Issue by alexandrudinu** [soflyy/oxygen-bugs-and-features#401]
**Describe the bug**
When using 'Product Images' the main product image and its thumbnails is not displayed properly.

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
*No*
_(I am just testing the new 3.0 Alpha 1)_

**To Reproduce**
1. Go to 'Dashboard > Oxygen > Templates'
2. Click on 'Add new'
3. Create a new template for single product page
4. Add new section
5. Add two columns
6. Add a new 'Product Images' element in the left column

**Expected behavior**
I expect to see a clear and nice image gallery of the product.

**What actually happens**
I see a messy one not properly displayed.

**Screenshots**
Observe how the main image is inside a grey border with space on top and left.
Also the thumbnails of the other images are on top of this border.

**Desktop (please complete the following information):**
- OS: macOS Mojave 10.14.5
 - Browser: Google Chrome Version 75.0.3770.100 (Official Build) (64-bit)
 - Oxygen Version [3.0 Alpha 1]

**Additional context**
I am testing this after I imported the hosting template, not in a blank installation.

<img width="1807" alt="Screenshot 2019-07-13 at 01 45 33" src="https://user-images.githubusercontent.com/28765264/61163748-7b683f00-a510-11e9-9734-9469af2a5817.png">

![Screenshot_2019-07-13 Oxygen Visual Editor - Single Product - Oxygen Shop](https://user-images.githubusercontent.com/28765264/61163669-dc434780-a50f-11e9-8fde-54e53752fae3.png)

**Comment by KittenCodes** [comment]
Hey @alexandrudinu, Please add the Product Images to the Product Builder element. You should then find they display correctly. Please also update to v3.0 Beta 2.
