### ISSUE TITLE
(3.0 Alpha 1) Oxygen changes editor page widths on all posts

### ISSUE THREAD

**Issue by wplit** [soflyy/oxygen-bugs-and-features#404]
**Describe the bug**
Oxygen changes the editor width to nearly full width to allow for the sections from Oxygen to be added. The problem is, this effects all blocks in posts & pages across the site & breaks the editor layout on existing posts that were using thin layout and have some images that are using the wide layout for eg.

**How normal post in editor should look;**

<img width=400 src="https://user-images.githubusercontent.com/43051571/61181809-66a1bd80-a66e-11e9-9cb4-c8afdfce539d.jpg">
<img width=400 src="https://user-images.githubusercontent.com/43051571/61181810-66a1bd80-a66e-11e9-8d73-ed06005a019b.jpg">

**Alpha having full width;**

<img width=400 src="https://user-images.githubusercontent.com/43051571/61181824-98b31f80-a66e-11e9-8370-190186bdc66c.jpg">

If the Oxygen blocks made use of the full alignment settings in Gutenberg, like the images do above, then the max width for the rest of the layout wouldn't need to be touched.

**Comment by wplit** [comment]
**ideal would look like this;** 

<img width="400" alt="Screen Shot 2019-07-14 at 7 50 54 pm" src="https://user-images.githubusercontent.com/43051571/61181996-d5801600-a670-11e9-8f2c-beeaefd0af12.png">

Oxygen blocks only set to full width, not the whole editor.

**Comment by KittenCodes** [comment]
@wplit Please could you replicate this on the Sandbox site here: http://alive-plover.w5.wpsandbox.pro?upass=gp3X8s73NDQj ?

**Comment by louisreingold** [comment]
@KittenCodes create a post in Gutenberg with Oxygen de-activated. Then activate Oxygen and you'll see the title and all Gutenberg blocks go full width.

**Comment by KittenCodes** [comment]
This is fixed in the latest version of Oxygen and our Gutenberg add-on.
