### ISSUE TITLE
Repeater - Making link breaks layout

### ISSUE THREAD

**Issue by Deanphillips** [soflyy/oxygen-bugs-and-features#405]
**Describe the bug**

When you make a repeater have a link wrapper it breaks the layout completely (in the live state) 

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
*If yes, provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*

https://www.loom.com/share/a7684cc75f4c46cc9c2a6f3dabba1590
http://average-elephant.w6.wpsandbox.pro/blog-loop/

**Comment by Deanphillips** [comment]
Still exists in V3
<img width="703" alt="Screenshot 2019-07-20 at 16 50 27" src="https://user-images.githubusercontent.com/21025321/61580887-db617580-ab0e-11e9-8a47-d4cb200ed3d4.png">
<img width="810" alt="Screenshot 2019-07-20 at 16 50 30" src="https://user-images.githubusercontent.com/21025321/61580888-dbfa0c00-ab0e-11e9-99ec-0d889845de2f.png">

A2

**Comment by Spellhammer** [comment]
Fixed in 3.1 Alpha 1 by removing the ability to make the Repeater Div a link wrapper.
