### ISSUE TITLE
Repeater - wordpress elements become just text

### ISSUE THREAD

**Issue by Deanphillips** [soflyy/oxygen-bugs-and-features#406]
When using the dynamic elements inside of the O2 widget area, they become text. This is fine but means we always need to use the "add data" field in the top toolbar

https://www.loom.com/share/2762bf5f6bff4bc7bdcd426394079450

**Comment by alpabuz** [comment]
Yes, it really doesn’t work.

**Comment by KittenCodes** [comment]
This is fixed in the latest version of Oxygen.
