### ISSUE TITLE
Repeater - Let us use classes 

### ISSUE THREAD

**Issue by Deanphillips** [soflyy/oxygen-bugs-and-features#407]
Right now we aren't able to use classes we've created on elements inside of the repeater. Not sure if this is a bug or a feature request.

**Comment by wplit** [comment]
What do you mean? What couldn't you add a class to? I'm able to add classes to all elements inside the repeater.

**Comment by Deanphillips** [comment]
Yep, you're right! Seems to work now (wasn't when I first created a loop) - I'll close this now @wplit  :)
