### ISSUE TITLE
Oxygen.3.0.alpha1 section error

### ISSUE THREAD

**Issue by vincenzo-72** [soflyy/oxygen-bugs-and-features#408]
1) When adding a section it creates an incorrect css, the w3c validator says this:
Error: CSS: background-image: auto is not a background-image value.
Even if no background image is added.

2) When you add any item and assign the tag, it goes to the top position.

3) When I enter text and double-click to change it, the top toolbar often disappears and no other elements can be saved or added.

**Comment by KittenCodes** [comment]
Hey @vincenzo-72,

> When you add any item and assign the tag, it goes to the top position.

Please can you explain what you mean by "assign the tag"?

> When I enter text and double-click to change it, the top toolbar often disappears and no other elements can be saved or added

Please could I have a screencast of this happening? I'm not able to replicate it on my Sandbox site.

**Comment by vincenzo-72** [comment]
For the text I can't supply nussun screencasts now because today it didn't give me any problem.

Here is a screencast about the sections:
The black section is below but when I change the tag it moves over.

![error-section](https://user-images.githubusercontent.com/52895065/61331069-6eee2a00-a821-11e9-9b32-bbac31b424f7.jpg)

**Comment by KittenCodes** [comment]
> The black section is below but when I change the tag it moves over.

This is fixed in 3.0 Alpha 2.
