### ISSUE TITLE
CSS incorrect for current menu items

### ISSUE THREAD

**Issue by wplit** [soflyy/oxygen-bugs-and-features#409]
**Describe the bug**

When we style the current active menu item from the settings panel, the following CSS is added to style those links `#_nav_menu-8-13 .current-menu-item  a { color: red; }`

This CSS fails in two situations;

1. When the top level menu item is for the current page, it causes all the sub menu links to also incorrectly inherit them active styles. (due to it using `.current-menu-item  a` and not `.current-menu-item >  a`)

2. If the current page's menu item is inside a sub menu, but we've already styled the sub menu items separately (from the drop down settings) then the active menu items CSS isn't applied as it's overridden by the sub menu CSS being more specific.

eg.. here the sub menu item should be having the color #a82525 due to it having the link to the current page, but the general drop down styles from Oxygen are overriding it. So we are unable to use current-menu-item styling in sub menus.

<img width="412" alt="Screen Shot 2019-07-15 at 10 38 45 am" src="https://user-images.githubusercontent.com/43051571/61191351-ca6acb80-a6ec-11e9-96cb-b5dc656ae166.png">

**Comment by KittenCodes** [comment]
@wplit I'm having problems replicating this. If you're still running into the issue, please replicate it on a Sandbox site and send us the URL: https://oxygenbuilder.com/try/.
