### ISSUE TITLE
Oxygen 3.0 Alpha 1

### ISSUE THREAD

**Issue by rfazille** [soflyy/oxygen-bugs-and-features#411]
**Describe the bug**
I can't install the 3.0 Alpha 1.
I have this error : Parse error: syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) in /home/monsieurmk/Sitebacasable/wp-content/plugins/oxygen/component-framework/api/wrapper/OxyEl.php on line 38

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
*Yes/No*

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
*If yes, provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*

**To Reproduce**

**Expected behavior**
*A clear and concise description of what you expected to happen.*

**What actually happens**
*A clear and concise description of what happens instead of the expected behavior.*

**Screenshots**
*If applicable, add screenshots to help explain your problem.*

**Desktop (please complete the following information):**
 - Oxygen Version [e.g. 2.2 Alpha]

**Smartphone (please complete the following information):**
 - Oxygen Version [e.g. 2.2 Alpha]

**Additional context**
*Add any other context about the problem here.*

**Comment by KittenCodes** [comment]
Hi @rfazille,

> Parse error: syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) in /home/monsieurmk/Sitebacasable/wp-content/plugins/oxygen/component-framework/api/wrapper/OxyEl.php on line 38

Please upgrade to PHP 7.0 or greater. You should then be able to activate Oxygen.

**Comment by louisreingold** [comment]
For clarity, this will be fixed in alpha 2 and Oxygen will continue to work with PHP 5.6 and up.
