### ISSUE TITLE
Borders not showing "all" styles

### ISSUE THREAD

**Issue by Jamie-owens** [soflyy/oxygen-bugs-and-features#413]
**Describe the bug**
When applying a border style to a section and then going back to change it, I am unable to change the border from the all selection as its blank. I would have to manually change the border for Top, Right, Bottom and Left

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
Yes

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
http://fancy-anaconda.w6.wpsandbox.pro/wp-admin/index.php

**To Reproduce**
1. Open the page I have created called "page".
2. Open the border options of the section I have created.
3. Try to change the border style while "Currently Editing" = "all".

**Expected behavior**
I would expect the border to be shown for "all" and not blank as it currently is. I should be able to change the border for all sides rather than individually for Top, Right, Bottom and Left.

**What actually happens**
Upon checking the border options for the section, the border for "all" is blank but is shown for Top, Right, Bottom and Left.

**Screenshots**
![border](https://user-images.githubusercontent.com/47915613/61236620-58b47100-a730-11e9-9bb8-2a3f7e0648cb.png)

**Desktop (please complete the following information):**
- OS: Windows 10
 - Browser: Chrome
 - Oxygen Version: 2.3

**Comment by adrien-robert** [comment]
+1

**Comment by Martin-1** [comment]
+1 as well

**Comment by alpabuz** [comment]
+1

**Comment by fmommeja** [comment]
+1

**Comment by shock2d** [comment]
same here

**Comment by KittenCodes** [comment]
This is the intended behaviour. Please see the video on the Borders element here: https://oxygenbuilder.com/documentation/styling-options/borders/.

If you would like to see different behaviour, please open a feature request: https://github.com/soflyy/oxygen-bugs-and-features.
