### ISSUE TITLE
(3.0 Alpha 1) - Woo Commerce Columns Display and Breakpoints

### ISSUE THREAD

**Issue by bluefish1960** [soflyy/oxygen-bugs-and-features#416]
**Describe the bug**
In woocommerce templates, I cannot organise my shop layout in columns the way I expect to. I choose categories list and the columns quantity, it displays wrongly on back and front ends. The block is not centered either.
Please see inline images below. 4 cols, 5 cols and 6 cols respectively---

In addition, I cannot select different columns quantities for screen sizes. If I choose 4 colums then it is 4 columns on all devices , no matter what I select at different breakpoints.

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
Yes

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
*If yes, provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*

NO - when I tried to replicate it a couple of days back there was no way to install 3.0 alpha because of an error - I believe this is now corrected but do not have time to try and replicate it now.

**To Reproduce**
1. Go to '.create new template for woo commerce shop page'
2. Click on add section, I set the section centered and child elements stacking vertically. Add a div and then...
3.Then scroll down to 'categories list' and add to div.
4. Try to change columns quantity. Save and check front end - images of mine below
5. Then try to make smaller screen sizes have different columns and save - it does not work. All screen sizes have same columns.

**Expected behavior**
I expect to see columns of 1, 2, 3, 4, 5 or whatever I choose in whichever breakpoint I select

**What actually happens**
Instead I get a mixture of columns as shown in the images below.
**Screenshots**
*If applicable, add screenshots to help explain your problem.*
![4cols](https://user-images.githubusercontent.com/25553194/61284339-aa074380-a7b6-11e9-8580-c3092da9e07b.jpg)
![5cols](https://user-images.githubusercontent.com/25553194/61284346-aecbf780-a7b6-11e9-8ce9-7b0c9446f499.jpg)
![6cols](https://user-images.githubusercontent.com/25553194/61284351-b095bb00-a7b6-11e9-86ba-519b5d4b0dcc.jpg)

**Desktop (please complete the following information):**
- OS:  Windows 10
 - Browser  Chrome
 - Oxygen Version 3.0 Alpha 1

**Smartphone (please complete the following information):**
N/A still in production on localhost - tested in Chrome by reducing browser window size

**Additional context**
None

**Comment by Deanphillips** [comment]
Can you please add a title to this. 3.0 Alpha 1 isn't helpful at all and makes it harder for us to all know what you're talking about. Thanks man.

**Comment by KittenCodes** [comment]
This is fixed in the latest version of Oxygen and our WooCommerce add-on.
