### ISSUE TITLE
DONE: Add support for key=>value style manual query in Easy Posts

### ISSUE THREAD

**Issue by srikat** [soflyy/oxygen-bugs-and-features#419]
At the moment, manual query can be written in Easy Posts element using query string method.

This method is not flexible enough for many use-cases where the query parameter values need to be dynamic i.e., to a variable or function return value.

As an example, consider the scenario where one would like to show posts that belong to the same category as the current post on a single post page while excluding the current post.

Here's the query part for this:

```
$categories = get_the_category();

// WP_Query arguments
$args = array(
	'post_type' => array( 'post' ),
	'posts_per_page' => '4',
	'cat'	=> $categories[0]->term_id,
	'post__not_in'	=> array( get_the_ID() ),
);
```

It is not possible to input this as a query string because the value of cat has to be set to a dynamic value: $categories[0]->term_id.

There are [several](https://www.facebook.com/groups/1626639680763454/permalink/1956164737810945/) [other](https://www.facebook.com/groups/1626639680763454/permalink/1956172754476810/) such cases where this limitation prevents us from using the rest of the features of Easy Posts.

Therefore, we request you to kindly add support for key-value style array in the manual query.

(originally requested [here](https://oxygenbuilder.com/forums/topic/add-support-for-key-value-style-manual-query-in-easy-posts/) in the forum where more use cases and votes can be seen)

**Comment by wplit** [comment]
This is also needed for the new loop builder, the Query settings are the same as the Easy Posts.

**Comment by alpabuz** [comment]
Good idea!

**Comment by adrien-robert** [comment]
Totally agree, Oxygen is the best site builder for WordPress in term of flexibility and the things you can do with it.
this feature will widen the gap with other builders for sure.
Must have!

**Comment by demetre19** [comment]
What they said +1

**Comment by Deanphillips** [comment]
Totally agree. Definitely needed.

**Comment by wkoehn** [comment]
+1

**Comment by sunnyt7** [comment]
Would really like to see this. Would make creating related posts or magazine sites a lot easier.

**Comment by mightyfree** [comment]
Agreed, online publications need support for dynamic queries via arguments and arrays.

**Comment by cinghaman** [comment]
Any movement on this from oxygen team?

**Comment by pablodesign** [comment]
I think this will help a lot

**Comment by vladmartinus** [comment]
+1

**Comment by mikejcsmith** [comment]
I would like to pass Easy Posts / Repeater a general array.  This would allow me to display posts / custom posts from another sub-blog in a multi-site, and also to use the Repeater for truly custom query results.

**Comment by shoelaced** [comment]
Same for Repeater.

**Comment by GianDS** [comment]
+1

**Comment by little-gatsby** [comment]
+1

**Comment by oskar931** [comment]
+1

**Comment by williammei** [comment]
+1

**Comment by tmz1970** [comment]
+1

**Comment by membus** [comment]
+1

**Comment by Eloise-Antoinette** [comment]
+1 for Repeater

**Comment by mindingear** [comment]
+1 Yes, please!

**Comment by Nathaniel-Fernandes** [comment]
+1

**Comment by binaryfire** [comment]
+1 Was just looking for a way to do this!

**Comment by Spellhammer** [comment]
The Advanced Query option satisfies this need.
