### ISSUE TITLE
Open modal function

### ISSUE THREAD

**Issue by alpabuz** [soflyy/oxygen-bugs-and-features#422]
Now we have a global function oxyCloseModal(). But we don't have the function to open modal.

There are many cases where this can be applied and it has been repeatedly asked in the Facebook group.

**Comment by louisreingold** [comment]
> it has been repeatedly asked in the Facebook group.

Thanks for asking here - the place where we actually notice and can do something about it. ;)

**Comment by adrien-robert** [comment]
+1 for this feature request, would love to get a closing "animation on scroll" for modal too, to reverse the one we choose to open the modal :)

**Comment by tmykhaylovsky** [comment]
+1 for this feature - instead of displaying gravity form submission text, I would like to open a better styled modal. Thank you

**Comment by hawkmusician** [comment]
+1 Really needed

**Comment by jcmatoskx** [comment]
+1

**Comment by adatfalo** [comment]
+1

**Comment by PaperjetStudios** [comment]
+1

**Comment by ZebulanStanphill** [comment]
I'm currently working on a project where I'm using a Repeater to generate a list of cards, each including a button to open a modal filled with dynamic data. Unfortunately, since the trigger element selector field is static, there seems to be no way to make this work without opening all modals at once. I tried using JS to modify the `data-trigger-selector` on the modal element, but that doesn't seem to have any effect. If there was an open-modal function of some sort, it would make what I'm trying to do a lot easier.

(For my particular use-case, an alternative approach would be something like #1498.)

**Comment by StoneCotton** [comment]
> I'm currently working on a project where I'm using a Repeater to generate a list of cards, each including a button to open a modal filled with dynamic data. Unfortunately, since the trigger element selector field is static, there seems to be no way to make this work without opening all modals at once. I tried using JS to modify the `data-trigger-selector` on the modal element, but that doesn't seem to have any effect. If there was an open-modal function of some sort, it would make what I'm trying to do a lot easier.
> 
> (For my particular use-case, an alternative approach would be something like #1498.)

I'm running into this exact problem and came here to see if anyone else has had this niche use case. Did you ever find a workaround so only one modal would open depending on the trigger?

**Comment by ZebulanStanphill** [comment]
@StoneCotton 
> Did you ever find a workaround so only one modal would open depending on the trigger?

Unfortunately, no.

The only solution I could find was to use completely from-scratch custom modals built using Code Block elements. However, this proved to be rather complicated (and not very friendly to update later on unless you were a coder), and so ultimately, we decided to give up on using modals and redesigned the page to not use them.

**Comment by adrien-robert** [comment]
Can we have update on this please? @KittenCodes 

Would be handy to have a javascript function to open a modal

**Comment by Spellhammer** [comment]
In 4.0 Beta 2 we exposed the show modal function for use in external code. Here's an example of how you can use it:

https://gist.github.com/Spellhammer/5ee15003eaccb96998a8eb2795d0c814

**Comment by harryfear** [comment]
Elijah gave us an Easter gift 🥚

**Comment by jkarelbroer** [comment]
@Spellhammer Will this work in Oxy 3.9?

**Comment by bardolf69** [comment]
So has this been implemented?  I have Oxygen builder 4.0.3 but oxyShowModal() doesn't appear to be defined.

**Comment by bardolf69** [comment]
ok, I can see the code in modal.class.php so it has been implemented so why is my javascript throwing

Uncaught ReferenceError: oxyShowModal is not defined
