### ISSUE TITLE
[3 Alpha 1 - Repeater] - Conditions In-Editor Behaviour Doesn't Work

### ISSUE THREAD

**Issue by Deanphillips** [soflyy/oxygen-bugs-and-features#423]
When conditions are set you can't test always show, always hide or show/hide. Conditions do however work on the front end, but it's hard to test things :)

I've tested this on a sandbox too:
http://average-elephant.w6.wpsandbox.pro/testing-conditions-in-builder/

**Comment by KittenCodes** [comment]
This is fixed in the latest version of Oxygen.
