### ISSUE TITLE
oxygen-toolset.php error on line 64

### ISSUE THREAD

**Issue by qriouslad** [soflyy/oxygen-bugs-and-features#424]
**Describe the bug**
Oxygen & Toolset integration bug occurring when starting to use a toolset-generated custom field. Error message in Oxygen Builder preview section.

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
No

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
Not tried.

**To Reproduce**
1. Install Toolset Types
2. Create a dropdown custom field attached to pages
3. Create a code snippet utilizing the custom field in if statement, via the Code Snippets plugin. Snippet is turned into a shortcode to use via Oxygen
4. Open a reusable part containing the shortcode with one argument
5. This error shows up on top of the OxygenBuilder content preview area: "Warning: Invalid argument supplied for foreach() in C:\laragon\www\astrologytv\wp-content\plugins\oxygen\component-framework\includes\toolset\oxygen-toolset.php on line 64"
6. I can still work with the template and save changes, but the error message is still displayed on top.

**Expected behavior**
No error message if editing and saving works.

**What actually happens**
Error message stays visible on top.

**Screenshots**
![oxygen_toolset_error](https://user-images.githubusercontent.com/4230816/61514018-1a1d0000-aa29-11e9-9150-a7853fc130c0.jpg)

**Desktop (please complete the following information):**
- OS: Windows 10 Pro
 - Browser: Latest Chrome
 - Oxygen Version: 2.4

**Additional context**
I'm only starting to see this error once I started creating and using a custom field created with Toolset Types.

**Comment by chrishaff** [comment]
It's October 6th, 2020 and I am getting this issue with the latest Oxygen/Toolset plugins. What's happening?

**Comment by KittenCodes** [comment]
@chrishaff This is fixed in Oxygen 3.6 Beta: https://oxygenbuilder.com/2020/09/28/oxygen-3-6-beta-1-now-available/.
