### ISSUE TITLE
CSS issue in Demo Site

### ISSUE THREAD

**Issue by mbnsrwr** [soflyy/oxygen-bugs-and-features#426]
There is a bug in this Demo design site provided by Oxygen [https://marketingagencyb.oxy.host/]
 
Steps: 
1. Play the video in the hero section.
2. Stop video by clicking outside video.
3. The video section disappears from screen but covers the map at the bottom of the page.

**Comment by KittenCodes** [comment]
Reproduced in 2.4.1.

**Comment by KittenCodes** [comment]
This has been fixed in the Marketing Agency design set.
