### ISSUE TITLE
(3.0 Alpha 1) Related products not displaying correct column number

### ISSUE THREAD

**Issue by dposnanski** [soflyy/oxygen-bugs-and-features#427]
**Describe the bug**
When I add a related products section to a single product, it shows one column less per row than it should.

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
No

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
Can't install alpha

**To Reproduce**
1. Create a single product template
2. Add a related products section
3. Choose any number of columns

**Expected behavior**
I expect to see the number of columns I select, evenly distributed in the row.

**What actually happens**
I see one column less per row, and space remaining on the side. The last product is displayed in the next row.

**Screenshots**
![image](https://user-images.githubusercontent.com/22684573/61578274-78fb7b80-aaf4-11e9-9a3d-08c054fa83c4.png)

**Desktop (please complete the following information):**
- OS: Windows 10
 - Browser Chrome Version 75.0.3770.142
 - Oxygen Version 3.0 Alpha 1

**Comment by KittenCodes** [comment]
This is fixed in the latest release of Oxygen and our WooCommerce add-on.
