### ISSUE TITLE
(3.0 Alpha 1) - Product price size does not change

### ISSUE THREAD

**Issue by dposnanski** [soflyy/oxygen-bugs-and-features#428]
**Describe the bug**
When I try to modify the product price size using the Font Size input, the size does not change. If the product has a price range, the font size of the dash does change.

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
No

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
No

**To Reproduce**
1. Create a single product template
2. Add a product builder
3. Add a price to the builder
4. Change the product size size from Color & Typoography > Font Size

**Expected behavior**
I expected the font size of the product price to change.

**What actually happens**
Nothing changes. The font stays the same (except for the dash).

**Screenshots**
*If applicable, add screenshots to help explain your problem.*
![image](https://user-images.githubusercontent.com/22684573/61579245-54f36680-ab03-11e9-8db4-d91c6ef2b548.png)
![image](https://user-images.githubusercontent.com/22684573/61579261-78b6ac80-ab03-11e9-8b3b-3984960d8a1d.png)

**Desktop (please complete the following information):**
- OS: Windows 10
- Browser Chrome Version 75.0.3770.142
- Oxygen Version 3.0 Alpha 1

**Comment by KittenCodes** [comment]
This is fixed in the latest release of Oxygen and the WooCommerce add-on.
