### ISSUE TITLE
3.0 Alpha 2 - Repeater - No Pagination

### ISSUE THREAD

**Issue by stupidcatdesign** [soflyy/oxygen-bugs-and-features#431]
I have more than 300 posts in a CPT and built a simple Repeater. I set the Settings>Reading to show 20 posts. Pagination is not present.

**Comment by Deanphillips** [comment]
I've requested a related feature you might like:

https://github.com/soflyy/oxygen-bugs-and-features/issues/414

**Comment by KittenCodes** [comment]
Hey @stupidcatdesign, repeaters don't yet have pagination. However, one of our users has found a workaround so that you can add pagination: https://www.facebook.com/groups/1626639680763454/permalink/2366327086794706/.

**Comment by stupidcatdesign** [comment]
Ha. I am that user!  That is my workaround.

**Comment by KittenCodes** [comment]
> Ha. I am that user! That is my workaround.

Classic! It's a great workaround!
