### ISSUE TITLE
DONE: Suggested changes to Oxygen breakpoints.

### ISSUE THREAD

**Issue by brianyhearne** [soflyy/oxygen-bugs-and-features#435]
Oxygen uses max-width for its breakpoints. Bootstrap uses min-width.

One of the consequences of this is that designing with the iPad in landscape mode becomes rather difficult as we are relying on the current page-width as set in 'settings' to dictate what will happen when a site is viewed at 1024px wide (iPad landscape)

if the breakpoints were set to min-width this would be easier BUT we would then have to design all the way up to our page-width which these days is typically set around the 1280px mark or thereabouts.

So if the max-width approach is to be kept then I would suggest changing the current 992px to 1024px - problem solved.

Additionally however I would also suggest that the dynamically declared 'first' breakpoint, which is equal to the width we enter in settings, should be the second breakpoint and not the first. The first should be the default one.

This lets us design on large screens, as most developers do, and to then shrink our design down to a more common screen size (say 1366px) and work from there.

**What are the use cases for this feature?**
Better control over designs.

**Examples of this feature or functionality.**
unknown

**Comment by Spellhammer** [comment]
Breakpoints are editable as of Oxygen 3.2 Alpha 1, addressing this feature request.
