### ISSUE TITLE
(3.0 Alpha 2) - Repeater Single Mode CSS Overridden

### ISSUE THREAD

**Issue by wplit** [soflyy/oxygen-bugs-and-features#438]
**Describe the bug**
If the user adds 'display' styles to the first div inside the repeater element via ID, then the single mode no longer works. 

This is because the CSS that is used to hide all repeater elements apart from the first one 

`.oxy-dynamic-list.oxy_list_render_single > div:not(:first-child) {
    display: none;
}`

Will be overridden if an ID is used to, say, add a flex layout to that div.

`#div_block-3-8 {
   display: flex;
}`

**Expected behavior**
Single mode should always remove the other divs from view, regardless of styles added.

**Steps to recreate**
1. Create a repeater element.
2. Loop through some posts.
3. Select the child div inside the repeater element.
4. Add display flex to layout child elements.
5. Go back to repeater element and try to select 'single mode'
6. Notice all elements are still visible as display: none is not being applied.

**Comment by KittenCodes** [comment]
Replicated in 3.0.

**Comment by KittenCodes** [comment]
This is fixed in the latest version of Oxygen.
