### ISSUE TITLE
(3.0 Alpha 2) - Repeater (Single Mode) Element Hidden on First Load

### ISSUE THREAD

**Issue by wplit** [soflyy/oxygen-bugs-and-features#439]
**Describe the bug**
If a repeater is set to single mode. When Oxygen first loads the page, none of the elements in the repeater div are visible.

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
yes - [http://glorious-mosquito.w5.wpsandbox.pro](http://glorious-mosquito.w5.wpsandbox.pro?upass=0de8tnP38LZB)

**To Reproduce**
1. Go to sandbox site above
2. Go to page 'repeater-test' and 'edit with Oxygen'
3. Notice the repeater element isn't visible

The only way to make it visible is to click 'normal mode' then back to 'single mode'

**Expected behavior**
The element should when visible when Oxygen first loads up.

**What actually happens**
The reason is due to the element not receiving the class 'oxy_repeater_original' when Oxygen first loads up, so the CSS is hiding it. As seen in screenshot below. Once 'normal mode' is clicked, the class is added and remains there once we go back to single mode.

**Screenshots**

<img width="1400" alt="Screen Shot 2019-07-28 at 11 39 28 am" src="https://user-images.githubusercontent.com/43051571/62001134-82a46500-b12c-11e9-934d-c7edc60ec1c8.png">

**Comment by KittenCodes** [comment]
Replicated in 3.0.

**Comment by KittenCodes** [comment]
This is fixed in the latest version of Oxygen.
