### ISSUE TITLE
Multiple sections wrapper for Gutenberg blocks

### ISSUE THREAD

**Issue by ciaoweb** [soflyy/oxygen-bugs-and-features#440]
I was wondering that it can be very convenient to have in Oxygen  a wrapper that can include multiple Oxygens sections and be then copied to Gutenberg blocks. 

So instead of the tedious work to copy each section to block library we can have multiple sections copied in a single block that ideally will populate a WordPress page. Eg. About Page block sections, Service page block sections and so on.

**Comment by KittenCodes** [comment]
You can put all of the blocks inside a Div and then copy the Div to a block.
