### ISSUE TITLE
(3.0 Alpha 2) Repeater - Error when converted to a reusable block

### ISSUE THREAD

**Issue by sagararyal** [soflyy/oxygen-bugs-and-features#442]
When a Repeater with ACF Pro content, of a custom post type, is saved as a reusable block, opening the reusable block in Oxygen editor gives an error as below:

<img width="1792" alt="Screen Shot 2019-07-30 at 12 14 20 AM" src="https://user-images.githubusercontent.com/5401575/62086960-4f62f280-b260-11e9-8317-56c49ae2fc15.png">

It seems the repeater is expecting the reusable block to be an archive.

The reusable block however works fine if is embedded in other parts of the site.

CPT has `'has_archive' => true,`

**Comment by KittenCodes** [comment]
Confirmed in 3.0.

**Comment by KittenCodes** [comment]
This is fixed in the latest version of Oxygen.
