### ISSUE TITLE
(3.0 Alpha 2) 404 template returns error while saving

### ISSUE THREAD

**Issue by dposnanski** [soflyy/oxygen-bugs-and-features#448]
**Describe the bug**
When I create a 404 page and I click on save, I get an error message: Error occurred while saving 400 Your server returned a 400 error for the request to /admin-ajax.php. Same happens if I create a general template and then change the template to 404, once I change it, it doesn't save.

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
No

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
Yes, http://itchy-guanaco.w6.wpsandbox.pro/?ct_template=404&ct_builder=true

**To Reproduce**
1. Create a 404 template
2. Add some stuff
4. Save, see error 400

**Expected behavior**
I expect my template to save.

**What actually happens**
Template doesn't save.

**Screenshots**
![image](https://user-images.githubusercontent.com/22684573/62193727-a825ae80-b378-11e9-903d-da2173063a77.png)

**Desktop (please complete the following information):**
- OS: Windows 10
- Browser Chrome Version 75.0.3770.142
- Oxygen Version 3.0 Alpha 2

**Comment by KittenCodes** [comment]
Replicated in 3.0.

**Comment by KittenCodes** [comment]
This is fixed in the latest version of Oxygen.
