### ISSUE TITLE
(3.0 Alpha 2) Product search widget returns valid signature error

### ISSUE THREAD

**Issue by dposnanski** [soflyy/oxygen-bugs-and-features#449]
**Describe the bug**
When I add a product search widget and view the page in the site, the following error is shown: Oxygen Error: Your shortcodes lack a valid signature - most likely because a migration has taken place. Please re-sign your shortcodes inside the WordPress admin panel, at Oxygen > Settings > Security. If I uncheck 'Check Oxygen's shortcodes for a valid signature before executing.' that part of my site works but others break and start showing shortcodes/empty queries instead. When I check the box again the shortcodes/empty queries issues isn't fixed and if I go to the templates in the backend, the content is gone.

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
Yes:
- disabled plugins, no change
- checked error logs (have a bunch of oxygen related errors saying: expects parameter 1 to be string, array given in /wp-content/plugins/oxygen/component-framework/components/component.class.php on line 3537,3541,3545,3549,3529,3533)
- php 7.3
- cleared cache, resaved permalinks
- resigned shortcodes

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
No, I tried but it shows correctly on sandbox install

**Expected behavior**
I expect the product search widget to appear.

**What actually happens**
I get an error message instead.

**Screenshots**
*If applicable, add screenshots to help explain your problem.*
When security box is unchecked
![image](https://user-images.githubusercontent.com/22684573/62199583-099f4a80-b384-11e9-8c21-284cf6db8131.png)

No content where my query results should be when not checking signature
![image](https://user-images.githubusercontent.com/22684573/62202340-68b38e00-b389-11e9-9486-e61cb65f646d.png)

Shortcodes displaying on single product pages
![image](https://user-images.githubusercontent.com/22684573/62202437-94367880-b389-11e9-9c6c-55e78e8062dc.png)

**Desktop (please complete the following information):**
- OS: Windows 10
- Browser Chrome Version 75.0.3770.142
- Oxygen Version 3.0 Alpha 2

**Comment by Spellhammer** [comment]
Since this can't be replicated on a Sandbox site, please send login credentials for a site where we can see the problem to support@oxygenbuilder.com and we'll investigate there.

**Comment by dposnanski** [comment]
Just sent an email with the info. Thanks!
