### ISSUE TITLE
Design Library Thumbnails broken for many assests

### ISSUE THREAD

**Issue by Gibsonion** [soflyy/oxygen-bugs-and-features#45]
**Describe the bug**
A lot of thumbnails in the design library are either missing or display the incorrect image for the assest. For one example of incorrect thumbs choose Financial > content > products

**Have you tried all the steps at **
Yes

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**

Yes, The issue exists in all version of Oxygen 2 I have tested, the design library for freelancer is especially affected with almost half the thumbnails missing.

**To Reproduce**
1. Go to design library
2. Go through the available assets
3. profit!

**Expected behavior**
Show thumbnails and correct ones.

**Screenshots**
http://prntscr.com/mfbi22
http://prntscr.com/mfbi7t
http://prntscr.com/mfbjad
http://prntscr.com/mfbjqb
http://prntscr.com/mfbk3o
http://prntscr.com/mfbkrw
http://prntscr.com/mfbl2c
http://prntscr.com/mfbl7e
http://prntscr.com/mfbldb
http://prntscr.com/mfblib
http://prntscr.com/mfblo2
http://prntscr.com/mfbm1n
http://prntscr.com/mfbm7w
http://prntscr.com/mfbmjw
http://prntscr.com/mfbmrv

There are a lot more.

- Firefox, Chrome
- Windows 7
- All versions of Oxygen 2.0 and above

**Comment by timpixel** [comment]
This may seem like an innocent problem, but I wonder how we should choose/insert  parts without actually seeing them?

**Comment by KittenCodes** [comment]
Most library items should now have screenshots.
