### ISSUE TITLE
Oxygen 3 / WooCommerce - Jittery Zoom on Product Gallery Images

### ISSUE THREAD

**Issue by greenyboy** [soflyy/oxygen-bugs-and-features#453]
**Describe the bug**
Create a template for a Product. Add a product image etc and save. Hovering over the product image zooms in OK. However, if the product has alternative images and you select one of those, the zoom gets very jittery and continues unless you refresh the page. 

**To Reproduce**
1. Create a template for a woocommerce product
2. Add a product Image element with at least 1 alternative image
3. Hover over main image. Then select an alternative image
4. Zoom is very jittery

**Additional context**
*Add any other context about the problem here.*

**Comment by Deanphillips** [comment]
Any chance you could name this something that related to the bug? (makes it easier for others to find) - thanks man

**Comment by KittenCodes** [comment]
Replicated in 3.0.

**Comment by KittenCodes** [comment]
This is fixed in Oxygen 3.1 and v1.1 of our WooCommerce add-on.
