### ISSUE TITLE
Toolset custom post blank page

### ISSUE THREAD

**Issue by babilonia07** [soflyy/oxygen-bugs-and-features#457]
**Describe the bug**
*A clear and concise description of what the bug is.*
I generated the template, but when i set for the toolset custom post, the oxygen have this output:

Failed to load resource: the server responded with a status of 404 () in the css

Also I have the toolset access plugin activate for this post, and the visitor cannot see any of the posts.
If i deactivate the toolset access plugin everytihng start to work without any problem.

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
*Yes*

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
*If yes, provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*
https://magnero.org/recurso/pruebas/

**To Reproduce**
1. Go to 'create template or activate for the custom post'
2. Click on 'new custom post or preview the custom post'
3. See error in front end

**Expected behavior**
*A clear and concise description of what you expected to happen.*
No blank page.

**What actually happens**
*A clear and concise description of what happens instead of the expected behavior.*
A blank page.
**Screenshots**
*If applicable, add screenshots to help explain your problem.*

**Desktop (please complete the following information):**
- OS: [e.g. iOS] Chrome OS (last version) 
 - Browser [e.g. chrome, safari] Chrome 
 - Oxygen Version [e.g. 2.2 Alpha] 2.4 stable

**Smartphone (please complete the following information):**
- Device: [e.g. iPhone6] motorola z2 play-
 - Browser [e.g. stock browser, safari] chrome-firefox
 - Oxygen Version [e.g. 2.2 Alpha] 2.4

**Additional context**
*Add any other context about the problem here.*

**Comment by KittenCodes** [comment]
@babilonia07 If you're still running into this issue in Oxygen 3.1, please replicate the issue on our Sandbox site and send us the login so that we can take a look.

You can create a Sandbox site here: https://oxygenbuilder.com/try/.
