### ISSUE TITLE
(3.0 Beta 1) Template does not display featured image as bg

### ISSUE THREAD

**Issue by Gibsonion** [soflyy/oxygen-bugs-and-features#458]
**Describe the bug**
When creating a template using a featured image bg, it displays correctly in the editor, but on the front end the featured image area is blank.

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
YES

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
http://hilarious-rook.w6.wpsandbox.pro/clients/

http://prntscr.com/on2n2z < In the editor

**To Reproduce**
1. create template
2. add featured image as background to a section
3. view front end

**Expected behavior**
Featured image should display as background

**What actually happens**
featured image does not display as background

**Screenshots**
http://prntscr.com/on2n2z < In the editor
http://prntscr.com/on2o75

Win10
Chrome
2.4.0 - 3.0 beta

**Comment by Spellhammer** [comment]
Replicated and reported internally.

**Comment by marcosmartini** [comment]
For me, this only happens if the Gutenberg plugin is active. If you deactivate Oxygen's Gutenberg plugin it loads properly.

**Comment by Gibsonion** [comment]
Is there any update on this? Have checked in the new 3.1 Beta 1 and this issue still exists

**Comment by alriksson** [comment]
@Spellhammer Do even background images have support for dynamic been waiting for this?
What I know only image src elements have dynamic options.

**Comment by KittenCodes** [comment]
This is fixed in Oxygen 3.1.
