### ISSUE TITLE
Oxygen / Google Kit Incompatibility

### ISSUE THREAD

**Issue by RenaudGagne** [soflyy/oxygen-bugs-and-features#459]
**Describe the bug**
 https://sitekit.withgoogle.com is a very useful plugin that a lot of people are starting to use. Somehow, the plugin works EXCEPT for the authentification of Google Analytics.

For us as an agency this plugin is a huge time saver and the fact that there is a compatibility with a google product is troubling. I opened a ticket on their Github: https://github.com/google/site-kit-wp/issues/373

Basically, the bug is that Google Kit cannot find our Google Analytics when it's searching for it.

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
Yes

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
*If yes, provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*

**To Reproduce**
1. Install Google Kit
2. Authenticate
3. Setup Google Analytics'
4. See that it cannot find GA account

**Expected behavior**
For the plugin to find my GA account

**What actually happens**
A Progress bar that never finds anything

**Screenshots**
![Site Kit by Google Dashboard ‹ Old Growth Media - Videographer _ Photography — WordPress](https://user-images.githubusercontent.com/14856170/62315869-4b9fbd80-b464-11e9-84cb-0150fed956d1.png)

**Desktop (please complete the following information):**
- OS: Windows
 - Browser: Tried all
 - Oxygen Version Lastest

**Additional context**
*Add any other context about the problem here.*
Maybe you have a security part that is preventing it to complete?

**Comment by KittenCodes** [comment]
@RenaudGagne If you disable Oxygen, can the Site Kit plugin find your GA account? I've tried both with and without Oxygen activated and I'm not able to get it to work.
