### ISSUE TITLE
Oxygen 3 Beta 1 - Related products tabs not appearing correctly.

### ISSUE THREAD

**Issue by Malkthealk** [soflyy/oxygen-bugs-and-features#462]
**Describe the bug**
When adding the Woocommerce related products section the tabs appear as normal lists instead of tabs.

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
*Yes/No*

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
*If yes, provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*

**To Reproduce**

**Expected behavior**
*A clear and concise description of what you expected to happen.*

**What actually happens**
*A clear and concise description of what happens instead of the expected behavior.*

**Screenshots**
*If applicable, add screenshots to help explain your problem.*

**Desktop (please complete the following information):**
 - Oxygen Version [e.g. 2.2 Alpha]

**Smartphone (please complete the following information):**
- Device: Tower computer
 - OS: Windows 10
 - Browser Chrome
 - Oxygen Version Oxygen 3 Beta 1

**Additional context**
*Add any other context about the problem here.*

**Comment by KittenCodes** [comment]
@Malkthealk Please can you add a screenshot showing what tabs you're referencing?

**Comment by Malkthealk** [comment]
![woo tabs problem](https://user-images.githubusercontent.com/33354467/62393542-60fb1180-b562-11e9-8942-d4d9c6616fb0.png)

**Comment by Malkthealk** [comment]
I didn't mean to close this

**Comment by KittenCodes** [comment]
@Malkthealk This is likely happening because you're using the Related Products element outside of the Product Builder element.

If that's not the case, please replicate the issue on the Sandbox site here so that I can take a look: http://sincere-monkey.w5.wpsandbox.pro?upass=qkMuO1RU9v90.

**Comment by Malkthealk** [comment]
Thank you for your email, I may have misheard the video, but I thought the Related products was placed out of the Product Builder.  My apologies,

Malky

**Comment by RichiesRiches** [comment]
This is still happening in Beta 2.  I can replicate it for you as I thought I just hosed something up and did a fresh install, and it happened again.

**Comment by jornmo** [comment]
I am getting the same behaviour

**Comment by jornmo** [comment]
> 
> 
> Thank you for your email, I may have misheard the video, but I thought the Related products was placed out of the Product Builder. My apologies,
> 
> Malky

Did not know that. Thanks!
