### ISSUE TITLE
Nested Repeaters Reverts Page When New Item is Added to Post

### ISSUE THREAD

**Issue by vanillaicedlatte** [soflyy/oxygen-bugs-and-features#463]
My situation: I set up Repeater fields for menu items. There are also nested Repeater fields for Add Ons under on those menu items.

Oxygen Beta 3 allowed me to nest Repeaters. And everything was fine and set up like this:

<img width="293" alt="Screen Shot 2019-08-02 at 12 46 38 PM" src="https://user-images.githubusercontent.com/20264271/62389027-5faaf400-b524-11e9-8655-5e78c871b662.png">

<img width="1389" alt="Screen Shot 2019-08-02 at 12 45 28 PM" src="https://user-images.githubusercontent.com/20264271/62389020-5c176d00-b524-11e9-982d-d7616771c358.png">

However, when I go back to the Menu Post to add a new item:
<img width="1403" alt="Screen Shot 2019-08-02 at 12 47 12 PM" src="https://user-images.githubusercontent.com/20264271/62389048-6c2f4c80-b524-11e9-9cea-d5628568cbbb.png">

I hit save, and go to the menu page expecting it to update, but it removes the nested repeater and everything below it.

<img width="1837" alt="Screen Shot 2019-08-02 at 12 47 24 PM" src="https://user-images.githubusercontent.com/20264271/62389103-810be000-b524-11e9-8b4b-8dce4dea5c11.png">

And then when I go back to edit with Oxygen, everything is removed in the editor as well.

<img width="294" alt="Screen Shot 2019-08-02 at 12 48 04 PM" src="https://user-images.githubusercontent.com/20264271/62389123-8cf7a200-b524-11e9-87a8-98739c47e8a6.png">

**Comment by Spellhammer** [comment]
Are you working in a single tab or do you have the Oxygen editor and WordPress post editor open in separate tabs?

**Comment by vanillaicedlatte** [comment]
> Are you working in a single tab or do you have the Oxygen editor and WordPress post editor open in separate tabs?

Separate tabs

**Comment by Spellhammer** [comment]
Please try replicating the issue you're seeing while working with a single tab and report back.

**Comment by Spellhammer** [comment]
When you save in the WordPress editor, the Oxygen shortcodes are saved in the state they were in when the WP editor was loaded, which means it'll overwrite any changes made in a separate Oxygen Builder tab since that post edit screen was loaded.

**Comment by vanillaicedlatte** [comment]
Interesting to know! Replicating the issue using only one tab, it worked fine. Looks like it's not specifically an issue with the repeater then, just using tabs. I will be sure to only do that from now on to avoid this issue. Thanks for the speedy help!
