### ISSUE TITLE
Conditions in re-usable templates don't show in editor

### ISSUE THREAD

**Issue by fscriven** [soflyy/oxygen-bugs-and-features#465]
**Describe the bug**
I have a template with conditions. Condition is: Only show these divs on pages with these tags. I put the template on the page. Nothing shows in the editor. Only in the front end do I see the effect of the conditions.

**Expected behavior**
Conditions should behave the same in the template and on the page they are put in in the editor if using them in re-usable blocks.

**What actually happens**
As description

**Comment by Spellhammer** [comment]
Pages by default don't have tags or categories. How have you enabled these capabilities on pages?

I've tested with a user logged in/logged out condition and it worked fine in a re-usable part. The issue, I think, is that when using a re-usable part which has elements with conditions, the elements' conditions are treated as "live" regardless of the preview mode set in the re-usable part template. That means that if the condition isn't true while you're in the editor, the elements are hidden.

I suspect that's the problem. Can you please test with a condition that evaluates to true in the builder and see if it's visible in the builder for you?

**Comment by fscriven** [comment]
Hi, thanks. Sorry, I didn't realise that tags weren't default for pages. Had installed this plugin a while back: https://wordpress.org/plugins/post-tags-and-categories-for-pages/ and forgotten about - if it's related to non standard WP behavior then of course you can't really say it's a bug.

Live is what I want and what I have set up and already evaluates to true. I have one page with many divs each div has  a condition: if PostTag==x then show. Using OR not AND. This allows me to set up special offers on my site and have them appear on many pages (by defining the categories for each page) while editing just one central location (this one page) with the conditions as mentioned.
