### ISSUE TITLE
Woo Shop page not displaying shop template

### ISSUE THREAD

**Issue by TrustedSamurai** [soflyy/oxygen-bugs-and-features#466]
**Describe the bug**
*A clear and concise description of what the bug is.*

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
*Yes/No*

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
*If yes, provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*

**To Reproduce**

**Expected behavior**
*A clear and concise description of what you expected to happen.*

**What actually happens**
*A clear and concise description of what happens instead of the expected behavior.*

**Screenshots**
*If applicable, add screenshots to help explain your problem.*

**Desktop (please complete the following information):**
 - Oxygen Version [e.g. 2.2 Alpha]

**Smartphone (please complete the following information):**
 - Oxygen Version [e.g. 2.2 Alpha]

**Additional context**
*Add any other context about the problem here.*

**Comment by TrustedSamurai** [comment]
**Describe the bug**
Not sure this is a bug, could be user error but have tried coming at this several different ways and watched this section of the version 3.0 Beta 3 times now.

**_WooCommerce created 'Shop' page does not display the template Shop_**.

I added a shop template and follow video instructions for adding Archive Taxonomies and PostTypes.  Then save this with a slug of 'shop' to begin with then changing this to a slug of 'shop-template'.   Video does not show setting Page 'Shop' to template 'Shop' but I did this.  Then when it failed I tried without too.

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
Yes

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**  YES.
http://gentle-iguana.w6.wpsandbox.pro?upass=hM24m0V9xXxB


**To Reproduce**
Steps to reproduce the behavior:

Go to 'homepage.'
Click on 'menu option Shop'
Notice that the shop template is not displayed.

Expected behavior: I expect to see the shop template displayed.

**What actually happens**
It seems to display the first 'fall back' page.



Desktop (please complete the following information):

OS: Win10
Browser  chrome
Oxygen Version [e.g. 3.0 Beta]

**Comment by Spellhammer** [comment]
The template priority was too low, so the default archive template was being used instead. I've set the shop template to 100 and it's now working at http://gentle-iguana.w6.wpsandbox.pro/shop/.
