### ISSUE TITLE
Dynamic data > Content , Font Size Issues

### ISSUE THREAD

**Issue by Noz5** [soflyy/oxygen-bugs-and-features#468]
**Describe the bug**
The "Content" text inserted via dynamic data, doesn't change size when editing text font size property. only changes when editing global settings Body text size.

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
*Yes*

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
Haven't use Sandbox, but it's a clean test wp install with ACF Pro and latest Oxygen + Gutenberg
 
**To Reproduce**
1. insert text
2. select dynamic data > content (content of a CPT in this case)
3. change font size . nothing happens
4. change font size from Global Settings > Body Text , this will change it

**Desktop (please complete the following information):**
- OS: Win10
 - Browser Firefox latest
 - Oxygen Version 3
 

**Note: The font size changes in the Builder, but does not reflect on the front end /display.
and i did hard refresh..

Update: This is only happening when I set the text TAG to P .. so tag should be Div in order for the font-size to work**

**Comment by KittenCodes** [comment]
@Noz5 This is working correctly in the latest version of Oxygen.
