### ISSUE TITLE
500 error only when saving woocommerce product page

### ISSUE THREAD

**Issue by parusha22** [soflyy/oxygen-bugs-and-features#469]
I have cleared the cache and deactivated plugins and get 500 error only when trying  to save a new product page with the Beta plugin. I use siteground - I doubt it is a server misconfig.

**Comment by Spellhammer** [comment]
Please check your error log for the actual 500 error details, send those details to support@oxygenbuilder.com, and we'll be glad to advise.

**Comment by parusha22** [comment]
This is what I managed to find

Cheers

#6 /home/mahesi96/public_html/jivada.com/wp-incl in /home/mahesi96/public_html/jivada.com/wp-content/plugins/woocommerce/templates/single-product/sale-flash.php on line 25
#5 [internal function]: do_shortcode_tag(Array)
#4 /home/mahesi96/public_html/jivada.com/wp-includes/shortcodes.php(325): OxygenElement->shortcode(Array, '', 'oxy-product-ima...')
#3 /home/mahesi96/public_html/jivada.com/wp-content/plugins/oxygen/component-framework/api/oxygen.element.class.php(121): Oxygen\WooElements\ProductImages->render(Array, Array, '')
#2 /home/mahesi96/public_html/jivada.com/wp-content/plugins/oxygen-woocommerce/elements/product-images.php(17): woocommerce_show_product_sale_flash()
#1 /home/mahesi96/public_html/jivada.com/wp-content/plugins/woocommerce/includes/wc-template-functions.php(1561): wc_get_template('single-product/...')
#0 /home/mahesi96/public_html/jivada.com/wp-content/plugins/woocommerce/includes/wc-core-functions.php(249): include()
Stack trace:
2019-08-05T11:45:33+00:00 CRITICAL Uncaught Error: Call to a member function is_on_sale() on boolean in /home/mahesi96/public_html/jivada.com/wp-content/plugins/woocommerce/templates/single-product/sale-flash.php:25
