### ISSUE TITLE
3.0ß1/Oxygen Gutenberg Beta 1 Changes Editor Font Size

### ISSUE THREAD

**Issue by imjeffp** [soflyy/oxygen-bugs-and-features#471]
Activating the Oxygen Gutenberg Beta 1 plugin changes the font sizes in the post/page editor as shown.

Inactive:
<img width="1325" alt="Screen Shot 2019-08-05 at 1 37 56 PM" src="https://user-images.githubusercontent.com/25798597/62497137-b3c20c80-b7a0-11e9-986c-4eb2da046c42.png">

Active:
<img width="1325" alt="Screen Shot 2019-08-05 at 1 37 15 PM" src="https://user-images.githubusercontent.com/25798597/62497170-c76d7300-b7a0-11e9-88e3-3fb718df2389.png">

Some of my custom CSS is also showing up in the editor. Notice the red text in the active screen.

Don't know if this is related to [385](https://github.com/soflyy/oxygen-bugs-and-features/issues/385). I only noticed it when I turned the Gutenberg plugin on.

**Comment by imjeffp** [comment]
Still an issue with ß2. There also this little bit of weirdness:
<img width="407" alt="Screen Shot 2019-08-08 at 5 08 51 PM" src="https://user-images.githubusercontent.com/25798597/62741165-976fdb00-b9ff-11e9-82e1-88aac03e88c2.png">

**Comment by KittenCodes** [comment]
> I can reproduce this on a Sandbox install

Hey @imjeffp, please can I have a link to the Sandbox install?

**Comment by imjeffp** [comment]
Here you go: http://denim-sable.w6.wpsandbox.pro?upass=iRs6NnW13vE1 <http://denim-sable.w6.wpsandbox.pro/?upass=iRs6NnW13vE1> (Click the blank install, but you probably knew that.)

**Comment by Spellhammer** [comment]
This is intended behavior.

Is there a reason you don't want the text to be styled as it will be styled on the front end?

**Comment by imjeffp** [comment]
It was unexpected and a change from the typical behavior of the Gutenberg blocks. I kind of like the standard behavior is all.

Should a new bug report be opened for the second bit of weirdness?

**Comment by KittenCodes** [comment]
> Should a new bug report be opened for the second bit of weirdness?

Yes please.
