### ISSUE TITLE
Rich text not working inside Gutenberg Block {Oxygen Gutenberg Beta 2}

### ISSUE THREAD

**Issue by gitsimhub** [soflyy/oxygen-bugs-and-features#473]
**Describe the bug**
I placed a rich text element to a Oxygen Gutenberg block. But i cant edit this inside Gutenberg itself. Normal text element works well.

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
Yes

**Screenshots**
https://cl.ly/ca40ae9ee51e

**Desktop (please complete the following information):**
- OS: MacOS
 - Browser Chrome Version 75.0.3770.142
 - Oxygen Version Oxygen 3.0 Beta 2

**Comment by Spellhammer** [comment]
I'm unable to replicate this on a fresh install running beta 2.

Do you have any other plugins activated? If so, please disable everything except for Oxygen and Oxygen-Gutenberg to see if the issue persists.

**Comment by gitsimhub** [comment]
Hey, ive just tried it again and its working fine now! Kinda weird. Did not change anything neither deleted the cache or installed/deinstalled sth. new.
We can close that now. If it happens again, i will make a new report.
