### ISSUE TITLE
Gutenberg Integration in Oxygen 3 Beta

### ISSUE THREAD

**Issue by ciaoweb** [soflyy/oxygen-bugs-and-features#474]
**Describe the bug**
When in the WordPress editing area I tick the box to make the page editable in Gutenberg and hit UPDATE I get an error message. 

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
No

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
No, since following the https://oxygenbuilder.com/try I get an error message?

See error screenshot:
![screencapture-joinusatworld-staging-wp-admin-post-php-2019-08-08-11_37_28](https://user-images.githubusercontent.com/2788541/62696900-65478480-b9d1-11e9-82a6-58d54114b098.png)

In this staging site errors appear in both new and old pages, test page here:
https://www.joinusatworld.com/staging/test-page/

**To Reproduce**
1. Go to 'WP editing area of the page.'
2. Click on 'Check box to allow Gutenberg editing'
3. Click on UPDATE

**Expected behavior**
*A clear and concise description of what you expected to happen.*

**What actually happens**
*A clear and concise description of what happens instead of the expected behavior.*

**Screenshots**
*If applicable, add screenshots to help explain your problem.*

**Desktop (please complete the following information):**
 - Oxygen Version [e.g. 2.2 Alpha]

**Smartphone (please complete the following information):**
 - Oxygen Version [e.g. 2.2 Alpha]

**Additional context**
*Add any other context about the problem here.*

**Comment by Spellhammer** [comment]
Please try this on a fresh install that has never had a previous 3.0 alpha or beta on it and see if the same error occurs.

**Comment by ciaoweb** [comment]
Hi,

In my staging area I have reset the database with WP Reset, installed the Atomic site and NO, I still getting same error message. I have reset database again, created a Main Template with inner, created a page in Oxygen, went to WP back end, ticked the checkbox and NO, still getting same error message as screenshot. Does a database reset completely erase any previous installation of Oxygen? I assume yes?

Look forward to good news on this important feature.#

Best wishes

**Comment by ciaoweb** [comment]
UPDATE
In a fresh WP install with only Oxygen and Gutenberg Beta installed I have imported Atomic site but still getting same error when I try t make ANY page editable in Gutenberg.

**Comment by KittenCodes** [comment]
This should be fixed in the latest version of Oxygen and the Gutenberg add-on.
