### ISSUE TITLE
Easy Posts shows "Home" Page in Oxygen editor when previewing Posts in case of a Posts page

### ISSUE THREAD

**Issue by srikat** [soflyy/oxygen-bugs-and-features#481]
Oxygen 2.4.1.

Only if latest posts are set to show on the homepage at Settings > Reading do previewing of Posts work properly in Oxygen's Easy Posts.

It does not work when a Posts page has been set.

Steps to reproduce:

1. Set a static Page titled say, "Blog" as the Posts page at Setting > Reading (in conjunction with a "Home" Page as the homepage).

2. Create a Template called say, "Archive" and apply it to all archives.

3. Edit this Template and make sure Previewing dropdown is set to "Posts".

4. Add an Easy Posts component.

The expected behavior is to see a grid of blog posts.

But what happens is that "Home" Page itself is shown by Easy Posts.

![screenshot](https://d.pr/i/O5Ybym+)

This issue is not present with the default WordPress setting where homepage is set to show the latest blog posts.

**Comment by KittenCodes** [comment]
@srikat Please make sure the template is also applied to the Blog Posts Index via "Where does this template apply" > Other.
