### ISSUE TITLE
DONE: Closing animations for Modals

### ISSUE THREAD

**Issue by srikat** [soflyy/oxygen-bugs-and-features#485]
It would be helpful if there is an option to individually select and set the closing animation for Modals. At the moment (2.4.1), it fades out all the time.

**Comment by adrien-robert** [comment]
Nice idea, +1!

**Comment by demetre19** [comment]
+1

**Comment by amandalucas** [comment]
+1

**Comment by Martin-1** [comment]
Good idea!

**Comment by flashpointrk** [comment]
+1

**Comment by thmbaker** [comment]
+1

**Comment by be1px** [comment]
+1

**Comment by alpabuz** [comment]
+1

**Comment by chembim** [comment]
+1

**Comment by HenkDz** [comment]
+1

**Comment by Deanphillips** [comment]
Elementor now has this too

**Comment by alriksson** [comment]
+1

**Comment by imjeffp** [comment]
Add my vote for this.

**Comment by hawkmusician** [comment]
+1

**Comment by Takkster** [comment]
+1

**Comment by jcmatoskx** [comment]
+1 setting close animation is necessary for design consistency

**Comment by cedricly** [comment]
Yes please, it would be much better for consistency.

**Comment by pheta** [comment]
+1

**Comment by alextester1990** [comment]
+1

**Comment by alanzirpoli** [comment]
+1

**Comment by Jimmyg128** [comment]
+1

**Comment by wysoczanskim** [comment]
+1

**Comment by schahramnouri** [comment]
I really love to see this feature. I have created modal as my sliding in menu item. It slides gently in, which I love to watch, but then it fades out rapidly when I close it. If we were able to manage animation for both opening and closing, it would be fantastic.

+1

**Comment by DahmaniAdame** [comment]
+1

**Comment by reachingmike** [comment]
+1

**Comment by joffreypersia** [comment]
+1... 

Anyone have found a solution since 2019..? :/

**Comment by Spellhammer** [comment]
As of 4.0 Alpha 1, Modals will animate out using whatever animation they animate in with.

**Comment by imjeffp** [comment]
Can we re-open this? Oxygen 4.8.2: my modals (and accordion closings) do not animate.
