### ISSUE TITLE
Oxygen templates don't save data if no WordPress posts or pages present (3.0 Beta 2)

### ISSUE THREAD

**Issue by rob** [soflyy/oxygen-bugs-and-features#487]
**Describe the bug**

With a default WordPress install, if you delete the sample Posts and Pages and then try to create an Oxygen template, it'll behave fine and let you add elements, style them, etc — it just won't save anything or add anything to the "Structure" tab. Clicking save will behave as if it is saved (without any errors), but refreshing will bring up a blank template again.

It's obvious now Oxygen requires a post or page to be present due to its architecture, but coming from Beaver Builder where you don't need any posts or pages and can still use Themer to create templates out of the box, perhaps a warning should be noted by Oxygen somewhere if it detects there's 0 posts or pages in WordPress.

**To Reproduce**

1. Install WordPress and Oxygen
2. Delete default WordPress posts and pages
3. Create a new Oxygen template, edit it, and save it
4. Refresh page and observe anything done in #3 wasn't actually saved

**Expected behavior**

Oxygen warning you that no posts or pages are present and that they are required for Oxygen to work correctly.

**What actually happens**

Everything behaves normally as if it's working, but it's not.

**Screenshots**

Screencast: https://www.youtube.com/watch?v=HWUM9AYUfsA

**Desktop (please complete the following information):**

Oxygen 3.0 Beta 2 (don't see this available in the sandbox to test, only stable version.)

**Comment by sunnyt7** [comment]
Is there any temporary fix for this?

**Comment by rob** [comment]
Yeah, add a post or page 😇

**Comment by KittenCodes** [comment]
I can no longer replicate this in Oxygen v3.6.
