### ISSUE TITLE
Overflow set to scroll on single product page thumbnails and image zoom gets jittery when selecting a second image.

### ISSUE THREAD

**Issue by TrustedSamurai** [soflyy/oxygen-bugs-and-features#491]
**Describe the bug**
1) When you view a single product with multiple images in the thumbnail, the div surrounding the thumbnails has overflow set to scroll.  It shows scroll bars which look messy.  Woo usually shows these thumbnails in their correct ratio.

2) When you hover over the main image it will auto zoom as you move your mouse over it.  If you select another image from the thumbnail selection and hover over the image it gets jittery.

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
*Yes*

**Expected behavior**
I expect the thumbnails to display in their correct ratio without cropping.
I expect that any image selected will display in zoom correctly on mouse hover.

**What actually happens**
Explained above.

**Screenshots**
Video link here.
http://somup.com/cqjb39e0z3

**Desktop (please complete the following information):**
 - Oxygen Version [e.g. 2.2 Alpha]

**Smartphone (please complete the following information):**
Windows 10.
Chrome
Oxygen 3.0 Beta 2

**Comment by KittenCodes** [comment]
> When you hover over the main image it will auto zoom as you move your mouse over it. If you select another image from the thumbnail selection and hover over the image it gets jittery.

This should be fixed in the latest version of Oxygen and the WooCommerce add-on.
