### ISSUE TITLE
(3.0 Beta 2) Photoswipe pswp class Not Clearing After Closing Image

### ISSUE THREAD

**Issue by AzzX** [soflyy/oxygen-bugs-and-features#493]
Add a gallery to a product template with woocommerce activated.
Gallery works fine but the 'pspw' css class is not resetting/clearing to remove the view after the Lightbox is closed.

Similar issue as https://stackoverflow.com/questions/31127896/photoswipe-pswp-class-not-clearing-after-closing-image

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
Yes

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
*If yes, provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*

Tried to recreate it, it works fine on the sandbox version http://motionless-ibex.w5.wpsandbox.pro/

**To Reproduce**
1. Create a gallery element - works fine.
2. Add A toggle element anywhere on same page, javascript for photoswipe-global gets called twice.

**Comment by KittenCodes** [comment]
This should be fixed in the latest version of Oxygen.
