### ISSUE TITLE
Error occurred while rendering menu ´Not Found 404´

### ISSUE THREAD

**Issue by alexandrudinu** [soflyy/oxygen-bugs-and-features#505]
<img width="889" alt="Capture" src="https://user-images.githubusercontent.com/28765264/63697250-d46c0800-c81c-11e9-8fc9-aa677620fa81.PNG">
**Describe the bug**
*A clear and concise description of what the bug is.*

On an fresh WP installation I try to create the ´Main´ menu and I get this error:
_´Error occurred while rendering menu ´Not Found 404´_

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
*Yes/No*
Yes
**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
*If yes, provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*
No

**To Reproduce**
1. Go to 'https://papitoys.staging.wpmudev.host/wp-login.php/ (Password Protection Enabled)'
2. Click on 'WordPress Dashboard > Oxygen > Template > Main > Edit with Oxygen'
3. See error

**Expected behavior**
*A clear and concise description of what you expected to happen.*

**What actually happens**
*A clear and concise description of what happens instead of the expected behavior.*
I expect to be able to build templates, to add header area, content area ...etc without error

**Screenshots**
*If applicable, add screenshots to help explain your problem.*
Yes, attached.

**Desktop (please complete the following information):**
 - Oxygen Version [e.g. 2.2 Alpha]

**Smartphone (please complete the following information):**
 - OS: Windows / Mac
 - Browser: Chrome Version 75.0.3770.142 (Official Build) (64-bit), Firefox 68.0.2 (64-bit)
 - Oxygen Version: 3.0 Candidate Release 1

**Additional context**
*Add any other context about the problem here.*
I tried with the previous version (Public beta 3) and it did not work...

**Comment by inferno-adam** [comment]
@alexandrudinu Did you try changing the selection in the `Previewing` menu in the top bar to something other the 'wp_admin...' value?

**Comment by KittenCodes** [comment]
Please make sure that the address you're using to access the site is the same as the address set via Settings > General in the WordPress admin area. For example, you may be accessing the site via HTTPS, but the site address is using HTTP.

**Comment by dipiana** [comment]
> Please make sure that the address you're using to access the site is the same as the address set via Settings > General in the WordPress admin area. For example, you may be accessing the site via HTTPS, but the site address is using HTTP.

Thanks, solved the same issue for me.
