### ISSUE TITLE
Oxygen 3RC1 - Can't save the content in my gutenberg blocks

### ISSUE THREAD

**Issue by guillaumelorain** [soflyy/oxygen-bugs-and-features#507]
I just created a gutemberg block, it contain an toggle (from the helper section). I want to custom the texts in the gutemberg editor so I do not edit the texts in my template so I have 
this : 
[Uploading Screen Shot 2019-08-27 at 3.08.19 pm.png…]()

Then when I add the block in gutemberg I can change the content but when I save the original text is back. It doesn't save my changes.

Thanks

**Comment by KittenCodes** [comment]
Replicated in RC1.

**Comment by KittenCodes** [comment]
@guillaumelorain 

Unfortunately, we haven't been able to replicate this issue. Please email admin credentials for your site and a link to the page in question to support@oxygenbuilder.com so that we can investigate this issue for you.

**Comment by shock2d** [comment]
Got same issue ones. But cannot help to replicate as I found how to deal with it.

Block created with oxygen was used 3 times on a page and the first one was not saving any data. After removing block, with problems saving, reloading page and adding the new one, everything works fine

**Comment by scriptaimago** [comment]
Goodmorning. Same issue.
If I change the background image of each the block then saves itself, otherwise it won't.
Furthermore, I do not see the block element properties ( such as background, font-size etc) on  the block settings section in the right panel.
Any clues?
Do you want an admin account to check it out?

**Comment by KittenCodes** [comment]
@guillaumelorain @shock2d @scriptaimago 

If you are still having problems with this in the latest version of Oxygen and our Gutenberg add-on, please open a support ticket by emailing support@oxygenbuilder.com so that we can take a look.
