### ISSUE TITLE
WooCommerce product image not displaying properly when is used separately

### ISSUE THREAD

**Issue by alexandrudinu** [soflyy/oxygen-bugs-and-features#509]
**Describe the bug**
*A clear and concise description of what the bug is.*

I try to build a single product page. I am not using the ´Product Builder´.
I am using the ´Product Image´, ´Add to cart´ Etc.
The image is displayed wrong.

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
*Yes*

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
*If yes, provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*

**http://proud-plover.w6.wpsandbox.pro?upass=7fTt45ZcXv9V**

**To Reproduce**
1. Build a single product page and add ´WooCommerce image´
2. Observe how messed up it looks

**Expected behavior**
*A clear and concise description of what you expected to happen.*

I expect to have a clean, nice looking image gallery just like when you use product builder.

**What actually happens**
*A clear and concise description of what happens instead of the expected behavior.*

Instead of having a nice image, we have a messed up gallery.

**Screenshots**
*If applicable, add screenshots to help explain your problem.*
![Screenshot_2019-08-27 Happy Ninja - Sandbox](https://user-images.githubusercontent.com/28765264/63755765-85bf7c00-c8b7-11e9-85af-8673d3589fb2.png)

 - Oxygen Version: Oxygen 3.0 Release Candidate 1

**Comment by KittenCodes** [comment]
You need to add your Product Images element to the Product Builder element for them to display correctly.

**Comment by svenolaf** [comment]
I'm having the same issue. Will have to settle for the Product Builder until fixed.

**Comment by KittenCodes** [comment]
@svenolaf 

> I'm having the same issue. Will have to settle for the Product Builder until fixed.

This isn't a bug. The Product Images element needs to be used inside the Product Builder.

**Comment by svenolaf** [comment]
@KittenCodes Thank you, I understand now, don't delete the Product Builder before adding other items. ;).
