### ISSUE TITLE
Oxygen 3RC1 - Repeater resets global colors and deletes content

### ISSUE THREAD

**Issue by dposnanski** [soflyy/oxygen-bugs-and-features#512]
**Describe the bug**
I am trying to visually create the blog archive and using the repeater field but, when I save it and check the frontend, all my global colors are gone. When I go back to the blog archive template, there's no content, as if I had never added the repeater. My error log shows the following: PHP Warning:  Invalid argument supplied for foreach() in /wp-content/plugins/oxygen/component-framework/includes/ajax.php on line 87

It also shows "no data for field" even if I have the hello world post.

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
Yes

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
No

**To Reproduce**
1. Create a main template
2. Add global colors
3. Add header, footer, and a section containing inner content
4. Create another template for blog posts (archive->posts)
5. Add a repeater with some fields (I added title and content)
6. Save
7. Go to frontend, see there are no styles present
8. Check blog template, all inner content is gone

**Expected behavior**
I expect my contents and styles to show on the frontend and not disappear.

**What actually happens**
All my stylings and content disappears (not even the color id's stick, they get reset).

**Screenshots**
Colors and styles present in main template:
![image](https://user-images.githubusercontent.com/22684573/63934911-affe6e80-ca5c-11e9-9f82-c249b72ca9d4.png)

Adding repeater to blog template:
![image](https://user-images.githubusercontent.com/22684573/63935126-27cc9900-ca5d-11e9-963f-c4c268ea3a40.png)

Checking the page:
![image](https://user-images.githubusercontent.com/22684573/63935235-577ba100-ca5d-11e9-894d-78ca120f060b.png)

Going back to the template (no content, no colors):
![image](https://user-images.githubusercontent.com/22684573/63935316-7843f680-ca5d-11e9-9d2b-ca40b24b225b.png)

**Desktop (please complete the following information):**
- OS: Windows 10
 - Browser Version 76.0.3809.132 (Official Build) (64-bit)
 - Oxygen Version Oxygen 3RC1

**Comment by dposnanski** [comment]
Just sent credentials via email.

**Comment by KittenCodes** [comment]
Replicated and reported internally.

**Comment by KittenCodes** [comment]
This is fixed in Oxygen 3.1.
