### ISSUE TITLE
[2.2 Beta 1] Menu component - editing the class has no effect

### ISSUE THREAD

**Issue by ddenev** [soflyy/oxygen-bugs-and-features#52]
**Describe the bug**
When a Menu component has a class set then editing the Menu properties does not do anything - nothing changes.

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
No, sandbox is 2.1 only

**To Reproduce**
1. Edit a new page/template with Oxygen
2. Add a Menu component (from WordPress group)
3. Add a class to the component and select that class for editing
4. Duplicate the component so that there are 2 of them (this is just for illustration)
5. Change any of the properties on the Primary tab, e.g. text color

**Expected behavior**
Changes apply

**What actually happens**
Nothing happens, changes are not applied

**Screenshots**
none

**Desktop (please complete the following information):**
- OS: Windows 7 64-bit
 - Browser Chrome
 - Oxygen Version 2.2 Beta 1

**Additional context**
This works ok when using the Icon component so I would expect that it should work with any component.

**Comment by Spellhammer** [comment]
Present in 2.1. Replicated and reported.
