### ISSUE TITLE
Cannot find css file

### ISSUE THREAD

**Issue by rstark8827** [soflyy/oxygen-bugs-and-features#522]
**Describe the bug**
Keep getting the error 403 when saving a page saying "Error occured while saving" 

I am reporting this because when looking at this with my sftp client, no search-form.css exists in this directly nor does it on previous pre 3.0 install as well. So I'm not sure why it is making this call, but thought this could be helpful for you to check out. See below the php warning from Kinsta

2019/09/02 20:57:17 [error] 3242#3242: *188567 FastCGI sent in stderr: "PHP message: PHP Warning: file_get_contents(/www/founderspark_401/public/wp-content/plugins/oxygen/component-framework/components/classes/search-form/search-form.css): failed to open stream: No such file or directory in /www/founderspark_401/public/wp-content/plugins/oxygen/component-framework/components/classes/search-form.class.php on line 97" while reading response header from upstream, client: 170.10.179.148, server: smilenwa.com, request: "POST /?action=oxy_render_search_form&nonce=1c50a616b0&post_id=1427 HTTP/1.0", upstream: "fastcgi://unix:/var/run/php7.3-fpm-founderspark.sock:", host: "smilenwa.com", referrer: "https://smilenwa.com/?ct_builder=true&ct_inner=true&oxygen_iframe=true"

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
*Yes*

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
*If yes, provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*
There is no search bar on this sandbox install. Maybe you guys should but that in the install?

**To Reproduce**
1. Go to home page in oxygen builder. 
2 Select the section from the structure in the right column to delete the section
3. click on the x to delete section
4. Save
5. Error on Saving. Section is not delted. 
**Expected behavior**
Save and section is deleted

**What actually happens**
403 when saving a page saying "Error occured while saving" after deleting a div on the main home page. It is not happening on other pages for some reason. However I"m confused because this seems to be oxygen related from the error message and there is not search-form.css file existing in the file path which is called.

**Desktop (please complete the following information):**
-OS: OS X
 - Chrome and Safari
 - Oxygen Version 3.0 RC1

**Additional context**
*Add any other context about the problem here.*

**Comment by rstark8827** [comment]
Strange. I was able to delete other things on the page and then I was able to delete the section which I wanted. It now seems to be working again. I am no longer seeing the kinsta error. So maybe it was just a random error. But I am no longer able to reproduce.

**Comment by KittenCodes** [comment]
@rstark8827 If you're able to reproduce the error again, please re-open this issue.

**Comment by abuntly** [comment]
I'm having the same issue last several days. I updated wp-rocket which had some "Cloudways" related updates, and it began saving properly without the 403 error.

Things were great until today.

I disabled wp-rocket and ConveyThis as they're both appearing in my error log (unsure if related) and I still cannot save changes without getting 403 error.

Finally, while in the middle of writing this up and testing things still I may have found something...
When I disable CSS Cache via Oxygen Settings, I save go switch tabs and save my template, when I enable CSS Cache in the other tab, then go back and save again, i get 403... tried a few times, any time i enable it, 403, disable it, no 403 and saves fine.

Seeing how I disabled wp-rocket (some caching etc, and cloudflare/some caching there too..) i dont think its colliding with them... So i currently think i found my solution, disable css caching in oxygen.. But not sure what its conflicting with.


`[Sat Jul 25 18:33:32.390664 2020] [proxy_fcgi:error] [pid 27953] [client 24.130.239.26:34558] AH01071: Got error 'PHP message: PHP Warning:  chmod(): Operation not permitted in /home/442694.cloudwaysapps.com/kzwxvfrrnn/public_html/wp-admin/includes/class-wp-filesystem-direct.php on line 168\nPHP message: PHP Warning:  chmod(): Operation not permitted in /home/442694.cloudwaysapps.com/kzwxvfrrnn/public_html/wp-admin/includes/class-wp-filesystem-direct.php on line 168\n', referer: https://camoeyes.com/wp-admin/options-general.php?page=wprocket
[Sat Jul 25 18:39:12.964244 2020] [proxy_fcgi:error] [pid 28543] [client 127.0.0.1:35332] AH01071: Got error 'PHP message: PHP Warning:  Creating default object from empty value in /home/442694.cloudwaysapps.com/kzwxvfrrnn/public_html/wp-content/plugins/oxygen/component-framework/includes/ajax.php on line 1389\n', referer: https://camoeyes.com/?ct_template=product-page&ct_builder=true&ct_inner=true&oxygen_iframe=true
[Sat Jul 25 18:39:14.086384 2020] [proxy_fcgi:error] [pid 28549] [client 24.130.239.26:35342] AH01071: Got error 'PHP message: PHP Warning:  file_get_contents(/home/442694.cloudwaysapps.com/kzwxvfrrnn/public_html/wp-content/plugins/oxygen/component-framework/components/classes/search-form/search-form.css): failed to open stream: No such file or directory in /home/442694.cloudwaysapps.com/kzwxvfrrnn/public_html/wp-content/plugins/oxygen/component-framework/components/classes/search-form.class.php on line 97\n', referer: https://camoeyes.com/?ct_template=product-page&ct_builder=true&ct_inner=true&oxygen_iframe=true
[Sat Jul 25 18:39:14.273621 2020] [proxy_fcgi:error] [pid 28550] [client 24.130.239.26:35346] AH01071: Got error 'PHP message: PHP Warning:  file_get_contents(/home/442694.cloudwaysapps.com/kzwxvfrrnn/public_html/wp-content/plugins/oxygen/component-framework/components/classes/search-form/search-form.css): failed to open stream: No such file or directory in /home/442694.cloudwaysapps.com/kzwxvfrrnn/public_html/wp-content/plugins/oxygen/component-framework/components/classes/search-form.class.php on line 97\n', referer: https://camoeyes.com/?ct_template=product-page&ct_builder=true&ct_inner=true&oxygen_iframe=true
[Sat Jul 25 18:39:26.859230 2020] [proxy_fcgi:error] [pid 28622] [client 24.130.239.26:35446] AH01071: Got error 'PHP message: PHP Warning:  file_get_contents(/home/442694.cloudwaysapps.com/kzwxvfrrnn/public_html/wp-content/plugins/oxygen/component-framework/components/classes/search-form/search-form.css): failed to open stream: No such file or directory in /home/442694.cloudwaysapps.com/kzwxvfrrnn/public_html/wp-content/plugins/oxygen/component-framework/components/classes/search-form.class.php on line 97\n', referer: https://camoeyes.com/?ct_template=product-page&ct_builder=true&ct_inner=true&oxygen_iframe=true
[Sat Jul 25 18:39:27.068495 2020] [proxy_fcgi:error] [pid 28625] [client 24.130.239.26:35458] AH01071: Got error 'PHP message: PHP Warning:  file_get_contents(/home/442694.cloudwaysapps.com/kzwxvfrrnn/public_html/wp-content/plugins/oxygen/component-framework/components/classes/search-form/search-form.css): failed to open stream: No such file or directory in /home/442694.cloudwaysapps.com/kzwxvfrrnn/public_html/wp-content/plugins/oxygen/component-framework/components/classes/search-form.class.php on line 97\n', referer: https://camoeyes.com/?ct_template=product-page&ct_builder=true&ct_inner=true&oxygen_iframe=true
[Sat Jul 25 18:40:59.636769 2020] [proxy_fcgi:error] [pid 28794] [client 24.130.239.26:35790] AH01071: Got error 'PHP message: PHP Warning:  include(/home/442694.cloudwaysapps.com/kzwxvfrrnn/public_html/wp-content/wp-rocket-config/camoeyes.com.php): failed to open stream: No such file or directory in /home/442694.cloudwaysapps.com/kzwxvfrrnn/public_html/wp-content/plugins/wp-rocket/inc/classes/Buffer/class-config.php on line 124\nPHP message: PHP Warning:  include(/home/442694.cloudwaysapps.com/kzwxvfrrnn/public_html/wp-content/wp-rocket-config/camoeyes.com.php): failed to open stream: No such file or directory in /home/442694.cloudwaysapps.com/kzwxvfrrnn/public_html/wp-content/plugins/wp-rocket/inc/classes/Buffer/class-config.php on line 124\nPHP message: PHP Warning:  include(): Failed opening '/home/442694.cloudwaysapps.com/kzwxvfrrnn/public_html/wp-content/wp-rocket-config/camoeyes.com.php' for inclusion (include_path='.:/usr/share/php') in /home/442694.cloudwaysapps.com/kzwxvfrrnn/public_html/wp-content/plugins/wp-rocket/inc/classes/Buffer/class-config.php on line 124\n'
[Sat Jul 25 18:41:05.391014 2020] [proxy_fcgi:error] [pid 28809] [client 207.46.13.200:35806] AH01071: Got error 'PHP message: PHP Warning:  include(/home/442694.cloudwaysapps.com/kzwxvfrrnn/public_html/wp-content/wp-rocket-config/camoeyes.com.php): failed to open stream: No such file or directory in /home/442694.cloudwaysapps.com/kzwxvfrrnn/public_html/wp-content/plugins/wp-rocket/inc/classes/Buffer/class-config.php on line 124\nPHP message: PHP Warning:  include(/home/442694.cloudwaysapps.com/kzwxvfrrnn/public_html/wp-content/wp-rocket-config/camoeyes.com.php): failed to open stream: No such file or directory in /home/442694.cloudwaysapps.com/kzwxvfrrnn/public_html/wp-content/plugins/wp-rocket/inc/classes/Buffer/class-config.php on line 124\nPHP message: PHP Warning:  include(): Failed opening '/home/442694.cloudwaysapps.com/kzwxvfrrnn/public_html/wp-content/wp-rocket-config/camoeyes.com.php' for inclusion (include_path='.:/usr/share/php') in /home/442694.cloudwaysapps.com/kzwxvfrrnn/public_html/wp-content/plugins/wp-rocket/inc/classes/Buffer/class-config.php on line 124\n'
[Sat Jul 25 18:41:06.815798 2020] [proxy_fcgi:error] [pid 28810] [client 24.130.239.26:35810] AH01071: Got error 'PHP message: PHP Warning:  include(/home/442694.cloudwaysapps.com/kzwxvfrrnn/public_html/wp-content/wp-rocket-config/camoeyes.com.php): failed to open stream: No such file or directory in /home/442694.cloudwaysapps.com/kzwxvfrrnn/public_html/wp-content/plugins/wp-rocket/inc/classes/Buffer/class-config.php on line 124\nPHP message: PHP Warning:  include(/home/442694.cloudwaysapps.com/kzwxvfrrnn/public_html/wp-content/wp-rocket-config/camoeyes.com.php): failed to open stream: No such file or directory in /home/442694.cloudwaysapps.com/kzwxvfrrnn/public_html/wp-content/plugins/wp-rocket/inc/classes/Buffer/class-config.php on line 124\nPHP message: PHP Warning:  include(): Failed opening '/home/442694.cloudwaysapps.com/kzwxvfrrnn/public_html/wp-content/wp-rocket-config/camoeyes.com.php' for inclusion (include_path='.:/usr/share/php') in /home/442694.cloudwaysapps.com/kzwxvfrrnn/public_html/wp-content/plugins/wp-rocket/inc/classes/Buffer/class-config.php on line 124\n', referer: https://camoeyes.com/?ct_template=product-page&ct_builder=true&ct_inner=true
[Sat Jul 25 18:41:29.796412 2020] [proxy_fcgi:error] [pid 28842] [client 24.130.239.26:35864] AH01071: Got error 'PHP message: PHP Warning:  Creating default object from empty value in /home/442694.cloudwaysapps.com/kzwxvfrrnn/public_html/wp-content/plugins/oxygen/component-framework/includes/ajax.php on line 1389\n', referer: https://camoeyes.com/?ct_template=product-page&ct_builder=true&ct_inner=true&oxygen_iframe=true
[Sat Jul 25 18:41:30.960310 2020] [proxy_fcgi:error] [pid 28845] [client 24.130.239.26:35876] AH01071: Got error 'PHP message: PHP Warning:  file_get_contents(/home/442694.cloudwaysapps.com/kzwxvfrrnn/public_html/wp-content/plugins/oxygen/component-framework/components/classes/search-form/search-form.css): failed to open stream: No such file or directory in /home/442694.cloudwaysapps.com/kzwxvfrrnn/public_html/wp-content/plugins/oxygen/component-framework/components/classes/search-form.class.php on line 97\n', referer: https://camoeyes.com/?ct_template=product-page&ct_builder=true&ct_inner=true&oxygen_iframe=true
[Sat Jul 25 18:41:31.533581 2020] [proxy_fcgi:error] [pid 28848] [client 24.130.239.26:35884] AH01071: Got error 'PHP message: PHP Warning:  file_get_contents(/home/442694.cloudwaysapps.com/kzwxvfrrnn/public_html/wp-content/plugins/oxygen/component-framework/components/classes/search-form/search-form.css): failed to open stream: No such file or directory in /home/442694.cloudwaysapps.com/kzwxvfrrnn/public_html/wp-content/plugins/oxygen/component-framework/components/classes/search-form.class.php on line 97\n', referer: https://camoeyes.com/?ct_template=product-page&ct_builder=true&ct_inner=true&oxygen_iframe=true
[Sat Jul 25 18:43:09.865268 2020] [proxy_fcgi:error] [pid 29034] [client 24.130.239.26:36182] AH01071: Got error 'PHP message: PHP Warning:  Creating default object from empty value in /home/442694.cloudwaysapps.com/kzwxvfrrnn/public_html/wp-content/plugins/oxygen/component-framework/includes/ajax.php on line 1389\n', referer: https://camoeyes.com/?ct_template=product-page&ct_builder=true&ct_inner=true&oxygen_iframe=true
[Sat Jul 25 18:43:11.459195 2020] [proxy_fcgi:error] [pid 29037] [client 24.130.239.26:36194] AH01071: Got error 'PHP message: PHP Warning:  file_get_contents(/home/442694.cloudwaysapps.com/kzwxvfrrnn/public_html/wp-content/plugins/oxygen/component-framework/components/classes/search-form/search-form.css): failed to open stream: No such file or directory in /home/442694.cloudwaysapps.com/kzwxvfrrnn/public_html/wp-content/plugins/oxygen/component-framework/components/classes/search-form.class.php on line 97\n', referer: https://camoeyes.com/?ct_template=product-page&ct_builder=true&ct_inner=true&oxygen_iframe=true
[Sat Jul 25 18:43:11.538159 2020] [proxy_fcgi:error] [pid 29040] [client 24.130.239.26:36202] AH01071: Got error 'PHP message: PHP Warning:  file_get_contents(/home/442694.cloudwaysapps.com/kzwxvfrrnn/public_html/wp-content/plugins/oxygen/component-framework/components/classes/search-form/search-form.css): failed to open stream: No such file or directory in /home/442694.cloudwaysapps.com/kzwxvfrrnn/public_html/wp-content/plugins/oxygen/component-framework/components/classes/search-form.class.php on line 97\n', referer: https://camoeyes.com/?ct_template=product-page&ct_builder=true&ct_inner=true&oxygen_iframe=true`

**Comment by abuntly** [comment]
Now, I enabled wp-rocket again and test, thinking im ready to go, I make some changes to my template and hit save only to get another 403... thought i had it :) so I proceed again, disable wp-rocket, go back to the tab, hit save and it saved this time.

But, i enable wp-rocket again and test and, it still saves changes.... So it seems possibly tied to wp-rocket but can't figure much past this point.
