### ISSUE TITLE
Gutenberg Integration removes dynamic backgrounds

### ISSUE THREAD

**Issue by gabrieluntura** [soflyy/oxygen-bugs-and-features#525]
**Describe the bug**
When I activate Oxygen Gutenberg Integration, all my sections on the frontend gets an inline CSS of 'style="background-image: auto"', removing some of my dynamic background images. When you have a featured image in the background, for example, it will get added inline, and the new Gutenberg Integration replaces that with "auto".

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
Yes

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
http://dilligent-batfish.w5.wpsandbox.pro/

**To Reproduce**
1. Create a section with a background of the featured image
2. Activate Oxygen Gutenberg Integration
3. It removes the background on the frontend.

**Screenshots**
*If applicable, add screenshots to help explain your problem.*

**Desktop (please complete the following information):**
 - Oxygen Version [3.0]

**Additional context**
*Add any other context about the problem here.*

**Comment by jkarelbroer** [comment]
Same here

**Comment by Hanleymade** [comment]
Same
