### ISSUE TITLE
DONE: Add subitems dropdown menu to mobile

### ISSUE THREAD

**Issue by estraatios** [soflyy/oxygen-bugs-and-features#526]
Hi.

I would like the ability to add the subitems of the menu in the mobile version and if anyone clicks the parent item then he will be able to see the subitems.
Currently, I can add the subitems and they are always showing in the menu under the parent item.
Please add this option.

**Comment by wplit** [comment]
For now, you can use my plugin and remove it if Oxygen ever builds this in.

https://github.com/wplit/Oxygen-Mobile-Sub-Menu

**Comment by estraatios** [comment]
Exacly what I was looking for. Thank you.

Have you contacted Oxygen team to add this in their product?

**Comment by KittenCodes** [comment]
You can use Oxygen's Pro Menu element. However, please note that you must disable the plugin linked above from wplit if you are using the Pro Menu.
