### ISSUE TITLE
Icon Box does not show 'Button Area' in structure until save and close/reopen

### ISSUE THREAD

**Issue by 5pinlink** [soflyy/oxygen-bugs-and-features#529]
https://media.giphy.com/media/VzkWZhM89EJMBKWXBM/giphy.gif
Check in the GIF above, you will see an extra layer in the icon box named Button Area, this can neither be selected or deleted, and as far as i can tell it does nothing, this is not then when you create an icon box with v3 (div 24)

**Comment by 5pinlink** [comment]
OK, this is the link layer, but the bug is still there, just different, when you create an icon box in v3 it doesn't show the link layer (Button Area) in structure, save, go to admin, reopen and the link layer (Button Area) is now visible.

**Comment by Lupul** [comment]
Added a screenshot as the one from the initial post isn't available anymore.
![image](https://user-images.githubusercontent.com/3596864/89914195-55263e80-dbfd-11ea-8a3d-2bdec72f77eb.png)

**Comment by KittenCodes** [comment]
Fixed in 3.7 Beta 1: https://oxygenbuilder.com/2021/01/22/oxygen-3-7-beta-1-now-available/.
