### ISSUE TITLE
[2.2 Beta 1] "flex-direction: unset" after clearing all changes from ID

### ISSUE THREAD

**Issue by ddenev** [soflyy/oxygen-bugs-and-features#53]
**Describe the bug**
After enabling and then disabling "Flex" on a component's ID, there is a "flex-direction: unset" leftover in the CSS which overrides the default for the component.

**To Reproduce**
1. Create a new page/template and edit it with Oxygen
2. Add a section element and select the ID for editing
3. Save the page and check the CSS for the div wrapper in Dev Tools. You will see that the default flex properties apply (these come from the .ct-section>.ct-section-inner-wrap selector in universal.css):
```
.ct-section>.ct-section-inner-wrap {
    display: flex;
    flex-direction: column;
    align-items: flex-start;
}
```
4. No go to Advanced/Layout and select the Flex button. Save the page and check the CSS. You will see:
```
#section-114-171 > .ct-section-inner-wrap {
    display: flex;
}
.ct-section>.ct-section-inner-wrap {
    display: flex;
    flex-direction: column;
    align-items: flex-start;
}
```
which is fine so far since I explicitly set the flex on the ID.

5. Now just disable Flex (hit the blue Flex button) to revert to default and save the page. Check the CSS. You will see:
```
#section-114-171 > .ct-section-inner-wrap {
    flex-direction: unset;
}
.ct-section>.ct-section-inner-wrap {
    display: flex;
    flex-direction: column;
    align-items: flex-start;
}
```
and this is the bug.

**Expected behavior**
CSS should revert to default and the "changed" indicator for Advanced/Layout tab should be removed.

**What actually happens**
There is a still CSS for the ID and the "changed" indicator is still on
![image](https://user-images.githubusercontent.com/1393766/52402894-10808b00-2ace-11e9-8268-b0b5ec8f62b3.png)

**Desktop (please complete the following information):**
- OS: Windows 7 64-bit
 - Browser Chrome
 - Oxygen Version 2.2 Beta 1

**Comment by Gibsonion** [comment]
This is big issue as it stops flex being able to be defined in classes +1 to get this solved

**Comment by timpixel** [comment]
This sounds quite important. And who knows, maybe css-writing/resetting problems like this can also be the reason for other cases of "the changed indicator is showing while it should not be"? I read multiple issues like this, perhaps there are some similarities. Related bugs and requests should be grouped together in github somehow I think, there must be a way to do that?

**Comment by Spellhammer** [comment]
Can you confirm whether you're able to replicate this on the latest stable version of Oxygen?

**Comment by drank** [comment]
Yes, I am able to replicate this on 2.2.1 - followed the steps above and got the same results - "flex-direction" is set to "unset" and the change indicator is still on.

**Comment by drank** [comment]
Some additional findings that might help pinpointing the problem.

"flex-direction: unset" is also added to every selector for which you simply change the "display" property. Setting it to anything, e.g. "none", "inline-block", etc., will immediately add a "flex-direction: unset" to the selector.

Here is steps to reproduce:
1. Open a new page with Oxygen
2. Go to Selectors and add a new selector - ".flex-direction-test"
3. Go to Layout and set Display to "none" (or anything but "flex") and save the page
4. Check the selector properties via either:
 a. Checking the DB (SELECT option_value FROM wp_options WHERE option_name = 'ct_custom_selectors'), paste the value in this nice PHP Serialized Editor - https://serializededitor.com/ and search for ".flex-direction-test" OR
 b. Applying the selector to an element and just checking via the Chrome Dev Tools

Please consider this bug with a higher priority - it is quite uncomfortable to manually clear this rogue addition every time via the DB.

Best regards!

**Comment by Spellhammer** [comment]
I was able to replicate this but I'm not entirely sure I understand how this is impacting you.

Here are the steps I took:

1. Create a new Section
2. Set Section to display: flex, saved
3. Deselected display: flex, saved

I now see flex-direction: unset in the CSS. However, by selecting Flex and a flex direction in the GUI the flex direction CSS is corrected. If the element is not being displayed as a flexbox element, flex-direction should have no impact on the layout of child elements.

Can you please clarify the difficulty this is causing for you? Is the concern entirely regarding the settings indicator light being on even though no settings are selected?

**Comment by Gibsonion** [comment]
> I was able to replicate this but I'm not entirely sure I understand how this is impacting you.

Because ID's override classes, any flex CSS via a class, breaks, unset by the ID, and not being able to use classes instead of ID's for style the flex settings is frustrating.

If you're not careful you end up playing a game of Fix CSS.Jenga lol

**Comment by drank** [comment]
@Spellhammer 

Exactly what @Gibsonion said. As I specified in [my post above](https://github.com/soflyy/oxygen-bugs-and-features/issues/53#issuecomment-489425689) even if I select anything other than "flex", the "flex-direction: unset" is still applied and no matter if I revert to default, this addition still stays and gets in the way of other class-based selectors.

At the end, this is a bug and a bug... is a bug :) why not just fix it and be done with it?

Best regards

**Comment by Spellhammer** [comment]
@Gibsonion @drank Thanks for the clarification, that's very helpful.

> At the end, this is a bug and a bug... is a bug :) why not just fix it and be done with it?

We prioritize bug fixes based on user impact and severity, so it's important that I understand  why and how this bug is impacting users' use of Oxygen.

**Comment by benfavre** [comment]
This should be priority number one as you end up loosing all the benefit of using classes, this is a ridiculously old bug, ... wtf

**Comment by Northrook** [comment]
Just want to note that I'm having a somewhat similar bug but effectively with a class.

I have a class that applies a pretty globally used set of rules to a lot of content, but I accidentally selected "Display: flex" while having it active. It now has "flex-direction: unset" applied to it, messing up a fair lot of my design that way.

Happens every so often when I forget which class I'm editing, but now that it happened to a globally used one, it made me look into the problem deeper.

Feel free to reach out if you have any questions.

**Comment by zeidanbm** [comment]
it's been a year since this issue was reported and still not fixed!

**Comment by tingeka** [comment]
If you use something like .p-1 for padding:8px on a section and you set display:flex by mistake, it mess up the whole layout because it applies p-1:not(.ct-section) class, which seems to be more specific and therefore overriding it.

It ends up being a whole bunch of !important. Honestly, this kind of things could be partially solved by being able to reset the default styles applied to a class, which is certainly possible giving the fact that a third party plugin provided such workaround.

**Comment by tingeka** [comment]
@Spellhammer 

If you use something like .p-1 for padding:8px on a section and you set display:flex by mistake, it mess up the whole layout because it applies p-1:not(.ct-section) class, which seems to be more specific and therefore overriding it.

It ends up being a whole bunch of !important. Honestly, this kind of things could be partially solved by being able to reset the default styles applied to a class, which is certainly possible giving the fact that a third party plugin provided such workaround.

It's a serious bug and still around with 3.4.

**Comment by Spellhammer** [comment]
This was inadvertently fixed at some point, as it's no longer reproducible.

If someone else is still running into this, let me know and I'll re-open the issue.
