### ISSUE TITLE
Inconsistent mouse selection in Safari

### ISSUE THREAD

**Issue by 5pinlink** [soflyy/oxygen-bugs-and-features#530]
https://media.giphy.com/media/MFU4P6IvDonMRzUlWC/giphy.gif
See in the GIF above, selection via mouse in Safari is very inconsistent, some times it will stick, others it will not, most common effected is selection of divs, Firefox/Chrome is not affected by this.

**Comment by KittenCodes** [comment]
@5pinlink I'm not able to load your gif - it results in a 404 error. If you're still having problems, please record a quick video in Loom to show what's wrong: https://www.loom.com/.
