### ISSUE TITLE
Edited indicator staying active after removing edits

### ISSUE THREAD

**Issue by 5pinlink** [soflyy/oxygen-bugs-and-features#531]
https://5pin.link/screengrabs/Oxygen_Visual_Editor_-_Controllerism_-_Turntable_Ninja_23227CA0.png

See image above, after removing any edits made in some of the edit panels, the blue edited indicator is staying lit.

**Comment by KittenCodes** [comment]
@5pinlink Please recreate this on a Sandbox site: https://oxygenbuilder.com/try/. Please then send me a link to the Sandbox site and information on which element has had all of the styles removed so that I can take a look.
