### ISSUE TITLE
Icon in Icon Box does not allow border Radius

### ISSUE THREAD

**Issue by 5pinlink** [soflyy/oxygen-bugs-and-features#533]
https://media.giphy.com/media/L1EdfscDUjyx7wbtX9/giphy.gif

See gif above, icons in the icon box can not have border radius set.

**Comment by 5pinlink** [comment]
https://media.giphy.com/media/Sx3wBn8HqGjPjcPgQq/giphy.gif

Icons are just a mess in the Icon box, as you can see in the gif above, background outline doesnt actually work properly either.

**Comment by KittenCodes** [comment]
@5pinlink I'm not able to access either of those gifs - they result in 404 errors.

It is possible to set a border radius on an icon box: https://d.pr/i/i7afxV. To prevent your icon from overflowing past the border, please set the overflow to hidden via Advanced > Layout.
