### ISSUE TITLE
Classes are ignored on Sections

### ISSUE THREAD

**Issue by 5pinlink** [soflyy/oxygen-bugs-and-features#534]
https://media.giphy.com/media/MDlJyGoegR0DUAzUdz/giphy.gif

See gif above, as you can see, what i have designed is not reflected on the front end at all, huge white space above the icons when checking on the front end, V3 is just not working.

**Comment by 5pinlink** [comment]
OK this is caused by having a class on sections, it completely ignores the class when viewing on the frontend.

**Comment by Spellhammer** [comment]
I have confirmed class styling on Sections in Oxygen 3.0 is working as expected.

Please provide steps to replicate the issue in your bug report. If you don't know how to make it happen, you should submit a support ticket at support@oxygenbuilder.com and we can help identify why it's not working on your site.
