### ISSUE TITLE
Notice: Undefined variable: shortcode_output

### ISSUE THREAD

**Issue by kauaicreative** [soflyy/oxygen-bugs-and-features#535]
**Describe the bug**
Notice: Undefined variable: shortcode_output in C:\www\rutherfordbound\wp-content\plugins\oxygen\component-framework\components\classes\span.class.php on line 63

Defining $shortcode_output on line 54 fixes the issue
54 `$shortcode_output=null;`

**Comment by KittenCodes** [comment]
This should be fixed in the latest version of Oxygen.
