### ISSUE TITLE
Modal contents do not scroll

### ISSUE THREAD

**Issue by 5pinlink** [soflyy/oxygen-bugs-and-features#536]
https://media.giphy.com/media/ge8z9szFcfJPVrH8i8/giphy.gif

As can be seen in the GIF above, when you scroll a modal panel, it does not scroll the contents of the panel.

**Comment by srikat** [comment]
https://github.com/soflyy/oxygen-bugs-and-features/issues/279

**Comment by 5pinlink** [comment]
Closing this, see link above.
