### ISSUE TITLE
Selected Element Text Indicator is misaligned

### ISSUE THREAD

**Issue by nshkrsh** [soflyy/oxygen-bugs-and-features#538]
**Describe the bug**
when we select any element in oxygen builder, we see a purple border around that element and the element name on top left corner.
on multiple of my oxygen instances, i find that the element name on top left is misaligned

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
*Yes*

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
*no*

**To Reproduce**
select any element on your oxygen builder area.

**Expected behavior**
the element name must be on top left corner of the selected element.

**What actually happens**
the element name is shown few pixels below the top left corner.
further, the margin drag area starts from middle of the element (see 3rd screenshot below)

**Screenshots**
![image](https://user-images.githubusercontent.com/47569720/64475983-0e3af800-d1a7-11e9-94d5-0036fba639d9.png)

![image](https://user-images.githubusercontent.com/47569720/64475999-30347a80-d1a7-11e9-8399-f389eddf64c0.png)

![image](https://user-images.githubusercontent.com/47569720/64476020-80134180-d1a7-11e9-8212-f6adf71a943b.png)

**Desktop (please complete the following information):**
- OS: Win 10 1903
 - Browser: Brave & Chrome (latest version)
 - Oxygen Version: v2.4.1

**Smartphone (please complete the following information):**
NA

**Comment by KittenCodes** [comment]
@nshkrsh I suspect this is caused by a conflict with another plugin on your site. Please disable all plugins (aside from Oxygen) and check if the labels align correctly. If they do, you can re-enable the plugins one-by-one until you find the conflict.
