### ISSUE TITLE
CRUD create update delete buttons ACF

### ISSUE THREAD

**Issue by Curb72** [soflyy/oxygen-bugs-and-features#539]
Button update
Button delete
Button Create

For dynamic content. Advanced custom fields. 

**What are the use cases for this feature?**
To pages for update create or delete dynamic data from ACF. Either on the frontend or backend. Show button or not show buttons on frontend.

**Comment by Spellhammer** [comment]
I'm not sure what you're requesting. Can you please elaborate and/or provide examples of other places where your request has been implemented?
