### ISSUE TITLE
Classes on Buttons do not effect the text

### ISSUE THREAD

**Issue by 5pinlink** [soflyy/oxygen-bugs-and-features#540]
When using buttons, if you apply a class/ the text is not changed, so for instance you can not change the text color, you have to change the text color at the ID level not the class level for.

**Comment by KittenCodes** [comment]
Please make sure you have removed the text colour from the ID. The class text colour should then be applied.

**Comment by alriksson** [comment]
It is not ID that cause the issue the default selector is: .ct-link-button which overrides on css class or ID. But when using class to style it is not always working with hover text color on the a.link since it is then listing to global a.link text color instead. Which has to be override in advanced panel and not button text hover color. Which isn't working.

**Comment by KittenCodes** [comment]
> It is not ID that cause the issue the default selector is: .ct-link-button which overrides on css class or ID

Here's a link to a page that has a class "button-text" added to the button. The button text is red, which is set via the class.

https://oxygen-qbzgfsm6hh76k.oxygen-demo.qsandbox.me/button/

**Comment by alriksson** [comment]
Specified in the button element or the advanced panel?

1) Specify hover color for the btn
2) Specify another link color and link hover color in global styling.

**Comment by KittenCodes** [comment]
> Specified in the button element or the advanced panel?

Button element: https://d.pr/i/lWZB9M

**Comment by alriksson** [comment]
Do you mind sharing access to the sandbox site?

**Comment by KittenCodes** [comment]
https://oxygen-qbzgfsm6hh76k.oxygen-demo.qsandbox.me/?qcmd=auto_login&user=demo&pass=demo&next=admin

**Comment by markelrayes** [comment]
I am having the same issue. Even though I have no settings inside of my Oxygen ID, I set all my settings inside of a class, the default color is overriding my class.

**Comment by T-21** [comment]
I think this issue still persists. I can't style the button within the class alone, even if you delete everything from the ID.
