### ISSUE TITLE
Button borders edit panel is non persistent

### ISSUE THREAD

**Issue by 5pinlink** [soflyy/oxygen-bugs-and-features#541]
https://media.giphy.com/media/RM0BS4KlPpCRZqupIM/giphy.gif

As can be seen in the gif above, button border controls adjust the border, but when you switch back to the button to re edit, the button border is still teh same, but the panel is completely reset.

**Comment by KittenCodes** [comment]
Duplicate: https://github.com/soflyy/oxygen-bugs-and-features/issues/95
