### ISSUE TITLE
Sider Pagination breaks with Gutenberg

### ISSUE THREAD

**Issue by DominikRapacki** [soflyy/oxygen-bugs-and-features#544]
**Describe the bug**
When using the Gutenberg integration the pagination of the slider brakes
*A clear and concise description of what the bug is.*
i used the make whole page editable in gutenberg function
**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
no
*Yes/No*

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
did not try
*If yes, provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*

**To Reproduce**

**Expected behavior**
pagination should stay as it was before the integration
*A clear and concise description of what you expected to happen.*

**What actually happens**
the css breaks as it looks like
*A clear and concise description of what happens instead of the expected behavior.*

**Screenshots**
https://prnt.sc/p3vfrx
*If applicable, add screenshots to help explain your problem.*

**Desktop (please complete the following information):**
- OS: [e.g. iOS] Windows
 - Browser [e.g. chrome, safari] Chrome
 - Oxygen Version [e.g. 2.2 Alpha] 3.0

**Smartphone (please complete the following information):**
 - Oxygen Version [e.g. 2.2 Alpha]

**Additional context**
*Add any other context about the problem here.*

**Comment by cyberinnovationcom** [comment]
I've encountered the same error when making the page editable for the client the slider breaks. I had to move the testimonial div about the slider and remove the slider for now. 
I tested on two sites and confirmed.. Here's a video showing the issues
https://share.getcloudapp.com/z8uwYR02
Thanks

**Comment by KittenCodes** [comment]
This should be fixed in the latest version of Oxygen and the Gutenberg add-on.
