### ISSUE TITLE
Values disappear from fields in breakpoints other than default (all devices)

### ISSUE THREAD

**Issue by r2cpoo** [soflyy/oxygen-bugs-and-features#554]
**Describe the bug**
*A clear and concise description of what the bug is.*

The bug is when using the Builder Menu on the left, usually after saving, some entered values (alpha/numeric) no longer display in the value's field.

For example, if you set a margin or padding value for a div and then save (page, template, etc) exit oxygen back to WP admin area and then re-open what you just saved, often times the value fields you just entered values into will be empty or in some cases will show the default value, usually the text being a darker color. 

This has existed since first release, i just figured it was on the backburner for things to get to when there was time. 

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
*Yes/No* Yes

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
Yes
*If yes, provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*

http://frantic-opossum.w6.wpsandbox.pro?upass=NRDxDc20j46o

**To Reproduce**
1. Go to Oxygen>Templates> 'test template.'
2. Click on 'Structure Menu' , Change breakpoint to anything but "All Devices"
3. Check properties for any div with round borders
4. No values are present

**Expected behavior**
*All values for any div, section, etc should always be present when viewing its properties *

**What actually happens**
*A clear and concise description of what happens instead of the expected behavior.*
It seems to forget to render the value in the field.

**Screenshots**
*If applicable, add screenshots to help explain your problem.*

**Desktop (please complete the following information):**
- OS: [e.g. iOS] Windows 7Pro, Acer Chromebook with 1080p screen
 - Browser [e.g. chrome, safari] Chrome, Opera
 - Oxygen Version [e.g. 2.2 Alpha] 3,0

**Smartphone (please complete the following information):**
 - Oxygen Version [e.g. 2.2 Alpha]
Haven't tried editing on a  smartphone yet

**Additional context**
*Add any other context about the problem here.*

**Comment by KittenCodes** [comment]
@r2cpoo I'm not able to reproduce this. If I set a value (for example, a width) on the red div at 992px then the value is shown when I reload the builder.

If this is still a problem, please record a quick video showing the steps you're taking (you can use Loom for this: https://www.loom.com/) and send it to support@oxygenbuilder.com so that we can take a look.
