### ISSUE TITLE
Text in O2 Gutenberg Block isn’t reliably updated

### ISSUE THREAD

**Issue by sfries79** [soflyy/oxygen-bugs-and-features#555]
**Describe the bug**
When I add a block, I built in Oxygen, to the Gutenberg editor and try to change a heading (only element I tested) inside it, it isn’t updated to the page. It is updated in the following cases:

- I just opened the editor and made one change. As soon as I’m trying to edit the text again without closing the editor it isn’t saved.
- I edit another standard Gutenberg text block. That somehow forces the change in my O2 block to be saved.

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
I stumbled across this while trying something unrelated in the sandbox.
The only other plugin I installed is ACF and deactivating it doesn’t change the behavior.
I also replicated the issue on an editable page I am currently working on.

**To Reproduce**
1.	Create a simple block in O2 (section and heading in my case)
2.	Create a page and use the block (write something in site the heading element)
3.	Publish the page
4.	Admire your work in another tab/browser without closing the editor
5.	Switch back to the editor and make another change to the heading
6.	Update the page
7.	Reload the page in the other tab/browser and don’t see anything changing

**Expected behavior**
Information edited in Gutenberg should appear on the page...

**Comment by KittenCodes** [comment]
Replicated internally.

**Comment by KittenCodes** [comment]
@sfries79 This should be fixed in v1.1.1 of the Gutenberg add-on.
