### ISSUE TITLE
Section background in Gutenberg block loses overlay color

### ISSUE THREAD

**Issue by sfries79** [soflyy/oxygen-bugs-and-features#556]
**Describe the bug**
A Gutenberg block with background image and overlay color loses the overlay color when the background image is changed in Gutenberg.

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
This behavior is present in all installations I tried including sandbox.

**To Reproduce**

1. Create a block containing a section with background image and overlay color
2. Use it in Gutenberg
3. Change the image in Gutenberg
4. Overlay color disappears

**Expected behavior**
I would expect the overlay color to stay the same as the image is changed. It would be even better if the client could choose from a set of overlay colors that are definable in O2.

**What actually happens**
Overlay color is lost, potentially making text unreadable.

**Comment by sfries79** [comment]
This issue isn’t reproduceable in 3.0.1 RC 1 since there is no longer an option to change section backgrounds. I hope this isn’t intentional because the last thing Gutenberg Integration needs is less features.

**Comment by KittenCodes** [comment]
@sfries79 This is working correctly in Oxygen 3.1. Section backgrounds retain their overlay when the image is changed in Gutenberg.
