### ISSUE TITLE
More roles in "Role Manager"

### ISSUE THREAD

**Issue by peterpinkster** [soflyy/oxygen-bugs-and-features#563]
**Describe the feature you'd like to see included in Oxygen.**
I would like to see more roles in Role Manager. So I can give my clients more freedom to change text and images or prehaps add blockes, sections etc WITHOUT destroying the design. Or change order of the sections without messing-up.

**What are the use cases for this feature?**
More freedom for the client. I am scared when they open Oxygen. But It would be great if they can open it and have less privileges. I would like they can change only move and edit some content.in my opinion. Gutenburg sucks on this. 

I would love to see a special Role for my clients, so (for example) they can safely open Oxygen and only change:

-  text
(with some basics of styling)
- images
(with some basic settings)
- background
(color, image fixed, parralax)
- colors 
(only from the settings/Global styles/Global Colors)
- Order of each section.
- prehaps some animation settings, effects or transformations?

It's just an idea because my client isn't satisfied.  she prefers to have Elementor 👎 

As designer, we don't have to worry too much, and the client can change some content seeing the final result of it.

**Examples of this feature or functionality.**
WorPress Plugin Brizy have it. I also have a lifetime licence with them.  Brizy have some really nice features.. and a great User Interface. But for me as developer its limited. 

p.s. Brizy have an AMAZING way to add contactforms!

**Comment by Martin-1** [comment]
Yes, yes, yes and a final huge YES! I have said it before. But front-end editors (or close to it the way Oxygen deals with it) are very popular. Even my clients know about them.

Customers want to SEE what happens on the site when they change stuff. Gutenberg has been passed by the big guys and Oxygen can't fall behind. Once you fall behind it is very difficult ot get back to the front.

**Comment by alpabuz** [comment]
+1

**Comment by bkno** [comment]
+1

Primarily I only believe clients should edit text / image / photo / headers / background. I don't think they need to be able to add new elements onto the page, just update what is there.

One way I see this working is to be able to 'lock' certain sections or templates so only the admin can update them, or specify a section to be 'client editable'.

The only approach I can think of for now is to store content intended to be edited by the client in ACF fields but they can't see what it looks like when editing.

**Comment by KittenCodes** [comment]
See Edit Mode added in v3.6: https://oxygenbuilder.com/documentation/other/client-control/
