### ISSUE TITLE
Conditional for Repeaters Inside Repeaters

### ISSUE THREAD

**Issue by christianmagill** [soflyy/oxygen-bugs-and-features#564]
**Describe the bug**
*A clear and concise description of what the bug is.*

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
Yes

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
*If yes, provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*

http://aquamarine-dugong.w5.wpsandbox.pro

User: admin / Password: admin

**To Reproduce**
1. Edit Homepage In Oxygen
2. Click on .phone-numbers div, highlighted with red border.
3. Click conditional icon
4. Choose Dynamic Data
5. Try and set the condition based on whether there are phone numbers in the ACF repeater.
6. Be disappointed.

**Expected behavior**
We should be able to select the phone_numbers field as a value for the condition.

**What actually happens**
Those fields are not available.

**Desktop (please complete the following information):**
- OS: Mac OS
 - Browser Chrome
 - Oxygen Version 3.0

**Comment by alriksson** [comment]
Experience another issue with repeaters module. It does not listen to conditions. Right now the workaround to do not display repeater module if ACF repeater is empty is by wrapping the repeater in a div. Then set the condition on the div.

**Comment by KittenCodes** [comment]
@christianmagill 

This is happening because you are trying to use the condition in a different repeater. To be able to access the "Phone Number" repeater field, you need to use it on an element that is within the repeater that has access to that data (in your example page, it's the repeater with the ID 668).
