### ISSUE TITLE
Columns With Fade Up Effect Disappear On The Front Ends

### ISSUE THREAD

**Issue by greatscottd** [soflyy/oxygen-bugs-and-features#565]
Hi All,
I am having issues when I attempt to Animate on Scroll - columns (fade up).

This is the problem: After I animate several rows of columns with the fade up effect, and then save, all the columns disappear on the front end...

...They show (and animate) if I'm logged in to WordPress on the same browser instance, but not if I open a new browser session or use incognito.

- I have attempted to clear the server cache
- I have re-signed the shortcodes,  with no avail.

**Comment by KittenCodes** [comment]
@greatscottd Are you able to replicate this on one of our Sandbox sites: https://oxygenbuilder.com/try/? If you can, please add the one click login for the site to this issue.
