### ISSUE TITLE
Template Bug: "Edit" Vs "Edit with Oxygen Differences

### ISSUE THREAD

**Issue by greatscottd** [soflyy/oxygen-bugs-and-features#566]
Please follow the images in the comment below:

**Comment by greatscottd** [comment]
Just follow these images with explanations in order to see the issue...

![1](https://user-images.githubusercontent.com/55542752/65247847-6bad3e00-daf1-11e9-9f53-6dbd0646b850.jpg)

![2](https://user-images.githubusercontent.com/55542752/65247867-710a8880-daf1-11e9-9d7b-9c9c3d3ad54e.jpg)

![3](https://user-images.githubusercontent.com/55542752/65247897-84b5ef00-daf1-11e9-87ad-0192df56ea89.jpg)

![4](https://user-images.githubusercontent.com/55542752/65247908-8a133980-daf1-11e9-84d9-ea7ab3e196db.jpg)

**Comment by wplit** [comment]
there is no 'edit in Oxygen' link. You must be using a plugin or a code snippet that is adding this link.

**Comment by wplit** [comment]
I can see now you're using the Oxygen toolbar plugin, this is where the 'edit with Oxygen' link is coming from. It's not a part of Oxygen itself.

**Comment by greatscottd** [comment]
OK, thanks for the reply. I'll remove.

Are there any known issues with Asset Cleanup plugin?

Scott
