### ISSUE TITLE
Notice: Undefined variable: shortcode_output

### ISSUE THREAD

**Issue by inferno-adam** [soflyy/oxygen-bugs-and-features#573]
**Describe the bug**
When WP_DEBUG is set to true, a notice is shown on the page:

`Notice: Undefined variable: shortcode_output in /var/www/html/wp-content/plugins/oxygen/component-framework/components/classes/span.class.php on line 63`

This is occuring when using a 'Text' element and inserting a variable from the 'Data' button with either the 'Page Title' or 'Content'. I suspect this could also be an issue with other variables but I have not tested it. If WP_DEBUG is set to false, the notice goes away. However, this is not ideal for testing in a development or staging environment.

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
Yes

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
No, but I suspect it is because WP_DEBUG is set to false. 

**To Reproduce**
1. Set WP_DEBUG to true.
2. Add a new page and set the title and add content.
3. Create a new Oxygen template.
4. Add a Heading and/or a Text element.
5. Edit the element(s) and click 'Insert Data'.
6. Insert either the Post Title or Content.
7. Save template and view the page on the frontend of the site.
8. Receive notice.

**Expected behavior**
No notice shown.

**What actually happens**
Notice is shown.

**Screenshots**
<img width="1321" alt="Oxygen Screen Shot" src="https://user-images.githubusercontent.com/8921196/65425441-d8129080-ddc2-11e9-9a16-614f7a5d677f.png">

**Desktop (please complete the following information):**
- OS: MacOS
- Server OS: Ubuntu 18.04 + Apache
- Browser: Chrome
- Oxygen Version: 3.0

**Comment by KittenCodes** [comment]
@inferno-adam This should be fixed in v3.1.
