### ISSUE TITLE
Loosing border width "px" units after setting it up after unset

### ISSUE THREAD

**Issue by shock2d** [soflyy/oxygen-bugs-and-features#579]
**Describe the bug**
*A clear and concise description of what the bug is.*

Not able to setup a border after unsetting it as it's loosing units type.

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**

Yes

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
*If yes, provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*

http://mushy-cottonmouth.w5.wpsandbox.pro/?ct_template=sidebar&ct_builder=true

**To Reproduce**

1. Create a template and assign it to anything
2. add text element and Save
3. set border like 5px solid #ff55ff, Save
4. unset all borders, Save
5. Try to setup border again like 25px solid #720101, Save

**Expected behavior**

New 25px wide border apears

**What actually happens**

Borders are being set wiout unit value:
    border-top-width: 22;
    border-right-width: 22;
    border-bottom-width: 22;
    border-left-width: 22;

**Screenshots**
![chrome_3AGwjfEUQ7](https://user-images.githubusercontent.com/6713025/65585129-a3513580-df8a-11e9-9c52-fe9220f2fa93.png)

**Desktop (please complete the following information):**
pc
win10
chrome 77
oxygen 3

**Comment by KittenCodes** [comment]
@shock2d I'm not able to reproduce this in the latest version of Oxygen. If you're still having problems, please email support@oxygenbuilder.com so that we can take a look at your site.

**Comment by StaggerLeee** [comment]
This bug is around in latest Beta version.
Switching to "em", Save, and back to "px" solves problem.
