### ISSUE TITLE
Post Parent ID condition is ignored... Bug found, FIX INCLUDED

### ISSUE THREAD

**Issue by yankiara** [soflyy/oxygen-bugs-and-features#580]
**Describe the bug**
It seems that Post Parent ID condition is not working at all.
Whatever the operator or value I use, it looks like it is ignored.

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
Yes

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
Yes: http://fragile-cardinal.w5.wpsandbox.pro/

**To Reproduce**
1. Create a blank page and select a parent (for instance child of Sample Page for a blank install)
2. Edit content with Oxygen (no need to create a template for this)
3. Add for instance a H1 heading
4. Add condition with "Post Parent ID", operator "==", and as the value the parent page ID
5. Try to invert the condition with operator "!="
6. Try all the operators with different values (the real parent ID or others)

**Expected behavior**
The heading should appear when Post Parent ID equals the actual parent ID of the page (selected at creation).

**What actually happens**
Whatever the operator or value, it nevers shows up.

**Screenshots**
*If applicable, add screenshots to help explain your problem.*

**Desktop (please complete the following information):**
- OS: Windows
 - Browser: Firefox & Chrome
 - Oxygen Version: 3.01 RC2

**Comment by yankiara** [comment]
I actually found the bug.

In file `component-init.php`, function `condition_post_parent_id_callback()` is wrong:

function condition_post_parent_id_callback($value, $operator) {
	$current_post_parent_id = wp_get_post_parent_id(get_the_ID());
	oxy_condition_eval_int($current_post_parent_id, $value, $operator);
}

This is the right code (tested and validated):

function condition_post_parent_id_callback($value, $operator) {
	$current_post_parent_id = wp_get_post_parent_id(get_the_ID());
	**_$value = intval($value);_**
	**_return_** oxy_condition_eval_int($current_post_parent_id, $value, $operator);
}

Could you please correct this in next release?

Thx, Yan.

**Comment by KittenCodes** [comment]
#719

**Comment by KittenCodes** [comment]
Fixed in v3.2.
