### ISSUE TITLE
Conflict with Toolset (with Video Explanation)

### ISSUE THREAD

**Issue by ViktorIwan** [soflyy/oxygen-bugs-and-features#583]
**Describe the bug**
OxygenBuilder cancel the load of important meta paramater in Custom Post Type with Toolset that has Relationship (One To Many)

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
Yes

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
*If yes, provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*

**To Reproduce and Expected Behavior **
See The Video for clear explanation 
https://www.screencast.com/t/7ygWyzFUigHU

**Comment by KittenCodes** [comment]
@ViktorIwan This should be fixed in the latest version of Oxygen.
