### ISSUE TITLE
CSS included in reverse order in Oxy 3.1

### ISSUE THREAD

**Issue by lucas-pelton** [soflyy/oxygen-bugs-and-features#584]
**Describe the bug**
After updating from 2.4.1 -> 3.0.1 universal.css is last in the stack of stylesheets instead of first in line.

Source before upgrade:
![image](https://user-images.githubusercontent.com/1626520/65722850-ff3abd80-e061-11e9-93c2-87c76c79f7ee.png)

Source after upgrade:
![image](https://user-images.githubusercontent.com/1626520/65722863-0c57ac80-e062-11e9-9097-913e261e3164.png)

**Comment by ivodolenc** [comment]
> **Describe the bug**
> After updating from 2.4.1 -> 3.0.1 universal.css is last in the stack of stylesheets instead of first in line.

As Lucas pointed out, the problem is with css loading (wrong priority) and minifying (the universal css is no longer minified). Also, AOS css seems to load in the footer and not in the header.

**Comment by KittenCodes** [comment]
@lucas-pelton Please can you let me know what problem the changed order of the files is causing you?

**Comment by lucas-pelton** [comment]
Rules defined in fresh-site-builds-1223.css that are supposed to override global styles in universal.css do not function as expected when universal.css is enqueued last.

In general, stylesheets should be enqueued from least-specific (universal) to most-specific (main template -> category template -> page template) to preserve the cascading nature of styling rules

**Comment by lucas-pelton** [comment]
I just ran across another instance of an issue caused by this wherein a page width defined for a specific page is overridden by the universal page width.

The stack is:
template.css -> ~no page width setting~
page.css -> ~homepage width1080~
uinversal.css -> universal page width 1120

Definitely, universal.css should be the first in the list, followed by template.css then page.css

**Comment by lucas-pelton** [comment]
@KittenCodes With the 3.2 update, I now have to TURN OFF css caching because universal.css is overriding several styles defined in stylesheets inappropriately placed before universal.css.

It's fairly clear here that this issue does NOT "Need more info" and universal.css should simply be first in line in the CSS stack.

**Comment by KittenCodes** [comment]
Thanks @lucas-pelton. I've reported this internally.

**Comment by lucas-pelton** [comment]
Thank you! Also, I'm noticing wildly different rules are applied when toggling the "Cache CSS" option.

When caching is turned on, universal.css doesn't even contain some of the rules I would expect to see, and when turned off, the ?xlink=css&ver=XXXXX _does_ include the expected rules. I notice the issue on multiple sites I've built, but am having a hard time reproducing in the sandbox. Can I clone one of the sites with issues and provide a login to access the cloned site to see the issue?

I'm not sure if it is related to this issue #584 and am happy to open a new issue if necessary.

**Comment by KittenCodes** [comment]
@lucas-pelton 

> Can I clone one of the sites with issues and provide a login to access the cloned site to see the issue?

That would be great, yes please. Could you send the site details to support@oxygenbuilder.com so that we can take a look?
