### ISSUE TITLE
Header row does not render div that is an immediate child of a row left/center/right

### ISSUE THREAD

**Issue by lucas-pelton** [soflyy/oxygen-bugs-and-features#585]
**Describe the bug**
A DIV placed as an immediate child of a header row section (left,center,right) does not render in final HTML. Other items that are direct children of the same section DO render.

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
Yes

**To Reproduce**
Add a DIV to a header row section and see that it does not render on the front end. Add a non-DIV and see it render.

**Screenshots**
Back-end Structure
![image](https://user-images.githubusercontent.com/1626520/65799811-ded63600-e129-11e9-9754-c45117876e72.png)

Front-end HTML
![image](https://user-images.githubusercontent.com/1626520/65799835-ed245200-e129-11e9-8152-027295a46ee7.png)

**Desktop (please complete the following information):**
- OS: Win10
 - Browser Current Chrome
 - Oxygen Version 3.0.1

**Comment by KittenCodes** [comment]
@lucas-pelton I'm not able to replicate this on a clean Sandbox site. If you're still able to reproduce this issue, please send us a link to the site so that we can take a look.

You can create a Sandbox site here: https://oxygenbuilder.com/try/.

**Comment by lucas-pelton** [comment]
I'm also unable to recreate this issue, but I'll gather more information for you if it crops up again...
