### ISSUE TITLE
The background image options for the Section do not work for different breakpoints in 3.0.1

### ISSUE THREAD

**Issue by alpabuz** [soflyy/oxygen-bugs-and-features#586]
When setting a background image for a section starting with version 3.0.1, styles are assigned inline, which makes it impossible to apply different settings for different breakpoints: 
<img src="http://s1.bild.me/bilder/110417/2504516screenshot_2019-09-28_002.png" style="max-width:100%">

In previous versions, this was possible and, for example, it was possible to set a different background image for the mobile width or change its position.

Workaround at the moment:
clear all settings for the section ID, assign a class to the section and set the necessary parameters for the class, then everything will work correctly.

**Comment by jamescrabb** [comment]
Needs addressing

**Comment by Shirkit** [comment]
Here's also a post I've made: https://www.facebook.com/groups/1626639680763454/permalink/2579536175473795/

**Comment by Spellhammer** [comment]
Fixed in 3.2 beta 1.
