### ISSUE TITLE
With custom height for background, the width becomes 0%

### ISSUE THREAD

**Issue by saeedcpo** [soflyy/oxygen-bugs-and-features#588]
On "onepage2" template, the background for some sections that has custom size don't show in frontend, but it shows on back-end.
When I change the size to Cover or other settings I can see the background.

There was no need to try troubleshooting steps. I replicated the issue in fresh sandbox
https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**

I replicated the issue on this sandbox:
http://poor-unicorn.w6.wpsandbox.pro?upass=K9h2P20KlbbW

**To Reproduce**
1. Go to  http://poor-unicorn.w6.wpsandbox.pro/?ct_builder=true
2. Look at the background setting for "Goodbye Template" sections. It has a background with dots with custom size of "height:130px" and "width:[emopty]"
2. Look at the "Goodbye Template" that has a background with dots
![image](https://user-images.githubusercontent.com/40629665/65858711-8003fd00-e373-11e9-9b3a-6ec5b815e844.png)
3. Save the page
4. Go back to fronted. Look at the "Goodbye template" sections. Dots has gone. with developer tools of browser you can notice that the width of the background has been set to "0%"
![image](https://user-images.githubusercontent.com/40629665/65858894-e8eb7500-e373-11e9-9d2b-d571b10da547.png)
![image](https://user-images.githubusercontent.com/40629665/65859149-67e0ad80-e374-11e9-9084-e6a2fca19fe1.png)

**Expected behavior**
I expected to see the background as I set and as I saw in the back-end.

**What actually happens**
The width sets to 0% instead of "auto"

**Desktop (please complete the following information):**
- OS Windows
 - Browser Chrome
 - Oxygen Version 3.0.1

**Comment by saeedcpo** [comment]
I know temporary fix is to put the appropriate size in width (in this case it is around 70px).

**Comment by KittenCodes** [comment]
@saeedcpo I wasn't able to find the "Goodbye template" on the Sandbox site. If you're still having problems with the background image in the latest version of Oxygen, please send us a link to where we can see this happening on the Sandbox site.
