### ISSUE TITLE
Have to resave templates after changing domain name.

### ISSUE THREAD

**Issue by benddesign** [soflyy/oxygen-bugs-and-features#589]
I've had this error occur on a couple different websites now. After updating the domain to launch the website, the templates  do not work correctly. No header or footer from the main template and none of the other templates work correctly either (i.e. a custom filterable gallery is only displaying titles but no images. After following the troubleshooting guide, all of the issues are still present. I happened to view my main template in the Oxygen editor and everything looked perfect. After saving the template it started working correctly again. After saving the rest of the templates from within the Oxygen editor they started working as well.

**Comment by shoelaced** [comment]
Re-signing the shortcodes worked for me.

**Comment by KittenCodes** [comment]
@benddesign Please follow these steps after changing domain or migrating a site:

Save your permalinks twice via Settings > Permalinks
Resign your shortcodes via Oxygen > Settings > Shortcodes
Regenerate your CSS cache via Oxygen > Settings > CSS Cache

​If you have any caching plugins installed, you will also need to clear the caches.
