### ISSUE TITLE
(3.1 Alpha) Pagination needs work

### ISSUE THREAD

**Issue by Deanphillips** [soflyy/oxygen-bugs-and-features#593]
I was pretty excited to see that pagniation was part of the repeater, but now having used it, I don't think it's that great to be honest.

1. There are limited options (there's been a bunch of discussions, including one by me and how the pagination could work)
2. It also doesn't place the pagination in the center of the repeater, but the div, which creates a poor UX
<img width="1506" alt="Screenshot 2019-10-03 at 14 39 07" src="https://user-images.githubusercontent.com/21025321/66131877-16daee80-e5ec-11e9-9dcc-0e83c4db9b5c.png">
<img width="582" alt="Screenshot 2019-10-03 at 14 40 25" src="https://user-images.githubusercontent.com/21025321/66131878-16daee80-e5ec-11e9-9696-0fa19d6e3792.png">

3. The repeater name covers it too

**Comment by Spellhammer** [comment]
Repeater pagination will be improved dramatically in the beta.

**Comment by jkarelbroer** [comment]
Would it be possible to set the default font size empty, so pagination is default invisible? Otherwise we have to walk through all existing pages that contain a Repeater component...
