### ISSUE TITLE
(3.1 Alpha) ACF Repeater causing 500 error

### ISSUE THREAD

**Issue by Deanphillips** [soflyy/oxygen-bugs-and-features#594]
Hey guys,

After upgrading to the latest version (3.1) from 3.0.1 I can no longer load my ACF repeater.

I've contacted my host and they said it's O2's issue:

[Thu Oct 03 14:09:46.484438 2019] [proxy_fcgi:error] [pid 12902] [client 127.0.0.1:49828] AH01071: Got error 'PHP message: PHP Fatal error: Uncaught Error: Call to a member function reset_postdata() on null in /home/250792.cloudwaysapps.com/xsbhtkabyq/public_html/wp-content/plugins/oxygen/component-framework/components/classes/dynamic-list.class.php:319\nStack trace:\n#0 /home/250792.cloudwaysapps.com/xsbhtkabyq/public_html/wp-content/plugins/oxygen/component-framework/components/classes/dynamic-list.class.php(415): Oxygen_VSB_Dynamic_List->resolve_recursively(Array)\n#1 /home/250792.cloudwaysapps.com/xsbhtkabyq/public_html/wp-content/plugins/oxygen/component-framework/components/classes/dynamic-list.class.php(502): Oxygen_VSB_Dynamic_List->parse_map_recursively(Array, Array, NULL, Array)\n#2 /home/250792.cloudwaysapps.com/xsbhtkabyq/public_html/wp-content/plugins/oxygen/component-framework/components/layouts/dynamic-list.php(22): Oxygen_VSB_Dynamic_List->parse_shortcodes_map(Array, Array, NULL, Array)\n#3 /home/250792.cloudwaysapps.com/xsbhtkabyq/public_html/wp-includes/template-loader.php(78): include('/hom...', referer: http://wordpress-250792-930666.cloudwaysapps.com/toolbox/?ct_builder=true&ct_inner=true&oxygen_iframe=true

**Comment by Spellhammer** [comment]
@Deanphillips How's the ACF repeater configured? Please provide as many details as possible so that we can try to replicate the problem.

**Comment by Deanphillips** [comment]
podcasts Archive - Thom Underwood Wellness - Watch Video
<https://www.loom.com/share/43ed49883a564802bc5de934a1f03779>
<https://www.loom.com/share/43ed49883a564802bc5de934a1f03779?utm_medium=gif>

It's a repeater inside a repeater, however it fails when loading the parent
(as shown in the video)

and this happens with no plugins loaded too (but O2)

https://www.loom.com/share/090bfa1688fa49f4bf5e22afbac19eed (attempt 2)

**Comment by Deanphillips** [comment]
@Spellhammer Were you able to replicate this?

**Comment by KittenCodes** [comment]
@Deanphillips If you still have an environment where this is happening, please send login details to support@oxygenbuilder.com so that we can take a look.

**Comment by Deanphillips** [comment]
Weirdly the release that came out after this had fixed it. The issue didn't
happen again :)

**Comment by KittenCodes** [comment]
@Deanphillips Excellent, thank you for letting me know!
