### ISSUE TITLE
[2.2 RC1] - Webfonts not loading in builder

### ISSUE THREAD

**Issue by benhohner** [soflyy/oxygen-bugs-and-features#60]
**Describe the bug**
After updating to 2.2RC1, webfonts do not load in builder. 

- Only the Display Font loads, body font does not load. If I go to global settings -> fonts and change one of the font settings that haven't loaded, the font then loads, but this only lasts until the page is refreshed.
- During my experimentation, I tried adding an additional font through global settings and saving the page. After this point, none of the webfonts loaded. I was unable to reproduce this behavior in the demo

Note: web fonts do load properly in the front end, they just don't load/display in the builder.

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
Yes

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
Note: in builder Playfair Display loads, but not Roboto.
http://adventurous-skipper.w5.wpsandbox.pro?upass=Dz3N0euXH6d5

Backend: http://adventurous-skipper.w5.wpsandbox.pro/?ct_builder=true&ct_inner=true
Frontend: http://adventurous-skipper.w5.wpsandbox.pro

**To Reproduce**
1. Load the builder
2. In the global settings select at least two webfonts
3. Save and refresh the page.
4. If two webfonts, only the first loads (tested with playfair display for display and roboto for body)
5. If three or more webfonts, sometimes none load (unable to reproduce in demo, but may be related)

**Expected behavior**
Webfonts should load in the builder in the exact same manner as they do in the front-end

**What actually happens**
Webfonts don't load in builder

**Screenshots**
Second font not working in builder with two webfonts selected
![2019-02-09 15_41_17-nvidia geforce overlay](https://user-images.githubusercontent.com/1463217/52526058-38fcb680-2c81-11e9-8a06-90481fa6d4bf.png)

Fonts still load properly on frontend
![2019-02-09 15_41_25-sandbox - just another wordpress site](https://user-images.githubusercontent.com/1463217/52526060-4d40b380-2c81-11e9-9a91-8382eedc3234.png)

**Desktop (please complete the following information):**
- OS: Windows 10 Version 10.0.17763 Build 17763
 - Browser Chrome  73.0.3683.27
 - Oxygen Version 2.2RC1

**Comment by Spellhammer** [comment]
Replicated and reported.

**Comment by louisreingold** [comment]
This is fixed in RC2: https://oxygenbuilder.com/2019/02/15/oxygen-2-2-release-candidate-2-now-available/

**Comment by Spellhammer** [comment]
Fixed in Oxygen 2.2.
