### ISSUE TITLE
Add a button to reset styles on element IDs and classes

### ISSUE THREAD

**Issue by KittenCodes** [soflyy/oxygen-bugs-and-features#605]
From a customer in a support ticket:

Add a button to reset the styles on elements and classes.

**Comment by alriksson** [comment]
+1

**Comment by maltmann-muc** [comment]
+1

**Comment by KittenCodes** [comment]
Duplicate: https://github.com/soflyy/oxygen-bugs-and-features/issues/119#issuecomment-540539814
