### ISSUE TITLE
Compact UI design

### ISSUE THREAD

**Issue by aformal** [soflyy/oxygen-bugs-and-features#607]
**Describe the feature you'd like to see included in Oxygen.**
It’s possible to provide a denser ui design, while even increase the clarity.

**What are the use cases for this feature?**
1. It will reduce scrolling through the options on smaller screens. -> enhanced usability, saving time
2. Properties are easier to spot. -> enhanced usability, saving time

**Examples of this feature or functionality**
I added a sketch, so you can understand the enhancement.

<img src="https://user-images.githubusercontent.com/56085341/68131097-bdcce600-ff1c-11e9-9920-a5e24da90b53.png" alt="background" width="300"/>

**Comment by Ikpixel** [comment]
O2 need to implement all your ideas. Nice work.

**Comment by demetre19** [comment]
+1

**Comment by alriksson** [comment]
Add responsive options to settings panel to push for more responsive settings in the global settings as well.

**Comment by alriksson** [comment]
@aformal Would be nice to see a more compact and improved element panel as well

Inspiration:
https://theme.co/changelog/img/multi-pro-3.0.0-x-7.0.0-cs-4.0.0-elements-pane-01.png

**Comment by Deanphillips** [comment]
Hey @aformal  

Any chance, you'd be able to look at placing the gradient in a different position and implement something like the attached (background position) indicator. 

It makes no sense that gradient is so near the bottom, that is doesn't have a wheel and I think adding a background stacking option in the UI like I suggested here would be ace 

Stacking images: https://github.com/soflyy/oxygen-bugs-and-features/issues/22
Stacking borders: https://github.com/soflyy/oxygen-bugs-and-features/issues/636 (for the border UI)

<img width="245" alt="Screenshot 2019-10-27 at 03 31 40" src="https://user-images.githubusercontent.com/21025321/67629181-ad58a380-f86a-11e9-94ab-4963f4bb7638.png">
<img width="270" alt="Screenshot 2019-10-27 at 03 16 25" src="https://user-images.githubusercontent.com/21025321/67629182-ad58a380-f86a-11e9-88a6-354cf46016d4.png">

**Comment by Deanphillips** [comment]
As much as I love the compact side, I do think icons serve flex well - attached
<img width="241" alt="Screenshot 2019-10-27 at 03 39 33" src="https://user-images.githubusercontent.com/21025321/67629297-7df66680-f86b-11e9-998f-efd26aeffb57.png">


Yellowpencils latest UI update seems very inline with yours, but not as compact

**Comment by aformal** [comment]
> As much as I love the compact side, I do think icons serve flex well - attached

@Deanphillips:

Yes, you are right. I also thought about using Icons. I didn't include them in the sketch, because it was more about proving a compact design could work. 

I also didn't do it because the icons have to change depending on the flex direction. I just checked Webflow and they have exactly this changing icons. It looks like they their implementation makes 
 sense and this is the way to go.

**Comment by aformal** [comment]
> Any chance, you'd be able to look at placing the gradient in a different position and implement something like the attached (background position) indicator.

@Deanphillips:
You have a good point there. I will take a look at it as soon as I find some time.

**Comment by aformal** [comment]
> @aformal Would be nice to see a more compact and improved element panel as well

@alriksson:
You are right, this part needs some work, too.

**Comment by Gibsonion** [comment]
+1

**Comment by alanzirpoli** [comment]
+1

**Comment by profiVideos** [comment]
+1

**Comment by wpsumo** [comment]
Some more inspiration from the theme.co team and pro builder:
https://theme.co/content/status-report-august-03-2020

Higher contrast and more modern design.

**Comment by avocadesign** [comment]
+1

**Comment by schietegal** [comment]
+1

I think this is the reason why relatively few people (compared to Elementor) use Oxygen. The website, the interface, the templates. It's about time that the CD gets some attention. See Webflow, wonderful design, super usability and it's getting bigger and bigger.

**Comment by octapress** [comment]
+1

How about possibility to install themes.
Community pool of oxygen themes could be kind of cool.

**Comment by Spellhammer** [comment]
UI overhauled in 4.0 alpha 1.

**Comment by wpsumo** [comment]
Think it's worth to keep this ticket as this suggestion of improve UX and color and design is much more appealing than 4.0 it's still not that sharp as the design example above. So use this to continue going towards that direction.

![](https://user-images.githubusercontent.com/56085341/68131097-bdcce600-ff1c-11e9-9920-a5e24da90b53.png)

**Comment by avocadesign** [comment]
I'd agree that while 4.0 alpha does make some improvements - there are some excellent ideas here that are not touched on at all in the UI revamp

**Comment by wpsumo** [comment]
Look at all @aformal example they are great color combination.

Look at theme.co's pro builder high contrast and great color combination. 
https://fb.watch/aO1btXPXGn/
https://fb.watch/aO1cvPsm2h/
