### ISSUE TITLE
Indicate if a property is already styled by a class, id or if it is inherited form a parent.

### ISSUE THREAD

**Issue by aformal** [soflyy/oxygen-bugs-and-features#608]
**Describe the feature you'd like to see included in Oxygen.**
While using Oxygen, I often find myself checking the developer tools to figure out where a style is coming form. At bigger or revisited project the amount of double checking even increases.

A simple tag like label next to the property label could solve this. It would show the following:

1. the property is already styled by an id
2. the property is already styled by a class
3. the property is inherited 

**What are the use cases for this feature?**
1. less double checking between Oxygen and the browser -> enhanced usability, saving time
2. writing less redundant  CSS

**Examples of this feature or functionality**
I added a sketch, so you can understand the feature.

<img src="https://user-images.githubusercontent.com/56085341/68157015-1e741700-ff4d-11e9-9185-fa1a7b268c4d.gif" alt="id_class_label" width="300">

**Comment by Martin-1** [comment]
A massive plus one from me on this one ➕1

**Comment by dmsdesignz** [comment]
1000+

**Comment by adrien-robert** [comment]
Wow, amazing!!! +100

**Comment by ziogio98** [comment]
Amazing idea!

**Comment by prmnth** [comment]
This would greatly improve the oxygen work flow .. Best enhancement. Hope they implement this in second set of improvements in 3.1

**Comment by 5pointDigital** [comment]
I hate begging. PLEASE do this!

And fix the disappearing Effects tab.

And make the CSS/JS panel more user-friendly.

**Comment by wkoehn** [comment]
This would be awesome!

**Comment by wkoehn** [comment]
This would go great with the ability to easily move the style to the class from the id. Something like this has been mentioned here before... https://github.com/soflyy/oxygen-bugs-and-features/issues/36

**Comment by wpdoit** [comment]
+1

**Comment by Dunkh4n** [comment]
Massively agree with that..
I think the color hint with just the border of the bouton would be enough though (and not cluttering too much the interface) ??
But what if something have a class and an ID (i know, don't do that, but what if??)

**Comment by greenyboy** [comment]
Oh yes please

**Comment by Hornet25** [comment]
Sounds like an excellent idea +1

**Comment by DeivisPau** [comment]
We need this so bad.  + for sure.

**Comment by alriksson** [comment]
+1

**Comment by AntonKing60** [comment]
It’s a + one from me...and it’s a + one from him...

**Comment by INTELLIPLANS** [comment]
+1

**Comment by dinolatoga** [comment]
upvoting this. :)

**Comment by EnterpriseBranding** [comment]
🥇 👍 💯

**Comment by Famarast** [comment]
+1 👍👍👍

**Comment by pablodesign** [comment]
+1 👍👍👍

**Comment by jornmo** [comment]
Yes pretty please :)

**Comment by demetre19** [comment]
+1

**Comment by alriksson** [comment]
Add a button for reset/redo/undo for the styling for each element.

**Comment by thmbaker** [comment]
Excellent suggesgions. Please hire him for the job.

**Comment by cedricly** [comment]
Wow!! We need this so badly *o*

**Comment by peterpinkster** [comment]
Hi...   did you all saw the interface of **webflow**?

I hope the **Oxygen Team** has!

https://preview.webflow.com/preview/flexbox-game?preview=d1a26b027c4803817087a91c651e321f&m=1

**Comment by ivanjuras** [comment]
We need this thing. Oxygen team, please implement all of this guy's ideas. They're very, very useful.

**Comment by alFrame** [comment]
> 
> 
> I hate begging. PLEASE do this!
> 
> And fix the disappearing Effects tab.
> 
> And make the CSS/JS panel more user-friendly.

So I did not trip out, it actually is sometimes there and sometimes not ^.^

**Comment by alanzirpoli** [comment]
+1

**Comment by KarzanTT** [comment]
+9999

**Comment by shmaltz** [comment]
Click 👍 if you think we need these enhancements :)

**Comment by Netzlichter** [comment]
Implement it like he is showing it :).

**Comment by avocadesign** [comment]
+1

**Comment by schietegal** [comment]
+1 Yes!

**Comment by porg** [comment]
* After testing in the sandbox for several days this is among my biggest difficulties in the routine work with Oxygen and among these certainly the hardest to overcome.
* As it requires either a lot of guesswork or a good memory of what you set where or a deep understanding of how Oxygen and the CSS behind words.

**Comment by elmichalos** [comment]
+1 000 000

**Comment by Spellhammer** [comment]
Added in 4.0 Alpha 1.

**Comment by wpsumo** [comment]
Would prefer clean dots instead of what is right now and unfolding on hover. With different design underline on flex box etc and not fitting design in some cases in alpha. Better just use a dot as in the example, which fits everywhere. A more compact view and new fresh flex box icons and grid icons with compact view we will fit everything.


![](https://user-images.githubusercontent.com/56085341/68157015-1e741700-ff4d-11e9-9185-fa1a7b268c4d.gif)

**Comment by avocadesign** [comment]
I totally Agree with this the lines are not as functional as the dots in my opinion - inconsistent across controls and hard to see in some low light situations - The dot in a consistent place near the label of the property would be better than what is implemented in 4.0 alpha i feel.

**Comment by avocadesign** [comment]
The visual confusion is especially strong on colour selections - where there can be a green or blue bar next to a solid block of a completely different colour - a dot next to the label would move the colours away from each other.
