### ISSUE TITLE
[2.2 RC1] - Builder effects menu display error

### ISSUE THREAD

**Issue by benhohner** [soflyy/oxygen-bugs-and-features#61]
**Describe the bug**
Clicking the Advanced Tab -> Effects -> Any effect menu, then clicking the Advanced Tab again results in the Effects menu disappearing.

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
Yes

**To Reproduce**
This is fairly easy to reproduce so I haven't created any demo.
1. Load the builder
2. Click on an element with Effects under the Advanced tab
3. Click into any of the Effects (Animate on Scroll, Opacity, etc.)
4. Click the advanced tab again
5. The Effects menu is now missing

The effects menu will reappear if you click the Primary Tab then the Advanced tab again.

**Expected behavior**
Clicking the Advanced tab should Display all the top level menu items, including the effects menu item

**What actually happens**
Clicking the advanced tab from any of the effects sub-menus results in the effects menu disappearing.

**Screenshots**
Broken
![2019-02-09 16_22_27-oxygen visual editor - main - sandbox](https://user-images.githubusercontent.com/1463217/52526460-f6d67380-2c86-11e9-83fd-48714849b662.png)

Normal
![2019-02-09 16_22_33-oxygen visual editor - main - sandbox](https://user-images.githubusercontent.com/1463217/52526459-f50cb000-2c86-11e9-8aad-c9e3fd801be8.png)

**Desktop (please complete the following information):**
- OS: Windows 10 Home Version 10.0.17763 Build 17763
 - Browser Chrome 73.0.3683.27
 - Oxygen Version 2.2 RC1 (previous versions not tested)

**Comment by KittenCodes** [comment]
Fixed in v3.4.
