### ISSUE TITLE
Neutral gray UI

### ISSUE THREAD

**Issue by aformal** [soflyy/oxygen-bugs-and-features#612]
**Describe the feature you'd like to see included in Oxygen.**
Designers need a neutral gray environment to judge a design choice. The current design has a bluish tint.

**What are the use cases for this feature?**
Judge a design directly in Oxygen. -> enhanced usability, saving time.

**Examples of this feature or functionality**
I added a sketch, so you can understand the enhancement.

![neutral_gray](https://user-images.githubusercontent.com/56085341/67689508-b4330380-f99b-11e9-9fda-2ba1df3d5fbe.png)

**Comment by sigersmit** [comment]
I also work with Webflow and their UI is fantastic. https://webflow.com/. 

- I really like the way they have the responsive view ports in the top of the window. 
- Also you can really easy see which settings apply to which style. 
- An other thing I like is the autofill when choosing your style.

**Comment by aformal** [comment]
> * Also you can really easy see which settings apply to which style.

Like this too. I made a little sketch, how it could look in Oxygen:

https://github.com/soflyy/oxygen-bugs-and-features/issues/608

**Comment by Deanphillips** [comment]
Webflow + https://thrivethemes.com/new-ui-architect/ has the best UI imo

**Comment by greenyboy** [comment]
+1

**Comment by demetre19** [comment]
+1

**Comment by adrien-robert** [comment]
+1

**Comment by avocadesign** [comment]
+1

**Comment by Spellhammer** [comment]
Added in 4.0 Alpha 1.

**Comment by wpsumo** [comment]
@Spellhammer use the dark sharp blue color from the example on add and save including the active times like when selecting a flex box style. The existing one feels oxygen 3.x consider



![](https://user-images.githubusercontent.com/56085341/67689508-b4330380-f99b-11e9-9fda-2ba1df3d5fbe.png)
