### ISSUE TITLE
Learndash 3 Incompatibility. 

### ISSUE THREAD

**Issue by Flipback8** [soflyy/oxygen-bugs-and-features#616]
Please watch. I find Oxygen 3 incompatible with Learndash 3. 
[LearnDash Incompatibility](https://www.loom.com/share/b3552a3b00554a7cb79ecf5672a6b2e8)

**Comment by KittenCodes** [comment]
@Flipback8 Please create a separate template for your lessons. You can then add the lesson content using Dynamic Data and not an Inner Content element.

If this doesn't work for you, please email your site info to support@oxygenbuilder.com so that we can take a look.
