### ISSUE TITLE
Allowed memory size of X bytes exhausted, when fetching 'ct_get_template_data' ajax call

### ISSUE THREAD

**Issue by VolcanicJosep** [soflyy/oxygen-bugs-and-features#618]
**Describe the bug**
When entering the oxygen builder page for a template that is used in all posts, when the number of posts is big, the 'ct_get_template_data' ajax call returns an error 500 caused by an Allowed memory size of XXXXXX bytes exhausted.
For my case, I have a web with 23.943 posts, and needed to set a memory_limit = 1536M, for it to work. The 'ct_get_template_data' call returns a 1.9 MB resource with a list of all the posts.

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
Yes

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
http://fancy-boar.w5.wpsandbox.pro?upass=C8nMrCae17Z9
I was creating dummy posts to this site, but im at 28,046 posts and the resource that downloads is still at 1.6 MB(the post titles from the original site are longer than the generated). I can't no longer install plugins, so i cant replicate the exact setup from my web.
 The list of plugins that are in use in the original site:

Advanced Custom Fields PRO
Custom Post Type UI
Easy Smooth Scroll Links
kk Star Ratings
MC4WP: Mailchimp for WordPress
Monarch Plugin
Oxygen
Popup Maker
Quick and easy Post creation for ACF Relationship Fields PRO
WordPress Importer
WP All Import Pro 
Yoast SEO

**To Reproduce**
1. Have many posts, and some plugins installed
2. Go to 'Templates'
3. Create a new template without any restrictions on which posts to effect. 
4. Click on 'Edit with Oxygen'
5. The builder does not work and a notice for an error 500 apeares

**Expected behavior**
There should be some type of pagination when fetching the data of 'ct_get_template_data'

**What actually happens**
All the posts are being fetch in one request and the memory limit for php is exceed if it's not massive.

**Screenshots**
*If applicable, add screenshots to help explain your problem.*

**Desktop (please complete the following information):**
- OS: macOS 10.14.6
 - Browser: chrome
 - Oxygen Version:  3.0.1

**Additional context**
There may be other situations and calls that are not prepared for massive sites.

**Comment by uzimike** [comment]
Half a year later and nothing has been done about this? I'm experiencing this problem now - did you find a fix or a workaround @VolcanicJosep?

**Comment by VolcanicJosep** [comment]
As I recall changing the Preview Dropdown Limit in the oxygen settings menu solved the problem

**Comment by uzimike** [comment]
> As I recall changing the Preview Dropdown Limit in the oxygen settings menu solved the problem

Lifesaver, thank you!

**Comment by KittenCodes** [comment]
> As I recall changing the Preview Dropdown Limit in the oxygen settings menu solved the problem

If the site contains a large number of posts then it's recommended to set the Preview Dropdown limit to prevent this issue from occurring.

**Comment by wpsumo** [comment]
@KittenCodes Would be nice if we can set a specific page also to be preview. As in some cases there is different design live or data if you fetch dynamically. And when limiting the preview to x it's not ideal as you may have 100 of pages and languages and all might not have the data you are designing in the moment so the preview is not ideal as it only take the x from the msot recent published pages.

**Comment by KittenCodes** [comment]
@wpsumo 

> Would be nice if we can set a specific page also to be preview.

That's a good idea and doesn't seem to be an existing feature request.  If you'd like to see that option in a future release, please open a feature request: https://github.com/soflyy/oxygen-bugs-and-features/issues/new/choose.
