### ISSUE TITLE
Gutenberg Copy/Paste breaks styling

### ISSUE THREAD

**Issue by sfries79** [soflyy/oxygen-bugs-and-features#619]
**Describe the bug**
This might be related to #600. Copying text from a Gutenberg block doesn’t just copy the text but the style information too. The first Screenshot shows two headlines with different background colors as I set them up in O2. 
![001](https://user-images.githubusercontent.com/53555778/66416492-387a1280-e9fe-11e9-89a1-9529dec04667.png)

When I select the text in the first one by double clicking and copy it to the second one it results in what you can see here:
![002](https://user-images.githubusercontent.com/53555778/66416504-3dd75d00-e9fe-11e9-8f02-a2d4ff61a61b.png)

Just copying part of the first headline and pasting it in the middle of the second one gives me this:
![003](https://user-images.githubusercontent.com/53555778/66416506-40d24d80-e9fe-11e9-8f26-1a8605b1c26e.png)

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
I observed this in 3.0.1 (one of my sites and Sandbox) and 3.1 Alpha.

**To Reproduce**
1. Create a block with two headlines and some styling (e.g. different background colors)
2. Use the block in Gutenberg
3. Copy all or some of the text from one headline to the other one
4. See what no client should experience

**Expected behavior**
I would expect not to be able to overwrite the styling of elements in Gutenberg.

**What actually happens**
Styling information gets copied, breaking design most of the time.

**Comment by Spellhammer** [comment]
Replicated and reported internally.

**Comment by KittenCodes** [comment]
Fixed in v1.1 of Oxygen's Gutenberg add-on.
