### ISSUE TITLE
DONE: Data Attributes on elements

### ISSUE THREAD

**Issue by PaperjetStudios** [soflyy/oxygen-bugs-and-features#62]
Adding data-whatever-etc is possible with a bit of cool javascript from https://wpdevdesign.com/how-to-add-data-attributes-to-elements-in-oxygen/

BUT it's a little hacky to be honest. It'd be hella useful to have proper data attributes in the UI, I use them all the time in my own little scripts and there's a lot of libraries out there that also do. 

Maybe like a little menu like the css class dropdown thingie, maybe in the advanced stuff someplace.

**Comment by LordWhisper** [comment]
It's not just about fancy things that can be done with data-attributes but it's just necessary for some things! 

For example when trying to build a fully functional "table" with divs. If you wanted to have some content shown for specific media queries for example it would be done with data-attribute and calling it in a CSS class within that media query 

**Ex:**
```
@media (max-width: 1000px) {
  .tbl-cell::before { 
    content: attr(data-feature);
  }
}
```

**Comment by alpabuz** [comment]
When such a possibility appears, it will greatly simplify the life of developers and leave other visual designers far behind. Perhaps some users do not even know how much it will be a powerful option.

**Comment by Caffeinedesign** [comment]
+1 i was justing post the same thing, other builders don't really have a way to do it, it would be a big surplus for oxygen over others and i don't think it's that hard to add a field wich puts that string in the middle of html markup :P

best way would be to have a blank field "add html attribute", even better if we had a way to add more than one ( blank field with a + on the right, so we can add another blank field), so anyone can add the markup he needs data or whatever exists in html:

https://www.w3schools.com/tags/ref_attributes.asp

it would open to tons of jquery plugins, avoiding using other jquerys to add markups :P

**Comment by sunnyt7** [comment]
+1 from me. Would help integrate with some other scripts I've been looking at.

**Comment by srikat** [comment]
Until this is implemented officially, here's a less hacky method that can be used today:

https://wpdevdesign.com/data-attributes-in-oxygen/

**Comment by scriptaimago** [comment]
+1
Core HTML, should be natively supported

**The A tag should have editable attributes like:**
_- title
- description
- name
- rel
- rev_

**Options for:**
_- download_

**Select for:**
_- hreflang_

**Comment by ERROPiX** [comment]
Hi everyone,

As a developer, I need this feature for many of websites I worked on, so I decided to create a plugin that solve this issue in clean way, see http://oxygen-attributes.erropix.com

Thanks

**Comment by Oxymaniac** [comment]
+1

**Comment by wpdoit** [comment]
+1
I will pray to the gods of Oxygen for it to be realized as soon as possible.

**Comment by ERROPiX** [comment]
@Oxymaniac @wpdoit I made this and having more features, please check https://www.erropix.com/products/oxygen-attributes/

**Comment by wpdevlab** [comment]
Really looking forward to it!

**Comment by alriksson** [comment]
Theme.co recently added this to their theme and builder: https://theme.co/changelog/

**Comment by shoelaced** [comment]
A gazillion times yes.

**Comment by wordpressguy22** [comment]
+1

**Comment by williammei** [comment]
+1

**Comment by MattisW** [comment]
+1 - absolutely necessary

**Comment by jacobopolavieja** [comment]
+1. Would definitely need this one! Hope it gets to us.

**Comment by aleklisefski** [comment]
+1 -- most important feature missing in Oxygen at present.

**Comment by shmaltz** [comment]
+1 +1

**Comment by Netzlichter** [comment]
+1

**Comment by Totelae** [comment]
+1

**Comment by Spellhammer** [comment]
Custom attributes introduced in 3.5 alpha 1.
