### ISSUE TITLE
Undefined index: tag in cache.php wherever background is set

### ISSUE THREAD

**Issue by sagemedia** [soflyy/oxygen-bugs-and-features#620]
**Describe the bug**
Notice: Undefined index: tag in [...]component-framework/includes/cache.php
This error appears for every instance where background is set.

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
Yes

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
Yes. In sandbox I had to use WP Debugging to enable debug display (not compatible with oxygen, but replicates the errors thrown with no plugins and only wp_debug_display enabled). Sandbox: http://carefree-scarab.w5.wpsandbox.pro

**To Reproduce**
1. Set a background (color or image) for any element.

**Expected behavior**
conditional statement to set styles for element backgrounds via function: oxygen_vsb_element_inline_styles

**What actually happens**
undefined index error for every instance where background styles should be applied.
Problem: $options['tag'] on lines 689 (bg image) & 699 (bg color)

**Screenshots**
<img width="1434" alt="Screen Shot 2019-10-09 at 12 31 01 PM" src="https://user-images.githubusercontent.com/56350744/66501085-ba1a8080-ea90-11e9-801a-a057adc5125a.png">

**Desktop (please complete the following information):**
- OS: OSX 10.14.5
 - Chrome, Safari, Firefox
 - Oxygen 3.0.1

**Comment by torchsmith** [comment]
I have the same issue. Anyone know the solution?

**Comment by KittenCodes** [comment]
This should be fixed in v3.2.
