### ISSUE TITLE
Links on admin Home page leading to 404's

### ISSUE THREAD

**Issue by jpedigo** [soflyy/oxygen-bugs-and-features#621]
In the admin, if you navigate to Oxygen > Home, a couple of the links lead to 404 pages on the oxygenbuilder.com site. Specifically, the Visit the Oxygen Forums and Tutorials & Documentation links. Also, the Slack link leads to a page on slack.com that says the invite is no longer active. Happening on every version since at least 2.4.1, which is the oldest version I'm using. Confirmed as well on 3.0 and 3.0.1. Obviously minor, but no one likes 404's.

**Comment by cstrouse** [comment]
Still an issue almost 7 months later.

**Comment by KittenCodes** [comment]
Fixed in v3.6 Beta.
