### ISSUE TITLE
Repeater Creates duplicate IDs when uisng Categorys

### ISSUE THREAD

**Issue by matthiasmarx** [soflyy/oxygen-bugs-and-features#622]
BUG:

When using the repeater element, oxygen creates duplicate IDs for the wrapping DIV and the category div. (Screenshot attached)

Browser: Chrome in the latest Version - Version 77.0.3865.90 (Offizieller Build) (64-Bit)
Oxygen Version: 3.0.1.

Plugins used: 
ACF
CPTUI
Elegant Custom Fonts

![OxygenBug_Same_ID](https://user-images.githubusercontent.com/56389884/66558272-92d8b780-eb53-11e9-89ca-77599d0638ec.png)

**Comment by KittenCodes** [comment]
Duplicate: https://github.com/soflyy/oxygen-bugs-and-features/issues/432
