### ISSUE TITLE
Super User only for Oxygen

### ISSUE THREAD

**Issue by ibandelanava** [soflyy/oxygen-bugs-and-features#626]
Pre-created Super User when Oxygen is installed. Like "Super Admin" for Multisite. 

With the same admin capabiities and only for use in designs with Oxygen. So Administrator accounts can´t view and use Oxygen.

Allow to change the password and rename this user, after Oxygen is installed.

This Scenario:

Finally clients that need Administrator accounts but without access to Oxygen Builder (Only Gutterberg editing, for example).

Oxygen Builder finally is only viewed and used by designer or developer.

**Comment by louisreingold** [comment]
The WordPress way to do this is to create a custom user role using the multitude of plugins available for that purpose and then use Oxygen's access controls to restrict that user role from accessing Oxygen.

**Comment by ibandelanava** [comment]
Yes, but the idea behind this, is that only one user included inside Oxygen code, can use Oxygen.

If we need install other plugins to assign or delete privileges or capabilities, that after, new admin accounts has access to uninstall this plugins or reasign capabilities, is wasted time.

This idea is intented for projects that we not maintenance anymore and are delivered to the final customer, but without access to Oxygen.

You don´t think the same?

**Comment by KittenCodes** [comment]
You can use Edit Mode to disable Oxygen access for other users on the site.
