### ISSUE TITLE
Undefined index: tag in /oxygen/component-framework/includes/cache.php on line 699, crashing the WP Admin

### ISSUE THREAD

**Issue by vankama** [soflyy/oxygen-bugs-and-features#627]
**Describe the bug**
When using Product Builder in Gutenberg block the following error occurs:
![image](https://user-images.githubusercontent.com/44664543/66718050-23c7c100-ede8-11e9-9e3c-12c3ba0620b5.png)

*A clear and concise description of what the bug is.*
Using Product Builder in Gutenberg block crashes the WordPress Admin.

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
**Yes**

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
*If yes, provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*
One Click Login: http://embarrassed-pigeon.w5.wpsandbox.pro?upass=7uGS571rwlQR

**To Reproduce**
### How to reproduce it:
1. Instal the latest stable versions of WordPress, Oxygen, Oxygen WC and Gutenberg Integrations & WooCommerce.

2. Create a new block

3. Recreate the same structure and add a product ID:
![image](https://user-images.githubusercontent.com/44664543/66717857-4f49ac00-ede6-11e9-80fa-6a8163ec0743.png)

4. Save the block, navigate to the WP Admin and you should see this:
_The site is experiencing technical difficulties. Please check your site admin email inbox for instructions._

If you have enabled the debuging features, you should see this:

**Notice:** Undefined index: tag in **.../wp-content/plugins/oxygen/component-framework/includes/cache.php** on line **699**
>
**Notice:** Undefined index: tag in **.../wp-content/plugins/oxygen/component-framework/includes/cache.php** on line **699**
>
**Notice:** wc_get_product was called **incorrectly**. wc_get_product should not be called before the woocommerce_init action. Backtrace: require_once('wp-admin/admin.php'), require_once('wp-load.php'), require_once('wp-config.php'), require_once('wp-settings.php'), do_action('init'), WP_Hook->do_action, WP_Hook->apply_filters, Oxygen_Gutenberg->init, do_shortcode, preg_replace_callback, do_shortcode_tag, CT_Section->add_shortcode, do_shortcode, preg_replace_callback, do_shortcode_tag, CT_Slider->add_shortcode, do_shortcode, preg_replace_callback, do_shortcode_tag, CT_Slide->add_shortcode, do_shortcode, preg_replace_callback, do_shortcode_tag, OxygenElement->shortcode, Oxygen\WooElements\ProductBuilder->render, wc_get_product, wc_doing_it_wrong Please see Debugging in WordPress for more information. (This message was added in version 2.5.) in **.../wp-includes/functions.php** on line **4773**

**Notice:** wc_get_product was called **incorrectly**. wc_get_product should not be called before the woocommerce_init action. Backtrace: require_once('wp-admin/admin.php'), require_once('wp-load.php'), require_once('wp-config.php'), require_once('wp-settings.php'), do_action('init'), WP_Hook->do_action, WP_Hook->apply_filters, Oxygen_Gutenberg->init, do_shortcode, preg_replace_callback, do_shortcode_tag, CT_Section->add_shortcode, do_shortcode, preg_replace_callback, do_shortcode_tag, CT_Slider->add_shortcode, do_shortcode, preg_replace_callback, do_shortcode_tag, CT_Slide->add_shortcode, do_shortcode, preg_replace_callback, do_shortcode_tag, OxygenElement->shortcode, Oxygen\WooElements\ProductBuilder->render, wc_get_product, wc_doing_it_wrong Please see Debugging in WordPress for more information. (This message was added in version 2.5.) in **.../wp-includes/functions.php** on line **4773**

**Notice:** wc_get_product was called **incorrectly**. wc_get_product should not be called before the woocommerce_init action. Backtrace: require_once('wp-admin/admin.php'), require_once('wp-load.php'), require_once('wp-config.php'), require_once('wp-settings.php'), do_action('init'), WP_Hook->do_action, WP_Hook->apply_filters, Oxygen_Gutenberg->init, do_shortcode, preg_replace_callback, do_shortcode_tag, CT_Section->add_shortcode, do_shortcode, preg_replace_callback, do_shortcode_tag, CT_Slider->add_shortcode, do_shortcode, preg_replace_callback, do_shortcode_tag, CT_Slide->add_shortcode, do_shortcode, preg_replace_callback, do_shortcode_tag, OxygenElement->shortcode, Oxygen\WooElements\ProductBuilder->render, do_shortcode, preg_replace_callback, do_shortcode_tag, CT_DIV_Block->add_shortcode, do_shortcode, preg_replace_callback, do_shortcode_tag, OxygenElement->shortcode, Oxygen\WooElements\ProductImages->render, wc_get_product, wc_doing_it_wrong

**Expected behavior**
The WordPress admin should continue to function.

**What actually happens**
The WordPress admin stops to function.

**Screenshots**
Screenshots added troughout the description.

**Desktop (please complete the following information):**
- OS: Windows
- Browser: Chrome Version 77.0.3865.90 (Official Build) (64-bit)
- Oxygen Version: oxygen.3.0.1

**Comment by vecchionico** [comment]
This issue is actually present in any page after installing the gutenberg integration plugin (tested with version 1.0.1), I just noticed it in a freshly installed Wordpress istance on an empty website. 

**Steps to reproduce**
1. install the gutenberg integration plugin
2. set `define( 'WP_DEBUG', true );` in wp-config
2. create a new page or post and edit with oxygen
3. save the page and check the frontend

You'll see the error message: "Undefined index: tag in /oxygen/component-framework/includes/cache.php on line 699"

**Comment by vecchionico** [comment]
this looks fixed to me in 3.1

**Comment by KittenCodes** [comment]
@vankama I'm not able to reproduce this. If you're still having problems using the latest stable release of Oxygen and our WooCommerce add-on, please email support@oxygenbuilder.com.
