### ISSUE TITLE
[2.2 RC1] - Styles-present indicator appearing even when properties are reset

### ISSUE THREAD

**Issue by benhohner** [soflyy/oxygen-bugs-and-features#63]
**Describe the bug**
Many builder properties have no way to clear the styles-present indicator or reset to default.
The following properties have been tested to perma-lock the styles-present indicator with no way to clear or reset to default.
- Advanced -> Layout -> Display
- 2.2 RC1 Advanced -> Effects -> Animate on Scroll -> Enable Animation
- 2.2. RC1 Advanced -> Effects -> Box Shadow -> Inset Checkbox
- 2.2. RC1 Advanced -> Effects -> Filter -> if Filter Amount is set and Filter is set back to none
- Advanced -> Custom CSS -> Apply Code: This is a unique bug, the styles-present indicator on the Custom CSS menu item is visible, but not the styles-present indicator for the Advanced tab
- Advanced -> JavaScript -> Apply Code: same as above
- Header Builder -> Advanced -> Header Row Container Width: No way to reset to default

This bug may also be a warning sign of additional CSS leftover in the generated CSS?

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
Yes

**To Reproduce**
1. Go to the specified advanced sub-tab in any of the bullets above
2. Enable the specified control
3. Disable the specified control
4. Go back to the Advanced tab
5. The Advanced tab and the related sub-tab will still show the styles-present indicator.

**Expected behavior**
The styles-present indicator should not display when the related sub-tab's settings are reset. Additionally there  should be a way to reset every sub-tab to default.

**Reproduction**
Login:
http://famous-fox.w5.wpsandbox.pro?upass=Pw6L5hf7Wi8F

See for many examples:
http://famous-fox.w5.wpsandbox.pro/ct_template/main/?ct_builder=true

**What actually happens**
The styles-present indicator still displays even when there is no setting set in the corresponding sub-tab.

**Screenshots**
styles-present indicator still visible even when all styles reset to default
![2019-02-09 17_03_15-oxygen visual editor - main - sandbox](https://user-images.githubusercontent.com/1463217/52526805-b7128a80-2c8c-11e9-9fe3-082a6cc4170a.png)

Display sub-tab with all styles reset and Advanced tab still showing styles-present
![2019-02-09 17_03_30-oxygen visual editor - main - sandbox](https://user-images.githubusercontent.com/1463217/52526811-cabdf100-2c8c-11e9-8805-6b349f5e5e90.png)

**Desktop (please complete the following information):**
- OS: Windows 10 Version 10.0.17763 Build 17763
- Browser: Chrome  73.0.3683.27
- Oxygen Version: 2.2RC1 (these bugs have been happening since at least 2.1)

**Comment by oldrup** [comment]
I think this is the same issue I'm experiencing with the Layout styles, screencasted here:
https://youtu.be/6cHROif8-uI

When you realize, that you need to move styling to classes instead of id's the "style present indicator" is very valuable to indicate where modified styling is still present - that is, when it works :)

A fix, or a "reset styles" button, would be appreciated 👍

**Comment by Spellhammer** [comment]
Fixed in Oxygen 4.1 beta 1.
