### ISSUE TITLE
Gallery Safari slide bug

### ISSUE THREAD

**Issue by alriksson** [soflyy/oxygen-bugs-and-features#632]
**Describe the bug**
When an open gallery in safari om mobile it is not possible to scroll.

UI issue that on mobile the arrows do not display so it's hard from a UX/UI to understand how you display next or prev images.

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
*Yes*

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
*If yes, provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*

**To Reproduce**
1. Create a 3 image gallery
2. Open on mobile device in safari and chrome
3. Click on image and swipe to next image
4. On safari it do not work both devices do not display next/prev indicators.

**Expected behavior**
Gallery should show indicators and allow the users to slide the gallery images on Safari.

**What actually happens**
Gallery does not slide or show navigation indicators.

**Desktop (please complete the following information):**
 - Oxygen Version [3.0.1]

**Smartphone (please complete the following information):**
- Device: [e.g. iPhone XS]
 - Browser [Chrome, Safari]
 - Oxygen Version [3.0.1]

**Comment by KittenCodes** [comment]
Images scroll correctly on both Android and iOS in the latest version of Oxygen. Please note that the images are scrolled using a swipe action on the images - the arrows don't exist on either mobile device.
