### ISSUE TITLE
Cannot remove background image from imported design set element

### ISSUE THREAD

**Issue by yankiara** [soflyy/oxygen-bugs-and-features#639]
**Describe the bug**
After importing design set element, there's no way to remove background image from section.

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
Yes

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
Yes: http://corral-donkey.w6.wpsandbox.pro

**To Reproduce**
1. After fresh install, edit Sample Page with Oxygen
2. Import Hero section from One Page 2 design set (there's only one element in hero category)
3. Select section, delete background image
4. Background image is still displayed, and visible with browser inspector

**Expected behavior**
No background should be displayed if background image field is emptied.

**What actually happens**
Background still shows up.

**Screenshots**
![Screenshot_1](https://user-images.githubusercontent.com/36680757/67049357-5817e600-f136-11e9-9073-3b4c1709cdc3.png)

**Desktop (please complete the following information):**
- OS: Windows 10
 - Firefox
 - Oxygen Version 3.0.1

**Comment by Spellhammer** [comment]
@yankiara This should be fixed now. You'll need to re-import the elements from the design set.

**Comment by yankiara** [comment]
Hi Elijah,

Thx for your fast answer! And nice to meet you :)
But the problem has been fixed only for the hero section, and remains for all other elements of the page.

No issue with separate elements from categories, though.
