### ISSUE TITLE
Unable to edit background images in Gutenberg

### ISSUE THREAD

**Issue by pauldyke** [soflyy/oxygen-bugs-and-features#643]
**Describe the bug**
I've created a block using Atomic Hero with Image on Right. When I use this block on a page in Gutenberg, there isn't a way to change the block background image.

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
Yes

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
*If yes, provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*

http://inventive-rook.w5.wpsandbox.pro/wp-admin/post.php?post=19&action=edit

**To Reproduce**
1. Go to background image test page
2. Click on the only block and view block settings
3. Click on the raspberry punnet image.
4. unable to edit image.

**Expected behavior**
I would expect either the background image to be clickable and ability to access the media library as per the cover block or for the background image url to be accessible in the block settings.

**Desktop (please complete the following information):**
- OS: windows 10
 - Browser chrome
 - Oxygen Version 3.0.1

**Additional context**
“Oxygen's Gutenberg integration is super powerful - we give full control to the client yet they do not touch Oxygen at all.” as per your website please.

**Comment by Spellhammer** [comment]
This is not a bug. It's a limitation of the Gutenberg integration. Please file a feature request if you'd like to be able to edit Div background images in Gutenberg. Currently you can only edit Section background images.
