### ISSUE TITLE
DONE: Accessible Viewport Menu

### ISSUE THREAD

**Issue by aformal** [soflyy/oxygen-bugs-and-features#646]
**Describe the feature you'd like to see included in Oxygen.**
An accessible viewport menu at the bottom of the screen to switch fast between the viewports.

**What are the use cases for this feature?**
Making the viewport always accessible. -> Faster workflow

**Examples of this feature or functionality.**
I added a sketch, so you can understand the feature.

<img src="https://user-images.githubusercontent.com/56085341/67702746-9624cd80-f9b2-11e9-86cf-a4285880406a.gif" alt="menu" width="300">

And a little hover effect to provide information when it is needed:

<img src="https://user-images.githubusercontent.com/56085341/67702765-9a50eb00-f9b2-11e9-900c-d5219491b8aa.gif" alt="menu_hover" width="300">

I apologize for any grammar or spelling mistakes. I'm not a native speaker.
I checked all the existing feature requests and I hope this post isn’t redundant.

**Comment by demetre19** [comment]
+10

**Comment by adrien-robert** [comment]
+1

**Comment by alriksson** [comment]
@aformal How about a smaller view of the elements view?

Some inspiration could be Themeco and their PRO builder: 
https://theme.co/changelog/#theme-pro-3-0-0-theme-x-7-0-0-cornerstone-4-0-0

**Comment by Deanphillips** [comment]
Really love this, man.

I'm curious though, how would things change if we were able to add our own custom breakpoints (aka more devices)

**Comment by cedricly** [comment]
Love this! Hope Oxygen goes with it!

**Comment by Spellhammer** [comment]
In 4.0, we moved the breakpoint buttons into the top bar of Oxygen to make them easier/quicker to access.
