### ISSUE TITLE
DONE: Full Screen Mode

### ISSUE THREAD

**Issue by aformal** [soflyy/oxygen-bugs-and-features#648]
**Describe the feature you'd like to see included in Oxygen.**
The possibility to hide also the left panel. 

**What are the use cases for this feature?**
Judge a design directly in Oxygen.

**Examples of this feature or functionality.**
I added a sketch, so you can understand the feature.
(click the images to enlarge)

![Artboard Copy 5](https://user-images.githubusercontent.com/56085341/67417296-b6c2e100-f5c8-11e9-9b71-ed9a711e7ed2.jpg)

![Artboard Copy 10](https://user-images.githubusercontent.com/56085341/67417316-c17d7600-f5c8-11e9-90a2-604bbbfe4413.jpg)

![Artboard Copy 11](https://user-images.githubusercontent.com/56085341/67417469-20db8600-f5c9-11e9-8434-31ab03b1d24d.jpg)

<img src="https://user-images.githubusercontent.com/56085341/67703064-1b0fe700-f9b3-11e9-9dbc-5e5c61f14b5d.gif" alt="menu" width="350">

**Comment by Martin-1** [comment]
+1

**Comment by demetre19** [comment]
+10

**Comment by adrien-robert** [comment]
Wow, awesome work!

**Comment by esaygo** [comment]
+1 nice!

**Comment by cedricly** [comment]
Love it! +1

**Comment by Janik-Dev** [comment]
+1

**Comment by 5pointDigital** [comment]
This actually makes the product look like an enjoyable experience, not the claustrophobic mish-mash of buttons and random empty fields we have now.

Really hope all your time creating these mock ups doesn't go to waste.

**Comment by Spellhammer** [comment]
3.3 alpha 1 introduces the ability to hide the Properties Pane, resulting in a full screen preview.
