### ISSUE TITLE
oxygen 2.2RC1 broke the editor

### ISSUE THREAD

**Issue by Phukit** [soflyy/oxygen-bugs-and-features#65]
Hi,

 I am on the latest WP version 5.0.3

and the page looks fine on the front end except the woocommerce page is broken.

I have tested all my plugins and the editor is broken when SG Optimizer is enabled. 

There is a conflict with the plugin  https://en-ca.wordpress.org/plugins/sg-cachepress/

When I disable the plugin everything works fine.

Thanks.

**Comment by Phukit** [comment]
I sometimes get this as well.

This site can’t be reached The webpage at https://"mysite"/testing/ct_template/title/?ct_builder=true might be temporarily down or it may have moved permanently to a new web address.
ERR_CONTENT_DECODING_FAILED

**Comment by Phukit** [comment]
After digging further into the plugin.

when this option is 'on' Minify the HTML Output  the editor is broken

when this option is 'off' than the editor works again.

I was on version 2.1.2 and this did not break the editor.

Thanks.

**Comment by KittenCodes** [comment]
@Phukit 

> when this option is 'on' Minify the HTML Output the editor is broken

It's not recommended to combine or minify Oxygen's files as doing so can break Oxygen.
