### ISSUE TITLE
CSS Styles / Colors Disappear on Template Save

### ISSUE THREAD

**Issue by steve-goldberg** [soflyy/oxygen-bugs-and-features#664]
**Describe the bug**
When I save a page template after making edits all of the CSS styles and global colors disappear sitewide.

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
Yes

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
No. The site is over 1GB and the upload fails every time.

**To Reproduce**

Open a template and add a reusable part as Editable.
Make changes to the reusable part, colors, delete elements.
Save the template.
All styles disappear.

**Expected behavior**
I expect the changes to be live.

**What actually happens**
All styles on the site are gone.

**Screenshots**
Video: https://cl.ly/fb26556c07be

**Desktop (please complete the following information):**
- OS: Mac
 - Browser Chrome
 - Oxygen Version 3.01 production

**Additional context**

I was able to create the issue once on video but not a second time from the start.

**Comment by benhohner** [comment]
Can you post a non 10 minute video of you reproducing the bug in a few steps? If you can't isolate the exact behaviour that causes the bug on your site, the devs won't be able to either.

Cheers!

**Comment by steve-goldberg** [comment]
I shortened the clip to under 3 minutes. This is the only clip I have of the bug happening.

https://cl.ly/b764156175ba

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by KittenCodes** [comment]
@steve-goldberg Unfortunately, I'm not able to view the video - it says "Uploading". Please could you add a new link?
