### ISSUE TITLE
No "Open in new tab" checkbox for Gutenberg block links

### ISSUE THREAD

**Issue by Jeremy-Bolella** [soflyy/oxygen-bugs-and-features#666]
**Describe the bug**
Gutenberg block links don't have the open in new tab checkbox. The oxygen editor dialog which looks almost identical has this and the dialog looks almost identical.

**Expected behavior**
The dialog should have a checkbox for opening in a new tab.

**What actually happens**
There is no checkbox :(

**Comment by KittenCodes** [comment]
This isn't a bug - the "open in a new tab" decision should be made by the developer/designer when creating the block.
