### ISSUE TITLE
Dynamic field editable in Gutenberg BUG

### ISSUE THREAD

**Issue by alriksson** [soflyy/oxygen-bugs-and-features#668]
**Describe the bug**
Gutenberg blocks allow url to be editable in Gutenberg even if it's dynamic:

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
*Yes*

**To Reproduce**
1. Create a button
2. Connect the URL dynamically with ACF (my case using the select field for predefined custom URLs)
3. Save the element to blocks
4. Add the element to Gutenberg and see the client can still edit this. Should only be editable through the ACF fields.

**Expected behavior**
The URL field is still editable even if fetching dynamic data.

**What actually happens**
Should not be editable in Gutenberg, should be editable in ACF only.

**Screenshots**
https://tppr.me/l7BE4

**Desktop (please complete the following information):**
- OS: [MACOS]
 - Browser [Chrome]
 - Oxygen Version [3.1 Beta]
 - Oxygen Gutenberg  [1.1 Beta]

**Comment by KittenCodes** [comment]
This isn't a bug - all links are intended to be editable in Gutenberg.
