### ISSUE TITLE
DONE: Adding a warning that Oxygen is in use elsewhere.

### ISSUE THREAD

**Issue by NichCitarella** [soflyy/oxygen-bugs-and-features#673]
Implementing a system that at launch would check if Oxygen is in use elsewhere, whether it be in another window/tab, different browser or by a different user, and prompt the user that another instance is loaded and that running 2 instances may result in data loss. This could be pretty much a clone of what WordPress natively does if 2 people try to edit a post at the same time.

This would be extremely useful for teams and in an ideal situation, would notify that person trying to open Oxygen that it is already in use and include who is using it and notify the person who is using Oxygen that a person was looking to access Oxygen.

**Comment by captivation** [comment]
My team would also love this feature built-in as well!

**Comment by KittenCodes** [comment]
Implemented.
