### ISSUE TITLE
2.2RC Smooth Scroll doesn't account for Sticky header 

### ISSUE THREAD

**Issue by wplit** [soflyy/oxygen-bugs-and-features#68]
**Describe the bug**
When anchor links are used to scroll the page to the target ID, the target element is cut off if the sticky header is active.

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
Yes, here is the demo. Just click the menu links to see the problem - 
http://powerful-shrew.w6.wpsandbox.pro/

**To Reproduce**
1. Create anchor links
2. Turn on sticky header
3. Notice you can't read the top of the sections.

**Expected behavior**
The script for the smooth scroll needs to include an offset that is equal to the height of the header when the sticky header is visible.

**Additional context**
The script you've added already for the smooth scroll already has offset() in it, but just needs to be used to work correctly with the sticky header feature.

**Comment by KittenCodes** [comment]
Feature request: #305

**Comment by LefBoutham** [comment]
The bug still exists.
