### ISSUE TITLE
Edit component in a new tab

### ISSUE THREAD

**Issue by aformal** [soflyy/oxygen-bugs-and-features#682]
**Describe the feature you'd like to see included in Oxygen.**
Creating components is a super useful feature. It could become even more useful if the user could edit them right in the editor without the need to go back to wordpress. 

This could be accomplish by adding the option "edit" to the context menu at the structure panel.

In my sketch I included the tabs in Oxygen. But I would be already happy, if you could open a component in a new browser tab.
 
**What are the use cases for this feature?**
Saving time by eliminating the need to go back to the wordpress backend to edit a component. 

**Examples of this feature or functionality.**
I added a sketch, so you can understand the feature.

<img src="https://user-images.githubusercontent.com/56085341/68121147-522c4e00-ff07-11e9-8f34-40fa59cbe554.gif" width="1140">

**Comment by Deanphillips** [comment]
Why was this closed?
