### ISSUE TITLE
Add Support for ACF Global Options page

### ISSUE THREAD

**Issue by Gibsonion** [soflyy/oxygen-bugs-and-features#687]
**Feature:**
Oxygen should have support for ACF options pages, where a user can set data to be used sitewide from one page. https://www.advancedcustomfields.com/resources/get-values-from-an-options-page/

**What are the use cases for this feature?**
Uses can set data that will be used on multiple pages from one page instead of needing to enter that data on every page.

**Comment by KittenCodes** [comment]
#142

**Comment by CINQDEV** [comment]
Is there a timescale for this to be added, stopping me from switching to Oxygen for all projects. Would be very very handy.
