### ISSUE TITLE
Selector detector / manually adding selector bug

### ISSUE THREAD

**Issue by Helmi** [soflyy/oxygen-bugs-and-features#689]
I got some similar classes within the post output (content) that I'm trying to style.

.alert
.alert-info
.alert-warning

There are div's in the post content that usually carry both of them like `class="alert alert-info"`. I did some styling on .alert already and managed to get .alert-warning working. When trying to select one of the .alert-info boxes to give that some additional styling Oxygen always puts me on the .alert selector. If I change the selection from the class tree it modifies the .alert selector to .alert-info instead of creating a new. I then selected a totally different element and changed the class name in the text field. When i started typing .alert-info as soon as i reached the dash it changes to the previously saved .alert selector and changes it to .alert-info again. I can't seem be able to create a new selector from the selector detector there.

My suspicion is that there's some name matching weirdness going on because even when I enter .alert-info manually as a selector it highlights certain categories in Advanced with the little dot that should usually show changes/overrides made there but there is nothing as this class was just created.

Also when I manually create the selector it always gets created in the "Uncategorized custom selectors" folder within another "Uncategorized" folder (that btw holds all Style sets created from the selector detector). The whole selector organization is a bit of a mess here. Not sure if that's only on my installation but I can't seem to have any chance to get this sorted.

I hope this description helps a bit and am sorry that I can't setup a test environment to reproduce the issue.

**Comment by KittenCodes** [comment]
@Helmi I haven't been able to replicate this. Please can you replicate the issue on our Sandbox and add the one click login to the thread? You can create a Sandbox site here: https://oxygenbuilder.com/try/
