### ISSUE TITLE
target="_blank" Links in Oxygen cause errors in Chrome Audit

### ISSUE THREAD

**Issue by wplit** [soflyy/oxygen-bugs-and-features#69]
**Describe the bug**
External links ([according to google docs](https://developers.google.com/web/tools/lighthouse/audits/noopener)) should be written like the following...

`<a href="https://examplepetstore.com" target="_blank" rel="noopener">
  Example Pet Store
</a>`

Without the rel="noopener", when we do site audits through chrome developer tools it always pulls up errors for all the social media icons and any external links, saying it's a security threat. And currently it's not something that we can edit easily in Oxygen.

**Sandbox Site**
http://dark-louse.w5.wpsandbox.pro/
- Open the site in chrome, go to dev tools, then click on audit and then 'run audit'. You'll see the error.. "Links to cross-origin destinations are unsafe"

To fix, please just add rel="noopener" to the html when also applying target="_blank", like in the case of the social icons where users can choose to link 'in a new tab'.

**Comment by KittenCodes** [comment]
#306

**Comment by adrien-robert** [comment]
Any update on this?
