### ISSUE TITLE
MU Plugin requires files from wrong domain

### ISSUE THREAD

**Issue by Xilonz** [soflyy/oxygen-bugs-and-features#693]
**Describe the bug**
Oxygen requires the icon from the wrong domain:
```
Access to image at 'https://mainexample.com/app/plugins/oxygen/component-framework/toolbar/UI/oxygen-icons/not-real-arrow-dropdown.svg' from origin 'https://subexample.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```
This might also happen to other includes, but this is the only one I noticed

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
Yes

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
Not possble

**To Reproduce**
1. Create multi site with a least 2 sites
1. Install & activate Oxygen __globaly__
2. Make sure domains of the sites don't match

**Expected behavior**
Correct domain to be used

**What actually happens**
Uses the wrong domain

**Comment by KittenCodes** [comment]
@Xilonz If you're still experiencing this issue, please open a support ticket: https://oxygenbuilder.com/support.
