### ISSUE TITLE
Add Offset option to Smooth Scroll to Hash Links to allow for sticky headers

### ISSUE THREAD

**Issue by KittenCodes** [soflyy/oxygen-bugs-and-features#698]
When using the Smooth Scroll to Hash Links option within Oxygen, it doesn't allow for sticky headers. It would be nice to have the option to offset it using another elements height, or manually set an offset in PX.

It's possible to use another element as an offset by disabling Oxygen's built-in option and using the following code:

```js
var $header = jQuery('#_my_header_id');

jQuery('a[href^="#"]').click(function(e){
	e.preventDefault();
	jQuery('html,body').animate({scrollTop:jQuery(this.hash).offset().top - $header.height()}, 750);
});
```

**Comment by wplit** [comment]
Same requests;
https://github.com/soflyy/oxygen-bugs-and-features/issues/133
https://github.com/soflyy/oxygen-bugs-and-features/issues/305

**Comment by KittenCodes** [comment]
@wplit I have no idea why I couldn't find those. Thank you. I'll close this.
