### ISSUE TITLE
Export/Import does not re-create folders and stylesets

### ISSUE THREAD

**Issue by drank** [soflyy/oxygen-bugs-and-features#70]
**Describe the bug**
When settings are exported (**Oxygen / Export & Import**) from one installation and then imported to another installation, the folders and the stylesets are not re-created at the new location.
This has the effect that all selectors and classes that were categorized into folders/stylesets at the source installation to be missing at the destination installation.
One has to manually re-create all the folders and stylesets and then assign the stylesets into the folders in order for the selectors and classes to appear, which is quite a hassle.

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
Yes. Check http://perfect-chimpanzee.w5.wpsandbox.pro?upass=0HIaj23t3DUc
You can see that the folder, the styleset and the selector are missing although the selector is present in the export JSON code in Oxygen / Export & Import

**To Reproduce**
1. Open the Editor
2. Go to Manage/Selectors
3. Create a folder named TestFolder.
4. Add a selector and put it in a new styleset named TestStyleset
5. Put the new styleset in the TestFolder
6. You should have this structure:
![image](https://user-images.githubusercontent.com/1393766/52649148-6f8c3880-2ef0-11e9-9143-674d3a297ef7.png)
7. Save and exit to admin
8. Go to Oxygen Export & Import and copy the export code
9. (Optional) You can check the JSON code at https://jsoneditoronline.org/
10. Open the Editor again and delete the selector, folder and styleset from Manage/Selectors and save
11. Go to Export & Import and import the previously exported JSON code
12. Open the editor again and go to Manage/Selectors

**Expected behavior**
I should expect to see the same structure as in the screenshot above.

**What actually happens**
The selector, the folder and the styleset are not there:
![image](https://user-images.githubusercontent.com/1393766/52653754-4b812500-2ef9-11e9-971b-bf773f699f5f.png)

**Desktop (please complete the following information):**
- Oxygen Version - checked with 2.1.2 and 2.2 RC1

**Comment by KittenCodes** [comment]
This is fixed in the latest version of Oxygen.
