### ISSUE TITLE
Problems with Date and Date formatting in Repeater

### ISSUE THREAD

**Issue by srikat** [soflyy/oxygen-bugs-and-features#701]
In the Repeater,

1) Insert Data > Post > Date does not use the specified format. Possibly related to https://github.com/soflyy/oxygen-bugs-and-features/issues/489.

2) Insert Data > Advanced > PHP Function Return Value > `the_time` and `Y` as argument. Repeater hangs with a loading indicator that never stops spinning.

Update: The date in the specified format appears fine on the front end but the Repeater component becomes unusable in the editor.

https://vimeo.com/371497095

Tested in both Oxygen v3.0.1 and 3.1 RC1.

**Comment by ivanjuras** [comment]
I noticed the bug, as well.

**Comment by srikat** [comment]
Facebook discussion: https://www.facebook.com/groups/1626639680763454/permalink/2549561445137935/

**Comment by KittenCodes** [comment]
Dynamic Data > Date ignores the specified format wherever it's used, it's not specific to the repeater.

PHP function return value doesn't work in the builder.

Both replicated in 3.1.

**Comment by crisclaessensgithub** [comment]
This is clearly not fixed with Oxygen 3.2? :-(

**Comment by hctrbz** [comment]
Using a PHP Function Return Value > `the_time` or `the_date` does indeed break the Repeater on the backend.

Try using a PHP Function Return Value > of `get_the_date`. I used this along with the Format > `Y` to return only the year each post was published and it worked great.

**Comment by Deralict** [comment]
Still not fixed in 3.6.1

**Comment by derSebastian** [comment]
maybe we see a fix in 3.7?

**Comment by yankiara** [comment]
WAKE UP OXYGEN!!! This is so ridiculous.

**Comment by adrien-robert** [comment]
Hope it will be fixed for 3.7.1

**Comment by viniciusmartin** [comment]
3.8.1 and not has fixed...

**Comment by Firsh** [comment]
Yup, still happening. Frontend doesn't have the desired effect either.

**Comment by KittenCodes** [comment]
Fixed in v3.8 Beta 1.

**Comment by patparker** [comment]
I am still having this problem, using 3.9, is anyone else?
