### ISSUE TITLE
Soft wrap for code blocks

### ISSUE THREAD

**Issue by vecchionico** [soflyy/oxygen-bugs-and-features#702]
**Describe the feature you'd like to see included in Oxygen.**
Soft wrap: the ability to wrap long texts in new lines. 

**What are the use cases for this feature?**
I think it would be useful when editing code blocks with very long lines of code.

**Examples of this feature or functionality.**
Soft wrapping can be seen in any modern text editor
![Screenshot from 2019-11-08 13-28-41](https://user-images.githubusercontent.com/56926179/68476717-ce86a000-022b-11ea-988b-8416f4fa0d9c.png)
*

**Comment by srikat** [comment]
https://github.com/soflyy/oxygen-bugs-and-features/issues/324
