### ISSUE TITLE
Post Type / Post Parent ID both conditions not working

### ISSUE THREAD

**Issue by wplit** [soflyy/oxygen-bugs-and-features#719]
**Describe the bug**
These two conditions aren't working due to 'return' missing from the code & the intval missing.

From what I can tell, this is what is needed to be working code (missing parts underlined)

<img width="1308" alt="Screen Shot 2019-11-14 at 12 17 51 pm" src="https://user-images.githubusercontent.com/43051571/68818392-eac98780-06d8-11ea-9b0f-1e8c690bcf84.png">

**Comment by wplit** [comment]
This is in latest version 3.1, didn't look at previous versions.

**Comment by KittenCodes** [comment]
Replicated in 3.1.

**Comment by gleysen** [comment]
I can confirm, having the same issue with post type conditions not working anymore.
When will this get fixed?!

**Comment by ivanjuras** [comment]
I can confirm, too. Please, fix this.

**Comment by KittenCodes** [comment]
Fixed in v3.2.

**Comment by pauldyke** [comment]
I am continuing to find that this doesn't work in v4.3. I can't use conditions to determine if a post is a parent.
