### ISSUE TITLE
DONE: Add the ability to use calc and rem to font size

### ISSUE THREAD

**Issue by petebytes** [soflyy/oxygen-bugs-and-features#72]
**Add the ability to use calc and rem for font sizes**
*Currently we have the option to use (px, %, em, auto, vw and vh*)

**What are the use cases for this feature?**
*There are times when I use calc for heading and subheadings.  A class is not a great option, since I change the calc based on the amount of text.
I prefer to use rem for spacing, and em for layouts.  This article has a good explanation of which to use when https://medium.com/code-better/css-units-for-font-size-px-em-rem-79f7e592bb97*

**Examples of this feature or functionality.**
*theme.co pro has the ability to use calc and rem, however nothing special about how they implemented it.  Just add more options to the existing drop-down*

![image](https://user-images.githubusercontent.com/676739/52730841-92166400-2f79-11e9-9f1a-e1c7573d018b.png)

How theme.co pro implements this option
![image](https://user-images.githubusercontent.com/676739/52730898-aeb29c00-2f79-11e9-958d-0bf3c8d69f1a.png)

**Comment by sunnyt7** [comment]
+1 for this. We definitely need to be able to use REM for font sizes.

**Comment by jamescrabb** [comment]
Calc being added to the UI would also be great

**Comment by TheLEAX** [comment]
+1 for REM ! Must have function with EM -- they are complementary functions

**Comment by creazy231** [comment]
+1 for `calc()`
+1 for `rem`

**Comment by johncrumpton** [comment]
em is relative to the font-size of its parent, while rem is only relative to the html (root) font-size. Please add rem.

**Comment by GianDS** [comment]
+1 Lovely Idea

**Comment by kevinrietveld** [comment]
+1 for rem

**Comment by jvorld** [comment]
+1 for calc()
+1 for rem

**Comment by KittenCodes** [comment]
This has been added.

**Comment by johncrumpton** [comment]
Thank you!
