### ISSUE TITLE
Setting padding to 0 doesn't work on section classes

### ISSUE THREAD

**Issue by sunnyt7** [soflyy/oxygen-bugs-and-features#720]
Noticed this bug on v3.0 and unfortunately kept forgetting to report it for v3.1. 

If you add a class to a section, and set any of the class' padding values to 0, it doesn't output on the front-end. 

Changing it to 1px or whatever else works. Setting it to 0 on the section ID also works.

To replicate:

- Create a section
- Add a class to it
- Set top/bottom padding to 0
- Check front-end. It will render your global section padding

**Comment by sunnyt7** [comment]
This is still a bug on v3.2. Plz fix so that I don't need to set paddings on IDs 😢

**Comment by chris-castillo-dev** [comment]
I've seen this problem as well and was not able to get the paddings to render properly even when setting the padding values on the ID. The CSS wasn't being generated in the Oxygen stylesheet unless the padding value was anything other than 0 (1px or more).

**Comment by chris-castillo-dev** [comment]
I'm experiencing the same issue. Setting padding values to IDs fixes it. Can we get a fix for this so we don't have to set values on IDs?

**Comment by davidlower8** [comment]
This is still a bug. I have found a walk around. If you delete the selector/class that you are using throughout for sections and reapply the styles - the bug goes away. For example, I usually use the class section-wrapper on all my sections. When this bug comes I delete that class from selector panel and reapply the class again with the same styles. Only needs to be done once. It is better than adding stuff to individual IDs.

**Comment by madjedo** [comment]
Bug still live... 3 years later

**Comment by dogstar10** [comment]
i'm still  seeing the same bug in v4...
i have a section with a class with 0px bottom padding...
on frontend the section takes the padding from the global styles and ignores the class....

**Comment by sunnyt7** [comment]
Sadly this is still a bug, and now you can't use the "none" unit workaround either.

**Comment by Spellhammer** [comment]
This should be fixed in the forthcoming 4.6 Beta 1.
