### ISSUE TITLE
perspective doenst seem to work at all.

### ISSUE THREAD

**Issue by peterpinkster** [soflyy/oxygen-bugs-and-features#731]
**Describe the bug**
*A clear and concise description of what the bug is.*
I tried to add perspective with the interface.. it doenst seems to work.
when I add custom CSS  `perspective: 1px;` I dont have any problems

I tried to put a paralax effect
https://keithclark.co.uk/articles/pure-css-parallax-websites/

**Comment by KittenCodes** [comment]
@peterpinkster Please set up an example of this on our Sandbox site and add the one click login to your reply: https://oxygenbuilder.com/try/.
