### ISSUE TITLE
Cannot sign shortcodes in WP 5.3

### ISSUE THREAD

**Issue by davidparys** [soflyy/oxygen-bugs-and-features#732]
**Describe the bug**
*A clear and concise description of what the bug is.*
After a migration from one domain to another, it is impossible to sign shortcodes

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
*Yes/No*

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
*If yes, provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*
Not really

**To Reproduce**
- Migrate one WP to another with a WP upgrade (5.2 to 5.3)

**Expected behavior**
the button should be clickable, but here nothing happens.

**Screenshots**
![image](https://user-images.githubusercontent.com/56082497/69012744-782b0700-0979-11ea-8981-824a2ccaa093.png)
The button is not clickable

**Comment by davidparys** [comment]
Deactivating this security check bugs out some of my templates. They don't load anymore either.

**Comment by KittenCodes** [comment]
@davidparys This is a known issue. You should be able to sign your shortcodes by disabling the Gutenberg add-on, signing the shortcodes and re-enabling the add-on.

**Comment by davidparys** [comment]
It actually worked on Firefox while it didn't on Chrome.
