### ISSUE TITLE
Translate functions trigger an error on 5.3 

### ISSUE THREAD

**Issue by davidparys** [soflyy/oxygen-bugs-and-features#733]
**Describe the bug**
It seems I have an issue, after migration to a new server with 5.3, some translate functions are not working properly.

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
*If yes, provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.**
No

Seems to be an issue maybe with a php extension that is not installed, can't figure out which one.

**Screenshots**
` // Translate
                        if ($transform['transform-type']=='translate') {
                                if ($transform['translateX'] && $transform['translateY'] && $transform['translateZ']) {
                                        $css .= "translate3d("
                                                . $transform['translateX'] . (isset($transform['translateX-unit']) ? $transform['translateX-unit'] : $defaults['translateX-unit']) . ","
                                                . $transform['translateY'] . (isset($transform['translateY-unit']) ? $transform['translateY-unit'] : $defaults['translateY-unit']) . ","
                                                . $transform['translateZ'] . (isset($transform['translateZ-unit']) ? $transform['translateZ-unit'] : $defaults['translateZ-unit']) . ")";
                                }
                                else if ($transform['translateX'] && $transform['translateY']) {
                                        $css .= $transform['transform-type'] . "("
                                                . $transform['translateX'] . (isset($transform['translateX-unit']) ? $transform['translateX-unit'] : $defaults['translateX-unit']) . ','
                                                . $transform['translateY'] . (isset($transform['translateY-unit']) ? $transform['translateY-unit'] : $defaults['translateY-unit']) . ")";
                                }
                                else if ($transform['translateX']) {
                                        $css .= $transform['transform-type'] . "("
                                                . $transform['translateX'] . (isset($transform['translateX-unit']) ? $transform['translateX-unit'] : $defaults['translateX-unit']) . ")";
                                }
                                else if ($transform['translateY']) {
                                        $css .= "translateY" . "("
                                                . $transform['translateY'] . (isset($transform['translateY-unit']) ? $transform['translateY-unit'] : $defaults['translateY-unit']) . ")";
                                }
                        }
`
![image](https://user-images.githubusercontent.com/56082497/69015533-2b552980-0995-11ea-9519-4a70610e9f06.png)

**Additional context**
To what refers the translate functions? Maybe there is a way to figure out the source.

**Comment by KittenCodes** [comment]
@davidparys If you're having this problem in the latest version of Oxygen, please open a support ticket: https://oxygenbuilder.com/support.
