### ISSUE TITLE
Color Picker launcher button display issue

### ISSUE THREAD

**Issue by lucas-pelton** [soflyy/oxygen-bugs-and-features#734]
**Describe the bug**
CSS from WP core is impacting the display of the color picker launch button

**To Reproduce**
Look at a color picker buton

**Expected behavior**
A circle

**What actually happens**
An oval

**Screenshots**
![image](https://user-images.githubusercontent.com/1626520/69075042-7dbe3680-09e5-11ea-90d8-f4ad9a63b1bf.png)

**Desktop (please complete the following information):**
- OS: Win10
 - Browser Chrome
 - Oxygen Version 3.1

**Comment by KittenCodes** [comment]
Fixed in Oxygen 3.2.
