### ISSUE TITLE
already exist

### ISSUE THREAD

**Issue by peterpinkster** [soflyy/oxygen-bugs-and-features#736]
**Describe the bug**
I created  selector ".ct_fancy_icon>svg" But I couldnt get it in a folder I created.
so I deleted the wrong folder withing the selector.. and try to create it again. But get this message:

`> '.ct_fancy_icon>svg' already exist.`

Getting a kind of tired of the bugs and missing options.

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
YES

The problem is that deleting folders doenst delete the selectors in the database

**Comment by KittenCodes** [comment]
@peterpinkster Please send login details for your site to support@oxygenbuilder.com so that we can take a look at this.
