### ISSUE TITLE
ACF data not being shown in repeater until Custom Post is resaved.

### ISSUE THREAD

**Issue by Hornet25** [soflyy/oxygen-bugs-and-features#738]
**Describe the bug**
I am using Oxygen 3.1. I have a Custom Post called Events that I am populating from the front end using a Gravity Form and connecting that to a Post Creation using the relevant add-on. I can create a post using the gravity form and I can see it in the back end. Up until 3.1 I have always used either post meta or PHP functions to display the custom fields as some where dates and I had real issues displaying dates in the front end. I understood that 3.1 rectified this so I gave it a go using the ACF fields as the dynamic data input. Now, when I create an event I can see the event with all of the data in the back end, but in the repeater all I see is the Post Title. The rest of the dynamic data fields are blank ('no data for this field'). If I go into the custom post in the back end and update the post, the data immediately appears. It is almost as if the contents of the post have been saved as a draft and it will not display without being resaved. I can get around this issue by saving the whole post as a draft in the Gravity Forms post creation add-on for this project, but I would obviously prefer to have a resolution.

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
*Yes*

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
It is tricky to emulate the problem in the sandbox as I would need several plugins to achieve it.

**To Reproduce**
See above

**Expected behavior**
I expected the dynamic data to appear as soon as the form was submitted and the post created.

**What actually happens**
The dynamic data of the post is only displayed after going into the post and 'updating' it.

**Screenshots**
*If applicable, add screenshots to help explain your problem.*

**Desktop (please complete the following information):**
- OS: Windows 10
 - Browser Chrome
 - Oxygen Version 3.1

**Comment by Hornet25** [comment]
I have tested this further and it appears that it works fine if you input the data directly into the custom post, it is when you use the Gravity form to populate the fields that Oxygen doesn't see the data until you resave the custom post. I am pretty certain this doesn't happen if you use post_meta or get_field in the PHP option to display the data.

**Comment by Spellhammer** [comment]
This is an issue with the way the front end submission works. When you save an ACF field from the post edit screen, two meta keys are generated, one visible and one not. When you submit ACF data from the front end using some solutions, only one of those keys is generated.

You should see the same inability to grab front-end submitted ACF data using get_field in a Code Block. It only works after saving via the post edit screen, because then the second key is generated for the fields.

If get_field also doesn't work until the post is re-saved, then it's not an Oxygen issue.

**Comment by Hornet25** [comment]
I have just done a test and using the get_field option in the PHP Function Return value field does let the dynamic data display without resaving the custom post in the back end. The problem with this option is that I cannot get the date to display in a preferred format. It seems to default to YYYY-mm-dd.

**Comment by estraatios** [comment]
I got the same problem when creating a repeater field on a page. I created text, image and date fileds in the repeater. Once I added a new row in the page in the repeater field the page lost the template.
I have a video where you can see it. 18:40 is the problem
https://youtu.be/3PWKz0eAyw4

**Comment by KittenCodes** [comment]
@Hornet25 Please email support@oxygenbuilder.com so that we can take a look at your site and how it's set up.
