### ISSUE TITLE
ACF Field Group Selected In Previewing Dropdown Results In 404 Error In Builder

### ISSUE THREAD

**Issue by Spellhammer** [soflyy/oxygen-bugs-and-features#74]
**Describe the bug**
When working with a Catch All template, the Previewing dropdown is populated with many post types that never should be edited via Oxygen, like ACF field groups. This can result in 404 errors within the builder while posts like those are selected in the Previewing dropdown.

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
N/A

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
Yes.

**To Reproduce**
1. Install ACF
2. Add a field group
3. Edit a Catch All template

**Expected behavior**
No 404 error.

**What actually happens**
Oxygen throws a 404 error because it's trying to request the field group, which doesn't work. This also causes the Menu element to fail to load. Everything works properly when you switch to a valid post in the Previewing dropdown.

**Screenshots**
N/A

**Comment by mflook** [comment]
Same issue here with Oxygen 2.2.

**Comment by dmccan** [comment]
Still happening with 2.3 beta 1

![image](https://user-images.githubusercontent.com/2622805/55843195-a18ad700-5afc-11e9-9650-350248d1a261.png)

**Comment by timpixel** [comment]
Perhaps it would be possible to build an option to hide/filter-out acf fields and such, in the preview dropdown. It's weird and unpractical to have all those acf fields showing up in the preview dropdown, making it somewhat unusable as well.

**Comment by KittenCodes** [comment]
This is fixed in the latest version of Oxygen.
