### ISSUE TITLE
ACF repeater field not showing after page data iiserted

### ISSUE THREAD

**Issue by estraatios** [soflyy/oxygen-bugs-and-features#746]
I created ACF fields with repeater (Text, Date Picket, Image and Wysiwyg) for a specific page and then went and add some data dor those fields.

After that, I created the front layout of the page using oxygen repeater element and everything worked fine.

After that, I went again to the backend of that page and add some more data.

I went to the front end and refresh the page. All data was gone.

I went to Oxygen edit page (it was still open) and saved. All data were back. I closed Oxygen.

After that again add some data to ACF fields and refresh the front end. Again blank page.

Went back to the backend and edit with Oxygen. All the layout I had created and the sections was gone.

I was making a video for my channel and you can see the point where I got the blank page in 18:40

https://www.youtube.com/watch?v=3PWKz0eAyw4&lc=z22bjdcierjedfpubacdp434ztrjc0yrrtu0hkve0htw03c010c

**Comment by KittenCodes** [comment]
@estraatios I'm not able to replicate this behaviour. Please email credentials for your site and a link to the template/page in your video to support@oxygenbuilder.com so that we can take a look.
