### ISSUE TITLE
3rd Party Support: Cookiebot breaks design/features

### ISSUE THREAD

**Issue by rorar** [soflyy/oxygen-bugs-and-features#749]
Hi there :-)
Cookiebot is one of the most famous Cookie Consent Plugin and well known for its automatic cookie detection.

**Describe the bug**
Cookiebot Plugin is enabled
I'm not a tec guy - what I can say is that it's breaking features like scripts, style and dropdowns.
Links won't open anymore - pages are blank.

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
YES

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
No - too bad :-/
http://jolly-seal.w6.wpsandbox.pro/

**To Reproduce**
Activate plugin.. 💩 is on fire, yo.

**Expected behavior**
Site's not breaking

**Desktop (please complete the following information):**
- OS: Win10
 - Browser Chrome
 - Oxygen Version 2.4

**Comment by KittenCodes** [comment]
@rorar As this isn't replicable on the Sandbox site, please send credentials for your site to support@oxygenbuilder.com so that we can take a look.

**Comment by rorar** [comment]
> @rorar As this isn't replicable on the Sandbox site, please send credentials for your site to [support@oxygenbuilder.com](mailto:support@oxygenbuilder.com) so that we can take a look.

will do it as soon i got some time, thanks for your reply :-)
