### ISSUE TITLE
Can't re-enable animations for all screen sizes

### ISSUE THREAD

**Issue by sunnyt7** [soflyy/oxygen-bugs-and-features#75]
Using 2.2 RC1.

It doesn't seem like there is a way to un-disable animations? (In Settings > Global Styles > Animate on Scroll).

To better explain... initially the animations are enabled for all devices. I chose to disable on mobile to test it out, but now it seems like I can't enable for all devices again? I think it's missing a blank selection from the dropdown.

![image](https://user-images.githubusercontent.com/5510344/52753902-8f8e2b80-2fc6-11e9-934c-f3fc0cb08210.png)

**Comment by KittenCodes** [comment]
This is fixed in the latest version of Oxygen.
