### ISSUE TITLE
BUG with Modal with condition POST TYPE

### ISSUE THREAD

**Issue by adrien-robert** [soflyy/oxygen-bugs-and-features#754]
I had Oxygen 2.4 I believe on a website, and was using a Modal on all my pages (the modal is inside my main template catch all) with an Oxygen condition on this modal to doesn't show on custom post type "ville" (= town). It always worked well.

But since I updated to Oxygen 3.1, my condition with Post Type on this modal doesn't work at all...

If I set "==" or "!=" the modal is always missing from the front-end...

I replicated the issue on this sandbox: http://talented-yacare.w6.wpsandbox.pro?upass=3ex3t4HDB9qW

![image](https://user-images.githubusercontent.com/4320990/69908918-7ab64380-13f2-11ea-83ea-080c0520abc8.png)

My modal with the condition never show on the html, either way (!= or ==)
If I have no condition on the modal or another condition that "Post Type", there is no problem.

**Comment by adrien-robert** [comment]
In the meantime I changed my condition and used Post ID conditions with the ID of the 3 pages (CPT Town/Ville) where I didn't wanted my modal

![image](https://user-images.githubusercontent.com/4320990/69909093-a981e900-13f5-11ea-8644-be1deaa52b27.png)

**Comment by srikat** [comment]
Known issue.

https://github.com/soflyy/oxygen-bugs-and-features/issues/719

**Comment by InStudiotz** [comment]
Conditions for Taxonomy terms not working either on version 3.1. 
I have had same issue on two sites 
<img width="837" alt="Screenshot 2019-12-03 at 09 08 21" src="https://user-images.githubusercontent.com/50168391/70027769-ef84ab80-15b3-11ea-95af-87955d30f878.png">

**Comment by gleysen** [comment]
I can confirm, having the same issue with post type conditions not working anymore.
When will this get fixed?!

**Comment by Spellhammer** [comment]
Post Type, Post Parent ID, and Taxonomy Term conditions are fixed in 3.2 beta 1.
