### ISSUE TITLE
Color picker resetting to 0 [red]

### ISSUE THREAD

**Issue by davidparys** [soflyy/oxygen-bugs-and-features#760]
**Describe the bug**
*A clear and concise description of what the bug is.*

Whenever you choose something in the color picker, the hue bar tends to go up for some reason where it shouldn't. And if you want to take a slight variation of white (top left corner) it goes fully back to top. 

**To Reproduce**
Just choose any colour other than red and try to pick a very slight variation of white of this colour. 

**Expected behavior**
*A clear and concise description of what you expected to happen.*
The hue bar shouldn't move vertically unless moved from the hue bar.

**Screenshots**
*If applicable, add screenshots to help explain your problem.*

[Gif showing it](https://imgur.com/YydszmA)

**Desktop (please complete the following information):**
Tested of Firefox & Chrome, same problem all latest version.

**Comment by KittenCodes** [comment]
@davidparys Please run a plugin conflict test by disabling all plugins (aside from Oxygen) and see if the issue persists. If it only happens with Oxygen active, please open a support ticket by emailing support@oxygenbuilder.com.
