### ISSUE TITLE
Missing dynamic condition operators for ACF fields (FIX INCLUDED)

### ISSUE THREAD

**Issue by yankiara** [soflyy/oxygen-bugs-and-features#763]
**Describe the bug**
When setting a dynamic condition with ACF field, only the following operators are available:
==, <=, >=, contains, is_blank, is_not_blank
This is not enough, we need at least:
!=, >, <, does not contain

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
*Yes*

**To Reproduce**
1. Edit page or template
2. Add any element
3. Add a condition
4. Select a ACF field for condition
5. Select operator

**Expected behavior**
The following operators (at least) should be available:
!=, >, <, does not contain

**What actually happens**
Only the following are available:
==, <=, >=, contains, is_blank, is_not_blank

**Screenshots**
![79215533_706544719873206_131044189549887488_n](https://user-images.githubusercontent.com/36680757/70376103-aad77800-1905-11ea-9d32-cfbd9926af57.jpg)

**Desktop (please complete the following information):**
- OS: NA
 - Browse: NA
 - Oxygen 3.1

**Comment by yankiara** [comment]
Here's the fix:
- edit /component-framework/component-init.php
- go to line 6191
- replace code with following PHP:

oxygen_vsb_register_condition('ZZOXYVSBDYNAMIC', array('custom'=>true), array('==', '!=', '>', '<', '>=', '<=', 'contains', 'does_not_contain', 'is_blank', 'is_not_blank'), "oxy_vsb_dynamic_condition_eval_callback", "Other");

function oxy_vsb_dynamic_condition_eval_callback($value, $operator, $shortcode) {

	if(stripos($shortcode, '[oxygen')  !== false) {
		$shortcode = ct_sign_oxy_dynamic_shortcode(array($shortcode));
	}
	else {
		return false;
	}
	
	$executed_shortcode = do_shortcode( $shortcode );

	if ($operator == "==") {
		if ($executed_shortcode == $value) {
			return true;
		} else {
			return false;
		}
	} else if ($operator == "!=") {
		if ($executed_shortcode != $value) {
			return true;
		} else {
			return false;
		}
	} else if ($operator == ">") {
		if ($executed_shortcode > $value) {
			return true;
		} else {
			return false;
		}
	} else if ($operator == "<") {
		if ($executed_shortcode < $value) {
			return true;
		} else {
			return false;
		}
	} else if ($operator == ">=") {
		if ($executed_shortcode >= $value) {
			return true;
		} else {
			return false;
		}
	} else if ($operator == "<=") {
		if ($executed_shortcode <= $value) {
			return true;
		} else {
			return false;
		}
	} else if ($operator == "contains") {
		if (strpos($executed_shortcode, $value) !== false) {
			return true;
		} else {
			return false;
		}
	} else if ($operator == "does_not_contain") {
		if (strpos($executed_shortcode, $value) === false) {
			return true;
		} else {
			return false;
		}
	} else if ($operator == "is_blank") {
		if (empty($executed_shortcode) ) {
			return true;
		} else {
			return false;
		}
	} else if ($operator == "is_not_blank") {
		if ( !empty($executed_shortcode) ) {
			return true;
		} else {
			return false;
		}
	} else {
		return false;
	}
}

**Comment by KittenCodes** [comment]
I've moved this over to feature requests and removed it from bugs.

**Comment by jcmatoskx** [comment]
> I've moved this over to feature requests and removed it from bugs.

I am facing the same issue. I understand it's not a bug, but I don't believe this is quite a "feature request" as much as it is a serious flaw/limitation in the mechanics of setting dynamic conditions.

Why on Conditions>Dynamic>ACF do we have the option equal, but not the option not equal/different than? like it is on other options? Why no "does not contain"?
It's simply not possible to cover all situations with the available options, at least not in an optimal case scenario.

I Have sections that I want to show, only when an ACF checkbox field is NOT selected/Not turned on, but that is not possible to achieve.

I also have sections I want to show by default and hide, when an ACF field is activated - Also not possible

Workarounds exist but are hacky and unnecessary. It's trying to work around a flaw of the system, not necessarily a lack of a feature. But setting up these workarounds requires making the ACF backend requiring more work and being more confusing for the final backend user, creating a less than optimal environment.

This feels like the equivalent of going to a "Make your own sandwich" restaurant, but being limited to only putting salad OR meat on the sandwich, and not being able to make it however you want.

Also the Conditions feature would have a lot more flexibility and power if the behaviour of the condition would not default to "Show if" but would let the user actually choose in the beginning what the condition behaviour would be "Show if" or "Hide if"

**Comment by yankiara** [comment]
I opened this bug more than 1 year ago... Now enhancement??? What a joke.
What are you waiting for to add the code I gave you?

**Comment by jcmatoskx** [comment]
I noticed that the backend has changed, now conditions are placed in their own file conditions.php 
but still no basic **!=, >, <, does not contain**  conditions for dynamic meta keys.
It's so frustrating this hasn't been fixed yet after all this time!😢

**Comment by KittenCodes** [comment]
Additional operators added in v3.8 Beta.

You should now see:

==, >=, <=, contains, is_blank, is_not_blank, !=, >, <, does_not_contain.
