### ISSUE TITLE
Non-editable and styling bugs in guttenberg Client view

### ISSUE THREAD

**Issue by anthonydvu** [soflyy/oxygen-bugs-and-features#766]
**Describe the bug**
Some elements are not editable within Guttenberg Client View. Other display styling bugs from client side. Examples include:
- Video URL not editable by client for video embeds.
- Multi column layouts display improperly

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
Yes

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
No. Seems to work okay in sandbox. 

**Expected behavior**
Expected behavior is that clients see page as it exactly is and all elements have some degree of editability for client.

**What actually happens**
- Many elements are not editable (i.e. embedded videos)
- Many styling issues occur in Guttenberg Client View

**Screenshots**
https://share.getcloudapp.com/QwuGRNxl
https://share.getcloudapp.com/nOumwGEX
https://share.getcloudapp.com/DOuvNze0

**Desktop (please complete the following information):**
- OS: Mac OSX Mojave
 - Browser: Chrome
 - Oxygen Version: 3.1

**Smartphone (please complete the following information):**
- not applicable for guttenberg editor. 

**Additional context**
*Add any other context about the problem here.*

**Comment by KittenCodes** [comment]
> Video URL not editable by client for video embeds

This is the expected behaviour. It's possible to edit the following field types:

- Text
- Rich Text
- Images
- Icons
- Link URLs
- Section Background Images

> Multi column layouts display improperly

Please create a support ticket by emailing details (including login credentials and a link to where we can see the problem) to support@oxygenbuilder.com.
