### ISSUE TITLE
wrap with div & structure panel

### ISSUE THREAD

**Issue by ramnathk** [soflyy/oxygen-bugs-and-features#77]
**Describe the bug**
*A clear and concise description of what the bug is.*
Hitting 'wrap with div' in the structure panel, causes the panel to go empty!

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
yes

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
*If yes, provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*

**To Reproduce**

1. create a template
2. open "structure" panel
3. add a heading
4. from the structure panel, click the hamburger and click 'wrap with div'
5. see bug

**Expected behavior**
a div is added as a parent in the structure panel 

**What actually happens**
the structure panel empties out

**Screenshots**
https://www.useloom.com/share/83d89ab96bd34573aa6a1426fdd836cd

**Desktop (please complete the following information):**
- OS: osx
 - Browser : Chrome
 - Oxygen Version: 2.2 RC1

**Comment by sunnyt7** [comment]
I have this issue on 2.3 beta 1 as well btw.

**Comment by Spellhammer** [comment]
Fixed in 3.0.

**Comment by matte619** [comment]
Same problem with 3.1

**Comment by KittenCodes** [comment]
@matte619 I'm not able to replicate this on a Sandbox site running v3.1. If you're able to replicate this on a Sandbox site, please send us the URL. You can create a Sandbox site here: https://oxygenbuilder.com/try/.
