### ISSUE TITLE
DONE: REM support for flexbox

### ISSUE THREAD

**Issue by Alexander-van-aken** [soflyy/oxygen-bugs-and-features#771]
We need REM value for flexbox. Check this out. Can we do that in Oxygen? My god, that saves me a ton of time.
https://www.youtube.com/watch?v=1jgsgvtdyn8&feature=youtu.be&t=102&fbclid=IwAR1hI-MMMuYe6QBQtzs8YLEL65v593RN7QGEOUSvnkJUzRC9zEiDD5jQa7o

**Comment by alriksson** [comment]
Themeco and their PRO theme used to be behind and slow. Now they have really caught up with their latest development cycles. And their new videos is very good as well just started recently.

Thing their panel is easier to use than Oxygen. And do not like that oxygen ID is not reset even once all css properties is disabled it still gives `flex-direction: unset;`

Themeco and PRO theme can be used for some better UX/UI and feature improvement inspiration for the Oxygen team to take into consideration.

**Comment by Alexander-van-aken** [comment]
100% agree.

**Comment by Deanphillips** [comment]
Agree, themeco are ahead now (by far imo)

**Comment by shinoamakusa** [comment]
If only Themeco Pro didnt allow creating template for Blog Posts we probably won't be looking for new builder at all ... Oxygen looks amazing but some stuff is either missing or a bit cumbersome

**Comment by KittenCodes** [comment]
Added REM in v3.6.
