### ISSUE TITLE
Horizontal Animation Squeezes Responsive Layout

### ISSUE THREAD

**Issue by ThePopularizer** [soflyy/oxygen-bugs-and-features#776]
**Describe the bug**

Horizontal animation effect narrows responsive layout width.

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**

N/A - not related to external elements. 

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**

Yes: 

https://oxygen-q5rn8ctl6g96k.oxygen-demo.qsandbox.me/

**To Reproduce**

1. Go to 'Edit with Oxygen'
2. Click on a section outside of view
3. Choose horizontal animation such as slide from left. 

**Expected behavior**

Keep mobile width regardless of animation. 

**What actually happens**

Mobile width narrows to accomodate horizontal animation. 

**Screenshots**1

![Image](https://i.imgur.com/gXsB6jX.png)

**Desktop (please complete the following information):**
- OS: MacOS High Sierra 
 - Browser: Chrome and Safari 
 - Oxygen Version 3.0.1

**Smartphone (please complete the following information):**
- Device: iPhone 6, Note 5
 - OS: Android, iOS 
 - Browser: Chrome, Safari 
 - Oxygen Version: 3.0.1

**Comment by KittenCodes** [comment]
@ThePopularizer Please add overflow: hidden to the parent element via Advanced > Layout as a workaround.

**Comment by ThePopularizer** [comment]
> @ThePopularizer Please add overflow: hidden to the parent element via Advanced > Layout as a workaround.

OK, thank you for the temporary workaround.

**Comment by Spellhammer** [comment]
This is an Animate on Scroll library issue, not an Oxygen bug. It can be fixed by adding overflow: hidden to the animated elements' container. In cases where you need vertical scrolling, you can add overflow-x: hidden to the container instead.

**Comment by etegan** [comment]
Upstream issue https://github.com/michalsnik/aos/issues/416
