### ISSUE TITLE
Create a new Component

### ISSUE THREAD

**Issue by gonzalesc** [soflyy/oxygen-bugs-and-features#777]
Hi,
I have searched and I didn't find anything.
Where can I found documentation to create a new component?

Regards

**Comment by srikat** [comment]
You can go through the code in  Oxygen WooCommerce and Oxygen Gutenberg extensions (plugins) and see how they did it.

**Comment by KittenCodes** [comment]
Third party tutorial: https://codewriteups.com/build-custom-oxygenbuilder-elements-in-wordpress.html
