### ISSUE TITLE
Pro-Menu width setting not applied on front end (3.2 alpha)

### ISSUE THREAD

**Issue by wplit** [soflyy/oxygen-bugs-and-features#781]
**Describe the bug**
When trying to set a width for the pro-menu component, it shows in the builder, but not on the front end. Only doesn't work when using classes.

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
Yes

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
[https://oxygen-q4nkclkgzbz6.oxygen-demo.qsandbox.me/](https://oxygen-q4nkclkgzbz6.oxygen-demo.qsandbox.me/) width of 100% applied to menu via class, not applied on front

**To Reproduce**
1. Add pro-menu to Oxygen page
2. Give it a class
3. Set a width with the visual controls
4. You will see it change, but after saving and viewing on the front the CSS isn't there.

**Comment by KittenCodes** [comment]
@wplit This seems to be the Menu element and not the Pro menu element?

**Comment by wplit** [comment]
This is happening for any element inside a header builder actually, I am unable to set the width using classes on elements. The CSS isn't applied on the front end.

**Comment by KittenCodes** [comment]
Thanks, I've updated our internal bug report.

**Comment by Spellhammer** [comment]
Fixed in 3.2 beta 1.
