### ISSUE TITLE
DONE: Add a "Edit with Oxygen" link below pages and posts

### ISSUE THREAD

**Issue by dawid-tuminski** [soflyy/oxygen-bugs-and-features#785]
**Describe the feature you'd like to see included in Oxygen.**
Would be great if we had a link "Edit with Oxygen" below pages and posts. We wouldn't have to first Click _Edit_ and then _Edit with oxygen_

**What are the use cases for this feature?**
Editing pages and and posts

**Examples of this feature or functionality.**
Divi has this functionality

**Comment by KittenCodes** [comment]
This has been implemented.
