### ISSUE TITLE
Wrong padding rendered on the Frontend

### ISSUE THREAD

**Issue by ddenev** [soflyy/oxygen-bugs-and-features#79]
**Describe the bug**
When a button with 2 classes is rendered on the frontent, there is a wrong padding added to one of the classes, which breaks the layout. The backend renders the padding correctly.

This is how it looks (and the generated CSS) on the backend:
![image](https://user-images.githubusercontent.com/1393766/52873873-b54b3a00-3158-11e9-857f-2efae16380f5.png)
![image](https://user-images.githubusercontent.com/1393766/52873907-cdbb5480-3158-11e9-870a-747b4abe352b.png)

This is how it looks (and the generated CSS) on the frontend (notice the "rogue" padding):
![image](https://user-images.githubusercontent.com/1393766/52873997-065b2e00-3159-11e9-9db8-530074bbeae3.png)
![image](https://user-images.githubusercontent.com/1393766/52874061-2db1fb00-3159-11e9-84bd-b5e3695a42d2.png)

I don't know if this bug manifests in other components I haven't tested that much.

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
Yes: http://thankful-eel.w6.wpsandbox.pro?upass=P1jwlKy21U5G

**To Reproduce**
1. Add a new Page and open it with Oxygen
2. Add a Section
3. In the Section set "Horizontal Item Alignment" to "Center"
4. Add a Button to the Section
5. Add 2 classes to the Button - "dde-button" and "dde-button--cta"
6. Select the "dde-button" class and add 60px left and right padding
7. Select the "dde-button--cta" class and in the Primary tab change one of the properties (I tested with Button Color, Button Hover Color, Text Color, Button Style)
8. Save the page and open the frontent view in a new tab

**Expected behavior**
The frontend should show the correct 60px paddings for the button

**What actually happens**
The backend and the frontent show different left/right paddings for the button

**Desktop (please complete the following information):**
- OS: Win7
 - Browser Chrome
 - Oxygen Version 2.2 RC1, reproduced in sandbox (2.1.2)

**Comment by KittenCodes** [comment]
#https://github.com/soflyy/oxygen/issues/1769

**Comment by drank** [comment]
This bug is still not fixed in the 3.1 beta 1 bugfix release.

**Comment by izaakbeer** [comment]
@KittenCodes @Spellhammer Any updated on this bug? Will it be addressed in version 4.0? 

It's been open for more than 3 years, since Feb 15th, 2019. It's still a bug in Oxygen version 3.9 (as I am running into this exact issue now).

**Comment by srikat** [comment]
FB group topic: https://www.facebook.com/groups/1626639680763454/posts/5017925754968146/?comment_id=5018027868291268&reply_comment_id=5018589168235138

**Comment by jschuh23** [comment]
Yes this is still a bug as I've run into the same issue recently. See FB link posted by @srikat above.

**Comment by Spellhammer** [comment]
Fixed in Oxygen 4.1 beta 1.
