### ISSUE TITLE
Invalid shortcodes warning when I put an accent in a ACF field/Oxygen Condition

### ISSUE THREAD

**Issue by ziogio98** [soflyy/oxygen-bugs-and-features#792]
**Describe the bug**
In general, Oxygen seems to hate accented letters. I usually avoid using them after I discovered this bug in my site, when I named a class "Hero_giorgiobarillà". The site displayed the invalid shortcode notice in the frontend and the oxygen support team told me to remove the "à". I did, and it worked fine. 

Now, I developed a new site with a lot of custom ACF fields and some Oxygen Conditions, and I used 1 time the word "sì" inside a condition linked to the answer "sì" of a dropdown menu select created with ACF.

"Sì" is the italian word for "yes", and writing "si" instead of "sì" is a grammatical mistake, since they mean totally different things. So, I sometimes forget the accent problem and use it. 

2 errors displayed in the backend, only on the pages where the condition was "display this when the selection on the dropdown menu is [sì]". I removed the conditions and everything worked fine, with no shortcodes error after that. 

The same thing happened on another site, with the same "sì" selection. I had to rename all the ACF fields to "si". 

BUT, strangely, I have another site where the "sì" word on conditions AND ACF fields does not create any issue. No idea why. Seems to be a issue 80% of the times, anyway. 

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**

Yes

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
I can, but I think it's a known issue. If it's not, please let me know and I'll try to recreate the problem in sandbox.

**To Reproduce**

1) Create a dropdown ACF field, with a choice being "sì"
2) Create a new page and a section
3) Set a display condition on the section: display when "dynamic data", "dynamic field" is "sì". 
4) Check the edit page backend, you will see the invalid shortcode notice

**Expected behavior**
Accents should not mess up the notice.

**What actually happens**
Accents have to be avoided in Oxygen, right now.

**Screenshots**
This is the notice inside the backend: https://ibb.co/xGj2jcJ

**Desktop (please complete the following information):**
- OS: Windows 10 Home
 - Browser Chrome, latest version
 - Oxygen Version 3.1

**Smartphone (please complete the following information):**
Not relevant.

**Comment by Martin-1** [comment]
Accented letters are very common in many languages. So this really NEEDS to be fixed.

**Comment by KittenCodes** [comment]
@ziogio98 I wasn't able to replicate this using Oxygen v3.1. If you're using 3.1 and experiencing the issue, please recreate it on our Sandbox site and send me the URL: https://oxygenbuilder.com/try/.
