### ISSUE TITLE
Custom social icons (Telegram, VK, etc)

### ISSUE THREAD

**Issue by codemotion** [soflyy/oxygen-bugs-and-features#796]
**Describe the feature you'd like to see included in Oxygen.**
*A clear, detailed description of the feature you're requesting.*

Oxygen social icons block is lack of world-famous social networks like Telegram or VK.

Just expanding of social networks list in the block settings will be enough. 

**What are the use cases for this feature?**
*e.g. Accessibility, e-commerce store that sells bicycles, etc.*

For all users who want to implement mentioned social networks on their sites.

**Examples of this feature or functionality.**
*If another product has done it well, provide examples here.*

There is no need to explain furthermore.

**Comment by KittenCodes** [comment]
Duplicate #234
