### ISSUE TITLE
Pagination in Easy Posts not working on static front page

### ISSUE THREAD

**Issue by Simbaclaws** [soflyy/oxygen-bugs-and-features#797]
Dear Oxygen team,

Apparently the custom query inside pagination for Easy Posts isn't working when put on the static front page of your website. Basically it entails the following bug in wordpress:

https://codex.wordpress.org/Pagination#static_front_page

(Check Static Front Page section in that url)

When you go to the advanced troubleshooting section on that url you'll see that in order to make pagination work for WP_Query inside a static front page you'll need to get the so called `get_query_var( 'paged' );` or `get_query_var( 'page' ); `attribute of a page on the home page.

This is then set to a variable called: $paged, which should be used inside the query for WP_Query of Easy posts like so:
`&paged=$paged `

inside of the query parameters.

Basically here is some wordpress boiler plate code that works out of the box:
```
<?php 
if ( get_query_var( 'paged' ) ) { $paged = get_query_var( 'paged' ); }
elseif ( get_query_var( 'page' ) ) { $paged = get_query_var( 'page' ); }
else { $paged = 1; }

$the_query = new WP_Query('posts_per_page=3&paged=' . $paged); 
?>
```

**Could you please add the ability to send a variable to the query parameters using PHP?**
**Or as a alternative solution: add the paged parameter to WP_query for each easy posts widget**

I've tried putting the following PHP inside the template PHP of easy posts and referencing that in the custom query, but I can not set it in the custom query section of easy posts.

I've tried doing this with a custom code block, but this means I'll have to recreate the easy posts within a custom code block, which is not ideal. This seems to work with pagination but for me it's pretty hard replicating the easy posts layout.

Please let me know what you think.
This issue is reproducable on any website because it's a wordpress bug that can be avoided with some simple PHP code. Please add this to your widget so that we can use custom post queries on the front page of a website.

Yours sincerely,
Hylke

**Comment by Simbaclaws** [comment]
Is there any progress on this issue since 2020? 
I understand it has been some rough times...

I keep having to use other plugins to create custom posts because the easy posts doesn't have this implemented.
Please let me know if anyone is looking into it....

**Comment by Spellhammer** [comment]
This should have been fixed in 3.9. If you're still experiencing the problem using Oxygen 3.9, please let me know.

**Comment by Simbaclaws** [comment]
Yes, I am still experiencing this on oxygen version 3.9.

Steps to reproduce:

- Create a static front page and set it as homepage in settings -> read
- Create a easy post on said front page
- Pagination doesn't work

Is there anything else I can do to help diagnose this issue?

**Comment by Simbaclaws** [comment]
Apologies, I just found out that it was my own mistake.

Apparently when you've accidentally set the posts and front page to the same page, this can make it so that pagination will cause the all posts page to display.

It's working now, thank you :)
