### ISSUE TITLE
DONE: More Options of Mobile Responsive Menu

### ISSUE THREAD

**Issue by sunnyt7** [soflyy/oxygen-bugs-and-features#80]
Would like to see some more customization options for the mobile menu. There are a couple things I currently need to do by hand:

1) If you're using an overlay menu, you're naturally going to set the menu's text colour to white to appear over whatever dark background you have behind it. However, this text colour also affects the close button on the mobile menu - meaning if you have white text and want a white bg mobile menu, the close icon won't appear. You need to set the close icon to be a dark colour using custom CSS.  The easy fix here is to allow you to set a colour for each of navigation text, burger icon, and close icon.

2) If I'm using the mobile menu on all device sizes, I want different font-sizes for the links.  For example, for desktops, I want much larger links in the mobile menu. Right now you can only set one font size, so this needs to be done by hand.

**Comment by gitsimhub** [comment]
would be great

**Comment by TnowL** [comment]
love to see this too

**Comment by adrien-robert** [comment]
I would like to have more control for responsive menu

For example with sub-menu for mobile:
- Show/Edit parent menu (with empty link/href)
- When we click on parent menu it show/hide the menu childrens

**Comment by Hornet25** [comment]
I definitely agree. I think there is a lot that could be enhanced with regards to Menus and Responsive Menus

**Comment by muzaffarsiddiqui** [comment]
+1

**Comment by Oxymaniac** [comment]
+1

**Comment by Spellhammer** [comment]
This should be addressed by the new Pro Menu element in 3.2, which is currently in beta.
