### ISSUE TITLE
Resigning shortcodes doesn't solve error. 

### ISSUE THREAD

**Issue by rrdirnens** [soflyy/oxygen-bugs-and-features#805]
**Describe the bug**
After saving my progress in Builder, the page I was building is empty(apart from template). 
Reopening the Oxygen builder I see the following: 
![image](https://user-images.githubusercontent.com/42729985/72268944-6e491b80-362b-11ea-968f-d5e7112214a8.png)
![image](https://user-images.githubusercontent.com/42729985/72268979-7a34dd80-362b-11ea-9ab3-9d4e421b732b.png)

In WP admin: 
![image](https://user-images.githubusercontent.com/42729985/72269114-b700d480-362b-11ea-88b7-e40801058bc2.png)
![image](https://user-images.githubusercontent.com/42729985/72269169-ced85880-362b-11ea-8f0a-7613bc4c38e4.png)

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
YES

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
NO

**Expected behavior**
The page is fine. 

**What actually happens**
The page is not fine. As described at top of this issue. 

**Desktop (please complete the following information):**
- OS: Win 10
 - Browser Chrome
 - Oxygen Version 3.1

Additional info: 
In the page that seems to cause the crash I am using two reusable components. I use these components in 3 other pages in the same way(same two on same page, same order, same structure) and it was fine.

**Comment by rrdirnens** [comment]
Update: trashing and remaking the page solved all issues, apparently. It's for sure possible I made some sort of mistake, but I honestly don't see what it could've been, as I did the same thing just now and everything is fine. 
Anyways, I hope my "solution" helps someone and maybe someone knows why this happens and how to prevent it, rather than fix it?

**Comment by KittenCodes** [comment]
@rrdirnens If you encounter this type of problem again, please send your site details to support@oxygenbuilder.com so that we can take a look.
