### ISSUE TITLE
Update fontawesome

### ISSUE THREAD

**Issue by CvH-Design** [soflyy/oxygen-bugs-and-features#807]
I would really appreciate, if you could update the integrated fontawesome-library on a regular basis. There are far more free icons by now and we always search for an icon at https://fontawesome.com/icons?d=gallery&m=free and then enter the name of the chosen icon at oxygen, but most of the icons are not integrated.

**Comment by NichCitarella** [comment]
FontAwesome 5 is a planned update for Oxygen 3.2. It is currently in its Alpha 1 stage of testing.

**Comment by CvH-Design** [comment]
Thank you! That is great news!
