### ISSUE TITLE
Dynamic Data fails to pull URLs from ACF field for links

### ISSUE THREAD

**Issue by NichCitarella** [soflyy/oxygen-bugs-and-features#808]
When using the dynamic data tool to pull a url field from ACF and insert it into the URL field for a link, no value is returned (ie the url is not actually inserted and it just becomes a dead link on the frontpage). However, when taking the same dynamic data code and putting it into a text box, the URL from ACF is correctly pulled and displayed on the front end.

I will update with the rest of the info shortly, just didn't want to forget to post this.

**Comment by KittenCodes** [comment]
@NichCitarella If you can recreate this issue on our Sandbox site, that would be a great help: https://oxygenbuilder.com/try/.
