### ISSUE TITLE
Pro menu text alignment doesn't work on 1st level items (vertical menu)

### ISSUE THREAD

**Issue by yankiara** [soflyy/oxygen-bugs-and-features#809]
**Describe the bug**
In desktop vertical menu, I need to align menu items to the left, but alignment option does not work with first level items. It only works with submenu items.

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
Yes

**To Reproduce**
1. Add a pro menu
2. Select vertical orientation
3. Text / Any alignment option
4. Check result (builder and frontend after save/reload)

**Expected behavior**
Main items should align accordingly to the selected option.

**What actually happens**
Main items are always centered (but sub menu items are OK).

**Desktop (please complete the following information):**
- OS: Windows 10
 - Browser: Firefox
 - Oxygen Version: 3.2 Alpha

**Comment by KittenCodes** [comment]
This is fixed in 3.2 Beta 1.
