### ISSUE TITLE
can't edit text fields inside link-wrappers

### ISSUE THREAD

**Issue by Alexander-van-aken** [soflyy/oxygen-bugs-and-features#817]
can't edit text fields inside link-wrappers. Only if you drag out the text field from the link-wrapper. See video https://drive.google.com/file/d/1WB5PJkYyo0hPtlTEp_yVh_vA3oQw9N6R/view

**Comment by KittenCodes** [comment]
@Alexander-van-aken I haven't been able to reproduce this on a clean Sandbox site. Please send your site info to support@oxygenbuilder.com so that we can take a look at your site.
