### ISSUE TITLE
Elements with background image URLs that contain special characters like 'í' disappear from builder after save and reload

### ISSUE THREAD

**Issue by dposnanski** [soflyy/oxygen-bugs-and-features#82]
**Describe the bug**
When I go to the builder, the divs containing background images disappear. They are visible in the frontend and in the shortcode, but they don't show up in the builder, not even in the structure. If I save, the divs disappear for good and are no longer visible in the shortcode.

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
Yes, but couldn't delete WPMUDEV Dashboard plugin since I'm using their hosting.

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
I wasn't able to reproduce it step-by-step, but I copied the shortcode from my installation into the sandbox and the same issue appeared. http://amiable-grouse.w6.wpsandbox.pro/

**To Reproduce**
1. Add a section or a div
2. Give said section or div a background image
3. Keep working on the site
4. At some point, after saving or going back to the builder, the divs will disappear

**Expected behavior**
I expect the builder to show me all the divs

**What actually happens**
The builder shows all divs except those with background images

**Screenshots**
This is how it looks like in the frontend:
![image](https://user-images.githubusercontent.com/22684573/52884803-5d6bfd80-316f-11e9-915a-2cf1175b8020.png)
This is how it looks like in the backend:
![image](https://user-images.githubusercontent.com/22684573/52884826-71176400-316f-11e9-8358-23f0eedfd6ec.png)

**Desktop (please complete the following information):**
- OS: Windows Version 10.0.17134 Build 17134
 - Browser: Chrome Version 72.0.3626.109 (Official Build) (64-bit)
 - Oxygen Version: 2.1.2

**Comment by Spellhammer** [comment]
What is the URL to the image that you're using as a background image? Does it contain any special characters?

**Comment by Spellhammer** [comment]
I was able to log in to your demo site and confirm that the URL to the image for the div that is disappearing contains a special character. This is a known issue in Oxygen and should be addressed in a future version of Oxygen. For now, image URLs should not contain special characters - in your case it is the **í** character in the image URL that's causing the Div to disappear.

**Comment by KittenCodes** [comment]
This is fixed in the latest version of Oxygen.
