### ISSUE TITLE
"Shortcodes lack a valid signature" and unable to edit page after adding slider with images

### ISSUE THREAD

**Issue by shaiunterslak** [soflyy/oxygen-bugs-and-features#820]
**Describe the bug**
I added a slider and added images to it in the oxygen visual editor. It now displays an error on the page in which I did so. It also doesn't allow me to scroll and edit then entire page, only the first bit. If I click structure in the visual editor - nothing shows up.

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
Yes

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
No

**Expected behavior**
element displayed - no error message - visible structure in editor - able to edit everything again.

**What actually happens**
element weird with visible short codes - can't see structure - can't edit everything on the page

**Desktop (please complete the following information):**
- OS: [e.g. iOS] mac os
 - Browser [e.g. chrome, safari] chrome
 - Oxygen Version [e.g. 2.2 Alpha] latest

**Comment by KittenCodes** [comment]
@shaiunterslak Please send your site details to support@oxygenbuilder.com so that we can take a look at this for you.
