### ISSUE TITLE
Link Wrapper changing color doesn't work on mouse hover.

### ISSUE THREAD

**Issue by JoaoPeixoto72** [soflyy/oxygen-bugs-and-features#824]
**Describe the bug**
*A clear and concise description of what the bug is.*
 I just select the icon inside a link wrapper, and go to :hover state and change the color. It works on oxygen editor, but when I save it, and check the result in the frontend it will not work. If i go change the effects and change opacity for example, it will work.

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
*Yes/No*
Yes

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
*If yes, provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*
Didn't tried, but asked on the facebook forum and others had the same problem, and asked me to fill a bug report.

**To Reproduce**
1. Create a link wrapper
2. Create a image inside that link wrapper
3. change the color on :hover state on the image
4. It will work on oxygen visual editor, but if you save, and go to frontend it will not change the color.

**Expected behavior**
*A clear and concise description of what you expected to happen.*
It should change the color.

**What actually happens**
*A clear and concise description of what happens instead of the expected behavior.*
Doesn't change the color.
**Screenshots**
*If applicable, add screenshots to help explain your problem.*

**Desktop (please complete the following information):**
 - Oxygen Version [e.g. 2.2 Alpha]

Browser Chrome on Windows 10
Oxygen 3.1

**Smartphone (please complete the following information):**
 - Oxygen Version [e.g. 2.2 Alpha]

**Additional context**
*Add any other context about the problem here.*

**Comment by KittenCodes** [comment]
@JoaoPeixoto72 Please can you record a quick video showing this (you can use Loom: https://www.loom.com/)?

**Comment by sphere-radio** [comment]
We are facing the same bug.

**Comment by gleysen** [comment]
Can this be opened again? (still having this problem)

**Comment by Spellhammer** [comment]
@sphere-radio-it @gleysen @JoaoPeixoto72 

I think this happens because the Link Wrapper has a color that overrides the hover color assigned to the icon.

If you want to do this, set the Link Wrapper's color to a different color on hover.

If you don't want all items dependent on the link wrapper's color to change on hover, add a custom state on the Link Wrapper:

:hover svg

Then change the color on that state.

Tested all of the above and it's working fine with 4.4 RC 1, should be fine in prior versions as well.

**Comment by sirhenryhu** [comment]
Sames here. The icon element was originally a child element in a link wrapper and I tried to pull it out to see if the link wrapper affected it and the issue remains. In my case, all hover settings on SVGs aren't working properly. Has this issue been fixed?

**Comment by oss001** [comment]
Same issue here. I went in and set the colors via CSS for the Link Wrappers.  Seems like the link wrapper has some colors associated with it that are not changeable in the interface. Not that I could find anyway...
