### ISSUE TITLE
Typing error on link button "edit individual border-radius"

### ISSUE THREAD

**Issue by quentin-th** [soflyy/oxygen-bugs-and-features#828]
Hello,

I just noticed a small typing error when styling the border radius of an element. The typing error is on the link button edit individual "radii" instead of "radius".

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
Yes

**To Reproduce**
It seems to happen on all elements.

1. Go to 'Advanced > border > border radius 
2. Under the field Border Radius, check the link button edit individual radii
2. See typing error

**Expected behavior**
It should be "edit individual radius"

**Screenshots**
![image](https://user-images.githubusercontent.com/19748866/73555361-c5cdf080-444d-11ea-86ef-0bb221f050aa.png)

**Comment by KittenCodes** [comment]
Fixed in v3.8 Beta 1.
