### ISSUE TITLE
Oxygen is incompatible with LearnDash Focus mode

### ISSUE THREAD

**Issue by vecchionico** [soflyy/oxygen-bugs-and-features#831]
**Describe the bug**
*Using LearnDash focus mode in a Oxygen website causes an infinite loop and the page where Focus mode is activated never finish loading*

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
*Yes*

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
*To replicate the issue simply install Oxygen and LearnDash, create a catch all Oxygen template and some dummy LD content (a single topic in a single course is enough), then activate the LD focus mode and check the topic page frontend. I'm not creating the sandbox myself because I'm not sure I can upload a third party commercial plugin to the sandbox site, but it's very easy to replicate*

**To Reproduce**
Check the previous section

**Expected behavior**
*Focus mode should work*

**What actually happens**
*Activating Focus mode creates an infinite loop and the website never loads*

**Desktop (please complete the following information):**
- OS: Linux
 - Browser: Chromium, Firefox
 - Oxygen Version: 3.1.1 and 3.2 beta 1

**Smartphone (please complete the following information):**
- Device: Android
 - OS: 9
 - Browser: Chromium and Firefox
 - Oxygen Version: 3.1.1 and 3.2 beta

**Additional context**
*The issue is probably caused because when enabling Focus mode LD tries to take control of the active theme, which in a Oxygen website is not available. This is more a conflict than a bug. If the issue can't be fixed (or LD devs should fix it) it should at least be advertised that Oxygen is not compatible with LearnDash *

**Comment by KittenCodes** [comment]
@vecchionico 

To use Focus Mode with Oxygen, you need to create a template and apply it to the four post types that use Focus Mode. These are:

- Lessons
- Topics
- Quizzes
- Assignments

Once you've saved the template, edit it with Oxygen. Add a Section element to the builder. Inside the Section, add a Text element and a Shortcode element. Add the [quizinfo] shortcode to the Shortcode element.

The text element will be used to get the lesson, topic, quiz and assignment content dynamically. Do do this, double click the text element and click Insert Data on the top bar. Select "Content" and click the Done button.

Here's a quick video: https://www.loom.com/share/cbfe0fa053b24940a4d2a14d1fa79ed5.

I hope this helps.

**Comment by vecchionico** [comment]
confirmed working, ty.

**Comment by techfairy** [comment]
video is not full width in Focus Mode in such kind of template. All other text, embed pdf etc are full width, but video half  width. It is not good looking ..

**Comment by chokeul8r** [comment]
Yeah - the solution provided did not work for me. I still get the infinite loop in focus mode.

**Comment by ErykJaroszewicz** [comment]
> Here's a quick video: https://www.loom.com/share/cbfe0fa053b24940a4d2a14d1fa79ed5.
> I hope this helps.

This workaround is no longer working... (probably shortcodes functionality in LD has changed due to new certificate builder)
Does anybody know the other way?

**Comment by ErykJaroszewicz** [comment]
(...) Oxygen is not compatible with LearnDash *
This is unfurtunately true for now (Focus mode is the 'heart' of LearnDash). Sorry to hear/say this.
Any comments on this?

**Comment by dickyibrohim** [comment]
Will this finish in V4?. I think 3.9 is still having problems with infinite loop (focus mode)
