### ISSUE TITLE
AJAX request failed

### ISSUE THREAD

**Issue by LaStationWeb** [soflyy/oxygen-bugs-and-features#835]
**Describe the bug**
Problem with Regenerating CSS.

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
YES

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
This is a completely fresh install.

**To Reproduce**
1. Create "re-usable part' - many of them
2. Add Global Color
3. Save
4. See AJAX Request Failed on some of the Template ID

**Expected behavior**
No problem in regenerating cache

**What actually happens**
*A clear and concise description of what happens instead of the expected behavior.*

**Screenshots**

**Desktop (please complete the following information):**
- OS: Linux Pop Os
 - Browser Chromium
 - Oxygen Version 3.1.1

**Additional context**
I followed all the troubleshooting steps and I can't figure out why this happen. This seem to be something that keeps happening across all my sites.

**Comment by KittenCodes** [comment]
@LaStationWeb Please send your site info to support@oxygenbuilder.com so that we can take a look at this for you.
