### ISSUE TITLE
Audio player ,mp3 player 

### ISSUE THREAD

**Issue by pezjr** [soflyy/oxygen-bugs-and-features#836]
Audio player or mp3 player element. 
Not everybody uses sound cloud.
The built in WordPress audio player is a pain to use with oxygen.
The first oxygen add a audio player element ( if i remember )
You just uploaded your audio-mp3 file or pasted the mp3 URL ,and you could style it any way you wanted. 
This would open oxygen to podcast , music ,DJ and radio websites.

**Comment by tontontoine** [comment]
When I bought Oxygen, I couldn't imagine there was not a simple way to display an audio player for self-hosted mp3 !
I only managed to put a block code with this PHP code  : echo wp_audio_shortcode(array('src' => get_post_field('url_audio')));
(I have a custom post field called url_audio)
But there's no styling option at all with this method...
I'm working on a new version of a music review website so I created a review custom post type and everything went fine (except for the problem with target URL)... until I tried to add the mp3 in my template...

**Comment by KittenCodes** [comment]
You can add an audio file by using the following code in the PHP & HTML tab of a Code Block element:

```html
<audio controls>
  <source src="https://mysite.com/files/audio-file.mp3" type="audio/mpeg">
Your browser does not support the audio element.
</audio>
```

**Comment by pezjr** [comment]
kitten code 
not everyone is a code person.
Oxygen builder had this element originally 
is that not why oxygen was developed not to use code . 
Like tontontoine said styling issues with code and short code elements .
Tried all word press plugins  and coding options.
oxygen builder should have never taken out the original audio element .
I do realize  Support Specialist at Oxygen don't see a market in podcasting fall on deaf ears, or just close the ticket

**Comment by pezjr** [comment]
kitten code
not everyone is a code person.
Oxygen builder had this element originally
is that not why oxygen was developed not to use code .
Like tontontoine said styling issues with code and short code elements .
Tried all word press plugins and coding options.
oxygen builder should have never taken out the original audio element .
I do realize Support Specialist at Oxygen don't see a market in podcasting fall on deaf ears, or just close the ticket

**Comment by pezjr** [comment]
> Kpudlo Did you ever read the post or just past and copy kittencode reply which is not app-able. Should the responds I would get .
