### ISSUE TITLE
Learndash 3 Focus Mode Broken.

### ISSUE THREAD

**Issue by Flipback8** [soflyy/oxygen-bugs-and-features#838]
Learndash Focus Mode breaks Learndash. 

I made a video a while back when the problem first arose. Here it is 
[Please Watch This Video](https://www.loom.com/share/b3552a3b00554a7cb79ecf5672a6b2e8)

After further investigation, I discovered that Focus Mode is the cause. Please fix so I can use Oxygen with Learndash.

**Describe the bug**
*A clear and concise description of what the bug is.*

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
*Yes/No*

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
*If yes, provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*

**To Reproduce**

**Expected behavior**
*A clear and concise description of what you expected to happen.*

**What actually happens**
*A clear and concise description of what happens instead of the expected behavior.*

**Screenshots**
*If applicable, add screenshots to help explain your problem.*

**Desktop (please complete the following information):**
 - Oxygen Version [e.g. 2.2 Alpha]

**Smartphone (please complete the following information):**
 - Oxygen Version [e.g. 2.2 Alpha]

**Additional context**
*Add any other context about the problem here.*

**Comment by KittenCodes** [comment]
Closed - duplicate #839
