### ISSUE TITLE
Submenu persistence between items selections

### ISSUE THREAD

**Issue by michacassola** [soflyy/oxygen-bugs-and-features#840]
**Submenu persistence between items selections**
When editing several items often one wants to edit the same attributes for example animations in the submenu animations. In my opinion it would make sense to stay in the same submenu even when switching over to another item. Of course only if the item has such a submenu. Editing would go a lot quicker this way and less clicks would be required.

**What are the use cases for this feature?**
Every Oxygen worker ever would benefit from this. It is basic usability.

**Comment by KittenCodes** [comment]
#13 

#112

**Comment by michacassola** [comment]
Ah, sorry for the duplicate post, should I delete it @KittenCodes ?

**Comment by KittenCodes** [comment]
@michacassola Yes please.

**Comment by michacassola** [comment]
All i could do is close it, I think it has to be deleted by an admin.
