### ISSUE TITLE
[v.3.1] Icon color does not change on hover

### ISSUE THREAD

**Issue by alpabuz** [soflyy/oxygen-bugs-and-features#842]
When adjusting the color of the icon for the hover state, the result is not displayed on the frontend (but works in the editor of Oxygen).
The bug has been verified through multiple tests and confirmed by several users.

1. Add new icon
2. Add hover state
3. Set new color for hover state
4. See the problem on the front end: when you hover the color does not change

 - Oxygen Version 3.1-3.1.1

When checking the code, I found that the color settings for the state during hovering are not displayed at all in the CSS. If you adjust the change in opacity on hover, then it works.

![Icon color does not change on hover](https://picabox.ru/pictures/2020/02/05/14/01/18408040.png)

**WORKAROUND**: 
Add a class for the icon and make settings for the class.

Edited: You can also work around this problem by using the Typography color settings in the Advanced tab. Thanks [Abhijeet Deshpande](https://www.facebook.com/abhijeet.deshpande4) for this idea.

**Comment by brendanquine** [comment]
Confirming this is still an ongoing issue.

**Comment by wdaellenbach** [comment]
a more eloquent workaround would be to add a class to your icon, and add custom CSS to that class:
`color: inherit;`

**Comment by zsoltmar** [comment]
I got around this limitation by removing the color from the icon and then applying a class to the wrapping link element. This class contains the intended icon color (as `color:`) and the hover color and it works because SVGs are set to `fill:currentColor`.

**Comment by joezingaro** [comment]
This is still an outstanding issue. 

Confirmed icon hover not working with Oxygen 4.0.3 and Wordpress 6.0.2

**Comment by wheeleran** [comment]
is there still no resolution of this? i've tried the above suggestions but it's not working for me.

**Comment by Josi-C** [comment]
At me it works with:

1. Add hover state
2. Advanced
3. Background
4. Image Overlay Color

WordPress 6.1.1 / Oxygen 4.2

**Comment by alFrame** [comment]
Not fixed. WP 6.5 and Oxygen 4.8.1...
