### ISSUE TITLE
Numerous errors in Angular.js when using Gravity Forms.

### ISSUE THREAD

**Issue by m0ch** [soflyy/oxygen-bugs-and-features#843]
![Screenshot 2020-02-05 at 20 05 00](https://user-images.githubusercontent.com/60708220/73864701-28126100-4853-11ea-8e25-81e49374e3cc.png)

**Describe the bug**
*Numerous errors in Angular.js when using Gravity Forms.*

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
*Yes*

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
*Yes. https://oxygen-qvjdhvcr2g36.oxygen-demo.qsandbox.me/sample-page/?ct_builder=true*

**To Reproduce**
1. Activate Gravity Forms.
2. Open Oxygen editor.
3. See errors in the console.

**Expected behavior**
*Expected this not to happen.*

**What actually happens**
*A lot of errors in Angular.js.*

**Screenshots**
*Added.*

**Desktop (please complete the following information):**
- OS: Catalina
 - Browser: Chrome
 - Oxygen Version: 3.1

**Comment by m0ch** [comment]
> @KittenCodes, why have you closed this?
> 
> The bug is still there in 2.4.1 (I just reproduced it) and I don't see any "fix" in the code for 3.0beta2.
> 
> I have provided enough info about the bug and the environment (and also about a potential fix) above - someone at Oxygen just needs to take it from there and implement a fix.

After six months it's still there.

**Comment by drank** [comment]
@m0ch, yes, I'm utterly disappointed with the way Oxygen manages their bugfixing. Even though I provided them with fixes for several of the bugs, they are still ignoring them. It is what it is... :)

**Comment by m0ch** [comment]
@drank, that's very disappointing. I guess you haven't solve this one on your own?

**Comment by KittenCodes** [comment]
This should be fixed in 3.2 Beta 1.

**Comment by m0ch** [comment]
> This should be fixed in 3.2 Beta 1.

@KittenCodes, when is it expected to be released?

**Comment by Spellhammer** [comment]
@m0ch We don't provide release estimates or timelines.

**Comment by michacassola** [comment]
You guys are hurting your own brand. Please question some of your choices dear Oxygen team.

**Comment by m0ch** [comment]
> @m0ch We don't provide release estimates or timelines.

@Spellhammer, that's fantastic. keep up the good work!

**Comment by m0ch** [comment]
I wonder how many people use Oxygen with Gravity Forms without knowing that they are incompatible. And if there may be security issues associated with this.

**Comment by Spellhammer** [comment]
> I wonder how many people use Oxygen with Gravity Forms without knowing that they are incompatible. And if there may be security issues associated with this.

They aren't incompatible. Oxygenbuilder.com has always used Gravity Forms for our support form. Besides the annoying console errors, using them together doesn't actually cause any problems.

> You guys are hurting your own brand. Please question some of your choices dear Oxygen team.

Is this in reference to the fact that we don't release estimates or timelines for development?

**Comment by michacassola** [comment]
@Spellhammer Yes, but mostly style of communication. There is an issue to be addressed here and even if you don't say when, you have to disarm peoples fear that Oxygen doesn't work with other Angular.js stuff. You don't do that with "We don't provide release estimates or timelines.", but more likely with something like: "Sorry that you have problems with ..., we are looking into it. We will provide more information here or in our next release notes that address this issue."

How can you trust a software company if concerns are brushed off?

You're explanation before quoting me should have been the answer, as this addresses the issue and offers reassurance.
