### ISSUE TITLE
Woocommerce Gallery Image Flicker on Zoom

### ISSUE THREAD

**Issue by plopdaddy** [soflyy/oxygen-bugs-and-features#845]
**Describe the bug**
Issue: WooCommerce Gallery Image flicker.
I have searched the group and can only see that it was supposed to be fixed in 3.1 - I am running 3.1.1
Oxygen Elements for WooCommerce 1.1
It is a new site (still in dev) so probably started with that version.

When I hover over the main image the zoom works fine. 
When I change the color & size options it is also fine.

But, as soon as I go to any of the gallery images it starts flickering and nothing fixes it unless i refresh the page.

[https://share.getcloudapp.com/kpumXr5n] 

I am pretty sure it was doing this from early on.

I tried deactivating any plugins, incl cache, that I thought might conflict but didn't help.

I added the basic product builder and did not custom build the template.

This is the facebook post I tried to get it sorted and was provided with a solution that fixes the issue.
.woocommerce img:not(.zoomImg){transition:transform ease 0.2s!important;}
Provided by Alexander Buzmakov
https://www.facebook.com/groups/1626639680763454/permalink/2740505019376909/

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
YES

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
I went to the test site but it does not include Woocommerce. 

**To Reproduce**
Please see initial info (above)

**Expected behavior**
I would expect that when you hover over a single product gallery image it does not flicker

**What actually happens**
See Initial info (Above)

**Screenshots**
[https://share.getcloudapp.com/kpumXr5n] 

**Desktop (please complete the following information):**
- Windows 10
 - Browser Firefox
 - Oxygen Version 3.1.1

**Smartphone (please complete the following information):**
 - Oxygen Version [e.g. 2.2 Alpha]

**Additional context**
*Add any other context about the problem here.*

**Comment by KittenCodes** [comment]
@plopdaddy 

> Oxygen Elements for WooCommerce 1.1

Please update to v1.1. You can download it from the customer portal here: https://oxygenbuilder.com/portal.
