### ISSUE TITLE
Conflict with WPMUDEV's Smush Pro plugin.

### ISSUE THREAD

**Issue by shoelaced** [soflyy/oxygen-bugs-and-features#849]
**Describe the bug**
*A clear and concise description of what the bug is.*

When Smush Pro is enabled, Oxygen fails to load properly and various issues appear, such as duplicate icons and long loading times. I'm not sure if it's happening with the free version of Smush but it didn't start happening until I updated Smush to v3.5.1. I'll put in a ticket with WPMUDEV too.

**Comment by shoelaced** [comment]
Update: WPMUDEV took a look at it and found out it that it's caused by the Lazyloading feature in Smush. After disabling Lazyloading it works fine, but it's still definitely a conflict. I'm not sure if it needs to be fixed in Smush or in O2 but there you have it.

**Comment by KittenCodes** [comment]
Please add "ct_builder" to the Smush Lazy Load exclude settings to prevent it from running in the builder: https://d.pr/i/gVARAO.

**Comment by shoelaced** [comment]
This doesn't work. The Lazyload exclusion settings support relative URL paths, but not URL query parameters.

**Comment by KittenCodes** [comment]
@shoelaced I've used this on a number of sites without problems. Please send your site details to support@oxygenbuilder.com so that we can take a look.
