### ISSUE TITLE
Header and footer styles reset on backend with pricing box when using '

### ISSUE THREAD

**Issue by dposnanski** [soflyy/oxygen-bugs-and-features#850]
**Describe the bug**
If I use ' in the title, subtitle or "normally $X", the styles of the header and footer reset. They go back to normal when I click on another pricing box, and reset again when I click on another pricing box again. Bug found when using an odd number of ' in the text. Looks ok on the frontend. It doesn't happen if the pricing box is on the same template as header and footer.

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
No

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
Yes https://oxygen-qmwdgtan8m47k.oxygen-demo.qsandbox.me/?ct_template=front&ct_builder=true&ct_inner=true

**To Reproduce**
1. Create a Main Catch-All Template
2. Add a Header Builder, an Inner Content and a Section as Footer
3. Add some menus/styling to Header and Footer
4. Create a Front Page Template
6. Add a Pricing Box
7. Add a ' to Title, Subtitle or "normally X" texts
8. See error
9. Add another ' to any of those fields
10. Error gone

**Expected behavior**
I expect the styling to look the same no matter the characters I use.

**What actually happens**
Styling of header/footer resets on backend when I use ' in any of the mentioned fields.

**Screenshots**
With an odd number of '
![image](https://user-images.githubusercontent.com/22684573/74219828-3080f680-4cae-11ea-9398-0c318facded7.png)
With an even number of '
![image](https://user-images.githubusercontent.com/22684573/74219936-76d65580-4cae-11ea-9dac-f07499e89eda.png)

**Desktop:**

- OS: Windows 10 Version 10.0.17763 Build 17763
- Browser: Chrome Version 79.0.3945.130 (Official Build) (64-bit)
- Oxygen Version: Oxygen 3.2 Beta 1 (Also happens in the previous version)

**Comment by KittenCodes** [comment]
Replicated in v3.1.

**Comment by KittenCodes** [comment]
Fixed in v3.8 Beta 1.
