### ISSUE TITLE
[3.2 Beta 1] The CSS property 'transition-duration' is missing when added to a Class

### ISSUE THREAD

**Issue by mikeingz** [soflyy/oxygen-bugs-and-features#853]
**Describe the bug**

Pretty big bug here.
When we add a transition to a class (Effects / Transition), the transition-duration will be missing in the CSS.
It will work on the backend, but NOT in the frontend.

On an ID:

![image](https://user-images.githubusercontent.com/2438157/74423292-fd478e80-4e8a-11ea-813d-450d6f44c7dc.png)

On a Class:

![image](https://user-images.githubusercontent.com/2438157/74423351-151f1280-4e8b-11ea-9d02-ecbf10ca3efb.png)

It's is currently breaking all the transition effects from design sets (when used with Class).

**Comment by KittenCodes** [comment]
Fixed in v3.2.
