### ISSUE TITLE
DONE: Custom Link Attributes

### ISSUE THREAD

**Issue by wpsumo** [soflyy/oxygen-bugs-and-features#858]
**Describe the feature you'd like to see included in Oxygen.**
Custom Link Attributes: Add HTML attributes directly to your <a> tags

Implement relations SEO properties (noopener, noreferrer...) 
Utilize Google’s new attribution for sponsored links and user-generated content? (rel="sponsored" and rel="ugc" [released by Google](https://webmasters.googleblog.com/2019/09/evolving-nofollow-new-ways-to-identify.html) this past September)

Custom Link Attributes `rel|noopener,rel|sponsored`

**What are the use cases for this feature?**
enhancement link controls 

It would also be useful to support JS-based attributes `onclick`. Up for discussion regarding security risk. But this can be added manually anyhow with a code block so I don't see the issue.

**Examples of this feature or functionality.**
Elementor 2.9

**Comment by Spellhammer** [comment]
I'd recommend checking this out: https://www.erropix.com/products/oxygen-attributes/.

**Comment by alriksson** [comment]
Thanks, but this is something to be considered a part of the core. right now using code block to solve it. Just think such basic web features should be a part of the core.

**Comment by us4consulting** [comment]
It's a basic feature.

**Comment by us4consulting** [comment]
Abdelouahed Errouaguy is a member of Oxygen Team. He is creator of Oxygen Attribute.( https://www.erropix.com/products/oxygen-attributes/).
This is why you do not want to be included in the core.
It's a shame .

**Comment by alriksson** [comment]
Yes thanks. Aware of the plugin and many attributes can be added by using a code block. But feeling more and more I have to use code block as the native blocks miss basic features. It's a bit sad as Oxygen is lovely to work with if all tiny things would tighten up.

**Comment by us4consulting** [comment]
I add https://github.com/soflyy/oxygen-bugs-and-features/issues/358 (Alt Text for icon)  in  Jun 11, 2019 .
They did not make this simple change.

**Comment by Spellhammer** [comment]
Target, rel, and custom attributes implemented in 3.5 alpha 1.

**Comment by wpsumo** [comment]
@Spellhammer Please consider adding dynamic function to the custom attributes and CSS class, so we can control this more dynamic than static values only.

**Comment by swinggraphics** [comment]
This has only sort-of been implemented. If you add links within text blocks, you still can't do anything with them at all, including edit them…
