### ISSUE TITLE
Shortcode Wrapper truncates shortcodes that have a dash/hyphen

### ISSUE THREAD

**Issue by petebytes** [soflyy/oxygen-bugs-and-features#86]
**Describe the bug**
*When you try to use a Shortcode Wrapper that contains a hypen, for example [mepr-active]
the shortcode is truncated at the hyphen and automatically adds a truncated closing tag*

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
*Yes*

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
*If needed I can provide access to an environment*

**To Reproduce**
1. Edit a template
2. Add a shortcode wrapper with a shortcode that contains a - (in memberpress there are several for example [mepr-unauthorized-message])
3.  On the view you should see the truncated closing tag [/mepr]

**Expected behavior**
*You should not see a truncated closing shortcode tag*

**Additional context**
*I am setting up a membership site and several of the shortcodes use hyphens which I use to show or hide content*

![image](https://user-images.githubusercontent.com/676739/52908973-43005580-323d-11e9-9de1-a2c32e0ea0ea.png)

**Comment by petebytes** [comment]
Note: using 2.2 RC2

**Comment by wplit** [comment]
I can confirm this is happening in 2.2 release also.

**Comment by petebytes** [comment]
@wplit has provided a mod to address the - dash issue here https://github.com/soflyy/oxygen-bugs-and-features/issues/106

Hope this can be incorporated in the next release :)

**Comment by petebytes** [comment]
What is the status on this - @wplit actually provided what may be the fix and I do not see any activity here.

**Comment by wplit** [comment]
seems to work fine in 2.3, using [mepr-show if="loggedout"][/mepr-show  without trouble. Also, memberpress supports underscore shortcodes so we can do it either way.

**Comment by petebytes** [comment]
@wplit cool thanks

**Comment by KittenCodes** [comment]
This is fixed in the latest version of Oxygen.
