### ISSUE TITLE
Pro Menu mobile drop-down link

### ISSUE THREAD

**Issue by estraatios** [soflyy/oxygen-bugs-and-features#865]
When I configure the drop-down in the mobile, the link for the drop-down should be the parent word and not just the icon.

As it is now you have to click the icon to see the drop-down menu. If you click the word that has the icon nothing happens (except the rotation of the icon).

Version : 3.2

**Comment by greatgraphicdesign** [comment]
I'm shocked it was set up this way.

**Comment by Spellhammer** [comment]
Let's assume you have a menu like this:

- Parent Link (url: google.com)
  - Sub link (url: google.com/something)
  - Sub link (url: google.com/something)

If we make the entire "Parent Link" link the trigger for the dropdown, clicking it will either:

- Cause the user to follow the link when they really wanted to trigger the dropdown
- Cause the dropdown to be triggered when they really wanted to follow the link

To solve this, we set the icon as the clickable toggle to activate dropdowns.

This could be improved by making the clickable area full-width for parent links that have a href of #

**Comment by yankiara** [comment]
"This could be improved by making the clickable area full-width for parent links that have a href of #"

This would be great!
And same behaviour with href empty, please!

**Comment by KittenCodes** [comment]
> This could be improved by making the clickable area full-width for parent links that have a href of #

This has been done in v3.2.1 RC 1.
