### ISSUE TITLE
DONE: Pro Menu - needs dropdown menu transition timing

### ISSUE THREAD

**Issue by greatgraphicdesign** [soflyy/oxygen-bugs-and-features#867]
The desktop dropdown menu needs a transition timing slider. I would like to be able to set the timing faster because it's too easy to pull away from the parent before the transition is completed, and if you do this the submenu disappears.

**Comment by Spellhammer** [comment]
The dropdown menu animation timing is inherited from the global AOS settings.

Improving usability of the dropdowns is something we're working on internally, namely making it easier to slide the mouse to animated dropdowns without the dropdowns reversing their animation.
