### ISSUE TITLE
Pro Menu - mobile menu anchors should be full width and height

### ISSUE THREAD

**Issue by greatgraphicdesign** [soflyy/oxygen-bugs-and-features#870]
The anchor tags in the mobile menu need to be 100% width and height so they are the size of the entire block. That way the entire block is clickable. I'm calling this a bug vs. feature request because it is expected behavior, and the current setup will frustrate visitors.

**Comment by Spellhammer** [comment]
Can you please elaborate with screenshots?

Which "entire block" should the links be the size of?

**Comment by greatgraphicdesign** [comment]
The anchor tags need to be as wide as the li tags. I am able to do this by...

@media screen and (max-width: 767px)
#menu-main-menu .menu-item a {
    display: inline-block;
    width: 100%;
}

This should be your default.
