### ISSUE TITLE
Show template name while editing

### ISSUE THREAD

**Issue by jmcbade** [soflyy/oxygen-bugs-and-features#871]
To show what template being edited besides the URL
Display the template name at the top of the edit screen

**What are the use cases for this feature?**
When editing using the Oxygen layout editor

**Examples of this feature or functionality.**
Just about every app in all the computer world :)

**Comment by srikat** [comment]
A plugin for this in the meantime: https://wordpress.org/plugins/wpdevdesign-oxygen-currently-editing/

**Comment by Spellhammer** [comment]
https://github.com/soflyy/oxygen-bugs-and-features/issues/592
