### ISSUE TITLE
What needs to be updated in the database when Changing hostname ?

### ISSUE THREAD

**Issue by runechronos** [soflyy/oxygen-bugs-and-features#879]
I don't know what to do in order to make the oxygen website load everything it needs, when I change my URL for example from http://localhost/blabla to http://MYIPADRESS/blabla (where MYIPADRESS is my actual IP Adress), in order to acces it from other computers on the network. It would be the same issue when going from dev to production with the real URL.

Before oxygen I used to update all infos with a script like:

> UPDATE wp_options SET option_value = replace(option_value, 'http://www.oldurl', 'http://www.newurl') WHERE option_name = 'home' OR option_name = 'siteurl';
UPDATE wp_posts SET guid = replace(guid, 'http://www.oldurl','http://www.newurl');
UPDATE wp_posts SET post_content = replace(post_content, 'http://www.oldurl', 'http://www.newurl');
UPDATE wp_postmeta SET meta_value = replace(meta_value,'http://www.oldurl','http://www.newurl');

 

But with Oxygen it seems other things needs to be linked again in the databse, like the css files and dynamic data embedded maybe ? 
For now I only get to see the raw text and icon, nothing is loaded except that (raw html it seems).
I didn't find the info, so I posted it here :s It's not really a bug I guess, just a lack of knowledge from me.

I think the problem is the "background-image url property" in the css files, that is not updated. And makes everything crash. How do you automatically change this value, when you move to production for example ?

Thanks in advance for your help.

**Comment by KittenCodes** [comment]
I would suggest using a plugin for this, such as Better Search Replace, or migrating the full site using All In One Migration.

You will also likely need to:

- Save your permalinks twice
- Resign your shortcodes via Oxygen > Settings > Security
- Regenerate your CSS cache via Oxygen > Settings > CSS Cache
