### ISSUE TITLE
Pro Menu - faulty slide-left animation on iOS

### ISSUE THREAD

**Issue by Rados51** [soflyy/oxygen-bugs-and-features#884]
**Describe the bug**
*Slide-left off-canvas animation works perfectly on desktop, but its without any transition when menu icon is clicked on mobile (iOS/Safari). On menu close, animation/slide works fine.*

**Expected behavior**
*Animation with transition delay when open mobile menu*

**What actually happens**
*Quick slide without delay*

**Screenshots**
https://youtu.be/ShhS-4ZDFEM

**Smartphone**
- Device: iphone 7
 - OS: 13.3.1
 - Browser Safari
 - Oxygen Version 3.2

**Comment by KittenCodes** [comment]
@Rados51 I haven't been able to replicate this issue.

Please send login details for your site and a link to the template that contains your menu element to support@oxygenbuilder.com so that we can take a look at the settings in your Menu element.

**Comment by Rados51** [comment]
@KittenCodes Hi, I've sent you an email with a login. Replicated the same problem inside the sandbox.

**Comment by KittenCodes** [comment]
Thanks @Rados51.
