### ISSUE TITLE
onResize event with wooCommerce product Images

### ISSUE THREAD

**Issue by Alexander-van-aken** [soflyy/oxygen-bugs-and-features#887]
When changing the viewports width of the browser, the code does not update the current state of the image size accordingly. see example video https://drive.google.com/file/d/1cb2T1xU5gIJOjyB53CKK2EtCQyvCVdqG/view

**Comment by KittenCodes** [comment]
Hey @Alexander-van-aken

I've not been able to replicate this - is it still a problem for you?

**Comment by Alexander-van-aken** [comment]
Heya :) I can’t remember anymore what the issue was. Can’t play my vid anymore. Can be closed.

**Comment by KittenCodes** [comment]
Sorry @Alexander-van-aken! Thanks for confirming.
