### ISSUE TITLE
Gallery widget cause an error in template editor; Uncaught TypeError: jQuery(...).photoSwipe is not a function on line #3

### ISSUE THREAD

**Issue by SpeedyWebPL** [soflyy/oxygen-bugs-and-features#888]
**Describe the bug**
Gallery widget cause an error in template editor.

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
*Yes*

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
*Yes*

**To Reproduce**
1. Edit home page in Oxygen (or another page)
2. Add gallery widget and save
3. Go to Oxygen->Templates
4. Click to edit Main template
5. Set preview on page with gallery widget
6. See error

**Expected behavior**
*No error*

**What actually happens**
*Uncaught TypeError: jQuery(...).photoSwipe is not a function on line #3*

**Screenshots**
![screen](https://user-images.githubusercontent.com/39051457/76340445-e8301500-62fb-11ea-8e8c-555a50ed13ff.jpeg)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: chrome
 - Oxygen Version 3.2

**Comment by alriksson** [comment]
I see various type of error in the builder lately. Together with errors in the console. Maybe it's time to improve the angular as it's also starts to become very slow once loader the builder while using ACF and fetch data dynamically.

**Comment by claytonschase** [comment]
Seeing the same error

**Comment by linformatique** [comment]
I am having the same issue, using Oxygen version 3.3.1 and Wordpress version 5.4.2

**Comment by siapliw** [comment]
I have the same error.

**Comment by KittenCodes** [comment]
The error occurs because the template doesn't know to load the photoSwipe JS files. We have replicated and reported the issue internally. However, it shouldn't impact the working of the front-end of your site.

**Comment by KittenCodes** [comment]
Fixed in 3.7 Beta 1: https://oxygenbuilder.com/2021/01/22/oxygen-3-7-beta-1-now-available/.
