### ISSUE TITLE
Getting error occurred while saving 200

### ISSUE THREAD

**Issue by mikeazores** [soflyy/oxygen-bugs-and-features#89]
**Describe the bug**
I'm getting "error occurred while saving" message following by 200.

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
Yes

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
*If yes, provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*

**To Reproduce**
1.Edit a page in oxygen
2. Change some images
4. Hit Save

**Expected behavior**
The page is saved without any error.

**What actually happens**
The page is saved BUT the red error window is shown with this message. I have to refresh the page to keep working.

**Screenshots**
![oxyerror](https://user-images.githubusercontent.com/9259573/53001602-54a75000-342b-11e9-9c18-8b1d6fa6b7f2.png)

**Desktop (please complete the following information):**
- OS: Mac OS
 - Browser Chrome
 - Oxygen 2.2 RC2

**Additional context**
Javascript error from my console:
<br />
<b>Deprecated</b>:  Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php://input stream instead. in <b>Unknown</b> on line <b>0</b><br />
<br />
<b>Warning</b>:  Cannot modify header information - headers already sent in <b>Unknown</b> on line <b>0</b><br />
<br />
<font size='1'><table class='xdebug-error xe-warning' dir='ltr' border='1' cellspacing='0' cellpadding='1'>
<tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> Warning: Cannot modify header information - headers already sent in /Users/xxx/www/kinesia360/wp-admin/includes/misc.php on line <i>1144</i></th></tr>
<tr><th align='left' bgcolor='#e9b96e' colspan='5'>Call Stack</th></tr>
<tr><th align='center' bgcolor='#eeeeec'>#</th><th align='left' bgcolor='#eeeeec'>Time</th><th align='left' bgcolor='#eeeeec'>Memory</th><th align='left' bgcolor='#eeeeec'>Function</th><th align='left' bgcolor='#eeeeec'>Location</th></tr>
<tr><td bgcolor='#eeeeec' align='center'>1</td><td bgcolor='#eeeeec' align='center'>0.0012</td><td bgcolor='#eeeeec' align='right'>399400</td><td bgcolor='#eeeeec'>{main}(  )</td><td title='/Users/xxx/www/kinesia360/wp-admin/admin-ajax.php' bgcolor='#eeeeec'>.../admin-ajax.php<b>:</b>0</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>2</td><td bgcolor='#eeeeec' align='center'>0.8348</td><td bgcolor='#eeeeec' align='right'>70269640</td><td bgcolor='#eeeeec'>do_action(  )</td><td title='/Users/xxx/www/kinesia360/wp-admin/admin-ajax.php' bgcolor='#eeeeec'>.../admin-ajax.php<b>:</b>44</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>3</td><td bgcolor='#eeeeec' align='center'>0.8348</td><td bgcolor='#eeeeec' align='right'>70271032</td><td bgcolor='#eeeeec'>WP_Hook->do_action(  )</td><td title='/Users/xxx/www/kinesia360/wp-includes/plugin.php' bgcolor='#eeeeec'>.../plugin.php<b>:</b>453</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>4</td><td bgcolor='#eeeeec' align='center'>0.8348</td><td bgcolor='#eeeeec' align='right'>70271272</td><td bgcolor='#eeeeec'>WP_Hook->apply_filters(  )</td><td title='/Users/xxx/www/kinesia360/wp-includes/class-wp-hook.php' bgcolor='#eeeeec'>.../class-wp-hook.php<b>:</b>310</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>5</td><td bgcolor='#eeeeec' align='center'>0.8514</td><td bgcolor='#eeeeec' align='right'>70888824</td><td bgcolor='#eeeeec'><a href='http://www.php.net/function.call-user-func-array:{/Users/xxx/www/kinesia360/wp-includes/class-wp-hook.php:286}' target='_new'>call_user_func_array:{/Users/xxx/www/kinesia360/wp-includes/class-wp-hook.php:286}</a>
(  )</td><td title='/Users/xxx/www/kinesia360/wp-includes/class-wp-hook.php' bgcolor='#eeeeec'>.../class-wp-hook.php<b>:</b>286</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>6</td><td bgcolor='#eeeeec' align='center'>0.8514</td><td bgcolor='#eeeeec' align='right'>70889624</td><td bgcolor='#eeeeec'>wp_admin_headers(  )</td><td title='/Users/xxx/www/kinesia360/wp-includes/class-wp-hook.php' bgcolor='#eeeeec'>.../class-wp-hook.php<b>:</b>286</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>7</td><td bgcolor='#eeeeec' align='center'>0.8514</td><td bgcolor='#eeeeec' align='right'>70890432</td><td bgcolor='#eeeeec'><a href='http://www.php.net/function.header' target='_new'>header</a>
(  )</td><td title='/Users/xxx/www/kinesia360/wp-admin/includes/misc.php' bgcolor='#eeeeec'>.../misc.php<b>:</b>1144</td></tr>
</table></font>
<br />
<font size='1'><table class='xdebug-error xe-warning' dir='ltr' border='1' cellspacing='0' cellpadding='1'>
<tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> Warning: Cannot modify header information - headers already sent in /Users/xxx/www/kinesia360/wp-content/plugins/oxygen/component-framework/includes/ajax.php on line <i>275</i></th></tr>
<tr><th align='left' bgcolor='#e9b96e' colspan='5'>Call Stack</th></tr>
<tr><th align='center' bgcolor='#eeeeec'>#</th><th align='left' bgcolor='#eeeeec'>Time</th><th align='left' bgcolor='#eeeeec'>Memory</th><th align='left' bgcolor='#eeeeec'>Function</th><th align='left' bgcolor='#eeeeec'>Location</th></tr>
<tr><td bgcolor='#eeeeec' align='center'>1</td><td bgcolor='#eeeeec' align='center'>0.0012</td><td bgcolor='#eeeeec' align='right'>399400</td><td bgcolor='#eeeeec'>{main}(  )</td><td title='/Users/xxx/www/kinesia360/wp-admin/admin-ajax.php' bgcolor='#eeeeec'>.../admin-ajax.php<b>:</b>0</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>2</td><td bgcolor='#eeeeec' align='center'>0.8580</td><td bgcolor='#eeeeec' align='right'>70946280</td><td bgcolor='#eeeeec'>do_action(  )</td><td title='/Users/xxx/www/kinesia360/wp-admin/admin-ajax.php' bgcolor='#eeeeec'>.../admin-ajax.php<b>:</b>99</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>3</td><td bgcolor='#eeeeec' align='center'>0.8580</td><td bgcolor='#eeeeec' align='right'>70947704</td><td bgcolor='#eeeeec'>WP_Hook->do_action(  )</td><td title='/Users/xxx/www/kinesia360/wp-includes/plugin.php' bgcolor='#eeeeec'>.../plugin.php<b>:</b>453</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>4</td><td bgcolor='#eeeeec' align='center'>0.8580</td><td bgcolor='#eeeeec' align='right'>70947944</td><td bgcolor='#eeeeec'>WP_Hook->apply_filters(  )</td><td title='/Users/xxx/www/kinesia360/wp-includes/class-wp-hook.php' bgcolor='#eeeeec'>.../class-wp-hook.php<b>:</b>310</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>5</td><td bgcolor='#eeeeec' align='center'>0.8580</td><td bgcolor='#eeeeec' align='right'>70950320</td><td bgcolor='#eeeeec'><a href='http://www.php.net/function.call-user-func-array:{/Users/xxx/www/kinesia360/wp-includes/class-wp-hook.php:286}' target='_new'>call_user_func_array:{/Users/xxx/www/kinesia360/wp-includes/class-wp-hook.php:286}</a>
(  )</td><td title='/Users/xxx/www/kinesia360/wp-includes/class-wp-hook.php' bgcolor='#eeeeec'>.../class-wp-hook.php<b>:</b>286</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>6</td><td bgcolor='#eeeeec' align='center'>0.8580</td><td bgcolor='#eeeeec' align='right'>70951504</td><td bgcolor='#eeeeec'>ct_save_components_tree_as_post(  )</td><td title='/Users/xxx/www/kinesia360/wp-includes/class-wp-hook.php' bgcolor='#eeeeec'>.../class-wp-hook.php<b>:</b>286</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>7</td><td bgcolor='#eeeeec' align='center'>1.0345</td><td bgcolor='#eeeeec' align='right'>74265856</td><td bgcolor='#eeeeec'><a href='http://www.php.net/function.header' target='_new'>header</a>
(  )</td><td title='/Users/xxx/www/kinesia360/wp-content/plugins/oxygen/component-framework/includes/ajax.php' bgcolor='#eeeeec'>.../ajax.php<b>:</b>275</td></tr>
</table></font>
{"page_settings_saved":false,"global_settings_saved":false,"classes_saved":false,"custom_selectors_saved":false,"style_sheets_saved":false,"global_colors":false,"google_fonts_cache":null}
09:41:45.335 iframe.min.js?ver=2.1.9:6 SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at iframe.min.js?ver=2.1.9:6
    at angular.js?ver=1.4.2:9280
    at processQueue (angular.js?ver=1.4.2:13075)
    at angular.js?ver=1.4.2:13091
    at Scope.$eval (angular.js?ver=1.4.2:14291)
    at Scope.$digest (angular.js?ver=1.4.2:14107)
    at Scope.$apply (angular.js?ver=1.4.2:14395)
    at done (angular.js?ver=1.4.2:9569)
    at completeRequest (angular.js?ver=1.4.2:9756)
09:41:45.336 VM4645:1 XHR finished loading: POST "https://localhost/kinesia360/wp-admin/admin-ajax.php?action=ct_save_components_tree&ct_inner=true&nonce=c621cfa37e&post_id=62".

**Comment by Spellhammer** [comment]
Is this in a local dev environment? EasyPHP Dev Server by chance?

**Comment by mikeazores** [comment]
> Is this in a local dev environment? EasyPHP Dev Server by chance?

Is a local environment in Mac OS (custom made). Here are the environment:

PHP Built On | Darwin MacBook-Pro-de-Miguel-2.local 17.7.0 Darwin Kernel Version 17.7.0: Thu Dec 20 21:47:19 PST 2018; root:xnu-4570.71.22~1/RELEASE_X86_64 x86_64
-- | --
Database Version | 5.5.5-10.2.13-MariaDB-log
Database Collation | utf8_general_ci
PHP Version | 5.6.33
Web Server | Apache/2.4.29 (Unix) OpenSSL/1.0.2n PHP/5.6.33
WebServer to PHP Interface | apache2handler


I must notice that this error occurs randomly (1 of 5 times) and I didn't be able to reproduce when I want. Also, this is also happening with version 2.2 RC1. I didn't test on other versions.

**Comment by Spellhammer** [comment]
This should be fixed in Oxygen 2.2.1. Can you confirm?

**Comment by mikeazores** [comment]
I just tried with Oxygen 2.2.1 and I can confirm this is not fixed. Probably it took a bit more time to throw the error though.

Here is my browser console:
`b>Deprecated</b>:  Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php://input stream instead. in <b>Unknown</b> on line <b>0</b><br />
<br />
<b>Warning</b>:  Cannot modify header information - headers already sent in <b>Unknown</b> on line <b>0</b><br />
<br />
<font size='1'><table class='xdebug-error xe-warning' dir='ltr' border='1' cellspacing='0' cellpadding='1'>
<tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> Warning: Cannot modify header information - headers already sent in /www/xxxx/wp-admin/includes/misc.php on line <i>1144</i></th></tr>
<tr><th align='left' bgcolor='#e9b96e' colspan='5'>Call Stack</th></tr>
<tr><th align='center' bgcolor='#eeeeec'>#</th><th align='left' bgcolor='#eeeeec'>Time</th><th align='left' bgcolor='#eeeeec'>Memory</th><th align='left' bgcolor='#eeeeec'>Function</th><th align='left' bgcolor='#eeeeec'>Location</th></tr>
<tr><td bgcolor='#eeeeec' align='center'>1</td><td bgcolor='#eeeeec' align='center'>0.0012</td><td bgcolor='#eeeeec' align='right'>406872</td><td bgcolor='#eeeeec'>{main}(  )</td><td title='/www/xxxx/wp-admin/admin-ajax.php' bgcolor='#eeeeec'>.../admin-ajax.php<b>:</b>0</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>2</td><td bgcolor='#eeeeec' align='center'>0.9364</td><td bgcolor='#eeeeec' align='right'>79604608</td><td bgcolor='#eeeeec'>do_action(  )</td><td title='/www/xxxx/wp-admin/admin-ajax.php' bgcolor='#eeeeec'>.../admin-ajax.php<b>:</b>44</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>3</td><td bgcolor='#eeeeec' align='center'>0.9365</td><td bgcolor='#eeeeec' align='right'>79606000</td><td bgcolor='#eeeeec'>WP_Hook->do_action(  )</td><td title='/www/xxxx/wp-includes/plugin.php' bgcolor='#eeeeec'>.../plugin.php<b>:</b>453</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>4</td><td bgcolor='#eeeeec' align='center'>0.9365</td><td bgcolor='#eeeeec' align='right'>79606240</td><td bgcolor='#eeeeec'>WP_Hook->apply_filters(  )</td><td title='/www/xxxx/wp-includes/class-wp-hook.php' bgcolor='#eeeeec'>.../class-wp-hook.php<b>:</b>310</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>5</td><td bgcolor='#eeeeec' align='center'>0.9596</td><td bgcolor='#eeeeec' align='right'>80591312</td><td bgcolor='#eeeeec'><a href='http://www.php.net/function.call-user-func-array:{/www/xxxx/wp-includes/class-wp-hook.php:286}' target='_new'>call_user_func_array:{/www/xxxx/wp-includes/class-wp-hook.php:286}</a>
(  )</td><td title='/www/xxxx/wp-includes/class-wp-hook.php' bgcolor='#eeeeec'>.../class-wp-hook.php<b>:</b>286</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>6</td><td bgcolor='#eeeeec' align='center'>0.9596</td><td bgcolor='#eeeeec' align='right'>80592112</td><td bgcolor='#eeeeec'>wp_admin_headers(  )</td><td title='/www/xxxx/wp-includes/class-wp-hook.php' bgcolor='#eeeeec'>.../class-wp-hook.php<b>:</b>286</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>7</td><td bgcolor='#eeeeec' align='center'>0.9596</td><td bgcolor='#eeeeec' align='right'>80592920</td><td bgcolor='#eeeeec'><a href='http://www.php.net/function.header' target='_new'>header</a>
(  )</td><td title='/www/xxxx/wp-admin/includes/misc.php' bgcolor='#eeeeec'>.../misc.php<b>:</b>1144</td></tr>
</table></font>
<br />
<font size='1'><table class='xdebug-error xe-warning' dir='ltr' border='1' cellspacing='0' cellpadding='1'>
<tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> Warning: Cannot modify header information - headers already sent in /www/xxxx/wp-content/plugins/oxygen/component-framework/includes/ajax.php on line <i>275</i></th></tr>
<tr><th align='left' bgcolor='#e9b96e' colspan='5'>Call Stack</th></tr>
<tr><th align='center' bgcolor='#eeeeec'>#</th><th align='left' bgcolor='#eeeeec'>Time</th><th align='left' bgcolor='#eeeeec'>Memory</th><th align='left' bgcolor='#eeeeec'>Function</th><th align='left' bgcolor='#eeeeec'>Location</th></tr>
<tr><td bgcolor='#eeeeec' align='center'>1</td><td bgcolor='#eeeeec' align='center'>0.0012</td><td bgcolor='#eeeeec' align='right'>406872</td><td bgcolor='#eeeeec'>{main}(  )</td><td title='/www/xxxx/wp-admin/admin-ajax.php' bgcolor='#eeeeec'>.../admin-ajax.php<b>:</b>0</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>2</td><td bgcolor='#eeeeec' align='center'>0.9648</td><td bgcolor='#eeeeec' align='right'>80648296</td><td bgcolor='#eeeeec'>do_action(  )</td><td title='/www/xxxx/wp-admin/admin-ajax.php' bgcolor='#eeeeec'>.../admin-ajax.php<b>:</b>99</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>3</td><td bgcolor='#eeeeec' align='center'>0.9648</td><td bgcolor='#eeeeec' align='right'>80649720</td><td bgcolor='#eeeeec'>WP_Hook->do_action(  )</td><td title='/www/xxxx/wp-includes/plugin.php' bgcolor='#eeeeec'>.../plugin.php<b>:</b>453</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>4</td><td bgcolor='#eeeeec' align='center'>0.9648</td><td bgcolor='#eeeeec' align='right'>80649960</td><td bgcolor='#eeeeec'>WP_Hook->apply_filters(  )</td><td title='/www/xxxx/wp-includes/class-wp-hook.php' bgcolor='#eeeeec'>.../class-wp-hook.php<b>:</b>310</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>5</td><td bgcolor='#eeeeec' align='center'>0.9648</td><td bgcolor='#eeeeec' align='right'>80652336</td><td bgcolor='#eeeeec'><a href='http://www.php.net/function.call-user-func-array:{/www/xxxx/wp-includes/class-wp-hook.php:286}' target='_new'>call_user_func_array:{/www/xxxx/wp-includes/class-wp-hook.php:286}</a>
(  )</td><td title='/www/xxxx/wp-includes/class-wp-hook.php' bgcolor='#eeeeec'>.../class-wp-hook.php<b>:</b>286</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>6</td><td bgcolor='#eeeeec' align='center'>0.9648</td><td bgcolor='#eeeeec' align='right'>80653520</td><td bgcolor='#eeeeec'>ct_save_components_tree_as_post(  )</td><td title='/www/xxxx/wp-includes/class-wp-hook.php' bgcolor='#eeeeec'>.../class-wp-hook.php<b>:</b>286</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>7</td><td bgcolor='#eeeeec' align='center'>1.1276</td><td bgcolor='#eeeeec' align='right'>83978368</td><td bgcolor='#eeeeec'><a href='http://www.php.net/function.header' target='_new'>header</a>
(  )</td><td title='/www/xxxx/wp-content/plugins/oxygen/component-framework/includes/ajax.php' bgcolor='#eeeeec'>.../ajax.php<b>:</b>275</td></tr>
</table></font>
{"page_settings_saved":false,"global_settings_saved":false,"classes_saved":false,"custom_selectors_saved":false,"style_sheets_saved":false,"global_colors":false,"google_fonts_cache":null}
11:49:49.546 iframe.min.js:6 SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at iframe.min.js:6
    at angular.js:9280
    at processQueue (angular.js:13075)
    at angular.js:13091
    at Scope.$eval (angular.js:14291)
    at Scope.$digest (angular.js:14107)
    at Scope.$apply (angular.js:14395)
    at done (angular.js:9569)
    at completeRequest (angular.js:9756)`

![Kinesia360  Centro de Osteopatía  Sacrocraneal y Reflexokinesia](https://user-images.githubusercontent.com/9259573/54600989-4a826c80-4a3e-11e9-98c4-b191ea9d9397.png)

**Comment by mradeck** [comment]
i am getting the same error... since v 2.2 also with 2.3 when I got this error, my whole pages are empty and i have to restore the whole database, this is very annoying...

**Comment by KittenCodes** [comment]
Hey @mikeazores,

If this is still an issue in the latest version of Oxygen, please replicate it on a debug site at https://oxygenbuilder.com/debug/ and send us the login. Alternatively, take a backup of a site with these issues using WP All In One Migration and send us the .wpress file along with credentials to log in so that we can investigate. Please also include a link to the page where you're getting the error.

**Comment by mikeazores** [comment]
Sorry, I updated my development environment so I no longer have PHP 5.6 installed to check if the error persists. As far as I noticed, this issue is related to PHP version as in PHP 7 doesn't pop.

**Comment by KittenCodes** [comment]
Thanks for the update @mikeazores
