### ISSUE TITLE
Bug with Modal + Gallery and Sticky Header

### ISSUE THREAD

**Issue by runechronos** [soflyy/oxygen-bugs-and-features#896]
Here is the bug:

When i create a Gallery with lightboxes inside a modal element, and my website is using a Sticky Header. The sticky header is still there, and i can't remove it or put the gallery above it (tried with Z-Indexes). So I can't see full images when i'm inside  the lightboxes, the sticky header always overlaps it. Is it a bug or is there a way to make it disapear in that particular case ?

Look at the screenshot:

![lightbox-modal-bug](https://user-images.githubusercontent.com/9034096/76508515-d01cda80-644e-11ea-8f3e-d66f0ed64239.jpg)

**Comment by Xilonz** [comment]
Does setting the position to relative on the gallery help? z-indexes only work on positioned elements. (so not position: static).

**Comment by KittenCodes** [comment]
@runechronos You can change the z-index of the Lightbox using CSS so that it is in front of the sticky header. Please add the following CSS to a stylesheet via Manage > Stylesheets in the top right of the builder:

```css
.pswp {
	z-index: 2147483641 !important;
}
```

**Comment by runechronos** [comment]
Thx for the answer , I've got another problem:
The modal element don't overlap the section under it, it is shrinked, yet when I look with the inspector, I see the element having the proper height, but it is cut. I tried to force **"overflow: visible"** , on the modal-id or ct-modal class as it is a fixed positioning but it's doing nothing. As you can see in the screenshot
![image](https://user-images.githubusercontent.com/9034096/79725342-5ef00300-82e9-11ea-8d5b-77c85898a76f.png)

**Comment by KittenCodes** [comment]
> The modal element don't overlap the section under it

@runechronos Please open a support ticket so that we can take a look at this: https://oxygenbuilder.com/support.
