### ISSUE TITLE
Pro-Menu not showing any menus to choose from

### ISSUE THREAD

**Issue by ocularrhythm** [soflyy/oxygen-bugs-and-features#897]
When adding a pro-menu to my template, it will generate a menu based on the first menu registered in WordPress. The dropdown to select a different menu is blank, even though I have at least 4 different registered menus within WordPress and are using them with the other menu components within Oxygen.

![Default option after adding component](https://user-images.githubusercontent.com/2738518/76640346-26a91800-6526-11ea-9b3c-5f91bb8534a9.jpg)
![Dropdown options for menu](https://user-images.githubusercontent.com/2738518/76640348-2741ae80-6526-11ea-87de-4ad8d65f6eb8.jpg)

The expected behavior is obviously just to be able to select a different menu.

I am running
-  WordPress 5.3.2
- Oxygen 3.2

I have not attempted to replicate in an isolated environment and the only other thing to note is that I did upgrade from 3.1 via FTP and not through the WP updater (not sure that matters but letting you know anyway). I will try and reproduce in another installation and report back here.

**Comment by KittenCodes** [comment]
@ocularrhythm Please send login details for your site to support@oxygenbuilder.com so that we can take a look at this for you.

**Comment by ocularrhythm** [comment]
Unfortunately I can't because I'm still developing locally. Once I get some spare time I will dig into this issue more and see if I can't find a solution for you/me.
