### ISSUE TITLE
Smooth scroll to hash links not working

### ISSUE THREAD

**Issue by theskywasgreen** [soflyy/oxygen-bugs-and-features#904]
Enabled smooth scroll to hash links but it isn't working. My hash links are in Gutenberg for my blog posts to create table of contents. 

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
No

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
*If yes, provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*

**To Reproduce**
1. Create hash links in post editor with Gutenberg
2. Enable Smooth scroll to hash links in Oxygen builder
3. Save
4. Test hash links on a post
5. No smooth scroll just jumps to hash link

**Expected behavior**
Smooth scroll on hash links

**What actually happens**
Just jumps directly to the hash link

**Desktop (please complete the following information):**
macOS 
Google Chrome
3.2
**Smartphone (please complete the following information):**
Xiaomi Mi Mix 3
Brave and Chrome
3.2

**Comment by KittenCodes** [comment]
@theskywasgreen Please create an example of this on our Sandbox site: https://oxygenbuilder.com/try/. Please then add a link so that I can see the problem.
