### ISSUE TITLE
parentComponent.hasClass is not a function

### ISSUE THREAD

**Issue by DaveSweeton** [soflyy/oxygen-bugs-and-features#907]
I'm opening an existing page in the oxygenbuilder to edit it.

Builder fails to load with a scripting error:

```
angular.js?ver=1.4.2:11500 TypeError: parentComponent.hasClass is not a function
    at buildOxygenTreeChild (controller.main.min.js?ver=3.2:1)
    at controller.main.min.js?ver=3.2:1
    at Object.forEach (angular.js?ver=1.4.2:322)
    at Scope.$scope.buildComponentsFromTree (controller.main.min.js?ver=3.2:1)
    at buildOxygenTreeChild (controller.main.min.js?ver=3.2:1)
    at controller.main.min.js?ver=3.2:1
    at Object.forEach (angular.js?ver=1.4.2:322)
    at Scope.$scope.buildComponentsFromTree (controller.main.min.js?ver=3.2:1)
    at buildOxygenTreeChild (controller.main.min.js?ver=3.2:1)
    at controller.main.min.js?ver=3.2:1
```

I'm using OxygenBuilder 3.2, WordPress 5.3.2.

**Comment by KittenCodes** [comment]
@DaveSweeton Please open a support ticket at https://oxygenbuilder.com/support so that we can take a look at this for you.

**Comment by DaveSweeton** [comment]
This was apparently due to a duplicate ID on one of the elements.

**Comment by KittenCodes** [comment]
Thanks for letting us know, @DaveSweeton

**Comment by aQziany** [comment]
@DaveSweeton - I have this problem now. How did you resolved this?

**Comment by DaveSweeton** [comment]
As I recall, the issue was two elements with the same IDs, so I found the duplicates and changed one of them so they were unique.

**Comment by aQziany** [comment]
@DaveSweeton - but where did you found them? As you can see in my screenshot above, I can't access the elements.

**Comment by DaveSweeton** [comment]
Hmm, it's been long enough I don't recall. If the builder works at all maybe I selected elements until I found it? I may have viewed the HTML source to see what the duplicates were. Sorry I can't be of more help!

**Comment by KittenCodes** [comment]
@aQziany Please open a support ticket so that we can take a look at this for you: https://oxygenbuilder.com/support.
