### ISSUE TITLE
Insert Dynamic Data button for Gallery Component

### ISSUE THREAD

**Issue by andreasritter** [soflyy/oxygen-bugs-and-features#908]
**Describe the feature you'd like to see included in Oxygen.**
Currently the "Gallery" component accepts images manually selected from the Media Library, WooCommerce and manually typing in the name of an ACF custom Field name. There should be a button for the Insert Dynamic Data dialog to visually select a custom data/ACF field. It should then also be possible to select a Repeater field. Currently it is impossible to use the Gallery inside a Repeater Component with a nested ACF Gallery field.

**What are the use cases for this feature?**
First of all this should be standard for the Gallery Component, because many other components support inserting dynamic data using the Insert Dynamic Data dialog. Manually having to type out the ACF field name makes the Gallery seem dated. Furthermore currently because of this rather primitive way to use an ACF field it is not possible to have a Gallery fed by a ACF sub-field in the repeater component to have a Gallery there. 
This is less a feature request but a request to bring the Gallery component up to par with e.g. the Image component.

**Examples of this feature or functionality.**
-

**Comment by KittenCodes** [comment]
See: #942

**Comment by reyadalfaituri** [comment]
Gallery > Dynamic Data option still does not work with MetaBox integration (the new deep integration v3.9 or above). 
Gallery > Dynamic Data option can work only with MetaBox Advanced Image filed under "blog" indexed page (like posts) not on pages like the home page.
Gallery > Dynamic Data option does not work with any MetaBox Image fields that are created using the Meta Box Setting pages.
------ Side Note: Image element (Dynamic Data feature) also sometimes does not work with some Meta Box image fields.
There are so many use cases for this feature alone! I hope this issue will be fixed soon ...
