### ISSUE TITLE
[2.2 RC2] Editor won't load with SVG Support's Force Inline SVG Enabled

### ISSUE THREAD

**Issue by NichCitarella** [soflyy/oxygen-bugs-and-features#91]
**Describe the bug**
Editor hangs on the spinning gear and never actual loads. 

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
Yes

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
http://fine-weasel.w6.wpsandbox.pro?upass=eYg1T5rGv6P5

**To Reproduce**
1. Install the "SVG Support" by Benbodhi and Activate.
2. Go into the SVG Support Settings
3. Next to "Enable Advanced Mode?" check "Yes"
4. Save the changes and waiting for the page to reload to enable another setting.
5. Next to "Force Inline SVG?" check "Yes"
6. Save the changes again
7. Go to any page and try to open the Oxygen Editor

**Expected behavior**
The editor should load.

**What actually happens**
Editor doesn't load.

**Comment by KittenCodes** [comment]
Hey @likeomgitznich,

I haven't been able to replicate this in Oxygen 2.2.1 or Oxygen 2.3. Are you still having problems with the SVG Support plugin?

There's a debug site here with Oxygen 2.3 and SVG Support installed: http://black-eland.w6.wpsandbox.pro?upass=2mLrW7yrV77Q if you'd like to take a look.
