### ISSUE TITLE
Part of Template being deleted/lost

### ISSUE THREAD

**Issue by Graham-P-Dunn** [soflyy/oxygen-bugs-and-features#910]
I am fairly new to WordPress/Oxygen but have managed to grasp the basics of the overall system but have run into the same problem four times now.

Having created a new installation of WordPress, installed the Oxygen and Oxygen Gutenburg plugins together with UpdraftPlus all works fine. 

I have created a template with header and footer taken from the library and then modified by myself.

Having then created several pages successfully I have found at a random point part or all of the template gets deleted/lost when editing a page.

It has happened 4 times now which is starting to get problematic as the site is due to go live soon.

I have even tried creating a fresh site twice but again when editing a page, the template gets corrupted or deleted at random points. The template is still in the admin area but has lost all or part of its content.

From what I can see it always happens when deleting a section, div etc from the structure panel.

What an I doing wrong or is this a bug in Oxygen.

Any help would be most appreciated.

Best Regards

Graham Dunn
iNET Solutions UK Ltd
Bradford, UK

**Comment by KittenCodes** [comment]
@Graham-P-Dunn Please send your site details and a link to the problematic template to us so that we can investigate this issue: https://oxygenbuilder.com/support.

**Comment by Graham-P-Dunn** [comment]
Hi, thanks for the quick reply :)

The site can be found at

     http://takealookat-co-uk.stackstaging.com/

The template is the only one on the site at present and can be found at

     http://takealookat-co-uk.stackstaging.com/?ct_template=main&ct_builder=true

Many Thanks

Graham Dunn
iNET Solutions UK Ltd
Bradford, UK

**Comment by Graham-P-Dunn** [comment]
Hi, Sorry forgot the username and pssword

Username : gpd@inetsolutionsuk.com

Password : FFinet2020!

**Comment by KittenCodes** [comment]
Thanks @Graham-P-Dunn. I've deleted the above details from this thread so that your details aren't accessible to the public.

**Comment by chris-castillo-dev** [comment]
I've encountered this problem and found out a condition under  which the problem occurs 100% of the time. When you edit the template, look at the very first item in the Structure panel. If the very first item says "Inner Content" instead of (I think) "Body", then when you save the template the template will become corrupt. The first element must not say "Inner Content" and the template will save successfully every time. If the template gets corrupted, I've had to restore from an earlier revision.

**Comment by Graham-P-Dunn** [comment]
Hi Chris
Thanks for your input on this problem. I've checked the template and the first item in the Structure Panel is 'Body'. The template has been created successfully and saved with the site working fine on several pages. I think the template is getting corrupted when editing pages and deleting multiple sections/div’s etc. from the Structure Panel. It’s happened 4 times now but at random times. Most of the time everything works just fine.
