### ISSUE TITLE
Can't publish or see any changes when I am not logged in or incognito mode

### ISSUE THREAD

**Issue by ayapallsafe** [soflyy/oxygen-bugs-and-features#912]
I have been working on migrating my site to http://dev1.allsafeit.com/

However, I notice when I log in you will be able to see all of the changes

![image](https://user-images.githubusercontent.com/62393043/77226287-1c37ef80-6bb2-11ea-986b-7fdd735489b8.png)

but under incognito I would nee hello world post

![image](https://user-images.githubusercontent.com/62393043/77226310-4b4e6100-6bb2-11ea-978e-a76694654724.png)

and a sample page which I do not understand why how can I post my page?

When I click on sample page it goes here

![image](https://user-images.githubusercontent.com/62393043/77226357-ada76180-6bb2-11ea-99a4-650b6e37ae6e.png)

**Comment by KittenCodes** [comment]
@ayapallsafe I suspect this is caused by caching. If you are using any caching plugins, please clear the caches.

If this doesn't help, please open a support ticket so that we can take a look at this for you: https://oxygenbuilder.com/support.
