### ISSUE TITLE
CSS Class not styling element when creating class, remains style of ID

### ISSUE THREAD

**Issue by mupersan** [soflyy/oxygen-bugs-and-features#913]
**Describe the bug**
When styling elements in oxygen builder, we create a class and start to style the class. The style will not apply to the same class used on other elements, instead they just retain the styling of the ID. Why?

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
Yes

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
No

**To Reproduce**

**Expected behavior**
When creating a new class on an element, that class should style other elements it is applied to on the page. 

**What actually happens**
No styling applies. 

**Screenshots**
*If applicable, add screenshots to help explain your problem.*

**Desktop (please complete the following information):**
- OS: Windows & MaxOS
 - Chrome & Brave
 - Latest Updated Version

**Smartphone (please complete the following information):**
 - Oxygen Version [e.g. 2.2 Alpha]

**Additional context**
*Add any other context about the problem here.*

**Comment by Spellhammer** [comment]
This is how CSS works and is not a bug.

ID styles trump class styles.

If you assign a width of 50px on the ID, and then add a class that has a width of 100px, the element will be 50px wide: https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity

**Comment by Yusgeek** [comment]
I am experiencing same thing.
Normally when I assign a class to elements I can style them and any element having same class will equally inherit the styles for that class, but later i just couldn't do that anymore. Nonetheless if I use code block and style the class using css, it works just fine, but thats not what I want. I want to be able to style directly without having to write codes all over.
Any help?

**Comment by M-Marbouh** [comment]
That's not a bug, it is related to the specificity calculation as Spellhammer said.
Just copy the styles from the #ID selector using the "copy styles to another selector" icon to the class you created for all elements, then delete the styles of the #ID. 
This way you will be able to see the style applied to all the elements sharing the same class.

**Comment by RANSIDRAT** [comment]
This issue is happening on my installation and has nothing to do with specificity - you can add a section with ZERO styles on the ID, create a class on the section and give it a background color of red, nothing happens, check the ID that there is no pre existing background color and add a background color to the ID of RED and suddenly it appears, remove the ID styling and the color dissappears again.
Deactivated ALL plugins and classes still do not work

**Comment by Kpudlo** [comment]
Hi @RANSIDRAT, 

If you're still having issues with this, please open a Support Ticket (https://oxygenbuilder.com/support) so we may investigate further.
