### ISSUE TITLE
DONE: UI/usability suggestions

### ISSUE THREAD

**Issue by alexanderkladov** [soflyy/oxygen-bugs-and-features#914]
I was wondering if anyone paid attention to any of the [enhancement suggestions submitted by the user **@afromal**](https://github.com/soflyy/oxygen-bugs-and-features/issues/created_by/aformal)? Every single one of his suggestions is great. Some are absolute killer features (like #683 with ability to quick edit, #608, #610, #647, #648, #681, #684). Most of them won't even be that hard to implement. And Oxygen community has loved & supported most of them with votes, clearly showing the need for them. Yet the discussion seems to be completely dead. Why aren't we seeing more buzz around these issues? Are any of them being worked on (or at least considered for near future)?

We need all that great stuff to speed up the workflow!

**Describe the feature you'd like to see included in Oxygen.**
All of the features proposed by @aformal

We also **desperately** need (in order of importance):
1. **ability to copy/paste styles from one ID/class/element/specific Advanced section to another**. It's so important, I can't believe it's still not implemented to this day, even though I can see it was heavily requested more than a year ago #36.
1. **ability to quickly reset styles for an ID/class/element/specific Advanced section** (i.e. Layout, Typography etc). This is also a core feature that should be available with a single click/shortcut (*perhaps via a right click menu?*). Has been requested more than a year ago too #119.
Right now I basically have to go to Settings > Selectors & remove the class entirely to reset it properly, since some properties won't reset even after you change them back (i.e. after some properties are modified once, the pesky blue circle stays next to the setting no matter what with no way to reset it #63).
1. **proper undo functionality**. 1 undo is not enough. 1 undo has so little use right now that it might as well not be there at all. Also requested more than a year ago #12.

**What are the use cases for this feature?**
Massive UI, usability & workflow improvements.

Lack of these features makes working with current UI extremely frustrating at times. I really hope we'll see progress on all of these soon.. I love Oxygen & what it's capable of and really would like to see it succeed! 😃

**Examples of this feature or functionality.**
[Check out every issue here](https://github.com/soflyy/oxygen-bugs-and-features/issues/created_by/aformal), most come with awesome animated demos, thanks to @aformal

**Comment by KittenCodes** [comment]
1, 2 and 3 have been implemented.

**Comment by Spellhammer** [comment]
These suggestions have mostly been implemented. Further requests to enhance the UI/usability of Oxygen should be posted as new feature requests.
