### ISSUE TITLE
Lightbox blocks interaction after closing

### ISSUE THREAD

**Issue by alextester1990** [soflyy/oxygen-bugs-and-features#918]
**Lightbox container remains after closing**
*After opening lightbox on a gallery element, the div class="pswp pswp--supports-fs pswp--open pswp--animate_opacity pswp--notouch pswp--css_animation pswp--svg pswp--visible pswp--zoom-allowed" remains, overlaying the whole page and making it impossible to click on anything.*

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
*Yes/No*

Wasn't able to reproduce on sandbox as I hit another bug on the way to reproducing.. Trying to create a gallery from media gallery isn't working. You select the media files and press insert but they don't appear there. https://oxygen-qzlwdkm6g6q8k.oxygen-demo.qsandbox.me/about/?ct_builder=true&ct_inner=true

**To Reproduce The Lightbox Issue**
1. Go to page builder
2. Create a gallery, enable lightbox
3. Save and open page in frontend
4. Click on image to open lightbox, then close the lightbox
5. Try to click on any other element. Inspect and you'll see the lightbox div overlaying the whole page.

**Expected behavior**
*All aspects of lightbox should be gone after clicking away.*

**What actually happens**
*Lightbox overlay remains.*

**Screenshots**
*If applicable, add screenshots to help explain your problem.*

**Desktop (please complete the following information):**
- OS: Windows
 - Browser Chrome
 - Oxygen Version 3.1

**Smartphone (please complete the following information):**
 - Oxygen Version [e.g. 2.2 Alpha]

**Additional context**
*Add any other context about the problem here.*

**Comment by KittenCodes** [comment]
@alextester1990 Please open a support ticket so that we can take a look at this for you: https://oxygenbuilder.com/support.
