### ISSUE TITLE
[2.2] Installing Marketing Agency template hangs

### ISSUE THREAD

**Issue by petebytes** [soflyy/oxygen-bugs-and-features#92]
**Describe the bug**
*Installing marketing agency template hangs, same system installing oxygen default template works fine.*

![image](https://user-images.githubusercontent.com/676739/53220502-14f68900-3622-11e9-85e5-a074d1a7b96f.png)

**Comment by petebytes** [comment]
Found a few others that hang - conference, flightschool
freelance, onepage2 and financial work

If you need access to the environment just let know

**Comment by Spellhammer** [comment]
This is a compatibility issue with PHP 7.2+ and will be corrected in a future update. For now, roll back to PHP 7.1 to import the new design sets.
