### ISSUE TITLE
Events Calendar template is not working

### ISSUE THREAD

**Issue by dichkovsky** [soflyy/oxygen-bugs-and-features#922]
**Description**
*Trying to setup a template to display Events Calendar archive page with calendar. Using atomic design set. Following instructions from [an article from your site](https://oxygenbuilder.com/tutorial/how-to-setup-the-events-calendar-with-oxygen/), and see that Events Calendar code is displayed in oxygen page builder. But when I'm visiting [a page](http://articles.beorganic.by/events/) where calendar should be displayed, I see that default archive template is used and no calendar is shown*

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
*Yes*

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
*Yes*
*https://oxygen-q7af975yywr8k.oxygen-demo.qsandbox.me/events/*

**To Reproduce**
[See article from oxygen builder site](https://oxygenbuilder.com/tutorial/how-to-setup-the-events-calendar-with-oxygen/)

**Expected behavior**
*Events Calendar archive template is used by the system, to display calendar*

**What actually happens**
*Default archive template is used*

**Screenshots**
*[see page](https://oxygen-q7af975yywr8k.oxygen-demo.qsandbox.me/events/)*

**Desktop (please complete the following information):**
- OS: Windows 10
 - Browser: chrome
 - Oxygen Version 3.2

**Smartphone (please complete the following information):**
- Device: Samsung Note 8
 - OS: Android 9
 - Browser chrome
 - Oxygen Version 3.2

**Additional context**
*-*

**Comment by KittenCodes** [comment]
@dichkovsky You needed to:

a) Add an event
b) Set the Events Template to the "Default Events Template" here: https://oxygen-q7af975yywr8k.oxygen-demo.qsandbox.me/wp-admin/edit.php?post_type=tribe_events&page=tribe-common&tab=display.

The Events page is now working.
