### ISSUE TITLE
Footer section displays in sidebar on desktop

### ISSUE THREAD

**Issue by steve-goldberg** [soflyy/oxygen-bugs-and-features#927]
**Describe the bug**

A footer section which includes a code block in the Main (catch-all) template is showing up in the sidebar on the Posts template.

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
Yes

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
*If yes, provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*

**To Reproduce**

1. Go to any post from the dropdown Guides.
2. Scroll down until you see the last ad block with a banner image.
3. You'll notice the footer section in the sidebar.

**Expected behavior**
I expect the footer section to be in the footer like it shows up in the Oxygen editor.

**What actually happens**
The entire footer section shows up in the sidebar. In the editor in shows up as a section in the footer of the site with the inner content element above it.

**Screenshots**
https://share.getcloudapp.com/12u18oKQ

**Desktop (please complete the following information):**
- OS: Apple Mojave
 - Browser Chrome and Firefox
 - Oxygen Version 3.2 Latest production build

**Smartphone (please complete the following information):**
N/A

**Additional context**
https://oxygen-q7vhpx2w9gs8k.oxygen-demo.qsandbox.me/

**Comment by KittenCodes** [comment]
@steve-goldberg Please open a support ticket with login details for the Sandbox site so that we can take a look at this for you. You can open a support ticket here: https://oxygenbuilder.com/support.

**Comment by steve-goldberg** [comment]
Here is the login details. No need for a new support ticket.

https://oxygen-q7vhpx2w9gs8k.oxygen-demo.qsandbox.me/wp-admin/
adminuser
425vKHMOXUz^tVLgRMtsmocY

Steve

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by KittenCodes** [comment]
@steve-goldberg The issue is caused by the LuckyWP Table of Contents plugin. You will need to reach out to the plugin developer to let them know the problem it is causing and for help with the issue.
