### ISSUE TITLE
Maintenance Mode

### ISSUE THREAD

**Issue by raykai** [soflyy/oxygen-bugs-and-features#937]
**Describe the feature you'd like to see included in Oxygen.**
Maintenance Mode

**What are the use cases for this feature?**
Accessibility

**Examples of this feature or functionality.**
https://oxypowerpack.com/maintenance-mode/ I don't know if this site is a scam...
"Coming Soon" and "Maintenance" pages with Oxygen Builder and activate them on a per role basis.
It would be nice to have this kind of feature in Oxygen. Seeing as everyone is building websites with Oxygen Builder needs to have a "Coming Soon" and "Maintenance" page

**Comment by KittenCodes** [comment]
https://www.youtube.com/watch?v=SvQh9BgGdhc
