### ISSUE TITLE
Error Saving in Template

### ISSUE THREAD

**Issue by ejeaglesct** [soflyy/oxygen-bugs-and-features#940]
**Describe the bug**
I've installed Oxygen on one of my websites, https://www.vtmasonicdistrict7.org/, with no other plugins, completely updated and when I click save within the editor inside Templates it says "Error occurred while saving". 

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
Yes

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
No

**To Reproduce**
1. Go to Templates > Edit > Edit in Oxygen
2. Click on 'Save'
3. See error

**Expected behavior**
Save the template.

**What actually happens**
Get afore mentioned error.

**Screenshots**
![Screen Shot 2020-04-02 at 10 07 12 AM](https://user-images.githubusercontent.com/16878439/78258807-bf013f80-74c9-11ea-9867-5148b5acf698.png)

**Desktop (please complete the following information):**
- OS: MacOs Catalina 10.15.4
 - Browser Chrome
 - Oxygen Version 3.2.1 RC 1

**Smartphone (please complete the following information):**
N/A

**Additional context**
None

**Comment by KittenCodes** [comment]
@ejeaglesct Please make sure the addresses set via Settings > General in the WordPress admin area match the address you're using to access the site. For example, if you're accessing the site via HTTPS then the site addresses must also use HTTPS and not HTTP.

If this doesn't help, please open a support ticket: https://oxygenbuilder.com/support.

**Comment by kadarpik** [comment]
we have just added multidomain plugin and this error occurred, the main site has changed to different domain, opening oxygenbuilder from main wordpress sites solves the error.
