### ISSUE TITLE
Gutenberg blocks background can't be changed

### ISSUE THREAD

**Issue by jeppewhoej** [soflyy/oxygen-bugs-and-features#941]
**Describe the bug**
*When making Gutenberg blocks with a background image the background image can't be changed. It can be changed in the backend but it doesn't show in the frontend*

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
*Yes*

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
*If yes, provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*

**To Reproduce**
1. Make gutenberg block with a background image
2. Go to page and insert the block made in oxygen
3. Try changing the background image in the block
4. Click update and go to frontend and see the image

**Expected behavior**
*The new image should show in the frontend*

**What actually happens**
*The new image don't show in the frontend*

**Smartphone (please complete the following information):**
- Device: [Macbook 15"]
 - OS: [iOS10.15.03]
 - Browser [Chrome]
 - Oxygen Version [Version 3.2.1]

**Comment by KittenCodes** [comment]
@jeppewhoej 

It's only possible to change Section background images in Gutenberg: https://oxygenbuilder.com/documentation/gutenberg-client-mode/.

If you would like to see the option to change background images on other elements, please open a feature request.

**Comment by jeppewhoej** [comment]
Hi @KittenCodes ,
I can't change Section background images either when the page is converted to gutenberg.

Why is that?

**Comment by KittenCodes** [comment]
@jeppewhoej Please open a support ticket so that we can take a look at this for you: https://oxygenbuilder.com/support.

**Comment by jeppewhoej** [comment]
Hi @KittenCodes,
Thanks for your reply, I noticed that I had an older version of the gutenberg plugin.
