### ISSUE TITLE
Gallery won't display after using flex layout and switching back to default layout

### ISSUE THREAD

**Issue by claytonschase** [soflyy/oxygen-bugs-and-features#943]
**Describe the bug**
*Gallery component doesn't show in the editor and on the front-end after selecting flex and then reverting back to the default layout*

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
*Yes*

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
*Yes, https://oxygen-qjdhj7k7q9t8k.oxygen-demo.qsandbox.me/?ct_builder=true&amp%3Bct_inner=true*

**To Reproduce**
1. Insert gallery
2. Click layout and click flex
3. Click flex again to turn off

**Expected behavior**
*I would expect the gallery to return to the default layout and not disappear entirely until flex or masonry is selected*

**What actually happens**
*The gallery disappears in the editor and on the front-end*

**Screenshots**
*https://imgur.com/a/JGGzMiW*

**Desktop (please complete the following information):**
- OS: Mac
 - Chrome
 - Oxygen Version 3.2

**Comment by KittenCodes** [comment]
@claytonschase 

> Gallery component doesn't show in the editor and on the front-end after selecting flex and then reverting back to the default layout

When you click on "flex", you're actually removing any layout options - there's no longer anything selected.

When you first create the Gallery, you will see there is a small border around the "flex" item, showing it is selected. That is no longer present when you click "flex", so there is no layout type selected.

**Comment by claytonschase** [comment]
How do I restore back to the original layout then? Like when I first add the gallery component?

**Comment by KittenCodes** [comment]
@claytonschase click "flex". Flex is the default layout.
