### ISSUE TITLE
DONE: Clear all the applied styles

### ISSUE THREAD

**Issue by gagankhatri** [soflyy/oxygen-bugs-and-features#945]
**Describe the feature you'd like to see included in Oxygen.**
Would like to request a feature to clear all the applied styles with one click like we got for Pro Menu.

**What are the use cases for this feature?**
This will save significant time  when going and clearing each properties applied to the element.

**Examples of this feature or functionality.**
I can compare this with Pro Menu Clear Current style

**Comment by alanzirpoli** [comment]
+1

**Comment by Spellhammer** [comment]
Implemented in 3.5 alpha 1.
