### ISSUE TITLE
Border Settings Not Retained

### ISSUE THREAD

**Issue by greenyboy** [soflyy/oxygen-bugs-and-features#95]
I'm using Oxygen Builder 2.2. When setting a border value on any element within Oxygen - colour, px value and type (Solid, Dashed etc), the values take effect on the element. If I click away from the element and then go back to these border properties, the values I previously set are not there. The border is still present on the element but the values are not. 

**Describe the bug**
*A clear and concise description of what the bug is.*

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
*Yes

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
*If yes, provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*
http://smoggy-flamingo.w5.wpsandbox.pro/wp-admin/post.php?post=8&action=edit

**To Reproduce**
1. Go to 'Templates and Edit the eader Template'
2. Click on the Text Element and go to the border settings
3. You will see there is no values for the border even though there is a border around the element

**Expected behavior**
*A clear and concise description of what you expected to happen.*
I would expect the border values to be there

**What actually happens**
The Values show as if there has been nothing set

**Screenshots**
*If applicable, add screenshots to help explain your problem.*

**Desktop (please complete the following information):**
- OS: [e.g. ]  Windows 10
 - Browser [e.g. chrome, safari] Chrome
 - Oxygen Version [e.g. 2.2 Alpha] 2.2

**Smartphone (please complete the following information):**
- Device: [e.g. iPhone6] Samsung Galaxy S8
 - OS: [e.g. iOS8.1] Android 8
 - Browser [e.g. stock browser, safari]  Chrome
 - Oxygen Version [e.g. 2.2 Alpha]

**Additional context**
*Add any other context about the problem here.*

**Comment by adrien-robert** [comment]
+1

**Comment by Martin-1** [comment]
+1 as well

**Comment by alpabuz** [comment]
+1

**Comment by fmommeja** [comment]
+1

**Comment by laboiteare** [comment]
+1 Same problem in 3.0

**Comment by KittenCodes** [comment]
This is the intended behaviour. Please see the video on the Borders element here: https://oxygenbuilder.com/documentation/styling-options/borders/.

If you would like to see different behaviour, please open a feature request: https://github.com/soflyy/oxygen-bugs-and-features.
