### ISSUE TITLE
Section > padding 0px not working

### ISSUE THREAD

**Issue by guillaumelorain** [soflyy/oxygen-bugs-and-features#951]
Hello.

I use 3.3 Alpha 1

My goal is to have a section with padding-top = 0 via a class.

1. I created a section. 
2. The default top padding is 75px but I want 0px. 
3. I add a class to this section with the padding-top = 0px
4. The change is visible in the oxygen admin
5. This change is not working on live website. The class is empty in the CSS, 

I noticed if I set padding-top=1px it's working. 
So the behaviour is if I set 0px it's like if I have an empty field. But the empty field means the default setting of the section so 75px and I want 0px via a class. 

Thanks

**Comment by KittenCodes** [comment]
#720
