### ISSUE TITLE
3.3 alpha, the new toggle button not rendered. 

### ISSUE THREAD

**Issue by pogeunpark** [soflyy/oxygen-bugs-and-features#952]
**Describe the bug**
*A clear and concise description of what the bug is.*
the new property pane toggle button is not rendered at all. just texts showed up like this
<img width="292" alt="Screen Shot 2020-04-02 at 11 36 18 AM" src="https://user-images.githubusercontent.com/43868794/78342936-0d4f3500-75d5-11ea-932f-33eda51d54f4.png">

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
*Yes/No*

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
*If yes, provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*

**To Reproduce**

**Expected behavior**
*A clear and concise description of what you expected to happen.*

**What actually happens**
*A clear and concise description of what happens instead of the expected behavior.*

**Screenshots**
*If applicable, add screenshots to help explain your problem.*

**Desktop (please complete the following information):**
- OS: [e.g. iOS] Mac Catalina 
 - Browser [e.g. chrome, safari] Chorome, the latest. 
 - Oxygen Version [e.g. 2.2 Alpha] 3.3 Alpha

**Smartphone (please complete the following information):**
 - Oxygen Version [e.g. 2.2 Alpha]

**Additional context**
*Add any other context about the problem here.*

**Comment by Spellhammer** [comment]
This is likely caused by some caching in your environment. Please try hard clearing your browser cache. If that doesn't work, please send us a ticket via https://oxygenbuilder.com/support so that we can investigate in your environment.

**Comment by pogeunpark** [comment]
You were right. I never thought it was caching related because it is in a staging environment without caching. Sorry about that. you can close this!

**Comment by Spellhammer** [comment]
Thank you for the update!
