### ISSUE TITLE
Keeps me logging out?

### ISSUE THREAD

**Issue by zaheen** [soflyy/oxygen-bugs-and-features#956]
**Describe the bug**
*I have tried use a second pro menu in the footer.*

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
*Yes/No*

Here is what happens every time when I try to save, and the I will be logged out when I refresh.

https://imgur.com/MkDB0RR

**Comment by KittenCodes** [comment]
@zaheen Please open a support ticket so that we can take a look at this for you: https://oxygenbuilder.com/support.
