### ISSUE TITLE
Short Code Conflict?

### ISSUE THREAD

**Issue by jim954** [soflyy/oxygen-bugs-and-features#958]
Trying to figure out the hang up with using a short code from a plugin with Oxygen.

I reviewed the documentation and faq but there is nothing other then how to use the shortcode tool to insert the code.

I went throught the Oxy truble shooter and made any changes I could.

I have no clue why the hang up if you could help.

A Simple page created with Oxygen has good load speed 
Google Score 86: https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fihomefind.stainyourdoor.com%2Fhome
Gt time 2.6s: https://gtmetrix.com/reports/ihomefind.stainyourdoor.com/4BMkSYGp
A simple page created with Oxy and has a short code has slow speed.
Google score 43: https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fihomefind.stainyourdoor.com%2Fmls-search%2F
GT time 8.2sec: https://gtmetrix.com/reports/ihomefind.stainyourdoor.com/KAMKEtaQ
The same short code used with only the Astra theme has great speed.
Google Score 98: https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fstainyourdoor.com%2Frover-basic-search%2F
GT time 1.6s : https://gtmetrix.com/reports/stainyourdoor.com/BQj7jgLj

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
YES

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
*If yes, provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*

**Comment by KittenCodes** [comment]
@jim954 Please set up an example of this on our Sandbox site and send us the URL to a normal page and a page with the shortcode so that we can take a look. You can create a Sandbox site here: https://oxygenbuilder.com/try/.
