### ISSUE TITLE
[2.2] Border settings persist, but do not show when editing

### ISSUE THREAD

**Issue by petebytes** [soflyy/oxygen-bugs-and-features#96]
When you make changes to an Image border, the settings are persisted and works fine.
When you open up the editor to change the border settings, the settings are not listed.

For example in the attached image I changed All border colors, width, style and radius.  The only setting that shows is Border radius.

![image](https://user-images.githubusercontent.com/676739/53267389-75c4a680-36a0-11e9-8a6d-ee5cf6d0c88c.png)

**Comment by KittenCodes** [comment]
Duplicate: #95

**Comment by adrien-robert** [comment]
+1
