### ISSUE TITLE
Link directly to posts

### ISSUE THREAD

**Issue by Xilonz** [soflyy/oxygen-bugs-and-features#962]
**Describe the feature you'd like to see included in Oxygen.**
When adding a link it would be nice to be able to link it to a post/page instead of manually searching for the url.

**What are the use cases for this feature?**
E.g. footers with a privacy policy link

**Examples of this feature or functionality.**
WordPress

**Comment by KittenCodes** [comment]
You can do this using the "set" button: https://www.loom.com/share/ab0bbd58430745ff9eb04e8b9910130d.

**Comment by Xilonz** [comment]
I ment inline links, in, for example, the text component.

**Comment by Kpudlo** [comment]
Closing as a duplicate of https://github.com/soflyy/oxygen-bugs-and-features/issues/2498
