### ISSUE TITLE
Using Contact form 7 in Oxygen

### ISSUE THREAD

**Issue by SwedBoy** [soflyy/oxygen-bugs-and-features#966]
In mobile phone the fields strech out beside the phones frame, I can not see the beging or the end of the text field

How do i fix that? - I think its a bug

Using wordpress shortcode to set it in in one of the oxygen design sets (atomic)

phone samsung note 9
**Describe the bug**
*A clear and concise description of what the bug is.*

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
*Yes/No*

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
*If yes, provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*

**To Reproduce**

**Expected behavior**
*A clear and concise description of what you expected to happen.*

**What actually happens**
*A clear and concise description of what happens instead of the expected behavior.*

**Screenshots**
*If applicable, add screenshots to help explain your problem.*

**Desktop (please complete the following information):**
 - Oxygen Version [e.g. 2.2 Alpha]

**Smartphone (please complete the following information):**
 - Oxygen Version [e.g. 2.2 Alpha]

**Additional context**
*Add any other context about the problem here.*

**Comment by KittenCodes** [comment]
@SwedBoy Please try setting the max-width of the shortcode element to 100% via Advanced > Size & Spacing.

If that doesn't help, please open a support ticket: https://oxygenbuilder.com/support.

**Comment by SwedBoy** [comment]
![Screenshot_20200405-182841_Chrome](https://user-images.githubusercontent.com/46443581/78504212-d65f5780-776b-11ea-9e05-e66868143133.jpg)

**Comment by SwedBoy** [comment]
![Screenshot_20200405-183838_Chrome](https://user-images.githubusercontent.com/46443581/78504366-ff341c80-776c-11ea-947c-663fba90d66b.jpg)
![20200405_183852](https://user-images.githubusercontent.com/46443581/78504367-ffccb300-776c-11ea-9eac-cb3b9b8d3b07.jpg)
![20200405_183848](https://user-images.githubusercontent.com/46443581/78504371-03f8d080-776d-11ea-8c0c-d0c188922c4c.jpg)

**Comment by SwedBoy** [comment]
contact form 7

**Comment by SwedBoy** [comment]
https://oxygenbuilder.com/support.

I come to the same place - this palce

**Comment by KittenCodes** [comment]
@SwedBoy Please open a support ticket from the https://oxygenbuilder.com/support page.  Scroll down the page slightly to see the support form.
