### ISSUE TITLE
Using design sets from a multisite

### ISSUE THREAD

**Issue by stephen-clark** [soflyy/oxygen-bugs-and-features#967]
**Describe the bug**
*A clear and concise description of what the bug is.*

If you've built out your design sets on a multisite installation (which is useful if you need to make a lot of them), then the  'install as a full site' on a new site won't bring across the pages.
(library still works)

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
*Yes*

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
*If yes, provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*

No, it is not a multisite.

**To Reproduce**

1. Create wordpress multisite
2. Add oxygen
3. Oxygen > settings > make site a design set (any subsite, inc. main will do)
4. Create page, add a component to it. Save.
5. On Edit page, activate all the design set options.

6. Go to blank site with oxygen
7. Activate design sets and add the one you created above
8. Import the one-page website you made above

**Expected behavior**
The design set page should appear on the new site

**What actually happens**
The design set page doesn't appear on the new site
(the library is intact though.

**Screenshots**
*If applicable, add screenshots to help explain your problem.*

**Desktop (please complete the following information):**

Not an OS or browser related issue.
 - Oxygen Version 3.2

**Smartphone (please complete the following information):**
N/A

**Additional context**
I have to design multiple design sets, it is not practical to keep creating new WP installs with all the plugins etc.  

I build out design sites on the multisite, and then duplicate them to create the next one.

This way I only have one site to host, licence and keep updated.

*Add any other context about the problem here.*

It's a real pain as doing it on stand alone sites is a lot more work.

**Comment by Spellhammer** [comment]
This is probably not an Oxygen issue. I suspect it's a hosting problem, as our official design sets run on a multi-site and I've personally set up design library sites on multi-site environments with no problems.

Please contact us via https://oxygenbuilder.com/support and we can investigate what exactly is happening.
