### ISSUE TITLE
Search field in selector css setting

### ISSUE THREAD

**Issue by magiaslab** [soflyy/oxygen-bugs-and-features#97]
It would be very useful to insert a search field in the settings of the css selectors in order to quickly find the class to modify

**Comment by milojennings** [comment]
YES!! I agree this is a must-have feature. It seems pointless to create a bunch of selectors, then not be able to select them from a list without opening a completely different interface to figure out which selectors are available.

**Comment by arsh999cg** [comment]
It is available in Oxygen 4.0 alpha 1 now.
