### ISSUE TITLE
Add 'Open by Hover' to Toggles, Tabs etc..

### ISSUE THREAD

**Issue by nicocollu** [soflyy/oxygen-bugs-and-features#971]
**Describe the feature you'd like to see included in Oxygen.**
I want to build a MegaMenu with Oxygen and I think I'll be able to, with Toggles.
Thing is, I don't know how to fix it so it opens by hover as well as click and stays open as long as you explore the dropdown section?

I want to offer this as a possible feature but if anyone is reading this and know the answer, could you please share some code with me to try out?

It would make the plausibility of Mega Menus much easier!

**Comment by KittenCodes** [comment]
This isn't an enhancement. Please post this question in our Facebook group: https://www.facebook.com/groups/1626639680763454/.

You may also find this video useful: https://www.youtube.com/watch?v=r2QgPvhGkBk
