### ISSUE TITLE
Over 500 PHP Warnings (Errors) in component-init.php

### ISSUE THREAD

**Issue by chris-castillo-dev** [soflyy/oxygen-bugs-and-features#975]
I was running performance tests on a site I was building with Oxygen and found the load times were lagging significantly. After examining the waterfall chart, there was a server wait time of between 400ms - 900ms.

1. I disabled ALL plugins except Oxygen, and the server wait time remained high at 430 - 500ms.

2. I disabled Oxygen (now all plugins were disabled) and the server wait time went down to 137ms.

3. I enabled Oxygen and Query Monitor and loaded the site's frontend and noticed over 500 (555) PHP errors. Attaching screenshot here.

WordPress debug log also shows these errors (domain removed for privacy reasons):

[06-Apr-2020 21:12:16 UTC] PHP Deprecated:  implode(): Passing glue string after array is deprecated. Swap the parameters in /var/www/site.url/htdocs/wp-content/plugins/oxygen/component-framework/component-init.php on line 4828

[06-Apr-2020 21:12:16 UTC] PHP Deprecated:  join(): Passing glue string after array is deprecated. Swap the parameters in /var/www/site.url/htdocs/wp-content/plugins/oxygen/component-framework/components/component.class.php on line 2276

![oxygen-php-errors](https://user-images.githubusercontent.com/46719081/78608971-c7da7400-782f-11ea-886b-717329d0b099.png)

Also attaching the Site Health Info here...

[site-health.txt](https://github.com/soflyy/oxygen-bugs-and-features/files/4441003/site-health.txt)

**Comment by chris-castillo-dev** [comment]
To update this ticket, I downgraded my PHP version on this site from 7.4 down to 7.2 and all errors went away.

**Comment by alriksson** [comment]
@chris-castillo-dev 7.4 is a stable php version we should not be forced to downgrade.

Another ticket on PHP issues:
https://github.com/soflyy/oxygen-bugs-and-features/issues/883

**Comment by lupett** [comment]
The same for me, better on 7.2 but not so much.

**Comment by cvladan** [comment]
Temporary solution: https://github.com/soflyy/oxygen-bugs-and-features/issues/883#issuecomment-627662275

**Comment by KittenCodes** [comment]
> PHP Error "implode() and join() - Passing glue string after array is deprecated.

Fixed in v3.6 Beta.
