### ISSUE TITLE
DONE: Add Conditionals to All Elements

### ISSUE THREAD

**Issue by wplit** [soflyy/oxygen-bugs-and-features#98]
**Conditionals for Individual Elements**
I'm continuing [this conversation from the forum](https://oxygenbuilder.com/forums/topic/conditional-dynamic-data/) as I think it's a highly requested feature and didn't want it to get lost over time.

**What are the use cases for this feature?**
Conditionals are pretty fundamental in building WP sites. The main use cases I find when needing in Oxygen are;

- Hiding empty field values from templates
- Most dynamic data, such as featured images where the overall design / structure of the template can need to change slightly depending on if the post has a featured image. 
- Building user dashboards for membership sites where almost all the page's content is different, depending on who the user is, if they're logged in, are they a paying member etc.. Being able to show a login section for those not logged in, an up sell for free users and something else for paid users, etc.
- Different menu for types of visitors.

**Examples of this feature or functionality.**
I'm not familiar with other builders unfortunately, however I think for individual elements this can be implemented in quite a simple / generic way similar to this I found from a divi extension... where the user can just add the conditionals to display that element or not.

<img width=500 src="https://wplift.com/wp-content/uploads/2017/11/best-divi-add-ons-1.png">

<img width=300 src="https://i.ibb.co/pfjvPVp/conditionals.png">

Toolset seems to have a [more user friendly way of adding conditionals](https://toolset.com/documentation/user-guides/conditional-html-output-in-views/), but I think even just adding that simple field where we need to add our own php if statement would be a big step forward and solve a lot.

**Conditionals for Templates**

The other thing would be to add conditionals to the page settings for the whole template, not just to individual elements. For example, we may need to style some elements differently depending on certain conditions. A common way I do this in theming is to add a body class conditionally. 

Use case; You want the post title to have less padding and move up higher on the page if there is no featured image above it. We would need to style the template differently, using a body class, that is only added on posts with no featured image. Then we could go ahead and add `.no-featured-image .post-title {}` to target that condition alone.

For this feature we'd need to be able to create custom body classes depending on the conditions we set.

**Comment by michelsouzafigueiredo** [comment]
Very Very nice feature request, thx @wplit

**Comment by widevisions** [comment]
One of the most interesting tools I found that impelments this functionality, is WP Brain (CodeCanyon). WP Brain adds the possibility to create a custom library of conditions according to simple or very complex rules, using a simple GUI. You can then insert in your posts / pages any content wrapped into a custom shortcode that applies these conditions, and the content will be executed / displayed only if the condition is true. Unfortunately it is pretty akward to use the WP Brain shortcode to wrap another extremely long Oxygen shortcode (for example a reusable part). It would be GREAT to be able to apply the same logic to Oxygen elements natively.

**Comment by Infusednl** [comment]
I was just writing the same suggestion when I saw this post! One example for the menu is the plugin:

- https://nl.wordpress.org/plugins/conditional-menus/

However it doesn't work with Oxygen as it is looking for registered menu's in a theme template and doesn't recognize it when Oxygen's menu element is placed inside a template.

Besides the menu it would indeed be really useful to create custom adaptive websites.
This is one of the most important things for me that I would like to see integrated in Oxygen for every element.

**Comment by milkstudio** [comment]
+1 for this feature; it would be particularly useful for Advanced Custom Fields which are nicely integrated into Oxygen already, so empty fields could be hidden instead of displaying the white space the block takes up with no content.

**Comment by dmccan** [comment]
I'd like to use conditional logic with reusable template parts.  For example, if I give the post the category of "Product Review" then I'd like the conditional block to insert my affiliate statement.  Or if I have a select box in my book CPT and select the format "Audio Book" then output a section with the fields "Reader" and "Recording Length".

**Comment by timpixel** [comment]
Would not displaying a block mean that it's not included in the page at all? It's different than setting it to display: none? Even though that may be a workaround/solution in some casesI guess.

**Comment by srikat** [comment]
This is now present in 2.4 Alpha 1.

https://oxygenbuilder.com/documentation/other/conditions/

https://www.youtube.com/watch?v=N9HC_WsMmaY
