### ISSUE TITLE
Pro menu bug with 10 items in drop down mobile menu.

### ISSUE THREAD

**Issue by alriksson** [soflyy/oxygen-bugs-and-features#987]
**Describe the bug**
Once a drop-down element includes several items it overlaps the close icon due to pro menu push up to display the drop-down menu instead of pushing it down.

It also happens if you have multiple dropdowns open which add up to the total items opened. As it pushes up and not push down drop down items. Please consider changing the logic here and all these issues would be solved.

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
*Yes*

**To Reproduce**
1. Create a menu in Wordpress
2. Add  10-15 child element to a parent menu item
3. Create a Pro menu and assign the menu.
4. Check the mobile menu once you open the drop-down.

**Expected behavior**
Be able to align the menu top and push the drop-down menu down instead of up.

**What actually happens**
It pushes up the items and covers the close icon of the off-canvas menu.

**Desktop (please complete the following information):**
 - Browser [Chromei]
 - Oxygen Version [e.g. 3.3 Alpha]

**Additional context**
Please consider fixing this in the oxygen 3.3 and push down the drop-down instead of up. And allow us to align the parent item in the top instead of the middle. No control over where we position the pro menu items at the moment.

**Comment by alriksson** [comment]
@Spellhammer @KittenCodes

**Comment by Spellhammer** [comment]
You can fix this by adding more top padding to the off-canvas menu under Mobile Menu > Menu Styles

**Comment by alriksson** [comment]
But if I want it to align to the top in general and not in the middle as it doesn't look as I want. Then more padding would just create another issue. The solution would be to push down and not up. Or let the user pick. I don't agree to close this ticket and have a push up to unfold child items in the drop-down.

**Comment by alriksson** [comment]
@Spellhammer It can be solved with some custom CSS to override pro menu. But could consider this to be allowed to adjust directly in the pro menu to align to and push down.

I solved my issue with custom CSS to override pro menus behavior. Still consider to close or open this feature. Adding padding is not going to solve the push menu up or down issue. It needs flexbox adjustments and margin to some selectors.
