### ISSUE TITLE
Pro menu off-canvas not full height

### ISSUE THREAD

**Issue by wpsumo** [soflyy/oxygen-bugs-and-features#988]
**Describe the bug**
pro-menu-off-canvas-container is not covering the top to bottom.

Problem:
```
.oxy-pro-menu-mobile-open-icon {
    display: inline-flex;
}
```

Which cause the gap on off-canvas in the bottom.

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
*Yes*

**To Reproduce**
No need to explain just pick off-canvas and see.

**Expected behavior**
Cover top to bottom

**What actually happens**
A tiny gap in the bottom.

**Desktop (please complete the following information):**
 - Browser [ chrome]
 - Oxygen Version [e.g. 3.3 Alpha]

**Comment by KarzanTT** [comment]
+1

**Comment by KittenCodes** [comment]
@wpsumo I'm not able to replicate this behaviour on a clean Sandbox site running Oxygen v3.3 Alpha 1.

If you're still having this problem, please replicate it on our Sandbox site and send us a link to where we can see the issue. You can create a Sandbox site here: https://oxygenbuilder.com/try/.
