### ISSUE TITLE
Code Wrapper

### ISSUE THREAD

**Issue by sergiubacioiu** [soflyy/oxygen-bugs-and-features#99]
A code wrapper would be very useful.

1: You have a custom field and you want to display page elements only if the field value is populated (if/else statements)
I know you can already do this with a code block but this way you can use the features of oxygen builder to use images, icons and others.
2: You want to wrap an image that you already styled in Oxygen in an a tag to use a lightbox.

I see this implemented with an option to add PHP & HTML Before, PHP & HTML After

**Comment by KittenCodes** [comment]
See: https://github.com/soflyy/oxygen-bugs-and-features/issues/211
