### ISSUE TITLE
Menu Pro error in preview

### ISSUE THREAD

**Issue by guillaumelorain** [soflyy/oxygen-bugs-and-features#994]
Hello, 

I noticed that the Menu Pro is not working in the Oxygen Admin after you change the previewing page.

First the preview is normal
<img width="1037" alt="Screen Shot 2020-04-09 at 9 42 58 am" src="https://user-images.githubusercontent.com/50704323/78849417-0433ed00-7a47-11ea-9838-385639a49bfa.png">

Then, if I change the previwing page the Menu pro is now on responsive mode. 
<img width="1008" alt="Screen Shot 2020-04-09 at 9 43 31 am" src="https://user-images.githubusercontent.com/50704323/78849435-0ac26480-7a47-11ea-850f-9904567f1886.png">

I use Oxygen 3.3 Alpha 1.
The website is on Local Flywheel

Thanks

**Comment by KittenCodes** [comment]
@guillaumelorain I'm not able to replicate this behaviour on a clean Sandbox site running Oxygen v3.3 Alpha 1.

If you're still having this problem, please replicate it on our Sandbox site and send us a link to where we can see the issue. You can create a Sandbox site here: https://oxygenbuilder.com/try/.
