### ISSUE TITLE
Add Support for Native Lazy Loading coming in WP 5.5

### ISSUE THREAD

**Issue by wplit** [soflyy/oxygen-bugs-and-features#995]
**Describe the feature you'd like to see included in Oxygen.**
To be able to use the native lazy loading feature when using the image component. I tested WP5.5 and although the lazy loading is applied automatically with images that are added inside Gutenberg, it isn't for images inside Oxygen using the image component, whether from the library or using the ID

https://core.trac.wordpress.org/ticket/44427

**Comment by KarzanTT** [comment]
+1 Native lazy loding feature in Oxygen

**Comment by joejoerson** [comment]
+1

**Comment by lfalipou** [comment]
of course +1

**Comment by kokohcokisiregar** [comment]
+1

**Comment by Netzlichter** [comment]
upvote

**Comment by alpabuz** [comment]
Yes please

**Comment by YammYcoding** [comment]
please, make all images lazy by default !!

**Comment by adrien-robert** [comment]
+1

**Comment by be1px** [comment]
+1

**Comment by Deralict** [comment]
+1

**Comment by leolemos** [comment]
+1

**Comment by xogabi** [comment]
+1

**Comment by yoshi-12321** [comment]
+1

**Comment by v-marinkov** [comment]
+1... I was stunned this is not implemented in Oxygen. Yet another core functionality missing with a bug report being ignored for nearly 1.5 years.

**Comment by romanseremet** [comment]
+1 for lazy loading

**Comment by kenkistudio** [comment]
+1

**Comment by wavedeck** [comment]
This is also something i am missing from oxygen 3.9 ;(

**Comment by madjedo** [comment]
> +1... I was stunned this is not implemented in Oxygen. Yet another core functionality missing with a bug report being ignored for nearly 1.5 years.

Mmm... Agreed. How can a "WordPress page builder" ignore this?

**Comment by AnInfiniteNumberofMonkeys** [comment]
Oxygen is stuck in 2017.

**Comment by uhlhosting** [comment]
+111111

**Comment by leolemos** [comment]
please, make all images lazy by default !!

**Comment by NicolaModugno** [comment]
+1

**Comment by PearcePunisher** [comment]
+1

**Comment by Spellhammer** [comment]
Image element now has a lazy load option.
